>gnl_CMER_CMG190C_unknown_zinc_finger_protein
AFEYAI----LLIGLL----------------SQIVRYVVFIIDVFVLTEGTWDDKGLWL
------------------------------------------------------------
---------------------------FYNELLSLFL-----------QLAAYLAFFTYV
HLFYSLPLHILRDLAVTARTFRQ----------RLIEF-IRYRQVVRSMHT-QFPN----
--------------------------------------ATEQEL----------------
AAGDRTCIICREEMFGGAGAKKLVCGHIFHLRCLRSWMER-----SMSCPTCRRDIRPLR
APTTSARPTASSGAATHHDDGARRNAPGSLSTRPQRGATAPIEAPATAARRVDTSAVPAS
TQQRMRPSTASADREASDPEHLSRNEWNAHSGRPPWTTARLTEMPPPSSSTSTPAPPPPS
SPPPPPPPPPQLLAVLEYIAQTAPHADVQCSPLPPTSTPAQPTRTHTTPASYARPRSATI
EDARRLQRQLDDLSSVMRNLIERLEHELEDRDAEQIERR
>Selaginella_moellendorffii_91152_PACid_15413277
TFLQAVFGRRYPVGV-----------------IDEEKILPLNREITAVGFLSKHPQG-LP
------------------------------------------------------------
------------------------AIKSSNQM-PFFL-----TEFSREELIVELASATHA
LFWTGIVISSLALGVIGYSAFKN--------WCKWKEW-RRLRQIQEELRR---------
---------------------------EEQVMEED-EEPATTQE-GSE------------
VPDGQLCVVCLLRR---KRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSGYI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVY--
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
TLFQAMFGRRYPVGL-----------------LDEEKILPLGAEITAVGVLHTAPDG-TP
------------------------------------------------------------
------------------------VVKSSKRL-PIFL-----TEFTREQLLVELASSTKV
LFWMGVAVSTVAAGVLGYSLVKN--------WTRWKQR-QQQRQSQNNSEN---------
---------------------------RQNSTIED-----EAEN-FED------------
IPDGELCVVCLLRR---RRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSVTGIV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVY--
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
TLFQTIIGNGYPIAL-----------------LDEEKILPIGKKITAIGLCR-AKNAESV
------------------------------------------------------------
------------------------EITSCPEI-PFFL-----SELTKDEMQAQLASRARI
LFWGSIVLGTLSVCLVGHAIYRG--------WKRIKLR-REARQAQQMFED---------
---------------------------AEDA--IR-EDNSSDDD-DDD------------
VGDGQLCVVCLRKR---RKAAFIPCGHLVCCCKCALRMER---EVEPLCPMCRQDIRYMI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
TLFQTIIGNGYPIAL-----------------LDEEKILPIGKKITAIGLCQ-AKDAESV
------------------------------------------------------------
------------------------EITSCPEI-PFFL-----SELTKDEMQAQLASRARI
LFWGSIVLGTLSVCLVGHAIYRG--------WTRIKLR-REARHARQMFEE---------
---------------------------AEDA--IH-RDDSS--D-DDE------------
IGDGQLCVVCLRKR---RRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDIRYMM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVY--
>Setaria_italica_Si036246m_PACid_19684534
TLFQTIIGNGYPIAL-----------------LDEEKILPIGKELTAIGLCR-ANDEGSV
------------------------------------------------------------
------------------------EISSCPEL-PFFL-----SELTKDEMQAQLASRARI
LFWGSVVLGTLSVCLVGHAIYRG--------WKRIKLR-REARQAQQLFEE---------
---------------------------GEDA--IQ-EDDSS----DEE------------
VGDGQLCVVCLRKR---RKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDIRYMM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
TLFQTIIGNGYPIAL-----------------LDEEKILPVGKEITAIGYIR-PHKA-SV
------------------------------------------------------------
------------------------EISSCSEI-PFFL-----SDLTKDEMEAELSSRAKT
LFWASVVLGTMSVCLLGFATYRS--------WKKIKER-REARQAQEVFRQ---------
---------------------------TTDE--VT-DDQSSDEE-AGE------------
MGDGQLCVICLRKR---RKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDIRYMI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
TLFQTIVGNGYPIAL-----------------LDEEKILPIGKEITAIGLCR-VNNQ-NV
------------------------------------------------------------
------------------------EITSCPEI-PFFL-----SDLTKGEIEAELDSRART
LFWVTFALGTMSVGLLGHAIYRF--------WEKVKQH-REARQAQQRFHQ---------
---------------------------ADDEDDTG-ENGSDDDF-PGE------------
MGDGQLCVICLRKR---RKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDIQYML
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVY--
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
TFIQALFGHEYPVGV-----------------LHEEKILPLGKCISAVGICN-SKDG-IP
------------------------------------------------------------
------------------------EIKSCKEL-PYFL-----ADMTKDEMVADLAFKAKI
LLWSGIVLGSLSIGVLGFAVMRN--------WNKWKAW-RQRRS-QQPIHT---------
---------------------------TSDE--DV-SQIDDNED-AGD------------
VPEGQLCVICLMRR---RRAAFIPCGHLACCHTCAVSVES---EVSPKCPLCRQAVRNSI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIF--
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
TFLQALFGHDYPVGL-----------------LDEEKLLPLGKEITAVGICS-LKNG-IP
------------------------------------------------------------
------------------------EIKSCKDL-PYFL-----SEMSKDQMVVDLVFKSKV
LFWSGVILGSVSIGVLGYAVVRN--------WNRWKEW-RQQRGVRPPSQA---------
---------------------------VTDD--TD-TQI-AEDD-AGD------------
VPDGELCVICLMRR---KRSAFVPCGHLVCCQRCALSVER---ELSPKCPVCRQIIRSSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Ricinus_communis_29706.m001280_PACid_16806294
TFLQAFFGYEYPVGL-----------------LDEEKILPLGKEINAVGLCG-SKNG-IL
------------------------------------------------------------
------------------------EITSCKDL-PFFL-----SDLSKEQMVVDLAFKTKV
LFWSGVVLGSFSICILGYAAVRN--------WNRWKAW-RQQRQFQQQSNS---------
---------------------------VSDA--DV-SQIDVEEE-TVD------------
VPDGQLCVICLMRR---RRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAVRNSI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIF-E
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
TFLQALFGHEYPVGL-----------------LDEEKILPLGKEINAVGICS-SRNG-VL
------------------------------------------------------------
------------------------EIKSCKDL-PYFL-----SDMTKDQMVVDLAFKTKV
LLWSGVVLGSLSIGILGYAAVRN--------WNRWKEW-RQHRQSQQQNHA---------
---------------------------ASTD--DD-PQIDADEE-AGD------------
VPDGQLCVICLMRR---RRSAFIPCGHLVCCQLCAISVER---EVSPKCPLCRQAVRNSM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIF--
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
TFLQALFGHEYPVGL-----------------LDEEKILPIGKDVSAVGLCF-LKNG-IL
------------------------------------------------------------
------------------------EIKSCKDL-PYFL-----TEMTKDQMVIDLAFRTKI
LFWSSIFLGSASIGILGFAFVRN--------WNRWKEW-RQRRRDEQQSHA---------
---------------------------AVDE--AT-AHI-AEDE-LGD------------
APDGQLCVICLMRR---RRSAFVPCGHLVCCQRCALSVER---EVSPKCPVCRQTITNSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
TFLQALFGHEYPVGL-----------------LDEEKILPLGKDVSAVGLCS-LRNG-IA
------------------------------------------------------------
------------------------EIKACNDL-PYYL-----SDLSKDQMIVDLSFKTKL
LFWSGILLGSMSVGIIGYAVVRN--------WNKWKQW-KQQRQLQQRRQQ---------
---------------------------PIE------PVPPTDDE-IED------------
VPDGQLCVICLMRR---RRSVFIPCGHLVCCQGCAISVES---EVAPKCPVCRQEVRDSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIF-E
>Glycine_max_Glyma18g27930.1_PACid_16309372
TFLQALFGHEYPVGL-----------------LDEEKILPLGKDITAVGLCS-LKNG-IA
------------------------------------------------------------
------------------------EIKSCKYL-PYFR-----SDLSKDQMIMDLSIKTKI
LFWGGIALGSMSVGVLGYAVVRN--------WNKWKQW-KQQRQLQQQRQA---------
---------------------------VSD------VEPQMDDE-IED------------
APDGQLCVICLMRR---RRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEIRDSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
TFLQALFGHEYPVGL-----------------LNEEKILPLGKDISAVGICS-FKNG-IP
------------------------------------------------------------
------------------------EIMSCKDL-PYFL-----SDLTKDQMLLDLAFRTKI
LFWSGIILGSLSISILGYAALRN--------WNRWKER-RQQRQAHQPSHA---------
---------------------------ASID--AN-SELTGEEE-IGD------------
IPDGQLCVICLMRR---RVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEIRGSM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVF--
>Prunus_persica_ppa006914m_PACid_17656817
TFLEALFGHRYPVGL-----------------LDEEKILPLGKEISAVGLCS-VKDG-VL
------------------------------------------------------------
------------------------EIKSCKDF-PYFL-----SEMSKDQMVVDLTSRTKV
LFWSGIFLGSVSIGVLAYAVSRN--------WNRWKVW-RQQRELQRSIRA---------
---------------------------SNAE--AQIQEEEEEED-AGD------------
VPDGQLCVICLMRR---RRSAFIPCGHLVCCQLCSISIER---DVAPKCPVCRQQIRTSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Citrus_clementina_0.9_012450m_PACid_19274708
TFLQAMFGLKCPIGV-----------------LAEEKILPLGKDISAVGICS-FKNG-IP
------------------------------------------------------------
------------------------EIKSCKDL-PYFL-----SEKTKDLMVVDLVNRSKI
LFWSGIVLGSLSIGILGYAIVRN--------WNRWKD--RQQRMSRQLTEA---------
---------------------------PSDD--AD-SQIGSDEDVAGD------------
IPDGQLCVVCLTRR---RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRSSM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
TFLQAMFGLKCPIGV-----------------LAEEKILPLGKDISAVGICN-FKNG-IP
------------------------------------------------------------
------------------------EIKSCKDL-PYFL-----SEKTKDQMVVDLVNRSKI
LFWSGIVLGSLSIGILGYAIVRN--------WNRWKD--RQQRMSRQLTET---------
---------------------------PSDD--AD-SQIGSDEEVAGD------------
IPDGQLCVVCLTRR---RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRSSM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
TVFQALVGLEYPVGL-----------------LYEEKILPLGKDITAVGICN-LKNG-IP
------------------------------------------------------------
------------------------EIKSCEDL-PYFL-----SILTKDQMIADLSFKSKV
LLWSGLILGTVAIGVLGYSISRN--------WSKWKEW-KARRAQQQQNAS---------
---------------------------RIEN-----LDETEEEE-SGD------------
VPDGELCVVCLMRR---RRSAFVPCGHLVCCHRCAFSVER---EVSPKCPVCRQPIRNSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Aquilegia_coerulea_v1.024769m_PACid_18143411
TLIQAIVGHAYPVGL-----------------LDEEKILPLGKEITAVGHCT-LQDG-NP
------------------------------------------------------------
------------------------QIISCKKV-PYFL-----SDMTKDQMIVDLVSKKKI
LFWAGIVLGSVSLGVLGYALTRN--------WQRLKEW-RQRRQIQQSREE---------
---------------------------EIANLDATPEDTRADEE-TED------------
IPEGQLCVICLMRR---KRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDIRTSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
TFLQAVFGHEYPVGV-----------------LDEEKILPLGKNISAVGICS-FENG-VP
------------------------------------------------------------
------------------------VIKSCSDF-PHFL-----CEMTKDQMILDLVFKTKF
LFWSSIVLGSLTVGILGYSAARN--------WNRWKQW-RQHRQLQNSRNDSPTSQLDSS
NDIPIYGDFASDDEAATVPDDELSSHVPDDE--LS-SHVPDDEL-SSH------------
VPDGQLCVICLMRR---KRSAFIPCGHLVCCERCAVSVER---ESSPKCPICRQQIRSSV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RIY--
>Tomato_Solyc12g049330.1.1
TFIQALFGHHYPVGV-----------------LDEEKILPLGKDITAIGVCS-SKDG-IL
------------------------------------------------------------
------------------------EIKSCEDL-PYFL-----SDMTKDQMLVELAFKTKI
LMWSGVLFGSVAVGVLGYAVVRN--------WNRWKLW-RHQRQAQQQRDA---------
---------------------------ASND--DD-VQVSADEE-SGD------------
VPDGQLCVICLTRR---KRAAFVPCGHLVCCQRC--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>SPL2_NP_564653
SFLQAFLYPDYPVGL-----------------LDIEKILPPGKDITAVGIYS-FNNG-VP
------------------------------------------------------------
------------------------EIKSCQDL-PYFL-----SEMTKDKMIEDLMEQTNF
IFLGSVILGIVSVGILSYAAVRT--------WNKWKQW-NHQRELPQRPND---------
---------------------------SVVD--------DEPED-ADE------------
IPDGELCVICVSRR---RVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRGSM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVYYS
>Arabidopsis_lyrata_474546_PACid_16040628
SFLQAFLFPDYPVGL-----------------LDIEKILPPGKDITAVGICS-FNNG-VP
------------------------------------------------------------
------------------------EIKSCQDL-PYFL-----SEMTKDKMIEELMDQTSF
IFFGSVILGIVSVGILSYAAVRT--------WNKWKQW-NHQRDLPQRPNE---------
---------------------------PVVD--------DEPED-ADE------------
IPDGELCVICVTRR---RVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSIRGSM
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVY--
>Aquilegia_coerulea_v1.022773m_PACid_18144013
AFLEAFF---LPVGH-----------------M-QKKILPLGKEINAIGLCS-LQDG-NL
------------------------------------------------------------
------------------------HIKATQEL-PYFL-----SEMTKGEMVKHLAYKTTI
LFWGGCIIGIVSLGVLGYTSFRI--------WEWWKVR-RQHFSNAEVDDV---------
-----------------------------------------YIG-NDE------------
IPSEQLCTICTMRR---KKYACVPCGHLVCCHKCARSIQH---DSTARCPECRH------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------LGHAYPFGLCLQEKFLPLNFAWYHPGLLEEKILPLGKEISVVGIGT-SEYG-NV
------------------------------------------------------------
------------------------EIKPCDEL-PYFL-----SDLTKDQMIGELAQKTNY
LLLSAIFFGSLSLAVIAYAVMIG--------CQRFEEKTQQRRQVQQQMTQ---------
---------------------------VQQSL----RNDVVEEG-MEA------------
LPEGLSCVV----------SVFVPCGHLVCCQTCAPLVAR-----DRRCPICRQYIQKYI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------ITY--
>Physcomitrella_patens_Pp1s12_190V6.2_PACid_18048531
DYLQGL----KMLGV-----------------KRVERVLPTGTNLTVVGEAVQDDRG-LI
------------------------------------------------------------
------------------------RIQKPNKG-PFYV-----TPKSLDQLVANLGRWSRW
YKYMSLGFTIVGIYFITSHAIKHF-------MERRRRE-ALHRRVM-EAAA-LRQASQRE
GGDGD----------------------MGDVTSHPLDDSVDTSQ-KKD------------
RGTPDLCVICLEQD---YNAVFLPCGHMCCCTSCSAQLTS--------CPLCRRHIDKFV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTYRH
>Physcomitrella_patens_Pp1s175_124V6.2_PACid_18055474
DYLQGL----KMLGV-----------------KRVERVLPTGTNLTVVGEAVQDDRG-LI
------------------------------------------------------------
------------------------RIQKPDKG-PFYV-----TPQSQDQLIENLGRWSRW
CQYMSFGLTLVGIYFITSRAIKHM-------LERWRRE-ALLTRVM-EAAA-LRKALQQE
GVDEE----------------------SDGVTAFPHDDNAHTAQ-KKD------------
GGMPSLCVICLEQD---YNAVLVPCGHMCCCTSCSSQLSL--------CPLCRRHIDQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Selaginella_moellendorffii_231449_PACid_15416766
DYLQGL----KMLGV-----------------KRVERVLPTGTALTVVGEAIKDDQG-TL
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----TPKSIDQLIANLGKWSRW
YKYMSLGFTLFGVFLVASHTIRYV-------MEKRRRA-ALNRRVM-EAAA-RRRERKEH
EGKAQ----------------------VGEF------AKVETAT-KRD------------
GRLPDLCVICLEQE---YNAVFVPCGHMCCCISCSAQLQN--------CPLCRRRIEQIV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTYRH
>Medicago_truncatula_Medtr1g111550.1_PACid_17439105
DYVQGL----KMLGV-----------------KRIERVLPVGTSLTVVGEAAKDDVG-TI
------------------------------------------------------------
------------------------RIQRPSKG-PFYV-----SPKTIDELIANIGRWARW
YKYASAGLTVLSVYMIANHAVRYI-------LERRRRN-ELEKRVL-AAAA-KISGQDNG
GE--M----------------------D---------DSLSDGA-KRE------------
RAMPNLCVICLEQE---YNSVFVPCGHMCCCTACSSHLTS--------CPLCRRQIEKAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Glycine_max_Glyma10g02920.1_PACid_16278382
DYLQGL----KMLGV-----------------KRIERVLPVGTSLTVVGEAAKDDVG-AI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDQLIANLGKWARW
YKYASVGLTVFGAYLIAKHAIRYI-------LERRRRS-ELQRRVL-AAAA-KKSGQNND
VE--K----------------------A---------DSLSDGA-KKD------------
RLMPDLCVICLEQE---YNAVFVPCGHMCCCTACSSHLTN--------CPLCRRQIEKVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Prunus_persica_ppa008230m_PACid_17644506
DYLQGL----KMLGV-----------------KRIERVLPTGTSLSVVGEAVKDDIG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDQLIANLGKWARW
YKYASLGLTVFGVYLVAKHSVQYI-------LERRRRW-ELQRRVL-AAAA-KRSGEDNE
GSNEK----------------------D---------DNVLDGS-K--------------
RLMPDLCVICLEHE---YNAVFVPCGHMCCCTTCSLHLTN--------CPLCRRRIDQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
DYLQGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAAKDDIG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDQLISNLGKWARW
YKYASMGLSIFGLYLVTKHVILYL-------MERRRRW-ELQKRVL-AAAA-KRSSQENE
GEIEK----------------------A---------SNGTDGT-KRD------------
RSMPDLCVICLERD---YNAVFVPCGHMCCCVACCSHLTN--------CPLCRRRIELVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
DYLQGL----KMLGV-----------------KRIERLLPTGTSLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDELIENLGKWARW
YKYASFGLTIFGTFLIAKRAIHYI-------LQRKRRW-ELHRRVL-AAAAVKRSEQDNE
GTNGQ----------------------A---------ENGSDGT-QRD------------
RVMPDLCVICLEQE---YNAVFVPCGHMCCCIICSWHLTN--------CPLCRRRIDQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Citrus_clementina_0.9_003846m_PACid_19263951
DYLQGL----KMLGV-----------------KRIERLLPTGTSLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDELIENLGKWARW
YKYASFGLTIFGTFLIAKRAIHYI-------LQRKRRW-ELHRRVL-AAAAVKRSEQDNE
GTNGQ----------------------A---------ENGSDGT-QRD------------
RVMPDLCVICLEQE---YNAVFVPCGHMCCCIICSSHLTN--------CPLCRRRIDQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
DYLQGL----KMLGV-----------------KRIGRLLPTGTSLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDELLENLGKWARW
YKYASFGLTIFGAFLIAKRVIRCI-------LQRKRRW-ELRRRVL-AAAAVQRSEQDNE
GTNGQ----------------------A---------ENGSDST-QRD------------
RVMPDLCVICLEQE----------CGHLCCCLICSSRLTN--------CPLCRRRIDQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Citrus_clementina_0.9_014777m_PACid_19265048
DYLQGL----KMLGV-----------------KRIGRLLPTGTSLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDELLENLGKWARW
YKYASFGLTIFGAFLIAKRVIRCI-------LQRKRRW-ELRRRVL-AAAAVQRSEQDNE
GTNGQ----------------------A---------ENGSDST-QRD------------
RVMPDLCVICLEQE---YNAVFFPCGHLCCCLICSSRLTN--------CPLCRRRIDQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
DYLQGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RVQRPHKG-PFYV-----SPRTIDELIGNLGKWARW
YRYASVSLTVFGAFLIAKHAIQYI-------MERRRRW-ELQSRVLAAAAA-KRQGQDSE
GSNGK----------------------A---------ENGSDNS-KRE------------
RPVPDLCVICLEQE---YNAVFLPCGHMCCCTTCSSHLTN--------CPLCRRRIEQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Ricinus_communis_29703.m001546_PACid_16806242
DYLQGL----KMLGV-----------------KRIERVLPTGTSLSVIGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDELIGNLGKWARW
YRYASVGLTVFGVFLIAKHAIQYI-------MERRRRW-ELQSRVL-AAAA-KRQGQDSD
GSNGK----------------------A---------ENGSDSS-KRE------------
RPIPDLCVICLEQE---YNAVFLPCGHMCCCTACSSHLTN--------CPLCRRRIEQI-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Vitis_vinifera_GSVIVT01011070001_PACid_17823049
DYLQGL----KMLGV-----------------KRIERVLPTGTPLTVVGEAIKDDVG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKSIDHLVANLGKWARW
YRYASLGFTVFGVYLIAKSAIQYV-------MERKRCW-ELRKRVL-AAAS-KKSGQDSE
DPDEK----------------------D---------ENGSDNT-KRD------------
RLMPDLCVICLEQE---YNAVFVPCGHMCCCTMCSSQLTN--------CPLCRRRIEQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
DYLQGL----KMLGV-----------------KRIERLLPVGSSLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKTIDQLISNLGKWARW
YRYASYGFTVFGICLIAKRAIQYI-------MERKRRW-ELQRRVL-AAVA-RRSEQDTE
GTDDK----------------------T---------KNAPDSA-KRD------------
RSMPDLCVICLEQE---YNSVFVPCGHMCSCTTCSLQLTN--------CPLCRRRIEQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Tomato_Solyc06g084360.1.1
DYLQGL----KMLGV-----------------KRIERVLPVGTPLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYI-----SHKTIDQLIANLGRWARW
YKYASMGFTAVGVYLLVKHTFHYM-------MERKRHW-ELRRRVL-AAAA-KRAGDEDE
GSDAT----------------------A---------ENGVD---NKD------------
LLMPDLCVICLEQE---YNSVFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
DYLQGL----KMLGV-----------------KRIERVLPTGSPLTVVGEAVKDDIG-SI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----TDKTIDQLIANLGKWSRL
YKYASMGLTAFGVYLLAKHAFQYI-------MDRRRLW-ETRKRVL-DAAA-KKAGQNEG
ALNGE----------------------A---------EIGSDSS-NKE------------
RPIPELCVICLEQE---YNSVFVQCGHMCCCMACSSHLTN--------CPL---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
DYLQGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAVKDDVG-TI
------------------------------------------------------------
------------------------WIQRPHKG-PFYV-----SPKSIDQLIANLGIWARL
YKYASLGFTAFGVYLIAKHAIRYI-------LERRRLL-DFQRRVR-AAAA-QRLEQDND
GTDGK----------------------A---------EDGPDVV-NKD------------
RIMPDICVICLEQE---YNAVFVPCGHLCCCTTCSSHLSN--------CPLCRRRIDQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Arabidopsis_lyrata_474968_PACid_16053684
DYLQGL----KMLGV-----------------KRIERVLPTGIPLTIVGEAVKDDIG-EF
------------------------------------------------------------
------------------------RIQKPDRG-PFYV-----SPKSLDQLISNLGKWSRW
YKYASMGFTVFGVFLITKHVIDSV-------LERRRRR-QLQKRVL-DAAA-KRAELESE
GSNGA----------------------R---------ESIADST-KKE------------
DAVPDLCVICLEQE---YNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDLAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTYRH
>SP1
DYLQGL----KMLGV-----------------KRIERVLPTGIPLTIVGEAVKDDIG-EF
------------------------------------------------------------
------------------------RIQKPDRG-PFYV-----SSKSLDQLISNLGKWSRL
YKYASMGFTVLGVFLITKHVIDSV-------LERRRRR-QLQKRVL-DAAA-KRAELESE
GSNGT----------------------R---------ESISDST-KKE------------
DAVPDLCVICLEQE---YNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDLAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTYRH
>Populus_trichocarpa_POPTR_0014s13410.1_PACid_18222628
DYLQGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAVKDDIG-TV
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKSIDELIGNLGKWARW
YKYASLGLTVFGAFLITKHVIRYI-------MERRRRW-ELQSRYV-SLVE-GIHDKMFQ
G------------------------------------KGHANGA-KRE------------
RPIPDLCVICLEQE---YNAVFLPCGHMCCCITCCSQLSN--------CPLCRRRIEQVV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KTFRH
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
DYLQGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYA-----SSKSIDQLIVNLGKWAKL
YRIASMGFATFGVFLLAKRALQHF-------LERRRRH-ELQKRVL-NAAA-QRQAREAE
GSKGT----------------------S----------DAEPNS-KKD------------
QLVLDICVICLEQE---YNAVFVPCGHMCCCVACSSHLTN--------CPLCRRRIDQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
DYLQGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAIRDDVG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKSIDQLIMNLGKWAKL
YRLASMGFATFGVFLLAKRAIQHF-------LERKRRH-ELQKRVL-NAAA-QRQAREAE
GSNGS----------------------S----------DTEPNS-KKD------------
QLVLDICVICLEQE---YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
DYLQGL----KMLGV-----------------KRTERVLPTGISLTVVGEAIKDDVG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKSIDQLIMNLGKWAKL
YRLASMGFATFGAFLLAKRAIQHF-------LERKRRH-ELQKRVL-NAAA-QRQAREAE
GSIGS----------------------S----------DTEPNS-KKD------------
QLVLDICVICLEQE---YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Setaria_italica_Si030396m_PACid_19714000
DYLQGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKSIDQLILNLGKWAKL
YRLASMGFATFSVFLLAKRAIQHF-------LERKRRH-ELQKRVL-NAAA-QRQAREAE
GGKGT----------------------S----------NTEPNS-KKD------------
QLVLDICVICLEQE---YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
DYLQGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYV-----SPKSIDQLIMNLGKWAKL
YQLASMGFAAFGVFLLAKRALQHF-------LERKRRH-ELQKRVH-AAAA-QRQAREAE
GGNGT----------------------S----------DVDSNN-KKD------------
QLVLDICVICLEQE---YNAVFVPCGHMCCCMNCSSHLTN--------CPLCRRRIDQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
DYLQGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI
------------------------------------------------------------
------------------------RIQRPHKG-PFYA-----SPKSIDQLILNLGKWAKL
YQLASMGFAAFGVFLLAKRALQHF-------LQKKRQH-ELNKRVR-AAAA-QRQAREAE
GADGT----------------------S----------NGDPNS-KKD------------
QLVLEICVICLEQE---YNAVFVPCGHMCCCMNCSSHVTN--------CPLCRRRIDQAV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
DYLQGL----KMLGV-----------------KRIERVLPTGTSLTVVGEMTLEQ----F
------------------------------------------------------------
------------------------RYEDRTNG-LFTCLQINGSPD------FQLGKWARW
YKYASMGLTFLGVFLIAKRSIEYV-------LERRRRR-ELQKRVL-AAAA-KRSGQDNE
GSNII----------------------P---------ENGLDGA-KRE------------
HLMPDLCVICLEQE---YNAAFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQVL
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTFRH
>SPL1_NP_564745
GYLKGF----KILGV-----------------RHVERVVPIGTPLTVVGEAVRDGMG-NV
------------------------------------------------------------
------------------------RIQKPEQG-PFYV-----TYIPLDQLISKLGDLSRR
FKYASMGLTVLGVILISKPVIEYILKRIEDTLERRRRQ-FALKRVV-DAAA-RRAKPVTG
G-----------------------------------------GT-SRD------------
GDTPDLCVVCLDQK---YNTAFVECGHMCCCTPCSLQLRT--------CPLCRERIQQVL
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KIYRH
>Arabidopsis_lyrata_338432_PACid_16045815
DYLKGL----KILGV-----------------RRVEHVVPIGTPLTIVGEAVKDGMG-NV
------------------------------------------------------------
------------------------RIQKPEQG-PFYV-----SYVPLDQLISKLGEWSRR
FKYASMGLTVVGVILLSKPVIKYILKKIEDTLERRRRQ-LLQKRVV--------------
------------------------------------------------------------
-DVPDLCVICHDQK---YNTAFVQCGHMCCCLTCSLRLTT--------CPLCREQIQQVL
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KIYRH
>Arabidopsis_lyrata_867782_PACid_16034683
-----------MLGV-----------------RRTEHVLPIGTPVTVVGEAVKDGIR-GF
------------------------------------------------------------
------------------------RIQKPEKG-LFFV-----SPVPLDKIISPMGKWLRR
FKYVYVGLTVVGVILISKPVIEYI-------LERRRGR-LLRKRVA-DAAA-KRAKLVAR
GLETQ----------------------H---------ENSLDST-SRD------------
RDVLDLCVICLEQK---YDATFVKCGHMCCCLTCSLHVKT--------CPICRRPIEHVL
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KIDR-
>Chlorella_variabilis_gi_307103723_gb_EFN51981.1
DEVQGS----RSVGV-----------------RQVERMLPVGTMLTAVGELATAGGK-ML
------------------------------------------------------------
------------------------VLRAPRDG-AFYL-----SRQPLPDVIASLQASSLA
CQQWAAAFTAVGASMLVAAATQHA-------LTWVRQR-RLRQRVE-KAMR-ERAAAAAA
AGGGG----------------------A---------AGAPAAS-AAEPQPADVAEAAEG
GARPSLCVVCLERP---CATVFPACGHMCACSRCSHGLRR--------CPICRSR-GAPI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVYTA
>Mulan_NP_078820
HYISGE----RPKGI-----------------QETEEMLKVGATLTGVGELVLDNN--SV
------------------------------------------------------------
------------------------RLQPPKQGMQYYL-----SSQDFDSLLQRQESSVRL
WKVLALVFGFATCATLFFILRKQ--------YLQRQER-LRLKQMQEEFQE-HEAQ----
-------------------------------------LLSRAKP-EDR------------
ESLKSACVVCLSSF---KSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITRVI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PLYNS
>Mus_musculus_gi_18043560_gb_AAH19516.1
HYISGE----RPKGI-----------------QETEEMLKVGATLTGIGELVLDNN--AV
------------------------------------------------------------
------------------------RLQPPKQGMQYYL-----SSQDFDSLLHRQESSVRL
WKVLVLVFGFATCATLFFILRKQ--------YLHRQER-LRQQQLQEEFLE-HEAQ----
-------------------------------------LLSQASP-EDR------------
ESLKSACVVCLSNF---KSCVFLECGHVCSCRQCYLALPE-----PKRCPICRREITRVI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PLYNS
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
HYMTGE----RPKGV-----------------QETEEMLKIGATITGVGELVLDNK--TI
------------------------------------------------------------
------------------------KLQPPKDGMLFYL-----SSMDYEGLLEKQEVQMRW
WRILSIVFGVASCITLFFILRRK--------YRHYKEK-QHLKNLQREFEE-SRAR----
-------------------------------------QRVQQEP-QNK------------
EEVQNPCSICLSTE---KSCVFLECGHVCSCISCYQALPS-----PKKCPICRNFIDRIV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PLYNS
>Danio_rerio_gi_148922854_ref_NP_001092230.1
HFISGE----RPQGI-----------------QETEEMLRLGASMTGVGELVLDNN--LV
------------------------------------------------------------
------------------------RLQPPKKGLRYFL-----SRLDYDTLLSKQEGHLRI
WRVLTVLLGLTACATFFYLLWRQ--------YVLRKER-RKEQSVLDEYRK-WQSK----
-------------------------------------RFQELHL-AKE------------
DVSPTACTICLNHE---RSCVFLECGHVCACEGCYRALPE-----PKKCPICRATIDRIV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------SLYNS
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
GFFSGV----RQRGL-----------------QTTEEVLREGSFLTAIGELELDGD--TL
------------------------------------------------------------
------------------------RMQPSNEG-PLFL-----TTATKSTLIKRFEDAKTT
TILKLVVCSTISAILVAFIAKKL--------YRKRKQE-REEAKIRERLDT-ERRERRAR
SRPHT-------------------------------------------------------
LSQDQLCVVCSTNP---KEIILLPCGHVCLCEDCAQKISV-------TCPVCRGSIVSKA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------AAFIA
>Volvox_carteri_96908_PACid_17997093
KALKSM----VKHGV-----------------RVTERYLPVDTAVTVVGELVADCMGSTA
AAAAGCRTRPAAGGSGNPLLASSSQQQPSDVSGSGVEAAAAADVARTATGGGGGTGSLSA
AATAVAAAAGAELLGQAALQALPYTLRMPGRG-PFHV-----TTLTLPQLRASLERTSGV
IRAFAWGFGLLGAALFVRKAAQA--------YHRLQAY-RRYKRYAALAEA-ARRTAAAG
GGAAA----------------------GMGTSAATGATAGDDDG-DGV------------
--------------------------------RSPGTVTS-----------------RTI
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVFRP
>rsz31o21_6
SXCWSLFLXANVLG-------------------------PLHSLLHGEGXSRTAQRALSS
------------------------------------------------------------
------------------------SMSSRWSRCPQYL------------------PHSRP
VWASGTARIATAVSCPVDIASRFFSN-----RTRPNSP-SIDTRLF-CCSA-LRAP----
--------------------------------------KISPRA-AAE------------
AEHDDLCIICMTDP---RDTTVLPCGHLCLCVDAQLLRVR-----SDRCPICRSPVDSLL
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------XI-RX
