>gnl_CMER_CMG190C_unknown_zinc_finger_protein
MRSTAKYAAISYCAIGLILGHAWLTQPNFYRATAYLYNSKTARFSAVNAGLVSLYLVGQL
VQRLLLGELRLVEAERL----HLRARESLVEMFLAMTVFSRTDFHARFLCMFAWTFFLKV
FHWLSQERLG------------------YVEQQVIMLSRPRLTHARLV-----------V
LFCWLFVTDACMLWHCLHFTSTNG-------------PSIMAMF------AFEYAI----
LLIGLL----------------SQIVRYVVFIIDVFVLTEGTWDDKGLWL----------
------------------------------------------------------------
-----------------FYNELLSLFL-----------QLAAYLAFFTYVHLFYSLPLHI
LRDLAVTARTFRQ----------RLIEF-IRYRQVVRSMHT-QFPN--------------
----------------------------ATEQEL----------------AAGDRTCIIC
REEMFGGAGAKKLVCGHIFHLRCLRSWMER-----SMSCPTCRRDIRPLRAPTTSARPTA
SSGAATHHDDGARRNAPGSLSTRPQRGATAPIEAPATAARRVDTSAVPASTQQRMRPSTA
SADREASDPEHLSRNEWNAHSGRPPWTTARLTEMPPPSSSTSTPAPPPPSSPPPPPPPPP
QLLAVLEYIAQTAPHADVQCSPLPPTSTPAQPTRTHTTPASYARPRSATIEDARRLQRQL
DDLSSVMRNLIERLEHELEDRDAEQIERR
>Selaginella_moellendorffii_91152_PACid_15413277
----------------------GIVLGLGMAALALRTWLKFGSHTRALKQVEGTAQVEIH
DLRSLVESGEKEPSSD---------SSPPLVIVRGRVALPPKTSSEEVLLARNQTDLAVF
VERTQTYLFNEWRGLFRWGPEWRGLLG-WGSLKEQVAFSRRKIPFVLLDSDPQ------Y
DGACVHINMENVE-HPLPLVTVFHQLHPVQTS-----SS-----------TFLQAVFGRR
YPVGV-----------------IDEEKILPLNREITAVGFLSKHPQG-LP----------
------------------------------------------------------------
--------------AIKSSNQM-PFFL-----TEFSREELIVELASATHALFWTGIVISS
LALGVIGYSAFKN--------WCKWKEW-RRLRQIQEELRR-------------------
-----------------EEQVMEED-EEPATTQE-GSE------------VPDGQLCVVC
LLRR---KRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSGYI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVY--
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
---------------------------------------------------------AVF
VERTQTYVLTEMSNFLG-----------WITQKDLVKFTRQVVPFVLAETEAHWSFRPSD
MAVYVHINLDESQ-HPIPLVTVHHQLHPVPAS-----SY-----------TLFQAMFGRR
YPVGL-----------------LDEEKILPLGAEITAVGVLHTAPDG-TP----------
------------------------------------------------------------
--------------VVKSSKRL-PIFL-----TEFTREQLLVELASSTKVLFWMGVAVST
VAAGVLGYSLVKN--------WTRWKQR-QQQRQSQNNSEN-------------------
-----------------RQNSTIED-----EAEN-FED------------IPDGELCVVC
LLRR---RRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSVTGIV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVY--
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
--------------------------------PRIAAVRGYVRTQGSFLRAPFSSEAGVV
VKHTQMCLFTEWRGIFGWTFDLHALL--FRSWKEQIVTSFRAVPFVLASTELG------N
STGVVHINVDEVDYQPLPLTTVFHKLIPLETT-----PY-----------TLFQTIIGNG
YPIAL-----------------LDEEKILPIGKKITAIGLCR-AKNAESV----------
------------------------------------------------------------
--------------EITSCPEI-PFFL-----SELTKDEMQAQLASRARILFWGSIVLGT
LSVCLVGHAIYRG--------WKRIKLR-REARQAQQMFED-------------------
-----------------AEDA--IR-EDNSSDDD-DDD------------VGDGQLCVVC
LRKR---RKAAFIPCGHLVCCCKCALRMER---EVEPLCPMCRQDIRYMI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
------------------------------------------------------------
--------------------------------PRIAAVRGYVRAHDKFFRAPFSGEAGVV
TKHTQMCLFTEWRGIFGWTFDLHALL--FRSWKEQIVTSFRSVPFVLVSTELG------N
PTGVVHINVDKAD-QPLPLTTVFHKLIPLETT-----PY-----------TLFQTIIGNG
YPIAL-----------------LDEEKILPIGKKITAIGLCQ-AKDAESV----------
------------------------------------------------------------
--------------EITSCPEI-PFFL-----SELTKDEMQAQLASRARILFWGSIVLGT
LSVCLVGHAIYRG--------WTRIKLR-REARHARQMFEE-------------------
-----------------AEDA--IH-RDDSS--D-DDE------------IGDGQLCVVC
LRKR---RRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDIRYMM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVY--
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
---------------------------------------------------PWSGEHGVV
TKHTQMCLFTEWRGIFGWTFDLHALL--FRSWKEQIVTYFRSVPFVLASSEIG------N
PIGMVYIDVEKAA-QPLPLTTVFHKLIPIETT-----PY-----------TLFQTIIGNG
YPIAL-----------------LDEEKILPIGKELTAIGLCR-ANDEGSV----------
------------------------------------------------------------
--------------EISSCPEL-PFFL-----SELTKDEMQAQLASRARILFWGSVVLGT
LSVCLVGHAIYRG--------WKRIKLR-REARQAQQLFEE-------------------
-----------------GEDA--IQ-EDDSS----DEE------------VGDGQLCVVC
LRKR---RKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDIRYMM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
----QLCLFNEWRGIFGWTFDLHALF--FKSIKEQIITSFRWVPFVLVDPE--------N
MTGMVHVKLDRAM-QPLPLTTVYHKLTPVDST-----PY-----------TLFQTIIGNG
YPIAL-----------------LDEEKILPVGKEITAIGYIR-PHKA-SV----------
------------------------------------------------------------
--------------EISSCSEI-PFFL-----SDLTKDEMEAELSSRAKTLFWASVVLGT
MSVCLLGFATYRS--------WKKIKER-REARQAQEVFRQ-------------------
-----------------TTDE--VT-DDQSSDEE-AGE------------MGDGQLCVIC
LRKR---RKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDIRYMI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
-----------------------ALF--FKSLKEQTITSFRWVPFALVDPASASD----K
STEMIHVKLDGAVQQSLPLTTVYHKLIPVEQN-----SY-----------TLFQTIVGNG
YPIAL-----------------LDEEKILPIGKEITAIGLCR-VNNQ-NV----------
------------------------------------------------------------
--------------EITSCPEI-PFFL-----SDLTKGEIEAELDSRARTLFWVTFALGT
MSVGLLGHAIYRF--------WEKVKQH-REARQAQQRFHQ-------------------
-----------------ADDEDDTG-ENGSDDDF-PGE------------MGDGQLCVIC
LRKR---RKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDIQYML----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVY--
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
---------------------------------------------------------AVI
LQRTQTCIYNEWKGFFGWTSDLRSIF--GRSLKEQETTFLRTVPFTLVEGGQW------P
QSDYVIVNMDGSS-HPLPLTMVYHQLQPIVAS-----RY-----------TFIQALFGHE
YPVGV-----------------LHEEKILPLGKCISAVGICN-SKDG-IP----------
------------------------------------------------------------
--------------EIKSCKEL-PYFL-----ADMTKDEMVADLAFKAKILLWSGIVLGS
LSIGVLGFAVMRN--------WNKWKAW-RQRRS-QQPIHT-------------------
-----------------TSDE--DV-SQIDDNED-AGD------------VPEGQLCVIC
LMRR---RRAAFIPCGHLACCHTCAVSVES---EVSPKCPLCRQAVRNSI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIF--
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
---------------------------------------------------------GVI
LQRTQTCIYNEWRGFFGWTSDIRTLF--ARSWKEKESTSLRTVPFILVEGGRW------P
QSDYVIVNMDGSR-HPLPLTTVYHQLQPVNAS-----PY-----------TFLQALFGHD
YPVGL-----------------LDEEKLLPLGKEITAVGICS-LKNG-IP----------
------------------------------------------------------------
--------------EIKSCKDL-PYFL-----SEMSKDQMVVDLVFKSKVLFWSGVILGS
VSIGVLGYAVVRN--------WNRWKEW-RQQRGVRPPSQA-------------------
-----------------VTDD--TD-TQI-AEDD-AGD------------VPDGELCVIC
LMRR---KRSAFVPCGHLVCCQRCALSVER---ELSPKCPVCRQIIRSSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
------CIYNEWKGFFGWTSDIRAIF--GRSWREQESTLSRSVPFVLVEAGRW------P
QSDYVIVNLDGSR-HPLPLTTVYHQLQPIDAS-----PY-----------TFLQAFFGYE
YPVGL-----------------LDEEKILPLGKEINAVGLCG-SKNG-IL----------
------------------------------------------------------------
--------------EITSCKDL-PFFL-----SDLSKEQMVVDLAFKTKVLFWSGVVLGS
FSICILGYAAVRN--------WNRWKAW-RQQRQFQQQSNS-------------------
-----------------VSDA--DV-SQIDVEEE-TVD------------VPDGQLCVIC
LMRR---RRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAVRNSI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIF-E
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
------CIYNEWKGFFGWTSDIRAIF--GRSWREQESTSLRMVPFVLVEGGRW------P
QSDYVIVNIDGSR-HALPLTTVYHQLQPIDAS-----PY-----------TFLQALFGHE
YPVGL-----------------LDEEKILPLGKEINAVGICS-SRNG-VL----------
------------------------------------------------------------
--------------EIKSCKDL-PYFL-----SDMTKDQMVVDLAFKTKVLLWSGVVLGS
LSIGILGYAAVRN--------WNRWKEW-RQHRQSQQQNHA-------------------
-----------------ASTD--DD-PQIDADEE-AGD------------VPDGQLCVIC
LMRR---RRSAFIPCGHLVCCQLCAISVER---EVSPKCPLCRQAVRNSM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIF--
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------RTVPFVLIDGSQW------P
AVDYVVVNMDGSK-HHLPLTTVYHQLQPINAS-----PY-----------TFLQALFGHE
YPVGL-----------------LDEEKILPIGKDVSAVGLCF-LKNG-IL----------
------------------------------------------------------------
--------------EIKSCKDL-PYFL-----TEMTKDQMVIDLAFRTKILFWSSIFLGS
ASIGILGFAFVRN--------WNRWKEW-RQRRRDEQQSHA-------------------
-----------------AVDE--AT-AHI-AEDE-LGD------------APDGQLCVIC
LMRR---RRSAFVPCGHLVCCQRCALSVER---EVSPKCPVCRQTITNSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
------------------------------------------------------------
---------------------------------------------------------GVV
LQRTQTCIYNEWKGLFGWTSDLRALF--LRSWRQQESTSLRKIPFVLIDVGRP------S
NPEYVVVNMDGSS-HPLPLTTVYHRLQPVNPP-----PY-----------TFLQALFGHE
YPVGL-----------------LDEEKILPLGKDVSAVGLCS-LRNG-IA----------
------------------------------------------------------------
--------------EIKACNDL-PYYL-----SDLSKDQMIVDLSFKTKLLFWSGILLGS
MSVGIIGYAVVRN--------WNKWKQW-KQQRQLQQRRQQ-------------------
-----------------PIE------PVPPTDDE-IED------------VPDGQLCVIC
LMRR---RRSVFIPCGHLVCCQGCAISVES---EVAPKCPVCRQEVRDSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIF-E
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
---------------------------------------------------------GVI
LQRTQTCIYNEWKGLFGWTSDLRAIF--ARSWRQQESTSLRKVPFLLTDVGRR------P
NAEYVVVNMDGSR-HPLPLTTVYHKLQPITAS-----PY-----------TFLQALFGHE
YPVGL-----------------LDEEKILPLGKDITAVGLCS-LKNG-IA----------
------------------------------------------------------------
--------------EIKSCKYL-PYFR-----SDLSKDQMIMDLSIKTKILFWGGIALGS
MSVGVLGYAVVRN--------WNKWKQW-KQQRQLQQQRQA-------------------
-----------------VSD------VEPQMDDE-IED------------APDGQLCVIC
LMRR---RRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEIRDSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------NAS-----PY-----------TFLQALFGHE
YPVGL-----------------LNEEKILPLGKDISAVGICS-FKNG-IP----------
------------------------------------------------------------
--------------EIMSCKDL-PYFL-----SDLTKDQMLLDLAFRTKILFWSGIILGS
LSISILGYAALRN--------WNRWKER-RQQRQAHQPSHA-------------------
-----------------ASID--AN-SELTGEEE-IGD------------IPDGQLCVIC
LMRR---RVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEIRGSM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVF--
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------IF--SRSWRERESKVFRTVPFILAEGGRR------P
ISEFVAVDMDGSR-HPLPLTTVYHHLHPVNPS-----PY-----------TFLEALFGHR
YPVGL-----------------LDEEKILPLGKEISAVGLCS-VKDG-VL----------
------------------------------------------------------------
--------------EIKSCKDF-PYFL-----SEMSKDQMVVDLTSRTKVLFWSGIFLGS
VSIGVLAYAVSRN--------WNRWKVW-RQQRELQRSIRA-------------------
-----------------SNAE--AQIQEEEEEED-AGD------------VPDGQLCVIC
LMRR---RRSAFIPCGHLVCCQLCSISIER---DVAPKCPVCRQQIRTSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Citrus_clementina_0.9_012450m_PACid_19274708
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------VNMDGSR-QPLPLTTAYQRLELANVS-----PF-----------TFLQAMFGLK
CPIGV-----------------LAEEKILPLGKDISAVGICS-FKNG-IP----------
------------------------------------------------------------
--------------EIKSCKDL-PYFL-----SEKTKDLMVVDLVNRSKILFWSGIVLGS
LSIGILGYAIVRN--------WNRWKD--RQQRMSRQLTEA-------------------
-----------------PSDD--AD-SQIGSDEDVAGD------------IPDGQLCVVC
LTRR---RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRSSM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------VNMDGSR-QPLPLTTAYQRLELANVS-----PF-----------TFLQAMFGLK
CPIGV-----------------LAEEKILPLGKDISAVGICN-FKNG-IP----------
------------------------------------------------------------
--------------EIKSCKDL-PYFL-----SEKTKDQMVVDLVNRSKILFWSGIVLGS
LSIGILGYAIVRN--------WNRWKD--RQQRMSRQLTET-------------------
-----------------PSDD--AD-SQIGSDEEVAGD------------IPDGQLCVVC
LTRR---RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRSSM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
---------------------------------------------------------GVI
LQRIQTCIYNEWRGLFRWTADLGSMLMPRRITKENASSSMNMVPFILVEEGKW------P
PSDHVVVNMEGST-HPLPLTTVYQHLQPVKAS-----SY-----------TVFQALVGLE
YPVGL-----------------LYEEKILPLGKDITAVGICN-LKNG-IP----------
------------------------------------------------------------
--------------EIKSCEDL-PYFL-----SILTKDQMIADLSFKSKVLLWSGLILGT
VAIGVLGYSISRN--------WSKWKEW-KARRAQQQQNAS-------------------
-----------------RIEN-----LDETEEEE-SGD------------VPDGELCVVC
LMRR---RRSAFVPCGHLVCCHRCAFSVER---EVSPKCPVCRQPIRNSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------PY-----------TLIQAIVGHA
YPVGL-----------------LDEEKILPLGKEITAVGHCT-LQDG-NP----------
------------------------------------------------------------
--------------QIISCKKV-PYFL-----SDMTKDQMIVDLVSKKKILFWAGIVLGS
VSLGVLGYALTRN--------WQRLKEW-RQRRQIQQSREE-------------------
-----------------EIANLDATPEDTRADEE-TED------------IPEGQLCVIC
LMRR---KRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDIRTSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AT-----PY-----------TFLQAVFGHE
YPVGV-----------------LDEEKILPLGKNISAVGICS-FENG-VP----------
------------------------------------------------------------
--------------VIKSCSDF-PHFL-----CEMTKDQMILDLVFKTKFLFWSSIVLGS
LTVGILGYSAARN--------WNRWKQW-RQHRQLQNSRNDSPTSQLDSSNDIPIYGDFA
SDDEAATVPDDELSSHVPDDE--LS-SHVPDDEL-SSH------------VPDGQLCVIC
LMRR---KRSAFIPCGHLVCCERCAVSVER---ESSPKCPICRQQIRSSV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RIY--
>Tomato_Solyc12g049330.1.1 genomic_reference:SL2.31ch12 evidence_code:10F0H1E0IEG gene_region:46263202-46267916 functional_description:"Zinc finger family protein (AHRD V1 ***- D7KLF2_ARALY)"
--MSIYDQAAAAVLSQIATAADGALIGLALAYVAVRSIVKFKANSSALHKINDAPSLNVS
DLRSLLSSSDNSDSSNHSDDGKLV-IVRGTVEAKSAVEGNWKSLRANILSAHNSAEKGVI
LQHTQTCIYNEWRGFFSWAGDLYSIF--PRVRKDQQSSSLRTVPFVLIETGRW------P
QPKYVNVNMDGST-HSLPLVTVYHHLQPLHAT-----PL-----------TFIQALFGHH
YPVGV-----------------LDEEKILPLGKDITAIGVCS-SKDG-IL----------
------------------------------------------------------------
--------------EIKSCEDL-PYFL-----SDMTKDQMLVELAFKTKILMWSGVLFGS
VAVGVLGYAVVRN--------WNRWKLW-RHQRQAQQQRDA-------------------
-----------------ASND--DD-VQVSADEE-SGD------------VPDGQLCVIC
LTRR---KRAAFVPCGHLVCCQRC------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------
>SPL2_NP_564653
--MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSIS
DLRSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGDKALI
IQRTQTYVYSGWKRLFQSTGHRFML---ERSLRKHGADFTRTVPFVIVGKDQQ------S
NSSFVAVNMDGSR-QPLPLTTVYNRLQPINS-------------------SFLQAFLYPD
YPVGL-----------------LDIEKILPPGKDITAVGIYS-FNNG-VP----------
------------------------------------------------------------
--------------EIKSCQDL-PYFL-----SEMTKDKMIEDLMEQTNFIFLGSVILGI
VSVGILSYAAVRT--------WNKWKQW-NHQRELPQRPND-------------------
-----------------SVVD--------DEPED-ADE------------IPDGELCVIC
VSRR---RVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRGSM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVYYS
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------VNMDGSR-QPLPLTTVYNRLQPINS-------------------SFLQAFLFPD
YPVGL-----------------LDIEKILPPGKDITAVGICS-FNNG-VP----------
------------------------------------------------------------
--------------EIKSCQDL-PYFL-----SEMTKDKMIEELMDQTSFIFFGSVILGI
VSVGILSYAAVRT--------WNKWKQW-NHQRDLPQRPNE-------------------
-----------------PVVD--------DEPED-ADE------------IPDGELCVIC
VTRR---RVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSIRGSM----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVY--
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----VIVDLDSST-HLLPLTTVYHKLQDLHVMSDEILPY-----------AFLEAFF---
LPVGH-----------------M-QKKILPLGKEINAIGLCS-LQDG-NL----------
------------------------------------------------------------
--------------HIKATQEL-PYFL-----SEMTKGEMVKHLAYKTTILFWGGCIIGI
VSLGVLGYTSFRI--------WEWWKVR-RQHFSNAEVDDV-------------------
-------------------------------YIG-NDE------------IPSEQLCTIC
TMRR---KKYACVPCGHLVCCHKCARSIQH---DSTARCPECRH----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------LGHA
YPFGLCLQEKFLPLNFAWYHPGLLEEKILPLGKEISVVGIGT-SEYG-NV----------
------------------------------------------------------------
--------------EIKPCDEL-PYFL-----SDLTKDQMIGELAQKTNYLLLSAIFFGS
LSLAVIAYAVMIG--------CQRFEEKTQQRRQVQQQMTQ-------------------
-----------------VQQSL----RNDVVEEG-MEA------------LPEGLSCVV-
---------SVFVPCGHLVCCQTCAPLVAR-----DRRCPICRQYIQKYI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ITY--
>Physcomitrella_patens_Pp1s12_190V6.2_PACid_18048531
--------------------------------------MLSWGGITLCLSGAALYCLSRN
TGRDALNLRSIERVNQLKDLAILL-ESACKVVPLVVTVAGRVGSETPIACEH-SSLRGVI
LEETAEQHFLKHNDTGS-----------WIQDSALMLSISKEVPWYLE-----------D
GTGRVYIVGARNA-AGMELTVASEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRVERVLPTGTNLTVVGEAVQDDRG-LI----------
------------------------------------------------------------
--------------RIQKPNKG-PFYV-----TPKSLDQLVANLGRWSRWYKYMSLGFTI
VGIYFITSHAIKHF-------MERRRRE-ALHRRVM-EAAA-LRQASQREGGDGD-----
-----------------MGDVTSHPLDDSVDTSQ-KKD------------RGTPDLCVIC
LEQD---YNAVFLPCGHMCCCTSCSAQLTS--------CPLCRRHIDKFV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTYRH
>Physcomitrella_patens_Pp1s175_124V6.2_PACid_18055474
--------------------------------------MLSWGGITLCFSGAALYCLSRN
TGRDALHLMSVERVNQLEDLAKLL-ESACTVVPWVVTVAGRVGAEAPIASEH-SSLRGVI
LEKSAEQHFLKHNDTGS-----------WIQHSALMLSISKEVPWYLE-----------D
GTSRVFIIGARNA-AGMDLTVASESFEEYGG------SLVRGTL------DYLQGL----
KMLGV-----------------KRVERVLPTGTNLTVVGEAVQDDRG-LI----------
------------------------------------------------------------
--------------RIQKPDKG-PFYV-----TPQSQDQLIENLGRWSRWCQYMSFGLTL
VGIYFITSRAIKHM-------LERWRRE-ALLTRVM-EAAA-LRKALQQEGVDEE-----
-----------------SDGVTAFPHDDNAHTAQ-KKD------------GGMPSLCVIC
LEQD---YNAVLVPCGHMCCCTSCSSQLSL--------CPLCRRHIDQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Selaginella_moellendorffii_231449_PACid_15416766
--------------------------------------MLPWGGITMCLSGVALYFLSRN
SGRDAATLKAVRRVDQLKDLAHLL-DSACKAVPLVVTVAGRVGSETPIGCDH-SSLRCVI
LEETAEQHFLKHNDTGS-----------WIQDSALMLSNNKEVPWFLE-----------D
ASGRVFIVGARGA-AGLELTIASEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRVERVLPTGTALTVVGEAIKDDQG-TL----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----TPKSIDQLIANLGKWSRWYKYMSLGFTL
FGVFLVASHTIRYV-------MEKRRRA-ALNRRVM-EAAA-RRRERKEHEGKAQ-----
-----------------VGEF------AKVETAT-KRD------------GRLPDLCVIC
LEQE---YNAVFVPCGHMCCCISCSAQLQN--------CPLCRRRIEQIV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTYRH
>Medicago_truncatula_Medtr1g111550.1_PACid_17439105
--------------------------------------MVPWRGVGCCLSAAALYLLGRT
SGRDVDILKSVNRVNQLRELAQLL-DEE--IFPLVVAISGRVGSETPISCEF-SGLRGVI
IEETAEQHFLKHSDAGS-----------WIQDSALMQSRSNEVPWYLD-----------D
GTGRVRVVGAQGA-TGFVLPVGSEAFEESGR------LPVRGTS------DYVQGL----
KMLGV-----------------KRIERVLPVGTSLTVVGEAAKDDVG-TI----------
------------------------------------------------------------
--------------RIQRPSKG-PFYV-----SPKTIDELIANIGRWARWYKYASAGLTV
LSVYMIANHAVRYI-------LERRRRN-ELEKRVL-AAAA-KISGQDNGGE--M-----
-----------------D---------DSLSDGA-KRE------------RAMPNLCVIC
LEQE---YNSVFVPCGHMCCCTACSSHLTS--------CPLCRRQIEKAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Glycine_max_Glyma10g02920.1_PACid_16278382
--------------------------------------MIPWGGLSCCLSAAALYLLGRS
SGRDAEILKSVTRVNQLKELAQLL-DAE--ILPLIVTISGRVSSETPINCEF-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTDRVHVVGARGA-SGFALPVGIEAFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPVGTSLTVVGEAAKDDVG-AI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDQLIANLGKWARWYKYASVGLTV
FGAYLIAKHAIRYI-------LERRRRS-ELQRRVL-AAAA-KKSGQNNDVE--K-----
-----------------A---------DSLSDGA-KKD------------RLMPDLCVIC
LEQE---YNAVFVPCGHMCCCTACSSHLTN--------CPLCRRQIEKVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Prunus_persica_ppa008230m_PACid_17644506
--------------------------------------MLPWGGLSCCLSAAALYLLGRS
SGRDADILKSATRINQLKELAKLL-DSEC-ILPLVVAISGRVSSETPITCEF-TGLRGVV
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTGRVHVVGARGA-TGFVLPVASEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTSLSVVGEAVKDDIG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDQLIANLGKWARWYKYASLGLTV
FGVYLVAKHSVQYI-------LERRRRW-ELQRRVL-AAAA-KRSGEDNEGSNEK-----
-----------------D---------DNVLDGS-K--------------RLMPDLCVIC
LEHE---YNAVFVPCGHMCCCTTCSLHLTN--------CPLCRRRIDQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
--------------------------------------MLPWGGISCCLSAAALYLLGRS
SGRDAELLKSVTRVNQLKELAQLL-EAE-HLLPLVVAISGRVSSDTPINCEF-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTGRAFVLGARNA-TNFILPVVSEVFEESGR------SLMRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTSLTVVGEAAKDDIG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDQLISNLGKWARWYKYASMGLSI
FGLYLVTKHVILYL-------MERRRRW-ELQKRVL-AAAA-KRSSQENEGEIEK-----
-----------------A---------SNGTDGT-KRD------------RSMPDLCVIC
LERD---YNAVFVPCGHMCCCVACCSHLTN--------CPLCRRRIELVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
--------------------------------------MIPWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLKELAHLL-DSGSKVLPFIVTVCGRVGSETPISCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTGRAFVVGARGA-TGFVLTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERLLPTGTSLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDELIENLGKWARWYKYASFGLTI
FGTFLIAKRAIHYI-------LQRKRRW-ELHRRVL-AAAAVKRSEQDNEGTNGQ-----
-----------------A---------ENGSDGT-QRD------------RVMPDLCVIC
LEQE---YNAVFVPCGHMCCCIICSWHLTN--------CPLCRRRIDQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Citrus_clementina_0.9_003846m_PACid_19263951
--------------------------------------MIPWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLKELAHLL-DSGSKVLPFIVTVCGRVGSETPISCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTGRAFVVGARGA-TGFVLTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERLLPTGTSLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDELIENLGKWARWYKYASFGLTI
FGTFLIAKRAIHYI-------LQRKRRW-ELHRRVL-AAAAVKRSEQDNEGTNGQ-----
-----------------A---------ENGSDGT-QRD------------RVMPDLCVIC
LEQE---YNAVFVPCGHMCCCIICSSHLTN--------CPLCRRRIDQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
--------------------------------------MISWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLEELAHLL-DGGSKVLPSIVSVSGRVGSETPISCEY-SGLRGVI
VEETTERHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTGCVFVVGARGA-TGFALTVGSEVFEESGR------SLVHGTL------DYLQGL----
KMLGV-----------------KRIGRLLPTGTSLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDELLENLGKWARWYKYASFGLTI
FGAFLIAKRVIRCI-------LQRKRRW-ELRRRVL-AAAAVQRSEQDNEGTNGQ-----
-----------------A---------ENGSDST-QRD------------RVMPDLCVIC
LEQE----------CGHLCCCLICSSRLTN--------CPLCRRRIDQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Citrus_clementina_0.9_014777m_PACid_19265048
--------------------------------------MISWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLEELAHLL-DGGSKVLPSIVSVSGRVGSETPISCEY-SGLRGVI
VEETTERHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTGCVFVVGARGA-TGFALTVGSEVFEESGR------SLVHGTL------DYLQGL----
KMLGV-----------------KRIGRLLPTGTSLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDELLENLGKWARWYKYASFGLTI
FGAFLIAKRVIRCI-------LQRKRRW-ELRRRVL-AAAAVQRSEQDNEGTNGQ-----
-----------------A---------ENGSDST-QRD------------RVMPDLCVIC
LEQE---YNAVFFPCGHLCCCLICSSRLTN--------CPLCRRRIDQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
--------------------------------------MLPWGGISCCLSAAALYLLGRS
SGRDAEVLKSVTRVNQLKELAKLL-DIESNISPSVVSISGRVGSETPINCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTDRVYVVGARGA-SGFVLTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTSLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RVQRPHKG-PFYV-----SPRTIDELIGNLGKWARWYRYASVSLTV
FGAFLIAKHAIQYI-------MERRRRW-ELQSRVLAAAAA-KRQGQDSEGSNGK-----
-----------------A---------ENGSDNS-KRE------------RPVPDLCVIC
LEQE---YNAVFLPCGHMCCCTTCSSHLTN--------CPLCRRRIEQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Ricinus_communis_29703.m001546_PACid_16806242
------------------------------------------------------------
-------LKSVTRVNQLNELAKLL-DIESKVLPLVVAISGRVGSETPINCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTDRTFVVGARGA-SGFALTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTSLSVIGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDELIGNLGKWARWYRYASVGLTV
FGVFLIAKHAIQYI-------MERRRRW-ELQSRVL-AAAA-KRQGQDSDGSNGK-----
-----------------A---------ENGSDSS-KRE------------RPIPDLCVIC
LEQE---YNAVFLPCGHMCCCTACSSHLTN--------CPLCRRRIEQI-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------
>Vitis_vinifera_GSVIVT01011070001_PACid_17823049
--------------------------------------MIPWGGISCCLSAAALYLLGRS
SGRDAEALKSVTRVQQLKDLVQLL-DTACKVLPLVVTVSGRVGSDTPIKCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
DTGRAYIVGARGA-TGLVLTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTPLTVVGEAIKDDVG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKSIDHLVANLGKWARWYRYASLGFTV
FGVYLIAKSAIQYV-------MERKRCW-ELRKRVL-AAAS-KKSGQDSEDPDEK-----
-----------------D---------ENGSDNT-KRD------------RLMPDLCVIC
LEQE---YNAVFVPCGHMCCCTMCSSQLTN--------CPLCRRRIEQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
--------------------------------------MIPWGGLSCCLSAAALYVLGRS
SGRDAEALKCVFRVNQLKELAQLL-DTECKVLPLVVTLCGRVGSDTPINCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTGRAYVLGARGA-SGFELNIASEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERLLPVGSSLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKTIDQLISNLGKWARWYRYASYGFTV
FGICLIAKRAIQYI-------MERKRRW-ELQRRVL-AAVA-RRSEQDTEGTDDK-----
-----------------T---------KNAPDSA-KRD------------RSMPDLCVIC
LEQE---YNSVFVPCGHMCSCTTCSLQLTN--------CPLCRRRIEQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Tomato_Solyc06g084360.1.1 genomic_reference:SL2.31ch06 evidence_code:10F0H1E1IEG gene_region:45791481-45798777 functional_description:"Baculoviral IAP repeat-containing protein 3 (AHRD V1 *--- B0XJ37_CULQU); contains Interpro domain(s)  IPR001841  Zinc f
--------------------------------------MVPWAGLSCCLSAAALYLLGRS
SGRDAEVLKSVTRVNQLKDLAQLL-DTASKVLPLVVTISGRVGSDTPINCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMCKEVPWYLD-----------D
GTGRTFIVGGRGA-TGLVLTVGSEAFEEAGR------SFVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPVGTPLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYI-----SHKTIDQLIANLGRWARWYKYASMGFTA
VGVYLLVKHTFHYM-------MERKRHW-ELRRRVL-AAAA-KRAGDEDEGSDAT-----
-----------------A---------ENGVD---NKD------------LLMPDLCVIC
LEQE---YNSVFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
--------------------------------------MIPVGGITCCLSAAALYLLGRS
SGRDADLLKSVTRVNQLKDLAQLL-EAASKVLPLVVTVSGRVGSETPINCEY-SGLRGVI
VEQTAEQHFLKHNDAGS-----------WIQDSALMLSMCKEVPWYLD-----------D
GTSRVHVVGARGA-TGLVLTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGSPLTVVGEAVKDDIG-SI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----TDKTIDQLIANLGKWSRLYKYASMGLTA
FGVYLLAKHAFQYI-------MDRRRLW-ETRKRVL-DAAA-KKAGQNEGALNGE-----
-----------------A---------EIGSDSS-NKE------------RPIPELCVIC
LEQE---YNSVFVQCGHMCCCMACSSHLTN--------CPL-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
--------------------------------------MLPWGGITCCMSAAALYLLGKS
SGRDADILKSVTRLNQLKDLAQML-DTACKVLPFVVTVSGRVGSDTPINCEH-SGLRGVI
VEEAAEQHFMKQNDSGS-----------WIQDSAQMLAMTKEVPWYLD-----------D
GTGRVHVLGARGA-TGLVLTVASETFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTSLTVVGEAVKDDVG-TI----------
------------------------------------------------------------
--------------WIQRPHKG-PFYV-----SPKSIDQLIANLGIWARLYKYASLGFTA
FGVYLIAKHAIRYI-------LERRRLL-DFQRRVR-AAAA-QRLEQDNDGTDGK-----
-----------------A---------EDGPDVV-NKD------------RIMPDICVIC
LEQE---YNAVFVPCGHLCCCTTCSSHLSN--------CPLCRRRIDQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Arabidopsis_lyrata_474968_PACid_16053684
--------------------------------------MIPWGGVTCCLSAAALYLLGRS
SGRDAEVLKTVTRVNQLKELAQLL-ELDSKILPFIVAVSGRVGSETPIKCEH-SGIRGVI
VEETAEQHFLKHNETGS-----------WVQDSALMLSMSKEVPWFLD-----------D
GTSRVHVMGARGA-TGFALTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGIPLTIVGEAVKDDIG-EF----------
------------------------------------------------------------
--------------RIQKPDRG-PFYV-----SPKSLDQLISNLGKWSRWYKYASMGFTV
FGVFLITKHVIDSV-------LERRRRR-QLQKRVL-DAAA-KRAELESEGSNGA-----
-----------------R---------ESIADST-KKE------------DAVPDLCVIC
LEQE---YNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDLAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTYRH
>SP1
--------------------------------------MIPWGGVTCCLSAAALYLLGRS
SGRDAEVLETVTRVNQLKELAQLL-ELDSKILPFIVAVSGRVGSETPIKCEH-SGIRGVI
VEETAEQHFLKHNETGS-----------WVQDSALMLSMSKEVPWFLD-----------D
GTSRVHVMGARGA-TGFALTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGIPLTIVGEAVKDDIG-EF----------
------------------------------------------------------------
--------------RIQKPDRG-PFYV-----SSKSLDQLISNLGKWSRLYKYASMGFTV
LGVFLITKHVIDSV-------LERRRRR-QLQKRVL-DAAA-KRAELESEGSNGT-----
-----------------R---------ESISDST-KKE------------DAVPDLCVIC
LEQE---YNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDLAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTYRH
>Populus_trichocarpa_POPTR_0014s13410.1_PACid_18222628
--------------------------------------MIPWGGISCCLSGAALYLLGRS
SGR---YLPSLIPLFFLIISSKLL-DIESKVLPLVVAISGRVGAESPISCEF-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTDRVYVVGARGA-SGFVLTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTSLTVVGEAVKDDIG-TV----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKSIDELIGNLGKWARWYKYASLGLTV
FGAFLITKHVIRYI-------MERRRRW-ELQSRYV-SLVE-GIHDKMFQG---------
---------------------------KGHANGA-KRE------------RPIPDLCVIC
LEQE---YNAVFLPCGHMCCCITCCSQLSN--------CPLCRRRIEQVV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTFRH
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGSDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAISGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-----------WIQDSAVMLSVSKEVPWYLD-----------D
GTGRVYVVGARSA-AGLILTVASEVFEESGR------TLVRGTL------DYLQGL----
KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYA-----SSKSIDQLIVNLGKWAKLYRIASMGFAT
FGVFLLAKRALQHF-------LERRRRH-ELQKRVL-NAAA-QRQAREAEGSKGT-----
-----------------S----------DAEPNS-KKD------------QLVLDICVIC
LEQE---YNAVFVPCGHMCCCVACSSHLTN--------CPLCRRRIDQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAVSGRVSSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-----------WIQDSAVMLSVSKEVPWYLD-----------D
GTGRVYVVGARSA-AGLILTVASEVFEESGR------TLVRGTL------DYLQGL----
KMLGV-----------------KRTERVLPTGTSLTVVGEAIRDDVG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKSIDQLIMNLGKWAKLYRLASMGFAT
FGVFLLAKRAIQHF-------LERKRRH-ELQKRVL-NAAA-QRQAREAEGSNGS-----
-----------------S----------DTEPNS-KKD------------QLVLDICVIC
LEQE---YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAVSGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-----------WIQDSAVMLSVSKEVPWYLD-----------D
GTGRVYMVGARSA-AGLILTVASEVFEESGR------TLVRGTL------DYLQGL----
KMLGV-----------------KRTERVLPTGISLTVVGEAIKDDVG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKSIDQLIMNLGKWAKLYRLASMGFAT
FGAFLLAKRAIQHF-------LERKRRH-ELQKRVL-NAAA-QRQAREAEGSIGS-----
-----------------S----------DTEPNS-KKD------------QLVLDICVIC
LEQE---YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Setaria_italica_Si030396m_PACid_19714000
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAVSGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-----------WIQDSAVMLSVSKEVPWYLD-----------D
GTGRVYVVGARAA-AGLILTVASEVFEESGR------TLVRGTL------DYLQGL----
KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKSIDQLILNLGKWAKLYRLASMGFAT
FSVFLLAKRAIQHF-------LERKRRH-ELQKRVL-NAAA-QRQAREAEGGKGT-----
-----------------S----------NTEPNS-KKD------------QLVLDICVIC
LEQE---YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
--------------------------------------LIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSTKDLAAIL-DTASKVLPLVVAVSGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-----------WIQDSAVMLSVSKEVPWYLD-----------D
GTGRVFVVGARGA-AGLVLTVASEVFEESGR------TLVRGTL------DYLQGL----
KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYV-----SPKSIDQLIMNLGKWAKLYQLASMGFAA
FGVFLLAKRALQHF-------LERKRRH-ELQKRVH-AAAA-QRQAREAEGGNGT-----
-----------------S----------DVDSNN-KKD------------QLVLDICVIC
LEQE---YNAVFVPCGHMCCCMNCSSHLTN--------CPLCRRRIDQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
--------------------------------------MVPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVTRTGSLKDLAAIL-DTASKVLPLVVAVSGRVSSDTPLICQQ-SGMRGVI
VEEMAEQHFLKHNDAGS-----------WIQDSAVMLSVSKEVPWYLD-----------D
GTGRVYVVGARAA-AGLVLTIASEVFEESGR------TLVRGTL------DYLQGL----
KMLGV-----------------KRTERVLPTGTSLTVVGEAIKDDVG-TI----------
------------------------------------------------------------
--------------RIQRPHKG-PFYA-----SPKSIDQLILNLGKWAKLYQLASMGFAA
FGVFLLAKRALQHF-------LQKKRQH-ELNKRVR-AAAA-QRQAREAEGADGT-----
-----------------S----------NGDPNS-KKD------------QLVLEICVIC
LEQE---YNAVFVPCGHMCCCMNCSSHVTN--------CPLCRRRIDQAV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
--------------------------------------MIPWGGITCCMSAAALYLLGRS
SGRDADILRKVTRVNQLKELAQLL-DIESKIMPLIVAISGRVGSETPISCEY-SGLRGVI
VEETAEQHFLKHNDAGS-----------WIQDSALMLSMSKEVPWYLD-----------D
GTARVFVVGARGA-TGFVLTVGSEVFEESGR------SLVRGTL------DYLQGL----
KMLGV-----------------KRIERVLPTGTSLTVVGEMTLEQ----F----------
------------------------------------------------------------
--------------RYEDRTNG-LFTCLQINGSPD------FQLGKWARWYKYASMGLTF
LGVFLIAKRSIEYV-------LERRRRR-ELQKRVL-AAAA-KRSGQDNEGSNII-----
-----------------P---------ENGLDGA-KRE------------HLMPDLCVIC
LEQE---YNAAFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQVL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RTFRH
>SPL1_NP_564745
--------------------------------------MIHLAGFTCCLGGVALYLLTRS
TGRD---IKSITRVYQLKDLEQLV-EVESKVVPLIIAVSGDVGSETPIKCEH-SYVLGVF
LKRTAEQQVLRRNWRFS-----------WVRNSTLMQPMTKEVPWYLD-----------D
GTGRVNVDVSQGE-LGLALTVGSDVFEKAEPV-----SLVQGAL------GYLKGF----
KILGV-----------------RHVERVVPIGTPLTVVGEAVRDGMG-NV----------
------------------------------------------------------------
--------------RIQKPEQG-PFYV-----TYIPLDQLISKLGDLSRRFKYASMGLTV
LGVILISKPVIEYILKRIEDTLERRRRQ-FALKRVV-DAAA-RRAKPVTGG---------
--------------------------------GT-SRD------------GDTPDLCVVC
LDQK---YNTAFVECGHMCCCTPCSLQLRT--------CPLCRERIQQVL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KIYRH
>Arabidopsis_lyrata_338432_PACid_16045815
--------------------------------------MIHLAGFTCCLGGIALYLLSRN
TGGV---VKSITRVNHLKDLEQL---VESKVFPLIIAVSGIVGSETPIKCEH-SDILGVF
LKKTAEQQVLSRNWRFS-----------WVRKSTLMQPMTKEVPWFLD-----------D
GTGRVNVAVSQGE-IGLALTVGSDVFEKAEPV-----SLVQGTL------DYLKGL----
KILGV-----------------RRVEHVVPIGTPLTIVGEAVKDGMG-NV----------
------------------------------------------------------------
--------------RIQKPEQG-PFYV-----SYVPLDQLISKLGEWSRRFKYASMGLTV
VGVILLSKPVIKYILKKIEDTLERRRRQ-LLQKRVV------------------------
---------------------------------------------------DVPDLCVIC
HDQK---YNTAFVQCGHMCCCLTCSLRLTT--------CPLCREQIQQVL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KIYRH
>Arabidopsis_lyrata_867782_PACid_16034683
--------------------------------------MIHLGGLTCCVSGGVLYLLSMI
PGSFFEMLNSVTRVHQIKDLENLL-QVEGK----IIAVSG--------------------
---TAQQLFLKRNWLFS-----------WVEDSKWMLPQAKEVPWYL-------------
------------------------------------------------------------
-MLGV-----------------RRTEHVLPIGTPVTVVGEAVKDGIR-GF----------
------------------------------------------------------------
--------------RIQKPEKG-LFFV-----SPVPLDKIISPMGKWLRRFKYVYVGLTV
VGVILISKPVIEYI-------LERRRGR-LLRKRVA-DAAA-KRAKLVARGLETQ-----
-----------------H---------ENSLDST-SRD------------RDVLDLCVIC
LEQK---YDATFVKCGHMCCCLTCSLHVKT--------CPICRRPIEHVL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KIDR-
>Chlorella_variabilis_gi|307103723|gb|EFN51981.1| hypothetical protein CHLNCDRAFT_27288 [Chlorella variabilis]
--------------------------------------MPCPRAVLCC------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------RIPDNQTQ------GFLGRVV------DEVQGS----
RSVGV-----------------RQVERMLPVGTMLTAVGELATAGGK-ML----------
------------------------------------------------------------
--------------VLRAPRDG-AFYL-----SRQPLPDVIASLQASSLACQQWAAAFTA
VGASMLVAAATQHA-------LTWVRQR-RLRQRVE-KAMR-ERAAAAAAAGGGG-----
-----------------A---------AGAPAAS-AAEPQPADVAEAAEGGARPSLCVVC
LERP---CATVFPACGHMCACSRCSHGLRR--------CPICRSR-GAPI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVYTA
>Mulan_NP_078820
MESGGRPSLCQFILLG-----------------------------TTSVVTAALYSVYRQ
KARVSQELKGAKKVHLGEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVI
QRLTLQEHKMVWNRTTHL----------WNDCSKIIHQRTNTVPFDLVPHEDG-------
VDVAVRVLKPLDS-VDLGLETVYEKFHPSIQ------SFTDVIG------HYISGE----
RPKGI-----------------QETEEMLKVGATLTGVGELVLDNN--SV----------
------------------------------------------------------------
--------------RLQPPKQGMQYYL-----SSQDFDSLLQRQESSVRLWKVLALVFGF
ATCATLFFILRKQ--------YLQRQER-LRLKQMQEEFQE-HEAQ--------------
---------------------------LLSRAKP-EDR------------ESLKSACVVC
LSSF---KSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITRVI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------PLYNS
>Mus_musculus_gi_18043560_gb_AAH19516.1
MESGSRPSLGQVILLG-----------------------------TSSMVTAVLYSIYRQ
KAQVAQELKGAKKIHLGEDLKGILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVI
QRLSLQEHKMVWNRTTHL----------WNDYSKIIHQRTNTVPFDLVPHEDG-------
VAVSVRVLKPLDS-VDLGLETVYEKFHPSVQ------SFTDAIG------HYISGE----
RPKGI-----------------QETEEMLKVGATLTGIGELVLDNN--AV----------
------------------------------------------------------------
--------------RLQPPKQGMQYYL-----SSQDFDSLLHRQESSVRLWKVLVLVFGF
ATCATLFFILRKQ--------YLHRQER-LRQQQLQEEFLE-HEAQ--------------
---------------------------LLSQASP-EDR------------ESLKSACVVC
LSNF---KSCVFLECGHVCSCRQCYLALPE-----PKRCPICRREITRVI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------PLYNS
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
MENGGRPSVGQVILLT-----------------------------TSSAITALFYSIYRH
KYRSVQTLKEAKKFCLTDDLPAVLSDLPGKCVPYAVIEGAVTSVKEVLNSQYVENCKGVI
QRLSLKEHKMVWNRTTHL----------WNDHEKIIHQRSNTVPFDLAPENPG------E
SGVSVRVLRPLEA-VDLGLETIYEKFHPAVQ------SFSNILG------HYMTGE----
RPKGV-----------------QETEEMLKIGATITGVGELVLDNK--TI----------
------------------------------------------------------------
--------------KLQPPKDGMLFYL-----SSMDYEGLLEKQEVQMRWWRILSIVFGV
ASCITLFFILRRK--------YRHYKEK-QHLKNLQREFEE-SRAR--------------
---------------------------QRVQQEP-QNK------------EEVQNPCSIC
LSTE---KSCVFLECGHVCSCISCYQALPS-----PKKCPICRNFIDRIV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------PLYNS
>Danio_rerio_gi_148922854_ref_NP_001092230.1
MEASGKPSTAQIVLLA-----------------------------TSSALTAVLYTIYKR
KSSHVARLREAKKMSLNPELKTILSEAPGKCVPYAVIEGVVRSVKETLNSQFVDNCKGVI
QRLTLNEKKMVWNRTTNL----------WNDCEKVIHQRTNTVPFDLAPHDDT-------
VPTTVRVLRPLDA-AELDLETTYENFHPSQQ------SLTNVIG------HFISGE----
RPQGI-----------------QETEEMLRLGASMTGVGELVLDNN--LV----------
------------------------------------------------------------
--------------RLQPPKKGLRYFL-----SRLDYDTLLSKQEGHLRIWRVLTVLLGL
TACATFFYLLWRQ--------YVLRKER-RKEQSVLDEYRK-WQSK--------------
---------------------------RFQELHL-AKE------------DVSPTACTIC
LNHE---RSCVFLECGHVCACEGCYRALPE-----PKKCPICRATIDRIV----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------SLYNS
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
MEFLHESVALG----------------------------------VDLLILGLCAREYVH
YKRTAKVLKAAPQYNIDGDLKSVVERQRDKKIPYAVIRGTVTPIGVPLRSSLVPSVSGVL
QIVKLHEHRVTRGFAGF-----------WTEQHKLLHESANEMPFELR-----------N
QSHGVEIVDALSA-AVLDVDVVYDNYEPSNL------SLFDHVF------GFFSGV----
RQRGL-----------------QTTEEVLREGSFLTAIGELELDGD--TL----------
------------------------------------------------------------
--------------RMQPSNEG-PLFL-----TTATKSTLIKRFEDAKTTTILKLVVCST
ISAILVAFIAKKL--------YRKRKQE-REEAKIRERLDT-ERRERRARSRPHT-----
--------------------------------------------------LSQDQLCVVC
STNP---KEIILLPCGHVCLCEDCAQKISV-------TCPVCRGSIVSKA----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AAFIA
>Volvox_carteri_96908|PACid:17997093
-------------------------MGELADRPSSWLNFVSYGGLASLGISAVLFQLAKL
QDGR---VFELDRAQALETLASIC--RPDHILPLLVAVRGRITCREPAVCQL-SGVPAVM
RELVEEEVYFKEQHTGR-----------TSQECFEIRREQEQREAFLE-----------D
RTGSIRLENLQHA-SGLP--GVMEVKQEFRHA-----DLLQGTLLQAVLSKALKSM----
VKHGV-----------------RVTERYLPVDTAVTVVGELVADCMGSTAAAAAGCRTRP
AAGGSGNPLLASSSQQQPSDVSGSGVEAAAAADVARTATGGGGGTGSLSAAATAVAAAAG
AELLGQAALQALPYTLRMPGRG-PFHV-----TTLTLPQLRASLERTSGVIRAFAWGFGL
LGAALFVRKAAQA--------YHRLQAY-RRYKRYAALAEA-ARRTAAAGGGAAA-----
-----------------GMGTSAATGATAGDDDG-DGV----------------------
----------------------RSPGTVTS-----------------RTI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RVFRP
>rsz31o21_6
------------------------------------------------------------
-------------------------------------------------CRVVRSV----
-------------------------------------PHSRFRPWFTR------------
-TPRTTMFGRRVY-ALLEIPKIHS--------------------------SXCWSLFLXA
NVLG-------------------------PLHSLLHGEGXSRTAQRALSS----------
------------------------------------------------------------
--------------SMSSRWSRCPQYL------------------PHSRPVWASGTARIA
TAVSCPVDIASRFFSN-----RTRPNSP-SIDTRLF-CCSA-LRAP--------------
----------------------------KISPRA-AAE------------AEHDDLCIIC
MTDP---RDTTVLPCGHLCLCVDAQLLRVR-----SDRCPICRSPVDSLL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------XI-RX
