>SPL1_NP_564745
mihlagftcclggvalylltrstgrdiksitrvyqlkdleqlveveskvvpliiavsgdvgsetpikcehsyvlgvflkrtaeqqvlrrnwrfswvrnstlmqpmtkevpwylddgtgrvnvdvsqgelglaltvgsdvfekaepvslvqgalgylkgfkilgvrhvervvpigtpltvvgeavrdgmgnvriqkpeqgpfyvtyipldqlisklgdlsrrfkyasmgltvlgviliskpvieyilkriedtlerrrrqfalkrvvdaaarrakpvtgggtsrdgdtpdlcvvcldqkyntafvecghmccctpcslqlrtcplcreriqqvlkiyrh
