>Cyanobacteria gi|158336842|ref|YP_001518016.1| hypothetical protein AM1_3710 [Acaryochloris marina MBIC11017] >gi|158307083|gb|ABW28700.1| conserved hypothetical protein [Acaryochloris marina MBIC11017]
---------------------------M--------------------------------
-----------------------------------KIIGIILIV---IGIILF-FVYSNL
KRKLASLRQ-ARPASIAELNHL---ASEIALEM-GS-GSWRDYVKLRGTI----------
QCDQ-PLISE-LKQMPCVHYNMTVVREYE--EQVTER-------D-------SDDKVVT-
------------------------------------------------------------
-----------------------------K--TQRGSETLSQNRESVPFFL-----QDDT
G-EIWVEPEGAQ--IETV-RVL-------DE-FSPEQPSGG-QLSFGGFSLSLSSA--ET
GRQTIGYRYQESVLPVQRQVFVVAQV----------------------------------
----------------------------SDFNQSLV--LEN-PTT-KGQRFVISLKSEEA
LAQTTQTS-------VTYA-FYGMI---STLVVGGLLVIFG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-----L-SA---------------
>Cyanobacteria gi|359460153|ref|ZP_09248716.1| hypothetical protein ACCM5_15608 [Acaryochloris sp. CCMEE 5410]
MQEPQSSISSDVGQNQSILGPTGVQASM--------------------------------
-----------------------------------KIIGIILIV---IGIILF-FVYSNL
KRKLASLRQ-ARPASIAELNHL---ASEIALEM-GS-GSWRDYVKLRGTI----------
QCDQ-PLISE-LKQMPCVHYNMTVVREYE--EQVTER-------D-------SDDKVVT-
------------------------------------------------------------
-----------------------------K--TQRGSETLSQNRESVPFFL-----QDDT
G-EIWVEPEGAQ--IETV-RVL-------DE-FSPEQPSGG-QLSFGGFSLSLSSA--ET
GRQTIGYRYQESVLPVQRQVFVVAQV----------------------------------
----------------------------SDFNQSLI--LEN-PTT-KGQRFVISLKSEEA
LAQTTQTS-------VTYA-FYGMI---STLVVGGLLVIFG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-----L-SA---------------
>Cyanobacteria gi|220906503|ref|YP_002481814.1| hypothetical protein Cyan7425_1067 [Cyanothece sp. PCC 7425] >gi|219863114|gb|ACL43453.1| conserved hypothetical protein [Cyanothece sp. PCC 7425]
-------------------------MGL--------------------------------
-----------------------------------AIVGAILLV---TGGILY-FVQRHY
QQKLYSIKL-ARKTTVAELKQL---ADQVGAEI-GQ-GSLREYVKLSGQI----------
KCDT-PLISE-LKQVPCVYYQMQVEREYE--ERLTER-------D-------NDGETRE-
------------------------------------------------------------
-----------------------------K--TQRGSETIASNSQSTPFFL-----QDQS
G-AIEVDPSGAA--IETV-QVL-------NE-FRPEAGSA--RISFGNFSLSVGGSF-PA
GRETIGYRYRESILPPDRRILIVATA----------------------------------
----------------------------SDSSGILS--LQK-PVE-KRQKFIISLKSEDH
LAQSTQQT-------ATYT-FYGMI---ACLGLGAILLVVG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-----IIR----------------
>Cyanobacteria gi|427714017|ref|YP_007062641.1| E3 Ubiquitin ligase [Synechococcus sp. PCC 6312] >gi|427378146|gb|AFY62098.1| E3 Ubiquitin ligase [Synechococcus sp. PCC 6312]
---------------------------M--------------------------------
-----------------------------------LFVSAILLI---AAVVLF-FVQRHY
RLRLRSLKL-ANRVNSQSIKQL---AADVATEI-GA-GSLREYVKLYGRV----------
KSDD-PLISE-LKQVPCVYYSMQVIREYE--ERVRSE-------D-------SEGRTEW-
------------------------------------------------------------
-----------------------------R--TERRSDTISSNSQSTPFLL-----QDAQ
G-TVRIDPEGAG--VETI-QVL-------NE-FRPEGNSN--RLSFGGFSLNLDIAVGSG
GGRTLGYRYQESILPLERQVLIVGEA----------------------------------
----------------------------SDQTGELV--IGK-PQQ-NGRKFFISLKSEDT
LTNHTQNI-------MTYT-TLGAI---ASGVIGVLVGILG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-----V-S----------------
>Cyanobacteria gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424] >gi|218172398|gb|ACK71131.1| conserved hypothetical protein [Cyanothece sp. PCC 7424]
---------------------------M--------------------------------
-----------------------------------ILIGIICLI---VGVILL-FFWRSN
RSKLRNLRL-ASASTISSLQTI---ANQIAEEI-GG-GSLREYVKIRGVI----------
ECDR-PLISQ-LKQEPCVYYSMTVTWEYN--EEVIKQ-------D-------NEGKTIR-
------------------------------------------------------------
-----------------------------E--KERKSETVAQNSRSIPFTL-----QDST
G-EIRVNPERAE--IETV-KVL-------EE-FRPENFSGG-SLTFGNFSINLPSF--EE
RRQTIGYRYQEEILPIGRQILVIGTA----------------------------------
----------------------------TDEEGMIT--IRK-PTE-KGQRYFISLKSEEE
LSQATNNA-------IRGT-FYSMI---FFLTLGLILLVAG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------V-----L-RG---------------
>Cyanobacteria gi|56752521|ref|YP_173222.1| hypothetical protein syc2512_d [Synechococcus elongatus PCC 6301] >gi|81300335|ref|YP_400543.1| hypothetical protein Synpcc7942_1526 [Synechococcus elongatus PCC 7942] >gi|56687480|dbj|BAD80702.1| hypothetical p
-------------------------MAA--------------------------------
-----------------------------------IILAAITAI---AAIVLY-FVRRHY
RFKLQSLLL-AQPATSLQLKEI---AEHVAGEI-GG-GNLRQYVKMWGAI----------
EVEQ-PLVSE-LKQESCVYYCSTVSREYE--ERVRKE-------D-------SEGKVTW-
------------------------------------------------------------
-----------------------------T--TERRSETISQNRRSTPFYL-----RDQH
G-RVRVEPESAA--IATI-PVL-------DE-FRPDSSAS--SLIFGAFSLSLSTT--AG
LGKTLGYRYREEILPCDRSVLVVGAA----------------------------------
----------------------------SDETGELT--LGP-SSE-ARQQFFIALKPETA
LLQEVKQT-------IQWL-TIGAI---ASVVVTVVAAIAA-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-----L------------------
>Cyanobacteria gi|443316014|ref|ZP_21045478.1| E3 Ubiquitin ligase [Leptolyngbya sp. PCC 6406] >gi|442784396|gb|ELR94272.1| E3 Ubiquitin ligase [Leptolyngbya sp. PCC 6406]
--------------------------MA--------------------------------
-----------------------------------GIIGLILLI---GGIALF-FVQRHQ
KQKAFSLKI-ARKVTAAELNDT---ASGVAAEI-GG-GSWRDYVKVWGKI----------
QVDE-PLISE-HTRQKCVYYCSKVLREYE--DTTTER-------N-------SEGRLET-
------------------------------------------------------------
-----------------------------K--TQRKTETISSNKQSIPFTL-----VDDS
G-TVEVNPESAD--IETV-EVM-------NE-FRRET---------------------KG
RRNTLGYRYQESLLPLNRNILVLGAA----------------------------------
----------------------------SDLTGRVV--ISK-PTK-ADTKYVISLKDEET
LSAAVERN-------AKIS-FFSMV---ACGIVGILLVLWQ-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-----L--S---------------
>Cyanobacteria gi|428773069|ref|YP_007164857.1| hypothetical protein Cyast_1243 [Cyanobacterium stanieri PCC 7202] >gi|428687348|gb|AFZ47208.1| hypothetical protein Cyast_1243 [Cyanobacterium stanieri PCC 7202]
---------------------------M--------------------------------
-----------------------------------GIFGFIIVA---IALILF-FVKQAQ
TKSHSSVLL-ARFTDVQELEST---CQAITEDI-GG-GNWRDYVKLWGKI----------
TIDE-PLISE-MKQEPCVHYRMLVQREYE--EKVRSQ-------D-------SEGKTVE-
------------------------------------------------------------
-----------------------------K--TVRKSETITQNQRSIPFIL-----EDKT
G-AITINPEDAK--FDTI-KIL-------DE-FRPEQPAGG-MLQFGNFSFLVRNN--NY
HTRTLGYRYQEFILPIHREVLIVGNV----------------------------------
----------------------------SDETGSLK--ITK-PMD-N-QPFLISLKTEEE
LNSDYQKN-------QNIL-KYSMI---SCFVIGFILILVN-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------V-----I--T---------------
>Cyanobacteria gi|22298202|ref|NP_681449.1| hypothetical protein tll0660 [Thermosynechococcus elongatus BP-1] >gi|22294381|dbj|BAC08211.1| tll0660 [Thermosynechococcus elongatus BP-1]
---------------------------M--------------------------------
-----------------------------------GVLGGILLV---IAVLVL-CGWWDY
RLKVRALNL-AVSSTPAQLHEL---QRRVAQEI-GG-GYLQEYVKISGQI----------
VADR-PLVSE-LKRLPCVHYRLCVSRVYK--TTESHE-------D-------GSSE----
------------------------------------------------------------
--------------------------------TKYRHEILSSNTQTIPFRL-----RDGD
M-EIYVDPRGAE--IETV-QVL-------NE-FQEDNNTT--HLAFGRFQMDLSSL--PK
HSDTVGYRYEEWILPVNQQVFVVGTA----------------------------------
----------------------------SDERGKLR--IRR-PHQ-KGQLFFISLESEEN
LTKKVRQY-------ARAS-IIAAG---VFSGLGILLILL--------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Cyanobacteria gi|22297743|ref|NP_680990.1| hypothetical protein tll0199 [Thermosynechococcus elongatus BP-1] >gi|22293920|dbj|BAC07752.1| tll0199 [Thermosynechococcus elongatus BP-1]
---------------------------M--------------------------------
-----------------------------------GVFAHLCLT---GSAFLF-ALEGYY
RLQLRGIKV-ASPSTIGELEKF---QQQVAQEM-GS-GSWREYVQVVGQV----------
TTSQ-PLLSE-VKRIPCVYYKTIISREYE--KE---------------------------
------------------------------------------------------------
-----------------------------G--SDRPSEIIGRHEQSTLFLL-----RDHQ
G-EIEVNPFGAE--IEAV-QVL-------DE-LRPADQPHAFALSLGFLSFNWH----FG
KGTTLGYRYQEWVLPLGQPVSVVGMA----------------------------------
----------------------------SDQGGVLR--LQK-PQN-RGQKFIISLSFEDP
LIQQYKQQ-------KRKM-TYASL---GATLCGVCGLVLA-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-----F------------------
>Cyanobacteria gi|428774782|ref|YP_007166569.1| hypothetical protein PCC7418_0109 [Halothece sp. PCC 7418] >gi|428689061|gb|AFZ42355.1| hypothetical protein PCC7418_0109 [Halothece sp. PCC 7418]
---------------------------MAIFT----------------------------
-----------------------------------LIVGIILGL---ISGASY-LQYRKL
QEEFSAIIS-TETSTVEDLKKI---SEEVAEEL-GNTGYFRQQAEVKVTI----------
QCEN-PLTAN-LSHESCIYYQTVINERYE--KTEWVE-------D-------DEGNFEPN
------------------------------------------------------------
--------------------------------KSEGSKNLVNNFRCVDFFL-----EDDT
G-QILVNPDHGK--IEGV-QVY-------DY-YQPADSIDELEMSCGDIEIEFSPRN-DA
EYQTLGYQFQEVILPVNTQVYIIGEA----------------------------------
----------------------------SDRVGDLE--LHQ-PSE-ENQLFLISYKSEEE
LSEEKREDIKKNKKIAQLY-LFSAI---AFLIFALINLLN--------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Chloroflexi gi|159899427|ref|YP_001545674.1| hypothetical protein Haur_2908 [Herpetosiphon aurantiacus DSM 785] >gi|159892466|gb|ABX05546.1| hypothetical protein Haur_2908 [Herpetosiphon aurantiacus DSM 785]
---------------------------M--------------------------------
-----------------------------------VFFGIVLLI---AAVICF-FFARSQ
SNKLADLNA-TDTYTTQMLHDL---HKKVVETL-GA-EALAEPCEIEGQV----------
SCDN-PLVAP-ISGQTCIAYRFSLTREYS--EVVHDT-------D-------SEGRKRT-
------------------------------------------------------------
-----------------------------R--TQTGSETIKSEEECAYFWI-----NDNF
G-KVWVDPTDAE--IEYE-AGQ-------NI-LLPSPDKAS-ILHFGDFEFAAPASN-KG
ARRTTGYRAQEELFTDDGRAYILGCV----------------------------------
----------------------------TDDEGEPT--IAY-HEK-KLDRMLVSRKTERE
LANSAAGW-------SRNL-YYGAA---GSAVAGIIFTIWG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------LL-----------------------
>Chloroflexi gi|309792827|ref|ZP_07687269.1| hypothetical protein OSCT_3220 [Oscillochloris trichoides DG-6] >gi|308225139|gb|EFO78925.1| hypothetical protein OSCT_3220 [Oscillochloris trichoides DG6]
---------------------------M--------------------------------
-----------------------------------AIVGVILLI---VGVICF-FVARSK
ANALHAMNA-ADTYTAQLLAEV---HRKITSTL-GG-NGWAQPCEIEGII----------
ECDS-PLKGP-ISGQPCVAYYYTQSREYE--ERVTST-------D-------SDGKRET-
------------------------------------------------------------
-----------------------------T--VERRSEQLRSEDRRIKFYV-----RDET
G-KTLVMPEGAD--LDLL-ETG-------NR-FDQDEKPW------------------TG
ATRTLGQSHVEQSLAVGTKVYLLGCA----------------------------------
----------------------------VDREGSVA--VGKHPKD-SKHRFMISRKSEQE
LANSAAFW-------SRNL-YYAAA---ASGGLGLILVVLG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------M-------LG---------------
>Chloroflexi gi|163846705|ref|YP_001634749.1| hypothetical protein Caur_1130 [Chloroflexus aurantiacus J-10-fl] >gi|222524514|ref|YP_002568985.1| hypothetical protein Chy400_1238 [Chloroflexus sp. Y-400-fl] >gi|163667994|gb|ABY34360.1| hypothetical protei
---------------------------M--------------------------------
-----------------------------------IVGGVLLLV---LAVIFF-FVARAN
AGKLQALNA-VDTYDTATLSAI---HRRITTAL-GA-HDFAQPCEVMGLI----------
ECAT-PLTGP-VSGQALVAYLYTTHREYE--ERITTQ---------------ESGRSTT-
------------------------------------------------------------
-----------------------------R--IERRSEQLEQNERRVPFTI-----RDDT
G-QVLVVPDGAK--IDLI-ETA-------NR-FLETPQPW------------------TG
ATRTLGQRQFERGLEVGIRVFVSGTA----------------------------------
----------------------------IDQNGQVV--IARHPTN-SKQTFIISRKSEHE
LANSAATW-------ARNM-RYAAI---ASGVIGLALVVGG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------V-----LVSG---------------
>Chloroflexi gi|269838375|ref|YP_003320603.1| hypothetical protein Sthe_2360 [Sphaerobacter thermophilus DSM 20745] >gi|269787638|gb|ACZ39781.1| conserved hypothetical protein [Sphaerobacter thermophilus DSM 20745]
---------------------MGTSGVL--------------------------------
-----------------------------------LIIGLVAAG---IGAVLL-FIGRRI
QAKTDLLAK-VPTVDASEVASL----------------IPGEMIEVKGVI----------
RCDT-PLTAE-LAQRACVYYSSRVVREYE--YRRRNA-------K-------GETV----
------------------------------------------------------------
--------------------------------RSRRSETVAHNEQFTPFYV-----EDSS
G-RVLVDPEGAE--VDAQ-KLV-------DR-FERNPGALGPTISLGGISLNL-----GG
DDGTIGYRYQEHVLPVDIPVYVLGVV----------------------------------
----------------------------QEGGT-----IGRPPAALKGRRFIISYRAEEA
LRESWGKK-------ARWL-GISAV---ALFALAVILFVVA-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------VGMLVA-------------------
>Actinobacteria gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941] >gi|108766407|gb|ABG05289.1| conserved hypothetical protein [Rubrobacter xylanophilus DSM 9941]
---------------------MVGTVVF--------------------------------
-----------------------------------LLVGVVLCV---AGGVLL-YFRRRM
LGKAELMRR-TRTSGAAGVSAL----------------SPGTLVEVKGTL----------
RCER-PLQSE-MAKERCAYYSSKVVREYL--ERDRGD---------------GAPG----
------------------------------------------------------------
--------------------------------SGRRSEVLARSERFAPFVV-----EDDT
G-GVPVSAEGAE--VDAK-KVV-------DR-FERGAGAAGLSVTIGGATIDL-----GG
GERTLGYRHTEEILPVDAPVYVLGAV----------------------------------
----------------------------RRDGG-----IGP-PEE-GAGRFVVSWRSEEA
LGESLGRG-------ARLL-GLIAL---GLFLAGAAFLAVG-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AAAALGYLQFR---------------
>Chloroflexi gi|221632287|ref|YP_002521508.1| hypothetical protein trd_0254 [Thermomicrobium roseum DSM 5159] >gi|221156341|gb|ACM05468.1| conserved hypothetical protein [Thermomicrobium roseum DSM 5159]
---------------------------M--------------------------------
-----------------------------------IFVTLCFLITAGVGLVCL-IGYRRT
RQQLRLLRL-VATCPIAELHER----------------IPGEMVEITGTV----------
HCAT-PLRSE-YTGQPCVYYRTVTERVVE--RHGRSK-------K---------------
------------------------------------------------------------
--------------------------------GGRLSEVVAQNEQRIAFEV-----DDGT
G-RVAVDPVGAE--IDGR-KLL-------DR-FEPVENGEGATLRIAGMSVEVR----AA
EWRTLGYRKIEEAVLVGYPVYVLGVL----------------------------------
----------------------------QDDGS-----IGRPPEGSRLREFLISARSEEE
LATSLRRR-------SYLF-LAGAI---TSFVVAGMLLIA--------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------LLVQSVISIS---------------
>Bacteroidetes/Chlorobi_group gi|124004219|ref|ZP_01689065.1| conserved hypothetical protein [Microscilla marina ATCC 23134] >gi|123990289|gb|EAY29788.1| conserved hypothetical protein [Microscilla marina ATCC 23134]
-------------------------MAL--------------------------------
-----------------------------------VIIGVVLIA---IAVALW-FNRKRQ
LSKALNIKY-HETSKVADVVDI---YKQLGDGL-DG-SYRGNIVELSGMS----------
RSDS-PLQSE-HTNAEVVYYRARVIHEYETLEIVRQQ-------D-------DEGNYYE-
------------------------------------------------------------
-----------------------------REVVHNHQETVSDNERFAPFYL-----DDGS
G-RILVEMDKAQ--RHTI-TSL-------DE-YQPEPPTGYDPY--------------GI
RGTTTGYRYIEEIIPNNHKLYVLGQA----------------------------------
----------------------------AESHGNLA--VVK-PTK-KDEEFIVSTKSEEE
LVQGAENS-------AKMS-LYGAI---GLGILGLILMVVG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------FTSKG----G---------------
>Actinobacteria gi|348176796|ref|ZP_08883690.1| hypothetical protein SspiN1_40700 [Saccharopolyspora spinosa NRRL 18395]
---------------------------MAV------------------------------
-----------------------------------IIIGVVLLV---AAAVGF-YFMRRA
RDELHAMIG-AETLPVNQLELL----RKASDDV-GARGGFRKECEVVGAAHP--------
RPEG-VLISE-LSKTVCVWFRYVVKRRYE--RVRYRD---------------GRRH----
------------------------------------------------------------
--------------------------------VDRGSETVAEHTSWEGYAL-----RDDH
SVLIGVDPNGTK--PDRPEQVV-------DR-FEPHNPQGPTV--FGFQLPNI-----LD
NSGTVGYEYKEWVIRPGRRLYILGEV----------------------------------
----------------------------HDKIGPLV--IGK-PEQ--KGFFIISTRSEQE
VRDSLRTQ-------HRLL-AFGIP---AAALAAIVCIVLG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------I-------VL---------------
>Actinobacteria gi|384564441|ref|ZP_10011545.1| E3 Ubiquitin ligase [Saccharomonospora glauca K62] >gi|384520295|gb|EIE97490.1| E3 Ubiquitin ligase [Saccharomonospora glauca K62]
---------------------------M--------------------------------
-----------------------------------WIAGVVLLV---VAVAAF-FYMKHT
RDELHAMIG-TETFSIPELERY----RAASDEL-GGKGAFRKTAEVVGAAHP--------
RPEG-PLTAE-LSKVECVWYRYRIDRHYE--VIEYRD---------------GKRY----
------------------------------------------------------------
--------------------------------RRKRTERVAEHTSHEGYAL-----IDDE
GRTIGVDPNGTN--PDGVEQTV-------SR-FEPHRGQQGSIELFGIKLPALF----GR
GDSTIGYDYKEWVIRPGQRLYILGEV----------------------------------
----------------------------HDRIGPLV--IGK-PRE--KGHFIISTRTEEE
LRQLRVRR-------HKFL-AIGTV---ASTVVGLGLIVAD-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-------FV---------------
>Actinobacteria gi|381164333|ref|ZP_09873563.1| superfamily II DNA helicase [Saccharomonospora azurea NA-128] >gi|418462936|ref|ZP_13033969.1| hypothetical protein SZMC14600_18329 [Saccharomonospora azurea SZMC 14600] >gi|359735029|gb|EHK83994.1| hypothetical protein SZ
---------------------------M--------------------------------
-----------------------------------WIVGVVLLV---VAVGAF-FYMKHT
RDELHAMIG-TETLSIPELERY----RGASDEV-GGTGAFRKTAEVVGAAHP--------
RPEG-TLTAE-LSKTECVWYRYRIDRHYE--VIEYRD---------------GKRH----
------------------------------------------------------------
--------------------------------RRKRTERVAEHTSHEGYAV-----IDNE
GRTIGVDPNGTK--PDGVEQTV-------SR-FEPHRDGGGGVDLFGIRLPALF----GR
SDSTIGYDYKEWVIRPGQRLYILGEV----------------------------------
----------------------------HDRIGPLV--IGK-PSE--KGHFIISTRTEEE
LRASRVQR-------HKLL-AAGTV---ASCVVGLGLLVGG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-------FT---------------
>Actinobacteria gi|375098891|ref|ZP_09745154.1| superfamily II DNA helicase [Saccharomonospora cyanea NA-134] >gi|374659623|gb|EHR59501.1| superfamily II DNA helicase [Saccharomonospora cyanea NA-134]
------------------------------------------------------------
---------------------------------------MLLLI---VAVGAF-FYMKHT
RNELHAMIG-TETLSIPELEQY----RSASDGL-GATGTFRKLSEVVGAAHP--------
RPEG-PLTAE-LSKVECVWYRYRIDRHYE--VIEYRD---------------GKRH----
------------------------------------------------------------
--------------------------------RRKRTERVAEHTSSEGYAV-----IDAE
GRTIEVDPNGTE--PDGVEQTV-------SR-FEPHGGKEGGVELFGIALPALL----GR
GDSTIGYDYKEWVIRPGRRLYVLGEV----------------------------------
----------------------------HDRTGPLV--IGK-PAG--KGHFIISTRTEQE
LRDSRVQR-------HKLL-AIGTV---ASTLLGLGLLVGG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-------FT---------------
>Actinobacteria gi|257054548|ref|YP_003132380.1| hypothetical protein Svir_04780 [Saccharomonospora viridis DSM 43017] >gi|256584420|gb|ACU95553.1| hypothetical protein Svir_04780 [Saccharomonospora viridis DSM 43017]
---------------------------M--------------------------------
-----------------------------------WIVGVVLLI---VAVVAF-FYMKHT
RSELHAMIG-TETLSIPQLEQY----RQASDEV-GGRGAFRKTAEVVGAAHP--------
GPHG-PLKAE-LSKTECVWYRYRIDRHYE--VIEYRD---------------GKRH----
------------------------------------------------------------
--------------------------------RRKRTERVAEHTSAQNYAV-----IDEE
GRTIGVDPNGTK--PDSVEQTV-------SR-FEPHRGNSQSIELFGFKLPTML----GR
GDSTIGYDYKEWVIRPGQRLYILGEV----------------------------------
----------------------------HDRFGPLM--IGK-PAQ--GGHFIISTRTEEE
LRASRVKR-------HKLL-AITVI---TSFVLGWVLLIAD-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-------LR---------------
>Actinobacteria gi|383829039|ref|ZP_09984128.1| E3 Ubiquitin ligase [Saccharomonospora xinjiangensis XJ-54] >gi|383461692|gb|EID53782.1| E3 Ubiquitin ligase [Saccharomonospora xinjiangensis XJ-54]
---------------------------M--------------------------------
-----------------------------------WIAGVVLLV---VAVAAF-LSMKHT
RDQLHTMIG-TETLSIPELEQY----RAASDEV-GASGMFRKTSEVVGEASP--------
SPDG-PLTAE-LSKTECVWYRYRIDRHYE--VIEYRD---------------GKRH----
------------------------------------------------------------
--------------------------------RRKRTERVAEHTSHKNYAI-----TDEQ
GRTINVDPDGIT--PDGAEQTV-------SR-FEPRRGRQGGIDLFGIVLPALS----GR
GDTTIGYDYKEWVVRPGRRLYVLGEV----------------------------------
----------------------------HDRTGALT--IGK-PEG--KGHFIISTRTEQE
LRDSRVRR-------HRLL-AIGTV---ASALGGLGLLVAG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-------FT---------------
>Actinobacteria gi|354613574|ref|ZP_09031488.1| hypothetical protein SacpaDRAFT_0895 [Saccharomonospora paurometabolica YIM 90007] >gi|353222061|gb|EHB86385.1| hypothetical protein SacpaDRAFT_0895 [Saccharomonospora paurometabolica YIM 90007]
---------------------------M--------------------------------
-----------------------------------WVLGVSVLA---VTAGAY-FAMRHT
RRELHAMIG-TETLSIQQLEQL----RDVSVEL-GGKGDLRRTVQVVGAAHP--------
GPDG-ALTAE-LSKAECVWFHYRVDRHYE--IIEHGE---------------FRR-----
------------------------------------------------------------
--------------------------------RKKRSENVIDHVSREKYAL-----VDEE
GRTVLVEPGDTE--PDGVEQSV-------HR-FEPVRSATGEIDLESLTPDSSS----GH
SEITVGYQYTEWSLRPGTRLHVLGEV----------------------------------
----------------------------EDTFGPLT--IRG-PGQ--GGHFVISTRPGNE
LRAERRKL-------HTGL-AVGVV---IGAVLGVGLVVGG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-------VT---------------
>Actionobacteria gi|325002910|ref|ZP_08124022.1| hypothetical protein PseP1_29285 [Pseudonocardia sp. P1]
---------------------------M--------------------------------
-----------------------------------LWIGIIALL---AGAGCF-WAAVHT
QRRVHAMMA-AETLPVPRLLEE----AGIAADLNGGPGRFRKVCEVVGEAAP--------
APVG-LLRSE-LAGVECVWHAHRVERRFE--RRERDS-------E-------GRMR----
------------------------------------------------------------
--------------------------------TSTHTETVSERVSPHGWPL-----LRD-
GHTIGVDPGGRR--PDPVELVL-------DR-FDPADERG------------------PR
GDRTLGYRNQEWVLRPGVRMYVLGEV----------------------------------
----------------------------DDRDGPLV--IRA-PQD-TSHPFVLSTRTEDE
LTATDRRS-------QRWW-ARGGA---ALVLLGLVLTIAG-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------A-------VT---------------
>Actinobacteria gi|331695440|ref|YP_004331679.1| hypothetical protein Psed_1589 [Pseudonocardia dioxanivorans CB1190] >gi|326950129|gb|AEA23826.1| hypothetical protein Psed_1589 [Pseudonocardia dioxanivorans CB1190]
---------------------------M--------------------------------
-----------------------------------WVIGVVVVL---VGAGFL-WSAVRA
QRSVHAMLA-AETLSVPELEEL----RRVSDDL-GARGSFRKVCEVVGAAHP--------
SPEG-VLRSE-LSGVECVWHSHRVQRRYK--HYDRDR-------D-------GSTR----
------------------------------------------------------------
--------------------------------VTTRTETVAEQTSGPGFAL-----LRD-
GRTIGVDHAGRR--PDGVEQVT-------DR-FEQTQEPSNGWADVVGALVG------SD
RDETIGYQYTEWVLRPGTPMYVLGEV----------------------------------
----------------------------HDAIGPLV--IAP-PAD-PKQPFVMSTSTEQQ
LTDAARGR-------QRFR-SRLGA---ALVVVGIVVVVLA-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L-------VL---------------
>Chloroflexi gi|309791495|ref|ZP_07685998.1| hypothetical protein OSCT_1949 [Oscillochloris trichoides DG-6] >gi|308226464|gb|EFO80189.1| hypothetical protein OSCT_1949 [Oscillochloris trichoides DG6]
---------------------------MFMFF----------------------------
-----------------------------------LVLTLTLAL---AGIITA-IIAWRG
ESHIIAMRE-TETLYIAQVIEQ------------HRQGRLGQTVEVVGTS----------
ECDV-PLRAP-YSSELCLAFEYTVNEEHE--RTERVR-------SLAPTHRFDLGHAAGR
------------------------------------------------------------
--------------------------------EISSHHLNIHAERVPRFYV-----HDAS
G-RIAVETQGAK--IDLI-EGM-------AR-FESYTG--------------------TL
NDVEREIWREEYNLPVGNRVYVLATL----------------------------------
----------------------------GDVNGEPV--LMRHPVD-PKRSFLISHRDEQS
YIKHTSIR-------TYGLYILSGVLISAAVISGLLLMWKG-------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Cyanobacteria gi|86607674|ref|YP_476436.1| hypothetical protein CYB_0172 [Synechococcus sp. JA-2-3B'a(2-13)] >gi|86556216|gb|ABD01173.1| conserved domain protein [Synechococcus sp. JA-2-3B'a(2-13)]
---------------------------MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARI
RDCLKLLLNPVSQVTASMRPTSLPPPERKAFMNWLMLLGLLCLP---ASLFSF-VEYLRS
QRLVQQLSA-TRLLKIAELRHL---GQTNPQAK-GA-----NLAQVYGRV----------
VCDR-PLVSE-LSRQPCVYYKSEISWEYD--EIECYRRYLNSRGDVAYSERISEGEYQNA
LRLGSRAKSYPGEMVGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPNPGYPQQLGSPGYPQ
KSPFSEVSSPQKHYANVYYDPSTGREYLLERETRTRDETLHSVVRQIPFFI-----EDET
G-RVRVDPTGAE--IEAM-SVV-------DEHIFPGKGPSRFNFNLKRYLSGVR----TE
NRSTRAFIYKEWVIPVDAMAFTMGQV----------------------------------
----------------------------RFEAGDPV--IRK-PLS--GERFMIAPKSPEA
LLEEQRSN-------ASSY-LVGSV---VLLGIGIFTVLHL-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------L--QSLQPYR---------------
>Thermotogae gi|239616922|ref|YP_002940244.1| LemA family protein [Kosmotoga olearia TBF 19.5.1] >gi|239505753|gb|ACR79240.1| LemA family protein [Kosmotoga olearia TBF 19.5.1]
---------------------------MQFV-----------------------------
-----------------------------------LLIGFVVML---LCVLFA-MQNLKK
KRLIDDTPT-SKVK-----------------------GVFIGLVELKGKV----------
KTTR-PLTSY-LTEKPCVYYRWSIEEHWTKRTTETYT-------D-------SHGKTRT-
------------------------------------------------------------
-----------------------------RTKTESGWKTVASGGDEIPFEL-----CDDT
G-CILIRPEKAR--VEAI-TVM-------NR-VCGRSDPLYYGKGPDR----------AI
MYSDHRRRFVERIIPPDADLYVFGQA----------------------------------
----------------------------REREDIVAPEVAY-DKE--APMFLISTREEKK
LSRRYSLY-------YWLLVAVG-I---IAAIATAYFSIDRTFS--LPQEPIQPYIVTIG
SFLVMLFIGWFWVTHNSLKSLQRRVQQGWSQIEVQLKRRHDLIPLLVNVVKGLVKHEQDT
QEKLAELRGELENM----------SGKEVLKVLIERYPNLKSQEAFIKLQKELSDTENRI
ALARGYYNEIASFYNARLERFPDLIVAKLGRLKHQRLWKQ----------------
>Thermotogae gi|389844132|ref|YP_006346212.1| hypothetical protein Theba_1281 [Mesotoga prima MesG1.Ag.4.2] >gi|387858878|gb|AFK06969.1| hypothetical protein Theba_1281 [Mesotoga prima MesG1.Ag.4.2]
---------------------------MDYSSIV--------------------------
-----------------------------------RLIGVGLSL---LMLLFS-FRSYRR
KRLIDDMPT-SKAH-----------------------GVFIGLVEVSGKV----------
ECQN-PITSY-LTESTCVQYSWEISEHWSKTTTETYT-------D-------SKGKTRT-
------------------------------------------------------------
-----------------------------RTKRESGWKTVASGESMCPFDL-----RDET
G-TIQIRPEKAK--IEGV-RAM-------DL-RCRSSDPLYYGKGPAE----------SI
IHSDHLRMFTESIIPLDARVYVIGQS----------------------------------
----------------------------REREDIVAPEIAH-DES--SPLFLISTREEER
ISKSYSLN-------YWLL-SLGGL---GVSLISFFIASRIGFYRWIPS-GVSDYFMPTG
IYLGLWLIGWFWTTFNSLKSLRERVRQGFSQLEVQLKRRHDLIPRLSSAVSSLMKHEQSI
QTKIAALRSEAAVN---------AKAAKRLLVLVEDYPELKSSEAVSRLQRELSDTENRL
ELARAYYNNIATFYNTRLERIPDNVVATLARLKNCELLLQSEGD--------GDSK
>Chloroflexi gi|57235080|ref|YP_180857.1| hypothetical protein DET0106 [Dehalococcoides ethenogenes 195] >gi|57225528|gb|AAW40585.1| lemA family domain protein [Dehalococcoides ethenogenes 195]
---------------------------MEFQIW---------------------------
-----------------------------------GYLVFALSL---VALVLA-FRVMRR
KRLVDDIPT-SRTQ-----------------------EVFIGLVELKGRA----------
ESEN-PFTGF-LSAKKCVYYHYKVEEHWSRLVTETYT-------D-------AKGHVGV-
------------------------------------------------------------
-----------------------------RTRQESGWTQVASGKEMQPFYL-----KDET
G-IILIQPEGAD--IQPQ-TLF-------DQ-TCGRSDPLYYAKGPQG----------SI
ANSDHRRRFTEEAIPLHAELYIMGQS----------------------------------
----------------------------RERGDIVAPEIAK-DKS--APMYVISTRTEKQ
ISRSYSGW-------FWFWIILG-L---LVSLGSGLLLSQQGAEGFNPG--WGAV-WWLG
FYLFGWLLGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVAGFSKHEHEL
QEMLAEVRTISKVN--GQDTTDIRSASAILVFNMEKYPELKADTLFLKLQEELAATESRI
ALARDYYNSIATFYNTRREIFPDRLLAGIFGFKERVLINASDLERTAPEVKLAE--
>Chloroflexi gi|270307560|ref|YP_003329618.1| LemA domain-containing protein [Dehalococcoides sp. VS] >gi|270153452|gb|ACZ61290.1| LemA domain protein [Dehalococcoides sp. VS]
---------------------------MELQIW---------------------------
-----------------------------------GYPVFALGL---TALVLA-FRTMRR
KRLVDDIPT-SRTR-----------------------GVFIGLVELKGTA----------
ESEK-PFTGF-LSAEKCVYYHYKVEERWSRMVTESYT-------D-------AKGHVQF-
------------------------------------------------------------
-----------------------------RTHQESGWTQVASGKEMQPFYL-----KDET
G-IILIQPEGAD--IQPK-NLF-------NK-TCGRNDPLYYAKGPQG----------SV
ANSDHQRRFTEEAIPLHAELYIMGQS----------------------------------
----------------------------RERQDVVAPEIAK-DKS--APLYVISTRTEKQ
ISRSYSGW-------FWFWIILG-L---LISLGSGLLLSQQDKESFNPD--WGIVALWSG
FYLLSWLLGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFSRHEREL
QEMLAELRTVSKVN--GQDTMDIKGASAILVFNMEKYPELKADTVFLKLQEELAATESRI
ALARDYYNSIATFYNTRREIFPDRLLAGIFGFKERVFINASELERAALKVKLAE--
>Chloroflexi gi|73748061|ref|YP_307300.1| hypothetical protein cbdb_A126 [Dehalococcoides sp. CBDB1] >gi|73659777|emb|CAI82384.1| lemA family domain protein [Dehalococcoides sp. CBDB1]
---------------------------MEFQIW---------------------------
-----------------------------------GYLVFVLGL---AALALA-FRTMRR
KRLVDDIPT-SRTH-----------------------GVFIGLVELKGTA----------
ESEK-PFTGF-LSAEQCVYYYYKVEERWSRMVTESFT-------D-------AKGHVQF-
------------------------------------------------------------
-----------------------------RTRQESGWTQVASGKEMQPFYL-----KDET
G-IILIQPEGAD--IQPK-NLF-------NR-TCGQNDPLYYAKGPQA----------SI
PNSDHQRRFTEEAIPLHAGLYIMGQS----------------------------------
----------------------------RERQDIVAPEIAK-DKS--APLYVISTRTEKQ
ISRTYSGW-------FWFWVGLG-L---LLASGSGLLLSQESTSGFNPD--FGVAVLWLG
LYLICWLFGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFGKHEREL
QEMLAEVRTISKVN--GQYPKDIQGASAILVFNMERYPELKADTLFLKIQEELAATESRI
ALARDYYNSIATFYNTRREVFPDRLLAGIFGFKERVLINASALERAVVKVKLAE--
>Chloroflexi gi|289432088|ref|YP_003461961.1| LemA family protein [Dehalococcoides sp. GT] >gi|288945808|gb|ADC73505.1| LemA family protein [Dehalococcoides sp. GT]
---------------------------MEFQIW---------------------------
-----------------------------------GYLVFVLGL---AALALA-FRTMRR
KRLVDDIPT-SRTH-----------------------GVFIGLVELKGTA----------
ESEK-PFTGF-LSAEQCVYYYYKVEERWSRMVTESFT-------D-------AKGHVQF-
------------------------------------------------------------
-----------------------------RTRQESGWTQVASGKEMQPFYL-----KDET
G-IILIQPEGAD--IQPK-NLF-------NR-TCGQNDPLYYAKGPER----------SI
PNSDHQRRFTEEAIPLHAGLYIMGQS----------------------------------
----------------------------RERQDIVAPEIAK-DKS--APLYVISTRTEKQ
ISRTYSGW-------FWFWVGLG-L---LLASGSGLLLSQESTSGFNPD--FGVAVLWLG
LYLICWLFGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFGKHEREL
QEMLAEVRTISKVN--GQDPKDIQGASAILVFNMERYPELKADTLFLKIQEELAATESRI
ALARDYYNSIATFYNTRREVFPDRLLAGIFGFKERMLINASALERAVVKVKLAE--
>Chloroflexi gi|147668909|ref|YP_001213727.1| LemA family protein [Dehalococcoides sp. BAV1] >gi|146269857|gb|ABQ16849.1| LemA family protein [Dehalococcoides sp. BAV1]
---------------------------MEFQIW---------------------------
-----------------------------------GYLVFVLGL---AALALA-FRAMRR
KRLVDDIPT-SRTH-----------------------GVFIGLVELKGTA----------
ESEK-PFTGF-LSAEQCVYYYYKVEERWSRMVTESFT-------D-------AKGHVQF-
------------------------------------------------------------
-----------------------------RTRQESGWTQVASGKEMQPFYL-----KDET
G-IILIQPEGAD--IQPK-NLF-------NR-TCGQNDPLYYAKGPQA----------SI
PNSDHQRRFTEEAIPLHAGLYIMGQS----------------------------------
----------------------------RERQDIVAPEIAK-DKS--APLYVISTRTEKQ
ISRTYSGW-------FWFWVGLG-L---LLASGSGLLLSQEGTSGFNPD--FGVAVLWLG
LYLICWLFGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFGKHEREL
QEMLAEVRTISKVN--GQDPKDIQGASAILVFNMERYPELKADTLFLKIQEELAATESWI
ALARDYYNSIATFYNTRREVFPDRLLAGIFGFKERVLINASALERAVVKVKLAE--
>Chlamydiae/Verrucomicrobia_group gi|182414263|ref|YP_001819329.1| LemA family protein [Opitutus terrae PB90-1] >gi|177841477|gb|ACB75729.1| LemA family protein [Opitutus terrae PB90-1]
---------------------------MDGSN----------------------------
-----------------------------------PLPVVLCGVAAGAFLLGS-LHLRRK
QRLLHDLPT-SKTQ-----------------------GVFIGLVEVAGTA----------
ESSA-PLRGY-LSGATCVHFDYEVQEHWSRTVTETYT-------D-------KEGKSRT-
------------------------------------------------------------
-----------------------------RTRHESGWTTVAHGGETQDFYL-----RDDT
G-AVLIRPAGAK--VEAQ-TLF-------EQ-TVNRGDPLYYAKGPDH----------AV
ANSDHRRRFVERGLALHTSLYVVGQA----------------------------------
----------------------------RERADVVAPEIAQ-DRN--APLFLISTRTERS
VQTRLAVG-------SWVCWALG-L---VAAVGAALFAMQN-----LPPGSFAPLAIALG
GYLGGWALGWTWMVFNSLVSLRNRVRQAWSLIEVQLKRRHDLLPSLTSVVSALSTHERST
QTAVSALRSQIQATPPGVAGPDFAGVAAALRGVAEAYPELTAQDSFARLQRELVTTEQRI
ALARSYYNDIATQFATRLERIPDGWVARLAAMKPQPLLAAADFERARVDVQFADAA
>gi|345864169|ref|ZP_08816373.1| hypothetical protein TevJSym_ak00400 [endosymbiont of Tevnia jerichonana (vent Tica)] >gi|345124700|gb|EGW54576.1| hypothetical protein TevJSym_ak00400 [endosymbiont of Tevnia jerichonana (vent Tica)]
---------------------------MHHDILTMPELTFWI------------------
-----------------------------------WVNSLALLC---LAALWFAFRNLSR
ARIIEDTPT-SLIR-----------------------SAHQGYVELNGTAA---------
TMQGEPILTP-LTHVPCCWYRYRIERRHE-------------------------------
------------------------------------------------------------
----------------------------------KGWRTSQQGSSDGLFLI-----KDPT
G-QCIIDPDGAQ--ITPSERQVWYGGSSFAT-AMPARSGGSSLAGLFSAALSLG----GQ
GHLGEHYRYTEETIYPGDPLYAIGLFKSFDETDRQALIKAHASDLLRQWKQDHPELLARF
DRNGDSRIDLDEWDQARRQAHRQATREEAAADRQNLHTLSNTGTS--RRPFIISSHAEFK
LVTRYKR-----------------I---AFAAISSFFSPAASPAGCSASDCSAELC----
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Proteobacteria gi|410692675|ref|YP_003623296.1| conserved hypothetical protein; putative membrane protein [Thiomonas sp. 3As] >gi|294339099|emb|CAZ87453.1| conserved hypothetical protein; putative membrane protein [Thiomonas sp. 3As]
---------------------------MLSGLSPSGAAPQV-------------------
-----------------------------------LFMALALGA---VGLVQF-FRLQRR
RRVMEDMPT-ARIR-----------------------SAAQGYVELIGRAL---------
PPDA-PLFSP-ITRTPCCWYRYKIEKRDD---------------D---------------
------------------------------------------------------------
--------------------------------NKNSWSVQEQGKSTTQFWL-----DDDT
G-RCIVDPEGAE--VRARSRNTWTGAA--AQ-LIPGTSE-------------------VL
MTGDSDHRYTEHLILPGQTLYALGWF--ASLSPLQASAHEEVRERIAAWKAD-PQKRRSF
DANADGELSMAEFEQLRQQAAAAVEADRRERAALPQTHVLKKPKD--RRLFLLTTEPHDD
LGGKLRWQ-------AWAWLAAGVL---GLAYGGAGLMMLV-------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Proteobacteria gi|296135054|ref|YP_003642296.1| hypothetical protein Tint_0566 [Thiomonas intermedia K12] >gi|295795176|gb|ADG29966.1| conserved hypothetical protein [Thiomonas intermedia K12]
---------------------------MLSGLSPSGAAPQV-------------------
-----------------------------------LLMALALGA---VGLVQF-FRLQRR
RRVMEDMPT-ARIR-----------------------SAAQGYVELIGRAL---------
PPDA-PLFSP-ITRTPCCWYRYKIEKRDD---------------D---------------
------------------------------------------------------------
--------------------------------NKNSWSVEEQGKSTTQFWL-----DDDT
G-RCIVDPEGAE--VRARSRNTWKGAA--AQ-LIPGTSE-------------------VL
MTGDNDHRYTEHLILPGQTLYALGWF--ASLSPLQASAHEEVRERIAAWKAD-PQQRRSF
DANADGELSMAEFEQLRQRAAAAVEAERRERAAQPQTHVLKKPKD--RRLFLLTTEPHDA
LSGKLCWQ-------AWAWLAAGVL---GLAYGGAGLLMRV-------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Mulan_NP_078820
---------------------------MESGGRPSLCQF---------------------
-----------------------------------ILLGTTSVV---TAALYS--VYRQK
ARVSQELKG-AKKVHL---------GEDLKSILSEAPGKCVPYAVIEGAV----------
RSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTTHL-----------------------
------------------------------------------------------------
--------------------------------WNDCSKIIHQRTNTVPFDLVPHEDGVDV
AVRVLKPLDSVD--LGLE-TVY-------EK-FHPSIQSFTDVIGHY-----------IS
GERPKGIQETEEMLKVGATLTGVGEL----------------------------------
----------------------------VLDNNSVR--LQP-PKQ--GMQYYLSSQDFDS
LLQRQESS-------VRLW-KVLAL---VFGFATCATLFFI-------------------
-------------------------------------------LRKQYLQRQERLRLKQM
QEEFQEHEAQLLSRAKPEDRESLKSA----------------------CVVCLSSFKSCV
FLECGHVCSCTECYRALPE--PKKCPICRQAITRVIPLYNS---------------
>SP1_NM_105064_AT1G63900
---------------------------MI-------------------------------
-----------------------------------PWGGVTCCL---SAAALY-LLGRSS
GRDAEVLETVTRVNQLKELAQLLELDS----------KILPFIVAVSGRV----------
GSET-PIKCE-HSGIRGVIVEETAEQHFLKHNETGS------------------------
------------------------------------------------------------
--------------------------------WVQDSALMLSMSKEVPWFL-----DDGT
S-RVHVMGARGA--TGFALTVG-------SEVFEESGR-SLVRGTLDY----------LQ
GLKMLGVKRIERVLPTGIPLTIVGEA----------------------------------
---------------------------VKDDIGEFR--IQK-PDR---GPFYVSSKSLDQ
LISNLGKW-------SRLY-KYASM---GFTVLGVFLITKH-------------------
------------------------------------------------VIDSVLER----
--RRRRQLQ-KRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAV
FVPCGHMCCCTACSSHLTS-----CPLCRRRIDLAVKTYRH---------------
>SPL1_NP_564745_AT1G59560
---------------------------MI-------------------------------
-----------------------------------HLAGFTCCL---GGVALY-LLTRST
GRD---IKSITRVYQLKDLEQLVEVES----------KVVPLIIAVSGDV----------
GSET-PIKCE-HSYVLGVFLKRTAEQQVLRRNWRFS------------------------
------------------------------------------------------------
--------------------------------WVRNSTLMQPMTKEVPWYL-----DDGT
G-RVNVDVSQGE--LGLALTVG-------SDVFEKAEPVSLVQGALGY----------LK
GFKILGVRHVERVVPIGTPLTVVGEA----------------------------------
---------------------------VRDGMGNVR--IQK-PEQ---GPFYVTYIPLDQ
LISKLGDL-------SRRF-KYASM---GLTVLGVILISKP-------------------
------------------------------------------------VIEYILKRIEDT
LERRRRQFALKRVVDAAARRAKPVTGG----------GTSRDGDTPDLCVVCLDQKYNTA
FVECGHMCCCTPCSLQLRT-----CPLCRERIQQVLKIYRH---------------
>SPL2_NP_564653_AT1G54150
---------------------------MSSPERALLNLLTDIALSFDG------------
-----------------------------------AILGLTLAV---SAVGSA-LKYAST
NAALKKIKD-APEVSISDLRSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGY
KNNN-VLISP-ETGDKALIIQRTQTYVYSGWKRLFQSTGHRFMLE---------------
------------------------------------------------------------
---------------------------------RSLRKHGADFTRTVPFVIVGKDQQSNS
S-FVAVNMDGSRQPLPLT-TVY-------NR-LQPINSSFLQAF--------------LY
PDYPVGLLDIEKILPPGKDITAVGIY----------------------------------
----------------------------SFNNGVPE--IKS-CQD---LPYFLSEMTKDK
MIEDLMEQ-------TNFI-FLGSV---ILGIVSVGILSYA-------------------
-----------------------------------------------AVRTWNKWKQWNH
QRELPQRPNDSVVDDEPEDADEIPDG--------------------ELCVICVSRRRVPA
FIPCGHVVCCRRCASTVERELNPKCPVCLQSIRGSMRVYYS---------------
