>Cyanobacteria gi|158336842|ref|YP_001518016.1| hypothetical protein AM1_3710 [Acaryochloris marina MBIC11017] >gi|158307083|gb|ABW28700.1| conserved hypothetical protein [Acaryochloris marina MBIC11017]
---------------------------MKIIGIILIV---IGIILFFVYSNLKRKLASLR
QARPASI-AELNHLASEIALEM----GS-GSWRDYVKLRGTI----------QCDQPLIS
ELKQMPC--VHYNMTVVREYE--EQVTERDSDDKVVTK--TQRGSETLSQNRESVPFFL-
----QDDTGE-IWVEPEGAQIET--VRVLDEFSPEQPSGG-QLSFGGFSLSL--SSA-ET
GRQTIGYRYQESVLPVQRQVFVVAQVS-DFNQSLVLEN-PTT-KGQRFVISLKSEEALAQ
TTQTS-------VTYAFYGMISTLVVGGLLVIFG--------------------------
------------------------------------------------------------
-----------------L-----L-SA
>Cyanobacteria gi|359460153|ref|ZP_09248716.1| hypothetical protein ACCM5_15608 [Acaryochloris sp. CCMEE 5410]
MQEPQSSISSDVGQNQSILGPTGVQASMKIIGIILIV---IGIILFFVYSNLKRKLASLR
QARPASI-AELNHLASEIALEM----GS-GSWRDYVKLRGTI----------QCDQPLIS
ELKQMPC--VHYNMTVVREYE--EQVTERDSDDKVVTK--TQRGSETLSQNRESVPFFL-
----QDDTGE-IWVEPEGAQIET--VRVLDEFSPEQPSGG-QLSFGGFSLSL--SSA-ET
GRQTIGYRYQESVLPVQRQVFVVAQVS-DFNQSLILEN-PTT-KGQRFVISLKSEEALAQ
TTQTS-------VTYAFYGMISTLVVGGLLVIFG--------------------------
------------------------------------------------------------
-----------------L-----L-SA
>Cyanobacteria gi|220906503|ref|YP_002481814.1| hypothetical protein Cyan7425_1067 [Cyanothece sp. PCC 7425] >gi|219863114|gb|ACL43453.1| conserved hypothetical protein [Cyanothece sp. PCC 7425]
-------------------------MGLAIVGAILLV---TGGILYFVQRHYQQKLYSIK
LARKTTV-AELKQLADQVGAEI----GQ-GSLREYVKLSGQI----------KCDTPLIS
ELKQVPC--VYYQMQVEREYE--ERLTERDNDGETREK--TQRGSETIASNSQSTPFFL-
----QDQSGA-IEVDPSGAAIET--VQVLNEFRPEAGSA--RISFGNFSLSV--GGSFPA
GRETIGYRYRESILPPDRRILIVATAS-DSSGILSLQK-PVE-KRQKFIISLKSEDHLAQ
STQQT-------ATYTFYGMIACLGLGAILLVVG--------------------------
------------------------------------------------------------
-----------------L-----I-IR
>Cyanobacteria gi|427714017|ref|YP_007062641.1| E3 Ubiquitin ligase [Synechococcus sp. PCC 6312] >gi|427378146|gb|AFY62098.1| E3 Ubiquitin ligase [Synechococcus sp. PCC 6312]
---------------------------MLFVSAILLI---AAVVLFFVQRHYRLRLRSLK
LANRVNS-QSIKQLAADVATEI----GA-GSLREYVKLYGRV----------KSDDPLIS
ELKQVPC--VYYSMQVIREYE--ERVRSEDSEGRTEWR--TERRSDTISSNSQSTPFLL-
----QDAQGT-VRIDPEGAGVET--IQVLNEFRPEGNSN--RLSFGGFSLNLDIAVG-SG
GGRTLGYRYQESILPLERQVLIVGEAS-DQTGELVIGK-PQQ-NGRKFFISLKSEDTLTN
HTQNI-------MTYTTLGAIASGVIGVLVGILG--------------------------
------------------------------------------------------------
-----------------L-----V--S
>Cyanobacteria gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424] >gi|218172398|gb|ACK71131.1| conserved hypothetical protein [Cyanothece sp. PCC 7424]
---------------------------MILIGIICLI---VGVILLFFWRSNRSKLRNLR
LASASTI-SSLQTIANQIAEEI----GG-GSLREYVKIRGVI----------ECDRPLIS
QLKQEPC--VYYSMTVTWEYN--EEVIKQDNEGKTIRE--KERKSETVAQNSRSIPFTL-
----QDSTGE-IRVNPERAEIET--VKVLEEFRPENFSGG-SLTFGNFSINL--PSF-EE
RRQTIGYRYQEEILPIGRQILVIGTAT-DEEGMITIRK-PTE-KGQRYFISLKSEEELSQ
ATNNA-------IRGTFYSMIFFLTLGLILLVAG--------------------------
------------------------------------------------------------
-----------------V-----L-RG
>Cyanobacteria gi|56752521|ref|YP_173222.1| hypothetical protein syc2512_d [Synechococcus elongatus PCC 6301] >gi|81300335|ref|YP_400543.1| hypothetical protein Synpcc7942_1526 [Synechococcus elongatus PCC 7942] >gi|56687480|dbj|BAD80702.1| hypothetical protein [Synech
-------------------------MAAIILAAITAI---AAIVLYFVRRHYRFKLQSLL
LAQPATS-LQLKEIAEHVAGEI----GG-GNLRQYVKMWGAI----------EVEQPLVS
ELKQESC--VYYCSTVSREYE--ERVRKEDSEGKVTWT--TERRSETISQNRRSTPFYL-
----RDQHGR-VRVEPESAAIAT--IPVLDEFRPDSSAS--SLIFGAFSLSL--STT-AG
LGKTLGYRYREEILPCDRSVLVVGAAS-DETGELTLGP-SSE-ARQQFFIALKPETALLQ
EVKQT-------IQWLTIGAIASVVVTVVAAIAA--------------------------
------------------------------------------------------------
-----------------L-----L---
>Cyanobacteria gi|443316014|ref|ZP_21045478.1| E3 Ubiquitin ligase [Leptolyngbya sp. PCC 6406] >gi|442784396|gb|ELR94272.1| E3 Ubiquitin ligase [Leptolyngbya sp. PCC 6406]
--------------------------MAGIIGLILLI---GGIALFFVQRHQKQKAFSLK
IARKVTA-AELNDTASGVAAEI----GG-GSWRDYVKVWGKI----------QVDEPLIS
EHTRQKC--VYYCSKVLREYE--DTTTERNSEGRLETK--TQRKTETISSNKQSIPFTL-
----VDDSGT-VEVNPESADIET--VEVMNEFRRET----------------------KG
RRNTLGYRYQESLLPLNRNILVLGAAS-DLTGRVVISK-PTK-ADTKYVISLKDEETLSA
AVERN-------AKISFFSMVACGIVGILLVLWQ--------------------------
------------------------------------------------------------
-----------------L-----L--S
>Cyanobacteria gi|428773069|ref|YP_007164857.1| hypothetical protein Cyast_1243 [Cyanobacterium stanieri PCC 7202] >gi|428687348|gb|AFZ47208.1| hypothetical protein Cyast_1243 [Cyanobacterium stanieri PCC 7202]
---------------------------MGIFGFIIVA---IALILFFVKQAQTKSHSSVL
LARFTDV-QELESTCQAITEDI----GG-GNWRDYVKLWGKI----------TIDEPLIS
EMKQEPC--VHYRMLVQREYE--EKVRSQDSEGKTVEK--TVRKSETITQNQRSIPFIL-
----EDKTGA-ITINPEDAKFDT--IKILDEFRPEQPAGG-MLQFGNFSFLV--RNN-NY
HTRTLGYRYQEFILPIHREVLIVGNVS-DETGSLKITK-PMD--NQPFLISLKTEEELNS
DYQKN-------QNILKYSMISCFVIGFILILVN--------------------------
------------------------------------------------------------
-----------------V-----I--T
>Cyanobacteria gi|22298202|ref|NP_681449.1| hypothetical protein tll0660 [Thermosynechococcus elongatus BP-1] >gi|22294381|dbj|BAC08211.1| tll0660 [Thermosynechococcus elongatus BP-1]
---------------------------MGVLGGILLV---IAVLVLCGWWDYRLKVRALN
LAVSSTP-AQLHELQRRVAQEI----GG-GYLQEYVKISGQI----------VADRPLVS
ELKRLPC--VHYRLCVSRVYK--TTESHEDGSSE------TKYRHEILSSNTQTIPFRL-
----RDGDME-IYVDPRGAEIET--VQVLNEFQEDNNTT--HLAFGRFQMDL--SSL-PK
HSDTVGYRYEEWILPVNQQVFVVGTAS-DERGKLRIRR-PHQ-KGQLFFISLESEENLTK
KVRQY-------ARASIIAAGVFSGLGILLILL---------------------------
------------------------------------------------------------
---------------------------
>Cyanobacteria gi|22297743|ref|NP_680990.1| hypothetical protein tll0199 [Thermosynechococcus elongatus BP-1] >gi|22293920|dbj|BAC07752.1| tll0199 [Thermosynechococcus elongatus BP-1]
---------------------------MGVFAHLCLT---GSAFLFALEGYYRLQLRGIK
VASPSTI-GELEKFQQQVAQEM----GS-GSWREYVQVVGQV----------TTSQPLLS
EVKRIPC--VYYKTIISREYE--KEG--------------SDRPSEIIGRHEQSTLFLL-
----RDHQGE-IEVNPFGAEIEA--VQVLDELRPADQPHAFALSLGFLSFNW--H---FG
KGTTLGYRYQEWVLPLGQPVSVVGMAS-DQGGVLRLQK-PQN-RGQKFIISLSFEDPLIQ
QYKQQ-------KRKMTYASLGATLCGVCGLVLA--------------------------
------------------------------------------------------------
-----------------L--------F
>Cyanobacteria gi|428774782|ref|YP_007166569.1| hypothetical protein PCC7418_0109 [Halothece sp. PCC 7418] >gi|428689061|gb|AFZ42355.1| hypothetical protein PCC7418_0109 [Halothece sp. PCC 7418]
-----------------------MAIFTLIVGIILGL---ISGASYLQYRKLQEEFSAII
STETSTV-EDLKKISEEVAEEL----GNTGYFRQQAEVKVTI----------QCENPLTA
NLSHESC--IYYQTVINERYE--KTEWVEDDEGNFEPN--KSEGSKNLVNNFRCVDFFL-
----EDDTGQ-ILVNPDHGKIEG--VQVYDYYQPADSIDELEMSCGDIEIEF--SPRNDA
EYQTLGYQFQEVILPVNTQVYIIGEAS-DRVGDLELHQ-PSE-ENQLFLISYKSEEELSE
EKREDIKKNKKIAQLYLFSAIAFLIFALINLL----------------------------
------------------------------------------------------------
--------------------------N
>Chloroflexi gi|159899427|ref|YP_001545674.1| hypothetical protein Haur_2908 [Herpetosiphon aurantiacus DSM 785] >gi|159892466|gb|ABX05546.1| hypothetical protein Haur_2908 [Herpetosiphon aurantiacus DSM 785]
---------------------------MVFFGIVLLI---AAVICFFFARSQSNKLADLN
ATDTYTT-QMLHDLHKKVVETL----GA-EALAEPCEIEGQV----------SCDNPLVA
PISGQTC--IAYRFSLTREYS--EVVHDTDSEGRKRTR--TQTGSETIKSEEECAYFWI-
----NDNFGK-VWVDPTDAEIEY--EAGQNILLPSPDKAS-ILHFGDFEFAA--PASNKG
ARRTTGYRAQEELFTDDGRAYILGCVT-DDEGEPTIAY-HEK-KLDRMLVSRKTERELAN
SAAGW-------SRNLYYGAAGSAVAGIIFTIWG--------------------------
------------------------------------------------------------
-----------------L--------L
>Chloroflexi gi|309792827|ref|ZP_07687269.1| hypothetical protein OSCT_3220 [Oscillochloris trichoides DG-6] >gi|308225139|gb|EFO78925.1| hypothetical protein OSCT_3220 [Oscillochloris trichoides DG6]
---------------------------MAIVGVILLI---VGVICFFVARSKANALHAMN
AADTYTA-QLLAEVHRKITSTL----GG-NGWAQPCEIEGII----------ECDSPLKG
PISGQPC--VAYYYTQSREYE--ERVTSTDSDGKRETT--VERRSEQLRSEDRRIKFYV-
----RDETGK-TLVMPEGADLDL--LETGNRFDQDEKPW-------------------TG
ATRTLGQSHVEQSLAVGTKVYLLGCAV-DREGSVAVGKHPKD-SKHRFMISRKSEQELAN
SAAFW-------SRNLYYAAAASGGLGLILVVLG--------------------------
------------------------------------------------------------
-----------------M-------LG
>Chloroflexi gi|163846705|ref|YP_001634749.1| hypothetical protein Caur_1130 [Chloroflexus aurantiacus J-10-fl] >gi|222524514|ref|YP_002568985.1| hypothetical protein Chy400_1238 [Chloroflexus sp. Y-400-fl] >gi|163667994|gb|ABY34360.1| hypothetical protein Caur_1130 
---------------------------MIVGGVLLLV---LAVIFFFVARANAGKLQALN
AVDTYDT-ATLSAIHRRITTAL----GA-HDFAQPCEVMGLI----------ECATPLTG
PVSGQAL--VAYLYTTHREYE--ERITTQES-GRSTTR--IERRSEQLEQNERRVPFTI-
----RDDTGQ-VLVVPDGAKIDL--IETANRFLETPQPW-------------------TG
ATRTLGQRQFERGLEVGIRVFVSGTAI-DQNGQVVIARHPTN-SKQTFIISRKSEHELAN
SAATW-------ARNMRYAAIASGVIGLALVVGG--------------------------
------------------------------------------------------------
-----------------V-----LVSG
>Chloroflexi gi|269838375|ref|YP_003320603.1| hypothetical protein Sthe_2360 [Sphaerobacter thermophilus DSM 20745] >gi|269787638|gb|ACZ39781.1| conserved hypothetical protein [Sphaerobacter thermophilus DSM 20745]
---------------------MGTSGVLLIIGLVAAG---IGAVLLFIGRRIQAKTDLLA
KVPTVDA-SEVASLI----------------PGEMIEVKGVI----------RCDTPLTA
ELAQRAC--VYYSSRVVREYE--YRRRNAKGETV------RSRRSETVAHNEQFTPFYV-
----EDSSGR-VLVDPEGAEVDA--QKLVDRFERNPGALGPTISLGGISLNL------GG
DDGTIGYRYQEHVLPVDIPVYVLGVVQ-EGGT---IGRPPAALKGRRFIISYRAEEALRE
SWGKK-------ARWLGISAVALFALAVILFVVA--------------------------
------------------------------------------------------------
-----------------VGMLV----A
>Actinobacteria gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941] >gi|108766407|gb|ABG05289.1| conserved hypothetical protein [Rubrobacter xylanophilus DSM 9941]
---------------------MVGTVVFLLVGVVLCV---AGGVLLYFRRRMLGKAELMR
RTRTSGA-AGVSALS----------------PGTLVEVKGTL----------RCERPLQS
EMAKERC--AYYSSKVVREYL--ERDRGDGAPG-------SGRRSEVLARSERFAPFVV-
----EDDTGG-VPVSAEGAEVDA--KKVVDRFERGAGAAGLSVTIGGATIDL------GG
GERTLGYRHTEEILPVDAPVYVLGAVR-RDGG---IGP-PEE-GAGRFVVSWRSEEALGE
SLGRG-------ARLLGLIALGLFLAGAAFLAVG--------------------------
------------------------------------------------------------
----------------AAAALGYLQFR
>Chloroflexi gi|221632287|ref|YP_002521508.1| hypothetical protein trd_0254 [Thermomicrobium roseum DSM 5159] >gi|221156341|gb|ACM05468.1| conserved hypothetical protein [Thermomicrobium roseum DSM 5159]
---------------------------MIFVTLCFLITAGVGLVCLIGYRRTRQQLRLLR
LVATCPI-AELHERI----------------PGEMVEITGTV----------HCATPLRS
EYTGQPC--VYYRTVTERVVE--RHGRSKK----------GGRLSEVVAQNEQRIAFEV-
----DDGTGR-VAVDPVGAEIDG--RKLLDRFEPVENGEGATLRIAGMSVEV--R---AA
EWRTLGYRKIEEAVLVGYPVYVLGVLQ-DDGS---IGRPPEGSRLREFLISARSEEELAT
SLRRR-------SYLFLAGAITSFVVAGMLLIA---------------------------
------------------------------------------------------------
-----------------LLVQSVISIS
>Bacteroidetes/Chlorobi_group gi|124004219|ref|ZP_01689065.1| conserved hypothetical protein [Microscilla marina ATCC 23134] >gi|123990289|gb|EAY29788.1| conserved hypothetical protein [Microscilla marina ATCC 23134]
-------------------------MALVIIGVVLIA---IAVALWFNRKRQLSKALNIK
YHETSKV-ADVVDIYKQLGDGL----DG-SYRGNIVELSGMS----------RSDSPLQS
EHTNAEV--VYYRARVIHEYETLEIVRQQDDEGNYYEREVVHNHQETVSDNERFAPFYL-
----DDGSGR-ILVEMDKAQRHT--ITSLDEYQPEPPTGYDPY---------------GI
RGTTTGYRYIEEIIPNNHKLYVLGQAA-ESHGNLAVVK-PTK-KDEEFIVSTKSEEELVQ
GAENS-------AKMSLYGAIGLGILGLILMVVG--------------------------
------------------------------------------------------------
-----------------FTSKG----G
>Actinobacteria gi|348176796|ref|ZP_08883690.1| hypothetical protein SspiN1_40700 [Saccharopolyspora spinosa NRRL 18395]
-------------------------MAVIIIGVVLLV---AAAVGFYFMRRARDELHAMI
GAETLPV-NQLELLR-KASDDV----GARGGFRKECEVVGAAHP--------RPEGVLIS
ELSKTVC--VWFRYVVKRRYE---RVRYRDGRRH------VDRGSETVAEHTSWEGYAL-
----RDDHSVLIGVDPNGTKPDRP-EQVVDRFEPHNPQGP---TVFGFQLPN--I---LD
NSGTVGYEYKEWVIRPGRRLYILGEVH-DKIGPLVIGK-PEQ--KGFFIISTRSEQEVRD
SLRTQ-------HRLLAFGIPAAALAAIVCIVLG--------------------------
------------------------------------------------------------
-----------------I-------VL
>Actinobacteria gi|384564441|ref|ZP_10011545.1| E3 Ubiquitin ligase [Saccharomonospora glauca K62] >gi|384520295|gb|EIE97490.1| E3 Ubiquitin ligase [Saccharomonospora glauca K62]
---------------------------MWIAGVVLLV---VAVAAFFYMKHTRDELHAMI
GTETFSI-PELERYR-AASDEL----GGKGAFRKTAEVVGAAHP--------RPEGPLTA
ELSKVEC--VWYRYRIDRHYE---VIEYRDGKRY------RRKRTERVAEHTSHEGYAL-
----IDDEGRTIGVDPNGTNPDGV-EQTVSRFEPHRGQQG-SIELFGIKLPA--LF--GR
GDSTIGYDYKEWVIRPGQRLYILGEVH-DRIGPLVIGK-PRE--KGHFIISTRTEEELRQ
LRVRR-------HKFLAIGTVASTVVGLGLIVAD--------------------------
------------------------------------------------------------
-----------------L-------FV
>Mulan_NP_078820
----------------MESGGRPSLCQFILLGTTSVV----TAALYSVYRQKARVSQELK
GAKKVHLGEDLKSILSEAPGKC----------VPYAVIEGAV----------RSVKETLN
SQFVENCKGVIQRLTLQEHKM--VWNRTTHL---------WNDCSKIIHQRTNTVPFDLV
PH--EDGVDVAVRVLKPLDSVDLGLETVYEKFHPSIQSFTDVIGHY------------IS
GERPKGIQETEEMLKVGATLTGVGELV-LDNNSVRLQP-PKQ--GMQYYLSSQDFDSLLQ
RQESS-------VRLWKVLALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQEHEA
QLLSRAKPEDRES-----------------LKSACVVCLSSFKSCVFLECGHVCSCTECY
RALPEP--KKCPICRQAITRVIPLYNS
>SP1_NM_105064_AT1G63900
--------------------------MIPWGGVTCCL---SAAALYLLGRSSGRDAEVLE
TVTRVNQLKELAQLL-ELDSKI---------LPFIVAVSGRV----------GSETPIKC
EHSGIRG--VIVEETAEQHFL--KHNETGS----------WVQDSALMLSMSKEVPWFL-
----DDGTSR-VHVMGARGATGFALTVGSEVFEESGR-SLVRGTLDY-----------LQ
GLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQK-PDR---GPFYVSSKSLDQLIS
NLGKW-------SRLYKYASMGFTVLGVFLITKHVIDSVLER------RRRRQLQ-KRVL
DAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACS
SHL-----TSCPLCRRRIDLAVKTYRH
>SPL1_NP_564745_AT1G59560
--------------------------MIHLAGFTCCL---GGVALYLLTRSTGRD---IK
SITRVYQLKDLEQLV-EVESKV---------VPLIIAVSGDV----------GSETPIKC
EHSYVLG--VFLKRTAEQQVL--RRNWRFS----------WVRNSTLMQPMTKEVPWYL-
----DDGTGR-VNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGY-----------LK
GFKILGVRHVERVVPIGTPLTVVGEAVRDGMGNVRIQK-PEQ---GPFYVTYIPLDQLIS
KLGDL-------SRRFKYASMGLTVLGVILISKPVIEYILKRIEDTLERRRRQFALKRVV
DAAARRAKPVTGG----------GTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCS
LQL-----RTCPLCRERIQQVLKIYRH
>SPL2_NP_564653_AT1G54150
-------MSSPERALLNLLTDIALSFDGAILGLTLAV---SAVGSALKYASTNAALKKIK
DAPEVSI-SDLRSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLIS
PETGDKA--LIIQRTQTYVYS--GWKRLFQSTGHRFML--ERSLRKHGADFTRTVPFVIV
GKDQQSNSSF-VAVNMDGSRQPLPLTTVYNRLQPINSSFLQAF---------------LY
PDYPVGLLDIEKILPPGKDITAVGIYS-FNNGVPEIKS-CQD---LPYFLSEMTKDKMIE
DLMEQ-------TNFIFLGSVILGIVSVGILSYAAVRTWNKWKQWNHQRELPQRPNDSVV
DDEPEDADEIPDG-------------------ELCVICVSRRRVPAFIPCGHVVCCRRCA
STVERELNPKCPVCLQSIRGSMRVYYS
>gi|375098891|ref|ZP_09745154.1| superfamily II DNA helicase [Saccharomonospora cyanea NA-134] >gi|374659623|gb|EHR59501.1| superfamily II DNA helicase [Saccharomonospora cyanea NA-134]
MLLLIVAVGAFFYMKHTRNELHAMIGTETLSIPELEQYRSASDGLGATGTFRKLSEVVGAAHPRPEGPLTAELSKVECVW
YRYRIDRHYEVIEYRDGKRHRRKRTERVAEHTSSEGYAVIDAEGRTIEVDPNGTEPDGVEQTVSRFEPHGGKEGGVELFG
IALPALLGRGDSTIGYDYKEWVIRPGRRLYVLGEVHDRTGPLVIGKPAGKGHFIISTRTEQELRDSRVQRHKLLAIGTVA
STLLGLGLLVGGLFT
>gi|86607674|ref|YP_476436.1| hypothetical protein CYB_0172 [Synechococcus sp. JA-2-3B'a(2-13)] >gi|86556216|gb|ABD01173.1| conserved domain protein [Synechococcus sp. JA-2-3B'a(2-13)]
MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPPPERKAFMNWLMLLGLLCLPASL
FSFVEYLRSQRLVQQLSATRLLKIAELRHLGQTNPQAKGANLAQVYGRVVCDRPLVSELSRQPCVYYKSEISWEYDEIEC
YRRYLNSRGDVAYSERISEGEYQNALRLGSRAKSYPGEMVGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPNPGYPQQLGS
PGYPQKSPFSEVSSPQKHYANVYYDPSTGREYLLERETRTRDETLHSVVRQIPFFIEDETGRVRVDPTGAEIEAMSVVDE
HIFPGKGPSRFNFNLKRYLSGVRTENRSTRAFIYKEWVIPVDAMAFTMGQVRFEAGDPVIRKPLSGERFMIAPKSPEALL
EEQRSNASSYLVGSVVLLGIGIFTVLHLLQSLQPYR
>gi|257054548|ref|YP_003132380.1| hypothetical protein Svir_04780 [Saccharomonospora viridis DSM 43017] >gi|256584420|gb|ACU95553.1| hypothetical protein Svir_04780 [Saccharomonospora viridis DSM 43017]
MWIVGVVLLIVAVVAFFYMKHTRSELHAMIGTETLSIPQLEQYRQASDEVGGRGAFRKTAEVVGAAHPGPHGPLKAELSK
TECVWYRYRIDRHYEVIEYRDGKRHRRKRTERVAEHTSAQNYAVIDEEGRTIGVDPNGTKPDSVEQTVSRFEPHRGNSQS
IELFGFKLPTMLGRGDSTIGYDYKEWVIRPGQRLYILGEVHDRFGPLMIGKPAQGGHFIISTRTEEELRASRVKRHKLLA
ITVITSFVLGWVLLIADLLR
>gi|239616922|ref|YP_002940244.1| LemA family protein [Kosmotoga olearia TBF 19.5.1] >gi|239505753|gb|ACR79240.1| LemA family protein [Kosmotoga olearia TBF 19.5.1]
MQFVLLIGFVVMLLCVLFAMQNLKKKRLIDDTPTSKVKGVFIGLVELKGKVKTTRPLTSYLTEKPCVYYRWSIEEHWTKR
TTETYTDSHGKTRTRTKTESGWKTVASGGDEIPFELCDDTGCILIRPEKARVEAITVMNRVCGRSDPLYYGKGPDRAIMY
SDHRRRFVERIIPPDADLYVFGQAREREDIVAPEVAYDKEAPMFLISTREEKKLSRRYSLYYWLLVAVGIIAAIATAYFS
IDRTFSLPQEPIQPYIVTIGSFLVMLFIGWFWVTHNSLKSLQRRVQQGWSQIEVQLKRRHDLIPLLVNVVKGLVKHEQDT
QEKLAELRGELENMSGKEVLKVLIERYPNLKSQEAFIKLQKELSDTENRIALARGYYNEIASFYNARLERFPDLIVAKLG
RLKHQRLWKQ
>gi|381164333|ref|ZP_09873563.1| superfamily II DNA helicase [Saccharomonospora azurea NA-128] >gi|418462936|ref|ZP_13033969.1| hypothetical protein SZMC14600_18329 [Saccharomonospora azurea SZMC 14600] >gi|359735029|gb|EHK83994.1| hypothetical protein SZMC14600_18329 [Saccharomonospora azurea SZMC 14600] >gi|379256238|gb|EHY90164.1| superfamily II DNA helicase [Saccharomonospora azurea NA-128]
MWIVGVVLLVVAVGAFFYMKHTRDELHAMIGTETLSIPELERYRGASDEVGGTGAFRKTAEVVGAAHPRPEGTLTAELSK
TECVWYRYRIDRHYEVIEYRDGKRHRRKRTERVAEHTSHEGYAVIDNEGRTIGVDPNGTKPDGVEQTVSRFEPHRDGGGG
VDLFGIRLPALFGRSDSTIGYDYKEWVIRPGQRLYILGEVHDRIGPLVIGKPSEKGHFIISTRTEEELRASRVQRHKLLA
AGTVASCVVGLGLLVGGLFT
>gi|389844132|ref|YP_006346212.1| hypothetical protein Theba_1281 [Mesotoga prima MesG1.Ag.4.2] >gi|387858878|gb|AFK06969.1| hypothetical protein Theba_1281 [Mesotoga prima MesG1.Ag.4.2]
MDYSSIVRLIGVGLSLLMLLFSFRSYRRKRLIDDMPTSKAHGVFIGLVEVSGKVECQNPITSYLTESTCVQYSWEISEHW
SKTTTETYTDSKGKTRTRTKRESGWKTVASGESMCPFDLRDETGTIQIRPEKAKIEGVRAMDLRCRSSDPLYYGKGPAES
IIHSDHLRMFTESIIPLDARVYVIGQSREREDIVAPEIAHDESSPLFLISTREEERISKSYSLNYWLLSLGGLGVSLISF
FIASRIGFYRWIPSGVSDYFMPTGIYLGLWLIGWFWTTFNSLKSLRERVRQGFSQLEVQLKRRHDLIPRLSSAVSSLMKH
EQSIQTKIAALRSEAAVNAKAAKRLLVLVEDYPELKSSEAVSRLQRELSDTENRLELARAYYNNIATFYNTRLERIPDNV
VATLARLKNCELLLQSEGDGDSK
>gi|383829039|ref|ZP_09984128.1| E3 Ubiquitin ligase [Saccharomonospora xinjiangensis XJ-54] >gi|383461692|gb|EID53782.1| E3 Ubiquitin ligase [Saccharomonospora xinjiangensis XJ-54]
MWIAGVVLLVVAVAAFLSMKHTRDQLHTMIGTETLSIPELEQYRAASDEVGASGMFRKTSEVVGEASPSPDGPLTAELSK
TECVWYRYRIDRHYEVIEYRDGKRHRRKRTERVAEHTSHKNYAITDEQGRTINVDPDGITPDGAEQTVSRFEPRRGRQGG
IDLFGIVLPALSGRGDTTIGYDYKEWVVRPGRRLYVLGEVHDRTGALTIGKPEGKGHFIISTRTEQELRDSRVRRHRLLA
IGTVASALGGLGLLVAGLFT
>gi|325002910|ref|ZP_08124022.1| hypothetical protein PseP1_29285 [Pseudonocardia sp. P1]
MLWIGIIALLAGAGCFWAAVHTQRRVHAMMAAETLPVPRLLEEAGIAADLNGGPGRFRKVCEVVGEAAPAPVGLLRSELA
GVECVWHAHRVERRFERRERDSEGRMRTSTHTETVSERVSPHGWPLLRDGHTIGVDPGGRRPDPVELVLDRFDPADERGP
RGDRTLGYRNQEWVLRPGVRMYVLGEVDDRDGPLVIRAPQDTSHPFVLSTRTEDELTATDRRSQRWWARGGAALVLLGLV
LTIAGAVT
>gi|309791495|ref|ZP_07685998.1| hypothetical protein OSCT_1949 [Oscillochloris trichoides DG-6] >gi|308226464|gb|EFO80189.1| hypothetical protein OSCT_1949 [Oscillochloris trichoides DG6]
MFMFFLVLTLTLALAGIITAIIAWRGESHIIAMRETETLYIAQVIEQHRQGRLGQTVEVVGTSECDVPLRAPYSSELCLA
FEYTVNEEHERTERVRSLAPTHRFDLGHAAGREISSHHLNIHAERVPRFYVHDASGRIAVETQGAKIDLIEGMARFESYT
GTLNDVEREIWREEYNLPVGNRVYVLATLGDVNGEPVLMRHPVDPKRSFLISHRDEQSYIKHTSIRTYGLYILSGVLISA
AVISGLLLMWKG
>gi|57235080|ref|YP_180857.1| hypothetical protein DET0106 [Dehalococcoides ethenogenes 195] >gi|57225528|gb|AAW40585.1| lemA family domain protein [Dehalococcoides ethenogenes 195]
MEFQIWGYLVFALSLVALVLAFRVMRRKRLVDDIPTSRTQEVFIGLVELKGRAESENPFTGFLSAKKCVYYHYKVEEHWS
RLVTETYTDAKGHVGVRTRQESGWTQVASGKEMQPFYLKDETGIILIQPEGADIQPQTLFDQTCGRSDPLYYAKGPQGSI
ANSDHRRRFTEEAIPLHAELYIMGQSRERGDIVAPEIAKDKSAPMYVISTRTEKQISRSYSGWFWFWIILGLLVSLGSGL
LLSQQGAEGFNPGWGAVWWLGFYLFGWLLGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVAGFSKHEHE
LQEMLAEVRTISKVNGQDTTDIRSASAILVFNMEKYPELKADTLFLKLQEELAATESRIALARDYYNSIATFYNTRREIF
PDRLLAGIFGFKERVLINASDLERTAPEVKLAE
>gi|270307560|ref|YP_003329618.1| LemA domain-containing protein [Dehalococcoides sp. VS] >gi|270153452|gb|ACZ61290.1| LemA domain protein [Dehalococcoides sp. VS]
MELQIWGYPVFALGLTALVLAFRTMRRKRLVDDIPTSRTRGVFIGLVELKGTAESEKPFTGFLSAEKCVYYHYKVEERWS
RMVTESYTDAKGHVQFRTHQESGWTQVASGKEMQPFYLKDETGIILIQPEGADIQPKNLFNKTCGRNDPLYYAKGPQGSV
ANSDHQRRFTEEAIPLHAELYIMGQSRERQDVVAPEIAKDKSAPLYVISTRTEKQISRSYSGWFWFWIILGLLISLGSGL
LLSQQDKESFNPDWGIVALWSGFYLLSWLLGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFSRHER
ELQEMLAELRTVSKVNGQDTMDIKGASAILVFNMEKYPELKADTVFLKLQEELAATESRIALARDYYNSIATFYNTRREI
FPDRLLAGIFGFKERVFINASELERAALKVKLAE
>gi|73748061|ref|YP_307300.1| hypothetical protein cbdb_A126 [Dehalococcoides sp. CBDB1] >gi|73659777|emb|CAI82384.1| lemA family domain protein [Dehalococcoides sp. CBDB1]
MEFQIWGYLVFVLGLAALALAFRTMRRKRLVDDIPTSRTHGVFIGLVELKGTAESEKPFTGFLSAEQCVYYYYKVEERWS
RMVTESFTDAKGHVQFRTRQESGWTQVASGKEMQPFYLKDETGIILIQPEGADIQPKNLFNRTCGQNDPLYYAKGPQASI
PNSDHQRRFTEEAIPLHAGLYIMGQSRERQDIVAPEIAKDKSAPLYVISTRTEKQISRTYSGWFWFWVGLGLLLASGSGL
LLSQESTSGFNPDFGVAVLWLGLYLICWLFGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFGKHER
ELQEMLAEVRTISKVNGQYPKDIQGASAILVFNMERYPELKADTLFLKIQEELAATESRIALARDYYNSIATFYNTRREV
FPDRLLAGIFGFKERVLINASALERAVVKVKLAE
>gi|147668909|ref|YP_001213727.1| LemA family protein [Dehalococcoides sp. BAV1] >gi|146269857|gb|ABQ16849.1| LemA family protein [Dehalococcoides sp. BAV1]
MEFQIWGYLVFVLGLAALALAFRAMRRKRLVDDIPTSRTHGVFIGLVELKGTAESEKPFTGFLSAEQCVYYYYKVEERWS
RMVTESFTDAKGHVQFRTRQESGWTQVASGKEMQPFYLKDETGIILIQPEGADIQPKNLFNRTCGQNDPLYYAKGPQASI
PNSDHQRRFTEEAIPLHAGLYIMGQSRERQDIVAPEIAKDKSAPLYVISTRTEKQISRTYSGWFWFWVGLGLLLASGSGL
LLSQEGTSGFNPDFGVAVLWLGLYLICWLFGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFGKHER
ELQEMLAEVRTISKVNGQDPKDIQGASAILVFNMERYPELKADTLFLKIQEELAATESWIALARDYYNSIATFYNTRREV
FPDRLLAGIFGFKERVLINASALERAVVKVKLAE
>gi|289432088|ref|YP_003461961.1| LemA family protein [Dehalococcoides sp. GT] >gi|288945808|gb|ADC73505.1| LemA family protein [Dehalococcoides sp. GT]
MEFQIWGYLVFVLGLAALALAFRTMRRKRLVDDIPTSRTHGVFIGLVELKGTAESEKPFTGFLSAEQCVYYYYKVEERWS
RMVTESFTDAKGHVQFRTRQESGWTQVASGKEMQPFYLKDETGIILIQPEGADIQPKNLFNRTCGQNDPLYYAKGPERSI
PNSDHQRRFTEEAIPLHAGLYIMGQSRERQDIVAPEIAKDKSAPLYVISTRTEKQISRTYSGWFWFWVGLGLLLASGSGL
LLSQESTSGFNPDFGVAVLWLGLYLICWLFGWLWAGYNSLVGLRNRVCQGYAQVDIQLKRRFDLIPNLAKSVEGFGKHER
ELQEMLAEVRTISKVNGQDPKDIQGASAILVFNMERYPELKADTLFLKIQEELAATESRIALARDYYNSIATFYNTRREV
FPDRLLAGIFGFKERMLINASALERAVVKVKLAE
>gi|354613574|ref|ZP_09031488.1| hypothetical protein SacpaDRAFT_0895 [Saccharomonospora paurometabolica YIM 90007] >gi|353222061|gb|EHB86385.1| hypothetical protein SacpaDRAFT_0895 [Saccharomonospora paurometabolica YIM 90007]
MWVLGVSVLAVTAGAYFAMRHTRRELHAMIGTETLSIQQLEQLRDVSVELGGKGDLRRTVQVVGAAHPGPDGALTAELSK
AECVWFHYRVDRHYEIIEHGEFRRRKKRSENVIDHVSREKYALVDEEGRTVLVEPGDTEPDGVEQSVHRFEPVRSATGEI
DLESLTPDSSSGHSEITVGYQYTEWSLRPGTRLHVLGEVEDTFGPLTIRGPGQGGHFVISTRPGNELRAERRKLHTGLAV
GVVIGAVLGVGLVVGGLVT
>gi|182414263|ref|YP_001819329.1| LemA family protein [Opitutus terrae PB90-1] >gi|177841477|gb|ACB75729.1| LemA family protein [Opitutus terrae PB90-1]
MDGSNPLPVVLCGVAAGAFLLGSLHLRRKQRLLHDLPTSKTQGVFIGLVEVAGTAESSAPLRGYLSGATCVHFDYEVQEH
WSRTVTETYTDKEGKSRTRTRHESGWTTVAHGGETQDFYLRDDTGAVLIRPAGAKVEAQTLFEQTVNRGDPLYYAKGPDH
AVANSDHRRRFVERGLALHTSLYVVGQARERADVVAPEIAQDRNAPLFLISTRTERSVQTRLAVGSWVCWALGLVAAVGA
ALFAMQNLPPGSFAPLAIALGGYLGGWALGWTWMVFNSLVSLRNRVRQAWSLIEVQLKRRHDLLPSLTSVVSALSTHERS
TQTAVSALRSQIQATPPGVAGPDFAGVAAALRGVAEAYPELTAQDSFARLQRELVTTEQRIALARSYYNDIATQFATRLE
RIPDGWVARLAAMKPQPLLAAADFERARVDVQFADAA
>gi|331695440|ref|YP_004331679.1| hypothetical protein Psed_1589 [Pseudonocardia dioxanivorans CB1190] >gi|326950129|gb|AEA23826.1| hypothetical protein Psed_1589 [Pseudonocardia dioxanivorans CB1190]
MWVIGVVVVLVGAGFLWSAVRAQRSVHAMLAAETLSVPELEELRRVSDDLGARGSFRKVCEVVGAAHPSPEGVLRSELSG
VECVWHSHRVQRRYKHYDRDRDGSTRVTTRTETVAEQTSGPGFALLRDGRTIGVDHAGRRPDGVEQVTDRFEQTQEPSNG
WADVVGALVGSDRDETIGYQYTEWVLRPGTPMYVLGEVHDAIGPLVIAPPADPKQPFVMSTSTEQQLTDAARGRQRFRSR
LGAALVVVGIVVVVLALVL
>gi|345864169|ref|ZP_08816373.1| hypothetical protein TevJSym_ak00400 [endosymbiont of Tevnia jerichonana (vent Tica)] >gi|345124700|gb|EGW54576.1| hypothetical protein TevJSym_ak00400 [endosymbiont of Tevnia jerichonana (vent Tica)]
MHHDILTMPELTFWIWVNSLALLCLAALWFAFRNLSRARIIEDTPTSLIRSAHQGYVELNGTAATMQGEPILTPLTHVPC
CWYRYRIERRHEKGWRTSQQGSSDGLFLIKDPTGQCIIDPDGAQITPSERQVWYGGSSFATAMPARSGGSSLAGLFSAAL
SLGGQGHLGEHYRYTEETIYPGDPLYAIGLFKSFDETDRQALIKAHASDLLRQWKQDHPELLARFDRNGDSRIDLDEWDQ
ARRQAHRQATREEAAADRQNLHTLSNTGTSRRPFIISSHAEFKLVTRYKRIAFAAISSFFSPAASPAGCSASDCSAELC
>gi|410692675|ref|YP_003623296.1| conserved hypothetical protein; putative membrane protein [Thiomonas sp. 3As] >gi|294339099|emb|CAZ87453.1| conserved hypothetical protein; putative membrane protein [Thiomonas sp. 3As]
MLSGLSPSGAAPQVLFMALALGAVGLVQFFRLQRRRRVMEDMPTARIRSAAQGYVELIGRALPPDAPLFSPITRTPCCWY
RYKIEKRDDDNKNSWSVQEQGKSTTQFWLDDDTGRCIVDPEGAEVRARSRNTWTGAAAQLIPGTSEVLMTGDSDHRYTEH
LILPGQTLYALGWFASLSPLQASAHEEVRERIAAWKADPQKRRSFDANADGELSMAEFEQLRQQAAAAVEADRRERAALP
QTHVLKKPKDRRLFLLTTEPHDDLGGKLRWQAWAWLAAGVLGLAYGGAGLMMLV
>gi|296135054|ref|YP_003642296.1| hypothetical protein Tint_0566 [Thiomonas intermedia K12] >gi|295795176|gb|ADG29966.1| conserved hypothetical protein [Thiomonas intermedia K12]
MLSGLSPSGAAPQVLLMALALGAVGLVQFFRLQRRRRVMEDMPTARIRSAAQGYVELIGRALPPDAPLFSPITRTPCCWY
RYKIEKRDDDNKNSWSVEEQGKSTTQFWLDDDTGRCIVDPEGAEVRARSRNTWKGAAAQLIPGTSEVLMTGDNDHRYTEH
LILPGQTLYALGWFASLSPLQASAHEEVRERIAAWKADPQQRRSFDANADGELSMAEFEQLRQRAAAAVEAERRERAAQP
QTHVLKKPKDRRLFLLTTEPHDALSGKLCWQAWAWLAAGVLGLAYGGAGLLMRV
