>gi|321268754|gb|ADW79203.1| ribosomal protein S10 [Cyanophora paradoxa]
MIKIYIFSHYFLAINFFVKTITYCLSLKKIPFKVYPQPKKCSILTTLRSPHVNKNSMEHFKIEKFKYIIE
INNINNKISKKIFNKLYYYCPAGLTFYIKYQTNEFKK

>gi|158939329|gb|ABW83990.1| granule-bound starch synthase [Cyanophora paradoxa]
MNIAPVSELQAAIDQAEKKLTIVFVGSECTPWSKTGGLGDVMRDLPVNLAQRGHRVMSIQPRYDQYFDAW
DTAVRSSIKVNGKLEDVGFFHITSKGVDRIFIDHPWFLAKVWGITGNKLYGAKTGVDYPDNPMRFALMCQ
AALEAPLRIPLPDPAGTVYGEDVIFVCNDWHSALVPIYLKANYKTRGLYQNAKSIFLLHNIIYQGRFPLE
FWPALNLPEAAKKDLVFESCFAPPPLDGISEQPIISLKPMAMMNFLQAGFIHADRICTVSPQFAAEVASG
PRGGVELDKYIRAKGITGIMNGMDIEMWDASKDKFLVTKYTASSVDEGKAANKAVLQAEMGLKVSPTTPL
IAFVGRLDDQKGADCMVEAMPYLVNTLGAQVVCYGSGREDMAAKFKALEKQFPGMAKGKTAFVPKEEHTL
MAGADYVLMPSRFEPCGLVQLHAMKYGAVPIVSCTGGLKDSVIPECGFTFEEIPSPEYPGMKISPELIAK
GTKIIEEGCKEALAGYGSKAFAGMRAACMKQDFAWKKRVLVYEKVFYETLGIDRGAPVTAKASPVAPEPS
AAPAPATISAATSGGILPVPKAAAPKAPKVGA

>gi|11467287|ref|NP_043144.1| hypothetical protein CypaCp007 [Cyanophora paradoxa]
MDNFLFSFYIIFFSLIVLALISFLIQEIQKSRFLDLEITRLRKKIYQEKATEKDYNNLASIYIKKKLYSQ
AQKEFLKILENKNLDKSQLALIYNSLGYICSAQEQYELAIEYYKKALFYIPDFILARINLARIFELKNLK
TEAINMYQEVLIFDPKNQLAKRKLSIIENLIL

>gi|11467328|ref|NP_043185.1| quinolinate synthetase [Cyanophora paradoxa]
MSIFLKNKQFENITSQEQTKNNYKQLINDIQTLKKDLNAIILAHYYQEPDIQDVADFLGDSLGLAREAAK
TNADIIVFAGVHFMAETAKILNPEKMVLLPDLNAGCSLADSCPPEIFSEFKKAHSDHLVISYINCSASIK
AMSDIICTSANAVDIVNKIPLTQPILFAPDQNLGRYVISKTGRDLLLWPGSCIVHETFSEKKIFEFQSLY
PTAEVIAHPECEPTILKHANYIGSTTSLLQYVKNSKKTTFIVITEPGIIHQMKKSCPEKQFLALPTVSGC
ACNECPHMRLNTLEKLYLAMKTRSPQIEIPESILLNAKKPIERMLEMSN

>gi|302191586|tpg|DAA33881.1| TPA_inf: one-helix protein 2 [Cyanophora paradoxa]
MSQNAPAAFTFGPAALLSGSCSRAPAVPRSSAVCLGSRSARRLPRAAGRARTVFSAEPAVRLELQGTPVG
IRGQSVGDASAGIRAELDERAKAESSKAPLVLETEIIVEEDEDEDENVANKLNRVSATSVGDFDNPSFEC
PYPNDKIKGGRITFDEQVAIAKRLTADWEYDRLMEVYERKRLFGMTPRAEVINGRVAMLGLLLGWLTERI
TGFTFLEQIGLGN

>gi|11467413|ref|NP_043270.1| photosystem I subunit VII [Cyanophora paradoxa]
MAHTVKIYDTCIGCTQCVRACPTDVLEMVPWDGCRANQIASAPRTEDCVGCKRCESACPTDFLSIRVYLG
AETTRSMGLGY

>gi|321268749|gb|ADW79198.1| NADH dehydrogenase subunit 5 [Cyanophora paradoxa]
MYLTLVFLPLISALVAFFVRFIGNKYAAYICTSLLGFTFILSIKSFYYIALLQNSCYIQTLPWLFGENLI
VFWGFLFDSVTCTMLIVVTSISFLVHFYSIEYMGSDPHLGRFMSYLSFFTFFMLILVTADNMVQMFVGWE
GVGLCSYLLINFFFNRIQANKAALKAMVMNRIGDFGLSLGIMALFYVCKSLDYHVIFSSILLFVDNSFYF
FNIKINLITCICLLLFIGAVGKSAQIGLHTWLPDAMEGPTPVSALIHAATMVTAGVFLIIRCSFLFEFSE
TALDILTILGALTAFFAATTGLLQNDAKRVIAYSTCSQLGYMVFVCGISGYSTSLFHLANHAFFKALLFL
TAGSLIHAVHDEQDFRKMGGLAYILPFSYSMLLVGSLSLTGFPFLTGFYSKDMILELTFSTYLIKGTFAY
ILGVLSAFCTAFYSFRLIFWAFLAKPNGYKHTYSHASESNFFITFPLGVLALASIFVGYLFRDMFIGVGT
SFWNNSIFILPENNFVLESEFIPVYNKLTPVVFSFGGLIIAFCFYNFLIKKIFIVKIFYIKFYTFLNKRW
YFDKIYNEFIALPIISFGYKITFKFIDRGILEIFGPTGLITNFTYLSKNISSIQSGLMYHYLFIILLGIT
ITLFTVIVIIQKMLYVSTNLVLIFILAVIGSSLKN

>gi|77176711|gb|ABA64470.1| DNA-dependent RNA polymerase II largest subunit [Cyanophora paradoxa]
IGFLNTILKVLRCVCFNCSKILCDKNDVRFKAAQRIKRPEAKLRAVMDICKSKSMCEGGEELDMNVSLDP
AAADKAGVPKRVGCGNPQPKIMKDGLKLTAEFKKTLDENQEKKIILMPEQVYNIFKRISDEDCRHMGLDP
RWARPDWFCITHLPVPPAAVRPGIAMNSVQRAEDDLTSKLMDIVRANAQLRKNEQNAAPAHHINELVTQL
QYHIATYMDNELPGIPPAQQRSGRALKSICQRLKGKEGRIRGNLMGKRVDFSARTVITADPNLGIDQVGV
PRSIALNLTTPEIVTPYNMDRMYQLIRAGPTEYPGARYIIRSDGTRFDLRYVRKASDLHLEPGYRVERHI
QDGDYVLFNRQPSLHKMSIMAHRIKVMPYSTFRLNLSVTSPYNADFDGDEMNLHVPQSFETRAEASEIIA
VPRQIVSPQSNRPVMGIVQDTLMASQKMTLRDTFIEKDVIMNIVMHLDSFDGRLPIPAIVKSPKGPRWTG
KQLFSTFLPNVNVVRFHSTHPDGESTDISPGDTQVRIENGELLCGIVCKRTLGTSAGSLIHVIMNEHGPD
TARVFFNMTQKVINNWLINVGFSVGIGDTIADDRTMESINSTLKKAKEEVDTVVIEAQQGKMELQPGRSF
IESFESKVNRILNQARDAAGKTAQGSLQRSNNVKTMLTSGSKGSFINISQMFACVGQQNVEGKRIPFGFR
NRTLPHFTKDDYGPESRGFVENSYLRGLTPQEFFFHAMGGREGLIDTAVKTSETGYIQRRLIKAMEDVMV
QYDNTTRNSMGEIIQFLYGEDGMAGEFIEGQRLESLELDDKEMEKKFKMNLDDRNFGEGFLDPDVAAEIR
GSAVIRHQLDKEYEQLLKDREQLRSEIVQSGEGAVHLPVNLKRLIWNAQKIYKVDTSKPSDLRPDIILQG
VELLSTQLVVIAGEDTLSREAQENATRLFNIHLRATLATKRVLSEYRLSAAALEWLLGVIESRFNQAIAH
PGEMVGAIAAQSIGEPATQM

>gi|193875702|gb|ACF24487.1| eukaryotic translation elongation factor 2 [Cyanophora paradoxa]
YVSKMVPTSDRGRFYAFGRVFSGTIRTGMKARIMGPNYVPGKKDDLFVKNIQRTVIMMGRYVEAVEDIPC
GNTCGLVGMDQFLVKSGTISDSEVAHNIKVMKFSVSPVVRVAVEPKNPGDLPKLVEGLKRLSKSDPCVQC
YTEESGEHIVAGVGELHLEICLKDLQEEFAGIDLKINDPVVSYRETVSTKSNQTCLSKSPNKHNRIYCEA
EPFAEGLAEAIESGKVNPRDDPKIRSKIMADEFGWDVTEARKIWTFGPDTNGPNVLVDTTKAVQYLNEIK
DSCVAAFQWATKEGALCEENMRAIRFNVMDVVLHADAIHRGGGQIIPTARRVYYAAELTAAPRLMEPVYL
CEIQTPENAIGGIYSVLNRKRGVIIAEEQRPGTPLYNVKAYLPVNESFGFTSDLRAATS

>gi|11467344|ref|NP_043201.1| hypothetical protein CypaCp064 [Cyanophora paradoxa]
MNVLSYFTWFVHLSSVLEWLNIIYFFLLYTKLKKNLSLKTFIFSFFISFCSALCACTLHFFNNQSFYYFL
INLQSFLTLFANITLYFSILIYKQQILKNQNY

>SP1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------IPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQ
LKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSW
VQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSE-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------VFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVK
DDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMG-----------------
------------------------------------------------------------
------------------------------------------------------------
FTVLGVFLITK-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------HVIDSVLERRRRR-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------QLQKRVLDAAAKRAE
LESEGSNGTR--------ESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACS
SHLTSCPLCRRRIDLAVKTYRH--------------------------------------

>gi|11467301|ref|NP_043158.1| allphycocyanin beta subunit [Cyanophora paradoxa]
MQDAITAVINAADVQGKYLDTASVEKLKSYFQTGELRVRAAATIAANSSAIIKEAVAKSLLYSDITRPGG
NMYTTRRYAACIRDLDYYVRYATYAMLAGDTSILDERVLNGLKETYNSLGVPVGATIQAIQAAKEVTAGL
VGPDAGREMGIYYDYISSGLG

>gi|6102770|emb|CAB59195.1| ubiquinol-cytochrome C reductase iron-sulfur subunit precursor [Cyanophora paradoxa]
LRLARAAGAIKPSVNARVGALLARPHATNAVATPAYSELSSVPLYQQEKKIERFTPGDENRRPFAYLVIG
SARFAYMAWTRVAVLKVISTMSASADVLALASVEVDVSSIPVGQNVTIKWRGKPVFIRHRTAAEIAEAGA
VNISELRHQETDAQRAQKPNFLIMLGVCTHLGCVPLGNAGDYNGWFCPCHGSHYDISGRIRKGPAPLNLE
VPPYKFTSDSTVLIG

>gi|321268766|gb|ADW79215.1| hypothetical protein [Cyanophora paradoxa]
MMQNILNSLSQKFVRIASDVLFTIIVEFKWCWETNPLFLVFIIYILFHLLIFLLYYLYPKLKRVFIRLFR
MVKLFIKKLIFFYRKVKFYYNRAKFYSKKKNRAILKRDARNFYDRKSEQFLDWLPGFLYKVYIVCSIIVE
IIIFIYLVMLPYGCYYCGQVFFEEWAKLSVYTMQMIYPWPFFKKTWEFIIWFLVEGAWGYIYELTIESSA
EKYEWVAVVYDKMRKKIISWSLSISANKIWFCQVFYPAWKSVIDFTIGFLYISFYVWFMQKDYLKTGTGL
KKKFIVWIDYLLEIGAQKSVRVSQRYVILPHFLPKLCYFMYFPYMFFYFFETFSEGLKTFKGTPYVYIPC
EHIPQVNFYVAFFFQLLEFTIDYLFFCIWWFYLFSEVDNCQKLSKTWSPKYPHRKAIEKIWMNPLIAVMW
NPEDERIWGTYRWPVHRRALKVFIDIRQVAKQMINGKRPLSLMIYVKLFYSFIRIFDLSPLYRILKKKKK
SKIEQKQLSIKLNDSAKKRKNKYTRKQKRLYSKKHKKLRNTTPFS

>gi|11467414|ref|NP_043271.1| hypothetical protein CypaCp134 [Cyanophora paradoxa]
MNNKIDNFLKQKKLIKVISGLNNFNTTHVIKIAKAASKTNASFIDIAAAPKLVEKVKKEVPNLPICVSAI
KPELFVPCVKAGAELIEIGNFDSLYNQGYKINFSDVLSLVKQTRSLLPDTPLSVTIPYLLPLNLQLELAY
RLEDLNVDLIQTEGKINKITSLLDNRNIETILPTLASTYLIANNVTIPVICASGLTISTIELPFKLNASG
IGIGNAVSKLNSTEEMINLLNEISTRINYSTVL

>gi|321268745|gb|ADW79194.1| ribosomal protein L2 [Cyanophora paradoxa]
MNNIKVVSKLLKSPCKLGIKKGGRNNTGVKTIQHRGGGHKKNYYIIDYKRHFKQISLIINKQYDPNRSTI
IGTAYNYYGFLLNIILPNRTNIGDVIFNSDKILDSTLMIKNGNSNYIFNINPGLLVNNIELKINKGSQLV
RSAGTYAQIMAHNKPLNNKYKTHIENIKNQKYTAIRLPSGEIRLVCSFSKATIGVLSNPDHKLKKIEKAG
RSRWLNRRPMVRGIAMNPVDHPHGGRTNGGRPSVTPYSRITKGKPTVFFSKNKKYYILKKRI

>gi|8928433|sp|Q9ZSW1.1|TBB1_CYAPA RecName: Full=Tubulin beta-1 chain; AltName: Full=Beta-1-tubulin
MREIVHVQGGQCGNQIGAKFWEVISDEHGVDPTGTYHGDSDLQLERINVYYNEATGGRYVPRAVLMDLEP
GTMDSVRAGPYGQLFRPDNFIFGQSGAGNNWAKGHYTEGAELIDSVLDVVRKEAEGCDCLQGFQITHSMG
GGTGSGMGTLLIAKVREEYPDRMMCTYSVFPSPKVSDTVVEPYNATLSVHQLVENADEVMVIDNEALYDI
CFRTLKLTTPTYGDLNHLVSACISGVTCCLRFPGQLNSDLRKLAVNLIPFPRLHFFMIGFVPLTSRGSQQ
YRALTVPELTQQMFDAKNMMCAADPRHGRYLTASALFRGRMSTKEVDEQMLNVQNKNSSYFVEWIPNNIK
ASVCDIPPKGLKMSATFIGNSTAIQEMFKRVSEQFTAMFRRKAFLHWYTGEGMDEMEFTEAESNMNDLVS
EYQQYQDATAEEEGEGDEEEAEGEAAA

>gi|321268762|gb|ADW79211.1| hypothetical protein [Cyanophora paradoxa]
MFNYIIILFTLIIIFNLIVIIKLNLSNKYSKIIFFKLQKNIIISGFILRFICINIIYNPLFEFLRKHFVI
NYNIYYQNWLEFILFNSKNSINQFNNDNGDFFYKVVLQSIEYDELNVTCLFFIHSSFYEFFIMINILGFL
IKFIKDDLYKIYLFIYLYIKQYSIKFSNYLFYNYLRNFNFIFLRLYKYLKNTVDSTSANYKISNTLSKIL
INNDSEKLSLLNSLNINEHQLIKVVLFYFCCFYFLFFYLQIYIFETLYVSFLLLPHYISMLLYLIRFMEK
NLFLHFNSREKNSFGNRRFFISYPQLYILIHELSMLIIVNILFLLLLIFICYYIYMFFINILNY

>gi|11467428|ref|NP_043285.1| photochlorophyllide reductase subunit L [Cyanophora paradoxa]
MKLAVYGKGGIGKSTTSCNISVALAKRGKKVLQIGCDPKHDSTFTLTGHLIPTIIDTLQEKDFHYEDIWP
EDVIYKGYAGVDCVEAGGPPAGAGCGGYVVGETVKLLKELNAFDEYDIILFDVLGDVVCGGFASPLNYAD
YCLIVTDNGFDALFAANRIAASVREKARTHQLRLAGLIGNRTTKSDLIEKYTENVPIPILQLLPLIEDIR
ISRVKGKTLFEMSESNPELSPICDYYLNIADQILAKPEGIIPNEVLDRDLFTLLSDFYLNMDSSESSNLT
LV

>gi|77176713|gb|ABA64471.1| DNA-dependent RNA polymerase II largest subunit [Cyanophora paradoxa]
HIGFLNTILKVLRCVCFNCSKILCDKNDVRFKAAQRIKRPEAKLRAVMDICKSKSMCEGGEELDMNVSLD
PAAADKAGVPKRVGCGNPQPKIMKDGLKLTAEFKKTLDENQEKKIILMPEQVYNIFKRISDEDCRHMGLD
PRWARPDWFCITHLPVPPAAVRPGIAMNSVQRAEDDLTSKLMDIVRANAQLRKNEQNAAPAHHINELVTQ
LQYHIATYMDNELPGIPPAQQRSGRALKSICQRLKGKEGRIRGNLMGKRVDFSARTVITADPNLGIDQVG
VPRSIALNLTTPEIVTPYNMDRMYQLIRAGPTEYPGARYIIRSDGTRFDLRYVRKASDLHLEPGYRVERH
IQDGDYVLFNRQPSLHKMSIMAHRIKVMPYSTFRLNLSVTSPYNADFDGDEMNLHVPQSFE

>gi|77176711|gb|ABA64470.1| DNA-dependent RNA polymerase II largest subunit [Cyanophora paradoxa]
IGFLNTILKVLRCVCFNCSKILCDKNDVRFKAAQRIKRPEAKLRAVMDICKSKSMCEGGEELDMNVSLDP
AAADKAGVPKRVGCGNPQPKIMKDGLKLTAEFKKTLDENQEKKIILMPEQVYNIFKRISDEDCRHMGLDP
RWARPDWFCITHLPVPPAAVRPGIAMNSVQRAEDDLTSKLMDIVRANAQLRKNEQNAAPAHHINELVTQL
QYHIATYMDNELPGIPPAQQRSGRALKSICQRLKGKEGRIRGNLMGKRVDFSARTVITADPNLGIDQVGV
PRSIALNLTTPEIVTPYNMDRMYQLIRAGPTEYPGARYIIRSDGTRFDLRYVRKASDLHLEPGYRVERHI
QDGDYVLFNRQPSLHKMSIMAHRIKVMPYSTFRLNLSVTSPYNADFDGDEMNLHVPQSFETRAEASEIIA
VPRQIVSPQSNRPVMGIVQDTLMASQKMTLRDTFIEKDVIMNIVMHLDSFDGRLPIPAIVKSPKGPRWTG
KQLFSTFLPNVNVVRFHSTHPDGESTDISPGDTQVRIENGELLCGIVCKRTLGTSAGSLIHVIMNEHGPD
TARVFFNMTQKVINNWLINVGFSVGIGDTIADDRTMESINSTLKKAKEEVDTVVIEAQQGKMELQPGRSF
IESFESKVNRILNQARDAAGKTAQGSLQRSNNVKTMLTSGSKGSFINISQMFACVGQQNVEGKRIPFGFR
NRTLPHFTKDDYGPESRGFVENSYLRGLTPQEFFFHAMGGREGLIDTAVKTSETGYIQRRLIKAMEDVMV
QYDNTTRNSMGEIIQFLYGEDGMAGEFIEGQRLESLELDDKEMEKKFKMNLDDRNFGEGFLDPDVAAEIR
GSAVIRHQLDKEYEQLLKDREQLRSEIVQSGEGAVHLPVNLKRLIWNAQKIYKVDTSKPSDLRPDIILQG
VELLSTQLVVIAGEDTLSREAQENATRLFNIHLRATLATKRVLSEYRLSAAALEWLLGVIESRFNQAIAH
PGEMVGAIAAQSIGEPATQM

>gi|68566162|sp|Q5CC93.1|UCRIA_CYAPA RecName: Full=Cytochrome b6-f complex iron-sulfur subunit 1, cyanelle; AltName: Full=Plastohydroquinone:plastocyanin oxidoreductase iron-sulfur protein 1; AltName: Full=Rieske iron-sulfur protein 1; Short=ISP 1; Short=RISP 1; Flags: Precursor
MAFTTTAVVAPRGAKITGQSSTCAIQNGKTVAVGTSKQVGSFKPVFAAAKPAKETTFSVSCSAASDDVPD
MGKRKLMNLLLLGAIAGPVAGAGGPFVSFLVPPKAGGGAGAGQAAKDALGNDVKVSSWLETHKPGDRSLA
QGLKGDATYLIVKEDGTLENYGLNAVCTHLGCVVPWNASENKFMCPCHGSQYDRTGKVVRGPAPLSLALA
HVSVLEDGVVAFEPWTETDFRTNTAPWWK

>gi|158939329|gb|ABW83990.1| granule-bound starch synthase [Cyanophora paradoxa]
MNIAPVSELQAAIDQAEKKLTIVFVGSECTPWSKTGGLGDVMRDLPVNLAQRGHRVMSIQPRYDQYFDAW
DTAVRSSIKVNGKLEDVGFFHITSKGVDRIFIDHPWFLAKVWGITGNKLYGAKTGVDYPDNPMRFALMCQ
AALEAPLRIPLPDPAGTVYGEDVIFVCNDWHSALVPIYLKANYKTRGLYQNAKSIFLLHNIIYQGRFPLE
FWPALNLPEAAKKDLVFESCFAPPPLDGISEQPIISLKPMAMMNFLQAGFIHADRICTVSPQFAAEVASG
PRGGVELDKYIRAKGITGIMNGMDIEMWDASKDKFLVTKYTASSVDEGKAANKAVLQAEMGLKVSPTTPL
IAFVGRLDDQKGADCMVEAMPYLVNTLGAQVVCYGSGREDMAAKFKALEKQFPGMAKGKTAFVPKEEHTL
MAGADYVLMPSRFEPCGLVQLHAMKYGAVPIVSCTGGLKDSVIPECGFTFEEIPSPEYPGMKISPELIAK
GTKIIEEGCKEALAGYGSKAFAGMRAACMKQDFAWKKRVLVYEKVFYETLGIDRGAPVTAKASPVAPEPS
AAPAPATISAATSGGILPVPKAAAPKAPKVGA

>gi|68566161|sp|Q5CC92.1|UCRIB_CYAPA RecName: Full=Cytochrome b6-f complex iron-sulfur subunit 2, cyanelle; AltName: Full=Plastohydroquinone:plastocyanin oxidoreductase iron-sulfur protein 2; AltName: Full=Rieske iron-sulfur protein 2; Short=ISP 2; Short=RISP 2; Flags: Precursor
MSAFACSAVAAPARGAIKANSSSVCAIENGKAVAVGTSKQVGAFKPVFAAAKAAKATTFSISCSAASDEV
PDMGKRKLMNLLLLGAIAGPTIGAGGPFVSFLVPPKSGGGAGAGQAAKDAAGNDIKVEKWLETXKPGDRS
LAQGLKGDATYLIVKEDGTLEKYGLNAVCTHLGCVVPWNQSEGKFMCPCHGSQYDRTGKVVRGPAPLSLA
LAHVNVLEDGVVAFEPWTETDFRTNTAPWWK

>gi|5304835|emb|CAB46076.1| ATP citrate lyase [Cyanophora paradoxa]
MASPQMAQLFSRSTQALIFNYKPNPVQRMLDFDFLARRETPSVAGLINVGSKGGFEKVFFGTKEIAVPVY
ASTQDAVRAHPNADVFINFASFRSAYQSSLEALEIPSIRVVVIIAEGVPEGDVKKLIAVSKKKGKIIIGP
ATVGGVQAGAFKIGDTAGTVDNIISCKLHRPGSVGFVSKSGGLSNECYNILSRTTDGLFEGIAVGGDAFP
GTTLADHVIRFQHIPQIVVLGELGGTDEYEIVEAMKKGVITKPICAGVSGTCAKVFPSEVQFGHAGAKSG
GMAESAEAKNQALRDAGAHVPTSFEELPDTIGKVYKDLVNSGKHVPVQDIPAPEMPMDIKKAMKAGKIRA
STNIICTISDDRGEEPTYAGIPMSEMIEQEYSVGDVLALLWFKRQLPKYATRFLEMCLIICADHGPCVSG
AHNAIIAARAGKDLVSCVASGLLTIGPRFGGAIDDAARDFKAACDAGMAADEFVESMKKLGKRIAGIGHR
IKTAENPDKRVQLLSEYADRHFPTTKYLNFAKSV

>gi|5304837|emb|CAB46077.1| ATP citrate lyase [Cyanophora paradoxa]
MASPQMAQLFSRSTQALIFNYKPNPVQRMLDFDFLARRETPSVAGLINVGSKGGFEKVFFGTKEIAVPVY
ASTQDAVRAHPNADVFINFASFRSAYQSSLEALEIPSIRVVVIIAEGVPEADVKKLIAVSKKKGKILIGP
ATVGGVQAGAFKIGDTAGTVDNIISCKLHRPGSVGFVSKSGGLSNECYNILSRTTDGLFEGIAVRGDAFP
GTTLADHVIRFQHIPQVKMIVVLGELGGTDEYEIVEAMKKGVITKPICAWVSGTCAKVFPSEVQFGHAGA
KSGGMAESAEAKNQALRDAGAHVPTSFEELPDTIGKVYKDLVNSGKHVPVQDIPAPEMPMDIKKAMKAGK
IRASTNIICTISDDRGEEPTYAGIPMSEMIEQEYSVGDVLALLWFKRQLPKYATRFLEMCLIICADHGPC
VSGAHNAIIAARAGKDLVSCVASGLLTIGPRFGGAIDDAARDFKAACDAGMAADEFVESMKKLGKRIAGI
GHRIKTAENPDKRVQLLSEYADRHFPTTKYLNFAKSVEAYTLTKSNNLILNVDGCIGALFCDFLVSSQCF
TDEEIQEVLDIGTMNGLFVQARTIGLIGHALDQKRLKQPLYRHPWDDILYAEEYLTREQKEEARMSGNKS
QKDFVEMQLRS

>gi|11467414|ref|NP_043271.1| hypothetical protein CypaCp134 [Cyanophora paradoxa]
MNNKIDNFLKQKKLIKVISGLNNFNTTHVIKIAKAASKTNASFIDIAAAPKLVEKVKKEVPNLPICVSAI
KPELFVPCVKAGAELIEIGNFDSLYNQGYKINFSDVLSLVKQTRSLLPDTPLSVTIPYLLPLNLQLELAY
RLEDLNVDLIQTEGKINKITSLLDNRNIETILPTLASTYLIANNVTIPVICASGLTISTIELPFKLNASG
IGIGNAVSKLNSTEEMINLLNEISTRINYSTVL

>gi|321268766|gb|ADW79215.1| hypothetical protein [Cyanophora paradoxa]
MMQNILNSLSQKFVRIASDVLFTIIVEFKWCWETNPLFLVFIIYILFHLLIFLLYYLYPKLKRVFIRLFR
MVKLFIKKLIFFYRKVKFYYNRAKFYSKKKNRAILKRDARNFYDRKSEQFLDWLPGFLYKVYIVCSIIVE
IIIFIYLVMLPYGCYYCGQVFFEEWAKLSVYTMQMIYPWPFFKKTWEFIIWFLVEGAWGYIYELTIESSA
EKYEWVAVVYDKMRKKIISWSLSISANKIWFCQVFYPAWKSVIDFTIGFLYISFYVWFMQKDYLKTGTGL
KKKFIVWIDYLLEIGAQKSVRVSQRYVILPHFLPKLCYFMYFPYMFFYFFETFSEGLKTFKGTPYVYIPC
EHIPQVNFYVAFFFQLLEFTIDYLFFCIWWFYLFSEVDNCQKLSKTWSPKYPHRKAIEKIWMNPLIAVMW
NPEDERIWGTYRWPVHRRALKVFIDIRQVAKQMINGKRPLSLMIYVKLFYSFIRIFDLSPLYRILKKKKK
SKIEQKQLSIKLNDSAKKRKNKYTRKQKRLYSKKHKKLRNTTPFS

>gi|11467297|ref|NP_043154.1| photosystem I assembly protein Ycf3 [Cyanophora paradoxa]
MPRSQRNDNFIDKTFTVIADLILKILPVSKKTKEAFAYYRDGMSAQSEGAYAEALENYYEALRLEEDPYD
KSYTFYNIALIHTSNGDQTKALEYYRQALDLNPKMPQALNNMAVIYHAQGEQAAEQGDMEMAEALFDQAA
FYWKQAIRLAPDNYIEAQNWLKTTGRSKLDILI

>gi|11467345|ref|NP_043202.1| ribosomal protein L33 [Cyanophora paradoxa]
MARAKGVRILVTLECTECRSNGERLGGGVSRYATKKNRRNTPNRLELNKFCPYCKKHVLHREIK

>gi|321268765|gb|ADW79214.1| NADH dehydrogenase subunit 9 [Cyanophora paradoxa]
MKIKLQMELQKFSLKHFSQLITKIIPRLIKDVFIINNELILIVENNNLNSTLFFLKYHTYTQYKVLCDIT
AVDFLDRIERFEVVYQFLSVSYASRLRIKVNLKETELINSISTLYPCANWYEREIWDLFGIFFMNHPDLR
RILTDYGFEGHPLKKDFPLSGYLEVRYDDIVKQVICEPVDITQEFRNFNFSSPWEITQ

>gi|321268760|gb|ADW79209.1| NADH dehydrogenase subunit 9 [Cyanophora paradoxa]
MKIKLQMELQKFSLKHFSQLITKIIPRLIKDVFIINNELILIVENNNLNSTLFFLKYHTYTQYKVLCDIT
AVDFLDRIERFEVVYQFLSVSYASRLRIKVNLKETELINSISMLYPCANWYEREIWDLFGIFFMNHPDLR
RILTDYGFEGHPLKKDFPLSGYLEVRYDDIVKQVICEPVDITQEFRNFNFSSPWEITQ

>gi|11467364|ref|NP_043221.1| glutamine amidotransferase [Cyanophora paradoxa]
MINSKNNSPIEISIIDYQMGNLYSVCKGIERSGGIPKIINSAEEIKKATALILPGVGSFDPAMKQLKKQD
LINPIKDAISEKKPFLGICLGLHLLFEESEEGIESGLGILSGSVKRIKNEPEITIPHMGWNQLQLTNPKC
YLWDGLTKYPWVYFVHSYFAQPKNPNVIAAAVTHGTQQVTAAIQYENISAVQFHPEKSASIGLHMLNNFV
QQSCN

>gi|1360714|emb|CAA77503.1| Fragment of DNA-dependent RNA polymerase rpoC1 subunit [Cyanophora paradoxa]
KITKPETINYRTLKPEMDGLFCEKIFGPVKDWECHCGKYKSIFYRGVICERCGVEITESQVRRHRMGYIE
LAAPVTHIWYLKGIPSYISILLNKKVKEIEQVVYFNAYVVLNPGTSDLLNYGDILTEDDEKWPYIEEKLY
TKELMDVELGIGAEAIQRLLSDLDLQAEAKTIREILISNSDKKKNTQKRAKLIKKLRIINNFIATKAK

>gi|11467372|ref|NP_043229.1| RNA polymerase beta' subunit [Cyanophora paradoxa]
MPKHEQYFDYVKINLASPERIRQWGERILKNGEIVGKITKPETINYRTLKPEMDGLFCEKIFGPVKDWEC
HCGKYKSIFYRGVICERCGVEITESQVRRHRMGYIELAAPVTHIWYLKGIPSYISILLNKKVKEIEQVVY
FNAYVVLNPGKSDLLNYGVILTEDDEKWPYIEEKLYTKELMDVELGIGAEAIQRLLSDLDLQAEAKTIRE
ILISNSDKKKNTQKRAKLIKKLRIINNFIATKAKPEWMILSLIPVIPPDLRPMVQLDGGRFATSDLNDLY
RRVINRNNRLLRLQEVFAPEIVVRNEKRILQEAVDALIDNGRRGRIVVGAKNRPLKSLSDIIEGKQGRFR
QNLLGKRVDYSGRSVIVVGLQLKLYQCGLPWEMAIELFQPFVIHRLIHQGLVNNIKAAKKLIQSNDPIIR
DILEEVIQNHPVLLNRAPTLHRLSIQAFEPILVEGRAIQLHPLVCPAFNADFDGDQMAVHVPLSLEAQTE
ARLLMLASNNLLSPATGQPIVTPSQDMVLGCYYLTVDNLKNQKGKGSYFINSEDVLIAYEQQRIDLHSYI
WVRFDTFSFDDILEEKNIQQVLYKREIDEFGTVIKVYNTRRIREDKDGFCLTQYIITTAGRVLFNKVVQK
ALIMEI

>gi|8928433|sp|Q9ZSW1.1|TBB1_CYAPA RecName: Full=Tubulin beta-1 chain; AltName: Full=Beta-1-tubulin
MREIVHVQGGQCGNQIGAKFWEVISDEHGVDPTGTYHGDSDLQLERINVYYNEATGGRYVPRAVLMDLEP
GTMDSVRAGPYGQLFRPDNFIFGQSGAGNNWAKGHYTEGAELIDSVLDVVRKEAEGCDCLQGFQITHSMG
GGTGSGMGTLLIAKVREEYPDRMMCTYSVFPSPKVSDTVVEPYNATLSVHQLVENADEVMVIDNEALYDI
CFRTLKLTTPTYGDLNHLVSACISGVTCCLRFPGQLNSDLRKLAVNLIPFPRLHFFMIGFVPLTSRGSQQ
YRALTVPELTQQMFDAKNMMCAADPRHGRYLTASALFRGRMSTKEVDEQMLNVQNKNSSYFVEWIPNNIK
ASVCDIPPKGLKMSATFIGNSTAIQEMFKRVSEQFTAMFRRKAFLHWYTGEGMDEMEFTEAESNMNDLVS
EYQQYQDATAEEEGEGDEEEAEGEAAA

>gi|11467310|ref|NP_043167.1| photosystem II 47 kDa protein [Cyanophora paradoxa]
MGLPWYRVHTVVLNDPGRLIAVHLMHTALVAGWAGSMALYEIAVFDPSDPVLNPMWRQGMFVLPFMVRLG
ITNSWGGWTINGENVTDPGFWSFEGVAAAHIGLSGLLFLAAIWHWVYWDLELFRDPRTGEPALDLPKMFG
IHLFLSGLLCFGFGAFHLTGLFGPGMWVSDAYSITGRVQPVAPAWGPEGFNPFNPGGVVSHHIAAGIVGI
LAGLFHLSVRPPQRLYKALRMGNIETVLSSSISAVFFAAFIVAGTMWYGSAATPVELFGPTRYQWDQEYF
HQEMERRVQKDVAAGASLSEAWNRIPAKLAFYDYIGNNPAKGGLFRAGPMNKGDGIAESWLGHATFKDKE
GRELTVRRMPTFFETFPVVLIDKDGVLRADIPFRRAESKYSIEQMGVTVSFYGGKLDGQTFTDAPTVKKY
ARKAQLGEAFEFDRETLKSDGVFRSSARGWFTFGHASFALIFFFGHLWHGGRTLFRDVFAGIGEEVTEQV
EFGAFQKVGDKTTRKQEAG

>gi|11467307|ref|NP_043164.1| hypothetical protein CypaCp027 [Cyanophora paradoxa]
MLFASNAIILKIKQRNSNSYIYTLYTYEEGLKEVIIFTNQKILCSNLKLYRIYFVLFKKGAPWDQIQRLY
PLFFYPKIEQNPLKMIVLEYLSELIIYQLYSPENCTFIYFIFHYTLFQLNICSNNMILPIFISSLYSLLK
FLGWEPELSNCVYTGESLNSENSNLTDSKIGFSASYGGIVKLNVLPKQEYIGFFNKDELFIFTNDN

>gi|9369269|emb|CAB99190.1| cytochrome c6 [Cyanophora paradoxa]
MAAFVAALPVIPSKAFIAGKADVAKAPVATNKGGVRMSKKATFTAAATAAALLAASPVFAADGAAIFTNN
CAACHAGGNNVIAAEKTLKKAALEQYLDGGYNVDAIKKQVTGGKNAMPAFGGRLAEDEIAAVAEYVYSQA
GNGW

>gi|321268754|gb|ADW79203.1| ribosomal protein S10 [Cyanophora paradoxa]
MIKIYIFSHYFLAINFFVKTITYCLSLKKIPFKVYPQPKKCSILTTLRSPHVNKNSMEHFKIEKFKYIIE
INNINNKISKKIFNKLYYYCPAGLTFYIKYQTNEFKK

>gi|11467413|ref|NP_043270.1| photosystem I subunit VII [Cyanophora paradoxa]
MAHTVKIYDTCIGCTQCVRACPTDVLEMVPWDGCRANQIASAPRTEDCVGCKRCESACPTDFLSIRVYLG
AETTRSMGLGY

