>MULAN_RING
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VVCLSSFKSCVFLECGHVCSCTECY--------------------
------------------------------------------------------------
----------------------RALPEPKKCPIC--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gi|321268754|gb|ADW79203.1| ribosomal protein S10 [Cyanophora paradoxa]
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------IKIYIFSHYFL
AINFFVKT----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------ITYCLSLKKIPFKVYPQPKKCSILTTLRSPHVNK---NSMEHFKIEKF--
----------------------------------KYIIEINNINN---------------
--------------------------------------KISK------------------
------------------------------------------KIFNKLYYYCPAGLTFYI
KYQTNEFKK---------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gi|11467287|ref|NP_043144.1| hypothetical protein CypaCp007 [Cyanophora paradoxa]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------DNFLFSFYII
FFSLIVLA----------------------------------------------------
---------------------------LISFLIQEIQKSRFLDLEITRLRKKIYQEKATE
KDYNNLASIYIKK-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------KLYSQAQKEFL--
-----------------------------------KILENKNLDK---------------
--------------------------------------SQLA------------------
------------------------------------------LIYNSLGYICSAQEQYEL
A-------------------------------------IEYYKKALFYIPDFILARINLA
RIFELKNLKTEAINMYQEVLIFDPKNQLAKRKLSIIENLIL-------------------
-------------------------------------------------------
>gi|321268749|gb|ADW79198.1| NADH dehydrogenase subunit 5 [Cyanophora paradoxa]
M-----------------------------------------------------------
----YLTLVFLPLISALVAFFVRFIGNKYAAYICTSLLGFTFILSIKSFYYIALLQNSCY
IQTLPWLFGENLIVFWGFLFDSVTCTMLIVVTSISFLVHFYSIEYMGSDPHLGRFMSYLS
FFTFFMLILVTADNMVQMFVGWE-------------------------------------
-------------------GVGLCSYLLINFFFNRIQANKA-------------------
---------ALKAMVMNRIGDFGL--------------------SLGIMALFYVCKSLDY
HVIFSSILLFVDNSFYFFNIKINLITCICL------------------------------
------------------------------------------------------------
-----LLFIGAVGKSAQIGLHTWLPDAMEGPT---PVSALIHAATMVTAGVFLIIRCSFL
FEFSETALDILTILGAL-------------------------------------------
------------------------------TAFFAATTGLLQNDAKRVIAYSTCSQLGYM
VFVCGISGYSTSLFHLANHAFFKALLFLTAGSLIHAV--HDEQDFRKMGGLAYILPFSYS
MLLVGSLSLTGFPFLTGFYSKDMILELTFSTYLIKGTFAYILGVLSAFCTAFYSFRLIFW
AFLAKPNGYK-------------------------------------HTYSHASESNFFI
TFPLGVLALASIFVGYLFRDMFIGVGTSFWNNSIFILPENNFVLE---------------
--------------------------------------SEFI------------------
------------------------------------------PVYNKLTPVVFSFGGLII
----------------------------------------AFCFYNFLIKKIFIVKIFYI
KFYTFLNKRWYFDKIYNEFIALPIISFGYKITFKFIDRGILEIFGPTGLITNFTYLSKNI
SSIQSGLMYHYLFIILLGITITLFTVIVIIQKMLYVSTNLVLIFILAVIGSSLKN
>gi|11467344|ref|NP_043201.1| hypothetical protein CypaCp064 [Cyanophora paradoxa]
MNVLSYFTWFVHLSSVLEWLNIIYFFLLYTKLKKNLSL----------------------
------------------------------------------------------------
--------------------------------------------------KTFIFSFFIS
FC----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------SALCACTLHFF--
---------------------NNQSFYYFLINLQSFLTLFANITL---------------
--------------------------------------YFSI------------------
------------------------------------------LIYKQQILKNQNY-----
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gi|11467328|ref|NP_043185.1| quinolinate synthetase [Cyanophora paradoxa]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------SIFLKNKQFENITSQEQTKNNYKQLINDIQTLKKD-
-LNAIILAHYYQEPDIQDVADFLG--------------------DSLGLAREAAKTNADI
-IVFAGVHFMAETAKILNPEKMVLLPDLNAGC----------------------------
---------------------------------------------SLADSCPPEIFSEFK
KAHSDHLVISYINCSASIKA---MSDIICTSA---NAVDIVNKIPLTQPILFAPDQNLGR
YVISKTGRDLLLWPGSC-------------------------------------------
------------------------------IVHETFSE----------------------
----------------------KKIFEFQSLYPTAEVIAHPECEPTILKHANYIGSTTSL
LQYVKNSKKTTFIVI---------------------------------------------
------------------TEPGIIHQMKKSCPEKQFLALPTVSGCACNECPHMRLNTL--
-----------------------------EKLYLAMKTRSPQIEI---------------
--------------------------------------PESI------------------
------------------------------------------LLNAKKPIERMLEMSN--
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gi|158939329|gb|ABW83990.1| granule-bound starch synthase [Cyanophora paradoxa]
MNIAPVSELQAAIDQAEKKLTIVFVGSECTPWSKTGGLGDVMRDLPVNLAQRGHRVMSIQ
PRYDQYFDAWDTAVRSSIKVNGKLEDVGFFHITSKGVDRIFIDHPWFLAKVWGITGNKLY
GAKTGVDYPDNPMRFALMCQAALEAPLRIPLPDPAGTVYGEDVIFVCNDWHSALVPIYLK
-------------------ANYK-------------------------------------
-------------------TRGLYQNAKSIFLLHNIIYQGRFPLEFWPALNLPEAAKKDL
VFESCFAPPPLDGISEQPIISLKP--------------------MAMMNFLQAGFIHADR
-ICTVSPQFAAEVAS--GPRGGVELDKYIRAK----------------------------
---------------------------------------------GITGIMNGMDIEMWD
ASKDKFLVTKYTASSVDEGKA--ANKAVLQAE---MGLKVSPTTPLIAFVGRLDDQKGAD
CMVEAMPYLVNTLGAQV-------------------------------------------
------------------------------VCYGSGREDMA-------------------
-------------------AKFKALEKQFPGMAKGKTAFVPKEEHTLMAGADYV------
------------------------------------------------------------
------------------------------------LMPSRFEPCGLVQLHAMKYGAVPI
VSCTGGLKDSVIPECGFTFEEIPSPEYPGMKISPELIAKGTKIIEEGCKEALAGYGSKAF
AGMRAACMKQDFAW------------------------KKRV------------------
------------------------------------------LVYEKV------------
----------------------------------------FYETLGIDRGAPVTAKASPV
APEPSAAPAPATISAATSGGILPVPKAAAPKAPKVGA-----------------------
-------------------------------------------------------
>gi|193875702|gb|ACF24487.1| eukaryotic translation elongation factor 2 [Cyanophora paradoxa]
Y-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------VSKMVPTSDRGRFYAFGR
VFSGTIRTGMKARIMGPNYVPGK-------------------------------------
---------------------------KDDLFVKNIQRTVIMMGRYVEAVEDIPCGNTCG
LV----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-GMDQFLVKSGTISDSEVAHNIKVMKFSVSPVVRVAVEPKNPGDLPKLVEG---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------LKRLSKSDPCVQCYTEESGEHIVAGVGELHLEIC
LKDLQEEFAGIDLKI---------------------------------------------
------------------NDPVVSYRETVSTKSNQTCLSKSPNK---HNRIYCEAEPF--
------------------------------AEGLAEAIESGKVNP------------RDD
PKIRSKIMADEFGWDVTEARKIWTFGPDTNGPNVLVDTTKAV------------------
------------------------------------------QYLNEIKDSCVAAFQWAT
KEGALCEENMRAIRFNVMDVVLHADAIHRGGGQIIPTARRVYYAAELTAAPRLMEPVYLC
EIQTPENAIGGIYSVLNRKRGVIIAEEQRPGTPLYNVKAYLPVNESFGFTSDLRAATS--
-------------------------------------------------------
>gi|302191586|tpg|DAA33881.1| TPA_inf: one-helix protein 2 [Cyanophora paradoxa]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------S--------------------QNAPAAFTFGPAALLS
GSCSRAPAVPRSSAVCLGSRSARRLPRAAGRA----------------------------
---------------------------------------------RTVFSAEPAVRLELQ
GTPVGIRGQSVGDASAGIRAE---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------LDERAKAESSKAPLVLETEII
VEEDEDEDENVANKL---------------------------------------------
-----------------------------------------------NRVSATSVGDF--
------------------------DNPSFECPYPNDKIKGGRITF---------------
--------------------------------------DEQV------------------
------------------------------------------AIAKRL------------
------------------------------------------------------------
---TADWEYDRLMEVYERKRLFGMTPRAEVINGRVAMLGLLLGWLTERITGFTFLEQIGL
GN-----------------------------------------------------
>gi|77176711|gb|ABA64470.1| DNA-dependent RNA polymerase II largest subunit [Cyanophora paradoxa]
I---------GFLNTILKVLRCVCFNCSKILCDKNDVRFKAAQRIKRPEAKLRAVM----
------------------------------------------------------------
----------DICKSKSMCEGGEELDMNVSLDPAAADKAGVPKRVGCGNPQPKIMKDGLK
LTAEFKKTLDENQEKKIILMPEQVYNIFKRISDEDCRHMGLDPRWARPDWFCITHLPVPP
AAVRPGIAMNSVQRAEDDLTSKLMDIVRANAQLRKNEQNAAPAHHINELVTQLQYHIATY
MDNELPGIPPAQQRSGRALKSICQRLKGKEGRIRGNLMGKRVDFSARTVITADPNLGIDQ
VGVPRSIALNLTTPEIVTPYNMDRMYQLIRAGPTEYPGARYIIRSDGTRFDLRYVRKASD
LHLEPGYRVERHIQDGDYVLFNRQPSLHKMSIMAHRIKVMPYSTFRLNLSVTSPYNADFD
GDEMNLHVPQSFETRAEASEIIAVPRQIVSPQSNRPVMGIVQDTLMASQKMTLRDTFIEK
DVIMNIVMHLDSFDGRLPIPAIVKSPKGPRWTGKQLFSTFLPNVNVVRFHSTHPDGESTD
ISPGDTQVRIENGELLCGIVCKRTLGTSAGSLIHVIMNEHGPDTARVFFNMTQKVINNWL
INVGFSVGIGDTIADDRTMESINSTLKKAKEEVDTVVIEAQQGKMELQPGRSFIESFESK
VNRILNQARDAAGKTAQGSLQRSNNVKTMLTSGSKGSFINISQMFACVGQQNVEGKRIPF
GFRN-------------------------------------------RTLPHFTKDDYGP
ESRGFVENSYLRGLTPQEFFFHAMGGREGLIDTAVKTSETGYIQRRLIKAMEDVMVQYDN
TTRNSMGEIIQFLYGEDGMAGEFIEGQRLESLELDDKEMEKKFKMNLDDRNFGEGFLDPD
VAAEIRGSAVIRHQLDKEYEQLLKDREQLRSEIVQSGEGAVHLPVNLKRLIWNAQKIYKV
DTSKPSDLRPDIILQGVELLSTQLVVIAGEDTLSREAQENATRLFNIHLRATLATKRVLS
EYRLSAAALEWLLGVIESRFNQAIAHPGEMVGAIAAQSIGEPATQM--------------
-------------------------------------------------------
>gi|11467413|ref|NP_043270.1| photosystem I subunit VII [Cyanophora paradoxa]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AHTVKIYDTCIGCT---QCVRACPTD----------------
------------------------------------------------------------
------------------------------------------------------------
------------VLEMVPWDGCRANQIASAPRTEDCVGCK--------------------
------------------------------------------------------------
-----------------------------------------------RCESACPTDFL--
------------------------------------------------------------
----------------------------------------SI------------------
------------------------------------------RVYLGAETTRSMGLGY--
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
