>Selaginella_moellendorffii_91152_PACid_15413277
--------------------GIVLGLGMAALALRTWLKFGSHTRALKQVEGTAQVEIHDL
RSLVESGEKEPSSD---------SSPPLVIVRGRVALPPKTSSEEVLLARNQTD------
-LAVFVERTQTYLFNEWR-GLFRWGPEWRGLLG-WGSLKEQVAFSRRKIP-FVLL--DSD
PQYD------GACVHINMENVE-HPLPLVTVFHQLHPVQT-S-------------SSTFL
QAVFGRRYPVGV-----------------IDEEKILPLNREITAVGFLS-----------
-KHPQG-LPAIKSSNQ-------------------------------------------M
PFFL-----------------TEFSREELIVELASA----------THALFWTGIVISSL
ALGVIGYSAFKN--------WCKWKEWRRL-R---QIQE-ELRR----------------
--------------------EEQVMEED-E---------EPATTQE-GSE----------
--VPDGQLCVVCLLR--R-KRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSG
--YIRVY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
------------------------------------------------------------
--AVFVERTQTYVLTEMS-NFLGWI-----------TQKDLVKFTRQVVP-FVLA--ETE
AHWSFRPSDMAVYVHINLDESQ-HPIPLVTVHHQLHPVPA-S-------------SYTLF
QAMFGRRYPVGL-----------------LDEEKILPLGAEITAVGVLH-----------
-TAPDG-TPVVKSSKR-------------------------------------------L
PIFL-----------------TEFTREQLLVELASS----------TKVLFWMGVAVSTV
AAGVLGYSLVKN--------WTRWKQRQQQ-R---QSQN-NSEN----------------
--------------------RQNSTIED--------------EAEN-FED----------
--IPDGELCVVCLLR--R-RRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSVTG
--IVRVY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
------------------------------PRIAAVRGYVRTQGSFLRAPFSSE------
-AGVVVKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRAVP-FVLA--STE
LGNS------TGVVHINVDEVDYQPLPLTTVFHKLIPLET-T-------------PYTLF
QTIIGNGYPIAL-----------------LDEEKILPIGKKITAIGLCR-----------
--AKNAESVEITSCPE-------------------------------------------I
PFFL-----------------SELTKDEMQAQLASR----------ARILFWGSIVLGTL
SVCLVGHAIYRG--------WKRIKLRREA-R---QAQQ-MFED----------------
--------------------AEDA--IR-E---------DNSSDDD-DDD----------
--VGDGQLCVVCLRK--R-RKAAFIPCGHLVCCCKCALRMER---EVEPLCPMCRQDIRY
--MIRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
------------------------------------------------------------
------------------------------PRIAAVRGYVRAHDKFFRAPFSGE------
-AGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRSVP-FVLV--STE
LGNP------TGVVHINVDKAD-QPLPLTTVFHKLIPLET-T-------------PYTLF
QTIIGNGYPIAL-----------------LDEEKILPIGKKITAIGLCQ-----------
--AKDAESVEITSCPE-------------------------------------------I
PFFL-----------------SELTKDEMQAQLASR----------ARILFWGSIVLGTL
SVCLVGHAIYRG--------WTRIKLRREA-R---HARQ-MFEE----------------
--------------------AEDA--IH-R---------DDSS--D-DDE----------
--IGDGQLCVVCLRK--R-RRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDIRY
--MMRVY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
-------------------------------------------------PWSGE------
-HGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTYFRSVP-FVLA--SSE
IGNP------IGMVYIDVEKAA-QPLPLTTVFHKLIPIET-T-------------PYTLF
QTIIGNGYPIAL-----------------LDEEKILPIGKELTAIGLCR-----------
--ANDEGSVEISSCPE-------------------------------------------L
PFFL-----------------SELTKDEMQAQLASR----------ARILFWGSVVLGTL
SVCLVGHAIYRG--------WKRIKLRREA-R---QAQQ-LFEE----------------
--------------------GEDA--IQ-E---------DDSS----DEE----------
--VGDGQLCVVCLRK--R-RKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDIRY
--MMRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
---------QLCLFNEWR-GIFGWTFDLHALF--FKSIKEQIITSFRWVP-FVLV--DPE
--NM------TGMVHVKLDRAM-QPLPLTTVYHKLTPVDS-T-------------PYTLF
QTIIGNGYPIAL-----------------LDEEKILPVGKEITAIGYIR-----------
--PHKA-SVEISSCSE-------------------------------------------I
PFFL-----------------SDLTKDEMEAELSSR----------AKTLFWASVVLGTM
SVCLLGFATYRS--------WKKIKERREA-R---QAQE-VFRQ----------------
--------------------TTDE--VT-D---------DQSSDEE-AGE----------
--MGDGQLCVICLRK--R-RKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDIRY
--MIRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ALF--FKSLKEQTITSFRWVP-FALVDPASA
SDKS------TEMIHVKLDGAVQQSLPLTTVYHKLIPVEQ-N-------------SYTLF
QTIVGNGYPIAL-----------------LDEEKILPIGKEITAIGLCR-----------
--VNNQ-NVEITSCPE-------------------------------------------I
PFFL-----------------SDLTKGEIEAELDSR----------ARTLFWVTFALGTM
SVGLLGHAIYRF--------WEKVKQHREA-R---QAQQ-RFHQ----------------
--------------------ADDEDDTG-E---------NGSDDDF-PGE----------
--MGDGQLCVICLRK--R-RKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDIQY
--MLRVY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
------------------------------------------------------------
--AVILQRTQTCIYNEWK-GFFGWTSDLRSIF--GRSLKEQETTFLRTVP-FTLV--EGG
QWPQ------SDYVIVNMDGSS-HPLPLTMVYHQLQPIVA-S-------------RYTFI
QALFGHEYPVGV-----------------LHEEKILPLGKCISAVGICN-----------
--SKDG-IPEIKSCKE-------------------------------------------L
PYFL-----------------ADMTKDEMVADLAFK----------AKILLWSGIVLGSL
SIGVLGFAVMRN--------WNKWKAWRQR-R----SQQ-PIHT----------------
--------------------TSDE--DV-S---------QIDDNED-AGD----------
--VPEGQLCVICLMR--R-RRAAFIPCGHLACCHTCAVSVES---EVSPKCPLCRQAVRN
--SIRIF-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWR-GFFGWTSDIRTLF--ARSWKEKESTSLRTVP-FILV--EGG
RWPQ------SDYVIVNMDGSR-HPLPLTTVYHQLQPVNA-S-------------PYTFL
QALFGHDYPVGL-----------------LDEEKLLPLGKEITAVGICS-----------
--LKNG-IPEIKSCKD-------------------------------------------L
PYFL-----------------SEMSKDQMVVDLVFK----------SKVLFWSGVILGSV
SIGVLGYAVVRN--------WNRWKEWRQQ-R---GVRP-PSQA----------------
--------------------VTDD--TD-T---------QI-AEDD-AGD----------
--VPDGELCVICLMR--R-KRSAFVPCGHLVCCQRCALSVER---ELSPKCPVCRQIIRS
--SVRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTLSRSVP-FVLV--EAG
RWPQ------SDYVIVNLDGSR-HPLPLTTVYHQLQPIDA-S-------------PYTFL
QAFFGYEYPVGL-----------------LDEEKILPLGKEINAVGLCG-----------
--SKNG-ILEITSCKD-------------------------------------------L
PFFL-----------------SDLSKEQMVVDLAFK----------TKVLFWSGVVLGSF
SICILGYAAVRN--------WNRWKAWRQQ-R---QFQQ-QSNS----------------
--------------------VSDA--DV-S---------QIDVEEE-TVD----------
--VPDGQLCVICLMR--R-RRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAVRN
--SIRIFE----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTSLRMVP-FVLV--EGG
RWPQ------SDYVIVNIDGSR-HALPLTTVYHQLQPIDA-S-------------PYTFL
QALFGHEYPVGL-----------------LDEEKILPLGKEINAVGICS-----------
--SRNG-VLEIKSCKD-------------------------------------------L
PYFL-----------------SDMTKDQMVVDLAFK----------TKVLLWSGVVLGSL
SIGILGYAAVRN--------WNRWKEWRQH-R---QSQQ-QNHA----------------
--------------------ASTD--DD-P---------QIDADEE-AGD----------
--VPDGQLCVICLMR--R-RRSAFIPCGHLVCCQLCAISVER---EVSPKCPLCRQAVRN
--SMRIF-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------RTVP-FVLI--DGS
QWPA------VDYVVVNMDGSK-HHLPLTTVYHQLQPINA-S-------------PYTFL
QALFGHEYPVGL-----------------LDEEKILPIGKDVSAVGLCF-----------
--LKNG-ILEIKSCKD-------------------------------------------L
PYFL-----------------TEMTKDQMVIDLAFR----------TKILFWSSIFLGSA
SIGILGFAFVRN--------WNRWKEWRQR-R---RDEQ-QSHA----------------
--------------------AVDE--AT-A---------HI-AEDE-LGD----------
--APDGQLCVICLMR--R-RRSAFVPCGHLVCCQRCALSVER---EVSPKCPVCRQTITN
--SVRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
------------------------------------------------------------
------------------------------------------------------------
--GVVLQRTQTCIYNEWK-GLFGWTSDLRALF--LRSWRQQESTSLRKIP-FVLI--DVG
RPSN------PEYVVVNMDGSS-HPLPLTTVYHRLQPVNP-P-------------PYTFL
QALFGHEYPVGL-----------------LDEEKILPLGKDVSAVGLCS-----------
--LRNG-IAEIKACND-------------------------------------------L
PYYL-----------------SDLSKDQMIVDLSFK----------TKLLFWSGILLGSM
SVGIIGYAVVRN--------WNKWKQWKQQ-R---QLQQ-RRQQ----------------
--------------------PIEP---------------VPPTDDE-IED----------
--VPDGQLCVICLMR--R-RRSVFIPCGHLVCCQGCAISVES---EVAPKCPVCRQEVRD
--SVRIFE----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWK-GLFGWTSDLRAIF--ARSWRQQESTSLRKVP-FLLT--DVG
RRPN------AEYVVVNMDGSR-HPLPLTTVYHKLQPITA-S-------------PYTFL
QALFGHEYPVGL-----------------LDEEKILPLGKDITAVGLCS-----------
--LKNG-IAEIKSCKY-------------------------------------------L
PYFR-----------------SDLSKDQMIMDLSIK----------TKILFWGGIALGSM
SVGVLGYAVVRN--------WNKWKQWKQQ-R---QLQQ-QRQA----------------
--------------------VSDV---------------EPQMDDE-IED----------
--APDGQLCVICLMR--R-RRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEIRD
--SVRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------NA-S-------------PYTFL
QALFGHEYPVGL-----------------LNEEKILPLGKDISAVGICS-----------
--FKNG-IPEIMSCKD-------------------------------------------L
PYFL-----------------SDLTKDQMLLDLAFR----------TKILFWSGIILGSL
SISILGYAALRN--------WNRWKERRQQ-R---QAHQ-PSHA----------------
--------------------ASID--AN-S---------ELTGEEE-IGD----------
--IPDGQLCVICLMR--R-RVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEIRG
--SMRVF-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------------IF--SRSWRERESKVFRTVP-FILA--EGG
RRPI------SEFVAVDMDGSR-HPLPLTTVYHHLHPVNP-S-------------PYTFL
EALFGHRYPVGL-----------------LDEEKILPLGKEISAVGLCS-----------
--VKDG-VLEIKSCKD-------------------------------------------F
PYFL-----------------SEMSKDQMVVDLTSR----------TKVLFWSGIFLGSV
SIGVLAYAVSRN--------WNRWKVWRQQ-R---ELQR-SIRA----------------
--------------------SNAE--AQIQ---------EEEEEED-AGD----------
--VPDGQLCVICLMR--R-RRSAFIPCGHLVCCQLCSISIER---DVAPKCPVCRQQIRT
--SVRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Citrus_clementina_0.9_012450m_PACid_19274708
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTAYQRLELANV-S-------------PFTFL
QAMFGLKCPIGV-----------------LAEEKILPLGKDISAVGICS-----------
--FKNG-IPEIKSCKD-------------------------------------------L
PYFL-----------------SEKTKDLMVVDLVNR----------SKILFWSGIVLGSL
SIGILGYAIVRN--------WNRWKD-RQQ-R---MSRQ-LTEA----------------
--------------------PSDD--AD-S---------QIGSDEDVAGD----------
--IPDGQLCVVCLTR--R-RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRS
--SMRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTAYQRLELANV-S-------------PFTFL
QAMFGLKCPIGV-----------------LAEEKILPLGKDISAVGICN-----------
--FKNG-IPEIKSCKD-------------------------------------------L
PYFL-----------------SEKTKDQMVVDLVNR----------SKILFWSGIVLGSL
SIGILGYAIVRN--------WNRWKD-RQQ-R---MSRQ-LTET----------------
--------------------PSDD--AD-S---------QIGSDEEVAGD----------
--IPDGQLCVVCLTR--R-RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRS
--SMRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
------------------------------------------------------------
--GVILQRIQTCIYNEWR-GLFRWTADLGSMLMPRRITKENASSSMNMVP-FILV--EEG
KWPP------SDHVVVNMEGST-HPLPLTTVYQHLQPVKA-S-------------SYTVF
QALVGLEYPVGL-----------------LYEEKILPLGKDITAVGICN-----------
--LKNG-IPEIKSCED-------------------------------------------L
PYFL-----------------SILTKDQMIADLSFK----------SKVLLWSGLILGTV
AIGVLGYSISRN--------WSKWKEWKAR-R---AQQQ-QNAS----------------
--------------------RIEN-----L---------DETEEEE-SGD----------
--VPDGELCVVCLMR--R-RRSAFVPCGHLVCCHRCAFSVER---EVSPKCPVCRQPIRN
--SVRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------PYTLI
QAIVGHAYPVGL-----------------LDEEKILPLGKEITAVGHCT-----------
--LQDG-NPQIISCKK-------------------------------------------V
PYFL-----------------SDMTKDQMIVDLVSK----------KKILFWAGIVLGSV
SLGVLGYALTRN--------WQRLKEWRQR-R---QIQQ-SREE----------------
--------------------EIANLDATPE---------DTRADEE-TED----------
--IPEGQLCVICLMR--R-KRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDIRT
--SVRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------A-T-------------PYTFL
QAVFGHEYPVGV-----------------LDEEKILPLGKNISAVGICS-----------
--FENG-VPVIKSCSD-------------------------------------------F
PHFL-----------------CEMTKDQMILDLVFK----------TKFLFWSSIVLGSL
TVGILGYSAARN--------WNRWKQWRQH-R---QLQN-SRNDSPTSQLDSSNDIPIYG
DFASDDEAATVPDDELSSHVPDDE--LS-S---------HVPDDEL-SSH----------
--VPDGQLCVICLMR--R-KRSAFIPCGHLVCCERCAVSVER---ESSPKCPICRQQIRS
--SVRIY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Tomato_Solyc12g049330.1.1 genomic_reference:SL2.31ch12 evidence_code:10F0H1E0IEG gene_region:46263202-46267916 functional_description:"Zinc finger family protein (AHRD V1 ***- D7KLF2_ARALY)"
MSIYDQAAAAVLSQIATAADGALIGLALAYVAVRSIVKFKANSSALHKINDAPSLNVSDL
RSLLSSSDNSDSSNHSDDGKLV-IVRGTVEAKSAVEGNWKSLRANILSAHNSAE------
-KGVILQHTQTCIYNEWR-GFFSWAGDLYSIF--PRVRKDQQSSSLRTVP-FVLI--ETG
RWPQ------PKYVNVNMDGST-HSLPLVTVYHHLQPLHA-T-------------PLTFI
QALFGHHYPVGV-----------------LDEEKILPLGKDITAIGVCS-----------
--SKDG-ILEIKSCED-------------------------------------------L
PYFL-----------------SDMTKDQMLVELAFK----------TKILMWSGVLFGSV
AVGVLGYAVVRN--------WNRWKLWRHQ-R---QAQQ-QRDA----------------
--------------------ASND--DD-V---------QVSADEE-SGD----------
--VPDGQLCVICLTR--R-KRAAFVPCGHLVCCQRC------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>SPL2_Arabidopsis_thaliana_AT1G54150.1_PACid_19654958
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTVYNRLQPINS-S----------------FL
QAFLYPDYPVGL-----------------LDIEKILPPGKDITAVGIYS-----------
--FNNG-VPEIKSCQD-------------------------------------------L
PYFL-----------------SEMTKDKMIEDLMEQ----------TNFIFLGSVILGIV
SVGILSYAAVRT--------WNKWKQWNHQ-R---ELPQ-RPND----------------
--------------------SVVD--DE---------------PED-ADE----------
--IPDGELCVICVSR--R-RVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRG
--SMRVY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGD------
-KALIIQRTQTYVYSGWK-RLFQSTGHRFML---ERSLRKHGADFTRTVP-FVIV--GKD
QQSN------SSFVAVNMDGSR-QPLPLTTVYNRLQPINS-S----------------FL
QAFLYPDYPVGL-----------------LDIEKILPPGKDITAVGIYS-----------
--FNNG-VPEIKSCQD-------------------------------------------L
PYFL-----------------SEMTKDKMIEDLMEQ----------TNFIFLGSVILGIV
SVGILSYAAVRT--------WNKWKQWNHQ-R---ELPQ-RPND----------------
--------------------SVVD--DE---------------PED-ADE----------
--IPDGELCVICVSR--R-RVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRG
--SMRVYYS---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTVYNRLQPINS-S----------------FL
QAFLFPDYPVGL-----------------LDIEKILPPGKDITAVGICS-----------
--FNNG-VPEIKSCQD-------------------------------------------L
PYFL-----------------SEMTKDKMIEELMDQ----------TSFIFFGSVILGIV
SVGILSYAAVRT--------WNKWKQWNHQ-R---DLPQ-RPNE----------------
--------------------PVVD--DE---------------PED-ADE----------
--IPDGELCVICVTR--R-RVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSIRG
--SMRVY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VIVDLDSST-HLLPLTTVYHKLQDLHVMS---------DEILPYAFL
EAFF---LPVGH-----------------M-QKKILPLGKEINAIGLCS-----------
--LQDG-NLHIKATQE-------------------------------------------L
PYFL-----------------SEMTKGEMVKHLAYK----------TTILFWGGCIIGIV
SLGVLGYTSFRI--------WEWWKVRRQH----------FSNA----------------
--------------------EVDDVYIG-------------------NDE----------
--IPSEQLCTICTMR--R-KKYACVPCGHLVCCHKCARSIQH---DSTARCPECRH----
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---LGHAYPFGLCLQEKFLPLNFAWYHPGLLEEKILPLGKEISVVGIGT-----------
--SEYG-NVEIKPCDE-------------------------------------------L
PYFL-----------------SDLTKDQMIGELAQK----------TNYLLLSAIFFGSL
SLAVIAYAVMIG--------CQRFEEKTQQRR---QVQQ-QMTQ----------------
--------------------VQQSLR-------------NDVVEEG-MEA----------
--LPEGLSCVV----------SVFVPCGHLVCCQTCAPLVAR-----DRRCPICRQYIQK
--YIITY-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Physcomitrella_patens_Pp1s12_190V6.2_PACid_18048531
---M-----LSWGGITLCLSGAAL-------------YCLSRNTGRDALNLRSIERV---
------------NQLKDLAILLESACK--VVPLVVTVAGRVGSETPIACEHSSL------
-RGVILEETAEQHFLKHN-DTGSWIQDSALML-----------SISKEVP-WYL------
-------EDGTGRVYIVGARNA-AGMELTVASEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRVERVLPTGTNLTVVGEAV-----------
-QDDRG-LIRIQKPNK-------------------------------------------G
PFYV-----------------TPKSLDQLVANLGRW----------SRWYKYMSLGFTIV
GIYFITSHAIKHF-------MERRRREALHRRVM-EAAA-LRQA----------------
--------------------SQREGGDGDMGDVTSHPLDDSVDTSQ-KKD----------
--RGTPDLCVICLEQ--D-YNAVFLPCGHMCCCTSCSAQLTS--------CPLCRRHIDK
--FVKTYRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Physcomitrella_patens_Pp1s175_124V6.2_PACid_18055474
---M-----LSWGGITLCFSGAAL-------------YCLSRNTGRDALHLMSVERV---
------------NQLEDLAKLLESACT--VVPWVVTVAGRVGAEAPIASEHSSL------
-RGVILEKSAEQHFLKHN-DTGSWIQHSALML-----------SISKEVP-WYL------
-------EDGTSRVFIIGARNA-AGMDLTVASESFEEYGG-S---------LVRGTLDYL
QGL----KMLGV-----------------KRVERVLPTGTNLTVVGEAV-----------
-QDDRG-LIRIQKPDK-------------------------------------------G
PFYV-----------------TPQSQDQLIENLGRW----------SRWCQYMSFGLTLV
GIYFITSRAIKHM-------LERWRREALLTRVM-EAAA-LRKA----------------
--------------------LQQEGVDEESDGVTAFPHDDNAHTAQ-KKD----------
--GGMPSLCVICLEQ--D-YNAVLVPCGHMCCCTSCSSQLSL--------CPLCRRHIDQ
--VVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Selaginella_moellendorffii_231449_PACid_15416766
---M-----LPWGGITMCLSGVAL-------------YFLSRNSGRDAATLKAVRRV---
------------DQLKDLAHLLDSACK--AVPLVVTVAGRVGSETPIGCDHSSL------
-RCVILEETAEQHFLKHN-DTGSWIQDSALML-----------SNNKEVP-WFL------
-------EDASGRVFIVGARGA-AGLELTIASEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRVERVLPTGTALTVVGEAI-----------
-KDDQG-TLRIQRPHK-------------------------------------------G
PFYV-----------------TPKSIDQLIANLGKW----------SRWYKYMSLGFTLF
GVFLVASHTIRYV-------MEKRRRAALNRRVM-EAAA-RRRE----------------
--------------------RKEHEGKAQVGEF------AKVETAT-KRD----------
--GRLPDLCVICLEQ--E-YNAVFVPCGHMCCCISCSAQLQN--------CPLCRRRIEQ
--IVKTYRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Medicago_truncatula_Medtr1g111550.1_PACid_17439105
---M-----VPWRGVGCCLSAAAL-------------YLLGRTSGRDVDILKSVNRV---
------------NQLRELAQLLDEE----IFPLVVAISGRVGSETPISCEFSGL------
-RGVIIEETAEQHFLKHS-DAGSWIQDSALMQ-----------SRSNEVP-WYL------
-------DDGTGRVRVVGAQGA-TGFVLPVGSEAFEESGR-L---------PVRGTSDYV
QGL----KMLGV-----------------KRIERVLPVGTSLTVVGEAA-----------
-KDDVG-TIRIQRPSK-------------------------------------------G
PFYV-----------------SPKTIDELIANIGRW----------ARWYKYASAGLTVL
SVYMIANHAVRYI-------LERRRRNELEKRVL-AAAA-KISG----------------
--------------------QDNGGE--MD---------DSLSDGA-KRE----------
--RAMPNLCVICLEQ--E-YNSVFVPCGHMCCCTACSSHLTS--------CPLCRRQIEK
--AVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Glycine_max_Glyma10g02920.1_PACid_16278382
---M-----IPWGGLSCCLSAAAL-------------YLLGRSSGRDAEILKSVTRV---
------------NQLKELAQLLDAE----ILPLIVTISGRVSSETPINCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRVHVVGARGA-SGFALPVGIEAFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPVGTSLTVVGEAA-----------
-KDDVG-AIRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDQLIANLGKW----------ARWYKYASVGLTVF
GAYLIAKHAIRYI-------LERRRRSELQRRVL-AAAA-KKSG----------------
--------------------QNNDVE--KA---------DSLSDGA-KKD----------
--RLMPDLCVICLEQ--E-YNAVFVPCGHMCCCTACSSHLTN--------CPLCRRQIEK
--VVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Prunus_persica_ppa008230m_PACid_17644506
---M-----LPWGGLSCCLSAAAL-------------YLLGRSSGRDADILKSATRI---
------------NQLKELAKLLDSEC---ILPLVVAISGRVSSETPITCEFTGL------
-RGVVVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRVHVVGARGA-TGFVLPVASEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTSLSVVGEAV-----------
-KDDIG-TIRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDQLIANLGKW----------ARWYKYASLGLTVF
GVYLVAKHSVQYI-------LERRRRWELQRRVL-AAAA-KRSG----------------
--------------------EDNEGSNEKD---------DNVLDGS-K------------
--RLMPDLCVICLEH--E-YNAVFVPCGHMCCCTTCSLHLTN--------CPLCRRRIDQ
--AVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
---M-----LPWGGISCCLSAAAL-------------YLLGRSSGRDAELLKSVTRV---
------------NQLKELAQLLEAE-H--LLPLVVAISGRVSSDTPINCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAFVLGARNA-TNFILPVVSEVFEESGR-S---------LMRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAA-----------
-KDDIG-TIRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDQLISNLGKW----------ARWYKYASMGLSIF
GLYLVTKHVILYL-------MERRRRWELQKRVL-AAAA-KRSS----------------
--------------------QENEGEIEKA---------SNGTDGT-KRD----------
--RSMPDLCVICLER--D-YNAVFVPCGHMCCCVACCSHLTN--------CPLCRRRIEL
--VVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSGSK--VLPFIVTVCGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAFVVGARGA-TGFVLTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERLLPTGTSLTVVGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDELIENLGKW----------ARWYKYASFGLTIF
GTFLIAKRAIHYI-------LQRKRRWELHRRVL-AAAAVKRSE----------------
--------------------QDNEGTNGQA---------ENGSDGT-QRD----------
--RVMPDLCVICLEQ--E-YNAVFVPCGHMCCCIICSWHLTN--------CPLCRRRIDQ
--VVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Citrus_clementina_0.9_003846m_PACid_19263951
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSGSK--VLPFIVTVCGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAFVVGARGA-TGFVLTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERLLPTGTSLTVVGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDELIENLGKW----------ARWYKYASFGLTIF
GTFLIAKRAIHYI-------LQRKRRWELHRRVL-AAAAVKRSE----------------
--------------------QDNEGTNGQA---------ENGSDGT-QRD----------
--RVMPDLCVICLEQ--E-YNAVFVPCGHMCCCIICSSHLTN--------CPLCRRRIDQ
--VVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
---M-----ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGGSK--VLPSIVSVSGRVGSETPISCEYSGL------
-RGVIVEETTERHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGCVFVVGARGA-TGFALTVGSEVFEESGR-S---------LVHGTLDYL
QGL----KMLGV-----------------KRIGRLLPTGTSLTVVGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDELLENLGKW----------ARWYKYASFGLTIF
GAFLIAKRVIRCI-------LQRKRRWELRRRVL-AAAAVQRSE----------------
--------------------QDNEGTNGQA---------ENGSDST-QRD----------
--RVMPDLCVICLEQ--E--------CGHLCCCLICSSRLTN--------CPLCRRRIDQ
--VVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Citrus_clementina_0.9_014777m_PACid_19265048
---M-----ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGGSK--VLPSIVSVSGRVGSETPISCEYSGL------
-RGVIVEETTERHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGCVFVVGARGA-TGFALTVGSEVFEESGR-S---------LVHGTLDYL
QGL----KMLGV-----------------KRIGRLLPTGTSLTVVGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDELLENLGKW----------ARWYKYASFGLTIF
GAFLIAKRVIRCI-------LQRKRRWELRRRVL-AAAAVQRSE----------------
--------------------QDNEGTNGQA---------ENGSDST-QRD----------
--RVMPDLCVICLEQ--E-YNAVFFPCGHLCCCLICSSRLTN--------CPLCRRRIDQ
--VVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
---M-----LPWGGISCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKELAKLLDIESN--ISPSVVSISGRVGSETPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRVYVVGARGA-SGFVLTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAV-----------
-KDDIG-TVRVQRPHK-------------------------------------------G
PFYV-----------------SPRTIDELIGNLGKW----------ARWYRYASVSLTVF
GAFLIAKHAIQYI-------MERRRRWELQSRVLAAAAA-KRQG----------------
--------------------QDSEGSNGKA---------ENGSDNS-KRE----------
--RPVPDLCVICLEQ--E-YNAVFLPCGHMCCCTTCSSHLTN--------CPLCRRRIEQ
--VVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Ricinus_communis_29703.m001546_PACid_16806242
--------------------------------------------------LKSVTRV---
------------NQLNELAKLLDIESK--VLPLVVAISGRVGSETPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRTFVVGARGA-SGFALTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTSLSVIGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDELIGNLGKW----------ARWYRYASVGLTVF
GVFLIAKHAIQYI-------MERRRRWELQSRVL-AAAA-KRQG----------------
--------------------QDSDGSNGKA---------ENGSDSS-KRE----------
--RPIPDLCVICLEQ--E-YNAVFLPCGHMCCCTACSSHLTN--------CPLCRRRIEQ
--I---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Vitis_vinifera_GSVIVT01011070001_PACid_17823049
---M-----IPWGGISCCLSAAAL-------------YLLGRSSGRDAEALKSVTRV---
------------QQLKDLVQLLDTACK--VLPLVVTVSGRVGSDTPIKCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDDTGRAYIVGARGA-TGLVLTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTPLTVVGEAI-----------
-KDDVG-TIRIQRPHK-------------------------------------------G
PFYV-----------------SPKSIDHLVANLGKW----------ARWYRYASLGFTVF
GVYLIAKSAIQYV-------MERKRCWELRKRVL-AAAS-KKSG----------------
--------------------QDSEDPDEKD---------ENGSDNT-KRD----------
--RLMPDLCVICLEQ--E-YNAVFVPCGHMCCCTMCSSQLTN--------CPLCRRRIEQ
--VVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
---M-----IPWGGLSCCLSAAAL-------------YVLGRSSGRDAEALKCVFRV---
------------NQLKELAQLLDTECK--VLPLVVTLCGRVGSDTPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAYVLGARGA-SGFELNIASEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERLLPVGSSLTVVGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYV-----------------SPKTIDQLISNLGKW----------ARWYRYASYGFTVF
GICLIAKRAIQYI-------MERKRRWELQRRVL-AAVA-RRSE----------------
--------------------QDTEGTDDKT---------KNAPDSA-KRD----------
--RSMPDLCVICLEQ--E-YNSVFVPCGHMCSCTTCSLQLTN--------CPLCRRRIEQ
--AVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Tomato_Solyc06g084360.1.1 genomic_reference:SL2.31ch06 evidence_code:10F0H1E1IEG gene_region:45791481-45798777 functional_description:"Baculoviral IAP repeat-containing protein 3 (AHRD V1 *--- B0XJ37_CULQU); contains Interpro domain(s)  IPR001841  Zinc f
---M-----VPWAGLSCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKDLAQLLDTASK--VLPLVVTISGRVGSDTPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMCKEVP-WYL------
-------DDGTGRTFIVGGRGA-TGLVLTVGSEAFEEAGR-S---------FVRGTLDYL
QGL----KMLGV-----------------KRIERVLPVGTPLTVVGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYI-----------------SHKTIDQLIANLGRW----------ARWYKYASMGFTAV
GVYLLVKHTFHYM-------MERKRHWELRRRVL-AAAA-KRAG----------------
--------------------DEDEGSDATA---------ENGVD---NKD----------
--LLMPDLCVICLEQ--E-YNSVFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQ
--VVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
---M-----IPVGGITCCLSAAAL-------------YLLGRSSGRDADLLKSVTRV---
------------NQLKDLAQLLEAASK--VLPLVVTVSGRVGSETPINCEYSGL------
-RGVIVEQTAEQHFLKHN-DAGSWIQDSALML-----------SMCKEVP-WYL------
-------DDGTSRVHVVGARGA-TGLVLTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGSPLTVVGEAV-----------
-KDDIG-SIRIQRPHK-------------------------------------------G
PFYV-----------------TDKTIDQLIANLGKW----------SRLYKYASMGLTAF
GVYLLAKHAFQYI-------MDRRRLWETRKRVL-DAAA-KKAG----------------
--------------------QNEGALNGEA---------EIGSDSS-NKE----------
--RPIPELCVICLEQ--E-YNSVFVQCGHMCCCMACSSHLTN--------CPL-------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
---M-----LPWGGITCCMSAAAL-------------YLLGKSSGRDADILKSVTRL---
------------NQLKDLAQMLDTACK--VLPFVVTVSGRVGSDTPINCEHSGL------
-RGVIVEEAAEQHFMKQN-DSGSWIQDSAQML-----------AMTKEVP-WYL------
-------DDGTGRVHVLGARGA-TGLVLTVASETFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAV-----------
-KDDVG-TIWIQRPHK-------------------------------------------G
PFYV-----------------SPKSIDQLIANLGIW----------ARLYKYASLGFTAF
GVYLIAKHAIRYI-------LERRRLLDFQRRVR-AAAA-QRLE----------------
--------------------QDNDGTDGKA---------EDGPDVV-NKD----------
--RIMPDICVICLEQ--E-YNAVFVPCGHLCCCTTCSSHLSN--------CPLCRRRIDQ
--VVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Arabidopsis_lyrata_474968_PACid_16053684
---M-----IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLKTVTRV---
------------NQLKELAQLLELDSK--ILPFIVAVSGRVGSETPIKCEHSGI------
-RGVIVEETAEQHFLKHN-ETGSWVQDSALML-----------SMSKEVP-WFL------
-------DDGTSRVHVMGARGA-TGFALTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGIPLTIVGEAV-----------
-KDDIG-EFRIQKPDR-------------------------------------------G
PFYV-----------------SPKSLDQLISNLGKW----------SRWYKYASMGFTVF
GVFLITKHVIDSV-------LERRRRRQLQKRVL-DAAA-KRAE----------------
--------------------LESEGSNGAR---------ESIADST-KKE----------
--DAVPDLCVICLEQ--E-YNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDL
--AVKTYRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>SP1
---M-----IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLETVTRV---
------------NQLKELAQLLELDSK--ILPFIVAVSGRVGSETPIKCEHSGI------
-RGVIVEETAEQHFLKHN-ETGSWVQDSALML-----------SMSKEVP-WFL------
-------DDGTSRVHVMGARGA-TGFALTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGIPLTIVGEAV-----------
-KDDIG-EFRIQKPDR-------------------------------------------G
PFYV-----------------SSKSLDQLISNLGKW----------SRLYKYASMGFTVL
GVFLITKHVIDSV-------LERRRRRQLQKRVL-DAAA-KRAE----------------
--------------------LESEGSNGTR---------ESISDST-KKE----------
--DAVPDLCVICLEQ--E-YNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDL
--AVKTYRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Populus_trichocarpa_POPTR_0014s13410.1_PACid_18222628
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGR---YLPSLIPL---
------------FFLIISSKLLDIESK--VLPLVVAISGRVGAESPISCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRVYVVGARGA-SGFVLTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTSLTVVGEAV-----------
-KDDIG-TVRIQRPHK-------------------------------------------G
PFYV-----------------SPKSIDELIGNLGKW----------ARWYKYASLGLTVF
GAFLITKHVIRYI-------MERRRRWELQSRYV-SLVE-GIHD----------------
--------------------KMFQG--------------KGHANGA-KRE----------
--RPIPDLCVICLEQ--E-YNAVFLPCGHMCCCITCCSQLSN--------CPLCRRRIEQ
--VVKTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGSDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAISGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARSA-AGLILTVASEVFEESGR-T---------LVRGTLDYL
QGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAI-----------
-KDDVG-TIRIQRPHK-------------------------------------------G
PFYA-----------------SSKSIDQLIVNLGKW----------AKLYRIASMGFATF
GVFLLAKRALQHF-------LERRRRHELQKRVL-NAAA-QRQA----------------
--------------------REAEGSKGTS----------DAEPNS-KKD----------
--QLVLDICVICLEQ--E-YNAVFVPCGHMCCCVACSSHLTN--------CPLCRRRIDQ
--AVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVSSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARSA-AGLILTVASEVFEESGR-T---------LVRGTLDYL
QGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAI-----------
-RDDVG-TIRIQRPHK-------------------------------------------G
PFYV-----------------SPKSIDQLIMNLGKW----------AKLYRLASMGFATF
GVFLLAKRAIQHF-------LERKRRHELQKRVL-NAAA-QRQA----------------
--------------------REAEGSNGSS----------DTEPNS-KKD----------
--QLVLDICVICLEQ--E-YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQ
--AVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYMVGARSA-AGLILTVASEVFEESGR-T---------LVRGTLDYL
QGL----KMLGV-----------------KRTERVLPTGISLTVVGEAI-----------
-KDDVG-TIRIQRPHK-------------------------------------------G
PFYV-----------------SPKSIDQLIMNLGKW----------AKLYRLASMGFATF
GAFLLAKRAIQHF-------LERKRRHELQKRVL-NAAA-QRQA----------------
--------------------REAEGSIGSS----------DTEPNS-KKD----------
--QLVLDICVICLEQ--E-YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQ
--AVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Setaria_italica_Si030396m_PACid_19714000
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARAA-AGLILTVASEVFEESGR-T---------LVRGTLDYL
QGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAI-----------
-KDDVG-TIRIQRPHK-------------------------------------------G
PFYV-----------------SPKSIDQLILNLGKW----------AKLYRLASMGFATF
SVFLLAKRAIQHF-------LERKRRHELQKRVL-NAAA-QRQA----------------
--------------------REAEGGKGTS----------NTEPNS-KKD----------
--QLVLDICVICLEQ--E-YNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQ
--AVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
---L-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSTKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVFVVGARGA-AGLVLTVASEVFEESGR-T---------LVRGTLDYL
QGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAI-----------
-KDDVG-TIRIQRPHK-------------------------------------------G
PFYV-----------------SPKSIDQLIMNLGKW----------AKLYQLASMGFAAF
GVFLLAKRALQHF-------LERKRRHELQKRVH-AAAA-QRQA----------------
--------------------REAEGGNGTS----------DVDSNN-KKD----------
--QLVLDICVICLEQ--E-YNAVFVPCGHMCCCMNCSSHLTN--------CPLCRRRIDQ
--AVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
---M-----VPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVTRT---
------------GSLKDLAAILDTASK--VLPLVVAVSGRVSSDTPLICQQSGM------
-RGVIVEEMAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARAA-AGLVLTIASEVFEESGR-T---------LVRGTLDYL
QGL----KMLGV-----------------KRTERVLPTGTSLTVVGEAI-----------
-KDDVG-TIRIQRPHK-------------------------------------------G
PFYA-----------------SPKSIDQLILNLGKW----------AKLYQLASMGFAAF
GVFLLAKRALQHF-------LQKKRQHELNKRVR-AAAA-QRQA----------------
--------------------REAEGADGTS----------NGDPNS-KKD----------
--QLVLEICVICLEQ--E-YNAVFVPCGHMCCCMNCSSHVTN--------CPLCRRRIDQ
--AVRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
---M-----IPWGGITCCMSAAAL-------------YLLGRSSGRDADILRKVTRV---
------------NQLKELAQLLDIESK--IMPLIVAISGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTARVFVVGARGA-TGFVLTVGSEVFEESGR-S---------LVRGTLDYL
QGL----KMLGV-----------------KRIERVLPTGTSLTVVGEMT-----------
-LEQ----FRYEDRTN-------------------------------------------G
LFTC------------LQINGSPD------FQLGKW----------ARWYKYASMGLTFL
GVFLIAKRSIEYV-------LERRRRRELQKRVL-AAAA-KRSG----------------
--------------------QDNEGSNIIP---------ENGLDGA-KRE----------
--HLMPDLCVICLEQ--E-YNAAFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQ
--VLRTFRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>SPL1_NP_564745
---M-----IHLAGFTCCLGGVAL-------------YLLTRSTGRD---IKSITRV---
------------YQLKDLEQLVEVESK--VVPLIIAVSGDVGSETPIKCEHSYV------
-LGVFLKRTAEQQVLRRN-WRFSWVRNSTLMQ-----------PMTKEVP-WYL------
-------DDGTGRVNVDVSQGE-LGLALTVGSDVFEKAEPVS---------LVQGALGYL
KGF----KILGV-----------------RHVERVVPIGTPLTVVGEAV-----------
-RDGMG-NVRIQKPEQ-------------------------------------------G
PFYV-----------------TYIPLDQLISKLGDL----------SRRFKYASMGLTVL
GVILISKPVIEYILKRIEDTLERRRRQFALKRVV-DAAA-RRAK----------------
--------------------PVTGG-------------------GT-SRD----------
--GDTPDLCVVCLDQ--K-YNTAFVECGHMCCCTPCSLQLRT--------CPLCRERIQQ
--VLKIYRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Arabidopsis_lyrata_338432_PACid_16045815
---M-----IHLAGFTCCLGGIAL-------------YLLSRNTGG---VVKSITRV---
------------NHLKDLEQL--VESK--VFPLIIAVSGIVGSETPIKCEHSDI------
-LGVFLKKTAEQQVLSRN-WRFSWVRKSTLMQ-----------PMTKEVP-WFL------
-------DDGTGRVNVAVSQGE-IGLALTVGSDVFEKAEPVS---------LVQGTLDYL
KGL----KILGV-----------------RRVEHVVPIGTPLTIVGEAV-----------
-KDGMG-NVRIQKPEQ-------------------------------------------G
PFYV-----------------SYVPLDQLISKLGEW----------SRRFKYASMGLTVV
GVILLSKPVIKYILKKIEDTLERRRRQLLQKRVV--------------------------
------------------------------------------------------------
---DVPDLCVICHDQ--K-YNTAFVQCGHMCCCLTCSLRLTT--------CPLCREQIQQ
--VLKIYRH---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Arabidopsis_lyrata_867782_PACid_16034683
---M-----IHLGGLTCCVSGGVL-------------YLLSMIPGSFFEMLNSVTRV---
------------HQIKDLENLLQVEGK------IIAVSG---------------------
--------TAQQLFLKRN-WLFSWVEDSKWML-----------PQAKEVP-WYL------
------------------------------------------------------------
--------MLGV-----------------RRTEHVLPIGTPVTVVGEAV-----------
-KDGIR-GFRIQKPEK-------------------------------------------G
LFFV-----------------SPVPLDKIISPMGKW----------LRRFKYVYVGLTVV
GVILISKPVIEYI-------LERRRGRLLRKRVA-DAAA-KRAK----------------
--------------------LVARGLETQH---------ENSLDST-SRD----------
--RDVLDLCVICLEQ--K-YDATFVKCGHMCCCLTCSLHVKT--------CPICRRPIEH
--VLKIDR----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Chlorella_variabilis_gi|307103723|gb|EFN51981.1| hypothetical protein CHLNCDRAFT_27288 [Chlorella variabilis]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------MPCPRAVLCCRIPDNQTQG---------FLGRVVDEV
QGS----RSVGV-----------------RQVERMLPVGTMLTAVGELA-----------
-TAGGK-MLVLRAPRD-------------------------------------------G
AFYL-----------------SRQPLPDVIASLQAS----------SLACQQWAAAFTAV
GASMLVAAATQHA-------LTWVRQRRLRQRVE-KAMR-ERAA----------------
--------------------AAAAAGGGGA---------AGAPAAS-AAEPQPADVAEAA
EGGARPSLCVVCLER--P-CATVFPACGHMCACSRCSHGLRR--------CPICRSRGAP
---IRVYTA---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Micromonas_sp._RCC299_gi|255086321|ref|XP_002509127.1|
---MAGEGHVSWPGVACIATGALFGYSSRAFKRNIPQYTDFRALERDLRAAASRARAEPT
RRRHHPTHAAGENEIRARPAQADDDDDDAPFGMLVAITGAARSDVLVPCVHAKRPDGRTP
ERAIYVDAVTDQYLARQAVRSGEWIRDCVVVA-----------AMAKEAPTWRL---EDP
AGHGVNMHRATSMAQASDAARA-ADWHLSLVHDEFESAGS-AGAGSSLHSRIIANALDVN
MGL----NVLGL-----------------RHRERVLAPGARLTAVGEVFIAPNGGPVGVD
GGDGAG-EIRLRRPRRRKGWRRHGRGWRRKGGTPGDEKSAPGDGDGDGDDAAMSPRMDPN
VFTV-----------------TQKPFDEYVDGFGSW----------GKVNAALGLGFLGV
GVALVLTKLWRAR-------LTRWREARFLRRMREAEEA-RRAA----------------
--------------------GGGEGDDGGDTA-------GTNTDTA-GAK----------
--VSPGETCVVCMYA--R-SEVVYKECGHLVCCGVCAGRMDR--------CPLCRRRSAH
---MRVYRAGL-------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Mulan_NP_078820
---MESGGRPSLCQFILLGTTSVV---------TAALYSVYRQKARVSQELKGAKKV---
------------HLGEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLTLQEHKMVWNRTTHLWNDCSKIIH-----------QRTNTVP-FDLVPHED-
-------G-VDVAVRVLKPLDS-VDLGLETVYEKFHPSIQ-S---------FTDVIGHYI
SGE----RPKGI-----------------QETEEMLKVGATLTGVGELV-----------
--LDNN-SVRLQPPKQ------------------------------------------GM
QYYL-----------------SSQDFDSLLQRQESS----------VRLWKVLALVFGFA
TCATLFFILRKQ--------YLQRQERLRLKQMQEEFQE-HEAQ----------------
---------------------------------------LLSRAKP-EDR----------
--ESLKSACVVCLSS--F-KSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
--VIPLYNS---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Mus_musculus_gi_18043560_gb_AAH19516.1
---MESGSRPSLGQVILLGTSSMV---------TAVLYSIYRQKAQVAQELKGAKKI---
------------HLGEDLKGILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLSLQEHKMVWNRTTHLWNDYSKIIH-----------QRTNTVP-FDLVPHED-
-------G-VAVSVRVLKPLDS-VDLGLETVYEKFHPSVQ-S---------FTDAIGHYI
SGE----RPKGI-----------------QETEEMLKVGATLTGIGELV-----------
--LDNN-AVRLQPPKQ------------------------------------------GM
QYYL-----------------SSQDFDSLLHRQESS----------VRLWKVLVLVFGFA
TCATLFFILRKQ--------YLHRQERLRQQQLQEEFLE-HEAQ----------------
---------------------------------------LLSQASP-EDR----------
--ESLKSACVVCLSN--F-KSCVFLECGHVCSCRQCYLALPE-----PKRCPICRREITR
--VIPLYNS---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
---MENGGRPSVGQVILLTTSSAI---------TALFYSIYRHKYRSVQTLKEAKKF---
------------CLTDDLPAVLSDLPGKCVPYAVIEGAVTSVKEVLNSQYVENC------
-KGVIQRLSLKEHKMVWNRTTHLWNDHEKIIH-----------QRSNTVP-FDLAPENP-
-------GESGVSVRVLRPLEA-VDLGLETIYEKFHPAVQ-S---------FSNILGHYM
TGE----RPKGV-----------------QETEEMLKIGATITGVGELV-----------
--LDNK-TIKLQPPKD------------------------------------------GM
LFYL-----------------SSMDYEGLLEKQEVQ----------MRWWRILSIVFGVA
SCITLFFILRRK--------YRHYKEKQHLKNLQREFEE-SRAR----------------
---------------------------------------QRVQQEP-QNK----------
--EEVQNPCSICLST--E-KSCVFLECGHVCSCISCYQALPS-----PKKCPICRNFIDR
--IVPLYNS---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Danio_rerio_gi_148922854_ref_NP_001092230.1
---MEASGKPSTAQIVLLATSSAL---------TAVLYTIYKRKSSHVARLREAKKM---
------------SLNPELKTILSEAPGKCVPYAVIEGVVRSVKETLNSQFVDNC------
-KGVIQRLTLNEKKMVWNRTTNLWNDCEKVIH-----------QRTNTVP-FDLAPHDD-
-------T-VPTTVRVLRPLDA-AELDLETTYENFHPSQQ-S---------LTNVIGHFI
SGE----RPQGI-----------------QETEEMLRLGASMTGVGELV-----------
--LDNN-LVRLQPPKK------------------------------------------GL
RYFL-----------------SRLDYDTLLSKQEGH----------LRIWRVLTVLLGLT
ACATFFYLLWRQ--------YVLRKERRKEQSVLDEYRK-WQSK----------------
---------------------------------------RFQELHL-AKE----------
--DVSPTACTICLNH--E-RSCVFLECGHVCACEGCYRALPE-----PKKCPICRATIDR
--IVSLYNS---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
---MEFLHESVALGVDLLILGLCA--------------REYVHYKRTAKVLKAAPQY---
------------NIDGDLKSVVERQRDKKIPYAVIRGTVTPIGVPLRSSLVPSV------
-SGVLQIVKLHEHRVTRG-FAGFWTEQHKLLH-----------ESANEMP-FEL------
-------RNQSHGVEIVDALSA-AVLDVDVVYDNYEPSNL-S---------LFDHVFGFF
SGV----RQRGL-----------------QTTEEVLREGSFLTAIGELE-----------
--LDGD-TLRMQPSNE-------------------------------------------G
PLFL-----------------TTATKSTLIKRFEDA----------KTTTILKLVVCSTI
SAILVAFIAKKL--------YRKRKQEREEAKIRERLDT-ERRE----------------
-------------------------------------RRARSRPHT--------------
--LSQDQLCVVCSTN--P-KEIILLPCGHVCLCEDCAQKISV-------TCPVCRGSIVS
--KAAAFIA---------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>rsz31o21_6
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------CRVVRSVP----------
-------------------------------HSRFRPWF---------------------
-----------------------------TRTPRTTMFGRRVYALLE-------------
-------IPKIHSSXC-------------------------------------------W
SLFLXANVLGPLHSLLHGEGXSRTAQRALSSSMSSRWSRCPQYLPHSRPVWASGTARIAT
AVSCPVDIASRFF-----SNRTRPNSPSIDTRLF-CCSA-LRAP----------------
----------------------------------------KISPRA-AAE----------
--AEHDDLCIICMTD--P-RDTTVLPCGHLCLCVDAQLLRVR-----SDRCPICRSPVDS
--LLXIRX----------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|CMER|CME171C similar to ring finger protein
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MAESGQVN------------------
-----------------------------RSPTDAVPLTGDT------------------
-------RAPVHSPDD-------------------------------------------T
GFEA-----------------SAHGTSELSKSLDAE------------------------
--------------------------------ATDAAAK-RPAA----------------
---------------------------------------ASSVASS--------------
--SEQPFDCSICFEV--PLEDPVVTMCGHLFCWSCLHRWMAQ-----HATCPVCKSLVDR
ERVIPLYGRGRTREDVSDAPKQQTKVARPNEAIPPRPAARRVEPPPQTANGALPPLRPGA
EHLSDWNVGVGAGSFMPYGTAGGISFTPFGLFPSIFGVQFTFPPQPPTGAPSATSSTAAR
VNPGDSGAYGGVPVSVQTEDATQAMVSRMLLMLGMFVIMCLLLF
>gnl|CMER|CMI144C similar to ring finger protein
---MAIIVFGIVAAVCVCLLLAAWLYACV-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RERRALRRAMTRESAANRAV-----------
-GDAED-PTRMGNQRA--------------------------------------------
-VFV-----------------DGVYLYSIPGNAGGE----------QRAPPGGVAGAGVW
GPTRIPASLVLAR-------LDKTSPPAPLTSCPSCGAE-SPAA----------------
---------------------------------------AAALATV-PNESQREGKGLCG
ADGVYCQCCSICLDPFMKGDMSRKLSCGHLFHSHCISKWVQR-----ANRCPLCQHEIVR
--LEEVVQDLRQTQGGSGSS----------------------------------------
----------------------------------------TGTAQDADTGTTAAPGSART
QPPSDSSISGTARSTAQENRPVPRPRNAQQYPLLGSLGSGFFFA
