>Selaginella_moellendorffii_91152_PACid_15413277
--------------------GIVLGLGMAALALRTWLKFGSHTRALKQVEGTAQVEIHDL
RSLVESGEKEPSSD---------SSPPLVIVRGRVALPPKTSSEEVLLARNQTD------
-LAVFVERTQTYLFNEWR-GLFRWGPEWRGLLG-WGSLKEQVAFSRRKIP-FVLLD--SD
-PQYD---GACVHINMENVE-HPLPLVTVFHQLHPVQT-S-------------SSTFLQA
VFGRRYPVGV-----------------IDEEKILPLNREITAVGFLS------------K
HPQG-LPAIKSSNQ-------------------------------------------MPF
FL-----------------TEFSREELIVELASA----------THALFWTGIVISSLAL
GVIGYSAFKN--------WCKWKEWRRL-R---QIQE-ELRR------------------
------------------EEQVMEED-E---------EPATTQE-GSE------------
VPDGQLCVVCLL---RRKRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSV----
---SGYIRVY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
------------------------------------------------------------
--AVFVERTQTYVLTEMS-NFLGWI-----------TQKDLVKFTRQVVP-FVLAETEAH
WSFRPSDMAVYVHINLDESQ-HPIPLVTVHHQLHPVPA-S-------------SYTLFQA
MFGRRYPVGL-----------------LDEEKILPLGAEITAVGVLH------------T
APDG-TPVVKSSKR-------------------------------------------LPI
FL-----------------TEFTREQLLVELASS----------TKVLFWMGVAVSTVAA
GVLGYSLVKN--------WTRWKQRQQQ-R---QSQN-NSEN------------------
------------------RQNSTIED--------------EAEN-FED------------
IPDGELCVVCLL---RRRRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSV----
---TGIVRVY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
------------------------------PRIAAVRGYVRTQGSFLRAPFSSE------
-AGVVVKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRAVP-FVLAS--TE
-LGNS---TGVVHINVDEVDYQPLPLTTVFHKLIPLET-T-------------PYTLFQT
IIGNGYPIAL-----------------LDEEKILPIGKKITAIGLCR-------------
AKNAESVEITSCPE-------------------------------------------IPF
FL-----------------SELTKDEMQAQLASR----------ARILFWGSIVLGTLSV
CLVGHAIYRG--------WKRIKLRREA-R---QAQQ-MFED------------------
------------------AEDA--IR-E---------DNSSDDD-DDD------------
VGDGQLCVVCLR---KRRKAAFIPCGHLVCCCKCALRMER---EVEPLCPMCRQDI----
---RYMIRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
------------------------------------------------------------
------------------------------PRIAAVRGYVRAHDKFFRAPFSGE------
-AGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRSVP-FVLVS--TE
-LGNP---TGVVHINVDKAD-QPLPLTTVFHKLIPLET-T-------------PYTLFQT
IIGNGYPIAL-----------------LDEEKILPIGKKITAIGLCQ-------------
AKDAESVEITSCPE-------------------------------------------IPF
FL-----------------SELTKDEMQAQLASR----------ARILFWGSIVLGTLSV
CLVGHAIYRG--------WTRIKLRREA-R---HARQ-MFEE------------------
------------------AEDA--IH-R---------DDSS--D-DDE------------
IGDGQLCVVCLR---KRRRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDI----
---RYMMRVY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
-------------------------------------------------PWSGE------
-HGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTYFRSVP-FVLAS--SE
-IGNP---IGMVYIDVEKAA-QPLPLTTVFHKLIPIET-T-------------PYTLFQT
IIGNGYPIAL-----------------LDEEKILPIGKELTAIGLCR-------------
ANDEGSVEISSCPE-------------------------------------------LPF
FL-----------------SELTKDEMQAQLASR----------ARILFWGSVVLGTLSV
CLVGHAIYRG--------WKRIKLRREA-R---QAQQ-LFEE------------------
------------------GEDA--IQ-E---------DDSS----DEE------------
VGDGQLCVVCLR---KRRKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDI----
---RYMMRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
---------QLCLFNEWR-GIFGWTFDLHALF--FKSIKEQIITSFRWVP-FVLVD--PE
---NM---TGMVHVKLDRAM-QPLPLTTVYHKLTPVDS-T-------------PYTLFQT
IIGNGYPIAL-----------------LDEEKILPVGKEITAIGYIR-------------
PHKA-SVEISSCSE-------------------------------------------IPF
FL-----------------SDLTKDEMEAELSSR----------AKTLFWASVVLGTMSV
CLLGFATYRS--------WKKIKERREA-R---QAQE-VFRQ------------------
------------------TTDE--VT-D---------DQSSDEE-AGE------------
MGDGQLCVICLR---KRRKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDI----
---RYMIRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ALF--FKSLKEQTITSFRWVP-FALVDPASA
-SDKS---TEMIHVKLDGAVQQSLPLTTVYHKLIPVEQ-N-------------SYTLFQT
IVGNGYPIAL-----------------LDEEKILPIGKEITAIGLCR-------------
VNNQ-NVEITSCPE-------------------------------------------IPF
FL-----------------SDLTKGEIEAELDSR----------ARTLFWVTFALGTMSV
GLLGHAIYRF--------WEKVKQHREA-R---QAQQ-RFHQ------------------
------------------ADDEDDTG-E---------NGSDDDF-PGE------------
MGDGQLCVICLR---KRRKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDI----
---QYMLRVY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
------------------------------------------------------------
--AVILQRTQTCIYNEWK-GFFGWTSDLRSIF--GRSLKEQETTFLRTVP-FTLVE--GG
-QWPQ---SDYVIVNMDGSS-HPLPLTMVYHQLQPIVA-S-------------RYTFIQA
LFGHEYPVGV-----------------LHEEKILPLGKCISAVGICN-------------
SKDG-IPEIKSCKE-------------------------------------------LPY
FL-----------------ADMTKDEMVADLAFK----------AKILLWSGIVLGSLSI
GVLGFAVMRN--------WNKWKAWRQR-R----SQQ-PIHT------------------
------------------TSDE--DV-S---------QIDDNED-AGD------------
VPEGQLCVICLM---RRRRAAFIPCGHLACCHTCAVSVES---EVSPKCPLCRQAV----
---RNSIRIF--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWR-GFFGWTSDIRTLF--ARSWKEKESTSLRTVP-FILVE--GG
-RWPQ---SDYVIVNMDGSR-HPLPLTTVYHQLQPVNA-S-------------PYTFLQA
LFGHDYPVGL-----------------LDEEKLLPLGKEITAVGICS-------------
LKNG-IPEIKSCKD-------------------------------------------LPY
FL-----------------SEMSKDQMVVDLVFK----------SKVLFWSGVILGSVSI
GVLGYAVVRN--------WNRWKEWRQQ-R---GVRP-PSQA------------------
------------------VTDD--TD-T---------QI-AEDD-AGD------------
VPDGELCVICLM---RRKRSAFVPCGHLVCCQRCALSVER---ELSPKCPVCRQII----
---RSSVRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTLSRSVP-FVLVE--AG
-RWPQ---SDYVIVNLDGSR-HPLPLTTVYHQLQPIDA-S-------------PYTFLQA
FFGYEYPVGL-----------------LDEEKILPLGKEINAVGLCG-------------
SKNG-ILEITSCKD-------------------------------------------LPF
FL-----------------SDLSKEQMVVDLAFK----------TKVLFWSGVVLGSFSI
CILGYAAVRN--------WNRWKAWRQQ-R---QFQQ-QSNS------------------
------------------VSDA--DV-S---------QIDVEEE-TVD------------
VPDGQLCVICLM---RRRRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAV----
---RNSIRIFE-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTSLRMVP-FVLVE--GG
-RWPQ---SDYVIVNIDGSR-HALPLTTVYHQLQPIDA-S-------------PYTFLQA
LFGHEYPVGL-----------------LDEEKILPLGKEINAVGICS-------------
SRNG-VLEIKSCKD-------------------------------------------LPY
FL-----------------SDMTKDQMVVDLAFK----------TKVLLWSGVVLGSLSI
GILGYAAVRN--------WNRWKEWRQH-R---QSQQ-QNHA------------------
------------------ASTD--DD-P---------QIDADEE-AGD------------
VPDGQLCVICLM---RRRRSAFIPCGHLVCCQLCAISVER---EVSPKCPLCRQAV----
---RNSMRIF--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------RTVP-FVLID--GS
-QWPA---VDYVVVNMDGSK-HHLPLTTVYHQLQPINA-S-------------PYTFLQA
LFGHEYPVGL-----------------LDEEKILPIGKDVSAVGLCF-------------
LKNG-ILEIKSCKD-------------------------------------------LPY
FL-----------------TEMTKDQMVIDLAFR----------TKILFWSSIFLGSASI
GILGFAFVRN--------WNRWKEWRQR-R---RDEQ-QSHA------------------
------------------AVDE--AT-A---------HI-AEDE-LGD------------
APDGQLCVICLM---RRRRSAFVPCGHLVCCQRCALSVER---EVSPKCPVCRQTI----
---TNSVRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
------------------------------------------------------------
------------------------------------------------------------
--GVVLQRTQTCIYNEWK-GLFGWTSDLRALF--LRSWRQQESTSLRKIP-FVLID--VG
-RPSN---PEYVVVNMDGSS-HPLPLTTVYHRLQPVNP-P-------------PYTFLQA
LFGHEYPVGL-----------------LDEEKILPLGKDVSAVGLCS-------------
LRNG-IAEIKACND-------------------------------------------LPY
YL-----------------SDLSKDQMIVDLSFK----------TKLLFWSGILLGSMSV
GIIGYAVVRN--------WNKWKQWKQQ-R---QLQQ-RRQQ------------------
------------------PIEP---------------VPPTDDE-IED------------
VPDGQLCVICLM---RRRRSVFIPCGHLVCCQGCAISVES---EVAPKCPVCRQEV----
---RDSVRIFE-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWK-GLFGWTSDLRAIF--ARSWRQQESTSLRKVP-FLLTD--VG
-RRPN---AEYVVVNMDGSR-HPLPLTTVYHKLQPITA-S-------------PYTFLQA
LFGHEYPVGL-----------------LDEEKILPLGKDITAVGLCS-------------
LKNG-IAEIKSCKY-------------------------------------------LPY
FR-----------------SDLSKDQMIMDLSIK----------TKILFWGGIALGSMSV
GVLGYAVVRN--------WNKWKQWKQQ-R---QLQQ-QRQA------------------
------------------VSDV---------------EPQMDDE-IED------------
APDGQLCVICLM---RRRRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEI----
---RDSVRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------NA-S-------------PYTFLQA
LFGHEYPVGL-----------------LNEEKILPLGKDISAVGICS-------------
FKNG-IPEIMSCKD-------------------------------------------LPY
FL-----------------SDLTKDQMLLDLAFR----------TKILFWSGIILGSLSI
SILGYAALRN--------WNRWKERRQQ-R---QAHQ-PSHA------------------
------------------ASID--AN-S---------ELTGEEE-IGD------------
IPDGQLCVICLM---RRRVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEI----
---RGSMRVF--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------------IF--SRSWRERESKVFRTVP-FILAE--GG
-RRPI---SEFVAVDMDGSR-HPLPLTTVYHHLHPVNP-S-------------PYTFLEA
LFGHRYPVGL-----------------LDEEKILPLGKEISAVGLCS-------------
VKDG-VLEIKSCKD-------------------------------------------FPY
FL-----------------SEMSKDQMVVDLTSR----------TKVLFWSGIFLGSVSI
GVLAYAVSRN--------WNRWKVWRQQ-R---ELQR-SIRA------------------
------------------SNAE--AQIQ---------EEEEEED-AGD------------
VPDGQLCVICLM---RRRRSAFIPCGHLVCCQLCSISIER---DVAPKCPVCRQQI----
---RTSVRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Citrus_clementina_0.9_012450m_PACid_19274708
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VNMDGSR-QPLPLTTAYQRLELANV-S-------------PFTFLQA
MFGLKCPIGV-----------------LAEEKILPLGKDISAVGICS-------------
FKNG-IPEIKSCKD-------------------------------------------LPY
FL-----------------SEKTKDLMVVDLVNR----------SKILFWSGIVLGSLSI
GILGYAIVRN--------WNRWKD-RQQ-R---MSRQ-LTEA------------------
------------------PSDD--AD-S---------QIGSDEDVAGD------------
IPDGQLCVVCLT---RRRISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTV----
---RSSMRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VNMDGSR-QPLPLTTAYQRLELANV-S-------------PFTFLQA
MFGLKCPIGV-----------------LAEEKILPLGKDISAVGICN-------------
FKNG-IPEIKSCKD-------------------------------------------LPY
FL-----------------SEKTKDQMVVDLVNR----------SKILFWSGIVLGSLSI
GILGYAIVRN--------WNRWKD-RQQ-R---MSRQ-LTET------------------
------------------PSDD--AD-S---------QIGSDEEVAGD------------
IPDGQLCVVCLT---RRRISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTV----
---RSSMRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
------------------------------------------------------------
--GVILQRIQTCIYNEWR-GLFRWTADLGSMLMPRRITKENASSSMNMVP-FILVE--EG
-KWPP---SDHVVVNMEGST-HPLPLTTVYQHLQPVKA-S-------------SYTVFQA
LVGLEYPVGL-----------------LYEEKILPLGKDITAVGICN-------------
LKNG-IPEIKSCED-------------------------------------------LPY
FL-----------------SILTKDQMIADLSFK----------SKVLLWSGLILGTVAI
GVLGYSISRN--------WSKWKEWKAR-R---AQQQ-QNAS------------------
------------------RIEN-----L---------DETEEEE-SGD------------
VPDGELCVVCLM---RRRRSAFVPCGHLVCCHRCAFSVER---EVSPKCPVCRQPI----
---RNSVRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------PYTLIQA
IVGHAYPVGL-----------------LDEEKILPLGKEITAVGHCT-------------
LQDG-NPQIISCKK-------------------------------------------VPY
FL-----------------SDMTKDQMIVDLVSK----------KKILFWAGIVLGSVSL
GVLGYALTRN--------WQRLKEWRQR-R---QIQQ-SREE------------------
------------------EIANLDATPE---------DTRADEE-TED------------
IPEGQLCVICLM---RRKRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDI----
---RTSVRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------A-T-------------PYTFLQA
VFGHEYPVGV-----------------LDEEKILPLGKNISAVGICS-------------
FENG-VPVIKSCSD-------------------------------------------FPH
FL-----------------CEMTKDQMILDLVFK----------TKFLFWSSIVLGSLTV
GILGYSAARN--------WNRWKQWRQH-R---QLQN-SRNDSPTSQLDSSNDIPIYGDF
ASDDEAATVPDDELSSHVPDDE--LS-S---------HVPDDEL-SSH------------
VPDGQLCVICLM---RRKRSAFIPCGHLVCCERCAVSVER---ESSPKCPICRQQI----
---RSSVRIY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Tomato_Solyc12g049330.1.1 genomic_reference:SL2.31ch12 evidence_code:10F0H1E0IEG gene_region:46263202-46267916 functional_description:"Zinc finger family protein (AHRD V1 ***- D7KLF2_ARALY)"
MSIYDQAAAAVLSQIATAADGALIGLALAYVAVRSIVKFKANSSALHKINDAPSLNVSDL
RSLLSSSDNSDSSNHSDDGKLV-IVRGTVEAKSAVEGNWKSLRANILSAHNSAE------
-KGVILQHTQTCIYNEWR-GFFSWAGDLYSIF--PRVRKDQQSSSLRTVP-FVLIE--TG
-RWPQ---PKYVNVNMDGST-HSLPLVTVYHHLQPLHA-T-------------PLTFIQA
LFGHHYPVGV-----------------LDEEKILPLGKDITAIGVCS-------------
SKDG-ILEIKSCED-------------------------------------------LPY
FL-----------------SDMTKDQMLVELAFK----------TKILMWSGVLFGSVAV
GVLGYAVVRN--------WNRWKLWRHQ-R---QAQQ-QRDA------------------
------------------ASND--DD-V---------QVSADEE-SGD------------
VPDGQLCVICLT---RRKRAAFVPCGHLVCCQRC--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>SPL2_Arabidopsis_thaliana_AT1G54150.1_PACid_19654958
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VNMDGSR-QPLPLTTVYNRLQPINS-S----------------FLQA
FLYPDYPVGL-----------------LDIEKILPPGKDITAVGIYS-------------
FNNG-VPEIKSCQD-------------------------------------------LPY
FL-----------------SEMTKDKMIEDLMEQ----------TNFIFLGSVILGIVSV
GILSYAAVRT--------WNKWKQWNHQ-R---ELPQ-RPND------------------
------------------SVVD--DE---------------PED-ADE------------
IPDGELCVICVS---RRRVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSI----
---RGSMRVY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGD------
-KALIIQRTQTYVYSGWK-RLFQSTGHRFML---ERSLRKHGADFTRTVP-FVIVG--KD
-QQSN---SSFVAVNMDGSR-QPLPLTTVYNRLQPINS-S----------------FLQA
FLYPDYPVGL-----------------LDIEKILPPGKDITAVGIYS-------------
FNNG-VPEIKSCQD-------------------------------------------LPY
FL-----------------SEMTKDKMIEDLMEQ----------TNFIFLGSVILGIVSV
GILSYAAVRT--------WNKWKQWNHQ-R---ELPQ-RPND------------------
------------------SVVD--DE---------------PED-ADE------------
IPDGELCVICVS---RRRVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSI----
---RGSMRVYY-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------S--
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VNMDGSR-QPLPLTTVYNRLQPINS-S----------------FLQA
FLFPDYPVGL-----------------LDIEKILPPGKDITAVGICS-------------
FNNG-VPEIKSCQD-------------------------------------------LPY
FL-----------------SEMTKDKMIEELMDQ----------TSFIFFGSVILGIVSV
GILSYAAVRT--------WNKWKQWNHQ-R---DLPQ-RPNE------------------
------------------PVVD--DE---------------PED-ADE------------
IPDGELCVICVT---RRRVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSI----
---RGSMRVY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------VIVDLDSST-HLLPLTTVYHKLQDLHV-MS--------DEILPYAFLEA
FF---LPVGH-----------------M-QKKILPLGKEINAIGLCS-------------
LQDG-NLHIKATQE-------------------------------------------LPY
FL-----------------SEMTKGEMVKHLAYK----------TTILFWGGCIIGIVSL
GVLGYTSFRI--------WEWWKVRRQH-F---SNAE-V---------------------
------------------------DD-V---------YIG-----NDE------------
IPSEQLCTICTM---RRKKYACVPCGHLVCCHKCARSIQH---DSTARCPECRH------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-LGHAYPFGLCLQEKFLPLNFAWYHPGLLEEKILPLGKEISVVGIGT-------------
SEYG-NVEIKPCDE-------------------------------------------LPY
FL-----------------SDLTKDQMIGELAQK----------TNYLLLSAIFFGSLSL
AVIAYAVMIG--------CQRFEEKTQQRR---QVQQ-QMTQ------------------
------------------VQQSLRND-------------VVEEG-MEA------------
LPEGLSCVV----------SVFVPCGHLVCCQTCAPLVAR-----DRRCPICRQYI----
---QKYIITY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Physcomitrella_patens_Pp1s12_190V6.2_PACid_18048531
---M-----LSWGGITLCLSGAAL-------------YCLSRNTGRDALNLRSIERV---
------------NQLKDLAILLESACK--VVPLVVTVAGRVGSETPIACEHSSL------
-RGVILEETAEQHFLKHN-DTGSWIQDSALML-----------SISKEVP-WYLEDGTGR
-----------VYIVGARNA-AGMELTVASEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRVERVLPTGTNLTVVGEAV------------Q
DDRG-LIRIQKPNK-------------------------------------------GPF
YV-----------------TPKSLDQLVANLGRW----------SRWYKYMSLGFTIVGI
YFITSHAIKHF-------MERRRREALHRRVM-EAAA-LRQA------------------
------------------SQREGGDGDMGDVTSHPLDDSVDTSQ-KKD------------
RGTPDLCVICLE---QDYNAVFLPCGHMCCCTSCSAQLTS--------CPLCRRHI----
---DKFVKTYRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Physcomitrella_patens_Pp1s175_124V6.2_PACid_18055474
---M-----LSWGGITLCFSGAAL-------------YCLSRNTGRDALHLMSVERV---
------------NQLEDLAKLLESACT--VVPWVVTVAGRVGAEAPIASEHSSL------
-RGVILEKSAEQHFLKHN-DTGSWIQHSALML-----------SISKEVP-WYLEDGTSR
-----------VFIIGARNA-AGMDLTVASESFEEYGG-S---------LVRGTLDYLQG
L----KMLGV-----------------KRVERVLPTGTNLTVVGEAV------------Q
DDRG-LIRIQKPDK-------------------------------------------GPF
YV-----------------TPQSQDQLIENLGRW----------SRWCQYMSFGLTLVGI
YFITSRAIKHM-------LERWRREALLTRVM-EAAA-LRKA------------------
------------------LQQEGVDEESDGVTAFPHDDNAHTAQ-KKD------------
GGMPSLCVICLE---QDYNAVLVPCGHMCCCTSCSSQLSL--------CPLCRRHI----
---DQVVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Selaginella_moellendorffii_231449_PACid_15416766
---M-----LPWGGITMCLSGVAL-------------YFLSRNSGRDAATLKAVRRV---
------------DQLKDLAHLLDSACK--AVPLVVTVAGRVGSETPIGCDHSSL------
-RCVILEETAEQHFLKHN-DTGSWIQDSALML-----------SNNKEVP-WFLEDASGR
-----------VFIVGARGA-AGLELTIASEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRVERVLPTGTALTVVGEAI------------K
DDQG-TLRIQRPHK-------------------------------------------GPF
YV-----------------TPKSIDQLIANLGKW----------SRWYKYMSLGFTLFGV
FLVASHTIRYV-------MEKRRRAALNRRVM-EAAA-RRRE------------------
------------------RKEHEGKAQVGEF------AKVETAT-KRD------------
GRLPDLCVICLE---QEYNAVFVPCGHMCCCISCSAQLQN--------CPLCRRRI----
---EQIVKTYRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Medicago_truncatula_Medtr1g111550.1_PACid_17439105
---M-----VPWRGVGCCLSAAAL-------------YLLGRTSGRDVDILKSVNRV---
------------NQLRELAQLLDEE----IFPLVVAISGRVGSETPISCEFSGL------
-RGVIIEETAEQHFLKHS-DAGSWIQDSALMQ-----------SRSNEVP-WYLDDGTGR
-----------VRVVGAQGA-TGFVLPVGSEAFEESGR-L---------PVRGTSDYVQG
L----KMLGV-----------------KRIERVLPVGTSLTVVGEAA------------K
DDVG-TIRIQRPSK-------------------------------------------GPF
YV-----------------SPKTIDELIANIGRW----------ARWYKYASAGLTVLSV
YMIANHAVRYI-------LERRRRNELEKRVL-AAAA-KISG------------------
------------------QDNGGE--MD---------DSLSDGA-KRE------------
RAMPNLCVICLE---QEYNSVFVPCGHMCCCTACSSHLTS--------CPLCRRQI----
---EKAVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Glycine_max_Glyma10g02920.1_PACid_16278382
---M-----IPWGGLSCCLSAAAL-------------YLLGRSSGRDAEILKSVTRV---
------------NQLKELAQLLDAE----ILPLIVTISGRVSSETPINCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTDR
-----------VHVVGARGA-SGFALPVGIEAFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPVGTSLTVVGEAA------------K
DDVG-AIRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDQLIANLGKW----------ARWYKYASVGLTVFGA
YLIAKHAIRYI-------LERRRRSELQRRVL-AAAA-KKSG------------------
------------------QNNDVE--KA---------DSLSDGA-KKD------------
RLMPDLCVICLE---QEYNAVFVPCGHMCCCTACSSHLTN--------CPLCRRQI----
---EKVVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Prunus_persica_ppa008230m_PACid_17644506
---M-----LPWGGLSCCLSAAAL-------------YLLGRSSGRDADILKSATRI---
------------NQLKELAKLLDSEC---ILPLVVAISGRVSSETPITCEFTGL------
-RGVVVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTGR
-----------VHVVGARGA-TGFVLPVASEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTSLSVVGEAV------------K
DDIG-TIRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDQLIANLGKW----------ARWYKYASLGLTVFGV
YLVAKHSVQYI-------LERRRRWELQRRVL-AAAA-KRSG------------------
------------------EDNEGSNEKD---------DNVLDGS-K--------------
RLMPDLCVICLE---HEYNAVFVPCGHMCCCTTCSLHLTN--------CPLCRRRI----
---DQAVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
---M-----LPWGGISCCLSAAAL-------------YLLGRSSGRDAELLKSVTRV---
------------NQLKELAQLLEAE-H--LLPLVVAISGRVSSDTPINCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTGR
-----------AFVLGARNA-TNFILPVVSEVFEESGR-S---------LMRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTSLTVVGEAA------------K
DDIG-TIRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDQLISNLGKW----------ARWYKYASMGLSIFGL
YLVTKHVILYL-------MERRRRWELQKRVL-AAAA-KRSS------------------
------------------QENEGEIEKA---------SNGTDGT-KRD------------
RSMPDLCVICLE---RDYNAVFVPCGHMCCCVACCSHLTN--------CPLCRRRI----
---ELVVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSGSK--VLPFIVTVCGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTGR
-----------AFVVGARGA-TGFVLTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERLLPTGTSLTVVGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDELIENLGKW----------ARWYKYASFGLTIFGT
FLIAKRAIHYI-------LQRKRRWELHRRVL-AAAAVKRSE------------------
------------------QDNEGTNGQA---------ENGSDGT-QRD------------
RVMPDLCVICLE---QEYNAVFVPCGHMCCCIICSWHLTN--------CPLCRRRI----
---DQVVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Citrus_clementina_0.9_003846m_PACid_19263951
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSGSK--VLPFIVTVCGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTGR
-----------AFVVGARGA-TGFVLTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERLLPTGTSLTVVGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDELIENLGKW----------ARWYKYASFGLTIFGT
FLIAKRAIHYI-------LQRKRRWELHRRVL-AAAAVKRSE------------------
------------------QDNEGTNGQA---------ENGSDGT-QRD------------
RVMPDLCVICLE---QEYNAVFVPCGHMCCCIICSSHLTN--------CPLCRRRI----
---DQVVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
---M-----ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGGSK--VLPSIVSVSGRVGSETPISCEYSGL------
-RGVIVEETTERHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTGC
-----------VFVVGARGA-TGFALTVGSEVFEESGR-S---------LVHGTLDYLQG
L----KMLGV-----------------KRIGRLLPTGTSLTVVGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDELLENLGKW----------ARWYKYASFGLTIFGA
FLIAKRVIRCI-------LQRKRRWELRRRVL-AAAAVQRSE------------------
------------------QDNEGTNGQA---------ENGSDST-QRD------------
RVMPDLCVICLE---QE-------CGHLCCCLICSSRLTN--------CPLCRRRI----
---DQVVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Citrus_clementina_0.9_014777m_PACid_19265048
---M-----ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGGSK--VLPSIVSVSGRVGSETPISCEYSGL------
-RGVIVEETTERHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTGC
-----------VFVVGARGA-TGFALTVGSEVFEESGR-S---------LVHGTLDYLQG
L----KMLGV-----------------KRIGRLLPTGTSLTVVGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDELLENLGKW----------ARWYKYASFGLTIFGA
FLIAKRVIRCI-------LQRKRRWELRRRVL-AAAAVQRSE------------------
------------------QDNEGTNGQA---------ENGSDST-QRD------------
RVMPDLCVICLE---QEYNAVFFPCGHLCCCLICSSRLTN--------CPLCRRRI----
---DQVVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
---M-----LPWGGISCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKELAKLLDIESN--ISPSVVSISGRVGSETPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTDR
-----------VYVVGARGA-SGFVLTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTSLTVVGEAV------------K
DDIG-TVRVQRPHK-------------------------------------------GPF
YV-----------------SPRTIDELIGNLGKW----------ARWYRYASVSLTVFGA
FLIAKHAIQYI-------MERRRRWELQSRVLAAAAA-KRQG------------------
------------------QDSEGSNGKA---------ENGSDNS-KRE------------
RPVPDLCVICLE---QEYNAVFLPCGHMCCCTTCSSHLTN--------CPLCRRRI----
---EQVVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Ricinus_communis_29703.m001546_PACid_16806242
--------------------------------------------------LKSVTRV---
------------NQLNELAKLLDIESK--VLPLVVAISGRVGSETPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTDR
-----------TFVVGARGA-SGFALTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTSLSVIGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDELIGNLGKW----------ARWYRYASVGLTVFGV
FLIAKHAIQYI-------MERRRRWELQSRVL-AAAA-KRQG------------------
------------------QDSDGSNGKA---------ENGSDSS-KRE------------
RPIPDLCVICLE---QEYNAVFLPCGHMCCCTACSSHLTN--------CPLCRRRI----
---EQI------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Vitis_vinifera_GSVIVT01011070001_PACid_17823049
---M-----IPWGGISCCLSAAAL-------------YLLGRSSGRDAEALKSVTRV---
------------QQLKDLVQLLDTACK--VLPLVVTVSGRVGSDTPIKCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDDTGR
-----------AYIVGARGA-TGLVLTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTPLTVVGEAI------------K
DDVG-TIRIQRPHK-------------------------------------------GPF
YV-----------------SPKSIDHLVANLGKW----------ARWYRYASLGFTVFGV
YLIAKSAIQYV-------MERKRCWELRKRVL-AAAS-KKSG------------------
------------------QDSEDPDEKD---------ENGSDNT-KRD------------
RLMPDLCVICLE---QEYNAVFVPCGHMCCCTMCSSQLTN--------CPLCRRRI----
---EQVVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
---M-----IPWGGLSCCLSAAAL-------------YVLGRSSGRDAEALKCVFRV---
------------NQLKELAQLLDTECK--VLPLVVTLCGRVGSDTPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTGR
-----------AYVLGARGA-SGFELNIASEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERLLPVGSSLTVVGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YV-----------------SPKTIDQLISNLGKW----------ARWYRYASYGFTVFGI
CLIAKRAIQYI-------MERKRRWELQRRVL-AAVA-RRSE------------------
------------------QDTEGTDDKT---------KNAPDSA-KRD------------
RSMPDLCVICLE---QEYNSVFVPCGHMCSCTTCSLQLTN--------CPLCRRRI----
---EQAVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Tomato_Solyc06g084360.1.1 genomic_reference:SL2.31ch06 evidence_code:10F0H1E1IEG gene_region:45791481-45798777 functional_description:"Baculoviral IAP repeat-containing protein 3 (AHRD V1 *--- B0XJ37_CULQU); contains Interpro domain(s)  IPR001841  Zinc f
---M-----VPWAGLSCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKDLAQLLDTASK--VLPLVVTISGRVGSDTPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMCKEVP-WYLDDGTGR
-----------TFIVGGRGA-TGLVLTVGSEAFEEAGR-S---------FVRGTLDYLQG
L----KMLGV-----------------KRIERVLPVGTPLTVVGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YI-----------------SHKTIDQLIANLGRW----------ARWYKYASMGFTAVGV
YLLVKHTFHYM-------MERKRHWELRRRVL-AAAA-KRAG------------------
------------------DEDEGSDATA---------ENGVD---NKD------------
LLMPDLCVICLE---QEYNSVFVPCGHMCCCMTCSSHLTN--------CPLCRRRI----
---EQVVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
---M-----IPVGGITCCLSAAAL-------------YLLGRSSGRDADLLKSVTRV---
------------NQLKDLAQLLEAASK--VLPLVVTVSGRVGSETPINCEYSGL------
-RGVIVEQTAEQHFLKHN-DAGSWIQDSALML-----------SMCKEVP-WYLDDGTSR
-----------VHVVGARGA-TGLVLTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGSPLTVVGEAV------------K
DDIG-SIRIQRPHK-------------------------------------------GPF
YV-----------------TDKTIDQLIANLGKW----------SRLYKYASMGLTAFGV
YLLAKHAFQYI-------MDRRRLWETRKRVL-DAAA-KKAG------------------
------------------QNEGALNGEA---------EIGSDSS-NKE------------
RPIPELCVICLE---QEYNSVFVQCGHMCCCMACSSHLTN--------CPL---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
---M-----LPWGGITCCMSAAAL-------------YLLGKSSGRDADILKSVTRL---
------------NQLKDLAQMLDTACK--VLPFVVTVSGRVGSDTPINCEHSGL------
-RGVIVEEAAEQHFMKQN-DSGSWIQDSAQML-----------AMTKEVP-WYLDDGTGR
-----------VHVLGARGA-TGLVLTVASETFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTSLTVVGEAV------------K
DDVG-TIWIQRPHK-------------------------------------------GPF
YV-----------------SPKSIDQLIANLGIW----------ARLYKYASLGFTAFGV
YLIAKHAIRYI-------LERRRLLDFQRRVR-AAAA-QRLE------------------
------------------QDNDGTDGKA---------EDGPDVV-NKD------------
RIMPDICVICLE---QEYNAVFVPCGHLCCCTTCSSHLSN--------CPLCRRRI----
---DQVVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Arabidopsis_lyrata_474968_PACid_16053684
---M-----IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLKTVTRV---
------------NQLKELAQLLELDSK--ILPFIVAVSGRVGSETPIKCEHSGI------
-RGVIVEETAEQHFLKHN-ETGSWVQDSALML-----------SMSKEVP-WFLDDGTSR
-----------VHVMGARGA-TGFALTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGIPLTIVGEAV------------K
DDIG-EFRIQKPDR-------------------------------------------GPF
YV-----------------SPKSLDQLISNLGKW----------SRWYKYASMGFTVFGV
FLITKHVIDSV-------LERRRRRQLQKRVL-DAAA-KRAE------------------
------------------LESEGSNGAR---------ESIADST-KKE------------
DAVPDLCVICLE---QEYNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRI----
---DLAVKTYRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>SP1
---M-----IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLETVTRV---
------------NQLKELAQLLELDSK--ILPFIVAVSGRVGSETPIKCEHSGI------
-RGVIVEETAEQHFLKHN-ETGSWVQDSALML-----------SMSKEVP-WFLDDGTSR
-----------VHVMGARGA-TGFALTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGIPLTIVGEAV------------K
DDIG-EFRIQKPDR-------------------------------------------GPF
YV-----------------SSKSLDQLISNLGKW----------SRLYKYASMGFTVLGV
FLITKHVIDSV-------LERRRRRQLQKRVL-DAAA-KRAE------------------
------------------LESEGSNGTR---------ESISDST-KKE------------
DAVPDLCVICLE---QEYNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRI----
---DLAVKTYRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Populus_trichocarpa_POPTR_0014s13410.1_PACid_18222628
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGR---YLPSLIPL---
------------FFLIISSKLLDIESK--VLPLVVAISGRVGAESPISCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTDR
-----------VYVVGARGA-SGFVLTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTSLTVVGEAV------------K
DDIG-TVRIQRPHK-------------------------------------------GPF
YV-----------------SPKSIDELIGNLGKW----------ARWYKYASLGLTVFGA
FLITKHVIRYI-------MERRRRWELQSRYV-SLVE-GIHD------------------
------------------KMFQG--------------KGHANGA-KRE------------
RPIPDLCVICLE---QEYNAVFLPCGHMCCCITCCSQLSN--------CPLCRRRI----
---EQVVKTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGSDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAISGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYLDDGTGR
-----------VYVVGARSA-AGLILTVASEVFEESGR-T---------LVRGTLDYLQG
L----KMLGV-----------------KRTERVLPTGTSLTVVGEAI------------K
DDVG-TIRIQRPHK-------------------------------------------GPF
YA-----------------SSKSIDQLIVNLGKW----------AKLYRIASMGFATFGV
FLLAKRALQHF-------LERRRRHELQKRVL-NAAA-QRQA------------------
------------------REAEGSKGTS----------DAEPNS-KKD------------
QLVLDICVICLE---QEYNAVFVPCGHMCCCVACSSHLTN--------CPLCRRRI----
---DQAVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVSSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYLDDGTGR
-----------VYVVGARSA-AGLILTVASEVFEESGR-T---------LVRGTLDYLQG
L----KMLGV-----------------KRTERVLPTGTSLTVVGEAI------------R
DDVG-TIRIQRPHK-------------------------------------------GPF
YV-----------------SPKSIDQLIMNLGKW----------AKLYRLASMGFATFGV
FLLAKRAIQHF-------LERKRRHELQKRVL-NAAA-QRQA------------------
------------------REAEGSNGSS----------DTEPNS-KKD------------
QLVLDICVICLE---QEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRI----
---DQAVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYLDDGTGR
-----------VYMVGARSA-AGLILTVASEVFEESGR-T---------LVRGTLDYLQG
L----KMLGV-----------------KRTERVLPTGISLTVVGEAI------------K
DDVG-TIRIQRPHK-------------------------------------------GPF
YV-----------------SPKSIDQLIMNLGKW----------AKLYRLASMGFATFGA
FLLAKRAIQHF-------LERKRRHELQKRVL-NAAA-QRQA------------------
------------------REAEGSIGSS----------DTEPNS-KKD------------
QLVLDICVICLE---QEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRI----
---DQAVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Setaria_italica_Si030396m_PACid_19714000
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYLDDGTGR
-----------VYVVGARAA-AGLILTVASEVFEESGR-T---------LVRGTLDYLQG
L----KMLGV-----------------KRTERVLPTGTSLTVVGEAI------------K
DDVG-TIRIQRPHK-------------------------------------------GPF
YV-----------------SPKSIDQLILNLGKW----------AKLYRLASMGFATFSV
FLLAKRAIQHF-------LERKRRHELQKRVL-NAAA-QRQA------------------
------------------REAEGGKGTS----------NTEPNS-KKD------------
QLVLDICVICLE---QEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRI----
---DQAVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
---L-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSTKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYLDDGTGR
-----------VFVVGARGA-AGLVLTVASEVFEESGR-T---------LVRGTLDYLQG
L----KMLGV-----------------KRTERVLPTGTSLTVVGEAI------------K
DDVG-TIRIQRPHK-------------------------------------------GPF
YV-----------------SPKSIDQLIMNLGKW----------AKLYQLASMGFAAFGV
FLLAKRALQHF-------LERKRRHELQKRVH-AAAA-QRQA------------------
------------------REAEGGNGTS----------DVDSNN-KKD------------
QLVLDICVICLE---QEYNAVFVPCGHMCCCMNCSSHLTN--------CPLCRRRI----
---DQAVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
---M-----VPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVTRT---
------------GSLKDLAAILDTASK--VLPLVVAVSGRVSSDTPLICQQSGM------
-RGVIVEEMAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYLDDGTGR
-----------VYVVGARAA-AGLVLTIASEVFEESGR-T---------LVRGTLDYLQG
L----KMLGV-----------------KRTERVLPTGTSLTVVGEAI------------K
DDVG-TIRIQRPHK-------------------------------------------GPF
YA-----------------SPKSIDQLILNLGKW----------AKLYQLASMGFAAFGV
FLLAKRALQHF-------LQKKRQHELNKRVR-AAAA-QRQA------------------
------------------REAEGADGTS----------NGDPNS-KKD------------
QLVLEICVICLE---QEYNAVFVPCGHMCCCMNCSSHVTN--------CPLCRRRI----
---DQAVRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
---M-----IPWGGITCCMSAAAL-------------YLLGRSSGRDADILRKVTRV---
------------NQLKELAQLLDIESK--IMPLIVAISGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYLDDGTAR
-----------VFVVGARGA-TGFVLTVGSEVFEESGR-S---------LVRGTLDYLQG
L----KMLGV-----------------KRIERVLPTGTSLTVVGEMT------------L
EQ----FRYEDRTN-------------------------------------------GLF
TC------------LQINGSPD------FQLGKW----------ARWYKYASMGLTFLGV
FLIAKRSIEYV-------LERRRRRELQKRVL-AAAA-KRSG------------------
------------------QDNEGSNIIP---------ENGLDGA-KRE------------
HLMPDLCVICLE---QEYNAAFVPCGHMCCCMTCSSHLTN--------CPLCRRRI----
---EQVLRTFRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>SPL1_NP_564745
---M-----IHLAGFTCCLGGVAL-------------YLLTRSTGRD---IKSITRV---
------------YQLKDLEQLVEVESK--VVPLIIAVSGDVGSETPIKCEHSYV------
-LGVFLKRTAEQQVLRRN-WRFSWVRNSTLMQ-----------PMTKEVP-WYLDDGTGR
-----------VNVDVSQGE-LGLALTVGSDVFEKAEPVS---------LVQGALGYLKG
F----KILGV-----------------RHVERVVPIGTPLTVVGEAV------------R
DGMG-NVRIQKPEQ-------------------------------------------GPF
YV-----------------TYIPLDQLISKLGDL----------SRRFKYASMGLTVLGV
ILISKPVIEYILKRIEDTLERRRRQFALKRVV-DAAA-RRAK------------------
------------------PVTGG-------------------GT-SRD------------
GDTPDLCVVCLD---QKYNTAFVECGHMCCCTPCSLQLRT--------CPLCRERI----
---QQVLKIYRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Arabidopsis_lyrata_338432_PACid_16045815
---M-----IHLAGFTCCLGGIAL-------------YLLSRNTGGV---VKSITRV---
------------NHLKDLEQL--VESK--VFPLIIAVSGIVGSETPIKCEHSDI------
-LGVFLKKTAEQQVLSRN-WRFSWVRKSTLMQ-----------PMTKEVP-WFLDDGTGR
-----------VNVAVSQGE-IGLALTVGSDVFEKAEPVS---------LVQGTLDYLKG
L----KILGV-----------------RRVEHVVPIGTPLTIVGEAV------------K
DGMG-NVRIQKPEQ-------------------------------------------GPF
YV-----------------SYVPLDQLISKLGEW----------SRRFKYASMGLTVVGV
ILLSKPVIKYILKKIEDTLERRRRQLLQKRVV----------------------------
------------------------------------------------------------
-DVPDLCVICHD---QKYNTAFVQCGHMCCCLTCSLRLTT--------CPLCREQI----
---QQVLKIYRH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Arabidopsis_lyrata_867782_PACid_16034683
---M-----IHLGGLTCCVSGGVL-------------YLLSMIPGSFFEMLNSVTRV---
------------HQIKDLENLLQVEGK------IIAVSG---------------------
--------TAQQLFLKRN-WLFSWVEDSKWML-----------PQAKEVP-WYL------
------------------------------------------------------------
------MLGV-----------------RRTEHVLPIGTPVTVVGEAV------------K
DGIR-GFRIQKPEK-------------------------------------------GLF
FV-----------------SPVPLDKIISPMGKW----------LRRFKYVYVGLTVVGV
ILISKPVIEYI-------LERRRGRLLRKRVA-DAAA-KRAK------------------
------------------LVARGLETQH---------ENSLDST-SRD------------
RDVLDLCVICLE---QKYDATFVKCGHMCCCLTCSLHVKT--------CPICRRPI----
---EHVLKIDR-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Chlorella_variabilis_gi|307103723|gb|EFN51981.1| hypothetical protein CHLNCDRAFT_27288 [Chlorella variabilis]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------MPCPRAVLCCRIPDNQTQG---------FLGRVVDEVQG
S----RSVGV-----------------RQVERMLPVGTMLTAVGELA------------T
AGGK-MLVLRAPRD-------------------------------------------GAF
YL-----------------SRQPLPDVIASLQAS----------SLACQQWAAAFTAVGA
SMLVAAATQHA-------LTWVRQRRLRQRVE-KAMR-ERAA------------------
------------------AAAAAGGGGA---------AGAPAAS-AAEPQPADVAEAAEG
GARPSLCVVCLE---RPCATVFPACGHMCACSRCSHGLRR--------CPICRSR-----
---GAPIRVYTA------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Micromonas_sp._RCC299_gi|255086321|ref|XP_002509127.1|
---MAGEGHVSWPGVACIATGALFGYSSRAFKRNIPQYTDFRALERDLRAAASRARAEPT
RRRHHPTHAAGENEIRARPAQADDDDDDAPFGMLVAITGAARSDVLVPCVHAKRPDGRTP
ERAIYVDAVTDQYLARQAVRSGEWIRDCVVVA-----------AMAKEAPTWRLEDPAGH
-GVNMHRATSMAQASDAARA-ADWHLSLVHDEFESAGS-AGAGSSLHSRIIANALDVNMG
L----NVLGL-----------------RHRERVLAPGARLTAVGEVFIAPNGGPVGVDGG
DGAG-EIRLRRPRRRKGWRRHGRGWRRKGGTPGDEKSAPGDGDGDGDDAAMSPRMDPNVF
TV-----------------TQKPFDEYVDGFGSW----------GKVNAALGLGFLGVGV
ALVLTKLWRAR-------LTRWREARFLRRMREAEEA-RRAA------------------
------------------GGGEGDDGGDTA-------GTNTDTA-GAK------------
VSPGETCVVCMY---ARSEVVYKECGHLVCCGVCAGRMDR--------CPLCRRRS----
---AH-MRVYR-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------AGL
>Mulan_NP_078820
---MESGGRPSLCQFILLGTTSVV---------TAALYSVYRQKARVSQELKGAKKV---
------------HLGEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLTLQEHKMVWNRTTHLWNDCSKIIH-----------QRTNTVP-FDLVPHEDG
-------VDVAVRVLKPLDS-VDLGLETVYEKFHPSIQ-S---------FTDVIGHYISG
E----RPKGI-----------------QETEEMLKVGATLTGVGELV-------------
LDNN-SVRLQPPKQ------------------------------------------GMQY
YL-----------------SSQDFDSLLQRQESS----------VRLWKVLALVFGFATC
ATLFFILRKQ--------YLQRQERLRLKQMQEEFQE-HEAQ------------------
--------------------------------------LLSRAKPEDR------------
ESLKSACVVCLS---SFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAI----
---TRVIPLYNS------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Mus_musculus_gi_18043560_gb_AAH19516.1
---MESGSRPSLGQVILLGTSSMV---------TAVLYSIYRQKAQVAQELKGAKKI---
------------HLGEDLKGILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLSLQEHKMVWNRTTHLWNDYSKIIH-----------QRTNTVP-FDLVPHEDG
-------VAVSVRVLKPLDS-VDLGLETVYEKFHPSVQ-S---------FTDAIGHYISG
E----RPKGI-----------------QETEEMLKVGATLTGIGELV-------------
LDNN-AVRLQPPKQ------------------------------------------GMQY
YL-----------------SSQDFDSLLHRQESS----------VRLWKVLVLVFGFATC
ATLFFILRKQ--------YLHRQERLRQQQLQEEFLE-HEAQ------------------
--------------------------------------LLSQASPEDR------------
ESLKSACVVCLS---NFKSCVFLECGHVCSCRQCYLALPE-----PKRCPICRREI----
---TRVIPLYNS------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
---MENGGRPSVGQVILLTTSSAI---------TALFYSIYRHKYRSVQTLKEAKKF---
------------CLTDDLPAVLSDLPGKCVPYAVIEGAVTSVKEVLNSQYVENC------
-KGVIQRLSLKEHKMVWNRTTHLWNDHEKIIH-----------QRSNTVP-FDLAPENPG
------ESGVSVRVLRPLEA-VDLGLETIYEKFHPAVQ-S---------FSNILGHYMTG
E----RPKGV-----------------QETEEMLKIGATITGVGELV-------------
LDNK-TIKLQPPKD------------------------------------------GMLF
YL-----------------SSMDYEGLLEKQEVQ----------MRWWRILSIVFGVASC
ITLFFILRRK--------YRHYKEKQHLKNLQREFEE-SRAR------------------
--------------------------------------QRVQQEPQNK------------
EEVQNPCSICLS---TEKSCVFLECGHVCSCISCYQALPS-----PKKCPICRNFI----
---DRIVPLYNS------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Danio_rerio_gi_148922854_ref_NP_001092230.1
---MEASGKPSTAQIVLLATSSAL---------TAVLYTIYKRKSSHVARLREAKKM---
------------SLNPELKTILSEAPGKCVPYAVIEGVVRSVKETLNSQFVDNC------
-KGVIQRLTLNEKKMVWNRTTNLWNDCEKVIH-----------QRTNTVP-FDLAPHDDT
-------VPTTVRVLRPLDA-AELDLETTYENFHPSQQ-S---------LTNVIGHFISG
E----RPQGI-----------------QETEEMLRLGASMTGVGELV-------------
LDNN-LVRLQPPKK------------------------------------------GLRY
FL-----------------SRLDYDTLLSKQEGH----------LRIWRVLTVLLGLTAC
ATFFYLLWRQ--------YVLRKERRKEQSVLDEYRK-WQSK------------------
--------------------------------------RFQELHLAKE------------
DVSPTACTICLN---HERSCVFLECGHVCACEGCYRALPE-----PKKCPICRATI----
---DRIVSLYNS------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
--------------MEFLHESVALGVDLLILGLCAREYVHYK---RTAKVLKAAPQY---
------------NIDGDLKSVVERQRDKKIPYAVIRGTVTPIGVPLRSSLVPSV------
-SGVLQIVKLHEHRVTRG-FAGFWTEQHKLLH-----------ESANEMP-FELRNQSHG
-----------VEIVDALSA-AVLDVDVVYDNYEPSNL-S---------LFDHVFGFFSG
V----RQRGL-----------------QTTEEVLREGSFLTAIGELE-------------
LDGD-TLRMQPSNE-------------------------------------------GPL
FL-----------------TTATKSTLIKRFEDA----------KTTTILKLVVCSTISA
ILVAFIAKKL--------YRKRKQEREEAKIRERLDT-ERRE------------------
--------------------------------------RRARSR-PHT------------
LSQDQLCVVCST---NPKEIILLPCGHVCLCEDCAQKISV-------TCPVCRGSI----
---VSKAAAFIA------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>rsz31o21_6
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------CRVVRSVP----------
-----------------------------HSRFRPWF-----------------------
---------------------------TRTPRTTMFGRRVYALLE---------------
-----IPKIHSSXC-------------------------------------------WSL
FLXANVLGPLHSLLHGEGXSRTAQRALSSSMSSRWSRCPQYLPHSRPVWASGTARIATAV
SCPVDIASRFF-----SNRTRPNSPSIDTRLF-CCSA-LRAP------------------
--------------------------------------KISPRA-AAE------------
AEHDDLCIICMT---DPRDTTVLPCGHLCLCVDAQLLRVR-----SDRCPICRSPV----
---DSLLXIRX-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>gnl|CMER|CME171C similar to ring finger protein
---MAESGQVN-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------RSPTDAVPLTGDT--------------------
-----RAPVHSPDD-------------------------------------------TGF
EA-----------------SAHGTSELSKSLDAE--------------------------
-------------------------------ATDAAA-KRPA------------------
---------------------------------------AASSV-ASS------------
SEQPFDCSICFEV--PLEDPVVTMCGHLFCWSCLHRWMAQ-----HATCPVCKSLV----
-DRERVIPLY----------------------------------GRGRTREDVSDAPKQQ
TKVARPNEAIPPRPAARRVEPPPQTANGALPPLRPGAEHLSDWNVGVGAGSFMPYGTAGG
ISFTPFGLFPSIFGVQFTFPPQPPTGAPSATSSTAA------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------RVNPGDSGAYGGVPVSVQTEDATQAMVS
RMLLMLGMFVIMCLLLF---
>gnl|CMER|CMI144C similar to ring finger protein
---MAIIVFGIVAAVCVCLLLAAWLYACV-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------RERRALRRAMTRESAANRAV-------------
GDAEDPTRMGNQRA---------------------------------------------V
FV-----------------DGVYLYSIPGNAGGE----------QRAPPGGVAGAGVWGP
TRIPASLVLAR-------LDKTSPPAPLTSCPSCGAE-SPAA------------------
-------------------------------------AAALATV-PNESQREGKGLCGAD
GVYCQCCSICLDPFMKGDMSRKLSCGHLFHSHCISKWVQR-----ANRCPLCQHEI----
VRLEEVVQDLRQTQGGSGSSTGTAQDADTGTTAAPGSARTQPPSDSSISGTARSTAQENR
PVPRPRNAQQYPLLGSLGSGFFFA------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
