>Selaginella_moellendorffii_91152_PACid_15413277
--------------------GIVLGLGMAALALRTWLKFGSHTRALKQVEGTAQVEIHDL
RSLVESGEKEPSSD---------SSPPLVIVRGRVALPPKTSSEEVLLARNQTD------
-LAVFVERTQTYLFNEWR-GLFRWGPEWRGLLG-WGSLKEQVAFSRRKIP-FVLL--DSD
PQYD------GACVHINMENVE-HPLPLVTVFHQLHPVQT-S-----SSTFLQAVFGRRY
---PVGV-----------------IDEEKIL---------------PLNREITAVGFLS-
-----------KHPQG-LPAIKSSNQ----------------------------------
---------MPFFL-----TEFSREELIVELASATHALFWTGIVISSLALGVIGYSAFKN
--------WCKWKEWRRL-R---QIQE-ELRR----------------------------
--------EEQVMEED-E---------EPATTQE-GSE------------VPDGQLCVVC
LLRRKRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSGYIRVY----
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
------------------------------------------------------------
--AVFVERTQTYVLTEMS-NFLGWI-----------TQKDLVKFTRQVVP-FVLA--ETE
AHWSFRPSDMAVYVHINLDESQ-HPIPLVTVHHQLHPVPA-S-----SYTLFQAMFGRRY
---PVGL-----------------LDEEKIL---------------PLGAEITAVGVLH-
-----------TAPDG-TPVVKSSKR----------------------------------
---------LPIFL-----TEFTREQLLVELASSTKVLFWMGVAVSTVAAGVLGYSLVKN
--------WTRWKQRQQQ-R---QSQN-NSEN----------------------------
--------RQNSTIED--------------EAEN-FED------------IPDGELCVVC
LLRRRRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSVTGIVRVY----
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
------------------------------PRIAAVRGYVRTQGSFLRAPFSSE------
-AGVVVKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRAVP-FVLA--STE
LGNS------TGVVHINVDEVDYQPLPLTTVFHKLIPLET-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKIL---------------PIGKKITAIGLCR-
------------AKNAESVEITSCPE----------------------------------
---------IPFFL-----SELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRG
--------WKRIKLRREA-R---QAQQ-MFED----------------------------
--------AEDA--IR-E---------DNSSDDD-DDD------------VGDGQLCVVC
LRKRRKAAFIPCGHLVCCCKCALRMER---EVEPLCPMCRQDIRYMIRIY----
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
------------------------------------------------------------
------------------------------PRIAAVRGYVRAHDKFFRAPFSGE------
-AGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRSVP-FVLV--STE
LGNP------TGVVHINVDKAD-QPLPLTTVFHKLIPLET-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKIL---------------PIGKKITAIGLCQ-
------------AKDAESVEITSCPE----------------------------------
---------IPFFL-----SELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRG
--------WTRIKLRREA-R---HARQ-MFEE----------------------------
--------AEDA--IH-R---------DDSS--D-DDE------------IGDGQLCVVC
LRKRRRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDIRYMMRVY----
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
-------------------------------------------------PWSGE------
-HGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTYFRSVP-FVLA--SSE
IGNP------IGMVYIDVEKAA-QPLPLTTVFHKLIPIET-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKIL---------------PIGKELTAIGLCR-
------------ANDEGSVEISSCPE----------------------------------
---------LPFFL-----SELTKDEMQAQLASRARILFWGSVVLGTLSVCLVGHAIYRG
--------WKRIKLRREA-R---QAQQ-LFEE----------------------------
--------GEDA--IQ-E---------DDSS----DEE------------VGDGQLCVVC
LRKRRKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDIRYMMRIY----
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
---------QLCLFNEWR-GIFGWTFDLHALF--FKSIKEQIITSFRWVP-FVLV--DPE
--NM------TGMVHVKLDRAM-QPLPLTTVYHKLTPVDS-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKIL---------------PVGKEITAIGYIR-
------------PHKA-SVEISSCSE----------------------------------
---------IPFFL-----SDLTKDEMEAELSSRAKTLFWASVVLGTMSVCLLGFATYRS
--------WKKIKERREA-R---QAQE-VFRQ----------------------------
--------TTDE--VT-D---------DQSSDEE-AGE------------MGDGQLCVIC
LRKRRKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDIRYMIRIY----
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ALF--FKSLKEQTITSFRWVP-FALVDPASA
SDKS------TEMIHVKLDGAVQQSLPLTTVYHKLIPVEQ-N-----SYTLFQTIVGNGY
---PIAL-----------------LDEEKIL---------------PIGKEITAIGLCR-
------------VNNQ-NVEITSCPE----------------------------------
---------IPFFL-----SDLTKGEIEAELDSRARTLFWVTFALGTMSVGLLGHAIYRF
--------WEKVKQHREA-R---QAQQ-RFHQ----------------------------
--------ADDEDDTG-E---------NGSDDDF-PGE------------MGDGQLCVIC
LRKRRKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDIQYMLRVY----
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
------------------------------------------------------------
--AVILQRTQTCIYNEWK-GFFGWTSDLRSIF--GRSLKEQETTFLRTVP-FTLV--EGG
QWPQ------SDYVIVNMDGSS-HPLPLTMVYHQLQPIVA-S-----RYTFIQALFGHEY
---PVGV-----------------LHEEKIL---------------PLGKCISAVGICN-
------------SKDG-IPEIKSCKE----------------------------------
---------LPYFL-----ADMTKDEMVADLAFKAKILLWSGIVLGSLSIGVLGFAVMRN
--------WNKWKAWRQR-R----SQQ-PIHT----------------------------
--------TSDE--DV-S---------QIDDNED-AGD------------VPEGQLCVIC
LMRRRRAAFIPCGHLACCHTCAVSVES---EVSPKCPLCRQAVRNSIRIF----
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWR-GFFGWTSDIRTLF--ARSWKEKESTSLRTVP-FILV--EGG
RWPQ------SDYVIVNMDGSR-HPLPLTTVYHQLQPVNA-S-----PYTFLQALFGHDY
---PVGL-----------------LDEEKLL---------------PLGKEITAVGICS-
------------LKNG-IPEIKSCKD----------------------------------
---------LPYFL-----SEMSKDQMVVDLVFKSKVLFWSGVILGSVSIGVLGYAVVRN
--------WNRWKEWRQQ-R---GVRP-PSQA----------------------------
--------VTDD--TD-T---------QI-AEDD-AGD------------VPDGELCVIC
LMRRKRSAFVPCGHLVCCQRCALSVER---ELSPKCPVCRQIIRSSVRIY----
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTLSRSVP-FVLV--EAG
RWPQ------SDYVIVNLDGSR-HPLPLTTVYHQLQPIDA-S-----PYTFLQAFFGYEY
---PVGL-----------------LDEEKIL---------------PLGKEINAVGLCG-
------------SKNG-ILEITSCKD----------------------------------
---------LPFFL-----SDLSKEQMVVDLAFKTKVLFWSGVVLGSFSICILGYAAVRN
--------WNRWKAWRQQ-R---QFQQ-QSNS----------------------------
--------VSDA--DV-S---------QIDVEEE-TVD------------VPDGQLCVIC
LMRRRRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAVRNSIRIFE---
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTSLRMVP-FVLV--EGG
RWPQ------SDYVIVNIDGSR-HALPLTTVYHQLQPIDA-S-----PYTFLQALFGHEY
---PVGL-----------------LDEEKIL---------------PLGKEINAVGICS-
------------SRNG-VLEIKSCKD----------------------------------
---------LPYFL-----SDMTKDQMVVDLAFKTKVLLWSGVVLGSLSIGILGYAAVRN
--------WNRWKEWRQH-R---QSQQ-QNHA----------------------------
--------ASTD--DD-P---------QIDADEE-AGD------------VPDGQLCVIC
LMRRRRSAFIPCGHLVCCQLCAISVER---EVSPKCPLCRQAVRNSMRIF----
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------RTVP-FVLI--DGS
QWPA------VDYVVVNMDGSK-HHLPLTTVYHQLQPINA-S-----PYTFLQALFGHEY
---PVGL-----------------LDEEKIL---------------PIGKDVSAVGLCF-
------------LKNG-ILEIKSCKD----------------------------------
---------LPYFL-----TEMTKDQMVIDLAFRTKILFWSSIFLGSASIGILGFAFVRN
--------WNRWKEWRQR-R---RDEQ-QSHA----------------------------
--------AVDE--AT-A---------HI-AEDE-LGD------------APDGQLCVIC
LMRRRRSAFVPCGHLVCCQRCALSVER---EVSPKCPVCRQTITNSVRIY----
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
------------------------------------------------------------
------------------------------------------------------------
--GVVLQRTQTCIYNEWK-GLFGWTSDLRALF--LRSWRQQESTSLRKIP-FVLI--DVG
RPSN------PEYVVVNMDGSS-HPLPLTTVYHRLQPVNP-P-----PYTFLQALFGHEY
---PVGL-----------------LDEEKIL---------------PLGKDVSAVGLCS-
------------LRNG-IAEIKACND----------------------------------
---------LPYYL-----SDLSKDQMIVDLSFKTKLLFWSGILLGSMSVGIIGYAVVRN
--------WNKWKQWKQQ-R---QLQQ-RRQQ----------------------------
--------PIEP---------------VPPTDDE-IED------------VPDGQLCVIC
LMRRRRSVFIPCGHLVCCQGCAISVES---EVAPKCPVCRQEVRDSVRIFE---
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWK-GLFGWTSDLRAIF--ARSWRQQESTSLRKVP-FLLT--DVG
RRPN------AEYVVVNMDGSR-HPLPLTTVYHKLQPITA-S-----PYTFLQALFGHEY
---PVGL-----------------LDEEKIL---------------PLGKDITAVGLCS-
------------LKNG-IAEIKSCKY----------------------------------
---------LPYFR-----SDLSKDQMIMDLSIKTKILFWGGIALGSMSVGVLGYAVVRN
--------WNKWKQWKQQ-R---QLQQ-QRQA----------------------------
--------VSDV---------------EPQMDDE-IED------------APDGQLCVIC
LMRRRRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEIRDSVRIY----
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------NA-S-----PYTFLQALFGHEY
---PVGL-----------------LNEEKIL---------------PLGKDISAVGICS-
------------FKNG-IPEIMSCKD----------------------------------
---------LPYFL-----SDLTKDQMLLDLAFRTKILFWSGIILGSLSISILGYAALRN
--------WNRWKERRQQ-R---QAHQ-PSHA----------------------------
--------ASID--AN-S---------ELTGEEE-IGD------------IPDGQLCVIC
LMRRRVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEIRGSMRVF----
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------------IF--SRSWRERESKVFRTVP-FILA--EGG
RRPI------SEFVAVDMDGSR-HPLPLTTVYHHLHPVNP-S-----PYTFLEALFGHRY
---PVGL-----------------LDEEKIL---------------PLGKEISAVGLCS-
------------VKDG-VLEIKSCKD----------------------------------
---------FPYFL-----SEMSKDQMVVDLTSRTKVLFWSGIFLGSVSIGVLAYAVSRN
--------WNRWKVWRQQ-R---ELQR-SIRA----------------------------
--------SNAE--AQIQ---------EEEEEED-AGD------------VPDGQLCVIC
LMRRRRSAFIPCGHLVCCQLCSISIER---DVAPKCPVCRQQIRTSVRIY----
>Citrus_clementina_0.9_012450m_PACid_19274708
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTAYQRLELANV-S-----PFTFLQAMFGLKC
---PIGV-----------------LAEEKIL---------------PLGKDISAVGICS-
------------FKNG-IPEIKSCKD----------------------------------
---------LPYFL-----SEKTKDLMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRN
--------WNRWKD-RQQ-R---MSRQ-LTEA----------------------------
--------PSDD--AD-S---------QIGSDEDVAGD------------IPDGQLCVVC
LTRRRISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRSSMRIY----
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTAYQRLELANV-S-----PFTFLQAMFGLKC
---PIGV-----------------LAEEKIL---------------PLGKDISAVGICN-
------------FKNG-IPEIKSCKD----------------------------------
---------LPYFL-----SEKTKDQMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRN
--------WNRWKD-RQQ-R---MSRQ-LTET----------------------------
--------PSDD--AD-S---------QIGSDEEVAGD------------IPDGQLCVVC
LTRRRISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRSSMRIY----
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
------------------------------------------------------------
--GVILQRIQTCIYNEWR-GLFRWTADLGSMLMPRRITKENASSSMNMVP-FILV--EEG
KWPP------SDHVVVNMEGST-HPLPLTTVYQHLQPVKA-S-----SYTVFQALVGLEY
---PVGL-----------------LYEEKIL---------------PLGKDITAVGICN-
------------LKNG-IPEIKSCED----------------------------------
---------LPYFL-----SILTKDQMIADLSFKSKVLLWSGLILGTVAIGVLGYSISRN
--------WSKWKEWKAR-R---AQQQ-QNAS----------------------------
--------RIEN-----L---------DETEEEE-SGD------------VPDGELCVVC
LMRRRRSAFVPCGHLVCCHRCAFSVER---EVSPKCPVCRQPIRNSVRIY----
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PYTLIQAIVGHAY
---PVGL-----------------LDEEKIL---------------PLGKEITAVGHCT-
------------LQDG-NPQIISCKK----------------------------------
---------VPYFL-----SDMTKDQMIVDLVSKKKILFWAGIVLGSVSLGVLGYALTRN
--------WQRLKEWRQR-R---QIQQ-SREE----------------------------
--------EIANLDATPE---------DTRADEE-TED------------IPEGQLCVIC
LMRRKRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDIRTSVRIY----
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------A-T-----PYTFLQAVFGHEY
---PVGV-----------------LDEEKIL---------------PLGKNISAVGICS-
------------FENG-VPVIKSCSD----------------------------------
---------FPHFL-----CEMTKDQMILDLVFKTKFLFWSSIVLGSLTVGILGYSAARN
--------WNRWKQWRQH-R---QLQN-SRNDSPTSQLDSSNDIPIYGDFASDDEAATVP
DDELSSHVPDDE--LS-S---------HVPDDEL-SSH------------VPDGQLCVIC
LMRRKRSAFIPCGHLVCCERCAVSVER---ESSPKCPICRQQIRSSVRIY----
>Tomato_Solyc12g049330.1.1 genomic_reference:SL2.31ch12 evidence_code:10F0H1E0IEG gene_region:46263202-46267916 functional_description:"Zinc finger family protein (AHRD V1 ***- D7KLF2_ARALY)"
MSIYDQAAAAVLSQIATAADGALIGLALAYVAVRSIVKFKANSSALHKINDAPSLNVSDL
RSLLSSSDNSDSSNHSDDGKLV-IVRGTVEAKSAVEGNWKSLRANILSAHNSAE------
-KGVILQHTQTCIYNEWR-GFFSWAGDLYSIF--PRVRKDQQSSSLRTVP-FVLI--ETG
RWPQ------PKYVNVNMDGST-HSLPLVTVYHHLQPLHA-T-----PLTFIQALFGHHY
---PVGV-----------------LDEEKIL---------------PLGKDITAIGVCS-
------------SKDG-ILEIKSCED----------------------------------
---------LPYFL-----SDMTKDQMLVELAFKTKILMWSGVLFGSVAVGVLGYAVVRN
--------WNRWKLWRHQ-R---QAQQ-QRDA----------------------------
--------ASND--DD-V---------QVSADEE-SGD------------VPDGQLCVIC
LTRRKRAAFVPCGHLVCCQRC---------------------------------
>SPL2_Arabidopsis_thaliana_AT1G54150.1_PACid_19654958
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTVYNRLQPINS-S--------FLQAFLYPDY
---PVGL-----------------LDIEKIL---------------PPGKDITAVGIYS-
------------FNNG-VPEIKSCQD----------------------------------
---------LPYFL-----SEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRT
--------WNKWKQWNHQ-R---ELPQ-RPND----------------------------
--------SVVD--DE---------------PED-ADE------------IPDGELCVIC
VSRRRVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRGSMRVY----
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGD------
-KALIIQRTQTYVYSGWK-RLFQSTGHRFML---ERSLRKHGADFTRTVP-FVIV--GKD
QQSN------SSFVAVNMDGSR-QPLPLTTVYNRLQPINS-S--------FLQAFLYPDY
---PVGL-----------------LDIEKIL---------------PPGKDITAVGIYS-
------------FNNG-VPEIKSCQD----------------------------------
---------LPYFL-----SEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRT
--------WNKWKQWNHQ-R---ELPQ-RPND----------------------------
--------SVVD--DE---------------PED-ADE------------IPDGELCVIC
VSRRRVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRGSMRVYYS--
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTVYNRLQPINS-S--------FLQAFLFPDY
---PVGL-----------------LDIEKIL---------------PPGKDITAVGICS-
------------FNNG-VPEIKSCQD----------------------------------
---------LPYFL-----SEMTKDKMIEELMDQTSFIFFGSVILGIVSVGILSYAAVRT
--------WNKWKQWNHQ-R---DLPQ-RPNE----------------------------
--------PVVD--DE---------------PED-ADE------------IPDGELCVIC
VTRRRVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSIRGSMRVY----
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VIVDLDSST-HLLPLTTVYHKLQDLHV-MSDEILPYAFLEAFFL---
---PVGH-----------------M-QKKIL---------------PLGKEINAIGLCS-
------------LQDG-NLHIKATQE----------------------------------
---------LPYFL-----SEMTKGEMVKHLAYKTTILFWGGCIIGIVSLGVLGYTSFRI
--------WEWWKVRRQH----------FSNA----------------------------
--------EVDDVYIG-------------------NDE------------IPSEQLCTIC
TMRRKKYACVPCGHLVCCHKCARSIQH---DSTARCPECRH-------------
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------LGHAY
---PFGLCLQEKFLPLNFAWYHPGLLEEKIL---------------PLGKEISVVGIGT-
------------SEYG-NVEIKPCDE----------------------------------
---------LPYFL-----SDLTKDQMIGELAQKTNYLLLSAIFFGSLSLAVIAYAVMIG
--------CQRFEEKTQQRR---QVQQ-QMTQ----------------------------
--------VQQSL----R---------NDVVEEG-MEA------------LPEGLSCVV-
------SVFVPCGHLVCCQTCAPLVAR-----DRRCPICRQYIQKYIITY----
>Physcomitrella_patens_Pp1s12_190V6.2_PACid_18048531
---M-----LSWGGITLCLSGAAL-------------YCLSRNTGRDALNLRSIERV---
------------NQLKDLAILLESACK--VVPLVVTVAGRVGSETPIACEHSSL------
-RGVILEETAEQHFLKHN-DTGSWIQDSALML-----------SISKEVP-WYL------
-------EDGTGRVYIVGARNA-AGMELTVASEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRVERVL---------------PTGTNLTVVGEAV-
-----------QDDRG-LIRIQKPNK----------------------------------
---------GPFYV-----TPKSLDQLVANLGRWSRWYKYMSLGFTIVGIYFITSHAIKH
F-------MERRRREALHRRVM-EAAA-LRQA----------------------------
--------SQREGGDGDMGDVTSHPLDDSVDTSQ-KKD------------RGTPDLCVIC
LEQDYNAVFLPCGHMCCCTSCSAQLTS--------CPLCRRHIDKFVKTYRH--
>Physcomitrella_patens_Pp1s175_124V6.2_PACid_18055474
---M-----LSWGGITLCFSGAAL-------------YCLSRNTGRDALHLMSVERV---
------------NQLEDLAKLLESACT--VVPWVVTVAGRVGAEAPIASEHSSL------
-RGVILEKSAEQHFLKHN-DTGSWIQHSALML-----------SISKEVP-WYL------
-------EDGTSRVFIIGARNA-AGMDLTVASESFEEYGG-S--------LVRGTLDYLQ
GLKMLGV-----------------KRVERVL---------------PTGTNLTVVGEAV-
-----------QDDRG-LIRIQKPDK----------------------------------
---------GPFYV-----TPQSQDQLIENLGRWSRWCQYMSFGLTLVGIYFITSRAIKH
M-------LERWRREALLTRVM-EAAA-LRKA----------------------------
--------LQQEGVDEESDGVTAFPHDDNAHTAQ-KKD------------GGMPSLCVIC
LEQDYNAVLVPCGHMCCCTSCSSQLSL--------CPLCRRHIDQVVKTFRH--
>Selaginella_moellendorffii_231449_PACid_15416766
---M-----LPWGGITMCLSGVAL-------------YFLSRNSGRDAATLKAVRRV---
------------DQLKDLAHLLDSACK--AVPLVVTVAGRVGSETPIGCDHSSL------
-RCVILEETAEQHFLKHN-DTGSWIQDSALML-----------SNNKEVP-WFL------
-------EDASGRVFIVGARGA-AGLELTIASEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRVERVL---------------PTGTALTVVGEAI-
-----------KDDQG-TLRIQRPHK----------------------------------
---------GPFYV-----TPKSIDQLIANLGKWSRWYKYMSLGFTLFGVFLVASHTIRY
V-------MEKRRRAALNRRVM-EAAA-RRRE----------------------------
--------RKEHEGKAQVGEF------AKVETAT-KRD------------GRLPDLCVIC
LEQEYNAVFVPCGHMCCCISCSAQLQN--------CPLCRRRIEQIVKTYRH--
>Medicago_truncatula_Medtr1g111550.1_PACid_17439105
---M-----VPWRGVGCCLSAAAL-------------YLLGRTSGRDVDILKSVNRV---
------------NQLRELAQLLDEE----IFPLVVAISGRVGSETPISCEFSGL------
-RGVIIEETAEQHFLKHS-DAGSWIQDSALMQ-----------SRSNEVP-WYL------
-------DDGTGRVRVVGAQGA-TGFVLPVGSEAFEESGR-L--------PVRGTSDYVQ
GLKMLGV-----------------KRIERVL---------------PVGTSLTVVGEAA-
-----------KDDVG-TIRIQRPSK----------------------------------
---------GPFYV-----SPKTIDELIANIGRWARWYKYASAGLTVLSVYMIANHAVRY
I-------LERRRRNELEKRVL-AAAA-KISG----------------------------
--------QDNGGE--MD---------DSLSDGA-KRE------------RAMPNLCVIC
LEQEYNSVFVPCGHMCCCTACSSHLTS--------CPLCRRQIEKAVKTFRH--
>Glycine_max_Glyma10g02920.1_PACid_16278382
---M-----IPWGGLSCCLSAAAL-------------YLLGRSSGRDAEILKSVTRV---
------------NQLKELAQLLDAE----ILPLIVTISGRVSSETPINCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRVHVVGARGA-SGFALPVGIEAFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PVGTSLTVVGEAA-
-----------KDDVG-AIRIQRPHK----------------------------------
---------GPFYV-----SPKTIDQLIANLGKWARWYKYASVGLTVFGAYLIAKHAIRY
I-------LERRRRSELQRRVL-AAAA-KKSG----------------------------
--------QNNDVE--KA---------DSLSDGA-KKD------------RLMPDLCVIC
LEQEYNAVFVPCGHMCCCTACSSHLTN--------CPLCRRQIEKVVKTFRH--
>Prunus_persica_ppa008230m_PACid_17644506
---M-----LPWGGLSCCLSAAAL-------------YLLGRSSGRDADILKSATRI---
------------NQLKELAKLLDSEC---ILPLVVAISGRVSSETPITCEFTGL------
-RGVVVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRVHVVGARGA-TGFVLPVASEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTSLSVVGEAV-
-----------KDDIG-TIRIQRPHK----------------------------------
---------GPFYV-----SPKTIDQLIANLGKWARWYKYASLGLTVFGVYLVAKHSVQY
I-------LERRRRWELQRRVL-AAAA-KRSG----------------------------
--------EDNEGSNEKD---------DNVLDGS-K--------------RLMPDLCVIC
LEHEYNAVFVPCGHMCCCTTCSLHLTN--------CPLCRRRIDQAVKTFRH--
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
---M-----LPWGGISCCLSAAAL-------------YLLGRSSGRDAELLKSVTRV---
------------NQLKELAQLLEAE-H--LLPLVVAISGRVSSDTPINCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAFVLGARNA-TNFILPVVSEVFEESGR-S--------LMRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTSLTVVGEAA-
-----------KDDIG-TIRIQRPHK----------------------------------
---------GPFYV-----SPKTIDQLISNLGKWARWYKYASMGLSIFGLYLVTKHVILY
L-------MERRRRWELQKRVL-AAAA-KRSS----------------------------
--------QENEGEIEKA---------SNGTDGT-KRD------------RSMPDLCVIC
LERDYNAVFVPCGHMCCCVACCSHLTN--------CPLCRRRIELVVKTFRH--
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSGSK--VLPFIVTVCGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAFVVGARGA-TGFVLTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERLL---------------PTGTSLTVVGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYV-----SPKTIDELIENLGKWARWYKYASFGLTIFGTFLIAKRAIHY
I-------LQRKRRWELHRRVL-AAAAVKRSE----------------------------
--------QDNEGTNGQA---------ENGSDGT-QRD------------RVMPDLCVIC
LEQEYNAVFVPCGHMCCCIICSWHLTN--------CPLCRRRIDQVVRTFRH--
>Citrus_clementina_0.9_003846m_PACid_19263951
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSGSK--VLPFIVTVCGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAFVVGARGA-TGFVLTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERLL---------------PTGTSLTVVGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYV-----SPKTIDELIENLGKWARWYKYASFGLTIFGTFLIAKRAIHY
I-------LQRKRRWELHRRVL-AAAAVKRSE----------------------------
--------QDNEGTNGQA---------ENGSDGT-QRD------------RVMPDLCVIC
LEQEYNAVFVPCGHMCCCIICSSHLTN--------CPLCRRRIDQVVRTFRH--
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
---M-----ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGGSK--VLPSIVSVSGRVGSETPISCEYSGL------
-RGVIVEETTERHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGCVFVVGARGA-TGFALTVGSEVFEESGR-S--------LVHGTLDYLQ
GLKMLGV-----------------KRIGRLL---------------PTGTSLTVVGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYV-----SPKTIDELLENLGKWARWYKYASFGLTIFGAFLIAKRVIRC
I-------LQRKRRWELRRRVL-AAAAVQRSE----------------------------
--------QDNEGTNGQA---------ENGSDST-QRD------------RVMPDLCVIC
LEQE-------CGHLCCCLICSSRLTN--------CPLCRRRIDQVVRTFRH--
>Citrus_clementina_0.9_014777m_PACid_19265048
---M-----ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGGSK--VLPSIVSVSGRVGSETPISCEYSGL------
-RGVIVEETTERHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGCVFVVGARGA-TGFALTVGSEVFEESGR-S--------LVHGTLDYLQ
GLKMLGV-----------------KRIGRLL---------------PTGTSLTVVGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYV-----SPKTIDELLENLGKWARWYKYASFGLTIFGAFLIAKRVIRC
I-------LQRKRRWELRRRVL-AAAAVQRSE----------------------------
--------QDNEGTNGQA---------ENGSDST-QRD------------RVMPDLCVIC
LEQEYNAVFFPCGHLCCCLICSSRLTN--------CPLCRRRIDQVVRTFRH--
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
---M-----LPWGGISCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKELAKLLDIESN--ISPSVVSISGRVGSETPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRVYVVGARGA-SGFVLTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTSLTVVGEAV-
-----------KDDIG-TVRVQRPHK----------------------------------
---------GPFYV-----SPRTIDELIGNLGKWARWYRYASVSLTVFGAFLIAKHAIQY
I-------MERRRRWELQSRVLAAAAA-KRQG----------------------------
--------QDSEGSNGKA---------ENGSDNS-KRE------------RPVPDLCVIC
LEQEYNAVFLPCGHMCCCTTCSSHLTN--------CPLCRRRIEQVVKTFRH--
>Ricinus_communis_29703.m001546_PACid_16806242
--------------------------------------------------LKSVTRV---
------------NQLNELAKLLDIESK--VLPLVVAISGRVGSETPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRTFVVGARGA-SGFALTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTSLSVIGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYV-----SPKTIDELIGNLGKWARWYRYASVGLTVFGVFLIAKHAIQY
I-------MERRRRWELQSRVL-AAAA-KRQG----------------------------
--------QDSDGSNGKA---------ENGSDSS-KRE------------RPIPDLCVIC
LEQEYNAVFLPCGHMCCCTACSSHLTN--------CPLCRRRIEQI--------
>Vitis_vinifera_GSVIVT01011070001_PACid_17823049
---M-----IPWGGISCCLSAAAL-------------YLLGRSSGRDAEALKSVTRV---
------------QQLKDLVQLLDTACK--VLPLVVTVSGRVGSDTPIKCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDDTGRAYIVGARGA-TGLVLTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTPLTVVGEAI-
-----------KDDVG-TIRIQRPHK----------------------------------
---------GPFYV-----SPKSIDHLVANLGKWARWYRYASLGFTVFGVYLIAKSAIQY
V-------MERKRCWELRKRVL-AAAS-KKSG----------------------------
--------QDSEDPDEKD---------ENGSDNT-KRD------------RLMPDLCVIC
LEQEYNAVFVPCGHMCCCTMCSSQLTN--------CPLCRRRIEQVVRTFRH--
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
---M-----IPWGGLSCCLSAAAL-------------YVLGRSSGRDAEALKCVFRV---
------------NQLKELAQLLDTECK--VLPLVVTLCGRVGSDTPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTGRAYVLGARGA-SGFELNIASEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERLL---------------PVGSSLTVVGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYV-----SPKTIDQLISNLGKWARWYRYASYGFTVFGICLIAKRAIQY
I-------MERKRRWELQRRVL-AAVA-RRSE----------------------------
--------QDTEGTDDKT---------KNAPDSA-KRD------------RSMPDLCVIC
LEQEYNSVFVPCGHMCSCTTCSLQLTN--------CPLCRRRIEQAVKTFRH--
>Tomato_Solyc06g084360.1.1 genomic_reference:SL2.31ch06 evidence_code:10F0H1E1IEG gene_region:45791481-45798777 functional_description:"Baculoviral IAP repeat-containing protein 3 (AHRD V1 *--- B0XJ37_CULQU); contains Interpro domain(s)  IPR001841  Zinc f
---M-----VPWAGLSCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKDLAQLLDTASK--VLPLVVTISGRVGSDTPINCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMCKEVP-WYL------
-------DDGTGRTFIVGGRGA-TGLVLTVGSEAFEEAGR-S--------FVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PVGTPLTVVGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYI-----SHKTIDQLIANLGRWARWYKYASMGFTAVGVYLLVKHTFHY
M-------MERKRHWELRRRVL-AAAA-KRAG----------------------------
--------DEDEGSDATA---------ENGVD---NKD------------LLMPDLCVIC
LEQEYNSVFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQVVKTFRH--
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
---M-----IPVGGITCCLSAAAL-------------YLLGRSSGRDADLLKSVTRV---
------------NQLKDLAQLLEAASK--VLPLVVTVSGRVGSETPINCEYSGL------
-RGVIVEQTAEQHFLKHN-DAGSWIQDSALML-----------SMCKEVP-WYL------
-------DDGTSRVHVVGARGA-TGLVLTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGSPLTVVGEAV-
-----------KDDIG-SIRIQRPHK----------------------------------
---------GPFYV-----TDKTIDQLIANLGKWSRLYKYASMGLTAFGVYLLAKHAFQY
I-------MDRRRLWETRKRVL-DAAA-KKAG----------------------------
--------QNEGALNGEA---------EIGSDSS-NKE------------RPIPELCVIC
LEQEYNSVFVQCGHMCCCMACSSHLTN--------CPL----------------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
---M-----LPWGGITCCMSAAAL-------------YLLGKSSGRDADILKSVTRL---
------------NQLKDLAQMLDTACK--VLPFVVTVSGRVGSDTPINCEHSGL------
-RGVIVEEAAEQHFMKQN-DSGSWIQDSAQML-----------AMTKEVP-WYL------
-------DDGTGRVHVLGARGA-TGLVLTVASETFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTSLTVVGEAV-
-----------KDDVG-TIWIQRPHK----------------------------------
---------GPFYV-----SPKSIDQLIANLGIWARLYKYASLGFTAFGVYLIAKHAIRY
I-------LERRRLLDFQRRVR-AAAA-QRLE----------------------------
--------QDNDGTDGKA---------EDGPDVV-NKD------------RIMPDICVIC
LEQEYNAVFVPCGHLCCCTTCSSHLSN--------CPLCRRRIDQVVRTFRH--
>Arabidopsis_lyrata_474968_PACid_16053684
---M-----IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLKTVTRV---
------------NQLKELAQLLELDSK--ILPFIVAVSGRVGSETPIKCEHSGI------
-RGVIVEETAEQHFLKHN-ETGSWVQDSALML-----------SMSKEVP-WFL------
-------DDGTSRVHVMGARGA-TGFALTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGIPLTIVGEAV-
-----------KDDIG-EFRIQKPDR----------------------------------
---------GPFYV-----SPKSLDQLISNLGKWSRWYKYASMGFTVFGVFLITKHVIDS
V-------LERRRRRQLQKRVL-DAAA-KRAE----------------------------
--------LESEGSNGAR---------ESIADST-KKE------------DAVPDLCVIC
LEQEYNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDLAVKTYRH--
>SP1
---M-----IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLETVTRV---
------------NQLKELAQLLELDSK--ILPFIVAVSGRVGSETPIKCEHSGI------
-RGVIVEETAEQHFLKHN-ETGSWVQDSALML-----------SMSKEVP-WFL------
-------DDGTSRVHVMGARGA-TGFALTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGIPLTIVGEAV-
-----------KDDIG-EFRIQKPDR----------------------------------
---------GPFYV-----SSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDS
V-------LERRRRRQLQKRVL-DAAA-KRAE----------------------------
--------LESEGSNGTR---------ESISDST-KKE------------DAVPDLCVIC
LEQEYNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDLAVKTYRH--
>Populus_trichocarpa_POPTR_0014s13410.1_PACid_18222628
---M-----IPWGGISCCLSGAAL-------------YLLGRSSGR---YLPSLIPL---
------------FFLIISSKLLDIESK--VLPLVVAISGRVGAESPISCEFSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTDRVYVVGARGA-SGFVLTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTSLTVVGEAV-
-----------KDDIG-TVRIQRPHK----------------------------------
---------GPFYV-----SPKSIDELIGNLGKWARWYKYASLGLTVFGAFLITKHVIRY
I-------MERRRRWELQSRYV-SLVE-GIHD----------------------------
--------KMFQG--------------KGHANGA-KRE------------RPIPDLCVIC
LEQEYNAVFLPCGHMCCCITCCSQLSN--------CPLCRRRIEQVVKTFRH--
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGSDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAISGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARSA-AGLILTVASEVFEESGR-T--------LVRGTLDYLQ
GLKMLGV-----------------KRTERVL---------------PTGTSLTVVGEAI-
-----------KDDVG-TIRIQRPHK----------------------------------
---------GPFYA-----SSKSIDQLIVNLGKWAKLYRIASMGFATFGVFLLAKRALQH
F-------LERRRRHELQKRVL-NAAA-QRQA----------------------------
--------REAEGSKGTS----------DAEPNS-KKD------------QLVLDICVIC
LEQEYNAVFVPCGHMCCCVACSSHLTN--------CPLCRRRIDQAVRTFRH--
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVSSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARSA-AGLILTVASEVFEESGR-T--------LVRGTLDYLQ
GLKMLGV-----------------KRTERVL---------------PTGTSLTVVGEAI-
-----------RDDVG-TIRIQRPHK----------------------------------
---------GPFYV-----SPKSIDQLIMNLGKWAKLYRLASMGFATFGVFLLAKRAIQH
F-------LERKRRHELQKRVL-NAAA-QRQA----------------------------
--------REAEGSNGSS----------DTEPNS-KKD------------QLVLDICVIC
LEQEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAVRTFRH--
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYMVGARSA-AGLILTVASEVFEESGR-T--------LVRGTLDYLQ
GLKMLGV-----------------KRTERVL---------------PTGISLTVVGEAI-
-----------KDDVG-TIRIQRPHK----------------------------------
---------GPFYV-----SPKSIDQLIMNLGKWAKLYRLASMGFATFGAFLLAKRAIQH
F-------LERKRRHELQKRVL-NAAA-QRQA----------------------------
--------REAEGSIGSS----------DTEPNS-KKD------------QLVLDICVIC
LEQEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAVRTFRH--
>Setaria_italica_Si030396m_PACid_19714000
---M-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARAA-AGLILTVASEVFEESGR-T--------LVRGTLDYLQ
GLKMLGV-----------------KRTERVL---------------PTGTSLTVVGEAI-
-----------KDDVG-TIRIQRPHK----------------------------------
---------GPFYV-----SPKSIDQLILNLGKWAKLYRLASMGFATFSVFLLAKRAIQH
F-------LERKRRHELQKRVL-NAAA-QRQA----------------------------
--------REAEGGKGTS----------NTEPNS-KKD------------QLVLDICVIC
LEQEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQAVRTFRH--
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
---L-----IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSTKDLAAILDTASK--VLPLVVAVSGRVGSDTPLICQQSGM------
-RGVIVEETAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVFVVGARGA-AGLVLTVASEVFEESGR-T--------LVRGTLDYLQ
GLKMLGV-----------------KRTERVL---------------PTGTSLTVVGEAI-
-----------KDDVG-TIRIQRPHK----------------------------------
---------GPFYV-----SPKSIDQLIMNLGKWAKLYQLASMGFAAFGVFLLAKRALQH
F-------LERKRRHELQKRVH-AAAA-QRQA----------------------------
--------REAEGGNGTS----------DVDSNN-KKD------------QLVLDICVIC
LEQEYNAVFVPCGHMCCCMNCSSHLTN--------CPLCRRRIDQAVRTFRH--
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
---M-----VPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVTRT---
------------GSLKDLAAILDTASK--VLPLVVAVSGRVSSDTPLICQQSGM------
-RGVIVEEMAEQHFLKHN-DAGSWIQDSAVML-----------SVSKEVP-WYL------
-------DDGTGRVYVVGARAA-AGLVLTIASEVFEESGR-T--------LVRGTLDYLQ
GLKMLGV-----------------KRTERVL---------------PTGTSLTVVGEAI-
-----------KDDVG-TIRIQRPHK----------------------------------
---------GPFYA-----SPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALQH
F-------LQKKRQHELNKRVR-AAAA-QRQA----------------------------
--------REAEGADGTS----------NGDPNS-KKD------------QLVLEICVIC
LEQEYNAVFVPCGHMCCCMNCSSHVTN--------CPLCRRRIDQAVRTFRH--
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
---M-----IPWGGITCCMSAAAL-------------YLLGRSSGRDADILRKVTRV---
------------NQLKELAQLLDIESK--IMPLIVAISGRVGSETPISCEYSGL------
-RGVIVEETAEQHFLKHN-DAGSWIQDSALML-----------SMSKEVP-WYL------
-------DDGTARVFVVGARGA-TGFVLTVGSEVFEESGR-S--------LVRGTLDYLQ
GLKMLGV-----------------KRIERVL---------------PTGTSLTVVGEMT-
-----------LEQ----FRYEDRTN----------------------------------
---------GLFTCLQINGSPD------FQLGKWARWYKYASMGLTFLGVFLIAKRSIEY
V-------LERRRRRELQKRVL-AAAA-KRSG----------------------------
--------QDNEGSNIIP---------ENGLDGA-KRE------------HLMPDLCVIC
LEQEYNAAFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQVLRTFRH--
>SPL1_NP_564745
---M-----IHLAGFTCCLGGVAL-------------YLLTRSTGRD---IKSITRV---
------------YQLKDLEQLVEVESK--VVPLIIAVSGDVGSETPIKCEHSYV------
-LGVFLKRTAEQQVLRRN-WRFSWVRNSTLMQ-----------PMTKEVP-WYL------
-------DDGTGRVNVDVSQGE-LGLALTVGSDVFEKAEPVS--------LVQGALGYLK
GFKILGV-----------------RHVERVV---------------PIGTPLTVVGEAV-
-----------RDGMG-NVRIQKPEQ----------------------------------
---------GPFYV-----TYIPLDQLISKLGDLSRRFKYASMGLTVLGVILISKPVIEY
ILKRIEDTLERRRRQFALKRVV-DAAA-RRAK----------------------------
--------PVTGG-------------------GT-SRD------------GDTPDLCVVC
LDQKYNTAFVECGHMCCCTPCSLQLRT--------CPLCRERIQQVLKIYRH--
>Arabidopsis_lyrata_338432_PACid_16045815
---M-----IHLAGFTCCLGGIAL-------------YLLSRNTGGV---VKSITRV---
------------NHLKDLEQL--VESK--VFPLIIAVSGIVGSETPIKCEHSDI------
-LGVFLKKTAEQQVLSRN-WRFSWVRKSTLMQ-----------PMTKEVP-WFL------
-------DDGTGRVNVAVSQGE-IGLALTVGSDVFEKAEPVS--------LVQGTLDYLK
GLKILGV-----------------RRVEHVV---------------PIGTPLTIVGEAV-
-----------KDGMG-NVRIQKPEQ----------------------------------
---------GPFYV-----SYVPLDQLISKLGEWSRRFKYASMGLTVVGVILLSKPVIKY
ILKKIEDTLERRRRQLLQKRVV--------------------------------------
---------------------------------------------------DVPDLCVIC
HDQKYNTAFVQCGHMCCCLTCSLRLTT--------CPLCREQIQQVLKIYRH--
>Arabidopsis_lyrata_867782_PACid_16034683
---M-----IHLGGLTCCVSGGVL-------------YLLSMIPGSFFEMLNSVTRV---
------------HQIKDLENLLQVEGK------IIAVSG---------------------
--------TAQQLFLKRN-WLFSWVEDSKWML-----------PQAKEVP-WYL------
------------------------------------------------------------
---MLGV-----------------RRTEHVL---------------PIGTPVTVVGEAV-
-----------KDGIR-GFRIQKPEK----------------------------------
---------GLFFV-----SPVPLDKIISPMGKWLRRFKYVYVGLTVVGVILISKPVIEY
I-------LERRRGRLLRKRVA-DAAA-KRAK----------------------------
--------LVARGLETQH---------ENSLDST-SRD------------RDVLDLCVIC
LEQKYDATFVKCGHMCCCLTCSLHVKT--------CPICRRPIEHVLKIDR---
>Chlorella_variabilis_gi|307103723|gb|EFN51981.1| hypothetical protein CHLNCDRAFT_27288 [Chlorella variabilis]
---M-----PCPRAVLCC------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------RIPDNQTQ-G--------FLGRVVDEVQ
GSRSVGV-----------------RQVERML---------------PVGTMLTAVGELA-
-----------TAGGK-MLVLRAPRD----------------------------------
---------GAFYL-----SRQPLPDVIASLQASSLACQQWAAAFTAVGASMLVAAATQH
A-------LTWVRQRRLRQRVE-KAMR-ERAA----------------------------
--------AAAAAGGGGA---------AGAPAAS-AAEPQPADVAEAAEGGARPSLCVVC
LERPCATVFPACGHMCACSRCSHGLRR--------CPICRSR-GAPIRVYTA--
>Micromonas_sp._RCC299_gi|255086321|ref|XP_002509127.1|
---MAGEGHVSWPGVACIATGALFGYSSRAFKRNIPQYTDFRALERDLRAAASRARAEPT
RRRHHPTHAAGENEIRARPAQADDDDDDAPFGMLVAITGAARSDVLVPCVHAKRPDGRTP
ERAIYVDAVTDQYLARQAVRSGEWIRDCVVVA-----------AMAKEAPTWRL---EDP
AGHGVNMHRATSMAQASDAARA-ADWHLSLVHDEFESAGSAGAGSSLHSRIIANALDVNM
GLNVLGL-----------------RHRERVL---------------APGARLTAVGEVFI
APNGGPVGVDGGDGAG-EIRLRRPRRRKGWRRHGRGWRRKGGTPGDEKSAPGDGDGDGDD
AAMSPRMDPNVFTV-----TQKPFDEYVDGFGSWGKVNAALGLGFLGVGVALVLTKLWRA
R-------LTRWREARFLRRMREAEEA-RRAA----------------------------
--------GGGEGDDGGDTA-------GTNTDTA-GAK------------VSPGETCVVC
MYARSEVVYKECGHLVCCGVCAGRMDR--------CPLCRRRSAH-MRVYRAGL
>Mulan_NP_078820
---MESGGRPSLCQFILLGTTSVV---------TAALYSVYRQKARVSQELKGAKKV---
------------HLGEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLTLQEHKMVWNRTTHLWNDCSKIIH-----------QRTNTVP-FDLVPHED-
-------G-VDVAVRVLKPLDS-VDLGLETVYEKFHPSIQ-S--------FTDVIGHYIS
GERPKGI-----------------QETEEML---------------KVGATLTGVGELV-
------------LDNN-SVRLQPPKQ----------------------------------
--------GMQYYL-----SSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQ
--------YLQRQERLRLKQMQEEFQE-HEAQ----------------------------
---------------------------LLSRAKP-EDR------------ESLKSACVVC
LSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITRVIPLYNS--
>Mus_musculus_gi_18043560_gb_AAH19516.1
---MESGSRPSLGQVILLGTSSMV---------TAVLYSIYRQKAQVAQELKGAKKI---
------------HLGEDLKGILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLSLQEHKMVWNRTTHLWNDYSKIIH-----------QRTNTVP-FDLVPHED-
-------G-VAVSVRVLKPLDS-VDLGLETVYEKFHPSVQ-S--------FTDAIGHYIS
GERPKGI-----------------QETEEML---------------KVGATLTGIGELV-
------------LDNN-AVRLQPPKQ----------------------------------
--------GMQYYL-----SSQDFDSLLHRQESSVRLWKVLVLVFGFATCATLFFILRKQ
--------YLHRQERLRQQQLQEEFLE-HEAQ----------------------------
---------------------------LLSQASP-EDR------------ESLKSACVVC
LSNFKSCVFLECGHVCSCRQCYLALPE-----PKRCPICRREITRVIPLYNS--
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
---MENGGRPSVGQVILLTTSSAI---------TALFYSIYRHKYRSVQTLKEAKKF---
------------CLTDDLPAVLSDLPGKCVPYAVIEGAVTSVKEVLNSQYVENC------
-KGVIQRLSLKEHKMVWNRTTHLWNDHEKIIH-----------QRSNTVP-FDLAPENP-
-------GESGVSVRVLRPLEA-VDLGLETIYEKFHPAVQ-S--------FSNILGHYMT
GERPKGV-----------------QETEEML---------------KIGATITGVGELV-
------------LDNK-TIKLQPPKD----------------------------------
--------GMLFYL-----SSMDYEGLLEKQEVQMRWWRILSIVFGVASCITLFFILRRK
--------YRHYKEKQHLKNLQREFEE-SRAR----------------------------
---------------------------QRVQQEP-QNK------------EEVQNPCSIC
LSTEKSCVFLECGHVCSCISCYQALPS-----PKKCPICRNFIDRIVPLYNS--
>Danio_rerio_gi_148922854_ref_NP_001092230.1
---MEASGKPSTAQIVLLATSSAL---------TAVLYTIYKRKSSHVARLREAKKM---
------------SLNPELKTILSEAPGKCVPYAVIEGVVRSVKETLNSQFVDNC------
-KGVIQRLTLNEKKMVWNRTTNLWNDCEKVIH-----------QRTNTVP-FDLAPHDD-
-------T-VPTTVRVLRPLDA-AELDLETTYENFHPSQQ-S--------LTNVIGHFIS
GERPQGI-----------------QETEEML---------------RLGASMTGVGELV-
------------LDNN-LVRLQPPKK----------------------------------
--------GLRYFL-----SRLDYDTLLSKQEGHLRIWRVLTVLLGLTACATFFYLLWRQ
--------YVLRKERRKEQSVLDEYRK-WQSK----------------------------
---------------------------RFQELHL-AKE------------DVSPTACTIC
LNHERSCVFLECGHVCACEGCYRALPE-----PKKCPICRATIDRIVSLYNS--
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
--------------MEFLHESVALGVDLLILGLCAREYVHYK---RTAKVLKAAPQY---
------------NIDGDLKSVVERQRDKKIPYAVIRGTVTPIGVPLRSSLVPSV------
-SGVLQIVKLHEHRVTRG-FAGFWTEQHKLLH-----------ESANEMP-FEL------
-------RNQSHGVEIVDALSA-AVLDVDVVYDNYEPSNL-S--------LFDHVFGFFS
GVRQRGL-----------------QTTEEVL---------------REGSFLTAIGELE-
------------LDGD-TLRMQPSNE----------------------------------
---------GPLFL-----TTATKSTLIKRFEDAKTTTILKLVVCSTISAILVAFIAKKL
--------YRKRKQEREEAKIRERLDT-ERRE----------------------------
---------------------------RRARSRP--HT------------LSQDQLCVVC
STNPKEIILLPCGHVCLCEDCAQKISV-------TCPVCRGSIVSKAAAFIA--
>rsz31o21_6
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------CRVVRSVP----------
-------------------------------HSRFRPW------------FTRTPRTTMF
GRRVYAL-----------------LEIPKIHSSXCWSLFLXANVLGPLHSLLHGEGXSR-
-----------TAQRALSSSMSSRWS----------------------------------
--------RCPQYL------------------PHSRPVWASGTARIATAVSCPVDIASRF
F-----SNRTRPNSPSIDTRLF-CCSA-LRAP----------------------------
----------------------------KISPRA-AAE------------AEHDDLCIIC
MTDPRDTTVLPCGHLCLCVDAQLLRVR-----SDRCPICRSPVDSLLXIRX---
