>gnl|CMER|CME030C unknown RING finger protein
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------EQEAFS
CPICYVDEVPEDDQLVLPECGHRFCALCLIAWAAV--RPTCPLCKGAFEAALVRRLL---
------------------------------------------------DGTPLAPGRWQL
EP--------LPLLRRAPWLVQRYGLAAHGGYAGCRGD-----------------ALTSS
ASASASAATASWFAAEAP-GATSATATAAAAI-------------GVAVNDDEDDGEEAR
EQAFWEQEAYEAELQANRFLFGNRRFGAGGYIR---------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------GERLYGR
PVRPHRRMGRKQRSVS--------------
>gnl|CMER|CME171C similar to ring finger protein
M---------------------------------------AESGQV--------------
-------------------NRSPTDA----------------------------------
--VPLTGDTR--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------APVHSPDD----------------------
--------------------------------TGFEASAHGTSELSKSLDAEAT------
------------------------------------------------------------
--------------------------------------DAAAKRPAAASSVASSSEQPFD
CSICF--EVPLEDP-VVTMCGHLFCWSCLHRWMAQ--HATCPVCKSLVDRERVIPLY---
-----------------------GRGRTREDVSDA--PKQQTKVARPNEAIPPRPAARRV
EPPPQTANGALPPLRPGAEHLSDWNVGVGAGSFMPYGTAGGI-------------SFTPF
GLFPSIFGVQFTFPPQPPTGAPSATSSTAARV----NPGDSGAYGGVPVSVQTEDATQA-
--------------MVSRMLLMLGMFVIMCLLLF--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>gnl|CMER|CMG008C unknown Zinc finger protein
M-----------------GQTLEKCAHTQHSAPKQLERSHAESSPS--------------
-------------------SRARHSNGGNSSPRNSSGRDVAGSAVSIT-----------A
ASEPIAGARR--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------SAQRSESRRTATVRTGAQQASEA-------
----------------------RRGLASPVSRKA-ERSNKTNHSVGFSAGSPEP------
------------------------PPPPPLIPRPGIDVYNLLDEDDVDN-----------
-----------------------------------------------------------S
CPICL-ESYSHENPRIVAFCGHAFHLGCIYEWMER--SPYCAICARAMQFSELASTE---
-----------------------SERVSRETRSES--DSSWTVQSDSDHSRSLENA----
-------------------------------------------------------LAELG
IDTGAIWGGSVLPPP------PSSSVSNPVKS-------------VTVTGDVSQSVPEQR
QMLRR---------SFSRQGLLTGSHGEINERANDDPLAVETVEMQDLIQWDEEHDVT--
-------APELVAPAPVTGLETYTTDSKTCAVQNQVLEAQVR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>gnl|CMER|CMI144C similar to ring finger protein
MAIIVFGIVAAVCVCLLLAAWLYACVRER----RALRRAMTRESAA--------------
-------------------NRAVGDAEDPTRMGNQRAVFVDG-----------------V
YLYSIPGNAG--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GEQRAPPGGVA----GAGVWGPT-------
----------------------RIPASLVLARLD-KTSPPAPLTSCPSCGAESP------
----------------------AAAAALATVPNESQREGKGLCGADGVY-----------
---------------------------------------------------------CQC
CSICL-DPFMKGDMSRKLSCGHLFHSHCISKWVQR--ANRCPLCQHEI----VRLEEVVQ
DLR----------------QTQGGSGSSTGTAQDA--DTGTTAAPGSARTQPP-------
------------------------------------------------------------
---------------------SDSSISGTARS----------------------TAQENR
PVPRP---------RNAQQYPLLGSLGSGFFFA---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>gnl|CMER|CMK309C unknown zinc-finger protein
MLLLVVEVVYGKGRSLLQQA---QCMHPH------------QSSEA--------------
-------------------DESSTGVQNESAPRWANTRLTKGPSEAAPEAPVSDLSPESS
TALPAVGAASERGEVCEAWRKQPATGTESVDPPARANDFRKPKGYARREPEDCPKWLDFR
AGNPEIPLDTVTGRIHLLADRQSARRVQEPQLESSAPAASTTAAVRKPTESSLGDHIARS
ILEHKQSTLNEDEDQTKRAEVEVGTPKTLAE---------ASSDSVKGSHATGEVPAAHW
KSSPSSLTCSDFARRHAKASMIFDQTTLLCMLGVPGYLSTADLAQ---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------FVAPFRSRIRRMRIVWDLSYSNSYAVLLRFLS
PDDAVLFRMEYDGRAFSEALAPERCRVLPVERVVYRCTSKQSSRLVASLALPSE------
------------------------QDGDEIVEY----DESTSSDADIGH-----------
------------------------------------------------------LEEWPT
CPVCL-DRLDLESI-LVGLCNHALHTACLARWGD----PSCPVCRFV-------------
-----------------------------SETLNP--QKTSCQVCNAQTQLWICLVCGHV
GCGRYVQHHALAHFRDTNHVFA---MELQSGRVWDYGSDSYVHRVLLNEVDGKHAVLEMR
ASTGSRAVAASGVPYHSD-GGANAPASSSQRSAPEIDEERTQLFAATIASKVDSLSQEYE
MLLLS---------QLESQRLWYEAKATELERA-------WSKRVQELEQRLER--LS--
-------KPKCSRDAATGDGAGNEFDAKLLRELNERLLRDA-AAWREQVE----------
------------------------------------------------------------
-----------------------------------------RLKRERDELAEQVNDLLQH
IEASAKLSARGNNSTSIRLEALRNRRITKP
>gnl|CMER|CMG126C similar to zinc finger protein
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------PKNGLSLGKVEA------
------------------------VAASLDVPEGYHWPHEAFRSLDVLT-----------
-----------------------------------------------------------R
CPICG-EHFRAP---VLLECGHSFCSECIRRALVY--RSECPQCRAPASAGQLRRNRLVQ
DVTTAWQQARECVLTRFSPQEHAGNTECRSSKLEASTESGLTVRERTEAACPVRAA----
-------------------------------------------------------ALTAQ
VATRGRARSAPVPPDEH---------TAAVSAVWTDRQHQNWDEAGVCCGNCEESASSAV
SMSKRTEPSHRFERSAERAGAQPPNGGLSGIAAVPQPLPVFQKTDDIYAEDWSEAAPTRT
PAALPGEAARAMEPRPRNDAESTATSGHASFTRRASCERIQQRDHTKYVECPICNRAYPP
AFIQVHVNECLDQLDAVEASGFPEAGSRALAKATNTLEDEYPMRKIPEVWYDGLTERRLR
EMIRALGMKAPPAWLRNRRGLIYLHREYVIRHNAECDVEPVTARKQRRNICREVEELAWF
QIESARRPTRPEAARSSNAT----------
>gnl|CMER|CML213C hypothetical protein, conserved
M---------------VKLPTLRRSIRDQVRRLRSLQRSESVCDANRLKALESFMDAVEA
ADVEMLFRKGDWDMVIFALNDIIWNAPLEVAARGASVLSRTNRRLLAVHGALHEQPPGRA
LTTPILVAER--------------------------------------------------
--SERLTRLAAFARTRVLTLPVLIRRLFRAVLDAPAANSEACTLLQNAVFSCLSTNCGTQ
DAQHSQISLSSRLSQLIYSLVCFAYEVDQASLDVLLDHVCAIWRSVATEPSGWNAPLPWM
LEAPSSITDAFWASSAPCLERQCDMATASVHAVLAALLSDMKLAADAQRRLLYRIHSMIQ
ELRAARDSFHVAPVSSIPYASEWFFEALTTRLVDEPQLVCLILSKLCGFEDDNPDTSAML
LVSQTQMRCLVRTITLRHLLRQAEACEAAARILLLLLSSSVVVKNLEACDFALCIFVACL
MLSDARNYPGVHQSRSVAATNGLEDRTTVQGENWRHQYGDLLLSALVSVFGDTQLRPVLL
FNMLHYRCSKAMIRFLGTGGEINIRDAFAVSVLRDEQHIAAQVQAALGQTRER-------
-----------LESLFAEEPVPEYNEAFPQIRSALHAAASAVEQGVRSACTASAIMKQGE
AGAGCVSISSVSEATRPSMASWAWTAALSVYAREYQDAAPHFADASHASDFSCSPADVYA
ALNTLHGLLAEEIVIEARKATDAAWRYERLRIQKAAELEILRKLLDEADAAKRELEQSTQ
CPVCF-ERLHAPS--ALVPCGHVLCKSCFVTLTTTLEEHLCPTCRQVFDPISALRIHLN-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
