>gnl_CMER_CMG190C_unknown_zinc_finger_protein
--------------------MRSTAKYAAISYCAIGLILGHAWLTQPNFYRATAYLYNSK
TARFSAVNAGLVSLYLVGQLVQRLLLGELRLVEAERLHLRARESLVEMFLAMTVFSRTDF
HARFLCMFAWTFFLKVFHWLSQERLGY---------------------------------
------------------------VEQQVIMLSRPRLTHARLVVLFCWLFVTDACMLWHC
LHFTSTNGPSIMAMFAFEYAILLIGLLSQIVRYVVFIIDVFVLTEGTWDDKGLWL-----
FYNELLSLFLQLAAYLAFFTYVHLFYSLPLHILRDLAVTARTF------RQRLIEFIRYR
QVVRSMHT----------------------------------------------------
---------------------------------QFPNATEQELAAGDRTCIICREEMFGG
AGAKKLVCGHIFHLRCLRSWME-----RSMSCPTCRRDIR--------------------
-----------PLRAPTTSARPTASSGAATHHDDGARRNAPGSLSTRPQRGATAPIEAPA
TAARRVDT-------------------SAVPASTQQRMRPSTASADREASDPEHLSRNEW
NAHSGRPPWTTARLTEMPPPSSSTSTPAPPPPSSPPPPPPPPPQLLAVLEYIAQTAPHAD
VQCSPLPPTSTPAQPTRTHTTPASYARPRSATIEDARRLQRQLDDLSSVMRNLIERLEHE
LEDRDAEQIERR
>sz14n09_3
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------LIFLDAAFAATAAAAPNHSSCSLPLRMPKNG----------
------------------------------------------------------------
------------------------------------------------------------
--------------LSLGKVEAVAASLDVPEGYHWPHEAFRSLDV-LTRCPICGEHF---
RAPVLLECGHSFCSECIRRALV-----YRSECPQCRAPASAGQLRRNRLVQDV-------
-----TTAWQQARECVLTRFSPQEHAGNTECRSSKLEASTESGLTVRERTEAACPVRAAA
LT-------------------------AQVATRGRARSAPVPPDEHTAAVSAVWTD----
---------------X--------------------------------------------
------------------------------------------------------------
------------
>rsz7l15_4
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------ELQSQLEKMSSEMRIVRKQADIARLGAEKSAAEAY--------TQRQFAESAQS
QVRRLSGELAQLRGQIEQQTEALRAADEAKTRSERR------------------------
----------VSRLEHELELLRKRNAATSASDVDWQHEMIEDMRR-KLYCTVCKAQE---
KQVTLLRCFHMFCRDCIQTNIAN----RNRKCPLCGEKFGTDDVKPIFFVATRECQEYGL
LHVMSVHACEHECMDVCAGVHMHVAFNEIMVRARMCGFGTSLARAPGTPAPPASH-----
---------------------------ERLTPAAASSARPLNDSND--------------
------------------------------------------------------------
------------------------------------------------------------
------------
>sz98a18_2
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------CWPTGXRHR
NDVXLAMAESGQVNRSPTDAVPLTGDT-------------RAPVHSPDDT----------
----------------------------------GFEASAH--------GTSELSKSLDA
EATDAAAK----------------------------------------------------
-------------------------------RPAAASSVASSSEQ-PFDCSICFEVPL--
EDPVVTMCGHLFCWSCLHRWMA-----QHATCPVCKSLVDRE------------------
------------------------------------------------------------
---------------------------RVIPLYGRGRTREDVSDAPKQQTKVARPN----
---------------EAIPPRPAARRVEPPPQTANGALPPX-------------------
------------------------------------------------------------
------------
>rsz9l20_5
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------YGRYYDPAKRLAGVRLVHIGRS
RAYSPRYDALGLLLIVQLVLEPIDVLMQRPAWKRKLRVLFKWALELFRKM----------
---------YASVSTSKRIAGDGVSQARPQMVTAVHTTDRFSGEETGLPGSRTTDQQRSW
SVVSPKFE----------------------------------------------------
---------------------------------PVPTARRARNES-RHRCVLCLDQC---
QGPTCTACGHVFCWICILDWVR-----QQNSCPVCRREAQLNDLRCLYSLGIHCMPK---
------------------------------------------------------------
---------------------------RSVLVGSLKTPYDSVPDGDCTHARIEWNR----
---------------SSNGTTRTRGX----------------------------------
------------------------------------------------------------
------------
>sz14d10_1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------VDEQNFERYGLDCPLCMRLL---
YEPLTTPCGHTFCRSCLARALD-----HASYCPICRTVLYVDSEKHPVTVAVAKVCEELF
PDVYRQRAIEEERECTHQFDAPAATAAVAPDGTPPVETQPASNSGNSSRSSGTTETTVPV
TSGPAVTVNQRIRWLPLFLLDEAVFPYQRIQLHIFEPRYRLMLRRVMASSRQFGFV----
---------------AVFRQPPAGLNVIRAAGGHPFMX----------------------
------------------------------------------------------------
------------
>rsz42d03_1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------RRQXVYAALNTL
HGLLAEEIVIEARKATD-------------------AAWRY--------ERLRIQKAAEL
EILRKLLD----------------------------------------------------
----------------------------------EADAAKRELEQ-STQCPVCFERLH--
APSALVPCGHVLCKSCFVTLTTT---LEEHLCPTCRQVFDPI------------------
------------------------------------------------------------
---------------------------SALRIHLNNSQPKGRHWYALSGPPHHQFP----
---------------KSNVRQKPSDPEPYTERVHGASLIFNLVQNQNLPLDHTKTPEHNS
ILCVHSIFCLLEDNGLCALHDLIGYFTASLGWAVHENRIAYASGLQELHRNLITSKRPLT
LSDLILLAHARP
>Selaginella_moellendorffii_91152_PACid_15413277
-----------------------------GIVLGLGMAALALRTWLKFGSHTRALKQVEG
TAQVEIHDLRSLVESGEKEPSSDS-SPPLVIVRGRVALPPKTSSEEVLLARN-QTDLAVF
VERTQTYLFNEWRGLFR-WGPEWRGLLG-WGSLKEQVAFSRRKIPFVLLD--SDPQYD--
----GACVHINMENVE-HPLPLVTVFHQLHPVQTS-----SSTFLQAVFGRRYPVGV---
--------------IDEEKILPLNREITAVGFLSKHPQG-LPAIKSSNQM-PFFL-----
TEFSREELIVELASATHALFWTGIVISSLALGVIGYSAFKN--------WCKWKEW-RRL
RQIQEELR--------------------------RE------------------------
----------EQVMEED-------------EEPATTQE-GSEVPD-GQLCVVCLLRR---
KRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVS--------------------
------------------------------------------------------------
---------------------------GYIRVY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
---------------------------------------------------------AVF
VERTQTYVLTEMSNFLG------------WITQKDLVKFTRQVVPFVLAE--TEAHWSFR
PSDMAVYVHINLDESQ-HPIPLVTVHHQLHPVPAS-----SYTLFQAMFGRRYPVGL---
--------------LDEEKILPLGAEITAVGVLHTAPDG-TPVVKSSKRL-PIFL-----
TEFTREQLLVELASSTKVLFWMGVAVSTVAAGVLGYSLVKN--------WTRWKQR-QQQ
RQSQNNSE--------------------------NR------------------------
----------QNSTIED-----------------EAEN-FEDIPD-GELCVVCLLRR---
RRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSVT--------------------
------------------------------------------------------------
---------------------------GIVRVY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
-------------------------------PRIAAVRGYVRTQGSFLRAPF-SSEAGVV
VKHTQMCLFTEWRGIFG-WTFDLHALL--FRSWKEQIVTSFRAVPFVLAS--TELGNS--
----TGVVHINVDEVDYQPLPLTTVFHKLIPLETT-----PYTLFQTIIGNGYPIAL---
--------------LDEEKILPIGKKITAIGLCR-AKNAESVEITSCPEI-PFFL-----
SELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRG--------WKRIKLR-REA
RQAQQMFE--------------------------DA------------------------
------------EDAIR-------------EDNSSDDD-DDDVGD-GQLCVVCLRKR---
RKAAFIPCGHLVCCCKCALRMER---EVEPLCPMCRQDIR--------------------
------------------------------------------------------------
---------------------------YMIRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
------------------------------------------------------------
-------------------------------PRIAAVRGYVRAHDKFFRAPF-SGEAGVV
TKHTQMCLFTEWRGIFG-WTFDLHALL--FRSWKEQIVTSFRSVPFVLVS--TELGNP--
----TGVVHINVDKAD-QPLPLTTVFHKLIPLETT-----PYTLFQTIIGNGYPIAL---
--------------LDEEKILPIGKKITAIGLCQ-AKDAESVEITSCPEI-PFFL-----
SELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRG--------WTRIKLR-REA
RHARQMFE--------------------------EA------------------------
------------EDAIH-------------RDDSSD---DDEIGD-GQLCVVCLRKR---
RRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDIR--------------------
------------------------------------------------------------
---------------------------YMMRVY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
--------------------------------------------------PW-SGEHGVV
TKHTQMCLFTEWRGIFG-WTFDLHALL--FRSWKEQIVTYFRSVPFVLAS--SEIGNP--
----IGMVYIDVEKAA-QPLPLTTVFHKLIPIETT-----PYTLFQTIIGNGYPIAL---
--------------LDEEKILPIGKELTAIGLCR-ANDEGSVEISSCPEL-PFFL-----
SELTKDEMQAQLASRARILFWGSVVLGTLSVCLVGHAIYRG--------WKRIKLR-REA
RQAQQLFE--------------------------EG------------------------
------------EDAIQ-------------EDDSS----DEEVGD-GQLCVVCLRKR---
RKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDIR--------------------
------------------------------------------------------------
---------------------------YMMRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
----QLCLFNEWRGIFG-WTFDLHALF--FKSIKEQIITSFRWVPFVLVD--PE--NM--
----TGMVHVKLDRAM-QPLPLTTVYHKLTPVDST-----PYTLFQTIIGNGYPIAL---
--------------LDEEKILPVGKEITAIGYIR-PHKA-SVEISSCSEI-PFFL-----
SDLTKDEMEAELSSRAKTLFWASVVLGTMSVCLLGFATYRS--------WKKIKER-REA
RQAQEVFR--------------------------QT------------------------
------------TDEVT-------------DDQSSDEE-AGEMGD-GQLCVICLRKR---
RKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDIR--------------------
------------------------------------------------------------
---------------------------YMIRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
------------------------ALF--FKSLKEQTITSFRWVPFALVDPASASDKS--
----TEMIHVKLDGAVQQSLPLTTVYHKLIPVEQN-----SYTLFQTIVGNGYPIAL---
--------------LDEEKILPIGKEITAIGLCR-VNNQ-NVEITSCPEI-PFFL-----
SDLTKGEIEAELDSRARTLFWVTFALGTMSVGLLGHAIYRF--------WEKVKQH-REA
RQAQQRFH--------------------------QA------------------------
----------DDEDDTG-------------ENGSDDDF-PGEMGD-GQLCVICLRKR---
RKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDIQ--------------------
------------------------------------------------------------
---------------------------YMLRVY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
---------------------------------------------------------AVI
LQRTQTCIYNEWKGFFG-WTSDLRSIF--GRSLKEQETTFLRTVPFTLVE--GGQWPQ--
----SDYVIVNMDGSS-HPLPLTMVYHQLQPIVAS-----RYTFIQALFGHEYPVGV---
--------------LHEEKILPLGKCISAVGICN-SKDG-IPEIKSCKEL-PYFL-----
ADMTKDEMVADLAFKAKILLWSGIVLGSLSIGVLGFAVMRN--------WNKWKAW-RQR
RS-QQPIH--------------------------T-------------------------
-----------TSDEDV-------------SQIDDNED-AGDVPE-GQLCVICLMRR---
RRAAFIPCGHLACCHTCAVSVES---EVSPKCPLCRQAVR--------------------
------------------------------------------------------------
---------------------------NSIRIF---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
---------------------------------------------------------GVI
LQRTQTCIYNEWRGFFG-WTSDIRTLF--ARSWKEKESTSLRTVPFILVE--GGRWPQ--
----SDYVIVNMDGSR-HPLPLTTVYHQLQPVNAS-----PYTFLQALFGHDYPVGL---
--------------LDEEKLLPLGKEITAVGICS-LKNG-IPEIKSCKDL-PYFL-----
SEMSKDQMVVDLVFKSKVLFWSGVILGSVSIGVLGYAVVRN--------WNRWKEW-RQQ
RGVRPPSQ--------------------------A-------------------------
-----------VTDDTD-------------TQI-AEDD-AGDVPD-GELCVICLMRR---
KRSAFVPCGHLVCCQRCALSVER---ELSPKCPVCRQIIR--------------------
------------------------------------------------------------
---------------------------SSVRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
------CIYNEWKGFFG-WTSDIRAIF--GRSWREQESTLSRSVPFVLVE--AGRWPQ--
----SDYVIVNLDGSR-HPLPLTTVYHQLQPIDAS-----PYTFLQAFFGYEYPVGL---
--------------LDEEKILPLGKEINAVGLCG-SKNG-ILEITSCKDL-PFFL-----
SDLSKEQMVVDLAFKTKVLFWSGVVLGSFSICILGYAAVRN--------WNRWKAW-RQQ
RQFQQQSN--------------------------S-------------------------
-----------VSDADV-------------SQIDVEEE-TVDVPD-GQLCVICLMRR---
RRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAVR--------------------
------------------------------------------------------------
---------------------------NSIRIFE--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
------CIYNEWKGFFG-WTSDIRAIF--GRSWREQESTSLRMVPFVLVE--GGRWPQ--
----SDYVIVNIDGSR-HALPLTTVYHQLQPIDAS-----PYTFLQALFGHEYPVGL---
--------------LDEEKILPLGKEINAVGICS-SRNG-VLEIKSCKDL-PYFL-----
SDMTKDQMVVDLAFKTKVLLWSGVVLGSLSIGILGYAAVRN--------WNRWKEW-RQH
RQSQQQNH--------------------------A-------------------------
-----------ASTDDD-------------PQIDADEE-AGDVPD-GQLCVICLMRR---
RRSAFIPCGHLVCCQLCAISVER---EVSPKCPLCRQAVR--------------------
------------------------------------------------------------
---------------------------NSMRIF---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------RTVPFVLID--GSQWPA--
----VDYVVVNMDGSK-HHLPLTTVYHQLQPINAS-----PYTFLQALFGHEYPVGL---
--------------LDEEKILPIGKDVSAVGLCF-LKNG-ILEIKSCKDL-PYFL-----
TEMTKDQMVIDLAFRTKILFWSSIFLGSASIGILGFAFVRN--------WNRWKEW-RQR
RRDEQQSH--------------------------A-------------------------
-----------AVDEAT-------------AHI-AEDE-LGDAPD-GQLCVICLMRR---
RRSAFVPCGHLVCCQRCALSVER---EVSPKCPVCRQTIT--------------------
------------------------------------------------------------
---------------------------NSVRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
------------------------------------------------------------
---------------------------------------------------------GVV
LQRTQTCIYNEWKGLFG-WTSDLRALF--LRSWRQQESTSLRKIPFVLID--VGRPSN--
----PEYVVVNMDGSS-HPLPLTTVYHRLQPVNPP-----PYTFLQALFGHEYPVGL---
--------------LDEEKILPLGKDVSAVGLCS-LRNG-IAEIKACNDL-PYYL-----
SDLSKDQMIVDLSFKTKLLFWSGILLGSMSVGIIGYAVVRN--------WNKWKQW-KQQ
RQLQQRRQ--------------------------Q-------------------------
-----------PIE----------------PVPPTDDE-IEDVPD-GQLCVICLMRR---
RRSVFIPCGHLVCCQGCAISVES---EVAPKCPVCRQEVR--------------------
------------------------------------------------------------
---------------------------DSVRIFE--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
---------------------------------------------------------GVI
LQRTQTCIYNEWKGLFG-WTSDLRAIF--ARSWRQQESTSLRKVPFLLTD--VGRRPN--
----AEYVVVNMDGSR-HPLPLTTVYHKLQPITAS-----PYTFLQALFGHEYPVGL---
--------------LDEEKILPLGKDITAVGLCS-LKNG-IAEIKSCKYL-PYFR-----
SDLSKDQMIMDLSIKTKILFWGGIALGSMSVGVLGYAVVRN--------WNKWKQW-KQQ
RQLQQQRQ--------------------------A-------------------------
-----------VSD----------------VEPQMDDE-IEDAPD-GQLCVICLMRR---
RRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEIR--------------------
------------------------------------------------------------
---------------------------DSVRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------NAS-----PYTFLQALFGHEYPVGL---
--------------LNEEKILPLGKDISAVGICS-FKNG-IPEIMSCKDL-PYFL-----
SDLTKDQMLLDLAFRTKILFWSGIILGSLSISILGYAALRN--------WNRWKER-RQQ
RQAHQPSH--------------------------A-------------------------
-----------ASIDAN-------------SELTGEEE-IGDIPD-GQLCVICLMRR---
RVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEIR--------------------
------------------------------------------------------------
---------------------------GSMRVF---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
-------------------------IF--SRSWRERESKVFRTVPFILAE--GGRRPI--
----SEFVAVDMDGSR-HPLPLTTVYHHLHPVNPS-----PYTFLEALFGHRYPVGL---
--------------LDEEKILPLGKEISAVGLCS-VKDG-VLEIKSCKDF-PYFL-----
SEMSKDQMVVDLTSRTKVLFWSGIFLGSVSIGVLAYAVSRN--------WNRWKVW-RQQ
RELQRSIR--------------------------A-------------------------
-----------SNAEAQI------------QEEEEEED-AGDVPD-GQLCVICLMRR---
RRSAFIPCGHLVCCQLCSISIER---DVAPKCPVCRQQIR--------------------
------------------------------------------------------------
---------------------------TSVRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Citrus_clementina_0.9_012450m_PACid_19274708
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VNMDGSR-QPLPLTTAYQRLELANVS-----PFTFLQAMFGLKCPIGV---
--------------LAEEKILPLGKDISAVGICS-FKNG-IPEIKSCKDL-PYFL-----
SEKTKDLMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRN--------WNRWKD--RQQ
RMSRQLTE--------------------------A-------------------------
-----------PSDDAD-------------SQIGSDEDVAGDIPD-GQLCVVCLTRR---
RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVR--------------------
------------------------------------------------------------
---------------------------SSMRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VNMDGSR-QPLPLTTAYQRLELANVS-----PFTFLQAMFGLKCPIGV---
--------------LAEEKILPLGKDISAVGICN-FKNG-IPEIKSCKDL-PYFL-----
SEKTKDQMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRN--------WNRWKD--RQQ
RMSRQLTE--------------------------T-------------------------
-----------PSDDAD-------------SQIGSDEEVAGDIPD-GQLCVVCLTRR---
RISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVR--------------------
------------------------------------------------------------
---------------------------SSMRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
---------------------------------------------------------GVI
LQRIQTCIYNEWRGLFR-WTADLGSMLMPRRITKENASSSMNMVPFILVE--EGKWPP--
----SDHVVVNMEGST-HPLPLTTVYQHLQPVKAS-----SYTVFQALVGLEYPVGL---
--------------LYEEKILPLGKDITAVGICN-LKNG-IPEIKSCEDL-PYFL-----
SILTKDQMIADLSFKSKVLLWSGLILGTVAIGVLGYSISRN--------WSKWKEW-KAR
RAQQQQNA--------------------------SR------------------------
----------IEN-----------------LDETEEEE-SGDVPD-GELCVVCLMRR---
RRSAFVPCGHLVCCHRCAFSVER---EVSPKCPVCRQPIR--------------------
------------------------------------------------------------
---------------------------NSVRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------PYTLIQAIVGHAYPVGL---
--------------LDEEKILPLGKEITAVGHCT-LQDG-NPQIISCKKV-PYFL-----
SDMTKDQMIVDLVSKKKILFWAGIVLGSVSLGVLGYALTRN--------WQRLKEW-RQR
RQIQQSRE--------------------------EE------------------------
----------IANLDATP------------EDTRADEE-TEDIPE-GQLCVICLMRR---
KRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDIR--------------------
------------------------------------------------------------
---------------------------TSVRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------AT-----PYTFLQAVFGHEYPVGV---
--------------LDEEKILPLGKNISAVGICS-FENG-VPVIKSCSDF-PHFL-----
CEMTKDQMILDLVFKTKFLFWSSIVLGSLTVGILGYSAARN--------WNRWKQW-RQH
RQLQNSRN--------------------------DSPTSQLDSSNDIPIYGDFASDDEAA
TVPDDELSSHVPDDELS-------------SHVPDDEL-SSHVPD-GQLCVICLMRR---
KRSAFIPCGHLVCCERCAVSVER---ESSPKCPICRQQIR--------------------
------------------------------------------------------------
---------------------------SSVRIY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>SPL2_Arabidopsis_thaliana_AT1G54150.1_PACid_19654958
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VNMDGSR-QPLPLTTVYNRLQPINSS--------FLQAFLYPDYPVGL---
--------------LDIEKILPPGKDITAVGIYS-FNNG-VPEIKSCQDL-PYFL-----
SEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRT--------WNKWKQW-NHQ
RELPQRPN--------------------------D-------------------------
-----------SVVDDE------------------PED-ADEIPD-GELCVICVSRR---
RVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIR--------------------
------------------------------------------------------------
---------------------------GSMRVY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRI-VVVRGVVKPKISGDEGYKNNNVLISPE-TGDKALI
IQRTQTYVYSGWKRLFQ-STGHRFML---ERSLRKHGADFTRTVPFVIVG--KDQQSN--
----SSFVAVNMDGSR-QPLPLTTVYNRLQPINSS--------FLQAFLYPDYPVGL---
--------------LDIEKILPPGKDITAVGIYS-FNNG-VPEIKSCQDL-PYFL-----
SEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRT--------WNKWKQW-NHQ
RELPQRPN--------------------------D-------------------------
-----------SVVDDE------------------PED-ADEIPD-GELCVICVSRR---
RVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIR--------------------
------------------------------------------------------------
---------------------------GSMRVY--YS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VNMDGSR-QPLPLTTVYNRLQPINSS--------FLQAFLFPDYPVGL---
--------------LDIEKILPPGKDITAVGICS-FNNG-VPEIKSCQDL-PYFL-----
SEMTKDKMIEELMDQTSFIFFGSVILGIVSVGILSYAAVRT--------WNKWKQW-NHQ
RDLPQRPN--------------------------E-------------------------
-----------PVVDDE------------------PED-ADEIPD-GELCVICVTRR---
RVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSIR--------------------
------------------------------------------------------------
---------------------------GSMRVY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------VIVDLDSST-HLLPLTTVYHKLQDLHVMSDEILPYAFLEAFF---LPVGH---
---------------MQKKILPLGKEINAIGLCS-LQDG-NLHIKATQEL-PYFL-----
SEMTKGEMVKHLAYKTTILFWGGCIIGIVSLGVLGYTSFRI--------WEWWKVR-RQH
FSNAEVDD----------------------------------------------------
-----------------------------------VYIGNDEIPS-EQLCTICTMRR---
KKYACVPCGHLVCCHKCARSIQH---DSTARCPECRH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------LGHAYPFGLCLQ
EKFLPLNFAWYHPGLLEEKILPLGKEISVVGIGT-SEYG-NVEIKPCDEL-PYFL-----
SDLTKDQMIGELAQKTNYLLLSAIFFGSLSLAVIAYAVMIG--------CQRFEEKTQQR
RQVQQQMT--------------------------QV------------------------
----------QQSLRND-----------------VVEEGMEALPE-GLSCVV--------
--SVFVPCGHLVCCQTCAPLVAR-----DRRCPICRQYIQ--------------------
------------------------------------------------------------
---------------------------KYIITY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Physcomitrella_patens_Pp1s12_190V6.2_PACid_18048531
--------------------------------------MLSWGGITLCLSGAALYCLSRN
TGRDALNLRSIERVNQLKDLAILL-ESACKVVPLVVTVAGRVGSETPIACEH-SSLRGVI
LEETAEQHFLKHNDTGS-WIQDSALML-----------SISKEVPWYLED----------
---GTGRVYIVGARNA-AGMELTVASEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRVERVLPTGTNLTVVGEAVQDDRG-LIRIQKPNKG-PFYV-----
TPKSLDQLVANLGRWSRWYKYMSLGFTIVGIYFITSHAIKHF-------MERRRREALHR
RVM-EAAA--------------------------LR------------------------
----------QASQREGGDGDMGDVTSHPLDDSVDTSQ-KKDRGT-PDLCVICLEQD---
YNAVFLPCGHMCCCTSCSAQLT--------SCPLCRRHID--------------------
------------------------------------------------------------
---------------------------KFVKTY--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Physcomitrella_patens_Pp1s175_124V6.2_PACid_18055474
--------------------------------------MLSWGGITLCFSGAALYCLSRN
TGRDALHLMSVERVNQLEDLAKLL-ESACTVVPWVVTVAGRVGAEAPIASEH-SSLRGVI
LEKSAEQHFLKHNDTGS-WIQHSALML-----------SISKEVPWYLED----------
---GTSRVFIIGARNA-AGMDLTVASESFEEYGGS-----LVRGTLDYLQGLKMLGV---
--------------KRVERVLPTGTNLTVVGEAVQDDRG-LIRIQKPDKG-PFYV-----
TPQSQDQLIENLGRWSRWCQYMSFGLTLVGIYFITSRAIKHM-------LERWRREALLT
RVM-EAAA--------------------------LR------------------------
----------KALQQEGVDEESDGVTAFPHDDNAHTAQ-KKDGGM-PSLCVICLEQD---
YNAVLVPCGHMCCCTSCSSQLS--------LCPLCRRHID--------------------
------------------------------------------------------------
---------------------------QVVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Selaginella_moellendorffii_231449_PACid_15416766
--------------------------------------MLPWGGITMCLSGVALYFLSRN
SGRDAATLKAVRRVDQLKDLAHLL-DSACKAVPLVVTVAGRVGSETPIGCDH-SSLRCVI
LEETAEQHFLKHNDTGS-WIQDSALML-----------SNNKEVPWFLED----------
---ASGRVFIVGARGA-AGLELTIASEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRVERVLPTGTALTVVGEAIKDDQG-TLRIQRPHKG-PFYV-----
TPKSIDQLIANLGKWSRWYKYMSLGFTLFGVFLVASHTIRYV-------MEKRRRAALNR
RVM-EAAA--------------------------RR------------------------
----------RERKEHEGKAQVGE------FAKVETAT-KRDGRL-PDLCVICLEQE---
YNAVFVPCGHMCCCISCSAQLQ--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------QIVKTY--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Medicago_truncatula_Medtr1g111550.1_PACid_17439105
--------------------------------------MVPWRGVGCCLSAAALYLLGRT
SGRDVDILKSVNRVNQLRELAQLL-DEE--IFPLVVAISGRVGSETPISCEF-SGLRGVI
IEETAEQHFLKHSDAGS-WIQDSALMQ-----------SRSNEVPWYLDD----------
---GTGRVRVVGAQGA-TGFVLPVGSEAFEESGRL-----PVRGTSDYVQGLKMLGV---
--------------KRIERVLPVGTSLTVVGEAAKDDVG-TIRIQRPSKG-PFYV-----
SPKTIDELIANIGRWARWYKYASAGLTVLSVYMIANHAVRYI-------LERRRRNELEK
RVL-AAAA--------------------------KI------------------------
----------SGQDNGGE--M---------DDSLSDGA-KRERAM-PNLCVICLEQE---
YNSVFVPCGHMCCCTACSSHLT--------SCPLCRRQIE--------------------
------------------------------------------------------------
---------------------------KAVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Glycine_max_Glyma10g02920.1_PACid_16278382
--------------------------------------MIPWGGLSCCLSAAALYLLGRS
SGRDAEILKSVTRVNQLKELAQLL-DAE--ILPLIVTISGRVSSETPINCEF-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTDRVHVVGARGA-SGFALPVGIEAFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPVGTSLTVVGEAAKDDVG-AIRIQRPHKG-PFYV-----
SPKTIDQLIANLGKWARWYKYASVGLTVFGAYLIAKHAIRYI-------LERRRRSELQR
RVL-AAAA--------------------------KK------------------------
----------SGQNND--VEK---------ADSLSDGA-KKDRLM-PDLCVICLEQE---
YNAVFVPCGHMCCCTACSSHLT--------NCPLCRRQIE--------------------
------------------------------------------------------------
---------------------------KVVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Prunus_persica_ppa008230m_PACid_17644506
--------------------------------------MLPWGGLSCCLSAAALYLLGRS
SGRDADILKSATRINQLKELAKLL-DSEC-ILPLVVAISGRVSSETPITCEF-TGLRGVV
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTGRVHVVGARGA-TGFVLPVASEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTSLSVVGEAVKDDIG-TIRIQRPHKG-PFYV-----
SPKTIDQLIANLGKWARWYKYASLGLTVFGVYLVAKHSVQYI-------LERRRRWELQR
RVL-AAAA--------------------------KR------------------------
----------SGEDNEGSNEK---------DDNVLDGS-K--RLM-PDLCVICLEHE---
YNAVFVPCGHMCCCTTCSLHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QAVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
--------------------------------------MLPWGGISCCLSAAALYLLGRS
SGRDAELLKSVTRVNQLKELAQLL-EAE-HLLPLVVAISGRVSSDTPINCEF-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTGRAFVLGARNA-TNFILPVVSEVFEESGRS-----LMRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTSLTVVGEAAKDDIG-TIRIQRPHKG-PFYV-----
SPKTIDQLISNLGKWARWYKYASMGLSIFGLYLVTKHVILYL-------MERRRRWELQK
RVL-AAAA--------------------------KR------------------------
----------SSQENEGEIEK---------ASNGTDGT-KRDRSM-PDLCVICLERD---
YNAVFVPCGHMCCCVACCSHLT--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------LVVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
--------------------------------------MIPWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLKELAHLL-DSGSKVLPFIVTVCGRVGSETPISCEY-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTGRAFVVGARGA-TGFVLTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERLLPTGTSLTVVGEAVKDDIG-TVRIQRPHKG-PFYV-----
SPKTIDELIENLGKWARWYKYASFGLTIFGTFLIAKRAIHYI-------LQRKRRWELHR
RVL-AAAAV-------------------------KR------------------------
----------SEQDNEGTNGQ---------AENGSDGT-QRDRVM-PDLCVICLEQE---
YNAVFVPCGHMCCCIICSWHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QVVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Citrus_clementina_0.9_003846m_PACid_19263951
--------------------------------------MIPWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLKELAHLL-DSGSKVLPFIVTVCGRVGSETPISCEY-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTGRAFVVGARGA-TGFVLTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERLLPTGTSLTVVGEAVKDDIG-TVRIQRPHKG-PFYV-----
SPKTIDELIENLGKWARWYKYASFGLTIFGTFLIAKRAIHYI-------LQRKRRWELHR
RVL-AAAAV-------------------------KR------------------------
----------SEQDNEGTNGQ---------AENGSDGT-QRDRVM-PDLCVICLEQE---
YNAVFVPCGHMCCCIICSSHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QVVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
--------------------------------------MISWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLEELAHLL-DGGSKVLPSIVSVSGRVGSETPISCEY-SGLRGVI
VEETTERHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTGCVFVVGARGA-TGFALTVGSEVFEESGRS-----LVHGTLDYLQGLKMLGV---
--------------KRIGRLLPTGTSLTVVGEAVKDDIG-TVRIQRPHKG-PFYV-----
SPKTIDELLENLGKWARWYKYASFGLTIFGAFLIAKRVIRCI-------LQRKRRWELRR
RVL-AAAAV-------------------------QR------------------------
----------SEQDNEGTNGQ---------AENGSDST-QRDRVM-PDLCVICLEQE---
-------CGHLCCCLICSSRLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QVVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Citrus_clementina_0.9_014777m_PACid_19265048
--------------------------------------MISWGGISCCLSGAALYLLGRS
SGRDAELLKTVTRVNQLEELAHLL-DGGSKVLPSIVSVSGRVGSETPISCEY-SGLRGVI
VEETTERHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTGCVFVVGARGA-TGFALTVGSEVFEESGRS-----LVHGTLDYLQGLKMLGV---
--------------KRIGRLLPTGTSLTVVGEAVKDDIG-TVRIQRPHKG-PFYV-----
SPKTIDELLENLGKWARWYKYASFGLTIFGAFLIAKRVIRCI-------LQRKRRWELRR
RVL-AAAAV-------------------------QR------------------------
----------SEQDNEGTNGQ---------AENGSDST-QRDRVM-PDLCVICLEQE---
YNAVFFPCGHLCCCLICSSRLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QVVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
--------------------------------------MLPWGGISCCLSAAALYLLGRS
SGRDAEVLKSVTRVNQLKELAKLL-DIESNISPSVVSISGRVGSETPINCEY-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTDRVYVVGARGA-SGFVLTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTSLTVVGEAVKDDIG-TVRVQRPHKG-PFYV-----
SPRTIDELIGNLGKWARWYRYASVSLTVFGAFLIAKHAIQYI-------MERRRRWELQS
RVLAAAAA--------------------------KR------------------------
----------QGQDSEGSNGK---------AENGSDNS-KRERPV-PDLCVICLEQE---
YNAVFLPCGHMCCCTTCSSHLT--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------QVVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Ricinus_communis_29703.m001546_PACid_16806242
------------------------------------------------------------
-------LKSVTRVNQLNELAKLL-DIESKVLPLVVAISGRVGSETPINCEY-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTDRTFVVGARGA-SGFALTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTSLSVIGEAVKDDIG-TVRIQRPHKG-PFYV-----
SPKTIDELIGNLGKWARWYRYASVGLTVFGVFLIAKHAIQYI-------MERRRRWELQS
RVL-AAAA--------------------------KR------------------------
----------QGQDSDGSNGK---------AENGSDSS-KRERPI-PDLCVICLEQE---
YNAVFLPCGHMCCCTACSSHLT--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------QI-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Vitis_vinifera_GSVIVT01011070001_PACid_17823049
--------------------------------------MIPWGGISCCLSAAALYLLGRS
SGRDAEALKSVTRVQQLKDLVQLL-DTACKVLPLVVTVSGRVGSDTPIKCEY-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---DTGRAYIVGARGA-TGLVLTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTPLTVVGEAIKDDVG-TIRIQRPHKG-PFYV-----
SPKSIDHLVANLGKWARWYRYASLGFTVFGVYLIAKSAIQYV-------MERKRCWELRK
RVL-AAAS--------------------------KK------------------------
----------SGQDSEDPDEK---------DENGSDNT-KRDRLM-PDLCVICLEQE---
YNAVFVPCGHMCCCTMCSSQLT--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------QVVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
--------------------------------------MIPWGGLSCCLSAAALYVLGRS
SGRDAEALKCVFRVNQLKELAQLL-DTECKVLPLVVTLCGRVGSDTPINCEY-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTGRAYVLGARGA-SGFELNIASEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERLLPVGSSLTVVGEAVKDDIG-TVRIQRPHKG-PFYV-----
SPKTIDQLISNLGKWARWYRYASYGFTVFGICLIAKRAIQYI-------MERKRRWELQR
RVL-AAVA--------------------------RR------------------------
----------SEQDTEGTDDK---------TKNAPDSA-KRDRSM-PDLCVICLEQE---
YNSVFVPCGHMCSCTTCSLQLT--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------QAVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
--------------------------------------MLPWGGITCCMSAAALYLLGKS
SGRDADILKSVTRLNQLKDLAQML-DTACKVLPFVVTVSGRVGSDTPINCEH-SGLRGVI
VEEAAEQHFMKQNDSGS-WIQDSAQML-----------AMTKEVPWYLDD----------
---GTGRVHVLGARGA-TGLVLTVASETFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTSLTVVGEAVKDDVG-TIWIQRPHKG-PFYV-----
SPKSIDQLIANLGIWARLYKYASLGFTAFGVYLIAKHAIRYI-------LERRRLLDFQR
RVR-AAAA--------------------------QR------------------------
----------LEQDNDGTDGK---------AEDGPDVV-NKDRIM-PDICVICLEQE---
YNAVFVPCGHLCCCTTCSSHLS--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QVVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
--------------------------------------MIPVGGITCCLSAAALYLLGRS
SGRDADLLKSVTRVNQLKDLAQLL-EAASKVLPLVVTVSGRVGSETPINCEY-SGLRGVI
VEQTAEQHFLKHNDAGS-WIQDSALML-----------SMCKEVPWYLDD----------
---GTSRVHVVGARGA-TGLVLTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGSPLTVVGEAVKDDIG-SIRIQRPHKG-PFYV-----
TDKTIDQLIANLGKWSRLYKYASMGLTAFGVYLLAKHAFQYI-------MDRRRLWETRK
RVL-DAAA--------------------------KK------------------------
----------AGQNEGALNGE---------AEIGSDSS-NKERPI-PELCVICLEQE---
YNSVFVQCGHMCCCMACSSHLT--------NCPL--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Arabidopsis_lyrata_474968_PACid_16053684
--------------------------------------MIPWGGVTCCLSAAALYLLGRS
SGRDAEVLKTVTRVNQLKELAQLL-ELDSKILPFIVAVSGRVGSETPIKCEH-SGIRGVI
VEETAEQHFLKHNETGS-WVQDSALML-----------SMSKEVPWFLDD----------
---GTSRVHVMGARGA-TGFALTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGIPLTIVGEAVKDDIG-EFRIQKPDRG-PFYV-----
SPKSLDQLISNLGKWSRWYKYASMGFTVFGVFLITKHVIDSV-------LERRRRRQLQK
RVL-DAAA--------------------------KR------------------------
----------AELESEGSNGA---------RESIADST-KKEDAV-PDLCVICLEQE---
YNAVFVPCGHMCCCTACSSHLT--------SCPLCRRRID--------------------
------------------------------------------------------------
---------------------------LAVKTY--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>SP1
--------------------------------------MIPWGGVTCCLSAAALYLLGRS
SGRDAEVLETVTRVNQLKELAQLL-ELDSKILPFIVAVSGRVGSETPIKCEH-SGIRGVI
VEETAEQHFLKHNETGS-WVQDSALML-----------SMSKEVPWFLDD----------
---GTSRVHVMGARGA-TGFALTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGIPLTIVGEAVKDDIG-EFRIQKPDRG-PFYV-----
SSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSV-------LERRRRRQLQK
RVL-DAAA--------------------------KR------------------------
----------AELESEGSNGT---------RESISDST-KKEDAV-PDLCVICLEQE---
YNAVFVPCGHMCCCTACSSHLT--------SCPLCRRRID--------------------
------------------------------------------------------------
---------------------------LAVKTY--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Populus_trichocarpa_POPTR_0014s13410.1_PACid_18222628
--------------------------------------MIPWGGISCCLSGAALYLLGRS
SGR---YLPSLIPLFFLIISSKLL-DIESKVLPLVVAISGRVGAESPISCEF-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTDRVYVVGARGA-SGFVLTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTSLTVVGEAVKDDIG-TVRIQRPHKG-PFYV-----
SPKSIDELIGNLGKWARWYKYASLGLTVFGAFLITKHVIRYI-------MERRRRWELQS
RYV-SLVE--------------------------GI------------------------
----------HDKMFQG--------------KGHANGA-KRERPI-PDLCVICLEQE---
YNAVFLPCGHMCCCITCCSQLS--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------QVVKTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGSDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAISGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-WIQDSAVML-----------SVSKEVPWYLDD----------
---GTGRVYVVGARSA-AGLILTVASEVFEESGRT-----LVRGTLDYLQGLKMLGV---
--------------KRTERVLPTGTSLTVVGEAIKDDVG-TIRIQRPHKG-PFYA-----
SSKSIDQLIVNLGKWAKLYRIASMGFATFGVFLLAKRALQHF-------LERRRRHELQK
RVL-NAAA--------------------------QR------------------------
----------QAREAEGSKGT----------SDAEPNS-KKDQLV-LDICVICLEQE---
YNAVFVPCGHMCCCVACSSHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QAVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAVSGRVSSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-WIQDSAVML-----------SVSKEVPWYLDD----------
---GTGRVYVVGARSA-AGLILTVASEVFEESGRT-----LVRGTLDYLQGLKMLGV---
--------------KRTERVLPTGTSLTVVGEAIRDDVG-TIRIQRPHKG-PFYV-----
SPKSIDQLIMNLGKWAKLYRLASMGFATFGVFLLAKRAIQHF-------LERKRRHELQK
RVL-NAAA--------------------------QR------------------------
----------QAREAEGSNGS----------SDTEPNS-KKDQLV-LDICVICLEQE---
YNAVFVPCGHMCCCMACSSHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QAVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAVSGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-WIQDSAVML-----------SVSKEVPWYLDD----------
---GTGRVYMVGARSA-AGLILTVASEVFEESGRT-----LVRGTLDYLQGLKMLGV---
--------------KRTERVLPTGISLTVVGEAIKDDVG-TIRIQRPHKG-PFYV-----
SPKSIDQLIMNLGKWAKLYRLASMGFATFGAFLLAKRAIQHF-------LERKRRHELQK
RVL-NAAA--------------------------QR------------------------
----------QAREAEGSIGS----------SDTEPNS-KKDQLV-LDICVICLEQE---
YNAVFVPCGHMCCCMACSSHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QAVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Setaria_italica_Si030396m_PACid_19714000
--------------------------------------MIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSMKDLAAIL-DTASKVLPLVVAVSGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-WIQDSAVML-----------SVSKEVPWYLDD----------
---GTGRVYVVGARAA-AGLILTVASEVFEESGRT-----LVRGTLDYLQGLKMLGV---
--------------KRTERVLPTGTSLTVVGEAIKDDVG-TIRIQRPHKG-PFYV-----
SPKSIDQLILNLGKWAKLYRLASMGFATFSVFLLAKRAIQHF-------LERKRRHELQK
RVL-NAAA--------------------------QR------------------------
----------QAREAEGGKGT----------SNTEPNS-KKDQLV-LDICVICLEQE---
YNAVFVPCGHMCCCMACSSHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QAVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
--------------------------------------LIPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVARAGSTKDLAAIL-DTASKVLPLVVAVSGRVGSDTPLICQQ-SGMRGVI
VEETAEQHFLKHNDAGS-WIQDSAVML-----------SVSKEVPWYLDD----------
---GTGRVFVVGARGA-AGLVLTVASEVFEESGRT-----LVRGTLDYLQGLKMLGV---
--------------KRTERVLPTGTSLTVVGEAIKDDVG-TIRIQRPHKG-PFYV-----
SPKSIDQLIMNLGKWAKLYQLASMGFAAFGVFLLAKRALQHF-------LERKRRHELQK
RVH-AAAA--------------------------QR------------------------
----------QAREAEGGNGT----------SDVDSNN-KKDQLV-LDICVICLEQE---
YNAVFVPCGHMCCCMNCSSHLT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QAVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
--------------------------------------MVPWGGVGCCLSAAALYLLGRS
SGRDAEVLRSVTRTGSLKDLAAIL-DTASKVLPLVVAVSGRVSSDTPLICQQ-SGMRGVI
VEEMAEQHFLKHNDAGS-WIQDSAVML-----------SVSKEVPWYLDD----------
---GTGRVYVVGARAA-AGLVLTIASEVFEESGRT-----LVRGTLDYLQGLKMLGV---
--------------KRTERVLPTGTSLTVVGEAIKDDVG-TIRIQRPHKG-PFYA-----
SPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALQHF-------LQKKRQHELNK
RVR-AAAA--------------------------QR------------------------
----------QAREAEGADGT----------SNGDPNS-KKDQLV-LEICVICLEQE---
YNAVFVPCGHMCCCMNCSSHVT--------NCPLCRRRID--------------------
------------------------------------------------------------
---------------------------QAVRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
--------------------------------------MIPWGGITCCMSAAALYLLGRS
SGRDADILRKVTRVNQLKELAQLL-DIESKIMPLIVAISGRVGSETPISCEY-SGLRGVI
VEETAEQHFLKHNDAGS-WIQDSALML-----------SMSKEVPWYLDD----------
---GTARVFVVGARGA-TGFVLTVGSEVFEESGRS-----LVRGTLDYLQGLKMLGV---
--------------KRIERVLPTGTSLTVVGEMTLEQ----FRYEDRTNG-LFTCLQING
SPD------FQLGKWARWYKYASMGLTFLGVFLIAKRSIEYV-------LERRRRRELQK
RVL-AAAA--------------------------KR------------------------
----------SGQDNEGSNII---------PENGLDGA-KREHLM-PDLCVICLEQE---
YNAAFVPCGHMCCCMTCSSHLT--------NCPLCRRRIE--------------------
------------------------------------------------------------
---------------------------QVLRTF--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>SPL1_NP_564745
--------------------------------------MIHLAGFTCCLGGVALYLLTRS
TGRD---IKSITRVYQLKDLEQLV-EVESKVVPLIIAVSGDVGSETPIKCEH-SYVLGVF
LKRTAEQQVLRRNWRFS-WVRNSTLMQ-----------PMTKEVPWYLDD----------
---GTGRVNVDVSQGE-LGLALTVGSDVFEKAEPVS----LVQGALGYLKGFKILGV---
--------------RHVERVVPIGTPLTVVGEAVRDGMG-NVRIQKPEQG-PFYV-----
TYIPLDQLISKLGDLSRRFKYASMGLTVLGVILISKPVIEYILKRIEDTLERRRRQFALK
RVV-DAAA--------------------------RR------------------------
----------AKPVTGG-------------------GT-SRDGDT-PDLCVVCLDQK---
YNTAFVECGHMCCCTPCSLQLR--------TCPLCRERIQ--------------------
------------------------------------------------------------
---------------------------QVLKIY--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Arabidopsis_lyrata_338432_PACid_16045815
--------------------------------------MIHLAGFTCCLGGIALYLLSRN
TGGV---VKSITRVNHLKDLEQL---VESKVFPLIIAVSGIVGSETPIKCEH-SDILGVF
LKKTAEQQVLSRNWRFS-WVRKSTLMQ-----------PMTKEVPWFLDD----------
---GTGRVNVAVSQGE-IGLALTVGSDVFEKAEPVS----LVQGTLDYLKGLKILGV---
--------------RRVEHVVPIGTPLTIVGEAVKDGMG-NVRIQKPEQG-PFYV-----
SYVPLDQLISKLGEWSRRFKYASMGLTVVGVILLSKPVIKYILKKIEDTLERRRRQLLQK
RVV---------------------------------------------------------
-------------------------------------------DV-PDLCVICHDQK---
YNTAFVQCGHMCCCLTCSLRLT--------TCPLCREQIQ--------------------
------------------------------------------------------------
---------------------------QVLKIY--RH-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Arabidopsis_lyrata_867782_PACid_16034683
--------------------------------------MIHLGGLTCCVSGGVLYLLSMI
PGSFFEMLNSVTRVHQIKDLENLL-QVEGK----IIAVSG--------------------
---TAQQLFLKRNWLFS-WVEDSKWML-----------PQAKEVPWYL------------
-----------------------------------------------------MLGV---
--------------RRTEHVLPIGTPVTVVGEAVKDGIR-GFRIQKPEKG-LFFV-----
SPVPLDKIISPMGKWLRRFKYVYVGLTVVGVILISKPVIEYI-------LERRRGRLLRK
RVA-DAAA--------------------------KR------------------------
----------AKLVARGLETQ---------HENSLDST-SRDRDV-LDLCVICLEQK---
YDATFVKCGHMCCCLTCSLHVK--------TCPICRRPIE--------------------
------------------------------------------------------------
---------------------------HVLKID--R------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Mulan_NP_078820
-----------------------------MESGGRPSLCQFILLGTTSVVTAALYSVYRQ
KARVSQELKGAKKVHLGEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVI
QRLTLQEHKMVWNRTTHLWNDCSKIIH-----------QRTNTVPFDLVP--------HE
DG-VDVAVRVLKPLDS-VDLGLETVYEKFHPSIQS-----FTDVIGHYISGERPKGI---
--------------QETEEMLKVGATLTGVGELV-LDNN-SVRLQPPKQGMQYYL-----
SSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQ--------YLQRQER-LRL
KQMQEEFQ--------------------------EH------------------------
----------EAQLLSRAKP-------------------EDRESL-KSACVVCLSSF---
KSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAIT--------------------
------------------------------------------------------------
---------------------------RVIPLY--NS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Mus_musculus_gi_18043560_gb_AAH19516.1
-----------------------------MESGSRPSLGQVILLGTSSMVTAVLYSIYRQ
KAQVAQELKGAKKIHLGEDLKGILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVI
QRLSLQEHKMVWNRTTHLWNDYSKIIH-----------QRTNTVPFDLVP--------HE
DG-VAVSVRVLKPLDS-VDLGLETVYEKFHPSVQS-----FTDAIGHYISGERPKGI---
--------------QETEEMLKVGATLTGIGELV-LDNN-AVRLQPPKQGMQYYL-----
SSQDFDSLLHRQESSVRLWKVLVLVFGFATCATLFFILRKQ--------YLHRQER-LRQ
QQLQEEFL--------------------------EH------------------------
----------EAQLLSQASP-------------------EDRESL-KSACVVCLSNF---
KSCVFLECGHVCSCRQCYLALPE-----PKRCPICRREIT--------------------
------------------------------------------------------------
---------------------------RVIPLY--NS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
-----------------------------MENGGRPSVGQVILLTTSSAITALFYSIYRH
KYRSVQTLKEAKKFCLTDDLPAVLSDLPGKCVPYAVIEGAVTSVKEVLNSQYVENCKGVI
QRLSLKEHKMVWNRTTHLWNDHEKIIH-----------QRSNTVPFDLAP--------EN
PGESGVSVRVLRPLEA-VDLGLETIYEKFHPAVQS-----FSNILGHYMTGERPKGV---
--------------QETEEMLKIGATITGVGELV-LDNK-TIKLQPPKDGMLFYL-----
SSMDYEGLLEKQEVQMRWWRILSIVFGVASCITLFFILRRK--------YRHYKEK-QHL
KNLQREFE--------------------------ES------------------------
----------RARQRVQQEP-------------------QNKEEV-QNPCSICLSTE---
KSCVFLECGHVCSCISCYQALPS-----PKKCPICRNFID--------------------
------------------------------------------------------------
---------------------------RIVPLY--NS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Danio_rerio_gi_148922854_ref_NP_001092230.1
-----------------------------MEASGKPSTAQIVLLATSSALTAVLYTIYKR
KSSHVARLREAKKMSLNPELKTILSEAPGKCVPYAVIEGVVRSVKETLNSQFVDNCKGVI
QRLTLNEKKMVWNRTTNLWNDCEKVIH-----------QRTNTVPFDLAP--------HD
DT-VPTTVRVLRPLDA-AELDLETTYENFHPSQQS-----LTNVIGHFISGERPQGI---
--------------QETEEMLRLGASMTGVGELV-LDNN-LVRLQPPKKGLRYFL-----
SRLDYDTLLSKQEGHLRIWRVLTVLLGLTACATFFYLLWRQ--------YVLRKER-RKE
QSVLDEYR--------------------------KW------------------------
----------QSKRFQELHL-------------------AKEDVS-PTACTICLNHE---
RSCVFLECGHVCACEGCYRALPE-----PKKCPICRATID--------------------
------------------------------------------------------------
---------------------------RIVSLY--NS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
----------------------------------MEFLHESVALGVDLLILGLCAREYVH
YKRTAKVLKAAPQYNIDGDLKSVVERQRDKKIPYAVIRGTVTPIGVPLRSSLVPSVSGVL
QIVKLHEHRVTRGFAGF-WTEQHKLLH-----------ESANEMPFELRN----------
---QSHGVEIVDALSA-AVLDVDVVYDNYEPSNLS-----LFDHVFGFFSGVRQRGL---
--------------QTTEEVLREGSFLTAIGELE-LDGD-TLRMQPSNEG-PLFL-----
TTATKSTLIKRFEDAKTTTILKLVVCSTISAILVAFIAKKL--------YRKRKQE-REE
AKIRERLD----------------------------------------------------
----------------------------TERRERRARSRPHTLSQ-DQLCVVCSTNP---
KEIILLPCGHVCLCEDCAQKIS-------VTCPVCRGSIV--------------------
------------------------------------------------------------
---------------------------SKAAAFIA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>rsz31o21_6
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------CRVVRSVPHSRFRPWFTRTPRTTMFGRRVYAL--L
EIPKIHSSXCWSLFLXANVLGPLHSLLHGEGXSRTAQRALSSSMSSRWSRCPQYL-----
-------------PHSRPVWASGTARIATAVSCPVDIASRFFSN-----RTRPNSPSIDT
RLFCCSAL----------------------------------------------------
------------------------------RAPKISPRAAAEAEH-DDLCIICMTDP---
RDTTVLPCGHLCLCVDAQLLRV-----RSDRCPICRSPVD--------------------
------------------------------------------------------------
---------------------------SLLXIRX--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>rsz12o01_6
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------VRRIASK----PITL-----
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------EHTWNL-NVPCVLILVHA---
FNGLFTIVDTVLVNHAQS---------NXSECPMCRVTIT--------------------
------------------------------------------------------------
---------------------------LRIRLYAVKRLERX-------------------
------------------------------------------------------------
------------------------------------------------------------
------------
