>gnl|BL_ORD_ID|3610 @Acaryochloris_marina_MBIC11017@ 641252794 AM1_3710 hypothetical protein [Acaryochloris marina MBIC11017]
MKIIGIILIVIGIILFFVYSNLKRKLASLRQARPASIAELNHLASEIALEMGSGSWRDYV
KLRGTIQCDQPLISELKQMPCVHYNMTVVREYEEQVTERDSDDKVVTKTQRGSETLSQNR
ESVPFFLQDDTGEIWVEPEGAQIETVRVLDEFSPEQPSGGQLSFGGFSLSLSSAETGRQT
IGYRYQESVLPVQRQVFVVAQVSDFNQSLVLENPTTKGQRFVISLKSEEALAQTTQTSVT
YAFYGMISTLVVGGLLVIFGLLSA
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1046 @Anabaena_sp_PCC_7120@ all1047 ABC transporter, permease protein NatC
MIEYLIFLAISTATFALFSLGLNLQWGFTGLINFGHIAFMTLGAYTTVLLSLKGVPLFIS
AIVGAIFAALLGLVIGFATLRLREDYLAIVTIGTGELIRLVVNNQDLPVGDTWVSGAFGV
QSYPIPLSTEPNLFFRLLMIGILTLLFAVTVFSLWRWIRNAQKLQLTDATDKTSSKQEIA
SRFGVGIILGLLATAIYISGVIT----LYNYIPKAGLMLVSLLVLAFVFWRL--EYLVRS
PWGRVLKAIREDEEIPKAMGKN--VFWYKLQ----SLMLGGAIAGIAGAFFAWQISAIYP
DNFQ-PQLTFDSW----------------------------IMVILGGAGNNIGSIL---
---GAVIYFAYDAITREVLPKIIPLDEARLGAFR--------IMCIGLILMVLMIWRPQG
ILGKKEELTLGK
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------------------------------------------------------
------------------------------------------------------------
------------------LIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIA
NQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVT----WEYNEEVIKQD
NEG---KTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKV---LEEFRP
ENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVI-GTATDEEGMITIRK
PTEKGQRYFISLKSEEE-------LSQATNNAIRGTFYSMIFFLTLGLILLVAGVLR---
-----------G
>gnl|BL_ORD_ID|5129 @Anabaena_variabilis_ATCC_29413@ gi|75910733|ref|YP_325029.1| unnamed protein product [Anabaena variabilis ATCC 29413]
MAKYLLASAGGAGFLWLFCGLFPVQAITNLNNSDKNLEIAQNNINHKNIDSL--------
-------------------------------------------VSQELTQKD---LTSSN
QPQKSENLDSDNTINSLPLIIQESTNSSPPSDQLAQVTSVSQLSDVQPTDWAFGALQSLV
ERYGCIA-GYPNLTYRGNRAMTRYEFAAGLNACLDRINELIATATADLVKKEDLATLQKL
QEQFAAELATLRGRVDALEARTTELEANQFSTTTKLNGEAIIAAIGATGGAPGSNDSNLI
LVNRVRLNLTTSFTGKDLLITGLQAYNFLGGATGEGSVQNSLGLGSPILSSSSARTSFEP
QFPGLNVKNLSSVGANSLELYKLLYIFPVADKLTLFVGTAAETSDAFPAITPFYGEGQES
ISRFAGLNPVVRVSGGTSGSGLASAAGFIYSISPNLDFRALYGSVNANLPQKSPTEALPG
VSTTPLGAGFFSGSSVIAAQLTFKPSRDIDIGLNYANSYHEINILGTGLISGDIGALSGV
SPGTPVKLNSFGGTVTWRFSPKVALSGYGAALFVDDSANNVDASTTFTSWMAGVHFKDLF
KSGNNGGIIFGQPLYRTDASGAAVLGSNRATPYHLEAYYRVRVSDNISITPGAFILFNPE
GDSRNETTTVGVLRTTFTF
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M---IL-----IGIICLIVGVILLFFWRSNRSKLRNLRLA----SASTISSLQTIANQIA
EEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIRE
KERKSETVAQNS--RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLT---
--FGNFSINLPSFEERRQTIGYRYQ-----EEILPIGRQILVIGTA--TDEEGMITIRKP
TEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>gnl|BL_ORD_ID|5206 @Arthrospira_platensis_NIES_39@ 650388547 NIES39_M02110 hypothetical protein [Arthrospira platensis NIES-39]
MVTTTEPTIKLVDEETENLLNWAATVEHSKASYFEKAQILAQKLGAHWLGDGLTQIGFWT
PKLTSQVMRRLEIFLEVLIPIDEIDLRADQQVVRFHRTRINLKQQGEYHWGVVAGMQPGS
REQVGSFYWLRYIDQAEKLQAIRDPLAYSLPYGVFGPAELYDIETLQAQRPDLEYFSRRG
TSRHPTIDLHDDDLSPLPNPKLIPRVRAPKNILQLHVGTATAAGTFEGLTSLYSRISDKL
AKNIPLTPLEENYIGYGAVQLLPTEPPIEFRDEYSPESEFFAFMSEDEDILEINLSKPDT
QDWGYDVPILGSSTTNPAIMGSRRPDEVVDFIATLHNFSTGPIQVIYDIVYGHADNQSEL
LLNRQFLKGQNMYGQDLNHQLPTVRAILLEMQRRKMNTGVDGIRIDGGQDFRFFNPLTGL
VEQDDAYLLAMSD------------------VVQD-----IGGYQRLLFTIFEDGRPWP-
-----------EEGWEEISTYRDLIELRPDSFQWGPLIFAHNTPTLKGFWERK----WKR
VCEVMYQGEN-WITGCANHD----TVRRGNQVELDQEINWNLGKTLSEVLHNGYDNPAVT
LWVYGFSPGLPMDFINATTRAPWMFFRNTDERYGVKVVAEEMGFLDWQITPELYQRDFVF
SGLKSLGFEDLEEIKQFGNALQQAMIDNDYSLPAVVEACQACLGDSAQECKVEYWQKMNH
PEMVEFLKDLNIPKLKEFALKFMEDCYEICNVSHYGEDLNAVQTNFNLQLRRFRHDRIWL
RQNLMGTDQFNKIGDQTQTVFYGVRGNPYREEDQVVMVAHMGGEPMTVTVGDWLELDLSD
WKVAIASPGVELNDNLASLKKFELKDSQGVLLVPQQPQK
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL----------------------------------------IGIICLIVGVILLFFW-
---------------------------------RSNRS----------------------
-----------------KLRNLR-------------------------------------
---------------------------------------LASASTISSLQTIANQIAEEI
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------GGGSLREYVKIRGV
IECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPF
TLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRY
QEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNA-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------IRGTFYS------MIF-------------FLTLGL--
-----------------------------ILLVAGVLRG
>gnl|BL_ORD_ID|3764 @Arthrospira_platensis_Paraca@ 646131498 AplaP_010100019256 sodium-dependent bicarbonate transporter [Arthrospira platensis Paraca]
MDFLSGFLTRFLAQLQSPTLGFLIGGMVIAAVNSQLQIPDAIYKFVVFMLLMKVGLSGGI
AIRGSNLTEMLLPAVFALVTGIVIVFIGRYTLAKLPNVKTVDAIATAGLFGAVSGSTMAA
ALTLLEEQGMEYEAWAAALYPFMDIPALV------------SAIVLASIYVSKQKHSDMA
DESLSKHESLSKQPVAAGDYPSKPEYPTTRQEYLSQQRGSANQG-VEIWPIIK----ESL
QGSALSALLLGLALGLLTRPESVFQSFYE----PLFRGLLSI------------------
-LMLVMGMEATARLGELRKVAQWYAVYAFIAPLLHGLIAFGLGMIAHVVTGFSLGGVVIL
AVIASSSSDISGPPTLRAGIPSANPSAYIGSSTAVGTPVAIALGIPLYIGLAQALMGG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
---------MILIGIICLIVGVILLFFWRSNRSKLRNLR------------LASASTISS
LQTIANQ--IAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVI
KQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENF
SGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEK
GQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLR--------------
---------------------------------------------------------G
>gnl|BL_ORD_ID|1128 @Arthrospira_sp_PCC_8005@ 648386350 APCC8_010100005922 polypeptide-transport-associated, ShlB-type [Arthrospira sp. PCC 8005]
MSLHIRLIGCQMTTVGLILFSPLVSAQALFSPNCNSAECLGLSQSFPLPPQSDPNRDRFL
QPLPSPPQIPPNGEPEIETPPPSSPPIPGDDTPFPISEIQIIGSSILSTEEINAIASTVS
NQTITLNQLQNIADQITEIYLRRGYMTSRAVVPQQTITDGVVEILVIEGSL-EKIEVEGT
RRLNPNYIISRVNLGAKTPLNTLQLENQLRLLRLNPLFDSVEASLRPGGGEGQSILVVRV
TEANPIQLSFSLD-NYSPPSIGSQRLGVNFSHLNLTGRGDFLLVSYKTTRLITGGESDIL
DFIYSIPVNAMDGTIQLRIPPYRNRV----ITEEFADLNIQGNSQLY-EISYRQPLVRTP
WEEFALSAGLSYQESQTLVDNQGLRFGFGPDDDG-VTRLVVLKLGQDYIRRDRLGVWALR
SQFSLGLGILNATNTKFLPNSDFVSWLGQIQRLQRIGDNHLLILQGDLQLAANPLFPSQQ
FVIGGAQSLRGYRQNVRAGDNGFRFSIEDRITLKRDRLNLPTLQLAPFLDMGQVWNHPNN
PNSLPSQTFLVGGGLGLLWEPIPHLNIRLDYGFPLIQLRDRGDNLQDHGIYFNLVYTLN
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M----ILIGIICLIVGVIL---------LFFWRSNRSKLRNLRL----------------
-----------------------------------------------------ASASTIS
S-------LQTIANQIAE--------------------------EIGGGSLREYVKIRGV
----------------------------------------IECD-RP--------LISQL
KQEPCVYYSMTVTWEYNEEVIKQDNEG-------------------KTIREKERKSETVA
QNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLP----S
FEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYF-------ISLK
SEEELSQATNNAIRGTFYSMIFFLT-LGLI----------LLV-----------------
-----AGVLRG-------------------------------------------------
-----------------------------------------------------------
>gnl|BL_ORD_ID|19755 Arabidopsis_thaliana AT1G59560.1|PACid:19657702
MIHLAGFTCCLGGVALYLLTRSTGRDIKSITRVYQLKDLEQLVEVESKVVPLI-------
-IAVSGDVGSETPIKCEHSYVLGVFLKRTA----EQQVLRRNWRFSWV----RNSTLMQP
MTKEVPWYLDDGTGRVNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGY------LKG
F----KILGVRHVERVVPIGTPLTVVGEAVRDGMGNVRIQKP-EQGPFYVTYIPLDQLIS
KLGDLSRRFKYASM-GLTVLGVILISKPVIEYILKRIEDTLERRRRQFALKRVVDAAARR
AKPVTGGGTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCSLQLRTCPLCRERIQQV
LKIYRH
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI-LIGIICLIVGVILLFFWRSNRSKLRNL-RLASASTISSLQTIANQIAEEIGGGSLRE
YVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ
NSRSIPFTLQDSTGEIRVNPERAEIETV-----KVLEEFRPENFSGGSLTFGNFSINLPS
FEERRQTIGYRYQEEILPIGRQILVIGTAT-DEEGMITIRKPTEKGQRYFISLKSEEELS
QATNNAIRGTFYSMIFFLTLGLILLVAGVL------------------------------
------------------------------------------------------------
----RG
>gnl|BL_ORD_ID|903 @Cyanobacterium_sp_UCYN_A@ 646530743 UCYN_09670 hypothetical protein [Cyanobacterium sp. UCYN-A]
MSF-----GIYNIHFLDFEKDTADMEFNVQEQTNPKDLSTETEGSLTPAFSLGNQPWQEW
LTPMVDSFAKVPEYVGRFFSEYKQPLTTLGLLILSFISVKIMIAVLGAID-DVPLLAPLL
QIIGLGYTLWFTWRY---LWKSSNRKELLSEFEAVKNQVFGNNI----------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWR---------SNRSKLRNLRLASASTISSLQTIANQ-----
----------IAEEIGGG-------------------SLREYVKIRGVIECDRPLISQLK
QEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVN
PERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQIL
VIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILL
VAGVLRG
>gnl|BL_ORD_ID|932 @Cyanobium_sp_PCC_7001@ 647589195 CPCC7001_112 glycosyl transferase, family 39 [Cyanobium sp. PCC 7001]
MITSGSDHAPEQGSQDMPSVNDPMKAPTSAPVRARGWLGSLGSAGLILLLISAVVLLLFW
GSNILYPLDKTESLQLDIARTMHSEHSLA---VPRVSGGPYFDKPPLPYWVAWPVFQFFP
ADPWLARLGAGVASTLGVVATVLLVHQQGRSEADPPRRSLLRALLAGLILACLPGYAAFA
HVAVHDSYITTCITVAAVGLYALLFGRPLGAPGPRGLAVIVGVAMGVGFLAKGLLAWALP
LAVVLGFAALTRQAAPLLRRWPQLLLSAALAVSVPLPWLLAAFHQAGPAFLAGFLGHSNL
ARVTSTVDSHAGPWFYYLPVVLLLSFPWGLVALPNRARWRQLLGQARQRDAGNRPVDLQL
FALVWLVLTVLLLSVASTKLPHYILSCLPPLAILAAFNLVPEPCPAAARQDPFSRSPRFY
AILGAGTAVVLAATGLVLAPLVAGLIKPDRVFPDYTAALVSHLEGWPFRTLLVLMALAVA
GLLLWIPQRRAALVTAWTLVAVL----------------SFSTVVPGLATVYRQHRQAAI
LDLADQVAGHTEAGVPIVILGKSYHSVALRSGHPILRLDGWPEVVALQRSSQGHAFEHGL
VVFAPRHRMLSDAQIREAGLR-MAALDERQNL--------------------LAVELRSA
GPAGG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIG-----------------------------------------IICLIVGVILLFFW
RSN----RSKLRNLRLASASTISSLQTIANQIAEEIGGGSLRE-----------------
-----------------------YVKIRGVIECDRPLISQLKQ------EPCV-------
-------YYSMTVT----------------------------------------------
------------------------------------------------------------
-------------WEYNEEVI-------------------------KQDNEGK-------
--------TIREKERKS------------------------ETVAQNSRSIPFT------
---------LQDSTGEI------------RVNPE--------------------------
---------RAEIET----VKVLEEFRPENFSGGSLTFGNFSINLPS----FEERRQT--
-------------------IGYRYQEEILPIGRQIL-------VIGTATDEEG-------
--------MITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVA
GVLRG
>gnl|BL_ORD_ID|2656 @Cyanothece_PCC_7424@ gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424]
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1048 @Cyanothece_PCC_7425@ gi|220906503|ref|YP_002481814.1| unnamed protein product [Cyanothece sp. PCC 7425]
MGLAIVGAILLVTGGILYFVQRHYQQKLYSIKLARKTTVAELKQLADQVGAEIGQGSLRE
YVKLSGQIKCDTPLISELKQVPCVYYQMQVEREYEERLTERDNDGETREKTQRGSETIAS
NSQSTPFFLQDQSGAIEVDPSGAAIETVQVLNEFRPEAGS-ARISFGNFSLSVGGSFPAG
RETIGYRYRESILPPDRRILIVATASDSSGILSLQKPVEKRQKFIISLKSEDHLAQSTQQ
TATYTFYGMIACLGLGAILLVVGLIIR
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
--MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLRE
YVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ
NSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINL-PSFEER
RQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNN
AIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|5519 @Cyanothece_PCC_7822@ gi|307149806|ref|YP_003890849.1| DNA-cytosine methyltransferase [Cyanothece sp. PCC 7822]
M-------------------ATRKFGQYKPIVDKDNTPTIGTLFS------GGGLFDVGA
MLAGIKPVWGVEFD-------PNSPSLSSAIAECYEKNLGRHLIK-----KPVQDVDFSS
LVPPDFLHCSPPCQKFSLS--------NPQRGETDNDLELALTTRRAIETLKPQVFTLEN
VVPYAKSLSFQTIKETLEKLGYQYRELILDAADFGVPQCRKRFFLVATNNLIPLELTLPK
KLSITWFEATVDLIDDLPESTLAAWQWQRLPFDVVQEFKNEADTAYLIERSGARNDRPLH
LRTANQPAWTIKAGLGSDGKGGNRLDPINLYVKGKILRPTPRFLARIMSVPDWYELPTAM
SIATTILGNGVCPLVAQQLLTALIPYLEKEKLPMSDPPVNEPNSLEIVSDEYLSADEEKE
LLRLERVVERSFYEAGSALRKIRALRLYRARFNSFEEYTQERFGFTRRQPYYLIEAANVV
DNLKSECEPLVHILPSSERQVRPLTKLNATEQRSVWNDAVSRAQGKVPSGRIVTEALEAL
KQRVREKSLAPFPYNEGDVCKILVKGNPDLKGKGGHWGVIVAINNFSADIQLADGIYLAK
EENLEELPYTPELREKAKIISDRLYRLSQHELEDSSKAFIAELGAEPRVILSDLEEQILN
LIEKNVNLLDDAKTVAIMDSLEGKKSVLKE
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGV-----IECDRPLISQLKQEPCVYYSMTVTWEYN--EEVIKQDNEGKTIREKERKS
ETVAQNSRSIP----FTLQDSTGEIRVNPERAE--------IETVKVLEEFRPENFSGGS
LTFGNFSINLPSFEERRQTIGYRYQEEIL-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------PIGRQILVIG-------------------------------TATDEEG
MITIRKPTEKG-------------------------------------QRYFI-------
-SLKSE---------------------------------------------------EEL
SQ---------------------------------------ATNN---------------
------------------AIRGTFY----------SMIFFLTLG----LIL---------
-------------LVA---------GVLRG
>gnl|BL_ORD_ID|1655 @Cyanothece_PCC_8801@ gi|218246452|ref|YP_002371823.1| hypothetical protein PCC8801_1616 [Cyanothece sp. PCC 8801]
MKINQTQIKIILLIAIVIAVILRVANLSNREFWYDEVLSLLLSTGQKINYQTPQDVPVIL
ANYTNLLQLPPENSLTETVQTLQTFLQGLVAEPHPPLFFIEQHLWLRLWGNSEIAMRSLG
VLFSLASMGCAYGLGRCLLGNTGGLIFAVFLGLNPYYLFHSLNVRMYVSLVFWTLLSSWS
LLELINLNCSKNITKKSVSKSKIMFSQMGWISLLIISVTAGLMTFYYFAFFVAFLGIIVL
YLDRQRWWQYAIYFAGSIVITSPWLWWGTRQQLRNADLERFSPNNSWLEAMLRHLQELIQ
VLGIHLIIGDWVSILPLGVSIISGLIAIALLTFCSWSLWKHEQKQLLIIGLLLGILPLLF
MLTLDIFTGKFTLGFGFGRSVIFVLPGCLLLGIIWLEKVAKNSKNMIIIAIISLYLMTNI
ADFA---------------LRPRQMFHQIADIINQQSQTPTLIIINSQAW----------
--GHILRLAYYLPPNEPLSLLAQNSKNLAPTLEKTLANQPQNYQRIIWLDSQRPVWGKPA
TEQQKQQIQQILNRQFELKDSKFLSGTWELDNFTLT----EMSKQ----------VPI--
------------------------------------------------------------
----------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------ILIGII----
---------------------------CLIVGVILLFFWRSNRSKLRNLRLASASTISSL
QTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQD
NEGKTIR-----EKERKSETVAQNSRSIPFTLQDSTGEIRVNPER---------------
AEIETVKVLE------EFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGR
QILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGL
ILLVAGVLRG
>gnl|BL_ORD_ID|4397 @Cyanothece_PCC_8802@ gi|257062260|ref|YP_003142318.1| hypothetical protein Cyan8802_4602 [Cyanothece sp. PCC 8802]
MINPTSIRTEFITESKIAPNLFERAVTFLPDLEINHVTHEVEGTPLYDALGWPYTRFGHQ
AKPNLLGAAFIQETGEPWQCKIYGELNKPRQDKETRGQGGQGGQGGQGGQGDKEDKKDFC
GEQSPVSPVSPVSPPSPPSQKRTGQYYAPKGIGDVPYLPPVPREIWEKLALEYDLPLPPE
NTSFWQWFQENKVIPLLLTEGGKKSLSALSSDIVAIALYGCLCGVDSETGAVKESLRPYI
EGRRVYIAFDQDKKQKTRRTVAKATQRLALAITKADGEPYQVLWNTEDGKGVDDVIKNQG
GDYFKQRIKLAQLIDPIQQQLNTLTRDIDLTVNQASLEGILKHLPRTGKLHISSPKCTRK
SSAIIEPLVKEWKQKKQLVISIVPRILLGKEQAVRWDINWIDEYGKTHFESYDTIGLCFD
SLGKLSSKNWSGALILFDEIRQGFKHFISSPTLEERRSFILKLLQEKLPEAVNGGGLVLG
--------CDSDLTDVEINYIDEICPVGKTFIVKNEYQPQKGLVIFNTGKYDETLDEILH
RYENGENLFIFCDTKAN-SQAIHDRLKQLDPNATHWLLNGDTTSEAENKAIIENNINYSL
KQQKPRSLVFTTSMSTGISIDGWINHQFHAEVFDHFTYGFVIAQGGILEPVEITQSMARV
RKNLDFTVYSGTGKKPDDLLNSCHPDVIKRQIYKRNHRAFDLQLITAEILEEKLGREPTH
YEILAEMMSKCDPETGMVIDPHLDLYCRVKARLNYASQNFDLMLYQQLIDEGYQLARYDC
LETTSTGNQIREIKEAHKWEEAEATADSLDICIEEAIEISYSNAPLEQRRQAAKAFLKQE
LPGVELTPDFIYKAVIKDKRRWLRGHKLFWYCQHPDMTREIDLGHYLNKIKQFANGVIFL
PDLRNVSVIVEEIKELGLWELIDLENPRELSKDDPRVLSFMERAYFRRYKLYNALGLTVT
EKTDSIKFIERLLQRLGIGLVLTRTEKQGEKKIRYYSLNTEALNDPDRVAVLEALTRRFL
GTVQTNYKLAEKLPSSVIESGTGHPQECIQKRSPVPPDLVHKESLGTGRAEECIQKRSPV
PCTGGPTKDSLSQTPGAQTFKLPMNRGFAHWCSFKYGEVIYDSRQIVPRPLWVIGSDESE
GCGLIVASEDGIEILPYRYGVRWASQQVS
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------------------------------------------------------
----LIGII----------CLIVG------------------------------------
------------------------------------------------------------
------------VILLFFWRSNRSKLRNL-------------------------------
------------------------------------------------------------
------RLASASTISSLQ----TIANQIAEEIGGGSLREYVK---------------IRG
VIECDRPLISQLKQEPCVYYSM----------TVTWEYN-------EEVIKQDNEGKTIR
EKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIET--VKVLEEFRPENFSGGSLTFG
NFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMI------------TIRK
PTEKGQRYFISLKSEEELSQATNNAIR---------------------------------
-------------------------GTFYSMIF-FLTLGLILLVAGVL------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------RG---------------------------------
-----------------------------
>gnl|BL_ORD_ID|621 @Cyanothece_sp_BH68_ATCC_51142@ 641674997 cce_0530 putative adenylate cyclase [Cyanothece sp. BH68, ATCC 51142]
MIIMAIEIERKFLVINDNWRSLGIGKVYKQGYIATADKITTIRVRIIGNEAYLTIKSKTE
GISRQEFEYPIPLEDAEIMLNTLCDRPLIEKVRY---TINQEKLIWEIDE--FKGDNEGL
ILAEIELKSEDQVIN-------FPDWVGEEVSHDPKYYNVNLVK----------------
-------------------------------------------------------HPYKI
----------------------------------------W
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRS----NRSKLRNLRLASASTISSLQTIANQ----IAEEIG
GGSLREY--------VKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGK
TIREKERKSETVAQNSRSIPFTLQDSTG-EIRVNPERAEIETVKVLEEFRPENFSGGSLT
FGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFI
SLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|4500 @Cyanothece_sp_CCY_0110@ 640628177 CY0110_06249 Abortive infection protein [Cyanothece sp. CCY 0110]
MTTKRIILIVLTIISLI-PVILSLIGSINQPQVQ-------SNLQLYQTNLVLQASEFSG
NNVSEFDKIRESILGKNPYQAAIKQYKEALNLSQKNLNQLENNLEIINQKSD--LIKESD
RTVNSIPIFSEG----NEQQRLQIEVNRQKKEIETIKI-------------------KIG
LLEIVQGNRTQGLTNLDNIQPLSFSPSVQNTADILSHLWDDNPSVLSESELTLKNELNGW
FRYY-SLNQLYQIQDRKNDLVSLQEKEQEAAQKAIIKLTIIAIIPVLGGLIGIGIIIFSL
VQLAIKKESAILAIDERFKWKTPWKLEITWQVLVVGFLFFGQIILPILVSFLNINLTELT
LRGKAFYVLGSYVAMSVGGIGVLYLSIKPFFPLPKDWFNFNWLSNWIVWGVGGYLVALPL
VVIISLINQNIWDGQGGSNPLLSLALEGQDIVVLAIFYFTAAIAAPFYEEIMFRGFLLPS
LTRYIPLWAAIGISSLIFAVAHLNLSEVLPLTVLGIVLGIVYTKSRNLLSSMLLHSLWNS
GTLISLFLLGSGAN
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-------ILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGG
GSLREYVKIRGVIECDRP---LISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKE
RKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSIN
LPSFEERRQTIGYRYQEEILPIGRQILVIGTA------------TDEEGMITIRKPTEKG
QRYFISLKSEEELSQATNNAI------RGTFYSMIFFLTLGLILLVAGVLRG--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>gnl|BL_ORD_ID|3366 @Cylindrospermopsis_raciborskii_CS_505@ 647107707 CRC_03432 3-beta hydroxysteroid dehydrogenase/isomerase [Cylindrospermopsis raciborskii CS-505]
MIMNVAIIGCGYVGYAVAKFWRQNPSFRVTVTTTSEHKVSTLQEVADAVEVTMGDDQIFL
NRVLKNQDVVLLAVGAKSSSSYEKTYLETAKTVTSLIKYHPKI-KQLIYTSSY---AIYG
DRNGVWVDEETPPAPPNLNSQILGKTEEILLAAATEKLRVCILRLGGIYGPGR---ELIK
IFSRTAGTTREGNGEEITNWVHLDDIVRVVEFARWQRLQGIYNLVDDSHFTSRELIDGVL
KTHNLPNVIWDATNKSTRQYNTWVSNQKLKDAGYQFIHPH------------IVL-----
--
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL-IGII-CLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGS--L
REYVKIRGVI-----------------ECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQ
DNEGKTIREKERKSETVAQN---SRSIPFTLQDSTGEIRV---------NPERAEIETVK
VLEEFRPENFSGGSLTFGNFS-----INLPSFEERRQTIGYRYQEEILPIGRQILVIGTA
TDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVL
RG
>gnl|BL_ORD_ID|4047 @Gloeobacter_violaceus_PCC_7421@ 637461464 glr4048 hypothetical protein [Gloeobacter violaceus PCC 7421]
MAM-----------------SSKSRPTAFRLAASEASMFSQNRKIVVTVKPEHFHKEWRL
VGKFHRRTNELLELLVMPPEVTCPADARQYYCLLMLNGSIRDTLRLRGLNNLDRPL----
------------TWTFD-------------------------------------------
---------------------SGG------------------QELGW-------------
------------------------------------------------------------
-------C
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLAS--ASTISSLQTIANQIAEE--------
IG----------------------------------GGSLREYVKIRGVIECDRPLISQL
KQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRV
NPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQI
LVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLIL
LVAGVLRG
>gnl|BL_ORD_ID|8 @Leptolyngbya_valderiana_BDU_20041@ Leptolyngbya_valderiana_BDU_20041 641057550 LVAL_00011 aldo/keto reductase [Leptolyngbya valderiana BDU 20041]
AALKAG-----VGVPRHQLYLTTKVLPNADRTATAREIDE---------------SLRRA
DIDYIDNLAIHGI----------------------NTWQHLEWVKAADGCMAAVRE----
-AIDAGKVRHVGFSTHGSLELILATMETGAFDFVNLHYYLLFQRHAPAIERASQLDMGVF
IISPVDKGGRLYAPSERLRRLCQPF--------------------SPLALNYRFLLSDRR
VTTLSLGAANPSELEEALEMCDRTDPLTDEERTVLERLDIQQTEVLGSDRCRQCYQCLPC
PENIHIPEVLRLRNLSLAYDMTEFGKYRYRMXENAXHWSRT
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL-IGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLR--
--EYV---KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERK
SETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVK-----VLEEFRPENFSGGSLTFGNF
SINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKS
EEELSQATNNA---------------------------------------IRGTFYSM--
-----------IFFLTLGLILLVAGVL------------RG
>gnl|BL_ORD_ID|5237 @Lyngbya_sp_CCY_8106@ 640019281 L8106_03012 hypothetical protein [Lyngbya sp. CCY 8106]
MSQQPSPNQRLNFDGSASVEGLVGQAGRDLIQTTTVYQGISIAGLFRREVKPPTQQEYRF
RQKLLSQVKEIWVENVLEKSLHNKAIIDLGLEERPDLVERRFSNVQISPEQSQKPLSTSR
GITTAFNRMGEGRTLLILGEPGAGKTTILLKLTRDLIDRTSDNLNRPIPVVFNLSSWAKK
QQKIADWLVDELQSNYGVSKSLGKAWVQDQQLLLLLDGLDEVRAKHREACVEAINQFLNL
KEYGLTEMVVCSRIKDYQALSNRLQ-VRGAICVQPLTSEHINQYIDKAGKQLQGVKTLLQ
QDTAMQEMMKSPLTLSIVSMAYKGFSVEKLQQFGSIEERRRHLFETYIEGMFDRHGRSKN
NKYKPEQTKYWLTWLATRMVQESQTVFLIEKIQFTWLEKKGERIFYRI-----ISALASG
LIFGLIFGLIFGLIFGLIIGLIFGLIIGLIIGLIIGLIFGLIFGLIGGEIKTVESLKWSS
QEFKKSIKKGLIFGLIIGLIIGLIVGQSVGQSGQWNEGLTIGLIFGLIFGLSYSLIQGLK
GAEIEVKKVANQGLKKSAFNALFFGLIIAIVAGILGLLGIEIVEILEQISNGITWEYLVL
TIPFGLTIGLAFGGGYAVIQHFTLRSMLYKKGVAPWNYARFLDYATELIFLQKVGGGYIF
IHRMLLEHFAQVEPEQVPESSVQISQSIDLINSSTTQELNPVNSEEVETLKTVEALEPES
VSNKICGNCQHENLSDSNFCSKCGTVLNSDSISN
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI---------------------------LIGIICLIVGVIL--LF--------------
----------FWRSN------------------RSKLRNLRLASA-----------STIS
SLQTIANQIAE--------EIGGGSLREYVKI------RGVIECDRP-------------
-------LISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS----
-----------------RSIPFTLQDSTGEIRVNPERAE------------IETVKVLEE
---------FRPENFSGGSLTFGNFSI----NLPSFEERRQTI----------------G
YRYQEEILPIGRQILVIGTATDEEGMITIRK-----PTEKGQRYFISLKSEEELSQATNN
AIRGTFYSMIFFLTLGLIL-LVAGVLRG--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|5698 @Microcoleus_chthonoplastes_PCC_7420@ 647570087 MC7420_4469 hypothetical protein [Microcoleus chthonoplastes PCC 7420]
MTQISTVRKFRRYCLDCLRILYWAYFKPFTFKRWLREIHPDLTLYSNPFLLQAEFRRHPR
LRRYADQVWWLSVFVPLLIMLLIAPIYSLSAGEPFNWQKSSLFFLGWLIGLVIARGGNEW
LGKWFYWFFLFLGGVTVAGNVLSRLAPEMMEALPILNLFLSNWFQLVPVAVGVAVGVAGG
VVVGVVVGVAGGVAGGVAGGVTGGVAVGVTGGVSVGVSGSVAIGIAFGIVLGMAGSVAGG
VVFGVIGGVAGGVIFSASGGMVGGVAFGIAWILGVLRVYFWIPELLWMIGLSFLSRQGKE
AQFLQYLPPRFDERIILPLPFMAQLIVAAYRDNPAASRQTIDYLIHSTNQQNVAAIAMTE
IAVDSLSHCHTMGDILAISDQLAWIPSPPPLTVSMILEPSTVSMILVRFMLEISQSVRAS
DNATSSYRQYELLQSPITRLEQLRNTLAYSQNVQLATGFGHIVQKWLKILQTAQQTLAEQ
AKRSAEIPQVYIAGASLNPDDAKTRFKGRLDIFREIETLAFSAQPPILLLHGGRRTGKTS
ALKYLSQKVGSELIPLLIDLQGAATATTLKGLANYLAEEI----IKAAKKSRN-FDLPYP
NPQQLSQEP--FLTLQTWLEKLERIAPGKRFLLCLDEFERLSEVIATTNSRIPLNFFRHV
LQHR----RQWILLFSGSHTLDELEP--------YWSDYLINTRSLR-----VSYLQQPE
AEELIVQPIADFPKIYESLTVSQIIQATRCQPYLVQLLCTVIVDHLNREKRQLATPDDVQ
TCIPIAIETGGMYFRELWTSLSEPEQDFLEDLITEETSYPPNKSTVRRLIRKEILEKTGD
CYRFQVPLVERFITQVVTEG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ILIGI---------------
----------------------------ICLIVGVILLFFW-------------------
------------------------------RSNRS-------------------------
------------------------------------------------------------
---------------------KLRN-----------------------------------
------------------------------------------------------------
-----------------LRLASASTISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRP
LISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDST
GEIRVNPERAEI---ETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEE
ILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISL--------KSEEELSQATNNAIR
---------GTFY------------------------------SMIFFLTLGLILLVAG-
----------------VLRG
>gnl|BL_ORD_ID|2062 @Microcystis_aeruginosa_NIES_843@ 641536048 MAE_20630 transposase [Microcystis aeruginosa NIES-843]
MWINFDQLLDLPNVTVVNYQKIAQTIFLKLALLNETIECPNCHQTLDRINQTEYNLVRDL
SILGNPVYLEVPRRQFHCQKCQKYISERLSFMRLRQHHTIRYESMIYERVKNCSIEEISR
EEGLGWEEVELIFNHCAKELEKEEWEAPERISLDEFSNLKGHKDFITTVVDMDKKILLDV
IKGHKQEELMEALKARPVAVREKVKEVSVDMWSGFTAVIKELFPNAKIIYDRFHVMAIIN
DELNNLRKLMGVHEKGLPHLLWKNKEDLKDEQKQQLEVILKEHPC----LGIAWEMKEEI
RQIYQSSKTFRGAERKLEKWIRIGGILYESSASMIQKHLQGICNYFENHTTNGLIEGMNT
KIKLIKRM-----------SYGFTNFE---------------------------------
---------------------------------------------------HLRLKLFAC
FNS
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL----------IGIICL--IVGVILLFFWRSNRS------------------------
---------------------------KLRNLRLASASTI--------------------
------SSLQTIANQIAEEIGGG--------SLREYVKIRG-------------------
-------------------------------------VI---------------------
------------------------------ECDRPLISQLKQEPCVYYSMTVTWEYNEEV
IKQDNEGKTIREKERKSE---------------TVAQNSRSIPFTLQDSTGEIRVNPERA
EIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGT
ATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGV
LRG
>gnl|BL_ORD_ID|3283 @Nodularia_spumigena_CCY9414@ 640026724 N9414_07866 Peptidase C14, caspase catalytic subunit p20 [Nodularia spumigena CCY9414]
MKRRTFLQRIGSILAVLGVTEAQWLTLCDRYSQALAQPSQRKLALLIGINQYQKSPALGG
CLTDVELQKELLIHRFGFVASDILTLTAEKATRTSIEEAFVAHLGQQVKAGDVAVFHFSG
YGTRIKSGRFIDTVQNALVPANAQD-----------AQKDEIVNYILE-ETIRLLLRSLP
TDRVTAVLDTSYNAPSKVQPTGWRIRVRPESAEAQLAIEELEFLQQLRSQNSSPIHELVL
TATSDTQQLAREILFSGFSAGLFTYALTQYLWETTPATTIQFSLSHVGSYMHKLGSNQQP
GWLSEQKNQPKALTV-ENLLLPNRTVGAEGVIRVIEDDGRTAQLFLAGLPPQVLENYGAN
SRFTVFTGEELILRSRTGLTAKAQISKIKPETPLQVGQLFQETVRVLPRSVNVIVGLDTG
LERIERVDATSAFAAINHVSTVVAGEQPADCVFGKLSETPSRYGLFTPGGKLIPNTSGES
GEAVKLVVQRLMGKLPTLLAAKLWRLTENEGSSRLPVKATLEIVNNLSSRVVMQRETTRT
LSAEHLQNKSLLTALSNPIVPIGSRMQYRLQNQSDRPIYLMLLGLKNNINAIAFYPWQSP
EESTFFNSKPLFQQVVVAPGETLLLPKGVTASEWMIPGPAYECEHQMILSTAPFSETLGY
LEKSKYPITDQRPFGALLKPLEIAQVLLQDLHNASAVKSEMNSTSTDSYVLDVKNWASFN
FDFQVA
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-------------ILIGI-----------------------ICLIVGV-----------
----------ILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREY----
-----VKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSE
T-----VAQNSRSIPFTLQDSTGEIRVNPERAE----IETVKVLEEFRPEN---------
-----------------FSGGSLTF----------------------GNFSINLPSFEER
RQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNN
AIRGTFYSM---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------IFFLTLGL---------------
----------------------ILLVAGVLR-----------------------------
------------------------------------------------------------
-----G
>gnl|BL_ORD_ID|1783 @Nostoc_punctiforme_ATCC_29133@ Npun_F1934 ABC-2 type transporter
MKRIFSQCV-----------KEIAQFRRDRLT------------------LGLAFLLPFL
TL---------LIFGF--------------------------------------AIRLES
KDIPLIVQDFD---RTNLSSSYIERLYATNQFTPKQWSGGNPARDAIDRGIAKAAVVIPP
QFSRDIQAGRNAKVQVLI---------DATDVNNARVIRGSIQRVTNFFMRDQGLIPDTN
IVTPRVRLWFNPGRLESLYIVPGTYGVVLWIFPSLLTAIAMVREKEKGTILQVYASSISA
TELLLGKGLAYLLIAITEALIVMGLGSIIFHIGIISNPITLLIGTLLFLIDSVSFGLLVG
VRSSNQNSAVQIVSLVGFITSLLLSGFIYPLSNIPFPLSLTPNVFPARYYIDITRDAFVR
GTGWTGVWFDLLMLAVLGFVFFNVARRLLSRMQISQ
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLT-------FGNFSINLPS
FEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQ
ATNNAIRGTF--------------YSMIFFLTLGLILLVAGV------------------
------------------------------------------------------------
----------------------------------------------------------LR
G-----------------------------------
>gnl|BL_ORD_ID|1783 @Nostoc_punctiforme_PCC_73102@ gi|186682334|ref|YP_001865530.1| ABC transporter [Nostoc punctiforme PCC 73102]
MKRIFSQCV-----------KEIAQFRRDRLT------------------LGLAFLLPFL
TL---------LIFGF--------------------------------------AIRLES
KDIPLIVQDFD---RTNLSSSYIERLYATNQFTPKQWSGGNPARDAIDRGIAKAAVVIPP
QFSRDIQAGRNAKVQVLI---------DATDVNNARVIRGSIQRVTNFFMRDQGLIPDTN
IVTPRVRLWFNPGRLESLYIVPGTYGVVLWIFPSLLTAIAMVREKEKGTILQVYASSISA
TELLLGKGLAYLLIAITEALIVMGLGSIIFHIGIISNPITLLIGTLLFLIDSVSFGLLVG
VRSSNQNSAVQIVSLVGFITSLLLSGFIYPLSNIPFPLSLTPNVFPARYYIDITRDAFVR
GTGWTGVWFDLLMLAVLGFVFFNVARRLLSRMQISQ
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLT-------FGNFSINLPS
FEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQ
ATNNAIRGTF--------------YSMIFFLTLGLILLVAGV------------------
------------------------------------------------------------
----------------------------------------------------------LR
G-----------------------------------
>gnl|BL_ORD_ID|1356 @Nostoc_sp_PCC_7120@ 637231412 all1047 permease protein of ABC transporter [Nostoc sp. PCC 7120]
MIEYLIFLAISTATFALFSLGLNLQWGFTGLINFGHIAFMTLGAYTTVLLSLKGVPLFIS
AIVGAIFAALLGLVIGFATLRLREDYLAIVTIGTGELIRLVVNNQDLPVGDTWVSGAFGV
QSYPIPLSTEPNLFFRLLMIGILTLLFAVTVFSLWRWIRNAQKLQLTDATDKTSSKQEIA
SRFGVGIILGLLATAIYISGVIT----LYNYIPKAGLMLVSLLVLAFVFWRL--EYLVRS
PWGRVLKAIREDEEIPKAMGKN--VFWYKLQ----SLMLGGAIAGIAGAFFAWQISAIYP
DNFQ-PQLTFDSW----------------------------IMVILGGAGNNIGSIL---
---GAVIYFAYDAITREVLPKIIPLDEARLGAFR--------IMCIGLILMVLMIWRPQG
ILGKKEELTLGK
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------------------------------------------------------
------------------------------------------------------------
------------------LIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIA
NQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVT----WEYNEEVIKQD
NEG---KTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKV---LEEFRP
ENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVI-GTATDEEGMITIRK
PTEKGQRYFISLKSEEE-------LSQATNNAIRGTFYSMIFFLTLGLILLVAGVLR---
-----------G
>gnl|BL_ORD_ID|3051 @Oscillatoria_sp_PCC_6506@ 648858089 OSCI_3080032 conserved hypothetical protein [Oscillatoria sp. PCC 6506]
MNDI----------------------------------------NQVASALEGKDYRKAA
QLLKQLQKDSPENPWVKFYIARYYELTNKLESAEKIYRQLLRDTTSPKIVAQTRQAIQRL
ETIEQNRR------KDAIALSKNDPRNAE-PGLLILEPVSPENKPAAIQHISRILKIDPY
TARTQIQSRGWRLYKTGTVGELRVYGEELLSAGIPVFWATLADIQKIQVFRVQYFQSLSP
QPTAICKNELDQLGSLTFN------WSEVSQCVEGLLPLFIEVMDYSPHRRSEKFRHKEI
TQDYAQIWDLHLPSRKCILRLCDQTYQFQKGITAEKIKESESKTQNSQNTARINWNNLVE
TFNQQLSVNLSSEFTPFAETALNYTQMLSRLKSHIDIERKSESPWDTAFQLYSVLVFLKS
QGQNK
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQ---DNEGKTIREKERKS----
ETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGN-FSINLP
SFEERRQTIGYRYQE-----EILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKS
E---------EELSQATNNAIRGTFYSMIFFLTLGLILLVAGVL----------------
------------------------------------------------------------
------------------------------------------------------------
---RG
>gnl|BL_ORD_ID|1143 @Prochlorococcus_marinus_AS9601@ 640078862 A9601_11471 possible lipoprotein [Prochlorococcus marinus AS9601]
M-NVFLVFLILGVIFLVFKKINSKKTKNLKLDKFKNKLQSTQTNIDRIFLREEEKTFSNP
NINIYIGVYDNEENINRKSNIH--RARLSKFKKS-----------KLNGEMIFQDDEQRI
YKFNDGKK----------------------------------------------------
------------------------------------------------------------
----------------------VYL--------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLAS-ASTISSLQTIANQI---AEE------
-----IGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKT
IREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFG
NFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISL
KSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1062 @Prochlorococcus_marinus_marinus_CCMP1375@ 637441485 Pro1064 Threonyl-tRNA synthetase [Prochlorococcus marinus marinus CCMP1375]
MPIITLPDGAQRTYSTPVTIAEIAAEIGPGLAKAAIAGEVNGELVDTCIPISVNANINII
TSKNKEGIDIIRHSFAHLLGHAIKQLYPDAKMAIGPVIENGFYYDIAYKDTFSLDDLNQI
ELRIKELIKQDYDVVVEEVSKEKARKTFLDRDEAYKVQIIDEIPDNETIKLYKHQEYIDM
CRGPHVPNTKHLRAFSLMKVSGAYWRGDSNNEMLQRIYGTAWGSTKELEAYLLKIEEAEK
RDHRKIGKKLDLFHTQEEAPGMIFWHPKGWSIYQVLESFIRETLILNDYKEIKTPQTVDR
SLWEKSGHWDKFKEDMFTTTSENREYAIKPMNCPCHIQVFNEGLKSYRDLPIRLAEFGSC
HRNEPSGALHGLMRVRNFVQDDAHIFCTEAQIQDEVSKFIDLVFDVYKAFGFESIIIKLS
TRPTKRVGSDEIWDKSEKALADALNIKKFEWSYLPGEGAFYGPKIEFSLKDCIDRVWQCG
TIQVDFSMPHRLGASYIDENSQKKVPVMLHRAILGSFERFIGILIEEYEGKFPPWLSPIQ
VIVIGITD-----RNSIKCKEISNLLMLRGYR------------------ATYDTRNEKV
GLKIREHTLQRIPYLLIIGDKEQEEGTVSVR------TMHGIDMGSMKLTEFQEIINEAI
SLKGNY---------------KPVPKR
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGI----------------------------------------ICLIVGV-------
------------------------------------------------------------
------------------------------------------------ILLF--------
-----------------------FWR--SNRSKLR-------------------------
------------------------------------------NLRLASASTISSLQTIAN
QIAEEIG-----------------------------------------------------
-----GGSLREYVKIRGVIECD------------------------------RPLISQLK
QEPCVYYSMTVTWEYNEEV-----------------------------------------
----------------IKQDNE-------------------GKTIREKERKSETVAQNSR
SIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTI
GYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEE--ELSQATNNAI
--RGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|743 @Prochlorococcus_marinus_MED4@ PMM0746 Possible Zn-dependent peptidase
M-NPGEVKYFNHSSKPKCVFVENKELPLVCIDFWFKAGSAFEESDRDGTAHFLEHMIFKG
TNKLMPGEFDYKIESLGGMSNASTGYDDAHYYVLIPENNFKESLALLTNIVLSPSINIDE
FEKEKSVVMDEIKQ-------------QNDQP------DEKLFNYFLSRVW-------KN
NKYGKTILGTEKNLQSLKKADLEKFHKSFYKKNNFCIAIAGNISEKTYEIYHENNFSYLD
PNETSQIKNNNKSILVASTGREEINFKNIELARIFMAWSIPSLKNQKMNIGFEILASILC
VGRNSRLVKVLKEERNLVESIYVDVNGGEFGSLLVIEACCDEINLKNVEEEINETIQEVV
SCKNLTLNEIRKAINIVKSNYIFNLETSTQLTSFFGNELLWGRKNTLIDLNNHLDYWSNT
NNFKEIINYLSRNKFTLIASTGK-
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGII----------CLIV-----GVILLFFW--------------------------
----------------------------------------RSNRSKLRNLRLASASTISS
LQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQ
DNEGKTIREKERKSETVAQNSR---------------SIPFTLQDSTGEI-------RVN
P-ERAEI----ETVKVLEEFRPE-NFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILP
IGRQILVIGTATDEEGMITIRKPTEKGQRY-----------FISLKS-EEELSQATNNAI
R-----------------------------------------------------------
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1217 @Prochlorococcus_marinus_MIT_9202@  647673386 P9202_1127 conserved hypothetical protein [Prochlorococcus marinus MIT9202]
MYSAKADDSNCYSNQYVGKVGASGTVCANMLIVDRDLLDEGIANGAVGSDFQITKDGITY
NFGNTGNKIFTGQIKNFSSLFKDQTSFNADIGYWNTSRATTMSRMFMNASSFNQDISNWE
LNNVTNINGMFQDSLVFNQDISSWNISKVTRLNSTFRGAAAFNQNLNSWDVSNVTRLDRT
FLKAINFNSDLNSWDVSKVVSMHRTFAGAKNFNGNISSWNTESLRSLRRTFDGARAFNKD
ISNWDVAEVTNFTRTFKNAGEFDQNLTSWNVEHYDQTPILFAPILSSNKQPCWGFNGCPN
GPNLTSSNPSDNSFGVNTSLNLTLTFDKDIRASETSGNIALHKSDDTLVKQYSNDSLNIS
GKVITLPAELIANTDYYLLIDPKIIESSNGISYKGITDKTELNFSTYSNDSVAPVITSQS
PEDNATDVSTSDPTVEIIFSENVVRGSGNISLYNYSTDALIRSFNMSNETDISISRNEMS
ISLRDTDGSVLINDGTQYYIKISAGAVVDEAASPNSFAGIESKNAFNFTTKSVSCGSISG
VVRYKNGMPVNGSTVKLYKDDSLITTTTTNSVGNYNFFPNSAGTFKVEFVKSAGKRGKGK
VDLTDGPVSSGRFIKNIQISSSCEEFLDLDGLLIDPAGVIYESSTRQPVSGVTVKLLYEG
SLVNNDWLDDSGGNNIQETASDGKYNFVLKGDVAQSGNYSITVDPPKGYGFESTKIISEN
GIFTPDLGGGVQTIQIQEDAPDSGDLTTYHLNFNFTFTGVSSTSSNGVINNHIPIDSKGD
PTLKPDVLGLAEAWTDASIRFSKAGLDAVNRRLEWLARNKRSDKKSFQGIDFSFSNPTLE
KVFNGSGKKFKDIESKDFENWARANWNDERMKNESDQIIDDLRNNSVDIAFAELREKTFD
PDLNPKGGKLLGNWFLWTDGEIVVGDYKKNATSSNQKSDALNLTFGADKKLKNNSLLGFA
FT----YGNDHIKIGSQGSKLNSDNYSVSIYSSQKFKSFLPTDFQLGVGKMDFYTTRFED
SIAHKGQRDANLIFGSLSFRPDPISKGNITFNPYARIEASHISLKPFSETGSHLALTFKE
QT--VNHKILALGSDLFSEFEIKEWEIKPFAKIEYNFDFTDDSIVDLNYVDDSTTNYRFS
ILNSADNFLSNTIGLQMSRQNRFGAVLSYKNEQGNSKNSDSYQLHINWNF
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI-------------------LIGIIC---LIV-----------------------GVIL
LF------------------------------FWRSNRS---------------------
------------------------------------------------------------
------------------------------------------KLRNLR------------
------------------------------------------------------------
------------------------------------------------------------
------------------------LASASTIS----------SLQTIANQ----------
------------------IAEEI--GGG--------------------------------
-SLRE-------------YVKI--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------RGVIECDRPLIS---
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------QLKQEPCVYYS
MTVTWEYNEEVIKQDNEGKTIREKERK-SETVAQNSRS-IPFTLQDSTGEIRVNPERAEI
ETVKVLE----------EFRPENFSGGSLTFGNFS------INLPSFEERRQTIGYRYQE
EILPIGRQILVIGTATDEEGMIT--IRKPTEKGQRYF----ISLKSEEELSQATNNAIRG
TFYSMIFFL--TLGLIL----LVAGVL-----RG----------------
>gnl|BL_ORD_ID|1744 @Prochlorococcus_marinus_MIT_9211@ 641286129 P9211_17441 Lysyl-tRNA synthetase [Prochlorococcus marinus MIT 9211]
M----------------------SDLKETRLEKA-----------QVLKKLGNG------
------------------------PYGIRFEVTHKAAVLQVEHQDLANGQERQLEVCVAG
RVISRRVMGKLAFFTLSDESGSIQLFLEKATLEEHSDLDQESPGSFSQLTDLVDSGDWIG
VNGILRRTDRGELSIKVFSWTMLCKSLQPLPDKWHGLSDVEKRYRQRYVDLIVNPQSRKT
FRSRALMVSAIRRWLDERDFLEIETPVLQSEAGGAEARPFITHHNTLDLSLYLRIATELH
LKRLVVGGFERVYELGRIFRNEGISTRHNPEFTTVEIYQAFADYTDMMDLTEEMISFVCS
QICGSTTIQYQGKEVDLTPPWRRITMHELVLESTGLDFYEFGQDISKASTAMQSVGLNVP
DHADSVGRLMNEAFEQAVEGDLFQPTFVMDYPIEISPLARKHRSKPGIVERFELFIAGRE
TANAFSELIDPVDQKERLLLQQSRRQAGDLEAHVIDEDFVNALEVGMPPTGGLGIGIDRL
VMLLTDSPSIRDVIAFPLLKPESGSQ
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIP---------FTLQDSTGEIRVNPERAEIETVKVLEEFRPENFS-------------
---------GGSLTFGNFSIN--------LPSFEERRQTIGYRYQEEILPI---------
--GRQILV--IGTATDEEGMITIRKPTEKGQ------RYFISLKSEEELS----------
------------------------------------------------------------
------------------------------------------------------------
-----------QATNNAIRGTFYSMIFFLTL---------------GLI----LLVAG--
------------------------------------------------------------
-----------------VLR-----G
>gnl|BL_ORD_ID|1309 @Prochlorococcus_marinus_MIT_9215@ gi|157413649|ref|YP_001484515.1| hypothetical protein P9215_13141 [Prochlorococcus marinus str. MIT 9215]
MFLNYLPSEMVEVVGLTMIFSFLVGTILILLFTSDQANTKNLYLRKAK------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI-------------LIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQI
AEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIR
EKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNF
SINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKS
EEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1148 @Prochlorococcus_marinus_MIT_9301@ 640160734 P9301_11481 possible Borrelia lipoprotein [Prochlorococcus marinus MIT 9301]
M-NVFLVFLILGVIFLVFKKISSKKTKNLKLDKFKNKLQSTQTNIDRIFLREEEKTFSNP
NINIYIGVYDNEENINRKSNIH--RARLSKFKKS-----------KLNGEMIFQDDEQRI
YKFNDGKK----------------------------------------------------
------------------------------------------------------------
----------------------VYL--------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLAS-ASTISSLQTIANQI---AEE------
-----IGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKT
IREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFG
NFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISL
KSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1470 @Prochlorococcus_marinus_MIT_9303@ 640086991 P9303_14811 SAM-dependent methyltransferase [Prochlorococcus marinus MIT 9303]
MTSSTNSSLTSTPTPGDKVEITCVDLDRHGNGLARWNNWVVIVNDLLPGERAQIEFVRRH
RNQFLARKVHSIETVSSRRQPPCKIAKECGGCSIQHLNDHGQSLLKQSHLREILLRLGQL
DNKIEPIMTDYTRALGYRNRALIPLYRNREGQLLMGYYRRGSHQIIDLNRCPVLDRGIDQ
YLAWIKDDLQQQNWPADSDLSSGEGVRHLGIR---IGQKTRQVLITLVSSTTELSGLHQQ
ANDWYRRWPEVKGITLNIQRQRNNLVLGQETILLAGDLDIEEHFCNLSLLLSTTTFFQVN
TIQAERIVLKLLKWLSTTLP---DINIIDAYC---GIGTISLPIAAAGYHVIGLELHAEA
IAQANKNALRNNL-GNASFLCGDVSLLLAKILQHHDVLVLDPPRKGLDQMVIKTILSVRP
ERVAYLSCDPATLARDLKQLIVPNGPYQIDQLQPIDFFPQTMHIECLALLIRISS
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI---------------LIGIIC-----------------LIVGVIL------LFFWRSN
RSKLRNLRLASASTISSLQTIANQIAEEIGGGS----------------LREYVKIRGVI
EC----------------DRPLIS----------------------QLKQEPCVYYSMTV
TWEYNEEVIKQDN--------EGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPER
A--------EIETVKVLEEFRPENFSGGSLT------------FGNFSINLPSF------
---EERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLK-SEEE
LSQATNNAIRGTFYSMIFFLTLGLILLVAGVLR---------------------------
------------------------------------------------------G
>gnl|BL_ORD_ID|1052 @Prochlorococcus_marinus_MIT_9312@ gi|78779437|ref|YP_397549.1| lipoprotein-like [Prochlorococcus marinus str. MIT 9312]
M-NIFLAILIFGIIFLFYKKFNSKKPKNLKLDKFKNKLQSTQTNIERIF-------LREE
EKTFSNPNINIHIGIYDNEDIINRKSNIHRARLSKFRKSKLNGEIIFQDDEQRIYKFNNG
KK----------------------------------------------------------
------------------------------------------------------------
----------------VYL--------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLAS-ASTISSLQTIANQIAEEIGGGSLRE-
-------YVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKER
KSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINL
PSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEEL
SQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|629 @Prochlorococcus_marinus_MIT_9313@ gi|33862902|ref|NP_894462.1| hypothetical protein PMT0629 [Prochlorococcus marinus str. MIT 9313]
MPQPHVWKLVDFIGRLCLSAVFVVAVPSKITKFSSVVEAISGQGIPESLAPFLLLAAIAC
LIVGSVLLLFGKSQKLGASLLLIFLVPTTVIFHAFPFQ----------------------
----------PKALFMNLGLT---------------------------------------
-------------------------------GGLT---LALTRPKFIER-----------
------------------------------------------------------------
----------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M----------------------------------------------------ILIGIIC
LIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYVKIRGVIEC
DRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQ
DSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEE
ILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIF
FLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1002 @Prochlorococcus_marinus_MIT_9515@ 640080684 P9515_10041 SAM (and some other nucleotide) binding motif:Generic methyl-transferase [Prochlorococcus marinus MIT 9515]
MSREPISKIAYKTLQQGKSIAGLAHKELSTRIMNFILPDN--KFGNLDI-DKKLLVDIQN
SMDRLREEDWDDAEKNIYPQKLLF--DEPWLRYLTQYPKIWLDMPNTWDRRRKQNYNDLP
KNIDNENYPKYYLRNFHHQTDGYLSDFSASIYDLQ---VEILFNGSADAMRRRIIKPLKE
GLNNFSSRKKSSLNILDVATGSGRTLKQLRGAFPKEKIMGLDLSGSYLKEASRFISNLDG
DLIELIKGNAEELPFEENTLQGITCVYLFHELPRTVRENVLK--EFFRVLEPGGSLILAD
SIQVSDSPDFIKIMENFYKSFHEPFYCDYIKEDITTKIKEIGFNNVKSNSFFMT-----K
VWSAIK-
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICL----------IVGV--------ILLFFWRSNRSKLRNLRLASASTISSLQT
IANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWE------YNEEV
IKQDNEG---KTIREKERKSETVAQNSRSIPFTLQDSTGEIRVN--PERAEIETVKVLEE
FRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPI------------------G
RQI-LVIGTATD---EEGMI--------------TIRKPTEKGQRYFISLKSEEELSQAT
NNAIRGT-----------------FY---------------------SMIFFLTLGLILL
VAGVLRG
>gnl|BL_ORD_ID|1027 @Prochlorococcus_marinus_NATL1A@ 640084312 NATL1_10331 thioredoxin peroxidase [Prochlorococcus marinus NATL1A]
MTTNE--CLRVGMQAPDFATTAVVDQEFKDITLSQYRGKYVVLFFYPLDFTFVCPTEITA
FSDRYSDFSSKNTEVLGVSVDSKFTHLAWIQTPRNE----------------GGIGDINY
PLVSDLKREICQSYN----------VLNEDGEA----------------DRGL-FIINPS
GIIMHSTINKAPVGRNIDETLRVLQAYQYVESHPDEVCPAGWTPGDKTMK----------
----------------------EDPKG----------SKEYFSAL---------------
------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGV---------------------------ILLFFW--------------
---RSNRSKLRNLRLASASTISS------LQTIANQIAEEIGGGSLREYVKIRGVIECDR
PLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDS
TGEIRVNPERAEI-----ETVKVLEEFR-----PENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|982 @Prochlorococcus_marinus_NATL2A@ gi|72382192|ref|YP_291547.1| thioredoxin peroxidase [Prochlorococcus marinus str. NATL2A]
MTTNE--CLRVGMQAPDFATTAVVDQEFKDITLSQYRGKYVVLFFYPLDFTFVCPTEITA
FSDRYSDFSSKNTEVLGVSVDSKFTHLAWIQTPRNE----------------GGIGDINY
PLVSDLKREICQSYN----------VLNEDGEA----------------DRGL-FIINPS
GIIMHSTINKAPVGRNIDETLRVLQAYQYVESHPDEVCPAGWTPGDKTMK----------
----------------------EDPKG----------SKEYFSAL---------------
------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGV---------------------------ILLFFW--------------
---RSNRSKLRNLRLASASTISS------LQTIANQIAEEIGGGSLREYVKIRGVIECDR
PLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDS
TGEIRVNPERAEI-----ETVKVLEEFR-----PENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|744 @Prochlorococcus_marinus_pastoris_CCMP1986@ gi|33861303|ref|NP_892864.1| Zn-dependent peptidase [Prochlorococcus marinus subsp. pastoris str. CCMP1986]
M-NPGEVKYFNHSSKPKCVFVENKELPLVCIDFWFKAGSAFEESDRDGTAHFLEHMIFKG
TNKLMPGEFDYKIESLGGMSNASTGYDDAHYYVLIPENNFKESLALLTNIVLSPSINIDE
FEKEKSVVMDEIKQ-------------QNDQP------DEKLFNYFLSRVW-------KN
NKYGKTILGTEKNLQSLKKADLEKFHKSFYKKNNFCIAIAGNISEKTYEIYHENNFSYLD
PNETSQIKNNNKSILVASTGREEINFKNIELARIFMAWSIPSLKNQKMNIGFEILASILC
VGRNSRLVKVLKEERNLVESIYVDVNGGEFGSLLVIEACCDEINLKNVEEEINETIQEVV
SCKNLTLNEIRKAINIVKSNYIFNLETSTQLTSFFGNELLWGRKNTLIDLNNHLDYWSNT
NNFKEIINYLSRNKFTLIASTGK-
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGII----------CLIV-----GVILLFFW--------------------------
----------------------------------------RSNRSKLRNLRLASASTISS
LQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQ
DNEGKTIREKERKSETVAQNSR---------------SIPFTLQDSTGEI-------RVN
P-ERAEI----ETVKVLEEFRPE-NFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILP
IGRQILVIGTATDEEGMITIRKPTEKGQRY-----------FISLKS-EEELSQATNNAI
R-----------------------------------------------------------
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1061 @Prochlorococcus_marinus_SS120@ Pro1064 Threonyl-tRNA synthetase
MPIITLPDGAQRTYSTPVTIAEIAAEIGPGLAKAAIAGEVNGELVDTCIPISVNANINII
TSKNKEGIDIIRHSFAHLLGHAIKQLYPDAKMAIGPVIENGFYYDIAYKDTFSLDDLNQI
ELRIKELIKQDYDVVVEEVSKEKARKTFLDRDEAYKVQIIDEIPDNETIKLYKHQEYIDM
CRGPHVPNTKHLRAFSLMKVSGAYWRGDSNNEMLQRIYGTAWGSTKELEAYLLKIEEAEK
RDHRKIGKKLDLFHTQEEAPGMIFWHPKGWSIYQVLESFIRETLILNDYKEIKTPQTVDR
SLWEKSGHWDKFKEDMFTTTSENREYAIKPMNCPCHIQVFNEGLKSYRDLPIRLAEFGSC
HRNEPSGALHGLMRVRNFVQDDAHIFCTEAQIQDEVSKFIDLVFDVYKAFGFESIIIKLS
TRPTKRVGSDEIWDKSEKALADALNIKKFEWSYLPGEGAFYGPKIEFSLKDCIDRVWQCG
TIQVDFSMPHRLGASYIDENSQKKVPVMLHRAILGSFERFIGILIEEYEGKFPPWLSPIQ
VIVIGITD-----RNSIKCKEISNLLMLRGYR------------------ATYDTRNEKV
GLKIREHTLQRIPYLLIIGDKEQEEGTVSVR------TMHGIDMGSMKLTEFQEIINEAI
SLKGNY---------------KPVPKR
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGI----------------------------------------ICLIVGV-------
------------------------------------------------------------
------------------------------------------------ILLF--------
-----------------------FWR--SNRSKLR-------------------------
------------------------------------------NLRLASASTISSLQTIAN
QIAEEIG-----------------------------------------------------
-----GGSLREYVKIRGVIECD------------------------------RPLISQLK
QEPCVYYSMTVTWEYNEEV-----------------------------------------
----------------IKQDNE-------------------GKTIREKERKSETVAQNSR
SIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTI
GYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEE--ELSQATNNAI
--RGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1446 @Prochlorococcus_sp_CC9311@ 638115069 sync_1481 hypothetical protein [Prochlorococcus sp. CC9311]
M--------------------------------------------------------EFL
TFESVVR-GRHLLGRV--------------------------------------------
------------------------------------FS--SLLWYQCGLNVVDLNA----
-GYRHKCHLMPITRFILIVGIGL-------------------------------------
-----------------------C
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|711 @Prochlorococcus_sp_WH_7803@ 640543064 SynWH7803_0712 Predicted flavoprotein related to choline dehydrogenase [Prochlorococcus sp. WH 7803]
MIIDDRHYDIIVIGSGAGGGTLAGALSRQGRRVLLLERGGAMALSDQNVADVDLFRKDRY
HPRNERWFGPDG----DPIAPQTTYALGGNTKIWGAVLERMREKDFDDLPLQNGISPRWP
FNYQHLAPFYDQAEHLYQVHGKSGVDPTEPARNGDFGHAPKPLMPFLEPLREGLKRQGCQ
PYDLPLSWSSSQEDPSGDAQLYGLDNADSEKLEVRSMARVM---------RLHVNPSGRE
VKAVEADVDGETWLFSADVVVLAAGAINTAA-------ILLRSSSEKHPRG-----LSNG
SDQVGRNLMN----------LQLTSILQLAAERNNGRYARSLGVNDYYWGDKNVSFPLGH
IQAAGGVLQDALFAESPPVLSLVSKLIPDFGLERLASRSVAWWAMTEVLPDPHNKVWLNN
DQIRINYLHNNREAHDRLVYRWIDTLTAVEADPITKVVTKAPTHPRGEAPLSVVGYACGT
CRMGDDPAASVVDGDGRSHELDNLYIADSSVFPSCPSVGPGLTTIALALRMSEALKQRFD
G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL----IGIICLIVGV---------------ILLF-----------------FWRSNRS
KLRNLRLASASTISSLQTIANQIAEEIGGGS---------LRE-----------------
---------------YVKIRGVIECD---------------------RPLISQLKQEPCV
YYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAE
IETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTA
TDEEGMITIRKPTEKGQRYFISLKSEEELSQATNN-------------------------
--AIRGTFYSMIF-----------------------------------------------
------------------------------------------------------------
-----------------------------------------FLTLGLILLVAGVLR----
G
>gnl|BL_ORD_ID|1856 @Raphidiopsis_brookii_D9@ 647109677 CRD_02285 Magnesium and cobalt transport protein CorA [Raphidiopsis brookii D9]
M--------------------NKKHARSGNNRSNRVIDSAKA---------GKSFTQEYY
HQPGTIPGTIIIHEDAQQPQIVLMDYNPTDLVEKRIINPEECSDYLRTQSVSWVDVQGLG
NLDVIHRLGQTFDLHPLILEDVVNMAERPK-IEDYEEQLVIIARMVVPNTNNRSFYSEQV
SLVLGTHYVLTIQEESEHDCFDNVRARINKNKGIIRREKSDYLAYSLLDAIIDGFFPVLE
LYGERIAQLEEEVITNPTSETLKQI--YQVKRELLHLRRGIWPQRDAISSLIRDGSHLIS
QEVSIYLRDCYDHAVQVLDMVENYRELVSGLMDVYMSAVSNKMNEIMKLLTVISSIFIPL
TFVVGVYGMNFSTEKSPYNMPELNWYWGYPFCLGLMAVIAGSLMLFFWRRGWLTNSFEVN
QK
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVI--------ECDRPLISQLKQEP-------------CVYY--SMTVTW-------
----------EYN------EEVIKQDNEGKTIREKERKSETVAQ------NSRSI-----
--------PFTLQDSTG-------EIRVNPERAEIETVK-----------VLEEFRP--E
NFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTA-----------TD
EEGMITIRKPTEKGQRYFISLKSEEEL---------SQATN---------NAIRGTFYSM
IFF---------------------------LTLGLILLVAGVL------RG---------
--
>gnl|BL_ORD_ID|1914 @Synechococcus_CC9605@ gi|78213469|ref|YP_382248.1| protoporphyrin IX magnesium-chelatase [Synechococcus sp. CC9605]
M----------------------TAPRKRRVFPFTAVIGQEEMKLALLLNVIDPRIGGVM
IMGDRGTGKSTTIRALADL-LPDIDVVAGDP-----------YNSSASDPDLQSSEVRER
MQQGETLSTEPRQVPMVDLPLGATEDRLCGTIDIEKALSEGVRAFEPGLLAKANRGLLYV
DEVNLLDDHLVDVLLDSAASGWNTVEREGVSVRHPA-------RFVLIGSGNPEEGELRP
QLLDRFGMSVEVRTVRDPELRVQVVDQRTSFDSDPDGFSTAVEGNQNALQQRVVEAQQRL
DQVTIDEDLRLRISAVCGELDVDGLRGDIVTNRAARALAAFEGRTEVSEEDVARVASCCL
RHRLRKDPLEQVDSGDRVVKVFCKVFERSESSDRADFELALAA
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTI-----SSLQTIANQIAEEIGGGS
LR------EYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREK
ERKSETVAQNSRSIPFT-LQDSTGEIR----VNPERAEIETVKVLEEFRPENFSGGSLTF
GNFSINLPSFEE-------------RRQTIGYRYQEEILPIGRQILVIGTATDEEGMI--
-------------TIRKPTEKGQ-----RYFIS--------------------LKSEEEL
SQAT-----------------NNAIRGTFYSMIFFLTLGL-----------ILLVAG---
---------------------------------------VLRG
>gnl|BL_ORD_ID|2513 @Synechococcus_elongatus_PCC_6301@ 637618204 syc2512_d hypothetical protein [Synechococcus elongatus PCC 6301]
MAAIILAAITAIAAIVLYFVRRHYRFKLQSLLLAQPATSLQLKEIAEHVAGEIGGGNLRQ
YVKMWGAIEVEQPLVSELKQESCVYYCSTVSREYEERVRKEDSEGKVTWTTERRSETISQ
NRRSTPFYLRDQHGRVRVEPESAAIATIPVLDEFRPDS-SASSLIFGAFSLSLSTTAGLG
KTLGYRYREEILPCDRSVLVVGAASDETGELTLGPSSEARQQFFIALKPETALLQEVKQT
IQWLTIGAIASVVVTVVAAIAALL--
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M--ILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLRE
YVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ
NSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERR
QTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNA
IRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1573 @Synechococcus_elongatus_PCC_7942@ gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococcus elongatus PCC 7942]
MAAIILAAITAIAAIVLYFVRRHYRFKLQSLLLAQPATSLQLKEIAEHVAGEIGGGNLRQ
YVKMWGAIEVEQPLVSELKQESCVYYCSTVSREYEERVRKEDSEGKVTWTTERRSETISQ
NRRSTPFYLRDQHGRVRVEPESAAIATIPVLDEFRPDS-SASSLIFGAFSLSLSTTAGLG
KTLGYRYREEILPCDRSVLVVGAASDETGELTLGPSSEARQQFFIALKPETALLQEVKQT
IQWLTIGAIASVVVTVVAAIAALL--
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M--ILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLRE
YVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ
NSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERR
QTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNA
IRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|2245 @Synechococcus_RCC307@ gi|148243345|ref|YP_001228502.1| metal-dependent hydrolase [Synechococcus sp. RCC307]
M-------------------------------------------NPLA------------
----AIELD---LAYLGPDP----------------LGED------RWVELLSSWLAQLQ
AELPSPLKADAYSLGLQFCDDAAIAELNGQWRQQPKPTDVLSFAAQED-APEPLEGLPIE
LGDIVISIPTAERQAPEHGHSLQQELLFLASHGLL--------HLLGWDHPDEASLAAML
SRQDA----------------------------LVQGAAAH
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQ-----------------DSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLT
FGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFI
SLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|661 @Synechococcus_sp_BL107@ 639885299 BL107_15500 Magnesium chelatase ATPase subunit I [Synechococcus sp. BL107]
M----------------------TAPRKRRVFPFTAVIGQEEMKLALLLNVIDPRIGGVM
IMGDRGTGKSTTIRALADL-LPDIDVVAGDP-----------YNSSATDPDLQSSEVRER
LTRNESVATEPRQVPMVDLPLGATEDRLCGTIDIEKALSEGVRAFEPGLLAKANRGLLYV
DEVNLLDDHLVDVLLDSAASGWNTVEREGISVRHPA-------RFVLIGSGNPEEGELRP
QLLDRFGMSVEVRTVRNPELRVQVVDQRTAFDSDPDSFSTAVEANQDALQQRVVDAQQRL
DQVSIDDDLRLRISAVCGELDVDGLRGDIVTNRAARALAAFEGRTEVSEEDVARVASCCL
RHRLRKDPLEQVDSGDRVVKVFCKVFERSEGTDRADFELALAA-----
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTI-----SSLQTIANQIAEEIGGGS
LR------EYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREK
ERKSETVAQNSRSIPFT-LQDSTGEIR----VNPERAEIETVKVLEEFRPENFSGGSLTF
GNFSINLPSFEE-------------RRQTIGYRYQEEILPIGRQILVIGTATDEEGMI--
-------------TIRKPTEKGQ-----RYFIS--------------------LKSEEEL
SQ---------------------------ATNNAIRG-----------------------
-------------------TFYSMIFFLTLGL------ILLVAGVLRG
>gnl|BL_ORD_ID|1898 @Synechococcus_sp_CB0101@ 650129476 SCB01_010100009564 Beta-lactamase-like protein [Synechococcus sp. CB0101]
MSATTAAATTVSLAAAAGGGNLLFRQLFDAATGTFTYLLADVSSRQGVLIDSVFEQHSRD
LSLIHELGIELVASLDTHAHADHVTGSWLMHEATGCAIGLAAAARADNVTLPLHHGDRVP
FGSRFVEVRSTPGHTDGCISFVLDDQSMAFTGDALLVRGCGRCDFQQGNAHTLWSSITEQ
IFSLPDSCLLYPGHDYTGRTVSSVAEEKAFNARLGGAATERDFVGHMQNMKLPHP-----
------------------HKIAEALPGNMRSGKPRQAE-----ARSVWAPVQRSYAGLPE
LSPAWVADHLPELTILDVRAAEELQGPDGHISGSL-----NIPLPDLEQRRQEI------
---PSGKPVVVVCHSGSRSALAT--------QQLL-----KEGIADIAN--LRGGLSRWC
DEGYPL------------AGAVAL
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M----------------------------------------------ILI----------
------------------------------------------------------------
----------------GIICLIV--------GVILLF---------------FWRSNRSK
LRNLRLA---------SASTISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQL
KQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDS-TGEIR
VNPE-------RAEIETVKVLEEFR-PENFSGGSLTFGNFSINLPSFEERRQTIGYRYQE
EILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTF----
---YSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|304 @Synechococcus_sp_CC9902@ Syncc9902_0307 phosphate:acyl-[acyl carrier protein] acyltransferase
M-------------LPKDPDPSQAPEPRSKSTRPRAIRRLVIWYRRNSAVTTIVDSAASS
ASAAGTVAGTVVSGAGTVASSVLQPLVFDPLRRLQGGNDEDEIKDEDRLWVAVDGMGGDD
APGPILEGCLQAIERLPLKIRFVGEQDRVRAAAADLELEAILEKAQASGHLELVPSGPSI
GMDDEATAVRRKRDASINVAMDLVKQGRATAVYSAGNSGAVMASAIFRLGRLKGIDRPAI
GALFPTKDPGQPVLVLDVGANMDCKPTYLHQFALLGNIYSRDVLQVEQPRVGLLNIGEEE
C-----KGNELSLKTFELLKEESRLHFAGNCEGRDVLSGEFDVVVCDGFTGNVLLKFLES
VGSVLL--GVLRSELPRGRRGKVGSAFLISNLKRIKKRLDHAEHGGALLLGVNGIAVIGH
GSSKALSVVSALRIAHSAASHGVMDDLAALQSGCD
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVIL------------------------LFFWRSNRSKLRNLRLASAST
ISSLQTIANQIAEEIG-------------------GGSLREYV-----------------
------------------KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEV-----I
KQDNEGKTIREKERKSETVA----QNSRSIPFTLQDSTGEIRVNP----ERAEIETVKVL
EEFRPENFSGGSLTFGNFSINL---PSFEERRQTIGYRYQEEILPIGRQILVIGTATDEE
GMITIRKPTEKGQRYFISLKSEEELSQATN----NAIRGTFYSMI-----------FFLT
LGLILLVAGVLRG-----------------------------------------------
-----------------------------------
>gnl|BL_ORD_ID|170 @Synechococcus_sp_JA_2_3B_a2_13@ 637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba(2-13)]
MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPPPE
RKAFMNWLMLLGLLCLPASLF------SFVEYLRSQRLVQQLSATRLLKIAELRHLGQTN
PQAKGANL---AQVYGRVVCDRPLVSELSRQPCVYYKSEISWEYDEIECYRRYLNSRGDV
AYSERISEGEYQNALRLGSRAKSYPGEMVGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPN
PGYPQQLGSPGYPQKSPFSEVSSPQKHYANVYYDPSTGREYLLERETRTRDETLHSVVRQ
IPFFIEDETGRVRVDPTGAEIEAMSVVDE---HIFPGKGPS--RFNFNLKRYLSGVRTEN
RSTRAFIYKEWVIPVDAMAFTMGQVRFEAGDPVIRKPL-SGERFMIAPKSPEALLEEQRS
NASSYLVGSVVLLGIGIFTVLH-LLQSLQPYR
>gnl|BL_ORD_ID|170 @Synechococcus_sp_JA_2_3B_a2_13@ 637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba(2-13)]
MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPPPE
RKAFMNWLMLLGLLCLPASLF------SFVEYLRSQRLVQQLSATRLLKIAELRHLGQTN
PQAKGANL---AQVYGRVVCDRPLVSELSRQPCVYYKSEISWEYDEIECYRRYLNSRGDV
AYSERISEGEYQNALRLGSRAKSYPGEMVGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPN
PGYPQQLGSPGYPQKSPFSEVSSPQKHYANVYYDPSTGREYLLERETRTRDETLHSVVRQ
IPFFIEDETGRVRVDPTGAEIEAMSVVDE---HIFPGKGPS--RFNFNLKRYLSGVRTEN
RSTRAFIYKEWVIPVDAMAFTMGQVRFEAGDPVIRKPL-SGERFMIAPKSPEALLEEQRS
NASSYLVGSVVLLGIGIFTVLH-LLQSLQPYR
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
-------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIAN-----QIA
EEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNE--------------
------------EVIKQDNEGKTI------------------------------------
--------------------------------------------REKERKSETVAQNSRS
IPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSF-----EER
RQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNN
AIRGTFYSMIFFLTLGLILLVAGVLRG-----
>gnl|BL_ORD_ID|357 @Synechococcus_sp_JA_3_3Ab@ 637871966 CYA_0374 glycosyl transferase, group 2 family protein [Synechococcus sp. JA-3-3Ab]
M--------YISVIIPTY---NRRPILQ---------KCLQALAQQ---QPGPYDGYEVV
VVDDGSTDGTLEWLQSQPPDLPPIRLLCQEHRGPAAARNLGFRHAQGSIIVFIDSDLVVV
---EHFLAAHAQMLRRHGVTGNPDSPHEAKVFTYGRVINTCNFRDPCSEPFKPTDFSAAF
FATGNVAIARHWLERACETPAGPFDERFHLYGWEDLELGVRLKRLGLRLVKCPQATGYHW
HPPFELAQIPALIERERQRGRMGILFYQKHPTWAVRLMIQLTPLHQCLWGLLSLGGWLNE
KRLEPLLRWLIRQGRSQLALELCRVFFLNWYNVQAVYESYRAMKARNTGIHLF
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KI-----RGVIEC------DRPLISQLKQE---PCVYYSMTVTWEYNEEVIKQDNEGKTI
REKERKSETVAQNSRSIPFTLQ-DSTGEIRVNPERAEIETVKVL----EEFRPENFSGGS
LTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRY
FISLKSEEELSQATNNAIRG----TFYS--------------------------------
-----------------------MIFFLTLGLILLV-----------AGVLRG
>gnl|BL_ORD_ID|3095 @Synechococcus_sp_PCC_7002@ 641612991 SYNPCC7002_F0019 hypothetical protein [Synechococcus sp. PCC 7002]
MSVL-------------------------------------------------------I
KAKGKIE-------------------------NGQLV--------------------LDA
ATAPF------------PRDGEVEVMVILKENQSANFSEVDLSIKDAAINIYDQTLDLIQ
NVKREKAEKNIILSIEDIRAGIRDRSGFRTAEEI--------------------------
---DAYL----QEERAS-----------------------------WDD
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSIN----------
-----------LPSFEERRQTI----GYRYQEEILPIGRQILVIGTATDEEGMITIRKPT
EKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|5086 @Synechococcus_sp_PCC_7335@ 647581342 S7335_1031 transposase [Synechococcus sp. PCC 7335]
MKRQWDTEELIEQFTLMPSELALLPEEITNATAHNRLGFAILLKFFQVEGRFPQHAGEVP
KVITNFIAQQLALSEADYRQYKWSGRTVKTHRSQIRTFLGIRPMRQSDQQELKRWLIAEI
LPLGLSFEALKAQAYGQLRQLKIEPPTAKGLERLIRSAARLHERSFCKQIAAQLSAKTRA
SINALLNTESPLEDENSQFRQSQLSYLKTDPGRLGLNSLLKEIEKLQRTRELELPSAFFN
HVVPKLVQQYRRRASTEPPRELRRHPPAIRYTLVAAFCWQREREIIDDLVTLLIQIIHRL
SISAERRVERELIASFKRVNRKEALLLKIATASLKQPEGTVRDVVYPVANPETLQSLIDE
QSAGETYHEKVHTRIRASYLHHYRRMVPAILDALSFHSNNEQHQPVVYALAILKRYQDSN
RRFYDEDETL-----VIEGVLPTHWPELIGETDSNGEVRINRVNYEICVLQALREKLRAR
AVWVVGAGRYGNPEQDLPQDFEAHREVY---YQELSQPLEAAAFIQQLKQTMQAELSQLN
QGMPKNKGVRIQTRKHGWISVSPVEAQPEPPNLLKLKAEITRRWPLTGLLEMLKETDLRV
NFTEQFESAATRENLDRNTLQRRLLLCLYGLGTNTGLKRVCAGIDNENYNNLLYVKRHYI
HKEHLRNAIAKVVNAVLRSRLETVWGEGTSACASDSKKFGAWDQNLMTEWHQRYGGLGVM
IYWHVEKKSVCIYSQLKTCSSSEVASMLEGLLRHNTEMKVERNYVDTHGQSEIAFAFCHL
LGFNLMPRLKRIGAQRLYFPEVGTKATYQNLQPVLSRAIDWDLIRRQYDQLIKYATALRL
GTAETEVILRHFNRSETKHPTYQGLAELGRAVKTIFLCRYLHSVELRQEIQDGLNVVERW
NGANDFIFYGRSGEFASNRRAHQELAALALHLLQISLVYINTLMIQRVLSEPRWWAQMQP
EDLRALTPLLWNHVTPYGVFRLDFSDRIDLEPVGSALSSA
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ILIGIICLIVGVI---
------------LLFFWRSNRSKLRNLRLASAS-------------------TISSL---
----QTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEV
IKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVL-EEFRPE
N-FSGGSLTFGNFSINLP-SFEERRQTIGYRYQEEILPIGRQILV---IGTATDEEGMIT
IRKPTEKGQRY------FISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLR-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------G
>gnl|BL_ORD_ID|1081 @Synechococcus_sp_RS9916@ 639888288 RS9916_36147 probable O-succinylbenzoic acid--CoA ligase [Synechococcus sp. RS9916]
M--PDPQALLSHCRAMPLW---RSKPRVVSLVP--------------------------T
QLRRLLD----------------HSAGVHWLRDLDVIWVGGAALLI--------DLADRA
RAL---------EVRLAPCYGATETAAMVAAQSPERFLAGEQSYGT---ALGDVELRLES
SGARLVRTLRLAIGRWREGALQPLVDGNGWWRSGDGASLEWAADGKSLLTMHGRLDDAIH
SGGETVFPDQLAQRLLRKAHADGCALDGVLFFPVDHPEWGQRLVALVRCREGCLATDQWH
QVQSCLEGLTRDWLPAERPSRWLQCPDLDVTDAGKWERKRWQAWVGLQ
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEI-LPIGR------QILVIGT-------------ATDEEGMITIRKPTEK---
--GQRYFISLKSEEELSQATNN--AIRGTFYSMIFFLTLG--LILL--------------
-VAGVLRG----------------------------------------
>gnl|BL_ORD_ID|2410 @Synechococcus_sp_WH5701@ 638960193 WH5701_07371 hypothetical protein [Synechococcus sp. WH5701]
MQARLRWIALTKAVPLAISRGTTASVRRLVVELEHEGLVGRGEAGGFETGHRAYATEAVA
AELEALLPRFASAEGLALAAELPAFQALDPWLSPLSPPARCAIDLALHDWWGQKLGQSLW
RLWGLDRAACSPTSVTLGLAGVGQVLARLDRWQDRLGCWPQRVKLKLGSPDGPGHDRALV
LAVVQRLQERADAAGMVSELQVDANGGWDLVTAQQLIPWLAEQGVVLVEQPLPAQLDPE-
----------------------------ADAASFAALDLSCPIPLVADESCWNLSDLLRL
APHVDGV-NIKLLK-------SGGLSEALLMAQTARSLGLDLMLGCYSDSALLNGAASQL
LPLVRWPDLDSHLNLIDDPFEGPELQADCLLPSNRPGL---------GVIELSGPT----
---------------------------------------AASAPC
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI-----------------------------------LIG--------------------
--------------------------------------IICLI-----------------
---------------------VGVIL--LFFWRS------NRSKLR--------------
-------NLRLASASTISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEP
CVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDS----TGEIRV
NPERAEIETVKVLEEFRPENFSGG----------------SLTFGNFS------------
---INLPSFEERRQTI-----GYRYQEE-ILPIGRQILVIGTATDEEGMITIRKPTEKGQ
RYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|237 @Synechococcus_sp_WH7805@ 639019560 WH7805_12228 hypothetical protein [Synechococcus sp. WH7805]
MPHPLLPDITSVAAAT----------AAAQGFELAGIQILTHLQPMTVQVQIRRSDGS--
-DVSLDDCAGFSRPMGEALESQALLTEAYVLEISSPGIGDQLQSDRDFQTFRSYPVEVLY
RDNEGRELRQQGSLLERDNDHVHVNVR----------GRIK-------------------
-------------RISRPS------------------------VIS--------VQLISP
T------------------------------------------------S
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M---ILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLR
EYVKIRGVIECDRPLISQLKQEPCVYYSMTVT-------------------WEYNEEVIK
QDNEGKTIREK----ERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRP
ENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKP
TEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1169 @Synechococcus_sp_WH_8109@ 647835886 SH8109_1201 magnesium chelatase ATPase subunit I [Synechococcus sp. WH 8109]
MLV--------------------TAPRKRRVFPFTAVIGQEEMKLALLLNVIDPRIGGVM
IMGDRGTGKSTTIRALADL-LPDIDVVAGDP-----------YNSSASDPDLQSSEVRER
MQQGETLSTEPRQVPMVDLPLGATEDRLCGTIDIEKALSEGVRAFEPGLLAKANRGLLYV
DEVNLLDDHLVDVLLDSAASGWNTVEREGVSVRHPA-------RFVLIGSGNPEEGELRP
QLLDRFGMSVEVRTVRDPELRVQVVDQRTSFDSDPDGFSTAVEGNQNALQQRVVEAQQRL
DQVTIDEDLRLRISAVCGELDVDGLRGDIVTNRAARALAAFEGRTDVSEEDVARVASCCL
RHRLRKDPLEQVDSGDRVVKVFCKVFERSESSDRADFELALAA
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTI-----SSLQTIANQIAEEIGGGS
LR------EYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREK
ERKSETVAQNSRSIPFT-LQDSTGEIR----VNPERAEIETVKVLEEFRPENFSGGSLTF
GNFSINLPSFEE-------------RRQTIGYRYQEEILPIGRQILVIGTATDEEGMI--
-------------TIRKPTEKGQ-----RYFIS--------------------LKSEEEL
SQAT-----------------NNAIRGTFYSMIFFLTLGL-----------ILLVAG---
---------------------------------------VLRG
>gnl|BL_ORD_ID|711 @Synechococcus_WH_7803@ gi|148239048|ref|YP_001224435.1| flavoprotein related to choline dehydrogenase [Synechococcus sp. WH 7803]
MIIDDRHYDIIVIGSGAGGGTLAGALSRQGRRVLLLERGGAMALSDQNVADVDLFRKDRY
HPRNERWFGPDG----DPIAPQTTYALGGNTKIWGAVLERMREKDFDDLPLQNGISPRWP
FNYQHLAPFYDQAEHLYQVHGKSGVDPTEPARNGDFGHAPKPLMPFLEPLREGLKRQGCQ
PYDLPLSWSSSQEDPSGDAQLYGLDNADSEKLEVRSMARVM---------RLHVNPSGRE
VKAVEADVDGETWLFSADVVVLAAGAINTAA-------ILLRSSSEKHPRG-----LSNG
SDQVGRNLMN----------LQLTSILQLAAERNNGRYARSLGVNDYYWGDKNVSFPLGH
IQAAGGVLQDALFAESPPVLSLVSKLIPDFGLERLASRSVAWWAMTEVLPDPHNKVWLNN
DQIRINYLHNNREAHDRLVYRWIDTLTAVEADPITKVVTKAPTHPRGEAPLSVVGYACGT
CRMGDDPAASVVDGDGRSHELDNLYIADSSVFPSCPSVGPGLTTIALALRMSEALKQRFD
G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL----IGIICLIVGV---------------ILLF-----------------FWRSNRS
KLRNLRLASASTISSLQTIANQIAEEIGGGS---------LRE-----------------
---------------YVKIRGVIECD---------------------RPLISQLKQEPCV
YYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAE
IETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTA
TDEEGMITIRKPTEKGQRYFISLKSEEELSQATNN-------------------------
--AIRGTFYSMIF-----------------------------------------------
------------------------------------------------------------
-----------------------------------------FLTLGLILLVAGVLR----
G
>gnl|BL_ORD_ID|1632 @Synechococcus_WH_8102@ gi|33866171|ref|NP_897730.1| hypothetical protein SYNW1637 [Synechococcus sp. WH 8102]
MVVGGSPEGARPHLDVPPRLMASTESLTTLAAELATADDLELLQGAADLQRYSKDAYDYS
PILQPQLESCRADLVVRPLTVAGVERLAAACGRHGVPLTLRGSGTGNYGQSVPLEGGVVM
LSGALREVEHLDPSTGVVMVQPGCLMRDLDQHLRAHGRQLRLLPSTWRSA--SIGGFLAG
GSGGIGSIRWGFLRDPGHLLGAELITVEREPRRLQLDATEAEALNHAYGTNGILTRLQLA
TAPAVNWHQISIDVETWGAAVALLQRCTRSAVELHLATLLERSVLQCLPAWSGPESDRHR
LLLLVAPDGVSTLARLAAASGAVLHDLGPEDLGGGQ-GLRDLSWNHTTLHKRSEDAGWTY
LQMLLPEPELPAMEQLKQRWGDALLWHLEGVRQQGAARLAALP-------LVRWSSTEQL
DALMRDCRE---VGAVLFNPHVITVEDGGLGVVDGDQVAAKHRYDPEGLLNPGKLRGWLE
SISSPGCPGSPHLSRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL---------------------------------------------------------
------------------------------------------------------------
--------------IGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAE
EIGG------GSLREYVKIRG--VIECDR-PLISQLKQEPC---------------VYYS
MTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ------NSRSIPFTLQDSTGE------
--IRVNPE------RAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRY
QEEILP-------------IGRQILVIGTATDEEGMITIRK-PTEKGQRYFISLKSEEEL
SQATNNAIRGTFYSMIFF----LT-----LGLI---------------LLVAGVL-----
--------------RG
>gnl|BL_ORD_ID|3565 @Synechocystis_sp_PCC_6803@ 637472195 slr6106 hypothetical protein [Synechocystis sp. PCC 6803]
MRFNDSGSDDDNSLERIKIEDKNISDLNLFNSVSSFVVDNKEIQEKIRYATNSISKTIEF
EKRISLPTIENIQQSFLGIISAEELIKLITDSSNNILRGIFYDNVRDFQGDNEVNTEISN
TIQSSFQDLFVLLNNGITIVAEHASQISSKL---TIEGFQVVNGCQTCHVLYNNKNLIND
KIYISLKI-------IVSDDNDVKTRIIKATNQQTVVKKEELIAIT--DFQKELESYYE-
AQPEEYRLYYERRSKQYASLTNIEKVRIITIPLQIKAFSSMFLDYAH---LAGRYHANLL
TSVNDNIFIN----THQKIAYYVSAYASYKIDYLLRNKQIDKKYNPFKYIILMGINLYLS
EHKKTNNISSKKFASYCEIIKENLWDDDKLTTMISQIINNINHITQTDLDRSYAKTRSFI
DTFKDKFK
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
--------------ILIGIIC------LIV----GVILLFFWRSNR--------------
---SKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEP
CVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPER
AEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIG
TATDEEGMITIRKPTEKGQRYFISLKSEEELSQ-ATNNAIRGTFYSMIFFLTLGLIL---
--------------------------------LVAGVLRG--------------------
--------
>gnl|BL_ORD_ID|658 @Thermosynechococcus_elongatus_BP_1@ 637313275 tll0660 hypothetical protein [Thermosynechococcus elongatus BP-1]
MGVLGGILLVIAVLVLCGWWDYRLKVRALNLAVSSTPAQLHELQRRVAQEIGGGYLQEYV
KISGQIVADRPLVSELKRLPCVHYRLCVSRVYKTTESHEDGSSET----KYRHEILSSNT
QTIPFRLRDGDMEIYVDPRGAEIETVQVLNEFQEDN-NTTHLAFGRFQMDLSSLPKHSDT
VGYRYEEWILPVNQQVFVVGTASDERGKLRIRRPHQKGQLFFISLESEENLTKKVRQYAR
ASIIAAGVFSGLGILLILL-----
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>gnl|BL_ORD_ID|1914 @Trichodesmium_erythraeum_IMS101@ gi|113475857|ref|YP_721918.1| unnamed protein product [Trichodesmium erythraeum IMS101]
MIKKFQSSFNRILLSRILLLTISGLVLGQYIIY--RQARSTFLNTARQNLKESADRKAEY
LQQWATSLKSSLVSAS-ESYVLESGTVEEHQSYIKRLDEMLSTQISCVQLSNLRTEEIVA
NTCGTERIDSLPENIWPQQQKQLFRDKYNIYVSYSILELLSADSESNGQKVNQKTQVSLV
WSVPVYVSEA-GERKL---RYALSIKSALP--MPTNRERGSFTGSTVVINVPEYRILASL
DSRK-------------LGRRISELSDTQTAKKLESIMKKAEEGQKHFAHIFSIEETDIL
SKNQGSDRSKNTFREIIDKLKEILPKLLRLKLSEDNEFLAGYVAIPSPIDRDNDKVWVVL
AITPIDFALSGLREVQKVLIILILFLLGASIIASIFLARDLAIPLKKLRDYAITLNDLNA
PSKVPQDLKIPEFNQLAVSLQKMVERLNRWADKIEVASKEAQVANQLKSEFLANISHELR
TPLNGIIGSLQIIYDGFCDTREEEIQFLKQANDSAIHLLRIIDDILDIRKIDARNLYMTF
ENINIIKLLEETVDIFRYDLEQKSLVLKLNASEEKILVYVDKKELQKVFENVISNAIKFT
EKGNIDISICRKYNQCIFSENQNNLVNAHTHKVNQVLVTIQDTGIGIDPEEQDKLFQPFV
MVDGTKTRKFGGNGLGLAMARGLVEMMNGNIHLYSEGIGRGTTVYITIPIQERLSLEKKQ
DISTEIKLN
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656  gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------------LIGIICLIVGVILLFFWRSNRSKL-----RNLRLASASTISS
LQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQL-----KQEPCVYYSMTVTWEYNE
------------EVIKQDNEGKTIREK-----------------ERKSETVAQNSR----
-SIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLP------SF
EERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQA
TNNA----IRGTFYSMI-------------------------------------------
--------------------------------------------------FFLTL-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GLI--------LLVAGVLRG-------------------
---------
