>Arabidopsis_thaliana_gi|30696917|ref|NP_176574.2| E3 ubiquitin ligase-like protein [Arabidopsis thaliana]gi|22135946|gb|AAM91555.1| putative RING zinc finger protein [Arabidopsis thaliana]gi|23197600|gb|AAN15327.1| putative RING zinc finger protein [Ar
--MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELD-SKILPFIV
AVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLD
DGTSRVHVMGARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFT
VLGVFLITKHVIDSV-------LERRRRRQLQK----RVLDAAAKRAELESEGSNGTR--
-------ESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRR
RIDLAVKTYR------------------------------H
>Arabidopsis_thaliana_gi|6520214|dbj|BAA87953.1| ZCF61 [Arabidopsis thaliana]
------------------------------------------------------------
-----------------------------------------------MQPMTKEVPWYLD
DGTGRVNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGYLKGFK----ILGVRHVERV
VPIGTPLTVVGEAVRDGMGNVRIQKPEQGPFYVTYIPLDQLISKLGDLSRRFKYASMGLT
VLGVILISKPVIEYILKRIEDTLERRRRQFALK----RVVDAAARRAKPVTGG-------
------------GTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCSLQLRTCPLCRE
RIQQVLKIYR------------------------------H
>Arabidopsis_thaliana_gi|8778741|gb|AAF79749.1|AC009317_8 T30E16.12 [Arabidopsis thaliana]
--MIHLAGFTCCLGGVALYLLTRSTGR---DIKSITRVYQLKDLEQLVEVE-SKVVPLII
AVSGDVGSETPIKCEHSYVLGVFLKRTAEQQVLRRNWRFSWVRNSTLMQPMTKEVPWYLD
DGTGRVNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGYLKGFK----ILGVRHVERV
VPIGTPLTVVGEAVRDGMGNVRIQKPEQGPFYVTYIPLDQLISKLGDLSRRFKYASMGLT
VLGVILISKPVIEYILKRIEDTLERRRRQFALK----RVVDAAARRAKPVTGG-------
---------SNSGTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCSLQLRTCPLCRE
RIQQVLKIYR------------------------------H
>Arabidopsis_thaliana_gi|18406385|ref|NP_564745.1| E3 Ubiquitin ligase family protein [Arabidopsis thaliana]gi|14475949|gb|AAK62796.1|AC027036_17 hypothetical protein [Arabidopsis thaliana]gi|30102702|gb|AAP21269.1| At1g59560 [Arabidopsis thaliana]gi|1
--MIHLAGFTCCLGGVALYLLTRSTGR---DIKSITRVYQLKDLEQLVEVE-SKVVPLII
AVSGDVGSETPIKCEHSYVLGVFLKRTAEQQVLRRNWRFSWVRNSTLMQPMTKEVPWYLD
DGTGRVNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGYLKGFK----ILGVRHVERV
VPIGTPLTVVGEAVRDGMGNVRIQKPEQGPFYVTYIPLDQLISKLGDLSRRFKYASMGLT
VLGVILISKPVIEYILKRIEDTLERRRRQFALK----RVVDAAARRAKPVTGG-------
------------GTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCSLQLRTCPLCRE
RIQQVLKIYR------------------------------H
>Oryza_sativa Japonica Group_gi|115473747|ref|NP_001060472.1| Os07g0647800 [Oryza sativa Japonica Group]gi|113612008|dbj|BAF22386.1| Os07g0647800 [Oryza sativa Japonica Group]
-MLIPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSTKDLAAILDTA-SKVLPLVV
AVSGRVGSDTPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLD
DGTGRVFVVGARGAAGLVLTVASEVFEESGR-TLVRGTLDYLQGLK----MLGVKRTERV
LPTGTSLTVVGEAIKDDVGTIRIQRPHKGPFYVSPKSIDQLIMNLGKWAKLYQLASMGFA
AFGVFLLAKRALQHF-------LERKRRHELQK----RCVLTNHLFGFRRT---------
--------------------------CYSHLHSSVV------------------CSLC--
-----------------------------------------
>Medicago_truncatula_gi|144924893|gb|ABE86663.2| Zinc finger, RING-type [Medicago truncatula]
MAMVPWRGVGCCLSAAALYLLGRTSGRDVDILKSVNRVNQLRELAQLLDE---EIFPLVV
AISGRVGSETPISCEFSGLRGVIIEETAEQHFLKHSDAGSWIQDSALMQSRSNEVPWYLD
DGTGRVRVVGAQGATGFVLPVGSEAFEESGR-LPVRGTSDYVQGLK----MLGVKRIERV
LPVGTSLTVVGEAAKDDVGTIRIQRPSKGPFYVSPKTIDELIANIGRWARWYKYASAGLT
VLSVYMIANHAVRYI-------LERRRRNELEK----RVLAAAAKISGQDNGG--EMD--
-------DSLSDGAKRERAMPNLCVICLEQEYNSVFVPCGHMCCCTACSSHLTSCPLCRR
QIEKAVKTFR------------------------------H
>Vitis_vinifera_gi|225436896|ref|XP_002274008.1| PREDICTED: hypothetical protein [Vitis vinifera]gi|296086688|emb|CBI32323.3| unnamed protein product [Vitis vinifera]
--MIPWGGISCCLSAAALYLLGRSSGRDAEALKSVTRVQQLKDLVQLLDTA-CKVLPLVV
TVSGRVGSDTPIKCEYSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLD
DDTGRAYIVGARGATGLVLTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGTPLTVVGEAIKDDVGTIRIQRPHKGPFYVSPKSIDHLVANLGKWARWYRYASLGFT
VFGVYLIAKSAIQYV-------MERKRCWELRK----RVLAAASKKSGQDSEDPDEKD--
-------ENGSDNTKRDRLMPDLCVICLEQEYNAVFVPCGHMCCCTMCSSQLTNCPLCRR
RIEQVVRTFR------------------------------H
>Populus_trichocarpa_gi|118486812|gb|ABK95241.1| unknown [Populus trichocarpa]
------------------------------------------------------------
-----------------------------------------------MLSMSKEVPWYLD
DGTDRVYVVGARGASGFVLTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKSIDELIGNLGKWARWYKYASLGLT
VFGAFLITKHVIRYI-------MERRRRWELQS----RVL-AAAKRSGQDNEGSNDKA--
-------ENGSDGAKRERPIPDLCVICLEQEYNAVFLPCGHMCCCITCCSQLSNCPLCRR
RIEQVVKTFR------------------------------H
>Physcomitrella_patens subsp. patens_gi|168043801|ref|XP_001774372.1| predicted protein [Physcomitrella patens subsp. patens]gi|162674364|gb|EDQ60874.1| predicted protein [Physcomitrella patens subsp. patens]
--MLSWGGITLCFSGAALYCLSRNTGRDALHLMSVERVNQLEDLAKLLESA-CTVVPWVV
TVAGRVGAEAPIASEHSSLRGVILEKSAEQHFLKHNDTGSWIQHSALMLSISKEVPWYLE
DGTSRVFIIGARNAAGMDLTVASESFEEYGG-SLVRGTLDYLQGLK----MLGVKRVERV
LPTGTNLTVVGEAVQDDRGLIRIQKPDKGPFYVTPQSQDQLIENLGRWSRWCQYMSFGLT
LVGIYFITSRAIKHM-------LERWRREALLT----RVMEAAALRKALQQEGVDEESDG
VTAFPHDDNAHTAQKKDGGMPSLCVICLEQDYNAVLVPCGHMCCCTSCSSQLSLCPLCRR
HIDQVVKTFR------------------------------H
>Physcomitrella_patens subsp. patens_gi|168002970|ref|XP_001754186.1| predicted protein [Physcomitrella patens subsp. patens]gi|162694740|gb|EDQ81087.1| predicted protein [Physcomitrella patens subsp. patens]
--MLSWGGITLCLSGAALYCLSRNTGRDALNLRSIERVNQLKDLAILLESA-CKVVPLVV
TVAGRVGSETPIACEHSSLRGVILEETAEQHFLKHNDTGSWIQDSALMLSISKEVPWYLE
DGTGRVYIVGARNAAGMELTVASEVFEESGR-SLVRGTLDYLQGLK----MLGVKRVERV
LPTGTNLTVVGEAVQDDRGLIRIQKPNKGPFYVTPKSLDQLVANLGRWSRWYKYMSLGFT
IVGIYFITSHAIKHF-------MERRRREALHR----RVMEAAALRQASQREGGDGDMGD
VTSHPLDDSVDTSQKKDRGTPDLCVICLEQDYNAVFLPCGHMCCCTSCSAQLTSCPLCRR
HIDKFVKTYR------------------------------H
>Oryza_sativa Indica Group_gi|218200138|gb|EEC82565.1| hypothetical protein OsI_27112 [Oryza sativa Indica Group]gi|222637570|gb|EEE67702.1| hypothetical protein OsJ_25368 [Oryza sativa Japonica Group]
-MLIPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSTKDLAAILDTA-SKVLPLVV
AVSGRVGSDTPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLD
DGTGRVFVVGARGAAGLVLTVASEVFEESGR-TLVRGTLDYLQGLK----MLGVKRTERV
LPTGTSLTVVGEAIKDDVGTIRIQRPHKGPFYVSPKSIDQLIMNLGKWAKLYQLASMGFA
AFGVFLLAKRALQHF-------LERKRRHELQK----RVHAAAAQRQAREAEGGNGTS--
--------DVDSNNKKDQLVLDICVICLEQEYNAVFVPCGHMCCCMNCSSHLTNCPLCRR
RIDQAVRTFR------------------------------H
>Zea_mays_gi|219884603|gb|ACL52676.1| unknown [Zea mays]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MLGVKRTERV
LPTGTSLTVVGEAIKDDVGTIRIQRPHKGPFYASSKSIDQLIVNLGKWAKLYRIASMGFA
TFGVFLLAKRALQHF-------LERRRRHELQK----RVLNAAAQRQAREAEGSKGTS--
--------DAEPNSKKDQLVLDICVICLEQEYNAVFVP----------------------
-----------------------------------------
>Populus_trichocarpa_gi|224131332|ref|XP_002321058.1| predicted protein [Populus trichocarpa]gi|222861831|gb|EEE99373.1| predicted protein [Populus trichocarpa]
--MIPWGGISCCLSGAALYLLGRSSGR---YLPSLIPLFFLIISSKLLDIE-SKVLPLVV
AISGRVGAESPISCEFSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLD
DGTDRVYVVGARGASGFVLTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKSIDELIGNLGKWARWYKYASLGLT
VFGAFLITKHVIRYI-------MERRRRWELQS----RYVSLVEGIHDKMFQG-------
-------KGHANGAKRERPIPDLCVICLEQEYNAVFLPCGHMCCCITCCSQLSNCPLCRR
RIEQVVKTFR------------------------------H
>Ricinus_communis_gi|255567656|ref|XP_002524807.1| zinc ion binding protein, putative [Ricinus communis]gi|223535991|gb|EEF37650.1| zinc ion binding protein, putative [Ricinus communis]
------------MRNAEYSKTTFGKGLDAEALKSVTRVNQLNELAKLLDIE-SKVLPLVV
AISGRVGSETPINCEYSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLD
DGTDRTFVVGARGASGFALTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGTSLSVIGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELIGNLGKWARWYRYASVGLT
VFGVFLIAKHAIQYI-------MERRRRWELQS----RVLAAAAKRQGQDSDGSNGKA--
-------ENGSDSSKRERPIPDLCVICLEQEYNAVFLPCGHMCCCTACSSHLTNCPLCRR
RIEQISASIPVKDSCQGTDFLFHPRIRCKILPIAAIAYNWK
>Zea_mays_gi|238014506|gb|ACR38288.1| unknown [Zea mays]
------------------------------------------------------------
------------------MRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLD
DGTGRVYVVGARSAAGLILTVASEVFEESGR-TLVRGTLDYLQGLK----MLGVKRTERV
LPTGTSLTVVGEAIKDDVGTIRIQRPHKGPFYASSKSIDQLIVNLGKWAK----------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Sorghum_bicolor_gi|242051098|ref|XP_002463293.1| hypothetical protein SORBIDRAFT_02g041380 [Sorghum bicolor]gi|241926670|gb|EER99814.1| hypothetical protein SORBIDRAFT_02g041380 [Sorghum bicolor]
-MMIPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKDLAAILDTA-SKVLPLVV
AVSGRVSSDTPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLD
DGTGRVYVVGARSAAGLILTVASEVFEESGR-TLVRGTLDYLQGLK----MLGVKRTERV
LPTGTSLTVVGEAIRDDVGTIRIQRPHKGPFYVSPKSIDQLIMNLGKWAKLYRLASMGFA
TFGVFLLAKRAIQHF-------LERKRRHELQK----RVLNAAAQRQAREAEGSNGSS--
--------DTEPNSKKDQLVLDICVICLEQEYNAVFVPCGHMCCCMACSSHLTNCPLCRR
RIDQAVRTFR------------------------------H
>Arabidopsis_lyrata subsp. lyrata_gi|297821220|ref|XP_002878493.1| predicted protein [Arabidopsis lyrata subsp. lyrata]gi|297324331|gb|EFH54752.1| predicted protein [Arabidopsis lyrata subsp. lyrata]
--MIHLGGLTCCVSGGVLYLLSMIPGSFFEMLNSVTRVHQIKDLENLLQVE-GK----II
AVSG----------------------TAQQLFLKRNWLFSWVEDSKWMLPQAKEVPWYL-
--------------------------------------------------MLGVRRTEHV
LPIGTPVTVVGEAVKDGIRGFRIQKPEKGLFFVSPVPLDKIISPMGKWLRRFKYVYVGLT
VVGVILISKPVIEYI-------LERRRGRLLRK----RVADAAAKRAKLVARGLETQH--
-------ENSLDSTSRDRDVLDLCVICLEQKYDATFVKCGHMCCCLTCSLHVKTCPICRR
PIEHVLKIDR------------------------------R
>Arabidopsis_lyrata subsp. lyrata_gi|297840101|ref|XP_002887932.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]gi|297333773|gb|EFH64191.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]
--MIPWGGVTCCLSAAALYLLGRSSGRDAEVLKTVTRVNQLKELAQLLELD-SKILPFIV
AVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLD
DGTSRVHVMGARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSPKSLDQLISNLGKWSRWYKYASMGFT
VFGVFLITKHVIDSV-------LERRRRRQLQK----RVLDAAAKRAELESEGSNGAR--
-------ESIADSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRR
RIDLAVKTYR------------------------------H
>Arabidopsis_lyrata subsp. lyrata_gi|297840639|ref|XP_002888201.1| hypothetical protein ARALYDRAFT_338432 [Arabidopsis lyrata subsp. lyrata]gi|297334042|gb|EFH64460.1| hypothetical protein ARALYDRAFT_338432 [Arabidopsis lyrata subsp. lyrata]
--MIHLAGFTCCLGGIALYLLSRNTGG---VVKSITRVNHLKDLEQLVE---SKVFPLII
AVSGIVGSETPIKCEHSDILGVFLKKTAEQQVLSRNWRFSWVRKSTLMQPMTKEVPWFLD
DGTGRVNVAVSQGEIGLALTVGSDVFEKAEPVSLVQGTLDYLKGLK----ILGVRRVEHV
VPIGTPLTIVGEAVKDGMGNVRIQKPEQGPFYVSYVPLDQLISKLGEWSRRFKYASMGLT
VVGVILLSKPVIKYILKKIEDTLERRRRQLLQK----RVV--------------------
------------------DVPDLCVICHDQKYNTAFVQCGHMCCCLTCSLRLTTCPLCRE
QIQQVLKIYR------------------------------H
>Selaginella_moellendorffii_gi|302772771|ref|XP_002969803.1| hypothetical protein SELMODRAFT_231449 [Selaginella moellendorffii]gi|302806814|ref|XP_002985138.1| hypothetical protein SELMODRAFT_234706 [Selaginella moellendorffii]gi|300146966|gb|EFJ13632.
--MLPWGGITMCLSGVALYFLSRNSGRDAATLKAVRRVDQLKDLAHLLDSA-CKAVPLVV
TVAGRVGSETPIGCDHSSLRCVILEETAEQHFLKHNDTGSWIQDSALMLSNNKEVPWFLE
DASGRVFIVGARGAAGLELTIASEVFEESGR-SLVRGTLDYLQGLK----MLGVKRVERV
LPTGTALTVVGEAIKDDQGTLRIQRPHKGPFYVTPKSIDQLIANLGKWSRWYKYMSLGFT
LFGVFLVASHTIRYV-------MEKRRRAALNR----RVMEAAARRRERKEHEGKAQVGE
F------AKVETATKRDGRLPDLCVICLEQEYNAVFVPCGHMCCCISCSAQLQNCPLCRR
RIEQIVKTYR------------------------------H
>Thellungiella_halophila_gi|312283085|dbj|BAJ34408.1| unnamed protein product [Thellungiella halophila]
--MIPWGGVTCCLSAAALYLLGRSSGRDAEVLKTVTRVSQLKELAQLLELDSSKLLPFIV
AVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLD
DGTSRVNVVGARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGMPLTIVGEAVKDDIGDLRIQKPERGPFYVSPKSLDQLISNLGKWSRWYKYASMGLT
VFGVFLITKHVIDSV-------LERRRRRELQK----RVLDAAAKRAERESEGSNGTH--
-------ESVSDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSCHLTSCPLCRR
RIDQVVKTYR------------------------------H
>Arabidopsis_thaliana_gi|334183615|ref|NP_001185305.1| E3 ubiquitin ligase-like protein [Arabidopsis thaliana]gi|332196044|gb|AEE34165.1| E3 ubiquitin ligase-like protein [Arabidopsis thaliana]
--MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELD-SKILPFIV
AVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLD
DGTSRVHVMGARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFT
VLGVFLITKHVIDSV-------LERRRRRQLQKSCFCRVLDAAAKRAELESEGSNGTR--
-------ESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRR
RIDLAVKTYR------------------------------H
>Medicago_truncatula_gi|357442691|ref|XP_003591623.1| Baculoviral IAP repeat-containing protein [Medicago truncatula]gi|355480671|gb|AES61874.1| Baculoviral IAP repeat-containing protein [Medicago truncatula]
MAMVPWRGVGCCLSAAALYLLGRTSGY-VDILKSVNRVNQLRELAQLLDE---EIFPLVV
AISGRVGSETPISCEFSGLRGVIIEETAEQHFLKHSDAGSWIQDSALMQSRSNEVPWYLD
DGTGRVRVVGAQGATGFVLPVGSEAFEESGR-LPVRGTSDYVQGLKVGVLMLGVKRIERV
LPVGTSLTVVGEAAKDDVGTIRIQRPSKGPFYVSPKTIDELIANIGRWARWYKYASAGLT
VLSVYMIANHAVRYI-------LERRRRNELEK----RVLAAAAKISGQDNGG--EMD--
-------DSLSDGAKRERAMPNLCVICLEQEYNSVFVPCGHMCCCTACSSHLTSCPLCRR
QIEKAVKTFR------------------------------H
>Glycine_max_gi|356500224|ref|XP_003518933.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Glycine max]
--MIPWGGLSCCLSAAALYLLGRSSGRDAEILKSVTRVNQLKELAQLLDA---EILPLIV
TISGRVSSETPINCEFSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLD
DGTDRVHVVGARGAAGFALPVGSEAFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPVGTSLTVVGEAAKDDVGAFRIQRPHKGPFYVSPKTIDQLIANLGKWARWYKYASMGLT
VFGAYLIAKHAIRYI-------LERRRRSELQR----RVLAAAAKKSGQNNDV--EKA--
-------DGLSDGVKKDRLMPDLCVICLEQEYNAVFVPCGHMCCCTTCSSHLTNCPLCRR
QIEKVVKTFR------------------------------H
>Glycine_max_gi|356535760|ref|XP_003536411.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like isoform 1 [Glycine max]
--MIPWGGLSCCLSAAALYLLGRSSGRDAEILKSVTRVNQLKELAQLLDA---EILPLIV
TISGRVSSETPINCEFSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLD
DGTDRVHVVGARGASGFALPVGIEAFEESGR-SLVRGTLDYLQGLK----MLGVKRIERV
LPVGTSLTVVGEAAKDDVGAIRIQRPHKGPFYVSPKTIDQLIANLGKWARWYKYASVGLT
VFGAYLIAKHAIRYI-------LERRRRSELQR----RVLAAAAKKSGQNNDV--EKA--
-------DSLSDGAKKDRLMPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTNCPLCRR
QIEKVVKTFR------------------------------H
>Brachypodium_distachyon_gi|357121695|ref|XP_003562553.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like isoform 1 [Brachypodium distachyon]
-MMVPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVTRTGSLKDLAAILDTA-SKVLPLVV
AVSGRVSSDTPLICQQSGMRGVIVEEMAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLD
DGTGRVYVVGARAAAGLVLTIASEVFEESGR-TLVRGTLDYLQGLK----MLGVKRTERV
LPTGTSLTVVGEAIKDDVGTIRIQRPHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFA
AFGVFLLAKRALQHF-------LQKKRQHELNK----RVRAAAAQRQAREAEGADGTS--
--------NGDPNSKKDQLVLEICVICLEQEYNAVFVPCGHMCCCMNCSSHVTNCPLCRR
RIDQAVRTFR------------------------------H
