>Methylibium_petroleiphilum PM1_gi|124266899|ref|YP_001020903.1| respiratory nitrate reductase subunit alpha apoprotein [Methylibium petroleiphilum PM1]gi|124259674|gb|ABM94668.1| respiratory nitrate reductase alpha subunit apoprotein [Methylibium petrol
M-S-HFL-----------------------------------------------------
---------------------------------------------------------DRL
THFKLPQEAFSGDHG--------RT-------------------------TGEDRTWEDA
YRNRWAHDKIVRSTHGVNCTGSCSWKIYVKGGIVTWETQQTDYPRTRADLPNHEPRGCAR
GASYSWYLYSANRVKYPMVRGRLLEAWRAALKVSKTPV----------------------
-----------DAW-TLVVENE--------------------------------------
------ATRRGYQKVRGMGGFVRSSW----DEVNQLIAAANVYTIKKYGPDRVIGFSPIP
AMSMVSYAAGSRYLS--------------------------------------LIG----
-------GVCMSFYDWYCDLPPASP-QIWGEQT-----D------VPESADWYNSTYIIA
WG--SNVPQTRTPDAHFFTEVRYKG---AK--TVAVTPDYAEVSKLADLWLHPKQGTDAA
LAMAMGHVALKEFFFDRRAAYFDDYARRYTDLP--------LLVLLEEKR----------
---LP-------DGRTVLAPGRYLRASDFNGKLGQTNNPDWKTVAFDTVGKAVLPNGSIG
FRWGAEGRDDAGKWNLEAKEARHDSDVKLKLSVLEDGAQAHEVVDVAFPYFAGAEVPHFT
PSPQAGGELNQARVPAVRLRLGKEGEERHALVATVFDLQAAQYGIDRGLGSGAKSYDDDA
PYTPAWQERITGVPRAQVITVAREFAANAEKTRGKSMVIIGAAMNHWYHADMNYRG----
-------------VINLLMMCGCIGQSGGGWAHYVGQEKLRPQTGWVPLAFA--------
-------TDWIR----------------------------------PPRQQNSTSFFYAH
TDQWRYEKLGVESILSPLFKTEADKGKFGGSLIDYNVRAERMGWLPSAPQLKTNPLQVV-
---------KDA------AAAGQDAKDYAVRALQDGRLEMSCEDPDAPQNWPRNLFVWRS
NLLGSSGKGHEYFCKHLLGTENGVQGKDLGRDDAKPHEVKWHEHAPEGKLDLVVTLDFRM
STTCLYSDIVLPTASWYEKNDLNTSDMHPFIHPLSAAVDPVWQARSDWEIYKGFAKAFSE
VCVGHLGVEKEL---VLTPMQHDTPAELAQGWDFKEWRKGECELIPGKTAPVMTVVERDY
PGVFKRFTSLGPLMTKVGNGGKGIAWKTEVEVKQLAELNGVDAEGRPRIVSDIDACEVIL
QLAPETNGHVAVKAWEALGKITGRDHTHLALHREDEKIRYRDVQAQPRKIISSPTWSGLE
SEKVSYNAGYTNVHELIPWRTLTGRQQFYQDHPWMVAFGEGFSSYRPPVDLKTTAAMLGA
KPNGQKEVVLNFITPHQKWGIHSTYSDNLMMLTLNRGGPVIWLSEEDAKAAGIADNDWVE
LFNVNGAISARAVVSQRVKPGMTMMYHAQEKIINAPGSEITGVRGGIHNSVTRIVTKPTH
MIGGYAQYSYGFNYYGTIGTNRDEFVVVRKMAKVDWLDTPADDHLAAVYQAQGENP
>Arabidopsis_thaliana_gi|18404810|ref|NP_564653.1| E3 ubiquitin ligase-like protein [Arabidopsis thaliana]gi|4587558|gb|AAD25789.1|AC006577_25 Contains similarity to gb|U45880 X-linked inhibitor of apotosis protein from Homo sapiens and contains PF|00097
M-S--SP-----------------------------------------------------
---------------------------------------------------------ERA
LLNLLTDIALSFD-G--------AI-------------------------LG--------
-------------------------------------------------------LTLAV
SAVGSALKYASTN--------------AALKKIKDAPEVS--------------------
---------ISDLR-SLLPASEDKSETN--------------------------------
-----DNRKSNDQRIVVVRGVVKPKISGD-EGYKN----NNVLISPETGDKALI------
---------IQRTQT--------------------------------------YVY----
-------SGWKRLFQSTGH-RFMLE-RSLRKHGADFTRT------VP---------FVIV
GK--DQQSN------SSFVAVNMDG---SR-QPLPLTTVYNR--------LQPINSS---
FLQAF-------------------LYPDY---P--------VGLLDIEKI----------
---LP-------PGKDITAVGIYSFNNG-VPEIKSCQD----------------------
-----------------------------------------------LPYF---------
------------------------------------------------------------
---------LSEMTKDKMIE---DLMEQTNF--------------------IFLGS----
-------------VILGIVSVGILS-----------------------YAAV--------
-------RTWNK------------------------------------------------
WKQWNHQR-----------------------------------------ELPQRPNDSV-
---------VDD--------EPEDADE-----IPDGELCVIC------------------
--VSRRRVPAFIPCGHV-------------------------------------------
------------------------------------------------------------
VCCRRCASTVER---ELNPK----------------------------------------
-------------------------------------------------------CPVCL
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SIRGSMR------------
-----------------------------------------------VYYS-----
>Arabidopsis_lyrata subsp. lyrata_gi|297847824|ref|XP_002891793.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]gi|297337635|gb|EFH68052.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]
M-S--SP-----------------------------------------------------
---------------------------------------------------------ERA
LLNLLTDIALSFD-G--------AI-------------------------LG--------
-------------------------------------------------------LTLAI
SAVGSALKYASTN--------------AALNKIKEAPEVS--------------------
---------VADLR-SLLPVSEDKSETN--------------------------------
-----DHG-----KIVVVRGVVKPKYSGD-ESHKN----NNVLISPETGDKALI------
---------IQRTQT--------------------------------------YVY----
-------SGWKRLFQSTGH-RFMLE-RSMRKHGADFMRT------VP---------FVIV
GK--DQQSQ------STFLDVNMDG---SR-QPLPLTTVYNR--------LQPINSS---
FLQAF-------------------LFPDY---P--------VGLLDIEKI----------
---LP-------PGKDITAVGICSFNNG-VPEIKSCQD----------------------
-----------------------------------------------LPYF---------
------------------------------------------------------------
---------LSEMTKDKMIE---ELMDQTSF--------------------IFFGS----
-------------VILGIVSVGILS-----------------------YAAV--------
-------RTWNK------------------------------------------------
WKQWNHQR-----------------------------------------DLPQRPNEPV-
---------VDD--------EPEDADE-----IPDGELCVIC------------------
--VTRRRVPAFIPCGHV-------------------------------------------
------------------------------------------------------------
VCCRVCASTVER---ELNPK----------------------------------------
-------------------------------------------------------CPVCL
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SIRGSMR------------
-----------------------------------------------VYYS-----
>Medicago_truncatula_gi|357514013|ref|XP_003627295.1| Baculoviral IAP repeat-containing protein [Medicago truncatula]gi|66947626|emb|CAJ00009.1| C3HC4 zinc finger containing protein [Medicago truncatula]gi|355521317|gb|AET01771.1| Baculoviral IAP repeat
M-S--SQ-----------------------------------------------------
---------------------------------------------------------EQA
LVSLLSQLALSFD-G--------AV-------------------------LG--------
-------------------------------------------------------FAVAY
VAVRSIRKFTLTS--------------AALRKITAAPSVS--------------------
---------VSDLR-SLLTETDEN------------------------------------
---------SDEGKIVIVRGTVDAKNVVD-GSWKALW--PGVLVSSESGDKGVV------
---------LQRTQT--------------------------------------CIY----
-------NEWKGLFGWTSDLRALFL-RSWRQQESTSLRK------IP---------FVLI
DV--GRPSN------PEYVVVNMDG---SS-HPLPLTTVYHR--------LQPVNPPPYT
FLQAL-------------------FGHEY---P--------VGLLDEEKI----------
---LP-------LGKDVSAVGLCSLRNG-IAEIKACND----------------------
-----------------------------------------------LPYY---------
------------------------------------------------------------
---------LSDLSKDQMIV---DLSFKTKL--------------------LFWSG----
-------------ILLGSMSVGIIG-----------------------YAVV--------
-------RNWNK------------------------------------------------
WKQWKQQR-----------------------------------------QL-QQRRQQP-
---------IEP-----VPPTDDEIED-----VPDGQLCVIC------------------
--LMRRRRSVFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCQGCAISVES---EVAPK----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------EVRDSVR------------
-----------------------------------------------IFES-----
>Glycine_max_gi|356504268|ref|XP_003520919.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like [Glycine max]
M-S--HQ-----------------------------------------------------
---------------------------------------------------------EQA
FVSLLSQLALSFD-G--------AV-------------------------LG--------
-------------------------------------------------------LALAY
AAVRTLFKFTATS--------------AALRKLHRAPSVS--------------------
---------VSDLR-SLLAEIPSDAD----------------------------------
-------GNSDGGNIVIVRGTVDAKSTVEGGTWKTLR--PGVLVSRESGDKSVI------
---------LQRTQT--------------------------------------CIY----
-------NEWKGLFGWTSDLRAIFA-RSWRQQESTSLRK------VP---------FVLI
DV--GRWPN------AEYVVVNMDG---SR-HPLPLSTVYHK--------LQPITASPYT
FLQAL-------------------FGHEY---P--------VGLLDEEKI----------
---LP-------LGKNITAVGLCSLKNG-IAEIKSCKD----------------------
-----------------------------------------------LPYF---------
------------------------------------------------------------
---------LSDLSKDQMIV---DLSSKTKI--------------------LFWGG----
-------------IALGSMSVGVLG-----------------------YAVV--------
-------RNWNK------------------------------------------------
WKQWKQQR-----------------------------------------QL-QQQRQAV-
---------SDV-----EPQMDDEIED-----VPDGQLCVIC------------------
--LMRRRRSVFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCQGCAISVER---EVAPK----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------EIRDSVR------------
-----------------------------------------------IYES-----
>Glycine_max_gi|356567748|ref|XP_003552078.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like [Glycine max]
M-S--HQ-----------------------------------------------------
---------------------------------------------------------EQA
LVSLLSQLALSLD-G--------AV-------------------------LG--------
-------------------------------------------------------FALAY
AAVRTLFKFTATS--------------SALRKLRRAPSLS--------------------
---------VSDLR-SLLAEIPSDGD----------------------------------
-------GNSKGGIIVIVRGTVDAKSAVD-GTWKTLR--PGVLVSRESGDKGVI------
---------LQRTQT--------------------------------------CIY----
-------NEWKGLFGWTSDLRAIFA-RSWRQQESTSLRK------VP---------FLLT
DV--GRRPN------AEYVVVNMDG---SR-HPLPLTTVYHK--------LQPITASPYT
FLQAL-------------------FGHEY---P--------VGLLDEEKI----------
---LP-------LGKDITAVGLCSLKNG-IAEIKSCKY----------------------
-----------------------------------------------LPYF---------
------------------------------------------------------------
---------LSDLSKDQMIM---DLSIKTKI--------------------LFWGG----
-------------IALGSMSVGVLG-----------------------YAVV--------
-------RNWNK------------------------------------------------
WKQWKQQR-----------------------------------------QL-QQQRQAV-
---------SDV-----EPQMDDEIED-----APDGQLCVIC------------------
--LMRRRRSVFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCQGCAISVER---EVAPK----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------EIRDSVR------------
-----------------------------------------------IYES-----
>Glycine_max_gi|356558912|ref|XP_003547746.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Glycine max]
M-S--HQ-----------------------------------------------------
---------------------------------------------------------EQA
VLSLLSKLALSFD-G--------AV-------------------------LG--------
-------------------------------------------------------VALAF
AAVRTLFKFTATS--------------ASLRKLRRAPSIS--------------------
---------VSDLR-SLLAEPPSDAD----------------------------------
-----------AGEIVIIRGTVDAKSAVD-GTWKTLK--PGVLVSRESGDKGVI------
---------LQRTQT--------------------------------------CIY----
-------NDWKGLLGWTSDLRAICA-RSLRQQDSTSFRK------VP---------FVLI
DV--GRRPN------AEYVVVNMDG---SR-HPLPLTTVYHK--------LQPINASPYT
FLQAL-------------------FGHEY---P--------VGLLDEEKI----------
---LP-------LGKDITAVGHCSLKNG-IAEIKSCKD----------------------
-----------------------------------------------IPYF---------
------------------------------------------------------------
---------LSDLSKDQMIV---DLSIKAKI--------------------LFWGG----
-------------ISLGSMSVGVLG-----------------------YAVL--------
-------RNWIK------------------------------------------------
WKRWKVQR-----------------------------------------QL-QQQRQAV-
---------SDA-----EPQVDDEIED-----VPDGQLCVIC------------------
--LMRRRRSVFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCQGCAISVER---EVAPK----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------EIRDSVR------------
-----------------------------------------------TYES-----
>Vitis_vinifera_gi|225442119|ref|XP_002274016.1| PREDICTED: hypothetical protein [Vitis vinifera]gi|297743001|emb|CBI35868.3| unnamed protein product [Vitis vinifera]
M-S--AH-----------------------------------------------------
---------------------------------------------------------DQA
AAAILAQVALAAD-G--------AI-------------------------LG--------
-------------------------------------------------------LALAY
VAVRSFIRLSSTS--------------SALRQIDQSPSFR--------------------
---------VSDLR-SLLSPSSDDESDQ--------------------------------
-------STSSDGLLVVVRGTVEAKSAID-GNWKSLR--PNVLVSHESGEKGVI------
---------LQRTQT--------------------------------------CIY----
-------NEWRGFFGWTSDIRTLFA-RSWKEKESTSLRT------VP---------FILV
EG--GRWPQ------SDYVIVNMDG---SR-HPLPLTTVYHQ--------LQPVNASPYT
FLQAL-------------------FGHDY---P--------VGLLDEEKL----------
---LP-------LGKEITAVGICSLKNG-IPEIKSCKD----------------------
-----------------------------------------------LPYF---------
------------------------------------------------------------
---------LSEMSKDQMVV---DLVFKSKV--------------------LFWSG----
-------------VILGSVSIGVLG-----------------------YAVV--------
-------RNWNR------------------------------------------------
WKEWRQQR-----------------------------------------GV-RPPSQAV-
---------TDD--TDTQI-AEDDAGD-----VPDGELCVIC------------------
--LMRRKRSAFVPCGHL-------------------------------------------
------------------------------------------------------------
VCCQRCALSVER---ELSPK----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------IIRSSVR------------
-----------------------------------------------IYGS-----
>Populus_trichocarpa_gi|224070805|ref|XP_002303243.1| predicted protein [Populus trichocarpa]gi|222840675|gb|EEE78222.1| predicted protein [Populus trichocarpa]
M-ASRAH-----------------------------------------------------
---------------------------------------------------------EQA
LAAMLSHLALSFD-G--------AI-------------------------LG--------
-------------------------------------------------------AALAY
AAVRSFLNFTANS--------------KSLAKIRKAPTLS--------------------
---------VSDLR-SLLQNHDQDHQ----------------------------------
---------DQEQKLVIVRGQVEAKSAVD-GSGKKSSRDSNVLLSHESGDKAVI------
---------LQRTQT--------------------------------------CIY----
-------NEWKGFFGWTSDLRSIFG-RSLKEQETTFLRT------VP---------FTLV
EG--GQWPQ------SDYVIVNMDG---SS-HPLPLTMVYHQ--------LQPIVASRYT
FIQAL-------------------FGHEY---P--------VGVLHEEKI----------
---LP-------LGKCISAVGICNSKDG-IPEIKSCKE----------------------
-----------------------------------------------LPYF---------
------------------------------------------------------------
---------LADMTKDEMVA---DLAFKAKI--------------------LLWSG----
-------------IVLGSLSIGVLG-----------------------FAVM--------
-------RNWNK------------------------------------------------
WKAWRQRR-----------------------------------------S--QQPIHTT-
---------SDE--DVSQIDDNEDAGD-----VPEGQLCVIC------------------
--LMRRRRAAFIPCGHL-------------------------------------------
------------------------------------------------------------
ACCHTCAVSVES---EVSPK----------------------------------------
-------------------------------------------------------CPLCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------AVRNSIR------------
-----------------------------------------------IFEC-----
>Populus_trichocarpa_gi|224054081|ref|XP_002298092.1| predicted protein [Populus trichocarpa]gi|222845350|gb|EEE82897.1| predicted protein [Populus trichocarpa]
M-SSRSH-----------------------------------------------------
---------------------------------------------------------EQA
LAALLSQLALSFD-G--------AI-------------------------LG--------
-------------------------------------------------------AALAY
AAVRSILNYTANS--------------KSLAKISKAPTLS--------------------
---------VSDLR-SLLQNHDQDHQ----------------------------------
---------DHEHNLVIVKGIVEAKSAVE-WTWKESFRPPKVLLSHNSAYKAVI------
---------LQKTQT--------------------------------------CIY----
-------NEWKGFLGWTSELRAIFG-RSLKEQETTLLRT------VP---------FILV
EG--AQWPR------SDYVIVNMVG---SA-HPLPLTTVYHQ--------LQRIAASRYT
FIQAL-------------------FGHEY---P--------VGVLHEEKI----------
---LP-------LGKCISAVGICNSKKG-IPEIKSCKD----------------------
-----------------------------------------------LPYF---------
------------------------------------------------------------
---------LADITKDQMVA---DLAFKAKI--------------------QLWSG----
-------------IFLGSLSIGVLG-----------------------FAVM--------
-------RNWNK------------------------------------------------
WQAWRQRH-----------------------------------------S--HLPNHTT-
---------IDA--DVSRID-EDEAGD-----VPDGQLCVIC------------------
--LTRRRRSAFIPCGHL-------------------------------------------
------------------------------------------------------------
ACCHFCAISVES---EVSPK----------------------------------------
-------------------------------------------------------CPLCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------AIRNSIR------------
-----------------------------------------------VFEC-----
>Ricinus_communis_gi|255560625|ref|XP_002521326.1| ubiquitin-protein ligase, putative [Ricinus communis]gi|223539404|gb|EEF40994.1| ubiquitin-protein ligase, putative [Ricinus communis]
M-S--SH-----------------------------------------------------
---------------------------------------------------------EQA
LASLVSQLALSFD-G--------AF-------------------------LG--------
-------------------------------------------------------VVVAL
TAVRSILKFASNS--------------KALRKIRNAPTVK--------------------
---------VSDIR-SVLEVSDE-------------------------------------
---------TQDQKLVIVRGQVEAKSAVD-GNWKSLIPNNNVLVAHESGDKAVI------
---------VQRIQT--------------------------------------CIY----
-------NEWKGFFGWTSDIRAIFG-RSWREQESTLSRS------VP---------FVLV
EA--GRWPQ------SDYVIVNLDG---SR-HPLPLTTVYHQ--------LQPIDASPYT
FLQAF-------------------FGYEY---P--------VGLLDEEKI----------
---LP-------LGKEINAVGLCGSKNG-ILEITSCKD----------------------
-----------------------------------------------LPFF---------
------------------------------------------------------------
---------LSDLSKEQMVV---DLAFKTKV--------------------LFWSG----
-------------VVLGSFSICILG-----------------------YAAV--------
-------RNWNR------------------------------------------------
WKAWRQQR-----------------------------------------QF-QQQSNSV-
---------SDA--DVSQIDVEEETVD-----VPDGQLCVIC------------------
--LMRRRRAAFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCQICAISVER---EVSPK----------------------------------------
-------------------------------------------------------CPLCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------AVRNSIR------------
-----------------------------------------------IFEC-----
>Oryza_sativa Japonica Group_gi|115451087|ref|NP_001049144.1| Os03g0177300 [Oryza sativa Japonica Group]gi|108706473|gb|ABF94268.1| C3HC4 zinc finger containing protein, putative, expressed [Oryza sativa Japonica Group]gi|113547615|dbj|BAF11058.1| Os03g
M-S--AR-----------------------------------------------------
---------------------------------------------------------DRE
TAVALARLAAALD-G--------AV-------------------------LG--------
-------------------------------------------------------LGTAA
LAVASWVKYLAAS--------------GQLRRIASAPAAA--------------------
---------IPDLR-SLLAEYGGGGGDG--------------------------------
----------DQPILAVVRGHVRAAPR------------GKYLVPPGSGEHCVV------
---------AKHTQL--------------------------------------CLF----
-------NEWRGIFGWTFDLHALFF-KSIKEQIITSFRW------VP---------FVLV
DP----ENM------TGMVHVKLDR---AM-QPLPLTTVYHK--------LTPVDSTPYT
LFQTI-------------------IGNGY---P--------IALLDEEKI----------
---LP-------VGKEITAIGYIRPHKA-SVEISSCSE----------------------
-----------------------------------------------IPFF---------
------------------------------------------------------------
---------LSDLTKDEMEA---ELSSRAKT--------------------LFWAS----
-------------VVLGTMSVCLLG-----------------------FATY--------
-------RSWKK------------------------------------------------
IKERREAR-----------------------------------------QA-QEVFRQT-
---------TDE--VTDDQSSDEEAGE-----MGDGQLCVIC------------------
--LRKRRKAAFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCCKCALIVER---QFDPL----------------------------------------
-------------------------------------------------------CPMCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DIRYMIR------------
-----------------------------------------------IYDN-----
>Oryza_sativa Indica Group_gi|218192193|gb|EEC74620.1| hypothetical protein OsI_10236 [Oryza sativa Indica Group]
M-S--AR-----------------------------------------------------
---------------------------------------------------------DRE
TAVALARLAAALD-G--------AV-------------------------LG--------
-------------------------------------------------------LGTAA
LAVASWVKYLAAS--------------GQLQRIASAPAAA--------------------
---------IPDLR-SLLAEYGGGGGDG--------------------------------
----------DQPILAAVRGHVRAAPR------------GKYLVPPGSGEHCVV------
---------AKHTQLWHRRLGLMFWIASGFLWKQYPEANCRGCGCTAANRNIPCLF----
-------NEWRGIFGWTFDLHALFF-KSIKEQIITSFRWVYHLYFVP---------FVLV
DP----ENM------TGMVHVKLDR---AM-QPLPLTTVYHK--------LTPVDSTPYT
LFQTI-------------------IGNGY---P--------IALLDEEKI----------
---LP-------VGKEITAIGYIRPHKA-SVEISSCSE----------------------
-----------------------------------------------IPFF---------
------------------------------------------------------------
---------LSDLTKDEMEA---ELSSRAKT--------------------LFWAS----
-------------VVLGTMSVCLLG-----------------------FATY--------
-------RSWKK------------------------------------------------
IKERREAR-----------------------------------------QA-QEVFRQT-
---------TDE--VTDDQSSDEEAGE-----MGDGQLCVIC------------------
--LRKRRKAAFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCCKCALIVER---QFDPL----------------------------------------
-------------------------------------------------------CPMCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DIRYMIR------------
-----------------------------------------------IYDN-----
>Oryza_sativa Japonica Group_gi|222624296|gb|EEE58428.1| hypothetical protein OsJ_09629 [Oryza sativa Japonica Group]
MFG--AR-----------------------------------------------------
---------------------------------------------------------QGD
GPGRWPALAAALD-G--------AV-------------------------LG--------
-------------------------------------------------------LGTAA
LAVASWVKYLAAS-----------------------RAAA--------------------
---------AHCLR-A--------GGRH--------------------------------
----------TRPPLAPRGWHRRLGLMFWIASGFLW---KQYPEANCRGCGCTA------
---------ANRNIP--------------------------------------CLF----
-------NEWRGIFGWTFDLHALFF-KSIKEQIITSFRWVYHLYFVP---------FVLV
DP----ENM------TGMVHVKLDR---AM-QPLPLTTVYHK--------LTPVDSTPYT
LFQTI-------------------IGNGY---P--------IALLDEEKI----------
---LP-------VGKEITAIGYIRPHKA-SVEISSCSE----------------------
-----------------------------------------------IPFF---------
------------------------------------------------------------
---------LSDLTKDEMEA---ELSSRAKT--------------------LFWAS----
-------------VVLGTMSVCLLG-----------------------FATY--------
-------RSWKK------------------------------------------------
IKERREAR-----------------------------------------QA-QEVFRQT-
---------TDE--VTDDQSSDEEAGE-----MGDGQLCVIC------------------
--LRKRRKAAFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCCKCALIVER---QFDPL----------------------------------------
-------------------------------------------------------CPMCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DIRYMIR------------
-----------------------------------------------IYDN-----
>Zea_mays_gi|212721266|ref|NP_001131841.1| uncharacterized protein LOC100193216 [Zea mays]gi|194692688|gb|ACF80428.1| unknown [Zea mays]
M-S--AR-----------------------------------------------------
---------------------------------------------------------DRE
TAEALVRLAASLD-G--------AV-------------------------LG--------
-------------------------------------------------------LGTAA
VAVASWVKYLAVS--------------GQLRLVASAATAS--------------------
---------IADAR-SLLSGDG--------------------------------------
----------AEPRIAAVRGYVRAH--------------DKFFRAPFSGEAGVV------
---------TKHTQM--------------------------------------CLF----
-------TEWRGIFGWTFDLHALLF-RSWKEQIVTSFRS------VP---------FVLV
ST--ELGNP------TGVVHINVDK---AD-QPLPLTTVFHK--------LIPLETTPYT
LFQTI-------------------IGNGY---P--------IALLDEEKI----------
---LP-------IGKKITAIGLCQAKDAESVEITSCPE----------------------
-----------------------------------------------IPFF---------
------------------------------------------------------------
---------LSELTKDEMQA---QLASRARI--------------------LFWGS----
-------------IVLGTLSVCLVG-----------------------HAIY--------
-------RGWTR------------------------------------------------
IKLRREAR-----------------------------------------HA-RQMFEEA-
---------EDA--IHRDDSS--DDDE-----IGDGQLCVVC------------------
--LRKRRRAAFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCSECALTIER---TPHPL----------------------------------------
-------------------------------------------------------CPMCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DIRYMMR------------
-----------------------------------------------VYDS-----
>Sorghum_bicolor_gi|242042023|ref|XP_002468406.1| hypothetical protein SORBIDRAFT_01g045370 [Sorghum bicolor]gi|241922260|gb|EER95404.1| hypothetical protein SORBIDRAFT_01g045370 [Sorghum bicolor]
M-S--AR-----------------------------------------------------
---------------------------------------------------------DRE
TAEALVRLAASLD-G--------AV-------------------------LG--------
-------------------------------------------------------LGTAA
VAVASWVKYLAVS--------------GQLRLVASAATAS--------------------
---------IGDAR-SLLRGDG--------------------------------------
----------NEPRIAAVRGYVRTQ--------------GSFLRAPFSSEAGVV------
---------VKHTQM--------------------------------------CLF----
-------TEWRGIFGWTFDLHALLF-RSWKEQIVTSFRA------VP---------FVLA
ST--ELGNS------TGVVHINVDE---VDYQPLPLTTVFHK--------LIPLETTPYT
LFQTI-------------------IGNGY---P--------IALLDEEKI----------
---LP-------IGKKITAIGLCRAKNAESVEITSCPE----------------------
-----------------------------------------------IPFF---------
------------------------------------------------------------
---------LSELTKDEMQA---QLASRARI--------------------LFWGS----
-------------IVLGTLSVCLVG-----------------------HAIY--------
-------RGWKR------------------------------------------------
IKLRREAR-----------------------------------------QA-QQMFEDA-
---------EDA--IREDNSSDDDDDD-----VGDGQLCVVC------------------
--LRKRRKAAFIPCGHL-------------------------------------------
------------------------------------------------------------
VCCCKCALRMER---EVEPL----------------------------------------
-------------------------------------------------------CPMCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DIRYMIR------------
-----------------------------------------------IYDS-----
>Brachypodium_distachyon_gi|357113780|ref|XP_003558679.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Brachypodium distachyon]
M-S--AR-----------------------------------------------------
---------------------------------------------------------DRE
TVEALARVAAALD-G--------AV-------------------------LG--------
-------------------------------------------------------LGTAA
LAVVSLAKYLAAS--------------GALRRIAEAPEVA--------------------
---------IPDLRYSLLAGLGE-------------------------------------
----------GESRLAVVRGLVRSPPW------------GKFLIPPGSREHCVV------
---------AKHTQT--------------------------------------CLF----
-------GEWRGIFGWTFDLHALFF-KSLKEQTITSFRW------VP---------FALV
DPASASDKS------TEMIHVKLDG---AVQQSLPLTTVYHK--------LIPVEQNSYT
LFQTI-------------------VGNGY---P--------IALLDEEKI----------
---LP-------IGKEITAIGLCRVNNQ-NVEITSCPE----------------------
-----------------------------------------------IPFF---------
------------------------------------------------------------
---------LSDLTKGEIEA---ELDSRART--------------------LFWVT----
-------------FALGTMSVGLLG-----------------------HAIY--------
-------RFWEK------------------------------------------------
VKQHREAR-----------------------------------------QA-QQRFHQA-
---------DDEDDTGENGSDDDFPGE-----MGDGQLCVIC------------------
--LRKRRKAAFVPCGHL-------------------------------------------
------------------------------------------------------------
VCCCNCAKRVEL---MNEPL----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DIQYMLR------------
-----------------------------------------------VYDS-----
>Physcomitrella_patens subsp. patens_gi|168019172|ref|XP_001762119.1| predicted protein [Physcomitrella patens subsp. patens]gi|162686836|gb|EDQ73223.1| predicted protein [Physcomitrella patens subsp. patens]
M-A--GH-----------------------------------------------------
---------------------------------------------------------EDE
LCAALMRLALAGD-G--------LV-------------------------MG--------
-------------------------------------------------------VGMTV
LAFRTWIKFWSHS--------------KALKDIKDTPVTR--------------------
---------IADLR-TLVEEPDVQAKEKIRTPEKISPPHQDIEVFATRSKVKMPSRPWMV
ERLPIPSLETKQEKLVIVRGRVQTKAFVE-SEGDQRD--AEALIPLNVPEKAVF------
---------VERTQT--------------------------------------YVL----
-------TEMSNFLGWITQ----------KDLVKFTRQV------VP---------FVLA
ET--EAHWSFRPSDMAVYVHINLDE---SQ-HPIPLVTVHHQ--------LHPVPASSYT
LFQAM-------------------FGRRY---P--------VGLLDEEKI----------
---LP-------LGAEITAVGVLHTAPDGTPVVKSSKR----------------------
-----------------------------------------------LPIF---------
------------------------------------------------------------
---------LTEFTREQLLV---ELASSTKV--------------------LFWMG----
-------------VAVSTVAAGVLG-----------------------YSLV--------
-------KNWTR------------------------------------------------
WKQRQQQR-----------------------------------------QS-QNNSENR-
---------QNSTIEDE----AENFED-----IPDGELCVVC------------------
--LLRRRRAAFIYCGHR-------------------------------------------
------------------------------------------------------------
VCCMGCAERVEH---GANPR----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SVTGIVR------------
-----------------------------------------------VYDS-----
>Selaginella_moellendorffii_gi|302817923|ref|XP_002990636.1| hypothetical protein SELMODRAFT_132031 [Selaginella moellendorffii]gi|300141558|gb|EFJ08268.1| hypothetical protein SELMODRAFT_132031 [Selaginella moellendorffii]
M-A--SH-----------------------------------------------------
---------------------------------------------------------DEE
ICAALTRLAMAGD-G--------IV-------------------------LG--------
-------------------------------------------------------LGMAA
LALRTWLKFGSHT--------------RALKQVEGTAQVE--------------------
---------IHDLR-SLVESGEKEPSSD--------------------------------
----------SSPPLVIVRGRVALPPKTS---------SEEVLLARNQTDLAVF------
---------VERTQT--------------------------------------YLF----
-------NEWRGLFRWGPEWRGLLGWGSLKEQVAFSRRK------IP---------FVLL
DS--DPQYD------GACVHINMEN---VE-HPLPLVTVFHQ--------LHPVQTSSST
FLQAV-------------------FGRRY---P--------VGVIDEEKI----------
---LP-------LNREITAVGFLSKHPQGLPAIKSSNQ----------------------
-----------------------------------------------MPFF---------
------------------------------------------------------------
---------LTEFSREELIV---ELTSATHA--------------------LFWTG----
-------------IVISSLALGVIG-----------------------YSAF--------
-------KNWCK------------------------------------------------
WKEWRRLR-----------------------------------------QI-QEELRRE-
---------EQVMEEDEEPATTQEGSE-----VPDGQLCVVC------------------
--LLRRKRAAFITCGHR-------------------------------------------
------------------------------------------------------------
VCCMGCARRIRHSQNAANAR----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SVSGYIR------------
-----------------------------------------------VYD------
>Selaginella_moellendorffii_gi|302770663|ref|XP_002968750.1| hypothetical protein SELMODRAFT_91152 [Selaginella moellendorffii]gi|300163255|gb|EFJ29866.1| hypothetical protein SELMODRAFT_91152 [Selaginella moellendorffii]
M-A--SH-----------------------------------------------------
---------------------------------------------------------DEE
ICAALTRLAMAGD-G--------IV-------------------------LG--------
-------------------------------------------------------LGMAA
LALRTWLKFGSHT--------------RALKQVEGTAQVE--------------------
---------IHDLR-SLVESGEKEPSSD--------------------------------
----------SSPPLVIVRGRVALPPKTS---------SEEVLLARNQTDLAVF------
---------VERTQT--------------------------------------YLF----
-------NEWRGLFRWGPEWRGLLGWGSLKEQVAFSRRK------IP---------FVLL
DS--DPQYD------GACVHINMEN---VE-HPLPLVTVFHQ--------LHPVQTSSST
FLQAV-------------------FGRRY---P--------VGVIDEEKI----------
---LP-------LNREITAVGFLSKHPQGLPAIKSSNQ----------------------
-----------------------------------------------MPFF---------
------------------------------------------------------------
---------LTEFSREELIV---ELASATHA--------------------LFWTG----
-------------IVISSLALGVIG-----------------------YSAF--------
-------KNWCK------------------------------------------------
WKEWRRLR-----------------------------------------QI-QEELRRE-
---------EQVMEEDEEPATTQEGSE-----VPDGQLCVVC------------------
--LLRRKRAAFITCGHR-------------------------------------------
------------------------------------------------------------
VCCMGCARRIRHSQNAANAR----------------------------------------
-------------------------------------------------------CPVCR
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SVSGYIR------------
-----------------------------------------------VYD------
>Pirellula_staleyi DSM 6068_gi|283778272|ref|YP_003369027.1| hypothetical protein Psta_0479 [Pirellula staleyi DSM 6068]gi|283436725|gb|ADB15167.1| protein of unknown function DUF107 [Pirellula staleyi DSM 6068]
M-KRQSHRSHSTLVAPRPYARIWFWCVLLPGLLLLALAPSSRGSLLAQADAEKPTADPVK
LERLVVPLPIVGNVDTIVRSQIDRWLKTIAADQANVDKRPLLVLEFRPAVGTVGEGSEYE
RALSLARFLASERLG--------RVRTVAFVPQSIEGHSVLPILACEQLVIGKDAEIGNA
GRDEAALDPTVRRGYSEIAERRQTIPAAVALGMLDNK------------------LAVTI
ATTPNGRRFVLSE---------------ELEKLRAAGEVTQEETLFHEGKSHKLSGRQLR
LEFSFASHLASDLR-ELATALE--------------------------------------
---------------VPVNDLTRASLPTDGWKPIRMQLSGNITRGEVNGIIRAL------
------RAQLEQTDA--------------------------------------NLLLLEI
DCTGGSIDHSRRLAQELVDLRSRLHTVAIVEKQALSDA------------------AIVA
LS---------CHELRVTSEARLGGAGAASFTPPQLATAKPAIMQ-----LAEAQSRDWS
LMMGM-------------------IDRRLEVFPCTREVTGQVRLLSEEEREALEDAAAWK
RGEMPVSTLSGIVGSDLIAYGQ-------ATPIEQKSD----------------------
----------------------------------------------ILREF---------
------------------------------------------------------------
-----------QLESDPPLV---QESWALEV--------------------IRWMADPRI
AGLLLFVGWFALMFEMSSPGVGVPG-----------------------FIAALCFLLYFW
SAFLNGTSGWLEVMLFLFGIICILAEIFFIPGTGFFGIGGAIAVIVSIVLASQTFVIPSN
VYQFKQLPFSLSMVAAGLAGGIGAVVFMHKFLPHTPYLKHMMLLPPTGEELEALEQRETI
VDLAYLAGKQGVTTTKLVPSGKALFGDELIDVLSDGEL----------------------
------------------------------------------------------------
------------------------------------------------------------
---------IELGTNVVVKE----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------VLGNRVV------------
-----------------------------------------------VKRA-----
>Streptomyces_sviceus ATCC 29083_gi|297202679|ref|ZP_06920076.1| integral membrane protein [Streptomyces sviceus ATCC 29083]gi|297148163|gb|EDY57288.2| integral membrane protein [Streptomyces sviceus ATCC 29083]
M-P--AE-----------------------------------------------------
---------------------------------------------------------DSR
TDDLDPAVLPSPKEAPKFLPWGVAV-------------------------LA--------
-------------------------------------------------------AGLAV
EAYANRQGTTPAA--------------PLPGGLAGTPSVLVGWLLTAVGLAIAGPG----
---------LTHLCGRLLQSTR--------------------------------------
-----------PGALRLLAGRVLM------------------------------------
---------AEATRI---------------------------------------------
--------------------------------------G------RP---------LGIV
CA--------------------------VASGAYAMTTLYDR--------TGPEVGPLTT
LGLAL-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VTSCTLATLLTAAVE-AKHARSDTTAALVRLGAPAT------MLRSA----
----------------AALRAGAL------------------------LALF--------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------GPLTLVV------------------
------------------------------------------------------------
------------------------------------------------------------
---------AEL---AALPL----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------TG
