>SPL2_NP_564653
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------SSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYA
STNAALKKIKDA------------------------------------------------
-------------------------------------PEVSISDLRSLLPASEDKSETND
NRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGDKALIIQRTQTYVYSGWKRLF-
------------------------------------------------------------
--------------------------------------------------------QSTG
HRFMLERSLRKHGADFTRTV------PFVIVGKDQQSNSSFVAVNMDGSRQPLPL-----
------------------------------------------------------------
-----------------------TTVYNRLQPINSSFLQAFLYPDYPVGLLDIEKILPPG
KDITAVGIYSFN------------------------------------------------
------------------------------------------------------------
-------------------------------NGVPEIKSCQDLPYFLSEMTKDKMIEDLM
EQTNFIFLGSV-------------------------------------------------
-------------ILGIVSVGILSYAAVRTWNKWKQWNHQRELPQRPNDSVVDDEPEDAD
EIPDGELCVICVSRRRVPAFIPCGHVVCCRRCASTVERELNPKCPVCLQSIRGSMRVYYS
>gnl|BL_ORD_ID|1836 @Prochlorococcus_sp_CC9311@ 638115460 sync_1872 possible Arginine repressor, C-terminal domain [Prochlorococcus sp. CC9311]
MHHDLLALNSNWNLSQTDPSTRVPLVSLDEALERSSLKKGISRRDFLAELLKDVQHQRLL
PLL---------------------------------------------------------
-----------------AMLPRRWRQEPASLPEQLRGLGNLLGEGLMSPLLLAAFADDLQ
HLLPQ-------------------------------RTNPRRSALDLWCQRTYNNPGSQQ
WPLPEGLETWRSQAAESLKSQNERLKPKGRSGLTGLTSLGGEIAWSNH------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------GLSYLQSA
EARHRNQQMAQVFNVLGSNLLVEQNLNV--------------------------------
------------------------------------------------------------
------------------------------------DTYRFEGQSSGKDLIQCLQSKGWR
CQARVRTSVASFGLGASTPSSDSNQWNQIPLAVPYRTGLQET------------------
----NQKEINALLPHACLELELQPPEDDTVLLQYYQGTEG-----LNGWAAMNDLDRPWQ
NGRSNGSVQYSPTVFRDQQLSDAVELCELM-----------------------GAIHNSE
AGMENLHLGGYG------------------------------------------------
------------------------------------------------------------
--------------------AIGFCIDSTALLEYALTGQTNLFPLT--------------
------------------------------------------------------------
-------------LGGLWRERLSAQLNHLLEQNMRPNDDAVDRYKRAIEDMPQDLYHTSV
TRTDARRRLLASQPSYSPFLLIQ------------------------------DLNLQKS
>gnl|BL_ORD_ID|1301 @Microcoleus_chthonoplastes_PCC_7420@ 647565661 MC7420_2944 hypothetical protein [Microcoleus chthonoplastes PCC 7420]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------KVLVLLLMLGIYGYGAWKFWTGFNRTN---FSRSLPN
RIYLSLLWPALI------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------VANKSYRKNFNRALKGR
>gnl|BL_ORD_ID|1621 @Prochlorococcus_sp_WH_7803@ 640543983 SynWH7803_1622 1-deoxy-D-xylulose 5-phosphate reductoisomerase [Prochlorococcus sp. WH 7803]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---LGSTGSIGTQTLDIVEDFPEQFRVVALSAGRNLSLL---------------------
-----------------------------------------------------VEQIQRH
SPELVALADEAL------------------------------------------------
-----------------------------LPELEQRLRALPA----------EHQPRCKP
QLVGGPSGLNVAASWDTADLVVTGIVGCAGLLPTLAAIRAGKDLALANKETLI-------
------------------------------------------------------------
-----------------------AAGPVVLPELKKSGSRLLPADSEHSAIFQCLQGTPWA
ENARLSTGVPTPGLRRIQLT------ASGGAFRDWAAADLENATVADATS----------
--------------HPNWSMGRKITVDSASLMNKGLEVIEAHYLFGLDYDHIEIVIHPQS
IIHSMIELA----------------DSSVL-----------------------AQLGWPD
MKLPILYCMSWP--------------------SRLETPWKRLDLT---------------
-------------------QVGQLTFRSPDPAKYPCME----------------------
-------------------------------LAYAAGRAGGTMPAVLNAANEEAVAQFLE
ERIHFLDIPDLI------------------------------------------------
-----------------------EAACERHKVDRIDHPQLDDVLAVDQWARLAVREQVAR
GTQRM------------------------------------------------SMAAVAA
>gnl|BL_ORD_ID|1621 @Synechococcus_WH_7803@ gi|148239958|ref|YP_001225345.1| 1-deoxy-D-xylulose 5-phosphate reductoisomerase [Synechococcus sp. WH 7803]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---LGSTGSIGTQTLDIVEDFPEQFRVVALSAGRNLSLL---------------------
-----------------------------------------------------VEQIQRH
SPELVALADEAL------------------------------------------------
-----------------------------LPELEQRLRALPA----------EHQPRCKP
QLVGGPSGLNVAASWDTADLVVTGIVGCAGLLPTLAAIRAGKDLALANKETLI-------
------------------------------------------------------------
-----------------------AAGPVVLPELKKSGSRLLPADSEHSAIFQCLQGTPWA
ENARLSTGVPTPGLRRIQLT------ASGGAFRDWAAADLENATVADATS----------
--------------HPNWSMGRKITVDSASLMNKGLEVIEAHYLFGLDYDHIEIVIHPQS
IIHSMIELA----------------DSSVL-----------------------AQLGWPD
MKLPILYCMSWP--------------------SRLETPWKRLDLT---------------
-------------------QVGQLTFRSPDPAKYPCME----------------------
-------------------------------LAYAAGRAGGTMPAVLNAANEEAVAQFLE
ERIHFLDIPDLI------------------------------------------------
-----------------------EAACERHKVDRIDHPQLDDVLAVDQWARLAVREQVAR
GTQRM------------------------------------------------SMAAVAA
>gnl|BL_ORD_ID|1932 @Synechococcus_CC9605@ gi|78213487|ref|YP_382266.1| 1-deoxy-D-xylulose 5-phosphate reductoisomerase [Synechococcus sp. CC9605]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------KA
ISVLGSTGSIGTQTLQIAEEFPEQFRVVALTAGRNLKLL---------------------
-----------------------------------------------------VEQVQRH
RPEVVALADSDL------------------------------------------------
-----------------------------LPELQERLK--DA----------GVTGADAP
QLVGGADGLNVAAAWDSADLVVTGIVGCAGLLPTLAAIRAGKDLALANKETLI-------
------------------------------------------------------------
-----------------------AAGPVVLPELKKSGSRLLPADSEHSAIFQCLQGTPWA
ENARLSTGVPTPGLRRIQLT------ASGGAFRDWTAADLEKATVADATS----------
--------------HPNWSMGRKITVDSASLMNKGLEVIEAHYLFGLDYDHIEIVIHPQS
IIHSMIELA----------------DSSVL-----------------------AQLGWPD
MKLPILYCLSWP--------------------SRLETPWRRLDLT---------------
-------------------EVGQLSFRAPDPAKYPCME----------------------
-------------------------------LAYAAGSAGGTMPAVMNAANEEAVAQFLE
EKIHFLDIPTVI------------------------------------------------
-----------------------EAACERHKPDLMAQPQLDDVLRVDQWARTAVREQVNR
GVTRL------------------------------------------------PMGAIAA
>gnl|BL_ORD_ID|1150 @Synechococcus_sp_WH_8109@ 647835867 SH8109_1182 1-deoxy-D-xylulose 5-phosphate reductoisomerase [Synechococcus sp. WH 8109]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------KA
ISVLGSTGSIGTQTLQIAEEFPEQFRVVALTAGRNLTLL---------------------
-----------------------------------------------------VDQVQRH
RPEVVALADADL------------------------------------------------
-----------------------------LPELQERLK--DA----------GITGTDAP
QLVGGADGLNVAAAWDSADLVVTGIVGCAGLLPTLAAIRAGKDLALANKETLI-------
------------------------------------------------------------
-----------------------AAGPVVLPELKKSGSRLLPADSEHSAIFQCLQGTPWA
ENARLSTGVPTPGLRRIQLT------ASGGAFRDWTAADLEKATVADATS----------
--------------HPNWSMGRKITVDSASLMNKGLEVIEAHYLFGLDYDHIEIVIHPQS
IIHSMIELA----------------DSSVL-----------------------AQLGWPD
MKLPILYCLSWP--------------------SRLETPWRRLDLT---------------
-------------------EVGQLSFRAPDPAKYPCME----------------------
-------------------------------LAYAAGRAGGTMPAVMNAANEEAVAQFLE
EKIHFLDIPAVI------------------------------------------------
-----------------------EAACERHKPDLMAQPQLDDVLRVDQWARTAVREQVKR
GVTRL------------------------------------------------PMGALAA
>gnl|BL_ORD_ID|225 @Synechococcus_sp_RS9916@ 639887413 RS9916_31867 1-deoxy-D-xylulose 5-phosphate reductoisomerase [Synechococcus sp. RS9916]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------LLHRHRPKDSIDLDEVCQGLAWETDPNCLIDVKA
ISVLGSTGSIGTQTLDIARDFPDQYKVVALTAGRNLALL---------------------
-----------------------------------------------------VEQIQEY
RPEVVALADTAL------------------------------------------------
-----------------------------LPELQKRLK--AA----------GVDEAATP
QLVGGPDGLNVAASWESADLVVTGIVGCAGLLPTLAAIRAGKDLALANKETLI-------
------------------------------------------------------------
-----------------------AAGPVVLPELKKSGSRLLPADSEHSAIFQCLQGTPWA
DNARLSTGVPTPGLRRIQLT------ASGGAFRDWDARDLEKATVADATS----------
--------------HPNWSMGRKITVDSASLMNKGLEVIEAHYLFGLDYDHIEIVIHPQS
IIHSMIELA----------------DSSVL-----------------------AQLGWPD
MKLPILYCLSWP--------------------ERQETPWRRLDLT---------------
-------------------EVGQLSFRKPDPAKYPCME----------------------
-------------------------------LAYAAGRAGGTMPAVMNAANEEAVAQFLE
EKIHFLDIPVVI------------------------------------------------
-----------------------EAACERHKTDLIDHPQLDDVLAVDQWARQAVREQVSR
GTRRM------------------------------------------------PAVLAA-
>gnl|BL_ORD_ID|2012 @Synechococcus_sp_CB0101@ 650129593 SCB01_010100010146 1-deoxy-D-xylulose 5-phosphate reductoisomerase [Synechococcus sp. CB0101]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------KA
LSVLGSTGSIGTQTLEIVEEFPDRFRVVALTAGNNLDLL---------------------
-----------------------------------------------------INQIQRH
APEVVALADEAK------------------------------------------------
-----------------------------LPELRERLNQLEP----------SVRPAKLP
ELVGGSDGLCTAAAWPTADLVVTGIVGCAGLLPTLAAIRAGKDLALANKETLI-------
------------------------------------------------------------
-----------------------AAGPVVLPELAKSGSRLLPADSEHSAIFQCLQGTPWA
DTARLSTGVPTPGLRRIQLT------ASGGAFRDWDAADLHKATVADATS----------
--------------HPNWSMGRKITVDSASLMNKGLEVIEAHYLFGLDYDHIEIVIHPQS
IIHSMVELA----------------DSSVL-----------------------GQLGWPD
MKLPILYCLSWP--------------------ERLETPWRRLDLT---------------
-------------------EVGQLTFRKPDPAKYPCME----------------------
-------------------------------LAYAAGRAGGTMPAVMNAANEQAVALFLE
EQIHFLDIPRLI------------------------------------------------
-----------------------DVVCDRHKADLTANPSLDDVLAVDAWSRQAVREAAAR
LQAKA------------------------------------------------PAALPA-
