>Mulan_gi|171542820|ref|NM_024544.2| Homo sapiens mitochondrial E3 ubiquitin protein ligase 1 (MUL1), nuclear gene encoding mitochondrial protein, mRNA
cggttccggcgtcgtgcgtcatcgctgggcgactgatttcgagtttccggtcaggttagg
ccgggggggtgcggtcctggtcggaaggaggtggagagtcgggggtcaccaggcctatcc
ttggcgccacagtcggccaccggggctcgccgccgtcatggagagcggagggcggccctc
gctgtgccagttcatcctcctgggcaccacctctgtggtcaccgccgccctgtactccgt
gtaccggcagaaggcccgggtctcccaagagctcaagggagctaaaaaagttcatttggg
tgaagatttaaagagtattctttcagaagctccaggaaaatgcgtgccttatgctgttat
agaaggagctgtgcggtctgttaaagaaacgcttaacagccagtttgtggaaaactgcaa
gggggtaattcagcggctgacacttcaggagcacaagatggtgtggaatcgaaccaccca
cctttggaatgattgctcaaagatcattcatcagaggaccaacacagtgccctttgacct
ggtgccccacgaggatggcg---tggatgtggctgtgcgagtgctgaagcccctggactc
agtggatctgggtctagagactgtgtatgagaagttccacccctcgattcagtccttcac
cgatgtcatcggccactacatcagcggtgagcggcccaaaggcatccaagagaccgagga
gatgctgaaggtgggggccaccctcacaggggttggcgaactgg------tcctggacaa
caactctgtccgcctgcagccgcccaaacaaggcatgcagtactatctaagcagccagga
cttcgacagcctgctgcagaggcaggagtcgagcgtcaggctctggaaggtgctggcgct
ggtttttggctttgccacatgtgccaccctcttcttcattctccggaagcagtatct---
---------gcagcggcaggagcgcctgcgcctcaagcagatgcaggaggagttccagga
gcatgaggcccagctgctgagccgagccaagcctgaggacagggagagtctgaagagcgc
ctgtgtagtgtgtctgagcagcttcaagtcctgcgtctttctggagtgtgggcacgtttg
ttcctgcaccgagtgctaccgcgccttgccagagcccaagaagtgccctatctgcagaca
ggcgatcacccgggtgatacccctgtacaacagctaatagtttggaagccgcacagcttg
acctggaagcacccctgcccccttttcagggatttttatc---------tcgaggccttt
ggaggagcagtggtgggggtagctgtcacctccaggtatgattgagggaggaattgggta
gaaactctccagacccatgcctccaatggcaggatgctgcctttcccacctgagagggga
ccctgtccatgtgcagcctcatcagagcctcaccctgggaggatgccgtggc----gtct
cctcccaggagccagatcagtgcgagtgtgactgaaaatgcctcatcacttaagcaccaa
agccagtgatcagcagctcttctgttcctgtgtcttctgtttttttctggtgaatcgttg
cttgctgtggacttggtggaggactcagaggggaggaaaggctgggccccgagtacaacg
gatgccttgggtgctgcctccgaagagactctgccgcagcttttcttctttttcctcatg
ccccgggaaacagtctttcttcagaattgtcaggctgggcaggtcaacttgtgttccttt
cccc-tcacctgcttgcctccttaacgcctgcacgtgtgtgtagaggacaaaagaaagtg
aagtcagcacatccgcttctgcccagatggtcggggccccgggcaacagattgaagagag
atcatgtgaagggcagttggtcaggcaggcctcctggtttcgccactggccctgatttga
actcctgccacttgggagagctcggggtggtccctggttttccctcctggagaatgaggc
gcagaggcctcgcctcctgaaggacgcagtgtggatgccactggcctagtgtcctggcct
cacagcttccttgcaaggctgtcacaaggaaaagcagccggctggcaccctgagcatatg
ccctcttggggctccctcatccagcccgtcgcagctttgacatcttggtgtactcatgtc
gcttctccttgtgttaccccctcccagtattaccatttgcccctcacctgcccttggtga
gccttttagtgcaagacagatggggctgttttcccccacctctgagtagttggaggtcac
atacacagctctttttttattgcccttttctgcctctgaatgttcatctctcgtcctcct
ttgtgcaggcgaggaaggggtgccctcaggggccgacactagtatgatgcagtgtccagt
gtgaacagcagaaattaaacatgttgcaaccaaaaaaaaaaaaaaaaaa
>Mus_musculus_gi|18043559|gb|BC019516.1| Mus musculus mitochondrial ubiquitin ligase activator of NFKB 1, mRNA (cDNA clone MGC:28945 IMAGE:4163969), complete cds
----------------------------gcggctgcgtaggggtcgcaggtgatttcg--
------------------------------------------------------------
----------aggcggctggtgcggcttggggtcgccatggagagcggttcgcgaccgtc
gctcggccaggtcatcctgctgggcaccagttcgatggtcaccgccgtactgtactccat
ataccggcagaaggcccaggtcgcgcaggaactcaagggagctaagaagattcatctggg
tgaagatttaaagggcattctttcagaagcaccggggaagtgtgtgccttacgctgtcat
cgaaggagctgtgcggtctgttaaagaaacactcaacagccagttcgtggaaaactgcaa
gggggtgatccagcggctgtcgcttcaggagcataagatggtgtggaaccgaactaccca
cctttggaatgactattccaagatcattcaccagaggactaacactgtgccctttgacct
cgtgccccacgaggacggcg---tggctgtgtccgtgcgagtgctgaagcccctggattc
agtggatctgggcctagagaccgtgtacgagaagttccacccctctgtgcagtccttcac
cgatgccattggccactacatcagtggcgagaggcccaaaggcatccaggagacagagga
gatgctgaaggtgggagccaccctcacggggatcggtgaactgg------tcctggacaa
caacgctgtccgcctgcagccccccaagcagggcatgcagtactacctgagcagccagga
ctttgacagcctgctgcacaggcaggagtctagtgtccggctctggaaggttctggtcct
ggtgttcggctttgctacctgtgccaccctcttcttcatcctgaggaagcagtacct---
---------tcatcggcaggagcgcctgcgccagcagcagctccaggaagagttccttga
acacgaggcccagctgctgagtcaagcctcgcctgaggacagggagagtctgaagagcgc
ctgtgttgtgtgtctgagcaacttcaagtcctgtgtcttcctcgagtgcgggcatgtgtg
ttcctgccgccagtgttaccttgccttgccagagcccaagaggtgcccgatctgtcggcg
ggagatcaccagggtgatacccttgtataacagctaggggtctg----------------
--------------tggtcacactgcaagtgacctttgtcaaggtctgtctgaggccttt
ggtggggtggctgt-------------accttcacatatgatggagg-------------
ggcactggcgagcctcacagctccaacagctggatgtggctttt----------------
------------------------gaacctggacctggtgtgg-gccgtggtgagggccc
cttcttgggagctagatccatgt--gtatgactgaataag--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------accagctcattgtccaggc--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------aaaaaaaaaaaaaaa
>Xenopus_laevis_gi|148226331|ref|NM_001091247.1| Xenopus laevis mitochondrial E3 ubiquitin protein ligase 1 (mul1), nuclear gene encoding mitochondrial protein, mRNA
ctcttggaa---------------------------------------------------
------------------------------------------------------------
-------------------------------------atggagaatggggggcgcccgtc
agtcggacaggttatcctgctcaccaccagttcagccatcaccgcgcttttctattccat
ttaccgccataaataccgatccgtccagactctgaaggaagccaagaagttctgcctgac
tgatgatctccccgcggttctgtcggaccttcccgggaaatgcgtcccctacgcagttat
agaaggggctgtgacttcagtgaaggaagttctaaacagtcagtatgtggaaaactgcaa
gggggtgatccaaaggctgtcgctgaaagagcacaagatggtgtggaacagaaccaccca
cctctggaacgaccatgagaaaatcatccaccagaggagcaacaccgtcccctttgacct
ggcaccggaaaatcccggggagtcgggggtgtcggtgagggttctccggcctttggaagc
cgtggatctgggcctggagaccatttatgagaagttccacccggcggtccagtctttctc
caatatacttggccattacatgaccggtgagcggcccaagggggttcaggagacggagga
gatgctgaaaatcggggcgacgatcacgggtgtcggggagttgg------ttctggacaa
caagaccatcaagctgcagccgcccaaggacgggatgttgttctacctcagctccatgga
ttacgagggactcctggagaaacaagaggtgcagatgcgctggtggaggatcctcagcat
cgtgtttggggtggcctcctgcatcaccctcttttttatcctcagacgcaagtaccg---
---------acactacaaggagaagcagcacctcaagaacctgcaaagagagtttgagga
gtcaagggcccgacagagggtccagcaggagccacagaacaaggaggaagtacaaaaccc
ctgctccatctgtctcagcaccgaaaagtcctgcgtcttcctggagtgcggccatgtttg
ttcctgcatcagctgctaccaggcgctccccagccccaaaaaatgccccatatgtagaaa
tttcattgaccgcattgttcctctttataacagctaaggggccc----------------
------------------------------------------------------------
------------------------------------------------------------
--------------------cccaaatttctgtctgtgacctca----------------
----------------------------------------------cgtggtgtgtgcac
tct---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------aaaatcaccaaaaaaaaaaaaaaa
>Danio_rerio_gi|148922853|ref|NM_001098760.1| Danio rerio mitochondrial E3 ubiquitin ligase 1b (mul1b), nuclear gene encoding mitochondrial protein, mRNA
---------------------------agtgaacgccagcacaactttagtgaagctggt
gtgtagattgaagg----------------------------------------------
-------------------------------------atggaggccagcggcaaaccctc
cacagcacagattgtgttgctggccactagttcagcactgacagctgttctatacaccat
atacaagaggaaatccagccatgttgcgagattaagggaagccaagaagatgtcattaaa
cccagagctgaaaactattctcagtgaagcaccaggaaaatgtgttccctatgcagttat
tgaaggagttgtgcgctcagtgaaagaaaccctgaacagccagtttgttgacaactgtaa
aggggtcatccagaggttgaccctaaacgagaagaagatggtgtggaatcgcacaacgaa
tttatggaatgactgtgaaaaggtcatccaccagcgcaccaacaccgttccctttgacct
cgccccacacgacgacactg---tacccacaacagtccgagtgctccgtccccttgatgc
ggctgaactggatctagagaccacatatgaaaacttccacccttcccagcagtctctgac
caacgtcattggccacttcatcagtggcgagcgtccacagggcatccaggagaccgaaga
aatgctacgtttgggtgccagcatgaccggtgttggggaactag------tgctggacaa
caatctggtgcgtcttcaaccgccaaaaaagggcctgcggtacttcctcagccgcctgga
ttatgacacgctccttagcaaacaagagggtcacttgaggatctggagggtcttgacggt
gctccttggattaactgcctgcgctacatttttctacctgctttggagacagtatgt---
---------gctgcgaaaggagcggagaaaagagcaaagtgtgctagatgaataccggaa
gtggcagagtaaacgttttcaggagctccacttggcgaaggaggatgtttctcccacagc
atgcacaatttgcttgaatcacgagcgttcttgtgtgtttttggagtgtggtcatgtgtg
tgcctgtgaggggtgttatagggccctgcctgaacctaagaagtgccccatatgccgggc
gacaatagatagaatcgtctcgctgtataacagttaaaggcctt---------------a
ttgtgaatatatagtacttgaaatgaggcatagcatttcatgcctttatctagagctgtg
atgaaaaaaatggttcgagatatcaattctgattctccgaatgcatcgctaaactctctt
gaattgttctgagcttagttttttaacagcagagtgtgttttaggctatttattaaggca
ctgtatcc-tttacaaaaacccatactcttctgcttgcatccaattcctaacaaataccg
cctc---aaactaaaatcatcgttaataaagtaggaaatgtttaagcaacttacaaagg-
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------tttt
catagtgagctgtgtttacattaattttgtgacatgcagtaagtcaacttacacagttca
ccccaatgcacactcttcctcatgagaattgtaaaagtgtacaattaaataataaacata
gagcaccatctgctgt--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------aataaactaaaaaaaaaaaaaaaaaaaaaaaa
>Drosophila_melanogaster_gi|442630078|ref|NM_139590.4| Drosophila melanogaster mitochondrial E3 ubiquitin protein ligase 1 homologue (Mul1), mRNA
cgagcagcgggaaacacagcaacactgagtaaacatatgtttttgtagcgtaatataaat
aaaatagcataacacaaa------------------------------------------
-------------------------------------atgga---------------att
tttacacgaatccgttgcactgggcgtggatctgctaatacttggcctgtgtgcgcgcga
gtacgtgcactacaagcgaactgccaaggtgctgaaggcggcaccacaatacaacatcga
tggagacctaaaatcggtggtggagcggcagcgcgacaagaagataccatatgcggtaat
ccggggcacagtgacgcccatcggggtgccactgaggagctccctggtgcccagtgtgag
tggagtgctgcagattgtgaagctgcatgagcacagggtaacgcgcg---gattcgccgg
cttctggacggaacaacacaagttgctgcacgaatccgccaacgagatgcccttcgagtt
gcgtaaccagagccatggtg---------------tggagattgtggacgccttgagtgc
cgccgtcttggacgtggacgtggtctacgacaactacgagccctccaatctgtccctctt
cgaccatgtgtttggtttcttctctggcgtccgtcagaggggattgcaaacgacggagga
ggtgctcagagaaggcagcttcctgaccgctattggtgaactgg------agttggatgg
cgatactctgcgcatgcagccctccaatgagggaccgctcttcctgaccactgccaccaa
gtcc---acgcttattaagcggttcgaagatgccaagacaacgacgatactcaagctggt
tgtgtgcagcaccatctctgccatcctggttgccttcattgccaagaaactctaccgaaa
acgaaagcaggagcgggaggaggccaaaattcgcgaacgcctggatacggagcgtcggga
gcggagggcgaggagtcgtcctcacactctgtcccaggatcaa---------------ct
ctgcgtggtgtgctccaccaatcccaaggagattatcctactgccatgtggtcatgtgtg
tctctgcgaggactgtg------cccagaaaatctccgtcacctgccccgtgtgtcgtgg
tagcatcgtctccaaggcagccgccttcatcgcctaggaaccaacgaagatgccaacaag
atcaccttgtacctgtgt------------------------------------------
------------------------------------------------------------
-------------------------gcgccaaactttttatttgttacaatgctcatgta
cggcatttatttaaaattattgaaagtcttgacatcggaatg------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Drosophila_persimilis_gi|195170746|ref|XM_002026137.1| Drosophila persimilis GL16061 (Dper\GL16061), mRNA
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------atgga---------------tat
tctaaacgaatctgttgctctcggcgtcgatttaattattttaggcatctgcgtacgcga
atatatgtacaacaagagggttgcaggactattaaagactgcaccgcaatacaacatcga
tggagatctcaaatccattgttgaacggcaacagaccaaaagtataccatatgcggtgat
ccggggtactgtcacgcccattggcgtgcccctgcgcagctcgctggttcccagtgtcag
cggagtgctgcagattgtgaagctccacgagcaccggatatcccggg---gcttttccgg
cttgtggatggaacagtgcaagcttctgcataaatctaccaacgagatgcccttcgagtt
gcgcagtcaagagcatggcg---------------tggagattgtggatgtcctgagcgc
agctgttcttgatgtggacgttgtctacgacagctacgagccctctacactctccgcctt
tgaccacatcttcggattcttcagtggcgtacgacaaaaaggcatccagaccacggagga
agttctgcgcgagggcagcttcctgacagccatcggaaagctag------agctggatgg
aaactcattgcgtatgcaaccttcaccggaaggaggactatttctgaccaccgccacaaa
atct---tccctcattaagcggtttgaggacgccaaatggacatggatattaaagattgc
tttttgtggcgccgtatcagctttcctaatcggcctcatagcaaggaaaatatatcgcaa
gaaaaagcagcagaaagaggaggcaagaatacacaacctcctggaaacagagcgtcgcga
acgccgtagccgcagtcgtcccctcacactatccgaagatcag---------------ct
atgcgttgtctgcgtaacaaatcccaaagagataattttactgccctgtggccatgtgtg
tctatgcgaggactgct------ctccccacattgccactcactgccccgtgtgtcgcgg
caaaatcgtgtcaagatccgcggccttcatcgcttag-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Tribolium_castaneum_gi|91093712|ref|XM_962280.1| PREDICTED: Tribolium castaneum similar to CG1134 CG1134-PA (LOC655721), mRNA
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------atgga---------------tta
tttaacggagggcatagccctgggtgtagatctcgtgatcttggcggcatgtatcaagca
gtactacaagaacaagaatgccatggctatgatccagggggccccctatctcaccatcaa
taaagacttgaaagaaatagttgagacacatccagagaaaaaactgtcatacgtatccat
aaggggaactgttaaaccactaggtaggcctattgtcagcagcaataatccaaatgtaac
aggcgttgtgcaattattacgaattaaggagcatgtaatccagcgga---gtacgacagg
attttggtcggactccgaacgtgttgtgcaggaagtccacaatgttatgcctttttccat
tggcaataaggcggtgtttg---------------tggaagttgcggacccgttagctgc
tgacgtcttagatatggatacgatatcggacgtcttcaatccgactgttccgagtgtcat
ggaccacatctggggcttctttgccgggatcaggcaacggggggtccagtcgactgagaa
aatgttaagggagggcaccactattacggggattggggagttggtttattcacaagattc
cagcatgttgcggctgcagcccccatcaaacggggcccccttttatttaacaaatatgca
agtcacgtcgctggttaaaaagttagacggctctaaacgaaattacaagttactgtgtat
attattcggaacaatcggtttagttattgggggtttcataattcggaaatatttgcgcca
taaagacagacaattggaggaaagtaagcggaaacaacaactggaagaatcaagacggaa
gaggcggcgacaaatgcgtgatcaaaatttaccagagaaccaa---------------at
ctgcgtcgtttgtaaaaataacccaattgagataattttactgccttgcggccacgtgtg
tctatgcgaggactgct------cactcgacatctctgccaactgtcccgtttgcagggc
tccaatagagaaaaaatcagtagcctatgttgcgtaa-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
