>SP1 gi|145337145|ref|NM_105064.3| Arabidopsis thaliana E3 ubiquitin ligase-like protein (AT1G63900) mRNA, complete cds
atgagaatatt-------------------------------------------------
-----------------------------------gagagagatcgaagcaaaggatcat
tcaattccaaccctctgaatcttttaatttcccctttcgaaattctcctcttctttcact
gcttctagtttctaattcttcaaactcttcctcgattcatactcataactctcattagct
aatttcgcatgatcttcttccatctctctgtgttctaaatccagattcgtttcactccca
tctctatttcattcaattcgctgcatccagattcaaaacctacctctatctctctgctca
tcaataacttcaaaggtattgttgttcttctgcaaacaagtaagagtgacttcagagtct
gatgattccttggggtggagttacttgctgcctcagcgccgctgctctttatcttctcgg
ccggagtagt------ggcagggatgctgaagtactcgaaacagtcactagggttaatca
gctcaaggagttagctcaattgctagaattagat---agcaagattctgcctttcattgt
tgcggtatcaggaagagtcggctctgagacacctatcaaatgcgagcatagtggcatacg
cggtgttattgttgaagaaacggcggaacaacatttcctgaaacataatgagacgggttc
ttgggtacaagatagtgcgttgat---gctatcaatgagcaaagaggttccttggtttct
ggacgatgggacaagccgtgtccatgtaatgggagctcgtggtgcgacgggttttgcctt
gactgttggtagtgaagtttttgaagagtcaggac---gctcgcttgtacgaggaacact
tgattatcttcaaggacttaagatgcttggagttaagcgcattgagcgtgttcttccaac
tggaataccgctaacaattgttggtgaggctgtcaaggacgatattggagaattcaggat
tcaaaaacctgacaggggccctttctacgtctcttctaaatcactcgatcagctcatttc
taatttgggaaaatggtcaaggttgtacaaatatgcctccatgg------------gttt
tactgttcttggtgtgttcctaattacgaagcatgtcattgactctgttcta--------
----------------------------------gagagaagacggcggagaca------
------------------gttacaaaaaagagtgcttgacgcagcagcaaagagagctga
gctagagagt------gaaggttcaaacgggaca------cgtgagagcatttcagattc
taccaagaaa---------gaagacgctgttcctgatctctgtgtgatatgcctagagca
ggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcaccgcatgctcctc
ccacttg------------accagctgtccactttgtcggagacgaatagatctggcggt
taagacatatcgtcactgaacaacaactcaggcctcagaaacattctctacttgagtctt
gtctgtaaataccgcaaaatcaaaacattacacagtttagcgttcgatattccctttggt
ttgatttcgacaacaaaacattttgaattatatagaaacataaggtgtttactcgatttg
caaaacagtacattcgtgtttacttattcgtgttgttgccaatgccatgaggtg
>A.lyrata_gi|297840100|ref|XM_002887886.1| Arabidopsis lyrata subsp. lyrata zinc finger family protein, mRNA
-tgagaatatt-------------------------------------------------
-----------------------------------gagagagatcgaagcaaaggatcat
tcaaatccaacactctgaatctt---------------------------ttctttcact
gcttctagtgtctaattctttaaactcttcctcgattcatactcatagctctcgttagct
aatttctcatgatcttcttccatcgctctgtattct-aatccagattcgtat-gctctca
tctctatttcattcaatttcactcatccagattcgaccattacctctatctctctactca
tcaatcacttcaaaggtattgttcttcttcttcaaacaagtaagagtgacttgagagtct
gatgattccttggggtggagttacttgctgcctcagcgccgccgctctttatcttctcgg
tcggagtagt------ggcagggatgctgaagtactcaaaactgtcactagggttaatca
gctcaaggagttagctcaattgctagaattagat---agcaagattctgcctttcattgt
tgcggtatcaggaagagtcggctctgagacacctatcaagtgtgagcatagtggcattcg
cggtgttattgttgaagaaacggctgaacaacattttctgaaacataatgagacgggttc
ttgggtgcaagatagtgcattgat---gttatcaatgagcaaggaggttccttggtttct
ggacgatgggacaagtcgtgtccatgtaatgggagctcgtggtgcaacgggttttgcctt
gactgttggaagtgaagtatttgaagagtcaggac---gctcgcttgtacgaggaacact
tgattatcttcaaggacttaagatgcttggagttaagcggattgagcgtgttcttccaac
tggaataccactaacaattgttggtgaggctgtcaaggacgatattggcgaattcaggat
tcaaaaacctgacagggggcctttctacgtctcacctaaatcactcgatcaactcatttc
taatttgggaaaatggtcaaggtggtacaaatatgcctctatgg------------gttt
tactgtttttggtgtgttcctaattacgaagcatgtcattgattctgttcta--------
----------------------------------gagagaagacgtcggagaca------
------------------gttacaaaaaagagtgcttgatgcagcagcaaagagggctga
gctagagagt------gaaggttcaaacggggca------cgtgagagcattgcagattc
taccaagaaa---------gaagacgctgttcctgatctctgtgtgatatgcctagagca
ggagtacaacgctgtgtttgttccgtgtggtcatatgtgctgctgcactgcatgctcctc
ccacttg------------accagctgtccactttgtcggagacgaatagatctggcggt
taagacatatcgtcactgaacaacaactcaggcctcagaaacattctctactcgagtctt
gtctgtaaataccgcaagatgaaaacattaca-gtttaggcgttcaatctccccttttat
ttgatttcgagaacaaaacattttgaattatatagaaacataaggtgtttactcgatttg
cagaacagtacattcgtgtttacttaaccgtatcgctgctaatgccatgaggtg
>Brassica_rapa_Bra027667 CDS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atgattcattggggtggagttacctgctgcctcagcgccgccgctctttatcttctcgg
tagcagtagc------ggcagggacgctgaagttctcaaaaccgtcactagggttaacca
gctcaaggagttagcgcaattgctagaattagatagcagcaagctcctgcctttcattgt
ggctgtatctggaagagttggctctgacacacctatcaagtgcgagcatagtggcatacg
cggtgttatcgtcgaggaaactgcggagcaacattttctgaagcacaatgagactggttc
ttgggttcaagatagtgctttgat---gctatctatgagtaaagaggttccttggtttct
ggacgatgggacaagtcgtgtgaatgtagtgggagctcgtggtgcaacaggctttgcctt
gaccgttggaagtgaagtgtttgaagagtcaggga---ggtctcttgtacggggaactct
tgattatctccaaggccttaagatgcttggagtaaagcgcattgagcgtgttcttcctac
tggaatgcctctaactattgttggtgaggctgtcaaggacgatattggagatctcaggat
tcagaaacctgaaagagggcctttctacgtctctcctaaatcactagatcagctcatttc
caatttggggaaatggtcaaggtggtacaagtatgcctctatgg------------gttt
aactgtttttggtgtgtttctaattacaaagcatgtcattgatcatgttctt--------
----------------------------------gagagaagacgccatcgaga------
------------------gttacagaaaagagtgcttgatgcagcagctaagagagctga
---agagact------gaaggttcaaacggggca------catgagagcgtttcagattc
taccaagaaa---------gaaggcgctgttcctgatctctgtgtgatctgtctagagca
taactataatgctgtgtttgttccgtgtggtcatatgtgctgctgcaccgcatgctcctc
ccacttg------------accagctgtccactttgccgaagacgtatagatcaggtggt
taagacatatcgtcactga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Thellungiella_halophila_Thhalv10008106m CDS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atgattccttggggtggagttacctgctgcctgagcgctgccgctctttatcttctcgg
ccggagtagt------ggcagggatgctgaagtactcaaaaccgtcactcgggttagcca
gcttaaggaattagcgcaattgctagagttagatagcagcaagctcctgcctttcattgt
ggcggtatcaggaagagttggctctgagacacctatcaagtgtgagcatagtggcatacg
cggtgttatcgtcgaggaaacggcggaacaacattttctgaaacacaatgagacgggttc
ttgggtacaagatagtgcattgat---gctgtcaatgagtaaggaggttccttggtttct
ggacgatgggacaagtcgtgtcaatgtggtgggagctcgtggtgcaacaggatttgcctt
gactgttggaagtgaagtatttgaagagtcagggc---gttcgcttgtacgaggaacact
tgattatcttcaaggcctcaagatgcttggagtaaaacgcattgagcgcgttcttccaac
tggaatgccgctaacaattgttggtgaggctgtcaaggacgatattggtgatttacggat
tcagaaacctgaaagggggcctttctacgtctctcctaaatcactcgatcagctcatttc
taatttgggaaaatggtcaaggtggtacaagtacgcctccatgg------------gttt
aactgtttttggtgtgtttctaataacaaaacatgttattgattctgttcta--------
----------------------------------gagagaagacgacggcgaga------
------------------gttacagaaaagagtgcttgatgcagcagctaagagagctga
gcgagagagt------gaaggctcaaacgggaca------catgagagcgtttcagattc
taccaagaaa---------gaagacgctgttcctgatctatgtgtgatctgcctagagca
ggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcaccgcatgctcttg
ccacttg------------accagctgtccactttgccggagacgaatagatcaggtcgt
taagacttaccgtcactga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Carica_papaya_evm.model.supercontig_9.121 CDS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atgattccatggggaggaatcacttgctgcatgagcgcggctgccctttatctgcttgg
caggagcagc------ggcagggatgcggatattcttagaaaagttacgcgagttaatca
gttgaaggaattggcgcagttgcttgacattgaa---agcaaaataatgccattgattgt
tgccatatctggaagagttggctctgagacaccaattagttgcgagtacagcggcttaag
gggagttatagtggaggaaacggctgaacaacattttctcaaacacaatgatgctggttc
ttggatacaagatagtgccctaat---gctgtcaatgagtaaagaggttccttggtacct
ggatgatgggactgctcgtgtatttgtagtaggagcacgaggtgctactggttttgttct
tactgtggggagtgaagtatttgaagaatcagggc---ggtctctcgtacgaggaacgtt
ggactatctccaaggcctcaagatgcttggagtcaaacgtattgaacgtgtacttccaac
tggtacttccttgacagttgttggtga----------gatgacattggaacaattcagat
acgaagaccgcacaaacggcctttttacgtgtctc-caaatcaatggatcacctgatttc
caa-ttagggaaatgggcaaggtggtacaagtatgcttcgatgg------------ggct
aacattccttggtgtttttctaattgcaaagcgttctattgagtatgttttg--------
----------------------------------gagagaaggcggcgacgaga------
------------------gttgcagaaaagggttcttgccgcagcagcgaaaagatcagg
gcaagataat------gaaggttcaaatataata------cctgaaaatgggttggatgg
tgctaagaga---------gagcatctgatgccagatctatgcgtgatatgccttgagca
agagtacaatgctgcttttgtcccgtgtggtcatatgtgttgttgtatgacttgctcttc
ccacttg------------acaaactgcccgctttgccggagacggattgagcaggtgct
caggaccttccgccattga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Spl1_gi|30102701|gb|BT006461.1| Arabidopsis thaliana At1g59560 gene, complete cds
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atgatacatttggctggatttacatgttgcttaggcggcgtcgctctttatcttcttac
caggagcaca------ggcagagata---------tcaaatcaatcactagggtttacca
actcaaggatttggaacaattagtagaagtagag---agcaaggtggtacctttgatcat
cgcagtatcaggagatgttggctctgagactcctattaagtgtgagcatagttatgttct
cggtgtatttctcaagagaacggcagaacaacaggttttgagacgtaattggagattttc
atgggttcgaaatagtacattgat---gcagccgatgactaaggaagtcccctggtatct
ggacgacgggacaggtcgtgtgaatgtagatgtatctcaaggtgaattaggcttggcgtt
gacggttggtagtgatgtatttgaaaaggcagagccggtatcgcttgttcaaggagcgtt
gggttatcttaaaggctttaagatacttggagtaagacacgttgagcgtgttgtcccaat
tggtacaccgcttacagttgttggtgaggctgttagggatggcatggggaatgtcaggat
tcaaaaacctgagcaaggacctttctacgtcacttatataccgctagatcagctcatctc
taaattgggagatttgtcaaggaggttcaagtatgcctccatgg------------gttt
aactgttcttggtgtgattcttatttcaaagcctgtgattgaatatattctaaagagaat
tgaag---------------------atactctagaaagaaggcggcgacaatt------
------------------cgcactgaaaagagttgttgatgcagctgctaggagagccaa
accagtaact------------------------------------------ggaggtgg
tacaagcaga---------gatggtgatacacctgatctctgtgtggtttgccttgacca
gaagtataacaccgcttttgttgagtgtggtcatatgtgctgctgcacaccatgctcctt
gcaacta------------aggacctgtcctctttgccgggaacgaatacaacaagtttt
gaaaatttaccgccattga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>A.lyrata_338432 CDS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atgatacatttggctggatttacgtgttgtttaggcggcatcgctctttatcttctcag
ccggaacaca------ggcggagttg---------tcaaatcaatcactagggttaacca
cctcaaggatttggaacaattg------gtagag---agcaaggtgtttcctttgatcat
agcagtatcaggaattgtcggctctgagacacctatcaagtgtgagcatagtgacatact
cggtgtttttctcaagaaaacggcagaacaacaggttttgagtcgtaattggaggttctc
gtgggttcgaaagagtacattgat---gcagccgatgactaaggaagtcccgtggtttct
ggacgatgggacaggtcgtgtgaatgtagcggtatctcaaggtgaaataggcttggcgtt
gacggttggaagtgatgtatttgaaaaggcagagccggtttcgcttgttcaaggaacctt
ggattatcttaaaggcctcaagatacttggagtaagacgcgttgagcatgttgtcccaat
tggtacaccgcttacaattgttggtgaggctgttaaggatggcatggggaatgtcaggat
tcaaaaacctgagcaaggacctttctacgtgtcttatgtaccgctcgatcaactcatctc
taaattgggagaatggtcaaggaggttcaagtatgcctccatgg------------gttt
aactgttgttggtgtgattcttctttcaaagcctgtgattaaatatattctaaagaaaat
tgaag---------------------atactctagagagaaggcggcgacaatt------
------------------gttacagaaaagagttgttgatg-------------------
------------------------------------------------------------
-----------------------------tacctgatctctgcgtgatctgccatgacca
gaagtataacaccgcttttgttcagtgtggtcatatgtgttgctgcttaacatgctcctt
gcgattg------------acgacctgtcctctttgccgggaacaaatacaacaagtttt
gaagatttaccgccattga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Brassica_rapa_Bra040424 CDS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atggaaccttggagtgggtt---atgttgcataggcgccgttgctctttatcttctcag
ccgccgaaca------gccagggatgttgactttctcaaatcggtcactagggttgacca
gctcaaggatttg------------------gag---agcgcggtgttgccttcgatcgt
ggcagtatcaggaacagttggctcggagacacccatcaagtgtgagcacagtggcattct
ctctgttattctccaggaaaccgcagagcaacagtttctgaaacgtaactggaagttttc
gtgggttcaagacactgcattgat---gctccccgtttgtaaggaagtcccttggtttct
ggacgatgggacaggccgcgtgatcgtagagggagctcgaagtggaataggttttgagtt
gaccgtcggaggtgaagtatttgaaaagccagaggcgtcttccctcgttcgaggaacctt
agattttctccgaggcctcgagatgcttggaataagacgcattgaacgtgttctcccagt
tggtacacgccttaccgttgttggtcagactataaaggatggtgttggggatgtgaggat
tcagaaacccgatcaagggccattctacgtctcccctataccgctcgatcacctcatctc
taaagtgggaaagtggtcaaggaggttcaagaaagcctccatgg------------gttt
agctgttgttggtgtgattctgatatcaaagcctgtgattaaatatattctagtgagaac
aggag---------------------attttcttgagagaaggcagcagcgact------
------------------gttaaagaaaagagttgttgatgcagctgctaagagaaagaa
acttgcagctcctaagagagaggaacgagtgacc------agtaaaggattggagaatgg
taaaagcaga---------gatggcgatgaacatgatcgttgtgtggtctgccttgagag
gaaatgtgacgccgcttttgttccgtgcggtcatatgtgctgctgcttgacatgcgcctt
gaagttg------ctgggaaagccttgtcctctctgccggaaacgaggaattcggatttt
gaagatttaccgcaattga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Solanum_lycopersicum_gi|460393457|ref|XM_004242278.1| PREDICTED: Solanum lycopersicum mitochondrial ubiquitin ligase activator of nfkb 1-A-like, transcript variant 2 (LOC101250130), mRNA
actcccaaattattttatggctacaaaaaaaaaaaaaaaaaaaaacgaagaagaagaaga
agaagaagtggatggatggattatagagttgttgaaggagaggtagataaagagcatgaa
cataactgcactctcaagtttcctctcaaccactcttagcatcttatggagtgtcagctt
cttcaaattccttttattttttaatcccaatttgtctcttcagttttactgttataaagc
cacatatgctctgcccttctgtaattgctctatttttgtttttccatgattgcttgtcgc
ctgaaacttgtgttgcttagtcataatttcattcgttaggtttaggttctattatccctt
cgagctaccggaa-----------------------------------------------
-atggttccatgggccggactctcttgctgtttgagtgcagctgctctttaccttctcgg
taggagcagt------ggaagagatgctgaagttcttaaatccgttacaagggttaatca
attgaaggatcttgcacaactactagatactgca---tccaaggtgttgcctctggtggt
tactatatctggaagggttggatcagatacaccaattaactgtgagtacagtggtctacg
aggcgtgattgtggaagaaactgccgaacaacattttctgaaacacaatgatgcaggttc
ttggatacaggattctgccttgat---gctctcaatgtgtaaagaagttccgtggtacct
ggatgatggcacaggtcgcacttttattgttggtggccgtggtgccacgggtttggtact
gacagttggaagtgaagccttcgaggaagcaggga---gatcatttgtgcgagggacatt
ggattatcttcaaggtcttaagatgcttggagtaaagaggattgaacgtgtgctgccagt
tggtactcctttgactgttgttggcgaggctgtcaaagatgacattgggacagttcggat
ccagcgaccacacaaaggcccattttatatctctcataaaactattgaccagctcattgc
aaatcttgggagatgggcaaggtggtacaagtatgcttcaatgg------------gttt
tactgctgtcggtgtatatctacttgtgaagcatacttttcattatatgatg--------
----------------------------------gaaagaaagcgtcactggga------
------------------attgcgcaggagagttcttgctgctgctgctaaaagagcagg
agatgaggat------gaaggttctgatgctaca------gctgagaatggagtggat--
----aataag---------gacctcttaatgccagatctatgtgttatatgtctggagca
ggaatacaactcagtttttgtcccgtgtggtcatatgtgctgttgcatgacgtgctcttc
acacttg------------acaaactgcccactatgtaggagacggatcgagcaggttgt
gaaaacttttcgccattgagcagaaagctgccttgttgaaatggccattttctgactcgc
tcataaaaatcattcggatattaacttgtagattgtattgaaagctggattttgtcagag
ttttatgtcattatgatgtatgtataatagcctctctccatctcaacggttaaactagca
------------------------------------------------------
>Brassica_rapa_899295 CDS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atgatacatttaggtggattgacatgttgcgtaagcggcggcgttctttatcttctcag
tatgatacca------ggcagcttttttgagatgctcaattcagtcactagggttcacca
gatcaaggatttggagaatttgctacaagtagag---ggcaag------------atcat
cgcagtctcagg------------------------------------------------
------------------aaccgcacaacaacttttcttgaaacgtaattggttgttttc
atgggttgaagatagtaaatggat---gcttccacaggctaaggaagtcccgtggtatct
------------------------------------------------------------
------------------------------------------------------------
---------------------gatgcttggagtaagacgcactgagcatgtcctcccaat
tggtacaccggttacagttgttggtgaggctgttaaagacggtatccggggtttcaggat
tcaaaaacccgagaagggacttttctttgtctcacctgtaccgctcgataagatcatctc
tccgatgggaaagtggttaaggaggttcaaatatgtctacgtag------------gttt
aactgttgttggtgtgattctgatttcaaagcctgtgattgagtatattcta--------
----------------------------------gagagaaggcgggggcgatt------
------------------gttacggaaaagagttgctgatgcagctgctaagagagccaa
attagtagct------agaggattggaaactcaa------catgagaacagcttagatag
tacaagcaga---------gatagagatgtacttgatctctgtgtgatctgccttgagca
gaagtatgacgcaacttttgtaaagtgtggtcatatgtgctgctgcttaacatgctcctt
gcacgtg------------aagacctgtcctatttgccggagaccaatagaacatgtttt
gaagattgaccgccgttga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Brassica_rapa_Bra007725 CDS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-atgataagttggagtggattcaaatgtttcatatgggcctaccttctttaccttctcag
ccggagaacaggcggcggcggcgatgttgaatttttcgattcggtcactaaagttgacca
cctcaaaggtctagcggaattgctagaagaaggg---agagaggtcaggcctttgatcgt
cgctgtaacaggatcagttgcctctgccacacctttcaaatgtcagcgtagtgaaatgct
tgctgttattctcgaggaaacggaagagatacagtttctgaaacgtaactggaagttttc
gtgggttcaagacactgcatccatcagcctccccatcactaagcaagtcccttggttcct
ggaagatgggacaggccgcgttaatgtatctggagctgaaactgcattaggctttgcttt
cactgtgggaagtgaagtatttgaaaagcctgaggcttcttcgcttcttccaggagcatt
agcttatctccaaggcctcaagatgcttggagtaagacgctttgagtatgttctcccaat
tggtacatggcttacggttgttggcgaggccgtaaaagatggtagcgggaatgtcaggat
tcaaaaacccgatcaagggcctttctacatctcacctaaacccctcgatcaactcattcc
taccttaggaacgtggtcaaggatattcaagtatgcctccatgggagcctccttctgttt
cactgttcgtggtgtgattataacttcaaagcctttgattatatatattctacatgtgat
tgaagatattctatttatgtttggatatattctatggagaatgcggcagggactgcctat
tctgaaaaaacatgtgacgttactgaaaagagttttttgtgcagctgcaaatagaacgag
acaagcgact---gaagaaggtttgtgtgaatcatttttccctgaatatgcttgtgaatt
tgctctgattatatctctcgcaccagatgtacctgatctctgtgtgatctgccttgaccg
aaagtgtgacgccgttttccttgagtgtggtcatatgtgctgctgcttaacatgctcctt
gtccttggagttacaagggaagcgttgtcctctttgccgtaaaccagtagt---ggtttt
gaagatttaccgcatttga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
