>SP1 gi|145337145|ref|NM_105064.3| Arabidopsis thaliana E3 ubiquitin ligase-like protein (AT1G63900) mRNA, complete cds
atgattccttggggtggagttacttgctgcctcagcgccgctgctctttatcttctcggc
cggagtagtggcagggatgctgaagtactcgaaacagtcactagggttaatcagctcaag
gagttagctcaattgctagaattagat---agcaagattctgcctttcattgttgcggta
tcaggaagagtcggctctgagacacctatcaaatgcgagcatagtggcatacgcggtgtt
attgttgaagaaacggcggaacaacatttcctgaaacataatgagacgggttcttgggta
caagatagtgcgttgatgctatcaatgagcaaagaggttccttggtttctggacgatggg
acaagccgtgtccatgtaatgggagctcgtggtgcgacgggttttgccttgactgttggt
agtgaagtttttgaagag---tcaggacgctcgcttgtacgaggaacacttgattatctt
caaggacttaagatgcttggagttaagcgcattgagcgtgttcttccaactggaataccg
ctaacaattgttggtgaggctgtcaaggacgatattggagaattcaggattcaaaaacct
gacaggggccctttctacgtctcttctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggttgtacaaatatgcctccatgggttttactgttcttggtgtgttccta
attacgaagcatgtcattgactctgttctagagagaagacggcggagacagttacaaaaa
agagtgcttgacgcagcagcaaagagagctgagctagagagtgaaggttcaaacgggaca
cgtgagagcatttcagattctaccaagaaagaagacgctgttcctgatctctgtgtgata
tgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcacc
gcatgctcctcccacttgaccagctgtccactttgtcggagacgaatagatctggcggtt
aagacatatcgtcac
>A.lyrata_gi|297840100|ref|XM_002887886.1| Arabidopsis lyrata subsp. lyrata zinc finger family protein, mRNA
atgattccttggggtggagttacttgctgcctcagcgccgccgctctttatcttctcggt
cggagtagtggcagggatgctgaagtactcaaaactgtcactagggttaatcagctcaag
gagttagctcaattgctagaattagat---agcaagattctgcctttcattgttgcggta
tcaggaagagtcggctctgagacacctatcaagtgtgagcatagtggcattcgcggtgtt
attgttgaagaaacggctgaacaacattttctgaaacataatgagacgggttcttgggtg
caagatagtgcattgatgttatcaatgagcaaggaggttccttggtttctggacgatggg
acaagtcgtgtccatgtaatgggagctcgtggtgcaacgggttttgccttgactgttgga
agtgaagtatttgaagag---tcaggacgctcgcttgtacgaggaacacttgattatctt
caaggacttaagatgcttggagttaagcggattgagcgtgttcttccaactggaatacca
ctaacaattgttggtgaggctgtcaaggacgatattggcgaattcaggattcaaaaacct
gacagggggcctttctacgtctcacctaaatcactcgatcaactcatttctaatttggga
aaatggtcaaggtggtacaaatatgcctctatgggttttactgtttttggtgtgttccta
attacgaagcatgtcattgattctgttctagagagaagacgtcggagacagttacaaaaa
agagtgcttgatgcagcagcaaagagggctgagctagagagtgaaggttcaaacggggca
cgtgagagcattgcagattctaccaagaaagaagacgctgttcctgatctctgtgtgata
tgcctagagcaggagtacaacgctgtgtttgttccgtgtggtcatatgtgctgctgcact
gcatgctcctcccacttgaccagctgtccactttgtcggagacgaatagatctggcggtt
aagacatatcgtcac
>Brassica_rapa_Bra027667 CDS
atgattcattggggtggagttacctgctgcctcagcgccgccgctctttatcttctcggt
agcagtagcggcagggacgctgaagttctcaaaaccgtcactagggttaaccagctcaag
gagttagcgcaattgctagaattagatagcagcaagctcctgcctttcattgtggctgta
tctggaagagttggctctgacacacctatcaagtgcgagcatagtggcatacgcggtgtt
atcgtcgaggaaactgcggagcaacattttctgaagcacaatgagactggttcttgggtt
caagatagtgctttgatgctatctatgagtaaagaggttccttggtttctggacgatggg
acaagtcgtgtgaatgtagtgggagctcgtggtgcaacaggctttgccttgaccgttgga
agtgaagtgtttgaagag---tcagggaggtctcttgtacggggaactcttgattatctc
caaggccttaagatgcttggagtaaagcgcattgagcgtgttcttcctactggaatgcct
ctaactattgttggtgaggctgtcaaggacgatattggagatctcaggattcagaaacct
gaaagagggcctttctacgtctctcctaaatcactagatcagctcatttccaatttgggg
aaatggtcaaggtggtacaagtatgcctctatgggtttaactgtttttggtgtgtttcta
attacaaagcatgtcattgatcatgttcttgagagaagacgccatcgagagttacagaaa
agagtgcttgatgcagcagctaagagagctga---agagactgaaggttcaaacggggca
catgagagcgtttcagattctaccaagaaagaaggcgctgttcctgatctctgtgtgatc
tgtctagagcataactataatgctgtgtttgttccgtgtggtcatatgtgctgctgcacc
gcatgctcctcccacttgaccagctgtccactttgccgaagacgtatagatcaggtggtt
aagacatatcgtcac
>Thellungiella_halophila_Thhalv10008106m CDS
atgattccttggggtggagttacctgctgcctgagcgctgccgctctttatcttctcggc
cggagtagtggcagggatgctgaagtactcaaaaccgtcactcgggttagccagcttaag
gaattagcgcaattgctagagttagatagcagcaagctcctgcctttcattgtggcggta
tcaggaagagttggctctgagacacctatcaagtgtgagcatagtggcatacgcggtgtt
atcgtcgaggaaacggcggaacaacattttctgaaacacaatgagacgggttcttgggta
caagatagtgcattgatgctgtcaatgagtaaggaggttccttggtttctggacgatggg
acaagtcgtgtcaatgtggtgggagctcgtggtgcaacaggatttgccttgactgttgga
agtgaagtatttgaagag---tcagggcgttcgcttgtacgaggaacacttgattatctt
caaggcctcaagatgcttggagtaaaacgcattgagcgcgttcttccaactggaatgccg
ctaacaattgttggtgaggctgtcaaggacgatattggtgatttacggattcagaaacct
gaaagggggcctttctacgtctctcctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggtggtacaagtacgcctccatgggtttaactgtttttggtgtgtttcta
ataacaaaacatgttattgattctgttctagagagaagacgacggcgagagttacagaaa
agagtgcttgatgcagcagctaagagagctgagcgagagagtgaaggctcaaacgggaca
catgagagcgtttcagattctaccaagaaagaagacgctgttcctgatctatgtgtgatc
tgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcacc
gcatgctcttgccacttgaccagctgtccactttgccggagacgaatagatcaggtcgtt
aagacttaccgtcac
>Carica_papaya_evm.model.supercontig_9.121 CDS
atgattccatggggaggaatcacttgctgcatgagcgcggctgccctttatctgcttggc
aggagcagcggcagggatgcggatattcttagaaaagttacgcgagttaatcagttgaag
gaattggcgcagttgcttgacattgaa---agcaaaataatgccattgattgttgccata
tctggaagagttggctctgagacaccaattagttgcgagtacagcggcttaaggggagtt
atagtggaggaaacggctgaacaacattttctcaaacacaatgatgctggttcttggata
caagatagtgccctaatgctgtcaatgagtaaagaggttccttggtacctggatgatggg
actgctcgtgtatttgtagtaggagcacgaggtgctactggttttgttcttactgtgggg
agtgaagtatttgaagaa---tcagggcggtctctcgtacgaggaacgttggactatctc
caaggcctcaagatgcttggagtcaaacgtattgaacgtgtacttccaactggtacttcc
ttgacagttgttggtgagatgaca---------ttggaacaattcagatacgaagaccgc
acaaacggcctttttacgtgtctccaaatcaatggatcacctgatttc---caattaggg
aaatgggcaaggtggtacaagtatgcttcgatggggctaacattccttggtgtttttcta
attgcaaagcgttctattgagtatgttttggagagaaggcggcgacgagagttgcagaaa
agggttcttgccgcagcagcgaaaagatcagggcaagataatgaaggttcaaatataata
cctgaaaatgggttggatggtgctaagagagagcatctgatgccagatctatgcgtgata
tgccttgagcaagagtacaatgctgcttttgtcccgtgtggtcatatgtgttgttgtatg
acttgctcttcccacttgacaaactgcccgctttgccggagacggattgagcaggtgctc
aggaccttccgccat
>Solanum_lycopersicum_gi|460393457|ref|XM_004242278.1| PREDICTED: Solanum lycopersicum mitochondrial ubiquitin ligase activator of nfkb 1-A-like, transcript variant 2 (LOC101250130), mRNA
atggttccatgggccggactctcttgctgtttgagtgcagctgctctttaccttctcggt
aggagcagtggaagagatgctgaagttcttaaatccgttacaagggttaatcaattgaag
gatcttgcacaactactagatactgca---tccaaggtgttgcctctggtggttactata
tctggaagggttggatcagatacaccaattaactgtgagtacagtggtctacgaggcgtg
attgtggaagaaactgccgaacaacattttctgaaacacaatgatgcaggttcttggata
caggattctgccttgatgctctcaatgtgtaaagaagttccgtggtacctggatgatggc
acaggtcgcacttttattgttggtggccgtggtgccacgggtttggtactgacagttgga
agtgaagccttcgaggaagcaggga---gatcatttgtgcgagggacattggattatctt
caaggtcttaagatgcttggagtaaagaggattgaacgtgtgctgccagttggtactcct
ttgactgttgttggcgaggctgtcaaagatgacattgggacagttcggatccagcgacca
cacaaaggcccattttatatctctcataaaactattgaccagctcattgcaaatcttggg
agatgggcaaggtggtacaagtatgcttcaatgggttttactgctgtcggtgtatatcta
cttgtgaagcatacttttcattatatgatggaaagaaagcgtcactgggaattgcgcagg
agagttcttgctgctgctgctaaaagagcaggagatgaggatgaaggttctgatgctaca
gctgagaatggagtggataat------aaggacctcttaatgccagatctatgtgttata
tgtctggagcaggaatacaactcagtttttgtcccgtgtggtcatatgtgctgttgcatg
acgtgctcttcacacttgacaaactgcccactatgtaggagacggatcgagcaggttgtg
aaaacttttcgccat










