>SPL2_A.thaliana gi|186490864|ref|NM_104293.4| Arabidopsis thaliana E3 ubiquitin ligase-like protein (AT1G54150) mRNA, complete cds
acttgtccgtgtgaccgtgtctacgacgttgaaatcgaaattaccaca------------
-----------------------------atgtcctcgccggagcgt---gctctcttga
atctattgacggacatcgctctctccttcgacggcgcaatcctcggactgactttagctg
ttagcgccgtcggttctgctctcaagtatgcttctaccaacgccgcgttgaagaagatca
aagatgcacccgaagtctccatttccgacctccgatcactgcttccggcttctga-----
-agacaaatcagagactaacgataacaggaagagcaatgatcagcgaatcgttgtggttc
gcggagtcgtcaaaccgaaaatttccggtgatgagggttacaaga---------acaaca
acgtgttaatctctccggagactggagataaagctcttatcattcagagaacgcaaactt
atgtgtatagtggatggaagagattgtttcagtccac---tggtcaccggtttatgttgg
agagatca---ttgcgcaaacacggtgctgattttacgagaacggtcccatttgtcattg
ttggaaaggatcagcaatcgaactctagttttgtcgctgttaacatggatggctcaaggc
aacctcttccgcttaccactgtgtataatcgcttgcagcctattaattc---------tt
cgtttcttcaagcctttttgtaccccgattatcctgttggtctgcttgatatagagaaga
ttttaccacctgggaaagatataacagctgttggcatctacagttttaataatggagttc
ctgaaatcaaatcgtgccaagatcttccttatttcttatcagagatgaccaaggacaaga
tgattgaggaccttatggaacagaccaactttatattcttgggcagcgttatcttgggca
ttgtgtctgttggcatccttagctatgctgctgtcaggacctggaataaatggaaacaat
ggaaccatcagagagaactgccacagagaccgaacg---------------attctgtgg
tcgatgatgaaccc------------------gaagatgcagatgaaatcccagatggag
aattgtgtgtgatctgcgtgtcaagaaggagagtacctgcgtttattccctgtggacatg
tagtatgttgcaggcgatgtgcttcaaccgtggaacgagagttaaaccctaagtgtccag
tttgtcttcagagcattaggggatctatgcgtgtatattactcttagtgaccctgaatct
tctctcattgtatgtaatagggtaatgcaatttgtactctcagagaatcggaagttaaca
aaatagtttgacaatgatttgaaagttcgtcaagtcactcaatatagagtgagagattgt
agaggatatgaaagcaaagtttttaaaaggaagaaattttgtaaccgataac--------
------------------------------------------------------a
>A.lyrata_474546 CDS
------------------------------------------------------------
-----------------------------atgtcctcgccggagcgt---gctctcttga
atctattgacggacatcgctctctccttcgacggcgcaatcctcggactgaccctagcta
ttagcgccgtcggttctgctctcaagtatgcctctaccaacgcggcgttgaacaagatca
aagaagcacccgaagtctccgttgccgacctccgatcactgcttccagtttctga-----
-agacaaatctgagactaacgatcatgggaa---------------aatcgttgtggttc
gcggagtcgtgaaaccaaaatattccggagatgagagtcacaaga---------acaaca
acgtgttaatctctccggagactggagataaagctcttatcatccagagaacgcaaactt
atgtgtatagtggatggaagagattgttccagtcaac---tggtcaccggtttatgttgg
agagatca---atgcgcaaacacggagctgattttatgagaacggtcccatttgtcattg
ttggaaaggatcaacaatcgcagtctacttttctcgatgttaacatggatggttcaaggc
aacctcttccgcttaccactgtgtataatcgcttgcagcctattaattc---------tt
cgtttcttcaagcctttttgttccctgattatcctgtcggtctgcttgatatagagaaga
ttttacctcctgggaaagatataacagctgttggcatctgcagttttaataatggagttc
ctgaaatcaaatcgtgccaagatcttccttatttcttatcagagatgaccaaggacaaaa
tgattgaggaactcatggatcagaccagctttatattctttggcagtgttatcttgggca
ttgtgtctgttggcatccttagctatgctgctgtcaggacctggaataaatggaaacaat
ggaaccatcagagagacctgccacagagaccaaacg---------------aacctgtgg
tcgatgatgaaccc------------------gaagatgcagatgaaatcccagatggag
aattgtgtgtgatctgcgtgacaagaaggagagtacctgcgtttattccctgtggacatg
tagtatgttgcagggtatgtgcttcaaccgtagaacgagagttaaaccctaagtgtccag
tttgtctccagagtattaggggatctatgcgtgtatattactctta--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------a
>Brassica_rapa_Bra037967 CDS
------------------------------------------------------------
-----------------------------atgtcctcgccggatcgttccgccgtcttcc
ccctcctgatcgacatcgctctatccttcgacggagccatcctcggagtaaccctagcct
taggcgccgtccgcgctgctttcaagtacgcctcgacctccgccgcgttgaataagatca
aagacgcccccgaagtctccgtctccgatctccgatcgctgattccggcgtctga-----
-tgaccaatccgagacgagcggtgagcagga------------gcgtatcgtggtggtta
gaggaacggtcaaagctaaggttacaggaggtgaagggagtaaca---agcagaacaaca
acgtgttgatctctcaggagacgggagataaagctcttatcattcatagatctcaaactt
atgtgtatagtggatggaagactttgtttcagttgacaaatggtcaccggtttcttctgg
aaagatct---ttgcccaaacaaggagctgacttcatgagaatggtcccttttgttatag
tggacaacactcaaccgtcgcagtctagctttgttgttgttaacatggatggtgcaaggc
agcctctcccgcttaccactgtgtataatcgtttgcagcctattaattcatctccctatg
cgtttcttcaagccttgttcttccctgagtatcccgttggtttgattgatgtagagaaga
tattaccacctgggagagacttaacggctgttggcatctgtagttttaacaacggagttc
ctgaaatcaaatcctgccaagatcttccgtacttcttatcagagatgactaaggacaaga
tgatattagacctcgcggagactaccagtgtaatattctggggcggtattatcatgggat
gtttgtctgctggcatccttggctttgctgctgccagggcctggaatagatggaaacaac
ggcaccatgaaagggaacagcaacagagaccagacgagcagagaccagagcaacccatgg
ttgctgatgagact------------------gaagatgaagatgagattccagatggag
cactgtgtgtgatctgtgtgacacgaaggagagttcctgcattcattccctgtggacatg
tagtatgctgcagacagtgcgcctcaaccgtggagcgtgaggttaaccctaagtgccctg
tttgtctccagagcattagaggatctatgcgcgtgtattactcttg--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------a
>Thellungiella_halophila_Thhalv10011564m CDS
------------------------------------------------------------
-----------------------------atgtcctcaccggatcgt---gccatcttca
acctcttgaccgacatcgctttatcctttgacggagccttcctcggagtaaccctagctt
atggcgccattcgctctgctttcaagtatgcctctagctccgccgcgttgagtaagatca
aagacgccccggaagtctccgtttccgaccgccgatcactgattccggcgtctga-----
-agaccaatctgagaatcgagatcacgggaatagccatgatcagcgtatcgttgtggttc
gcggaaccgtcagacctaagtttaccggtgatgggagtcacaag------------gaca
acgtgcttatctctcaggagactggcgataaagctcttattattcagagaactcagactt
atacgtatagtggatggaagactttgtttcagttgtcaaatactcaccggtttctttttg
aaagatctatgatgcctaaacaagaaactgcgttaacgagaatggtcccgtttgttattg
tggaaaaaaatcaacgatcgcagtctagttttctacttgttaacatggatggcgcaaggc
aacctcttcctcttaccactgtgtataatcgcttgcagcctattaattcaactccctttg
cctttcttcaagtcttgttcttccctgagtatcctgttggcctgcttgatgtagagaata
tcttaccacctgggagagatttaacagcagttggcgtctgtagtctcaataatggagttc
ctgaaatcaagtcgtgccaagatcttccctttttcttgtcagagatgactaaggacaaga
tgatactggaccttatgcacactaccagagtaacattctgggccggtgttgtcatgggct
gtttgtctgctggcatccttggcttagttgctgtcaggacatggaagagatggaaactac
ggtatcatcaaagagagccgctgcagagaccagacg---------------aacccgtgg
tcgatgacgagaca------------------gaagatgcagatgagattccagatggac
aattgtgtgtgatctgcgtgacaagaaggaggatccctgcatttattccctgtggacatg
tagtatgttgcagacagtgtgccttaaccgtggaacgagcgttaaaccccaagtgtccgg
tttgcctccagagcattagaggatctatgcgtgtatattactcttg--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------a
>Carica_papaya_evm.model.supercontig_25.125 CDS
------------------------------------------------------------
-----------------------------atgtcttcccccgagcaa---gccttagcgt
cccttgtctctcaccttgctctctccctcgacggcgctgtcttgggtgtggcactcgcct
acgctgctgttcgctccttcttcaagttcaccgccaattccgccgcccttcgcaagatcc
gaagcgctccgcagcttcgcgtgtctgatctccgttccctcctcccggtctcatcaga--
-agatcagtcacagccatccgatagcgat-----ccctcttcaac-tctggtgattgtcc
gcggcaccgtagaagcgaaatcagctgttgatgggagttggaaaggcttaaggcacaaca
acgtgttggtctctcaggagtctggagataaagctgttgttatccagagaacacagactt
acatatataatgagtggaagggcttctttgggtggacttcggatctgcgcgctatatttg
gaagatct---tggggtaaacaagagtctgcttcatcaagaatggtaccttttgttcttg
ttgaggatggtcgatggccacaatctgattatgttattgtcaacacggagggctctttac
atccccttcctcttacaactgtttatcaccaattgcagcctgttaatgcatccccttata
cattccttcaggcactctttggtcatgaatatcctgttggtctccttaatgaagagaaaa
ttcttcctttgggaaaggatataagtgctgttggcatttgcagttttaagaatggaattc
ctgagatcatgtcatgcaaggatcttccatattttctgtcagacttaacgaaggatcaga
tgctattagaccttgcttttaggacaaagatactgttttggagtggtatcattcttggtt
ctctgtcaatcagtattcttggctatgctgctctgaggaactggaacagatggaaagagc
ggaggcaacaaagacaggcccatca---acctagcc---------------atgctgcca
gcattgatgcaaactctgaattgacgggtgaggaggagataggtgatattccggatgggc
agctgtgtgtaatctgcttgatgaggagaagggtgcctgcttttattccatgtgggcaca
tagcatgttgccaaccttgcgctttgtcggttgaacgggaattaacaccaaaatgtcctg
tttgtcgacaggaaatcagaggctcaatgcgagtattctatgcttg--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------a
>Solanum_lycopersicum_gi|460414066|ref|XM_004252348.1| PREDICTED: Solanum lycopersicum mitochondrial ubiquitin ligase activator of nfkb 1-like (LOC101259919), mRNA
gtagtcttaaaaaaagaggtactcatagccaataaacaagccatagaaatagcgttcagt
ttccggcgaccgagaatttgaaagtagccatgtcaatatacgatcaa---gcggcagctg
ccgtgctatcgcaaatagctacggcggcggatggcgcacttattggcttagccctagctt
acgttgccgtacggagtattgtcaagttcaaagccaattcttccgcccttcacaaaatca
acgatgcgccgtcgcttaatgtctccgatctccgttcattactttcttcttccgacaact
ctgatagttcaaatcattccgatgacggtaa---------------gcttgtgattgttc
gcggtactgtggaggcgaaatcggcggttgagggtaactggaaaagcttgagagctaata
ttctctcag---ctcataattctgctgaaaaaggcgttatattgcaacatactcaaacat
gtatctataatgagtggagaggcttcttttcgtgggctggtgatctgtattcaatatttc
caagagtc---cggaaggatcaacaatcgtcctctttgagaacggttccctttgttctta
ttgaaactgggaggtggccgcaaccaaaatatgttaatgtcaatatggatggttctacgc
attccctacctcttgtgacagtttatcatcacttgcaacctttacatgctacgcctctca
cttttatccaggctctctttggtcatcactatcctgttggagtattggatgaagaaaaaa
ttctaccacttggtaaagatataaccgctattggtgtttgcagctcaaaagatgggattt
tggagatcaaatcatgtgaagacctaccctatttcttgtctgatatgaccaaggatcaaa
tgctggtagagcttgccttcaaaacaaaaattctgatgtggagtggagttttatttggtt
cagttgcagttggtgtccttggatatgctgttgtgaggaactggaatcgatggaagctgt
ggagacaccagaggcaggctcagca---acaaaggg---------------atgctgcaa
gcaatgacgatgatgtgcaggttagtgctgatgaggaatctggagatgttcccgatggtc
agttgtgtgtgatatgccttacgaggaggaagcgcgcagcatttgttccgtgtggacacc
tggtatgttgccagcgctgtgccttgtcagttgaacgtgatttagcacccaagtgtcctt
tatgtaggcagacaattcatagttctgtaaggatatatgattcttgacgagcaaatagtt
acgagttattttgagtagctgatgctgggaaggtggttgtgcatttgtaaagcatgtgat
gaaaactacattggactgtctcatgggaggatggtcgttgatattccgaggggattagat
actagaatttaacatgcatatttttcgtgtctgtacatacattttttgctgactcattat
tgtacccttaaagacaatattcattacaatgctagggagtcattttgctaaaaaa
