>gnl|BL_ORD_ID|26400 @Branchiostoma_floridae@ jgi|Brafl1|118249|estExt_fgenesh2_pg.C_110120
MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------SKRKRGDEGFADSNE
GEEERYFLNPES------------------------------------------------
------------------------------------------------------------
--VSEHLYCSICQDVFKEPQRAP--------------CGHSY-CKQCIMAWLRTSK----
--TCPEDRRPVRE-KDLHYDFILANIIGDHMVACPFRKLGCEFIGKLELLTSHRKSCCFN
----------------------------------PANLPEFLLEEPQSSTAAAATASSVD
TSSS--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------FLCTSDDENKLPSPPKPSLKMRLFKNGASQRD
LLKNMFDKENRPK-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|18744 @Takifugu_rubripes@ jgi|Takru4|740138|fgh5_pg.C_scaffold_300000011
MG--------------AKESRIGFLSYDEAVKRVTDVELKRLKDAFKRTSGLTCYM----
--------TQQCFYREVLGDGVPLKVAEVIYTSFGGSSKGLHFNNLIVGLVLLTRGRDEE
KSKCTLIHFHTRADFDLFSLFASDLGGYAAREEIEAVLQILDGEIPTSLQKCFIESEKVS
YERFRAWLFLNKEAFTLSRWLLSGGVCVTLTDDSDTPTFYQTLAGVTHLEESDIIDLEKR
YWLLKAQSRTGRFDLETFVP------------------LVSPPIHASLSEGLFHAFDENR
DNHIDFKEISCG---------------------------------------LSACCRGPI
AERQKFCFKVFDVDHDGVLSRDELHEMVVA--LLEVWKDNRTDTLPELTSSVSDIVEDIL
KMHDTTKLRHLTLEDYQIWSVSSALANEFL--------------NLLFQVCHIVLGLRPG
TPEEEGQIIRGWLERESRHGLQQGQNWFLISMLWWQQWKDYVKYEHKGIVLEQPSLL---
------------------------------SSLRNSVNASTVEPLLPDRLGGLGTFSFVS
PSEERSPDGVSSSSE---------------------------------------------
----------------------------ATETESCFARQHNTSDNNNQCFSGANGHIPSQ
LAAQRPGAIDNQSLAPTLTLEGGRLK--------RSLQLVPGRDFETVPEPVWRALYHWY
GANLSLPRPVILDSKTSQAELELFPRYLLFLRQQPATRSPQSNVWV--------------
------------------------------------------NMGSVPSPNAPLKRVLAY
TGCFSRIDTIKDIHLYLSQRLRIKEEDMRLWLYNSENYLTLLDDEDHTLENLKIQDEQQL
VIEVRNKDMSWPEEMSFIANSSKMDRHKVPTEKGATGLSNL-------------------
-----------------------------------GNTCFMNSSIQCVSNTKALTDYFLS
GRHLYELNRTNPIGMRGHMAKCYGD-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------LVMELWSGTQKSVAPLK
LRWTIAKYAPRFNGFQQQDSQELLAF----------LLDGLHEDLNRVHEKPYVELKDS-
-------------------------------------NGRPD------------------
-----------------------------------------------WEVASEAW-----
------------------------------------------------------------
------------ENHLRRNRSIVVDLFHGQL---------KSQVKCKTCGH---------
-------------------------ISARFDPFNFLSLPLPMDSYMHLEITVIKLEGST-
-----PVRYGLRLNMDEKYMGLKKQLSELCSLKPEQILLAEVH----TSNIKNFPLDNQK
VRLSANGFLCAFEVPVPGSPMSLSSPTLTDLTP-TANGSVSGDGLA--------------
-------------------------DRSALIPNGGPNIVVPCSPEMPLGNGLANGRVTPL
QESPFIGYIIAMHRKMMRTELYFLSSQKNRPSLFGMPLIVPCTVHTTKKDLYDAVWIQVS
RLASPLPPQEASNHAQDCDDSMGYQYPFTLRVVGKDGNTCAWCPWYRFCRGCIIECTDDR
ASLGNAYIAVDWDPTALHLRYQTSQERIVEEHCSVEQSRRAQAEPISLDSCLKAFTSEEE
LGEDELYYCSKCKTHRLATKKLDLWRLPPILIVHLKRFQFVNGRWIKSQKIVKFPRENFD
P-----------------SAFLAPRDLGQHCLQSRSESEDLLRVGEDNLSSISA------
----------------------------------PAGFYNLPKASPASSRKSAPSLSRTS
SPSS-----------------------------------------------------SPK
SGGGGRRPARLRLAKLEETTESSLSTEASS---------------------SHCDVVLVN
GDSNGLSLDCSTDSSLDPDNSLLQHRDNMCLDAVYNLYAISCHSGIMGGGHYVTYAKNPK
KKWYCYNDSSCKEVHSEEIDTDSAYILFYEQQGVEYSQFLPKIDGKKMADTSSMDEDFES
DYKKYCVLQ---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|797 @Ustilago_maydis@ jgi|Ustma1|798|UM00798
MTTQSSAGPQSQPSRDFFASSPSATPGSPSKQASQASKQPDALVTPSSVTANTSVCADNL
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LDHHQHEPQHDAASVVIGIEGS
INDSAAIHRRRQQPRRAAVQNAKPLFLAEDEDDAINWPVADQEEGDDFFSTQLADQKVKR
PARATVNSDEKDFQP-STLSSLSSPPSETVYKRSPPSDDVQASNGPAKRP-KKSWSTPAS
VATTKSAPRHCSPTPDPRLRHDAFDRRYIGTFVLSAWSLSKGSSYVKPGDAVRIFRPRK-
---------------------KHATAEPKIASKLTNGGMQKAKQTTLNFRGASAGPTNFF
TSKQKSKEKEHFIVRFSNMRGFEVGRLPLEVAIWMSKLIDAGIAEFEGVVVDCPPSLTVG
CDIILQVKAYIKFDAFFSTLLGSREFDDQNEALRPETAESDLEKTLRERKISLLRMFRVC
DLKPRLSNAILKSHK---------------------------------------------
----------------------------------------------ASDDFSSEAMLDQY
GGDIQGAVKHAGSDLAISTENGTQLP--------HAGEDASSTAIDLDVEGDTDAVAHLE
IADQLQSAKRQTDGDADTEEN---------------------------------------
------------------------------------------------------------
-------------------------DGTELNLNQLDQVYRKAQANDAHLPEVEPPESFVL
TLRPYQKQALGWMKNMEMAPGQSSSSQEQSVTQQGNGDTGE------------------R
NVSLHPLWEEYEFPLDYDNPQANERLILSATRLFYFNPYTGDLSLDFQRASKGSRGGILA
DEMGLGKTIMVASLLHANRTSDPGEESEGEINAVDAAEGD--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------VSTKRKGSAKQTSLASAFAASTSSVDQRKALLKASVSKGKASL
VVAPMSLIG-----QWRDELIRASAPGSL---TPVLYYADTKGDLLAQLESGKVDVVITS
YGTLVTEYRRFLDGGGASNRHLSVSAPLYCIDWLRVILDEAHNIKNRSTMNARACCDLV-
--------------------------------------SRRR------------------
-----------------------------------------------WALTGTPI-----
------------------------------------------------------------
------------INRLTDLFSLLKFLRVEPWGDFSFF---NSFVCKPFQAK---------
-------------------------STKALDVVQ-----------VILESVLLRREKKM-
---------------------KDKDGKPIVELPPKTIVVKELE----FSELERRIYDNVY
RRAYLQ-----FASLKANGTVTRNLSVIFSVLM-RLRQAVCHPSLV--------------
-------------------------LKAGSKVQSGGIRKDHVDRNGEVGVGEGDHVEVDA
DAVEFGLD----------------SDHVGGNG-------------TPSTQDLRELVAQFQ
LDEAGEAGDDST------------------------------------------------
------------------------------------ESYTKATVERLIGEMHGDQATVPP
VVSDGENECPICLEESQ------------ISPCYLPRCMHSA-CKACLVDYLGQCKQKGD
QGACPTCRKGPVQETDLIEAIRTRPATRAAS-------------GGASPTDRPGKACTLT
----------------------------------SVPSVIYVRNNLRTSTKLSALISHLN
TLRA-----------------TEAAFKGVIFSQFTSFLDLIEPVLTRYRFHFLRLDGSTP
QKVRDKLVLEFQSPSPTNHVVLFLISLKAGGVGLNLTA----------------------
------------------------------------------------------------
----ANKIWLLDFWWNSSIENQAIDRIHRFGQTSPVSVFRYIIKDSIEDRILLIQKRKDM
LIKHALNTDNHPHGTKPNSEMLANLDL-LFGE----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|8448 @Branchiostoma_floridae@ jgi|Brafl1|79530|fgenesh2_pg.scaffold_86000015
MP----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------KKRDDEATKQAIADKVKQIQSKQARWMQERKEQ
LDRGGGRQHTQTGG-------------------------------------TAGQRGAAN
RRDKKPAAQSTNSAYIPWISKNDI------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------DKQFQQKSTRSQPPKPSSAPTGKSRK
PETLTKTTTVHNHNE---------------------------------------------
------------------------------------------------------------
----------RKVLTQRPKSASRTLE--------RPKTYTKGSFDQLNGNALADDVRPTS
NGSNQNARQIESEDGTQDEEDMVPSTQSDSEDSTHSSNQE--------------------
------------------------------------------------------------
-----------------------------------------FPKQDNISSAREPLHKHNL
KPNKAGNDVENGVKATEVQADQSGSRSARARA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------MLSPDMFDALADQIA
NRLKVRMDKPAS------------------------------------------------
------------------------------------------------REDTGGGGQVSQ
ETSIDTHKCQVCSSLMVPPDHRPMLVIP---------CGHTF-CSACVRHTD--------
--TCPGCGQEVSS---LTCNIMLQQIIMEYKSKRKPKTRDHSNLHISSANHTYAPQK---
----------------------------------YSGGTSRFDSLGEERKTVPSSVKRRD
PGSHGDGKHKGFHGNRGEDYVEKYHTLTVRCEVLETEADGIRDKMEAVAKQLEREQKQVA
AIEKQEESLREQIRMIEEKISSLQSHKEGYRDTCDELE----------------------
------------------------------------------------------------
---------------------------------------------GQHFNLASKLSMVEV
TLQSLTVERDKVRILAHNFDPSINIEDD--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|10239 @Ciona_intestinalis@ jgi|Cioin2|290319|estExt_fgenesh3_pg.C_chr_07q0591
MEWMNNVKSIHGDHSLAGTSLSDVHGFSNLPLGLNSGQTFHSSDHLSTGKLYEPHTSSAY
HMPLMKHSTSHTDLNSVSAHKSSYDNFPSPFDYLPRTPQSSSSLELLRDYQKSSALEPSP
H-----------------------------------------------------------
-------------------------------------SNSLHLNGTKYPQRHERAKLHSP
ANFQTQREHSPMPSRPSPFKGHMGHPKYEFSNRSLDYKRQATESTSPFLVNEFSKSSSRI
PPSTNTLSS------------------------------------------SYALSAQIN
SPFRTSFYKLNNVQPDTRIPDTAMANHLKLGTPFSYYPNMYPNREIPYPMFYPPLMPPGL
VPGMSGYPNPTEILPHRA------------------------------------------
------------------------------------------------------------
---------------------------DHGSLVQPSHYKPDLHHIPMPQQPAIHQVEKIP
PHTITPSSSHDSGSS---------------------------------------------
--------------------------------YKNGWKPQDSVHNDARKRSEQPLLKQQH
PVDHEDRRCSEHIPPNNYVKENHKVT--------EHVNGQKRTTADTDMRPYMHSVHPSN
KHTNNHPQPRTNENAHSLQNDSAIKPTTEISTPDHIQQ----------------------
------------------------------------------------------------
-----------------------------------------------NSNDELKKRLQSP
ISEPVNREENNAMSPNKEEKKENEEKNRKRKLDLVTSLSTS-------------------
--------------------------------------------TSGRSNSSETNQAQGN
LSRNASTEPGTPRREKRPRKSETEDDYFYEWPYEDFSSSEPENDDSGDEDFFCA------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------SKKKLLIKKSKDVGLASSRPMRQSSLRAASLLNEHREGSASDG
DTFPSRRLKKNSENERMDKKLREKKAKSRKISSESMSSENCNDDLNETLSPKKVESSASS
GRSKETKLKRKLKKLRRSKHELNKSQSDDSPVKKKRKKKNLTKSDSSESQSKKVKKEKN-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------IEKLNTSNQDGKKIKSPKKLRPQLEADVKSKKS---------------
---------------------------------------------LHKEIVCKTKSGES-
---------------------KSKSQSGISKSLIELYTGPAKPCNELESPVQNRECSKQG
NDLF--------------------------------------------------------
-------------------------GTEFTESEAAAFNQAFEAAKKELEIKEGAGTTLPL
HSNLQNETPIVTSPVVQAQSQQVQSEPLQQEVKQRKKPGRKPKH-SKDNSALSPTKSSKK
HELKTETPKTHLKPKTENKSSL--------------------------------------
----------------------------------LPKSGARKGRPPGSSSIHKLREKQKA
AIREAQQSKQECSQPIRPNTSVETTPAKNESLTSTPKVK---------------------
--EQPSHEAPSTSGFTTPSSVRKPPLFLKSSRPSTPINAKERKLAFQSPLPPNLKKLTCN
SAIGETVLHKAARHGYMENMKHYLESGFSVNAKDNAGYTALHEACVQGRLEAAKLLLQFG
ADVN------------------------------LNSLDGTRPIHDAVEYDHIEMTRLMM
SCGADPLLSKFSGRSIKNMIRSTQMG---------------NFINAYLKELQPVCEELME
DSDMKWKIPFSSVLESKQDQGYDLMGNPPAEDTQAHCMEFELFDEQPIDTYLVQPSDTTD
RSNYYLLNDILQVKGCSKADFLLEHCCN--IRTMPTNKFCSEADLNKFGKRNRNFNETNS
LIELVAADKPLTRHVGLRVHPTGEVEEIPQFKKQKSSRLPPPVANDNVVKFLPKTTDTPT
CSETPDQTRSNSNLLENLSDSVIDDHREESLACLQKLTASFCMTGHIGKEYKDFGKVNGI
HTPGTQTPVKKPRPPAMEVNLPKTSTPNIEKNHKQNSDHIPMECLPPYNHHIEPKQPPKL
PPLAPINTDSGLRSLPTQQNGVDFSPFNKLPTFTESQNPVNTPNLVPEI
>gnl|BL_ORD_ID|25069 @Homo_sapiens@ gi|237681119|ref|NP_009231.2| breast cancer type 1 susceptibility protein isoform 2 [Homo sapiens]
MDLSALRVEEVQNVINAMQKILECPICLELIKEPVSTKCDHIFCKFCMLKLLNQKKGPSQ
CPLCKNDITKRSLQES--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------TRFSQLVEEL
LKIICAFQLDTGLEYANSYNFAKKENNSPEHLKDEVSIIQSMGYRNRAKRLLQSEPENPS
LQETSLSVQLSNLGTVRTLRTKQRIQPQKTSVYIELGSDSSEDTVNKATYCSV-------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------GDQELLQITPQGTRDEISLDSAKKAA
CEFSETDVTNTEHHQPSNNDLNTTEKRAAERHPEKYQGSSVSNLHVEPCGTNTHASSLQH
ENSSLLLTKDRMNVEKAEFCNKSKQPGLARSQHNRWAGSKETCNDRRTPSTEKKVDLNAD
PLCERKEWNKQKLPCSENPRDTEDVPWITLNSSIQKVNEWFSRSDELLGSDDSHDGESES
NAKVADVLDVLNEVDEYSGSSEKIDLLASDPHEALICKSERVHSKSVESNIEDKIFGKTY
RKKASLPNLSHVTENLIIGAFVTEPQIIQERPLTNKLKRKRRPTSGLHPEDFIKKADLAV
QKTPEMINQGTNQTEQNGQVMNITNSGHENKTKGDSIQNEKNPNPIESLEKESAFKTKAE
PISSSISNMELELNIHNSKAPKKNRLRRKSSTRHIHALELVVSRNLSPPNCTELQIDSCS
SSEEIKKKKYNQMPVRHSRNLQLMEGKEPATGAKKSNKPNEQTSKRHDSDTFPELKLTNA
PGSFTKCSNTSELKEFVNPSLPREEKEEKLETVKVSNNAEDPKDLMLSGERVLQTERSVE
SSSISLVPGTDYGTQESISLLEVSTLGKAKTEPNKCVSQCAAFENPKGLIHGCSKDNRND
TEGFKYPLGHEVNHSRETSIEMEESELDAQYLQNTFKVSKRQSFAPFSNPGNAEEECATF
SAHSGSLKKQSPKVTFECEQKEENQGKNESNIKPVQTVNITAGFPVVGQKDKPVDNAKCS
IKGGSRFCLSSQFRGNETGLITPNKHGLLQNPYRIPPLFPIKSFVKTKCKKNLLEENFEE
HSMSPEREMGNENIPSTVSTISRNNIRENVFKEASSSNINEVGSSTNEVGSSINEIGSSD
ENIQAELGR-----NRGPKLNAMLRLGVL---QPEVYKQSLPGSNCKHPEIKKQEYEEVV
QTVNTDFSPYLISDNLEQPMGSSHASQVCSETPDDLLDDGEIKEDTSFAENDIKESSAVF
SKSVQKGELSRSPSPFTHTHLAQGYRRGAKKLESSEENLSSEDEELPCFQHLLFGKVNNI
PSQSTRHSTVATECLSKNTEENLLSLKNSLNDCSNQVILAKASQEHHLSEETKCS-----
------------------------------------------------------------
------------ASLFSSQCSELEDLTANTNTQDPFLIGSSKQMRHQSESQGVGLSDKEL
VSDDEERGTGLEENNQEEQSMDSNLGEAASGCESETSVSEDCSGLSSQSDILTTQQRDTM
QHNLI-------------------------------------------------------
----------------------------------KLQQEMAELEAV--------------
-------------------------LEQHGSQPSNSYPSIISDSSALEDLRNPEQSTSEK
DSHIHGQRNNSMFSKRPREHISVLTSQKSSEYPISQNPE------GLSADKFEVSADSST
SKNKEPGVERSS------------------------------------------------
--------------------------------------------------------PSKC
PSLDDRWYMHSCSGSLQNRNYPSQEELIKVVDVEEQQLEESGPHDLTETSYLPRQDLEGT
PYLESGISLFSDDPESDPSEDRAPESARVGNIPSSTSALKVPQLKVAESAQSPAAAHTTD
----------------------------------TAGYNAMEESVSREKPELTASTERVN
KRMS-------------------MVVSGLTPEEFMLVYKFARKHHITLT--------NLI
TEETTHVVMKTDAEFVCERTLKYFLGIAGG--------------KWVVSYFWVTQSIKER
KMLNEHDFEVRGDVVNGRNHQGPKRARESQDRKIFRGLEICCYGPFTNMPT---------
----DQLEWMVQLCGASVVKELSSFTLGTGVHPIVVVQPDAWTEDNGFHAIGQMCEAPVV
TREWVLDSVALYQCQELDTYLIPQIPH-SHY-----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|8599 @Trichoplax_adhaerens@ jgi|Triad1|60259|fgeneshTA2_pg.C_scaffold_14000143
MERSCVLTVHDDFNTTAKSSLVEVKENIHIVMGNEAADLDSIVCSITYAYFL--------
--------AQRSLTESNVRVIPVIDIPRKDFQLRAEISYLFKSIKLKENLLTFADEIDLQ
ALYDANKLSLTIVDHNRLSNKHEQLADCITDIVDHHLDEDQFPECDIILEPV--------
-----------GSCATLIAEQLMDGDCSLIDNEVGLLLLSAIIVDTANLDVNFARTTEKD
IEIANKLETYVDFDELPFSR----------------LELYDKMKEAKFNVSHLSTYDL--
---------------------------------------------------LRKDYKSIA
ALDQSVGISSVTIPMEEFIERNQFVNDVSA------------------------------
----FGDEKNLAGFVIMSFYFESDIAKRQLLVYEKACNDNGTKIGLFLSRAPTLKIEAVD
CPHPCMQIFKQLNVKDSRKVIMPLVKEFLNTGL---------------------------
------------------------------KSLENETKTENMNSEICTSDAALIADITPH
AEPINVSTANSNSDA---------------------------------------------
------------------------------------------------------------
-----------------------------------------------------FSVASNA
DSTDKIAPDPHDSIEEVDNEDIIVNNNDDESQNSGSYTVNQVNNEC--------------
------------------------------------------VDLASPELETTTEESVKL
LKVSKLNLESESSPTSATIIDENQAEGTLEISDNSDSEVTASYDVNEPLENLNYQQENTL
NKKILSYRSLGETDTKNVA-SHELKVVDTSENSQSTPLSPI-------------------
-----------------------------------DEESPSYNVTTTVSFPETSNDVCES
SSHNADNSIANIYKPKAIDVSAPEDIPQTDAIYLPELSPIPEESPRREGMFNLDKTNQGQ
NIADRTTVSSLAEDESNVQFCTAIGDSVADNETSYINDEQSNSKSYDQNS----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------FTGNQSMLQSTVVMADSSIMDKDEGLQTTNLSVSNYETCIQDS
KDQSTAFMN-----NIVEKTLDTPQEEPE---NPSVNHDVNATIIAASNSEIAVESCLND
SLLDATLVANQDGIEVESNHEESVTENVDNEINSTIIIAASSPTNIPQSSTNDSTIDAT-
------------------------------------------------------------
------------------------------------------------SVSNQSE-----
------------------------------------------------------------
------------PECDHTSQSIVEDVNTIEL---------DNSSNIEIAGK---------
-------------------------VEHESDSLK--------------QREILTDSQDN-
------------------------------------------------------------
-RIKDDAPLDKQCNLDHDTEKVDNMTTTAEPVACRITACAITDALS--------------
-------------------------DSRLIQINSGNSNTATENDKYAYKPVDNKISTLDS
KD----------------------TNLSSGEVEVTGSENIESELTDTKEQDNTEAVAGNS
QNNQSPVARPSS------------------------------------------------
----------------------------------FNREGKRKSVLKVPATLSTSLTSPAA
TADDSTASI---------------------------------------------------
------------------------------------------------------------
----------------------------------PPSTESIPENTKQESTSGATEDDTLP
KSKS-----------------------------------------------------QPR
KLKVPRSISNIDPDAIEEYTAEEELSDTRTWRLVNIGG----------------------
-----------------ESKELDLRIVEAYRKVVSHGGYTHDGSALIVFSGCYMPKKSEP
NYSYILDHLFLYVMSTVETLVVQQYRIIFFNGGMSKDSFPSFKWLKKCYKTIDRSPKFGR
KIKFVSSLEELKKLVSLDQVSVPDVEI-NLG-----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|6738 @Drosophila_melanogaster@ gi|24648046|ref|NP_732373.1| Mekk1, isoform B [Drosophila melanogaster]
MSNRRRVRTIDYLALQQSLRLQKTPAATTNAEEQVAREEENGNGHHSTVTAETPPTPPIP
PIPPIRLRREQSVEEDVARVE---------------------------------------
------------------------------------------------------------
------YRVKQTPSRPVQMTRNRIGALEEDMPPEDELAAHYEAFGTTPPRTRLKIKNRDW
ERKQKVVNVTASADLPASVGGTPKKTRTARSRVLRRNTMDCALLNEMFVNDESKRTDKRL
QSLLRDSEREMKNSLATTAVAAPRGNS------------------------FHETAHPLE
SLDQIMPLNSEAMAPIPLRIASKVVESCNRYRCVSSRPIGYRSSAPPLAFAAQLPAGMLR
SDGRATPGLGKRKDFHETFA----------------------------------------
------------------------------------------------------------
---------------------------NLIKLGSVDRQDAKLSQEEHTWQTELKDLIWLE
LQAWQADRTVEQQDKYLFEARQGVSDLLTHIINYKFQPRYRREPSLISLDSGTHSDSNSN
ASSPLPSKMCQGCMSLYCKDCMDHQELALREVEGMLTRLEAAEALYPSSQAMGALHPIYK
SQSFVGRIKSMCLWYNITKQNKLKLS--------ILGKILARLQDEKFSWPVCTSSYIAT
DSGSSSASGVENDDSAVNSMDSSKPPSMAGSASRKGVTPC--------------------
------------------------------------------------------------
-----------------------------------------------HKVQFMLNDATHV
PGETSSSNESTSTEVSQWSSECSHSHMRKGSMHDINIFSVE-------------------
--------------------------PLGTCSSNGTGEQSTGLYRKFIENVLKSRGLAKS
LAFLHKLHNVALYKAHIALEKPGAEDFDYESDAESIEEDVPRLDPEISREQVVELRTYGY
WSEEAQSINLPSYIPTFVFLSGIPLQFMHEFLR---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------MRLETRPVRPNPLSLEQLMKELREGLTLALTHRERYQRHITTA
LVENEAELG-----SYISILNHYDATVRK---TFELYLEYIDQLVLVAVPEGNQKSVLEK
EWMFTKLISPMIKGMHTLASQKFCG-----------IISKLLRSISERLVKRTVELDQQ-
---------------IDGTADTDDNEEVKWQLLTICRETQSL------------------
-----------------------------------------------LTVERERS-----
------------------------------------------------------------
------------IKVLFFAKTFCRDVETTDFHREHYEHDVANQQHDFICSD---------
-------------------------VKAAFKLLQ--------------QDVLQVRNKLT-
--------AIIEGVQKRCCLSNMRDLDEQDKQAVLSRTREILH----QGYKFGFEYHKDV
IRLFEQKIMDQKDSGAHTVDLALGIIAYAKMWM-HFVMERCERGRG--------------
-------------------------MRPRWASQGLEFLILACDPQITQHLDDDEFEALKQ
QMDRCISHVIGIT--------------------------------SEPEKVAKKKASPRT
RKTSSPATSRSRTPTRTPMSAGMVLNPNTPP-----------------------------
----------------------------------LQSPPYNKLLHPQFSLKEDVSGTSYS
PVDSSDYVDTPCQRSANGELRLL-------------------------------------
----------------VPQTPPTPASPGKSSLESTPLALRQERVRDA-------------
VNRLDMDLEDGLRERRLIGQVKSLNSSDKVHIRARSVHFRWHRGIKIGQGRFGKVYTAVN
NNTGELMAMKEIAIQPGETRALKNVAEELKILEGIKHKNLVRYYGIEVHREELLIFMELC
SEGTLESLVELTGNLPEALTRRFTAQLLSGVSELHKHGIVHRDIKTANIFLVDGSNSLKL
GDFGSAVKIQAHTTVPGELQGY--------------------------------------
----------------------------VGTQAYMAPEVFTKTNSDGHGRAADIWSVGCV
VVEMASGKRPWAQ-------------------FDSNFQIMFKVG----------------
MGEKPQAPESLSQEGHDFIDHCLQHDPKRRLTAVELLEHNFCKYGRDECSSEQLQ-----
------------------------------------------------------------
---------------------------------MQVRGSFRRNVATSSS
>gnl|BL_ORD_ID|3782 @Saccharomyces_cerevisae@ gi|6323251|ref|NP_013323.1| Utp13p [Saccharomyces cerevisiae S288c]
MDLKTSYKGISLNPIYAGSSAVATVSENGKILATPVLDEINIID----------------
LTPGSRKILHKISNEDEQEITALKLTPDGQYLTYVSQAQLLKIFHLKTGKVVRSMKISSP
S-----------------------------------------------------------
------YILDADSTSTLLAVGGTDGSIIVVDIENGYITHSFKGHGGTISSLKFYGQLNSK
IWLLASGDTNGMVKVWDLVKRKCLHTLQEHTSAVRGLDIIEVPDNDEPSLNLLSGGRDDI
INLWDFNMKKKCKLL-KTLPVNQQVESCGFLKDGDGKRIIYTAGGDAIFQLIDSESGSVL
KRTNKPIEELFIIGVLPILSNSQM------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------FLVLSDQTLQLINVEEDLKNDEDTIQVTSSIAGNHGIIADMRYVG
PELNKLALATNSPSL---------------------------------------------
------------------------------------------------------------
----------RIIPVPDLSGPEASLP--------LDVEIYEGHEDLLNSLDATEDGLWIA
TASKDNTAIVWRYNENSCKFDIYAKYIGHSAAVTAVGLPNIVSKGY--------------
------------------------------------------PEFLL-------------
-----------------------------------------------TASNDLTIKKWII
PKPTASMDVQIIKVSEYTRHAHEKDINALSVSPNDSIFATA-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------SYDKTCKI------------------
-----------------------------------------------WNLENGEL-----
------------------------------------------------------------
------------EATLANHKRGLWDVSFCQY-----------------------------
------------------------------------------------DKLLATSSGDK-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------TVKIWSLDTFSVMKT
LEGHTNAVQRCS------------------------------------------------
--------------------------------------------------FINKQKQLIS
CGADGLIKIWDCS------------------------------SGECLKTLDGHNNRLWA
LSTMNDGDMIVSADAD--GVFQFWKDCTEQEIEEEQEKAKLQVEQEQSLQNYMSKGDWTN
AFLLAMTLDHPMRLF-------------------NVLKRALGESRSRQDTEEGKIEVIFN
EELD-------------------QAISILNDEQLILLMKRCRDWNTNAKTH------TIA
QRTIRCILMHHNIAKLSE------------------------------------------
------------------------------------------------------------
------------------------------IPGMVKIVDAIIPYTQRHFTRVDNLVEQSY
ILDYALVEMDKLF-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|3266 @Cladonia_grayi@ jgi|Clagr2|103549|fgenesh1_pg.5_#_162
MEEASMSGTDDDLPPLGQPSLQNQTHHRRHLRYATPETSTPPPPHFILEAAMSSQHSRSV
PPPNPHRNSRPTSASPPPPSVLASSGPNHHPGSQPPVLEVDGQDHDRMETDEESEESDSG
AEADT-------PDAASSEGATAGVSEATEIMIPPAAGHDEDMDTSPDNPAANENPPTPA
HTNIVTTAPTNEATGELTALRVVHVQMPPNDIDAAQILNAAIVGGTTHSPEEREARLLAA
ERELAALGSMRRAERVRAERNRHEGRQGREAEDHEDRDDEDSEDSEDEEEAPFWASLKED
TSAPDEHELKMIEDTIDEVTALNHEHWERKAFEPLDDPEYVPGEGHRISWTVVGVHGTPD
KPNKAKFMRSPSVLIDGFYWNIKYYPHGNDG-----------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------TEQLSIYIECSPTPYETAEAEAKKAD
TEEKKAATPTPALSA---------------------------------------------
------------------------------------------------------------
------------------------------------------------DQGAIPVIDPEA
SASDNAPAPPAEEAAPSVSVNAAPSAHADDMEATPTSVKKLEPEEEEPWGIPAQISCVIY
NPNEPRVNFSQKGCHRFYNDN---------------------PDWGWTRFHGPWDEIHKR
QRYQRQALLRNDTLSMTAYIRTFKDDTKALWWHPPKDKAEWDCMTMTGVRSFDCHHQSTA
LIAAISSWLHLTPIVDLIRNMHVPDPIWEANLRMRPAYEDLQDILDGDTGAAFTEERELD
LLPLLKTLNFYGADVDGKMDVVMIWETLRRILNFEASGLDTVAECKSSGNNMFNDVLVLK
QPDPFGNDTNLSYQPQLRQIEAQESEAHSVQETIDLASHYKEKAFRMWRSFAGEEQNLAQ
NPAVLQIELHRQRFLKEARKWKKLTHRVELNETVIFNSYEYTLYGMIVHSGDLESKDYYS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------VIRPEGPGTRWLKYAGDNSHRKVEILTTKKAIYAHEGVGMSAD
GTAAVAYIALYVRTDRLPSVLCTPFKSKS---LPQVVVEKSSGTITAGDGGLSDSKDNEE
EMQEDMPVYIYGSELFNEHTGRGLCDPWVEQNRGNWVKEFKFPPKTTITEIKKTLIDKAP
GHVVVEKSSGTITAGDGGPSDSKDNEEEMQEDMPVYIYGSELFNEHTGRGLCDPWVEKNR
GNWVKEFKFPPKTTISEIKKTLIDKAPGHVRLWPMFTMVSGANAYPSLNFGNSAENSLEE
IASQTGGCRFWMFSGGPDSTGATASPPAQPASEEQHARVAAEAAQRAALLAAIRAEAAVD
RIIATGDDTEMAEAANTLQQEGLAATITHDRQSLQQSSGMLSSESSNTTPTRTTYFLVKL
FDTESQSLRGMGSHVVKSEAKISEEVKKLLKVDSHESWDLWIEQGLHIRPKDQIKSNATF
EGIFGGANGNIIIAQRHLTSAQVASLEAEGKCSNPMEYFHYLHGHDNPTYFQEHVTNSYF
GRYYSSCSVKMGRAHGQGTLVTLAGDAYTGTFVAGEKSGQGNMAYANGDTYTGEWKANEP
NGQGRMVYAKTGNVYTGGFKKRKRHGKGHMVFEVADEEMHLCKICYEMGRAHGQGTLVTL
AGDAYTGTFVAGEKSGQGNMAYANGGTYTGEWKANEPNGQGRMVYAKTGNVYTGGFKKRK
R-----------------------------------------------------------
---------------------------------------------------HGKGHMVFE
VADEEMHLCKICYEVEMDALFYD--------------CGHVVACDECARQVD--------
--VCPVCRRNVRAVVKIWKT----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>AT4G03965.1|PACid:19647576
MSQLG-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------VETSQAQPE
TPQSTTFLDLLRLQMDGL------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------DRSRRRKRTLKERLGFKRI-------------------
------------------------------------GCCGPTWGLRLTSNTGEDDDEPFE
NRLVSG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------SDHVTGPL-------------NQGMNLATALAAERN
YRTEETEASGSLTPLKVSLMRL--------------------------------------
----------------------------------LEETAERVVVEENETERVTASASSTV
RGVNNDSVCCVCMGRKKGAAFIP--------------CGHTF-CRVCSREVWLNRG----
--SCPLCNRPIIEILDIY------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|2015 @Cladonia_grayi@ jgi|Clagr2|115687|estExt_fgenesh1_pm.C_530012
MKIIIVGAGNSGLTTYLFLEKLLPSALPHDVQIEITIYEKHQAGVEKYPTSGSTTVGGAL
GIVPNGLHVLQDLNEE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LFEKIVAKGYSCSHFCMRNSYG
YTLARFPTIDHGPPPMYTVMIGRQDFWQCLREAVPDKAIVHANV-------LEVTCGQSR
QARLKFADGSPDVEADLIIGADGVRSIVKKAVTGDGKIDHHPPTYEGLVGIGGFISASTL
GSTYPPGQTTMTFGAHGFFGYGPCNLAPQV------------------------------
------------------------------------------------------------
-------------------------------NGSDKITPTNRADQIPSPETPLHEAIWWS
TYQVDTPPSTTHPDL---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SAIKFQLQSR---------
-------------------------HSNWKDPII--------------QKIISTATVDSV
YPTW--------------------------------------------------------
------------------------------------------------------------
-------------------------TTPQLPTWSNKNAVLVGDAAHALQPSSGQGASQA-
---------------------------------------------LEDAQAFSMLLAHFL
HQSHSPSPPPSPSPSPSPSPS---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------PSPSPSPSPSHTPLPPS----------------------------------
----------------------------------QAIPLALKKYEEIRKPRVTAIQEHSK
RFGD--------------------------------------------------------
--------MKRRKGFLEEWMTYFFIWMMGKWGGVGGKGGAL-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
