>Jannaschia_sp_CCS1 gnl |BL_ORD_ID|762	gi|89053183|ref|YP_508634.1| unnamed protein product [Jannaschia sp. CCS1]
M-----------------------------------------------------------
----WDIFAIMGVTCA----------------LCAVGLSLIMTS-HGQGAAIMSVFTVAA
LVGLF-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------ALDGRPGMLLAFGAGAGVFGCAAAIGTFR---------------------F
WHGGTPLARAGLTLAILAGLAAT----------LGLAAYLAIPR----------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Rhodomicrobium_vannielii_ATCC_17100 gnl |BL_ORD_ID|2107	gi|312114902|ref|YP_004012498.1| hypothetical protein Rvan_2174 [Rhodomicrobium vannielii ATCC 17100]
MRTPLR-----------------LLHAITGFVGLVIILRFLGHTAYAELYGDAASILAVK
SWIVWRLPVLIVALAV----------------AGATGFALAGPSPRGLAARKLARMRVIA
VNGILVLVPAAIFLFWK-------------AEAGEFDA----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TFAALQTIEFIAGGVNIVLIGMSFRDGLRLTGRLRRCPDAPARRS----------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>SP1_NM_105064
M-----------IPWG--------------------------------------------
-----------GVTCC----------------LSAAALYLLGRS-SGRDAEVLETVTRVN
QLKELA--------QLL--------------ELDSKIL---------PFIVAVSGRVGS-
-ETPIKCEHSGIRGVIVEETAEQ------------------------------HFLKHNE
TGS-W-------------------------------------------------------
----------------------------VQDSALMLSM-----------------SKEVP
WFL---D--DGTS-R-VHVMGARGATGFALTVGSEVFEESGR-SLVRGTLD--------Y
LQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFR--IQKPD-RG-PFYVSSKSLDQL
ISNLGKWSRLYKYASMGFTVLGVFL---ITKHVIDSVLER------RRRRQLQ-KRVLDA
AAKR-AELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSS
HL-----TSCPLCRRRIDLAVKTYRH
>SPL1_NP_564745_AT1G59560
M-----------IHLA--------------------------------------------
-----------GFTCC----------------LGGVALYLLTRS-TGRD---IKSITRVY
QLKDLE--------QLV--------------EVESKVV---------PLIIAVSGDVGS-
-ETPIKCEHSYVLGVFLKRTAEQ------------------------------QVLRRNW
RFS-W-------------------------------------------------------
----------------------------VRNSTLMQPM-----------------TKEVP
WYL---D--DGTG-R-VNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALG--------Y
LKGFKILGVRHVERVVPIGTPLTVVGEAVRDGMGNVR--IQKPE-QG-PFYVTYIPLDQL
ISKLGDLSRRFKYASMGLTVLGVIL---ISKPVIEYILKRIEDTLERRRRQFALKRVVDA
AARR-AKPVTGG----------GTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCSL
QL-----RTCPLCRERIQQVLKIYRH
>Mulan_NP_078820
MESGGRPSLCQFILLG--------------------------------------------
-------------TTS----------------VVTAALYSVYRQ-KARVSQELKGAKKVH
LGEDLK--------SIL-------------SEAPGKCV---------PYAV-IEGAVRSV
KETLNSQFVENCKGVIQRLTLQE------------------------------HKMVWNR
TTHLW-------------------------------------------------------
----------------------------NDCSKIIHQR-----------------TNTVP
FDLVPHE--DGVDVA-VRVLKPLDSVDLGLETVYEKFHPSIQ-SFTDVIGH--------Y
ISGERPKGIQETEEMLKVGATLTGVGELVLDN-NSVR--LQPPK-QGMQYYLSSQDFDSL
LQRQESSVRLWKVLAL---VFG--F---ATCATLFFILRK--QYLQRQER-LRLKQMQEE
FQEHEAQLLSRAKPEDRESLKSA----------CVVCLSSFKSCVFLECGHVCSCTECYR
ALPEP--KKCPICRQAITRVIPLYNS
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDG---------------------------------------
--------AILGLTLA----------------VSAVGSALKYAS-TNAALKKIKDAPEVS
I-SDLR--------SLL-------------PASEDKSETNDNRKSNDQRIVVVRGVVKP-
-KISGDEGYKNNNVLISPETGDK------------------------------ALIIQRT
QTYVY-------------------------------------------------------
----------------------------SGWKRLFQSTGHRFMLERSLRKHGADFTRTVP
FVIVGKD--QQSNSSFVAVNMDGSRQPLPLTTVYNRLQPINS-SFLQA-----------F
LYPDYPVGLLDIEKILPPGKDITAVGIYSFNN-GVPE--IKSCQ-DL-PYFLSEMTKDKM
IEDLMEQTNFIFLGSVILGIVSVGI---LSYAAVRTWNKWKQWNHQRELPQRPNDSVVDD
EPED-ADEIPDG-------------------ELCVICVSRRRVPAFIPCGHVVCCRRCAS
TVERELNPKCPVCLQSIRGSMRVYYS
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656	 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece			
M-----------------------------------------------------------
--------ILIGIICL----------------IVGVILLFFWRS-NRSKLRNLRLASAST
ISSLQTIAN-----QIA-------------EEIGGGSL---------REYVKIRGVIEC-
-DRPLISQLKQEPCVYYSMTVTWEYNE--------------------------EVIKQDN
EGKTI-------------------------------------------------------
-------------------------REKERKSETVAQN-----------------SRSIP
FTL---Q--DSTG-E-IRVNPERAEIE-TVKVLEE-FRPENFSGG-SLTFGNFSINLPSF
EERRQTIGYRYQEEILPIGRQILVIGTATDEE-GMIT--IRKPTEKGQRYFISLKSEEEL
SQATNNAIRGTFYSMIFFLTLGLIL---LVAGVLR----G--------------------
------------------------------------------------------------
--------------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|2513	 637618204 syc2512_d hypothetical protein [Synechococcus elongatus			
MAA---------------------------------------------------------
--------IILAAITA----------------IAAIVLYFVRRH-YRFKLQSLLLAQPAT
SLQLKEIAE-----HVA-------------GEIGGGNL---------RQYVKMWGAIEV-
-EQPLVSELKQESCVYYCSTVSREYEE--------------------------RVRKEDS
EGKVT-------------------------------------------------------
-------------------------WTTERRSETISQN-----------------RRSTP
FYL---R--DQHG-R-VRVEPESAAIA-TIPVLDE-FRPDS-SAS-SLIFGAFSLSLSTT
AGLGKTLGYRYREEILPCDRSVLVVGAASDET-GELT--LGPSSEARQQFFIALKPETAL
LQEVKQTIQWLTIGAIASVVVTVVA---AIAALL--------------------------
------------------------------------------------------------
--------------------------
>Synechococcus_elongatus_PCC_7942_gnl|BL_ORD_ID|1573	 gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococc			
MAA---------------------------------------------------------
--------IILAAITA----------------IAAIVLYFVRRH-YRFKLQSLLLAQPAT
SLQLKEIAE-----HVA-------------GEIGGGNL---------RQYVKMWGAIEV-
-EQPLVSELKQESCVYYCSTVSREYEE--------------------------RVRKEDS
EGKVT-------------------------------------------------------
-------------------------WTTERRSETISQN-----------------RRSTP
FYL---R--DQHG-R-VRVEPESAAIA-TIPVLDE-FRPDS-SAS-SLIFGAFSLSLSTT
AGLGKTLGYRYREEILPCDRSVLVVGAASDET-GELT--LGPSSEARQQFFIALKPETAL
LQEVKQTIQWLTIGAIASVVVTVVA---AIAALL--------------------------
------------------------------------------------------------
--------------------------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|198	 637312804 tll0199 hypothetical protein [Thermosynechococcus elo			
M-----------------------------------------------------------
--------GVFAHLCL----------------TGSAFLFALEGY-YRLQLRGIKVASPST
IGELEKFQQ-----QVA-------------QEMGSGSW---------REYVQVVGQVTT-
-SQPLLSEVKRIPCVYYKTIISREYEK--------------------------E------
------------------------------------------------------------
--------------------------GSDRPSEIIGRH-----------------EQSTL
FLL---R--DHQG-E-IEVNPFGAEIE-AVQVLDE-LRPADQPHAFALSLGFLSFNW--H
FGKGTTLGYRYQEWVLPLGQPVSVVGMASDQG-GVLR--LQKPQNRGQKFIISLSFEDPL
IQQYKQQKRKMTYASLGATLCGVCG---LVLALF--------------------------
------------------------------------------------------------
--------------------------
>Synechococcus_sp_JA_2_3B_a2_13_gnl|BL_ORD_ID|170	 637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba			
MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPPPE
RKAFMNWLMLLGLLCL----------------PAS--LFSFVEY-----LRSQRLVQQLS
ATRLLKIAELRHLGQTN-------------PQAKGANL------------AQVYGRVVC-
-DRPLVSELSRQPCVYYKSEISWEYDEIECYRRYLNSRGDVAYSERISEGEYQNALRLGS
RAKSYPGEMVGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPNPGYPQQLGSPGYPQKSPFS
EVSSPQKHYANVYYDPSTGREYLLERETRTRDETLHSV-----------------VRQIP
FFI---E--DETG-R-VRVDPTGAEIE-AMSVVDEHIFPGKGPSRFNFNLKRYLSGV--R
TENRSTRAFIYKEWVIPVDAMAFTMGQVRFEA-GDPV--IRKPL-SGERFMIAPKSPEAL
LEEQRSNASSYLVGSVVLLGIGIFT---VLHLLQSLQPYR--------------------
------------------------------------------------------------
--------------------------
>Rickettsia_akari_str_Hartford gnl|BL_ORD_ID|412	gi|157825538|ref|YP_001493258.1| unnamed protein product [Rickettsia akari str. Hartford]
MSDLFSNVNNSFVQYM--------------------------------------------
--KYPVVLSIVICFCL----------------VACVE-----------------------
-----------------------------------------------QPPAPIEYKVGDV
TANNNSTALEHDEGLIVQRTMED------------------------------DTVSEKV
SGILE-------------------------------------------------------
----------------------------EPKAKIIECY----------------------
------N--DD-----IEIPISRNEYEEEIEQ-SNFVKPLNGVMLTEFKDG---------
KSKGIDIAVKEYSDVKSIAAGTVIYSGFNKQF-GNLV--IVKLDKD--DLEVAYASLDDL
LLKKGDK-----------------I---TKNSVIGHVKHKLYFAMRRNRIAVDPSKYIEF
------------------------------------------------------------
--------------------------
>Raphidiopsis_brookii_D9_gnl|BL_ORD_ID|839	 647108643 CRD_01208 conserved hypothetical protein [Raphidiopsis brookii D			
MKQSFFNRQLT-------------------------------------------------
--------QFVGILLG-----------------------------MGVALFILRGLRIIT
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------LPSGIIGLLFLGAIAIGVLSYLQTKWWRF----------------
------------------------------------------------------------
--------------------------
>Paracoccus_denitrificans_PD1222 gnl|BL_ORD_ID|833	gi|119383591|ref|YP_914647.1| unnamed protein product [Paracoccus denitrificans PD1222]
MSGAKALDALARRLLPAGYGC---------------------------------------
-----------AVLPL----------------AAEPAPLLPEEA-GAVARAVPKRRREFA
LGRMALRAAIRQAGHDL-------------PA----------------------------
-TRPIAARADRQP-----------------------------------------------
------------------------------------------------------------
---------------------------------------------------------DLP
PGIRASL--SHGGDYCIAIAAPPGGASVGID-----LEPCDRAVPEGLAETIMPFRL--R
GPKDALLAFCAKEAMFKAQYPLT----------GRMLDFRAVPAVIGPRRFRACMGDRLI
GGRWGQAAGYWLALSLWSG-----------------------------------------
------------------------------------------------------------
--------------------------
>Gluconacetobacter_xylinus_NBRC_3288 gnl|BL_ORD_ID|2765	gi|347761906|ref|YP_004869467.1| unnamed protein product [Gluconacetobacter xylinus NBRC 3288]
MKTAIWN-----------------------------------------------------
--------------------------------RGQTGFRHSLRHGEATHKAVDGRTKLKT
DENAVADAIGQLVLPFTHTPRFAADDFVFSPSNAAARSWLLGPTPWPERRLALWGPAGTG
KTHMLDIWVR--------------------------------------------------
------------------------------------------------------------
----------------------------------MHEALLLHGASLSHAHVAGLFAAPVP
VMAIALDGADQCGDERALLHLINTAREHGMALLLGARTP---------------------
-PARWPVGLPDLASRLRATMAVA-----MGQPGDGLLRVLLLRLLAERQIVVAQPVVEWL
LRRLPRTARAMQAAVRRLDHAALATGRPVTRALAAHVLSDMLAGSESHAFVPDP------
------------------------------------------------------------
--------------------------
>Prochlorococcus_sp_WH_7803_gnl|BL_ORD_ID|565	 640542918 SynWH7803_0566 hypothetical protein [Prochlorococcus sp. WH 7			
MEDSLS------------------------------------------------------
---------------------------------------------WPLSRSLLDAVLADR
LSDRLVAELVWERLGYR-------------RQRDGDAPWLAGPQTPQAWRDAFPEAPEVV
ATRPASVALTRSIA----------------------------------------------
------------------------------------------------------------
----------------------------REHKQLLKKQLHFAGYRIGELYPRRTRRATVV
SWLLAWL--AARG----DVLPADGALP---ELLDPPVNPVQG------------------
HPGDAPVG----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Synechococcus_WH_7803_gnl|BL_ORD_ID|565	 gi|148238902|ref|YP_001224289.1| hypothetical protein SynWH7803_0566 [Synech			
MEDSLS------------------------------------------------------
---------------------------------------------WPLSRSLLDAVLADR
LSDRLVAELVWERLGYR-------------RQRDGDAPWLAGPQTPQAWRDAFPEAPEVV
ATRPASVALTRSIA----------------------------------------------
------------------------------------------------------------
----------------------------REHKQLLKKQLHFAGYRIGELYPRRTRRATVV
SWLLAWL--AARG----DVLPADGALP---ELLDPPVNPVQG------------------
HPGDAPVG----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Sphingobium_sp_SYK-6 gnl |BL_ORD_ID|2360	gi|347528596|ref|YP_004835343.1| unnamed protein product [Sphingobium sp. SYK-6]
M-----------------------------------------------------------
----------------------------------------------ARSKMIGAKAHVAR
LRKLAGEATVRRVGKAL-------------FAA--------------GELIQVESQIGI-
-TSGAVSGKNHTPG----------------------------------------------
------------------------------------------------------------
---------PVGGYPNADTHLLADSHETNQIAPLVVEI-----------------SVNAP
YAGYVHDGTSRMG-----------------------------------------------
---------------------------------ARPYLQLARDAKKTEVTQLVRRAVDRA
VKTSRGTE----------------------------------------------------
------------------------------------------------------------
--------------------------
>Synechococcus_sp_RS9917_gnl|BL_ORD_ID|2449	 638963634 RS9917_01901 hypothetical protein [Synechococcus sp. RS9917]			
M-----------------------------------------------------------
---------LFMVLCS---------------SPAQARFAAFAEPEGGDDVAVIEHLKLKV
------------------------------PEAARQAWLEAERGSWEPWLSRQQGFLGR-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--DLLWNPETEEGTLLIRWHSREAWKAIPLQEVEAVQQRFEQ------------------
------LAREATGQRLGNPFPLLYAGELLPQ-----------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Hyphomicrobium_denitrificans_ATCC_51888 gnl|BL_ORD_ID|1739	gi|300023278|ref|YP_003755889.1| hypothetical protein Hden_1765 [Hyphomicrobium denitrificans ATCC 51888]
M------------------LERDLYEPVYNYLELRFRDRLQPARGDLRHITAITANTGGN
ATGIWSKPDLCIISLS----------------RQKYGLSWQIDL-HGFEVKPQGACSVQS
VHEALNHTSLVNFTHLV-------------WHVGDWNE----------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------SRADCSTILSRC----------------------
---------SHYGVGLITFSTPGDLTSYVLHLPARRHEPSSD------------------
-------------------------------------------------------AFDEF
VETRLSQDDRTKLLSWITELRR--------------------------------------
------------------------------------------------------------
--------------------------
>Mesorhizobium_ciceri_biovar_biserrulae_WSM1271 gnl|BL_ORD_ID|5854	gi|319785210|ref|YP_004144686.1| unnamed protein product [Mesorhizobium ciceri biovar biserrulae WSM1271]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------SLAPITY
GPIGSPLGARFSSYLGSMGRYVVLPIQLVKHG----------------PMLLGHIPICWE
VQQLADLMAQCL------------------------------------------------
------------------------------------------------------------
--------------------------
>Mesorhizobium_opportunistum_WSM2075 gnl|BL_ORD_ID|6022	gi|337270560|ref|YP_004614615.1| hypothetical protein Mesop_6120 [Mesorhizobium opportunistum WSM2075]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------SLAPITY
GPIGSPLGARFSSYLGSMGRYVVLPIQLVKHG----------------PMLLGHIPICWE
VQQLADLMAQCL------------------------------------------------
------------------------------------------------------------
--------------------------
>Cyanothece_sp_BH68_ATCC_51142_gnl|BL_ORD_ID|4859	 641679280 cce_4771 hypothetical protein [Cyanothece sp. BH68, ATCC 5			
M-----------------------------------------------------------
--------NFEGLICEHNRSHPYYRFSYLPENIKQFMFTLILTARGSGIKAISARIKLEK
FTQMSNEDIISLYQESF-------------PGSESNDN---------------------M
DTKPNNKGLNHSFFNY--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
