>rsz31o21
ttccgaatntgcaaaagtgaatctacaggtgaacgacagatggggcaacgatcgctacgc
acgcgcaacaactgtgctcagtctacacagagacacaggtggccacacggcagcaccgtg
gtatcccgcgggtccgtcatgcaaatgatacagagatcatcgtgttctgcttcagcggct
gctcttggcgagatcttcggcgctctcaaggcgctgcagcagaatcacaatcgggtatcg
atgcttggcgagtttggccgggttctgttcgaaaagaaacgactcgcgatatcgactggg
cacgaaaccgcggtggctattctggcggtaccgctggcccataccggcctcgaatggggt
aggtactgggggcaccggctccagcggctcgacatggaactgctcagcgcgcgttgtgcg
gttcgtgaggnnccttcgccatgaagaagactgtgcagaggcccgagcacgtttgcganc
aaaaacaaactccaacanaaactgctgtggattttcgggatctctaacaaggcgtacact
cttcttccgaacattcaagtcgttctttatggtgtacgcgtgaaccatggtcggaaccgg
ctgtgtggaacgctccgcaccaccctgcag

