>SPL2_NP_564653
M-------------------------S--SPER-ALLNLLTDIALSFDGAILGLTLAVSA
VGSALKYASTNAAL--------KKIKDAPE------------------------VSISDL
RSLLP------ASEDKS-------------------------------------------
------------------------------------ETNDNRKSNDQRIVVVRGVVKPKI
SGD-EGYK----NNNVLISPETGDKALIIQRTQTYVYSGWKRLFQST-----GHRFMLER
S----LR------KHGADFTRTVPFVIVGKDQQSN------SSFVAVNMDGSR--QPLPL
TTVYNRLQPINSS---FLQAFLYPD-------------------------YPVGLLDIEK
ILPPGKDITAVGIYSFNN-GVPEIKSCQDLPYFLSEMTKDKMIEDLMEQTNFIFLGSVIL
GIVSVGILSYAAVRT----------------WNKWKQWNHQRELPQRPND----------
-------------------------------SVV-D-DEPEDADEIPDGELCVICVSRRR
VPAF--IPCGHVVCCRRCASTVER---ELNPKCPVCL-QSIRGSMRVYYS-----
>Arabidopsis_lyrata_gnl_BL_ORD_ID_6881__474546_PACid_16040628
M-------------------------S--SPER-ALLNLLTDIALSFDGAILGLTLAISA
VGSALKYASTNAAL--------NKIKEAPE------------------------VSVADL
RSLLP------VSEDKS-------------------------------------------
------------------------------------ETNDHG-----KIVVVRGVVKPKY
SGD-ESHK----NNNVLISPETGDKALIIQRTQTYVYSGWKRLFQST-----GHRFMLER
S----MR------KHGADFMRTVPFVIVGKDQQSQ------STFLDVNMDGSR--QPLPL
TTVYNRLQPINSS---FLQAFLFPD-------------------------YPVGLLDIEK
ILPPGKDITAVGICSFNN-GVPEIKSCQDLPYFLSEMTKDKMIEELMDQTSFIFFGSVIL
GIVSVGILSYAAVRT----------------WNKWKQWNHQRDLPQRPNE----------
-------------------------------PVV-D-DEPEDADEIPDGELCVICVTRRR
VPAF--IPCGHVVCCRVCASTVER---ELNPKCPVCL-QSIRGSMRVYYS-----
>Brassica_rapa_gnl_BL_ORD_ID_14784__037967_PACid_22698294
M-------------------------S--SPDRSAVFPLLIDIALSFDGAILGVTLALGA
VRAAFKYASTSAAL--------NKIKDAPE------------------------VSVSDL
RSLIP------ASDDQS-------------------------------------------
------------------------------------ET----SGEQERIVVVRGTVKAKV
TGGEGSNKQ---NNNVLISQETGDKALIIHRSQTYVYSGWKTLFQLTN----GHRFLLER
S----LP------KQGADFMRMVPFVIVDNTQPSQ------SSFVVVNMDGAR--QPLPL
TTVYNRLQPINSSPYAFLQALFFPE-------------------------YPVGLIDVEK
ILPPGRDLTAVGICSFNN-GVPEIKSCQDLPYFLSEMTKDKMILDLAETTSVIFWGGIIM
GCLSAGILGFAAARA----------------WNRWKQRHHEREQQQRPDEQ---------
---------------------------RPEQPMV-A-DETEDEDEIPDGALCVICVTRRR
VPAF--IPCGHVVCCRQCASTVER---EVNPKCPVCL-QSIRGSMRVYYS-----
>Thellungiella_halophila_gnl_BL_ORD_ID_4555__Thhalv10011564m_PACid_20184051
M-------------------------S--SPDR-AIFNLLTDIALSFDGAFLGVTLAYGA
IRSAFKYASSSAAL--------SKIKDAPE------------------------VSVSDR
RSLIP------ASEDQS-------------------------------------------
------------------------------------ENRDHGNSHDQRIVVVRGTVRPKF
TGD-GSHK-----DNVLISQETGDKALIIQRTQTYTYSGWKTLFQLSN----THRFLFER
SM---MP------KQETALTRMVPFVIVEKNQRSQ------SSFLLVNMDGAR--QPLPL
TTVYNRLQPINSTPFAFLQVLFFPE-------------------------YPVGLLDVEN
ILPPGRDLTAVGVCSLNN-GVPEIKSCQDLPFFLSEMTKDKMILDLMHTTRVTFWAGVVM
GCLSAGILGLVAVRT----------------WKRWKLRYHQREPLQRPDE----------
-------------------------------PVV-D-DETEDADEIPDGQLCVICVTRRR
IPAF--IPCGHVVCCRQCALTVER---ALNPKCPVCL-QSIRGSMRVYYS-----
>Carica_papaya_gnl_BL_ORD_ID_10657__evm.model.supercontig_25.125_PACid_16414718
M-------------------------S--SPEQ-ALASLVSHLALSLDGAVLGVALAYAA
VRSFFKFTANSAAL--------RKIRSAPQ------------------------LRVSDL
RSLLP------VSSEDQ-------------------------------------------
-------------------------------------SQPSDSDPSSTLVIVRGTVEAKS
AVD-GSWKGL-RHNNVLVSQESGDKAVVIQRTQTYIYNEWKGFFGWTS----DLRAIFGR
S----WG------KQESASSRMVPFVLVEDGRWPQ------SDYVIVNTEGSL--HPLPL
TTVYHQLQPVNASPYTFLQALFGHE-------------------------YPVGLLNEEK
ILPLGKDISAVGICSFKN-GIPEIMSCKDLPYFLSDLTKDQMLLDLAFRTKILFWSGIIL
GSLSISILGYAALRN----------------WNRWKERRQQRQAHQPSHAA---------
---------------------------SIDANSE-L-TGEEEIGDIPDGQLCVICLMRRR
VPAF--IPCGHIACCQPCALSVER---ELTPKCPVCR-QEIRGSMRVFYA-----
>Ricinus_communis_gnl_BL_ORD_ID_8129__29706.m001280_PACid_16806294
M-------------------------S--SHEQ-ALASLVSQLALSFDGAFLGVVVALTA
VRSILKFASNSKAL--------RKIRNAPT------------------------VKVSDI
RSVLE------VSDETQ-------------------------------------------
---------------------------------------------DQKLVIVRGQVEAKS
AVD-GNWKSLIPNNNVLVAHESGDKAVIVQRIQTCIYNEWKGFFGWTS----DIRAIFGR
S----WR------EQESTLSRSVPFVLVEAGRWPQ------SDYVIVNLDGSR--HPLPL
TTVYHQLQPIDASPYTFLQAFFGYE-------------------------YPVGLLDEEK
ILPLGKEINAVGLCGSKN-GILEITSCKDLPFFLSDLSKEQMVVDLAFKTKVLFWSGVVL
GSFSICILGYAAVRN----------------WNRWKAWRQQRQFQQQSNSV---------
---------------------------SDADVSQ-I-DVEEETVDVPDGQLCVICLMRRR
RAAF--IPCGHLVCCQICAISVER---EVSPKCPLCR-QAVRNSIRIFEC-----
>Populus_trichocarpa_gnl_BL_ORD_ID_12209__POPTR_0003s06390.1_PACid_18218320
M-------------------------ASRAHEQ-ALAAMLSHLALSFDGAILGAALAYAA
VRSFLNFTANSKSL--------AKIRKAPT------------------------LSVSDL
RSLLQ------NHDQDH-------------------------------------------
------------------------------------------QDQEQKLVIVRGQVEAKS
AVD-GSGKKSSRDSNVLLSHESGDKAVILQRTQTCIYNEWKGFFGWTS----DLRSIFGR
S----LK------EQETTFLRTVPFTLVEGGQWPQ------SDYVIVNMDGSS--HPLPL
TMVYHQLQPIVASRYTFIQALFGHE-------------------------YPVGVLHEEK
ILPLGKCISAVGICNSKD-GIPEIKSCKELPYFLADMTKDEMVADLAFKAKILLWSGIVL
GSLSIGVLGFAVMRN----------------WNKWKAWRQRRS-QQPIHTT---------
---------------------------SDEDVSQ-I-DDNEDAGDVPEGQLCVICLMRRR
RAAF--IPCGHLACCHTCAVSVES---EVSPKCPLCR-QAVRNSIRIFEC-----
>Eucalyptus_grandis_gnl_BL_ORD_ID_23965__F04419.1_PACid_23585686
M-------------------------S--SHEQ-AIVSLLSNFALSFDGAVLGLTLAYAA
VRTIVKLTSSSSAL--------RKLQDAPS------------------------VRVSDL
RSVLS------LEGGSD-------------------------------------------
-----------------------------------SEPDSSSRSGREDLVIVRGLVEAKS
AVEGGTWKSL--RQNVLVSQDSGDRAVIVQRTQTCIYNEWKGFFGWTS----DLRAILSR
S----LR------ERKSSSLRTVPFVLIDGSQWPA------VDYVVVNMDGSK--HHLPL
TTVYHQLQPINASPYTFLQALFGHE-------------------------YPVGLLDEEK
ILPIGKDVSAVGLCFLKN-GILEIKSCKDLPYFLTEMTKDQMVIDLAFRTKILFWSSIFL
GSASIGILGFAFVRN----------------WNRWKEWRQRRRDEQQSHAA---------
---------------------------VDEATAH-I-A-EDELGDAPDGQLCVICLMRRR
RSAF--VPCGHLVCCQRCALSVER---EVSPKCPVCR-QTITNSVRIYDS-----
>Glycine_max_gnl_BL_ORD_ID_43458__16g01030.1_PACid_16301042
M-------------------------S--HQEQ-AVLSLLSKLALSFDGAVLGVALAFAA
VRTLFKFTATSASL--------RKLRRAPS------------------------ISVSDL
RSLLA------EPPSDA-------------------------------------------
--------------------------------------------DAGEIVIIRGTVDAKS
AVD-GTWKTL--KPGVLVSRESGDKGVILQRTQTCIYNDWKGLLGWTS----DLRAICAR
S----LR------QQDSTSFRKVPFVLIDVGRRPN------AEYVVVNMDGSR--HPLPL
TTVYHKLQPINASPYTFLQALFGHE-------------------------YPVGLLDEEK
ILPLGKDITAVGHCSLKN-GIAEIKSCKDIPYFLSDLSKDQMIVDLSIKAKILFWGGISL
GSMSVGVLGYAVLRN----------------WIKWKRWKVQRQLQQQRQAV---------
---------------------------SDAEP-----QVDDEIEDVPDGQLCVICLMRRR
RSVF--IPCGHLVCCQGCAISVER---EVAPKCPVCR-QEIRDSVRTYES-----
>Phaseolus_vulgaris_gnl_BL_ORD_ID_21270__091018531m_PACid_23552061
M-------------------------S--HQEQ-ALVSLLSQLALSFDGAVLGFALAYAA
IRTLVKFSATSAAL--------RKLRRAPY------------------------LSVSDL
RSLLA------DTPSDA-------------------------------------------
----------------------------------------NSNSDGGAIVIVRGNVDAKS
AVD-GSWKTL--RPGVLVSRESGDRGVILQRTQTCIYNEWKGLFGWTS----DLRAIFAR
S----WR------QQESTSLRKVPFVLIDVGWRPS------TEYVVVNMDGSR--HPLPL
TTVYHKLQPINASPYTFLQALFGHE-------------------------YPVGLLDEEK
ILPVGKDVTAVGLVSLNN-GVAEIKSCKDLPYFLSDLSKDQMIVDLSIKTKILFWGGIAL
GSMSVGILGYAVVRN----------------WNKWKQWKLQRQLQQQRQAV---------
---------------------------SDVEP-----QVDDEIEDVPDGQLCVICLMRRR
RSVF--IPCGHLVCCQGCAISVEH---EVAPKCPVCR-QEIRNSVRIFES-----
>Medicago_truncatula_gnl_BL_ORD_ID_48043__Medtr8g025010.1_PACid_17479694
M-------------------------S--SQEQ-ALVSLLSQLALSFDGAVLGFAVAYVA
VRSIRKFTLTSAAL--------RKITAAPS------------------------VSVSDL
RSLLT------ETDENS-------------------------------------------
--------------------------------------------DEGKIVIVRGTVDAKN
VVD-GSWKAL--WPGVLVSSESGDKGVVLQRTQTCIYNEWKGLFGWTS----DLRALFLR
S----WR------QQESTSLRKIPFVLIDVGRPSN------PEYVVVNMDGSS--HPLPL
TTVYHRLQPVNPPPYTFLQALFGHE-------------------------YPVGLLDEEK
ILPLGKDVSAVGLCSLRN-GIAEIKACNDLPYYLSDLSKDQMIVDLSFKTKLLFWSGILL
GSMSVGIIGYAVVRN----------------WNKWKQWKQQRQLQQRRQQP---------
---------------------------IEPVP-----PTDDEIEDVPDGQLCVICLMRRR
RSVF--IPCGHLVCCQGCAISVES---EVAPKCPVCR-QEVRDSVRIFES-----
>Prunus_persica_gnl_BL_ORD_ID_16287__ppa006914m_PACid_17656817
M-------------------------S--SHEQ-ALISLVSQLALSFDGAILGVALAYAA
VRTVLKLNSVSSAL--------RKLHNAPS------------------------VQVSDL
RSILS------LDHSDE-------------------------------------------
-----------------------------------------SQPSDAKLVVVRGTVEAKS
AVD-GNWNIL--NSGVLVSQGTKERAVVLQRTQTCVYNEWKGFVGWPS----DLRAIFSR
S----WR------ERESKVFRTVPFILAEGGRRPI------SEFVAVDMDGSR--HPLPL
TTVYHHLHPVNPSPYTFLEALFGHR-------------------------YPVGLLDEEK
ILPLGKEISAVGLCSVKD-GVLEIKSCKDFPYFLSEMSKDQMVVDLTSRTKVLFWSGIFL
GSVSIGVLAYAVSRN----------------WNRWKVWRQQRELQRSIRAS---------
---------------------------NAEAQIQEE-EEEEDAGDVPDGQLCVICLMRRR
RSAF--IPCGHLVCCQLCSISIER---DVAPKCPVCR-QQIRTSVRIYDS-----
>Cucumis_sativus_gnl_BL_ORD_ID_29614__360260.1_PACid_16980714
M-------------------------S--TSEQ-ALVTLLSRFALSFDGAVLGAALAYAT
VRTVLKLTASCSAL--------NELRKAPY------------------------VTVSDL
RHIVS------DGVSEQ-------------------------------------------
------------------------------------------SESDRKLVVVRGTVETRS
SVE-GNRKSL--QPNVLISQESGDRAVIIQRTQVCIFNEWKGFFGWTS----DLRAIFGR
T----FR------KQESTSFRTVPFVLLE-GHSTY------SDFVVVNMEGSR--HPLPL
TTVYHQLQPVCATPYTFLQAVFGHE-------------------------YPVGVLDEEK
ILPLGKNISAVGICSFEN-GVPVIKSCSDFPHFLCEMTKDQMILDLVFKTKFLFWSSIVL
GSLTVGILGYSAARN----------------WNRWKQWRQHRQLQNSRNDSPTSQLDSSN
DIPIYGDFASDDEAATVPDDELSSHVPDDELSSH-V-PDDELSSHVPDGQLCVICLMRRK
RSAF--IPCGHLVCCERCAVSVER---ESSPKCPICR-QQIRSSVRIYDS-----
>Malus_domestica_gnl_BL_ORD_ID_47849__0000215866_PACid_22667834
M-------------------------S--SDSN-AIISLLSQLVLSWDGAVLGVALACAA
MRSVLNFTASSSAL--------RNLRQAPA------------------------VKVSDL
RSILP------LDHSD--------------------------------------------
-----------------------------------------------KLVVVRGTVEAKS
LVD-GTWTAF--KSGVLVSKDRNDRAVILQSTKTYIIHKWKGFIGFF-----NLRSIVWR
Y----WRHWKDSEEHESNLVRKVPFVLVDGDQWPI------RDMVVVNVDGSS--HPIPL
TIAYHHLQPVNPSPFSFLKALFGTN-------------------------YPIGVLTVDK
ILPVGKEISAVGLCSLKN-GVSEIKFCNDLPYFLSEMSKDEMVGDLASSTRMLFWTAFVL
GSMSIGVLSYAVVRN----------------WNKWKVWRQQRQLQQSSQAA---------
---------------------------DSDAEAQ-I-EEE----DVPEGQLCVICLMRRR
RSAF--IPCGHRVCCHPCSISIER---DIAPKCPVCR-QEIRTSLRVYDS-----
>34887_Solyc12g049330.1.1_genomic_reference_SL2.31ch12_evidence_code_10F0H1E0IEG_gene_region_46263202-46267916_functional_description_"Zinc_finger_family_protein__AHRD_V1_***-_D7KLF2_ARALY_"
M-------------------------S--IYDQ-AAAAVLSQIATAADGALIGLALAYVA
VRSIVKFKANSSAL--------HKINDAPS------------------------LNVSDL
RSLLS------SSDNSD-------------------------------------------
---------------------------------------SSNHSDDGKLVIVRGTVEAKS
AVE-GNWKSL--RANILSAHNSAEKGVILQHTQTCIYNEWRGFFSWAG----DLYSIFPR
V----RK------DQQSSSLRTVPFVLIETGRWPQ------PKYVNVNMDGST--HSLPL
VTVYHHLQPLHATPLTFIQALFGHH-------------------------YPVGVLDEEK
ILPLGKDITAIGVCSSKD-GILEIKSCEDLPYFLSDMTKDQMLVELAFKTKILMWSGVLF
GSVAVGVLGYAVVRN----------------WNRWKLWRHQRQAQQQRDAA---------
---------------------------SNDDDVQ-V-SADEESGDVPDGQLCVICLTRRK
RAAF--VPCGHLVCCQRC-------------------------------------
>Panucum_virgatum_gnl_BL_ORD_ID_48680__Pavirv00039347m_PACid_23804892
M-------------------------S--ARDR-ETAEALVRLAASLDGAVLGLGTAAVA
VASWVKYLTVSGQL--------RLVASAAA------------------------SSIADL
RSLLP------GSGGEP-------------------------------------------
-----------------------------------------------RLAAVRGYVRPKP
------------GGMILQPPFSGEHGVITKHTQMCLFTEWRGIFGWTF----DLHALLFR
S----WK------EQIVTSFRTVPFVLASSEIGNP------IGMVHINVEKADPNQPLPL
TTVFHKLIPIETTPYALFQTIIGNG-------------------------YPIALLDEEK
ILPIGKELTAIGLCRAKD-ESVEISSCPDLPFFLSELTKDEMQAQLASRARTLFWGSIVL
GTLSVCLVGHAIYRC----------------WKRIKLRREARQAQQLFEEA---------
---------------------------EDAIQEG-D-SS---DEEVGDGQLCVVCLRRRR
KAAF--IPCGHLVCCCKCALRMER---EAEPLCPMCR-QDIRYMMRIYDS-----
>Sorghum_bicolor_gnl_BL_ORD_ID_4679__Sb01g045370.1_PACid_1954575
M-------------------------S--ARDR-ETAEALVRLAASLDGAVLGLGTAAVA
VASWVKYLAVSGQL--------RLVASAAT------------------------ASIGDA
RSLLR------GDGNEP-------------------------------------------
-----------------------------------------------RIAAVRGYVRTQ-
-------------GSFLRAPFSSEAGVVVKHTQMCLFTEWRGIFGWTF----DLHALLFR
S----WK------EQIVTSFRAVPFVLASTELGNS------TGVVHINVDEVD-YQPLPL
TTVFHKLIPLETTPYTLFQTIIGNG-------------------------YPIALLDEEK
ILPIGKKITAIGLCRAKNAESVEITSCPEIPFFLSELTKDEMQAQLASRARILFWGSIVL
GTLSVCLVGHAIYRG----------------WKRIKLRREARQAQQMFEDA---------
---------------------------EDAIRED-N-SSDDDDDDVGDGQLCVVCLRKRR
KAAF--IPCGHLVCCCKCALRMER---EVEPLCPMCR-QDIRYMIRIYDS-----
>Zea_mays_gnl_BL_ORD_ID_17805__GRMZM2G004023_T06_PACid_20837531
M-------------------------S--ARDR-ETAEALVRLAASLDGAVLGLGTAAVA
VASWVKYLAVSGQL--------RLVASAAT------------------------ASIADA
RSLLS------GDGAEP-------------------------------------------
-----------------------------------------------RIAAVRGYVRAH-
-------------DKFFRAPFSGEAGVVTKHTQMCLFTEWRGIFGWTF----DLHALLFR
S----WK------EQIVTSFRSVPFVLVSTELGNP------TGVVHINVDKAD--QPLPL
TTVFHKLIPLETTPYTLFQTIIGNG-------------------------YPIALLDEEK
ILPIGKKITAIGLCQAKDAESVEITSCPEIPFFLSELTKDEMQAQLASRARILFWGSIVL
GTLSVCLVGHAIYRG----------------WTRIKLRREARHARQMFEEA---------
---------------------------EDAIHRD-D-SS--DDDEIGDGQLCVVCLRKRR
RAAF--IPCGHLVCCSECALTIER---TPHPLCPMCR-QDIRYMMRVYDS-----
>Oryza_sativa_gnl_BL_ORD_ID_30371__LOC_Os03g08000.1_PACid_21912843
M-------------------------S--ARDR-ETAVALARLAAALDGAVLGLGTAALA
VASWVKYLAASGQL--------RRIASAPA------------------------AAIPDL
RSLLAEYGGGGGDGDQP-------------------------------------------
-----------------------------------------------ILAVVRGHVRAAP
------------RGKYLVPPGSGEHCVVAKHTQLCLFNEWRGIFGWTF----DLHALFFK
S----IK------EQIITSFRWVPFVLVDPE--NM------TGMVHVKLDRAM--QPLPL
TTVYHKLTPVDSTPYTLFQTIIGNG-------------------------YPIALLDEEK
ILPVGKEITAIGYIRPHK-ASVEISSCSEIPFFLSDLTKDEMEAELSSRAKTLFWASVVL
GTMSVCLLGFATYRS----------------WKKIKERREARQAQEVFRQT---------
---------------------------TDEVTDD-Q-SSDEEAGEMGDGQLCVICLRKRR
KAAF--IPCGHLVCCCKCALIVER---QFDPLCPMCR-QDIRYMIRIYDN-----
>Selaginella_moellendorffii_gnl_BL_ORD_ID_11999__91152_PACid_15413277
M-------------------------A--SHDE-EICAALTRLAMAGDGIVLGLGMAALA
LRTWLKFGSHTRAL--------KQVEGTAQ------------------------VEIHDL
RSLVE------SGEKEP-------------------------------------------
-----------------------------------------SSDSSPPLVIVRGRVALPP
KTS---------SEEVLLARNQTDLAVFVERTQTYLFNEWRGLFRWGP----EWRGLLGW
GS---LK------EQVAFSRRKIPFVLLDSDPQYD------GACVHINMENVE--HPLPL
VTVFHQLHPVQTSSSTFLQAVFGRR-------------------------YPVGVIDEEK
ILPLNREITAVGFLSKHPQGLPAIKSSNQMPFFLTEFSREELIVELASATHALFWTGIVI
SSLALGVIGYSAFKN----------------WCKWKEWRRLRQIQEELRRE---------
---------------------------EQVMEEDEEPATTQEGSEVPDGQLCVVCLLRRK
RAAF--ITCGHRVCCMGCARRIRHSQNAANARCPVCR-QSVSGYIRVYD------
>Physcomitrella_patens_gnl_BL_ORD_ID_37837__Pp1s52_256V6.3_PACid_18074375
M-------------------------A--GHED-ELCAALMRLALAGDGLVMGVGMTVLA
FRTWIKFWSHSKAL--------KDIKDTPV------------------------TRIADL
RTLVE------EPDVQA------------------------------------------K
EKIRTPEKISPPHQDIEVFATRSKVKMPSRPWMVERLPIPSLETKQEKLVIVRGRVQTKA
FVE-SEGDQR--DAEALIPLNVPEKAVFVERTQTYVLTEMSNFLGWIT------------
-----QK------DLVKFTRQVVPFVLAETEAHWSFRPSDMAVYVHINLDESQ--HPIPL
VTVHHQLHPVPASSYTLFQAMFGRR-------------------------YPVGLLDEEK
ILPLGAEITAVGVLHTAPDGTPVVKSSKRLPIFLTEFTREQLLVELASSTKVLFWMGVAV
STVAAGVLGYSLVKN----------------WTRWKQRQQQRQSQNNSENR---------
---------------------------QNSTIED----EAENFEDIPDGELCVVCLLRRR
RAAF--IYCGHRVCCMGCAERVEH---GANPRCPVCR-QSVTGIVRVYDS-----
>gnl|BL_ORD_ID|1836 @Prochlorococcus_sp_CC9311@ 638115460 sync_1872 possible Arginine repressor, C-terminal domain [Prochlorococcus sp. CC9311]
M-------HH-----DLLALNSNWNLS--QTDP-STRVPLVSLDEALERSSLKKGISRRD
FLAELLKDVQHQRLLPLLAMLPRRWRQEPASLPEQLRGLGNLLGEGLMSPLLLAAFADDL
QHLLP---------QRTNPRRSALDLWCQRTY-NNPGSQQWPLPEGLETWRSQAAESLKS
QNERLKPK-G-RSGLTGLTSLGGEIAWSNHGLSYLQSAEARHRNQ--QMAQVFNVLGSNL
LVE-----QNLNVDTYRFEGQSSGKDLI----QCLQSKGWRCQARVRT----SVASFGLG
AS---TP------SSDSNQWNQIPLAVPYR-----------TGLQETNQKEIN--ALLPH
ACLELELQPPE-DDTVLLQYYQGTEGLNGWAAMNDLDRPWQNGRSNGSVQYSPTVFRDQQ
LS------DAVELCELMG-----------------------AIHNSEAGMENLHLGG--Y
GAIGFCIDSTALLEYALTGQTNLFPLTLGGLW-RERLSAQLNHLLEQNMRP---------
---------------------------ND-----DA-VD-------------------RY
KRAIEDMPQDLYHTSVTRTDARRRLLASQPSYSPFLLIQDLNLQKS---------
>QUERY_Prochlorococcus_sp_CC9311_gnl|BL_ORD_ID|1836 @Prochlorococcus_sp_CC9311@ 638115460 sync_1872 possible Arginine repressor, C-terminal domain [Prochlorococcus sp. CC9311]
M-------HH-----DLLALNSNWNLS--QTDP-STRVPLVSLDEALERSSLKKGISRRD
FLAELLKDVQHQRLLPLLAMLPRRWRQEPASLPEQLRGLGNLLGEGLMSPLLLAAFADDL
QHLLP---------QRTNPRRSALDLWCQRTY-NNPGSQQWPLPEGLETWRSQAAESLKS
QNERLKPK-G-RSGLTGLTSLGGEIAWSNHGLSYLQSAEARHRNQ--QMAQVFNVLGSNL
LVE-----QNLNVDTYRFEGQSSGKDLI----QCLQSKGWRCQARVRT----SVASFGLG
AS---TP------SSDSNQWNQIPLAVPYR-----------TGLQETNQKEIN--ALLPH
ACLELELQPPE-DDTVLLQYYQGTEGLNGWAAMNDLDRPWQNGRSNGSVQYSPTVFRDQQ
LS------DAVELCELMG-----------------------AIHNSEAGMENLHLGG--Y
GAIGFCIDSTALLEYALTGQTNLFPLTLGGLW-RERLSAQLNHLLEQNMRP---------
---------------------------ND-----DA-VD-------------------RY
KRAIEDMPQDLYHTSVTRTDARRRLLASQPSYSPFLLIQDLNLQKS---------
>gnl|BL_ORD_ID|769 @Prochlorococcus_sp_WH_7803@ 640543123 SynWH7803_0770 hypothetical protein [Prochlorococcus sp. WH 7803]
M-------AD-----DLLKLSDSWGHS--QGDG-TDIAPLVPFEQALESSSLRRNISRDD
FLKSTLTQLNHQRLIPLLFMLPRRWRLQPAALPQSLRNLGGVLEHGLLSPLLLAALADDL
QHLIA------HEGKRQPAKKNAMDRWCQRSI-DLDDGSSRLLPTNL-----IALQSISS
PDSAPPSP-GAGALARVAKGFSAELQWRNEGLPFLQPENARLRNR--ALAQVLNVLGSNR
LPP-----PPGSSEPFRFESCDRSSALI----THLIAGGWQCRARFRA----SVASFGLG
AS---TR------DGD--QWSQIPLAVPYR-----------TGLCDSQGEERR--ALLPH
CSLEMELQ-PDHGEPFLLQYYQGTEGLNGWAALNDLNRPWQNDRSNGTVAYPGPELTGET
LS------AALDLCDLMG-----------------------AVHNSAAQQNRLVIGG--Y
GALGYCIDSTAMLEVAVRQTTHLFPLTLGGLW-RQRLDDQLNQLLENGLKA---------
---------------------------SA-----ET-VE-------------------RY
RQSLDTTPQDLFVNRNTVNDANRRLLASQPPHSPFALVRSLNGESTAKP------
>gnl|BL_ORD_ID|769 @Synechococcus_WH_7803@ gi|148239106|ref|YP_001224493.1| hypothetical protein SynWH7803_0770 [Synechococcus sp. WH 7803]
M-------AD-----DLLKLSDSWGHS--QGDG-TDIAPLVPFEQALESSSLRRNISRDD
FLKSTLTQLNHQRLIPLLFMLPRRWRLQPAALPQSLRNLGGVLEHGLLSPLLLAALADDL
QHLIA------HEGKRQPAKKNAMDRWCQRSI-DLDDGSSRLLPTNL-----IALQSISS
PDSAPPSP-GAGALARVAKGFSAELQWRNEGLPFLQPENARLRNR--ALAQVLNVLGSNR
LPP-----PPGSSEPFRFESCDRSSALI----THLIAGGWQCRARFRA----SVASFGLG
AS---TR------DGD--QWSQIPLAVPYR-----------TGLCDSQGEERR--ALLPH
CSLEMELQ-PDHGEPFLLQYYQGTEGLNGWAALNDLNRPWQNDRSNGTVAYPGPELTGET
LS------AALDLCDLMG-----------------------AVHNSAAQQNRLVIGG--Y
GALGYCIDSTAMLEVAVRQTTHLFPLTLGGLW-RQRLDDQLNQLLENGLKA---------
---------------------------SA-----ET-VE-------------------RY
RQSLDTTPQDLFVNRNTVNDANRRLLASQPPHSPFALVRSLNGESTAKP------
>gnl|BL_ORD_ID|2526 @Synechococcus_sp_RS9916@ 639889746 RS9916_27834 possible Arginine repressor, C-terminal domain [Synechococcus sp. RS9916]
MTEQGNARMP-----DPLALSSAWGAS--PGDQ-TDIAPLLGLNAVLETSWLRKGISRDH
FLTELLTDLHQRRLVPLLAMLPKRWRLGAAALPDHLRKLAELLEGGSVSPLLLAALADDL
HHLFP------VQDNATGATADALKRWTATTVQPGPDAAGQPLPQSLKAWKEQADHGQHE
-------Q-AHNAAAGGLRQLGADLVWQNHGLQNLQSAASRWGNT--LMAQVFNALGANH
LPPSVRG-TSGRDTPFLFEGVSTSQQLL----ELLRTRGWSCKARVRA----SVASFGLG
ASCPNTA------ATTT-TWLQVPLAVPYR-----------TGLLD-QGEELE--ALLPH
CSLELELTPPDAQAPTLLQYYQGTEGFNGWAAMNDLHRPWQNDRTNGSVAYPGEPIEAAQ
LD------LALDLCDLMA-----------------------AVHNSAATQGKLRTGG--Y
GALGFCIDSTALIEQALTGRCHLFPLTLGGIW-RERLREHLEQLLDQGLRV---------
---------------------------ID----DTS-VE-------------------RY
RQALDTLPCDLHLHGNACAGALERLRASQPAHSPFLLVRRLNGEEHRR-------
>gnl|BL_ORD_ID|1012 @Synechococcus_sp_RS9917@ 638962170 RS9917_10556 possible Arginine repressor, C-terminal domain [Synechococcus sp. RS9917]
MA-------------DLLALSGQWGAR--EEDR-TALAPLLPFPAVLEDSWLRRGIQRDA
FLRELLQGLHQRRLIPLLAMLPRGWRLAPAALPEKLRGLGSLLEEGLVSPTLLAALADDL
QHLLP------AGDPDNAAGTTALSRWTARQVVNPEDGSRQALPQSLQQWQELAHQPAME
PTPWPPAK-AGSMSAPNLRSLGAGLTWHNQGLAPLQPAHCRQANR--LLAQVFNALSANR
LPDAARGATAAAVEPFQFEGVVSTAALM----ALLRSRGWSARARVRS----SVASFGLG
AS---TA------AEDG-TWHQIPLALPYR-----------TGLLR-HGLEIE--SLLPH
CCLELELQPPEAAEPVLLQYYQGSEGLNGWAAMNDLDRPWQNDRGNGTVAYPGPAFEAEH
LD------LALDLCDLMA-----------------------AVHNSTAAAGQLRFGG--Y
GALGFCIDSTALLEQALTGRSTLFPLTLGGIW-RERLAQQLERLLNTGLST---------
---------------------------ASTSHGDEA-VE-------------------RY
RDALQRLPQDLSLQGEAALRAEARLIRSLPTHSPFVCVRALNGEAAAETSLSDPL
>gnl|BL_ORD_ID|1840 @Prochlorococcus_marinus_MIT_9303@ 640087364 P9303_18551 possible Arginine repressor, C-terminal domain [Prochlorococcus marinus MIT 9303]
MAEETPH-SL-----NPLALSQSWGQD--EHDD-IHTAPLIALEEVLETSRLRRGISREQ
LLSELLRDLDHRRLIPLIGMLPRGWRIAPAVLPERLRGIATLLEDGLLSPLLLAALADDL
QHLLP------TPENQPP---SALELWRQPSV-ALKPGHGVGVPSNLKNCRLLANQPITS
DALFDRKQLGRTPLGKGLTAVGSGLVWHNEGLVMLQNESSQRMNE--LMAQVLNCLAANR
LPE-----ALHHSEPFLFEGLSSGRQLI----ELLNRQGWHCCGRIRA----SVASFGLG
AS---QA------KGRG-RWLQVPLAMPYR-----------TGLEDDRNQEIL--SLLPH
CSFELELQ-PQDNDSILLQYCQGIEGMNGWVAMNDLHRPWQNDRHNGTVAYPSQPSTQQR
LA------DAIEITELIA-----------------------AVHNVEASSQKLHLGG--Y
GALGYCIDSTALLEQCLNGSTHLFPLTLGGIW-RERLRRRLDILLDQGFCI---------
---------------------------NT-----SV-VD-------------------RY
RWGLDTLPQDLNLQGSARLEAMQRLSSCQPSHSPFALVRSLNGEVDL--------
>gnl|BL_ORD_ID|429 @Prochlorococcus_marinus_MIT_9313@ gi|33862702|ref|NP_894262.1| arginine repressor domain-containing protein [Prochlorococcus marinus str. MIT 9313]
MAEEIPH-SL-----NPLALSQSWGQD--EHDD-IHTAPLIALEEVLETSSLRRGISREQ
LLSELLRDLDHRRLIPLIGMLPRGWRMAPAVLPELLRGIATLLEDGLLSPLLLAALADDL
QHLLP------IRENEPP---SALELWRQPSV-ALKPGHGVGVPCNLKNCRLLANQPITS
DAFSDPKQLAPTALGKGLTALGSGLVWHNEGLVMLQNESSQRMNE--LMAQVLNCLAANR
LPE-----ALHPSEPFLFEGLSSGRQLI----ELLNRQGWHCCGRIRA----SVASFGLG
AS---QA------NESG-RWFQVPLAIPYR-----------TGLEDDRNQEIL--SLLPH
CSFELELQ-PQGNDSILLQYCQDIEGVNGWTAMNDLHRPWQNDRHNGTVAYPSQPLTQQR
LA------DAIEITELIA-----------------------AVHNMEASSQKLHLGG--Y
GALGYCIDSTALLEQCLNGSTHLFPLTLGGIW-RERLRRSLDILLDQGFCI---------
---------------------------NT-----SV-VD-------------------RY
RWGLDTLHQDLSLQGSARLEAMQRLLSCQPSHSPFALVRNLNGEVDL--------
>gnl|BL_ORD_ID|1592 @Synechococcus_RCC307@ gi|148242692|ref|YP_001227849.1| hypothetical protein SynRCC307_1593 [Synechococcus sp. RCC307]
M--------------DPLQLDPAWPSA----------VPLLDLETALEQSLLQSGLSRQD
YIKRLVQDLHKPRLQPLLWLLPRRWRLAPAQLPQQLHGLAQLLERGLLTPSLLAVLGDEM
AQLLP------QPDQAT----TPLERWSGAGE------------SSLKPWSEVMALSQSD
APA------DATGAEAKASHLAPGLVWNNLGLHYGQNQARRQANS--AAAQWLNHHAAR-
---------------------GGSRELI----ETLQQRGWQIKARFRA----SVASFGLG
AC---FR------SQASDSWQQIPIGLPMR-----------SGLLDQNGQEIT--MLLPH
SAVEMELC--GEGCELLLQFYQGTEGICGWEALNDLQRPWQNDRHNGTVRYMGEPWQGSN
LL------ELMDLTDVMA-----------------------LVHNSVASELQLRWGG--Y
GSVGYCIDTTALVQQALLDQCDLFPLLLNGIW-RERLLRTSQRLPASSALQ---------
----------------------------------------------------------RY
QKALMELPLDLSHHGSSSTEAWQRLQGCQPLSSPFCLSQHIQHAPNDVTAVAL--
>gnl|BL_ORD_ID|1793 @Synechococcus_sp_CB0205@ 650132433 SCB02_010100009145 hypothetical protein [Synechococcus sp. CB0205]
MGRPMASGSPLASVVDPLQLDPDWSCS----------VPLLAFEDALDQSVFRSGLTRSD
WLKRLAHQLHKPQLLPLLWLLPKGWKLAPADLPQRLQTLGGLVERELLTPALLGAVADAL
PHFLN------GEHAAA------MGRWRGQQD--------AELPSSLEQLLQL------N
PSSTDPTD--PQVGNTEAERLSGGLIWHNAGLHHEQSASERERNA--LAARVLNRLAANA
LEQ----------DQWQIDGASSCRAWF----SRLQQEGWSLQAQLRA----SVASFGLG
AS---LP------N--PEGCSQVPLALPIR-----------TGLLGEGEQDIQ--GLLPH
SCLELEWR--RGNDLIRLQYYQGTEGLCGWEALNDLHRPWQNDRVNGTIRYLGEPFCAER
LL------EVMDLCDIMA-----------------------LIHNQQSDADALWLGG--Y
GALGFCIDSSAVLQQAMDGRCDLFPCLLGAIW-RERLLQRARGLQLQQESQ---------
---------------------------H------RA-RE-------------------RY
CRALTELPHDGFCFAEGSRDAKRRLKASQPQSSPFRLTQQ---------ALV--L
>QUERY_Synechococcus_sp_RS9917_gnl|BL_ORD_ID|2449 638963634 RS9917_01901 hypothetical protein Synechococcus sp. RS9917
M----------------------------------------------LFMVLCSSPAQAR
FAAFA--------------------------------EPEGGDDVAVIEHLKLKVPEAAR
QAWLE------AERGSW-------------------------------------------
------------------------------------------------------------
-EPWLSRQQGFLGRDLLWNPE-TEEGTLLIR--------WHSREAWKAIPLQEVEAVQQR
FEQLARE------ATG--QRLGNPFPLLYAGELLP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1721 @Prochlorococcus_sp_WH_7803@ 640544084 SynWH7803_1722 Conserved hypothetical protein specific to cyanobacteria [Prochlorococcus sp. WH 7803]
MITTAKSRLRRALFRV--------------------------IGPLMALVIALAGHDELR
DTAMA--------------------------------AERGDDDVAVVEHLRIQVPDQAR
DAWME------AERGSW-------------------------------------------
------------------------------------------------------------
-EPWLAQQKGFLGRDLLWDPR-TEEGTLLIR--------WSSRDAWKGIPQEDVMAVQER
FEQIARQ------ALG--QSQGNPFPLVYEGELLP-P-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1721 @Synechococcus_WH_7803@ gi|148240058|ref|YP_001225445.1| hypothetical protein SynWH7803_1722 [Synechococcus sp. WH 7803]
MITTAKSRLRRALFRV--------------------------IGPLMALVIALAGHDELR
DTAMA--------------------------------AERGDDDVAVVEHLRIQVPDQAR
DAWME------AERGSW-------------------------------------------
------------------------------------------------------------
-EPWLAQQKGFLGRDLLWDPR-TEEGTLLIR--------WSSRDAWKGIPQEDVMAVQER
FEQIARQ------ALG--QSQGNPFPLVYEGELLP-P-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2041 @Synechococcus_sp_WH7805@ 639021398 WH7805_05501 hypothetical protein [Synechococcus sp. WH7805]
MITFPWIGLRRVLFNL--------------------------SGLCLALVIALAGHDDLR
LIAFA--------------------------------DPEGGYDVAVVEHLRIQVPDQAR
DAWME------AERGSW-------------------------------------------
------------------------------------------------------------
-EPWLTQQKGFLGRDLLWDPT-SQEGTLLIR--------WSSREAWKAIPQEEVEAVQQR
FELIARQ------ALG--QVEGNPFPLVYEGELLP-P-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|878 @Synechococcus_CC9605@ gi|78212435|ref|YP_381214.1| hypothetical protein Syncc9605_0891 [Synechococcus sp. CC9605]
M-----HHLRFVLLRV--------------------------IAPCLALVLLLGGLSETE
VRAES--------------------------------DPTRGDVEAVVEHLRLQVPRESR
DQWMA------SERGSW-------------------------------------------
------------------------------------------------------------
-EPWLKQQPGFLGRDLFWDPA-TEEGTLLIR--------WSSRKAWKSIPMAEVEIVQER
FETLARE------ATG--QRQGNPFPLVFEGELLP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1364 @Synechococcus_sp_WH_8109@ 647836086 SH8109_1402 conserved hypothetical protein [Synechococcus sp. WH 8109]
M-----------------------------------------------------------
--------------------------------------------VAVVEHLRLQVPRDSR
DQWMV------AESGSW-------------------------------------------
------------------------------------------------------------
-EPWLKQQPGFLGRDLFWDPV-TEEGTLLIR--------WSSRKAWKSISMAEVEKVQER
FETLARE------QTG--QRHGNPFPLVFEGELLP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2078 @Synechococcus_sp_CB0101@ 650129659 SCB01_010100010480 hypothetical protein [Synechococcus sp. CB0101]
M--------------------------------------------------LLAGHPDVA
IAESV--------------------------------QPGGGFEVAVVEHLRVKVPAEGR
EAWLK------AERGSW-------------------------------------------
------------------------------------------------------------
-EPWLQQQPGYLGRDLLWDPE-REEGTLLIR--------WASREQWKAIPLAEVEAVQER
FEELARQ------ATG--SRQGNPFPLVFEGELQPAA-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1216 @Synechococcus_sp_CB0205@ 650131852 SCB02_010100006232 hypothetical protein [Synechococcus sp. CB0205]
M---------RLLARV--------------------------AALVLCVAMLLAGHPDVA
IATNA--------------------------------KPGGQLEVVVVEHLRIKVPADGR
AAWLQ------AEQGSW-------------------------------------------
------------------------------------------------------------
-EPWLEQQDGYLGRDLLWDSE-REEGTLLIR--------WASREQWKAIPETEVEAVQER
FEQLARE------STG--QGQGNPFPLVFEGELIPAA-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|756 @Prochlorococcus_sp_CC9311@ 638114371 sync_0782 hypothetical protein [Prochlorococcus sp. CC9311]
M-QSLLPRFQPLMIRV--------------------------ATLISVALVLMVQSADVR
FAAFA--------------------------------DPDGGYDVAVIEHLRISVPAQGR
EAWLE------AERGSW-------------------------------------------
------------------------------------------------------------
-EPWLAQQSGFLGRDLLWDPE-TEEGTLLIR--------WSSRQAWKAIPSEQVEEVQAR
FEQLARN------AMALPQVMDNPFPLVFEGELLP-P-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1930 @Prochlorococcus_marinus_MIT_9303@ 640087455 P9303_19451 hypothetical protein [Prochlorococcus marinus MIT 9303]
M-------NCRSLSRL--------------------------ISFVLSFLVMLSGHPDVA
IAARH--------------------------------DPDGGDDVAVVEHLRIKVPAHAR
EAWLK------AEQGSW-------------------------------------------
------------------------------------------------------------
-EPWLAKQSGYLGRDIFWDAE-QEEGILLIR--------WASREQWKSIPQAEVDVVQAR
FEQLARE------ATG--QASSHPFLLQFEGELVP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|357 @Prochlorococcus_marinus_MIT_9313@ gi|33862630|ref|NP_894190.1| hypothetical protein PMT0357 [Prochlorococcus marinus str. MIT 9313]
M-------NCRSLSRL--------------------------ISFVLSFLVMLSGHPDVA
IAARH--------------------------------DPDGGDDVAVVEHLRIKVPAHAR
EAWLK------AEQGSW-------------------------------------------
------------------------------------------------------------
-EPWLAKQSGYLGRDIFWDAE-QEEGILLIR--------WASREQWKSIPQAEVDVVQAR
FEQLARE------ATG--QASSHPFLLQFEGELVP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|469 @Synechococcus_sp_RS9916@ 639887662 RS9916_33087 hypothetical protein [Synechococcus sp. RS9916]
M--------NRVLPMVSWLMAALLWFCPPAFAPAAFARTAFPSSTFSSTAFSLTALPSST
FATT---------------------------------TTRSASEVTVVEHLRIKVPANAL
SVWHK------AEEGSW-------------------------------------------
------------------------------------------------------------
-EPWLAKQEGFIGRDLLWDPE-TEEGTLLIR--------WASREQWKAIPAADVAQVQEQ
FERIARD------GMG--QTSGNPFPLVFEGELLP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1325 @Prochlorococcus_marinus_MIT_9211@ 641285696 P9211_13251 hypothetical protein [Prochlorococcus marinus MIT 9211]
MYRVFKKSGIGLFF----------------------------LKLFICVVILFFGTTHIA
VASSQI-------------------------------TLESPKEYMIVEYLRLRVPEEDR
EAWLI------AEKKSW-------------------------------------------
------------------------------------------------------------
-EPWLEKKDGFLGRQLFWDKQ-SEEGTVLIS--------WSSRGDWKSIPKEEIEKVQGL
FEELARG------QTG--KEFGNPFPIQFEGELLP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1691 @Prochlorococcus_marinus_NATL1A@ 640084983 NATL1_16991 hypothetical protein [Prochlorococcus marinus NATL1A]
MKTLRTKYFIEKIFSF--------------------------LLLGVIFISTIFGNVKNI
QAASL--------------------------------LKVNFPKESIVEHLKLDVPKKFK
NAWLK------AEEGSW-------------------------------------------
------------------------------------------------------------
-EPWLLKQDGFLGRQLFWDPK-EEEATLLIG--------WESRAVWKSISQTEINLVQHD
FEKIARK------ETG--EQSGNPFPLIFEGELNP-E-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1644 @Prochlorococcus_marinus_NATL2A@ gi|72382685|ref|YP_292040.1| hypothetical protein PMN2A_0846 [Prochlorococcus marinus str. NATL2A]
MKTLRTKYFIEKIFSF--------------------------LLLCVIFISTVFGNVKNI
QAESL--------------------------------LKMNFPKESIVEHLKLDVPKKFK
NAWLK------AEEGSW-------------------------------------------
------------------------------------------------------------
-EPWLLKQDGFLGRQLFWDPK-EEEATLLIG--------WESRAVWKSISQTEINLVQHD
FEKIARN------ETG--EQSGNPFPLIFEGELNP-E-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1350 @Prochlorococcus_marinus_marinus_CCMP1375@ 637441777 Pro1353 Uncharacterized secreted or membrane protein [Prochlorococcus marinus marinus CCMP1375]
M--LFVKLLRKKIFIV--------------------------LTLFLSFLALFLANAQVV
YAANQ--------------------------------VDMKNTDTTVIEYLRLKVSDQER
RAWLT------AEKKSW-------------------------------------------
------------------------------------------------------------
-EPWLKEQKGFLGRQLLWNPQ-KQEAILLIS--------WATREDWKRIPQEEIDKIQKL
FEEIAKD------LTG--ETLSNPFPIKAQGELFP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1349 @Prochlorococcus_marinus_SS120@ Pro1353 Uncharacterized secreted or membrane protein
M--LFVKLLRKKIFIV--------------------------LTLFLSFLALFLANAQVV
YAANQ--------------------------------VDMKNTDTTVIEYLRLKVSDQER
RAWLT------AEKKSW-------------------------------------------
------------------------------------------------------------
-EPWLKEQKGFLGRQLLWNPQ-KQEAILLIS--------WATREDWKRIPQEEIDKIQKL
FEEIAKD------LTG--ETLSNPFPIKAQGELFP-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|579 @Synechococcus_sp_WH5701@ 638958337 WH5701_14516 hypothetical protein [Synechococcus sp. WH5701]
M------------GRV--------------------------CALALLLLSLLLGVTPTA
VTAAPSDVV----------------------------QQDGIQQQVVVEVLRLKVPAADR
EAWLE------AERQSW-------------------------------------------
------------------------------------------------------------
-EPWLQAQSGFLERRIYWDAD-SEEGVLLIY--------WASRRQWHGIATAEVERVQER
FDQLARQ------GTG--RSDPQPFPLLFSGELIA-Q-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2716 @Cyanobium_sp_PCC_7001@ 647591016 CPCC7001_581 conserved hypothetical protein [Cyanobium sp. PCC 7001]
MTLLRRLGITALRGVL--------------------------LLLLLGVVGLQAGPGAMA
AATGPAAVMRPGGAAPAPSTPALRSPMAEPRAEQPPKQPPMDAQSEVVEVLRLQVPARSR
QAWLE------AEQASW-------------------------------------------
------------------------------------------------------------
-EPWLARQEGFLGRQLFWDPQ-REEGLLLIR--------WASRGQWKAISPEAVGAVQER
FEQHARQ------LTG---SRTNPFPLLDEAELQP-L-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1947 @Synechococcus_sp_BL107@ 639886605 BL107_11211 hypothetical protein [Synechococcus sp. BL107]
MMRK--------------------------------------FVLLFAILVMFAG-----
---------------------------------------QVLASDVVIEQLRLKVPESQV
QTWLE------AEKQTW-------------------------------------------
------------------------------------------------------------
-QPWLEAQEGFLGRDIAWDPA-HEEGQLLIQ--------WATRDQWKAISSDEVELVQRK
FDSVVNA------ALGRSATAESPFPLVLEGELLP-LRLPG-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1490 @Synechococcus_sp_CC9902@ Syncc9902_1507 conserved hypothetical protein
MIRK--------------------------------------FVLLFAILVMFAG-----
---------------------------------------QVLASDAVIEQLRLKVPESQV
QTWLD------AEKQTW-------------------------------------------
------------------------------------------------------------
-QPWLEQQDGFLGRDIAWDPA-HEEGQLLIH--------WATRDQWKAINPDDVDMVQRQ
FDSVVNA------ALGRSASAESPFPLVLEGELLP-LRLPG-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1604 @Synechococcus_WH_8102@ gi|33866143|ref|NP_897702.1| hypothetical protein SYNW1609 [Synechococcus sp. WH 8102]
MTRA--------------------------------------IALLLAMLLGVAA-----
---------------------------------------PAMAEQGVIEQLRLAVPASHR
ELWLQ------AEASSW-------------------------------------------
------------------------------------------------------------
-QPWLEQQSGFEGRQLFWDPQ-REEGLLLIR--------WSSREQWKAIPAAEVERVQEV
FEAQVNQ------ALKRDPAAGPLFPLLAEGELQV-QELPSR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1473 @Prochlorococcus_marinus_AS9601@ 640079199 A9601_14781 hypothetical protein [Prochlorococcus marinus AS9601]
M--SFNLNLKKNFQRF--------------------------CLLLICSVVLIFQSEFPN
LKAL---------------------------------TMDNFQSEMVIEELRLKVPADAK
GAWLN------AEKEIW-------------------------------------------
------------------------------------------------------------
-EPWLSSQDGFLGRQLFWDKE-KEEALILVN--------WKSKKLWKSIPMSEVNLVQQK
FEDNVKA------ALN---VGDNPFELIYEGELDK-QR----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1464 @Prochlorococcus_marinus_MIT_9301@ 640161056 P9301_14641 hypothetical protein [Prochlorococcus marinus MIT 9301]
M--RFNLNLKKKIQGF--------------------------CLSLICLVVLTVQSDIPN
LRAL---------------------------------TMDNFQSEMVTEELRLKVPADVK
AAWLN------AEKEIW-------------------------------------------
------------------------------------------------------------
-EPWLSSQDGFLGRQLFWDKE-KEEALILVN--------WKSKKLWKSIPMSEVNVVQQK
FEDNVKA------ALN---VGDNPFELIYEGELDK-QR----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|341 @Prochlorococcus_marinus_MIT_9202@  647672488 P9202_1454 conserved hypothetical protein [Prochlorococcus marinus MIT9202]
M--KLNLNLKKKIQRF--------------------------CLILICLVVLIFQSGVPN
LKAL---------------------------------NMDDYQGEMVIEELRLKVPGDVK
EAWLN------AEKEIW-------------------------------------------
------------------------------------------------------------
-EPWLSSQDGFLGRQLFWDKE-KEEALILVN--------WKNKKLWKSIPMSEVNVVQQK
FEDNVKA------ALN---VGENPFKLIYEGELDK-QR----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1497 @Prochlorococcus_marinus_MIT_9215@ gi|157413837|ref|YP_001484703.1| hypothetical protein P9215_15041 [Prochlorococcus marinus str. MIT 9215]
M--KLNLNFKKHLQKF--------------------------CLVLICSIILIFQSDISN
LKAL---------------------------------SMDIYQGEMVIEELRLKVPADIK
AAWLN------AEKEIW-------------------------------------------
------------------------------------------------------------
-EPWLSSQDGFLGRQLFWDKE-KEEALILVN--------WKNKKLWKNIPMSEVNLVQQK
FEDNVKA------ALN---VGDNPFKLIYEGELDK-QR----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1275 @Prochlorococcus_marinus_MED4@ PMM1279 conserved hypothetical protein
M--KIKFNVKEKIKNL--------------------------SFLFIFLFIFLFQINSPT
LNAL---------------------------------PMDTYQSGPVTEELRLKIPSEFK
KVWLQ------AEKEVW-------------------------------------------
------------------------------------------------------------
-EPWLSIQSGFLGRQIFWDKE-KEEALILVN--------WENKKLWKSISMNEVNEVQEK
FEENVKT------SLN---TNVNPFELIYEGELVK-QG----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1279 @Prochlorococcus_marinus_pastoris_CCMP1986@ gi|33861835|ref|NP_893396.1| hypothetical protein PMM1279 [Prochlorococcus marinus subsp. pastoris str. CCMP1986]
M--KIKFNVKEKIKNL--------------------------SFLFIFLFIFLFQINSPT
LNAL---------------------------------PMDTYQSGPVTEELRLKIPSEFK
KVWLQ------AEKEVW-------------------------------------------
------------------------------------------------------------
-EPWLSIQSGFLGRQIFWDKE-KEEALILVN--------WENKKLWKSISMNEVNEVQEK
FEENVKT------SLN---TNVNPFELIYEGELVK-QG----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1438 @Prochlorococcus_marinus_MIT_9515@ 640081127 P9515_14401 hypothetical protein [Prochlorococcus marinus MIT 9515]
M--KINFKIKEKIKNL--------------------------TFLFICLFIFLSQINSPI
LKAL---------------------------------PMDTYQSELVTEELRLKIPSEFK
KIWLQ------AEKEVW-------------------------------------------
------------------------------------------------------------
-EPWLSIQEGFLGRQIFWNKE-KEEALILVN--------WENKKLWKSISMNEVNEIQEK
FEENVKT------SLN---INFNPFQLIYEGELIK-QG----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1372 @Prochlorococcus_marinus_MIT_9312@ gi|78779757|ref|YP_397869.1| hypothetical protein PMT9312_1373 [Prochlorococcus marinus str. MIT 9312]
M--KINSNFKKRIKSF--------------------------FFLFFSLFVFLNQINTHI
TEAI---------------------------------AMDNYKQELVVEELRLKVPAQYK
EVWLK------TEKKIW-------------------------------------------
------------------------------------------------------------
-EPWLSSQDGFLGRQLFWDKE-KEEALILVN--------WKSKKLWKSIPMSEVNVVQEK
FEDNVKT------DLN---VSENPFELIYEGELNK-QV----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|574 @Anabaena_sp_PCC_7120@ all0575 unknown protein
MG----------------------------------------------------------
---------------------------------------------VVIEFLRFKVEASLR
ESYIQ------KDAEIW-------------------------------------------
------------------------------------------------------------
-TAALAKYPGFLGKEVWINPLESTEVIFIIR--------WETKEHWKTMPAADLEAIEQR
FRQ---------------AVGD-NYELVESGEYQV-RKFLHN------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|885 @Nostoc_sp_PCC_7120@ 637230937 all0575 hypothetical protein [Nostoc sp. PCC 7120]
MG----------------------------------------------------------
---------------------------------------------VVIEFLRFKVEASLR
ESYIQ------KDAEIW-------------------------------------------
------------------------------------------------------------
-TAALAKYPGFLGKEVWINPLESTEVIFIIR--------WETKEHWKTMPAADLEAIEQR
FRQ---------------AVGD-NYELVESGEYQV-RKFLHN------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|950 @Anabaena_variabilis_ATCC_29413@ gi|75906558|ref|YP_320854.1| unnamed protein product [Anabaena variabilis ATCC 29413]
MG----------------------------------------------------------
---------------------------------------------VVIEFLRFKVEASLR
ESYIH------KDAEIW-------------------------------------------
------------------------------------------------------------
-TTALAKYPGFLGKEVWTNPLESTEVIFIIY--------WETKEHWKTIPAADLEAIEQR
FKQ---------------AVGD-IYELVEFREYQV-RKFLHN------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1629 @Nodularia_spumigena_CCY9414@ 640025053 N9414_01742 hypothetical protein [Nodularia spumigena CCY9414]
------------------------------------------------------------
---------------------------------------------MVIELLKFQVAPEER
ENYIQ------KDAEIW-------------------------------------------
------------------------------------------------------------
-TTGLAKYPGFLGKEVWINPNDPTEVIFIIR--------WATQEQWKAIPLEDLQMIEDK
FTQ---------------AMGK-SYPIVESAEYQV-RKFPHS------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|614 @Cyanothece_PCC_7424@ gi|218437628|ref|YP_002375957.1| hypothetical protein PCC7424_0629 [Cyanothece sp. PCC 7424]
------------------------------------------------------------
---------------------------------------------MVIEWLKFKIDPESR
ETFIE------KDNQIW-------------------------------------------
------------------------------------------------------------
-TAALAPYPGFLGKEVWINPHIPDEIVLVIH--------WETRQQWSAVPNSVLEETERQ
FRE---------------EMGKDQYQLVETKEYQV-RKFIN-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|3129 @Cyanothece_PCC_7822@ gi|307153075|ref|YP_003888459.1| hypothetical protein Cyan7822_3232 [Cyanothece sp. PCC 7822]
------------------------------------------------------------
---------------------------------------------MVIEWLKFRVPAQSR
EKFIQ------KDELIW-------------------------------------------
------------------------------------------------------------
-TAALAKFKGFLGKEVWVNPKIDDEIVLVIH--------WENHEAWSSIPAAALEEIEDK
FSQ---------------SMRNDEYKLIESGEYQV-RKFIS-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2733 @Cyanothece_sp_BH68_ATCC_51142@ 641677134 cce_2645 putative dimeric alpha-beta barrel protein [Cyanothece sp. BH68, ATCC 51142]
------------------------------------------------------------
---------------------------------------------MVIEWLKFQVSPESR
DIFIQ------LDNEIW-------------------------------------------
------------------------------------------------------------
-TPVLAEFPGFLGKEVWISPNIPQEVTLIIR--------WETREQWKAIPQTLLEETEQK
FAQ---------------RMQDHPYEMIEVREYQV-RKFPNS------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2991 @Microcystis_aeruginosa_NIES_843@ 641536990 MAE_29920 hypothetical protein [Microcystis aeruginosa NIES-843]
------------------------------------------------------------
---------------------------------------------MVIEWLEFQVKPEAR
EKFIQ------KDQEIW-------------------------------------------
------------------------------------------------------------
-TKFLAKQPGFLGKELWINPAIEEKLIIVVH--------WQTQEQWKAISKNLLDDTEAK
FSL---------------VMGKDNYQLLKVKEFQV-RKFRENFQNNLGSLGT--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|5345 @Microcoleus_chthonoplastes_PCC_7420@ 647569732 MC7420_3669 hypothetical protein [Microcoleus chthonoplastes PCC 7420]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MLARCPGFISKEVWIEPETPTEVILIIR--------WTSREQWKAIPQEQLEGTQKQ
FEQ---------------EFGK-DYQMIQASEYQV-RKFPQTPS----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|4752 @Arthrospira_platensis_NIES_39@ 650388091 NIES39_L04370 hypothetical protein [Arthrospira platensis NIES-39]
------------------------------------------------------------
---------------------------------------------MVIEWLRFKVPPTLW
EAFIQ------KDEQVW-------------------------------------------
------------------------------------------------------------
-TEGLKQFPGFIGKETWVDPK-LEEVILVIR--------WETREQWKSIPTEALEKLDL-
------------------AMGDLKMPIIESYEYQV-RKFLH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|3384 @Arthrospira_platensis_Paraca@ 646131117 AplaP_010100017279 hypothetical protein [Arthrospira platensis Paraca]
------------------------------------------------------------
---------------------------------------------MVIEWLRFKVPPTLW
EAFIQ------KDEQVW-------------------------------------------
------------------------------------------------------------
-TEGLKQFPGFIGKETWVDPK-LEEVILVIR--------WETREQWKSIPTEALEKLDL-
------------------AMGDLKMPIIESYEYQV-RKFLH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1042 @Arthrospira_sp_PCC_8005@ 648386264 APCC8_010100005432 hypothetical protein [Arthrospira sp. PCC 8005]
------------------------------------------------------------
---------------------------------------------MVIEWLRFKVPPTLW
EAFIQ------KDEQVW-------------------------------------------
------------------------------------------------------------
-TEGLKQFPGFIGKETWVDPK-LEEVILVIR--------WETREQWKSIPTEALEKLDL-
------------------AMGDLKMPIIESYEYQV-RKFLH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2036 @Lyngbya_sp_CCY_8106@ 640016057 L8106_12810 hypothetical protein [Lyngbya sp. CCY 8106]
MD----------------------------------------------------------
---------------------------------------------MVIEWLQLKVPQEKW
EAFLK------RDEEVW-------------------------------------------
------------------------------------------------------------
-TQGLKQYPGFMGKETWIDPQ-KEEIVLVIR--------WETRQQWKSIPQEELDALDQ-
------------------RMGDLRMPIVKSYEYQV-RKFLH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|5204 @Oscillatoria_sp_PCC_6506@ 648860294 OSCI_3890004 conserved hypothetical protein [Oscillatoria sp. PCC 6506]
------------------------------------------------------------
---------------------------------------------MIIEWLKFRVPAEKC
EAFIQ------RDEEVW-------------------------------------------
------------------------------------------------------------
-TAGLRSFPGFLGKETWVDPE-RNEVVFMIR--------WETREQWKSIPQNKIDEIDQ-
------------------LMGDLQMPIVEVREYQV-RKFLH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1017 @Synechococcus_elongatus_PCC_6301@ 637616677 syc1017_d hypothetical protein [Synechococcus elongatus PCC 6301]
------------------------------------------------------------
---------------------------------------------MVVEWLKFAVPATEQ
AAFLA------ADAAVW-------------------------------------------
------------------------------------------------------------
-TPLLSRYPGYLRKEVWQDPSDRDHLVMVIH--------WQSREQWKSIPEDVLIEGDRR
FQA---------------QLGR-EYPLVEAQEFAI-VPQPEI------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|552 @Synechococcus_elongatus_PCC_7942@ gi|81299314|ref|YP_399522.1| unnamed protein product [Synechococcus elongatus PCC 7942]
------------------------------------------------------------
---------------------------------------------MVVEWLKFAVPATEQ
AAFLA------ADAAVW-------------------------------------------
------------------------------------------------------------
-TPLLSRYPGYLRKEVWQDPSDRDHLVMVIH--------WQSREQWKSIPEDVLIEGDRR
FQA---------------QLGR-EYPLVEAQEFAI-VPQPEI------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2563 @Nostoc_punctiforme_ATCC_29133@ Npun_F2834 hypothetical protein
------------------------------------------------------------
---------------------------------------------MIIKLLKFEIAPHLR
ENFIH------KDTQIW-------------------------------------------
------------------------------------------------------------
-TTALAEYPGFLGKEVWIQPQ---------------------RSYISYTEQSQLTKTKGK
IPS---------------FEGK--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2563 @Nostoc_punctiforme_PCC_73102@ gi|186683114|ref|YP_001866310.1| hypothetical protein Npun_F2834 [Nostoc punctiforme PCC 73102]
------------------------------------------------------------
---------------------------------------------MIIKLLKFEIAPHLR
ENFIH------KDTQIW-------------------------------------------
------------------------------------------------------------
-TTALAEYPGFLGKEVWIQPQ---------------------RSYISYTEQSQLTKTKGK
IPS---------------FEGK--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1479 @Synechococcus_sp_PCC_7002@ 641611346 SYNPCC7002_A1336 hypothetical protein [Synechococcus sp. PCC 7002]
------------------------------------------------------------
----------------------------------------------MVEWLTFAVPQADQ
AKFIE------TELEIW-------------------------------------------
------------------------------------------------------------
-NPIDRRSPAFVRKEIWQDADHPDQLTVVVS--------WSSQALRKVVSPEEVDAAEKA
FDK---------------AMG-KSYPILEKKEFRN-LSTTN-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1294 @Synechococcus_sp_JA_2_3B_a2_13@ 637875726 CYB_1324 antibiotic biosynthesis monooxygenase domain protein [Synechococcus sp. JA-2-3Ba(2-13)]
MS----------------------------------------------------------
-------------------------------------TCPSPPGPIAIEHLCFRVPPGGQ
AAFLE------QDERVW-------------------------------------------
------------------------------------------------------------
-GSALRRHPGFLGKEVWLDQEDPELVHLILR--------WASRADWKAFPSEQVEALDR-
------------------QMRPFYVRLEQAKEYQL-WQPGPSAGTGKQD-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2184 @Synechococcus_sp_JA_3_3Ab@ 637873827 CYA_2294 antibiotic biosynthesis monooxygenase domain protein [Synechococcus sp. JA-3-3Ab]
MS----------------------------------------------------------
------------------------------------------DQPIAIEHLCFRVPPGGQ
RAFIL------QDEQVW-------------------------------------------
------------------------------------------------------------
-GPALRQQPGFLGKEVWLDVEDRELVHLILR--------WASRAAWKAFPPEQAEALDR-
------------------QMQPFYVRLEQAKEYQL-WQPGLPAEEAAN------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|147 @Cyanothece_sp_CCY_0110@ 640623792 CY0110_10337 hypothetical protein [Cyanothece sp. CCY 0110]
M-----------------------------------------------------------
--------------------------------------SGEFLDFLKHKYAYVAVGEFKP
GQFSE------AQKLYE-------------------------------------------
------------------------------------------------------------
-KAVSTYKQGFQGAFLLQKPG-TDEGIAVIM--------WEKIEDMEANQSEVYEKIIEE
MSPLFVKPPKTDFYEVCSEIDGFSET----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|288 @Microcystis_aeruginosa_NIES_843@ 641534268 MAE_02890 hypothetical protein [Microcystis aeruginosa NIES-843]
M-----------------------------------------------------------
---------------------------------------PEFLDFLKHKYAYVAIGEFKP
GCFSE------AQKLYE-------------------------------------------
------------------------------------------------------------
-KAVSTYSTGFQGAFLLQKPG-TDEGIAVII--------WDKIDDMEANKSEAHELLLKS
MAPLFAKPPVTDFYEVCSEIEGSPI-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|1014 @Prochlorococcus_marinus_MIT_9312@ gi|78779399|ref|YP_397511.1| lectin subunit alpha [Prochlorococcus marinus str. MIT 9312]
M-----------------------------------------------------------
------------------------------------------------------DPLDPL
TEIIN------SGQGFS-------------------------------------------
------------------------------------------------------------
-------------------PAIALERII-----------WA-------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MIGVFFF
GAISISMTNSMRSKNLLGTKSLFS-------FSKDKENRDDSTSQLSDDDE---------
------------------------------------------------------------
-------------------------------------------------------
