>Cyanothece_sp_PCC_7425 gi|220906503|ref|YP_002481814.1| unnamed protein product [Cyanothece sp. PCC 7425]
MG----------------------------------------------------------
-------LAIVGAILLVTGGI-LYFVQRHYQQKLYSIKLARKT-TVAELKQLADQVGAEI
GQ------------------------------------------GSLREYVKLSGQIKCD
T--P----------LISELKQV-------PCVYYQMQVEREYEE----------------
------------------------------------------------------------
----------------RLTERDNDGETR--------------EKTQRGSETIASNSQSTP
-FFL---Q--------DQSG----------AIEVD--PSGAAIE-TVQVLNE-FRPEA--
GSARISFGNFSLSVGGSFPAGRETIGYRYRESILPPDRRILIVAT--------------A
SDSSGILSL-QKPVE--KRQK---------------------------------------
FIISLKSEDHLAQSTQQTATYTFYGMIACLGLGA---ILLVVGLIIR-------------
------------------------------------------------------------
--------------------------------------------------
>Acaryochloris_marina_MBIC11017 gi|158336842|ref|YP_001518016.1| unnamed protein product [Acaryochloris marina MBIC11017]
------------------------------------------------------------
-------MKIIGIILIVIGII-LFFVYSNLKRKLASLRQARPA-SIAELNHLASEIALEM
GS------------------------------------------GSWRDYVKLRGTIQCD
Q--P----------LISELKQM-------PCVHYNMTVVREYEE----------------
------------------------------------------------------------
----------------QVTERDSDDKVV--------------TKTQRGSETLSQNRESVP
-FFL---Q--------DDTG----------EIWVE--PEGAQIE-TVRVLDE-FSPEQP-
SGGQLSFGGFSLSL-SSAETGRQTIGYRYQESVLPVQRQVFVVAQ--------------V
SDFNQSLVL-ENPTT--KGQR---------------------------------------
FVISLKSEEALAQTTQTSVTYAFYGMISTLVVGG---LLVIFGLLSA-------------
------------------------------------------------------------
--------------------------------------------------
>Cyanothece_sp_PCC_7424 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424]
------------------------------------------------------------
-------MILIGIICLIVGVI-LLFFWRSNRSKLRNLRLASAS-TISSLQTIANQIAEEI
GG------------------------------------------GSLREYVKIRGVIECD
R--P----------LISQLKQE-------PCVYYSMTVTWEYNE----------------
------------------------------------------------------------
----------------EVIKQDNEGKTI--------------REKERKSETVAQNSRSIP
-FTL---Q--------DSTG----------EIRVN--PERAEIE-TVKVLEE-FRPENF-
SGGSLTFGNFSINL-PSFEERRQTIGYRYQEEILPIGRQILVIGT--------------A
TDEEGMITI-RKPTE--KGQR---------------------------------------
YFISLKSEEELSQATNNAIRGTFYSMIFFLTLGL---ILLVAGVLRG-------------
------------------------------------------------------------
--------------------------------------------------
>Synechococcus_elongatus_PCC_7942 gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococcus elongatus PCC 7942]
MA----------------------------------------------------------
-------AIILAAITAIAAIV-LYFVRRHYRFKLQSLLLAQPA-TSLQLKEIAEHVAGEI
GG------------------------------------------GNLRQYVKMWGAIEVE
Q--P----------LVSELKQE-------SCVYYCSTVSREYEE----------------
------------------------------------------------------------
----------------RVRKEDSEGKVT--------------WTTERRSETISQNRRSTP
-FYL---R--------DQHG----------RVRVE--PESAAIA-TIPVLDE-FRPDS--
SASSLIFGAFSLSL-STTAGLGKTLGYRYREEILPCDRSVLVVGA--------------A
SDETGELTL-GPSSE--ARQQ---------------------------------------
FFIALKPETALLQEVKQTIQWLTIGAIASVVVTV---VAAIAALL---------------
------------------------------------------------------------
--------------------------------------------------
>Thermosynechococcus_elongatus_BP-1 gi|22298202|ref|NP_681449.1| unnamed protein product [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
-------MGVLGGILLVIAVL-VLCGWWDYRLKVRALNLAVSS-TPAQLHELQRRVAQEI
GG------------------------------------------GYLQEYVKISGQIVAD
R--P----------LVSELKRL-------PCVHYRLCVSRVYKT----------------
------------------------------------------------------------
----------------TESHEDGS------------------SETKYRHEILSSNTQTIP
-FRL---R--------DGDM----------EIYVD--PRGAEIE-TVQVLNE-FQEDN--
NTTHLAFGRFQMDL-SSLPKHSDTVGYRYEEWILPVNQQVFVVGT--------------A
SDERGKLRI-RRPHQ--KGQL---------------------------------------
FFISLESEENLTKKVRQYARASIIAAGVFSGLGI---LLILL------------------
------------------------------------------------------------
--------------------------------------------------
>Thermosynechococcus_elongatus_BP-1 gi|22297743|ref|NP_680990.1| unnamed protein product [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
-------MGVFAHLCLTGSAF-LFALEGYYRLQLRGIKVASPS-TIGELEKFQQQVAQEM
GS------------------------------------------GSWREYVQVVGQVTTS
Q--P----------LLSEVKRI-------PCVYYKTIISREYEK----------------
------------------------------------------------------------
------------------------------------------EGSDRPSEIIGRHEQSTL
-FLL---R--------DHQG----------EIEVN--PFGAEIE-AVQVLDE-LRPADQP
HAFALSLGFLSFNW---HFGKGTTLGYRYQEWVLPLGQPVSVVGM--------------A
SDQGGVLRL-QKPQN--RGQK---------------------------------------
FIISLSFEDPLIQQYKQQKRKMTYASLGATLCGV---CGLVLALF---------------
------------------------------------------------------------
--------------------------------------------------
>Rubrobacter_xylanophilus_DSM_9941 gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941]
MVGTVV------------------------------------------------------
-------FLLVGVVLCVAGGV-LLYFRRRMLGKAELMRRTRTS-GAAGVSALSP------
-----------------------------------------------GTLVEVKGTLRCE
R--P----------LQSEMAKE-------RCAYYSSKVVREYLE----------------
------------------------------------------------------------
----------------RDRGDGA-------------------PGSGRRSEVLARSERFAP
-FVV---E--------DDTG----------GVPVS--AEGAEVD-AKKVVDR-FERGAGA
AGLSVTIGGATIDL----GGGERTLGYRHTEEILPVDAPVYVLGA--------------V
RRDGGI----GPPEE--GAGR---------------------------------------
FVVSWRSEEALGESLGRGARLLGLIALGLFLAGA---AFLAVGAAAALGYLQFR------
------------------------------------------------------------
--------------------------------------------------
>Sphaerobacter_thermophilus_DSM_20745 gi|269838375|ref|YP_003320603.1| hypothetical protein Sthe_2360 [Sphaerobacter thermophilus DSM 20745]
MGTSGV------------------------------------------------------
-------LLIIGLVAAGIGAV-LLFIGRRIQAKTDLLAKVPTV-DASEVASLIP------
-----------------------------------------------GEMIEVKGVIRCD
T--P----------LTAELAQR-------ACVYYSSRVVREYEY----------------
------------------------------------------------------------
----------------RRRNAKGE------------------TVRSRRSETVAHNEQFTP
-FYV---E--------DSSG----------RVLVD--PEGAEVD-AQKLVDR-FERNPGA
LGPTISLGGISLNL----GGDDGTIGYRYQEHVLPVDIPVYVLGV--------------V
QEGGTI----GRPPAALKGRR---------------------------------------
FIISYRAEEALRESWGKKARWLGISAVALFALAV---ILFVVAVGMLVA-----------
------------------------------------------------------------
--------------------------------------------------
>Thermomicrobium_roseum_DSM_5159 gi|221632287|ref|YP_002521508.1| unnamed protein product [Thermomicrobium roseum DSM 5159]
MIF---------------------------------------------------------
-------VTLCFLITAGVGLV-CLIGYRRTRQQLRLLRLVATC-PIAELHERIP------
-----------------------------------------------GEMVEITGTVHCA
T--P----------LRSEYTGQ-------PCVYYRTVTERVVER----------------
------------------------------------------------------------
----------------HGRSKKGG----------------------RLSEVVAQNEQRIA
-FEV---D--------DGTG----------RVAVD--PVGAEID-GRKLLDR-FEPVENG
EGATLRIAGMSVEV---RAAEWRTLGYRKIEEAVLVGYPVYVLGV--------------L
QDDGSI----GRPPEGSRLRE---------------------------------------
FLISARSEEELATSLRRRSYLFLAGAITSFVVAG---MLLIALLVQSVISIS--------
------------------------------------------------------------
--------------------------------------------------
>Chloroflexus_aurantiacus_J-10-fl gi|163846705|ref|YP_001634749.1| hypothetical protein Caur_1130 [Chloroflexus aurantiacus J-10-fl]
------------------------------------------------------------
-------MIVGGVLLLVLAVI-FFFVARANAGKLQALNAVDTY-DTATLSAIHRRITTAL
GA------------------------------------------HDFAQPCEVMGLIECA
T--P----------LTGPVSGQ-------ALVAYLYTTHREYEE----------------
------------------------------------------------------------
----------------RITTQESGRST---------------TRIERRSEQLEQNERRVP
-FTI---R--------DDTG----------QVLVV--PDGAKID-LIETANR-FLETPQP
-----------------WTGATRTLGQRQFERGLEVGIRVFVSGT--------------A
IDQNGQVVIARHPTN--SKQT---------------------------------------
FIISRKSEHELANSAATWARNMRYAAIASGVIGL---ALVVGGVLVSG------------
------------------------------------------------------------
--------------------------------------------------
>Chloroflexus_sp._Y-400-fl gi|222524514|ref|YP_002568985.1| hypothetical protein Chy400_1238 [Chloroflexus sp. Y-400-fl]
------------------------------------------------------------
-------MIVGGVLLLVLAVI-FFFVARANAGKLQALNAVDTY-DTATLSAIHRRITTAL
GA------------------------------------------HDFAQPCEVMGLIECA
T--P----------LTGPVSGQ-------ALVAYLYTTHREYEE----------------
------------------------------------------------------------
----------------RITTQESGRST---------------TRIERRSEQLEQNERRVP
-FTI---R--------DDTG----------QVLVV--PDGAKID-LIETANR-FLETPQP
-----------------WTGATRTLGQRQFERGLEVGIRVFVSGT--------------A
IDQNGQVVIARHPTN--SKQT---------------------------------------
FIISRKSEHELANSAATWARNMRYAAIASGVIGL---ALVVGGVLVSG------------
------------------------------------------------------------
--------------------------------------------------
>@Synechococcus_sp_JA_2_3B_a2_13@ 637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba(2-13)]
MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPPPE
RKAFMNWLMLLGLLCLPASLF-SFVEYLRSQRLVQQLSATRLL-KIAELRHLGQTNPQAK
GA----------------------------------------------NLAQVYGRVVCD
R--P----------LVSELSRQ-------PCVYYKSEISWEYDEIECYRRYLNSRGDVAY
SERISEGEYQNALRLGSRAKSYPGEMVGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPNPG
YPQQLGSPGYPQKSPFSEVSSPQKHYANVYYDPSTGREYLLERETRTRDETLHSVVRQIP
-FFI---E--------DETG----------RVRVD--PTGAEIE-AMSVVDEHIFPGKGP
SRFNFNLKRYLSGV---RTENRSTRAFIYKEWVIPVDAMAFTMGQ--------------V
RFEAGDPVI-RKPLS---GER---------------------------------------
FMIAPKSPEALLEEQRSNASSYLVGSVVLLGIGIFTVLHLLQSLQPYR------------
------------------------------------------------------------
--------------------------------------------------
>Pseudonocardia_dioxanivorans_CB1190 gi|331695440|ref|YP_004331679.1| hypothetical protein Psed_1589 [Pseudonocardia dioxanivorans CB1190]
------------------------------------------------------------
-------MWVIGVVVVLVGAG-FLWSAVRAQRSVHAMLAAETL-SVPELEEL-RRVSDDL
GAR-----------------------------------------GSFRKVCEVVGAAHPS
P--E--------GVLRSELSGV-------ECVWHSHRVQRRYKH----------------
------------------------------------------------------------
----------------YDRDRDGS------------------TRVTTRTETVAEQTSGPG
-FAL---L--------RDGR----------TIGVD--HAGRRPDGVEQVTDR-FEQTQEP
SNGWADVVGALVGS-----DRDETIGYQYTEWVLRPGTPMYVLGE--------------V
HDAIGPLVI-APPAD--PKQP---------------------------------------
FVMSTSTEQQLTDAARGRQRFRSRLGAALVVVGI---VVVVLALVL--------------
------------------------------------------------------------
--------------------------------------------------
>Acetobacterium_woodii_DSM_1030 gi|379012200|ref|YP_005270012.1| unnamed protein product [Acetobacterium woodii DSM 1030]
M-----------------------------------------------------------
-------AIIIGLLIIIAGIFYAVYIYRKNTNKVQEIQFQQTT-CIKDVLDIVGDLSSLD
--------------------------------------------ENYRHYSEVKGQLHSV
S-----------GNVEAPFSQR-------PVAYYENEVYSVHEE----------------
------------------------------------------------------------
----------------TRTERDDKGNTR--------------TVTDKVETSLSSEKSPVE
-VYL---S--------DSSS--------DEKVYIDLASFGSDVD-LMPGCNR-MESKDSD
--WVRNNFNFSVNQ----NRGSRFLGYRFFEEILPEDQPMYILGE--------------I
HKRGNRLYV-GRSVA--AKKP---------------------------------------
SHVTYKSEDELLDDIKNEKLVAIGIGVAGVVVGIAVMFLF--------------------
------------------------------------------------------------
--------------------------------------------------
