>Selaginella_moellendorffii_gi|302770663|ref|XP_002968750.1| hypothetical protein SELMODRAFT_91152 [Selaginella moellendorffii]gi|300163255|gb|EFJ29866.1| hypothetical protein SELMODRAFT_91152 [Selaginella moellendorffii]
M----------------A--SHDEEICAALTRLAMAGDGIVLGL----------------
-----GMAALALRTWLKFGSHTRALKQVEGTAQVEIHDLRSLVESGE-------KEPSSD
SSP-----------------------------------PLVIVRGRVALPPKTS---SE-
-----EVLLARNQTDLAVFVERTQTYLFNEWR-GLFRW----GPEWRGLLG-WGSLKEQV
AFSRR-KIP-FVLLD--SDPQY----D------GACVHINMENVE-HPLPLVTVFHQLHP
VQT-S--------------SSTFLQAVFGRRYPVGV-----------------IDEEKIL
PLNREITAVGF-------------LS-KHPQG-LPAIKSSN-Q-----------------
-------------------------MPFFL-----TEFSREELIVELASATHALFWTGIV
ISSLALGVIGYSAFKN--------WCKWKEWRRL-RQIQEEL------------------
------------------R-REEQVMEEDEE------------P-ATTQEGSE-------
-----VPDGQLCVVCLLRRKRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSG
YIRVYD---
>Physcomitrella_patens subsp. patens_gi|168019172|ref|XP_001762119.1| predicted protein [Physcomitrella patens subsp. patens]gi|162686836|gb|EDQ73223.1| predicted protein [Physcomitrella patens subsp. patens]
------------------MAGHEDELCAALMRLALAGDGLVMGV----------------
-----GMTVLAFRTWIKFWSHSKALKDIKDTPVTRIADLRTLVEEPDVQAKEKIRTPEKI
SPPHQDIEVFATRSKVKMPSRPWMVERLPIPSLETKQEKLVIVRGRVQTKAFVE---SEG
DQRDAEALIPLNVPEKAVFVERTQTYVLTEMS-NFLGW---------------ITQKDLV
KFTRQ-VVP-FVLAE--TEAHW----SFRPSDMAVYVHINLDESQ-HPIPLVTVHHQLHP
VPA-S--------------SYTLFQAMFGRRYPVGL-----------------LDEEKIL
PLGAEITAVGV-------------LH-TAPDG-TPVVKSSK-R-----------------
-------------------------LPIFL-----TEFTREQLLVELASSTKVLFWMGVA
VSTVAAGVLGYSLVKN--------WTRWKQRQQQ-RQSQNNS------------------
------------------E-NRQNSTIE-----------------DEAENFED-------
-----IPDGELCVVCLLRRRRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSVTG
IVRVYDS--
>Sorghum_bicolor_gi|242042023|ref|XP_002468406.1| hypothetical protein SORBIDRAFT_01g045370 [Sorghum bicolor]gi|241922260|gb|EER95404.1| hypothetical protein SORBIDRAFT_01g045370 [Sorghum bicolor]
-----------------M-SARDRETAEALVRLAASLDGAVLGL----------------
-----GTAAVAVASWVKYLAVSGQLRLVASAATASIGDARSLL------RGDGN-----E
P-------------------------------------RIAAVRGYVRT--QGS------
------FLRAPFSSEAGVVVKHTQMCLFTEWR-GIFGW----TFDLHALL--FRSWKEQI
VTSFR-AVP-FVLAS--TELGN----S------TGVVHINVDEVDYQPLPLTTVFHKLIP
LET-T--------------PYTLFQTIIGNGYPIAL-----------------LDEEKIL
PIGKKITAIGL-------------CR-AK-NAESVEITSCP-E-----------------
-------------------------IPFFL-----SELTKDEMQAQLASRARILFWGSIV
LGTLSVCLVGHAIYRG--------WKRIKLRREA-RQAQQMF------------------
------------------E-DAEDA--IRED------------N-SSDDDDDD-------
-----VGDGQLCVVCLRKRRKAAFIPCGHLVCCCKCALRMER---EVEPLCPMCRQDIRY
MIRIYDS--
>Zea_mays_gi|212721266|ref|NP_001131841.1| uncharacterized protein LOC100193216 [Zea mays]gi|194692688|gb|ACF80428.1| unknown [Zea mays]
-----------------M-SARDRETAEALVRLAASLDGAVLGL----------------
-----GTAAVAVASWVKYLAVSGQLRLVASAATASIADARSLL------SGDGA-----E
P-------------------------------------RIAAVRGYVRA--HDK------
------FFRAPFSGEAGVVTKHTQMCLFTEWR-GIFGW----TFDLHALL--FRSWKEQI
VTSFR-SVP-FVLVS--TELGN----P------TGVVHINVDKAD-QPLPLTTVFHKLIP
LET-T--------------PYTLFQTIIGNGYPIAL-----------------LDEEKIL
PIGKKITAIGL-------------CQ-AK-DAESVEITSCP-E-----------------
-------------------------IPFFL-----SELTKDEMQAQLASRARILFWGSIV
LGTLSVCLVGHAIYRG--------WTRIKLRREA-RHARQMF------------------
------------------E-EAEDA--IHRD------------D-SS--DDDE-------
-----IGDGQLCVVCLRKRRRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDIRY
MMRVYDS--
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------PWSGEHGVVTKHTQMCLFTEWR-GIFGW----TFDLHALL--FRSWKEQI
VTYFR-SVP-FVLAS--SEIGN----P------IGMVYIDVEKAA-QPLPLTTVFHKLIP
IET-T--------------PYTLFQTIIGNGYPIAL-----------------LDEEKIL
PIGKELTAIGL-------------CR-AN-DEGSVEISSCP-E-----------------
-------------------------LPFFL-----SELTKDEMQAQLASRARILFWGSVV
LGTLSVCLVGHAIYRG--------WKRIKLRREA-RQAQQLF------------------
------------------E-EGEDA--IQED------------D-SS---DEE-------
-----VGDGQLCVVCLRKRRKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDIRY
MMRIY----
>Oryza_sativa Japonica Group_gi|115451087|ref|NP_001049144.1| Os03g0177300 [Oryza sativa Japonica Group]gi|108706473|gb|ABF94268.1| C3HC4 zinc finger containing protein, putative, expressed [Oryza sativa Japonica Group]gi|113547615|dbj|BAF11058.1| Os03g
-----------------M-SARDRETAVALARLAAALDGAVLGL----------------
-----GTAALAVASWVKYLAASGQLRRIASAPAAAIPDLRSLLAEYGGGGGDGD-----Q
P-------------------------------------ILAVVRGHVRAAPRGK------
------YLVPPGSGEHCVVAKHTQLCLFNEWR-GIFGW----TFDLHALF--FKSIKEQI
ITSFRW-VP-FVLVD--PE--N----M------TGMVHVKLDRAM-QPLPLTTVYHKLTP
VDS-T--------------PYTLFQTIIGNGYPIAL-----------------LDEEKIL
PVGKEITAIGY-------------IR-PH-KA-SVEISSCS-E-----------------
-------------------------IPFFL-----SDLTKDEMEAELSSRAKTLFWASVV
LGTMSVCLLGFATYRS--------WKKIKERREA-RQAQEVF------------------
------------------R-QTTDE--VTDD------------Q-SSDEEAGE-------
-----MGDGQLCVICLRKRRKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDIRY
MIRIYDN--
>Brachypodium_distachyon_gi|357113780|ref|XP_003558679.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Brachypodium distachyon]
-----------------M-SARDRETVEALARVAAALDGAVLGL----------------
-----GTAALAVVSLAKYLAASGALRRIAEAPEVAIPDLRYSLLA----GLGEG-----E
S-------------------------------------RLAVVRGLVRSPPWGK------
------FLIPPGSREHCVVAKHTQTCLFGEWR-GIFGW----TFDLHALF--FKSLKEQT
ITSFR-WVP-FALVDPASASDK----S------TEMIHVKLDGAVQQSLPLTTVYHKLIP
VEQ-N--------------SYTLFQTIVGNGYPIAL-----------------LDEEKIL
PIGKEITAIGL-------------CR-VN-NQ-NVEITSCP-E-----------------
-------------------------IPFFL-----SDLTKGEIEAELDSRARTLFWVTFA
LGTMSVGLLGHAIYRF--------WEKVKQHREA-RQAQQRF------------------
------------------H-QADDEDDTGEN------------G-SDDDFPGE-------
-----MGDGQLCVICLRKRRKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDIQY
MLRVYDS--
>Populus_trichocarpa_gi|224070805|ref|XP_002303243.1| predicted protein [Populus trichocarpa]gi|222840675|gb|EEE78222.1| predicted protein [Populus trichocarpa]
M----------------ASRAHEQALAAMLSHLALSFDGAILGA----------------
-----ALAYAAVRSFLNFTANSKSLAKIRKAPTLSVSDLRSLLQNHDQDHQDQEQ-----
--------------------------------------KLVIVRGQVEAKSAVD-GSGKK
SSRDSNVLLSHESGDKAVILQRTQTCIYNEWK-GFFGW----TSDLRSIF--GRSLKEQE
TTFLR-TVP-FTLVE--GGQWP----Q------SDYVIVNMDGSS-HPLPLTMVYHQLQP
IVA-S--------------RYTFIQALFGHEYPVGV-----------------LHEEKIL
PLGKCISAVGI-------------CN-SK-DG-IPEIKSCK-E-----------------
-------------------------LPYFL-----ADMTKDEMVADLAFKAKILLWSGIV
LGSLSIGVLGFAVMRN--------WNKWKAWRQ--RRSQQPI------------------
------------------H-TTSD--EDVSQ------------I-DDNEDAGD-------
-----VPEGQLCVICLMRRRRAAFIPCGHLACCHTCAVSVES---EVSPKCPLCRQAVRN
SIRIFEC--
>Vitis_vinifera_gi|225442119|ref|XP_002274016.1| PREDICTED: hypothetical protein [Vitis vinifera]gi|297743001|emb|CBI35868.3| unnamed protein product [Vitis vinifera]
M----------------S--AHDQAAAAILAQVALAADGAILGL----------------
-----ALAYVAVRSFIRLSSTSSALRQIDQSPSFRVSDLRSLLSPSSDDESDQSTSS--D
G-------------------------------------LLVVVRGTVEAKSAID-GNWKS
LRP--NVLVSHESGEKGVILQRTQTCIYNEWR-GFFGW----TSDIRTLF--ARSWKEKE
STSLR-TVP-FILVE--GGRWP----Q------SDYVIVNMDGSR-HPLPLTTVYHQLQP
VNA-S--------------PYTFLQALFGHDYPVGL-----------------LDEEKLL
PLGKEITAVGI-------------CS-LK-NG-IPEIKSCK-D-----------------
-------------------------LPYFL-----SEMSKDQMVVDLVFKSKVLFWSGVI
LGSVSIGVLGYAVVRN--------WNRWKEWRQQ-RGVRPPS------------------
------------------Q-AVTD--DTDTQ------------I--AEDDAGD-------
-----VPDGELCVICLMRRKRSAFVPCGHLVCCQRCALSVER---ELSPKCPVCRQIIRS
SVRIYGS--
>Ricinus_communis_gi|255560625|ref|XP_002521326.1| ubiquitin-protein ligase, putative [Ricinus communis]gi|223539404|gb|EEF40994.1| ubiquitin-protein ligase, putative [Ricinus communis]
M----------------S--SHEQALASLVSQLALSFDGAFLGV----------------
-----VVALTAVRSILKFASNSKALRKIRNAPTVKVSDIRSVLEVSDE-------TQ--D
Q-------------------------------------KLVIVRGQVEAKSAVD-GNWKS
LIPNNNVLVAHESGDKAVIVQRIQTCIYNEWK-GFFGW----TSDIRAIF--GRSWREQE
STLSR-SVP-FVLVE--AGRWP----Q------SDYVIVNLDGSR-HPLPLTTVYHQLQP
IDA-S--------------PYTFLQAFFGYEYPVGL-----------------LDEEKIL
PLGKEINAVGL-------------CG-SK-NG-ILEITSCK-D-----------------
-------------------------LPFFL-----SDLSKEQMVVDLAFKTKVLFWSGVV
LGSFSICILGYAAVRN--------WNRWKAWRQQ-RQFQQQS------------------
------------------N-SVSD--ADVSQ------------I-DVEEETVD-------
-----VPDGQLCVICLMRRRRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAVRN
SIRIFEC--
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------CIYNEWK-GFFGW----TSDIRAIF--GRSWREQE
STSLR-MVP-FVLVE--GGRWP----Q------SDYVIVNIDGSR-HALPLTTVYHQLQP
IDA-S--------------PYTFLQALFGHEYPVGL-----------------LDEEKIL
PLGKEINAVGI-------------CS-SR-NG-VLEIKSCK-D-----------------
-------------------------LPYFL-----SDMTKDQMVVDLAFKTKVLLWSGVV
LGSLSIGILGYAAVRN--------WNRWKEWRQH-RQSQQQN------------------
------------------H-AAST--DDDPQ------------I-DADEEAGD-------
-----VPDGQLCVICLMRRRRSAFIPCGHLVCCQLCAISVER---EVSPKCPLCRQAVRN
SMRIF----
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----R-TVP-FVLID--GSQWP----A------VDYVVVNMDGSK-HHLPLTTVYHQLQP
INA-S--------------PYTFLQALFGHEYPVGL-----------------LDEEKIL
PIGKDVSAVGL-------------CF-LK-NG-ILEIKSCK-D-----------------
-------------------------LPYFL-----TEMTKDQMVIDLAFRTKILFWSSIF
LGSASIGILGFAFVRN--------WNRWKEWRQR-RRDEQQS------------------
------------------H-AAVD--EATAH------------I--AEDELGD-------
-----APDGQLCVICLMRRRRSAFVPCGHLVCCQRCALSVER---EVSPKCPVCRQTITN
SVRIY----
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-NA-S--------------PYTFLQALFGHEYPVGL-----------------LNEEKIL
PLGKDISAVGI-------------CS-FK-NG-IPEIMSCK-D-----------------
-------------------------LPYFL-----SDLTKDQMLLDLAFRTKILFWSGII
LGSLSISILGYAALRN--------WNRWKERRQQ-RQAHQPS------------------
------------------H-AASI--DANSE------------L-TGEEEIGD-------
-----IPDGQLCVICLMRRRVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEIRG
SMRVF----
>Medicago_truncatula_gi|357514013|ref|XP_003627295.1| Baculoviral IAP repeat-containing protein [Medicago truncatula]gi|66947626|emb|CAJ00009.1| C3HC4 zinc finger containing protein [Medicago truncatula]gi|355521317|gb|AET01771.1| Baculoviral IAP repeat
M----------------S--SQEQALVSLLSQLALSFDGAVLGF----------------
-----AVAYVAVRSIRKFTLTSAALRKITAAPSVSVSDLRSLLTETDENSD--------E
G-------------------------------------KIVIVRGTVDAKNVVD-GSWKA
LWP--GVLVSSESGDKGVVLQRTQTCIYNEWK-GLFGW----TSDLRALF--LRSWRQQE
STSLR-KIP-FVLID--VGRPS----N------PEYVVVNMDGSS-HPLPLTTVYHRLQP
VNP-P--------------PYTFLQALFGHEYPVGL-----------------LDEEKIL
PLGKDVSAVGL-------------CS-LR-NG-IAEIKACN-D-----------------
-------------------------LPYYL-----SDLSKDQMIVDLSFKTKLLFWSGIL
LGSMSVGIIGYAVVRN--------WNKWKQWKQQ-RQLQQRR------------------
------------------Q-QPIE-----PV------------P-PTDDEIED-------
-----VPDGQLCVICLMRRRRSVFIPCGHLVCCQGCAISVES---EVAPKCPVCRQEVRD
SVRIFES--
>Glycine_max_gi|356567748|ref|XP_003552078.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like [Glycine max]
M----------------S--HQEQALVSLLSQLALSLDGAVLGF----------------
-----ALAYAAVRTLFKFTATSSALRKLRRAPSLSVSDLRSLLAEIPSDGD--GNSK--G
G-------------------------------------IIVIVRGTVDAKSAVD-GTWKT
LRP--GVLVSRESGDKGVILQRTQTCIYNEWK-GLFGW----TSDLRAIF--ARSWRQQE
STSLR-KVP-FLLTD--VGRRP----N------AEYVVVNMDGSR-HPLPLTTVYHKLQP
ITA-S--------------PYTFLQALFGHEYPVGL-----------------LDEEKIL
PLGKDITAVGL-------------CS-LK-NG-IAEIKSCK-Y-----------------
-------------------------LPYFL-----SDLSKDQMIMDLSIKTKILFWGGIA
LGSMSVGVLGYAVVRN--------WNKWKQWKQQ-RQLQQQR------------------
------------------Q-AVSD-----VE------------P-QMDDEIED-------
-----APDGQLCVICLMRRRRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEIRD
SVRIYES--
>S.lycopersicum_New__Gene_Model_C_gnl|BL_ORD_ID|12:4626300246267916
M----------------S--IYDQAAAAVLSQIATAADGALIGL----------------
-----ALAYVAVRSIVKFKANSSALHKINDAPSLNVSDLRSLLSSSD-NSDSSNHSD--D
G-------------------------------------KLVIVRGTVEAKSAVE-GNWKS
LRA--NILSAHNSAEKGVILQHTQTCIYNEWR-GFFSW----AGDLYSIF--PRVRKDQQ
SSSLR-TVP-FVLIE--TGRWP----Q------PKYVNVNMDGST-HSLPLVTVYHHLQP
LHA-T--------------PLTFIQALFGHHYPVGV-----------------LDEEKIL
PLGKDITAIGV-------------CS-SK-DG-ILEIKSCE-D-----------------
-------------------------LPYFL-----SDMTKDQMLVELAFKTKILMWSGVL
FGSVAVGVLGYAVVRN--------WNRWKLWRHQ-RQAQQQR------------------
------------------D-AASN--DDDVQ------------V-SADEESGD-------
-----VPDGQLCVICLTRRKRAAFVPCGHLVCCQRCALSVER---DLAPKCPLCRQTIHS
SVRIYDS--
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------IF--SRSWRERE
SKVFR-TVP-FILAE--GGRRP----I------SEFVAVDMDGSR-HPLPLTTVYHHLHP
VNP-S--------------PYTFLEALFGHRYPVGL-----------------LDEEKIL
PLGKEISAVGL-------------CS-VK-DG-VLEIKSCK-D-----------------
-------------------------FPYFL-----SEMSKDQMVVDLTSRTKVLFWSGIF
LGSVSIGVLAYAVSRN--------WNRWKVWRQQ-RELQRSI------------------
------------------R-ASNA--EAQIQ------------EEEEEEDAGD-------
-----VPDGQLCVICLMRRRRSAFIPCGHLVCCQLCSISIER---DVAPKCPVCRQQIRT
SVRIY----
>Citrus_clementina_0.9_012450m_PACid_19274708
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------VNMDGSR-QPLPLTTAYQRLEL
ANV-S--------------PFTFLQAMFGLKCPIGV-----------------LAEEKIL
PLGKDISAVGI-------------CS-FK-NG-IPEIKSCK-D-----------------
-------------------------LPYFL-----SEKTKDLMVVDLVNRSKILFWSGIV
LGSLSIGILGYAIVRN--------WNRWKD-RQQ-RMSRQLT------------------
------------------E-APSD--DADSQ------------IGSDEDVAGD-------
-----IPDGQLCVVCLTRRRISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRS
SMRIY----
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------VNMDGSR-QPLPLTTAYQRLEL
ANV-S--------------PFTFLQAMFGLKCPIGV-----------------LAEEKIL
PLGKDISAVGI-------------CN-FK-NG-IPEIKSCK-D-----------------
-------------------------LPYFL-----SEKTKDQMVVDLVNRSKILFWSGIV
LGSLSIGILGYAIVRN--------WNRWKD-RQQ-RMSRQLT------------------
------------------E-TPSD--DADSQ------------IGSDEEVAGD-------
-----IPDGQLCVVCLTRRRISAFNPCGHLVCCRRCAISVER---EASPKCPVCRMTVRS
SMRIY----
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------GVILQRIQTCIYNEWR-GLFRW----TADLGSMLMPRRITKENA
SSSMN-MVP-FILVE--EGKWP----P------SDHVVVNMEGST-HPLPLTTVYQHLQP
VKA-S--------------SYTVFQALVGLEYPVGL-----------------LYEEKIL
PLGKDITAVGI-------------CN-LK-NG-IPEIKSCE-D-----------------
-------------------------LPYFL-----SILTKDQMIADLSFKSKVLLWSGLI
LGTVAIGVLGYSISRN--------WSKWKEWKAR-RAQQQQN------------------
------------------A-SRIE----NLD------------E-TEEEESGD-------
-----VPDGELCVVCLMRRRRSAFVPCGHLVCCHRCAFSVER---EVSPKCPVCRQPIRN
SVRIY----
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------PYTLIQAIVGHAYPVGL-----------------LDEEKIL
PLGKEITAVGH-------------CT-LQ-DG-NPQIISCK-K-----------------
-------------------------VPYFL-----SDMTKDQMIVDLVSKKKILFWAGIV
LGSVSLGVLGYALTRN--------WQRLKEWRQR-RQIQQSR------------------
------------------E-EEIANLDATPE------------DTRADEETED-------
-----IPEGQLCVICLMRRKRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDIRT
SVRIY----
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--A-T--------------PYTFLQAVFGHEYPVGV-----------------LDEEKIL
PLGKNISAVGI-------------CS-FE-NG-VPVIKSCS-D-----------------
-------------------------FPHFL-----CEMTKDQMILDLVFKTKFLFWSSIV
LGSLTVGILGYSAARN--------WNRWKQWRQH-RQLQNSRNDSPTSQLDSSNDIPIYG
DFASDDEAATVPDDELSSH-VPDD--ELSSH------------V-PDDELSSH-------
-----VPDGQLCVICLMRRKRSAFIPCGHLVCCERCAVSVER---ESSPKCPICRQQIRS
SVRIY----
>SPL2_NP_564653
M----------------S--SPERALLNLLTDIALSFDGAILGL----------------
-----TLAVSAVGSALKYASTNAALKKIKDAPEVSISDLRSLLPASEDKSETNDNRKSND
Q-------------------------------------RIVVVRGVVKPKISGD-----E
GYKNNNVLISPETGDKALIIQRTQTYVYSGWK-RLFQS----TGHRFML---ERSLRKHG
ADFTR-TVP-FVIVG--KDQQS----N------SSFVAVNMDGSR-QPLPLTTVYNRLQP
INS-S-----------------FLQAFLYPDYPVGL-----------------LDIEKIL
PPGKDITAVGI-------------YS-FN-NG-VPEIKSCQ-D-----------------
-------------------------LPYFL-----SEMTKDKMIEDLMEQTNFIFLGSVI
LGIVSVGILSYAAVRT--------WNKWKQWNHQ-RELPQRP------------------
------------------N-DSVV--D------------------DEPEDADE-------
-----IPDGELCVICVSRRRVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRG
SMRVYYS--
>Arabidopsis_lyrata subsp. lyrata_gi|297847824|ref|XP_002891793.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]gi|297337635|gb|EFH68052.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]
M----------------S--SPERALLNLLTDIALSFDGAILGL----------------
-----TLAISAVGSALKYASTNAALNKIKEAPEVSVADLRSLLPVSEDKSETNDHGK---
---------------------------------------IVVVRGVVKPKYSGD-----E
SHKNNNVLISPETGDKALIIQRTQTYVYSGWK-RLFQS----TGHRFML---ERSMRKHG
ADFMR-TVP-FVIVG--KDQQS----Q------STFLDVNMDGSR-QPLPLTTVYNRLQP
INS-S-----------------FLQAFLFPDYPVGL-----------------LDIEKIL
PPGKDITAVGI-------------CS-FN-NG-VPEIKSCQ-D-----------------
-------------------------LPYFL-----SEMTKDKMIEELMDQTSFIFFGSVI
LGIVSVGILSYAAVRT--------WNKWKQWNHQ-RDLPQRP------------------
------------------N-EPVV--D------------------DEPEDADE-------
-----IPDGELCVICVTRRRVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSIRG
SMRVYYS--
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------VIVDLDSST-HLLPLTTVYHKLQD
LHV-MS---------DEILPYAFLEAFF---LPVGH-----------------M-QKKIL
PLGKEINAIGL-------------CS-LQ-DG-NLHIKATQ-E-----------------
-------------------------LPYFL-----SEMTKGEMVKHLAYKTTILFWGGCI
IGIVSLGVLGYTSFRI--------WEWWKVRRQH-FSNAEVD------------------
------------------D-VYIG--------------------------NDE-------
-----IPSEQLCTICTMRRKKYACVPCGHLVCCHKCARSIQH---DSTARCPECRH----
---------
>Physcomitrella_patens subsp. patens_gi|168002970|ref|XP_001754186.1| predicted protein [Physcomitrella patens subsp. patens]gi|162694740|gb|EDQ81087.1| predicted protein [Physcomitrella patens subsp. patens]
----------------------------MLSWGGITLCLSGAAL-------------YCL
S-RNTGRDALNLRSIERV---------------NQLKDLAILLESA-CKVVP--------
--------------------------------------LVVTVAGRVGSETPIACEHSSL
RG---------------VILEETAEQHFLKHN-DTGSW----IQDSALMLSISK------
------EVP-WYLED-----------------GTGRVYIVGARNA-AGMELTVASEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRVERVL
PTGTNLTVVGE-------------AV-QDDRG-LIRIQKPN-K-----------------
-------------------------GPFYV-----TPKSLDQLVANLGRWSRWYKYMSLG
FTIVGIYFITSHAIKHF-------MERRRREALHRRVM-EAA------------------
------------------A-LRQASQREGGDGDMGDVTSHPLDDSVDTSQKKD-------
-----RGTPDLCVICLEQDYNAVFLPCGHMCCCTSCSAQLTS--------CPLCRRHIDK
FVKTYRH--
>Physcomitrella_patens subsp. patens_gi|168043801|ref|XP_001774372.1| predicted protein [Physcomitrella patens subsp. patens]gi|162674364|gb|EDQ60874.1| predicted protein [Physcomitrella patens subsp. patens]
----------------------------MLSWGGITLCFSGAAL-------------YCL
S-RNTGRDALHLMSVERV---------------NQLEDLAKLLESA-CTVVP--------
--------------------------------------WVVTVAGRVGAEAPIASEHSSL
RG---------------VILEKSAEQHFLKHN-DTGSW----IQHSALMLSISK------
------EVP-WYLED-----------------GTSRVFIIGARNA-AGMDLTVASESFEE
YGG-S----------LVRGTLDYLQGLK----MLGV-----------------KRVERVL
PTGTNLTVVGE-------------AV-QDDRG-LIRIQKPD-K-----------------
-------------------------GPFYV-----TPQSQDQLIENLGRWSRWCQYMSFG
LTLVGIYFITSRAIKHM-------LERWRREALLTRVM-EAA------------------
------------------A-LRKALQQEGVDEESDGVTAFPHDDNAHTAQKKD-------
-----GGMPSLCVICLEQDYNAVLVPCGHMCCCTSCSSQLSL--------CPLCRRHIDQ
VVKTFRH--
>Selaginella_moellendorffii_gi|302772771|ref|XP_002969803.1| hypothetical protein SELMODRAFT_231449 [Selaginella moellendorffii]gi|302806814|ref|XP_002985138.1| hypothetical protein SELMODRAFT_234706 [Selaginella moellendorffii]gi|300146966|gb|EFJ13632.
----------------------------MLPWGGITMCLSGVAL-------------YFL
S-RNSGRDAATLKAVRRV---------------DQLKDLAHLLDSA-CKAVP--------
--------------------------------------LVVTVAGRVGSETPIGCDHSSL
RC---------------VILEETAEQHFLKHN-DTGSW----IQDSALMLSNNK------
------EVP-WFLED-----------------ASGRVFIVGARGA-AGLELTIASEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRVERVL
PTGTALTVVGE-------------AI-KDDQG-TLRIQRPH-K-----------------
-------------------------GPFYV-----TPKSIDQLIANLGKWSRWYKYMSLG
FTLFGVFLVASHTIRYV-------MEKRRRAALNRRVM-EAA------------------
------------------A-RRRERKEHEGKAQVGEF------AKVETATKRD-------
-----GRLPDLCVICLEQEYNAVFVPCGHMCCCISCSAQLQN--------CPLCRRRIEQ
IVKTYRH--
>Medicago_truncatula_gi|144924893|gb|ABE86663.2| Zinc finger, RING-type [Medicago truncatula]
--------------------------MAMVPWRGVGCCLSAAAL-------------YLL
G-RTSGRDVDILKSVNRV---------------NQLRELAQLLDEE---IFP--------
--------------------------------------LVVAISGRVGSETPISCEFSGL
RG---------------VIIEETAEQHFLKHS-DAGSW----IQDSALMQSRSN------
------EVP-WYLDD-----------------GTGRVRVVGAQGA-TGFVLPVGSEAFEE
SGR-L----------PVRGTSDYVQGLK----MLGV-----------------KRIERVL
PVGTSLTVVGE-------------AA-KDDVG-TIRIQRPS-K-----------------
-------------------------GPFYV-----SPKTIDELIANIGRWARWYKYASAG
LTVLSVYMIANHAVRYI-------LERRRRNELEKRVL-AAA------------------
------------------A-KISGQDNGGEMD-----------DSLSDGAKRE-------
-----RAMPNLCVICLEQEYNSVFVPCGHMCCCTACSSHLTS--------CPLCRRQIEK
AVKTFRH--
>Glycine_max_gi|356535760|ref|XP_003536411.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like isoform 1 [Glycine max]
----------------------------MIPWGGLSCCLSAAAL-------------YLL
G-RSSGRDAEILKSVTRV---------------NQLKELAQLLDAE---ILP--------
--------------------------------------LIVTISGRVSSETPINCEFSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTDRVHVVGARGA-SGFALPVGIEAFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PVGTSLTVVGE-------------AA-KDDVG-AIRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDQLIANLGKWARWYKYASVG
LTVFGAYLIAKHAIRYI-------LERRRRSELQRRVL-AAA------------------
------------------A-KKSGQNNDVE--KA---------DSLSDGAKKD-------
-----RLMPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTN--------CPLCRRQIEK
VVKTFRH--
>Prunus_persica_ppa008230m_PACid_17644506
----------------------------MLPWGGLSCCLSAAAL-------------YLL
G-RSSGRDADILKSATRI---------------NQLKELAKLLDSE-C-ILP--------
--------------------------------------LVVAISGRVSSETPITCEFTGL
RG---------------VVVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTGRVHVVGARGA-TGFVLPVASEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTSLSVVGE-------------AV-KDDIG-TIRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDQLIANLGKWARWYKYASLG
LTVFGVYLVAKHSVQYI-------LERRRRWELQRRVL-AAA------------------
------------------A-KRSGEDNEGSNEKD---------DNVLDGSK---------
-----RLMPDLCVICLEHEYNAVFVPCGHMCCCTTCSLHLTN--------CPLCRRRIDQ
AVKTFRH--
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
----------------------------MLPWGGISCCLSAAAL-------------YLL
G-RSSGRDAELLKSVTRV---------------NQLKELAQLLEAE--HLLP--------
--------------------------------------LVVAISGRVSSDTPINCEFSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTGRAFVLGARNA-TNFILPVVSEVFEE
SGR-S----------LMRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTSLTVVGE-------------AA-KDDIG-TIRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDQLISNLGKWARWYKYASMG
LSIFGLYLVTKHVILYL-------MERRRRWELQKRVL-AAA------------------
------------------A-KRSSQENEGEIEKA---------SNGTDGTKRD-------
-----RSMPDLCVICLERDYNAVFVPCGHMCCCVACCSHLTN--------CPLCRRRIEL
VVKTFRH--
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
----------------------------MIPWGGISCCLSGAAL-------------YLL
G-RSSGRDAELLKTVTRV---------------NQLKELAHLLDSG-SKVLP--------
--------------------------------------FIVTVCGRVGSETPISCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTGRAFVVGARGA-TGFVLTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERLL
PTGTSLTVVGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDELIENLGKWARWYKYASFG
LTIFGTFLIAKRAIHYI-------LQRKRRWELHRRVL-AAA------------------
------------------AVKRSEQDNEGTNGQA---------ENGSDGTQRD-------
-----RVMPDLCVICLEQEYNAVFVPCGHMCCCIICSWHLTN--------CPLCRRRIDQ
VVRTFRH--
>Citrus_clementina_0.9_003846m_PACid_19263951
----------------------------MIPWGGISCCLSGAAL-------------YLL
G-RSSGRDAELLKTVTRV---------------NQLKELAHLLDSG-SKVLP--------
--------------------------------------FIVTVCGRVGSETPISCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTGRAFVVGARGA-TGFVLTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERLL
PTGTSLTVVGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDELIENLGKWARWYKYASFG
LTIFGTFLIAKRAIHYI-------LQRKRRWELHRRVL-AAA------------------
------------------AVKRSEQDNEGTNGQA---------ENGSDGTQRD-------
-----RVMPDLCVICLEQEYNAVFVPCGHMCCCIICSSHLTN--------CPLCRRRIDQ
VVRTFRH--
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
----------------------------MISWGGISCCLSGAAL-------------YLL
G-RSSGRDAELLKTVTRV---------------NQLEELAHLLDGG-SKVLP--------
--------------------------------------SIVSVSGRVGSETPISCEYSGL
RG---------------VIVEETTERHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTGCVFVVGARGA-TGFALTVGSEVFEE
SGR-S----------LVHGTLDYLQGLK----MLGV-----------------KRIGRLL
PTGTSLTVVGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDELLENLGKWARWYKYASFG
LTIFGAFLIAKRVIRCI-------LQRKRRWELRRRVL-AAA------------------
------------------AVQRSEQDNEGTNGQA---------ENGSDSTQRD-------
-----RVMPDLCVICLEQE-------CGHLCCCLICSSRLTN--------CPLCRRRIDQ
VVRTFRH--
>Citrus_clementina_0.9_014777m_PACid_19265048
----------------------------MISWGGISCCLSGAAL-------------YLL
G-RSSGRDAELLKTVTRV---------------NQLEELAHLLDGG-SKVLP--------
--------------------------------------SIVSVSGRVGSETPISCEYSGL
RG---------------VIVEETTERHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTGCVFVVGARGA-TGFALTVGSEVFEE
SGR-S----------LVHGTLDYLQGLK----MLGV-----------------KRIGRLL
PTGTSLTVVGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDELLENLGKWARWYKYASFG
LTIFGAFLIAKRVIRCI-------LQRKRRWELRRRVL-AAA------------------
------------------AVQRSEQDNEGTNGQA---------ENGSDSTQRD-------
-----RVMPDLCVICLEQEYNAVFFPCGHLCCCLICSSRLTN--------CPLCRRRIDQ
VVRTFRH--
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
----------------------------MLPWGGISCCLSAAAL-------------YLL
G-RSSGRDAEVLKSVTRV---------------NQLKELAKLLDIE-SNISP--------
--------------------------------------SVVSISGRVGSETPINCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTDRVYVVGARGA-SGFVLTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTSLTVVGE-------------AV-KDDIG-TVRVQRPH-K-----------------
-------------------------GPFYV-----SPRTIDELIGNLGKWARWYRYASVS
LTVFGAFLIAKHAIQYI-------MERRRRWELQSRVLAAAA------------------
------------------A-KRQGQDSEGSNGKA---------ENGSDNSKRE-------
-----RPVPDLCVICLEQEYNAVFLPCGHMCCCTTCSSHLTN--------CPLCRRRIEQ
VVKTFRH--
>Ricinus_communis_29703.m001546_PACid_16806242
------------------------------------------------------------
-----------LKSVTRV---------------NQLNELAKLLDIE-SKVLP--------
--------------------------------------LVVAISGRVGSETPINCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTDRTFVVGARGA-SGFALTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTSLSVIGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDELIGNLGKWARWYRYASVG
LTVFGVFLIAKHAIQYI-------MERRRRWELQSRVL-AAA------------------
------------------A-KRQGQDSDGSNGKA---------ENGSDSSKRE-------
-----RPIPDLCVICLEQEYNAVFLPCGHMCCCTACSSHLTN--------CPLCRRRIEQ
I--------
>Populus_trichocarpa_gi|118486812|gb|ABK95241.1| unknown [Populus trichocarpa]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MLSMSK------
------EVP-WYLDD-----------------GTDRVYVVGARGA-SGFVLTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTSLTVVGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYV-----SPKSIDELIGNLGKWARWYKYASLG
LTVFGAFLITKHVIRYI-------MERRRRWELQSRVL--AA------------------
------------------A-KRSGQDNEGSNDKA---------ENGSDGAKRE-------
-----RPIPDLCVICLEQEYNAVFLPCGHMCCCITCCSQLSN--------CPLCRRRIEQ
VVKTFRH--
>Vitis_vinifera_gi|225436896|ref|XP_002274008.1| PREDICTED: hypothetical protein [Vitis vinifera]gi|296086688|emb|CBI32323.3| unnamed protein product [Vitis vinifera]
----------------------------MIPWGGISCCLSAAAL-------------YLL
G-RSSGRDAEALKSVTRV---------------QQLKDLVQLLDTA-CKVLP--------
--------------------------------------LVVTVSGRVGSDTPIKCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------DTGRAYIVGARGA-TGLVLTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTPLTVVGE-------------AI-KDDVG-TIRIQRPH-K-----------------
-------------------------GPFYV-----SPKSIDHLVANLGKWARWYRYASLG
FTVFGVYLIAKSAIQYV-------MERKRCWELRKRVL-AAA------------------
------------------S-KKSGQDSEDPDEKD---------ENGSDNTKRD-------
-----RLMPDLCVICLEQEYNAVFVPCGHMCCCTMCSSQLTN--------CPLCRRRIEQ
VVRTFRH--
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
----------------------------MIPWGGLSCCLSAAAL-------------YVL
G-RSSGRDAEALKCVFRV---------------NQLKELAQLLDTE-CKVLP--------
--------------------------------------LVVTLCGRVGSDTPINCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTGRAYVLGARGA-SGFELNIASEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERLL
PVGSSLTVVGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYV-----SPKTIDQLISNLGKWARWYRYASYG
FTVFGICLIAKRAIQYI-------MERKRRWELQRRVL-AAV------------------
------------------A-RRSEQDTEGTDDKT---------KNAPDSAKRD-------
-----RSMPDLCVICLEQEYNSVFVPCGHMCSCTTCSLQLTN--------CPLCRRRIEQ
AVKTFRH--
>Tomato_Solyc06g084360.1.1 genomic_reference:SL2.31ch06 evidence_code:10F0H1E1IEG gene_region:4579148145798777 functional_description:"Baculoviral IAP repeatcontaining protein 3 (AHRD V1 * B0XJ37_CULQU); contains Interpro domain(s)  IPR001841  Zinc f
----------------------------MVPWAGLSCCLSAAAL-------------YLL
G-RSSGRDAEVLKSVTRV---------------NQLKDLAQLLDTA-SKVLP--------
--------------------------------------LVVTISGRVGSDTPINCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMCK------
------EVP-WYLDD-----------------GTGRTFIVGGRGA-TGLVLTVGSEAFEE
AGR-S----------FVRGTLDYLQGLK----MLGV-----------------KRIERVL
PVGTPLTVVGE-------------AV-KDDIG-TVRIQRPH-K-----------------
-------------------------GPFYI-----SHKTIDQLIANLGRWARWYKYASMG
FTAVGVYLLVKHTFHYM-------MERKRHWELRRRVL-AAA------------------
------------------A-KRAGDEDEGSDATA---------ENGVD--NKD-------
-----LLMPDLCVICLEQEYNSVFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQ
VVKTFRH--
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
----------------------------MIPVGGITCCLSAAAL-------------YLL
G-RSSGRDADLLKSVTRV---------------NQLKDLAQLLEAA-SKVLP--------
--------------------------------------LVVTVSGRVGSETPINCEYSGL
RG---------------VIVEQTAEQHFLKHN-DAGSW----IQDSALMLSMCK------
------EVP-WYLDD-----------------GTSRVHVVGARGA-TGLVLTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGSPLTVVGE-------------AV-KDDIG-SIRIQRPH-K-----------------
-------------------------GPFYV-----TDKTIDQLIANLGKWSRLYKYASMG
LTAFGVYLLAKHAFQYI-------MDRRRLWETRKRVL-DAA------------------
------------------A-KKAGQNEGALNGEA---------EIGSDSSNKE-------
-----RPIPELCVICLEQEYNSVFVQCGHMCCCMACSSHLTN--------CPL-------
---------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
----------------------------MLPWGGITCCMSAAAL-------------YLL
G-KSSGRDADILKSVTRL---------------NQLKDLAQMLDTA-CKVLP--------
--------------------------------------FVVTVSGRVGSDTPINCEHSGL
RG---------------VIVEEAAEQHFMKQN-DSGSW----IQDSAQMLAMTK------
------EVP-WYLDD-----------------GTGRVHVLGARGA-TGLVLTVASETFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTSLTVVGE-------------AV-KDDVG-TIWIQRPH-K-----------------
-------------------------GPFYV-----SPKSIDQLIANLGIWARLYKYASLG
FTAFGVYLIAKHAIRYI-------LERRRLLDFQRRVR-AAA------------------
------------------A-QRLEQDNDGTDGKA---------EDGPDVVNKD-------
-----RIMPDICVICLEQEYNAVFVPCGHLCCCTTCSSHLSN--------CPLCRRRIDQ
VVRTFRH--
>Arabidopsis_lyrata subsp. lyrata_gi|297840101|ref|XP_002887932.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]gi|297333773|gb|EFH64191.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]
----------------------------MIPWGGVTCCLSAAAL-------------YLL
G-RSSGRDAEVLKTVTRV---------------NQLKELAQLLELD-SKILP--------
--------------------------------------FIVAVSGRVGSETPIKCEHSGI
RG---------------VIVEETAEQHFLKHN-ETGSW----VQDSALMLSMSK------
------EVP-WFLDD-----------------GTSRVHVMGARGA-TGFALTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGIPLTIVGE-------------AV-KDDIG-EFRIQKPD-R-----------------
-------------------------GPFYV-----SPKSLDQLISNLGKWSRWYKYASMG
FTVFGVFLITKHVIDSV-------LERRRRRQLQKRVL-DAA------------------
------------------A-KRAELESEGSNGAR---------ESIADSTKKE-------
-----DAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDL
AVKTYRH--
>SP1
----------------------------MIPWGGVTCCLSAAAL-------------YLL
G-RSSGRDAEVLETVTRV---------------NQLKELAQLLELD-SKILP--------
--------------------------------------FIVAVSGRVGSETPIKCEHSGI
RG---------------VIVEETAEQHFLKHN-ETGSW----VQDSALMLSMSK------
------EVP-WFLDD-----------------GTSRVHVMGARGA-TGFALTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGIPLTIVGE-------------AV-KDDIG-EFRIQKPD-R-----------------
-------------------------GPFYV-----SSKSLDQLISNLGKWSRLYKYASMG
FTVLGVFLITKHVIDSV-------LERRRRRQLQKRVL-DAA------------------
------------------A-KRAELESEGSNGTR---------ESISDSTKKE-------
-----DAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTS--------CPLCRRRIDL
AVKTYRH--
>Thellungiella_halophila_gi|312283085|dbj|BAJ34408.1| unnamed protein product [Thellungiella halophila]
----------------------------MIPWGGVTCCLSAAAL-------------YLL
G-RSSGRDAEVLKTVTRV---------------SQLKELAQLLELDSSKLLP--------
--------------------------------------FIVAVSGRVGSETPIKCEHSGI
RG---------------VIVEETAEQHFLKHN-ETGSW----VQDSALMLSMSK------
------EVP-WFLDD-----------------GTSRVNVVGARGA-TGFALTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGMPLTIVGE-------------AV-KDDIG-DLRIQKPE-R-----------------
-------------------------GPFYV-----SPKSLDQLISNLGKWSRWYKYASMG
LTVFGVFLITKHVIDSV-------LERRRRRELQKRVL-DAA------------------
------------------A-KRAERESEGSNGTH---------ESVSDSTKKE-------
-----DAVPDLCVICLEQEYNAVFVPCGHMCCCTACSCHLTS--------CPLCRRRIDQ
VVKTYRH--
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
----------------------------MIPWGGVGCCLSAAAL-------------YLL
G-RSSGSDAEVLRSVARA---------------GSMKDLAAILDTA-SKVLP--------
--------------------------------------LVVAISGRVGSDTPLICQQSGM
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSAVMLSVSK------
------EVP-WYLDD-----------------GTGRVYVVGARSA-AGLILTVASEVFEE
SGR-T----------LVRGTLDYLQGLK----MLGV-----------------KRTERVL
PTGTSLTVVGE-------------AI-KDDVG-TIRIQRPH-K-----------------
-------------------------GPFYA-----SSKSIDQLIVNLGKWAKLYRIASMG
FATFGVFLLAKRALQHF-------LERRRRHELQKRVL-NAA------------------
------------------A-QRQAREAEGSKGTS----------DAEPNSKKD-------
-----QLVLDICVICLEQEYNAVFVPCGHMCCCVACSSHLTN--------CPLCRRRIDQ
AVRTFRH--
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
----------------------------MIPWGGVGCCLSAAAL-------------YLL
G-RSSGRDAEVLRSVARA---------------GSMKDLAAILDTA-SKVLP--------
--------------------------------------LVVAVSGRVSSDTPLICQQSGM
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSAVMLSVSK------
------EVP-WYLDD-----------------GTGRVYVVGARSA-AGLILTVASEVFEE
SGR-T----------LVRGTLDYLQGLK----MLGV-----------------KRTERVL
PTGTSLTVVGE-------------AI-RDDVG-TIRIQRPH-K-----------------
-------------------------GPFYV-----SPKSIDQLIMNLGKWAKLYRLASMG
FATFGVFLLAKRAIQHF-------LERKRRHELQKRVL-NAA------------------
------------------A-QRQAREAEGSNGSS----------DTEPNSKKD-------
-----QLVLDICVICLEQEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQ
AVRTFRH--
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
----------------------------MIPWGGVGCCLSAAAL-------------YLL
G-RSSGRDAEVLRSVARA---------------GSMKDLAAILDTA-SKVLP--------
--------------------------------------LVVAVSGRVGSDTPLICQQSGM
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSAVMLSVSK------
------EVP-WYLDD-----------------GTGRVYMVGARSA-AGLILTVASEVFEE
SGR-T----------LVRGTLDYLQGLK----MLGV-----------------KRTERVL
PTGISLTVVGE-------------AI-KDDVG-TIRIQRPH-K-----------------
-------------------------GPFYV-----SPKSIDQLIMNLGKWAKLYRLASMG
FATFGAFLLAKRAIQHF-------LERKRRHELQKRVL-NAA------------------
------------------A-QRQAREAEGSIGSS----------DTEPNSKKD-------
-----QLVLDICVICLEQEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQ
AVRTFRH--
>Setaria_italica_Si030396m_PACid_19714000
----------------------------MIPWGGVGCCLSAAAL-------------YLL
G-RSSGRDAEVLRSVARA---------------GSMKDLAAILDTA-SKVLP--------
--------------------------------------LVVAVSGRVGSDTPLICQQSGM
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSAVMLSVSK------
------EVP-WYLDD-----------------GTGRVYVVGARAA-AGLILTVASEVFEE
SGR-T----------LVRGTLDYLQGLK----MLGV-----------------KRTERVL
PTGTSLTVVGE-------------AI-KDDVG-TIRIQRPH-K-----------------
-------------------------GPFYV-----SPKSIDQLILNLGKWAKLYRLASMG
FATFSVFLLAKRAIQHF-------LERKRRHELQKRVL-NAA------------------
------------------A-QRQAREAEGGKGTS----------NTEPNSKKD-------
-----QLVLDICVICLEQEYNAVFVPCGHMCCCMACSSHLTN--------CPLCRRRIDQ
AVRTFRH--
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
----------------------------LIPWGGVGCCLSAAAL-------------YLL
G-RSSGRDAEVLRSVARA---------------GSTKDLAAILDTA-SKVLP--------
--------------------------------------LVVAVSGRVGSDTPLICQQSGM
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSAVMLSVSK------
------EVP-WYLDD-----------------GTGRVFVVGARGA-AGLVLTVASEVFEE
SGR-T----------LVRGTLDYLQGLK----MLGV-----------------KRTERVL
PTGTSLTVVGE-------------AI-KDDVG-TIRIQRPH-K-----------------
-------------------------GPFYV-----SPKSIDQLIMNLGKWAKLYQLASMG
FAAFGVFLLAKRALQHF-------LERKRRHELQKRVH-AAA------------------
------------------A-QRQAREAEGGNGTS----------DVDSNNKKD-------
-----QLVLDICVICLEQEYNAVFVPCGHMCCCMNCSSHLTN--------CPLCRRRIDQ
AVRTFRH--
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
----------------------------MVPWGGVGCCLSAAAL-------------YLL
G-RSSGRDAEVLRSVTRT---------------GSLKDLAAILDTA-SKVLP--------
--------------------------------------LVVAVSGRVSSDTPLICQQSGM
RG---------------VIVEEMAEQHFLKHN-DAGSW----IQDSAVMLSVSK------
------EVP-WYLDD-----------------GTGRVYVVGARAA-AGLVLTIASEVFEE
SGR-T----------LVRGTLDYLQGLK----MLGV-----------------KRTERVL
PTGTSLTVVGE-------------AI-KDDVG-TIRIQRPH-K-----------------
-------------------------GPFYA-----SPKSIDQLILNLGKWAKLYQLASMG
FAAFGVFLLAKRALQHF-------LQKKRQHELNKRVR-AAA------------------
------------------A-QRQAREAEGADGTS----------NGDPNSKKD-------
-----QLVLEICVICLEQEYNAVFVPCGHMCCCMNCSSHVTN--------CPLCRRRIDQ
AVRTFRH--
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
----------------------------MIPWGGITCCMSAAAL-------------YLL
G-RSSGRDADILRKVTRV---------------NQLKELAQLLDIE-SKIMP--------
--------------------------------------LIVAISGRVGSETPISCEYSGL
RG---------------VIVEETAEQHFLKHN-DAGSW----IQDSALMLSMSK------
------EVP-WYLDD-----------------GTARVFVVGARGA-TGFVLTVGSEVFEE
SGR-S----------LVRGTLDYLQGLK----MLGV-----------------KRIERVL
PTGTSLTVVGE-------------MT-LEQ----FRYEDRT-N-----------------
-------------------------GLFTCLQINGSPD------FQLGKWARWYKYASMG
LTFLGVFLIAKRSIEYV-------LERRRRRELQKRVL-AAA------------------
------------------A-KRSGQDNEGSNIIP---------ENGLDGAKRE-------
-----HLMPDLCVICLEQEYNAAFVPCGHMCCCMTCSSHLTN--------CPLCRRRIEQ
VLRTFRH--
>SPL1_NP_564745
----------------------------MIHLAGFTCCLGGVAL-------------YLL
T-RSTGR---DIKSITRV---------------YQLKDLEQLVEVE-SKVVP--------
--------------------------------------LIIAVSGDVGSETPIKCEHSYV
LG---------------VFLKRTAEQQVLRRN-WRFSW----VRNSTLMQPMTK------
------EVP-WYLDD-----------------GTGRVNVDVSQGE-LGLALTVGSDVFEK
AEPVS----------LVQGALGYLKGFK----ILGV-----------------RHVERVV
PIGTPLTVVGE-------------AV-RDGMG-NVRIQKPE-Q-----------------
-------------------------GPFYV-----TYIPLDQLISKLGDLSRRFKYASMG
LTVLGVILISKPVIEYILKRIEDTLERRRRQFALKRVV-DAA------------------
------------------A-RRAKPVTGG-------------------GTSRD-------
-----GDTPDLCVVCLDQKYNTAFVECGHMCCCTPCSLQLRT--------CPLCRERIQQ
VLKIYRH--
>Arabidopsis_lyrata subsp. lyrata_gi|297840639|ref|XP_002888201.1| hypothetical protein ARALYDRAFT_338432 [Arabidopsis lyrata subsp. lyrata]gi|297334042|gb|EFH64460.1| hypothetical protein ARALYDRAFT_338432 [Arabidopsis lyrata subsp. lyrata]
----------------------------MIHLAGFTCCLGGIAL-------------YLL
S-RNTGG---VVKSITRV---------------NHLKDLEQLVE---SKVFP--------
--------------------------------------LIIAVSGIVGSETPIKCEHSDI
LG---------------VFLKKTAEQQVLSRN-WRFSW----VRKSTLMQPMTK------
------EVP-WFLDD-----------------GTGRVNVAVSQGE-IGLALTVGSDVFEK
AEPVS----------LVQGTLDYLKGLK----ILGV-----------------RRVEHVV
PIGTPLTIVGE-------------AV-KDGMG-NVRIQKPE-Q-----------------
-------------------------GPFYV-----SYVPLDQLISKLGEWSRRFKYASMG
LTVVGVILLSKPVIKYILKKIEDTLERRRRQLLQKRVV----------------------
------------------------------------------------------------
------DVPDLCVICHDQKYNTAFVQCGHMCCCLTCSLRLTT--------CPLCREQIQQ
VLKIYRH--
>Arabidopsis_lyrata subsp. lyrata_gi|297821220|ref|XP_002878493.1| predicted protein [Arabidopsis lyrata subsp. lyrata]gi|297324331|gb|EFH54752.1| predicted protein [Arabidopsis lyrata subsp. lyrata]
----------------------------MIHLGGLTCCVSGGVL-------------YLL
S-MIPGSFFEMLNSVTRV---------------HQIKDLENLLQVE-GK-----------
---------------------------------------IIAVSG---------------
----------------------TAQQLFLKRN-WLFSW----VEDSKWMLPQAK------
------EVP-WYL-----------------------------------------------
--------------------------------MLGV-----------------RRTEHVL
PIGTPVTVVGE-------------AV-KDGIR-GFRIQKPE-K-----------------
-------------------------GLFFV-----SPVPLDKIISPMGKWLRRFKYVYVG
LTVVGVILISKPVIEYI-------LERRRGRLLRKRVA-DAA------------------
------------------A-KRAKLVARGLETQH---------ENSLDSTSRD-------
-----RDVLDLCVICLEQKYDATFVKCGHMCCCLTCSLHVKT--------CPICRRPIEH
VLKIDRR--
>Chlorella_variabilis_gnl|BL_ORD_ID|28282 jgi|ChlNC64A_1|139486|IGS.gm_25_00037
M----------------THFVSPMLFTSLLGYGGLATCALGGLL-------------ALV
G-LAKGKQARQLGAAVPV---------------ESLSELKQLLALVP-------------
--------------------------------------VIVAVTGRVLAPKPYRCEMSDT
DA---------------AIIEMR--EEKKSERRAGAEW----VGTTQLLRESVK------
------EAE-WGLVD----------------GSGTEVPVVAGRRA-DGDYLQMSGDRLIP
DNQ-T--------QGFLGRVVDEVQGSR----SVGV-----------------RQVERML
PVGTMLTAVGELATAVEHPSVFKGAV-RKGGK-MLVLRAPR-D-----------------
-------------------------GAFYL-----SRQPLPDVIASLQASSLACQQWAAA
FTAVGASMLVAAATQHA-------LTWVRQRRLR-QRVEKAM------------------
------------------R-ERAAAAAAAGGGGAAGAPAAS---------AAEPQPADVA
EAAEGGARPSLCVVCLERPCATVFPACGHMCACSRCSHGLRR--------CPICRSR-GA
PIRVYTA--
>Micromonas_sp._RCC299_gi|255086321|ref|XP_002509127.1|
MAGEGHVS-----------------------WPGVACIATGALFGYSSRAFKRNIPQYTD
F-RALERDLRAAASRARAEPTRRRHHPTHAAGENEIRARPAQADDDDDD-----------
----------------------------------APFGMLVAITGAARSDVLVPCVHAKR
PDGRTPERA--------IYVDAVTDQYLARQAVRSGEW----IRDCVVVAAMAK------
------EAPTWRLED-------PAGHGVNMHRATSMAQASDAARA-ADWHLSLVHDEFES
AGS-A-GAGSSLHSRIIANALDVNMGLN----VLGL-----------------RHRERVL
APGARLTAVGEVFIAPNGGPVG--VDGGDGAG-EIRLRRPRRRKGWRRHGRGWRRKGGTP
GDEKSAPGDGDGDGDDAAMSPRMDPNVFTV-----TQKPFDEYVDGFGSWGKVNAALGLG
FLGVGVALVLTKLWRAR-------LTRWREARFL-RRMREAE------------------
------------------EARRAAGGGEGDDGGDTA-------GTNTDTAGAK-------
-----VSPGETCVVCMYARSEVVYKECGHLVCCGVCAGRMDR--------CPLCRRR-SA
HMRVYRAGL
>Mulan_NP_078820
M----------------ESGGRPSLCQFILL---GTTSVVTAAL-------------YSV
Y-RQKARVSQELKGAKKV---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLALV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
VIPLYNS--
>Macaca_mulatta_gi|108998731|ref|XP_001096167.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 isoform 1 [Macaca mulatta]gi|355744987|gb|EHH49612.1| hypothetical protein EGM_00302 [Macaca fascicularis]
M----------------ENGGRPSLCQFILL---GTTSVVTAAL-------------YSV
Y-RQKARVSQELKGAKKV---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLALV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
VIPLYNS--
>Pan_troglodytes_gi|114554451|ref|XP_513168.2| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 isoform 2 [Pan troglodytes]
M----------------ESGGRPSLCQFILL---GTTSVVTAAL-------------YSV
Y-RQKARVSQELKGAKKV---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----NSQDFDSLLQRQESSVRLWKVLALV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
VIPLYNS--
>Pongo_abelii_gi|297666161|ref|XP_002811397.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like isoform 1 [Pongo abelii]gi|297666163|ref|XP_002811398.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like isoform 2 [Pongo
M----------------ESGGRPSLCQFILL---GTTSVVTAAL-------------YSV
Y-RQKARVSQELKGAKKV---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------MDVAVRVLKPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLALV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
VIPLYNS--
>Macaca_fascicularis_gi|75076710|sp|Q4R7G8.1|MUL1_MACFA RecName: Full=Mitochondrial ubiquitin ligase activator of NFKB 1; AltName: Full=E3 ubiquitin-protein ligase MUL1gi|67969201|dbj|BAE00954.1| unnamed protein product [Macaca fascicularis]
M----------------ENGGRPSLCQFILL---GTTSVVTAAL-------------YSV
Y-RQKAWVSQELKGAKKV---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLDS-VDLGLEAVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLALV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
VIPLYNS--
>Macaca_mulatta_gi|297282393|ref|XP_001096288.2| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 isoform 2 [Macaca mulatta]
M-----------------------------------------------------------
-------------GAKKV---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLALV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
VIPLYNS--
>Callithrix_jacchus_gi|296206921|ref|XP_002750428.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Callithrix jacchus]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------MVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VGVAVRVLKPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLALV
FGFATCAILFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRSLPE-----PKRCPICRQAITR
VIPLYNS--
>Nomascus_leucogenys_gi|332244904|ref|XP_003271606.1| PREDICTED: LOW QUALITY PROTEIN: mitochondrial ubiquitin ligase activator of NFKB 1-like [Nomascus leucogenys]
M----------------ESGGRPSLCQFILL---GTTSVVTAVL-------------YSV
Y-RQKAQVSQELKGAKKV---------------HLGEDLKTILSEAPGKCVP--------
---------------------------------------YAVIEGGLITXAQEFETSLVN
---------------------MTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLRPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQNFDSLLQRQESSVRLWKVLALV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITR
VIPLYNS--
>Sus_scrofa_gi|335290618|ref|XP_003356224.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Sus scrofa]
M----------------ESGGRPSLGQFILL---GTSSVVTAVL-------------YSV
Y-RQKAQVAQELKGAKRI---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLDS-LDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-AVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLMLV
FGFATCATLFFILRKQ--------YLQRQERLRL-KQLEEEF------------------
------------------R-EHEARLLSGAQP------------------EDR-------
-----ESLKSACVVCLSNFRSCVFLECGHVCSCAECYRALPE-----PKRCPICRQAITR
VIPLYNS--
>Canis_lupus familiaris_gi|73950663|ref|XP_544520.2| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Canis lupus familiaris]
M----------------ESGGRPSLGQFILL---GTSSVVTAVL-------------YSV
Y-RQKAQVAQELKGAKRI---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VGVAVRVLKPLDS-QDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLTLV
FGFATCAALFFILRKH--------YLQRQERQRL-RQMEKEF------------------
------------------Q-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLNSFKSCVFLECGHVCSCAECYRALPE-----PKRCPICRQEITR
VIPLYNS--
>Ailuropoda_melanoleuca_gi|301759711|ref|XP_002915681.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Ailuropoda melanoleuca]gi|281343041|gb|EFB18625.1| hypothetical protein PANDA_003719 [Ailuropoda melanoleuca]
M----------------ESGGRPSLGQFILL---GTSSVVTAVL-------------YSV
Y-RQKAQVAQELKGAKRI---------------HLGEDLKNILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VAVAVRVLKPLDS-QDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFESLLQRQDSSVRLWKVLTLV
FGFATCAALFFLLRRH--------YLQRQERRRL-QQMENEF------------------
------------------R-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSSFKSCVFLECGHVCSCAECYRALPE-----PKRCPICRQAITR
VIPLYNS--
>Oryctolagus_cuniculus_gi|291399366|ref|XP_002716047.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Oryctolagus cuniculus]
M----------------ESGGKPSLGQFILL---GTSSVVTAVL-------------YSV
Y-RQKAQVSRELKGAKKI---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLAPHEDG-------------VGVAVRVLKPLDA-VDLGLETVYEKFHP
SVQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NS-TVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWRVLALV
FGFATCATLFFILRRQ--------YLQRQERLRL-QQMQEEF------------------
------------------R-EHEAQLLSQARP------------------EDR-------
-----ESLKSACVVCLSNFKSCVFLECGHVCSCSECYRALPE-----PKRCPICRREVTR
VVPLYNS--
>Loxodonta_africana_gi|344283431|ref|XP_003413475.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Loxodonta africana]
M----------------ESGGRPSLSQFILL---GTSSVVTAIL-------------YSV
Y-RQKAQVSHELKGAKKI---------------HLGEDLKSILLEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLDS-VDLGLETVYEKFHP
SIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKILTLL
FGFAACATLFFILRKQ--------YLQRQERLRL-KQMQEEF------------------
------------------R-EREAQLLSRATP------------------EDR-------
-----ENLKSACVVCLSNFKSCVFLECGHVCSCTECYRALPE-----PKSCPICRQEITR
VVPLYNS--
>Cavia_porcellus_gi|348571241|ref|XP_003471404.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Cavia porcellus]
M----------------EGGGRPSVGQFILL---GTSSVVTAIL-------------YSV
Y-RQKARVAQELKGAKKM---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVVVRVLKPLDS-VDLGLETVYEKFHP
SVQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQKQESSVRLWKILALV
FGFATCASLFFILRKQ--------YLQRQERLRL-EQLQEEF------------------
------------------R-EHEAQLLSQASP------------------EDR-------
-----ESLKSACVVCLNSFKSCVFLECGHICSCHECYRALPE-----PKRCPICRREITR
VIPLYNS--
>Heterocephalus_glaber_gi|351713657|gb|EHB16576.1| Mitochondrial ubiquitin ligase activator of NFKB 1 [Heterocephalus glaber]
M----------------DSGGRPSLGQVILL---GTSSVVTAIL-------------YSV
Y-RQKAQVAQELKGAKKI---------------HLGEDLKNILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VDVAVRVLKPLES-VNLGLETVYEKFHP
SVQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATLTGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVKLWKILALV
FGFATCATLFFILRRQ--------YLQWQERLRL-EQMQEEF------------------
------------------R-EREAQLLSQASP------------------EDR-------
-----ESLKSACVMCLSSFKSCVFLECGHVCSCHECYRALPE-----PKKCPICRRKITR
VVPLYNS--
>Equus_caballus_gi|149694310|ref|XP_001504389.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Equus caballus]
M----------------EGGGRPSLGQVILL---GTSSVVTAIL-------------YSV
Y-RQKAQVAQELKGARRI---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGVVRSVKETLNSQFVD
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------SVP-FELVPHEDG-------------VDVAVRVLKPLDA-LDLGLETVYEKYHP
LVQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGAALTGVGE-------------LV-LD-NN-AVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLQGQESSARLWKVLTLV
FGFAACAALFFILWKQ--------YLQRQERLRL-KQMEEEF------------------
------------------R-EHEAQLLSRAKP------------------EDR-------
-----ESLKSACVVCLSNFKACVFLECGHVCSCAECYRALPE-----PKRCPICRQQITR
VVPLYSS--
>Mus_musculus_gi_18043560_gb_AAH19516.1
M----------------ESGSRPSLGQVILL---GTSSMVTAVL-------------YSI
Y-RQKAQVAQELKGAKKI---------------HLGEDLKGILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLSLQEHKMVWNRTTHLW----NDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VAVSVRVLKPLDS-VDLGLETVYEKFHP
SVQ-S----------FTDAIGHYISGER----PKGI-----------------QETEEML
KVGATLTGIGE-------------LV-LD-NN-AVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLHRQESSVRLWKVLVLV
FGFATCATLFFILRKQ--------YLHRQERLRQ-QQLQEEF------------------
------------------L-EHEAQLLSQASP------------------EDR-------
-----ESLKSACVVCLSNFKSCVFLECGHVCSCRQCYLALPE-----PKRCPICRREITR
VIPLYNS--
>Rattus_norvegicus_gi|157821595|ref|NP_001100165.1| mitochondrial ubiquitin ligase activator of NFKB 1 [Rattus norvegicus]gi|149024382|gb|EDL80879.1| similar to RIKEN cDNA 0610009K11 (predicted), isoform CRA_b [Rattus norvegicus]
M----------------ESGSRPSLGQVILL---GTSSMVTAVL-------------YSI
Y-RQKAQVAQELKGAKKI---------------HLGEDLKAILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VAMAVRVLKPLDS-VDLGLETVYEKFHP
SVQ-S----------FTDAIGHYISGER----PKGV-----------------QETEEML
KVGATLTGIGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------MQYYL-----SSQDFDSLLHRQESSVRLWKVLVLV
FGFATCATLFFILRKQ--------YLQRQERLRQ-QQLQDEF------------------
------------------L-EHEAHLLSQASP------------------EDR-------
-----ESLKSACVVCLSNFKSCVFLECGHVCSCRQCYLALPE-----PKRCPICRRGITR
VIPLYNS--
>Cricetulus_griseus_gi|344238869|gb|EGV94972.1| Mitochondrial ubiquitin ligase activator of NFKB 1 [Cricetulus griseus]
M-----------------------------------------------------------
---------QGLLGAKKI---------------HLGEDLKGILLEATGKCVP--------
---------------------------------------YAVIEGAVQSVKETLNSQFVE
NCKG-------------VIQRSTLQEHKMVWNRTTHLWCVSSNDYSKIIHQRTN------
------TVP-FDLVPHEDG-------------VAVAVRVLKPLDS-VDLGLETVYEKFHP
SVQ-S----------FADVIGHYISGER----PRGI-----------------LETEEML
KVGATITGVGE-------------LV-LD-NN-SVRLQPPK-Q-----------------
-------G-----------------LQYYL-----SSQDFDSLLHRQESSVRLWKILVLV
FGFATCTTLFFILRRQ--------YLQWQERLRQ-QQLQEEF------------------
------------------R-EHEAHLLSQALP------------------EDR-------
-----ESLKSSCVVCLSSFKSCVFLECGHVCSCRQCYLALPE-----PKRCPVCRREITR
MIPLYSS--
>Monodelphis_domestica_gi|126328467|ref|XP_001366550.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Monodelphis domestica]
M----------------DSGGRPSAIQLILL---GTSSAVAAAL-------------YSV
Y-RHKAQAARELKGAKKI---------------HLGEDLKSILIDAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCEKIIHQRTN------
------TVP-FDLVPHEDG-------------TGVAVRVLKPLDS-ADLGLETVYEKFHP
TIQ-S----------FTDVIGHYISGER----PKGI-----------------QETEEML
KVGATITGVGE-------------LV-LD-NN-SIRLQPPK-Q-----------------
-------G-----------------LQYYL-----SSQDFDTLLQRQESSVKLWKILTVI
FGFATCATLFFILRRQ--------YLHRRERQRM-KQMQEEF------------------
------------------R-QHEARVLRAASA------------------EER-------
-----ETLKNACVVCLSSTKSCVFLECGHVCSCSECYQALSE-----PKKCPICRQEIVR
VVPLYNS--
>Ornithorhynchus_anatinus_gi|345318835|ref|XP_001515759.2| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Ornithorhynchus anatinus]
M----------------ENGGRPSAGQLILL---GASSAITAIL-------------YSV
Y-RRKSQVAHSLKGAKKI---------------NLDRDLKNILMEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLSSQFLE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCEKVIHQRTN------
------TVP-FDLVPHEEG-------------TGVSIRVLKPLDS-VDLGLERVYEKFHP
AVQ-S----------FADVIGHYISGER----PKGV-----------------QETEEML
KVGAAVTGIGE-------------LV-LD-DS-SIRLQPPK-Q-----------------
-------G-----------------LHYYL-----SSQDFDTLLQRQESSVRLWKVLTAV
FGFATCATLFFLLRRQ--------YLRHRERRRA-KRMQEEF------------------
------------------R-ENEARLLSGAGG------------------EDR-------
-----EAPKDACVVCLGNVKTCVFLECGHVCSCTECYRALPQ-----PKRCPICRREISR
VVPLYNS--
>Bos_taurus_gi|300794078|ref|NP_001179111.1| mitochondrial ubiquitin ligase activator of NFKB 1 [Bos taurus]gi|297472296|ref|XP_002685772.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Bos taurus]gi|296490084|gb|DAA32197.1| mitoc
M----------------ESGGRPSLGQFILL---GTSSVVTAFL-------------YSV
Y-RQKAQVAQELKGAKRI---------------HLGEDLKSILSEAPGKCVP--------
---------------------------------------YAVIEGAVRSVKETLNSQFVE
NCKG-------------VIQRLTLQEHKMVWNRTTHLW----NDCSKIIHQRTN------
------TVP-FDLVPHEDG-------------AGVAVRVLKPLDA-VDLGLETVYERFHP
STP-S----------FTDVVGHYLSGER----PKGV-----------------QETEEML
KVGAPLTGVGE-------------LV-LD-HS-CVRLQPPKGP-----------------
-------G-----------------MQYYL-----SSQDFDSLLQRQESSVRLWKVLALV
FGFAACASLFFLLRKQ--------YLRR--RRER-QRPEEEF------------------
------------------R-ER-ACPEEDRPE------------------EDR-------
-----EGPKGACVVCLNNFRSCVFLECGHLCACTECYRALPE-----PRRCPICRQEISR
VVRLYNS--
>Gallus_gallus_gi|118108991|ref|XP_424579.2| PREDICTED: similar to Chromosome 1 open reading frame 166, partial [Gallus gallus]
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------VVRSVRDTLSSQFVE
NCKG-------------VGQRLTLQEHKMGWNRTTHLW----NDYEKIIHQRTN------
------TTA-FDLAPLEDG-------------TGVAVRVMKPLEA-AELSLETVHEKFHP
SVQ-S----------FPDVIGHYISGER----PKGI-----------------QETEQML
KVGAALTGVGE-------------LV-LD-NN-TIKLQPPK-Q-----------------
-------G-----------------LRYYL-----TSSDFDALLRKQESSAKLWKMLTIL
FGFATCAALFFLLRKQ--------YRHHRERQHL-KQMQEEF------------------
------------------R-QAQERLMREVNA------------------EGG-------
-----ETLKNACVICLSSAKSCVFLECGHVCSCTECYRALPE-----PKRCPICRQAITR
VVPLYNS--
>Meleagris_gallopavo_gi|326932512|ref|XP_003212360.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Meleagris gallopavo]
M---------------------------------GMRFGLTPLK-------------TNL
WSLDIACILQNPGGARRL---------------RLDGELRAVLLEAPGRCVP--------
---------------------------------------YAVIEGVVRTVKDTLSSQFVE
NCKG-------------VVQRLTLQEHKMVWNRTTHLW----NDYEKIIHQRTN------
------TTA-FDLAPLEDG-------------AGVAVRVMKPLEA-AELSLETVHEKFHP
SVQ-S----------FPDVIGHYISGER----PKGI-----------------QETEQML
KVGAALTGVGE-------------LV-LD-NN-TIKLQPPK-Q-----------------
-------G-----------------LRYYL-----TSADFDALLKKQESSAKLWKILTIL
FGFSTCAVLFFLLRKQ--------YRHHRERQHL-KQMQEEF------------------
------------------R-QAQERLMREVNA------------------EGG-------
-----EMLKNACVICLSSAKSCVFLECGHVCSCSECYQALPE-----PKRCPICRQAIIR
VVPLYNS--
>Taeniopygia_guttata_gi|224080452|ref|XP_002193021.1| PREDICTED: similar to mitochondrial ubiquitin ligase activator of NFKB 1 [Taeniopygia guttata]
M----------------EGGGRPSAAQAVLL---TASTALTALL-------------YSV
Y-RQKARVASGLEGARKV---------------RLDGDLRALLLEAPGRCVP--------
---------------------------------------YAVIEGVVRSVKDTLSSQFVE
NCKG-------------VVQRLTLREHKMVWNRTTHLW----NDYEKIIHQRTN------
------TTP-FDLVPAEDG-------------AGVTVRVMKPLEA-SELSLETVYEKFHP
SVQ-S----------FTDVLGHYISGER----SKGI-----------------QETEQML
KVGTALTGVGE-------------LV-LD-NA-TIKLQPPK-Q-----------------
-------G-----------------MPYYL-----SSLDFESLLHKQESGVRFWKILTVV
SGFATCAVLFFLLRKQ--------YRQLRERQRL-RQMQEEF------------------
------------------R-QAQERLM---NT------------------EGG-------
-----EILKNACVVCLSNTKSCVFLECGHICSCHECYLALPK-----PKKCPVCRQGITR
VVPLYNS--
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
M----------------ENGGRPSVGQVILL---TTSSAITALF-------------YSI
Y-RHKYRSVQTLKEAKKF---------------CLTDDLPAVLSDLPGKCVP--------
---------------------------------------YAVIEGAVTSVKEVLNSQYVE
NCKG-------------VIQRLSLKEHKMVWNRTTHLW----NDHEKIIHQRSN------
------TVP-FDLAPENPGE------------SGVSVRVLRPLEA-VDLGLETIYEKFHP
AVQ-S----------FSNILGHYMTGER----PKGV-----------------QETEEML
KIGATITGVGE-------------LV-LD-NK-TIKLQPPK-D-----------------
-------G-----------------MLFYL-----SSMDYEGLLEKQEVQMRWWRILSIV
FGVASCITLFFILRRK--------YRHYKEKQHL-KNLQREF------------------
------------------E-ESRARQRVQQEP------------------QNK-------
-----EEVQNPCSICLSTEKSCVFLECGHVCSCISCYQALPS-----PKKCPICRNFIDR
IVPLYNS--
>Xenopus_(Silurana) tropicalis_gi|301627377|ref|XP_002942853.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like [Xenopus (Silurana) tropicalis]
M----------------ETGGRPSVGQVILL---GASSAITALF-------------YSI
Y-RHKYRSVQALKEAKRF---------------SLTDDLQAVLSDLPGKCVP--------
---------------------------------------YAVIEGAVTSVKEVLSSQYVE
NCRG-------------VIQRLSLKEHKMVWNRTTHLW----NDHEKIIHQRSN------
------TVP-FDLAPEESGG------------AGVSVRVVRPLEA-VDLGLETVYEKFYP
AVQ-S----------FPNILGHYMTGER----PKGV-----------------QETEEML
KLGAAITGIGE-------------LV-LD-NK-TIKLQPPK-A-----------------
-------G-----------------LCYYL-----SGTDFPGLLERQEGQMRWWRILSIV
FGAATCVTLFFILRRQ--------YRHRKEKRQL-QNLQREF------------------
------------------E-ESRARQRVQQEQ------------------HNE-------
-----EEVRNPCAICLGKERSCVFLDCGHICSCYPCYQALPS-----PKKCPMCRNDIAR
VVPLYNS--
>Danio_rerio_gi_148922854_ref_NP_001092230.1
M----------------EASGKPSTAQIVLL---ATSSALTAVL-------------YTI
Y-KRKSSHVARLREAKKM---------------SLNPELKTILSEAPGKCVP--------
---------------------------------------YAVIEGVVRSVKETLNSQFVD
NCKG-------------VIQRLTLNEKKMVWNRTTNLW----NDCEKVIHQRTN------
------TVP-FDLAPHDDT-------------VPTTVRVLRPLDA-AELDLETTYENFHP
SQQ-S----------LTNVIGHFISGER----PQGI-----------------QETEEML
RLGASMTGVGE-------------LV-LD-NN-LVRLQPPK-K-----------------
-------G-----------------LRYFL-----SRLDYDTLLSKQEGHLRIWRVLTVL
LGLTACATFFYLLWRQ--------YVLRKERRKE-QSVLDEY------------------
------------------R-KWQSKRFQELHL------------------AKE-------
-----DVSPTACTICLNHERSCVFLECGHVCACEGCYRALPE-----PKKCPICRATIDR
IVSLYNS--
>Tetraodon_nigroviridis_gi|47229066|emb|CAG03818.1| unnamed protein product [Tetraodon nigroviridis]
M----------------DSGGKPSTSQMVVL---ATSSALAAFF-------------YSI
Y-RSKAMTVTRLKAAKKV---------------SIEQDLKGLLSETPGRCVP--------
---------------------------------------YAVIEGVVRSVKETLNSQFVE
NCKG-------------VIERLTLKEEKMVWNRTTHIW----NSTEKIIHQRTN------
------TVP-FTLASQDDD-------------VTASVRVIRPLEA-SDLDLETTYENFHP
SAH-S----------LSSVIGHFLSGER----PKGI-----------------HETEEML
RVGDSLTGVGE-------------LV-LD-NH-LIKLQPPK-P-----------------
-------G-----------------FCYFL-----TRMDYDGLLRRQSNSLRLWRILSLL
FGLAACSTLLFLLWRL--------YQHRRRSRKE-RSVLEEF------------------
------------------A-QQQKKRLRELNV------------------DES-------
-----CLSPSVCSICLSRQRSCVFLECGHVCACAQCCDALPS-----PKKCPICRAPIAR
VVTLYNS--
>Oreochromis_niloticus_gi|348503231|ref|XP_003439169.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Oreochromis niloticus]
M----------------DSSGKPSTAQIVVL---ATSSALTAFF-------------YSI
Y-RSRATIVARLKEAKKV---------------SLDQDLKTILSETPGRCIP--------
---------------------------------------YAVIEGVVRSVKETLNSQFVD
NCKG-------------VIERLTLKEEKMVWNRTTHIW----NSTEKIIHQRIN------
------TVP-FALGSHDDD-------------IAATVRVIRPLDA-AELDLETTYENFHP
TVQ-S----------LSSVIGHFISGER----PKGI-----------------HETEEML
RVGDSITGVGE-------------LV-LD-NN-LIKLQPPK-Q-----------------
-------G-----------------FCYFL-----TRLDYESLLRKQGNSVRLWKILAIV
FGMAACSTLLYILWKQ--------YIHRRQSKKE-KSILEEF------------------
------------------K-EQQRKRLRELNI------------------EES-------
-----SISPTSCTVCLSRDRSCVFLECGHVCTCSQCYEALPE-----PKKCPICRASIDR
VVPLYNS--
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
MEFLHESVALGVDLLILGLCAREY------------------------------------
--VHYKRTAKVLKAAPQY---------------NIDGDLKSVVERQRDKKIP--------
---------------------------------------YAVIRGTVTPIGVPLRSSLVP
SVSG-------------VLQIVKLHEHRVTRG-FAGFW----TEQHKLLHESAN------
------EMP-FELRN-----------------QSHGVEIVDALSA-AVLDVDVVYDNYEP
SNL-S----------LFDHVFGFFSGVR----QRGL-----------------QTTEEVL
REGSFLTAIGE-------------LE-LD-GD-TLRMQPSN-E-----------------
-------------------------GPLFL-----TTATKSTLIKRFEDAKTTTILKLVV
CSTISAILVAFIAKKL--------YRKRKQEREE-AKIRERL------------------
------------------D-TERRERRARSR-------------------PHT-------
-----LSQDQLCVVCSTNPKEIILLPCGHVCLCEDCAQKISV-------TCPVCRGSIVS
KAAAFIA--
>Consensus95
X----------------XXXXXXXXXXXXXXXXXXXXXXXXXXX-------------XXX
X-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--X
X-------------------------------------XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX----XXXXXXXXXXXXXXXXXX
XXXXX-XXX-XXXXXXXXXXXX----X-----XXXXXXXXXXXXX-XXXXXXXXXXXXXX
XXX-X----------XXXXXXXXXXXXXXXXXXXXX-----------------XXXEXXL
XXGXXXXXXGX-------------XX-XXXXX-XXXXXXXX-X-----------------
-------X-----------------XXXXX-----XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX-------XXXXXXXXXXXXXXXXXX------------------
------------------XXXXXXXXXXXXXXXXXX-------XXXXXXXXXX-------
-----XXXXXXCXXCXXXXXXXXXXXCGHXXXCXXCXXXXXX---XXXXXCPXCRXXXXX
XXXXXXX--
>Consensus100
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-----------------XXXXXXX
XXXXXXXXXGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXCXXCXXXXXXXXXXXCGHXXXCXXCXXXXXXXXXXXXXXCPXXXXXXXX
XXXXXXXXX
