>Physcomitrella_patens subsp. patens_gi|168019172|ref|XP_001762119.1| predicted protein [Physcomitrella patens subsp. patens]gi|162686836|gb|EDQ73223.1| predicted protein [Physcomitrella patens subsp. patens]
--MA--GHEDEL-CAALMRLALAGD-----------------------------------
---------GLVMGVGMTV---LAFRT-------------WIKFWSHSKALKDIKDTPVT
---RIADLR-TLVE-EPDVQAKEKIRTPEKISPPHQDIEVFATRSKVKMPSRPWMVERLP
IPSLETKQEKLVIVRGRVQTKAFVESEGDQRDA--EALIPLN-------VPEKAVFVERT
QTYVLTE-----------------------------------------------------
--------------------------------------------------MSNFLGW---
--------ITQKDLVKFTRQVVP-FVLA--ETE-AHWSFRPSDMAVYVHINLDESQ-HPI
PLVTVHHQ-LHPVPA-S----------SYTLFQAMFGRRYPVGLLDEEKILPLGAEITAV
GVLH------------TAPDG-TPVV-KSSK-R-L-------------------------
----------------PIFL-----TEFTREQLLVELASSTKVLFWMGVAVSTVAAGVLG
-YSLVKN--------WTRWKQRQQQRQSQ-NNSENRQNSTIE------------------
---------------------DEAENFEDIPDGELCVVCLLRRRRAAFIYCGHRVCCMGC
AERVEH---GANPRCPVCRQSVTGIVRVYDS--
>Oryza_sativa Japonica Group_gi|115451087|ref|NP_001049144.1| Os03g0177300 [Oryza sativa Japonica Group]gi|108706473|gb|ABF94268.1| C3HC4 zinc finger containing protein, putative, expressed [Oryza sativa Japonica Group]gi|113547615|dbj|BAF11058.1| Os03g
--MS--ARDRET-AVALARLAAALD-----------------------------------
---------GAVLGLGTAA---LAVAS-------------WVKYLAASGQLRRIASAPAA
---AIPDLR-SLLA-EYGGGGGDGDQPI--------------------------------
----------LAVVRGHVRAAPRG-----------KYLVPPG-------SGEHCVVAKHT
QLCLFNE-----------------------------------------------------
--------------------------------------------------WRGIFGWTFD
LHALF--FKSIKEQIITSFRWVP-FVLV--DPE---NM------TGMVHVKLDRAM-QPL
PLTTVYHK-LTPVDS-T----------PYTLFQTIIGNGYPIALLDEEKILPVGKEITAI
GYIR------------PH-KA-SVEI-SSCS-E-I-------------------------
----------------PFFL-----SDLTKDEMEAELSSRAKTLFWASVVLGTMSVCLLG
-FATYRS--------WKKIKERREARQAQ-EVFRQTTDE---------------------
---------------VTDDQ-SSDEEAGEMGDGQLCVICLRKRRKAAFIPCGHLVCCCKC
ALIVER---QFDPLCPMCRQDIRYMIRIYDN--
>SPL2_NP_564653
--MS--SPERAL-LNLLTDIALSFD-----------------------------------
---------GAILGLTLAV---SAVGS-------------ALKYASTNAALKKIKDAPEV
---SISDLR-SLLP-ASEDKSETNDNRKSNDQR---------------------------
----------IVVVRGVVKPKISGDEGYKNN----NVLISPE-------TGDKALIIQRT
QTYVYSG-----------------------------------------------------
--------------------------------------------------WKRLFQSTGH
RFML---ERSLRKHGADFTRTVP-FVIV--GKD-QQSN------SSFVAVNMDGSR-QPL
PLTTVYNR-LQPINS--------------SFLQAFLYPDYPVGLLDIEKILPPGKDITAV
GIYS------------FN-NG-VPEI-KSCQ-D-L-------------------------
----------------PYFL-----SEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILS
-YAAVRT--------WNKWKQWNHQRELP-QRPNDSVVD---------------------
---------------------DEPEDADEIPDGELCVICVSRRRVPAFIPCGHVVCCRRC
ASTVER---ELNPKCPVCLQSIRGSMRVYYS--
>Physcomitrella_patens subsp. patens_gi|168002970|ref|XP_001754186.1| predicted protein [Physcomitrella patens subsp. patens]gi|162694740|gb|EDQ81087.1| predicted protein [Physcomitrella patens subsp. patens]
--M---------------------------------------------------------
---------LSWGGITLCL---SGAAL-------------YCLSRNTGRDALNLRSIERV
--NQLKDLA-ILLE-SA------------C------------------------------
--KVVPL---VVTVAGRVGSETP--------------IACEH-------SSLRGVILEET
AEQHFLK-----------------------------------------------------
--------------------------------------------------------HN-D
TGSW----IQDSALMLSISKEVP-WYL---EDG-TG----------RVYIVGARNA-AGM
ELTVASEV-FEESGR-S----------LVRGTLDYLQGLKMLGVKRVERVLPTGTNLTVV
GEAV------------QDDRG-LIRI-QKPN-K-G-------------------------
----------------PFYV-----TPKSLDQLVANLGRWSRWYKYMSLGFTIVGIYFIT
-SHAIKHF-------MERRRREALHRRVM-EAAA-L---RQASQRE--GGDGDMGDVTSH
PLDDS----------------VDTSQKKDRGTPDLCVICLEQDYNAVFLPCGHMCCCTSC
SAQLTS--------CPLCRRHIDKFVKTYRH--
>Physcomitrella_patens subsp. patens_gi|168043801|ref|XP_001774372.1| predicted protein [Physcomitrella patens subsp. patens]gi|162674364|gb|EDQ60874.1| predicted protein [Physcomitrella patens subsp. patens]
--M---------------------------------------------------------
---------LSWGGITLCF---SGAAL-------------YCLSRNTGRDALHLMSVERV
--NQLEDLA-KLLE-SA------------C------------------------------
--TVVPW---VVTVAGRVGAEAP--------------IASEH-------SSLRGVILEKS
AEQHFLK-----------------------------------------------------
--------------------------------------------------------HN-D
TGSW----IQHSALMLSISKEVP-WYL---EDG-TS----------RVFIIGARNA-AGM
DLTVASES-FEEYGG-S----------LVRGTLDYLQGLKMLGVKRVERVLPTGTNLTVV
GEAV------------QDDRG-LIRI-QKPD-K-G-------------------------
----------------PFYV-----TPQSQDQLIENLGRWSRWCQYMSFGLTLVGIYFIT
-SRAIKHM-------LERWRREALLTRVM-EAAA-L---RKALQQE--GVDEESDGVTAF
PHDDN----------------AHTAQKKDGGMPSLCVICLEQDYNAVLVPCGHMCCCTSC
SSQLSL--------CPLCRRHIDQVVKTFRH--
>SP1
--M---------------------------------------------------------
---------IPWGGVTCCL---SAAAL-------------YLLGRSSGRDAEVLETVTRV
--NQLKELA-QLLE-LD------------S------------------------------
--KILPF---IVAVSGRVGSETP--------------IKCEH-------SGIRGVIVEET
AEQHFLK-----------------------------------------------------
--------------------------------------------------------HN-E
TGSW----VQDSALMLSMSKEVP-WFL---DDG-TS----------RVHVMGARGA-TGF
ALTVGSEV-FEESGR-S----------LVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIV
GEAV------------KDDIG-EFRI-QKPD-R-G-------------------------
----------------PFYV-----SSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLIT
-KHVIDSV-------LERRRRRQLQKRVL-DAAA-K---RAELESE--GSNGTR------
---ES----------------ISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTAC
SSHLTS--------CPLCRRRIDLAVKTYRH--
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
--L---------------------------------------------------------
---------IPWGGVGCCL---SAAAL-------------YLLGRSSGRDAEVLRSVARA
--GSTKDLA-AILD-TA------------S------------------------------
--KVLPL---VVAVSGRVGSDTP--------------LICQQ-------SGMRGVIVEET
AEQHFLK-----------------------------------------------------
--------------------------------------------------------HN-D
AGSW----IQDSAVMLSVSKEVP-WYL---DDG-TG----------RVFVVGARGA-AGL
VLTVASEV-FEESGR-T----------LVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVV
GEAI------------KDDVG-TIRI-QRPH-K-G-------------------------
----------------PFYV-----SPKSIDQLIMNLGKWAKLYQLASMGFAAFGVFLLA
-KRALQHF-------LERKRRHELQKRVH-AAAA-Q---RQAREAE--GGNGTS------
----D----------------VDSNNKKDQLVLDICVICLEQEYNAVFVPCGHMCCCMNC
SSHLTN--------CPLCRRRIDQAVRTFRH--
>SPL1_NP_564745
--M---------------------------------------------------------
---------IHLAGFTCCL---GGVAL-------------YLLTRSTGRD---IKSITRV
--YQLKDLE-QLVE-VE------------S------------------------------
--KVVPL---IIAVSGDVGSETP--------------IKCEH-------SYVLGVFLKRT
AEQQVLR-----------------------------------------------------
--------------------------------------------------------RN-W
RFSW----VRNSTLMQPMTKEVP-WYL---DDG-TG----------RVNVDVSQGE-LGL
ALTVGSDV-FEKAEPVS----------LVQGALGYLKGFKILGVRHVERVVPIGTPLTVV
GEAV------------RDGMG-NVRI-QKPE-Q-G-------------------------
----------------PFYV-----TYIPLDQLISKLGDLSRRFKYASMGLTVLGVILIS
-KPVIEYILKRIEDTLERRRRQFALKRVV-DAAA-R---RAKPVTG--G-----------
------------------------GTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPC
SLQLRT--------CPLCRERIQQVLKIYRH--
>Chlorella_variabilis_gnl|BL_ORD_ID|28282 jgi|ChlNC64A_1|139486|IGS.gm_25_00037
--MTHFVSPMLFTSL---------------------------------------------
---------LGYGGLATCA---LGGLL-------------ALVGLAKGKQARQLGAAVPV
--ESLSELK-QLLA-LV-------------------------------------------
-------PV-IVAVTGRVLAPKP--------------YRCEM-------SDTDAAIIEMR
EEKKSER-----------------------------------------------------
----------------------------------------------------------RA
GAEW----VGTTQLLRESVKEAE-WGL---VDG-SG---------TEVPVVAGRRA-DGD
YLQMSGDR-LIPDNQ-TQG--------FLGRVVDEVQGSRSVGVRQVERMLPVGTMLTAV
GELATAVEHPSVFKGAVRKGGKMLVL-RAPR-D-G-------------------------
----------------AFYL-----SRQPLPDVIASLQASSLACQQWAAAFTAVGASMLV
-AAATQHA-------LTWVRQRRLRQRVE-KAMRERAAAAAAAGG---GGAAGAPAASAA
EPQPA----------------DVAEAAEGGARPSLCVVCLERPCATVFPACGHMCACSRC
SHGLRR--------CPICRSRG-APIRVYTA--
>Micromonas_sp._RCC299_gi|255086321|ref|XP_002509127.1|
--MAGEGH----------------------------------------------------
---------VSWPGVACIA---TGALFGYSSRAFKRNIPQYTDFRALERDLRAAASRARA
EPTRRRHHPTHAAG-ENEIRARPAQADDDD------------------------------
--DDAPFGM-LVAITGAARSDVL--------------VPCVHAKRPDGRTPERAIYVDAV
TDQYLAR-----------------------------------------------------
--------------------------------------------------------QAVR
SGEW----IRDCVVVAAMAKEAPTWRL---EDP-AGHGVNMHRATSMAQASDAARA-ADW
HLSLVHDE-FESAG--SAGAGSSLHSRIIANALDVNMGLNVLGLRHRERVLAPGARLTAV
GEVFIAPNGGPVGVDGGDGAG-EIRL-RRPRRRKGWRRHGRGWRRKGGTPGDEKSAPGDG
DGDGDDAAMSPRMDPNVFTV-----TQKPFDEYVDGFGSWGKVNAALGLGFLGVGVALVL
-TKLWRAR-------LTRWREARFLRRMR-EAEEARRAAGGGEGDD------------GG
DTAGT----------------NTDTAGAKVSPGETCVVCMYARSEVVYKECGHLVCCGVC
AGRMDR--------CPLCRRRS-AHMRVYRAGL
>Mulan_NP_078820
--MESGGRPSLCQ-----------------------------------------------
---------FILLGTTSVV---TAAL--------------YSVYRQKARVSQELKGAKKV
--HLGEDLK-SILS-EA-------------------------------------------
---PGKCVP-YAVIEGAVRSVKE-------------TLNSQF------VENCKGVIQRLT
LQEHKMV-----------------------------------------------------
--------------------------------------------------------WNRT
THLW----NDCSKIIHQRTNTVP-FDLVPHEDG-VD---------VAVRVLKPLDS-VDL
GLETVYEK-FHPSIQ-S----------FTDVIGHYISGERPKGIQETEEMLKVGATLTGV
GELV------------LD-NN-SVRL-QPPK-QGM-------------------------
----------------QYYL-----SSQDFDSLLQRQESSVRLWKVLALVFGFATCATLF
-FILRKQ--------YLQRQERLRLKQMQ-EEFQEHEAQLLSRAKP--------------
--------------------------EDRESLKSACVVCLSSFKSCVFLECGHVCSCTEC
YRALPE-----PKKCPICRQAITRVIPLYNS--
>Sus_scrofa_gi|335290618|ref|XP_003356224.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Sus scrofa]
--MESGGRPSLGQ-----------------------------------------------
---------FILLGTSSVV---TAVL--------------YSVYRQKAQVAQELKGAKRI
--HLGEDLK-SILS-EA-------------------------------------------
---PGKCVP-YAVIEGAVRSVKE-------------TLNSQF------VENCKGVIQRLT
LQEHKMV-----------------------------------------------------
--------------------------------------------------------WNRT
THLW----NDCSKIIHQRTNTVP-FDLVPHEDG-VD---------VAVRVLKPLDS-LDL
GLETVYEK-FHPSIQ-S----------FTDVIGHYISGERPKGIQETEEMLKVGATLTGV
GELV------------LD-NN-AVRL-QPPK-QGM-------------------------
----------------QYYL-----SSQDFDSLLQRQESSVRLWKVLMLVFGFATCATLF
-FILRKQ--------YLQRQERLRLKQLE-EEFREHEARLLSGAQP--------------
--------------------------EDRESLKSACVVCLSNFRSCVFLECGHVCSCAEC
YRALPE-----PKRCPICRQAITRVIPLYNS--
>Canis_lupus familiaris_gi|73950663|ref|XP_544520.2| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Canis lupus familiaris]
--MESGGRPSLGQ-----------------------------------------------
---------FILLGTSSVV---TAVL--------------YSVYRQKAQVAQELKGAKRI
--HLGEDLK-SILS-EA-------------------------------------------
---PGKCVP-YAVIEGAVRSVKE-------------TLNSQF------VENCKGVIQRLT
LQEHKMV-----------------------------------------------------
--------------------------------------------------------WNRT
THLW----NDYSKIIHQRTNTVP-FDLVPHEDG-VG---------VAVRVLKPLDS-QDL
GLETVYEK-FHPSIQ-S----------FTDVIGHYISGERPKGIQETEEMLKVGATLTGV
GELV------------LD-NN-SVRL-QPPK-QGM-------------------------
----------------QYYL-----SSQDFDSLLQRQESSVRLWKVLTLVFGFATCAALF
-FILRKH--------YLQRQERQRLRQME-KEFQEHEAQLLSRAKP--------------
--------------------------EDRESLKSACVVCLNSFKSCVFLECGHVCSCAEC
YRALPE-----PKRCPICRQEITRVIPLYNS--
>Loxodonta_africana_gi|344283431|ref|XP_003413475.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Loxodonta africana]
--MESGGRPSLSQ-----------------------------------------------
---------FILLGTSSVV---TAIL--------------YSVYRQKAQVSHELKGAKKI
--HLGEDLK-SILL-EA-------------------------------------------
---PGKCVP-YAVIEGAVRSVKE-------------TLNSQF------VENCKGVIQRLT
LQEHKMV-----------------------------------------------------
--------------------------------------------------------WNRT
THLW----NDYSKIIHQRTNTVP-FDLVPHEDG-VD---------VAVRVLKPLDS-VDL
GLETVYEK-FHPSIQ-S----------FTDVIGHYISGERPKGIQETEEMLKVGATLTGV
GELV------------LD-NN-SVRL-QPPK-QGM-------------------------
----------------QYYL-----SSQDFDSLLQRQESSVRLWKILTLLFGFAACATLF
-FILRKQ--------YLQRQERLRLKQMQ-EEFREREAQLLSRATP--------------
--------------------------EDRENLKSACVVCLSNFKSCVFLECGHVCSCTEC
YRALPE-----PKSCPICRQEITRVVPLYNS--
>Mus_musculus_gi_18043560_gb_AAH19516.1
--MESGSRPSLGQ-----------------------------------------------
---------VILLGTSSMV---TAVL--------------YSIYRQKAQVAQELKGAKKI
--HLGEDLK-GILS-EA-------------------------------------------
---PGKCVP-YAVIEGAVRSVKE-------------TLNSQF------VENCKGVIQRLS
LQEHKMV-----------------------------------------------------
--------------------------------------------------------WNRT
THLW----NDYSKIIHQRTNTVP-FDLVPHEDG-VA---------VSVRVLKPLDS-VDL
GLETVYEK-FHPSVQ-S----------FTDAIGHYISGERPKGIQETEEMLKVGATLTGI
GELV------------LD-NN-AVRL-QPPK-QGM-------------------------
----------------QYYL-----SSQDFDSLLHRQESSVRLWKVLVLVFGFATCATLF
-FILRKQ--------YLHRQERLRQQQLQ-EEFLEHEAQLLSQASP--------------
--------------------------EDRESLKSACVVCLSNFKSCVFLECGHVCSCRQC
YLALPE-----PKRCPICRREITRVIPLYNS--
>Monodelphis_domestica_gi|126328467|ref|XP_001366550.1| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1 [Monodelphis domestica]
--MDSGGRPSAIQ-----------------------------------------------
---------LILLGTSSAV---AAAL--------------YSVYRHKAQAARELKGAKKI
--HLGEDLK-SILI-DA-------------------------------------------
---PGKCVP-YAVIEGAVRSVKE-------------TLNSQF------VENCKGVIQRLT
LQEHKMV-----------------------------------------------------
--------------------------------------------------------WNRT
THLW----NDCEKIIHQRTNTVP-FDLVPHEDG-TG---------VAVRVLKPLDS-ADL
GLETVYEK-FHPTIQ-S----------FTDVIGHYISGERPKGIQETEEMLKVGATITGV
GELV------------LD-NN-SIRL-QPPK-QGL-------------------------
----------------QYYL-----SSQDFDTLLQRQESSVKLWKILTVIFGFATCATLF
-FILRRQ--------YLHRRERQRMKQMQ-EEFRQHEARVLRAASA--------------
--------------------------EERETLKNACVVCLSSTKSCVFLECGHVCSCSEC
YQALSE-----PKKCPICRQEIVRVVPLYNS--
>Ornithorhynchus_anatinus_gi|345318835|ref|XP_001515759.2| PREDICTED: mitochondrial ubiquitin ligase activator of NFKB 1-like [Ornithorhynchus anatinus]
--MENGGRPSAGQ-----------------------------------------------
---------LILLGASSAI---TAIL--------------YSVYRRKSQVAHSLKGAKKI
--NLDRDLK-NILM-EA-------------------------------------------
---PGKCVP-YAVIEGAVRSVKE-------------TLSSQF------LENCKGVIQRLT
LQEHKMV-----------------------------------------------------
--------------------------------------------------------WNRT
THLW----NDCEKVIHQRTNTVP-FDLVPHEEG-TG---------VSIRVLKPLDS-VDL
GLERVYEK-FHPAVQ-S----------FADVIGHYISGERPKGVQETEEMLKVGAAVTGI
GELV------------LD-DS-SIRL-QPPK-QGL-------------------------
----------------HYYL-----SSQDFDTLLQRQESSVRLWKVLTAVFGFATCATLF
-FLLRRQ--------YLRHRERRRAKRMQ-EEFRENEARLLSGAGG--------------
--------------------------EDREAPKDACVVCLGNVKTCVFLECGHVCSCTEC
YRALPQ-----PKRCPICRREISRVVPLYNS--
>Danio_rerio_gi_148922854_ref_NP_001092230.1
--MEASGKPSTAQ-----------------------------------------------
---------IVLLATSSAL---TAVL--------------YTIYKRKSSHVARLREAKKM
--SLNPELK-TILS-EA-------------------------------------------
---PGKCVP-YAVIEGVVRSVKE-------------TLNSQF------VDNCKGVIQRLT
LNEKKMV-----------------------------------------------------
--------------------------------------------------------WNRT
TNLW----NDCEKVIHQRTNTVP-FDLAPHDDT-VP---------TTVRVLRPLDA-AEL
DLETTYEN-FHPSQQ-S----------LTNVIGHFISGERPQGIQETEEMLRLGASMTGV
GELV------------LD-NN-LVRL-QPPK-KGL-------------------------
----------------RYFL-----SRLDYDTLLSKQEGHLRIWRVLTVLLGLTACATFF
-YLLWRQ--------YVLRKERRKEQSVL-DEYRKWQSKRFQELHL--------------
--------------------------AKEDVSPTACTICLNHERSCVFLECGHVCACEGC
YRALPE-----PKKCPICRATIDRIVSLYNS--
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
--MEFLHE----------------------------------------------------
---------SVALGVDLLI---LGLC--------------AREYVHYKRTAKVLKAAPQY
--NIDGDLK-SVVE-RQ-------------------------------------------
---RDKKIP-YAVIRGTVTPIGV-------------PLRSSL------VPSVSGVLQIVK
LHEHRVT-----------------------------------------------------
---------------------------------------------------------RGF
AGFW----TEQHKLLHESANEMP-FEL---RNQ-SH----------GVEIVDALSA-AVL
DVDVVYDN-YEPSNL-S----------LFDHVFGFFSGVRQRGLQTTEEVLREGSFLTAI
GELE------------LD-GD-TLRM-QPSN-E-G-------------------------
----------------PLFL-----TTATKSTLIKRFEDAKTTTILKLVVCSTISAILVA
-FIAKKL--------YRKRKQEREEAKIR-ERLDTERRERRARSRPHT------------
-----------------------------LSQDQLCVVCSTNPKEIILLPCGHVCLCEDC
AQKISV-------TCPVCRGSIVSKAAAFIA--
>Cyanothece_sp_PCC_7425 gi|220906503|ref|YP_002481814.1| unnamed protein product [Cyanothece sp. PCC 7425]
--MG--------------------------------------------------------
---------LAIVGAILLV---TGGIL-------------YFVQRHYQQKLYSIKLARKT
TVAELKQLADQVGA-EI------------G------------------------------
--Q-GSLRE-YVKLSGQIKCDTP--------------LISEL-------KQVPCVYYQMQ
VEREYEE--------------RLTERDNDGETR---------------------------
------------------------------------------------------------
-----EKTQRGSETIASNSQSTP-FFL---QDQ-SG----------AIEVD--PSG-AAI
ETVQVLNE-FRPEA---GSARISFGNFSLSVGGSFPAGRETIGYRYRESILPPDRRILIV
ATAS------------DS-SG-ILSL-QKPVEKRQ-------------------------
----------------KFII-----SLKSEDHLAQSTQQTATYTFYGMIACLGLGAILLV
-VGLIIR-----------------------------------------------------
------------------------------------------------------------
---------------------------------
>Acaryochloris_marina_MBIC11017 gi|158336842|ref|YP_001518016.1| unnamed protein product [Acaryochloris marina MBIC11017]
------------------------------------------------------------
---------MKIIGIILIV---IGIIL-------------FFVYSNLKRKLASLRQARPA
SIAELNHLASEIAL-EM------------G------------------------------
--S-GSWRD-YVKLRGTIQCDQP--------------LISEL-------KQMPCVHYNMT
VVREYEE--------------QVTERDSDDKVV---------------------------
------------------------------------------------------------
-----TKTQRGSETLSQNRESVP-FFL---QDD-TG----------EIWVE--PEG-AQI
ETVRVLDE-FSPEQ--PSGGQLSFGGFSLSL-SSAETGRQTIGYRYQESVLPVQRQVFVV
AQVS------------DF-NQ-SLVL-ENPTTKGQ-------------------------
----------------RFVI-----SLKSEEALAQTTQTSVTYAFYGMISTLVVGGLLVI
-FGLLSA-----------------------------------------------------
------------------------------------------------------------
---------------------------------
>Cyanothece_sp_PCC_7424 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424]
------------------------------------------------------------
---------MILIGIICLI---VGVIL-------------LFFWRSNRSKLRNLRLASAS
TISSLQTIANQIAE-EI------------G------------------------------
--G-GSLRE-YVKIRGVIECDRP--------------LISQL-------KQEPCVYYSMT
VTWEYNE--------------EVIKQDNEGKTI---------------------------
------------------------------------------------------------
-----REKERKSETVAQNSRSIP-FTL---QDS-TG----------EIRVN--PER-AEI
ETVKVLEE-FRPEN--FSGGSLTFGNFSINL-PSFEERRQTIGYRYQEEILPIGRQILVI
GTAT------------DE-EG-MITI-RKPTEKGQ-------------------------
----------------RYFI-----SLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLV
-AGVLRG-----------------------------------------------------
------------------------------------------------------------
---------------------------------
>Synechococcus_elongatus_PCC_7942 gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococcus elongatus PCC 7942]
--MA--------------------------------------------------------
---------AIILAAITAI---AAIVL-------------YFVRRHYRFKLQSLLLAQPA
TSLQLKEIAEHVAG-EI------------G------------------------------
--G-GNLRQ-YVKMWGAIEVEQP--------------LVSEL-------KQESCVYYCST
VSREYEE--------------RVRKEDSEGKVT---------------------------
------------------------------------------------------------
-----WTTERRSETISQNRRSTP-FYL---RDQ-HG----------RVRVE--PES-AAI
ATIPVLDE-FRPDS---SASSLIFGAFSLSL-STTAGLGKTLGYRYREEILPCDRSVLVV
GAAS------------DE-TG-ELTL-GPSSEARQ-------------------------
----------------QFFI-----ALKPETALLQEVKQTIQWLTIGAIASVVVTVVAAI
-AALL-------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Thermosynechococcus_elongatus_BP-1 gi|22298202|ref|NP_681449.1| unnamed protein product [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
---------MGVLGGILLV---IAVLV-------------LCGWWDYRLKVRALNLAVSS
TPAQLHELQRRVAQ-EI------------G------------------------------
--G-GYLQE-YVKISGQIVADRP--------------LVSEL-------KRLPCVHYRLC
VSRVYKT--------------TESHEDGS-------------------------------
------------------------------------------------------------
-----SETKYRHEILSSNTQTIP-FRL---RDG-DM----------EIYVD--PRG-AEI
ETVQVLNE-FQEDN---NTTHLAFGRFQMDL-SSLPKHSDTVGYRYEEWILPVNQQVFVV
GTAS------------DE-RG-KLRI-RRPHQKGQ-------------------------
----------------LFFI-----SLESEENLTKKVRQYARASIIAAGVFSGLGILLIL
-L----------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Thermosynechococcus_elongatus_BP-1 gi|22297743|ref|NP_680990.1| unnamed protein product [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
---------MGVFAHLCLT---GSAFL-------------FALEGYYRLQLRGIKVASPS
TIGELEKFQQQVAQ-EM------------G------------------------------
--S-GSWRE-YVQVVGQVTTSQP--------------LLSEV-------KRIPCVYYKTI
ISREYEK-----------------------------------------------------
------------------------------------------------------------
-----EGSDRPSEIIGRHEQSTL-FLL---RDH-QG----------EIEVN--PFG-AEI
EAVQVLDE-LRPADQ-PHAFALSLGFLSFNW---HFGKGTTLGYRYQEWVLPLGQPVSVV
GMAS------------DQ-GG-VLRL-QKPQNRGQ-------------------------
----------------KFII-----SLSFEDPLIQQYKQQKRKMTYASLGATLCGVCGLV
-LALF-------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Rubrobacter_xylanophilus_DSM_9941 gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941]
--MVGTVV----------------------------------------------------
---------FLLVGVVLCV---AGGVL-------------LYFRRRMLGKAELMRRTRTS
GAAGVSALSPGT------------------------------------------------
----------LVEVKGTLRCERP--------------LQSEM-------AKERCAYYSSK
VVREYLE--------------RDRGDGA--------------------------------
------------------------------------------------------------
-----PGSGRRSEVLARSERFAP-FVV---EDD-TG----------GVPVS--AEG-AEV
DAKKVVDR-FERGAG-AAGLSVTIGGATIDL----GGGERTLGYRHTEEILPVDAPVYVL
GAVR------------RD-GG----I-GPPEEGAG-------------------------
----------------RFVV-----SWRSEEALGESLGRGARLLGLIALGLFLAGAAFLA
VGAAAALGYLQFR-----------------------------------------------
------------------------------------------------------------
---------------------------------
>Sphaerobacter_thermophilus_DSM_20745 gi|269838375|ref|YP_003320603.1| hypothetical protein Sthe_2360 [Sphaerobacter thermophilus DSM 20745]
--MGTSGV----------------------------------------------------
---------LLIIGLVAAG---IGAVL-------------LFIGRRIQAKTDLLAKVPTV
DASEVASL---IPG-EM-------------------------------------------
-----------IEVKGVIRCDTP--------------LTAEL-------AQRACVYYSSR
VVREYEY--------------RRRNAKGE-------------------------------
------------------------------------------------------------
-----TVRSRRSETVAHNEQFTP-FYV---EDS-SG----------RVLVD--PEG-AEV
DAQKLVDR-FERNPG-ALGPTISLGGISLNL----GGDDGTIGYRYQEHVLPVDIPVYVL
GVVQ------------E--GG-TIGR-PPAALKGR-------------------------
----------------RFII-----SYRAEEALRESWGKKARWLGISAVALFALAVILFV
-VAVGMLVA---------------------------------------------------
------------------------------------------------------------
---------------------------------
>Thermomicrobium_roseum_DSM_5159 gi|221632287|ref|YP_002521508.1| unnamed protein product [Thermomicrobium roseum DSM 5159]
------------------------------------------------------------
---------MIFVTLCFLITAGVGLVC-------------LIGYRRTRQQLRLLRLVATC
PIAELHE---RIPG-EM-------------------------------------------
-----------VEITGTVHCATP--------------LRSEY-------TGQPCVYYRTV
TERVVER--------------HGRSKKG--------------------------------
------------------------------------------------------------
--------GRLSEVVAQNEQRIA-FEV---DDG-TG----------RVAVD--PVG-AEI
DGRKLLDR-FEPVEN-GEGATLRIAGMSVEV---RAAEWRTLGYRKIEEAVLVGYPVYVL
GVLQ------------DD-GS----I-GRPPEGSRLR-----------------------
----------------EFLI-----SARSEEELATSLRRRSYLFLAGAITSFVVAGMLLI
-ALLVQSVISIS------------------------------------------------
------------------------------------------------------------
---------------------------------
>Chloroflexus_aurantiacus_J-10-fl gi|163846705|ref|YP_001634749.1| hypothetical protein Caur_1130 [Chloroflexus aurantiacus J-10-fl]
------------------------------------------------------------
---------MIVGGVLLLV---LAVIF-------------FFVARANAGKLQALNAVDTY
DTATLSAIHRRITT-AL------------G------------------------------
--A-HDFAQ-PCEVMGLIECATP--------------LTGPV-------SGQALVAYLYT
THREYEE--------------RITTQES-GRST---------------------------
------------------------------------------------------------
-----TRIERRSEQLEQNERRVP-FTI---RDD-TG----------QVLVV--PDG-AKI
DLIETANR-FLETP------------------QPWTGATRTLGQRQFERGLEVGIRVFVS
GTAI------------DQ-NG-QVVIARHPTNSKQ-------------------------
----------------TFII-----SRKSEHELANSAATWARNMRYAAIASGVIGLALVV
-GGV-----LVSG-----------------------------------------------
------------------------------------------------------------
---------------------------------
>Chloroflexus_sp._Y-400-fl gi|222524514|ref|YP_002568985.1| hypothetical protein Chy400_1238 [Chloroflexus sp. Y-400-fl]
------------------------------------------------------------
---------MIVGGVLLLV---LAVIF-------------FFVARANAGKLQALNAVDTY
DTATLSAIHRRITT-AL------------G------------------------------
--A-HDFAQ-PCEVMGLIECATP--------------LTGPV-------SGQALVAYLYT
THREYEE--------------RITTQES-GRST---------------------------
------------------------------------------------------------
-----TRIERRSEQLEQNERRVP-FTI---RDD-TG----------QVLVV--PDG-AKI
DLIETANR-FLETP------------------QPWTGATRTLGQRQFERGLEVGIRVFVS
GTAI------------DQ-NG-QVVIARHPTNSKQ-------------------------
----------------TFII-----SRKSEHELANSAATWARNMRYAAIASGVIGLALVV
-GGV-----LVSG-----------------------------------------------
------------------------------------------------------------
---------------------------------
>@Synechococcus_sp_JA_2_3B_a2_13@ 637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba(2-13)]
--MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPP
PERKAFMNWLMLLGLLCLP---ASLFS-------------FVEYLRSQRLVQQLSATRLL
KIAELRHLGQTNPQ-AK------------G------------------------------
--A-----N-LAQVYGRVVCDRP--------------LVSEL-------SRQPCVYYKSE
ISWEYDEIECYRRYLNSRGDVAYSERISEGEYQNALRLGSRAKSYPGEMVGKKPGLGYSD
SGSFQKRVDPDYSNSFPQKPNPGYPQQLGSPGYPQKSPFSEVSSPQKHYANVYYDPSTGR
EYLLERETRTRDETLHSVVRQIP-FFI---EDE-TG----------RVRVD--PTG-AEI
EAMSVVDEHIFPGKG-PSRFNFNLKRYLSGV---RTENRSTRAFIYKEWVIPVDAMAFTM
GQVR------------FE-AG-DPVI-RKPL-SGE-------------------------
----------------RFMI-----APKSPEALLEEQRSNASSYLVGSVVLLGIGIFTVL
-HLL--QSLQPYR-----------------------------------------------
------------------------------------------------------------
---------------------------------
>Pseudonocardia_dioxanivorans_CB1190 gi|331695440|ref|YP_004331679.1| hypothetical protein Psed_1589 [Pseudonocardia dioxanivorans CB1190]
------------------------------------------------------------
---------MWVIGVVVVL---VGAGF-------------LWSAVRAQRSVHAMLAAETL
SVPELEELR-RVSD-DL------------G------------------------------
--ARGSFRK-VCEVVGAAHPSPE------------GVLRSEL-------SGVECVWHSHR
VQRRYKH--------------YDRDRDGS-------------------------------
------------------------------------------------------------
-----TRVTTRTETVAEQTSGPG-FAL---LRD-GR----------TIGVD--HAGRRPD
GVEQVTDR-FEQTQE-PSNGWADVVGALVGS-----DRDETIGYQYTEWVLRPGTPMYVL
GEVH------------DA-IG-PLVI-APPADPKQ-------------------------
----------------PFVM-----STSTEQQLTDAARGRQRFRSRLGAALVVVGIVVVV
-LALVL------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Acetobacterium_woodii_DSM_1030 gi|379012200|ref|YP_005270012.1| unnamed protein product [Acetobacterium woodii DSM 1030]
--M---------------------------------------------------------
---------AIIIGLLIII---AGIFYA------------VYIYRKNTNKVQEIQFQQTT
CIKDVLDIVGDLSS-LD-------------------------------------------
----ENYRH-YSEVKGQLHSVSG-------------NVEAPF-------SQRPVAYYENE
VYSVHEE--------------TRTERDDKGNTR---------------------------
------------------------------------------------------------
-----TVTDKVETSLSSEKSPVE-VYL---SDS-SS--------DEKVYIDLASFG-SDV
DLMPGCNR-MESKDS-------DWVRNNFNFSVNQNRGSRFLGYRFFEEILPEDQPMYIL
GEIH------------KR-GN-RLYV-GRSVAAKK-------------------------
----------------PSHV-----TYKSEDELLDDIKNEKLVAIGIGVAGVVVGIAVMF
LF----------------------------------------------------------
------------------------------------------------------------
---------------------------------
