>@Cyanothece_PCC_7425@ gi|220906503|ref|YP_002481814.1| unnamed protein product [Cyanothece sp. PCC 7425]
--MG--------------------------------------------------------
---------LAIVGAILLVTGGIL-------------YFVQRHYQQKLYSIKLARKTTV-
------------AELKQLADQVGAE-IGQGSLREYVKLSGQIKCDTPLISELKQV-----
--PCVYYQMQVEREYEE--------------RLTERD-NDGETR----------------
------------------------------------------------------------
----------------EKTQRGSETIASNSQSTP-FFLQDQSG-A----------IEV-D
PSGAAIETVQVLNE-FRPEA-GSAR---------ISFGNFSLSVGGSFPAGRETIGYRYR
ESILPPDRRILIVAT--------------ASDSSGILSLQKPVEKR--------------
---------------------------QKFII-----SLKSEDHLAQSTQ---QTATYTF
YGMIACLGLGAILLVVGLIIR---------------------------------------
------------------------------------------------------------
----------------------------
>@Acaryochloris_marina_MBIC11017@ 641252794 AM1_3710 hypothetical protein [Acaryochloris marina MBIC11017]
------------------------------------------------------------
---------MKIIGIILIVIGIIL-------------FFVYSNLKRKLASLRQARPASI-
------------AELNHLASEIALE-MGSGSWRDYVKLRGTIQCDQPLISELKQM-----
--PCVHYNMTVVREYEE--------------QVTERD-SDDKVV----------------
------------------------------------------------------------
----------------TKTQRGSETLSQNRESVP-FFLQDDTG-E----------IWV-E
PEGAQIETVRVLDE-FSPEQPSGGQ---------LSFGGFSLSL-SSAETGRQTIGYRYQ
ESVLPVQRQVFVVAQ--------------VSDFNQSLVLENPTTKG--------------
---------------------------QRFVI-----SLKSEEALAQTTQ---TSVTYAF
YGMISTLVVGGLLVIFGLLSA---------------------------------------
------------------------------------------------------------
----------------------------
>@Cyanothece_PCC_7424@ gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424]
------------------------------------------------------------
---------MILIGIICLIVGVIL-------------LFFWRSNRSKLRNLRLASASTI-
------------SSLQTIANQIAEE-IGGGSLREYVKIRGVIECDRPLISQLKQE-----
--PCVYYSMTVTWEYNE--------------EVIKQD-NEGKTI----------------
------------------------------------------------------------
----------------REKERKSETVAQNSRSIP-FTLQDSTG-E----------IRV-N
PERAEIETVKVLEE-FRPENFSGGS---------LTFGNFSINL-PSFEERRQTIGYRYQ
EEILPIGRQILVIGT--------------ATDEEGMITIRKPTEKG--------------
---------------------------QRYFI-----SLKSEEELSQATN---NAIRGTF
YSMIFFLTLGLILLVAGVLRG---------------------------------------
------------------------------------------------------------
----------------------------
>@Synechococcus_elongatus_PCC_6301@ 637618204 syc2512_d hypothetical protein [Synechococcus elongatus PCC 6301]
--MA--------------------------------------------------------
---------AIILAAITAIAAIVL-------------YFVRRHYRFKLQSLLLAQPATS-
------------LQLKEIAEHVAGE-IGGGNLRQYVKMWGAIEVEQPLVSELKQE-----
--SCVYYCSTVSREYEE--------------RVRKED-SEGKVT----------------
------------------------------------------------------------
----------------WTTERRSETISQNRRSTP-FYLRDQHG-R----------VRV-E
PESAAIATIPVLDE-FRPDS-SASS---------LIFGAFSLSL-STTAGLGKTLGYRYR
EEILPCDRSVLVVGA--------------ASDETGELTLGPSSEAR--------------
---------------------------QQFFI-----ALKPETALLQEVK---QTIQWLT
IGAIASVVVTVVAAIAALL-----------------------------------------
------------------------------------------------------------
----------------------------
>@Synechococcus_elongatus_PCC_7942@ gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococcus elongatus PCC 7942]
--MA--------------------------------------------------------
---------AIILAAITAIAAIVL-------------YFVRRHYRFKLQSLLLAQPATS-
------------LQLKEIAEHVAGE-IGGGNLRQYVKMWGAIEVEQPLVSELKQE-----
--SCVYYCSTVSREYEE--------------RVRKED-SEGKVT----------------
------------------------------------------------------------
----------------WTTERRSETISQNRRSTP-FYLRDQHG-R----------VRV-E
PESAAIATIPVLDE-FRPDS-SASS---------LIFGAFSLSL-STTAGLGKTLGYRYR
EEILPCDRSVLVVGA--------------ASDETGELTLGPSSEAR--------------
---------------------------QQFFI-----ALKPETALLQEVK---QTIQWLT
IGAIASVVVTVVAAIAALL-----------------------------------------
------------------------------------------------------------
----------------------------
>@Thermosynechococcus_elongatus_BP_1@ 637313275 tll0660 hypothetical protein [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
---------MGVLGGILLVIAVLV-------------LCGWWDYRLKVRALNLAVSSTP-
------------AQLHELQRRVAQE-IGGGYLQEYVKISGQIVADRPLVSELKRL-----
--PCVHYRLCVSRVYKT--------------TESHED-GSSETK----------------
------------------------------------------------------------
--------------------YRHEILSSNTQTIP-FRLRDGDM-E----------IYV-D
PRGAEIETVQVLNE-FQEDN-NTTH---------LAFGRFQMDL-SSLPKHSDTVGYRYE
EWILPVNQQVFVVGT--------------ASDERGKLRIRRPHQKG--------------
---------------------------QLFFI-----SLESEENLTKKVR---QYARASI
IAAGVFSGLGILLILL--------------------------------------------
------------------------------------------------------------
----------------------------
>@Thermosynechococcus_elongatus_BP_1@ 637312804 tll0199 hypothetical protein [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
---------MGVFAHLCLTGSAFL-------------FALEGYYRLQLRGIKVASPSTI-
------------GELEKFQQQVAQE-MGSGSWREYVQVVGQVTTSQPLLSEVKRI-----
--PCVYYKTIISREYEK--------------E----------------------------
------------------------------------------------------------
-----------------GSDRPSEIIGRHEQSTL-FLLRDHQG-E----------IEV-N
PFGAEIEAVQVLDE-LRPAD-QPHA---------FALSLGFLSF-NWHFGKGTTLGYRYQ
EWVLPLGQPVSVVGM--------------ASDQGGVLRLQKPQNRG--------------
---------------------------QKFII-----SLSFEDPLIQQYK---QQKRKMT
YASLGATLCGVCGLVLALF-----------------------------------------
------------------------------------------------------------
----------------------------
>@Synechococcus_sp_JA_2_3B_a2_13@ 637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba(2-13)]
--MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPP
PERKAFMNWLMLLGLLCLPASLFS-------------FVEYLRSQRLVQQLSATRLLKI-
------------AELRHLGQTNPQA-KGA----NLAQVYGRVVCDRPLVSELSRQ-----
--PCVYYKSEISWEYDEIECYRRYLNSRGDVAYSERI-SEGEYQNALRLGSRAKSYPGEM
VGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPNPGYPQQLGSPGYPQKSPFSEVSSPQKHY
ANVYYDPSTGREYLLERETRTRDETLHSVVRQIP-FFIEDETG-R----------VRV-D
PTGAEIEAMSVVDEHIFPGK-GPSR---------FNFNLKRYLS-GVRTENRSTRAFIYK
EWVIPVDAMAFTMGQ--------------VRFEAGDPVIRKPLS-G--------------
---------------------------ERFMI-----APKSPEALLEEQR---SNASSYL
VGSVVLLGIGIFTVLHLLQSLQPYR-----------------------------------
------------------------------------------------------------
----------------------------
>Physcomitrella_patens subsp. patens_gi|168002970|ref|XP_001754186.1| predicted protein [Physcomitrella patens subsp. patens]gi|162694740|gb|EDQ81087.1| predicted protein [Physcomitrella patens subsp. patens]
--M---------------------------------------------------------
---------LSWGGITLCLSGAAL-------------YCLSRNTGRDALNLRSIERV---
------------NQLKDLAILLESA---CKVVPLVVTVAGRVGSETPIACEHSSL-----
--RGVILEETAEQ------------------HFLKHN-DTGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSISKEVP-WYLEDGTG-R----------VYIVG
ARNAAGMELTVASE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRV
ERVLPTGTNLTVVGE-------------AVQDDRGLIRIQKPNK----------------
---------------------------GPFYV-----TPKSLDQLVANLG---RWSRWYK
YMSLGFTIVGIYFITSHAIKHF-------MERRRREALHRRVMEAAA-LRQASQREGGDG
DMGDVTSHPLDDSVDTSQKKD------------RGTPDLCVICLEQDYNAVFLPCGHMCC
CTSCSAQLTSCPLCRRHIDKFVKTYRH-
>Physcomitrella_patens subsp. patens_gi|168043801|ref|XP_001774372.1| predicted protein [Physcomitrella patens subsp. patens]gi|162674364|gb|EDQ60874.1| predicted protein [Physcomitrella patens subsp. patens]
--M---------------------------------------------------------
---------LSWGGITLCFSGAAL-------------YCLSRNTGRDALHLMSVERV---
------------NQLEDLAKLLESA---CTVVPWVVTVAGRVGAEAPIASEHSSL-----
--RGVILEKSAEQ------------------HFLKHN-DTGSWI----------------
------------------------------------------------------------
--------------------QHSALMLSISKEVP-WYLEDGTS-R----------VFIIG
ARNAAGMDLTVASE--SFEEYGG-S---------LVRGTLDYLQ------GLKMLGVKRV
ERVLPTGTNLTVVGE-------------AVQDDRGLIRIQKPDK----------------
---------------------------GPFYV-----TPQSQDQLIENLG---RWSRWCQ
YMSFGLTLVGIYFITSRAIKHM-------LERWRREALLTRVMEAAA-LRKALQQEGVDE
ESDGVTAFPHDDNAHTAQKKD------------GGMPSLCVICLEQDYNAVLVPCGHMCC
CTSCSSQLSLCPLCRRHIDQVVKTFRH-
>Selaginella_moellendorffii_gi|302772771|ref|XP_002969803.1| hypothetical protein SELMODRAFT_231449 [Selaginella moellendorffii]gi|302806814|ref|XP_002985138.1| hypothetical protein SELMODRAFT_234706 [Selaginella moellendorffii]gi|300146966|gb|EFJ13632.
--M---------------------------------------------------------
---------LPWGGITMCLSGVAL-------------YFLSRNSGRDAATLKAVRRV---
------------DQLKDLAHLLDSA---CKAVPLVVTVAGRVGSETPIGCDHSSL-----
--RCVILEETAEQ------------------HFLKHN-DTGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSNNKEVP-WFLEDASG-R----------VFIVG
ARGAAGLELTIASE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRV
ERVLPTGTALTVVGE-------------AIKDDQGTLRIQRPHK----------------
---------------------------GPFYV-----TPKSIDQLIANLG---KWSRWYK
YMSLGFTLFGVFLVASHTIRYV-------MEKRRRAALNRRVMEAAA-RRRERKEHEGKA
QVGEFA------KVETATKRD------------GRLPDLCVICLEQEYNAVFVPCGHMCC
CISCSAQLQNCPLCRRRIEQIVKTYRH-
>Medicago_truncatula_gi|144924893|gb|ABE86663.2| Zinc finger, RING-type [Medicago truncatula]
MAM---------------------------------------------------------
---------VPWRGVGCCLSAAAL-------------YLLGRTSGRDVDILKSVNRV---
------------NQLRELAQLLDEE-----IFPLVVAISGRVGSETPISCEFSGL-----
--RGVIIEETAEQ------------------HFLKHS-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMQSRSNEVP-WYLDDGTG-R----------VRVVG
AQGATGFVLPVGSE--AFEESGR-L---------PVRGTSDYVQ------GLKMLGVKRI
ERVLPVGTSLTVVGE-------------AAKDDVGTIRIQRPSK----------------
---------------------------GPFYV-----SPKTIDELIANIG---RWARWYK
YASAGLTVLSVYMIANHAVRYI-------LERRRRNELEKRVLAAAA-KISGQDNGGE--
MDD---------SLSDGAKRE------------RAMPNLCVICLEQEYNSVFVPCGHMCC
CTACSSHLTSCPLCRRQIEKAVKTFRH-
>Glycine_max_gi|356535760|ref|XP_003536411.1| PREDICTED: mitochondrial ubiquitin ligase activator of nfkb 1-like isoform 1 [Glycine max]
--M---------------------------------------------------------
---------IPWGGLSCCLSAAAL-------------YLLGRSSGRDAEILKSVTRV---
------------NQLKELAQLLDAE-----ILPLIVTISGRVSSETPINCEFSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTD-R----------VHVVG
ARGASGFALPVGIE--AFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPVGTSLTVVGE-------------AAKDDVGAIRIQRPHK----------------
---------------------------GPFYV-----SPKTIDQLIANLG---KWARWYK
YASVGLTVFGAYLIAKHAIRYI-------LERRRRSELQRRVLAAAA-KKSGQNNDVE--
KAD---------SLSDGAKKD------------RLMPDLCVICLEQEYNAVFVPCGHMCC
CTACSSHLTNCPLCRRQIEKVVKTFRH-
>Prunus_persica_ppa008230m_PACid_17644506
--M---------------------------------------------------------
---------LPWGGLSCCLSAAAL-------------YLLGRSSGRDADILKSATRI---
------------NQLKELAKLLDSE---C-ILPLVVAISGRVSSETPITCEFTGL-----
--RGVVVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTG-R----------VHVVG
ARGATGFVLPVASE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGTSLSVVGE-------------AVKDDIGTIRIQRPHK----------------
---------------------------GPFYV-----SPKTIDQLIANLG---KWARWYK
YASLGLTVFGVYLVAKHSVQYI-------LERRRRWELQRRVLAAAA-KRSGEDNEGSNE
KDD---------NVLDGSK--------------RLMPDLCVICLEHEYNAVFVPCGHMCC
CTTCSLHLTNCPLCRRRIDQAVKTFRH-
>Cucumis_sativus_Cucsa.084910.1_PACid_16956611
--M---------------------------------------------------------
---------LPWGGISCCLSAAAL-------------YLLGRSSGRDAELLKSVTRV---
------------NQLKELAQLLEAE----HLLPLVVAISGRVSSDTPINCEFSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTG-R----------AFVLG
ARNATNFILPVVSE--VFEESGR-S---------LMRGTLDYLQ------GLKMLGVKRI
ERVLPTGTSLTVVGE-------------AAKDDIGTIRIQRPHK----------------
---------------------------GPFYV-----SPKTIDQLISNLG---KWARWYK
YASMGLSIFGLYLVTKHVILYL-------MERRRRWELQKRVLAAAA-KRSSQENEGEIE
KAS---------NGTDGTKRD------------RSMPDLCVICLERDYNAVFVPCGHMCC
CVACCSHLTNCPLCRRRIELVVKTFRH-
>Citrus_sinensis_orange1.1g019223m_PACid_18093190
--M---------------------------------------------------------
---------IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSG---SKVLPFIVTVCGRVGSETPISCEYSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTG-R----------AFVVG
ARGATGFVLTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERLLPTGTSLTVVGE-------------AVKDDIGTVRIQRPHK----------------
---------------------------GPFYV-----SPKTIDELIENLG---KWARWYK
YASFGLTIFGTFLIAKRAIHYI-------LQRKRRWELHRRVLAAAAVKRSEQDNEGTNG
QAE---------NGSDGTQRD------------RVMPDLCVICLEQEYNAVFVPCGHMCC
CIICSWHLTNCPLCRRRIDQVVRTFRH-
>Citrus_clementina_0.9_003846m_PACid_19263951
--M---------------------------------------------------------
---------IPWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLKELAHLLDSG---SKVLPFIVTVCGRVGSETPISCEYSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTG-R----------AFVVG
ARGATGFVLTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERLLPTGTSLTVVGE-------------AVKDDIGTVRIQRPHK----------------
---------------------------GPFYV-----SPKTIDELIENLG---KWARWYK
YASFGLTIFGTFLIAKRAIHYI-------LQRKRRWELHRRVLAAAAVKRSEQDNEGTNG
QAE---------NGSDGTQRD------------RVMPDLCVICLEQEYNAVFVPCGHMCC
CIICSSHLTNCPLCRRRIDQVVRTFRH-
>Citrus_sinensis_orange1.1g019651m_PACid_18093104
--M---------------------------------------------------------
---------ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGG---SKVLPSIVSVSGRVGSETPISCEYSGL-----
--RGVIVEETTER------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTG-C----------VFVVG
ARGATGFALTVGSE--VFEESGR-S---------LVHGTLDYLQ------GLKMLGVKRI
GRLLPTGTSLTVVGE-------------AVKDDIGTVRIQRPHK----------------
---------------------------GPFYV-----SPKTIDELLENLG---KWARWYK
YASFGLTIFGAFLIAKRVIRCI-------LQRKRRWELRRRVLAAAAVQRSEQDNEGTNG
QAE---------NGSDSTQRD------------RVMPDLCVICLEQE-------CGHLCC
CLICSSRLTNCPLCRRRIDQVVRTFRH-
>Citrus_clementina_0.9_014777m_PACid_19265048
--M---------------------------------------------------------
---------ISWGGISCCLSGAAL-------------YLLGRSSGRDAELLKTVTRV---
------------NQLEELAHLLDGG---SKVLPSIVSVSGRVGSETPISCEYSGL-----
--RGVIVEETTER------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTG-C----------VFVVG
ARGATGFALTVGSE--VFEESGR-S---------LVHGTLDYLQ------GLKMLGVKRI
GRLLPTGTSLTVVGE-------------AVKDDIGTVRIQRPHK----------------
---------------------------GPFYV-----SPKTIDELLENLG---KWARWYK
YASFGLTIFGAFLIAKRVIRCI-------LQRKRRWELRRRVLAAAAVQRSEQDNEGTNG
QAE---------NGSDSTQRD------------RVMPDLCVICLEQEYNAVFFPCGHLCC
CLICSSRLTNCPLCRRRIDQVVRTFRH-
>Manihot_esculenta_cassava4.1_011064m_PACid_17986177
--M---------------------------------------------------------
---------LPWGGISCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKELAKLLDIE---SNISPSVVSISGRVGSETPINCEYSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTD-R----------VYVVG
ARGASGFVLTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGTSLTVVGE-------------AVKDDIGTVRVQRPHK----------------
---------------------------GPFYV-----SPRTIDELIGNLG---KWARWYR
YASVSLTVFGAFLIAKHAIQYI-------MERRRRWELQSRVLAAAAAKRQGQDSEGSNG
KAE---------NGSDNSKRE------------RPVPDLCVICLEQEYNAVFLPCGHMCC
CTTCSSHLTNCPLCRRRIEQVVKTFRH-
>Vitis_vinifera_gi|225436896|ref|XP_002274008.1| PREDICTED: hypothetical protein [Vitis vinifera]gi|296086688|emb|CBI32323.3| unnamed protein product [Vitis vinifera]
--M---------------------------------------------------------
---------IPWGGISCCLSAAAL-------------YLLGRSSGRDAEALKSVTRV---
------------QQLKDLVQLLDTA---CKVLPLVVTVSGRVGSDTPIKCEYSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDDTG-R----------AYIVG
ARGATGLVLTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGTPLTVVGE-------------AIKDDVGTIRIQRPHK----------------
---------------------------GPFYV-----SPKSIDHLVANLG---KWARWYR
YASLGFTVFGVYLIAKSAIQYV-------MERKRCWELRKRVLAAAS-KKSGQDSEDPDE
KDE---------NGSDNTKRD------------RLMPDLCVICLEQEYNAVFVPCGHMCC
CTMCSSQLTNCPLCRRRIEQVVRTFRH-
>Eucalyptus_grandis_Egrandis_v1_0.010112m_PACid_18812196
--M---------------------------------------------------------
---------IPWGGLSCCLSAAAL-------------YVLGRSSGRDAEALKCVFRV---
------------NQLKELAQLLDTE---CKVLPLVVTLCGRVGSDTPINCEYSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTG-R----------AYVLG
ARGASGFELNIASE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERLLPVGSSLTVVGE-------------AVKDDIGTVRIQRPHK----------------
---------------------------GPFYV-----SPKTIDQLISNLG---KWARWYR
YASYGFTVFGICLIAKRAIQYI-------MERKRRWELQRRVLAAVA-RRSEQDTEGTDD
KTK---------NAPDSAKRD------------RSMPDLCVICLEQEYNSVFVPCGHMCS
CTTCSLQLTNCPLCRRRIEQAVKTFRH-
>Tomato_Solyc06g084360.1.1 genomic_reference:SL2.31ch06 evidence_code:10F0H1E1IEG gene_region:4579148145798777 functional_description:"Baculoviral IAP repeatcontaining protein 3 (AHRD V1 * B0XJ37_CULQU); contains Interpro domain(s)  IPR001841  Zinc f
--M---------------------------------------------------------
---------VPWAGLSCCLSAAAL-------------YLLGRSSGRDAEVLKSVTRV---
------------NQLKDLAQLLDTA---SKVLPLVVTISGRVGSDTPINCEYSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMCKEVP-WYLDDGTG-R----------TFIVG
GRGATGLVLTVGSE--AFEEAGR-S---------FVRGTLDYLQ------GLKMLGVKRI
ERVLPVGTPLTVVGE-------------AVKDDIGTVRIQRPHK----------------
---------------------------GPFYI-----SHKTIDQLIANLG---RWARWYK
YASMGFTAVGVYLLVKHTFHYM-------MERKRHWELRRRVLAAAA-KRAGDEDEGSDA
TAE---------NGVDN--KD------------LLMPDLCVICLEQEYNSVFVPCGHMCC
CMTCSSHLTNCPLCRRRIEQVVKTFRH-
>Mimulus_guttatus_mgv1a009837m_PACid_17671176
--M---------------------------------------------------------
---------IPVGGITCCLSAAAL-------------YLLGRSSGRDADLLKSVTRV---
------------NQLKDLAQLLEAA---SKVLPLVVTVSGRVGSETPINCEYSGL-----
--RGVIVEQTAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMCKEVP-WYLDDGTS-R----------VHVVG
ARGATGLVLTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGSPLTVVGE-------------AVKDDIGSIRIQRPHK----------------
---------------------------GPFYV-----TDKTIDQLIANLG---KWSRLYK
YASMGLTAFGVYLLAKHAFQYI-------MDRRRLWETRKRVLDAAA-KKAGQNEGALNG
EAE---------IGSDSSNKE------------RPIPELCVICLEQEYNSVFVQCGHMCC
CMACSSHLTNCPL---------------
>Aquilegia_coerulea_v1.007878m_PACid_18162338
--M---------------------------------------------------------
---------LPWGGITCCMSAAAL-------------YLLGKSSGRDADILKSVTRL---
------------NQLKDLAQMLDTA---CKVLPFVVTVSGRVGSDTPINCEHSGL-----
--RGVIVEEAAEQ------------------HFMKQN-DSGSWI----------------
------------------------------------------------------------
--------------------QDSAQMLAMTKEVP-WYLDDGTG-R----------VHVLG
ARGATGLVLTVASE--TFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGTSLTVVGE-------------AVKDDVGTIWIQRPHK----------------
---------------------------GPFYV-----SPKSIDQLIANLG---IWARLYK
YASLGFTAFGVYLIAKHAIRYI-------LERRRLLDFQRRVRAAAA-QRLEQDNDGTDG
KAE---------DGPDVVNKD------------RIMPDICVICLEQEYNAVFVPCGHLCC
CTTCSSHLSNCPLCRRRIDQVVRTFRH-
>Arabidopsis_lyrata subsp. lyrata_gi|297840101|ref|XP_002887932.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]gi|297333773|gb|EFH64191.1| zinc finger family protein [Arabidopsis lyrata subsp. lyrata]
--M---------------------------------------------------------
---------IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLKTVTRV---
------------NQLKELAQLLELD---SKILPFIVAVSGRVGSETPIKCEHSGI-----
--RGVIVEETAEQ------------------HFLKHN-ETGSWV----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WFLDDGTS-R----------VHVMG
ARGATGFALTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGIPLTIVGE-------------AVKDDIGEFRIQKPDR----------------
---------------------------GPFYV-----SPKSLDQLISNLG---KWSRWYK
YASMGFTVFGVFLITKHVIDSV-------LERRRRRQLQKRVLDAAA-KRAELESEGSNG
ARE---------SIADSTKKE------------DAVPDLCVICLEQEYNAVFVPCGHMCC
CTACSSHLTSCPLCRRRIDLAVKTYRH-
>SP1
--M---------------------------------------------------------
---------IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLETVTRV---
------------NQLKELAQLLELD---SKILPFIVAVSGRVGSETPIKCEHSGI-----
--RGVIVEETAEQ------------------HFLKHN-ETGSWV----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WFLDDGTS-R----------VHVMG
ARGATGFALTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGIPLTIVGE-------------AVKDDIGEFRIQKPDR----------------
---------------------------GPFYV-----SSKSLDQLISNLG---KWSRLYK
YASMGFTVLGVFLITKHVIDSV-------LERRRRRQLQKRVLDAAA-KRAELESEGSNG
TRE---------SISDSTKKE------------DAVPDLCVICLEQEYNAVFVPCGHMCC
CTACSSHLTSCPLCRRRIDLAVKTYRH-
>Thellungiella_halophila_gi|312283085|dbj|BAJ34408.1| unnamed protein product [Thellungiella halophila]
--M---------------------------------------------------------
---------IPWGGVTCCLSAAAL-------------YLLGRSSGRDAEVLKTVTRV---
------------SQLKELAQLLELD--SSKLLPFIVAVSGRVGSETPIKCEHSGI-----
--RGVIVEETAEQ------------------HFLKHN-ETGSWV----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WFLDDGTS-R----------VNVVG
ARGATGFALTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGMPLTIVGE-------------AVKDDIGDLRIQKPER----------------
---------------------------GPFYV-----SPKSLDQLISNLG---KWSRWYK
YASMGLTVFGVFLITKHVIDSV-------LERRRRRELQKRVLDAAA-KRAERESEGSNG
THE---------SVSDSTKKE------------DAVPDLCVICLEQEYNAVFVPCGHMCC
CTACSCHLTSCPLCRRRIDQVVKTYRH-
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
--M---------------------------------------------------------
---------IPWGGVGCCLSAAAL-------------YLLGRSSGSDAEVLRSVARA---
------------GSMKDLAAILDTA---SKVLPLVVAISGRVGSDTPLICQQSGM-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSAVMLSVSKEVP-WYLDDGTG-R----------VYVVG
ARSAAGLILTVASE--VFEESGR-T---------LVRGTLDYLQ------GLKMLGVKRT
ERVLPTGTSLTVVGE-------------AIKDDVGTIRIQRPHK----------------
---------------------------GPFYA-----SSKSIDQLIVNLG---KWAKLYR
IASMGFATFGVFLLAKRALQHF-------LERRRRHELQKRVLNAAA-QRQAREAEGSKG
TSD----------AEPNSKKD------------QLVLDICVICLEQEYNAVFVPCGHMCC
CVACSSHLTNCPLCRRRIDQAVRTFRH-
>Sorghum_bicolor_Sb02g041380.1_PACid_1959657
--M---------------------------------------------------------
---------IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTA---SKVLPLVVAVSGRVSSDTPLICQQSGM-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSAVMLSVSKEVP-WYLDDGTG-R----------VYVVG
ARSAAGLILTVASE--VFEESGR-T---------LVRGTLDYLQ------GLKMLGVKRT
ERVLPTGTSLTVVGE-------------AIRDDVGTIRIQRPHK----------------
---------------------------GPFYV-----SPKSIDQLIMNLG---KWAKLYR
LASMGFATFGVFLLAKRAIQHF-------LERKRRHELQKRVLNAAA-QRQAREAEGSNG
SSD----------TEPNSKKD------------QLVLDICVICLEQEYNAVFVPCGHMCC
CMACSSHLTNCPLCRRRIDQAVRTFRH-
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
--M---------------------------------------------------------
---------IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTA---SKVLPLVVAVSGRVGSDTPLICQQSGM-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSAVMLSVSKEVP-WYLDDGTG-R----------VYMVG
ARSAAGLILTVASE--VFEESGR-T---------LVRGTLDYLQ------GLKMLGVKRT
ERVLPTGISLTVVGE-------------AIKDDVGTIRIQRPHK----------------
---------------------------GPFYV-----SPKSIDQLIMNLG---KWAKLYR
LASMGFATFGAFLLAKRAIQHF-------LERKRRHELQKRVLNAAA-QRQAREAEGSIG
SSD----------TEPNSKKD------------QLVLDICVICLEQEYNAVFVPCGHMCC
CMACSSHLTNCPLCRRRIDQAVRTFRH-
>Setaria_italica_Si030396m_PACid_19714000
--M---------------------------------------------------------
---------IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSMKDLAAILDTA---SKVLPLVVAVSGRVGSDTPLICQQSGM-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSAVMLSVSKEVP-WYLDDGTG-R----------VYVVG
ARAAAGLILTVASE--VFEESGR-T---------LVRGTLDYLQ------GLKMLGVKRT
ERVLPTGTSLTVVGE-------------AIKDDVGTIRIQRPHK----------------
---------------------------GPFYV-----SPKSIDQLILNLG---KWAKLYR
LASMGFATFSVFLLAKRAIQHF-------LERKRRHELQKRVLNAAA-QRQAREAEGGKG
TSN----------TEPNSKKD------------QLVLDICVICLEQEYNAVFVPCGHMCC
CMACSSHLTNCPLCRRRIDQAVRTFRH-
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
--L---------------------------------------------------------
---------IPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVARA---
------------GSTKDLAAILDTA---SKVLPLVVAVSGRVGSDTPLICQQSGM-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSAVMLSVSKEVP-WYLDDGTG-R----------VFVVG
ARGAAGLVLTVASE--VFEESGR-T---------LVRGTLDYLQ------GLKMLGVKRT
ERVLPTGTSLTVVGE-------------AIKDDVGTIRIQRPHK----------------
---------------------------GPFYV-----SPKSIDQLIMNLG---KWAKLYQ
LASMGFAAFGVFLLAKRALQHF-------LERKRRHELQKRVHAAAA-QRQAREAEGGNG
TSD----------VDSNNKKD------------QLVLDICVICLEQEYNAVFVPCGHMCC
CMNCSSHLTNCPLCRRRIDQAVRTFRH-
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
--M---------------------------------------------------------
---------VPWGGVGCCLSAAAL-------------YLLGRSSGRDAEVLRSVTRT---
------------GSLKDLAAILDTA---SKVLPLVVAVSGRVSSDTPLICQQSGM-----
--RGVIVEEMAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSAVMLSVSKEVP-WYLDDGTG-R----------VYVVG
ARAAAGLVLTIASE--VFEESGR-T---------LVRGTLDYLQ------GLKMLGVKRT
ERVLPTGTSLTVVGE-------------AIKDDVGTIRIQRPHK----------------
---------------------------GPFYA-----SPKSIDQLILNLG---KWAKLYQ
LASMGFAAFGVFLLAKRALQHF-------LQKKRQHELNKRVRAAAA-QRQAREAEGADG
TSN----------GDPNSKKD------------QLVLEICVICLEQEYNAVFVPCGHMCC
CMNCSSHVTNCPLCRRRIDQAVRTFRH-
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
--M---------------------------------------------------------
---------IPWGGITCCMSAAAL-------------YLLGRSSGRDADILRKVTRV---
------------NQLKELAQLLDIE---SKIMPLIVAISGRVGSETPISCEYSGL-----
--RGVIVEETAEQ------------------HFLKHN-DAGSWI----------------
------------------------------------------------------------
--------------------QDSALMLSMSKEVP-WYLDDGTA-R----------VFVVG
ARGATGFVLTVGSE--VFEESGR-S---------LVRGTLDYLQ------GLKMLGVKRI
ERVLPTGTSLTVVGE-------------MTLEQ---FRYEDRTN----------------
---------------------------GLFTCLQINGSPD------FQLG---KWARWYK
YASMGLTFLGVFLIAKRSIEYV-------LERRRRRELQKRVLAAAA-KRSGQDNEGSNI
IPE---------NGLDGAKRE------------HLMPDLCVICLEQEYNAAFVPCGHMCC
CMTCSSHLTNCPLCRRRIEQVLRTFRH-
>SPL1_NP_564745
--M---------------------------------------------------------
---------IHLAGFTCCLGGVAL-------------YLLTRSTGRD---IKSITRV---
------------YQLKDLEQLVEVE---SKVVPLIIAVSGDVGSETPIKCEHSYV-----
--LGVFLKRTAEQ------------------QVLRRN-WRFSWV----------------
------------------------------------------------------------
--------------------RNSTLMQPMTKEVP-WYLDDGTG-R----------VNVDV
SQGELGLALTVGSD--VFEKAEPVS---------LVQGALGYLK------GFKILGVRHV
ERVVPIGTPLTVVGE-------------AVRDGMGNVRIQKPEQ----------------
---------------------------GPFYV-----TYIPLDQLISKLG---DLSRRFK
YASMGLTVLGVILISKPVIEYILKRIEDTLERRRRQFALKRVVDAAA-RRAKPVTGG---
----------------GTSRD------------GDTPDLCVVCLDQKYNTAFVECGHMCC
CTPCSLQLRTCPLCRERIQQVLKIYRH-
>Arabidopsis_lyrata subsp. lyrata_gi|297840639|ref|XP_002888201.1| hypothetical protein ARALYDRAFT_338432 [Arabidopsis lyrata subsp. lyrata]gi|297334042|gb|EFH64460.1| hypothetical protein ARALYDRAFT_338432 [Arabidopsis lyrata subsp. lyrata]
--M---------------------------------------------------------
---------IHLAGFTCCLGGIAL-------------YLLSRNTGG---VVKSITRV---
------------NHLKDLEQLVE-----SKVFPLIIAVSGIVGSETPIKCEHSDI-----
--LGVFLKKTAEQ------------------QVLSRN-WRFSWV----------------
------------------------------------------------------------
--------------------RKSTLMQPMTKEVP-WFLDDGTG-R----------VNVAV
SQGEIGLALTVGSD--VFEKAEPVS---------LVQGTLDYLK------GLKILGVRRV
EHVVPIGTPLTIVGE-------------AVKDGMGNVRIQKPEQ----------------
---------------------------GPFYV-----SYVPLDQLISKLG---EWSRRFK
YASMGLTVVGVILLSKPVIKYILKKIEDTLERRRRQLLQKRVVD----------------
-----------------------------------VPDLCVICHDQKYNTAFVQCGHMCC
CLTCSLRLTTCPLCREQIQQVLKIYRH-
>Chlorella_variabilis_gnl|BL_ORD_ID|28282 jgi|ChlNC64A_1|139486|IGS.gm_25_00037
--MTHFVSPMLFTSL---------------------------------------------
---------LGYGGLATCALGGLL-------------ALVGLAKGKQARQLGAAVPV---
------------ESLSELKQLL-------ALVPVIVAVTGRVLAPKPYRCEMSDT-----
--DAAIIEMREEK------------------KSERRA-GA-EWV----------------
------------------------------------------------------------
--------------------GTTQLLRESVKEAE-WGLVDGSGTE----------VPVVA
GRRADGDYLQMSGDRLIPDNQTQ-G---------FLGRVVDEVQ------GSRSVGVRQV
ERMLPVGTMLTAVGELATAVEHPSVFKGAVRKGGKMLVLRAPRD----------------
---------------------------GAFYL-----SRQPLPDVIASLQ---ASSLACQ
QWAAAFTAVGASMLVAAATQHA-------LTWVRQRRLRQRVEKAMR-ERAAAAAAAGGG
GAA---------GAPAASAAEPQPADVAEAAEGGARPSLCVVCLERPCATVFPACGHMCA
CSRCSHGLRRCPICRSR-GAPIRVYTA-
>Micromonas_sp._RCC299_gi|255086321|ref|XP_002509127.1|
---------MAGEGH---------------------------------------------
---------VSWPGVACIATGALFGYSSRAFKRNIPQYTDFRALERDLRAAASRARAEPT
RRRHHPTHAAGENEIRARPAQADDD-DDDAPFGMLVAITGAARSDVLVPCVHAKRPDGRT
PERAIYVDAVTDQ------------------YLARQAVRSGEWI----------------
------------------------------------------------------------
--------------------RDCVVVAAMAKEAPTWRLEDPAG-HGVNMHRATSMAQASD
AARAADWHLSLVHD--EFESAGS-AGAGSSLHSRIIANALDVNM------GLNVLGLRHR
ERVLAPGARLTAVGEVFIAPNGGPVGVDG-GDGAGEIRLRRPRRRKGWRRHGRGWRRKGG
TPGDEKSAPGDGDGDGDDAAMSPRMDPNVFTV-----TQKPFDEYVDGFG---SWGKVNA
ALGLGFLGVGVALVLTKLWRAR-------LTRWREARFLRRMREAEEARRAAGGGEGDDG
GDTAG-------TNTDTAGAK------------VSPGETCVVCMYARSEVVYKECGHLVC
CGVCAGRMDRCPLCRRRSAHMRVYRAGL
>@Synechococcus_sp_CB0101@ 650127929 SCB01_010100001846 acetylornithine aminotransferase [Synechococcus sp. CB0101]
--MTPPPRISPATSAVMQTYGRFPLELVRGRGVWVWDSQGRRYL----------------
---------DGVAGIAVCTLGHSS-------------AVMRRALGRQLRKLQHVSNL---
------------YRIPEQEQLAAWITANSCADAVFFCNSGAEANEGAIKLA---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------R---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>@Synechococcus_WH_8102@ gi|33864918|ref|NP_896477.1| hypothetical protein SYNW0382 [Synechococcus sp. WH 8102]
--MDC-------------------------------------------------------
------------------------------------------------------------
------------TQF----------------------TPGHVRVSSGYNCLFAWK-----
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------R---------------
------------------------------------------------------------
----------------------------------RVLHYRPPHQ----------------
---------------------------TKFQV-----APKSSAILFRSLRDLSKPSRQTA
RARRGLRSLVSTTVDTGIIDRR-------STTWTRQNAKQRLNLQKHRKQEMRSASGKYS
WTTYNRSFFSYSLTTGAVVTN---------------------------------------
----------------------------
>@Synechococcus_RCC307@ gi|148243088|ref|YP_001228245.1| hypothetical protein SynRCC307_1989 [Synechococcus sp. RCC307]
--MNP-------------------------------------------------------
------------------------------------------------------------
----------------DLADAL--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------QALVAVAIEST-VGLEDHTQ-S----------AAVAD
AMRACTAQLMSVSE--QFQDSDLD------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
