>AT1G62370.1|PACid:19656822
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------SQ---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------LGDLLRES-------EDGTRSERT--
------------------------------------------------------------
-----MMMSLLEEDQINGGDRTMSKWTTLKQ-----------------RLRFDWVGCC--
GKPLTLRLRQAET---PIVVD---------------DDD---------------------
------------------------------------------------------------
---------------------DEEESQNQVVDFSDPGTG---------------------
-----TELDCLTRGSTRNLAEALA---EERLAHVTEEET--------------------A
VTK-VPLMRLLAESD----------------------------GCDSTTTWLGNDPLCCV
CMGREKGAAFIPCGH-TYCRVCSREIWMN-RGTCPLCNRSIFDVLDLY-----
>AT4G03965.1|PACid:19647576
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------SQ---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------LG--VETS-------QAQPETPQ---
------------------------------------------------------------
---STTFLDLLRL-QMDGLDRSRRRKRTLKE-----------------RLGFKRIGCC--
GPTWGLRLTSNT------------------------GED---------------------
------------------------------------------------------------
---------------------DDEPFENRLVSGSDHVTG---------------------
---------PLNQG--MNLATALA---AER--NYRTEET--------------EASGSLT
PLK-VSLMRLLEETAERV-------------VVEENETERVTASASSTVRGVNNDSVCCV
CMGRKKGAAFIPCGH-TFCRVCSREVWLN-RGSCPLCNRPIIEILDIY-----
>AT4G22250.1|PACid:19648651
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------MSE---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------LD--LGTS-------QRMTETHRT--
------------------------------------------------------------
---TTTFLDLLRR-QMSGHDLTR-RKRTLKE-----------------RLRFKCIGCC--
GPTWNLRLTNNTTLHSPTSRD---------------DEI---------------------
------------------------------------------------------------
---------------------EELQIETGLVLESDHGSG---------------------
------------TG--MNLATALE---AER--YNRGEST--------------EAEADMT
PRR-VSLMRLLEETAEKI-------------VDDDGKETEILTASIGTLTG--NDSVCCV
CMGRKKGAAFIPCGH-TFCRVCSRELWLN-RGSCPLCNRPIIEILDIF-----
>AT3G25030.1|PACid:19659043
M------------IQMDGGD----------------------------------------
------------------------------------------------------------
---------------------------------------------RLRVTLLDRMST---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------VESSRSCLTLEAILMAD-------KNRTSPQILSP
-------------------------------------------------PPSRSQS----
---NRSLVEVMQREHRHS--RDKTAWKSLRE-----------------KLRLKRNGSV--
WISSNSIPSLDT----PIPNR---------------DNV-----SH--------------
----------------------------------------------------QLGFLLSN
S-----------------------------------GNV---------------------
-----TEEASSVEGR-IRLGAVLA---EERALSAREEET--------------PAEREVE
PAR-MSLMELLEENEGQMSFVSVD------GEAE-----------EEVAAVTAAEISCCV
CMVRSKGAAFIPCGH-TFCRLCSRELWVQ-RGNCPLCNTTILEVLDLF-----
>AT4G13100.1|PACid:19645359
M------------IQMDGGD----------------------------------------
------------------------------------------------------------
---------------------------------------------RLRVTLLDRMST---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------VENGRSSVTLEDILMAE-------TSSFRSLTTPT
-------------------------------------------------TPVRNHS----
---SSSLLDVMRRERR----RDKTAWKSLRD-----------------KLRLKRTATG--
WISSNPIPTLDN----HILTP---------------DND-----SHR-------------
--------------------------------------------------FNRLGFLLTN
SETN--------------------------RSSRDVSDA---------------------
-----AEEAAEREGR-LRLGTVLA---AER--------------------------EEMQ
PPR-MSLMELLEDNDGHMYELSAR------DEVEVEGRDGCDGGGEAVAVTGAAELGCCV
CMVRSKGAAFIPCGH-TFCRLCSRELWVQ-RGNCPLCNTAILQVLDIF-----
>AT3G07120.1|PACid:19661071
M-----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------SALKS---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------RSNSLAGLSLDAVLGGE-------ILIEPPSLPSP
-------------------------------------------------PPLPSKSLVPH
RPTSQTLFDIIREEYAKEGHKDRTTWQIFRE-----------------KLRLKRTGSA--
WTSSLHIPASDI----LIPNP---------------KHIGTAFRSHSAG-----------
---------------------------LNIRDLVHAIPMSDPPGSSGRAMFTRGSSMRVG
SSKNPDDSPDISVLEDGPPSRSFKPQLSRHDSVRDHSEGEENNRRRHPIVTFVEERQMSA
REAVAAQEAAEAEAA-AAGGSEDEDDDDEEDDSGETEEM--------------KSSSASE
PKQTMSLMDLLEETDRQMGLTGSRYAMDEDEEYEEDEEDENNEEEGDSHGGGEGELSCCV
CMVKIKGASFTPCGH-TFCKLCSKELMAQ-KGHCPVCSSFVLEFLEIF-----
>AT1G30860.1|PACid:19654074
MVSSPQRFGLILRDRNQNAG---VFQKNLKSPVKEV--LKSHVSDENLVDSWIETHNNKN
NRVLESPLESKR-------NDNL-VASSLVQIWEARLNRSNGGNSPSSSQSTASSSSRSD
SGVSVQDSGLSESSSIDGDSEIADRTVEIESRSHGLVSDSGESKWGRVADLIRRLSNEDK
KRTAGDNGSGGGGGLEIIRTPRPYCTSSSSEKSNFPVVSFSPKIRGRQAFTDFLMQMERD
RHRELDSLFERNAVSRFTQRGRLQSMLRLRNLNRCLVIQDRNRSNAKTTGLNRIESGSAV
LHLREKFHANVVNSAAATDKRKNHQRSTEMNNKSVEETEGTTTTSTRLKDGGVTLEAFFA
ERLRPRNRKIEEATLCKEEESVSGTVDSQKNCLQLQETREVEETCNDGKSEKKEEENTSP
-SEYLSRESRLRQNQDENNVGKYMQETRETEGLVHESNEMDQCLDQQETSYLNRWGEQEE
YADEQSYYGEYNDDWLSEIARPRSYWEELRKSRYLEVMNTRSEKDDICRLLERRTVTD--
FLDSGLREKIDN----LMMSR---------------VQTHSDKHSKK-------------
--------------------------------------------------------WELQ
QEEEEEVNFEIDEEIKEEPLRGGEEQDDR-DDLSQSSSS---------------------
-----HISASSPAGSWSSQDTDVT---STPALVVQNPQSPEMELISGMRSQIQQLQQEMS
VLR-DSVKTCLDANASLQ---------------------------HKAHQENPMKRKCCV
CDETQVEAVLYRCGHMCMCLKCANELHWS-GGKCPICRAQIVDVVRVIYDTRN
>AT2G34920.1|PACid:19641615
MASLRPSFGSVLRDRNQRHNDDVVFKKNLKAQVKTAPPAISDESSENRVDSLIGNKRKKN
NKSRPGSPEKPRTRKGNNFSDNLGGASSLVQIWEARLNRSNGGNSAIHSQSIEISSEASV
QEIHLLAPSIDGESESENESKSPDQTVEIES-----------GTLNSVSDIIRRLSNE-Q
KLTASNN--GGAVDMPIVKTP-------TLEKSSFQVVTCSPRIRGRQAYSDLLVHLERE
RHRELESLLGRNAVSRFPQRGRLQSMLRLRSLKRGLAIQDRHRGTTK-SDLNRFQPSSTI
LHLREKLREKAANAAAEAGLKKGQQSTVETESMQSKETSG-------------ILHSPST
ERLSPQKRNIEEAILRKNE------TETKMSYLQLKKAIVAE-------VLERESDNTSP
LTSVTPQEPRILRNEEAGKLESGTEGTQET-----------PFLETQEMSFQSGWEEQEE
YEDEQSYYGDMSYDWFTEISRPRTYWEDLRKSRYLEVMNTKSDKDDICRLLERRTVSG--
FLQSGLREKIDK----LIMSR---------------VQIHPAH-----------------
---------------------------------------------------------RIE
EATKEEEKYDI----------GEEKDEDR-DDLSQ-SSS---------------------
-----QIFAPSPAGSWSSLDTGVT---STPTHNLHS-----------------TLQLEMS
ELR-DSVKTCLDVNASLQ---------------------------KSVHLENPFKRKCCV
CNETQVETLLYRCGHMCTCLRCANELQYN-GGKCPICHAKILDVVRVFVDSRT
>AT1G59560.1|PACid:19657702
MIHLAG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------FTCCLGGVALYLLTRSTGRD---IKSITRVYQLKD
LEQLVEVESKVVPLIIAVSGDVGSETPIKCEHSY--------------------------
---------------VLGVFLKRTAEQQVLRRN------WRFSWVRNSTLMQPMTKEVPW
YLDDGTGRVNVDVSQGELGLA---------------LTVGSDVFEKAEPVSLVQGA----
------------------LGYLKGFKILGVRHVERVVPIGTPLTVVGEAVRDGMGNVRIQ
KPEQ------------GPFYVTYIPLDQLISKLGDLSRR---------------------
-----FKYASMGLTV---LGVILISKPVIEYILKRIED---------------TLERRRR
QFA---LKRVVDAAARRA------------KPVTGG----------GTSRDGDTPDLCVV
CLDQKYNTAFVECGHMCCCTPCSLQLR-----TCPLCRERIQQVLKIY---RH
>AT1G63900.1|PACid:19655208
MIPWGG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------VTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKE
LAQLLELDSKILPFIVAVSGRVGSETPIKCEHSG--------------------------
---------------IRGVIVEETAEQHFLKHN------ETGSWVQDSALMLSMSKEVPW
FLDDGTSRVHVMGARGATGFA---------------LTVGSEVFEESGR-SLVRGT----
------------------LDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQ
KPDR------------GPFYVSSKSLDQLISNLGKWSRL---------------------
-----YKYASMGFTV---LGVFLITKHVIDSVLER---------------------RRRR
QLQK----RVLDAAAKRA------------ELESEGSNGTRESISDSTKKEDAVPDLCVI
CLEQEYNAVFVPCGHMCCCTACSSHLT-----SCPLCRRRIDLAVKTY---RH
>AT1G54150.1|PACid:19654958
MSSPERALLNLLTD----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------IALSFDGAILGLTLAVS------------------
--------------------AVGSALKYASTNAALKKIKDAPEVSISDLRSLLPASEDKS
ETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGDK----ALIIQRTQT---
YVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVIVGKDQQSNSSFVAVNMDGSRQP
LPLTTVYNRLQPINSSFLQAFLYPDYPVGLLDIEKILPPGKDITAVGIYSFNN-GVPEIK
SCQD------------LPYFLSEMTKDKMIEDLMEQTNF---------------------
-----IFLGSVILGI---VSVGILSYAAVRTWNKWKQW---------------NHQRELP
QRPNDSVVDDEPEDADEI----------------------------------PDGELCVI
CVSRRRVPAFIPCGHVVCCRRCASTVERELNPKCPVCLQSIRGSMRVY---YS
