>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|6149 641255358 AM1_6306 response regulator [Acaryochloris marina MBIC11017]
MQLTTPQAANILIVDDNLNNLKVLVGILSDSPYKIRRAVTGDIALQCITAAPPDLIML--
------------------------------------------------------------
-------------------------------------------------------DIILP
DFSGY-------------------------------------------------------
---------------------------EICAKLKQDPETASIP--IIFMSALSSN-----
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------ADKVK
AF----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------TVGGADYI------TKPFESTEVKARIRN
QLQ----LRAAQAQVKLLTAELEKMRTVQISQSGNN------------------------
---------------------------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|2810 alr2811 valine-pyruvate aminotransferase
M-----------------ILVCCTRLIFLSTLQLSLLLKLMNPALTKIGDQMSNLTGVRA
IMKDIIETLKSGGGQDLINLSAGNPLILPEVEQLWRDCTAELLASQEYGEVVCRYGSSQG
YAPLIEAVVKDFNRRYGLNLTDRNILITPGSQTLYFYAANVFGGYTSSGDLKQIVLPLSP
DYTGY------------------------GGICLVPEAL---------------------
---------------------------------------------VAYKPSLDID-----
------------------AAAHSFKYRPDF-SQVSISESTGCVIFSRPCNPTGNVLTDD-
EVRKIAALAAPYNVPVLIDSAYAPPFPALNFTDMSLIFGENILHCTSLSKAGLPGE----
------RIGIAIGNERLI------QVLESFQTNASLHSSRYGQAIAARAINSGALAQIAE
QV----------IRPFYKNKFAIVENALEAAMPKE-------------------------
------------------------------------------------------------
---------------------LPWFLHRGEGAIFSWLWLQDLPITDW-------ELYQEL
KKVGVIVVPGST-------------------FFPGLKE-----------EWAHKHQCVRI
SLT----GSDTEIALGMQRLAKAVEQIYQRTPISA-------------------------
---------------------------------
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|3117 637233195 alr2811 valine--pyruvate transaminase [Nostoc sp. PCC 7120]
M-----------------ILVCCTRLIFLSTLQLSLLLKLMNPALTKIGDQMSNLTGVRA
IMKDIIETLKSGGGQDLINLSAGNPLILPEVEQLWRDCTAELLASQEYGEVVCRYGSSQG
YAPLIEAVVKDFNRRYGLNLTDRNILITPGSQTLYFYAANVFGGYTSSGDLKQIVLPLSP
DYTGY------------------------GGICLVPEAL---------------------
---------------------------------------------VAYKPSLDID-----
------------------AAAHSFKYRPDF-SQVSISESTGCVIFSRPCNPTGNVLTDD-
EVRKIAALAAPYNVPVLIDSAYAPPFPALNFTDMSLIFGENILHCTSLSKAGLPGE----
------RIGIAIGNERLI------QVLESFQTNASLHSSRYGQAIAARAINSGALAQIAE
QV----------IRPFYKNKFAIVENALEAAMPKE-------------------------
------------------------------------------------------------
---------------------LPWFLHRGEGAIFSWLWLQDLPITDW-------ELYQEL
KKVGVIVVPGST-------------------FFPGLKE-----------EWAHKHQCVRI
SLT----GSDTEIALGMQRLAKAVEQIYQRTPISA-------------------------
---------------------------------
>Anabaena_variabilis_ATCC_29413_gnl|BL_ORD_ID|1705 gi|161567478|ref|YP_321609.2| avtA gene product [Anabaena variabilis ATCC 29413]
M----------------------------------------NPALTKIGDQMSNLTGVRA
IMKDIIETLKSGGGQDLINLSAGNPLILPEVEQLWRDCTAELLASQEYGEVVCRYGSSQG
YAPLIEAVVKDFNRRYGLNLTDRNVLITPGSQTLYFYAANVFGGYTGNGDLKQIVLPLSP
DYTGY------------------------GGICLVPEAL---------------------
---------------------------------------------VAYKPSLDID-----
------------------AAAHSFKYRPDF-SQVSISESTGCVIFSRPCNPTGNVLTDD-
EVRKIAALAAPYNVPVLIDSAYAPPFPALNFTDMSLIFGENILHCTSLSKAGLPGE----
------RIGIAIGNERLI------QVLESFQTNASLHSSRYGQAIAARAINSGALAQIAE
QV----------IRPFYQNKFAIVENALEAAMPKE-------------------------
------------------------------------------------------------
---------------------LPWFLHRGEGAIFSWLWLQDLPITDW-------ELYQEL
KKVGVIVVPGST-------------------FFPGLKE-----------EWAHKHQCVRI
SLT----GSDTEIALGMQRLAKAVEQVYQRTPVSA-------------------------
---------------------------------
>Synechococcus_sp_PCC_7002_gnl|BL_ORD_ID|393 641610245 SYNPCC7002_A0235 valine-pyruvate aminotransferase [Synechococcus sp. PCC 7002]
M--------------------------------------SQAPLLSKFGTQMSRLTGVRA
IMKDIIDTLKAGAGQDFINLSAGNPVIIPEVEQLWRDCTNDLLNSPEYGEVVCRYGSSQG
YEPLIEAIATDFNQRYGLNLTGENILITPGSQSLYFLAANAFGGYDHVGQLKSIILPLSP
DYTGY------------------------GGVSLYPEAI---------------------
---------------------------------------------RAFKPSLDID-----
------------------QVNHRFKYRPDF-SQLNIDENTGCVIFSRPCNPTGNVLSDE-
EAEKIADLAAVHDVPVFIDSAYAPPFPALNFTEMKPLFGGNVIHCLSLSKAGLPGE----
------RVGIAIGEPRFI------GVLQAFLTNACIHSSRYGQAIAARAIQSGALANIAE
TV----------IRPYYQNKIQILEAALDRAMPKD-------------------------
------------------------------------------------------------
---------------------VPWYLHRGEGAIFAWLWFDELPMTDW-------ELYQEL
KAVGVIAVPGSP-------------------FFPGLRE-----------DWPHKQQCLRI
SLT----ATDSEIEMAMERLAKVVKKVYAK------------------------------
---------------------------------
>Cyanothece_sp_BH68_ATCC_51142_gnl|BL_ORD_ID|5037 641679458 cce_4951 hypothetical protein [Cyanothece sp. BH68, ATCC 51142]
M-----------------------------------------------------------
---------KSDEAGVRLYFDGGT------------------------------------
-------------------------------------------------------FPLNP
GHGGC------------------------GAVIIQENDE---------------------
---------------------------------------------QSFSKYLGEN-----
---ITNNQAEYGGLILGLEKA----LEMNI-SSLEVKGDSELVI----CQVIGSY-----
-------------------------------------------RCRNSGLRPLHRQ----
------AISLAKQFEHIHFDWIPREINKKADAAATEAIQSVLPQSKAIIPDNLPLCKARE
GL---------KKR----------INRLNQ------------------------------
------------------------------------------------------------
-------------------------------------QGDGAKFKEWIQLKSGRDQFSSL
RGARLHEAVPDS-------------------VIDAISQA------LIEDEQDLLDKSLRW
YLR----GLKPALALKKARVDAEISANITRKKSAL-------------------------
---------------------------------
>Lyngbya_sp_CCY_8106_gnl|BL_ORD_ID|2306 640016327 L8106_19221 formate dehydrogenase accessory protein [Lyngbya sp. CCY 8106]
MSAAKSKKKSNIWTIEESQIRSRLDDIATEEPLEIRLVSPAQTLAVTMRTPGADFDLVTG
FLYSEGVITSREDISKMS------------------------------------------
-------------------------------------------------------YCVDP
DIDGE-------------------------------------------------------
------------------------------------QRQNIIN--VALKSGLTFD-----
-----------------------------------FKRLERHFFMTSACGVCGKASIESL
KFRELPQISSDFN-----------------------------------------------
-----------VNTEIIY------RLNDQLKLAQGLFSATGGLHAAALFNSQGKLLKLRE
DV----------GR----------HNALDK------------------------------
------------------------------------------------------------
-------------------------------LIGSSLLTDDLPLAHHIVMVSGRSSFEIL
QKCIVAGVPILC-------------------AVSAPSSL------AVEIAQ-AFNITLIG
FLR----GRRFNIYSGIERIKLAS------------------------------------
---------------------------------
>SP1_NM_105064
M--IPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVA
VSGRVGSE----------------------------------------------------
-------------------------------------------------------TPIKC
EHSGI------------------------RGVIVEETAE---------------------
------------------------------------------------QHFLKHN-----
---ETGSWVQDSALMLSMSKEVPWFLDDGT-SRVHVMGARGATG----------------
----------------------------FALTVGSEVFEESGRSLVRGTLDYLQGL----
------KMLGVKRIERVLPTGIPLTIV-------GEAVKDDIGEFRIQKPDRGPFYVSSK
SLDQLISNLGKWSRLYKYASMGF-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------TVLGVFLI------TKHVIDSVLERRRRR
QLQ----KRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVP
CGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>Cyanothece_sp_CCY_0110_gnl|BL_ORD_ID|247 640623896 CY0110_10837 histidyl-tRNA synthetase [Cyanothece sp. CCY 0110]
MGTIQTLPGTRDILPEEIGYWQYVESIATQILSRAMYYEIRPPIFEQTSLFERGIGEATD
VVGKEMYTFSDRGDRSLTLRPEGTAGVVRAYLQNNLYAAGGVQRLWYCGPMFRYERPQAG
RQRQF--------------------------------------------------HQIGL
ELIGT---------------------------------------------------ADPR
ADVEVIALATDILKTLGLQSLKLDINSVGDRNDRQRYREALVNYFLPYKEELDPD-----
----SQDRLQRNPLRILDSK--------DK-RTKEINENAPSIL-----EHLGDASKK--
HFDQVQQLLSDLGIEYNINPCLVRGLDYYTHTAFEMISDDLGAQATVCGGGRYDGLVEEL
GGNATPAVGWAIGMERLI------ILLKQLQSSPEMTPDIYLVSRGEAAEGQG--LILAQ
KL----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
RKEGLTVELDMSGSAFGKQFKRADRSGAIACIVLGEEEAENKTMQLKWLQSKEQQAMTQA
ELF----TKVGELKEQLDRHKRTMNHSTQ-------------------------------
---------------------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|4197 647568581 MC7420_6143 Roadblock/LC7 domain superfamily [Microcoleus chthonoplastes PCC 7420]
M---------------------------------AINAEKLGMIIKDFASATSDVEGA--
------------------------------------------------------------
-------------------------------------------------------AVVTP
D--GL-------------------------------------------------------
------------------------------------------PLATTLPSGMDDE-----
------RVSAMSAAMLSLGERIGKELVRGTIDRIYVEGAKGFSV----------------
----------------------------LTSCGEDTVF----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------LVLATKAAKQGLLML
EIK----RTVGELQMVLS------------------------------------------
---------------------------------
>Prochlorococcus_marinus_MED4_gnl|BL_ORD_ID|1662 PMM1666 SqdX
M-----------------------------------------KIAFFTETFLPKVDGIVT
RLTKTIEFLTKNGDEVIVFCPEGCPDSYKGAT-----IVGVAAMPLPLYPELKLGLPGPA
VSDKLEEFKPDLV------------------------------------------HVVNP
AVLGL------------------------GGIWLAKTNN---------------------
--IPLIASYHTHLPKYLEHYGMGMLEPLLWELLKAAHNQALLN--LCTSTAMVNE-----
---LEDKGIQRTALWQRGVDTENFRPELRS-EKMREKLFGKYQNTDSLLIYVGRLSAEK-
QIERIKPVLDNIP----------------------------GACLALVGDGPYRGQLEKI
FENTNTNFIGYLSGEELASAYASGDIF-LFPSSTETLGLVLLEAMAAGCPVIGANKGGIP
DI----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------INNGINGCLYNPDEKDNGERSLIEATKKI
LAD----KNKKEAMRKEARKEAEQWDWNQATLQLQKYYAETLENIS--------------
---------------------------------
>Prochlorococcus_marinus_pastoris_CCMP1986_gnl|BL_ORD_ID|1666 gi|33862222|ref|NP_893783.1| SqdX [Prochlorococcus marinus subsp. pastoris str. CCMP1986]
M-----------------------------------------KIAFFTETFLPKVDGIVT
RLTKTIEFLTKNGDEVIVFCPEGCPDSYKGAT-----IVGVAAMPLPLYPELKLGLPGPA
VSDKLEEFKPDLV------------------------------------------HVVNP
AVLGL------------------------GGIWLAKTNN---------------------
--IPLIASYHTHLPKYLEHYGMGMLEPLLWELLKAAHNQALLN--LCTSTAMVNE-----
---LEDKGIQRTALWQRGVDTENFRPELRS-EKMREKLFGKYQNTDSLLIYVGRLSAEK-
QIERIKPVLDNIP----------------------------GACLALVGDGPYRGQLEKI
FENTNTNFIGYLSGEELASAYASGDIF-LFPSSTETLGLVLLEAMAAGCPVIGANKGGIP
DI----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------INNGINGCLYNPDEKDNGERSLIEATKKI
LAD----KNKKEAMRKEARKEAEQWDWNQATLQLQKYYAETLENIS--------------
---------------------------------
>Synechococcus_sp_PCC_7335_gnl|BL_ORD_ID|1381 647577621 S7335_4709 DNA-directed RNA polymerase, gamma subunit [Synechococcus sp. PCC 7335]
M-----------------------------------------------------------
----------------------------PKVEQRFDYVKIGIASPERIREWGERTLPNGT
VVGEVTKPETINY------------------------------------------RTLKP
EMDGLFCERIFGPAKDWECHCGKYKRVRHRGIVCERCGVEVTESRVRRHRMGYIKLAAPV
AHVWYLKGIPSYIAILLDMPLRDVEQIVYFNAYVVLDAGNADN--LSYKQLLSEDQWMEI
EDQLYAEESQLSGIEVGIGAEALKRLLEDL-QLEETAEMLRETI------ATSKGQKRA-
KLIKRLRVIDNFIATGSNPDWMVLDVIPVIPPDLRPMVQLDGGRFATSDLNDLYRR----
------VINRNNRLARLQEILAPEIIVRNEKRMLQEAVDALIDNGRRGRTVVGANNRPLK
SLSDIIEGKQGRFR----------QNLLGKRVDYSGRSVIVVGPNLKIHQCGLPREMAIE
LFQPFVIHRLIRQGLVNNIKAAKKLIQRSDPSVWEVLEDVIENHPVMLNRAPTLHRLGIQ
AFEPIMVEGRAIQLHPLVCPAFNADFDGDQMAVHVPLSLEAQSEARLLMLASNNVLSPAT
GRPIITPSQDMVLGCYYLTADNPSKQKGAGRYFANMEDA------IAAYEQGNVDLHAKV
WLRFVGDVETAEEDNEPIKVEEDGNGGSTKTYKFRRVREDESGNV---------------
---------ISQYVETTPGRIIYNHAVLGALAE
