>gnl|BL_ORD_ID|6149 @Acaryochloris_marina_MBIC11017@ 641255358 AM1_6306 response regulator [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------QLTTPQAANILIVD-------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------DNLNNLKVLVGILSDSPYKIR
RAVTGDIALQCITAAPPDLI-MLDIILPDFSGYEICAKLKQDPETASIPIIFMSA---LS
SNADK--------VKAFTVGGADYITKPFESTEVKARIRNQLQLRAAQAQVKLLTAELEK
MRTVQISQSGNN------------------------------------------------
---------
>gnl|BL_ORD_ID|2329 @Acaryochloris_marina_MBIC11017@ 641251507 AM1_2413 transketolase, putative [Acaryochloris marina MBIC11017]
MTTFPIDLKAYKPLTLDASNPTLTPEQRETLKSNIQLCRDAIVFFTATGAARGVGGHTGG
PYDTVPEVMILDALFRGSADKYVPIFFDEAGHRVATQYLMSTLEGSLPAEQLMSYRAANS
TLPGHPELGLTPGVKFSSGRLGHMWPYVNGVALANPGKTAFCLGSDGSQQEGNDAEAARL
AVAQQINVKLLIDDNDITIAGSPSDYLPGFSVKKTLEGHGLKVLEGDGEDIDGLYARICE
AINTPGPVAVINKRAMCVGIDGLEGSNHGHDVISVDAALKYLEARGHSDAVSNLKSVVKP
SQDYTFLGASEKYDSNRNVFGDA-VVEVLSGMSEAD--RKAKVLVVDSDLEGSCGLHKIR
AANPEIFISGGIQERGNLSAAAGFGMAAGKQGIFATFSAFLEMCISEITMARLNKSNLLC
HFSHAGIDDMADNTCHFGINNMFADNGLDDGYETRLYFPADANQMKACVKSVFDNSGLRF
IFSTRSKVPLLTDANGGELYAGNYTFTPGKDEVVREGTAGYIVSFGEA---LYRSLDAVE
RLKKEGIDVGLINKSTLNVVDEDMMKKIGAAPFVVVVE-------------SFNRRTGLG
SRFGSW-LLERGLSPKFAYLGT----------------------------------HEEG
CGGL---------------------WEQFPHQGIDPVGIMKTVKSLAS------------
---------
>gnl|BL_ORD_ID|2810 @Anabaena_sp_PCC_7120@ alr2811 valine-pyruvate aminotransferase
MILVCCTRLIFLSTLQLSLLLKLMNPALTKIGDQMSNLTGVRAIMKDIIETLKSGGGQDL
INLSAGNPLILPEVEQLWRDCTAELLASQEYGEVVCRYGSSQGYAPLIEAVVKDFNRRYG
LNLTDRNILITPGSQTLYFYAANVFGGYTSSGDLKQIVLPLSPDYTGYGGICLVPEALVA
YKPSLDIDAAAHSFKYRPDFSQVSISESTGCVIFSRPCNPTGNVLTDDEVRKIAALAAPY
NVPVLIDSAYAPPFPALNFTDMSLIFGENILHCTSLSKAGLPGERIGIAIGN--ERLIQV
LESFQTNASLH-------------------SSRYGQAIAARAINSG----ALAQIAEQVI
RPFYKNKFAIVENALEAAMPKELPWFLHRG-----------EGAIFSWLWLQDLPITDWE
LYQELKKVGVIVVP-GSTFFPGLKEEW----AHKHQCVRISLTG--SDTEIALGMQRLA-
------------------------------------------------------------
-------------------------------------------KAVEQ------------
------------------------------------------------------------
--------------------IYQRTPISA-------------------------------
------------------------------------------------------------
-------------------
>gnl|BL_ORD_ID|6092 @Anabaena_sp_PCC_7120@ alr8560 reverse transcriptase homolog
MTWIV-------------------------------------------------------
------------EVQVAMYTSKTSFKTTVEWNAIPWQ-----------------------
----------------------------------------------------------KL
ERKVFKLQKRIYKASQRGDVKAVRQLQKTLLHSWSAKCLAVRRVTQDNRGKKTAGVDGRK
NL--------SPKARLILVQSMKLGDKASPTRRVWIPKPGSSGEKRPLSIPTLYDRALQS
LVKLALEPEWE-------------------ARFEPNSFGFR---PG----RNAHDAMKAI
FNTIKFKPKYV---LDADIAKCFDKIDHNVLLSKLNTFPTISRQIRAWLKAGVIDFSEYA
LREKSDHTTSMGVPQGGTISPLLANIALHGMENRIKQVALTLPGCKSENRQAISLIRFAD
DFVILHKDLAVIQRCQQIISEWLSELGLELKPSKTRISHTLNMYEGKVGFDFLGFTVRQF
PVGKYHSGKSSSGKLLGYKTLITPSKAKLKIHAQKIGKLIDEHKAVPQSDLIAHLNPVIR
GWTNYYSCVVSKRIFNQADTTLFSQLKAWAEHRHPNKSSRWSCQKYWQTVGSDNWVFKPH
NQKIRLLKHRETRIVRHIQVKGSRSPFDGDWVYWSSRMGKHPEAPIRVATLLKMQKGKCT
HCGLFFHHEDLMEIDHKIPRSQGGKDSYDNLQLL--------------HGHCHDAKTAED
KCAVTVPELDEDYLNLNPF
>gnl|BL_ORD_ID|1705 @Anabaena_variabilis_ATCC_29413@ gi|161567478|ref|YP_321609.2| avtA gene product [Anabaena variabilis ATCC 29413]
MNPALTKIGDQMSNLTGVRAIMKDIIETLKSGGGQDLINLSAGNPLILPEVEQLWRDCTA
ELLASQEYGEVVCRYGSSQGYAPLIEAVVKDFNRRYGLNLTDRNVLITPGSQTLYFYAAN
VFGGYTGNGDLKQIVLPLSPDYTGYGGICLVPEALVAYKPSLDIDAAAHSFKYRPDFSQV
SISESTGCVIFSRPCNPTGNVLTDDEVRKIAALAAPYNVPVLIDSAYAPPFPALNFTDMS
LI-FGENILHCTS--------LSKAGLPGERIGIAIGNERLIQV--------------LE
SFQTN-ASLHSSRYGQAIAARAINSGALAQIAEQVIRPFYQNKFAIVENALEAAMPKELP
W---FLHRGEGAIFSWLWLQDLPITDWELYQELKK-VGVIVVPGST--------------
----FFPGLKEEWAHKHQCVRISLTGSDTEIAL----------GMQRLAKAVEQVYQRTP
VSA-----------------
>gnl|BL_ORD_ID|521 @Anabaena_variabilis_ATCC_29413@ gi|75812808|ref|YP_320425.1| flavin oxidoreductase/NADH oxidase [Anabaena variabilis ATCC 29413]
----------------------------------MDLFTPLIIRDITLP-----------
----SRVAMSPMCQYSAENGFA-------------------NDWHFVHLGSRAV------
-------------------------GGTGLIMVEATAVTPQGRITPGDLGL-----WDDK
QIEPLTRIVRFLRQQGSVTGIQLAHAGRK-----ASCNVPWLGGTPLTPEQGGWQPVAPS
PIPFQENAPVPIS--------LDERGIQETIFAFVAAAQRALQVGFQMIEIHAAHGYLLH
SFLSPLSNRRTDRYGGSL--------------ENRMRLLLE-----VVRRVRDVLPNGMP
L---FVRISATDWVEGGWDLQQSII---LSRELKT-LGVDLIDVSTGGLVPHARIPVEKG
YQVPFAAKIREEAGIMTGAVGLINEAEYADQIITRGCADLVLIGRELLRNPYWSIYARCS
LDEEPNWPVPYGYAVKRQRR
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPF----I
VAVSGRVGSETPIKCEHSG----IRGVIVEE-TAEQHFLKH-----NETGSWVQDSALML
SMSKEVPWFLDDGTSRVHVMG---ARGATGFALTVGSEVFEESGRSLVRG-TLDYLQ---
-----GLKMLGVKR--IERVLPTGIP--------LTIVGEAVKDD---------------
---------------------------------IGEFRIQKPDRGPFYVSSKSLD-----
----QLISNLGKWS--RLYKYASMGFTVLGVFL----------------ITKHVIDSVLE
RRRRRQLQKRVLDAAAKRAE---LES--------EGSN----GTRESISDSTKKEDAVPD
LCVICLEQEYNAVFV-----PCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>SP1_NM_105064
MI---------------------------------PWGGVTCCLSAAALYLLGRSSGRDA
EVLETVTRVNQLKEL--AQLLELDSKILPF------------------IVAVSGRVGSET
PIKCEH---------SGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDD
GTSRVHVMGARGATGFALTVGSEVFEE---------------------------------
--------------------------------------------SGRSLVRGTLDYLQGL
KMLGVKRI----ERVLPTGIPLTIVGEAV-----------KDDIGEF-----RIQKPDRG
PF----------------YVSSKSLDQLISNLGKWS--RLYKYASMGFTVLGVFL-----
--------------ITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGS-------NG
TRESISDSTKKEDAVPDLCVICLEQEYNAVF-----VPCGHMCCCTACSSHLTSCPLCRR
RIDLAVKTYRH-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>gnl|BL_ORD_ID|1897 @Arthrospira_sp_PCC_8005@ 648387126 APCC8_010100009866 primosome assembly protein PriA [Arthrospira sp. PCC 8005]
MHKSSVVLYGGAIESPSVSSRLFPKSDPLPLKLAEGGLSYGSENWGGNGDHQLVEVLVDI
PTLRQTEDTEDIEQ------LYTYQVPPHLDIMPGDILSVPFGAQ---------------
--QIGAIAIRLTS------ELPENLREPGKATSIKVRPVEDITVKGFFPPNYWQLLQQVA
QYYQTPLIKAIRTALPPGLLRRSQRRIRLVTNAIPDGAEEFLQPKAQRILQL--LRQSAT
GDYTWQYLQRQIKG---GSR--------GLQDLIKRGWVESYLEPPTPPRPKLRPAITLV
IDWVELDFIDITTRQREVLEILRRRGGEMWVTDLLQTCNTSSSLLKTLEKKGCVVIGDRE
ILRTEQGISTIADQPLSLTEHQQQALDVILGLSGFHQLLLHGVTG------------SGK
TEV-----YLQAI---------------------------------------APIIDQGK
SALVLVPEIGLTPQLTDRFRARF---GEVVFVYHSGLSEGER----------YDTWRNMI
QGTPQVVIGTRSAIF------APLPNLGIIVLDEEHDSSFKQDQPQPCYHARTVAAWRAE
LENCPLILGSATPALETWQHHRHNHNPSIHYLSLPERVLSRPQPPVEVVDMRRELKQGNR
SIFSRSLQLAIASLRDNNQQGILFIHRRGHSTFVSCRSCGYVMECPRCDVSLSYHHIHAE
AIPYLRCHYCNHSQSYPQRCPQCDSPYFKHFGSGTQRVAQELTRLFPELRFIRFDSDTTR
TKNAHRILLTQFANREADLLVGTQMLTKGLDLDSVGLVGIVSADGLLHLSDYRASERAFQ
TLLQVAGRAGRGNDPGQVILQTYTPEHPVVEAVRNHAYQSFVETELQHRSELNYSPSGGL
ILLQLRGYNAIEVEQTAHLLASELSSDLLPGTCELLGPAPAPIMRVANQYRWQILLKFLP
GQTTPPPSLAALAEKCPPSVRFSIDVDPLSFG
>gnl|BL_ORD_ID|286 @Arthrospira_sp_PCC_8005@ 648385504 APCC8_010100001514 hypothetical protein [Arthrospira sp. PCC 8005]
M--------------------INRDKDFCFCTLALG------EKY-----RRLVKQL---
--------AQDIQQYSPGTSLVVYTDLPEDLRDQNNILAFPHQSQGVLYCFHDRRFVIEK
ALSLFRVAIHIDADTTIIEEVPEIDWQPGITSGQGKFP----NIIGHLDAKEKYLGEKIP
KEREA--FHKIASKLGISLENTFWIQEALYIVARDEGREKEFIKQWGRIGRYLELRQIHR
GDGNAIGLAAAKVGWTVNTH--------GFQDLIK---VRRHLDASKDPTEKL-PNSQLK
TMGDELKF---KLKYHSRLNLARIKALKDW------------------------------
------------------------------------------------------------
-EF-----Y---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------YG
>SP1_NM_105064
M-----------------------------------------------------------
----------------------------------------IPWGGVTCCLSAAALYLLG-
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------RSSGRDAEV
LETV-------------------------------------------------TRVNQLK
E---LAQLLE-LDSKI-LPFIVAVSGRVGSETP---IKCEHSGIRGVIVEETAEQHFLKH
NETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATG----FALTVGSEVFEESGR
SLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFY-VSS
KSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKH----------------VIDSV----
--------------LERRRRRQLQKRVLDAAA------------------KRAELESEGS
NGT--------------RESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCT---
---------------------------------------------------------ACS
SHLTSCPLCRRRI-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------DLAVKTYRH-------------------------------
-----
>gnl|BL_ORD_ID|1760 @Cyanobium_sp_PCC_7001@ 647590049 CPCC7001_1734 ribonuclease H [Cyanobium sp. PCC 7001]
M-----------------------------------------------------------
--------VAAACDGACSGNP----------------------------GPGGWGALLRF
EDGSV--HEMGGAEADTTN-------NRMELTAA--------------------------
-----------------------------LALLEAL--RDLPRHPDLAIRTDSRYLID--
---------GLGKWIQGWKRKGWRTASGGAVLN---RDLWEKLDRARLADVPLRHVRGHS
G-------------------------------------------------DP--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------DNERCDTIAV
AFSRGR-------------IPPLQEGEVLGMARLEADVPAMAPEAVEPRPGREPTALGDA
SG---EDP-----APAA------LQQLL----------SRLEWADRV-AEQAYGLTLVEL
AQLVEQPLRNLERRTRPWTW----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------RDWRVEPIGDGRWRLRR
GTAGLGDGR---------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|2656 @Cyanothece_PCC_7424@ gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424]
M-----------------------------------------------------------
--------------------------------I-LIGII----------CLIVGVILLFF
WRSNRSKLRNLRLASA-------------------------------------------S
TISS--------------------------------------------------------
-------------LQTIANQI-------------AEEIGGGSLREYVKIRGVIECDRPLI
SQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKT-IREKERKSETVAQNSRSIPFTLQDSTG
EIRVNPE-R-----A--EIETVKVL-----------------------------------
------------------------------------------------------------
-------------------------EEFRPENFSGGSLTFGNFSINLPS-----------
-----------FEERRQTIGY---------------------------------------
----------------------RYQ-------EEILPI----------------------
------------------------------GRQIL-------------------------
-------------------------------------VIGTAT-DEEGM-ITIRKPTEK-
--GQRYFISLKSEEELSQA-----TNNAIRGTFYSMIFFL--------------------
--TLGLILLVA--------------------------GVL--------------------
------------------------------------------------------------
------------------------------------------------RG
>gnl|BL_ORD_ID|497 @Cyanothece_PCC_7425@ gi|220905952|ref|YP_002481263.1| unnamed protein product [Cyanothece sp. PCC 7425]
M-----------------------------------------------------------
----------------------------DMPN------LMPQQT----------------
QPIHRTTTGQLPAEL---------------------------------------------
------------------------------------------------------------
----------------------------------------------------------AE
LSEESLTHS---------------------------------------------------
------------------------------------------------------------
-----------------------------SSVLPSIP---SLCCIC---DTNVCVLICVV
L-----------------------------
>gnl|BL_ORD_ID|4224 @Cyanothece_PCC_7822@ gi|307154170|ref|YP_003889554.1| RNA-directed DNA polymerase [Cyanothece sp. PCC 7822]
M----------------------------------------NKEQTEYSDWQSINWKQIE
KTVWK-------------------------------------------------------
--------------------------------------LQKRIYRAKVEGNQKLVKKLQR
LLVNSRSAKALAIRKVTQDNRGKRTAGIDGKKALKPKERFTLLSELKISGKSKPLRRIYI
PKPNGEKRPLSIPTIKDRATQMLVTLALEPEWEAVFEPNSYGFRKGRSCHDAISAIFNQI
RFKNKWVLDADIAKCFDKINHNYLLEKLGDTLIGFKRQIRAWLKSGYREGKELFPS-TEG
TPQGGVISPLLANITLHGIE-NYLNEWVKTWKGSKGRGKRDNLRSFAFIRYAD-------
-----------------D-----------------FVCIHESKEVIEKAKELISQ-----
-YLKPIGLELKPEKTQVVHTLEGFD-----------------------------------
------------------------------------------------------------
-----------------------------------FLGCNIRHYPK----------GKHH
CGKH--------------------------------------------------------
-----NNKLIGFKTLIKPSDKA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------IKRHYDTIA
NQIRENKSISQE-------GLIGLLNPII----------------RGWCNYYQPYVSKKI
FSHFN---------DLIYRILKRWMLRRHPN---------KSLKWIKEKYYKKVEL----
-------RNWVFKSAKGHELIQHNHTKI-----RRHIKVQDVKSPYDGDVVYWGERLSKS
LE-LTTREQ-----KLLKKQKGDCPICG--------EKFKAGDLWEVDHIIPKSLGGKD-
------------------------------------------------RYENL------Q
LIHAHCHDKKTRTDG--------------SLKTRYS------------------------
------------------------------------------------------------
------
>gnl|BL_ORD_ID|3195 @Cyanothece_PCC_8801@ gi|218247992|ref|YP_002373363.1| hypothetical protein PCC8801_3232 [Cyanothece sp. PCC 8801]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------KTLITLKIEKFEEKGQE-----------Y
FVATSDQIQGL-VAEGDTIEEVVEIASDLAKILIE-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------NAAAIANKV-------------------------
-------------------------------N
>gnl|BL_ORD_ID|703 @Cyanothece_PCC_8801@ gi|218245500|ref|YP_002370871.1| hypothetical protein PCC8801_0627 [Cyanothece sp. PCC 8801]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------RPVIRGEVKD----KNTDFTKYEDAKPYLIKNIGEYC
SYCERRVTNLLAVEHIQPKEHYPELELVWGNFLLACTNCNSIKGQKNINLSDYFWCNRDN
TFRVFTYFDGVVNINNQLTLIEQNIGKKTIDLIGLDRVPGHRKYSNKDTRWQKRRDIWGK
AQRSYDNLQ------NNNTEELRQTIVDLA------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----LESGFWSIWMT--------------------------------------------
------------------------------------VFNDDKDMLKRF------------
-------------------------------------IEAFPGTCQNCFDQDFNAVPRPG
G-----------------------------IV
>SP1_NM_105064
M-----------------------------------------IPWGGVTCCLSAAALYLL
GRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGV
IVEETAEQ--------------HFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHV
MGARGATGFA--------------------------------------------------
----------------------------------LTVGSEVFEESGRSLVRGTLDYLQGL
KMLG--VKRIERVL--------PTGIPLTIV-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------GEAVKDDI
GEFRIQKPDRGPFYVS--------------------------------------------
-----------SKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQ
LQKRVLDAAA--------KRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAV
FVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>gnl|BL_ORD_ID|5037 @Cyanothece_sp_BH68_ATCC_51142@ 641679458 cce_4951 hypothetical protein [Cyanothece sp. BH68, ATCC 51142]
M-----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------KS
DEAGVRLYFD--------------GGTFPLNPGHGGCGA---------------------
-------------------------------VIIQ-------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ENDEQSFSKYLGENITNNQAEYGGLILGLEKA------LEMNISSLEVKGDSELV
----ICQVIGSYRCRNSG-------LRPLH-----RQAISLAKQFEHIHFDWIPREINKK
ADAAATEAIQSVLPQSKAIIPDNLPLCKARE-GLKKRINRLNQQGDGAKFKEWIQLKSGR
DQFSSLRGARLHEA------VPDSVIDAISQALIEDEQDLLDKSLRWYLRGLKPALALKK
--------------ARVDAEIS-------ANI------------TRKKSAL---------
--------------------------------------------------------
>gnl|BL_ORD_ID|2226 @Cyanothece_sp_BH68_ATCC_51142@ 641676625 cce_2136 hypothetical protein [Cyanothece sp. BH68, ATCC 51142]
M------KV----EVKATLLEWACRRGGLDDETLLSAFPKLPEWKEGKSQPTLKQLEKFA
QKNRVPLGMLFLPSPPVEKLPIADFRTIKNNNINEPSQNLLETIYLCQQIQEWYSQHLRD
NGFNENEFVGCV------------------TIENSVTEVAQNIRDVVSFSLEERQQLTNL
EDTRRFFIAQVRKLNILVIISGIVGNNTYRSLDPDEFRGF--------------------
-------------------------------VLID-------------------------
------------------------------------------------------------
------------------------------------------------------------
-----RFSPLIFING---KDT-----KSAQIFTLAHELAHIWLGSEGISNIEIADVRNQD
AHEIWCNQVAAEL------------LVPLE-----DELKRLAKIYQVSSLVITRRLYDLK
--VYDYQEFRNIYEQE----LDDFQLSRKQK-----------KKKDGGDFYRNLNAKMGY
QFLQALVSSTLE-----------------GKTLFRDAFRLL---------------GIKK
--------------SEAFYNIA-------NNL------------TEG-------------
--------------------------------------------------------
>gnl|BL_ORD_ID|2314 @Cyanothece_sp_CCY_0110@ 640625972 CY0110_00380 transcription-repair coupling factor [Cyanothece sp. CCY 0110]
M------VF---------------------------------------------------
------------------------------------------------------------
------------------------SSLIR-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------TLQKST-------------------------------
----------------LTKELLDKLKGNKELGLKGINRLPKGLISSA--LAQANQQNLLV
IC----A----TL---EEAGRWTAQLEIMGWKT---VSFYPTTEASPYEPLNPESEMIWG
QMQVLSNLNLSVTENNNYAIVTTEKALQPHLPPPESFHKYCLNLQTGITEKSKIFDEALV
KLGYERVNLVEVEGQWSRRGDIVDIFPVSSEVPIRLEWFGDELEKIREFDPATQRSLDSI
ESILLTPVSFNTIIANTIKENDYNLDNYLSKEEKEGLENYNYPSGMQRFLGIAFDEPACI
LDYVNLNTLCVFDEIEQCKSHSDRWLDYIEENWQDQEKSVPKIHRSFDDSLQLTQEFSKL
YLSELSEVNNKNALDLSSRPLPTTPHQFAKLAEI-LRGKREIYSGITLDKYATWLISAQP
SRTVSLLQEHDCPAQFIPNLRDYPAINKSHIQGTAIALKYSGLAELEGFILPTFRIVVVT
DKEFFGQHVLATAGYIRKRRRATSKKVDLQQLHPGDYVVHKSHGIGKFL---KLESLATR
EYLVVQYADGILRIPADSFDS-------------LSRYRHTGSTPPQLHKMTGKMWQKSK
QRVRKNIKKLAVD-LINLYAKRAKNVGFT-------YPLDTPWQQELEDSF--PYQPTPD
QLKAIQDVKIDLESDRPMDRLVCGDVGF------------GKTEVAVRAIFKAVTSG---
--------H----------------KQVAFLAPTTILTQQHYHTLKERFAP--YPINI--
-----GLLNRFRTNSEKK---EIIDR---------LATGELDIVVGTQ------------
----------------QLLGKSIKFKDLGLLVVDE-EQ-RFGVNQ------KEKIKDMKS
HVDVLTLTATPIPRTLYMSLSGIREMSLI-------TTPPPSRRPIK-------------
--------------------THLSRYNPDVVRTAIRNELDRGGQVFYVVPRVEGIEEVAA
ELKKMVPSARIAIGHGQMNVNDLEMTMLSFNNGDADILVCTTIV-----ESGLDIPRV-N
TIIIEDAQKFGLAQLYQLRGRVGRA---------GIQAHAW-----LLYPSKAQLTE--T
ARKRLRALQEFSQLG----SGYQLATRDMEIRGVGNLLGAEQSGQMESIGFELYMDMLQE
AIKE--------IQGQEIPKVED-TQVDLQLTAFIPTDYIPDM-EQKMSAYRAIAV-ANS
K----------KELAQIAAEWNDRYGKLPIPVQQLLQVIEL-------------------
KQLAKSLG---------FSR-------IKPEGKQNIVLETPMEEPAWKLLEENLPAH---
-LR---------------------------------SRFVYT------------------
----PKKV--------------------------------TVRGLGVM------------
-------KPQKQLESL-------LEWL-------GKMQDAI---PVTS------------
------------------------------------------------------------
-------------------------------EY
>gnl|BL_ORD_ID|247 @Cyanothece_sp_CCY_0110@ 640623896 CY0110_10837 histidyl-tRNA synthetase [Cyanothece sp. CCY 0110]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------GTIQTLPGTRD--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------ILPE-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------EIGYWQYVESIATQI----------
---------------------------------LSRAMYYEIRPPIFEQTS----LFERG
IGEATDVVGKEMYTFSDRGDRSLTLRPEGTAGVVRAYLQNNLYAAGGVQRLWYCGPMFRY
ERPQAGRQRQFHQIGLELIGTADPRADVEVIALATDILKTLGLQSLKLD--INSVGDRND
RQRYRE--------ALVNYFLPYKE-----------ELDPDSQDRLQRNPLRILDSKD--
--------------------------------------------------------KRTK
EINENAPSILEHLGDASKKHFDQVQQLLSDLGIEYNINPCLVRGLDYYTHTAFEMI---S
DDLGAQATVCGGGRYDGLVEELGGN---------ATPAVGWAIGMERLIILLKQLQSSPE
MTPDIYLVSRGEAAEGQGLILAQ---------------------KLRKEGLTVELDMSGS
AFGKQFKRADRSGAIACIV-----------------------LGEEEAENKTMQLKWLQS
K----------EQQAMTQAELFTKVGELK-------------------------------
EQLDRHK-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTMNHST-------------------
------------------------------------------------------------
--------------------------------Q
>SP1_NM_105064
M-----------------------------------------------------------
IPWGGVTCCLSAAALYLLGRSSGRDAEVL-------------------------------
-----ETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETA
EQH--------FLKHNETGSWVQDSALMLS------------------------------
----------------------------------MSKEVPWFLDD------GTSRVHVMG
ARGATGFAL---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------TVGSEVFEESGRSLVR----GTLDYLQGLKM
L---------GVKRIERVLPTGIPLTIVGEAVKD------DIGEF--RIQKPDRGPFYVS
SKSLDQLISNL---------GKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQ
KRVLDAAAKRAELESEGSNGTRESISDSTKKEDA-----------------------VPD
LCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH-----------
-----
>gnl|BL_ORD_ID|1747 @Gloeobacter_violaceus_PCC_7421@ 637459140 glr1748 hypothetical protein [Gloeobacter violaceus PCC 7421]
M---------------------AVSLKQAFEVGKYLISQRLAGRERFPLVLMLEPLFRCN
LACPGCGKIQHPGEILRRN----------------LTPEECSRA------VEECGAPIVT
IPGGEPLLHPQIDQIVEGLVDRGKFVYLCTNAILLEKNLDKFTPSDYFSFSVHLDGLREE
HDQAVDREGVFDIAMRAIKAAKARGFRVTTNTTIFNNADPQRVREFFDFLGGLDIDGM--
--MVSP----------------GYSYEWAPDQEHFLQRDQTRALFREILAPYRSGEARWN
FNHNPLFLDFLEGLKDYECTPWGMPSYSVLG----------------------------W
QKPCYLLNEGHYATWQELLDNTRWEDYGHASGNPK-CRDCM--------VHCGYEQTAAI
DAMEIANIP----RVLASVITGR-
>gnl|BL_ORD_ID|1873 @Gloeobacter_violaceus_PCC_7421@ 637459266 gvip259 photosystem II protein [Gloeobacter violaceus PCC 7421]
MTATLSNFLWSIFWGGVVVALGAAAL--------TAIS-R--------------------
------------------------------------------------------------
------------------------------------------------------------
----IDR-----------------------------------IR----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>gnl|BL_ORD_ID|8 @Leptolyngbya_valderiana_BDU_20041@ Leptolyngbya_valderiana_BDU_20041 641057550 LVAL_00011 aldo/keto reductase [Leptolyngbya valderiana BDU 20041]
AALKAGV------------------------GVPR--------HQLYLTTKVLPNADRTA
TAREIDESLRRADIDYIDNLAIHGINTWQHLE------WVKAADGCMAAVREA---IDAG
KVRHVGFSTHGSLELILA-----------TMETGAFDFVNLHYYLLFQRHAPAIER----
---------ASQLDMGVFIISPVDKGGRLYAPSERLRRLCQPFSPLALNYRF------LL
SDRRVTTLSLGAANPSELEEALEMCDRTDPLTDEERTVLERLDIQQTEVLGSDRCRQ---
------------CYQCL---------PCPE-------NIHIPEV-LRLRNLSLAYDMTEF
GKYRYRMXENAXHWSRT
>gnl|BL_ORD_ID|2306 @Lyngbya_sp_CCY_8106@ 640016327 L8106_19221 formate dehydrogenase accessory protein [Lyngbya sp. CCY 8106]
MSAAKSKKKSNIWTIEESQIRSRLDDIATEEPLEIRLVSPAQTLAVTMRTPGADFDLVTG
FLYSEGVITSREDISKMSYCVDPDIDGEQRQNIINVALKSGLTFDFKRLERHFFMTSACG
VCGKASIESLKFRELPQISSDFNVNTEIIYRLNDQLKLAQGLFSATGGLHAAALF---NS
QGKLLKLREDVGRHNALDKLIGSSLLTDDLPLAHHIVMVSGRSSFEILQKCIVAGV----
----------------------PILCAVSA------------------------------
---------------------------------PSSLAVEIA------------------
--------------------------QAFNITLIG-FL-----------RGRRFNI----
-------------------------------------------YSGI-------------
-----------ERIKLA-----S
>gnl|BL_ORD_ID|5492 @Microcoleus_chthonoplastes_PCC_7420@ 647569879 MC7420_1162 exsB protein [Microcoleus chthonoplastes PCC 7420]
MTGVKM------------------------------------------------------
----------------------------------------------------------SK
AVV-------------------------------------LLS-----------------
------------GGL-----------------------------DSSTVLYQAKAEGYEC
YAISFDYQQRHQRELESAI-AIAKGAGVKYHQVVRFDLSQWGGSALTDDTL---------
DLPQTRSLQQMSQSIPITYVPARNTIFLSFGLSYAEAIGA--TALYLGVNALDYSGYPDC
RPDYIQA----------------------------------------MQEVFRLGTKQGR
EGEPIQIITPLIQL----------------KKTEII---------ELGNKLGVPWHETWS
CYAGDEVACGVCDSCRLRLAAFAELGLNDPLSYKPL
>gnl|BL_ORD_ID|4197 @Microcoleus_chthonoplastes_PCC_7420@ 647568581 MC7420_6143 Roadblock/LC7 domain superfamily [Microcoleus chthonoplastes PCC 7420]
M-----------------------------------------------------------
-------------------------------------AINAEKLGMIIKDFASATSDVEG
AAV------------------------------VTPDGLPLATTLP--------------
------------SGM----------------------------DDERVSAM---------
SAAMLSLGERIGKELVRGTIDRIYVEGAKGFSVLTSCG-EDTVF------LVLATKAAKQ
GLLMLEIKR--------------------------------------TVGELQMVLS---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>SP1_NM_105064
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------IPWGGVTCCLSAAALYLLGRS-------------
----------------------------------------------------SGRDAEVL
ETV-----------TRVNQLKELAQLL---------------ELDSKILPF---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------IVAVSGRVGS
ETPIKCEHSGIRGVIVEETAEQHFLKH---------------------------------
------------------------------------------------------------
----NETGSWVQDSALM--LSMSKEVPWFLDDGTSR------------------------
------------------------------------------------------------
------VHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTG
IPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRL-------------
-----------YKYASMGFTVLGVFLITKHVID------SVLERRRRRQLQKRVLDAAAK
RAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQE-----------------------
------------------------------------------------------------
------------------------------------------------------------
---YNAVFVPCGHMCCCTACSSHLT-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------SCPLC---------------------------------
------------------------------------------------------------
------------------------------------RRRIDLAVKTYRH-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>SP1_NM_105064
M---IPWGGVTCCLSAAALYLLGRS--------SGRDAEVLETVTR------------VN
QLKELAQLLEL-DSKILPFI-----------------VAVSGRVGSETPIKCEHSGIRGV
IVEETAEQHFLKHNETGSWV------------QDSALMLSMSKEVPWFLD--DGTSRVHV
MGARGATGFALTV---------------------------------------------GS
EVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDR
GPFYVSSKSLDQLISNLGKWSRLYKYASMGF---TVLGVFLITKHVIDS------V----
---------------------LERRRRRQLQKR-----------------VLDAAAKRAE
LESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPL
CRRRIDLAVKTY------------------------------------------------
--RH
>SP1_NM_105064
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------IPWGGVTCCLSAAALYLLGRS---------------------------------
------------------------------------------------------------
---------------------------------SGRDAEVLET---VTRVNQL-------
-----KELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNE
TGSWVQDS-------------ALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSE
VFEESGRSLVRGTL----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------DYLQGLKML---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------GVKRIERVLPTGIPLTIVGEAVKDDIGEF-RIQKPDRGPFYVSSKSLDQ
LISNLGKWSRLYKYASMGFTVLGVFLITKHVIDS--VLERRRRRQLQKRVLD--------
----------AAAKRAELESEGSNGTRESISDSTK-------------------------
--KEDAVPDLCVICLE--------------------------------------------
------------------------------------------------------------
--------------QEYNAVFVPCGHMCCCTACSSHLTSC-PLCRRRIDLAVKT------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------YRH-------------------
---------------------
>SP1_NM_105064
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------IPWGGVTCCLSAAALYLLGRS---------------------------------
------------------------------------------------------------
---------------------------------SGRDAEVLET---VTRVNQL-------
-----KELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNE
TGSWVQDS-------------ALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSE
VFEESGRSLVRGTL----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------DYLQGLKML---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------GVKRIERVLPTGIPLTIVGEAVKDDIGEF-RIQKPDRGPFYVSSKSLDQ
LISNLGKWSRLYKYASMGFTVLGVFLITKHVIDS--VLERRRRRQLQKRVLD--------
----------AAAKRAELESEGSNGTRESISDSTK-------------------------
--KEDAVPDLCVICLE--------------------------------------------
------------------------------------------------------------
--------------QEYNAVFVPCGHMCCCTACSSHLTSC-PLCRRRIDLAVKT------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------YRH-------------------
---------------------
>gnl|BL_ORD_ID|3117 @Nostoc_sp_PCC_7120@ 637233195 alr2811 valine--pyruvate transaminase [Nostoc sp. PCC 7120]
MILVCCTRLIFLSTLQLSLLLKLMNPALTKIGDQMSNLTGVRAIMKDIIETLKSGGGQDL
INLSAGNPLILPEVEQLWRDCTAELLASQEYGEVVCRYGSSQGYAPLIEAVVKDFNRRYG
LNLTDRNILITPGSQTLYFYAANVFGGYTSSGDLKQIVLPLSPDYTGYGGICLVPEALVA
YKPSLDIDAAAHSFKYRPDFSQVSISESTGCVIFSRPCNPTGNVLTDDEVRKIAALAAPY
NVPVLIDSAYAPPFPALNFTDMSLIFGENILHCTSLSKAGLPGERIGIAIGN--ERLIQV
LESFQTNASLH-------------------SSRYGQAIAARAINSG----ALAQIAEQVI
RPFYKNKFAIVENALEAAMPKELPWFLHRG-----------EGAIFSWLWLQDLPITDWE
LYQELKKVGVIVVP-GSTFFPGLKEEW----AHKHQCVRISLTG--SDTEIALGMQRLA-
------------------------------------------------------------
-------------------------------------------KAVEQ------------
------------------------------------------------------------
--------------------IYQRTPISA-------------------------------
------------------------------------------------------------
-------------------
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGT
SRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDY-----LQGLKMLGVKRIERVLPT
GIPLTIVGEAVKDDIGE--FRIQKPDRGPFYVSSKSLDQLISNLGKW--SRLYKYASMGF
TVLGVFL--ITKH---V------IDSVLERRRR----R-QLQKRVLDAAAKRAELESEGS
NGTRESISDSTKKEDAVPDL----------------------------------------
---------CVICLEQEYNAVFVPCGH----------------------MCCCTACSSHL
TSCP----LCRRRIDLAVKTYRH-------------
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSE-------------------------------------------TPIKCEHSGIR
GVIV-----------------------------------EETAEQHFLKHNETGS-----
-------------------------WVQDSALMLSMSKEVPWFLDD--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GTS--
-------------------------------------RVHVMGARGATGFALTVGSEVFE
ESGRSL---VRGTLDYLQGLKMLGVKRIERVL----------------------------
---------PTGIPLTIVGEAVKDDIGEFRIQKP------------DRGPFYVSSKSLDQ
LISNL-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------GKWSRLYKYASMGFT---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VLGVFLIT--------------------
------------KHVIDSVLERR-----------RRRQLQKRVLDAAAKRAE--------
-----------------------------------LESEGSNGTRESISDSTKKEDAVPD
LCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLC------------------------
--------------RRRI------------------------------------------
----------------------------------------------------------DL
AVKTYRH
>gnl|BL_ORD_ID|1649 @Prochlorococcus_marinus_marinus_CCMP1375@ 637442082 Pro1652 SAM radical enzyme [Prochlorococcus marinus marinus CCMP1375]
MS-NPQSKKLNALRQPSSTLENAKVLIIRLPCNPIFPIGPIYLADHLHKC----------
----FPTLPIKILDLAALPSIDVERVLISNINSFQPTLLVFSWRDIQ-IYAPVDGRGGNP
LQHSFEAF-YAQNP----LKKIRGAIG----GLRLMKSHYGELWRNQRLIKKGVEQAKIY
FKNAMALVGGGAVSVFYEQLGKSLPKGTIISIGEGEPLLEKLLLGKSINEERCFIVGKTP
RSGLIHEQPKSAIKTACDYSYIASIWPQL-NWYLD---------GGDFYIGVQT------
----------KRGCPHNCCYCVYTVVEGKQVRVNPVEEVISEIRQLYKLGVRNIWFTD--
------AQFIPAKRYIEDAKELLKAIKKEKMDGIRWAAYIRADNLDAELAKLMVETGM-S
YFEIGITSGSQELVRKMRMGYNL----RTVIENCILLANAGFKDHVSVNYSFNVIDERPE
TIRQTIAYHRELERIFGVKKVEPAIFFIGLQPHTHLEQYGFDKGLLKPGYNPMSMMPWTA
RKLLWNPEPMGKTFGRICLEAFDSCPNDFGRTVMNLLERDYGVAPLAEALRAPLEGRSAI
AKAVR
>gnl|BL_ORD_ID|1662 @Prochlorococcus_marinus_MED4@ PMM1666 SqdX
M-----------------------------------------------------------
-----------------------------KI-----------AFFTETFLPKVDGIVTR-
------------------------------------------------------------
-----------------------------------LTKTIEFLTKNGDEVIVFCPEGCPD
SYKGATIVGVAAMPLPLYPELKLGLPGPAVSDKLEEFKPDLVHVVNPAVLGLGGIWLAKT
NNIPLIASYHTHLPKYL--------EHYGMGMLEPLLWELLKAAHNQALLNLCTST----
---AMVNELEDKGIQRTALWQRGVDTENFRPELRSE---KMREKLFGKYQNTDSLLIYVG
RLSAEKQIERIKPVLDNIPGACLALVG-DGPYRGQLEKIFENTNTNFIGYLSGEELASAY
ASGDIFLFPSSTETLGLVLLEAMAAGCPVIGANKGGIPDIINNGINGCLYNPDEKDNGER
SLIEATKKILADKNKKEAMRKEARKEAEQ-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------WDWNQATL-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------QLQK
YYAE---TLENIS
>gnl|BL_ORD_ID|1315 @Prochlorococcus_marinus_MIT_9202@  647673486 P9202_964 glutamyl-tRNA synthetase [Prochlorococcus marinus MIT9202]
MYAQKIGGKFLLRIEDTDFVRSKSEYTKNILEGLKWLGLKW-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------DDEILKQSDRISIHKSYIKKLLECGA
AYRC-----FTTEDEISELREEQKNKGLPPKHDNRHRSLSKE-EIDSFIAQGKTSVIRFK
IDEKIEIKW----------------------VDLIRGEIKWQGKDLGG------------
----------DLVLSRRAKGYEIGDPLY--------------------------------
------------------------------NLAVVVDDNFMNITHVVRGEDHISNTAKQI
LIYEALNFKLP-------TFSHTPLILNNEGKKLSKRDCVTSIDEFRDMGYLPEALSNYM
AFLG-------WSPKSTDREILSLNEISEIFDLSDINKAGAKFSWEKLN-----------
--WINSQYIKSMESIKL---SEIMRKYWDDNGWVPPSQEWAHKLAILIRDSMILLKDSID
QSKPFFLIPTIK------------------------KEGQDFLENKDSKASLRLILNYLN
EQNAMKLNKEKAKEIINEISKMHNVKKGILMKSL--------------------------
------------------------------------------------------RVAFFG
SLSGPDLIQS--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------WELFSENKTDISRIERCFKS-----------------
------------------------------------------------------------
------------------------------------------------------------
----------------I
>SP1_NM_105064
MIPWGG----------VTCCLSAAALYLLGRSSGR----DAEVLETVTRVNQLKELAQLL
ELDSKILPF--------------------------------------------IVAVSGR
VGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSR
--VHVMG-ARGATGFALTVGSEVFE-----------------------------------
----------ESGRSLVR----GTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDI
GEFR---------IQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYA--------------
----------SMGFTVLGVFLITK---------------HVI-------DSVLERRRRR-
------------------------------------------------------------
------------------------------------------------------------
----------------------------QLQKRVLDAAAKRAELESEGSNGTR-------
-------------------ESISDSTKKEDAVPDLCV-ICLEQEYNAVFVPCG-HMCCCT
ACSSHLTSCPLCRRRIDLAVKTYRH-----------------------------------
------------------------------------------------------------
-
>SP1_NM_105064
-----MIPW-----GGVTCCLSAAALYLLGRSSGRDAEVLET-----------------V
TRVNQLKELAQLL-----------------ELDSKILPFIVAVS----------------
-------------GRVGSETPIKCEHSGIRGVIVEET-----------------------
-------AEQHFLKHNETGS---------------WVQDS--------------------
---ALMLSM---------SKEVP---WFLD--DGTSRVHV------MGARG---------
------ATGFALTVGSEVFEESGRSLVRGTLDYLQGLK-----MLGVKRIERVLPT---G
IPLT----------------------------IVGE--AVKDD---IGEFRIQKP-DRGP
FYVSSKSLDQLISNLGKWSR-------LYKYASM--------GFTVLGVFLITKHVIDSV
LERRRRRQLQKRVLDAAAKRAELES-----EGSNGTRESISDSTKKED------AVPDLC
VICLEQEYNAV---------------------FVPCGHMCCCTACSSHLTSCPLC-RRRI
DLAVKTYRH---------------------------------------------------
---------------------------------------
>SP1_NM_105064
MIP---------------------------------------------------------
----------------------------------------------------WGGVTCCL
SAAALYLLGRSSGRDA--------------------EVLETVTRVNQLKELAQLLELDSK
ILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHN-ETGSWVQDSALMLSMSK
E---VPWFLDDGTSRVHVMGAR-------GATGFALT----VGSEVFEESGRSLV-----
------------------------------------------------------------
-------RGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQK-------
PDRGPFYVSSKSLDQLISNLGKWSRLYK---YASMGFTVLGVFLITKHVIDSVLERRRRR
QLQ----------------------------------KRVLDAAA------KRAELESEG
SNGTRESISDST----KKEDAVPDLCVICLE-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------QEYNAVFVPCGHMCCCTA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------CSSHLTSCPL
CRRRIDLAVKTYRH
>gnl|BL_ORD_ID|1436 @Prochlorococcus_marinus_MIT_9303@ 640086956 P9303_14471 putative acetazolamide conferring resistance protein Zam [Prochlorococcus marinus MIT 9303]
MKFTVADLLDQLPPTGGLEIKKLEKILKLTTKADRDGLETALQGLLRLGIVNNEEAGAIK
RSDDESLIEARLRCSSKGFCFALRDDGGDDIYIRDHQLNHAWNGDRVLVRITRDGGRRRS
PEGGVQCILERTTTSLLGHVERKDQNVLAIPLDDRILATIQLPDGDKAHLNDGEQTSVVE
VKLDRYPIAQFPAEGHVARSLPLNGGPSSDRDLLLTKANLQDRPAPPRSSLKTPTAKHRQ
DLS--SQPALLLRS-----WQVSDAPPLPAVYVEPHAGGTRLWIHAPAVAERLSI-GNNL
DLWLRDRAEALCLGEVWHP---LLGQILSKACSFK--------VGEINDAVSVALDISAD
GEVIDWHFSLSSIKPV-AEIGPKTLTA----------LSNRKPKARTVPAALKSVK----
-------------------DHLAQLETLIFCARTLQMG---EQASGSIELDLAVPELQCL
GDLRWADPDSYRHQWTLPLDQTDPQSVLSPIIR----AAHRAWAQHAQNL-------QLP
----------GLVIEASEAENSTLNDVAKSALALDIALELDEEGSPAATELAKAFATTAC
RRVLDQQ---LRHALPEPVLRLAIHDSQKENGNIESDHEDTKSMDTNLQSPWCCPTIHYT
DLVNQEIIVSLLSNGKDRPNVRQK-EKLVLGSRECWQQLKWPLFSTSQAKNLKEICSESL
VHRLNTLRRQAEELRQDLIAMVQARIVEPLVGEEHQGVISGVQSYGFFVEIPPSMAEGLV
HVSSLNDDWYEYRSRQNRLVGRKNRKIYQLGDQVNVKVLKVDALRNQIDLEVNGSAMTVE
ANMNVDSDLTNQVTTTKSEVKGKITKNNEQLVSSSEA
>SP1_NM_105064
MI-------------PWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVN----------
---QLKELAQLLELDSKI---------------------------------------LPF
IVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWF
LDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPT
GIPLTIVGEAVKDDIGEFRIQK----PDRGPFYVSSKSLDQLISNLGKWSRLYK------
--YASMGFTVLGVFLIT-----------------------------------KHVIDSV-
------------------------------------------------------------
-----------------------LERRR--------------------------------
------------------------------------------------------------
-----------------------------------------------RRQLQKRVLDAAA
KRAELESEGSN-------------------------------------------------
---------------------GTRESISDSTKKEDAVPDLCVICLEQEYNAVF-------
---------------------------VPCGHMCCCTACSSHLTSCP-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------LCRRRI------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------DLAVKTYRH
>gnl|BL_ORD_ID|766 @Prochlorococcus_marinus_MIT_9313@ gi|33863038|ref|NP_894598.1| acetazolamide conferring resistance protein Zam [Prochlorococcus marinus str. MIT 9313]
MKFTVADLLDQLPPTGGLEIKKLEKILKLTTKADRDGLETALQALLKLGIVNNEEAGAIK
RSDDESLIEARLRCSSKGFCFALRDDGGDDIYIRDHQLNHAWNGDRVLVRITRDGGRRRS
PEGGVQCILERSTTSLLGHVE--------RKDQNILAIPLDDRILATIQLPDGDQAHLND
GEQTSVVEVKLDRYPIAQF------------------PAEGHVARSLPLNGGPSSDRDLL
LTKA--------------------------------------------------------
-------------------------------------------------NLQDRPAPPRS
SLKTPTA--------KHRQDLSSQPALLLRSWQVSDAPPLPAVYVEPHAGGTRLWIHAPA
VAERLTIGNNLDLWLRDRAEALCLGEVWHPLLGQILSKACSFKVGE---INDAVSVALD-
-ISADGEVTNWHFSLSSIKPVAEIGPKTLTALSNRKPKA-R----TVPAAL---------
KPVKDHL--------AQLETLIFCA----RTLQMGEQASGS------IELDLAVPELQCL
G------DLRWADPDSYHHQWALPLDQTDPQSVL-----SPMIRAAHRAWAQHAQNL-QL
PGLVIEASEADNNTLNDVAKSALALDIALELDEEGRPAATELAKAFSTTACRRVLDQQLR
HALPETLLRLGINDSQKENGNIESDHEDTKTKDSNLQSPWCCPTIHYTDLVNQEIIVTLL
SNGKDRPNVRQKEKVVLGSRECWQQIKWPLFSTSQAKNLEEICSKSLVHRLNTLRRQAEE
LRQDLIAMVQARIVEPLVGEEHQGVISGVQSYGFFVEIPPSMAEGLVHVSSLNDDWYEYR
SRQNRLVGRKNRKIYQLGDQVNVKVVKVDALRNQIDLEVNGSAITVEANMNVNSDPTNQA
TTTKKSEVKGKITKNNEQLVSSSEA
>SP1_NM_105064
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------IP---------
------------------------------------------------------------
------------------------------------------------------------
-------------WG-------------------------GV------------------
--------------------------------------------TC--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------CLS---------------------------------------------
----------------------------------------------------AAALYLLG
RSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVI
VEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGS
EVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDR
GPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLIT----KHVIDS------VLER
RRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVP
CGHMCCCTACS----------------SHLTSCPLCRRRIDLAVKTYR------------
----------------------------H
>gnl|BL_ORD_ID|219 @Prochlorococcus_marinus_NATL1A@ 640083484 NATL1_02191 putative Rubisco transcriptional regulator [Prochlorococcus marinus NATL1A]
MAE-----I---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------PFTLDQLRILKAIVDEGSFKKAADSLFVTQ--------------
-----PAVSLQVQNLEKQLDIAIFDRGGRKAQLTEAGKLLLNYCEKILGECLETCKAVED
LNNL--------KGGSIIIGASQTTGTYLMP-----RMIGVFRQKYPEVSV---------
----QLQIHSTRRTGWSVANGQIDIAIIGGQLPLELNELLEV------------------
--IPFATDE-LALVLPTNHPLAKS--------------KELTKEDLYSLRFITLDNQS--
TTRKVVDQLLSSSGLDVQRLHIEMELNSLEAIKNAVQSNLGAAFLPVVSIERELSGGSIH
R----------------------PIVADLEVKR-ELKVITNPGRYSSRAAEAFT-RDI--
---LP--------LFASSF--SPLFNP---------------------QN----------
------------------------------------------------------------
------------------------------
>gnl|BL_ORD_ID|198 @Prochlorococcus_marinus_NATL2A@ gi|72383349|ref|YP_292704.1| Rubisco transcriptional regulator [Prochlorococcus marinus str. NATL2A]
M---AEIPFTLDQLRILKAIVDEGSFKKAADSLFVTQPAVSLQVQNLEKQLDIAIFDRGG
RKAQLTEAGKLLLNYCEKILGECLETCKAVEDLNNLKGGS-----------IIIGASQTT
------------------------------------------------------------
----------------------------------------------------------GT
YLMPRMIGVFRQKYPEVSVQLQIHSTRRT-------------------GWSVANGQIDIA
IIGGQ---------------------LPLELNELLEVIPFATDELALVLP----------
---------TNHPLAK--------------------------------------------
------------------------------------------------------------
----------SKELTKEDLYSLRFITLDN--QSTTRKVLDQLLSSSGLD--VQRLHIEME
LNSLEAIKNAVQSNLGAAFLPVVSIERELSGGSIHRPIVADLEVKR--------------
------------------------------------------------------------
-----------------------ELKVITNPGRYSSRAAEAFTRDILPLFA-----SSFS
PLFNP---------------------------------------------------QN
>gnl|BL_ORD_ID|1666 @Prochlorococcus_marinus_pastoris_CCMP1986@ gi|33862222|ref|NP_893783.1| SqdX [Prochlorococcus marinus subsp. pastoris str. CCMP1986]
M-----------------------------------------------------------
-----------------------------KI-----------AFFTETFLPKVDGIVTR-
------------------------------------------------------------
-----------------------------------LTKTIEFLTKNGDEVIVFCPEGCPD
SYKGATIVGVAAMPLPLYPELKLGLPGPAVSDKLEEFKPDLVHVVNPAVLGLGGIWLAKT
NNIPLIASYHTHLPKYL--------EHYGMGMLEPLLWELLKAAHNQALLNLCTST----
---AMVNELEDKGIQRTALWQRGVDTENFRPELRSE---KMREKLFGKYQNTDSLLIYVG
RLSAEKQIERIKPVLDNIPGACLALVG-DGPYRGQLEKIFENTNTNFIGYLSGEELASAY
ASGDIFLFPSSTETLGLVLLEAMAAGCPVIGANKGGIPDIINNGINGCLYNPDEKDNGER
SLIEATKKILADKNKKEAMRKEARKEAEQ-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------WDWNQATL-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------QLQK
YYAE---TLENIS
>gnl|BL_ORD_ID|1648 @Prochlorococcus_marinus_SS120@ Pro1652 SAM radical enzyme
MS-NPQSKKLNALRQPSSTLENAKVLIIRLPCNPIFPIGPIYLADHLHKC----------
----FPTLPIKILDLAALPSIDVERVLISNINSFQPTLLVFSWRDIQ-IYAPVDGRGGNP
LQHSFEAF-YAQNP----LKKIRGAIG----GLRLMKSHYGELWRNQRLIKKGVEQAKIY
FKNAMALVGGGAVSVFYEQLGKSLPKGTIISIGEGEPLLEKLLLGKSINEERCFIVGKTP
RSGLIHEQPKSAIKTACDYSYIASIWPQL-NWYLD---------GGDFYIGVQT------
----------KRGCPHNCCYCVYTVVEGKQVRVNPVEEVISEIRQLYKLGVRNIWFTD--
------AQFIPAKRYIEDAKELLKAIKKEKMDGIRWAAYIRADNLDAELAKLMVETGM-S
YFEIGITSGSQELVRKMRMGYNL----RTVIENCILLANAGFKDHVSVNYSFNVIDERPE
TIRQTIAYHRELERIFGVKKVEPAIFFIGLQPHTHLEQYGFDKGLLKPGYNPMSMMPWTA
RKLLWNPEPMGKTFGRICLEAFDSCPNDFGRTVMNLLERDYGVAPLAEALRAPLEGRSAI
AKAVR
>gnl|BL_ORD_ID|1698 @Prochlorococcus_sp_CC9311@ 638115322 sync_1734 possible ligand gated channel (GIC family) [Prochlorococcus sp. CC9311]
MLAGIVLISLPIQTVAKELQVGVSGSPPFVMDEDGNLSGISIEIWKDVAKRLDQPYKLVI
QPNTNANIKAVADGSVDLAIGPISITPARLANPKIDFTQPYFHGYEGLLIPQKPPGLITR
LRPFIGWAALSSVGILVSLLFIFGNLIWLAERRNNTDQFPRQYMRGVGNGMWFGLVTLTT
VGYGDRAPVSRSGRTIAGIWMVMSLVAVSSITAGLASAFTLSLAELAPSSIRDKSDLRGK
KIAVVEGTTSLRWGKLYEIDPTLTKNL--------NEAINMLNQGKVEGVIFDEAPLRHY
LKENEQSKLKLANFPLAVQTYGFVLPMGS-------------------------------
--------------------------------------------------------PLRN
PLNI--------------------------------------------------------
-------ELLAMERNGETEKI------ESKLLD---------------------------
----------------------
>SP1_NM_105064
MI----------------------------------------------------------
---------------------------------------------PW-------------
---------------GGVTCCLSAAALYL-------------------------------
------------------------------------------------------------
-------------------------------LGRSSGRDAEVLETV--------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
RVNQLKELAQLLE-----------------------------------------------
----------------------------------------------LDSK------ILP-
--FIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETG-SWVQDSALMLSMSKE
VPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVR--GTLDYLQGLKMLGVKRI
ERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGK----------
----WSRLYKYASMGFTVLGVFLITKH--VID--SVLERRRR--RQLQKRVLDAAAKRAE
LES-EGSNGTRESISDSTKKEDAVPDLCVI---CLEQEYNAVFVPCGH-----------M
CCCTACSSHLTS------------------------------------------------
-CPLCRRRIDLAVKTYRH------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>gnl|BL_ORD_ID|608 @Raphidiopsis_brookii_D9@ 647108404 CRD_00973 Peptidase M22, glycoprotease [Raphidiopsis brookii D9]
M------------------------DLFPIPIFSHL------------------------
-------------EQL--MTTILAIETSCDETAVAIVKNRYVKSSVIASQIPL---HQRY
GGVVPEVASRQHLETINQVIAQA---------------------------------LDDS
LM-------DWGEI--DGVAATCAPGLVGALLVGLTAGK-------------TLAMVHKK
PFLG----VHHLEGHIYAT----------------------YLAEPDLNPPFLS------
LLVSGGHTSLIYVQDCGKYETLGQTVDDAAGEAFDKVARLLGLAYPGGPIIDQLAQMGNP
HAFSLPEGKISLPQGGYHPYNSSFSGLKTAVLRLVQQFQKDGETIPVADIAASFQATLAK
A---------LTKRAIACACDYGIKTIAIGGGVAANSGLRQYLEAAAREHNLRVLFPPLK
FCTDNAAMIACAASDHLSRGHRSNWTLGVHSRLPVTQVMDLYK-----------------
----------V
>gnl|BL_ORD_ID|611 @Synechococcus_CC9605@ gi|78212168|ref|YP_380947.1| VIC family potassium channel protein [Synechococcus sp. CC9605]
MRRRRARGQLKLITAPWRGPISALSAVI------------FAGALGYRITEGWDWGDCLW
MVLITISTIGFG------------EVAPLSPPGRLVTVLIVVGGLVVVQLAIQRVLGLKE
SGYFRRLREFRFLRMLEGLHDH----VILCGYGRIGQEIAAQLQRDAVPLVVIETDPERK
AVA---------DENGFWVLQADATL-----DETLLDAGLERCCSLVAALPSDASNLYVI
LSAKDLRPDCRL----------IARANSDEAASKLRLAGATVVVSPYVAGGRVMAA--SA
LR----PLALNFMDLLAGSDYEIEEFQLSQNPLLLKEIEGKSLSEL--ELGRRSG-----
------------------------------------------------------AIVLAI
RDNGKLIANPGGATQMAAGQLLIV------------------------------------
------------------------------------------------------------
------------------LGSKTQLT-TFQRLL---------------------------
--------------GEAVDTIE--------------------------------------
----SMPG
>SP1_NM_105064
M-----------------------------------------------------IPWGGV
TCCLSAAALYLLGRS---------------------------------------------
------------------------------------------------------------
--------------------------------------------------SGRDAEVLET
VTRVNQLKELAQLLELD-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------SKILPFIVAVSGRVGS-----------------
------------------------------------------------------------
------------ETPIKCEHS--------------------GIRGVIVEETAEQHFLKHN
ETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRG
TLDYLQGLKMLGVKRIERVLPT-GIPL---------TIVGEAVKDDIGEFRIQKPDRGPF
-YVSSKSLDQLIS--NLGKWSR---------------------------------LYKYA
SMGFTVLGVFLITKHVIDSVLERRRR------------RQLQKRVLDAAAKRAELE-SEG
SNGTR-------------------------------------------------------
-----------------------------------ESISDSTKKEDAVPDLCVI------
------------------------------------------------------------
CLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>gnl|BL_ORD_ID|1906 @Synechococcus_elongatus_PCC_7942@ gi|81300668|ref|YP_400876.1| unnamed protein product [Synechococcus elongatus PCC 7942]
MSSPLQPFLEPANVQQLAGEALTWLFTPAGQLLLASPSAQQLSLLSDPNTLSIPSWLQQV
IEKVLA--SNHLDQNLEPQVEQLRVALATEVVHIPLTLELQWLADVESEASFLLVTGSCQ
DSHQNLFLDWQQLQSLEVQRLSHKVGHWSWNRSQ-ADEFLAPPHIYTQIGRSLHEPFTLT
SFLQHCHSSLESLQANAISLGNQRSHYLWDFPVKTAHSDRWFECHCLLHHDETGELLSLV
GNIRDITEEHHIL------SLVQDSETRFQV------LIESNPNGILVLDEQGAVLFANH
VAEQVFDQS--------LSELQG-KYLG-------LPLTLNVTVQLDLVQPD-GSLRYVE
VSIVPIPWQQSKAYLALLTDITSLQQTQQRLKLLQEATENSPASILITSAEGIIEYVNPA
FE-----LMTGYGADEVIGKNPRFLKSGLMSPSFYQDLWETITAGETWRGELYNRRKTGE
LFWDRTSISPVKDLAGQIIHFVAVKEDITEQKRNRELLDHQANYDSLTDLPNRSLALDRL
RQATALSERSNDTVIVMLLDLDRFKNINDTLGHSYGDCLLQEIAKRLRYHLPREITISRL
GGDEFLIICPAVKENIHLEKLSQQLLKIISQPITIEAEELVITASIGVACYPNDGVTPEV
LMRNADTAMYSAKRNGGNDFQLFMPTMNAEAHARIQLETHLRHALEQYQLK-------VF
YQPIISLQDNHVVGL-EALARWHDPELGNIPPDRFIPIAEETGLIIPLGYRVIEQACQDV
AIWQQKYNYPFWVAVNLSPRQLRSNRFTQITAKILQRHNFRPNYLKLEVTEQMLLDNTST
IAQMLDTLHRKGIALALDDFGTGYSALSYLRRYPFQSLKVDQSFLRDIPHSTESCALVKT
IVAMAHGLGMQAVAEGVETAEQVEFLKAIGCEYGQGYWFSRPLPAVEIDSFLAVSTGHES
IS
>SP1_NM_105064
MI----------------------------------------------------------
------------------------------------------------------------
PWGGVTCCLSAAALYLLGRSSGRDAE---------VLETVTRVNQLKE------------
-------LAQLLELDSKILPF-------------------------------IVAVSGRV
GSE--------------------TPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSA
LMLSM------SKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDY
LQGLKMLGV---KRIERVLPTGIPLTIVGEAVKDDIGEFR--------IQKPDRGPFYVS
SKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLE----------RRRRRQL
QKRVLD------------------------AAAKRAELESEGSNGTRESI---SDSTKKE
DAVPDLCVICLEQEYNAVF------------------------------VPCGHMCCCTA
CSSHLTSCPL--------------------------------------------------
------------------------------------------------------------
-----------------------------------------------CRRRIDLAVKTY-
-------------------RH
>gnl|BL_ORD_ID|1573 @Synechococcus_sp_CB0101@ 650129150 SCB01_010100007922 1-(5-phosphoribosyl)-5-[(5- phosphoribosylamino)methylideneamino] imidazole-4-carboxamide isomerase [Synechococcus sp. CB0101]
MKLTQRWTAQPASLGLTQGYRHFQLLGEQGKGAERAARLEAVLERSCRLLIPLRQLRDRG
LWQPGWQSLSRPVSMQIIPAIDLLDGHCVRLHQGDYDQVTRFNDDPVAQALDWQRQGAQR
LHLVDLDGAKTGQPVNDQAVKAITAALSIPVQLGGGVRSAERAEELL----ACGLDRVIL
GTVAIEKPELVKELAA--RHPGKVVVGIDAKDGLVATRGWIETSTVKATDLAKSFEGCGV
AAIISTDIATDGTLAGPNLEALRAMAEASSIPVIASGGIGTLDDILSLLSIAPLGVEGVI
-------------VGRALYDGTVDLAEALQAIGPERLQDALTSS----------------
-----------------------------------TGSITV-------------------
------------------------------------------------------------
-------------------------------
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPW---FLD
DGTSRVHVMGARGATGFA------LTVGS--EVFE-ESGRSLVRGTLDYLQGLKMLGVKR
IERVL----------PTGIPLTIVGEAVKDD-------IGE-FRIQKPDRGPFYV-----
------------------------------------------------------------
------------------------------------------------------------
---------------------SSKSLDQL--------------------ISNLGKWSRLY
KYASMGFTVLGVFLITKHVIDSV--LERRRRRQL-------------QKRV-------LD
AAAKRAELESEGSNGT--------------RESISDSTKKEDAVPDLCVICLEQEYNAVF
VPCGHMCCCTACSSHLTSC----------------PLCRRRIDLAVKTYRH---------
------------------------------------------------------------
-------------
>gnl|BL_ORD_ID|106 @Synechococcus_sp_CC9902@ Syncc9902_0107 hypothetical protein
M-----------------------------------------------------------
------------------------------IVLPNSSLQLLW------------------
---GCNPALQFEKAWLLHLLRHNVSSQLECWSQPSQILLRNKSLFPVLVESGLLRLHRTP
SASA--LAAEQSSRIFRI----SALKEYGEFGVIHL------------------------
--------------------------------SDEEGLDA--LTWYHLCPHGTSIWRNFT
HHYF---SASSYIHSFPIGPRDIFLSSESPLLNSSLSSTRPYPWTFMGTL-----WSSGS
RCLAASLFLRALPNG----FFFSASSFSCGLPLDKYRDYLSHSVFSLCPDGDRHFDTFRL
----WESLSTGTIPLVI------DNRHSLS--------LIFPDGHPIPTFSSWKDALFFA
SSYLARPTALNALQFSISSWWTSSQHTLSRSLS-----SSFSF-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----KS
>gnl|BL_ORD_ID|1784 @Synechococcus_sp_CC9902@ Syncc9902_1802 conserved hypothetical protein
M-----------------------------------------------------------
------------------------------------------------------------
----------------------------------GEGWLTDSERY---------------
------------------------------------------------------------
------------------------------------------WACRF-------------
-----HRDARSWAQ-------------DPRVF---VDQGREMP--------------NGE
PA------------------------------LLKSRRYL------------RDAEARKL
------------------------------------------------------------
------------------------------------------------------------
-------------------WLELVRKGWAPTPPLWGNDA---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----EP
>gnl|BL_ORD_ID|1069 @Synechococcus_sp_JA_2_3B_a2_13@ 637875498 CYB_1096 putative nicotinate phosphoribosyltransferase [Synechococcus sp. JA-2-3Ba(2-13)]
MLSPDFSSLRPQDYGLLTDLYQFTMAACYVGEGLESQPAAFELFVRRLPTDYGYLIAMGL
TQAVDYLQQLSFAPEALRALRETGIFADAPERFWELLARCRFEGDVWAVPEGTAIFANQP
LLRVEAPLWQAQLVE---TYLLSTFNYQTLIATKAARMRDA-AGDEAILLEFGTRRAF--
----------GPQAGLWAARAALA--AGFNATSNVLAALKLGRKPAGTMAHSLVMAIAAL
SGDETRAFQ-SFRR-----YFPQAALLID--------TYDPIQGARTAAQLFAARSPDQL
GSQGEIGGVRIDS---------------GDLEDLSRRVKQI------------LPQGAPV
FVSG-----DLDEYEIERLHRSQAPISGYGVGTRLVTG--EGVNGVYK------------
----LVEINGIPVAKASFAKATLPG-----RKQIFRGPEGDLLGHADEPPPPGYEPLLRK
VMEKGLLLDPLPDLEAIARTSRASVLCLPQGVRQLRQPDPWPTALTAALQRLKDHTLGQE
----CASAGPA
>gnl|BL_ORD_ID|1358 @Synechococcus_sp_JA_3_3Ab@ 637872988 CYA_1435 putative lipoprotein [Synechococcus sp. JA-3-3Ab]
MASHNSKSRFRHPIAPLVLASSLVGGVAACSLTSDPPAVTQVPPTISAQAPETAVQGSES
IAFYYDGVKTSVTIKDAAVLFAACTLNTNDSGKIVNFVNNTLKVGPITAADVTGLGDPLK
PSVSDFTADGVVDCKDAAVLFAAISTGLPPTASKINSFLATTLKLSGVSVTQPNLDTFFS
GPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPAQFYVHPTRGDD
NNLGTSRLEPFKTVERALESTEVQTAASLGGGTNVIVRIIADGTEEVSSTNIESLTLTAG
SVTVLPDSDVNFTLKLMNGKLLTLNKGYRLQGFKIESGDPG----GTNTRAAAITLAAAG
TP--LKDMLIDCTGLGTAGTATAGVGSGDRCIEVTASSATVTLDNVDVLIKGDKDYTAGI
RHVGTSTILRVI-NGSSVVATGQGSSGNQGVVG-----ILENSDL--------GSVEIE-
GPNTEVNLSAIRPV----------------------------------------------
----------ASGARNVAILLRGNSFRTRKVINSEIKVNEANPGQIGVCVGSTINVTVQG
-----STFTNSSPGRNSIAICQRTTGSVSPD--PLSSGNRFNNFSTSPDKRFVTFPDCSC
PSSS---
>gnl|BL_ORD_ID|393 @Synechococcus_sp_PCC_7002@ 641610245 SYNPCC7002_A0235 valine-pyruvate aminotransferase [Synechococcus sp. PCC 7002]
MSQAPLLSKFGTQMSRLTGVRAIMKDIIDTLKAGAGQDFINLSAGNPVIIPEVEQLWRDC
TNDLLNSPEYGEVVCRYGSSQGYEP-----LIEAIATDFNQ-----RYGLNLTGENILIT
PGSQSL-------YFLAANAFGGYDHVGQLKSIILPLSPDYTGYGGVSLYPEAIRAFKPS
LDIDQVNHRFKYRPDFSQLNIDENTGCVIFSRPCNPTGNVLSDEEAEKIADLAAVHDVPV
FIDSAYAPPFPALNFTEMKPLFGGNVIHCLSLSKAGLPGE-------------RVGIAIG
EPRFIGVLQAFLTNACIHSSRYGQAIAARAIQSGALANIAETVIRPYYQNKIQ----ILE
AAL---DRAMPKDVPWYLHRGEGAI----------FAWLWFDELPMTD--------WELY
QELKAVGV------------IAVPGSPFFPGLRE--------------------------
---------------------------------DWP------------------------
------HKQQCLRISLTATDSEIEMAME--------------------------------
--------------------------RLAKVVKKVYAK
>gnl|BL_ORD_ID|1381 @Synechococcus_sp_PCC_7335@ 647577621 S7335_4709 DNA-directed RNA polymerase, gamma subunit [Synechococcus sp. PCC 7335]
MPKVEQRFDYVKIGIASPERIREWGERTLPNGTVVGEVTKPETINYRTLKPEMDGLFCER
IFGPAKDWECHCGKYKRVRHRGIVCERCGVEVTESRVRRHRMGYIKLAAPVAHVWYLKGI
PSYIAILLDMPLRDVEQIVYFNAYVVLDAGNADNLSYKQLLSEDQWMEIEDQLYAEESQL
SGIEVGIGAEALKRLLEDLQLEETAEMLR------------------ETIATSKGQKRAK
LIKRLRVIDNFIATGSNPDWMVLDV--------IPVIPPDLRPMVQLDGGRFATSDLNDL
YRRVINRNNR-----------------LARLQEILAPEIIVRNEKRMLQEAVDALIDNGR
RGRTVVGANNRPLKSLSDIIE--GKQGRFRQNLLGKRVDYSGRSVIVVGPNLKIHQCGLP
REMAIELFQPFVIHRLIRQGLVNNIKAAKK---LIQRSDPSVWEVLEDVIENHPVMLNRA
PTLHRLGIQ-----AFEPI--MVEGRAIQLHPLVCPAFNADFDGDQMAVHVPLSLEAQSE
ARLLMLASNNVLSPATGRPIITPSQDMVLGCYYLTADNPSKQKGAGRYFANMEDAIAAYE
QGNVDLHAKVWLRFVGDVETAEEDNEPIKVEEDGNGGSTKTYKFRRVREDESGNVISQYV
ETTPGRIIYNHAVLGALAE
>gnl|BL_ORD_ID|721 @Synechococcus_sp_RS9916@ 639887919 RS9916_34347 hypothetical protein [Synechococcus sp. RS9916]
MLLATEGHTELPWRLDGMARPGSHRLFVFARVSVAAAGLALVQPVLGPVLPLPAVEMTSR
QPQMRVLVAEGARLDLRADGSNRFQVRGLGRRAQQLTRLQVRLSRGRLLVDSPDLRGERQ
VRVTGLTVHSQDPRGIWLGKRRYAGSLELMVRNGRLQAVNHL-----GVETYLASV---V
GSEMP-------------------------------QDWPLAALQAQAV-------AART
YALRQRGRKGSFDVQATVASQVYRGLESATPRTQEAVDTTRSLVMVHGGKLINAVFHSS-
----SGGATEPSGEVWRTQLP-----YLVSVPDHDAQSPVHRWTQMFDRRQLQAAFRETG
GLQAVDVLRTSSTGRLRSVRVRGPGGSVVLSGRELRQRLGLKSTMVRFNWLAQDVAGQHS
RPAQQGGLPEGDRPLLIGLWRDSASGSSTSPQSHGRAQALIPPPPPPPLVPAPGLSAPQS
GRVLEVRGQGFGHGVGMSQWGARGLAEQGADFRQI-LRHYYRGITIRPFQP--------A
DDPSMAFHPALR-------PAWNS
>gnl|BL_ORD_ID|2480 @Synechococcus_sp_RS9917@ 638963667 RS9917_02056 FAD linked oxidase, N-terminal [Synechococcus sp. RS9917]
MTQ--------GSAGLQAL-------------------QAELAPLPQL------------
------------------------------------SLLQGEADLLRFSRDAYDY-----
-------------------SPVLRER-LSHCRAGL----------VVRPESVAAVRAVAA
ACARHGVPLTLRGAGTGNYGQCVPLQGGVVMLMGALSAVRAIDPHSGVVEVESGCLLRDL
DQAVAGHHRQLRLLPSTWRTATIGGFIAGGSGGIGSVRWGFLRDPGHLLGLEVVTLEAEP
RLLQ---LDAADAEALNHAYGTNGIITALRLSTAPRQAWHELSIDCADWE---VAVDLAQ
RCQQAALELHL--CTVLERSIVDQLPNWSGAPAGCHRLLLLVAADGVSTVERLAAAVGAV
CRHLGPEADHHGNGLRELSWNHTTLHCRSLDPSWTYLQMLLPQPELPLLNQLRADWGDDL
LWHLEGVRQGGTARLAALPLVRWQGGDALERLIAQCRDLGAVIFNPHVITVEDGGLGVID
GEQVAAKRHHDPMGLLNPGKLRGWSA
>SP1_NM_105064
M-----------------IPWGGVTCCLSAAALY-----------------------LLG
RSS-GRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKC--EHSGIR
GVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALT
VGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQK
PDRGPFYVSSKSLDQLISNLGKWSRLYKYAS-----------MGFTVLGVFLITKHVIDS
VLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNA
VFVPCGHMC------------------------------------------CCTACSSHL
TSCPLCRRRIDLAVKTYR------------------------------------------
------------------------------------------------------------
---------------------------------------------------------H
>gnl|BL_ORD_ID|2057 @Synechococcus_sp_WH7805@ 639021414 WH7805_05581 hypothetical protein [Synechococcus sp. WH7805]
MHWPAVDADHLLVRSDQMLELEQQWLSSGLPVAALMETVGQRMAEWCLQRPDRLAQGVLV
LVGPGHNGGDGLVLGRKLLEKGIAVRLWAPLPLRQALTHEHWRHLLWLGVPVQEFEPDPA
DPSLWIDALFGLGQTRPLPDQVTQLLQQ-RQLSAPGQ------LISLD-------CPAGL
D------SDSGTPL-----GTAVAVASDTLTVALIKR----GLVQDAALPFAGKVHRIDP
GVPPRLMASLTSPLVFQVGASDLKTLPVPAEKSTAMKYERGRLLLIAGSERYRGAAHLAV
RGALASGAGSVRAALPKVVDQQLWQWAPEVVSEPALESDDSGSLLWGAALERSDLSRLDA
LLLGPGLGLMEGVWRGWAEPLQTFRGLLVLDADALNQLSGDVEGWRWFLKR-------MG
PTWITPH-----------PQEFERLFPFCDQGSPLERAAAAAERSGV-------------
-VVLLKGAHSVIADPS-----GSVRQLVGTDCQVARTGLGDLLAGLAGGWGARLQAAASP
ADGAALAAAGLLHAQAA-----C------GCSRSSGALTIADQLTQL-------------
------------------------------------------------------------
----------------------------------VRSVTRMSDE
>SP1_NM_105064
M-----------------------------------------------------------
-----------------------IPWGG--------------------------------
------------------------------------------------------------
--------------------VTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELA---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------QLLELDSKILPFI----------
------------------------------------------------------------
-------------------------------------VAVSGRVGSETPIKCEHSG---I
RGVIVEETAEQHFLK--------HNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGA
RGATGFALTVGSEVFEESGRSLVRG-----------TLDYLQGLKMLGVKRIERVLPT--
-GIPLTIVGEA-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------VKDDIGEFRIQKPD-------RGPFYVSSKSLD
QLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELE
SEGSNGTRESISDSTKKEDAVPD----------------------LCVICLEQEYNAVFV
PCGHMCCCTACSSHLTSCP-----------------------------------------
------------LCRRRIDLAVKTY-----------------------------------
----------------------------------------RH------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>SP1_NM_105064
MI----------------------------------------------------------
---------------------------------------------PW-------------
---------------GGVTCCLSAAALYL-------------------------------
------------------------------------------------------------
-------------------------------LGRSSGRDAEVLETV--------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
RVNQLKELAQLLE-----------------------------------------------
----------------------------------------------LDSK------ILP-
--FIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETG-SWVQDSALMLSMSKE
VPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVR--GTLDYLQGLKMLGVKRI
ERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGK----------
----WSRLYKYASMGFTVLGVFLITKH--VID--SVLERRRR--RQLQKRVLDAAAKRAE
LES-EGSNGTRESISDSTKKEDAVPDLCVI---CLEQEYNAVFVPCGH-----------M
CCCTACSSHLTS------------------------------------------------
-CPLCRRRIDLAVKTYRH------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>SP1_NM_105064
M---IPWGGVTCCLSAAALYLLGRSSGRD------------------------------A
-----------------------------------------E-------VLETVTRVNQL
KELAQL------LELDSKILPFIVAVSGRVG----------------------------S
ETPIKCEHSGIRGVIV--------------------------------EETAEQHFLKH-
-------NETGSWVQDSALMLSM------SKEVPWFLDDGTSRVHVMGARGATGF-ALTV
GSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGI--PLTIVGEAVK---------
-----------------------------------------DDIGEFRIQKPD-------
------------------------------------------------------------
------------------RGPFYVSSK-------------------------------SL
DQLISNLGKWSRLYKYAS-------------MGFTVLGVFLITKHV-IDSVLERRRRRQL
QK--------RVLDAAAKRAELESEGSNGTRESISDSTKKE-----DAVPDLC-------
--------VICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYR-H
>SP1_NM_105064
MI----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------PWGGVTCCLSAA
ALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSET-------
------------------------------------------PIKCEHSGIRG-------
------------------------VIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPW
FLDDGTSRV-------------------------------------HVMGARGATGFALT
VGSEVFEESGRS----LVRGTLDYLQGLKMLG--------VKRIERVLPTGIPLTIVGEA
VKDDIGEFRIQKPDRGPFYVSSKSLDQLISNL------------------------GKWS
RLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRES
IS----------------------DSTKKEDAVP-------DLCVICLE---QEYNAVFV
PC-----GHMCCCTAC--------------------------------------------
--------------SSHLTSCPLCRRRIDLAVKTYRH---------------
>SP1_NM_105064
MIPW--------------------------------------------------------
-----------------------------------GGVTCCLSAAALYLLGRSSGR---D
AEVLE---------------------TVTRVNQLKELAQLL--ELDSKILPFIVAVSGRV
GS------------ETPIKCEHSGIRGVIVEETAEQHFLKHNE----TGSWVQDSALMLS
MSKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLV----------------
------------------------------------------------------------
------------------------------------------------------------
-------------RGTLDY---LQGLKMLGVKRIERVLPTG-------------------
----IPLTIVGEAVKDDIGEFRIQKPDRGP--FYVSSKSLDQLISNLGKWSRLYKYASMG
FTVLGV------------------------------------------------------
-----------------FLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGS----
----------------NGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTA
CSSHLTSCPLCRRRID--------------------------------------------
-----------------------------------------LAVKTYRH
>gnl|BL_ORD_ID|459 @Trichodesmium_erythraeum_IMS101@ gi|113474402|ref|YP_720463.1| unnamed protein product [Trichodesmium erythraeum IMS101]
MERSISKSLFFLQRLEPKISVMDRYIIAELIGPFLFGVGLFSSLGITVGAMFELVRKVTE
SGLPISIAIQVFLLK-MPEFIGLAFPMAMILTTLMVYSQMSGHSEIVALRSCGISIYRMI
IPTIILSLTVTTLSFALNEIIVPSANYQASLILEKTLEQENPPFKEENIFYPEFGKVKQP
DGSQDDTLTRLFYAE-----KFDGKYMQGVTILDRSQYGVDQIVSSESATWNSAENIWDL
FNGTIYLVSPDGSYRNIVKFDHKKLKLSTAPLDLAGKRRTYKQMNISQSYEYLELMRLSG
NY---RKVVKTQVRIQQKLALPFVCLVMGLVGAALGIRPQRKANRGTSFGISVIIIFAYY
LLSFI-TGAMGQKEILTPFLAG--WLPNFLGLGVAVFLLARVSR
