>Thhalv10008098m|pacid:20187795
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaaaaaatcggtatc------cgccaaagctgactcctgc
ttagagttgcgtcggatccgcaactagttggtcgttc-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------agagaagaagaagaagaaaatgattccttggg
gtggagttacctgctgcctgagcgctgccgctctttatcttctcggccggagtagtggca
gggatgctgaagtactcaaaaccgtcactcgggttagccagcttaaggaattagcgcaat
tgctagagttagatagcagcaagctcctgcctttcattgtggcggtatcaggaagagttg
gctctgagacacctatcaagtgtgagcatagtggcatacgcggtgttatcgtcgaggaaa
cggcggaacaacattttctgaaacacaatgagacgggttcttgggtacaagatagtgcat
tgatgctgtcaatgagtaaggaggttccttggtttctggacgatgggacaagtcgtgtca
atgtggtgggagctcgtggtgcaacaggatttgccttgactgttggaagtgaagtatttg
aagagtcagggcgttcgcttgtacgaggaacacttgattatcttcaaggcctcaagatgc
ttggagtaaaacgcattgagcgcgttcttccaactggaatgccgctaacaattgttggtg
aggctgtcaaggacgatattggtgatttacggattcagaaacctgaaagggggcctttct
acgtctctcctaaatcactcgatcagctcatttctaatttgggaaaatggtcaaggtggt
acaagtacgcctccatgggtttaactgtttttggtgtgtttctaataacaaaacatgtta
ttgattctgttctagagagaagacgacggcgagagttacagaaaagagtgcttgatgcag
cagctaagagagctgagcgagagagtga--------------------------------
----------------------------------------aggctcaaacgggacacatg
agagcgtttcagattctaccaagaaagaagacgctgttcctgatctatgtgtgatctgcc
tagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcaccgcat
gctcttgccacttgaccagctgtccactttgccggagacgaatagatcaggtcgttaaga
cttaccgtcactgaacaacaactcaaccgtcagaagcattctctactcgtgtcttgtctg
tatcaaaacgatcagtttagcctccgttatcctctcttgtttgattttgagaacagtaca
tttgaattatatatattgtatacattttgataacactacatctaaaattgtagccttgga
aactaaagtgtccttgaaagactaaacatttttatttggcaagtcggttcgtaacaatgt
attaggcttcattaagaagaaattagatgtgataattgttgtcctcgatgcagtgtagca
aaggaaacgattaatcatggatactttcaattcctcttccttaaatgggtttg
>Thhalv10008105m|pacid:20187794
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaaaaaatcggtatc------cgccaaagctgactcctgc
ttagagttgcgtcggatccgcaactagttggtcgttcaga--cagcgtcgacga------
------------------------------------------------------------
------------------------------gatatttttctggtctttcttcgtctataa
atccattcattcaa----------------------------------------------
------------------------------------------------------------
----------------------------agagaagaagaagaagaaaatgattccttggg
gtggagttacctgctgcctgagcgctgccgctctttatcttctcggccggagtagtggca
gggatgctgaagtactcaaaaccgtcactcgggttagccagcttaaggaattagcgcaat
tgctagagttagatagcagcaagctcctgcctttcattgtggcggtatcaggaagagttg
gctctgagacacctatcaagtgtgagcatagtggcatacgcggtgttatcgtcgaggaaa
cggcggaacaacattttctgaaacacaatgagacgggttcttgggtacaagatagtgcat
tgatgctgtcaatgagtaaggaggttccttggtttctggacgatgggacaagtcgtgtca
atgtggtgggagctcgtggtgcaacaggatttgccttgactgttggaagtgaagtatttg
aagagtcagggcgttcgcttgtacgaggaacacttgattatcttcaaggcctcaagatgc
ttggagtaaaacgcattgagcgcgttcttccaactggaatgccgctaacaattgttggtg
aggctgtcaaggacgatattggtgatttacggattcagaaacctgaaagggggcctttct
acgtctctcctaaatcactcgatcagctcatttctaatttgggaaaatggtcaaggtggt
acaagtacgcctccatgggtttaactgtttttggtgtgtttctaataacaaaacatgtta
ttgattctgttctagagagaagacgacggcgagagttacagaaaagagtgcttgatgcag
cagctaagagagctgagcgagagagtga--------------------------------
----------------------------------------aggctcaaacgggacacatg
agagcgtttcagattctaccaagaaagaagacgctgttcctgatctatgtgtgatctgcc
tagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcaccgcat
gctcttgccacttgaccagctgtccactttgccggagacgaatagatcaggtcgttaaga
cttaccgtcactgaacaacaactcaaccgtcagaagcattctctactcgtgtcttgtctg
tatcaaaacgatcagtttagcctccgttatcctctcttgtttgattttgagaacagtaca
tttgaattatatatattgtatacattttgataacactacatctaaaattgtagccttgga
aactaaagtgtccttgaaagactaaacatttttatttggcaagtcggttcgtaacaatgt
attaggcttcattaagaagaaattagatgtgataattgttgtcctcgatgcagtgtagca
aaggaaacgattaatcatggatactttcaattcctcttccttaaatgggtttg
>Thhalv10008368m|pacid:20187796
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaaaaaatcggtatc------cgccaaagctgactcctgc
ttagagttgcgtcggatccgcaactagttggtcgttcaga--cagcgtcgacga------
------------------------------------------------------------
------------------------------gatatttttctggtctttcttcgtctataa
atccattcattcaa----------------------------------------------
------------------------------------------------------------
----------------------------agagaagaagaagaagaaaatgattccttggg
gtggagttacctgctgcctgagcgctgccgctctttatcttctcggccggagtagtggca
gggatgctgaagtactcaaaaccgtcactcgggttagccagcttaaggaattagcgcaat
tgctagagttagatagcagcaagctcctgcctttcattgtggcggtatcaggaagagttg
gctctgagacacctatcaagtgtgagcatagtggcatacgcggtgttatcgtcgaggaaa
cggcggaacaacattttctgaaacacaatgagacgggttcttgggtacaagatagtgcat
tgatgctgtcaatgagtaaggaggttccttggtttctggacgatgggacaagtcgtgtca
atgtggtgggagctcgtggtgcaacaggatttgccttgactgttggaagtgaagtatttg
aagagtcagggcgttcgcttgtacgaggaacacttgattatcttcaaggcctcaagatgc
ttggagtaaaacgcattgagcgcgttcttccaactggaatgccgctaacaattgttggtg
aggctgtcaaggacgatattggtgatttacggattcagaaacctgaaagggggcctttct
acgtctctcctaaatcactcgatcagctcatttctaatttgggaaaatggtcaaggtggt
acaagtacgcctccatgggtttaactgtttttggtgtgtttctaataacaaaacatgtta
ttgattctgttctagagagaagacgacggcgagagttacagaaaagagtgcttgatgcag
cagctaagagagctgagcgagagagtgaaggtatatccattggtgaatcttactctacat
attggttgcactggctctgactaacagaactcttgtcatcaggctcaaacgggacacatg
agagcgtttcagattctaccaagaaagaagacgctgttcctgatctatgtgtgatctgcc
tagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcaccgcat
gctcttgccacttgaccagctgtccactttgccggagacgaatagatcaggtcgttaaga
cttaccgtcactgaacaacaactcaaccgtcagaagcattctctactcgtgtcttgtctg
tatcaaaacgatcagtttagcctccgttatcctctcttgtttgattttgagaacagtaca
tttgaattatatatattgtatacattttgataacactacatctaaaattgtagccttgga
aactaaagtgtccttgaaagactaaacatttttatttggcaagtcggttcgtaacaatgt
attaggcttcattaagaagaaattagatgtgataattgttgtcctcgatgcagtgtagca
aaggaaacgattaatcatggatactttcaattcctcttccttaaatgggtttg
>Thhalv10008100m|pacid:20187793
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaaaaaatcggtatc------cgccaaagctgactcctgc
ttagagttgcgtcggatccgcaactagttggtcgttcagatccaacgacaatcaccgaac
gccccgaataatcgataactccatcactgtctgattcttagcggagataatcacgatcat
gtttcaatgctctatgtattaatcaagcttcgtttgctcctagaccctatttttttttaa
tttcatctgtccagatccgaacaatacattcaataaaaattaaattcgctgcttaatttg
aatcctatctctctgctcatcatctggagaggcattattcttcttcaaacaaataagagt
gacttcaaaattcaatctctctctctttagagaagaagaagaagaaaatgattccttggg
gtggagttacctgctgcctgagcgctgccgctctttatcttctcggccggagtagtggca
gggatgctgaagtactcaaaaccgtcactcgggttagccagcttaaggaattagcgcaat
tgctagagttagatagcagcaagctcctgcctttcattgtggcggtatcaggaagagttg
gctctgagacacctatcaagtgtgagcatagtggcatacgcggtgttatcgtcgaggaaa
cggcggaacaacattttctgaaacacaatgagacgggttcttgggtacaagatagtgcat
tgatgctgtcaatgagtaaggaggttccttggtttctggacgatgggacaagtcgtgtca
atgtggtgggagctcgtggtgcaacaggatttgccttgactgttggaagtgaagtatttg
aagagtcagggcgttcgcttgtacgaggaacacttgattatcttcaaggcctcaagatgc
ttggagtaaaacgcattgagcgcgttcttccaactggaatgccgctaacaattgttggtg
aggctgtcaaggacgatattggtgatttacggattcagaaacctgaaagggggcctttct
acgtctctcctaaatcactcgatcagctcatttctaatttgggaaaatggtcaaggtggt
acaagtacgcctccatgggtttaactgtttttggtgtgtttctaataacaaaacatgtta
ttgattctgttctagagagaagacgacggcgagagttacagaaaagagtgcttgatgcag
cagctaagagagctgagcgagagagtga--------------------------------
----------------------------------------aggctcaaacgggacacatg
agagcgtttcagattctaccaagaaagaagacgctgttcctgatctatgtgtgatctgcc
tagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcaccgcat
gctcttgccacttgaccagctgtccactttgccggagacgaatagatcaggtcgttaaga
cttaccgtcactgaacaacaactcaaccgtcagaagcattctctactcgtgtcttgtctg
tatcaaaacgatcagtttagcctccgttatcctctcttgtttgattttgagaacagtaca
tttgaattatatatattgtatacattttgataacactacatctaaaattgtagccttgga
aactaaagtgtccttgaaagactaaacatttttatttggcaagtcggttcgtaacaatgt
attaggcttcattaagaagaaattagatgtgataattgttgtcctcgatgcagtgtagca
aaggaaacgattaatcatggatactttcaattcctcttccttaaatgggtttg
>Thhalv10008106m|pacid:20187792
c----------ttccttgtttctgt----cttttatcatcttcttccccaaaccctgagc
ttgagaatatgagagagatcaaacaaaagatcatccaattacaataatctgaactttttc
ttcgaaat---ttacgtcttccatcgattcg-----cagatccaacgacaatcaccgaac
gccccgaataatcgataactccatcactgtctgattcttagcggagataatcacgatcat
gtttcaatgctct-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------atagaagaagaagaagaaaatgattccttggg
gtggagttacctgctgcctgagcgctgccgctctttatcttctcggccggagtagtggca
gggatgctgaagtactcaaaaccgtcactcgggttagccagcttaaggaattagcgcaat
tgctagagttagatagcagcaagctcctgcctttcattgtggcggtatcaggaagagttg
gctctgagacacctatcaagtgtgagcatagtggcatacgcggtgttatcgtcgaggaaa
cggcggaacaacattttctgaaacacaatgagacgggttcttgggtacaagatagtgcat
tgatgctgtcaatgagtaaggaggttccttggtttctggacgatgggacaagtcgtgtca
atgtggtgggagctcgtggtgcaacaggatttgccttgactgttggaagtgaagtatttg
aagagtcagggcgttcgcttgtacgaggaacacttgattatcttcaaggcctcaagatgc
ttggagtaaaacgcattgagcgcgttcttccaactggaatgccgctaacaattgttggtg
aggctgtcaaggacgatattggtgatttacggattcagaaacctgaaagggggcctttct
acgtctctcctaaatcactcgatcagctcatttctaatttgggaaaatggtcaaggtggt
acaagtacgcctccatgggtttaactgtttttggtgtgtttctaataacaaaacatgtta
ttgattctgttctagagagaagacgacggcgagagttacagaaaagagtgcttgatgcag
cagctaagagagctgagcgagagagtga--------------------------------
----------------------------------------aggctcaaacgggacacatg
agagcgtttcagattctaccaagaaagaagacgctgttcctgatctatgtgtgatctgcc
tagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatgtgctgctgcaccgcat
gctcttgccacttgaccagctgtccactttgccggagacgaatagatcaggtcgttaaga
cttaccgtcactgaacaacaactcaaccgtcagaagcattctctactcgtgtcttgtctg
tatcaaaacgatcagtttagcctccgttatcctctcttgtttgattttgagaacagtaca
tttgaattatatatattgtatacattttgataacactacatctaaaattgtagccttgga
aactaaagtgtccttgaaagactaaacatttttatttggcaagtcggttcgtaacaatgt
attaggcttcattaagaagaaattagatgtgataattgttgtcctcgatgcagtgtagca
aaggaaacgattaatcatggatactttcaattcctcttccttaaatgggtttg
>gi|145337145|ref|NM_105064.3| Arabidopsis thaliana E3 ubiquitin ligase-like protein (AT1G63900) mRNA, complete cds
ATGAGAATATTGAGAGAGATCGAAGCAAAGGATCATTCAATTCCAACCCTCTGAATCTTTTAATTTCCCC
TTTCGAAATTCTCCTCTTCTTTCACTGCTTCTAGTTTCTAATTCTTCAAACTCTTCCTCGATTCATACTC
ATAACTCTCATTAGCTAATTTCGCATGATCTTCTTCCATCTCTCTGTGTTCTAAATCCAGATTCGTTTCA
CTCCCATCTCTATTTCATTCAATTCGCTGCATCCAGATTCAAAACCTACCTCTATCTCTCTGCTCATCAA
TAACTTCAAAGGTATTGTTGTTCTTCTGCAAACAAGTAAGAGTGACTTCAGAGTCTGATGATTCCTTGGG
GTGGAGTTACTTGCTGCCTCAGCGCCGCTGCTCTTTATCTTCTCGGCCGGAGTAGTGGCAGGGATGCTGA
AGTACTCGAAACAGTCACTAGGGTTAATCAGCTCAAGGAGTTAGCTCAATTGCTAGAATTAGATAGCAAG
ATTCTGCCTTTCATTGTTGCGGTATCAGGAAGAGTCGGCTCTGAGACACCTATCAAATGCGAGCATAGTG
GCATACGCGGTGTTATTGTTGAAGAAACGGCGGAACAACATTTCCTGAAACATAATGAGACGGGTTCTTG
GGTACAAGATAGTGCGTTGATGCTATCAATGAGCAAAGAGGTTCCTTGGTTTCTGGACGATGGGACAAGC
CGTGTCCATGTAATGGGAGCTCGTGGTGCGACGGGTTTTGCCTTGACTGTTGGTAGTGAAGTTTTTGAAG
AGTCAGGACGCTCGCTTGTACGAGGAACACTTGATTATCTTCAAGGACTTAAGATGCTTGGAGTTAAGCG
CATTGAGCGTGTTCTTCCAACTGGAATACCGCTAACAATTGTTGGTGAGGCTGTCAAGGACGATATTGGA
GAATTCAGGATTCAAAAACCTGACAGGGGCCCTTTCTACGTCTCTTCTAAATCACTCGATCAGCTCATTT
CTAATTTGGGAAAATGGTCAAGGTTGTACAAATATGCCTCCATGGGTTTTACTGTTCTTGGTGTGTTCCT
AATTACGAAGCATGTCATTGACTCTGTTCTAGAGAGAAGACGGCGGAGACAGTTACAAAAAAGAGTGCTT
GACGCAGCAGCAAAGAGAGCTGAGCTAGAGAGTGAAGGTTCAAACGGGACACGTGAGAGCATTTCAGATT
CTACCAAGAAAGAAGACGCTGTTCCTGATCTCTGTGTGATATGCCTAGAGCAGGAGTACAACGCTGTGTT
TGTCCCGTGTGGTCATATGTGCTGCTGCACCGCATGCTCCTCCCACTTGACCAGCTGTCCACTTTGTCGG
AGACGAATAGATCTGGCGGTTAAGACATATCGTCACTGAACAACAACTCAGGCCTCAGAAACATTCTCTA
CTTGAGTCTTGTCTGTAAATACCGCAAAATCAAAACATTACACAGTTTAGCGTTCGATATTCCCTTTGGT
TTGATTTCGACAACAAAACATTTTGAATTATATAGAAACATAAGGTGTTTACTCGATTTGCAAAACAGTA
CATTCGTGTTTACTTATTCGTGTTGTTGCCAATGCCATGAGGTG
