>Thhalv10008098m|pacid:20187795
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaa-aaaatcggtatc------cgccaaagctgactcctg
---------cttagagttgcgtcggatccgcaactagttggtcgttc-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------agagaagaagaagaag
aaaatgattccttggggtggagttacctgctgcctgagcgctgccgctctttatcttctc
ggccggagtagtggcagggatgctgaagtactcaaaaccgtcactcgggttagccagctt
aaggaattagcgcaattgctagagttagatagcagcaagctcctgcctttcattgtggcg
gtatcaggaagagttggctctgagacacctatcaagtgtgagcatagtggcatacgcggt
gttatcgtcgaggaaacggcggaacaacattttctgaaacacaatgagacgggttcttgg
gtacaagatagtgcattgatgctgtcaatgagtaaggaggttccttggtttctggacgat
gggacaagtcgtgtcaatgtggtgggagctcgtggtgcaacaggatttgccttgactgtt
ggaagtgaagtatttgaagagtcagggcgttcgcttgtacgaggaacacttgattatctt
caaggcctcaagatgcttggagtaaaacgcattgagcgcgttcttccaactggaatgccg
ctaacaattgttggtgaggctgtcaaggacgatattggtgatttacggattcagaaacct
gaaagggggcctttctacgtctctcctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggtggtacaagtacgcctccatgggtttaactgtttttggtgtgtttcta
ataacaaaacatgttattgattctgttctagagagaagacgacggcgagagttacagaaa
agagtgcttgatgcagcagctaagagagctgagcgagagagtga----------------
--------------------------------------------------------aggc
tcaaacgggacacatgagagcgtttcagattctaccaagaaagaagacgctgttcctgat
ctatgtgtgatctgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatg
tgctgctgcaccgcatgctcttgccacttgaccagctgtccactttgccggagacgaata
gatcaggtcgttaagacttaccgtcactgaacaacaactcaaccgtcagaagcattctct
actcgtgtcttgtctgt------------atcaaaacgat---cagtttagcctccgtta
tcctctcttgtttgattttgagaacagtaca-tttgaattatatatattgtatacatttt
gataacactacatctaaaattgtagccttggaaactaaagtgtc-------cttgaaaga
ctaaacatttttatttggcaagtcggttcgtaacaatgtattaggcttcattaagaagaa
attagatgtgataattgttgtcctcgatgcagtgtagcaaaggaaacgattaatcatgga
tactttcaattcctcttccttaaatgggtttg
>Thhalv10008105m|pacid:20187794
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaa-aaaatcggtatc------cgccaaagctgactcctg
---------cttagagttgcgtcggatccgcaactagttggtcgttcaga--cagcgtcg
acga--------------------------------------------------------
----------------------------------------gatatttttctggtctttct
tcgtctataaatccattcattcaa------------------------------------
------------------------------------------------------------
--------------------------------------------agagaagaagaagaag
aaaatgattccttggggtggagttacctgctgcctgagcgctgccgctctttatcttctc
ggccggagtagtggcagggatgctgaagtactcaaaaccgtcactcgggttagccagctt
aaggaattagcgcaattgctagagttagatagcagcaagctcctgcctttcattgtggcg
gtatcaggaagagttggctctgagacacctatcaagtgtgagcatagtggcatacgcggt
gttatcgtcgaggaaacggcggaacaacattttctgaaacacaatgagacgggttcttgg
gtacaagatagtgcattgatgctgtcaatgagtaaggaggttccttggtttctggacgat
gggacaagtcgtgtcaatgtggtgggagctcgtggtgcaacaggatttgccttgactgtt
ggaagtgaagtatttgaagagtcagggcgttcgcttgtacgaggaacacttgattatctt
caaggcctcaagatgcttggagtaaaacgcattgagcgcgttcttccaactggaatgccg
ctaacaattgttggtgaggctgtcaaggacgatattggtgatttacggattcagaaacct
gaaagggggcctttctacgtctctcctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggtggtacaagtacgcctccatgggtttaactgtttttggtgtgtttcta
ataacaaaacatgttattgattctgttctagagagaagacgacggcgagagttacagaaa
agagtgcttgatgcagcagctaagagagctgagcgagagagtga----------------
--------------------------------------------------------aggc
tcaaacgggacacatgagagcgtttcagattctaccaagaaagaagacgctgttcctgat
ctatgtgtgatctgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatg
tgctgctgcaccgcatgctcttgccacttgaccagctgtccactttgccggagacgaata
gatcaggtcgttaagacttaccgtcactgaacaacaactcaaccgtcagaagcattctct
actcgtgtcttgtctgt------------atcaaaacgat---cagtttagcctccgtta
tcctctcttgtttgattttgagaacagtaca-tttgaattatatatattgtatacatttt
gataacactacatctaaaattgtagccttggaaactaaagtgtc-------cttgaaaga
ctaaacatttttatttggcaagtcggttcgtaacaatgtattaggcttcattaagaagaa
attagatgtgataattgttgtcctcgatgcagtgtagcaaaggaaacgattaatcatgga
tactttcaattcctcttccttaaatgggtttg
>Thhalv10008368m|pacid:20187796
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaa-aaaatcggtatc------cgccaaagctgactcctg
---------cttagagttgcgtcggatccgcaactagttggtcgttcaga--cagcgtcg
acga--------------------------------------------------------
----------------------------------------gatatttttctggtctttct
tcgtctataaatccattcattcaa------------------------------------
------------------------------------------------------------
--------------------------------------------agagaagaagaagaag
aaaatgattccttggggtggagttacctgctgcctgagcgctgccgctctttatcttctc
ggccggagtagtggcagggatgctgaagtactcaaaaccgtcactcgggttagccagctt
aaggaattagcgcaattgctagagttagatagcagcaagctcctgcctttcattgtggcg
gtatcaggaagagttggctctgagacacctatcaagtgtgagcatagtggcatacgcggt
gttatcgtcgaggaaacggcggaacaacattttctgaaacacaatgagacgggttcttgg
gtacaagatagtgcattgatgctgtcaatgagtaaggaggttccttggtttctggacgat
gggacaagtcgtgtcaatgtggtgggagctcgtggtgcaacaggatttgccttgactgtt
ggaagtgaagtatttgaagagtcagggcgttcgcttgtacgaggaacacttgattatctt
caaggcctcaagatgcttggagtaaaacgcattgagcgcgttcttccaactggaatgccg
ctaacaattgttggtgaggctgtcaaggacgatattggtgatttacggattcagaaacct
gaaagggggcctttctacgtctctcctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggtggtacaagtacgcctccatgggtttaactgtttttggtgtgtttcta
ataacaaaacatgttattgattctgttctagagagaagacgacggcgagagttacagaaa
agagtgcttgatgcagcagctaagagagctgagcgagagagtgaaggtatatccattggt
gaatcttactctacatattggttgcactggctctgactaacagaactcttgtcatcaggc
tcaaacgggacacatgagagcgtttcagattctaccaagaaagaagacgctgttcctgat
ctatgtgtgatctgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatg
tgctgctgcaccgcatgctcttgccacttgaccagctgtccactttgccggagacgaata
gatcaggtcgttaagacttaccgtcactgaacaacaactcaaccgtcagaagcattctct
actcgtgtcttgtctgt------------atcaaaacgat---cagtttagcctccgtta
tcctctcttgtttgattttgagaacagtaca-tttgaattatatatattgtatacatttt
gataacactacatctaaaattgtagccttggaaactaaagtgtc-------cttgaaaga
ctaaacatttttatttggcaagtcggttcgtaacaatgtattaggcttcattaagaagaa
attagatgtgataattgttgtcctcgatgcagtgtagcaaaggaaacgattaatcatgga
tactttcaattcctcttccttaaatgggtttg
>Thhalv10008100m|pacid:20187793
caatatagggggcccgaaattctgttgggcctttatgataataat----aattctctgat
tcataaatatgtcaccgatttaa-aaaatcggtatc------cgccaaagctgactcctg
---------cttagagttgcgtcggatccgcaactagttggtcgttcagatccaacgaca
atcaccgaacgccccgaataatcgataactccatcactgtctgattcttagcggagataa
tcacgatcatgtttcaatgctctatgtattaatcaagcttcgtttgctcctagaccctat
ttttttttaatttcatctgtccagatccgaacaatacattcaataaaaattaaattcgct
gcttaatttgaatcctatctctctgctcatca------tctggagaggcattattcttct
tcaaacaaataagagtgacttcaaaattcaatctctctctctttagagaagaagaagaag
aaaatgattccttggggtggagttacctgctgcctgagcgctgccgctctttatcttctc
ggccggagtagtggcagggatgctgaagtactcaaaaccgtcactcgggttagccagctt
aaggaattagcgcaattgctagagttagatagcagcaagctcctgcctttcattgtggcg
gtatcaggaagagttggctctgagacacctatcaagtgtgagcatagtggcatacgcggt
gttatcgtcgaggaaacggcggaacaacattttctgaaacacaatgagacgggttcttgg
gtacaagatagtgcattgatgctgtcaatgagtaaggaggttccttggtttctggacgat
gggacaagtcgtgtcaatgtggtgggagctcgtggtgcaacaggatttgccttgactgtt
ggaagtgaagtatttgaagagtcagggcgttcgcttgtacgaggaacacttgattatctt
caaggcctcaagatgcttggagtaaaacgcattgagcgcgttcttccaactggaatgccg
ctaacaattgttggtgaggctgtcaaggacgatattggtgatttacggattcagaaacct
gaaagggggcctttctacgtctctcctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggtggtacaagtacgcctccatgggtttaactgtttttggtgtgtttcta
ataacaaaacatgttattgattctgttctagagagaagacgacggcgagagttacagaaa
agagtgcttgatgcagcagctaagagagctgagcgagagagtga----------------
--------------------------------------------------------aggc
tcaaacgggacacatgagagcgtttcagattctaccaagaaagaagacgctgttcctgat
ctatgtgtgatctgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatg
tgctgctgcaccgcatgctcttgccacttgaccagctgtccactttgccggagacgaata
gatcaggtcgttaagacttaccgtcactgaacaacaactcaaccgtcagaagcattctct
actcgtgtcttgtctgt------------atcaaaacgat---cagtttagcctccgtta
tcctctcttgtttgattttgagaacagtaca-tttgaattatatatattgtatacatttt
gataacactacatctaaaattgtagccttggaaactaaagtgtc-------cttgaaaga
ctaaacatttttatttggcaagtcggttcgtaacaatgtattaggcttcattaagaagaa
attagatgtgataattgttgtcctcgatgcagtgtagcaaaggaaacgattaatcatgga
tactttcaattcctcttccttaaatgggtttg
>Thhalv10008106m|pacid:20187792
c----------ttccttgtttctgt----cttttatcatcttcttccccaaaccctgagc
ttgagaatatgagagagatcaaa-caaaagatcatccaattacaataatctgaacttttt
---------cttcgaaat---ttacgtcttccatcgattcg-----cagatccaacgaca
atcaccgaacgccccgaataatcgataactccatcactgtctgattcttagcggagataa
tcacgatcatgtttcaatgctct-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------atagaagaagaagaag
aaaatgattccttggggtggagttacctgctgcctgagcgctgccgctctttatcttctc
ggccggagtagtggcagggatgctgaagtactcaaaaccgtcactcgggttagccagctt
aaggaattagcgcaattgctagagttagatagcagcaagctcctgcctttcattgtggcg
gtatcaggaagagttggctctgagacacctatcaagtgtgagcatagtggcatacgcggt
gttatcgtcgaggaaacggcggaacaacattttctgaaacacaatgagacgggttcttgg
gtacaagatagtgcattgatgctgtcaatgagtaaggaggttccttggtttctggacgat
gggacaagtcgtgtcaatgtggtgggagctcgtggtgcaacaggatttgccttgactgtt
ggaagtgaagtatttgaagagtcagggcgttcgcttgtacgaggaacacttgattatctt
caaggcctcaagatgcttggagtaaaacgcattgagcgcgttcttccaactggaatgccg
ctaacaattgttggtgaggctgtcaaggacgatattggtgatttacggattcagaaacct
gaaagggggcctttctacgtctctcctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggtggtacaagtacgcctccatgggtttaactgtttttggtgtgtttcta
ataacaaaacatgttattgattctgttctagagagaagacgacggcgagagttacagaaa
agagtgcttgatgcagcagctaagagagctgagcgagagagtga----------------
--------------------------------------------------------aggc
tcaaacgggacacatgagagcgtttcagattctaccaagaaagaagacgctgttcctgat
ctatgtgtgatctgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatg
tgctgctgcaccgcatgctcttgccacttgaccagctgtccactttgccggagacgaata
gatcaggtcgttaagacttaccgtcactgaacaacaactcaaccgtcagaagcattctct
actcgtgtcttgtctgt------------atcaaaacgat---cagtttagcctccgtta
tcctctcttgtttgattttgagaacagtaca-tttgaattatatatattgtatacatttt
gataacactacatctaaaattgtagccttggaaactaaagtgtc-------cttgaaaga
ctaaacatttttatttggcaagtcggttcgtaacaatgtattaggcttcattaagaagaa
attagatgtgataattgttgtcctcgatgcagtgtagcaaaggaaacgattaatcatgga
tactttcaattcctcttccttaaatgggtttg
>gi|145337145|ref|NM_105064.3| Arabidopsis thaliana E3 ubiquitin ligase-like protein (AT1G63900) mRNA, complete cds
----------------------------------atgagaatatt---------------
----------gagagagatcgaagcaaaggatcattcaattccaaccctctgaatctttt
aatttcccctttcgaaattctcctcttctttcactgcttctagtttctaattc-------
ttcaaactcttcctcgattcatactcataactctcattagctaatttcg-----------
-catgatcttcttccatctctctgtgttctaaatccagattcgtttcactcccatctcta
tttcattcaattcgctgcatccagattcaaaacctac-----------------------
------------ctctatctctctgctcatcaataacttcaaaggtattgttgttcttct
gcaaacaagtaagagtgacttcagagtct-------------------------------
--gatgattccttggggtggagttacttgctgcctcagcgccgctgctctttatcttctc
ggccggagtagtggcagggatgctgaagtactcgaaacagtcactagggttaatcagctc
aaggagttagctcaattgctagaattagat---agcaagattctgcctttcattgttgcg
gtatcaggaagagtcggctctgagacacctatcaaatgcgagcatagtggcatacgcggt
gttattgttgaagaaacggcggaacaacatttcctgaaacataatgagacgggttcttgg
gtacaagatagtgcgttgatgctatcaatgagcaaagaggttccttggtttctggacgat
gggacaagccgtgtccatgtaatgggagctcgtggtgcgacgggttttgccttgactgtt
ggtagtgaagtttttgaagagtcaggacgctcgcttgtacgaggaacacttgattatctt
caaggacttaagatgcttggagttaagcgcattgagcgtgttcttccaactggaataccg
ctaacaattgttggtgaggctgtcaaggacgatattggagaattcaggattcaaaaacct
gacaggggccctttctacgtctcttctaaatcactcgatcagctcatttctaatttggga
aaatggtcaaggttgtacaaatatgcctccatgggttttactgttcttggtgtgttccta
attacgaagcatgtcattgactctgttctagagagaagacggcggagacagttacaaaaa
agagtgcttgacgcagcagcaaagagagctgagctagagagtga----------------
--------------------------------------------------------aggt
tcaaacgggacacgtgagagcatttcagattctaccaagaaagaagacgctgttcctgat
ctctgtgtgatatgcctagagcaggagtacaacgctgtgtttgtcccgtgtggtcatatg
tgctgctgcaccgcatgctcctcccacttgaccagctgtccactttgtcggagacgaata
gatctggcggttaagacatatcgtcactgaacaacaactcaggcctcagaaacattctct
acttgagtcttgtctgtaaataccgcaaaatcaaaacattacacagtttagcgttcgata
ttccctttggtttgatttcgacaacaaaacattttgaattatata---------------
-----------------------------gaaacataaggtgtttactcgatttgcaaaa
cagtacattcgtgtttacttattcg-----------------------------------
---------------tgttgttgccaatgccatgagg-----------------------
------------------------------tg
