>gnl|BL_ORD_ID|419 @Ehrlichia_canis_Jake@ gi|73667053|ref|YP_303069.1| hypothetical protein Ecaj_0429 [Ehrlichia canis str. Jake]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--LVPQ---------------------EVIASNSLLCEYVKYTTINIKSATCIGSTDIIN
NKLKIHISKDSNLQPIVQPHAKSLF-----------------------------------
LLEVTIPSSIVKNDPYLR---------NI-YIISQSES----------------------
--LDANLYCLVDASHIQSFTNEIYDTVQNKVPKFVDNIFKYTEVI---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------FAKLEIDSHLKLNEYEILCSI---------------
-----------------------------------------LPDAE--------------
-FIIHEIEEKNSCCSCCPPFT---------------------------------------
----------SKQNITRVQSQESLLQENDAEQVTLPKPE---------------------
-------------------DNITNTSISSTDSSTEHNSISSLLSFVNVTIESINSFQNNS
K-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Mulan_NP_078820
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--ESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQE---------------------
--LKG---AKKVHLGEDLK--------SILSEAPGKCVPYAVIEGAVRSVKETLNSQFVE
NCKGVIQRLTLQEHKMVWNRTTHLWN-------------------DCSKIIHQRTNTVPF
DLVPHEDGV----DVAVR---------VL-KPLDSVDL----GLETVYEKFHPSIQSFTD
VIG------HYISGERPKGIQETEEMLK--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------VGATLTGVGELVLDNNSVR---------------
-----------------------------------------LQPPKQGMQYYLSSQD---
-FDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQYLQR------------------
----------QERLRLKQMQEEFQEHEAQLLSRAKPE-----------------------
-------------------DRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEPK
KCPICR------------------------------------------------------
---QAITRVIPLYNS---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Mulan_NP_078820
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--ESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQE---------------------
--LKG---AKKVHLGEDLK--------SILSEAPGKCVPYAVIEGAVRSVKETLNSQFVE
NCKGVIQRLTLQEHKMVWNRTTHLWN-------------------DCSKIIHQRTNTVPF
DLVPHEDGV----DVAVR---------VL-KPLDSVDL----GLETVYEKFHPSIQSFTD
VIG------HYISGERPKGIQETEEMLK--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------VGATLTGVGELVLDNNSVR---------------
-----------------------------------------LQPPKQGMQYYLSSQD---
-FDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQYLQR------------------
----------QERLRLKQMQEEFQEHEAQLLSRAKPE-----------------------
-------------------DRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEPK
KCPICR------------------------------------------------------
---QAITRVIPLYNS---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Mulan_NP_078820
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--ESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQE---------------------
--LKG---AKKVHLGEDLK--------SILSEAPGKCVPYAVIEGAVRSVKETLNSQFVE
NCKGVIQRLTLQEHKMVWNRTTHLWN-------------------DCSKIIHQRTNTVPF
DLVPHEDGV----DVAVR---------VL-KPLDSVDL----GLETVYEKFHPSIQSFTD
VIG------HYISGERPKGIQETEEMLK--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------VGATLTGVGELVLDNNSVR---------------
-----------------------------------------LQPPKQGMQYYLSSQD---
-FDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQYLQR------------------
----------QERLRLKQMQEEFQEHEAQLLSRAKPE-----------------------
-------------------DRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEPK
KCPICR------------------------------------------------------
---QAITRVIPLYNS---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|2252 Streptomyces_avermitilis_MA_4680 gi|29828788|ref|NP_823422.1| ABC transporter ATP-binding protein [Streptomyces avermitilis MA-4680]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------VHVSATPVLALRGVSKRFGAVQA---------------------
--LTD---VELEIHAGEVV--------ALVGDNGAGKSTLVKTIA---------------
------------------------------------------------------------
GVHPIDEGVIEWDGKAVQ--------------INKPHDAQNLGIATVYQDLALCDNIDVV
GNL------YLGRELRKRGILDEVEMERRSRELLTTLSIRIPSVRIPI------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------ASLSGGQRQTVAIARSM---------------
-----------------------------------------LGEPK--------------
-LVILDEPTAALGVE---------------------------------------------
----------QTAQVLDLVERLRERGHAVILIS---------------------------
-------------------HNMADVKAVADKVAVLRLGRNNGVFEVKSTSQEEII-----
------------------------------------------------------------
---SAITGATDNAVTRRAARNGEAQK----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|3363 @Pseudomonas_stutzeri_A1501@ gi|146283762|ref|YP_001173915.1| hypothetical protein PST_3445 [Pseudomonas stutzeri A1501]
M-----------------------------------------------------------
--------------------------------LNATTWFERYQQRYRWATRAYDR-----
---------------------------------------------------FVQDLVPEL
VDTLQRNEQVTVAVYGATQVGKTTLILDLLGLSTLTTNEVGSVLRGG-------------
-------------------------------------QQLGKSATAMPIRYGRSLDDGWY
IAGEGPLSADTARETLRAFRRKVESGGICDAEVLDIRIPRGLFQQC--------------
------------------------------------------------------------
-------------DDSSAGLELNIIDIPGINSHSSAEQA---------------------
--L-----VTKLADRYVVA--------ADIVLLVGKADSLGFLNERDLIIPALADWAAQP
TRFRIVLTYGFSPDSLVSQFKDQELTVEQVRDVHIGQMRTHDYVFPPEFRSNLFVLELGD
SIVDLGRTNPEYLQRILQ---------VT-NDFRGELLENIVKAAGPYARLQGAFQLDRV
IN-------ARVERLRKALENQEVEYGRQRRQITDELAAFHPELLDASDEEIYVAIDKLG
VDRLDLKNKLDELSASIKRLEEFNCAALFLTEFSAGAVEKVSWLQ---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------EQLENCEQLQRKACIQAASLL---------------
-----------------FDKGVLPSWLKDEVPVIEYQRKALLDIDSHLNSYVLDGYW---
-WSSSNFNEDRNSLQKALRLNAR-------------------------------------
----------EHGERIQSATKRALHERKRALLADYKNLKSHCIILQSYLESLQALEREYR
CICAEYADDLQEMDRALGMASSFESQLNAAFMEELRSTKEDVESHPVPAQRFYGLLHTRL
LLSEID------------------------------------------------------
---RMYEGKSF-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|1267 @Frankia_alni_ACN14a@ gi|111220773|ref|YP_711567.1| unnamed protein product [Frankia alni ACN14a]
MLYLAGQILAYVLVAMVIGAALAWVFLIAPLRRQVRQTRDAQPDPTVDGAEPAPAADAVE
ADAVEADGTDAGRTEAWGIEARETDARETDPRSADRAGTALALLPSPGEPYPREL-----
---------------------------------------------------GGEIAVGGD
SGRVPESAGSSERAGAPATVGDRLGQDADSRAFVPDTVGAELATTGPIPLPINAVRVGEP
VAELVAL--------------------LRRQRDDAALEKADLTARLAVAEQRAAESEQRI
GAAERHAMTASARVEEIESTLRARVEAATSAAGG--------------------------
------------------------------------------------------------
--GTRAVDAPSPTGPDTTAADTGLTVAELAREAELLRQQ---------------------
--L-----VEAEGRAAKFS--------SRLAMARTEAEDAQRLVATMTTRLDRHQAEWAA
ERLSLLGRIERTEASLERGTEAASAANPVAEP----------------------------
ASAAVEYAELVGTAKALA---------SA-RAVRSTRA----------------------
-----AVPLFAAEPAEVAEPAEVAEPVDADEPVDVAEPGGTP------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------EPVDRAEPVDRAEPVDGAESV---------------
---------------------------------DAVVSPGVAGPGR--------------
------EDEPAVG-----------------------------------------------
----------EESARLDESVRPHSDGAALAAAASVES-----------------------
-------------------GTAAPAGSEPVRAGALGVAGMRARTSGVTKERPAAVAGVPA
PTGSGS------------------------------------------------------
---VTAPGVRSGATGEQAAGGRVVQEAAPRWNGLLDPGGAVGDNLKEIVGIGPVIESRLR
TLGITTFSQLAEMGDTDVDRLAHKLDGFGDRIISDDWVGQAQDLQVRHYGGVF-------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|2990 @Methylibium_petroleiphilum_PM1@ gi|124268184|ref|YP_001022188.1| uroporphyrin-III methylase [Methylibium petroleiphilum PM1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------QLGLMLLLLLVSVTALSMAWYGQRRVR
TLEQELVRRQQDSAGQAAEAQLLAKQAQELSRDAVAKVT---------------------
--LTESRLAEITAQRGQLE--------ELIQSLSRARDENLVVDIDAGIRVALQQTAITG
SAAPLVAALKAADERLARVSQP--------------------------------------
RLEPVRRAIARDLDRVKA---------VSVADIASLAI----------------------
---------KLDEAARLVDEAPLQVLDPQRLAEAKAPRAV--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ARVAPSPASAAASAAPVGGLR---------------
-----------------------------------------AELGDWWQGLWAETRT---
-LLRVTRIDQPQAMLLAP------------------------------------------
----------EQGFFLRENLKLRLLNARLALMSRQFD-----------------------
-------------------TAQSDLQAAVAAVDNYFDRGARKTQLLTELLRSVVPQARQA
GVPRPD------------------------------------------------------
---DTLAALTTAAAGR--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|2307 @Rubrobacter_xylanophilus_DSM_9941@ gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------VGTVVFLLVGVVLCVAGGVLLYF------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------RRRMLGKAE---------------------
--LMR---RTRTSGAAGVS--------A--------------------------------
------------------------------------------------------------
----LSPGTLVEVKGTLR---------CE-RPLQS-------------------------
------------------------EMAKERCAYYSSKVVREYLERDRGDGAPGSGRRSEV
LARSERFAPFVVE-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------DDTGGVPVSAEGAEVDAKKVVDRFERGAGAAGLSVT
IGGATIDLGGGERTLGYRHTEEILPVDAPVYVLGAVRRDGGIGPPE------EGAGR---
-FVVSWRSEEALGESLGRGARLLGLI----------------------------------
----------ALGLFLAGAAFLAVGAAAALGYLQFR------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|1342 @Rhodopseudomonas_palustris_CGA009@ RPA1350 putative transport protein ExbB2
MTIEKNDVRGAGWGWSRGAKSVAKAVTKAGLLAAVGGMLLTATPANAWWNDEWQLRKKIT
IDTSAAGANITDPIGTTPVLVRLHTGNFRFNATKEDGGDLRFVAGDDKTPLKYHVEKFDA
LLGEALVWVAVPDLQPGAKTDLWLYYGNKKAVAIADSKGTYDPDTQLVYHFAERGTVPLD
STVWANNAQSVGQPADGAIIGTGLRLDGRTPLTLPSSSALALAGSGGWTWSAWVKPAAAQ
PNSALYS-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--RRDGGNAVVIGFDNGAPFVEVANAGAVQRSATAAPVA---------------------
--LNSWHHVAVVAGNGRVTLYLDGNAYAVLDAALPALNTLAFVGGDALASNPAPTASPAA
SQAPLPDGSSPQGAPT--------------------------------------------
GDAPAADAPVAAAPAAMA---------GFAGDIDEL------------------------
---------EISKASRPAGFVRVAALGQG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------LDKGK--------------
-LLTFTIDEETASWLSGYFAVILKSVTLDGWVVIAILMVMAVISWMVMV-----------
----------DRASYLRRQARANARFIACYNAVDF-------------------------
-------------------DLRLLSYGSPEDVATLGGRLNNKDAALMRSSSLYRIYHIAA
DEIRRR---------------------------------------------------SHQ
GGLPVLTSNSIAAMRAALDGGVVRESQRLNRLMVMLTIAISGGPFLGLLGTVVGVMITFA
AIAASGDVNVNAIAPGIAAALVATVAGLGVAIPALFGYNYLISQIKNLTADVQVFVDDVV
TRIAELYTSDLPSPLRRDQAAE--------------------------------------
-------------------------
>gnl|BL_ORD_ID|248 @Mycobacterium_smegmatis_MC2_155@ gi|118469180|ref|YP_884672.1| unnamed protein product [Mycobacterium smegmatis str. MC2 155]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------QIREHVGANKPAI
ILYPSGTVVTFDELEARANRLAHHFRNQGLQEGDVVAILMENNSHIHTVMWAARRSGLYY
VPISTHLTAAEAAYIVDNSGAKAIVGSAKMRDVLAGLGDELPNGLPDTLLIADGDLDGWL
RYPEAVADLPDTPIDDELDGDLLQYSSGTTGRPKGIKRE---------------------
--LPH---VHPSENPGMMA--------ALISFWMTPDSVYLSPAPLYHTAPSVWSMQVQA
AGHTTVVMEKFDAEGCLEAIQKHRVTHG--------------------------------
QFVPAMFTRMLKLPESVR---------NS-YDVSSLKRVMHAAAPCPVDIKKQMIDWWGP
IVDEY----YASSEAIGATLITAEEWLKHP------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GSVGKPLTGIVHVLDEDGNE----------------
-----------------------------------------LPPGQAGEIFFEGGQD---
-FEYLNDAEKTASSRDARGWKTVGDIGYLD------------------------------
----------EEGYLYLTDRRHHMIISGGVNIYPQEA-----------------------
-------------------ENMLVTHPKVMDAAVFGVPDDEMGQSVKGVVQTVDPADATP
EFGE--------------------------------------------------------
---ELLAWLRDRLAHYKCPRSISFELQLPRTDTGKLYKQELIAKYS--------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|199 @Ehrlichia_canis_Jake@ gi|73666833|ref|YP_302849.1| trigger factor [Ehrlichia canis str. Jake]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--LDCYVVKEVSNDKLKWEYEFVIDKKYFLDQLDSKLSEIAKNVKVPGFRVGKASIDLVK
KEYLNDVMTDVVRKTIESTSSDFVKSNK--------------------------------
------------------------------------------------------------
-------------FGEIISSNIDIVSYPNYYSDNDSKEENLVYKLSFEVMPEAPLMDIDS
IVLNG---IEVDIQESDVS--------EFIENLKKQRPNFIVVNGAEYAV--------QE
GDKVVIDYQNKVKGKILRGGSAKDFALVIGKGVALKEFENQLLGMRVGETKSFPLTFPDD
YSVAYLAGKTTDMSVVVK---------SI-YVVKDVQDNE--------------------
---------SVARSYGFKDVAEMENFVRKQIGQQFDQMVLTIMKKELFDYMDNT------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------YSIDVPECVVKQEITKINKEI---------------
-----------------------------------------LDSGE--------------
-DIQIDVEKEAVRRV---------------------------------------------
----------KLGMLLIRMSRHNNITIKNEDVLSFIK-----------------------
-------------------NNYTDYGVDINNVLKMLQSNKNFANYISGKVLEDKVINYII
KLVKKD------------------------------------------------------
---RKVMTTKEINLMFENI-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|2206 @Syntrophomonas_wolfei_Goettingen@ gi|28212040|ref|NP_782984.1| diaminopimelate decarboxylase [Clostridium tetani E88]
M-----------------------------------------------------------
----------------------RLFGTMEVKDNNLYIGGVSCKELKNKYSTPLYI-----
---------------------------------------------------IDEDFLRGR
CKEYYNNFGVEKHGNKVAYAGKSFLTIAMCQIIKEEGLFLDVVSSGELYTALKANFPMNK
IYFHGNN--------------------KTLDEIEMGIELGVGKFVVDNFYEMNNINNMAR
KKGIKQSILLRITPGIEAHTHDYIKTGQVDSKFG--------------------------
------------------------------------------------------------
----------------------FSMVGEEVYKAVETALS---------------------
--LPN---INLSGIHCHIG--------SQIF-----------------------------
------------------------------------------------------------
ETTPYEEAV----DIMFE---------IL-KEIKNRYD---------YEISEVDLGGGFG
IY-------YTKEDKPKETKEYCEAILKKALNKSKELGIKLPMLGIEPGRSIIGNAATLI
YTIGAIKEIPGIRKYVSIDGGMNNNIRPALYDAKYE------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CEVANNMNSDDRELVTIAGKC---------------
-----------------------------------------CETGD--------------
--IVIEDVEISKS-----------------------------------------------
----------KSGDILAIPSVGAYGYSMSSNYNKIPK-----------------------
-------------------PAIVLVKDGESRVMCKRESFDDMLKNELSL-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|11 @Treponema_pallidum_DAL_1@ gi|378974645|ref|YP_005223253.1| lon1 gene product [Treponema pallidum subsp. pallidum DAL-1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------LGN
LMLGPYC--------------------RSSLWRELSWQEVTGIVAPDTIAYLKARAQDHP
FLLAHERACAAIRLGMRMYGDGY-------------------------------------
------------------------------------------------------------
--------------------NICVIGASGTGKRTTLQYL---------------------
--LKD---FVPRPEQMWDI--------AYAYNFVHPHEPQVLQFPAGEGMPFATALRRSV
NAILNTAQDIVKSDAFLRERRTLLADIETRECAELSRIEAELYTRGFRVRWHRKRGTYSF
DLVPLLKGK----DSSFE---------AL-HDLASRAK----LSRCVVHELHARYRLSCD
EV---SSLLHTLRTARRAARRRLAQYYRARLRLIILEQMACIKKRVACYAPVFSPPPVSC
AAEQTEREKTSSSRLIEVPHEFEEMRARIISYIERIQTDVQVRVQCLMSMRISALVKKRF
FDRYTLNFVCVHTEHAGYVFTEHQPNLANLCGSIESKGNEGDTLENGHLRIRAGALHRAH
AGVLIVQLEDLLAEEEAWTHLKRALRTKQVLLPAGSSQSQGMLRPEGVPLTCKLVLVGEP
CSFERLSQEDSSFRELFKVCAEFDTSMPNSDKNQVALIAYLDRVV---------------
-----------------------------------------ARYGTFSLDSSAYARL---
-LAYAEELAESHTRLSTSFVQIADLVLESHAVAVDMHPDVSVITAHVVQEALNRRQYVCS
RARERFQRMIACGELLVEVQGYRIGRINALAIEEHCG-----------------------
-------------------HSFGIVISLTAQASAGKEGVMNIEREAGLSGEIYDKAHLII
TSLLRE------------------------------------------------------
---KCLSAFADAAFDPAVDDLGKGQDSFPLCLSAALCFEQSYHGIDGDSASAAEFLVLLS
AIGRFPLRQDRAITGSVNQLGQVQAIGGVSEK---------------------ISGFYDV
CALNGLTGMQGVLIPKSSCAQLFLPERVQDAVRAGTFHVWAVCTIDDALELMVPDDLKEQ
GSAQLYQCVRARLRDFYVTVKGHCE
>gnl|BL_ORD_ID|249 @Legionella_pneumophila_2300_99_Alcoy@ gi|296105747|ref|YP_003617447.1| O-methyltransferase [Legionella pneumophila 2300/99 Alcoy]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------NKFPQSFSEANERI
GNAIHHVCLNALDAKFIKSNIQESYQSWANVLYDRVFLNWGLCDKKIYRELSSLNFDFST
VGFFPHVYGQSLLFYLIRPLIKIHFFNKRLLDVGCGNGVGL-------------------
-----------------------KISSELLKTRYALGID---------------------
--LVNKL-VTNSNNNFYIE--------DKINYMQADAENMAIANESFDIVTNLESS----
------------------------------------------------------------
HLYPQIEHFFSEVERVLAPNGFFCYADVN-FDVKRQAE----------------------
---RFETFVKTRKNLRIIEKHNITKMIQ--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ASIYQRLIVNEKRFYQLAQYL---------------
-----------------------------------------LGPDK--------------
-INYTSELANVAS-----------------------------------------------
----------SMGLMFLPWWRIRFKNPALQALGKFARRYKHWNKKYYFYYLIQKIDS---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|3459 @Flavobacterium_johnsoniae_UW101@ gi|146301226|ref|YP_001195817.1| unnamed protein product [Flavobacterium johnsoniae UW101]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------FFIEVILPLSLAKTFTYRVSEAEFHFIKKGMRVAVPF
GKSKIYTALVLDIHENAPTLYEAKEIHQILDERPIATEIQIKHWLWVANYYMCGIGDVYR
GAFPTGLLLES-------------------------------------------------
------------------------------------------------------------
--ETIVSHKPDVVVNDSELSDDEFLIYEALQHQSSLKVQ---------------------
-------EIASILNRKNIL--------PILQKLIARDIIFLEEEIKESYKPKLVRYVKLH
SKYETDQGLGSLLDILKNDKQKEI------------------------------------
VLAYFQISASEKKPVTVK---------KL-VEVSGSSS----------------------
---------SVVKTLVKNEILEEYLLQQDRVLFTGEKSEKELLLSEAQQNAFTAIKQSLT
EKEVCLLHGVTSSGKTEIYIKLIEEYLHTGRQVLYLLPEIALTTQLVSRLRLHFGDKVAV
FHSKYSNNERVEVWKQTLENSEKAQIVIGARSALFLPFNDLGLLIVDEEHEQTFKQTDPA
------------------------------------------------------------
------------------------PRYHARDAAIVLANFHNAKVL---------------
-----------------------------------------LGSATPSIETYFNTQNDKY
GLVTLTERYKNVRLPEVVLVDLKDKHFRKRMTGH--------------------------
----------FSDLLIEEITEALSLGEQVILFQNRRGYSPIIECLTCGHVPHCQQCDVSL
TYHKFKNQLRCHYCGYAIAKPTNCHSCSSIDLTTKGFGTEQIEQELASLFPKAKTARMDQ
DTTRGKFGFEKIIDTFKNREIDILVGTQMLAKGLDFDNVSLVGIMNADNMLHHPDFRAFE
RSFQMMTQVAGRAGRSEKQGKVVIQTYNPNHNTIQQVTNHNYNGMYKEQLYDRQIYKYPP
YFRIIKLTIKHKDFDKLKEGSMWLYQVLSQNLNIPVLGPEEPAISRIRNEYIRTILIKIP
QNMHLGNTKKTIQKMLNSFEAVAQYRAIKVVVNVDFY-----------------------
-------------------------
>gnl|BL_ORD_ID|37 @Sulfurimonas_denitrificans_DSM_1251@ gi|78776239|ref|YP_392554.1| succinate dehydrogenase/fumarate reductase iron-sulfur protein [Sulfurimonas denitrificans DSM 1251]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------KINIKRESLHVE---------------------
--------YDVSLQGVTLL--------EVLNEIKYKLDATLTFNSGCRSSVCGSCALRVN
GREVLACSYKAEDGDVVEPL----------------------------------------
LNSPIERDLVVNMDKAYS---------FN-AKAKAWQS----------------------
---------SFAQHVKLTDEDEMRNALQSDCILCGSCYSACP------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------VYEVNKEF---------------
-----------------------------------------LGPFSLTRVWR--------
-YVSDKREENPKGKIDNIQINGVWDCTLCNACTLVCPQGIS-------------------
----------SKADIEKLRARSVMFGYSDSSFANFGGGFSFDGTPSF-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|1839 @Geobacter_metallireducens_GS_15@ gi|78223054|ref|YP_384801.1| unnamed protein product [Geobacter metallireducens GS-15]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---LVMKNIWKEREKALE---------NQ-YIYKQEQD----------------------
---------KIERMQKEERERLVREMCRNRCPKCGDEIKAMTFRGVPLD-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------RCPGCGGVW---------------
-----------------------------------------LGPNDLRILASKDHRS---
-WFEKWFKEENETSEKVA------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
