>gnl|BL_ORD_ID|419 @Ehrlichia_canis_Jake@ gi|73667053|ref|YP_303069.1| hypothetical protein Ecaj_0429 [Ehrlichia canis str. Jake]
M-----------------------------------------------------------
------------------------------------------------------------
----------LVPQEVIASNSLLCEYVKYTTINIKSATCIGSTDIINNKLKIHISKDSNL
QPIVQPHAKSLFLLEVTIPSSIV-KNDPYLRNIYI-----ISQSESLDANLYCLVDASH-
-IQSFTNEIYDTVQNKVPKFVDNIFKYTEV----------------------------IF
AKLEIDSHLKLNE-----YEILCSILPDAE-----FIIHEIEEKNSCCSCCPPFTSKQNI
TRVQSQESLLQENDAEQVTLPKPE------------------------------------
-----------------DNITNTSISSTDSSTEHNSISSLLSFVNVTIESINSFQNN---
---------------SK-----------------
>Mulan_NP_078820
M------------------------------ESGGRPSLCQFILLGTTSVVTAALYSVYR
Q-----------KARVSQELKGAKKVHLGEDLKS--------------------------
--ILSEAPGKCVPYAVIEG---AVRSVKETLNSQFVENCKGVIQRLT--LQEHKMVWNRT
THLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRV-----LKPLDSVDLGLETVYEKFHP
SIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSVRLQPPKQGMQYYL
SSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRK------------QYLQRQER
LRLKQMQEEFQEHEAQLLSRAKPE------------------------------------
-----------------DRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEP---
---------------KKCPICRQAITRVIPLYNS
>gnl|BL_ORD_ID|199 @Ehrlichia_canis_Jake@ gi|73666833|ref|YP_302849.1| trigger factor [Ehrlichia canis str. Jake]
MLDCYVVKEVSNDKLKWEYEFVIDKKYFLDQLDSKLSEIAKNVKVPGFRVGKASIDLVKK
EYLNDVMTDVVRKTIESTSSDFVKSNKFGEIISSNIDIVSYPNYYSDNDSKEENLVYKLS
FEVMPEAPLMDIDSIVLNG---IEVDIQESDVSEFIENLKK--QRPN------FIVVNGA
EYAVQEGDKVVIDYQNKVKGKILRGGSAKDFALVIGKGVALKEFENQLLGMRVGETKSFP
-LTFPDDYSVAYLAGK-------TTDMSVVVKSIYVVKD-VQDNESV-------------
----------------------ARSYGFKDVAEMENFVRK------------QIGQQFDQ
MVLTIMKKELFDYMDNTYSIDVPECVVKQEITKINKEILDSGEDIQIDVEKEAVRRVKLG
MLLIRMSRHNNITIKNEDVLSFIKNNYTDYGVDINNVLKML-------QSNKNFANYISG
KVLEDKVINYIIKLVKKDRKVMTTKEINLMFENI
>gnl|BL_ORD_ID|3459 @Flavobacterium_johnsoniae_UW101@ gi|146301226|ref|YP_001195817.1| unnamed protein product [Flavobacterium johnsoniae UW101]
MFFIEVILPLSLAKTFTYRVSEAEFHFIKKGMRVAVPFGKSKIYTALVLDIHENAPTLYE
AKEIHQILDERPIATEIQIKHWLWVANYYMCGIGDVYRGAFPTGLLLESETIVSHKPDVV
VNDSELSDDEFLIYEALQHQSSLKVQ-------------EIASILNRKNILP--------
-----ILQKLIARDIIFLEEEIKESYKPKLVRYVKLHSKYETDQGLGSLLDILKNDKQKE
IVLAY-------------------------------------------------------
---------FQISASEKKPVTVKKLVEV-SGSSSSVVKTLVKNEILEEYLLQQDRVLFTG
EKSEKELLLSEAQQNAFTAIKQSLTEKEVCLLHGVTSSGKTEIYIKLIEEYLHTGRQVLY
LLPEIALTTQLV-SRLRLHFGDKVAVFHSKYSNNERVEVWKQ-----------TLENSEK
AQIVIGARSALFLPFNDLGLLIVDEEHEQT------------------------------
-------------FKQTDPAPRYHARDAAIVLANFH-------------NAKVLLGSATP
SIET-YFNTQNDKYGLVTLT------------------------------ERYKNVRLPE
VVLVDLKD-----------KHFRKRMTGHFSD--LLIEEITEALSLGEQV-ILFQNRRGY
SPIIEC--------------LTCGHVPHCQQCDVSLTYHKFKNQLRCHYCGYAIAKPTNC
HSCSSIDLTTKGFGTEQIEQELASLFPKAKTARMDQDTTRGKFGFEKIIDTFKNREIDIL
VGTQMLAKGLDFDNVSLVGIMNADNMLHHPDFRAFERSFQMMTQVAGRAGRSEKQGKVVI
QTYNPNHNTIQQVTNHNYNGMYKEQLYDRQIYKYPPYFRIIKLTIKHKDFDKLKEGSMWL
YQVLSQNLNIPVLGPEEPAISRIRNEYIRTILIKIPQNMHLGNTKKTIQKMLNSFEAVAQ
YRAIKVVVNVDFY
>gnl|BL_ORD_ID|1267 @Frankia_alni_ACN14a@ gi|111220773|ref|YP_711567.1| unnamed protein product [Frankia alni ACN14a]
MLYLAG---QILAYVLVAM--VIGAALAWVFLIAPLRRQVRQTRDAQPDPTVDGAEPAPA
ADAVEADAVEADG--------TDAGRT-----------EAWGIEARET--DARETDPRSA
-----------DRAGTALALLPSPGEPYPRELGGEIAVGGDSGRVPESAGSSERAGAPAT
VGDRLGQDADSRAFVPD---------------------------TVGAELATTGPIPLPI
NAVRVGEPVAELVALLRRQRDDAALEKADLTARL-----------------AVAEQRAAE
SEQRIGAAERH--------AMTASARVEEIESTLRARVEAATSAAGGGTRAVDAPSPTGP
DTTAADTGLTVAELAREAELLRQQLVEAEGRAAKFSSRLAMARTEAEDAQRLVATMTTRL
DRHQAEWAAERLSLLGRIERTEASLERGTEAASAANPVAEPASAAVEYAELVGTAKALAS
ARAVRSTRAAVPLFAAEPAEVAEPAEVAEPVDADEPVDVAEPGGTPEPVDRAEPVDRAEP
VDGAESVDAVVSPGVAGPGREDEPAVGEESARLDESVRPHSDGAALAAAASVESGTAAPA
GSEPVRAGALGVAGMRARTSGVTKERPAAVAGVPAPTGSGSVTAPGVRSGATGEQAAGGR
VVQEAAPRWNGLLDPGGAVGDNLKEIVGIGPVIESRLRTLGITTFSQLAEMGDTDVDRLA
HKLDGFGDRIISDDWVGQAQDLQVRHYGGVF
>gnl|BL_ORD_ID|1839 @Geobacter_metallireducens_GS_15@ gi|78223054|ref|YP_384801.1| unnamed protein product [Geobacter metallireducens GS-15]
ML----------------------------------------------------------
-----------------------------------------------------VMKNIWK
E-----------------------------------------------------------
---------REKA-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------LENQYIYKQE
Q-----------------------------DKIERMQKEERERLV----------REMCR
N--RCPKCGDEIKAMTF-------------RGVPLDR-CPGCGGVWLGPNDLRILASKDH
RSWFEKWFKEENETSE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------KV
A
>gnl|BL_ORD_ID|249 @Legionella_pneumophila_2300_99_Alcoy@ gi|296105747|ref|YP_003617447.1| O-methyltransferase [Legionella pneumophila 2300/99 Alcoy]
MN----------------------------------------------------------
------------------------------------------------------------
---------------------------KFP------QSFSE-------------------
-------ANERIGNAIHHVCLNALDAKFIKSNIQESYQSWANVLY------------DRV
FLNWGLCDK------------------KIYRELSSLNFDFSTVGFFPHVYGQSLLFYLIR
PLIK---------------------------------------------------IHFFN
KRLLDVGCGNGVGLKIS-----SELLKTRY-------------------------ALGID
LVNK-------LVTNSNNNFYIED------------------------------------
-KINYMQADAENMAIANESFDIVTNLESSHLYPQIEHFFSEVERVLA-PNGFFCYADVNF
DVKRQAERFETFVKTRKNLRIIEKHNIT-KMIQASIYQRLIVNEKRFYQLAQY-------
-------LLGPDKINYTSELANV----ASSMGL-MFLPWWRIRFKNPALQALGKFARR-Y
KHWNKKYYFYYLIQKID-------------------------------------------
-----------------------------------------------------------S
>gnl|BL_ORD_ID|2990 @Methylibium_petroleiphilum_PM1@ gi|124268184|ref|YP_001022188.1| uroporphyrin-III methylase [Methylibium petroleiphilum PM1]
M----------------------------QLGLMLLLLLVSVTALSMAWYGQRRVRTLEQ
ELVRRQQDSAGQAAEAQLLAKQAQELSRDAVAKVTLTESRLAEITAQRGQLEELIQSLSR
ARDENLVVDIDA--GIRVALQQTAITGSA-----APLVAALKAADERLARVSQPRLEPVR
RAIARDLDRVKAVSVADIASLAI--KLDEAARLVDEAPLQVLDPQRLAEAKAPRAVARVA
PSPASAAASAAPVGGLRAELGDWWQGLWAETRTLLRVTRIDQPQAMLLAPEQGFFLR-EN
LKLRLLNARLALMSRQFDTAQSDLQAAVAAVDNYFDRGARKT----------QLLTELLR
SVVPQARQAGVPRPDDTLAALTTA----AAGR----------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|248 @Mycobacterium_smegmatis_MC2_155@ gi|118469180|ref|YP_884672.1| unnamed protein product [Mycobacterium smegmatis str. MC2 155]
MQI---------------------------------------------------------
-------------------------------REHVGANKPAIILYPSGTVVTFD----EL
EARANRLAHHFRNQGLQEGDVVAILMENN-------SHIHTVMWAARRSGL-------YY
VPISTHLTAAE---------------AAYIVDNSGAKAIVGSAKMRDV---------LAG
LGDEL------PNGLPDTLLIADGDLDGWLRYPE----------AVADLPDTPIDDELDG
DLLQYSSGTTGRPKGIKRELPHVHPSENPGMMAALISFWMTPDSVYLSPAPLYHTAPSVW
SMQVQAAGHTTVVMEKFDAEGCLEAIQKHRVTHGQFVPAMFTRMLKLPESVRNSYDVSSL
KRVMHAAAPCPVDIKKQMIDWWGPIVDEYYASSEAIGATLITAEEWLKHPGSVGKPLTGI
VH-VLDEDGNELPPGQAGEIFFEGGQDFEYLNDAEKTASSRDARGWKTVGDIG-YLDEEG
YLYLTDRRHHMIISGGVNIYP-----QEAENMLVTHPKVMDAAVFG-VPDDEMGQSVKGV
VQTVDPADATPEFGEELLAWLRDRLAHYKCPRSISFELQLP--RTDTGKLYKQELIAKYS
>gnl|BL_ORD_ID|3363 @Pseudomonas_stutzeri_A1501@ gi|146283762|ref|YP_001173915.1| hypothetical protein PST_3445 [Pseudomonas stutzeri A1501]
M--------------------------------------------LNATTWFERYQQRYR
WATRAYDRFVQDLVPELVDTLQRNEQVTVAVYGATQVGKTTLILDLLGLSTLTTNEVGSV
LRGGQQLGKSATAMPIRYGRSLDDGWYIAGEGPLSADTARETLRAFRRKVESGGICDAEV
LDIRIPRG----LFQQCDDSSAGLELNIIDIPGIN------------SHSSAEQALVTKL
ADRYVVAADIVLLV-------------------------GKADSLGFLNERDLIIPALAD
WAAQPTRFRIVLTYGFSPDSLVSQFKDQELTVEQVRDVHIGQM-----------------
-----------------------------------RTHDYVFPPEFRSNLFVL-------
------------------ELGDSIVDLGRTNPEYLQRIL---------QVTNDFRGELLE
----NIVKAAG---------PYARL-------------------QGAFQLDRVINARVER
LRKAL--------------------------ENQEVEYGRQRRQITDELAAFHPELLDA-
------SDEEIYVAIDKLGVDRL------DLKNKL--DELSASIKRLEEFNCAALFLTEF
SAGAVEKVSWLQEQLENCE-----------------------------------------
------------------------------QLQRKACIQAASLLFDKG------------
------------------VLPSWLKDEVPVIEYQRKALLDIDSHLNSYVLDGYWW-----
---SSSNFNEDR----NSLQKALRLNAREHGERIQSA-----------------------
----------------TKRALHERKRALLADYKNLKSHCIILQSYLESLQALEREYRCIC
AEYADD-----LQEMDRALGMASSFESQLNAAFMEELRSTKEDVESHPVPA---------
------------------------------------------------------------
--QRFYGLLHTRLLLSEIDRMYEGKSF-----------------------
>gnl|BL_ORD_ID|1342 @Rhodopseudomonas_palustris_CGA009@ RPA1350 putative transport protein ExbB2
MTIEKNDVRGAGWGWSRGAKSVAKAVTKAGLLAAVGGMLLTATPANAWWNDEWQLRKKIT
IDTSAAGANITDPIGTTPVLVRLHTGNFRFNATKEDGGDLRFVAGDDKTPLKYHVEKFDA
LLGEALVWVAVPDLQPGAKTDLWLYYGNKKAVAIADSKGTYDPDTQLVYHFAERGTVPLD
STVWANNAQSVGQPADGAIIGTGLRLDGRTPLTLPSSSALALAGSGGWTWSAWVKPAAAQ
PNSALYSRR----DGGNAVVIGFDNGAPFVEVANAGAVQRSATAAPVALNSWHHVAVVAG
NGRVTLYLDGNAYAVLDAALPALNTLAFVGGDALASNPAPTASPAASQAPLPDGSSPQGA
PTGDAPAADAPVAAAPAAMAGFAGDIDELEISKASRPAGFVRVAALGQGLDKGKLLTFTI
DEETASWLSGYFAVILKSVTLDGWVVIAILMVMAVISWMVMVDRASYLRRQARANARFIA
CYNAVDFDLRLLSYGSPEDVATLGGRLNNKDAALMRSSSLYRIYHIAADEIRRRSHQGGL
PVLTSNSIAAMRAALDGGVVRESQRLNRLMVMLTIAISGGPFLGLLGTVVGVMITFAAIA
ASGDVNVNAIAPGIAAALVATVAGLGVAIPALFGYNYLISQIKNLTADVQVFVDDVVTRI
AELYTSDLPSPLRRDQAAE
>gnl|BL_ORD_ID|2307 @Rubrobacter_xylanophilus_DSM_9941@ gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
----------VGTVVF--------------------------------------------
----------------------------------------------------------LL
VGVVLCV----------------------------------------AGGVLLYFR----
------------------RRMLGKA-----------------------------------
------------------------------------------------------------
------------------------------------------ELMRRTRTS---GAAGVS
AL---SPGTLVE---VKGTLRCERPLQSEMAKERCAYYSSKVVREYLERDRGDGAPGSGR
RSEVLARSERFAPFV---------------------VEDDTGGVPVSA------EGAEV-
-----------DAKKVVDRFERGAGAAGLSVTIGGATIDLGGGERTLGYRHTEEILPVDA
------------------------------------------------------------
----------------------------------------------------PVYVLGAV
RRDG---------------------------------------------------GIGPP
EEGAGR---------------------------------FVVSWRSEEALGE--------
-------------------------------------------------SLGRGARLLGL
IALGLFLAGAAFLAVGAAAALGYLQFR---------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|2252 Streptomyces_avermitilis_MA_4680 gi|29828788|ref|NP_823422.1| ABC transporter ATP-binding protein [Streptomyces avermitilis MA-4680]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------VHVSATPVL-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------ALRGVSKR-----------------------------------
----------FGAVQALTDVELEIHAGEVVALV---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GDNGAGKSTLVKTIA---------------------------------------------
-------------------------------------GVHPIDEGVIEWDGKAVQIN-KP
HDAQNLGIA--------------TVYQDL--ALCDNIDVVGNLYLGRELRKRGI------
--------------LDEVEMERRSRELLTTLSI---------------------------
---------RIPSVRIPIASLSGGQ-------------RQTV------------AIARSM
LGEPKLVILDEPTAAL-------GVEQTAQVLDLVERLRERGHA----------------
------------------------------------------------------------
-VILISHNMADVKAVADKVAVLRLGRNNGVF---EVKSTSQEEIISAITGATDNAVTRRA
ARNGEAQK----------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|37 @Sulfurimonas_denitrificans_DSM_1251@ gi|78776239|ref|YP_392554.1| succinate dehydrogenase/fumarate reductase iron-sulfur protein [Sulfurimonas denitrificans DSM 1251]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------KINIKRESLHVEYDVSLQGVTL--LEVLN-------------------
------------------------------------------------------------
------------------------------------------------------------
----EIKYKLDAT-----------------------------------------------
----------------------------------------------------------LT
FNSGCRSSVCG-------------------------------------------------
------------------------------------------------------------
--------SCALRVNG-REVLACSYKAEDGDVVEPLLNSPIERDLVVNMDKAYSF-----
------------------NAKAKAWQSSFAQH---VKLTDEDEMRNALQSDCILCGSCYS
ACPVYEVNKEFLGPFSLTRVWRYVSDK-------------------------REENPKGK
IDNIQINGVWDCTLCNACTLVCPQGISSKADIEKLRARSVMFGYSDSSFANFGGGFSFDG
TPSF
>gnl|BL_ORD_ID|2206 @Syntrophomonas_wolfei_Goettingen@ gi|28212040|ref|NP_782984.1| diaminopimelate decarboxylase [Clostridium tetani E88]
MRLFGTMEVKDNNLYIGGVSCKELKNKYSTPLYIIDEDFLRGRCKEYYNNFGVEKHGNKV
AYAGKSFLTIAMCQIIKEEGLFLDVVSSGELYTALKANFPMN-------KIYFHGNNKTL
DEIEMG--IELGVGKFVVDNFYEMNNINNMARKKGIKQSIL---LRITPGIEAHTHDYIK
TGQVDSKFGFSMVGEEVYKAVETALSLPNINLSGIHCHIGSQIFETTPYEEAVDIMFEIL
KEIKNRYDYEISEVDLGGGFGIYYTKEDKPKETKEYCEAILKKALNKSKELGIKLPMLGI
EPGRSIIGNA----ATLIYTIGAIKEIP---GIRKYVS---IDGGM---NNNIRPALYDA
--------------------------------------KYECEVANNMNSD-DRELVTIA
GKCCETGDIVIEDVEISKSK-----------------------------------SGDIL
AIPSVGAYGYSM-------------SSNYNK-----------------------------
--IPK-------------------------------------------------------
-PAIV-LVKDGESRVMCKRESFDDMLKNELSL
>Mulan_NP_078820
M----------------------------------------------------ESGGRP-
----------SLCQFIL---LGTTSVVTAALYSVYRQKARVSQELKGAKKVHLGEDLKSI
LSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLT---L------QEHKMVWNR
TTH-----------------------LWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRVL
K--------PLDSVDLG-----LETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEML
KVGATLTG-V----GELVLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVR--LWKV
LALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQEHEAQLLSRAKPE-DRESLKSA
CVVC-----------LSSFK-----------------------------------SCVFL
ECGHV----CSC-------------TECYRA-----------------------------
--LPE-------------------------------------------------------
-PKKCPICRQAITRVIPLYNS-----------
>gnl|BL_ORD_ID|11 @Treponema_pallidum_DAL_1@ gi|378974645|ref|YP_005223253.1| lon1 gene product [Treponema pallidum subsp. pallidum DAL-1]
MLGN--------LMLGPYCRSSLWRELSWQEVTGIVAPDTIAYLKARAQDHPFLLAHERA
CAAIRLGMRMYGDGYNICVIGASGTGKRTTLQYLLKDFVPRPEQMWDIAYAYNFVHPHEP
QVLQFPAGEGMPFAT--ALRRSVNAILNTAQDIVKSDAFLRERRTLLADIETRECAELSR
IEAELYTRGFRVRWHRKRGTYSFDLVPLLKGKDSSFEALHDLASRAKLSRCVVHELHARY
RLSCDEVSSLLHTLR----------------------------TARRAARRRLAQYYRAR
LRLIILEQMACIKKRV-ACYAPVFSPPPVSCAA-----EQTEREKTSSSRLIEVPHEFEE
MRARIISYI--ERIQTDVQVRVQCLMSMRISALVKKRFFDRYTLNFVCVHTEHAGYVFTE
HQPNLANLCGSIESKGNEGDTLENGHLRIRAGALHRAHAGVLIVQLEDLLAEEEAWTHLK
RALRTKQVLLPAGSSQSQGMLRPEGVPLTCKLVLVGEPCSFERLSQEDSSFRELFKVCAE
FDTSMPNSDKNQVALIAYLDRVVARYGTFSLDSSAYARLLAYAEELAESHTRLSTSFVQI
ADLVLESHAVAVDMHPDVSVITAHVVQEALNRRQYVCSRARERFQRMIACGELLVEVQGY
RIGRINALAIEEHCGHSFGIVISLTAQASAGKEGVMNIEREAGLSGEIYDKAHLIITSLL
REKCLSAFADAAFDPAVDDLGKGQDSFPLCLSAALCFEQSYHGIDGDSASAAEFLVLLSA
IGRFPLRQDRAITGSVNQLGQVQAIGGVSEKISGFYDVCALNGLTGMQGVLIPKSSCAQL
FLPERVQDAVRAGTFHVWAVCTIDDALELMVPDDLKEQGSAQLYQCVRARLRDFYVTVKG
HCE
>Mulan_NP_078820
MESGGRPSLCQFILLG---------------TTSVVTAALYSVYRQKA------------
----RVSQELKG-------------AKKVHLGEDLK------------------------
SILSEAPGKCVPYAVIEGAVRSVKETLNS--------QFVENCKGVIQRLTLQEHKMVWN
RTTHLWNDCSKI-IHQRTNTVPFDLVPHEDGVDVAVRVLKPLDSVDLGLETVYEKFHPSI
QSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSVRLQPPKQGMQYYLSS
QDFDSLLQRQESSVRLWKVLALVFG--FATCATLFFILRKQYLQRQERLRLKQMQEEFQE
HEAQLLSRAKPEDRESLKSACVVCLSSFKSCVFLE--------CGHVCSCTE--------
--------C-------------------------YRA-----------------------
---------LP-------------------------EP----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-KKC-----------------------PIC------------------------------
------RQ----------------------------------------------------
-------------------------AITRVIP----------LYN---------------
--S
