>gnl|BL_ORD_ID|33476 @Branchiostoma_floridae@ jgi|Brafl1|131976|estExt_fgenesh2_pg.C_6120027
MQQ---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------QDIPVDATIMESEST--------------VWAIM
EKAGMTLGL---------------------------------------------------
------------------------------------------------------------
---------------------LTVVNVVVGQIILLVGRPYFGVYAVSSSNGRSQWFFELT
IIASLSASQLNLPL------------------------IVPKSWSATLLLTVLCFATSWA
VSVLSICQLIGN------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------SLWRPIAAFT
GAVDLLILPLALELFIIPPFFRRRRGWSCLYLDPVPLYEVLAPVVFLSKFFTWYFWSICS
I-------------------------------------------------------WKSV
NYLIPL---EPTLHGYLPEMFSVIAYSVETVWAPVRKILSVITATQFCGSILLIPPVVTN
YVRRMDTQRMAWNLCLKWFRRGKFIQRMPTRDPRSLHNTVDREVTTADGNCVVCHEDPVA
VTLVPCGH-RCLCRD------CGDILTRGRHMTTSRKCPLDRRP----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------ITSVVDAHDF
IVWEAT------------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|17557 @Nematostella_vectensis@ jgi|Nemve1|203108|fgenesh1_pg.scaffold_40000076
MSKLLLILLCFTVINLSNTTKTNIR--------------GENEE-------SGRKSSKNE
EFYVGGI-----PYLADAISSLVWFIRGLLGFFYFIMNTVLLTVTQLAARALRILQNVVR
FVEFIGYCVRVVMQANYNFVMSTFKSTKQYAQNCSEFIRHLFESTIDTFISMLRTACGLL
HSVVVG----------------IPRLFEFAGSVCKTSLQSAGSVAEK--------SYVKC
KHVATTVAS---------------------------------------------------
-------------------------------------------VPGSAAWEIINAINAVI
QLIISTIINTFLILYDLSRAVFSFIRKTVVTIIKTFWSYLLRFLVQSGE--------VLE
IVGYGMSKTATVIT----------------------NSAYHGFDRIYNTVAYVIGTIYYG
VITTIDN-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------LLWVIK----
-----------------------------------------SIFSLMIRAVTTSLSGVHS
ALSETMKNIQNALYYLSSKFPGGKLSMISLVSIGMITYSVRFLFGLNVGVVCFDILEKAI
QNFVSRINRRSIISQQVTVVAEEERPSTT----------------------------LDN
KPSVSNDEHVN-----------------------RLREELERERDKTL--CVICAEQPKQ
ILIMPCRH-MCLCSV------CADTLLTHWNRRACPLCRCRIRS----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------LIEGIVGKQNWKEAGKKIDSLTVILELPHK
AALKSLAHLE--------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|8201 @Homo_sapiens@ gi|4505447|ref|NP_000901.1| neuropeptide Y receptor type 2 [Homo sapiens]
MGP-----------------------------------IGAEADENQTVEEMKVEQYGPQ
TTPRGELVPDPEP-----------------------------------------------
------------------------------------------------------------
--------------------ELIDSTKLIEVQVVLILAYCSIILLGVIGNSLVIHVVIKF
KSMRTVTNF---------------------------------------------------
------------------------------------------------------------
---------------------FIANLAVADLLVNTLCLPFTLTYTLMGEWKMGPVLCHLV
PYAQGLAVQVSTIT------------LTVIALDRHRCIVYHLESKISKRISFLIIGLAWG
ISALLASPLAIFREYSLIEIIPDFE---IVACTEKWPGEEKSIYGTVYSLSSLLILYVLP
LGIISFSYT---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------RIWSKL----
------------------------------------------------------------
--------------------------------------------------KNHVSPGAAN
DHYHQRRQKTTKMLVCVVVVFAVSWLPLH-----------------------------AF
QLAVDIDSQVL--------------------------------------------DLKEY
KLIFTVFHIIAMCST------FANPLLYGWMNSNYRKAFLSAFR----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------CEQRLDAIHSEVSVTFKAKKNLEVRKNSGP
N-----------------------------------------------------------
------------------------------------------------DSFTEATNV---
------------------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|18835 @Takifugu_rubripes@ jgi|Takru4|555429|e_gw2.130.176.1
MIG------------------------------------------------YLMMMRECK
PVPRVVS-----P-----------------------------------------------
------------------------------------------------------------
----------------------FIEASFLTLQVTFTSSETSPGIADL--------NLCRC
GTNSSCLAF---------------------------------------------------
------------------------------------------------------------
-----------------------------RKGVEVLYPFTMEFYLMAGC--------MIY
VMWKNVGRQVSPGH----------------------HHVTQKLTFDLLRQGRVIYGLVSG
ALVILVGLVI--------------------------------------------------
-----------------------------------------------------------F
ILY---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------QLWVSW----
--------------------------QKFRHLAFLMLYVYHIVVIPLM--------SLCC
LV-----------------------------------------GLLVHRVERHVKEGGYN
--------PTRNLDVVLLIATASGQLALS-------------------------------
---------YF-----------------------SLVAALTVGAEGPL------ASLDLS
YSILTLLELLLQNTF------IIEGLHRHPNLLAEKK-----------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------KKKKHRMIKSNRET
S-----------------------------------------------------------
------------------------------------------------EDMTRGSGWEGE
PAVRVHDGKKPWAQRIIKEICAFLILSNIMVNSHVHVSF-------------FCITCFTF
PRLSDVGHSSVWSPPPVDRLRETIFRLLRLVRSG
>gnl|BL_ORD_ID|2724 @Drosophila_melanogaster@ gi|45555286|ref|NP_996448.1| CG8974, isoform E [Drosophila melanogaster]
MEE-------------------------------------------------------PK
SVPTAEL-----P-----------------------------------------------
------------------------------------------------------------
--------------------------------------------------------STST
GASSSSSTL---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------SNNVSYDK----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------IAWTRD----
------------------------------------------------------------
-------------------------------------------------ITEPLAEESST
SQLRPLGTSIPTNSTASELKKSNTSYSFT--------------GDYLSGGNKADLKGGYP
FGGTDTDTKAN-----------------------EKDKEKEHTADDSLYECNICLDTAKD
AVVSMCGHLFCW-PC------LHQWLLTRPNRKLCPVCKAAVDK----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------DKVIPLYGRNST
HQEDPRNKVPPRPAGQRTEPDPVPGFPGFGFGDGFHMSFGIGAFPFGFITSTLNFGEPRP
PAANRGTRQYEDEQTLSKLFSYLAVVWILWLFYA
>gnl|BL_ORD_ID|1251 @Saccharomyces_cerevisae@ gi|6320576|ref|NP_010656.1| Ypr1p [Saccharomyces cerevisiae S288c]
M-----------------------------------------------------------
------------P-----------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ATL
KNSSATLKL---------------------------------------------------
------------------------------------------------------------
---------------------------------------------NTGA--------SIP
VLGFGTWRSVDNNG-----------------------------------YHSVIAALKAG
YRHIDAAAIYLNEEEV--------------------------------------------
---------------------------------------------GRAIKDSGVPREEIF
ITT---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------KLWGTE----
---------------QRDPEAALNKSLKRLGLDYVDLYLMHWPVPLKTDRVTDG--NVLC
IP-----------------------------------------TLEDGTVDIDTKEWNFI
--------KTWELMQELPKTGKTKAVGVS-------------------------------
------NFSIN-----------------------NIKELLESPNNK----VVPATNQIEI
HPLLPQDELIAFCKE------KGIVVEAYSPFGSANAPLLKEQA----------------
------------------------------------------------------------
------------------------------------------------------------
-----------------IIDMAKKHGVEPAQLIISWSIQRGYVVLAKSVNPERIVSNFKI
FTLP--------------------------------------------------------
-------------------E----------------------------DDFKTISNLSKV
HGTKRVVDMKWGSFPIFQ------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|2119 @Ciona_intestinalis@ jgi|Cioin2|216812|fgenesh3_pg.C_chr_06q000046
MFD--------------------KF--------------SEVVYLTPSNCCIPTMFRTQQ
LLNRPAI-----P------LVQLLDFVPRPGMRWIVSGKPKPSSEGFSINFKVGPAEQDD
IAFHFNPRFVKRQVARNARTNMAWRSDHEDSTPYFP------------------------
----------------------FEKYKHFQVEITCLADTFKVKVNGE--------SFTKF
KHRYDLHRI---------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------THLN
IDGQVDVDSVEFGY----------------------------------------------
-------------------------------------------VGSDRNIQERFVTFHNP
KSMFTLPLERRLTSGYEITIIGRATAHMFGFNYHCGPDPTNDYAFRFFPDFGTQRVVRNF
MIN---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------KVWNPN----
------------------------------------------------------------
--------------------------------------------------------PEVI
SSYFPFRQRELFTIRCVCHNDKFSVYVNDVHFCDFTYKVPLYRISFFEIDGGIDIENITV
QWQPLEDPRYQ-----------------------QQQERCES------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|8741 @Drosophila_melanogaster@ gi|161078743|ref|NP_001097966.1| CG31427, isoform C [Drosophila melanogaster]
MKWLVLF--------------VITL--------------GLGLA-------TPNSTYNHY
RLPTALR-----P-----------------------------------------------
---------------------------------------------------------IKY
DLHVLTQLEYADD---------FSFNGSVKIQIQVLENTNNITLHSK--------ELTID
ETATTLRQI---------------------------------------------------
------------------------------------------------------------
----------------------------------------------TGE--------DLK
NNC-VSSTEVNPEH-------------DFYILRTCRQLLAGQVYELSLLFSSTLSDRLRG
YYRSSYVDPVANETRC--------------------------------------------
---------------------------------------------GLAITRRRKQIFNPC
MFTGLSNMPVKHTGKDDFLPD---------------------------------------
------------------------------------------------------------
--------------------------------------------------YVWTEF----
------------------------------------------------------------
------------------------------------------------------------
-------------QESLPISTYLVAYSVN-------------------------------
----------------------------------DAKEGIRKGDSKWAFQAVAKTEVGFH
N-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------NNIGSISD----
------------------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|6710 @Trichoplax_adhaerens@ jgi|Triad1|52395|fgeneshTA2_pg.C_scaffold_1001142
MNN--------------------------------------------------------G
NSSKDTF-----P-----------------------------------------------
-------------------------YRSVSYGIQWKGVYEHAYKNCDIVGVTRPLTFAAY
QFNVLHHIIYAKN---------------FDVYFAVAKDHTIRVLNKD--------FIEVF
QTASELRAVLFLLFNPRTNDLITGGAGGMRIYEYKQRKKKPFEQRESILMSDYKLNVKQF
YPDVGGSWVKKMQLNHKMQHVYCMSDTDVFVYDCVDGHKIFKITSAHKAMITGCVHSLVS
RLVVTCSKDTYVKVWTDNGNHLATMKGHSKAITNMIQHPNSEMLVLTSSSDGTIKIWSLH
IMAQIYSISIMPSGIPWIGIAHNNNIYVASNRQCEMWSLNHLVDFWANTYSPVISISLAS
FTKKFTHVIALSDDNSIRILSVKKKKRITTILPPPTLSALSRVIDMAYSRYHSLFYVLLN
PTEIWIYTTRTDPACRITVWNKEIIESILYDRSISKGRQEKQEVTSLAIVNSFIEINSTT
YDSENIDHSLRIDSNDSEGRPNATNLPSFLAIGTKNGRIVFIHPAHKERIYKRLTSRDPV
SQINHDVEEKKLIILSIRRDHKIIQFFSLPNLELKHEVHCAITLSKYCLMSPVLLCGHSD
GKLRKCHLHSANISKNEMVEVAPSHFNSVLCIDKCISRKVFLTSCKDGIIKVWDINACLI
SEITLDHTLLSVNFLPKQGDMLLGFKGHLFLIPATKIFQREIEDANQSDHYSDSEVAVTD
NFIDSVNTPEQVTMEDYLMPYKLSLENSWFIEKDDQTEGKRALKKISEIPKKVVSAESET
DYRVPIEVYESSMEEESDISINFEEISLG-----------------------------KS
PMSTPFSSEAS-----------------------GSEELTDMKKSDNFPQWDGTTELNKS
PDVIQLEYLLASSQN------KKNTKVENGQRPTKRKVVRRSRKDRIKSSETTKNRGKEI
KNLKDAKKTDRQNFKVTEAAKVLSAVESNREAKSQSGYRQDDKYYRNNNAQRFDVKDHAK
TDTINEKEFNPVIDDVVSDESRGIRENDSVSGSYKTTTSGVQRNYRPRNILQRSNTALDN
IRIQEKTNALNGTNSPCSYTGKSNRAIVRTRSELVYKSVSHVNRKEKLRKHQEIKTNQKE
KEFSRPEIHIQTGKVQKNHFDDSYRIDHGHSPLAVDAPLTTSSENHFDFIIEDECELLAS
STDIEIQDVHQDYNKKIVINQESQNASGIHAPVSLTQMNRSKIKNRRLDKVSSINDNKKS
HEIRDKQKPSTVDVNPFNSQVPIHYPPDWYIKYIQRLRQ-------------LKEERRDK
HVNAAKKRLELETERLKRQRNLIWNKL-------
>gnl|BL_ORD_ID|6100 @Ustilago_maydis@ jgi|Ustma1|6101|UM06101
MLQ---------------------------------------------------------
------W-----P-----------------------------------------------
-------------------------------------------------GSILVIGAGGL
GCEILSN---------------LALTGFYNIHIIDMDTIDVSNLNRQ--------FLFRE
KDVGRSKAH---------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------VAAEF
VQQRVPGVQITPYH----------------------GKIQDKDEQYYKQFNIIVCGLDSV
EARRWINATLVNMVDD---QDPDSLKPLIDGGTEGFKGQARVILPTVTSCYECSLDMLNK
QTTYPICTIANTPRLPEHCIEWASVLEWPRVFPDKKLDNDNPDHISWLLEHASTRAASFG
ITG---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------VTWNLT----
------------------------------------------------------------
--------------------------------------------------------QGVV
KNIIPAIASTNAIIAAACVLEAFKFATTA------------------------APFLNNY
MMFTGNDSVYTYTFEHEKRPDCPVCGGEARPMTFSAQDTLER------------------
--------LIEQLGE------LTDLQIKKPSLSLAGKPLYYQAPPQLEHATRPNLQMKLV
ELCEQG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------DEITVTDAR---
------------------------------------------------------------
----------------------LPFTLGIIVNFS
>gnl|BL_ORD_ID|4840 @Cladonia_grayi@ jgi|Clagr2|76605|estExt_Genewise1Plus.C_100255
MAA---------------------------------------SFGKGSSIAYKRGRSQDS
PTPLASL-----PVPKATKLEDETALDDAGTPAFLRQSQYEIRAKFNDLAWKEKFRLWQG
RNDSSSQWAQDHLSPQVAKRNRYANVQPWLKSRIHLRVAEGKSDYINASPITLPDPRTGT
DTNYIATQGPKQSGLSHFWHMIWHETGDVAVIVMLTQTHDGLMEKCC--------QYFPL
QPESGSMKI---------------------------------------------------
------------------------------------------------------------
---------------------------EPLDKAQDVAEGSVNFLETVSEPDSKIEIRKLS
LQFGGKTK----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------EVWHFL----
------------------------------------------------------------
-------------------------------------------------------FSGWP
DFAVPENEDRAALLELLKLSAEKNKSPSN-------------------------PRVVHC
SAGVGRSGTFI-----------------------ALEHLLALGESGAITEAKDDEDLIYD
VVNRLREQRMLMVQNEIQYEFLYDVVKEQFKERQRQLALLASGQ----------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------HSPKLRKLASGMKA
AILG--------------------------------------------------------
-------------------EGKEEDSYLSGNQTNEGQGGESRSEEPKRQSLSEIRLKERG
PADENGETRARFRSQSQVEERLLEGIPRVFGSFGRPFIFISGCIVAIMAGVTGAF-----
----------------------------IWVMGS
>gnl|BL_ORD_ID|11 @Saccharomyces_cerevisae@ gi|330443362|ref|NP_009341.2| Bdh1p [Saccharomyces cerevisiae S288c]
MRALAYFKKGDIHFTNDIPRPEIQTDDEVIIDVSWCGICGSDLHEYLDGPIFMPKDGECH
KLSNAAL-----P--------------------------------------LAMGHEMSG
IVSKVGPKVTKVKVGDHVVVDAASSCADLHCWPHSKFYNSKPCDACQRGSENLCTHAGFV
GLGVISGGFAEQVVVSQHHI--IPVPKEIPLDVAALVEPLSVTWHAV--------KISGF
KKGSSALVL---------------------------------------------------
------------------------------------------------------------
-------------------------------------------------GAGPIGLCTIL
VLKGMGASKIVVSE------------------------IAERRIEMAKKLGVEVFNPSKH
GHKSIEILRGLTKSHD--------------------------GFDYSYDCSGIQVTFETS
LKALTFKGTATNI-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------AVWGPK----
-----------------------------------PVPFQPMDVTLQEKVMTGSIGYVVE
DFEEVVRAIH--------------------------------------------------
----------------------------------------------------------NG
DIAMEDCKQLI-----------------------TGKQRIEDGWEKGFQELMDHKESNVK
ILLTPNNH----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------GEMK--------
------------------------------------------------------------
----------------------------------
