>CA500187_3 EST WHE4016_D04_H08ZT Wheat meiotic anther cDNA library Triticum aestivum cDNA clone WHE4016_D04_H08, mRNA sequence.
----------------------------------------------THASGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYVVGARSAAGLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRI--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ920299_3 EST CJ920299 Y. Ogihara unpublished cDNA library, whchan Triticum aestivum cDNA clone whchan10n18 5', mRNA sequence.
--------------------PPARRPFPRAGSAARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYIVGARSAAGLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLX-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ878738_3 EST CJ878738 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls29d05 5', mRNA sequence.
----------------LAGIPPAGPP----SVPARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYVVGARSAAGLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLIL------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ879335_2 EST CJ879335 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls30d05 5', mRNA sequence.
------------NPLRLAGIPPAGPP----SVPARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYVVGARSAAGLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLIX------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ883756_1 EST CJ883756 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls7k01 5', mRNA sequence.
-----------IRSSSLAGIPPAGPP----SVPARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYVVGARSAAGLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLIX------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>BJ279557_1 EST BJ279557 Y. Ogihara unpublished cDNA library, Wh_r Triticum aestivum cDNA clone whr3i24 5', mRNA sequence.
-----------------AGIPPAGPP----SVPARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYVVGARSAAGLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLP-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ680849_3 EST CJ680849 Y.Ogihara unpublished cDNA library Wh_OKCS Triticum aestivum cDNA clone whok2c07 5', mRNA sequence.
------------------SRLPVRRPFPRAGSAARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYVVGARSAAGLILT
VASEVFEESGRTLVRGTLXYLQGLKMLGVKRTERVLPTGTSLTVVGXAIKXDVGTIXIXR
PHKXPFYASPKXIXQLILNLXX--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ828305_2 EST CJ828305 Y. Ogihara unpublished cDNA library, whatlal Triticum aestivum cDNA clone whatlal25p16 5', mRNA sequence.
-------------------RLPVRRPFPRAGSAARRTISPREMLVPWGGFGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSX---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ832870_1 EST CJ832870 Y. Ogihara unpublished cDNA library, whatlal Triticum aestivum cDNA clone whatlal39j21 5', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
----------------------------LSVSKEVPWYLDDGTGRVYVVGARSAAGLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMX----------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ920379_2 EST CJ920379 Y. Ogihara unpublished cDNA library, whchan Triticum aestivum cDNA clone whchan11m19 5', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GLILT
VASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEA------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>AJ603193_3 EST AJ603193 T06 Triticum aestivum cDNA clone H08_T06_plate_5, mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ERPPGQVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFAALGVFLLAKRALDHFLQRKRQREFH
KKVRAAAAQGQARDAEGGNGTSDG---EPX------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ881906_3 EST CJ881906 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls38f02 5', mRNA sequence.
------------------------------------------------------------
------------LALVLRQGFL--------------------------------------
------------------------------------------------------------
LPDEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKVRAAAAQRQARDAEGGNGTSX-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>SP1_NM_105064
-------------------------------------------MIPWGGVTCCLSAAALY
LLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIR
GVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALT
VGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQK
PDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQ
KRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCC
TACSSHLTSCPLCRRRIDLAVKTYRH----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>BJ258967_2 EST BJ258967 Y. Ogihara unpublished cDNA library, Wh_h Triticum aestivum cDNA clone whh14f19 5', mRNA sequence.
PPRRNPALKKSVAPASPESRLPVRRPFPRAGSAARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQX------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ927492_1 EST CJ927492 Y. Ogihara unpublished cDNA library, whchan Triticum aestivum cDNA clone whchan33e05 5', mRNA sequence.
------ALKKSVAPASPESRPPVPPSVP-----ARRTISPREMLVPWGGVGCCLSAAALY
LLGRSSGRDAEVLRSVARTGSLKDLAAILDTASKVLPLVVAVSGRVSSDTPLICQQSGMR
GVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDGTGRVYVVGARSAAX----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>CJ574082_5 EST CJ574082 Y.Ogihara unpublished cDNA library Wh_OKCS Triticum aestivum cDNA clone rwhok2c07 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------IKDDVGTIRIQR
PHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQDPAPDNTRTTTFETTYFKFRSPWLPVCR
YLERGT-----SWSLIGVLL-------LKLEAMEAHSLRLTLRQLLILLVLYSCVQSVLV
APCFQ------RSDQHGCYLLV---DQLILSDGNAMLFDMRX------------------
-----------
>BJ264436_4 EST BJ264436 Y. Ogihara unpublished cDNA library, Wh_h Triticum aestivum cDNA clone whh14f19 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------FGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQDPAPDNTRTTTFETTYFKFRSPWLPVCR
YLERGT-----SWSLIGVLL-------LKLEAMEAHSLRLTLRQLLILLVLYSCVQSVLV
APCFQ------RSDQHGCYLLV---DQLILSDGNAMLFDIVKDN----------------
-----------
>CJ706374_2 EST CJ706374 Y.Ogihara unpublished cDNA library Wh_V4816 Triticum aestivum cDNA clone whv16n5o10 5', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQDPAPDNTRTTTFETTYFKFRSPWLPVCR
YLERGT-----SWSLIGVLLX------LKLEAMEAHSLRLTLRQLLILLVLYSCVQSVLV
XRLVSN----XRSDQHGC------------------------------------------
-----------
>CJ600942_6 EST CJ600942 Y.Ogihara unpublished cDNA library Wh_V4816 Triticum aestivum cDNA clone rwhv16n5o10 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--KDHFMHLXKSIDQLIXNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQDPAPDNTRTTTFETTYFKFRSPWLPVCR
YLERGT-----SWSLIGVLL-------LKLEAMEAHSLRLTLRQLLILLVLYSCVQSVLV
-RLVSNSALIDNMDASSIYWLI---NFYPTETLCCLTLRIIISSDIYRTPPPDVLVCSLL
GFCLATEEENX
>CJ845879_5 EST CJ845879 Y. Ogihara unpublished cDNA library, whatlal Triticum aestivum cDNA clone whatlal39j21 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQDPAPDNTRTTTFETTYFKFRSPWLPVCR
YLERGT-----SWSLIGVLL-------LKLEAMEAHSLRLTLRQLLILLVLYSCVQSVLV
-RLVSNSALIDNMDASSIYWLI---NFYPTETLCCHX-----------------------
-----------
>CJ841172_5 EST CJ841172 Y. Ogihara unpublished cDNA library, whatlal Triticum aestivum cDNA clone whatlal25p16 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------DQLVLEICVICXEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQDPAPDNTRTTTFETTYFKFRSPWLPVCR
YLERGT-----SWSLIGVLL-------LKLEAMEAHSLRLTLRQLLILLVLYSCVQSVLV
-RLVSNSALIDNMDASSIYWLI---NFYPTETLCCLTKX---------------------
-----------
>CJ932280_4 EST CJ932280 Y. Ogihara unpublished cDNA library, whchan Triticum aestivum cDNA clone whchan10n18 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------XKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMVQDPAPDNTRTTSFKTTYFKFL-PWLPVCA
DIWNAE----LSWSLIGVLLHCRN---FTVDAVPVADLPCTL-QL--------CTECSCV
APCFQ------RSDQHRCLVVVFTGGSIDSIQRKCYVVDMRII-----------------
-----------
>CJ893616_4 EST CJ893616 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls38f02 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------XKDDVGTIRIQR
PHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKVRAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMVQDPAPDNTRTTSFKTTYFKFL-PWLPVCA
DIWNAE----LSWSLIGVLLHCRN---FTVDAVPVADLPCTL-QL--------CTECSCV
APCFQ------RSDQHRCLVVVFTGGSIDSIQRKCYVVHCKG------------------
-----------
>CJ939161_6 EST CJ939161 Y. Ogihara unpublished cDNA library, whchan Triticum aestivum cDNA clone whchan31g16 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------KRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLLV---DQLILSKGTAMLFDIVKX-----------------
-----------
>CJ887159_5 EST CJ887159 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls18o01 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--ARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLLV---DQLILSKGTAMX-----------------------
-----------
>CJ890519_5 EST CJ890519 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls29d05 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------SYTNLLSMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLLV---DQLILSKGTAMX-----------------------
-----------
>CJ891129_5 EST CJ891129 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls30d05 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLLV---DQLILSKGTAMX-----------------------
-----------
>CJ895795_4 EST CJ895795 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls7k01 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------KWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLLV---DQLILSKGNCYV-----------------------
-----------
>BJ284542_5 EST BJ284542 Y. Ogihara unpublished cDNA library, Wh_r Triticum aestivum cDNA clone whr3i24 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------AEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLLV---DQLILSKGTAMLFDIVKDX----------------
-----------
>CJ875179_2 EST CJ875179 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls18o01 5', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------LILNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSC-
------------------------------------------------------------
-----------
>CJ875332_2 EST CJ875332 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls18o02 5', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------LILNLGKWAKLYQLASMGFAAFGVFLLAKRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSC-
------------------------------------------------------------
-----------
>CJ875466_1 EST CJ875466 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls19o01 5', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------NLGKWAKLYXLASMGFAAFGVFLLAXRALDHFLQRKRQREFH
KKARAAAAQRQARDAEGGNGTSDG---XPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTX----
------------------------------------------------------------
-----------
>CJ939701_5 EST CJ939701 Y. Ogihara unpublished cDNA library, whchan Triticum aestivum cDNA clone whchan33e05 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----XXAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMXCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLTG---GSVDSIQRNCYVVHERX------------------
-----------
>CJ887427_4 EST CJ887427 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls19o01 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------AAQRQARDAEGGNGTSDG---EXKKDQLVLEICVICLEQEYNAVFVPXGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLTG---GSVDSIQRNC-------------------------
-----------
>CJ887160_6 EST CJ887160 Y. Ogihara unpublished cDNA library, whthls Triticum aestivum cDNA clone whthls18o02 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------QRKRQRXFH
KKARAAAAQRQARDAEGGNGTSDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCXLLV---DSVDSIQRNCX------------------------
-----------
>CJ810762_5 EST CJ810762 Y. Ogihara unpublished cDNA library, whsct Triticum aestivum cDNA clone whsct12i15 3', mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----HVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSFAVDAAPVADLPCTL-QL--------CTECSCV
APCFQ------RSDPHGCYLLV---DQLILSKGTAMLLTKDX------------------
-----------
>CA638665_2 EST wre1n.pk0010.c5 wre1n Triticum aestivum cDNA clone wre1n.pk0010.c5 5' end, mRNA sequence.
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------SDG---EPKKDQLVLEICVICLEQEYNAVFVPCGHMCCC
MNCSSHVTNCPLCRRRIDQAVRTFRHWHYMMQNPAPDNTRTSSFETTYFQFQSPWLPVCR
YLERGTELELVNWSFALLTKTSSNGGSYSRSTLRKLLISCTYSCVRVSCVRLFNSALIAH
GAILRGLLIHQRMHLLHVRYILRYXX----------------------------------
-----------
