>Rhodomicrobium_vannielii_ATCC_17100
MRTPLRLLHAITGFVGLVIILRFLGHTAYAELYGDAASILAVKSWIVWR-----------
------------------------------------------------------------
------------LPVLIVALAVAGATG---------------------------------
----------------------------------------FAL-----------------
----------------------------------------------AGPSPRGLAARKLA
RMRVIAVNGILVLVPA-----------------------------AIFLFWKAEAGEFDA
TFAALQTIEFIAGGVN-IVLIGMSFRDGLRLTGRL-------------------------
------------------------------------------------------------
-----------------RRCPDAPAR-----------------------RS
>SP1_NM_105064
M--------------------IPWG--------GVTCCLSAAALYLLGR--SSGRDAEVL
ETVTRVNQLKELAQLL-------ELD----------------------------------
------------SKILPFIVAVSGRVGS------------ETPIKCEHSGIRGVIVEETA
EQHFLKHNETGS-WV---------QDSALMLSMSKEV--PWFL---D--------DGTS-
RVHVMGARGATGFALTVGSEVFEESGR-SLVRGTLDYL--------QGLKMLGVKRIE--
--RVLPTGIPLTIVGEAVKDDIGEF----------RIQKPDRG--PFYVSSKSLDQLISN
LGKWSRLYKYASMGF----TVLGVFLITKHVIDSV-------LERRRRRQLQKRVLDAAA
KRAELESEGSNG---------TRESISDSTKKEDAV-PD---LCVICLEQEYNAVFVPCG
HMCCCTACSSHL-----TSCPLCRRRIDLAVKTY---------------RH
>Oryza_sativa_LOC_Os07g45350.1_PACid_16873618
L--------------------IPWG--------GVGCCLSAAALYLLGR--SSGRDAEVL
RSVARAGSTKDLAAIL-------DTA----------------------------------
------------SKVLPLVVAVSGRVGS------------DTPLICQQSGMRGVIVEETA
EQHFLKHNDAGS-WI---------QDSAVMLSVSKEV--PWYL---D--------DGTG-
RVFVVGARGAAGLVLTVASEVFEESGR-TLVRGTLDYL--------QGLKMLGVKRTE--
--RVLPTGTSLTVVGEAIKDDVGTI----------RIQRPHKG--PFYVSPKSIDQLIMN
LGKWAKLYQLASMGF----AAFGVFLLAKRALQHF-------LERKRRHELQKRVHAAAA
QRQAREAEGGNG---------TSD-VDSNNKKDQLV-LD---ICVICLEQEYNAVFVPCG
HMCCCMNCSSHL-----TNCPLCRRRIDQAVRTF---------------RH
>Physcomitrella_patens
M--------------------LSWG--------GITLCLSGAALYCLSR--NTGRDALNL
RSIERVNQLKDLAILL-------ESA----------------------------------
------------CKVVPLVVTVAGRVGS------------ETPIACEHSSLRGVILEETA
EQHFLKHNDTGS-WI---------QDSALMLSISKEV--PWYL---E--------DGTG-
RVYIVGARNAAGMELTVASEVFEESGR-SLVRGTLDYL--------QGLKMLGVKRVE--
--RVLPTGTNLTVVGEAVQDDRGLI----------RIQKPNKG--PFYVTPKSLDQLVAN
LGRWSRWYKYMSLGF----TIVGIYFITSHAIKHF-------MERRRREALHRRVMEAAA
LRQASQREGGDGDMGDVTSHPLDDSVDTSQKKDRGT-PD---LCVICLEQDYNAVFLPCG
HMCCCTSCSAQL-----TSCPLCRRHIDKFVKTY---------------RH
>SPL1_NP_564745_AT1G59560
M--------------------IHLA--------GFTCCLGGVALYLLTR--STGRD---I
KSITRVYQLKDLEQLV-------EVE----------------------------------
------------SKVVPLIIAVSGDVGS------------ETPIKCEHSYVLGVFLKRTA
EQQVLRRNWRFS-WV---------RNSTLMQPMTKEV--PWYL---D--------DGTG-
RVNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGYL--------KGFKILGVRHVE--
--RVVPIGTPLTVVGEAVRDGMGNV----------RIQKPEQG--PFYVTYIPLDQLISK
LGDLSRRFKYASMGL----TVLGVILISKPVIEYILKRIEDTLERRRRQFALKRVVDAAA
RRAKPVTGGGTS-------------------RDGDT-PD---LCVVCLDQKYNTAFVECG
HMCCCTPCSLQL-----RTCPLCRERIQQVLKIY---------------RH
>Mulan_NP_078820
MESGGR---------PSLCQFILLG----------TTSVVTAALYSVYR--QKARVSQEL
KGAKKVHLGEDLKSIL------SEAP----------------------------------
------------GKCVPYAV-IEGAVRSV----------KETLNSQFVENCKGVIQRLTL
QEHKMVWNRTTHLWN---------DCSKIIHQRTNTV--PFDLVPHE--------DGVDV
AVRVLKPLDSVDLGLETVYEKFHPSIQ-SFTDVIGHYI--------SGERPKGIQETE--
--EMLKVGATLTGVGELVLDN-NSV----------RLQPPKQGM-QYYLSSQDFDSLLQR
QESSVRLWKVLALVFG-FATCATLFFILRKQYLQR-------QERLRLKQMQEEFQEHEA
QL-----------------------LSRAKPEDRESLKS---ACVVCLSSFKSCVFLECG
HVCSCTECYRALPEP--KKCPICRQAITRVIPLY---------------NS
>Mus_musculus_gi_12832384_dbj_BAB22084.1__unnamed_protein_product__Mus_musculus_
MESGSR---------PSLGQVILLG----------TSSMVTAVLYSIYR--QKAQVAQEL
KGAKKIHLGEDLKGIL------SEAP----------------------------------
------------GKCVPYAV-IEGAVRSV----------KETLNSQFVENCKGVIQRLSL
QEHKMVWNRTTHLWN---------DYSKIIHQRTNTV--PFDLVPHE--------DGVAV
SVRVLKPLDSVDLGLETVYEKFHPSVQ-SFTDAIGHYI--------SGERPKGIQETE--
--EMLKVGATLTGIGELVLDN-NAF----------RLQPPKQGM-QYYLSSQDFDSLLHR
QESSVRLWKILVLVFG-FATCATLFFILRKQYLHR-------QERLRQQQLQEEFLEHEA
QL-----------------------LSQASPEDRESLKS---ACVVCLSNFKSCVFLECG
HVCSCRQCYLALPEP--KRCPICRREITRVIPLY---------------NS
>SPL2_NP_564653
MSSPER---------ALLNLLTDIALSFDGAILGLTLAVSAVGSALKYA--STNAALKKI
KDAPEV-SISDLRSLLPASEDKSETNDNRK------------------------------
------------SNDQRIV-VVRGVVKPK--ISGDEGYKNNNVLISPETGDKALIIQRTQ
TYVYSGWKRLFQ-ST-GHRFMLERSLRKHGADFTRTV--PFVIVGKD------QQSNSS-
FVAVNMDGSRQPLPLTTVYNRLQPINS----SFLQAFL--------YPDYPVGLLDIE--
--KILPPGKDITAVGI-YSFNNGVP----------EIKSCQDL--PYFLSEMTKDKMIED
LMEQTNFIFLGSVILG-IVSVGILSYAAVRTWNKW-------KQWNHQR---ELPQRPND
SVV----------------------DDEP--EDADEIPDGE-LCVICVSRRRVPAFIPCG
HVVCCRRCASTVERELNPKCPVCLQSIRGSMRVY---------------YS
>Oryza_sativa
MSARDR---------ETAVALARLAAALDGAVLGLGTAALAVASWVKYL--AASGQLRRI
ASAPAA-AIPDLRSLL------AEYGGGGG------------------------------
------------DGDQPILAVVRGHVRAAPR---------GKYLVPPGSGEHCVVAKHTQ
LCLFNEWRGIFG-WTFDLHALFFKSIKEQIITSFRWV--PFVLVDPE--------NMTG-
MVHVKLDRAMQPLPLTTVYHKLTPVDS-TPYTLFQTII--------GNGYPIALLDEE--
--KILPVGKEITAIGY-IRPHKASV----------EISSCSEI--PFFLSDLTKDEMEAE
LSSRAKTLFWASVVLG-TMSVCLLGFATYRSWKKI-------KERREARQAQEVFRQTTD
EVT----------------------DDQSSDEEAGEMGDGQ-LCVICLRKRRKAAFIPCG
HLVCCCKCALIVERQFDPLCPMCRQDIRYMIRIY---------------DN
>Physcomitrella_patens
MAGHED---------ELCAALMRLALAGDGLVMGVGMTVLAFRTWIKFW--SHSKALKDI
KDTPVT-RIADLRTLV------EEPDVQAKEKIRTPEKISPPHQDIEVFATRSKVKMPSR
PWMVERLPIPSLETKQEKLVIVRGRVQTKAFVESEGDQRDAEALIPLNVPEKAVFVERTQ
TYVLTEMSNFLG-WI---------TQKDLVKFTRQVV--PFVLAETEAHWSFRPSDMAV-
YVHINLDESQHPIPLVTVHHQLHPVPA-SSYTLFQAMF--------GRRYPVGLLDEE--
--KILPLGAEITAVGVLHTAPDGTP----------VVKSSKRL--PIFLTEFTREQLLVE
LASSTKVLFWMGVAVS-TVAAGVLGYSLVKNWTRW-------KQRQQQRQSQNNSENRQN
STI----------------------EDEA--ENFEDIPDGE-LCVVCLLRRRRAAFIYCG
HRVCCMGCAERVEHGANPRCPVCRQSVTGIVRVY---------------DS
>Synechococcus_elongatus_PCC_7942
M---------------------------AAIILAAITAIAAIVLYFVRRHYRFKLQSLLL
AQPATSLQLKEIAEHV-----AGEIG----------------------------------
------------GGNLRQYVKMWGAIEV------------EQPLVSELKQESCVYYCSTV
SREYEERVRKED--SEGKVTWTTERRSETISQNRRST--PFYL---R--------DQHG-
RVRVEPESAA--IATIPVLDEFRPDSSAS--SLIFGAFSLSLSTTAGLGKTLGYRYRE--
--EILPCDRSVLVVGA-ASDETGEL----------TLGPSSEARQQFFIALKPETALLQE
VKQTIQWLTIGAIASV-VVTVVAAIAA---------------------------------
------------------------------------------------------------
-------------------------------------------------LL
>Thermosynechococcus_elongatus_BP-1
M-----------------------------GVLGGILLVIAVLVLCGWWDYRLKVRALNL
AVSSTPAQLHELQRRV-----AQEIG----------------------------------
------------GGYLQEYVKISGQIVA------------DRPLVSELKRLPCVHYRLCV
SRVYKTTESHED--GSSE----TKYRHEILSSNTQTI--PFRL---R--------DGDM-
EIYVDPRGAE--IETVQVLNEFQEDNNTT--HLAFGRFQMDLSSLPKHSDTVGYRYEE--
--WILPVNQQVFVVGT-ASDERGKL----------RIRRPHQKGQLFFISLESEENLTKK
VRQYARASIIAAGVFS-GLGILLI------------------------------------
------------------------------------------------------------
-------------------------------------------------LL
>Rubrobacter_xylanophilus_DSM_9941
M-----------------------VGTVVFLLVGVVLCVAGGVLLYFRR--RMLGKAELM
RRTRTSG--------------AAGVS----------------------------------
------------ALSPGTLVEVKGTLRC------------ERPLQSEMAKERCAYYSSKV
VREYLERDRGDGAPG-------SGRRSEVLARSERFA--PFVV---E--------DDTG-
GVPVSAEGAE--VDAKKVVDRFERGAGAAGLSVTIGGATIDLG---GGERTLGYRHTE--
--EILPVDAPVYVLGA-VRRDGG-------------IGPPEEGAGRFVVSWRSEEALGES
LGRGARLLGLIALGLFLAGAAFLAVGAAAALGYLQ-------------------------
------------------------------------------------------------
-------------------------------------------------FR
>Sphaerobacter_thermophilus_DSM_20745
M-----------------------GTSGVLLIIGLVAAGIGAVLLFIGR--RIQAKTDLL
AKVPTVD--------------ASEVA----------------------------------
------------SLIPGEMIEVKGVIRC------------DTPLTAELAQRACVYYSSRV
VREYEYRRRNAK--GETV----RSRRSETVAHNEQFT--PFYV---E--------DSSG-
RVLVDPEGAE--VDAQKLVDRFERNPGALGPTISLGGISLNLG---GDDGTIGYRYQE--
--HVLPVDIPVYVLGV-VQ-EGGTI----------GRPPAALKGRRFIISYRAEEALRES
WGKKARWLGISAVALF-ALAVILFVVAVGML-----------------------------
------------------------------------------------------------
-------------------------------------------------VA
>Rhodomicrobium_vannielii_ATCC_17100
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------TEDRDEKAEGAPPCVICGMRPQVPEYRP--
--FCSRRCADVDLH-------------RWLGGVYAIPVKPEEEEDEGDATG
>Mesorhizobium_ciceri_biovar_biserrulae_WSM1271
M-----------------------------------------------------------
------------------------------------------------------------
----------------SLAPITYGPIGS--------------------------------
--------------------PLGARFSSYLGSMGRYVVLPIQLVKHG-------------
------------------------------------------------------------
---------------------------------------------PMLLGHIPICWEVQQ
LADLMAQ-----------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CL
>Mesorhizobium_opportunistum_WSM2075
M-----------------------------------------------------------
------------------------------------------------------------
----------------SLAPITYGPIGS--------------------------------
--------------------PLGARFSSYLGSMGRYVVLPIQLVKHG-------------
------------------------------------------------------------
---------------------------------------------PMLLGHIPICWEVQQ
LADLMAQ-----------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CL
>Hyphomicrobium_denitrificans_ATCC_51888
MLERDLYEPVYNYLELRFRDRLQPARGDLRHITAITANTGGNATGIWSK-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------PDLCIISLSRQKYGLSWQI------------DLHGF
EV-----KPQGACSVQSVHEALNHTSLVNFTHLVWH---------------VGDWNESRA
DCSTILSRCSHYGVGLITFSTPGDLTSYVLHLPARRHEPSSDAFDEFVETRLSQDDRTKL
LSWITEL-----------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RR
