>gnl|BL_ORD_ID|3051 @Acidobacterium_capsulatum_ATCC_51196@ gi|225874751|ref|YP_002756210.1| hypothetical protein ACP_3205 [Acidobacterium capsulatum ATCC 51196]
MRYPQWP----------------PDYDTETARQRGSDRF---------------------
----YAALM-AIQVIKPIQTLGFIYRHQEIERRPPMQPGQ---------WAMMNKFDDAM
LARVPAMIDRIQPVMDGGNVEHK--NALSLLQLGL----EHFHPYIAGLLWVTGLEAIFD
SRGK-----EAFKKKLCDCLGPGTLVFPNWHAKTDAPT---------------LTVEEIA
IPL-----------------FVLRNK-LAHGADLRSAAAD---KKHPVDFTKRVSLTQNT
ETVNYALLLCDAA-----------------CYL---------LC-QVLQRVL-----
>gnl|BL_ORD_ID|2274 @Acidobacterium_capsulatum_ATCC_51196@ gi|225873974|ref|YP_002755433.1| putative regulatory protein, FmdB family [Acidobacterium capsulatum ATCC 51196]
M----------------------PLYE---------------------------------
----Y---------------------------RCKQCGHQ---------FEKIQSFSAPE
LKECPVCQGEVERLLSAPAVQFK----------GA------------------G-WYVTD
YAGK------------------------NGSNK---PKSGSS------------------
-------------------------------------------SESSASAASESSSPAKS
ESASASSTPAAKS-------------------------------------------E
>gnl|BL_ORD_ID|1874 @Agrobacterium_tumefaciens_C58@ gi|15889211|ref|NP_354892.1| hypothetical protein Atu1917 [Agrobacterium tumefaciens str. C58]
MLGLVPSICNQSMLCDVDARDRPEHDVERDVRFTVVRSAALWAAFCCPNQMTHLGSQTDS
SASQADSLTPFNILFSHNKCEIAGSPSATQQSHWSDVRPATLFQNAAMPNFITMKRRTAL
TLIASLPFAPLARAQSAGNNIRFDPLLTQADALSSLKAVIVSIDGEEVASRAYHGASLNG
STNIKSAS--KSVISALVGMAIDRKIIEGADQPIATILRGDFPPNPDPRLERITVGNLLS
MQSGLERMSGPNYGRWVASRNWVRMALGSGFAGEPGGGMLYSTASTHL---LSAILTKAS
GRSTLSL---------ARDWFRPLEGFSIG---GWER---------DPQGIYLGG-----
----NQMAMTARSLLAFGEL------YRLGGVTPDGERLISQEWIS----QSWQQRTNS-
---------VFNGDGYGYC---WFI--------------KEMAGETVYYAWGYGGQMLYI
V-PARRLS------VVMTSREDAPSARTG--------YRDQLHGLMED---------IIR
AV-----
>gnl|BL_ORD_ID|4226 @Anaeromyxobacter_dehalogenans_2CP_1@ gi|220919350|ref|YP_002494654.1| metallo peptidase [Anaeromyxobacter dehalogenans 2CP-1]
MIPLLVALAVSAAPSQPRTLRLDLFHTGTATEERFAVDRVVLEPLPFPGNPARP-VDDTN
LGKYFFEVRDLATNRVVYSRGYASIYGEWETTEDARKVGRTFSESLRFPAPDAPVQVLVK
KRGAGNAFQEVWSTVVDPKDRFVDPSRPPSPG---PLIEILKSGDPAHKLDLLLLGDGYT
EAERGKFEKDARRLVAELFEHEPFRSRKADFNVW-----GLCPPAEEKGVSRPL------
-TGVHRRTRVGATYDA---FGSERYLLTFENRSMRDVASFAPYDALAILANGE-------
--TYGGGG---------------------IFNLYATVAADNRWAGY----IFVHELGHHL
AALAD--EYFTSDTAYLSPEGRPEPWEPNVTADP---KAAKWADLVAAGTPLPTPWPKDV
FTKRANEFQERRK---RIRAQNRPE--AEMDALFLAQQKEETALLGQ-------------
--------ARFSKA-----------VGAFEGANYEATGYFRPQMDCVMFTRDPVPFCSVC
QRSI------------------------------------------------------GR
VI-DLYTAR-------------------
>gnl|BL_ORD_ID|568 @Anaeromyxobacter_dehalogenans_2CP_1@ gi|220915692|ref|YP_002490996.1| SirA-like protein [Anaeromyxobacter dehalogenans 2CP-1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------A
EVTATQGGTVVVVNAEQMGRGDDGLGAKLLGNYLRTLASLEPKPEAIVFYNGA-------
------------------------------------------------------------
------------------------------------------VRLLGPGSAHLE------
------------------ALRQLDDAGVDL------------------------------
--------LACITC-----------LEFFQLTGKLEVGHVSNMRE-------------IA
QRTLAA----------------------------------------------------AK
VI-TL-----------------------
>gnl|BL_ORD_ID|634 @Aquifex_aeolicus_VF5@ gi|15606242|ref|NP_213620.1| hypothetical protein aq_913 [Aquifex aeolicus VF5]
MDIYKKLPPLQEPRLFMSTERTYLSQLRFSILVISFALGLTKI-EWVAKMMNKGDIAEFL
RTG---------------------------------------------------------
----------------------------------------------AGALAVIATLVAAV
----------------------------------------GLFSFYKTMSYLKC------
-----GEQVDAKEVVDPRIYMAAERTFLAWIRTAIAITVFGFVIEKFEFF----------
-------------LVQLDRILHISTRVH----------------------------HEKL
FSIGAF------------------------------------------------------
---------------------------------------------------------IIG
IG----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------VL
TLVLGTANFYRTISQIDRGFYRTNVWLYKAYGLVI-F-----------------------
------------------------------------------------------------
-----------------------------ITCLTLAFYILELI-----------------
----------
>gnl|BL_ORD_ID|28 @Aquifex_aeolicus_VF5@ gi|15605639|ref|NP_213014.1| 3-hydroxyisobutyrate dehydrogenase [Aquifex aeolicus VF5]
MKVG------------------------------------------------------FI
GLG---------------------------------------------------------
----------------------------------------------HLGRAIAKRLIEQG
V---------------------------------------ELIVWNRTLSKAHEF-----
-----AKETGAEVTSSPADLINKVDRVFVIVFD---------------------------
-------------SQASEEVIFGEKGLVKGDIKGKTVIDMTTNHYLYAQK-----AYEEL
KKLGAFYLDAPVLGSVIPALKGELTIVVGGDKEKFEENKPLFEKFCRAIYYLGEAGMGSK
MKLVNNIVL----GGIMEVLAEAIAIGEKAGIDKETLINVLNDGAGKSYILDVKKKKLLE
EDFSTHFSVNLIYKDLHYA-----------------------------------------
----------------------QDLIKDLGLFSFTTAAVKETYGLARKE-----------
------------------------------------GFGNLDFSAVYKLFKED-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|1154 @Bdellovibrio_bacteriovorus_HD100@ gi|42522805|ref|NP_968185.1| hypothetical protein Bd1281 [Bdellovibrio bacteriovorus HD100]
MHRG--------------------------------------------------------
-------------------------------NFMKSVISVFIFLLSLSAHAEVGFKNGNQ
--KTA---------VLAQGRIVVHCFGNNPGGP---------------------------
------------------------------------------------------------
----------SHGSFICRE--EILTAGEYDYFVGPA------------------------
------------------------------------------------------------
---------GIKGDSVTLTALHQDGSQRTKTVDYDSAKGQSKKSINLW--IATLLQRPLL
DPGTN-----------TVRYKITSNGKVTASGEFVAEIKDGGTKNCSRTG-------SYT
SNTP--------------------------------------------------------
------------------------------------------------------------
SDCQNGTSLCRRYFNENNYCL---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>gnl|BL_ORD_ID|693 @Bordetella_petrii_DSM_12804@ gi|163854999|ref|YP_001629297.1| mraY gene product [Bordetella petrii DSM 12804]
M----LLE------------------------IARWLSD---------------------
----------------------DVRAIGVLEY------------------ITMRAVLA--
-----------------------------CATA-----------------------LLIG
LV----------------------------AGPRVIRKLTEMKIG----QAVRAYG----
-------------------PESHLVKTGTPTMGG--------------------------
------------ALILIAV----AISTL--------------------------LWADWT
N-----------------------RF----------------VW------VVLLVTFGFG
WIGWMDDYRKVVYRDPEGMPARQKFFWQATIGLV-AAVYLAFAVSAPANTELWPLFKAWV
SSGFAMPLPTRADLIVPF------FKSVSYPLG---------VLGFVALTWAVIV-----
--------------------------GTSNAVNLTDGLDGLAIMPTVMVG----SALGIF
AYV--------------------------------VGRVDYSKYLLFPYI--------PG
AAELMVLCAAIAGAGLAFLWFNAY----PAQVFMGDVGALALGGALGTIAVIVRQEIVLF
IMGGVFVVETLSVMMQVTWFKYTKR----------------KYGQGRRIFRMAPLHHHFE
VGGWKETQVVVR---FWIISMM--------------------------------------
---LVLIGLSTLK---------------LR
>gnl|BL_ORD_ID|1866 @Bordetella_petrii_DSM_12804@ gi|163856172|ref|YP_001630470.1| unnamed protein product [Bordetella petrii DSM 12804]
MTKKQLLSGACGQAPAGRHDAVQSRLAPGEAILARLETDLDAHLAFRPGSVVLTGRRLLA
CCSDDGQWREWPVAPRLRLSLADHAGVATLELRDGPVRLAAWRFTLARNAAALRLVAAFD
AVQAGRQTSAPACSTCHLPLPAGQAECPVCAQAAARPPSSWALLRLWRFARPYRGPLLAG
FVLTLLATAATLVPPYLTMPLMDDVLIPFQNGAPIDYSLVRLYLGGLLASAALAWGLGWA
RTYILAWVSERIGADLRTTTYEHLQQLSLQYFGGKRTGDLISRIGSETDRICIFLSLHLL
DFATDVLMIAMTAAILVSINPWLALVTLAPLPFIVWMIHAVRDRLRHGFEKVDRIWADIT
NVLADTIPGIRVVKAFAQEKREVQRFRAANNRNLEVNDRVNSLWSLFSPTVTLLTEIGL-
LVVWVFGIWQVANK-------------QITVGVL-AAF---LAYIGRFYTRLDSMSRIVS
VTQKAAAGAKRIFDILDH------VSSVPEPDAPARLDR---VAGRIELRNVAFR-----
--------------------------YGNRSV--IQGLD-LAIAPGEMIGLVGHSGSGKS
TLINLICRFYDVSEGAILVDGIDIRNLRIADHRRHIGLVLQEPFLFFGTIAENIAYGRPQ
ATRAEIVAAARAAHAHDFILRLPH----GYDSLVGERGQALSGGERQRISI----ARALL
IDPRILILDEATSSVDTTTEKEIQKALDNLVRGRTTIAIAHRLSTLRRADRLVVLAHGRV
VEQGRHEALMARQGAYYRLYQA--------------------------------------
---QARTGEADLRDDVDDADGGDDDDAPHA
>Mulan_NP_078820
MES---------------------------------------------------------
--------GGRPSLCQFILLGTTSV---------------------VTAALYSVYRQKAR
VSQELKGAKKVHLGEDLK------------------------------------------
---------------SILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLTLQ
EHKMV-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------WNRTTHLWNDCSKIIHQRTN-------------------------------
-----------------TVPFDLVPHEDGV------------------------------
-DVAVRVLKPLDSVDLGL------------------------------------------
-------ETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLK---VGATLTGVGELV
LDNNSVRLQPPKQGMQYYLSSQD---FDSLLQRQESSVRLWKVLALVFGFATCATLFFIL
RKQYLQRQERLRLKQMQEEFQE--HEAQLLSRAKPEDRESLKSACVVCLSSFKSCV----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FLECGHVCS-----------------------CTECYRAL------------
------------------------------------------------------------
---------------------------------PEPKKCPICRQAITRVIPL--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------YNS
>gnl|BL_ORD_ID|678 @Campylobacter_concisus_13826@ gi|157164541|ref|YP_001466545.1| DNA-directed RNA polymerase, beta subunit [Campylobacter concisus 13826]
MKLTNLKPVEIKEEHRPRDFEAFQLRLASPEKIKSWSYGEVKKPETINYRTLKPERDGLF
CAKIFGPIRDYECLCGKYKKMRYKGIKCEKCGVEVTTSKVRRSRMGHIELVTPVAHIWYV
NFLPSRIGALLGIKMKDLERVLYYEAYIVDNAGEAYYDNENSKKVEKYDVLNEEQYQSLA
SRYEETGFTARMGGEVIYDMLAELDLTQILNQLKEEMEATNSEAKKKTIVKRLKVIESFL
NSGNRPEWMMITNLPVLPPDLRPLVNLDGGKFAVSDVNDLYRRVINRNSRLKRLLELDAP
EIIIRNEKRMLQEAVDALFDNGRRANAVKGANKRPLKSLSEIIKGKQGR--FRQNLLGKR
VDFSGRSVIVVGPKLKMDQCGLPKKMALELFKPHLLARLEEKGYATTVKQAKKMIEDKTN
EVWECLEEVVKDYPVMLNRAPTLHKLSIQAFHPVLVEGKAIQLHPLVCAAFNADFDGDQM
AVHVPLSQEAIAECKILMLSSMNILLPASGKAITVPSQDMVLGIYYLSLERNDEKGANKI
FSSVDEVMIAEEANTLGLHAKIKTMVDNKIIFTTAGRLILRAILPDFVPENMWNKIMKKK
DIANLVDYVYRNGGLEVTADFLDKLKNLGFRYATKAGISISIADIIVPDSKQKYIDEAKK
KVREIQKQYGAGLLTDSERYNKIIDIWTDTNNSVASEMMKLIQSDKGGFNSIYMMADSGA
RGSAAQIRQLAGMRGLMAKPDGSIIETPIISNFREGLNIMEYFNSTHGARKGLADTALKT
ANAGYLTRKLIDVAQNVKVTMHDCGTHEGVEITDITESGELIESLEERVLGRVLADDVID
PITNEILFSEGTLLDEEKAKAITEAGIKS--VSIRTPITCKAPKGVCAKCYGLNLGEGKL
VKPGEAVGIISAQSIGEPGTQLTLRTFHIGGTASTEQQDRQVIAQKEGFIRYYNLSTYE-
---------NNGKKIVANRRSAAVLLVEPK----------IKSTIDGKIEIEYAHEDVNI
VIKGKKEEIKYTI---RRNDLAKPNELAGVSGKIEGKMYIPYANGDKVKENESI-VEIIK
EGWN-IPNRIPYASELKISDGDPVTRKITADANGVVK----FFILKGDFLDRLKDIKKGH
KVTEKGFFVVVSDKDGREAVRHYIPRNSIIQVSDNDAVERATVVSLPEKDDKLIIAEWDP
YSTPTIAEEAGVVSFEDVEPGYSATEQADEATGQRRLVINEYLPSGVKPAIIITTKSGHL
IKYPLDPKTAIFVSSGDEVAQADILAKTPKAVAKSKDITGGLPRVSELFEARRPKNTAIV
AEIDGVVRFDKPLRSKERIIIQAEDGTTAEYLIEKSRQIQVRDGEFVHAGEKLTDGLISS
HDILRILGEKALHYYLISEIQQVYRRQGVAIADKHIEIIVSQMLRQVKIVDSGNTNFIVG
DMVSRNKFKEENERIMKMGGEPAIAEPILLGVTRAAIGSDSVISAASFQETTKVLTEASI
AAKFDYLEDLKENVILGRMIPVGTGFYKDKKIKIKEN
>gnl|BL_ORD_ID|694 @Campylobacter_concisus_13826@ gi|157164873|ref|YP_001466560.1| bifunctional 2-C-methyl-D-erythritol 4-phosphate cytidylyltransferase/2-C-methyl-D-erythritol 2,4-cyclodiphosphate synthase protein [Campylobacter concisus 13826]
MLDISLIMLGAGNSSR--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------FELPVKKQWL
RIGSDPLWL----------------------FATKNLSNFY--------------TFKEI
IVVSKECKYMSKFAPNYKFVDGGETRQDSLKNALELVSSEFVLVSDIARPCISSELFHKI
IEAAAQADCVV-PALKIADTAYLGENAIDREKVKL-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------IQTPQLS-----------------------------
------------------------------------------------------------
------------------RTTLLKKALSSGEIYTDDSSAMRA------------------
--IGASVWHILGDE---MARKITFKEDLVKISALKAPENELFVGS--------GFDVHEF
EKGRPLVLC--GEKIDYE------FGLKAHSDG-DVALHALTDAILGAAGLGDIGELFPD
TDDKFKDISSIYLLQEAYKRVQ------SVGFVLTNA-------------DITIMAQKPK
LSKLKSKMEANIAQALNLSQSRINVKATTTEGLGFVGRCEGIAVMASASL----------
------------------------------------------------------------
-------------KF---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------YN-----------------------------------
------------------------------------------------------------
---------------------------------WTQI
>Mulan_NP_078820
ME----------------------------------------------------------
------------------------------------------------------------
SGGRPSLCQFILLGTT-SVVT---AALYSVYRQKA-RVSQELKGAKKVHLGEDLK-----
----SILSEAPGKCVPYAVIEGAVRSVKETL---NSQFVENCKGVIQRLTLQEHKMV-WN
RTTHLWNDC-------SKIIHQRTNTVPFDLV------PHEDGVDVAVRVLKPLDSVDLG
--------LETVYEKFHPSIQSFTDVIGHYIS-GERPK-------GIQETEEML------
-------KVGATLTGVGELV-LDNNSVRLQPPKQGMQYY---LSSQDFDSLLQRQESSVR
LWKVLALVFGFA---------------------------TCATLFFILRKQYLQRQERLR
LKQMQEEFQEHEA------QLLSRAKPEDRESLKSACVVCLSSFKSCVFLE-CGHVCSCT
EC-------------------YRALPEPKKCPICR-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------QAITRVIPLYN-----------------------S
>gnl|BL_ORD_ID|2185 @Candidatus_Solibacter_usitatus_Ellin6076@ gi|116621331|ref|YP_823487.1| unnamed protein product [Candidatus Solibacter usitatus Ellin6076]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------KCGVL----------------------------
------------------------------------------------------------
--LAAAALSAAAQAPGPRTLRLDYVHTGTAAEEHFAQDGVVLEGAWPGPLDRWVDESNLG
KYYFQVLDRG------------TNRVIYS-----RGFASIYGEWETTDEAKTQ-----HR
AF----QESV----------RFPAPAGPVQVVIKKR-------GPRNEFREVWS------
--TV----------------------------VDPADPAVDRAAPPK--------VNVW-
---AVMQNGAPRDKVDLLLMGDGY-TAAEMEKWHGDARRMAE-------------TLFA-
-----------ASPFKEHRQDFN--VWAVDTPAEESGVAR------PSDGVFRRSPLRAA
YDVFGSERYV---LTFDNKR------------LREAASAAPYEFIE--------------
IVVNDRKYGGGGIFNLFATVSADNAFTPYVFVHEFGHHFAGLADEYYTSDVAYGSATERP
EPWEPN---------ATADPRAGKWKDLLTAGIDLPSIWPKKAYEQMEQAIQERRRTIRA
Q-HRPEAEMEALFREESGLATKLLGSGPNAGKVGAFEGAMYEGRGYFRAQQDCMMFGRDA
G-----------FCAVCRRAIERV------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------IRMYAK
>gnl|BL_ORD_ID|314 @Chlamydia_trachomatis_434_Bu@ gi|166154288|ref|YP_001654406.1| unnamed protein product [Chlamydia trachomatis 434/Bu]
MSFFH-------------------------------------------------------
------------------------------TRKYKLILRGLLCLAGCFLMNSCS------
-----------------SSRGNQPADE--------------SIYVLSMNRMICDCVSR-I
TGDRVKNIVLIDGAIDPHSYEMVKGDEDRMAMSQLIFCNGLGLE-HSASLRKHLEGNPKV
VDLGQRLLNKNCFDLLSEEGFPDPHIWTDMR-VWGAAVKEMA---AALIQQFPQ------
---YEEDFQKNADQILSEMEELDRWAVRSLSTIPEKNRYLVTGHNAFSYFTRRYLSSDAE
RVSGEWRSRCISPEGLSPEAQISIRDIMRVVEYISANDVEVVFLEDTLNQDALRKIVSCS
KSGQKIRLAKSPLYSDNVCDNYFSTFQHNVRTITEELGGTVLE-
>gnl|BL_ORD_ID|147 @Chlamydia_trachomatis_434_Bu@ gi|166154121|ref|YP_001654239.1| unnamed protein product [Chlamydia trachomatis 434/Bu]
MH----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SLTVFQ------EIFNRYT
EKPYPATSILVP---LYFPEEPLTFSEDLSPSTAPIL-NPPGLEPQALPVETPKDPV---
----TTSIPPP------SHPKESKHSWACVPIYPGLSHEELLKENYPALKRYIQRPARAS
CGIFVHESQEHEILFFNRLAKILSQKIFPTRLV--------------------LFYQKTL
SDFSHSPH----PFCLAPLPTIRYKN-------------SQVNYHDPVLHDKVT-CI---
-----------PIYSSSQYEK-DSALKRDLWTLLTSLSASMQKS
>gnl|BL_ORD_ID|557 @Chlamydophila_abortus_S26_3@ gi|62185205|ref|YP_219990.1| ligA gene product [Chlamydophila abortus S26/3]
MQSTYSREQYISLCKDIEEDDYRYYVLHNPTISDYDYDMKMRQLLSIEAQHPEWKVLWSP
SMRLGDRTSGSFPIVAHAHPMLSIANAYTLEELYEFFSRIEKTLGYTPKYTLEIKIDGIA
VAIRYEQRVLVQALSRGNGRKGEDITANIRTIRSLPLRLSKEAPEFLEVRGEVFFSRATF
CQINAAQRQAEKPEFANPRNAAGGTLKLLSAKEAAQRNLEISIYGSLAEENKRSHYENLL
LCKEWGFPVFGQPRQCQTIEKVVASLHEIEVARAQLPMEIDGVVIKVDDIEDQKVLGMTA
KHYRWALAYKYAPERAETILEDIIVQVGRTGVLTPVAKLRPVVLSGSRVSRASLYNEDEI
ERKDIRIGD---TVYVEKGGEIIPQVVGVCLEKRPEGTQPWVMPEYCPVCHQKVTRESDK
VSVRCTNSL---CSA------------------GVIEKIRFFCGRDALDIDHLGEKVVTK
LFDLGCIHRRCDIFQITEEDLRQVPGFKDKSIR------NVLKSIEKAKSVPLDRFITAL
GIPYVGIGGANALAQHFLSLESVMAASLDDLKAIEGIGDKVAESIVAYFHQPEHLEEIQK
ML-------------------------SLGVHILPCHRASSSCLGKAFVITGTLEKLTRS
EAETYIRNCGGKVGSSVSKNTDYLVVGQDPGS--KLKRAQELGVPILSEDELLKLLY
>gnl|BL_ORD_ID|1401 @Chlorobium_tepidum_TLS@ CT1422 2-desacetyl-2-hydroxyethyl bacteriochlorophyllide A dehydrogenase
ME----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------AK
KSKAIVFSGVNQIELREVTLKPVSSTDVLVETWWSSISTGTE------------------
---------------------------------KMALNGLIPSPPF------IFPFIPGY
ETVGRIVEA---------------------GDHVNQGLIGKFAYVAGS------FGYEDV
NAAFGGASQFIV---------------CPVESLTVLDGIANPQCGI--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AL--------PLGATAL-------------------------
------------------------------------------------------------
------------------------------HIVDLAEVKNRKVL----------------
-VLGQGAVGILAAELAKRFGASLVAVTEPHQRRLDISTSDIKVNPEKQDVSVALAGHEF-
-DVLIDSTGIMSAIETGLRFLKFHGKVIFGGYYQ---------------------RMNID
YSQAFNKELSFIAARQWAKGDLHRVRELIAAGKINAEKIFTHQCTVD---DNLMEAYMQA
FSDSDCLKMIIHWKHGNEAGEHFPTCNTA---------N
>gnl|BL_ORD_ID|1528 @Chlorobium_tepidum_TLS@ CT1552 valyl-tRNA synthetase
MSDHSAQNLEKTYNHHEVEERWRSAHWEAIGTFHAEHSRVLKEGATPYTVLMPPPNVTGS
LTLGHVLNHTLQDIFIRYARMMGKEALWLPGTDHAGIATQTVVEKKLRKEGVTRHDLGRR
DFLDKVWEWREEYGGLILRQLRKLGISCDWRRNLFTMDERASEAVINTFVALYREGLIYR
GRRIINWCPVSQTALSDEEVIMKSRRDKLVYISYPLAKDPTR------------------
---------------------------------SITIATVRPETILADVAIAVNP-----
------------------------------NDERYADLIGELVIVPIAGRHVPVIADDYV
DIEFGTGALKITPAHDPNDYEVAKRHNLPVFSVIGKDARMTDECGYAGMDRFDARDKIVA
DLAELGYLVKLEEYEHNVGYSERADVVVEPYLSEQWFVKMQPLAEPALKVVNDGEIRFHP
EHWINTYRHWMENIQDWCISRQLWWGHRIPAWYDDKGNV---------------WVASSY
EEA------CHLAGTD---KLSQDEDVLDTWFSSWLWPLTTLGWTGPHSDNDDLRAFY--
PTDTLVTGPD--IIFFWVARMIMAGLHFKGDV------PFRDVYFTSIIRDMKGRKLSKS
LGNSPDPLKVIDTYGTD-ALRFTIVYIAPLGQDVLFGEEKCELGRNFATKIWNASRFVFM
QREKLFATREEFVEAFANFTPQRELMSSAGRWLMSRYNAMLERYHQAMANFKVNDMVKIV
HEFFWGDYCDWYVEALKSELTGDITEERGRHAVCLAVSVLEGVLKALHPVMPFITDEIWH
AIAPRSAEETIATEAMPQPDASWRGEDA-----AAFDLVRNMVSEIRSLRSAFNVPHDLR
AQAVIRAS----SPAALVALQTGRAIFPAMTKCEVELGESVERPAHSAASVVDGNELFIK
LEGLISFEKEKQRLEKEITKVTAYIESLEKKLSNEKFVSNAPADVVAKEKEKLEESRSMV
LKLQGNLEVL----------------------------S
>gnl|BL_ORD_ID|1927 @Chloroflexus_aurantiacus_J_10_fl@ gi|163847531|ref|YP_001635575.1| hypothetical protein Caur_1971 [Chloroflexus aurantiacus J-10-fl]
MKA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-REIMT------------------------------------------------------
-------------KNVVC------------------------------------------
-----------------------------------------------------VTDD---
------------------------------------------------------------
------------AAVEDAARLMTRNRISGLPVVNPQGMLVGLVTEHDLIAKEGRTVKEIM
TRSVISVSPDTEVEQIQH----------------------LLTNQRIRRVPVVENGKVVG
IVSRSDLVRQ----IAMRWVC--------------------GVCGEIVRALEAPKHCPRC
GADT--------------------------------------------------------
---------------------------HAF------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------THEVVPPGM------------------
------------------------------------------------------------
-----------------------------
>gnl|BL_ORD_ID|2164 @Clostridium_tetani_E88@ gi|28211998|ref|NP_782942.1| inosine 5-monophosphate dehydrogenase [Clostridium tetani E88]
MAII-------------------LKKGYTFDDVLLLPN----------------------
----------------KSEVLPKDVLLNTNLTKKIKLNIPLI-------SAGMDTVTESR
MAIAMAREGGIGIIH---KNMSIEKQAEEVDRVKRQENGVITDPFHLSPDKKLQDALDLM
SKYRISGVPITVEGKLVGIITNRDIVFEDDYSKKISELMTDEDLITAPENTTIDQAREIL
KKHKIE---KLPLVDENFNLKGLITIKDIDK---------IKMYPNSAKD----------
DKGRLLCGAAVGVTADMIERVDAL--------VKAQVDVITIDTA----HGHSRGVLEGV
------------------------------RKIKELYPELQIIAGNVATPEATRDLILAG
ADCVKVG---IGPGSICTTRVVAGVGVPQLTAVMDCVEEAQKHGVPVIADGGIKYSGDIV
KALAAGASVCMMGSLLAGCAESPGETEIYQGRSYKVYRGMGSLASMACGSKDRYFQEDNK
KLVPEGVEGRVPYKGYLSDTVYQLVGGIRSGMGYLGSKTLKDLYESARFIVQTSAGLRES
HPHDISITKEA-----PNYST---------NA
>gnl|BL_ORD_ID|2206 @Clostridium_tetani_E88@ gi|28212040|ref|NP_782984.1| diaminopimelate decarboxylase [Clostridium tetani E88]
MRLFGTMEVKDNNLYIGGVSCKELKNKYSTPLYIIDEDFLRGRCKEYYNNFGVEKHGNKV
AYAGKSFLTIAMCQIIKEEGLFLDVVSSGELYTALKANFPMN-------KIYFHGNNKTL
DEIEMG--IELGVGKFVVDNFYEMNNINNMARKKGIKQSIL---LRITPGIEAHTHDYIK
TGQVDSKFGFSMVGEEVYKAVETALSLPNINLSGIHCHIGSQIFETTPYEEAVDIMFEIL
KEIKNRYDYEISEVDLGGGFGIYYTKEDKPKETKEYCEAILKKALNKSKELGIKLPMLGI
EPGRSIIGNA----ATLIYTIGAIKEIP---GIRKYVS---IDGGM---NNNIRPALYDA
--------------------------------------KYECEVANNMNSD-DRELVTIA
GKCCETGDIVIEDVEISKSK-----------------------------------SGDIL
AIPSVGAYGYSM-------------SSNYNK-----------------------------
--IPK-------------------------------------------------------
-PAIV-LVKDGESRVMCKRESFDDMLKNELSL
>gnl|BL_ORD_ID|1363 @Cytophaga_hutchinsonii_ATCC_33406@ gi|110637791|ref|YP_677998.1| ADP-glyceromanno-heptose 6-epimerase [Cytophaga hutchinsonii ATCC 33406]
M-----------------------------------------------------------
----------------------------------------------------MVVTGAAG
FIGSCLIQRLNELNFNFI-----------------------------VAVDHFENPEKKK
N-----------------------------------------LENKKIQEYV------DR
DDFFDWLDKNNKHVEFIFHIGART---------DTTEFDKAIFDRLNVA-YSKNM---WN
ACIKYQIPLVYASSAA-------------------------TYGNGEFGYDDNEQKIP--
---QLKPLNPYGDSKNDFDIWALQQEKQPFFWAGLKFFNVYGPNEYHKSRMASVIFHAFH
QIKNSGKMKLFRSHKAEYTDGGQMRDFVYVKDVCNVIIFLMNHRKNSGIYNLGSGTARTF
LDLAKNTFKNMEVTENISFIDTPIDIRDKYQYFTEANMGKLKSIGYTDTFHT---LEEGI
KDYVKNYLI----PNKYW
>gnl|BL_ORD_ID|1477 @Cytophaga_hutchinsonii_ATCC_33406@ gi|110637905|ref|YP_678112.1| copper transport system protein [Cytophaga hutchinsonii ATCC 33406]
MNLHMKNIVLGLTLLIVAWSCNKESGKNTPDNVFYTCSMDPQVMEKKPGKCPICKMDLTK
VIIDKNDMQSGLKLNNEQEQSANIKTLIISEGDLGREKTVNGRIVINENKRFKISSRVSG
RIEKLYIKSLGETISKGVKLYDLYSEDLLVAQREYLIAIEKSKEFSGSELDYIQLADGAK
NKLILWGMNENQIKSLI-----NKKELSNTVTIYSPYKGVVTSVNKREGDYV-----MDG
DVVFETADLSTLWVEAELYAG------------EVNEFDVNDPVAIKIIGFPGKI---WN
SRIDFFAPQLQTQSKV-------------------------NLVRAEISNTDMSLRPGMQ
ANIVLKENTKKALF--LPLNAILQDSKGATVWI---------------------------
------KEKDGSYHSRMVITGIESNDNIEIRSG---------------------------
-----------------------------------IEAGEEVVINGAYLLNSEYIFKKGT
NPMAGH-------DMSNM
>gnl|BL_ORD_ID|1150 @Dehalococcoides_ethenogenes_195@ gi|57234064|ref|YP_181906.1| orotate phosphoribosyltransferase [Dehalococcoides ethenogenes 195]
M----------------------------------------------------------E
DVETLFEKTGAILK----GHFLLT---------SGLHSPI--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------YWEKFRIIENPEYNQQLC
GMIAEHYKDKGIELVAGPTTGGIVLAHEIARQMGLKCVFAEKIADSERG-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------FRRGFVIKPGAKVLVVDDI
LTTGKSVREVLAAVKKA---GGEVAGIGVLVDRSDTALQFNAPVFS--------------
---------------------------------------------------CLRSATTTY
KPEDCPLCRQGL------------------------------------------------
------------------------------------------------------------
------------------------P------------------------LTKHGS-----
------------------------------------------------------------
------------S
>gnl|BL_ORD_ID|1081 @Dehalococcoides_ethenogenes_195@ gi|57234088|ref|YP_181837.1| glutamine-dependent NAD(+) synthetase [Dehalococcoides ethenogenes 195]
MGKLRLAMAQIDSVVGDLAGNTACIIRHIQEARSLGADVIVFPELAICGYPPEDLLHKPR
FVEGNLHSLDSVIK----ASEGITVIVGYVDSHNGLHNSAAIIHNASLIDSYHKIFLPNY
GVFDENRYFLPGNRCPVYTICGLRVGVNICEDIWFASGPSTAQSNKGAELIINISASPYH
FGKRNQREKMLSDRARENRVYIAYTNMVGGQDELVFDGASNVFDYTGNLVLRGKQFQEDL
LVLDLDIPALTRQGDMSTEIPDSIFVSASGLSEPKLPFENSDSVPLDADAEVYQALLLGT
KDYINKNGFKKVVI--GLSGGIDSSLVAAIATDALGADNVVGVIMPSRYSSAGSISDSLR
LAE--NLGIKTLQIPIDPIFKSFLSTLSEVFAGTETDTTEENIQARIRGNLLMALSNKFH
WLVLNTSNKSETAIGYSTLYGDMAGGFAIIKDVPKVLVYRLAHNRNKSAGFELIPHNVLT
KPPSAELKP-NQ----------------------------LDTDSLPPY-ELLDPILE--
----------AYV---------EQDKSIDQIVALGFEESIV-------KRVVKMVDRSEY
KRRQAPPGI------------------------KITP----------KAFG---------
------------RDRRL-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------P------------------------ITNRYNH----
------------------------------------------------------------
-----------VG
>gnl|BL_ORD_ID|405 @Dehalococcoides_ethenogenes_195@ gi|57234804|ref|YP_181161.1| hypothetical protein DET0416 [Dehalococcoides ethenogenes 195]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------AQDKTLVCRDCGNEFI-------
------------------------------------------------------------
----------------------------------------FTAGEQEFY-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------ASRGLKN
EPKRCPACRSARRSENRGEGGERRTYEVVCA-----------------------------
------------------------------------------------------------
----------------ACGVQTTVP--------FEPTEGRPVYCKDCYAKTKESE-----
------------------------------------------------------------
-------------
>gnl|BL_ORD_ID|59 @Deinococcus_radiodurans_R1@ gi|10957459|ref|NP_051603.1| extracellular nuclease [Deinococcus radiodurans R1]
MSGKRAANALLLAGLLALSACGSQQPAGTGAAVPAPGPVTSGTSRSSLGVYQLSLSGAGS
AIKQASVQRLGAQATEVGGLSFKSNNYGYYVDSSNNTLRMWATFDVTNTSDQPLAAPTFI
PVDT---------------EGAGGTIGTTAFKNV---------------------RYFDG
SDASSRA------PLLAFDSSND--PKTAVKTQLLRDLDSGSVQVNLPAGLQLAGTSHTG
WKMGALP-----AGATGQVTLAASIPAASNSQDNPFSFDLVFTV----ADNV---PSTTL
TNIGAVQGQTPGGDRPAALTGAQTIEGVVTAVEPGLSGFFVQEEGIDADRDETTSDGLFV
-------------YCAASCPALSAGDRVRVSGTVAEYGGATQMTAPTVTKLLSGLALPPA
AELKLPLDKTQQERYEGMRVRFPETLTITNNYTYGRYGQLDLSNAGRMFNPTNGNASASE
QSTITLDDGVSAQ----NPLDLNYLSAERTRRTGDTVTGL-----SGVWHSVANQPML--
--EPEGAVEFVSANSRASNALPHDVGGSLRV--GGANVLNYFTTYGGSTDRGANNAGELA
RQRAKMATTLTTLNADVLSLMEVQNNGDTALNDLVAALNEKAGAGTYAAVTTGSVGTDAI
KVAIIYKPSKVTPVGQFMTDNNSVFSRPPVAQTFRDKTTGGVFSVIANHLKSKGSCPTSG
DVDTGQGCWNQLRVRQAQALLGFVDTVKQKSGDQDVLLLGDFNAYGAEDPIKVLQGGGFE
SLNLRIPAEDRYSYQFNGLFGYLDHALASQNLSAQVSGITEWHVNSDEPVIADYNTEFKK
VAGCTGTNCTGIDLFDPTNPFRASDHDPVLVGLNLTADAGTTPTPAPTTALSANPS----
-----ALTVTAGGAAVSSTLTTSTQNYSGADFTVSTQNSAGLTVAPSATSVSPNGTFTVS
VTAPAGTAAGTYPVTVTTTGAGGLTATATLNVTVSVGGTPPPSSTGSDLIISEYVEGTSN
NKALEFYNPTANTLDLSAYTVELYANGATKATNTQKLTGSLAPGAVLVLVNGSAVPELKA
RGTVSSVTNFNGDDAIVLKKSGVVIDSFGQVGVQSMWGADVTLRRKSGIVSGDSNPNDPF
SAATEWDSFPVDTFDGLGSR
>Mulan_NP_078820
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
ESGGRPSLC--------------------------------------------------Q
FILLGTTSVVTAALYSVYRQKAR-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------VSQELKGAK---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------KVHLGEDLKSILSEAPGKCV---PYAVIEGAVR----------SVKETL
NSQFVENCKGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQRT------------------
-----------------------------------------NTVPFDLVPHEDGVDVAVR
VLKPLDSVD--LGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGV
GELVLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFI
LRKQYLQRQERLRLKQMQEEFQEHEAQLLSRAKPEDRESLKSACVVCLSSFKSCVFLECG
HVCSCTECYRALPEPKKCPICRQAITRVIPLYNS--------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|2297 @Desulfovibrio_vulgaris_DP4@ gi|120603199|ref|YP_967599.1| preprotein translocase subunit SecA [Desulfovibrio vulgaris DP4]
MLGFLFKKVFGSKNDRYIKRLRPIVAAINALEPQMQSLRDEDFPVRIAEYRQQVEEGRKL
DDMLPEVFALVREAGKRVFNMRHFDVQLVGGMALHHGKIAEMKTGEGKTLVATLPVVLNA
LTGKGVHVVTVNDYLAKRDAAWMGQLYNFLGLSVGVIVHGLDDEQRKAAYGADITYGTNN
EFGFDYLRDNMKFYAEQLVQRG-HNFAIVDEVDSILIDEARTPLIISGASEE--------
----------------------STGLYRHMDE---IVRKLTRDTHFTVDEK-----ARTA
MLTDEGVAFCETLVGIDNLYD-----------------------------------PGNI
TTQHHLMQALKAHNLFRRDVDYIVKEGQVVIVDEFTGRLMPGRRFSDGLHQALEAKEAVK
IEAENQTLASITFQNYFRMYAKLAGMTGTADTEAVEFHQIYSLEVVSIPTNKPMQRKDFA
DAIYRTKREKYDAIAQAIAELHKAGQPVLVGTISIETSELLS-------------TMLKK
TGVPHSVLNAKHHEKEAEIVALAGQRGHVTIATNMAGRGTDIV-----------------
------------------------------------------------------------
-------------------------LGEGVRELGGL------------------------
---------------------------------------------------HILGTERHE
SRRIDNQLRGRSGRQGDPGSSRFYLSLEDDLMRLFGSERISGLMEKLGMEEGEPIEARMV
SRAIENAQKRVEGHNFEIRKTLLDYD------NVMNQQREVIY-----TLRRDAMSAPDL
GPTMEEFLDDVLEDVYAPAE---------GGEAPSADT----------------------
------VAAVWGRLADVCNITRVMQPAPALPTRDEARAAVL------------SILHELR
EDTGESYRDIIRYFMLEE---------------------------------LDRCWKEHL
RNMDHLR---DG---IGLRG----------------------------------------
-----------YGQRDPKLEYKREGFAMFQEMLFRIKEGVFRSLTRLRVQRVEEEAFRHK
EQPAAVAYSGGEAEAGPAQPHREDPKVGRNDLC---------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------PCGSGRKYKKCCGA
>gnl|BL_ORD_ID|419 @Ehrlichia_canis_Jake@ gi|73667053|ref|YP_303069.1| hypothetical protein Ecaj_0429 [Ehrlichia canis str. Jake]
M-----------------------------------------------------------
------------------------------------------------------------
----------LVPQEVIASNSLLCEYVKYTTINIKSATCIGSTDIINNKLKIHISKDSNL
QPIVQPHAKSLFLLEVTIPSSIV-KNDPYLRNIYI-----ISQSESLDANLYCLVDASH-
-IQSFTNEIYDTVQNKVPKFVDNIFKYTEV----------------------------IF
AKLEIDSHLKLNE-----YEILCSILPDAE-----FIIHEIEEKNSCCSCCPPFTSKQNI
TRVQSQESLLQENDAEQVTLPKPE------------------------------------
-----------------DNITNTSISSTDSSTEHNSISSLLSFVNVTIESINSFQNN---
---------------SK-----------------
>gnl|BL_ORD_ID|199 @Ehrlichia_canis_Jake@ gi|73666833|ref|YP_302849.1| trigger factor [Ehrlichia canis str. Jake]
MLDCYVVKEVSNDKLKWEYEFVIDKKYFLDQLDSKLSEIAKNVKVPGFRVGKASIDLVKK
EYLNDVMTDVVRKTIESTSSDFVKSNKFGEIISSNIDIVSYPNYYSDNDSKEENLVYKLS
FEVMPEAPLMDIDSIVLNG---IEVDIQESDVSEFIENLKK--QRPN------FIVVNGA
EYAVQEGDKVVIDYQNKVKGKILRGGSAKDFALVIGKGVALKEFENQLLGMRVGETKSFP
-LTFPDDYSVAYLAGK-------TTDMSVVVKSIYVVKD-VQDNESV-------------
----------------------ARSYGFKDVAEMENFVRK------------QIGQQFDQ
MVLTIMKKELFDYMDNTYSIDVPECVVKQEITKINKEILDSGEDIQIDVEKEAVRRVKLG
MLLIRMSRHNNITIKNEDVLSFIKNNYTDYGVDINNVLKML-------QSNKNFANYISG
KVLEDKVINYIIKLVKKDRKVMTTKEINLMFENI
>Mulan_NP_078820
ME---------------S------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------G----GRPSLCQ--------------------------------FILLGTTSVV
TAALYSVYR--------------------------QKARVSQELKGAKKVH---------
-LGEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQF---------VENCKGVIQRLTL
QEH------------------------KMVWNRTTHLWNDCSKIIHQRTNTVPFD--LVP
HEDGVDVAVRVLKPLDSVDLGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLK
VGATLTGVGELVLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFA
TCATLFFILRKQYLQRQERL-------------RLKQMQEEFQEHEAQLLSRAK----PE
DRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEPKKCPICRQAITRVIPLYN--
------------------------------------------------------------
----------------------------S
>gnl|BL_ORD_ID|940 @Fervidobacterium_nodosum_Rt17_B1@ gi|154249646|ref|YP_001410471.1| diguanylate cyclase [Fervidobacterium nodosum Rt17-B1]
MRSL--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VENHIGDFLDIL-------------------TYQKKEWI--------
----E-------------------FWKKLPYKPITDNYANKF------------DGFYEK
LLSISRNELTELSHWYDENKENIR-----------DELTVRIRKSARDFQLS--------
-KEDFVIYLIVG-------------IGEKDWIVVDGKSEKVIVFDVYSIWKKG-------
-------------KIDKLA---------------DAIYQSVVHFRHGELEG--NYYDKS-
---------EIFEYLKKQIVSAKNE---------------NLLEMICKLLDEHVPYYNWT
GFYLMDDEGMLVLGPYVGEPTEHVRIPVG-KGICGQAADTKLTFIVQDVSQETNYLSCSP
-HVKSEIVVPIFRNDGSVFGEIDIDSHYIAPFD-------------NRDKEFLEWIAKQL
MVRTVHWDEFKRRIKIAYIDSYLSYLLSEI---IKYNVTYFVDLYVFNDPNKVPENLFKL
WRISEKLSCSEIKNI----------YVVDKVEEQRAVLYSEIDSI--------SLDYNIL
NLPPQDVVFYMIKNLREEMAKKLFYIH-----YQATRLAQSFINSKLIIKYT-----LNK
DSNINTILYAFLTG-------ITAGYAGSFNRAMFFYYTDEKFVFQKA------------
-------IGPRTQEEANRIWEAIEDI------------ELNMKDFLDT-VSKDFRSALEL
LYEGKTIELDVVKKYTDGEAHVISKEEIPELAETFDILKEFALVTVKSGENI--LGLIIA
DNNFDLKPISD--YQLTVLKDLADQMAFILEN-------------RRFFETVKEKAEI-D
VLTGLKTRRTFEEFIQNIPLNSFSLAFLDLNKFKMINDMYGHEKGDEILKKFGKCINMNI
RKTDIAFR-----YGGDEVIIILNTTEET--IVEKVIGRILDCFSSSAGMTFSTGVAIYP
AEG---DINKVLKLADERCYKSKITGKIEFEDSELNS
>gnl|BL_ORD_ID|1640 @Flavobacterium_johnsoniae_UW101@ gi|146299407|ref|YP_001193998.1| unnamed protein product [Flavobacterium johnsoniae UW101]
MKLKKILFPILL------------LCFFMADAQTASIKNADKKYDSYAYA----------
------------------------------------------------------------
--------DAIKAYEKLVEKGVREERIFQRLGNSYYFIGELKDALKYYQELFSINENQEA
DYLYKYAQCLKSEGNYTKADEILEKFSQKAPSDKRVVL---FLKNRNYLEDIKSNSGRFD
IADAGINSKDSDYGSTILDNKLVFTSARDTGSIIKKNFKWTNKAISTLYAVDLNPDGSIG
KPMLFHKQNLQVNFNQSTPVFTKDGKTMYFTRNNSVDGKRKQNENKVTFLKLYKAVLINN
EWKEVQ----ELPFNSD----------EYSVAHPALSVDEKTLY--FAS----DMPGTLG
LSDIYKV--SILSNGGFGAPENLGPEINT-----EGRETFPFISDENELYFASDGRPGLG
GLDIFVSKITKECTFD-EVQNVGEPINSKQDDFAFIINSKNRNGFFSSNRVNGHGLDDVY
RFTENRRLICEQQISGTITDQETNETLSNVALILFDEAGKTAVEAKSDANGNYVFSNVKC
GKKY-YIKTAKEDYLFKEVSITLKKATGSASLPIALEKKPKPITAIPVVIKTNNSIKPVK
VTIAVGTDLGKLLKIPMNFFDLGKATIKKSSV--PQLQKMVDMLNQYPTIKVDIRSHTDS
RSSSESNQILSDKR------------------------------------AQSTKDWLVS
KGINADRLTAKGFGETQLVNKCADGVKCTEQQHQQNR-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-RSEFIIVSL---
>Mulan_NP_078820
M--ESGGRPSLCQFILLGTTSVVTAALYSVY-----RQKARVSQE------LKGAKKVHL
GEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTT
HLWNDCSKIIHQRTNTV------PFDLVPHEDGVDVAV-----RVLKPLDSVD-------
----LGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDN
NSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQYLQ
RQERLRLKQMQEEFQEHEAQLLSRAKPEDRESLKSACVVCLSS-----------------
----------------------------------FKSCVFL-------------------
------------------------------------------------------------
----------------ECGHVCSCTECYRAL--------------PEP--KKCPICR---
------------------------------------------------------------
-----------------------------------------------------------Q
AITRVIPLYNS-------------------------------------------------
-------------------------------
>gnl|BL_ORD_ID|1839 @Geobacter_metallireducens_GS_15@ gi|78223054|ref|YP_384801.1| unnamed protein product [Geobacter metallireducens GS-15]
ML----------------------------------------------------------
-----------------------------------------------------VMKNIWK
E-----------------------------------------------------------
---------REKA-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------LENQYIYKQE
Q-----------------------------DKIERMQKEERERLV----------REMCR
N--RCPKCGDEIKAMTF-------------RGVPLDR-CPGCGGVWLGPNDLRILASKDH
RSWFEKWFKEENETSE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------KV
A
>Mulan_NP_078820
MES---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--GGRPSLCQFILLGTTSVVTAALYSVYRQ-KARVS-QELKGAKKVHLGEDLKSILSEAP
GKCVP-----------------------YAVIEGAVRSVKETLNSQFVENCKGVIQRLTL
QEHKMVWNRTTHLWNDC--------SKIIHQRTNTVPFDLVPHEDGVDVAVRVLKPLDSV
DLGLETVYEKFHPSIQSFTDVIG-----HYISGERPKGIQE-------------------
-TEEMLKVGATLTG--VGELVLDNNSVR-------LQPPKQGMQYYLSSQDFDSLLQRQE
SSVRLWKVLALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQEHEAQLLSRAKPED
RESL-----------------KSACVVCLSSFKS--------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------CVFLECGHV
CSCTECYRALPEPKKCPICRQAITRVIPLYNS----------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|2384 @Heliobacterium_modesticaldum_Ice1@ gi|167630523|ref|YP_001681022.1| ppdK gene product [Heliobacterium modesticaldum Ice1]
MSKKWV------------------------------------------------------
--------------YLFEEGKAEMKSLLGGKGANLAEMTNIGLPVPPGLTITTEACNAYY
DAGKNFPEGLMDQVKSALAEVEAKLGKKFGDAENPLLVSVRSGAVFSMPGMMDTILNLG-
------LNDVTVKGLAQATQNDRFALDCYRRFIQMYSDVVLGASHADFEHILEEYRERQG
V------RFDNELSVESLNALIADYKAMVRRTTGQTFPQDPMAQLEGAVRAVFSSWNNDR
ARVYRQINRIPDNLGTAVNVQAMVFGNMGNDCGTGVAFTRNPSTGEKALYGEY-----LI
NAQGEDVVAGI----RTPLHISRMQEELPECFEQFVEIC-GILERHYRNMQDIEFTIERG
KLWMLQTRNGKRTAAAAVKIAVDMVQEGLISKEEAILRVEPEHLDQLLHRRIDPTAKLTV
IA------------TGLPASPGAASGKVVFDADEAEALGK---AGEKVILVRMETTPDDI
HGIVQA--QGI-----LTS-RGGMTSHAAVVARQMGKPCVCGCEALRIDYNRGDFAVATA
SGGIKTYRKGDIISI-------DGATGRVIEGVVPMLEPELTKEFRVLLDWAD--EIRTL
GVRANADKPEEAEMARNFGAAG------------IGLTRTEHMFMAQDRLPIVQ-----E
MILAQSLEEREAALAKLLPMQQGDFYGILKAMAGFPVCIRLLDPPLHEFLPSLEDLLVDT
TRLR-------------CAIETTDGDRKEAL-LDELNEKEQLMKKVRALHEFNPMLGHRG
CRLGITYPE-----------IYAMQA------------------RAIFQAVVQLVDEGFD
VEPEVEIPLVAEVKELAYLRKVVEETAAAVMTETGTKFHYTVGTMIEVPRAALTADQIAK
EAQFFSFGTNDLTQTTFGFSRDDAESKFFGVYSERKLLSDNPFIVLDRDGVGSLM-----
------------KIAVERGR--ATRPDLLVGICGEHGGEPSSIEFCHLIGLNFVSCSPYR
VPIARLAAAQAAIQN---G
>gnl|BL_ORD_ID|2534 @Heliobacterium_modesticaldum_Ice1@ gi|167630673|ref|YP_001681172.1| adhE gene product [Heliobacterium modesticaldum Ice1]
M-----------------------------------------------------------
---------------------------LG-------------------------------
----------------------ADDGTTHGASPASDVTQAIDRLVNQAQAALDRFLELDQ
EQVDNIIHSMAVAGLEQRMPLAKMAVEETRRGV--YEDKIIKNTFAT-ESVYHSIKYHQT
VGVISVNEFDDYEEVAEPVGVIAALTPVTNPTSTTMFKALIAMKTRNPIIFAFHPGAQRS
SAAAAQ-----------VVYEAAVRAGAPEHC---IQWVEQPSIDATNLLMRHPGVNLIL
ATGGANMVLAAYSCGKPALGVG------PGNVPCFIEKT-ANLHRAVTD-----------
-LIMSKTFDNGMICASEQAVIVDRAIAGDFE------RYMSEHKCYFLNE--DEKTRLEG
IVINEEKCAVNADIVGQPAARIAEMAGFSVPPDTKILLARLEGVGPQYPLSREKLSPVLA
YYIVDGAEEGIDRAEEMVR-FGGM-GHSAVIHSE--DPAVIDAFSRRIKAGRLIVNAPAS
QGAIGEIYNANMPSLTLGCGTFGGNSTSANVSVVNLINKKRVARRREKMQWFKIPERIYF
QFGAVAYLEKMPDIHRAFIVTDPVMVQQGYVDRVLHYLRKRHIYVHSEIFAEVEPDPSVE
TVMRGCRMMRDFKPDVIIALGGGSVMDAAKGMWLF------YEHPETDF--SLLRLRFMD
IRKRVYKYPKLGAKARLVAIPTTSGTGSEVTSFAVISDKERNIKYPLADYELTPDVAIID
PEFVMTVPPGVTADTGMDVLTHAIEAYVSVLASDYTDALAIKAIQMVFEYLPRAFHNGHD
KQAREKMHNASCIAGMAFTNAFL-GINHAMAHQLGGVFHIPHGRANAILLPHTIAFNASR
PTKFTSFPNYE------SYVADRR-------YAEIARMVGLPARTVE-EGVQSLIEAVRH
LMQKLRMPLTLAELGIERNRFMSLVPEL-----AERAFDDQT-----------TTANP-R
MPL--MTELQQILINAYGG
>gnl|BL_ORD_ID|2014 @Heliobacterium_modesticaldum_Ice1@ gi|167630152|ref|YP_001680651.1| pstC gene product [Heliobacterium modesticaldum Ice1]
MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------PNGENTAITTEFVVR-----------------------------------
---------------KESLSKG---------------------ASKKRRIWDVAEKMTEG
LLFL----------SAFIGVVTIILIFLFLFKEAIPL-----------------------
----------------------------MTDPAAGTLLSK-------------KWYPISS
PPV-----------------FGLL-------------PLIAG--SIIVTFGAIVISVPLG
VGAAIYLAMVASPVV---------------------------------------------
---------------------------------------------RETLKPAIE------
-----------------------VLAGIPSVVVGFFGLAVLAPLIKDLF-----------
------------------------------------------------------------
-----NLPTGLTALTGAITLALMALPTITSIS------------EDAISSVPRRYMEASL
SLGATRWQAIKTVIVPAALSGITAAIMLGIGRAIGETMTVLMVTGNAGVIPDTFLVPVRT
MTATIAAE-----------------------MGEVARGSDHYYALFLVGAVLFLMTFLIN
LVADIVSR----------------------------------------------------
----RMKEVE---------
>Mulan_NP_078820
ME----------------------------------------------------------
------------------------------------------------------------
------------------------------SGGRPSLCQF--------------------
--------------------------------------ILLGTTSVVTAALYSVYRQKA-
-------RVSQELKGAKKVHLGEDLKSILSEAPGKCV---PYAVIEGAVRSV--------
------------------------------------------------------------
---------------KETLNSQ------------FVENCKGVIQR---------LTLQEH
KMVWNRTTHLWNDCSK--------------------------------------------
-IIHQRTNTVPFDLV--PHEDGVDVAVRVLKPLDSVDLG-LETVYEKFHPSIQSFTDVIG
HYISGERPKGIQETEEMLK-VGATLTGV--------GELVLDNNSVRLQ--------PPK
QGMQYYLSSQDFDSL---------------------------------------------
---------------------------------------------LQRQESSVR------
------------------------LWKVLALVFGFATCATLFFILRKQYLQRQERLRL--
------------------------------------------------------------
-----------------------------------------KQMQEEFQEHEAQLLSRAK
PEDRESLKSACVVCLSSFKSCVF-------------------------------------
---------------------------------------------LECGHVCSCTECYRA
L------------------------------------------------------PEPKK
CPICRQAITR--VIPLYNS
>gnl|BL_ORD_ID|785 @Heliobacterium_modesticaldum_Ice1@ gi|167628923|ref|YP_001679422.1| unnamed protein product [Heliobacterium modesticaldum Ice1]
MDKEILRKTVENVRELIDTKNYRIADTILEELLTEHPHNPEINYLLAYVKHVSGFDLHLA
IDYYNQSLVYGFDEYWVRYHRAQLYHLLGNTESAIKDL----------------------
----EIAISINENNVDAKNILNLINGNELFTNKANNHNCEFKVLVNSIPKAGTNLLTTCI
NSIKALRYSGYHVEHEEPHQLITIF-------------DSLRKGQYVSSHLYPTY---TN
VNIVEKNKFKTLLMVRDPRDVVVSWV--------------NYATKKEYVRYT--------
--------------------DYLIR-----------------------------------
------------------------------------------------------LKDDHQ
RLLTGISGVSRDQCSK---------------------RYGQEDIGTVFREYLKWNNYEYN
LMV--------------------------------------------------RYEDLIG
PEGNGSKEKQIQQIEKVLRHLGITIPNE--------QILVISNKVFNVD-----------
------------------------------------------------------------
-------------------------------------------------SPTFR------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------KGIIGDWKNHFSDEH-
-------------------KKAFKEIAGDVLITLG-------------------------
-------------------------------YEE--------------------------
------------------------------------------------------------
---------------NYDW
>gnl|BL_ORD_ID|4318 @Herpetosiphon_aurantiacus_DSM_785@ gi|159900852|ref|YP_001547099.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------TATEAAMPVLQLRQISKRFGAVQALSNVDFEVYSNEVVALVG------DNGA
GKSTLIKTIAGAYKPDEGDYVFEGKVVSINSPRDATDLGVE------------TVYQD--
-----LALCDNLDVVSNLYLG------RENVRRSGLKSFDLLNETEMERRATEVL-----
------------------------------------------------------------
--------RDLSVKIPSVRVQIANL------------------SGGQRQSVAVARSVMWN
SKVVLLDEPT--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------AALGVEQTRQVKDLIMRLRDRGLAVVVISHNVADVFEVS-----
--DR-----------------------------------------IIV----------MR
LGRRVA---------------------TFHTARSTNEQVIGAITGAMLPSNAYGEAE
>gnl|BL_ORD_ID|4688 @Herpetosiphon_aurantiacus_DSM_785@ gi|159901222|ref|YP_001547469.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------TTLNVGDLAPEFELPAD-----------------------NGETIRLSDFRG
KRVVLYFYPKDDTPGCTTQACGFR------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------DAYPQIEEQNAVVIGVSPDSVASHQKFKTKFDLPFLLV-A-----
--DEQHSLAEAY---------------------------------GVWGEKSMYGKKYMG
VTRSHFIIDENG-------YLIDVQG-KISPADSVSGALKLLIK-------------
>gnl|BL_ORD_ID|249 @Legionella_pneumophila_2300_99_Alcoy@ gi|296105747|ref|YP_003617447.1| O-methyltransferase [Legionella pneumophila 2300/99 Alcoy]
MN----------------------------------------------------------
------------------------------------------------------------
---------------------------KFP------QSFSE-------------------
-------ANERIGNAIHHVCLNALDAKFIKSNIQESYQSWANVLY------------DRV
FLNWGLCDK------------------KIYRELSSLNFDFSTVGFFPHVYGQSLLFYLIR
PLIK---------------------------------------------------IHFFN
KRLLDVGCGNGVGLKIS-----SELLKTRY-------------------------ALGID
LVNK-------LVTNSNNNFYIED------------------------------------
-KINYMQADAENMAIANESFDIVTNLESSHLYPQIEHFFSEVERVLA-PNGFFCYADVNF
DVKRQAERFETFVKTRKNLRIIEKHNIT-KMIQASIYQRLIVNEKRFYQLAQY-------
-------LLGPDKINYTSELANV----ASSMGL-MFLPWWRIRFKNPALQALGKFARR-Y
KHWNKKYYFYYLIQKID-------------------------------------------
-----------------------------------------------------------S
>gnl|BL_ORD_ID|327 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116330127|ref|YP_799845.1| glucose-1-phosphate thymidylyltransferase [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
MP-------------------------------------------------KVQRILIDE
REIPIGLRSLTRIRSFSEIRNGILSTVQRTKELYPDAKIFYVHSNPAFQQAFLERNPKLF
PYDEKDVDLVLSPESCL----------PWNLIDGTAKNIEDDL---------ELGKEVQK
WIRKLKVKSNHFHVIGKSKHLHVHSSAVIYPG----------------------------
-----------------------------------------VVFDTTSGP---VIVDKDV
KITSFSFIEGPVYVGPNSQIDN-----------------ARITGATSIGATCRIGGEVGA
CLIGDFTNK-------------------HHEGFLGHSILGSWVNVGALATTSDLKNNYGV
VKIREENDECITGSIK--------------------------------------------
---------------------------------FGSVISDYCKIAIGVMLNTGTVVDFGS
NVVSSRIGGYVSPFTWAESGQPYILDLFLRDARKIMARRNRELTLSE-------------
--------TELIRILYESKVKK
>gnl|BL_ORD_ID|171 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116329971|ref|YP_799689.1| hypothetical protein LBJ_0190 [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
MN----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------PEEKVKLLETLDLI------LKHL
QNQS-----------PNPGSDY--------------KVVLYLVPIFGIVFG---CALLFF
VFYWWYRQR--IEIIKAGLYKKETFDLRTYSFFLG------------------LIFTFVG
IALSIG------------------------------------------------------
---------------------------------FISVLGQSLA-----------------
-MLGGLV-----------------------------------------------------
------PLGTGLGLLCYYKFSR
>gnl|BL_ORD_ID|2454 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116332254|ref|YP_801972.1| lipoprotein [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
MK----------------------------------------------------------
--------------------RNVLLFTIYIFGIFFFLNLYFCKKNNL-------------
---------------------------PLGIKDERWREESSELVSAYCQ-----------
------------------------------------------------------------
-----------------------------------------KLASCTKGA-----KDSSS
STEP-----------PDLKHSS--------------------------------------
-------QELIQERLKPANCAEK---FRNSNAYL--------------------------
--LANENPETIKKVVRSC------------------------------------------
---------------------------------FQTVIGENCE-----------------
-KVRRGVLKLSEDCVR---------------LQIIQFKQD--------------------
----------------------
>Mulan_NP_078820
ME----------------------------------------------------------
----------------SGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQELKGAKKVH
LGEDLKSILSEAPGKCV----------PYAVIEGAVRSVKETLNSQFVE-------NCKG
VIQRLTLQE-HKMVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRVLKPLDSV
DLGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSV
RLQP-----------PKQGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFF
ILRKQYLQR--QERLRLKQMQEE---FQEHEAQL--------------------------
--LSRAKPEDRESLKSACVVCLSS------------------------------------
---------------------------------FKSCVFLECG-----------------
-HVCS-----CTECYRALPEPKKCPICRQAITRVIPL-----------------------
-------------------YNS
>gnl|BL_ORD_ID|132 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116329932|ref|YP_799650.1| tRNA modification GTPase TrmE [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
MNDTIAAVSTASGPGAIGIIRMSGPGALSISSSFLFSKNGFLSPSDIQPRIAIQCVFQIG
DRKIDQILFFYFKTPNSYTGEDLCEFHFHGNPILLREALDAIFRAGARPAKQGEFSRRAF
LNGKLDLTGVEAIGRLISARSRFELELAQKNVFGEVSRLTSNLRSQLISLKAECEAEIDF
STEDLTYES-LEERKVRIEGVKTFCQTVIAKSNS---------------AEKVIQQLRIV
LYG-------------------------------EPNTGKSSLMNVLLG------KDRSI
ISEI-----------PGTTRDY------ISEEILLEGIPVRLVDTAGV------------
---RETEDH--IERLGIERSEKE---FQSADIRLF------------------L------
--IDVSKKEEWKKFIAKAKGRLEGSILVANKIDIRDSSWNPNLFSDVKDLIICEISCKTK
EGIPILLDEIQKKAATMGHVEDYVLLEERQRYHFETIV----------------------
-------------------------RCLDKTLRLIEEGAPAEIYIQEMNYALSEIGEVNG
RVDTEEVLGRIFSKFC---IGK
>gnl|BL_ORD_ID|355 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116330155|ref|YP_799873.1| hypothetical protein LBJ_0399 [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
MT----------------------------------------------------------
--------------------GFLTVVLCLGVAAVFFHLLYSVDTRRIDNAE---------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------KKRDAQNGVSKEYGDPKKV
YGKN-----------WDPNLPK-----------------PRICPVCG-------------
----KYLQK--MEYLYAVIEEPPSPGIKRHARIYG------------------CRYCYLG
LDEETS------------------------------------------------------
---------------------------------TQNVSSQN-------------------
--------------------------------QNIE-RAPIEIKDEE-------------
-------------------LGL
>gnl|BL_ORD_ID|802 @Methylibium_petroleiphilum_PM1@ gi|124265996|ref|YP_001020000.1| sugar ATP binding ABC transporter protein [Methylibium petroleiphilum PM1]
MLRLELLGISKQYPAVKANDGVSLRVAPGQIHAVLGENGAGKSTLMKIIYGAVRPDAGEM
VWDGRQVQIASPAQARQL-----------GISMVYQHFSLFDTLTAAENVWLGLDKSLSL
AEVTVRIVQVAKVYGLEVDPQRPVHSLSVGERQRVEIVRAL-LTDPKLLILDEPTSVLTP
QAVETLFVTLRQLAERGCSILYISHKLDEIRALCHHC--TVLRGGKVTGEVDPRTVGNAD
LSRLMIGAEPPKLQHIQARLGD--VAL--------------QVSGLTLAKQSPFGTDLKD
IGFEVKAGEIVGVAGVSGNGQQELMAALSGEDPRAPLGAVKLFGHDIGRQPPRARRALGL
HFVPEERLGRGAVPTLSLAANTLLTRTEAVGRGGWLHMARVHRLAESLIRTYNVKAGGPK
AAAKSLSGGNLQKFIVGREIDARPKLLIVSQPTWGVDVGAAAQIRGALLKLRDEGCAVLV
VSEELDELFEISDRLLVIAQGRLSPSVATMRTTVELIGEWMSGLWPKADTANGEALHHA-
--------------------------------------------------
>gnl|BL_ORD_ID|2990 @Methylibium_petroleiphilum_PM1@ gi|124268184|ref|YP_001022188.1| uroporphyrin-III methylase [Methylibium petroleiphilum PM1]
M----------------------------QLGLMLLLLLVSVTALSMAWYGQRRVRTLEQ
ELVRRQQDSAGQAAEAQLLAKQAQELSRDAVAKVTLTESRLAEITAQRGQLEELIQSLSR
ARDENLVVDIDA--GIRVALQQTAITGSA-----APLVAALKAADERLARVSQPRLEPVR
RAIARDLDRVKAVSVADIASLAI--KLDEAARLVDEAPLQVLDPQRLAEAKAPRAVARVA
PSPASAAASAAPVGGLRAELGDWWQGLWAETRTLLRVTRIDQPQAMLLAPEQGFFLR-EN
LKLRLLNARLALMSRQFDTAQSDLQAAVAAVDNYFDRGARKT----------QLLTELLR
SVVPQARQAGVPRPDDTLAALTTA----AAGR----------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|248 @Mycobacterium_smegmatis_MC2_155@ gi|118469180|ref|YP_884672.1| unnamed protein product [Mycobacterium smegmatis str. MC2 155]
MQI---------------------------------------------------------
-------------------------------REHVGANKPAIILYPSGTVVTFD----EL
EARANRLAHHFRNQGLQEGDVVAILMENN-------SHIHTVMWAARRSGL-------YY
VPISTHLTAAE---------------AAYIVDNSGAKAIVGSAKMRDV---------LAG
LGDEL------PNGLPDTLLIADGDLDGWLRYPE----------AVADLPDTPIDDELDG
DLLQYSSGTTGRPKGIKRELPHVHPSENPGMMAALISFWMTPDSVYLSPAPLYHTAPSVW
SMQVQAAGHTTVVMEKFDAEGCLEAIQKHRVTHGQFVPAMFTRMLKLPESVRNSYDVSSL
KRVMHAAAPCPVDIKKQMIDWWGPIVDEYYASSEAIGATLITAEEWLKHPGSVGKPLTGI
VH-VLDEDGNELPPGQAGEIFFEGGQDFEYLNDAEKTASSRDARGWKTVGDIG-YLDEEG
YLYLTDRRHHMIISGGVNIYP-----QEAENMLVTHPKVMDAAVFG-VPDDEMGQSVKGV
VQTVDPADATPEFGEELLAWLRDRLAHYKCPRSISFELQLP--RTDTGKLYKQELIAKYS
>gnl|BL_ORD_ID|534 @Mycobacterium_smegmatis_MC2_155@ gi|118472265|ref|YP_884958.1| unnamed protein product [Mycobacterium smegmatis str. MC2 155]
MQIDGQQLAAFAAVIELGSFDAAAARLHVTPSAVSQRIKALEQRVGQVLVVREKPCTATP
AGVPLLRLAAQTALLESEALAEMGGGSSHRPRMALAVNADSMASWFTGVFRRLPDVLFDI
RIEDQDLSARFLREGVVMGAVTTERTPVSGCRVHPLGAMRYIPVASAEYMA-------RY
LPDGFNREAAA-----------AAPSLAWNRDDRLQDQLVRKVFRRDVTRPVHFIPTAEG
FGAAV------RAGLG------------WGMYPE----------DLVDASFVPITEHHLD
VPLFWQCWKLDSP-----------------LVQAITDAVLA-------------------
------------------------------------------------------------
------------------------------ASARLRG--RRTAAE---------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------R
>Mulan_NP_078820
M--ESGGRPSLCQFIL------LGTTSVVTAALYSVYRQKARV--------SQELKGAKK
VHLGEDLKSIL-------------------------------------SEAPGKCVPYAV
IEGAVR------------------------------------------------------
-SVKETLNS----------------------QFVENCKGVIQRL-TLQEHKMVWNR----
TTHLWNDCSKIIHQR------TNTVP-------------FDLVPHEDGVD----------
--------VAV---RVLKPLDSVDLGLETVYEKFHPSIQSFTDVI----GHYISGERPKG
IQETEEMLKV----GATLTG----------------------------------------
----------------------------------------------VGELVLDN------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------NSVRLQPPKQGM------------------------
------------------------------------------------------------
-------------------QYYLSSQDFDSL-----LQRQESSVRL--------------
------------------------------------------------------------
------------------------------------------------------------
-------------------WKVLALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQ
EHEAQLLSRAKPEDRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEPKKCPICR
QAITRVIPLYNS
>gnl|BL_ORD_ID|1368 @Nitratiruptor_SB155_2@ gi|152991122|ref|YP_001356844.1| seryl-tRNA synthetase [Nitratiruptor sp. SB155-2]
MIDLRALEK---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------DFDTIA----------------------------TRLQTK
GVEE------------------------------------KVLAELKELFEEYKKEKTIL
QELQTKQNSLSKMFGQYKREGKDINELKNELEINKGKIA-------AHQEVVRDLEEKLK
NIALTIPNPPDPDVPVGENEEDNVVLKTVLEPKGFDFEPKEHWELGEK----------LG
WIDFERGVKLAKSRFSVLKKEAARLERALINF------------MLDHNKEYGFEEV---
----CVPFMAN--------------------------------SATLLGTGQLPKFEEDL
FKICDEDLYMIP---TAEVPLTNLYRDEIIKDLEDPIK----------------------
-------------------------------LTAYTPCF---------------------
--------------------------------------------RKE-------------
--------------------------------------------AGSGGRDVRGMIRQHQ
---FDKVE---------------LVAITRPEESDKVFDEMVKC------ASSLLAKL---
---GLPHRHVMLCTGDLGFSAAKTIDLEVWLPGQGK--------------YREISSISNT
RDFQARRAQIRFKDGKKNRLVHTLN--------GSSLAVGRTLIAIMEN-----------
------------------------------------------------------------
---------------------------------------------------------YQQ
KDGSIAI-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------PKVLES------------------------------------------
-----------YL
>Mulan_NP_078820
M-----------------------------------------------------------
------------------ESGGRPSLCQFILLGTTSVVT---------------------
------------------------------------------------------AALYSV
YRQKAR------------------------------------------------------
----------------VSQELKGAKKVHLGEDLKSI------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------LSEAPGKCVPY-------------------------AVIEGAVRSVKETLN
SQFVENC---KGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQRTN-----TVPFDLVPHE
DGVDVAVRV----LKPLDSVDLGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEE-
------MLKVGATLTGVGELVLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLWK
VLALV----FGFATCATLFFILRKQYLQRQ-E---RLRLKQMQEEFQEHEAQLLSRAKPE
DRESLKSACVVCLSSF---------------------------------------KSCVF
LECGHVCSCTECYRALPEPK----KC-PICRQAITR-----VI-----------------
--PLYN------------S-------------------
>gnl|BL_ORD_ID|1588 @Petrotoga_mobilis_SJ95@ gi|160903080|ref|YP_001568661.1| DNA topoisomerase I [Petrotoga mobilis SJ95]
MPKKSTKSKGNSEESKYVVIVESPSKAKTIERYLGKEYKVIASKGHIRDLPKKEFGVDIE
HDFEPIFQVIPGKEKVIQEIKKETKGRKVLLASDMDREGEAIAWHLSQILDLDPKEKNRI
IFSEITKNAIKNSISNPQSLDLKKVDAQIARRILDRLVGYKISPLVWKVLKDYKTSAGRV
QSAALKLIVDKERKIFIFKPKKYFNIYLEYKGQNIPLTKEDGKKIKPESITKIKKDQIFE
YLKDKDFKLVNVEEKESIRKPPL-PFITSTLQQAAVSTFNWASSKVMKIAQELYEGVETS
EGSIAFITYMRTDSTRVSNEAQQAAINYLEKNYGKDYVGHYLSKNKKSNVQDAHEAIRPT
DINMDVNNAKRLISSDHLKLYTLI----WNRFMASQSAPSRYLEKTYTIEDNTNKYAF--
----------------------------------------------EITSKKCIFDGFEK
F-WNPNNKEVNFEIGKNDKITYD-------------------------QLKFEEKETNPP
NRYTEATLIKELESKGIGRPSTYATI---ISTLLQRKYVSK-------------------
IAKSTLRPTTTGFVVTDFLETYFPEIV---DVKFTANMEEDLDKIEDGKNKSKVV-----
LEQF-YKEFETFLSTASNNIKNKKEILHYESDVPC-------------------EKCGKN
MK---LNFGRYGLYLSC---EECKETQKIPAESFGVTIKEKLYI---KEYL--QETLK--
----IDKEENKIDEKCPICGGDLILKHGKFGEFIACSNYPECKYTRNVKARG---KCPNC
GGDIVKLKSKKGKTYFKCN---SCSTMYWNEPSEYSCPNCGETLFYKTSKGKEKLYREKD
KAYFDIEEIKQLTK------
>gnl|BL_ORD_ID|3363 @Pseudomonas_stutzeri_A1501@ gi|146283762|ref|YP_001173915.1| hypothetical protein PST_3445 [Pseudomonas stutzeri A1501]
M--------------------------------------------LNATTWFERYQQRYR
WATRAYDRFVQDLVPELVDTLQRNEQVTVAVYGATQVGKTTLILDLLGLSTLTTNEVGSV
LRGGQQLGKSATAMPIRYGRSLDDGWYIAGEGPLSADTARETLRAFRRKVESGGICDAEV
LDIRIPRG----LFQQCDDSSAGLELNIIDIPGIN------------SHSSAEQALVTKL
ADRYVVAADIVLLV-------------------------GKADSLGFLNERDLIIPALAD
WAAQPTRFRIVLTYGFSPDSLVSQFKDQELTVEQVRDVHIGQM-----------------
-----------------------------------RTHDYVFPPEFRSNLFVL-------
------------------ELGDSIVDLGRTNPEYLQRIL---------QVTNDFRGELLE
----NIVKAAG---------PYARL-------------------QGAFQLDRVINARVER
LRKAL--------------------------ENQEVEYGRQRRQITDELAAFHPELLDA-
------SDEEIYVAIDKLGVDRL------DLKNKL--DELSASIKRLEEFNCAALFLTEF
SAGAVEKVSWLQEQLENCE-----------------------------------------
------------------------------QLQRKACIQAASLLFDKG------------
------------------VLPSWLKDEVPVIEYQRKALLDIDSHLNSYVLDGYWW-----
---SSSNFNEDR----NSLQKALRLNAREHGERIQSA-----------------------
----------------TKRALHERKRALLADYKNLKSHCIILQSYLESLQALEREYRCIC
AEYADD-----LQEMDRALGMASSFESQLNAAFMEELRSTKEDVESHPVPA---------
------------------------------------------------------------
--QRFYGLLHTRLLLSEIDRMYEGKSF-----------------------
>gnl|BL_ORD_ID|3499 @Pseudomonas_stutzeri_A1501@ gi|146283898|ref|YP_001174051.1| ABC transporter ATP-binding protein [Pseudomonas stutzeri A1501]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------SNLNAIQLSGVSKSFDGFMALSQADFTARWGEVHALL
GENGAGKSSLMNIAAGLYA-----------------------------------------
-----------------PESGSLLINDNAVRLSGPRDASRYHIGM-----------VHQH
FKLVKPFTVAENIQLALPE----------------GPGNHAFSGS-HRQRLAALEQRISD
KAA--ELGFSIDPRKIT----ESLSVAEQQRVEILKVLL---------AGARILILDEPT
----AVLTDGEAERLLETVRAFARQ-------GAAVILVTHKMSDVKRFADRVTVMRGGR
TIQTL--------------------------DPQTVSVPELVRLTVGE-SAPASEYQPA-
------IPGEVRLQVRDLRSTGAGGQGVL--------NGVNLSLRAGEIYGIAGVGGNGQ
SELA-------------------NVLMGLPEPC---------------------------
--------------------DGTLELTGFGDLRRASAEQ---------------------
--------------------------------RRELRIAAIPADRYGAALAGELS-----
---VAENFGVGQ------------VHSGRYGSFFRLR-----------------------
---------------RKRLEAEAAEAVAGFDVQGVRS----LKQKAALLSGGNAQKLVIA
REFSRDPLLVLVHSPSR------GLDVRATAAVHARLRAAREAGAAVLVI----------
----------------------------------------------------SEDLDEVL
ALADRIGVMSGGRIVAEFDRPADRQAIGSAMVSHDEPGHAEPVAEGASHE
>Mulan_NP_078820
MESGGRPSLCQ----------FILLG-------------TTSVVTAALYSVYR---QKAR
VSQELKGAKKVHLGEDLKSILSEAPGKCVPYAVIEGAVRSV--KETLNSQFVENCKGVIQ
RLTLQEHKMVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRVLKPLDSVDLGL
ETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNS-----
---------------VRLQPPKQGMQYYLSSQDFDSLLQRQESSVRL-WKVLALVFGFAT
CATLFFILRKQYLQRQERLRLKQMQEEFQE-----HEAQLLSRAKPEDRESLKSACVVCL
SSFKSCVFLECGHVCSCTECYRALPEPKKCP-----------ICRQAITRV---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------IPLYNS
>gnl|BL_ORD_ID|1342 @Rhodopseudomonas_palustris_CGA009@ RPA1350 putative transport protein ExbB2
MTIEKNDVRGAGWGWSRGAKSVAKAVTKAGLLAAVGGMLLTATPANAWWNDEWQLRKKIT
IDTSAAGANITDPIGTTPVLVRLHTGNFRFNATKEDGGDLRFVAGDDKTPLKYHVEKFDA
LLGEALVWVAVPDLQPGAKTDLWLYYGNKKAVAIADSKGTYDPDTQLVYHFAERGTVPLD
STVWANNAQSVGQPADGAIIGTGLRLDGRTPLTLPSSSALALAGSGGWTWSAWVKPAAAQ
PNSALYSRR----DGGNAVVIGFDNGAPFVEVANAGAVQRSATAAPVALNSWHHVAVVAG
NGRVTLYLDGNAYAVLDAALPALNTLAFVGGDALASNPAPTASPAASQAPLPDGSSPQGA
PTGDAPAADAPVAAAPAAMAGFAGDIDELEISKASRPAGFVRVAALGQGLDKGKLLTFTI
DEETASWLSGYFAVILKSVTLDGWVVIAILMVMAVISWMVMVDRASYLRRQARANARFIA
CYNAVDFDLRLLSYGSPEDVATLGGRLNNKDAALMRSSSLYRIYHIAADEIRRRSHQGGL
PVLTSNSIAAMRAALDGGVVRESQRLNRLMVMLTIAISGGPFLGLLGTVVGVMITFAAIA
ASGDVNVNAIAPGIAAALVATVAGLGVAIPALFGYNYLISQIKNLTADVQVFVDDVVTRI
AELYTSDLPSPLRRDQAAE
>Mulan_NP_078820
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MESGGRPSLCQFILLGTTSV-------
----------------------------VTAALYSVYRQKARVSQELKGAKKVHLGEDLK
SILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLTLQEHKMVWN--------
RTTHLWNDCSKIIHQRTNTVPFDL-VPHEDGVDVAVRVLKPLDSVDLGLETVYEKFHPSI
QSFTDVIGHYISGERP-------KGIQETEEMLKVGATLTGV--GELVLDNNSVRLQPPK
QGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQYLQRQERLRLKQ
MQEEFQEHEAQLLSRAKPED--RESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALP-
----EPKKCPI------CRQAITRVIPLYN------------------------S
>Mulan_NP_078820
MESGGRPSLCQFILL---------------------------GTTSVVTAALYSVYRQKA
RVSQELKGAKKVHL--------------------------GEDLKSILSEAPGKCVPYAV
IEGAVRSVKETLNSQFV-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------ENCKGVIQRLTL---------------QEH
KMVWNRTTHLWNDCSKIIHQRTNT--------VPFDLVPHEDGV----D-----VAVRVL
KPLDS-VDLGLETVYEKFHPSI------------QSFTDVIGHYISGERPKGIQETEEML
KVGATLTGVGELVLDNN-SVRLQPPKQGMQ----YYLSSQDFDSLLQRQESSV--RLWKV
LALVFGFATCATLFFI--LRKQYLQRQERLRLKQMQEEFQEHEAQLLSRAKPEDR-----
-----------------ESLKSACVVCLSSFKSCVFLE----------------------
--------------------------CGHVCS----------------CTECYRALP---
---------EP--------KKCPICRQAITRVIPL-------------------------
--------------YNS
>gnl|BL_ORD_ID|2307 @Rubrobacter_xylanophilus_DSM_9941@ gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
----------VGTVVF--------------------------------------------
----------------------------------------------------------LL
VGVVLCV----------------------------------------AGGVLLYFR----
------------------RRMLGKA-----------------------------------
------------------------------------------------------------
------------------------------------------ELMRRTRTS---GAAGVS
AL---SPGTLVE---VKGTLRCERPLQSEMAKERCAYYSSKVVREYLERDRGDGAPGSGR
RSEVLARSERFAPFV---------------------VEDDTGGVPVSA------EGAEV-
-----------DAKKVVDRFERGAGAAGLSVTIGGATIDLGGGERTLGYRHTEEILPVDA
------------------------------------------------------------
----------------------------------------------------PVYVLGAV
RRDG---------------------------------------------------GIGPP
EEGAGR---------------------------------FVVSWRSEEALGE--------
-------------------------------------------------SLGRGARLLGL
IALGLFLAGAAFLAVGAAAALGYLQFR---------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|5 @Rubrobacter_xylanophilus_DSM_9941@ gi|108802862|ref|YP_642799.1| DNA gyrase subunit A [Rubrobacter xylanophilus DSM 9941]
MLDTFSGNIQPHSIEDEIRSSFLSYAMSVIVSRALPDVRDGLKPVHRRVLYAMHDLGLQP
NRPYRKSATVVGEVIG-KYHPHGDAAVYDTLVRLAQDFSMRHPLVDGQGNFGSVDGDPAA
AMRYTEARLTRIATEMLRDINADTVNFVPNFDESQREPEVLPA---RFPNLLVNGADGIA
VGMATKIPPHNLGEVIDATVALIEDPELDDEGLARYIKG----PDFPTGGIVVGTR----
-GIREAIRTGRGSVRVR-AKAHTEQ---------------------IKGNRTQI----VV
TE--LPYQVNKAQLLQKIAELVKDRKISDIADLRDESDRGGMRIVIELKREAVP--KVVL
NNLFKHTQMQQSFGVNLVALVDGVPKTLSYKEALRHYIAHQFEVVTRRTRHELGRARARA
HI---LEGLLIALSNLDEVVETIRR--SRNVETARRNLVKRFRLSE------------RQ
AQAILDLRLQRLTALERRKVEQDHRDLVEKIEYLEGVLADESKV----YGIIREELLEI-
------------------KAAY-------------------ADERRTAITAQEG-AEFEV
EDLIAEEEMVISISHEGYLKSVPIGSFRKQGRGGVGVAGMELKEGDYIEHLFITTTHHYM
LFFTNRGKVYRLKVHQLPRMGRAAKGRHVANLLPLAPGERIAAVISTRDFDEAEYLLFAT
RRGMVKKTPFRDYNTPLKNEGIIAIKLAGGDELIAVRHASDEDEVVFVTRDGKGLRF---
RQGDVRPMGRATAGVKGITLKGDDALLSMDVVSDEAADLFMVTEKGFGKRTAISEFRPQG
RGGQGVIAMKVNGERGKIAGVQVVRPGLHELVIVSNMGTTIRIDSDSVPRQGRAAQGVRV
MNLREGDSVSALAKVVSSRGEPGEPDELALDGITEEEAERSATGSRPAPAANGGRKR---
-------------------------------------------------G
>gnl|BL_ORD_ID|820 @Rubrobacter_xylanophilus_DSM_9941@ gi|108803677|ref|YP_643614.1| aspartyl/glutamyl-tRNA amidotransferase subunit B [Rubrobacter xylanophilus DSM 9941]
M---------SH------RHGF-------------PEKRE----VH-------GGLELKD
RKAYQ-------AVIGLEFHVH---------------LSTRTKMFCG------------C
RVTYGEPPNTHVCPVCL------------------GHPGALPVANERAVEL------GVM
AGLA-----------LNCRVA----------GRAVFARKNYFYPDLPKGYQISQYEEPIC
TGGHIDVPTSEGTVRVRIRRLHLEEDTAKNVHVGESGRMHGSVGSLIDFNRSGVPLMEIV
TEPDIPSPEAARQTAVRLREILQAVGASE-ADMEKGQMRCEANVSLR-NPDGTPGTRTEL
KNINSFRFMERGLVRELRRQREVLESGGRVEQATIHYDPVADEVHELRSKE---FAEDYR
YF---PEPDLLPLQLSPAWVEELRRRLPELPEQTRRRFVEQYGLSE------------AD
A-AVLAAERELAAFYERVASEADPRQAANWISGDLRALLNEAQVGISGSKVRPEHLVELI
RLVQEGTISRSAAKTVLGRVFE-------------------SGERPSRVVEREGLAQMGA
DELGGIVDEVISSNPE--------------------------------------------
---------------------------------------------------EAE------
-------------------------------------------------------RV---
RNGDQKVVG------------------------------FLIG-----------------
---------------------QVMR-----------------------------------
----------------ATRGQ-----------------------------ADGGRVRQL-
-------------------------------------------ILERLGS
>Mulan_NP_078820
M-----------------------------------------------------------
----------------------ESGGRPSLCQFILLGTT---------------SVVTAA
LYSVYRQKARVSQELK-------------------------------------GAKKVHL
----------GEDLKSILSEAPGKCVPYAVIEG-----AVRSVKETLNSQFVENCKGVIQ
RLTLQEHKMVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDVA-V--RVLKPLDSVD
LGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQET------EEMLKVGATL--------
----------------------------------TGVGE---------------------
------------------------------------------------------------
--------------------LVLDNNSVRLQPPK---------QGMQYYLSSQDFDSLLQ
RQESSVRLWKVLALVFGFATCATLFFILRKQ-------------------YLQRQERLRL
KQMQEEFQEHEAQLLSRAKPED-RESLKSACVVCLSSFKSCVFLECGHVCSCT-------
-----------------------------ECYRALPEPKKCPICRQAITRVIPL------
----------------------------------------------YNS
>gnl|BL_ORD_ID|2252 Streptomyces_avermitilis_MA_4680 gi|29828788|ref|NP_823422.1| ABC transporter ATP-binding protein [Streptomyces avermitilis MA-4680]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------VHVSATPVL-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------ALRGVSKR-----------------------------------
----------FGAVQALTDVELEIHAGEVVALV---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GDNGAGKSTLVKTIA---------------------------------------------
-------------------------------------GVHPIDEGVIEWDGKAVQIN-KP
HDAQNLGIA--------------TVYQDL--ALCDNIDVVGNLYLGRELRKRGI------
--------------LDEVEMERRSRELLTTLSI---------------------------
---------RIPSVRIPIASLSGGQ-------------RQTV------------AIARSM
LGEPKLVILDEPTAAL-------GVEQTAQVLDLVERLRERGHA----------------
------------------------------------------------------------
-VILISHNMADVKAVADKVAVLRLGRNNGVF---EVKSTSQEEIISAITGATDNAVTRRA
ARNGEAQK----------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|994 @Sulfurimonas_denitrificans_DSM_1251@ gi|78777197|ref|YP_393512.1| hypothetical protein Suden_0999 [Sulfurimonas denitrificans DSM 1251]
MKKILLLAITLSSLLFAQTENETCKKCH--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
PDIVNEFEGSMHRNATYYDDEIHKAVWDMHPSRDSGKYSCAECHAPNAKDEKEVAQGITC
VSCHTIKDVEEHAGANKNVYSKDKKTFYSAEAGRENEKVIYKQESSWLGMNKTTVGSPYH
DID------------YTNEKYYNGQMCMGCH----SHRQNSSEFMICETGKDGA-QNKEE
NCITCHMPKVEGTATTIRQSQK-HAYHGFAGAHKKPELLSQYVEIELGKKSNGFDVFVTN
KAPHDLMLHPLRVTELRVKIISEKESKSLQTFTF--VKVIGNESGPSMPWLANQVVVDTM
LKGNEKR-----------------------------------------------------
-----------------------------------------------------------A
IPYTEVLKKGDKV-----------------------------------------------
-----------------------------------------------------------E
VELG--YYLVN-------------------------------------------------
------------------------------------------------------------
--------PKALK----KLNLEGNKKAEKFTVLKQK------------------------
----------------------------------------------SFIAE---------
------------------------------------------------------------
------------------------------------------------------------
----
>gnl|BL_ORD_ID|37 @Sulfurimonas_denitrificans_DSM_1251@ gi|78776239|ref|YP_392554.1| succinate dehydrogenase/fumarate reductase iron-sulfur protein [Sulfurimonas denitrificans DSM 1251]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------KINIKRESLHVEYDVSLQGVTL--LEVLN-------------------
------------------------------------------------------------
------------------------------------------------------------
----EIKYKLDAT-----------------------------------------------
----------------------------------------------------------LT
FNSGCRSSVCG-------------------------------------------------
------------------------------------------------------------
--------SCALRVNG-REVLACSYKAEDGDVVEPLLNSPIERDLVVNMDKAYSF-----
------------------NAKAKAWQSSFAQH---VKLTDEDEMRNALQSDCILCGSCYS
ACPVYEVNKEFLGPFSLTRVWRYVSDK-------------------------REENPKGK
IDNIQINGVWDCTLCNACTLVCPQGISSKADIEKLRARSVMFGYSDSSFANFGGGFSFDG
TPSF
>gnl|BL_ORD_ID|2206 @Syntrophomonas_wolfei_Goettingen@ gi|28212040|ref|NP_782984.1| diaminopimelate decarboxylase [Clostridium tetani E88]
MRLFGTMEVKDNNLYIGGVSCKELKNKYSTPLYIIDEDFLRGRCKEYYNNFGVEKHGNKV
AYAGKSFLTIAMCQIIKEEGLFLDVVSSGELYTALKANFPMN-------KIYFHGNNKTL
DEIEMG--IELGVGKFVVDNFYEMNNINNMARKKGIKQSIL---LRITPGIEAHTHDYIK
TGQVDSKFGFSMVGEEVYKAVETALSLPNINLSGIHCHIGSQIFETTPYEEAVDIMFEIL
KEIKNRYDYEISEVDLGGGFGIYYTKEDKPKETKEYCEAILKKALNKSKELGIKLPMLGI
EPGRSIIGNA----ATLIYTIGAIKEIP---GIRKYVS---IDGGM---NNNIRPALYDA
--------------------------------------KYECEVANNMNSD-DRELVTIA
GKCCETGDIVIEDVEISKSK-----------------------------------SGDIL
AIPSVGAYGYSM-------------SSNYNK-----------------------------
--IPK-------------------------------------------------------
-PAIV-LVKDGESRVMCKRESFDDMLKNELSL
>gnl|BL_ORD_ID|345 @Thermosipho_melanesiensis_BI429@ gi|150020259|ref|YP_001305613.1| hypothetical protein Tmel_0358 [Thermosipho melanesiensis BI429]
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------ILYQMNIFFNFFIEE------------------
------------------------------------------------------------
-------------------------------NLSKKTIGSLLGISPDRVRLW--------
------------------------------------------------IKNYLLYGEAEC
KRGKPKKESFEEEMERLRAEEEGNSKKIEVINELKERFSL--------------------
---ELLCKISGISKSTYYRAMKRKDKDNLKKK----------------------------
-TKIYTSNAKGYTNIE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------EERLKI
>gnl|BL_ORD_ID|211 @Thermosipho_melanesiensis_BI429@ gi|150020125|ref|YP_001305479.1| hypothetical protein Tmel_0220 [Thermosipho melanesiensis BI429]
M--------------------------------------KEKNKIVIGIILSILISGVVL
FFYSFSL-----------------------------------------------------
--------------------NKNIINSIFFSLN---------YEKFIVAIILV-------
-------------TLSFVFDGVKHFIVFRILDQKIGIFPSINSCFVTGYFSSVTPFSVGG
QPFQI-------------------------YYLNKKGVDSAYATQVVLLRLFEMISLMFF
IDLSYIIFFSHNITGISQNIIFLGLILTFLSSIVILLGIAFPKTIGKLLRVLKKVKILSK
IVNFD------------------------KIEHWFHK-----------------------
--LDIVIKK-----------IFREHKWLI----------------FIDFIMMFILLIFQS
YVFYYSIKIFTNINIP--------------------FFKFFSIVNIVNAVAFLVPTPGAS
GSFEIIYTNVFSSFSPNKEAIIKGVLFYRFLSYYLLI-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----IFGTIILLPFAFKKDKV
>gnl|BL_ORD_ID|327 @Thermotoga_maritima_MSB8@ gi|15643101|ref|NP_228144.1| dihydroorotate dehydrogenase [Thermotoga maritima MSB8]
MLELK-------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------PPLVLLSG
PAGFGEYLKLMDHRYVGGVLLKTVTLHPKEGNPTPR----------------MADSDFYV
INRIGLENPGIHAFVENIPELPVPMIASLGGDSFEEY-----------------------
---------------------------------------------------------LEV
ARVFKKVADRFYAVEFNFSCP----NVKEGGLSIVKNAEEWKKLLNTLRKELPDSFLI--
----AKVGVEGIFVEDAAEFVM---------KTGWDGITLV--NTVRGLHFEKDTMILG-
-------GLSGPVLKP-----IALRAVYEVKKRFPELFVIASGGVYS-------------
-VKDAEEFLKVGADVIGVGSALFKDPGV--------------------------------
------------------------------------------------------------
------VEEIGKY-----------------------------------------------
------------------------------------------------------------
-------------------------------------LLE--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------VKR
>gnl|BL_ORD_ID|1124 @Thermus_thermophilus_HB27@ gi|46199433|ref|YP_005100.1| hypothetical protein TTC1131 [Thermus thermophilus HB27]
MVIASPWRRLVASLVDSLVLL---------------PLSLLLMALAGVDPLGPTTWVQDL
LFQ-WIPG---------------------------------------------------W
--------------------------TYYTAFTALYGATPGKMALGLKVVRTDERPVDWL
TAFMREV-------------------------------VGKTLSTL--------------
---------------------PLGLGY----------------------------LW---
-----------AFF----------------------------------------------
-----------------------------HPRRQAWHDLIADTLVVRASRPG
>Mulan_NP_078820
M-----------------------------------------------------------
------------------------------------------------------------
-----------------ESGGRPSLCQFILLGTTSVVTA-----ALYSVY--RQKARVSQ
ELKGAKKV--------------------------HLGEDLKSILSEAPGKCVPYAVIEGA
VRSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQRTNTVPFDLVP-
------HEDGVDVAVRVLKPLDSVD-------LGLETVYEKFHPSIQSFTDVIGHYISGE
RPKGIQETEEMLKV--GATLTGVG--------ELVLDNNSVRLQPPKQGMQYYL------
------------------------------------------------------------
--------------SSQDFDSLLQRQESSVRLWKVLALV---------------------
--FGFAT----CATLFF------------------------ILRKQYLQRQERLRLKQMQ
EEFQEHEAQLLSRAKPEDRESLKSACVVCL------------------------------
------------------------------SSFKSCVFLECGHVCS---CTECYRALPEP
KKCPICRQAITRVIPLYNS-----------------------------
>gnl|BL_ORD_ID|11 @Treponema_pallidum_DAL_1@ gi|378974645|ref|YP_005223253.1| lon1 gene product [Treponema pallidum subsp. pallidum DAL-1]
MLGN--------LMLGPYCRSSLWRELSWQEVTGIVAPDTIAYLKARAQDHPFLLAHERA
CAAIRLGMRMYGDGYNICVIGASGTGKRTTLQYLLKDFVPRPEQMWDIAYAYNFVHPHEP
QVLQFPAGEGMPFAT--ALRRSVNAILNTAQDIVKSDAFLRERRTLLADIETRECAELSR
IEAELYTRGFRVRWHRKRGTYSFDLVPLLKGKDSSFEALHDLASRAKLSRCVVHELHARY
RLSCDEVSSLLHTLR----------------------------TARRAARRRLAQYYRAR
LRLIILEQMACIKKRV-ACYAPVFSPPPVSCAA-----EQTEREKTSSSRLIEVPHEFEE
MRARIISYI--ERIQTDVQVRVQCLMSMRISALVKKRFFDRYTLNFVCVHTEHAGYVFTE
HQPNLANLCGSIESKGNEGDTLENGHLRIRAGALHRAHAGVLIVQLEDLLAEEEAWTHLK
RALRTKQVLLPAGSSQSQGMLRPEGVPLTCKLVLVGEPCSFERLSQEDSSFRELFKVCAE
FDTSMPNSDKNQVALIAYLDRVVARYGTFSLDSSAYARLLAYAEELAESHTRLSTSFVQI
ADLVLESHAVAVDMHPDVSVITAHVVQEALNRRQYVCSRARERFQRMIACGELLVEVQGY
RIGRINALAIEEHCGHSFGIVISLTAQASAGKEGVMNIEREAGLSGEIYDKAHLIITSLL
REKCLSAFADAAFDPAVDDLGKGQDSFPLCLSAALCFEQSYHGIDGDSASAAEFLVLLSA
IGRFPLRQDRAITGSVNQLGQVQAIGGVSEKISGFYDVCALNGLTGMQGVLIPKSSCAQL
FLPERVQDAVRAGTFHVWAVCTIDDALELMVPDDLKEQGSAQLYQCVRARLRDFYVTVKG
HCE
