>gnl|BL_ORD_ID|2134 @Cyanidioschyzon_merolae@_gnl|CMER|CML314C similar to RING zinc finger protein
---------------------MGNVNSQADVHVAQRFGDGPGNDAPEARVLGPRPVPAVE
TSPGNLVPQPGAVDGLPPTGTVSWQRPGGDVNQGSSSGLRWLQGGAERSTQPVPTMVHAY
TIKNDLNVR---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------KKSVRLVRDPENP-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------QQFL
LEFVFDATCSGLCTVF--------------------------------------------
------------------------------------------------------------
----------------------------------FMAKDLTNRTTRVEQFHVEPLEPVPP
VPTPFEAGMGQRYRQNSHRGFVPSRYR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ESF
LFEQNPAKLAKHRYPIVILLQRLESAEDLAK-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------SGHRQVQQSAGRSTDTDPNGGSL--------------
------------------------------------------------------------
--------------------------VRFQATYVTLCMPPKGLELAD-------------
-------------------------EIPVKVVQQKILVDGTIYELQEIYGIEERMASADD
SDAAAAEAEHDDLCIIC-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-MTDPRDTTVLP------------------------------------------------
-------------CRHLCLCVDCAQLLRVRSD----------------------------
--------------------------------------------RCP-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------ICR----
------------------------------------------------------------
---------------------------------------------SPVDSLLHIRNLRAN
AR----------------------------------------------------------
-------------------------------------------
>gnl|BL_ORD_ID|4519 @Cyanidioschyzon_merolae@_gnl|CMER|CMT012C similar to C3HC4 zinc-binding integral peroxisomal membrane protein PEX10
------------------------------------------------------------
----------------------------------MAT--------LTRASVRVPVAQQAE
VLRASEK-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------DKQVRNELARALQNIWQGGS
IVLGRFLHIQR---------------LNQRWSRAQRAPSRVPLSTGQAQG----------
------------TSRSSTLGSLQQP-----------------------------------
--------------------------------------------WEPLGAPPTAFRFLS-
--------------------------------DLVFYWSTVGIGRQTPGEEFCDLFECTI
ATGDRIQVATLSWKQRLLETLLYATIDSFQLLLYWLRVALRRVARFLERDWYSQCLLSRE
RRCRVASTLRFVDT----------------------------------------------
------------------------------------------------------------
----------------------------CCARLQLLQSSDRHALALTIQ-----------
-----------------------------------------------------------W
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------LMRVHLALFYLYGRYYDPAKRLAG-----------------------------
--------------------------------------VRLVHIGRSRAYSPRY------
--DALGLLLIVQLVLEPIDVLMQRPAWKRKLRVLFKWALELFRKMYASVSTSKRIAGDGV
SQARPQM-----------------------------------------------------
-----------------------VTAVHTTDRFSGEETGLPGSRTTDQQRSWS-------
-------------------------------VVSPKFEPVPTARR---------------
--------------------------ARNESRHRCVLCLDQ-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-CQDPTCTA---------------------------------------------------
-------------CGHV-FCWICILDWVRQQN----------------------------
--------------------------------------------SCP-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------VCRREAQ
LNDLRCLYSLG-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>gnl|BL_ORD_ID|1686 @Cyanidioschyzon_merolae@_gnl|CMER|CMK039C photoregulatory zinc-finger protein COP1
----------------------------------MEGGSPAVGRAGSLADAPTSSDPAPT
ASANDRSNTADPQQPSTSSPLVNAADPGAKNVALVEQ--------TEPATPTASTGNE--
--------------------------------------------------QHRTT-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------QPAPRQF--
------------------------------------------------------------
---------------SPAQRCNHNQVKRLGPALKSL----ECPICFDLFRAAVTTRCGHT
FCFSCIMRHFRNHKSCPVCGGFLT--RDQIA----------PDSSVQKAVRLAQAASPSL
LTRSKTSSRVDDVRSSTLVSDEEKPQRKAQRTGTLDTQEECVAESDGE------------
--------------------------------------------FK-------SEAAAAF
AALMSQQSGHAGRPRQALFAAGSTHAPREQRQEIAPAASDDQHRASSRERPILSKQDP--
--------------------------------------IIEQILSDLERE------TQKG
QESNFVDKLKRIASRL--------------------------------------------
-----------------------------------SGSEIDQI-----------------
------------------------------VETLLEQRRRLQRMSLGTDYTILKSFLEYN
IELKRR------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ELA
KIEAELLQLEADLQRANELQQRRAESMKDSG-----------------------------
-----------------------------------------------ERGAPEA------
------------------------------------------------------------
------------------------------------------------------------
--------------AEKRVQRMLILFEQLQQRYLE--LRPPNLKESSPQPAGMDRDNQQS
H-----------------------------------------ATR---------------
--------------------------ARPYDLGPSPLA----------------------
-----------------------LSSV-------------TAQSSGHLPTDITEV-----
DADPLEQFAHELCTATKYAQM------------------RCLTLLRYGEPFRGSNIVSCL
DFDMFGELLAAA-------------GVMRKIKIFDLHTVVDHDAQVKYPI----------
------------------------------------------------------------
-CELPARAKLSCLSWSPSTRQHIASSD---------------------------------
-------------YDGV-VCIWDTESCKLVAE----------------------------
--------------------------------YEEHEKRAWTVDYCP-------------
---------------------------------MKPHILASGSDDGNVKIWSTT--QRDS
VGTIRMNANV-----CCIKFAPLQHECLLAVGSADHQ------AYVYDLRSMAQPLHI--
----LKGHRKAISYIRFF-------CSNREIVTASTDSTLRLWDLRSC----QCERIYTG
HCNERNFVGLSVKPDWIACGSEDNHVYTYYRSLTSPAIVSDFAAEPAQHSAEVV------
--ARSGGALDV------AGAPGSRFLQPDSGTFGGPHFVSAVAWRKDTDTLAAANSQGL-
------------------------------------------------------------
------------------IRIFELS------------------
>gnl|BL_ORD_ID|3721 @Cyanidioschyzon_merolae@_gnl|CMER|CMR259C probable DNA repair protein RAD5
MDRMQTQIGNRHA---------------STPFQSQVGAASSARKRYRGGEAQRRPNSQAS
HETGAKSRQQH----------------------AAER--------AYSPS---ATSWEAK
TGRLSD--------------------------------------------GVGSS-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------RRTPAVGREVFDSPTPESE--
------------------------------------------------------------
------PASSCASPQDPVE------------DMDSL----EPWIQ-KQLVA---------
--------------------------LRAEH----------GGGTTRWPKYLGSILVP--
------------VRATAT------------------------------------------
--------------------------------------------LEPMAVTSGAELVLKV
SPIMSNGTGSLGR---------HNRNRQRQRLRFAVRVCTAEHGREFGRLEPLEALDLPT
CLGALQSANLIIARARAVDCPLHIRFACVFIAEVAIFAAKSMFSFAAPGE------RSGR
RPAGFDADQEDALTHW--------------------------------------------
------------------------------------------------------------
--IAQLFHSLTGSGTDTNETTALSSDTITHTKARIEAPGERGSASVTKCLRTEAFRPEDA
VQWILAAAENVHVDAPPVP----------------------VPPLLASTLRPYQQSALNW
------------------------------------------------------------
-------------------------------MVARERAPSHTPSSDDTQQTWREQRLPDG
TRYFQHRVSGRVSLQPPMTSPAVAGGILADEMGLGKTVEAISLM-----LANPRPPQEQT
RLDRQAALFTKHPERVTTESHRENESDTKAGGRRAANAAAAAQTRRSLVDSCCGGTLIVC
PMS----------------ILSQWCAELNTHVADDADFIVHIYYANDRETDPLV------
-----------------------------------------LARFQVVITTYGTLYSTWK
STQQTES-----------------------------------------------------
--------------AEARGLYALRWHRLILDEA--HVIKNPSSGCSRAVL----------
------------------------------------------DLRSRYRWALTGTPLQNN
LEDIYPLLRFLAVEPWSDASLWKRYIARPFE-----------------------SGQAAK
MQAALSLLSSILQPLMLRRTKRTLDEH-------------TGAPILELPAKQTEVV--YV
DLSAAERQLYDAVYKASRARF---------------------------STFLADNQITFY
LTTVFEMLMRIRQLCDHP-------LLIMSCPARDLHILQDVQKFMQRLTEGRGSDQATT
YLETLAGQLQQSLHDERS------------------------------------------
-IESSTNTKPLCPICLESIDDAVALRN---------------------------------
-------------CAHV-FCRDCILTLLLSNR----------------------------
----------------------------------------HGNAQCP-------------
------------VCRKGCSFADVMSTPRRSRFRVDLE-----------RGF---------
--------------FLSTKLARLVNDLVEAVQAFERDPVRHGKCVV-----FSQWTGM--
----LDLIERA----------------------------LQAWNHEHARTLFQVGRLDGT
LSQSRRTAVL------------------EAFATMNPSTSA--------------------
--ATATGRMNVLLASLRAGGVGLNLTAASSVFLVDPWWNPYVEEQAMDRVHRMGQTRTVQ
IRRYIVRDSV----------------------------------------EERMLLLQDK
KRSMVEDALGSSGTENQSSRLADLLLLFSLDAGGATGSRSKRL
>gnl|BL_ORD_ID|648 @Cyanidioschyzon_merolae@_gnl|CMER|CME171C similar to ring finger protein
-------------------------MAESGQ-------------------VNRSPTDAV-
--------------------------PLTGDTRAPVH--------SPDDT-----GFEAS
--------------------------------------------------AHGTS-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ELSKS------------------LDAEA----------TDAAAKR---------P--
------------AAASSVASSSEQP-----------------------------------
--------------------------------------------FD--------------
-------------------------------------------------CSI--------
------------------------------------------------------------
--C-FEVPLEDPVVTM--------------------------------------------
-----------------------------------CGH----------------------
--------------------------LFC-------------------------------
-----------------------------------------------------------W
-------------------------------SC---------------------------
-------------LH-----------------------------------RW--------
------------------------------------------------------------
-----------------MAQH---------------------------------ATCPVC
KSL-----------------------V------------------DRERVIPLYGR----
------------------------------------------------------------
GRTREDV-----------------------------------------------------
--------------SDAPKQQT-KVAR-------------PNE-----------------
-------------------------------AIPPRP-----AAR---------------
-----------RVEPPPQTANGALPPLRPGA-----------------------------
---------------------EHLSDWNVGVGAGSFMPYGTAGGISFTP------FGLF-
------------------------------------------------PSI---------
----FG------------------------------------------------------
------------------------------------------------------------
-VQF--------------------------------------------------------
------------------------------------------------------------
--------------------------------------------TFP-------------
-----------------------------------PQ-----------P-----------
--PTGAPSAT--------------------------------------------------
----------------------------------------------SS----TAAR----
-------------------------------------VNPGDS-----------------
--GAYGG--------------------------------------VPVSVQTEDATQAMV
SR---------------------------------------------------MLLM---
-----------------------LGMFVIMCLLLF--------
>gnl|BL_ORD_ID|3382 @Cyanidioschyzon_merolae@_gnl|CMER|CMQ255C CAD complex (carbamoyl-phosphate synthase II / aspartate carbamoyltransferase catalytic chain / dihydroorotase)
---MTTIQGDASYGAQDLELQVPGLLTDAGKRRSRLELADGSVFEGWSFGAARSVAGEVV
FQTGMVGYEQTLSDPSYCQQIIVFTYPLVGNYGVPSM--------SERDAYGLPLHFEAA
RIHAAGLVVLNYEQEYSHWLAKQSLGEWLQEQQVPGICGIDTRLVTQKIREHGSMLGRIV
LEDDRNEDQAFIDPNRLNLVAQVSCKQPYEYGAPDARYHVLAVDCGLKYNQLRCLARRHC
RMTVVPWDEDINADKYRSCDGLFISNGPGDPTMVLETIRNIQQWLSEERPVFGICLGHQL
LALAAGAQTYKLKYGNRGHNQPCIDERTGRCYITSQNHGYAVDTNSLAPGWEPYFTNAND
GSNEGIIHRKKPAFSVQFHPEARAGPCDTEFLFDLFVEMMRTK--------QPPPAPQRL
AATGACPASDKSIRKVLVLGSGGLSIGQAGEFDYSGSQAIKALKQEGIYSVLINPNIATV
QTTGGLADKVYFLPIDPES------------VMRIA----ENERP-DGIFLQFGGQTALN
CGIELQKRNFFQENGIRVLGTPVETIMDTED----------RELFNKR---LAEIGEP--
------------FARSATAASVEQAITEAERIGYPVIVRAAFALGGLGSGFANNAQELRQ
LASKALSCSPQLLVERSMKGWKEIEYEVVRDAYDNCITVCNMENFDPLGVHTGESIVVAP
SQTLSDAEYQMLR---------NS------------AIKTVRHLGVVGECNIQFALNPNS
REYCIIEVNARLSRSSALASKATGYPLAFVAAKLALGRALPAIRNSITQE------TTA-
--C-FEPSLDYIVVKMPRWDLKKFERVNRQLGSSMKSVGEAMAIGRNFEETIQKAIRMVR
DYYVNGFERDVEPYSDEEMQTPTEARILAIASGLASGHSVEEIHEKSQIDRWFLMRLARI
TRFEQTLERLAANAMNTGSENWLTADLLCAAKQLGFSDRQIGRLVGNTELEIRKLRKEYG
IVPNIKQIDTVAAEFPAKTNYLYATYAGSQGAHDVSARFGGIIVLGSGAYRIGSSVEFDW
CAVAAVRALRAKGTRTIMMNYNPETVSTDYDECDRLYFEELSFERVLDICEREAVDGVIV
SMGGQIPNNIAMSLHRQGVHVLGTSPEMIDSAENRYKFSRMLDRIGVDQPRWKELTSIAD
AAAFCDSVGYPCLVRPSYVLSGAAMNVAYKEEDLERYLSEAARVSREHPVVISKFILEAK
EIDVDAVARNGELVVHFISEHVENAGVHSGD---ATLVLPAQDLEPETVRKLEDATRKIA
NALNVSGPMNLQFIAKNNEIKVIECNI------------------RASRSFPFVSKTIGL
DLAKMATKVMLGLTVQPYPVDISTVPHVGVKVAMFSFARLLGADPILGVEMASTGEVACF
GESREEAYLKGLRAAGIRLPQRNICLSIGSYKEKLEFLESAKKLAAIGYRLYATPGTADF
LVEHNVPCTLVVWPSDEYQQGTLDVTRLIQDKMIDFFINLPSQNKLRRVATFMSNGYISR
RTAVDFSIPLLTNIKCAKLLVRALARYGRGVSLPLQPYDVRFSARVITLPGLVNMCTSRL
EHEPFAAPNGDRCDPESPLMNGDQHPKRNAAADARLCAL-----LDDFDRQLLRGGYVAW
VGAAVAPDFLVAESETLRTVREQLARW--GRCDHAIYAYATAANAATLPSLANEVAGLFI
ALDNTEPMIHRRAAASAAATNAVSADQAPLRENLTPWLRHLELWPRHKPVILHTSSTQAL
SAMLFGAVLYARPIHIHAVRRREDIALIRSAKERGIPVTCDVR-----------------
-VEDLCGDALQHELEQRDVDALWDALDAIDTVTGSPRLVLGLLLEAVHRGRLTMTWLLSR
LVEFPRSFLGLAPAGSSAHADTYVEVDIDQTERFVPADGDSNEKAYQLRGRVLRVVVRKR
IAYLDDKVLLEAGAGHD-LLESATETATATAEDTVVGAVPAQPALPSAPDVRNARAASSV
RPSFRPATLPVESAVAAVTTDDSTADIDRARAAVEQRARQLDMVNFPRVSVANRSWMPST
KANRSTLLEPRPLDSFSCAPVDVPLVRRSWQA-ASPQ-----------PGWPHY--QTSL
PAPVSVPAGS------SAQRDLLRHQSILSVSQFSRAELHALFGVAQEMRQMVNRMGM--
----LDLLRGRVLALVFYEPSTRTSCSFAAAMQRLGGTVIQMNDLQSS----SVAKGESL
LDTVRTMASYADAVVLRHPEAGAAERAAQALP-KTPLINAGDGTGEHPTQALLDVFTIRE
ELGTVNGLVITFVGDLRNGRTVHSLARLLALYQVRINYVSPRELRMPSQVLEEVATRGIE
QREYTNLEDCLAETDVLYMTRLQRERFADPGDYERFNAFYVITPRTLTRAKDTMIVMHPL
PRVNEIAPEVDSDPRAVYFRQMEYGMYVRMALLSMVLGRS---
>gnl|BL_ORD_ID|4729 @Cyanidioschyzon_merolae@_gnl|CMER|CMT287C unknown zinc-finger protein
-----MKYGHRLRAFYEVFGAADQVGPDGTAPDARERPAPGTAPKSRTSDWHRQVEPEVV
CD-------------------------------VAEN--------AGRDS---SAGYETS
ASSGAGG-------------------------------------------GRGSS-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------QRSL--------SPVPAED--
----------------------------------------------------------TT
SEADPLPDAAVMGPRAPAS------------QLPDL----RSELG-DRYRALYAMYKAGK
AAVRCIRAT-----------------MDEHAPRAHHRTSVPPEALGRRSRYLKLLGNN--
------------LQLSRIPSDLEQV-----------------------------------
--------------------------------------------FD--------------
------------------------------------------------------------
--------------------------------------AVWVFFDSIIRE------IGAF
RRV-FEERTADLQCRL---------DVLRQQGASS-------------------------
----------------------------SVRGALELGAEAEQV-----------------
--------------------------LVC---------------LQIAQVAIGKILKKFT
KALALIASDEAAARG--------------------------------------------W
------------------------------------------------------------
--------------H-----------------------------------GW--------
---------------------------------------------------------DVA
DVREDALEGAGQ-------SESEQSSTTTTS---ATPAGSGGRSDADGVDKRRGGTRGVG
NAA----PNAIQDAKLERAVRLAMCGSLSSALALD----------PSEEAPPLV------
----LVTRLRRFLVQQPFVCDQRRLGFLADLRHRKDCAVLALHRILESLTPAATGDDAAL
GGAPTGQ----LHTAAACAPGRGVD-----------------------------------
--------------GDQRTLGALTLLRHVLDDVPP-----PGEYSLHAPSAHLP------
-------------------------------ALPP-------GGR---------------
--------------------------VRPFAEECRLLA----------------------
-----------------RQLESQLAAY----------------NPTTDPSSPYEVATRF-
------------YLANVAASG---------------------------PAV---------
TAEAFLRAARSVPMHFLC------------------PICLDML-----------------
-FET--------------------------------------------------------
-VELP-------------------------------------------------------
-------------CRHR-FCEVCIQEARFSAE----------------------------
--------------------------------------LQGATLSCP-------------
------LCQPGLYRRHCCETADTSAVQAARHASASPE-----------ECVSSA--ERDA
LSPADACARTEQRERRASSIDGLLRAAFPAQWRLRERQARATREMLERRRRFRERVAH--
----LDAAKLR-----------------------------------SSGNLESVAR----
-------------KRFHWVCQCFGDRSGRARPVATPPPSAGDAVADVEPAAD--------
--GRRAGLVDARAGVLGDPKPD-----------------------AAAQTQGKPATSVPQ
NRARSACSIA--------------------------------------------------
-------------------------------------------
>gnl|BL_ORD_ID|4703 @Cyanidioschyzon_merolae@_gnl|CMER|CMT259C hypothetical protein
-----MKYGHRLRAFYEVFGAADQVGPDGTAPDARERPAPGTAPKSRASDWHRQVEPEVV
CD-------------------------------VAEN--------AGRDS---SAGYETS
ASSGAGG-------------------------------------------GRGSS-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------QRSL--------SPVPAED--
----------------------------------------------------------TT
PEADPLPDAAVMGPRAPAS------------QLPDL----RSELG-DRYRALYAMYKAGK
AAVRCIRAT-----------------MDEHAPRAHHRTSVPPEALGRRSRYLKLLGNN--
------------LQLSRIPSDLEQV-----------------------------------
--------------------------------------------FD--------------
------------------------------------------------------------
--------------------------------------AVWVFFDSIIRE------IGAF
RRV-FEERTADLQCRL---------DVLRQQGASS-------------------------
----------------------------SVRGALELGAEAEQV-----------------
--------------------------LVC---------------LQIAQVAIGKILKKFT
KALALIASDEAAARG--------------------------------------------W
------------------------------------------------------------
--------------H-----------------------------------GW--------
---------------------------------------------------------DVA
DVREDALEGAGQ-------SESEQSSTTTTS---ATPAGSGGRSDADGVDKRRGGTRGVG
NAA----PNAIQDAKLERAVRLAMCGSLSSALALD----------PSEEAPPLV------
----LVTRLRRFLVQQPFVCDQRRLGFLADLRHRKDCAVLALHRILESLTPAATGDDAAL
GGAPTGQ----LHTAAACAPGRGVD-----------------------------------
--------------GDQRTLGALTLLRHVLDDVPP-----PGEYSLHAPSAHLP------
-------------------------------ALPP-------GGR---------------
--------------------------VRPFAEECRLLA----------------------
-----------------RQLESQLAAY----------------NPTTDPSSPYEVATRF-
------------YLANVAASG---------------------------PAV---------
TAEAFLRAARSVPMHFLC------------------PICLDML-----------------
-FET--------------------------------------------------------
-VELP-------------------------------------------------------
-------------CRHR-FCEVCIQEARFSAE----------------------------
--------------------------------------LQGATLSCP-------------
------LCQPGLYRRHCCETADTSAVQAARHASASPE-----------ECVSSA--ERDA
LSPADACARTEQRERRASSIDGLLRAAFPAQWRLRERQARATREMLERRRRFRERVAH--
----LDAAKLR-----------------------------------SSGNLESVAR----
-------------KRFHWVCQCFGDRSGRARPVATPPPSAGDAVADVEPAAD--------
--GRRAGLVDARAGVLGDPKPD-----------------------AAAQTQGKPATSVPQ
NRARSACSIA--------------------------------------------------
-------------------------------------------
>gnl|BL_ORD_ID|903 @Cyanidioschyzon_merolae@_gnl|CMER|CMG126C similar to zinc finger protein
------------------------------------------------------------
-------------------------MPKNGLSLGKVE--------AVAASLDVPEGYH--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------WPHE------------AFRSLDVLTRCPICGEHFRAPVLLECGHS
FCSECIRRALVYRSECPQCRA--------------------PASAGQ-------------
------------LRRNRLVQDVTTAWQQAREC----------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------VLTRFSPQEHAG------NTEC
RSSKLEASTESGLT----------------------------------------------
------------------------------------------------------------
------------------------------VRERTEAACPVRAAALTAQVATRGRARSAP
VPPDEHTAAVSAV----------------------------------------------W
------------------------------------------------------------
--------------------------------------------TDRQHQNWDEAGVCCG
NC----------------------------------------------------------
---EESASSAVSMSKRTEPSHRFERSAERAG-----------------AQPPNGGLSGIA
AVP---------------------------------------------QPLPVFQKT---
--------------------------------------------------------DDIY
AEDWSEA-----------------------------------------------------
--------------APTRTPAAL-----------------PGE-----------------
------------------------------------------AAR---------------
-----------AMEP------------RPRN-----------------------------
-------------------------------------------DAESTATSGHASFTRRA
SCERIQQRDHTKY-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-VECPICNRAYPPAFIQVHVNE--------------------------------------
-------------------CLDQLDAVEASG-----------------------------
---------------------------------------------FP-------------
--------------------------EAGSRALAKAT-----------------------
--------NTLEDEYPMRKIPEVWYDGLTE----------------RRLREMIRALGMKA
PPAWLRNRRGLIYLHREYVIRHNAECDVEPVTARKQRRNICREVEELAWFQIESAR----
------------------------------------------------------------
---------------------------------------------RPTRPEAARSSNAT-
------------------------------------------------------------
-------------------------------------------
>gnl|BL_ORD_ID|951 @Cyanidioschyzon_merolae@_gnl|CMER|CMG190C unknown zinc finger protein
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MRST------------------------
-----------------------------------------AKYAAISYCAIGLILGHAW
LTQPNF------YRATAYLYNSKTA-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------RFSAVNAGLVSLYLVGQLVQRLLLGE------LRLV
EAERLHLRARESLVEM--------------------------------------------
------------------------------------------------------------
-----------FLAMTVFSRTDFHARFLC-------------------------------
--------------------------------------------------------MFAW
TFFLKVF-----------------------------------------------------
--------------------------------------------------HW--------
------------------------------------------------------------
------------------------LSQERLG-----------------------------
---------------------------------------------YVEQQVIML------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------SRPRLTHARLVVLFCWLFVTDACMLWHCLHFTST
NGPSIMAMFAFEYAILLIGLLSQIVRYVVFIIDVFVLTEGTWDDKG-LWLFYNELLSLFL
QLAA------------------------------------------------------YL
AFFTYVHLFYSLPLHILR------------------DLAVTARTFRQRLIEF--------
------------------------------------------------------------
-IRYRQVVRSMHTQFPNATEQELAAGD--------------------------RTCIICR
EEMFGGAGAKKLVCGHI-FHLRCLRSWMERSM----------------------------
--------------------------------------------SCP-------------
------------TCRRDIRPLRAPTTSARPTASSGAATHHDDGARRNAPGSLSTRPQRGA
TAPIEAPATAARRVDTSAVPASTQQRMRPSTASADRE-----------------------
-------------------------------ASDPEHLSRNEWNAHSGRPPWTTAR----
----------------------LTEMPPPSSSTSTPAPPP-PSSPPPPPPPPPQLLAVLE
YIAQTAPHADVQCSPLPPTSTPA----------------------QPTRTHTTPASYA--
----------------------------------RPRSATIEDARRLQRQLDDLSSVMRN
LIERLEHELEDRDAEQIERR-----------------------
>gnl|BL_ORD_ID|4175 @Cyanidioschyzon_merolae@_gnl|CMER|CMS362C 9-cis-epoxycarotenoid dioxygenase, neoxanthin cleavage enzyme-like protein
------------------------------------------------------------
----------------------MNLHPGDKTAFVVGNGALRHWKGAS-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------VNATATFQ----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------CGRL
KRRSLRPARSGGATHL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------SSQESGAT
NTVREQGQLTSAPGKTQSLSAFDRRSWELAH-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GDMNEEDSYVLDLPDLPHDLVGTLYRNGPSKFTIG-------------
------------------------------------------SRR---------------
-----------MLHPWEGDGAVAAFTLRGDG----TVWFRNRFVRTEGYLKERRAGYQLY
RGTFATPLPGGIVTNAFRLEQKNLANTNVIYHANQLLALYEGGLPYELRPDTLETKGVFR
LGGT--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-LTGPMPMFTAHPHVDPLRRGRLVGFSSRMHLNGLRIR----------------------
------------------FLEFASENWKLCSERTVDIDGFGFFHDFMITQRYYILLQAPL
RFHPLPFVLGL---------------------------------KCP-------------
-----------------------------------GECITWEGDRMPTRLLLIPRDDPGA
PVREVLSETCTAFHFVNAYDDDDDDAVVLDACRMDRLFLGETRRHRNGLSR---------
-----------------------------------------------------TQRVVEA
VDFGTQVPKCSLWRCRIPTRSGSGTQRATWREVNTTHVDFPVVNPSRLTQPYRYVYMGAS
ALGTEPGPLKNIIKVDADTGQTLATWQPPSVYEFAGEPVFAPRLIEPDKESAEDDGYILS
VVSDGLHRSTYLVILDASDLKLVCKVPLRTFLPMGLHGTWTAQVFQPQPKRRTVQDLFES
KNWNEVDSSLPLFRF----------------------------
>gnl|BL_ORD_ID|737 @Cyanidioschyzon_merolae@_gnl|CMER|CMF094C hypothetical protein, conserved
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MKRVQA------------
L-----------VELGARLAELSGT-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----LEQTLSDVESRYG--KLRTLSDLYS-SGFLLYGFAL--------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------W
WSIFL-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------ASFLVYS-----------------VVPVSRTFRT----CLSFSQK-
----------------------------------------------------VEWI-SRV
VS-------------------NV--------NAVIMVVVS--SGLLQQTF----------
-WSLIQ-------------------------------------GK-VLGRALPHEASFYI
SQALLLS----YFCYDAVLILLFMRSI--------------SSPCSSLAHHLFSALSIMF
CFYIGEK----QPLALIWATGIALTEVSTPLVNARWFLSFRYRERWQYKVIGLGMLVAFV
LGRVIYIPVL-------------VAGIVLAA------------------------PMYLN
PGEA------LCAFWLG------LVG----------------------------------
-------------SASSVTIWILNVYWTMLMLRG--------------------------
--------------------------------------------ARK-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------LFKSQARNSMTDQAAMYSA
IRGRPPALGDNENTHLKTV-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>gi|334184784|ref|NP_973633.2| RING-finger domain-containing protein [Arabidopsis thaliana]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MDSAPSPSSLDFELSPPV
L-----------VTMTSTSSSASDN-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----VEGADDDANT-HGIFNWRDFSSCWRVSESNLYCFSLALLI----------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------W
---FF-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------ASFILIENLYGPKNVWLGPSSSILVEPSSIFVKSIKVKVLDYSEPG
LQLYG-------------------------------------FYRTPALDCFVNWSESRV
LSISHESYKGWPYYLNSGSLLNITYTVKPQGSAVQLVVDEGHQGVPQSVLNDPAYRYNVW
SWNLIE-------------------------------------GSGMIQLEIRKSSSYYL
AVANLKSKDVEVTTTDQVELNIDVKAVLYDTKQSFYNCNFSNGECT------FNAMSL--
---VGNSVVVTSPAA---SQGVSIED--------EWYIRFSYQPREIAYVIGTGVVICFM
LVAIQFCNRFQCSGGEGHLTEDDSARTRLLADKDDDGSSMGSCDDSYANDDADLEEFMGN
DGEASNRSRRLCAICFDVPRDCFFLP----------------------------------
-------------CGHSVSCYECGT--TMQEADG--------------------------
--------------------------------------------SCP-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------I----CRRKMKKVKRIYTV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
