>AT4G22250.1|PACid:19648651
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MSELD
LGTSQR------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MTETHRTTTTFLDLLRRQMSGHDLTRRKRTLKERLRFKCIGCCGPTWNLRLTNNT
TLHSPTSRDDEIEELQIETGLVLESDHGSGTGMNLATALEAE----------RYNRGEST
EAEADMTPRRV----SLMRLLEETAE----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------KIVDDDGKETEILTASIGTLTGNDSVCCV-----------------------
-----------------CMGR---------------------------------------
---KKGAAFIPCGHTFC--------RVCSRELWLNRGSCPLC------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------NRPIIEILDIF-------------------------------------------
------------------------------------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|17010 @Homo_sapiens@ gi|21361493|ref|NP_057506.2| RING finger protein 141 [Homo sapiens]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------GQQISDQ
TQLVIN------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------KLPEKVAKHVT
LVRESGSLTYEEFLGRVAELNDVTAKVASGQEKHLLF-----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------EVQPGSDSSAFWKVV
VRVVCTKINKSSGIVEASRIMNLYQ-----------------------------------
----------------------------------------------------------FI
QLYKDITSQAA----GVLAQSSTSEEPDE---------NSSSVT----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------SCQASLWMGRVKQLT-DEEECCI-----------------------
-----------------C------------------------------------------
-MDGRADLILPCAHSFC--------QKCIDKWSDRHRNCPICRLQMTGANESW-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--VVSDAPTEDDMANYILNM----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------A
DEAGQPHRP---------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|8449 @Trichoplax_adhaerens@ jgi|Triad1|61032|fgeneshTA2_pg.C_scaffold_19000105
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------AK----KAVSKLPTKR-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------FTRPSEPSSEDDNLCPV-----------------------
-----------------CLDEF--------------------------------------
-VAGDVLRILPCKHEFH--------KTCVDSWLENKQTCPLCKSNFLR------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--TLGLIPSDDNTSSNNTESEALSQLHGRDISL---------------------------
--------------------NAIPGEEQAESNENNDSDSDGFRVCTIQVASSSPTERNLL
SEDSNCY-----------------------------------------------------
-------------------HIETEVVLSTERRRSSASE----------------------
------------------------------------------------------------
----------------------------------------------ASCDTLSTVGS---
--SGKDNSP--LIHEIRKL-----------------------------------------
------------------------------------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|2952 @Saccharomyces_cerevisae@ gi|6322369|ref|NP_012443.1| Srs2p [Saccharomyces cerevisiae S288c]
M-----------------------------------------------------------
-----------------------SSNNDLWLHLVSQLNTQQRAAALFDYTRGLQVIAGPG
TGKTKVLTSRVAYLILHHHIHPRDIIVTTFTNKAANEMKERLQEMLRGAGVNISELLIGT
FHSICLKILYRFGHLVDLQKDWRIIDEKEIDVILDDMIEKVPDQIRDYASSITRKVNLCM
PSKNGDEWTIHPKLIKKQISKLKSNAILPEEYILDSNHDAALGYFYQIYQSELSKKNTLD
FDDLLMYTFRLLTRVRVLSNIKHVLVDEFQDTNGIQLDLMFLFAKGNHHLSRGMTIVGDP
DQSIYAFRNALAHNFLEMGRKCPIEYSTIILVENYRSSQKILNTSEILITQQNKGRQNRA
PLRAQFDLDFPPVYMNFPAYFLEAPSLVRELLYLKALPNLFTFNDFAILVRQRRQIKRIE
SALIEH------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RIPYKIIRGHS
FWDSKETRAMLNLLKLIFSPNDKHAILASLLYPARGLGPATGEKIKNALDTLATDVSCFQ
ILKDISSKKIMLDIPTKGRSVIADFISMIENCQLLLQSTLLGGLS---------------
------------------------------------------------------------
------------------------------------------------------------
-----------------DLFDKLYELSGLKYEYLYKDGKKKNDQLEK-------------
------------------------------------------------------SEPNLL
NARHKNIELLKNYFLALLSKSESSDKEKNEAIKAATDEAEPIEN----------------
-KVITPKEYLRNFFNSLSLHSDAAEEEESESNKDAKIKREKNGFVTISTIHGAKGLEWPV
VFIPGCEEGIIPCVFN--------------------------------------------
------DDKKDESEEDEEEDQENSKKDASPKKTRVLSVEDSIDEERRMFFVAQTRAKYLL
YLSNTVTVEDVDRPRIASRFLTTDLIKAMSDSQKLFESTN--------------------
------------------------------------------------------------
------------------------------------------------------------
--------------SIKKLYRILNKKPPAEDDKLFSLDQLRKDYNQFIENRRERMIWQGI
QMNDVYGIQLSRNKLLGSVSDFTSAADQLRLETQNSIFPQKKLIEKSRPSKINGNYAPKS
RVKSPEKRYAPETTSFHSPTKK---KVYAPQYVSTTNV----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------PSRQEFHSSTGKNIPFLRREDRSIT----------------------------
---------------DISPRSSTRSLKGASPNKTSHMSDDLMRPS---PTRKDKVTRNIH
FATAGTF-----------------------------------------------------
---------------RIETQSNVDELHPPEYSNKSGQS----------------------
------------------------------------------------------------
----------------------------------------------LTSSEFSGFSS---
-ACSNSDQPTNLIEDINNELDLSDEELLNDISIERRRELLGSKKTKKIKPKTRNRKSKRG
DKVKVEEVIDLKSEFEEDDSRNTTAAELLHNPDDTTVDNRPIISNAKFLADAAMKKTQKF
SKKVKNEPASSQMDIFSQLSRAKKKSKLNNGEIIVID--------------------
>gnl|BL_ORD_ID|2836 @Ustilago_maydis@ jgi|Ustma1|2837|UM02837
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------SYLPPINTLWDHASHPSKRAWSRSPSPEPAHHDTVHTQAGPSTQLTPLR
QAAIQR------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RLVRQSTRGDH
LPMRTRSAEQARLLRALKGYPPIGSSADADQLSDLEESIEVGRFQMVRFGERYIVQIGRR
RTMREEELSNEEDDGRRAGFSAVDAGLSFAPEGGVLPAMQDASLQTNG------------
--------------------------GDNEGITGPGLFVGGHTGHAQAEFNQRRIAEAER
RARDAEAGANRAAAAAEAARSQ--AERQAAFQEEQDAVDLDADVEDLDEGDDEANTK---
--VWRRKTRLKADSGEKERLRRKWSCRQVDRRKDAQTDRQRANMAVC--------QLGNR
SAQNMYQFSKAIHSQLLHTRSHYTNDHPTLATLH---TPSWKHILNQIVNAAAVPKITVT
ANEGKVTAGKR----SIDRRRSTTKACNQ---------KNSILTPYLLLI--PCVGSFDR
ISFFVNMILLGTENIIIRDVLTEKFDKP--ASVDQTFTDFDGVAYHLESTSKAGPLTLSM
DIRCWSELVQAGAMEVLKREYNSWIRDAVEPEYSVTLEFDYAKVPAA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------GPERDALIASVSLLKRNAMAAPFERAFAMQKQLEQEAESNVPSTGT
EIMPINYRDDEAIYVIPSADRVTVVF----------------------------------
------------TTTFKEETDKVLGKVFLQEFVDARRQPSIQNAPQVL------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------YSNREPPLEVRNVAGLNKGDDVGYVTFVLFPRHFSNAEVM
ASTISRIQLFRDYLHYHIKCSKAYMHSR--------------------------------
------------MRHRVAEFLKVLNRAKPELAEKERKT----------------------
------------------------------------------------------------
----------------------------------------------ASGRTFRRA-----
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|5478 @Cladonia_grayi@ jgi|Clagr2|97901|fgenesh1_pm.7_#_45
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KVRSEDPHELSDFKLLSFDCFGT-------------
----------------------------------------------------------LV
DWESGIYEELK----PLLARLPSSNPVKT-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------NRALAIKSFNDIEVSL-----------------------
-----------------CASKPGLKYS---------------------------------
-------------------------TLLSESYLTLAETFSLPQPPQAE------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--VDAVGASVGQWPAFPDTVAALNRL----------------------------------
---------KKHYKLVILSNVDKESFSHVLCGSLANVDFDAVYVA---------------
-EQIGSYKPSLKNFQYLLGHVKEELGVEKG------------------------------
------------QVLHTAHGIESDHVPCKEMGMTSAWI----------------------
------------------------------------------------------------
----------------------------------------------ARGETTGPGST--M
ESMGDRATPTWVFEDMMEMATATDEDFEKDRC----------------------------
------------------------------------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|4117 @Ciona_intestinalis@ jgi|Cioin2|249845|gw1.09q.9.1
L-----------------------------------------------------------
---------------------TGSPRP---------------------------------
------------------------------------------------------------
-------------EVRWFHGG------EDVTGSLNYEISYSMD-----------------
--------------------------------------------------GRASLHINEV
FDEDAGHFTCQVSNDYGKASSMAELVVESKWGRGVRRVIVSPARSPGLR-KTSASPVKRL
RETSRSPVRTMSPSKRLEE--IEQLDIEKYFRPKFLRKPESRECNEGEATRIDCKVTGRP
LPDVTFYKEGSQVYEDYNHRIVVKEDGIRSLIISPARPEDSGEYTVVARSAAGKAVSTLS
LTVIPQEGIERPRILEKPQSVTVKEGDMVRLEVFAVGRPTPEIVWLKDNV-----LLIPE
KHPELRIEGVDGHGLLTIDRAAKGLHDAWYTATAVNKAGRDLSRCKVNVNRIEYDPEPSR
KLYIPKSKGLKQAVEPSPERVDLRKLDNFDET--DLYDSSRMQKP----RIKKKLVSAK-
----QKILGSVHFECHIVPIGDPTM------------------------RVE-WLLDGKQ
LEYANRIMTTFEFGY-----AALDINAVY---------PRDTGVISCRATNAHGQV----
---------------QSSCTLIVKEERGLVEKTQLPDTTQLGKIETTE-------RHRQE
ISLAHVSHQTDEVEVRSAPKIVLNPDPVVVQEGEPARFRCRVVGSPLPKVDWYLNGQAIR
QSKRFRI----WSDGIHYFEIA-TVRGYDHGQVKMVAQNIE-GSVEATTTIEVSQARDLR
TVLHKADIQTSDSKTKKEKGRHMVPLREVEKPIAGLKKVKRVERHEE--------LQSKF
SK-------------------------LSEEERMLN-TFEAD----------KKKSTQRD
RKYESFIRKTK----DSLSHWDEPKPEEAPKIPFLQRPKQSLPPPYEIKV--DVTPDMQA
PVVLERIHNV-----TVQSGKDARFRVRFHGNPEPEISWYRNEIALEKSERLGWIFPENN
VCELFIRDCHVDDSGSISVRISNPAG---------------QAGSQGFLLVQAVEALHFT
ESLTDVDAKENEKSVIFECSVSDFTAEVEWRRCGTDGAAEEVLRTSEKFQTRAD------
GAQRLLRIADIKLSDAGS----------YSCVMFAAGDKEIKSTAQLH------------
------VKVVPKKIQSGLKNQVAREGGACDFTAVVSHAGVAGTWMKDGVEIQASSKHVIT
ENGNKRSLTVNDSRAADEGVYEYIYCDEKSLANLTVQAMHVSIVKKLKDMSVFAG-----
----------------EVVTLEVK---ISRDDAIATW-----------------------
-----------------SRNEQTVTSDKRLITTSD-------------RSRHMLIIENCT
VEDSGVYTFAAGTAS-CSATLEVKSVDVTTGIQDSTNVESTDGVFECHVNQAGYSAGKWF
CGQ----------------TEIKSDNVKYSVKTDGKKQVLVVHNTTAQDSGVYSYVTGSK
STSEAKLVVIPVEITGTLQDVTEAETAAVN------LTATLSESGVHG--------AWFK
DGQPLQNTSNVSAVVDGKQHSLFIRSLSLNDQGVYEF------RIGNK-TTSASLTVQGA
QITKPLSDATATETESVRFECQVASDGVQGSWMKNGELLDADYSHRFVSSSEGRTQILMI
NDVTKEDSGSYSFKFGSASTSANLSITGIKFSKGLRNITVAEGSDADFTVEVA-------
---------NENIS---NVRWERNGVMINCDDVKYRVQSQGQRFT-LIVHCVTKKDEAAY
SCIAGSAKTSARLYVEAVTITRKLTEVR--------------------------------
------------AMEHRNVELT------TEVTNSSVSG----VWTRNGVTVTE-------
TERVKTTHRGKTHQLV----------------------------------------ITDA
QADDSGSYQFAVGKSTTSAKVIVEAIHLTSRMKD------------VVVKETQTATY--E
CEVSHPDVPAAACKWTKNGVVIKPSNLISI-TVDGRTHRLKI------------HTCAAE
DSGVYSFTAGEDSCTAALNVEAVTIVKQMPKKLQANAHDVAVLECTVDAPGISAFWVKDG
KRIDTTQDKSVKYEAISRDVTHTLKVKDIAAEDAGVYEFVAGSVRNKTTLYVEGKNI
>gnl|BL_ORD_ID|18211 @Takifugu_rubripes@ jgi|Takru4|553741|e_gw2.18.54.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------NISPSSLVLFIVLKKHRVYLCPFVDLWPPFRLESSLLEVLQMDFEVEELS
SPLDSQ------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------VIVWKLE
LPSAPETVAKTEGAMRIYTTQRDFVGLAPLVMDTDILNTAVLTGKKVVMPVRTVAVEEDG
VVTDVSDYADCSSTNEDVLKVSDRCDYVFVN-----------------------------
------------------------------------------------------------
---------------------------------------------------GKETNGKVK
ILVNFTYSYMSAQLELNVWIPQLPLQIEVSDTELSQIKSWRVPILSSKRGGWNSEETN--
----------------------------------------------------RKAKGCML
QFQHAMVRVLT----HFVAEQVDPRDPKAYFLGSDWQADVTRLVRYFMKVEDPQVAKLQA
GRVLSGRDLGTTTIQVFSPLSDVILAKKTIKVTDEKVTITEMGVQLVTGLS---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------LTLQLSPGSNRAILA-------------------------
------------------------------------------------------------
-------------------------TTTTEEILQNPKEFPLCQFFQEALVSAWLQFSDGS
QTPLDVYDPTSYRLA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--VTSLDQGVVSVQDKPPTVVAEGEGEGVLVRLEMAICEACQKSKRKSTIAVG-------
---------NGSLKVKFQVNSRRPGSSTNNTKSNNDNEVDGKRKQRRPSQDPPDREESAM
QKITTTIKSTERTFISSVETPGQKTEEEIGGEELLANRPLTDLEIGMYALLGVFCLAILV
FLVNCISYVVKFRHKKPPSHVQDPPGHRHDWVWLGTDA----------------------
------------------------------------------------------------
-----------------------ELVMSVPGSPIQQDAQTTTTVIDIECDQTASLSRRPS
CLASVTDSPLSCVGSIRN----KPTHTESLHSPTSRRKRVQFTTFSTLERQHSPHVIPRE
NGHGIHWVGKTDGCEEEPQMSIAELEGNL-------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|3735 @Trichoplax_adhaerens@ jgi|Triad1|57150|fgeneshTA2_pg.C_scaffold_6000130
MCFTLIYKVHEEWLDNVCKGIIHDRKYDSDATMYERKLQLQPSQTRLPKHWKKICIKVVA
KPENIADPCQVNLPVSAMVLNNFEPLPGNANYAQVMSYINKATHLLACLYFQDFCKNISF
EAVSPCTYIKIPLKELIQSILSGLYGIQLVRATTGNSGDTPAAPVVDGARRDSQTLVPTV
NITVDKSEAESDSESSWHQSKIHQQERDDVRTNLFQRLKHSFQQHIHQQEHIQQIQHVIH
SSLNNTQNANLLPIICALETEKAFYFIQPYASYTLRDVVMYSPAMLTSSLSKPLFIVYQI
LNALHAYHCCGIG--VGQFSLEDVLIDENYW-----------VRLSGLQFRCEVIPSKED
KKAANTLNATSIDEKREKDDNMETADDLYALANRLVGNPTPAKVQVSGPT---------P
PPSARLPIGGNAIPSKDKLTMRRGSAFVTSMTLS------NKNLAVNNQHALENAKQTL-
LNFSEKLGNKKPSI----TSLKYQHRLLNKLSDMMCDLPQLVTNWTNNKISNFDYLMALN
RLAGRRFGDPNNHPILPWVVDFSRSDSSW----------RDLKKSKFRLNK------GDR
QLDATYESSGRNNSNDSGIHVRHHVSDGLSEITYHVYLARRMRRAVLCQYVRSEWVPAEY
PSTIQKLQEWTPDECIPEFFTDPSIFTSIHTDMPDLQVNPWASSPEDFVRRHKHLLDGEH
VSKRLHHWIDLIFGYKLSGKAAVKAKNVHLHLADNHEKPMNYGTVQL-FTEPHPKW----
---------------KSPNSIASAANVLLRNKNQSKASSQSEANESSQDGVGRYSSKQDS
IDLTNDDVLEISIDSTNAPEHLLA--HTADQESSPSMSLKSQLRSPLSLFRQQRNDSDSK
VQNKLKVGQILLPDGFEPLEILDNYESLAHFKKKCLAQSLKLGHEEMSRTNNVTDSNS--
--------TTQDSKQLKEKEKEKDKDKDKDK---DKEKDTKGKKKEE--------ESSNI
TKSGAVSLDHLITEDMKSLGFLLGEMLFSDKLRMLSPTLDVKERREICKAICKSSSNSIT
NLPRSLCKVIH----ELMTLGEDTENSSESSLKLFSDDGLPIVTPALMIS--SCTSKFSF
PDYFKDLYAFICELQTINNRPDTSQGKPRSNSTDQYQANETNKPVHDQPANLSST-PSNS
KTN----SVHASGKNNIAVSLQVPVGGGNTPNQNTTPEHIIQTETGGPILDEANEGL---
----STSSKKGEKDSIGSI-LRKLSKEIPGSVLATALEADRFPLVASRFPLEASRFPIRG
KLQAIVKLCQTKLPQLMSQLDSIGLELLLPHIMILFEDNELKYKAAYHLFNILGKHMGMK
TSNASLVKPILKLFESKIPVEDHVHLLNIHFTMNLINYLGLQSYIENFLPFLIESLPHNV
KSVNRHPRRPGPKRSNTESPLQSSSSSRKSSASRKTKFRRNSIA--IDYVSYLSGSNKKN
RPPSDTVRKHSEEEGPDRSSLELQ---VTEEPPNRGI-----------------------
-----------------SD-TLTVPSDPKIVDSDDGMLFRSHSFSGSERDKHKSTQNEKY
HVDSR----ASDGDSRKSSSLSNNAKNITESKVCQAAVETLKEIIPFMGPILT---GRYI
ANQALRLLPSGYVWSDTTDTYIRSSNVNETIKYGYLVDLLAHICKVYGPS----------
---------------VLFQQYVPAIVSAINNANDKRLSSKIEGGLIGSMLLFRACLPYTK
NKELLQNVESLALVV-------FQPLIKVIASGTLMFPGGGIARVGICQYMINVLRYIGE
RIGRDNARDLLADTIQLYFSCFDRVHSNEQKGLENGESVDYIPNKLEISEHKGIDY----
--IADEDSKNYGFSDSSDHNCPSLPQLQVVFNASMAYYSYVGFCKLIGDIFIGENLCNHD
LIWQLALSYDERLA---NKNDPNPDLSTTESNSRYIISVDYLNLT-----------EKVV
SCDGGAV------HVWDGETGKTLREIK--------------------------------
------------LPEKPACSLTKLPSPSTTLIIASIDGNLRFIDTRSGNIVYDWKASVSD
SDAIKSICSGNNGNFVAVGFASGKISVLDNRTGFIEARWEAHSGDILSLKPFGSSTFLSS
SGDHKICAWREDGKLVCSLRGQTEPVHTFTTYKDQILSISQANKFGVHSEMDENATY--T
CHKLHSNFMKGSVKSIAALPLTK-------------------------------TVLVGS
DSGDIGLIA---------------------------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|700 @Ustilago_maydis@ jgi|Ustma1|701|UM00701
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------DRNT
TLWSGGSGLGAVFANLPARSNTVPPKNVSSLNPFEKADLEVTANLDCSSDPELLQTPGWI
ESQDFHVAPGVVPTGETDLFTARDKDRGHVLDVGHMQGDVQQAFSGEAFHSEICHAGNTH
MPVANLSSQNEELDCNADDDQLQS------------------------------------
------------------------LQGFGFGSAATLAPPFG-NSLVHQPSFGAMATHAVP
TLIRMAREARLALASPGETFYSLSELYTLEHHFLEPCPAQSASSLDT--------QQAKH
GAIAARVRDLNLCTSP------------------------------------------AL
ESCRSCFGRDS----VSLEDSKTTTPGEEWLQPYLSNLDKAMNTMQPGYD--NATLQLGH
PDYQTATSCL--------------------------------------------------
-------------TQNPMWGLSSNYAGPSFDNTSRNSIMLGNNGSDGLLTSENSSSLSFS
RSLPELSTMLRET----------WSSQADLESLEADGRNEPVSRPEEAEELEARTCVNRH
GAAAELN-----------------------------------------------------
-----------RGHYNSVDLPFRRGGSPLQGEAFTRPGTSSVNVSANLLGGRMEEGCIGS
RKRIWYRAPNGQFVSATQALSGQFVSDGDGNSYGQGSSTGSEGIRRIRRRRKSEEVERKY
RCDYD---------GCEKAYGTLNLGTLTLPDALLCA-----------------------
-----------------FASRSCLQPCPDFQLSNT-----------IDLNTHRATNEHGP
RLNALGSIDREGCSAFVGSATRQSG-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------YGKLGPSRTEALDSSISSRSAEGEIGAKLGSVWRMEKMAVCDRQRDMTESW
HDRCGYVKNFRDSQVVGVYEIGYVNRES--------------------------------
------------RMLLLYDSWTYSSLYNHEFVILKSDS----------------------
------------------------------------------------------------
---------------------------------------IFIVQAKNKGRAAFVLKSVNF
CVSARKAAKEFVIRDS--------------------------------------------
------------------------------------------------------------
---------------------------------------------------------
