>AT4G22250.1|PACid:19648651
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MSELD
LGTSQR------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MTETHRTTTTFLDLLRRQMSGHDLTRRKRTLKERLRFKCIGCCGPTWNLRLTNNT
TLHSPTSRDDEIEELQIETGLVLESDHGSGTGMNLATALEAE----------RYNRGEST
EAEADMTPRRV----SLMRLLEETAE----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------KIVDDDGKETEILTASIGTLTGNDSVCCV-------------
---------------------------CMGR-----------------------------
-------------KKGAAFIPCGHTFC--------RVCSRELWLNRGSCPLC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------NRPIIEILDIF---------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|17010 @Homo_sapiens@ gi|21361493|ref|NP_057506.2| RING finger protein 141 [Homo sapiens]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------GQQISDQT
QLVINK------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------LPEKVAKHVT
LVRESGSLTYEEFLGRVAELNDVTAKVASGQE----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------KHLLFEVQPGSDSSAFWK
VVVRVVCTKINKSSGIVEASR---------------------------------------
----------------------------------------------------IMNLYQFI
QLYKDITSQAA----GVLAQSSTSEEPDE-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------NSSSVTSCQASLWMGRVKQLTDEEECCIC-------------
------------------------------------------------------------
-----------MDGRADLILPCAHSFC--------QKCIDKWSDRHRNCPICRLQMTGAN
ESW---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------VVSDAPTEDDMANYILNM------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------ADEAGQPHRP-----------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|8449 @Trichoplax_adhaerens@ jgi|Triad1|61032|fgeneshTA2_pg.C_scaffold_19000105
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AKKAVSKLPTK-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RFTRPSEPSSEDDNLCPV-------------
---------------------------CLDEF----------------------------
-----------VAGDVLRILPCKHEFH--------KTCVDSWLENKQTCPLCKSNFLR--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------TLGLIPSDDNTSSNNTESEALSQLHGRDISLNAI--------------
---------------------------------PGEEQAESNENNDSDSDGFRVCTIQVA
SSSPTERNLLSEDSNCY------------------------------HIETE--------
----------------------------------------------------VVLSTERR
RSSASE------------------------------------------------------
------------------------------------------------------------
--------------ASCDTLSTVGS-----SGKDNSP--LIHEIRKL-------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|2952 @Saccharomyces_cerevisae@ gi|6322369|ref|NP_012443.1| Srs2p [Saccharomyces cerevisiae S288c]
M-----------------------------------------------------------
-----------------------SSNNDLWLHLVSQLNTQQRAAALFDYTRGLQVIAGPG
TGKTKVLTSRVAYLILHHHIHPRDIIVTTFTNKAANEMKERLQEMLRGAGVNISELLIGT
FHSICLKILYRFGHLVDLQKDWRIIDEKEIDVILDDMIEKVPDQIRDYASSITRKVNLCM
PSKNGDEWTIHPKLIKKQISKLKSNAILPEEYILDSNHDAALGYFYQIYQSELSKKNTLD
FDDLLMYTFRLLTRVRVLSNIKHVLVDEFQDTNGIQLDLMFLFAKGNHHLSRGMTIVGDP
DQSIYAFRNALAHNFLEMGRKCPIEYSTIILVENYRSSQKILNTSEILITQQNKGRQNRA
PLRAQFDLDFPPVYMNFPAYFLEAPSLVRELLYLKALPNLFTFNDFAILVRQRRQIKRIE
SALIEH------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RIPYKIIRGHS
FWDSKETRAMLNLLKLIFSPNDKHAILASLLYPARGLGPATGEKIKNALDTLATDVSCFQ
ILKDISSKKIMLDIPTKGRSVIADFISMIENCQLLLQSTLLGGL----------------
------------------------------------------------------------
------------------------------------------------------------
-------------SDLFDKLYELSGLKYEYLYKDGKKKNDQL------------------
----------------------------------------------------EKSEPNLL
NARHKNIELLKNYFLALLSKSESSDKEKNEAI--KAATDEAEPI---------------E
NKVITPKEYLRNFFNSLSLHSDAAEEEESESNKDAKIKREKNGFVTISTIHGAKGLEWPV
VFIPGCEEGIIPCVFN--------------------------------------------
------DDKKDESEEDEEEDQENSKKDASPKKTRVLSVEDSIDEERRMFFVAQTRAKYLL
YLSNTVTVEDVDRPRIASRFLTTDLIKAMSDSQKLFESTN--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------SIKKLYRILNKKPPAEDDKLFSLDQLRKDYNQFIEN
RRERMIWQGIQMNDVYGIQLSRNKLLGSVSDFTSAADQLRLETQNSIFPQKKLIEKSRPS
KINGNYAPKSRVKSPEKRYAPETTSFHSPTKK---KVYAPQYVSTTNV------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------PSRQEFHSSTGKNIPFLRREDRSI-------------------
----------------------------TDISPRSSTRSLKGASPNK-------------
------TSHMSDDLMRPSPTRKDKV------TRNIHFATAGTFRIETQSNVD--------
----------------------------------------------------ELHPPEYS
NKSGQS------------------------------------------------------
------------------------------------------------------------
--------------LTSSEFSGFSS----ACSNSDQPTNLIEDINNELDLSDEELLNDIS
IERRRELLGSKKTKKIKPKTRNRKSKRGDKVKVEEVIDLKSEFEEDDSRNTTAAELLHNP
DDTTVDNRPIISNAKFLADAAMKKTQKFSKKVKNEPASSQMDIFSQLSRAKKKSKLNNGE
IIVID--------------------
>gnl|BL_ORD_ID|2836 @Ustilago_maydis@ jgi|Ustma1|2837|UM02837
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------SYLPPINTLWDHASHPSKRAWSRSPSPEPAHHDTVHTQAGPSTQLTPLR
QAAIQR------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RLVRQSTRGDH
LPMRTRSAEQARLLRALKGYPPIGSSADADQLSDLEESIEVGRFQMVRFGERYIVQIGRR
RTMREEELSNEEDDGRRAGFSAVDAGLSFAPEGGVLPAMQDASLQTNG------------
--------------------------GDNEGITGPGLFVGGHTGHAQAEFNQRRIAEAER
RARDAEAGANRAAAAAEAARSQ--AERQAAFQEEQDAVDLDADVEDLDEGDDEANTK---
--VWRRKTRLKADSGEKERLRRKWSCRQVDRRKDAQTDRQRANMAVC--------QLGNR
SAQNMYQFSKAIHSQLLHTRSHYTNDHPTLATLH---TPSWKHILNQIVNAAAVPKITVT
ANEGKVTAGKR----SIDRRRSTTKACNQ-----------KNSILTPYLLLIPCVGSFDR
ISFFVNMILLGTENIIIRDVLTEKFDKPA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------SVDQTFTDFDGVAYHLESTSKAGPLTLSMDIRCWSELVQAGAMEVLKREYNS
WIRDAVEPEYSVTLEFDYAKVPAAGPERDALIASVSLLKRNAMAAPF-------------
---------------------------ERAFAMQKQLEQEAESNVPSTGTEIMPINYRDD
EAIYV------IPSADRVTVVFTTTFKEETDKVLGKVFLQEFVDARRQPSI---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------QNAPQVLYSNREPPLEVRNVAGLNKGDDVGYVTFVLFPRH
FSN---AEVMASTISRIQLFRDYLHYHIKCSKAYMHSR--MRHRVAEFLKVL--------
----------------------------------------------------NRAKPELA
EKERKT------------------------------------------------------
------------------------------------------------------------
--------------ASGRTFRRA-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|5478 @Cladonia_grayi@ jgi|Clagr2|97901|fgenesh1_pm.7_#_45
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KVRSEDPHELSDFKLLSFDCFGT-------------
----------------------------------------------------------LV
DWESGIYEELK----PLLARLPSSNPVKT-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------NRALAIKSFNDIEVSL-------------
---------------------------CASKPGLKYS-----------------------
-----------------------------------TLLSESYLTLAETFSLPQPPQAE--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------VDAVGASVGQWPAFPDTVAALNRL------------------------
-------------------KKHYKLVILSNVDKESFSHVLCGSLANVDFD----------
------AVYVAEQIGSYKPSLKNFQYLLGHVKEELGVEKGQVLHTAHGIESD--------
----------------------------------------------------HVPCKEMG
MTSAWI------------------------------------------------------
------------------------------------------------------------
--------------ARGETTGPGST--MESMGDRATPTWVFEDMMEMATATDEDFEKDRC
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|4117 @Ciona_intestinalis@ jgi|Cioin2|249845|gw1.09q.9.1
L-----------------------------------------------------------
---------------------TGSPRP---------------------------------
------------------------------------------------------------
-------------EVRWFHGG------EDVTGSLNYEISYSMD-----------------
--------------------------------------------------GRASLHINEV
FDEDAGHFTCQVSNDYGKASSMAELVVESKWGRGVRRVIVSPARSPGLR-KTSASPVKRL
RETSRSPVRTMSPSKRLEE--IEQLDIEKYFRPKFLRKPESRECNEGEATRIDCKVTGRP
LPDVTFYKEGSQVYEDYNHRIVVKEDGIRSLIISPARPEDSGEYTVVARSAAGKAVSTLS
LTVIPQEGIERPRILEKPQSVTVKEGDMVRLEVFAVGRPTPEIVWLKDNV-----LLIPE
KHPELRIEGVDGHGLLTIDRAAKGLHDAWYTATAVNKAGRDLSRCKVNVNRIEYDPEPSR
KLYIPKSKGLKQAVEPSPERVDLRKLDNFDET--DLYDSSRMQKP----RIKKKLVSAK-
----QKILGSVHFECHIVPIGDPTM------------------------RVE-WLLDGKQ
LEYANRIMTTFEFGY-----AALDINAVY---------PRDTGVISCRATNAHGQV----
---------------QSSCTLIVKEERGLVEKTQLPDTTQLGKIETTE-------RHRQE
ISLAHVSHQTDEVEVRSAPKIVLNPDPVVVQEGEPARFRCRVVGSPLPKVDWYLNGQAIR
QSKRFRI----WSDGIHYFEIA-TVRGYDHGQVKMVAQNIE-GSVEATTTIEVSQARDLR
TVLHKADIQTSDSKTKKEKGRHMVPLREVEKPIAGLKKVKRVERHEE--------LQSKF
SK-------------------------LSEEERMLN-TFEAD----------KKKSTQRD
RKYESFIRKTK----DSLSHWDEPKPEEAPKI--PFLQRPKQSLPPPYEIKVDVTPDMQA
PVVLERIHNV-----TVQSGKDARFRVRFHGNPEPEISWYRNEIALEKSERLGWIFPENN
VCELFIRDCHVDDSGSISVRISNPAG---------------QAGSQGFLLVQAVEALHFT
ESLTDVDAKENEKSVIFECSVSDFTAEVEWRRCGTDGAAEEVLRTSEKFQTRAD------
GAQRLLRIADIKLSDAGS----------YSCVMFAAGDKEIKSTAQLH------------
------VKVVPKKIQSGLKNQVAREGGACDFTAVVSHAGVAGTWMKDGVEIQASSKHVIT
ENGNKRSLTVNDSRAADEGVYEYIYCDEKSLA----------NLTVQAMHVSIVKKLKDM
SVFAG---------------------EVVTLEVK---ISRDDAIATW-------------
---------------------------SRNEQTVTSDKRLITTSD-------------RS
RHMLIIENCTVEDSGVYTFAAGTAS-CSATLEVKSVDVTTGIQDSTNVESTDGVFECHVN
QAGYSAGKWFCGQ----------------TEIKSDNVKYSVKTDGKKQVLVVHNTTAQDS
GVYSYVTGSKSTSEAKLVVIPVEITGTLQDVTEAETAAVN------LTATLSESGVHG--
------AWFKDGQPLQNTSNVSAVVDGKQHSLFIRSLSLNDQGVYEF------RIGNK-T
TSASLTVQGAQITKPLSDATATETESVRFECQVASDGVQGSWMKNGELLDADYSHRFVSS
SEGRTQILMINDVTKEDSGSYSFKFGSASTSANLSITGIKFSKGLRNITVAEGSDADFTV
EVA----------------NENIS---NVRWERNGVMINCDDVKYRVQSQGQRFT-LIVH
CVTKKDEAAYSCIAGSAKTSARLYVEAVTITRKLTEVR--AMEHRNVELT----------
--------------------------------------------------------TEVT
NSSVSG----VWTRNGVTVTE-------TERVKTTHRGKTHQLV----------------
------------------------ITDAQADDSGSYQFAVGKSTTSAKVIVEAIHLTSRM
KD------------VVVKETQTATY--ECEVSHPDVPAAACKWTKNGVVIKPSNLISI-T
VDGRTHRLKI------------HTCAAEDSGVYSFTAGEDSCTAALNVEAVTIVKQMPKK
LQANAHDVAVLECTVDAPGISAFWVKDGKRIDTTQDKSVKYEAISRDVTHTLKVKDIAAE
DAGVYEFVAGSVRNKTTLYVEGKNI
>gnl|BL_ORD_ID|18211 @Takifugu_rubripes@ jgi|Takru4|553741|e_gw2.18.54.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------NISPSSLVLFIVLKKHRVYLCPFVDLWPPFRLESSLLEVLQMDFEVEELS
SPLDSQ------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------VIVWKLE
LPSAPETVAKTEGAMRIYTTQRDFVGLAPLVMDTDILNTAVLTGKKVVMPVRTVAVEEDG
VVTDVSDYADCSSTNEDVLKVS--------------------------------------
------------------------------------------------------------
------------------------------------------DRCDYVFVNGKETNGKVK
ILVNFTYSYMSAQLELNVWIPQLPLQIEVSDTELSQIKSWRVPILSSKRGGWNSEETN--
----------------------------------------------------RKAKGCML
QFQHAMVRVLT----HFVAEQVDPRDPKAYFLGSDWQADVTRLVRYFMKVEDPQVAKLQA
GRVLSGRDLGTTTIQVFSPLSDVILAKKTIKVTDEKVTITEMGVQLVTGL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------SLTLQLSPGSNRAILATT-------------
------------------------------------------------------------
-------------------------------------TTEEILQNPKEFPLCQFFQEALV
SAWLQFSDGSQTPLDVYDPTSYRLA-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------VTSLDQGVVSVQDKPPTVVAEGEGEGVLVRLEMAICEACQKSKRKSTI
AVG----------------NGSLKVKFQVNSRRPGSSTNNTKSNNDNEVDGKRKQRRPSQ
DPPDREESAMQKITTTIKSTERTFISSVETPGQKTEEEIGGEELLANRPLTDLEIGMYAL
LGVFCLAILVFLVNCISYVVKFRHKKPPSHVQDPPGHRHDWVWLGTDAELVMSVPGSPIQ
QDAQTT------------------------------------------------------
------------------------------------------------------------
---------TTVIDIECDQTASLSRRPSCLASVTDSPLSCVGSIRN----KPTHTESLHS
PTSRRKRVQFTTFSTLERQHSPHVIPRENGHGIHWVGKTDGCEEEPQMSIAELEGNL---
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|3735 @Trichoplax_adhaerens@ jgi|Triad1|57150|fgeneshTA2_pg.C_scaffold_6000130
MCFTLIYKVHEEWLDNVCKGIIHDRKYDSDATMYERKLQLQPSQTRLPKHWKKICIKVVA
KPENIADPCQVNLPVSAMVLNNFEPLPGNANYAQVMSYINKATHLLACLYFQDFCKNISF
EAVSPCTYIKIPLKELIQSILSGLYGIQLVRATTGNSGDTPAAPVVDGARRDSQTLVPTV
NITVDKSEAESDSESSWHQSKIHQQERDDVRTNLFQRLKHSFQQHIHQQEHIQQIQHVIH
SSLNNTQNANLLPIICALETEKAFYFIQPYASYTLRDVVMYSPAMLTSSLSKPLFIVYQI
LNALHAYHCCGIG--VGQFSLEDVLIDENYW-----------VRLSGLQFRCEVIPSKED
KKAANTLNATSIDEKREKDDNMETADDLYALANRLVGNPTPAKVQVSGPT---------P
PPSARLPIGGNAIPSKDKLTMRRGSAFVTSMTLS------NKNLAVNNQHALENAKQTL-
LNFSEKLGNKKPSI----TSLKYQHRLLNKLSDMMCDLPQLVTNWTNNKISNFDYLMALN
RLAGRRFGDPNNHPILPWVVDFSRSDSSW----------RDLKKSKFRLNK------GDR
QLDATYESSGRNNSNDSGIHVRHHVSDGLSEITYHVYLARRMRRAVLCQYVRSEWVPAEY
PSTIQKLQEWTPDECIPEFFTDPSIFTSIHTDMPDLQVNPWASSPEDFVRRHKHLLDGEH
VSKRLHHWIDLIFGYKLSGKAAVKAKNVHLHLADNHEKPMNYGTVQL-FTEPHPKW----
---------------KSPNSIASAANVLLRNKNQSKASSQSEANESSQDGVGRYSSKQDS
IDLTNDDVLEISIDSTNAPEHLLA--HTADQESSPSMSLKSQLRSPLSLFRQQRNDSDSK
VQNKLKVGQILLPDGFEPLEILDNYESLAHFKKKCLAQSLKLGHEEMSRTNNVTDSNS--
--------TTQDSKQLKEKEKEKDKDKDKDK---DKEKDTKGKKKEE--------ESSNI
TKSGAVSLDHLITEDMKSLGFLLGEMLFSDKLRMLSPTLDVKERREICKAICKSSSNSIT
NLPRSLCKVIH----ELMTLGEDTENSSESSL--KLFSDDGLPIVTPALMISSCTSKFSF
PDYFKDLYAFICELQTINNRPDTSQGKPRSNSTDQYQANETNKPVHDQPANLSST-PSNS
KTN----SVHASGKNNIAVSLQVPVGGGNTPNQNTTPEHIIQTETGGPILDEANEGL---
----STSSKKGEKDSIGSI-LRKLSKEIPGSVLATALEADRFPLVASRFPLEASRFPIRG
KLQAIVKLCQTKLPQLMSQLDSIGLELLLPHIMILFEDNELKYKAAYHLFNILGKHMGMK
TSNASLVKPILKLFESKIPVEDHVHLLNIHFTMNLINYLGLQSYIENFLPFLIESLPHNV
KSVNRHPRRPGPKRSNTESPLQSSSSSRKSSA----------SRKTKFRRNSIA--IDYV
SYLSGSNKKNRPPSDTVRKHSEEEGPDRSSLELQ---VTEEPPNRGI-------------
---------------------------SD-TLTVPSDPKIVDSDDGMLFRSHSFSGSERD
KHKSTQNEKYHVDSR----ASDGDSRKSSSLSNNAKNITESKVCQAAVETLKEIIPFMGP
ILT---GRYIANQALRLLPSGYVWSDTTDTYIRSSNVNETIKYGYLVDLLAHICKVYGPS
-------------------------VLFQQYVPAIVSAINNANDKRLSSKIEGGLIGSML
LFRACLPYTKNKELLQNVESLALVV-------FQPLIKVIASGTLMFPGGGIARVGICQY
MINVLRYIGERIGRDNARDLLADTIQLYFSCFDRVHSNEQKGLENGESVDYIPNKLEISE
HKGIDY------IADEDSKNYGFSDSSDHNCPSLPQLQVVFNASMAYYSYVGFCKLIGDI
FIGENLCNHDLIWQLALSYDERLA---NKNDPNPDLSTTESNSRYIISVDYLNLT-----
------EKVVSCDGGAV------HVWDGETGKTLREIK--LPEKPACSLTKL--------
----------------------------------------------------PSPSTTLI
IASIDGNLRFIDTRSGNIVYDWKASVSDSDAIKSICSGNNGNFVAVGFASGKISVLDNRT
GFIEARWEAHSGDILSLKPFGSSTFLSSSGDHKICAWREDGKLVCSLRGQTEPVHTFTTY
KDQILSISQANKFGVHSEMDENATY--TCHKLHSNFMKGSVKSIAALPLTK---------
----------------------TVLVGSDSGDIGLIA-----------------------
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|700 @Ustilago_maydis@ jgi|Ustma1|701|UM00701
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------DRNT
TLWSGGSGLGAVFANLPARSNTVPPKNVSSLNPFEKADLEVTANLDCSSDPELLQTPGWI
ESQDFHVAPGVVPTGETDLFTARDKDRGHVLDVGHMQGDVQQAFSGEAFHSEICHAGNTH
MPVANLSSQNEELDCNADDDQLQS------------------------------------
------------------------LQGFGFGSAATLAPPFG-NSLVHQPSFGAMATHAVP
TLIRMAREARLALASPGETFYSLSELYTLEHHFLEPCPAQSASSLDT--------QQAKH
GAIAARVRDLNLCTSP------------------------------------------AL
ESCRSCFGRDS----VSLEDSKTTTPGEEWLQ--PYLSNLDKAMNTMQPGYDNATLQLGH
PDYQTATSCL--------------------------------------------------
-------------TQNPMWGLSSNYAGPSFDNTSRNSIMLGNNGSDGLLTSENSSSLSFS
RSLPELSTMLRET----------WSSQADLESLEADGRNEPVSRPEEAEELEARTCVNRH
GAAAELN-----------------------------------------------------
-----------RGHYNSVDLPFRRGGSPLQGEAFTRPGTSSVNVSANLLGGRMEEGCIGS
RKRIWYRAPNGQFVSATQALSGQFVSDGDGNS----------YGQGSSTGSEGIRRIRRR
RKSEEVERKYRCDYD---------GCEKAYGTLNLGTLTLPDALLCA-------------
---------------------------FASRSCLQPCPDFQLSNT-----------IDLN
THRATNEHGPRLNALGSIDREGCSAFVGSATRQSG-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------YGKLGPSRTEALDSSISSRSAEGEIGAKLGSVWRMEKMAVC
DRQRDMTESWHDRCGYVKNFRDSQVVGVYEIGYVNRES--RMLLLYDSWTYS--------
----------------------------------------------------SLYNHEFV
ILKSDS------------------------------------------------------
------------------------------------------------------------
-------IFIVQAKNKGRAAFVLKSVNFCVSARKAAKEFVIRDS----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
