>Aquilegia_coerulea_gnl|BL_ORD_ID|33246 _026_00048.1|PACid:22056357

ML----------------------------PWGG-----------ITCCMSAAALY----
------------------------------------LLGKSSGR-----DADILKSVTRL
NQLKDLAQMLDTA------------------------------CKVLPFVVTVSGRVGSD
TPINCE-----------------------------HSGLRGVIVEEAAEQHFMKQNDSGS
WIQDSAQM------LAMTKEVPWYLD-----------------DGTGRVHVLGA------
------RGATGLVLTVASETFE---ESGRSLVRGTLDYLQGLKM-LGVKRIERVLPTGTS
LTVVGEAVKDDVGTIWIQRPHKGPFYVSPKSIDQLIANLGIWARLYKYAS--LGFTAFGV
YLIA-KHAIRYILERRRLLDFQRRVRAAAAQRLEQDNDGTDGKAEDG-PDVVNKDRIMPD
ICVICLEQEYNAVFVPCGHLCCCTTCSSHLS-----NCPLCRRRIDQVVRTFRH
>Aquilegia_coerulea_gnl|BL_ORD_ID|32964 _026_00047.1|PACid:22056075

MLLD----------------------GKFGPGGG-----------LFCCITAAGFY----
------------------------------------LLACSYKS-----EKEYLQFITKI
DQLKDLS------------------------------------LKALPLLVAVSGRVGSD
TPIKCK-----------------------------RSDSKCVILKERE------------
-------------------------------------------DGTGRVHVVGA------
------EGASELDLTFASKIFE---APDESLLHEISNECFTCKTDLSIKRMEVVLPIGEL
LTAIGEAVKDKNGAIQIQRPHTGKFYLTQKSIDCLISDLGSCQSIFKCFS--VGFTVFGV
ILIA-EHLINKVMERRLRSDLRQSGVSAAAQRLEQDNDGLNGRTSNE-SESEN-DGLVRD
LCVVCEDQSTT------WHLS------------------------HKHLATLTL
>Aquilegia_coerulea_gnl|BL_ORD_ID|4964 _014_00808.1|PACid:22027970

MSSTLNERIISLIAQLAL--------ATDGAGAG-----------VFLAYFTVQIW----
---------RNYRYTSSALERIHQAKSITISDLRSLLIDDNNSS---QTQSSSEKQLVII
RGLVEAKSVVDGN-----------------------------WKNLIP-----SSSSSNS
SSISSSIGKSGGLLLSN------------------QSGAKGVVLQNTQTYVYNDYKGLLG
YAVDLRTL------LGKPSKGPNALSIRTIPFVLVQNGDSQSLDSKDYVVVNLE------
------GSMHPLPLTTCYHHLQPIPTTPYTLIQAIVGHAYP----VGLLDEEKILPLGKE
ITAVGHCTLQD-GNPQIISCKKVPYFLSDMTKDQMIVDLVSKKKILFWAGIVLGSVSLGV
LGYALTRNWQRLKEWRQRRQIQ--------QSREEEIANLDATPEDTRADEETEDIPEGQ
LCVICLMRRKRAAFVPCGHFVCCYRCALSVERDSAPKCPLCRQDIRTSVRIYDS
>Arabidopsis_lyrata_gnl|BL_ORD_ID|19937 _474968|PACid:16053684

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------IPWGGVT
CCLSAAALYLLGRSSGRDAEVLKTVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETP
IKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGA
RGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVK
DDIGEFRIQKPDRGPF--YVSPKSLDQLISNLGKWSRWYKYASMG--FTVFGVFLITKHV
IDSV-------LERRR--------RRQLQKRVLDAAAKRAEL-ESEGSNGARESIADSTK
KEDAVPDLCVI-CLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKT------
---------------YRH
>Arabidopsis_lyrata_gnl|BL_ORD_ID|12068 _338432|PACid:16045815

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------IHLAGFT
CCLGGIALYLLSRNTG---GVVKSITRVNHLKDLEQLVE--SKVFPLIIAVSGIVGSETP
IKCEHSDILGVFLKKTAEQQVLSRNWRFSWVRKSTLMQPMTKEVPWFLDDGTGRVNVAVS
QGEIGLALTVGSDVFEKAEPVSLVQGTLDYLKGLKILGVRRVEHVVPIGTPLTIVGEAVK
DGMGNVRIQKPEQGPF--YVSYVPLDQLISKLGEWSRRFKYASMG--LTVVGVILLSKPV
IKYILKKIEDTLERRR--------RQLLQKRVVD--------------------------
----VPDLCVI-CHDQKYNTAFVQCGHMCCCLTCSLRLTTCPLCREQIQQVLKI------
---------------YRH
>Arabidopsis_lyrata_gnl|BL_ORD_ID|936 _867782|PACid:16034683

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------IHLGGLT
CCVSGGVLYLLSMIPGSFFEMLNSVTRVHQIKDLENLLQVEGK----IIAVSG-------
---------------TAQQLFLKRNWLFSWVEDSKWMLPQAKEVPWYL------------
-----------------------------------MLGVRRTEHVLPIGTPVTVVGEAVK
DGIRGFRIQKPEKGLF--FVSPVPLDKIISPMGKWLRRFKYVYVG--LTVVGVILISKPV
IEYI-------LERRR--------GRLLRKRVADAAAKRAKL-VARGLETQHENSLDSTS
RDRDVLDLCVI-CLEQKYDATFVKCGHMCCCLTCSLHVKTCPICRRPIEHVLKI------
---------------DRR
>Arabidopsis_lyrata_gnl|BL_ORD_ID|23612 _879732|PACid:16057359

MFEQNVSTFVFLDEIDPAAQRYKIKVQIVKLWRGFQKETGSAIEMVLIDEKGTRMHATVE
DKLMNKFKSDLKEDQSILVDTFQLVNNGFEYKTSPHSFKISFFRTTSVTICDDFPNDVPE
KYFVDFLKILAGVLDSKTLVDVIGHIVNIGPLEDIMIRGRSTTKLDVELRDTNDARLLCT
FWGKYADQVSTYAAEHSADMIVCVVRFAQIKEFRGNRSISNSYNSTRILLDPQTKVAHEF
RSNAAAVIYLGGYEIKRKAEYLKSATRVKDLRGLSELLENKTK--PLVVAISGRVGSSRP
LKCEHSGIWGVFMEEKAKLVFGTRSLHGGLMRHSAEFLLKHKEVPWFLEDSTGRINVVGA
RFAEGFYDNLKEFVFVEPAS-ELIKKFVKPEGFVKILEHNCFERVHELGKPLTIVGEAVK
YSNGALVIKRPTDGSFMFFDGYSSVDKMISLLESQSQALVYFSIA--LTAVGTLVYASYV
MPLI-----------K--------KSWFLDKSDTTAGQRAET-ETKHNSMGKAQ------
-SNYAFGLCFTSTFSDAANFNYKQTGFMMIVKSTFSALNNLGLRQRTDISSIKVIFSSES
ICLQIQKERVPAASPYHL
>Arabidopsis_lyrata_gnl|BL_ORD_ID|20460 _334745|PACid:16054207

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------EPVVE-SAVF
LSFVGASCYLFGRKIKRRVDYLGSITRVDGLKSLDDLLAKNTT--NLLVLVSGRVGSAAP
LDCKHNGLLGVLVEETAKLDCKIELEGGGLIEKSLTFLLHQKETPWYLEDCTGQVNVVGV
QDALGFNSILNKYVFKMPAS-ELLKTVVIPDG-TKVLKHNCHGRALNIGTYLTFVGEAVR
DKAGTVMIQRPKEQSFLVYSGEGSFENMVAELKS----MVYIGLGKIIGTVGVALAVMYG
VHCI----------RRVLLPFEWEKEELRNRSEKAKSDRGRTHQRKESDMGRTHQRKESD
ASRLPIGLAFL---------------------------------------LVKG------
---------------KDC
>gnl|BL_ORD_ID|17261 Arabidopsis_thaliana AT1G63900.1|PACid:19655208
MIPWGGVTCCLSAAALYLLG---RSSGRDAEVLETVTRV-----------NQLKELA-QL
LELDSKI----------LPFIVAVSGRVGSETPIKCEHSG--------------------
---------------------IRG--------VIVEETAEQHFLKHNETG--SWVQDSAL
MLSMSKEVPW-------------FLDDGTSRVHVMGARGATGFALTVGSE----VFEESG
R---SLVRGTLD-----------------------YLQGLKM----LGVKRIERVLPTGI
PLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWS---------RLYKYAS
MGFTVLGVFLITKHVIDSVLER------RRRRQLQK----RVLDAAAKRAELESEGSNGT
RESISDSTKKEDAVPD--LCVICLEQEYNAVFVPCGHMCCCTACSSHLTS-----CPLCR
RRIDLAVKTYRH
>gnl|BL_ORD_ID|19755 Arabidopsis_thaliana AT1G59560.1|PACid:19657702
MIHLAGFTCCLGGVALYLLT---RSTGRD---IKSITRV-----------YQLKDLE-QL
VEVESKV----------VPLIIAVSGDVGSETPIKCEHSY--------------------
---------------------VLG--------VFLKRTAEQQVLRRNWRF--SWVRNSTL
MQPMTKEVPW-------------YLDDGTGRVNVDVSQGELGLALTVGSD----VFEKAE
PV--SLVQGALG-----------------------YLKGFKI----LGVRHVERVVPIGT
PLTVVGEAVRDGMGNVRIQKPEQGPFYVTYIPLDQLISKLGDLS---------RRFKYAS
MGLTVLGVILISKPVIEYILKRIEDTLERRRRQFA---LKRVVDAAARRAKPVTGG----
------GTSRDGDTPD--LCVVCLDQKYNTAFVECGHMCCCTPCSLQLRT-----CPLCR
ERIQQVLKIYRH
>gnl|BL_ORD_ID|17011 Arabidopsis_thaliana AT1G54150.1|PACid:19654958
MSSPE------------------RALL-----------------------NLLTDIA---
LSFDGAI----------LGLTLAVSA-VGSALKYASTNAALKKIKDAPEVSISDLRSLLP
ASEDKSETNDNRKSNDQRIVVVRG--------VVKPKISGDEGYKNNNVLISPETGDKAL
IIQRTQTYVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVI-VGKD------QQSN
S---SFVAVNMDGSRQPLPLTTVYNRL-QPINSS-FLQAFLYPDYPVGLLDIEKILPPGK
DITAVGIYSFNN-GVPEIKSCQDLPYFLSEMTKDKMIEDLMEQT---------NFIFLGS
VILGIVSVGILSYAAVRTWNKWKQWNHQRELPQRP---NDSVVD----------------
-----DEPEDADEIPDGELCVICVSRRRVPAFIPCGHVVCCRRCASTVERELNPKCPVCL
QSIRGSMRVYYS
>gnl|BL_ORD_ID|25464 Arabidopsis_thaliana AT3G23280.2|PACid:19663411
MGQQQSKGELLYQQVSYGNSEGIRALHRDGGDLEWMDREGKTPLILACMNSELFDVAKTL
IELGSNVNAYRPGRHAGTPLHHAAKRGLENTVKLLLSHGA------NPLVLNDDCQTPLE
VARVKGFSNVVR-AIEKHICLFSGWMREFYGPTFLDLFAPQLLSRRVWVVIVPTGSRNPT
KPFKLELVVYA------------SLQDAQPRTVMPLWKANLEEPKAKQSDTSVMIVDNST
KTRLKFAPSTEGDSQQLKWFCDACKGIPQPMHPPVFLQA--PPSAP---------PPPSE
DGLAMGM-------NASLHTTMSDPSNLNHHSIGQASSSSGPSSSTAPPSGKASAFGFNS
HGIGIV---LESSPSAPPLTDDDIATVDDGPIHYP-SIDSTPVDLPSAASLPAS------
----TEGERKEDGNTG--TCAICLDAPSEAVCVPCGHVAGCMSCLKEIKSK-NWGCPVCR
AKIDQVIKLYRV
>Brachypodium_distachyon_gnl|BL_ORD_ID|17609 _1g19510.1|PACid:21820379

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------MVPWGGVG---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CCLSAAALYLL
GRSSGRDAEVLRSVT--RTGSLKDLAAILDTASKVLPL-------------VVAVSGRVS
S---DTPLICQQSGMRGVIVEEMAEQHFLKHNDAGSWIQD-SAVMLSVSKE--------V
PWYL-------DDGTGRVYVV--GARAAAGLVLTIASEVF--EESGRTLVRGTLDYLQGL
KMLGVKRTERVLPTGTSLT---VV------GEAIKDDVGTIR----------------IQ
RPHKGPFYASPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALQHFL-----QKK
RQHELNKRVRAAAAQRQAREAEGADGTSNGDPNS-KKDQLVLEICVICLEQEYNAVFVPC
GHMCCCMNCSSHVT-----NCPLCRRRIDQAVRTFRH
>Brachypodium_distachyon_gnl|BL_ORD_ID|13589 _1g72800.1|PACid:21816359

MSA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------RDRE---
----------------------------------TVEALARVAAALDGAVLGLGTAA---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------LAVVSLAKYLA
ASGA-----------------LRRIAEAPEVAIPDLRYSLLA-GLGEGESRLAVVRGLVR
SPPWGKFLIPPGSREHCVVAKHTQTCLFGEWRGIFGWTFDLHALFFKSLKEQTITSFRWV
PFALVDPASASDKSTEMIHVKLDGAVQQSLPLTTVYHKLIPVEQNSYTLFQTIVGNGYPI
ALLDE---EKILPIGKEIT---AIGLCRVNNQNVE-----------------------IT
SCPEIPFFLSDLTKGEIEAELDSRARTLFWVTFALGTMSVGLLGH-AIYRFW-----EKV
KQHREARQA----QQRFHQADDEDDTGENGSDDDFPGEMGDGQLCVICLRKRRKAAFVPC
GHLVCCCNCAKRVELMNEPLCPVCRQDIQYMLRVYDS
>Brachypodium_distachyon_gnl|BL_ORD_ID|29186 _3g30547.2|PACid:21831956

MSSRPSSSSSSRRSSSPFSAGNRRPPTSSSSSSSYMAGRLIPRSSPSSVSSQFYGGGGSS
RSTTPGRRGPGGSAPAPPPAPVPFPSADELVIEDTSRSGDSISVTIRFRPLSDREIQRGD
EISWYPDGDRLVRCDFVQPAAYAYDRVFGPSTATEAVYDVAARPVVKGAMEGINGTVFAY
GVTSSGKTHTMHGDQNCPGIIPLAIKDVFSLIQDTPGREFLLRVSYLEIYNEVINDLLDP
TGQNLRVREDAQGTYVEGIKEEVVLSPGHALSFIAAGEEHRHVGSNNFNLFSSRSHTIFT
MMIESSDRGDEYDGAMYSQLNLIDLAGSESSKTETTGLRRREGSYINKSLLTLGTVIGKL
SEGRATHIPYRDSKLTRLLQSSLSGHGHVSLICTITPASSNMEETHNTLKFASRAKRVEI
YASRNRLVDEKSLIKKYQKEISTLKQELDQFRRGMIGGASQEEIMILRQQLEEGQVKMQS
RLEEEEDAKAALMSRIQRLTKLILVSTKSNIPALTDLSSHQRQNSVSEEDKLTTSQDSSM
LVQNDSTVKDSVSLALSDPLDEINQLRSASGDHSSVTGSATDSSQVGITASDHMDLLIEQ
VKMLAGEIAFGTSSLKRLIEQSIEDPEGTKNQIENLEREIQQKRRHMRALEQKLMESGEA
SVANASMVDMQQTITKLTTQCNEKAFELELKSADNRVLQEQLQQKSVEICDLQEKVQRLE
GQFITKNSPSPEQCTPQEIVDLKSKLQCKEVESEKLKYEHLEI-IEENRDLINQNQKLSE
EAAYAKELACSAAVELKNLAEEVT---------------KLSIQNAKQAKELLIAQ----
-----------EKAHSRVPIR--KGRP---------------TGRGRDEVGTLSLDLEDM
KMELLARKQRETALEAALAEKELL------EEEYKKKFDEAKKKELSLENDLAGMWVLVA
KLKRGAFNISELNVDERSINL---ADITNDTKENKGDKTVALVEKQMSDDTLKSLTAEDY
RSPEFEPLLVRLKAKIQEMKEKETDPLSDKDGNS--------HVCKVCFESATAAVLLPC
RHFCLCKPCALACS-----ECPLCRTRIVDRIITF-T
>Brachypodium_distachyon_gnl|BL_ORD_ID|29185 _3g30547.3|PACid:21831955

MSSRPSSSSSSRRSSSPFSAGNRRPPTSSSSSSSYMAGRLIPRSSPSSVSSQFYGGGGSS
RSTTPGRRGPGGSAPAPPPAPVPFPSADELVIEDTSRSGDSISVTIRFRPLSDREIQRGD
EISWYPDGDRLVRCDFVQPAAYAYDRVFGPSTATEAVYDVAARPVVKGAMEGINGTVFAY
GVTSSGKTHTMHGDQNCPGIIPLAIKDVFSLIQDTPGREFLLRVSYLEIYNEVINDLLDP
TGQNLRVREDAQGTYVEGIKEEVVLSPGHALSFIAAGEEHRHVGSNNFNLFSSRSHTIFT
MMIESSDRGDEYDGAMYSQLNLIDLAGSESSKTETTGLRRREGSYINKSLLTLGTVIGKL
SEGRATHIPYRDSKLTRLLQSSLSGHGHVSLICTITPASSNMEETHNTLKFASRAKRVEI
YASRNRLVDEKSLIKKYQKEISTLKQELDQFRRGMIGGASQEEIMILRQQLEEGQVKMQS
RLEEEEDAKAALMSRIQRLTKLILVSTKSNIPALTDLSSHQRQNSVSEEDKLTTSQDSSM
LVQNDSTVKDSVSLALSDPLDEINQLRSASGDHSSVTGSATDSSQVGITASDHMDLLIEQ
VKMLAGEIAFGTSSLKRLIEQSIEDPEGTKNQIENLEREIQQKRRHMRALEQKLMESGEA
SVANASMVDMQQTITKLTTQCNEKAFELELKSADNRVLQEQLQQKSVEICDLQEKVQRLE
GQFITKNSPSPEQCTPQEIVDLKSKLQCKEVESEKLKYEHLEI-IEENRDLINQNQKLSE
EAAYAKELACSAAVELKNLAEEVT---------------KLSIQNAKQAKELLIAQ----
-----------EKAHSRVPIR--KGRP---------------TGRGRDEVGTLSLDLEDM
KMELLARKQRETALEAALAEKELL------EEEYKKKFDEAKKKELSLENDLAGMWVLVA
KLKRGAFNISELNVDERSINL---ADITNDTKENKGDKTVALVEKQMSDDTLKSLTAEDY
RSPEFEPLLVRLKAKIQEMKEKETDPLSDKDGNS--------HVCKVCFESATAAVLLPC
RHFCLCKPCALACS-----ECPLCRTRIVDRIITF-T
>Brassica_rapa_gnl|BL_ORD_ID|33068 _027667|PACid:22716578

M-------------------IHWGGVTCCLSAAALYLLGSSS--GRDAEVLKTVTRVNQL
KELAQLLELDSSKLLPFIVAVSGRVGSDTPIKCEHSGIRGV--IVEETAEQHF-LKHNET
G-SWVQDSA-LMLSMSKEVPWFLDDGTSRVNVVGARGATGFALTVGSEVFEE-SGRSLVR
GTLDYLQGLKMLGVKRIERVLPTGMPLTIVGEAVKDDIGDLRIQKPERGPFYV--SPKSL
DQLISNLGKWSRWYKYASMG----LTVFGVFLITKHVIDHV-------LER---------
------RRHRELQKRVLDAAAKRAE-ETEGSNG--AHESVSDS------------TKKEG
AVPDLCVICLEHNYNAVFVPCGHMCCCTACSSHL----TSCPLCRRRIDQVVKTYRH
>Brassica_rapa_gnl|BL_ORD_ID|36378 _040424|PACid:22719888

M-------------------EPWSGL-CCIGAVALYLLSRRT--ARDVDFLKSVTRVDQL
KDLE-------SAVLPSIVAVSGTVGSETPIKCEHSGILSV--ILQETAEQQF-LKRNWK
F-SWVQDTA-LMLPVCKEVPWFLDDGTGRVIVEGARSGIGFELTVGGEVFEKPEASSLVR
GTLDFLRGLEMLGIRRIERVLPVGTRLTVVGQTIKDGVGDVRIQKPDQGPFYV--SPIPL
DHLISKVGKWSRRFKKASMG----LAVVGVILISKPVIKYILVRTGDFLER---------
------RQQRLLKKRVVDAAAKRKKLAAPKREERVTSKGLENG------------KSRDG
DEHDRCVVCLERKCDAAFVPCGHMCCCLTCALKL--LGKPCPLCRKRGIRILKIYRN
>Brassica_rapa_gnl|BL_ORD_ID|30202 _007725|PACid:22713712

M-------------------ISWSGFKCFIWAYLLYLLSRRTGGGGDVEFFDSVTKVDHL
KGLAELLEEG-REVRPLIVAVTGSVASATPFKCQRSEMLAV--ILEETEEIQF-LKRNWK
F-SWVQDTASISLPITKQVPWFLEDGTGRVNVSGAETALGFAFTVGSEVFEKPEASSLLP
GALAYLQGLKMLGVRRFEYVLPIGTWLTVVGEAVKDGSGNVRIQKPDQGPFYI--SPKPL
DQLIPTLGTWSRIFKYASMGASFCFTVRGVIITSKPLIIYILHVIEDILFMFGYILWRMR
QGLPILKKHVTLLKRVFCAAANRTRQA--------TEEGLCESFFPEYACEFALIISLAP
DVPDLCVICLDRKCDAVFLECGHMCCCLTCSLSLELQGKRCPLCRKPV-VVLKIYRI
>Brassica_rapa_gnl|BL_ORD_ID|39988 _016684|PACid:22723498

MKSLRFAILKFEVLNNLYRLVSPLGM-SDFGVVLGYDISDLRNGLRKADSFNSITRVADI
KCLDDLLK---EKASNLLVVLSGKVASATPFNCKHDDDSSSGDVFEAKFEMEYETKKDDD
G-GLIHKSH-NFLLQINETPWYLEDGTGLVKVVRAELADGYVDTMKPQ-FDMLSMSEIFQ
RFENPQEGSKVI----CRCALDTGTSLTIVGEAARDEAGTLSIQNPKEQSFMIFSGEGSF
DKMVANLKSNSEFYFFYSKI----FGTIAVAIAVVKGVGFV-------------------
--------RRVLRERSENATDSDNEEN---------------------------------
-----------------------------------------P---------------
>Brassica_rapa_gnl|BL_ORD_ID|39503 _016685|PACid:22723013

M-----------------------------------------------------------
-------------------------------GCT-------------------ETELGDD
GSAWITKSH-NFLFQVKRCPWYLEDSTGVVKVVGAEAADDFLDTLTPH-LDM-SLSEIFG
SIVEPKQGSQTI----FRASLDTGTSLTIIGEAARDEAGNLTIQNTNEQPFRIFSGEGSF
DKMVANLKSNSEFYFFYSKI----FGTIAFAIVVFKGVSFI-------------------
--------RRVLRERADNA-DSDDEET---------------------------------
-----------------------------------------P---------------
>Citrus_clementina_gnl|BL_ORD_ID|13924 _0.9_014777m|PACid:19265048

-----------------------MISWGGISCCLSGAALYLLGRSSGRDAELLKTVTRVN
QLE--ELAHLLD------GGSKVLPSIVSVSGRVGSETPIS--------------CEYSG
LRGVIVEETTERHFLKHN----DAGSWIQDSALMLSMS---------KEVPWYLDDGTG-
------CVFVVGARGATGFALTVGSEVFEESGRSLVHGTLDYLQGLKM-LGVKRIGRLLP
TGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELLENLGKWARWYKYASFGLTIF
GAFLIAKRVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNGQAENGSDSTQRDRVMP
D--LCVICLEQEYNAVFFPCGHLCCCLICSSRLT-----NCPLCRRRIDQVVRTFRH
>Citrus_clementina_gnl|BL_ORD_ID|13925 _0.9_019918m|PACid:19265049

M-----------------------------------------------------------
------------------------------------------------------------
-----------RSFLRQSRVSINSRSW---------------------------DDGTG-
------CVFVVGARGATGFALTVGSEVFEESGRSLVHGTLDYLQGLKM-LGVKRIGRLLP
TGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELLENLGKWARWYKYASFGLTIF
GAFLIAKRVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNGQAENGSDSTQRDRVMP
D--LCVICLEQEYNAVFFPCGHLCCCLICSSRLT-----NCPLCRRRIDQVVRTFRH
>Citrus_clementina_gnl|BL_ORD_ID|23563 _0.9_012472m|PACid:19274709

MSLLEQHLASLYQLAVSFDGAVL-----GVALAYTAVRSFLDFRYT---SNALGKVRNAP
QLKVSDLRALLDEKQSQPSDQEQNSRLVIVRGQVEAKSAVDGINWKTLMYSNDILVSESG
DKAVILEQRKAFLYNEWR----DLFGWTPDIRAIFGRSLKTSEPSSLRTVPFILVEGDRW
PQSDYIIVNMDGSR--QPLPLTTAYQRLELANVSPF-TFLQAMFGLKCPIGVLAEEKILP
LGKDISAVGICSFKN-GIPEIKSCKDLPYFLSEKTKDLMVVDLVNRSKILFWSGIVLGSL
SIGILGYAIVR----NWNRWKDRQQRMSRQLTEAPSDDADSQIGSDEDVAGD------IP
DGQLCVVCLTRRRISAFNPCGHLVCCRRCAISVEREASPKCPVCRMTVRSSMRIYFS
>Citrus_clementina_gnl|BL_ORD_ID|23562 _0.9_012450m|PACid:19274708

MSLLEQHLASLYQLAVSFDGAVL-----GVALAYTAVRSFLDFRYT---SNALGKVRNAP
QLKVSDLRALLDEKQSQPSDQEQNSRLVIVRGQVEAKSAVDGINWKTLMYSNDILVSESG
DKAVILEQRKAFLYNEWR----DLFGWTPDIRAIFGRSLKTSEPSSLRTVPFILVEGDRW
PQSDYIIVNMDGSR--QPLPLTTAYQRLELANVSPF-TFLQAMFGLKCPIGVLAEEKILP
LGKDISAVGICSFKN-GIPEIKSCKDLPYFLSEKTKDLMVVDLVNRSKILFWSGIVLGSL
SIGILGYAIVR----NWNRWKDRQQRMSRQLTEAPSDDADSQIGSDEDVAGD------IP
DGQLCVVCLTRRRISAFNPCGHLVCCRRCAISVEREASPKCPVCRMTVRSSMRIYFS
>Carica_papaya_gnl|BL_ORD_ID|23657 _evm.model.supercontig_9.121|PACid:16428004

M------------IPWGGITCCMSAAALYLLGRSSG------------------------
--RDADILRKVTRVNQLKE----LAQLLDI---------ESKIMPL--------------
IVAISGRVGSETPISCEYSGLR--------------------GVIVEETAEQHFLKHND-
---------------AGSWIQDSALML---------SMSKEVPW-YLDDG----TARVFV
VGARGATGFVLTVGSEVFE----------------------------------------E
SGRSLVRGTLDYLQGL------------------------------KMLGVKRIERVLPT
GTSLTVVG-------------------------EMT---LEQFRYEDRTNGLFTCLQING
-------------------------------SPDF-QLGKWARWYKYASMGLTFLGVFLI
AKRSIEYVLERRRRREL------------QKRVLAAAAKRSGQDNEGSNIIPENGLDGAK
REHLMPDLCVICLEQEYNAAFVPCGHMCCCMTCSSHLT-----NCPLCRRRIEQVLRT--
----------------------------------FRH
>Carica_papaya_gnl|BL_ORD_ID|10657 _evm.model.supercontig_25.125|PACid:16414718

M-----------SSPEQALASLVSHLALSLDGAVLG-----------VALAYAAVRSFFK
FTANSAALRKIRSAPQLRVSD--LRSLLPVSSEDQSQPSDSDPSST--------------
LVIVRGTVEAKSAVDGSWKGLRHN-------NVLVSQESGDKAVVIQRTQTYIYNEWKG-
---------------FFGWTSDLRAIFGRSWGKQESASSRMVPFVLVEDGRWPQSDYVIV
NTEGSLHPLPLTTVYHQLQ-----------------------------------------
---PVNASPYTFLQALFGHEYPV--------------------------GLLNEEKILPL
GKDISAVG------------------------ICSFKNGIPEIMSCKDLPYFLSDLTK--
-------------------------------DQMLLDLAFRTKILFWSGIILGSLSISIL
GYAALRNWNRWKERR--------------QQRQAHQPSHAASIDANSELTGEEEIGDIPD
GQ-----LCVICLMRRRVPAFIPCGHIACCQPCALSVERELTPKCPVCRQEIRGSMRV--
----------------------------------FYA
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|13853 _03.g169050.t1.1|PACid:19872172

M----------------STFT-------------------------GSPRPS--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----SWLD---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------YI-------SIGGVASL--G
ASFIFFQL----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AGGHDARIQQLVQAV
-ALDWLAGARQLDG-TLPRLVAARGRIGCREPSKCELSDQPAVMRELLEEEVYFK-----
---------EHTSGRVTHESFEVRREQEQREAFLEDV-SGSIRLDNLQHAAGLPSVMEVK
QVFRPV--DLLQGTLLQAVINKAFKSMVKHGVR--STERFLPVNTTVTVIGELCRDTLGA
PASTSGS-----------NSSSSGSSGGSGSSRAAVAAAPAG------------------
-----AGNRGQDAGAGPS------SGSK-SINAAGISSKLSGASS------K-----GGG
GGGGLGPSGGDTAASSSTS-----AMTAAATAAAAAVGSELLTQAAAAGASVVAQALPYT
LRMPSHGPFHVTTLTLPQLRASMERTSRTLRV--FAWGFGV-LGTALVV--RKLFAQLWR
LRQHRIGQRRMAEAEAVRRQRAAERAAA-AGVNGTAALAQAAAEEESGAR------NPGT
CVVCMDRDADVVFTGCGHLCACYGCS----TNLTKCPICRVNSRM-LRVY-R--------
-----P
>Capsella_rubella_gnl|BL_ORD_ID|20058 _v10020775m|PACid:20905831

M-----------------------IPWGGVTCCLSAAALYLLGRS--SGRDAEVLKTVTR
VNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNET
GSWVQDSALMLSMSK--EVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEES-GRSLVR
GTLDYLQGLKMLGVKRIERVLPTGIPLTVVGEAVKDDIGEFRIKKPDRGPF--YVSPKSL
DQLISNLGKWSRWYKYASMGFTVFGVFLITKHVIDSV-------LERRRRRQLQKRVLDA
AA--------KRAELETEGI----------------------------------------
--------------------------------H
>Capsella_rubella_gnl|BL_ORD_ID|21378 _v10020547m|PACid:20907165

M-----------------------MHLAGFTCCLGGVALYLLSRS--TGR---VVESINR
VCHLKDLEQLVDGESKVFP-LVIVSGTVGSETPIKCEYSDVLGVFVKKTAEQQVLRRNWR
FSWVRDRTFMQPMTK--EVPWYLDDGTGRVNVAVSQGEIGLALTVGSDVFEKSVPVSLVQ
GALSYLKGLQILGVRRIEHVVPIGTPLTVVGEAVKDGMGNVRIQKPEQGPF--YVSYIPL
DQLISKLGECSRKFKYASMGLTVLGVILLSKPVIRYILKRIEDYLERRRRQLLLNRVADA
AARRAEPVAPRRAEPVTRGLERQHENSSDGTSRYGDTPDLCVICLDRKYNAAFVQCGHMC
CCVRCSSQLSTCPLCREPIEQVLRIYR-----H
>Capsella_rubella_gnl|BL_ORD_ID|1198 _v10019584m|PACid:20886816

M-----------------------IQLGGLACCLSGSFLDYL-----SKIPASFVKSVTR
VRHIKDLEQLVPLESK----VVAVSGIVGSETPLKCKHSDMLCVFIEETAQQLFLKRNWM
FSWVPDCNWMVPITK--EVPWYLDDGTGRVNVE-ANKVRCFELKVGSKVFQESEPSSECH
------RGLEMLGVLRTERVLPIGTSVTIIGEAVKDSIGGFTIQESKEVPF--FVSSLPF
DELISSFGKWSRKLKYASIGFTVVGVVLILKPVVDYM-------LERRRRRLLRKRVADA
AV--------KRAKLVTRGLEAQD----------GDLLDLCVICLEHKNDAAFVRCGHMC
CCSICSLHVKTCPLCRRPIEQVLRIYR-----L
>Capsella_rubella_gnl|BL_ORD_ID|3249 _v10009854m|PACid:20888881

MESLCF-----------------LLDLAVYLSC-GGAAFYLRGRK--LQRKANYLGSITR
VLDLRCLDELLAENTTNL--LVVVSGRVGSAAPLNC--NGLLGVLVKEKAKLEGELELEN
GGSIETSFKFLLREK--ETPWYLEDSTGQVNVLGVQDAEGFYGILNEYVLDM--PASELL
NGVVLPQGTKVLKHNCHGRALNIGTFLTFVGEAVKDKAGNVMIQSPKEQPFRVYSGEGSF
DSMIDELKSVSEVNILIGKIFGTIAVALAVLYGVEYI-------RTVLLPFVWKKKELRN
RS--------KKPKSNSGKPHQRKESDTSSL-----------------------------
-----------------PIGLALLLVKDSDKDS
>Capsella_rubella_gnl|BL_ORD_ID|3812 _v10010078m|PACid:20889446

MGSQFFKSLLRVEKKTPIKDFEEEITPNAVACCLGGAAIYYLLRSWKCKRQAQILNRAVR
VEELQDLEDLIGNNNTSGL-LVAVCGKVGSNAAFMCNRSGLLAVSLTEKAKLVFPTEDEL
GFLDMDYEEILLSHKTVTVPWFLEDHTGRVNVV------GFYGTFRRNVFAE--PMNELC
------KEVEIVTHICSEDVLEIGRPLSIVAKAFRGEDGSPTI---KALPSLVFDGYICV
DKEVYNLQSQSGSCMHIAFFLAIIGVLLCEK-----------------------------
------------------------------------------------------------
---------------------------------
>Cucumis_sativus_gnl|BL_ORD_ID|5673 _084910.1|PACid:16956611

M---------------LPWGG-------------------------ISCCLSAAALYLLG
RSSGRDAELLKSVTRVNQLKELAQLLEAE-HLLPLVVA---------------ISGRV--
----SSDTPIN------------CEFSGLRGVIVEETAEQHFLKH-NDAGS---------
-------WIQDS--------------ALMLSMS---------KEVPWYLDDG-----TGR
AFVLGARN-----------------ATNFILPVVSEVFEESGRSLMRG--------TLDY
LQGL----KMLGVKRIERVLPTGTSLTVVGEAAKDDIGTIRIQRPHKGPFYVSPKTIDQL
ISNLGKWARWYKYASMGLSIFGLYL-----VTKHVILYLMERRRRWELQKRVLAAAAKRS
SQENEGEIEKASNGTD------------------------------GTKRDRSMPD--LC
VICLERDYNAVFVPCGHMCCCVACCSHLT-----NCPLCRRRIELVVKTFRH
>Cucumis_sativus_gnl|BL_ORD_ID|29614 _360260.1|PACid:16980714

MSTSEQALVTLLSRFALSFDG---------------------------AVLGAALAYATV
RT------VLKLTASCSALNELRKAPYVTVSDLRHIVSDGVSEQSESDRKLVVVRGTV--
----ETRSSVEGNRKSLQPNVLISQESGDRAVIIQRTQVCIFNEW-KGFFG---------
-------WTSDL--------------RAIFGRTFRKQESTSFRTVPFVLLEG---HSTYS
DFVVVNME-----------------GSRHPLPLTT--VYHQLQPVCAT--------PYTF
LQAVFGHEYPVGVLDEEKILPLGKNISAVGICSFEN-GVPVIKSCSDFPHFLCEMTKDQM
ILDLVFKTKFLFWSSIVLGSLTVGI--LGYSAARNWNRWKQWRQHRQLQNSRNDSPTSQL
DSSNDIPIYGDFASDDEAATVPDDELSSHVPDDELSSHVP------DDELSSHVPDGQLC
VICLMRRKRSAFIPCGHLVCCERCAVSVERESSPKCPICRQQIRSSVRIYDS
>Cucumis_sativus_gnl|BL_ORD_ID|21376 _255450.8|PACid:16972405

MGQQQSKDELLYQQ--VSYGNTEGIKALCRDGAGLEWIDKEAKTPLIVACMNPE-LHNVA
RT------LIELGANVNAYRPGRH----NGTPLHHAAKRGL----ENNVKLLLSNGANPL
IMNDDCQSPLDVARAKGHSNVVRTIES----------HICLFSGWLREFYGPGFLELLAP
QLVSRKVWAVILPCGARNLSKPFKLELAIYTSLQDAQPRTVVQLWKADLDQSKLQHSDPS
VMIVDNAA-----------------KTRLKLASGNENDKEQLQWFCNACKGITSMMHPTF
MSGNHGPGVSATAPPDSEDVELAMAINASIQSVIH--GRPPFPD----PNPSSEASTSSS
HTGPVGQTT----HSTKLGTNESEMNEAGQSITAN--------EHPQIQTNVTPP-----
DAVPSAPLAADEILDNGAIHYPSIDSSPIDLSSQTAHNAPLQAGEGKDEMSSS-----SC
VICLDAPVQGACIPCGHMAGCMNCLTEIK-SKKWGCPVCRAKIDQVVRLYAV
>Citrus_sinensis_gnl|BL_ORD_ID|2126 _1.1g019194m|PACid:18093191

MIPWGGISCCLSGAALYLLGRSSGRDAELLKTVTRVNQLKEL--AHLLDSGSKVLPFIVT
VCGRVGSETPISCEYSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLDD
GTGRAFVVGARGATGFVLTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERLLPTGTS
LTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELIENLGKWARWYKYASFGLTIFGTFL
IAKRAIHYILQRKRRWELHRRVLAAAAVKRSEQDNEGTNGQAENGSDGTQRDRVMPDLCV
ICLEQEYNAVFVPCGHMCCCIICSWHLTNCPLCRRRIDQVVRTFRH
>Citrus_sinensis_gnl|BL_ORD_ID|2039 _1.1g019204m|PACid:18093103

MISWGGISCCLSGAALYLLGRSSGRDAELLKTVTRVNQLEEL--AHLLDGGSKVLPSIVS
VSGRVGSETPISCEYSGLRGVIVEETTERHFLKHNDAGSWIQDSALMLSMSKEVPWYLDD
GTGCVFVVGARGATGFALTVGSEVFEESGRSLVHGTLDYLQGLKMLGVKRIGRLLPTGTS
LTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELLENLGKWARWYKYASFGLTIFGAFL
IAKRVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNGQAENGSDSTQRDRVMPDLCV
ICLEQEYNAVFFPCGHLCCCLICSSRLTNCPLCRRRIDQVVRTFRH
>Eucalyptus_grandis_gnl|BL_ORD_ID|29270 _H01525.4|PACid:23590991

MGEIRTLSSFECKYNHVDRLIKGMASEITTLRTKVKEHREAWVKRPLVGRASRDTLSLST
RPVPHILTSPLIVSDSSPPPYPSIVSCSRPSSSCSCPSSIPATSVPLRSGELVLAGHALV
AFRAPFGGGGLISVGGPRASVSCSWSARGSRSLPHMIPWGGLSCCLSAAALYVLGRSSGR
DAEALKCVFRVNQLKELAQLLDTECKVLPLVVTLCGRVGSDTPINCEYSGLRGVIVEETA
EQHFLKHNDAGSWIQDSALMLSMSKEVPWYLDDGTGRAYVLGARGASGFELNIASEVFEE
SGRSLVRGTLDYLQGLKMLGVKRIERLLPVGSSLTVVGEAVKDDIGTVRIQRPHKGPFYV
SPKTIDQLISNLGKWARWYRYASYGFTVFGICLIAKRAIQYIMERKRRWELQRRVLAAVA
RRSEQDTEGTDDKTKNAPDSAKRDRSMPDLCVICLEQEYNSVFVPCGHMCSCTTCSLQLT
NCPLCRRRIEQAV---------------------------------KTFRH
>Glycine_max_gnl|BL_ORD_ID|4091 _02g16860.1|PACid:16248331

M---------------IPWGG--LSCCL-------------SAAALYLLGRSSGRDAEIL
KSVTRVNQLKELAQL--LDAEILPLIVTISGRVSSETPIN-------------CEFSGLR
GVIVEETAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDDGTDR------
-VHVVGARGAAGFALPVGSEAFEESGRSLVRGTLDYLQGL----KMLGVKRIERVLPVGT
SLTVVGEAAKDDVGAFRIQRPHKGPFYVSPKTIDQLIANLGKWARWYKYASMGLTVFGAY
LIAKHAIRYILERRR---RSELQRRVLAAAAKKSGQNNDVEKA--DGLSDGVKKDR----
LMPD--LCVICLEQEYNAVFVPCGHMCCCTTCSSHLT-----NCPLCRRQIEKVVKTFRH
>Glycine_max_gnl|BL_ORD_ID|43458 _16g01030.1|PACid:16301042

MSHQEQAVLSLLSKLALSFDGAVLGVALAFAAVRTLFKFTATSASLRKLRRAPSISVSDL
RSL-----LAEPPSDA----D-AGEIVIIRGTVDAKSAVD-GTWKTLKPGVLVSRESGDK
GVILQRTQTCIYNDWKGLLGWTSDLRAICARSLRQQDSTSFRKVPFVLIDVGRRPNAEYV
VVNMDGSRH------PLPLTTVYHKLQPINASPYTFLQALFGHEYPVGLLDEEKILPLGK
DITAVGHCSLKN-GIAEIKSCKDIPYFLSDLSKDQMIVDLSIKAKILFWGGISLGSMSVG
VLGYAVLRNWIKWKRWKVQRQLQQQ-------------------RQAVSDAEPQVDDEIE
DVPDGQLCVICLMRRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRTYES
>Glycine_max_gnl|BL_ORD_ID|6360 _03g13060.1|PACid:16251643

MSHQEQAFVSLLSQLALSFDGAVLGLALAYAAVRTLFKFTATSAALRKLHRAPSVSVSDL
RSL-----LAEIPSDADGNSD-GGNIVIVRGTVDAKSTVEGGTWKTLRPGVLVSRESGDK
SVILQRTQTCIYNEWKGLFGWTSDLRAIFARSWRQQESTSLRKVPFVLIDVGRWPNAEYV
VVNMDGSRH------PLPLSTVYHKLQPITASPYTFLQALFGHEYPVGLLDEEKILPLGK
NITAVGLCSLKN-GIAEIKSCKDLPYFLSDLSKDQMIVDLSSKTKILFWGGIALGSMSVG
VLGYAVVRNWNKWKQWKQQRQLQQQ-------------------RQAVSDVEPQMDDEIE
DVPDGQLCVICLMRRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRIYES
>Linum_usitatissimum_gnl|BL_ORD_ID|34600 _10008163|PACid:23173780

M---------------MVPWGGISCCLSAA------------------------AFYLLG
RSSGRDAEALKSV-------TRVNQ-----LKELAKL-----------------------
---------------------------------------------------------FDV
------ENSLLPL-----------VVAISGRVGSET------------------------
------------------P--INCEFSGLRGVIVEETAEQHFLKHNDAG-SWIQDSTLML
SMSKEVPWYLD-----------------DGTD-RAFVLGARGASGFVLTLASEVFEE-S-
-GRSLVRGTLDYLQGLKMLGVKRIERVLPTGTSL-TVVG-----EAVKDDIGKVRIQR-P
HKGPFYVSPKNI-------DELIGNLGKWASLYKYASVGLTVFGAFLIAKQAVEYIMERR
RRWDLHKKVLAAAAAKRSGSQDTEGSNATAEDDSDASKR-DCIPDICVICLENEYNAVFL
PCGHMCCCTTCCSHLS-----SCPLCRRRIEQVVKTYRH
>Linum_usitatissimum_gnl|BL_ORD_ID|36037 _10003391|PACid:23175217

MGLLSG------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------LWA
------------------------ETEFSSRVGSEE------------------------
-----------------PP--IKCELSGQRGIIVKETVEHHFVKRSDDGKSWIRDKAKVL
TTRREVPWYLD-----------------DGSGVRAIV------NGFVLTKRREVFEEKS-
-ERSLVGGPLDRVEGLKMLAVNRIEWVLPIGEEL-TVVGCVTTCEKFGIWFGKIESKR--
----------AK-------VELTLELARLRRESQF-------------------------
---------------------------------DDGWRFGSIAGRISVA-----------
-------------------------------------SS
>Malus_domestica_gnl|BL_ORD_ID|18124 _0000238779|PACid:22638098

MLPWGGLSCCLSGAALYLLGRSSGRDAEILKSATRINQLKELAKLLDS-EFRLPVVVAVS
GRVSSETPINCEFTGLRGVVVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLDDGT
GRVFVVGARAATGFVLPVASEVFE---------------ESGRSLVRGTLDYLQGLKMLG
VKRIERVLPTGTSMSVVGEAVKDDIGTIRIQRPQKGPFYVSPKTIDQLIANLGKWARWYK
YASVGLTVFGVYLVAKHSIQYIIERKRRWELQKRVLAAAAK---RSGEDGEGILLRDPIT
MLFAIYAQKCTKRFYLFLPGSNEKDDGASD--------GNKRDRMMPD---LCVICLEQD
YNAVFVPCGHMCCCTTCSLHLTSCPLCRRRIDQAVKTFRH
>Malus_domestica_gnl|BL_ORD_ID|27598 _0000757393|PACid:22647575

MRIWEGVWWCLGALALYLPGWRFSSDADVLESVPRINPMSELAKLLEF--RRTPLVVGVS
GTVCCENPIHCEFAGLRGVVVMQTAAQRFLKRNEKGEWQMGYTSLLSECKEVPWYLDDGT
GRVNVVGATDASGFTFPASSGQFEQSRRCHKCEMNRLECETKRSVERERIDDREGIKLLG
VQRTEHVLPIGISLSVVGEAVKDNVGTIRIQKPHKGPFYVSTKSIDELIASHKNWARFLK
CASFGVAVIGLTLNAAELDKYIRERLRRSEWMRSRRRAAAVADIRSRQHNA---------
-------------------GSSDTRAVAADYIRSQRDNAGERAAAAPDGANSCVICLEQQ
YNVVFIPCGHMCCCTTCCSQLTECPLCRQPFSQAVRTFRP
>Manihot_esculenta_gnl|BL_ORD_ID|26209 _4.1_011064m|PACid:17986177

MLPWGG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ISCCL-----------------
--------------SAAALYLLGRSSGRDAEVLKSVTRVNQLKELAKLLDIESNISPSVV
SISGRVGSETPINCEYSGLRG------------VIVEETAEQHFLKHNDAGSWIQD----
----SALMLSMS------------KEVPWYLDDGTD---------RVYVVGARGASGFVL
TV-----------GSEVFEESGRSLVRGTLDYLQGL----KMLGVKRIERVLPTGTS---
LTVVGEAVKDDIGTVRVQRPHKGPFYVSPRTIDELIG--------NLGKWARWYRYASVS
LTVFGAFLIAKHAIQYIMERRRR--------------WELQSRVLAAAAAKRQGQDSE--
----------------------------------------------GSNGKAENGSDNSK
RE---------RPVPDLCVICLEQEYNAVFLPCGHMCCCTTCSSHLT-----NCPLCRRR
IEQVVKTFRH
>Manihot_esculenta_gnl|BL_ORD_ID|16192 _4.1_009144m|PACid:17976041

MSSHEQ------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------VLASLVSQLALSFDGAILGVAL
A-YAAVRSFLKFTSNSKALRKISKAPTLRVSDLRSVLDLPQPSDENQNQNVDQGQTQKLV
IVRGQVEPKSAVDGNWKSLRSNALVSHECGDKAVIIQRTQTCIYNEWKGFFGWTSD----
----IRAIFGRSWRE---QESTSLRMVPFVLVEGGRWPQS--DYVIVNIDGSRHA--LPL
TT-----------VYHQLQP----IDASPYTFLQALFGHEYPVGLLDEEKILPLGKE---
INAVGICSSRN-GVLEIKSCKDLPYFLSDMTKDQMVV--------DLAFKTKVLLWSGVV
LGSLSIGILGYAAVRN-WNRWKE--------------WRQH---------RQSQQQNH--
--------------AASTDDD---------PQID---------------------ADEEA
GD---------VPDGQLCVICLMRRRRSAFIPCGHLVCCQLCAISVEREVSPKCPLCRQA
VRNSMRIFEC
>Manihot_esculenta_gnl|BL_ORD_ID|18241 _4.1_006589m|PACid:17978120

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TQDQIDLLVEQVKMLAGE
IAFSTSTLKRLVEQSVNDPDSSKTQIQNMEREIQEKRRQMRVLEQRIIESGEASISNASL
VDMQQTVTRLMTQCNEKSFELELRSADNRVLQEQLQTKCSENKELQEKIKILEQQLASLS
YDKTPLTADHGVPGEYVDELKRKVQSQEIENEKLKIEQVQ----LSEENSGLRVQN----
----QKLAEEASYA----------KEL---------------------------ASAAAV
EL-----------KNLAGEVTKLSLQNAKLE---------KELLAAR-ESMHSRGTSMQN
INGVNRKYSDGMRSGRRGRLHGRGNEISSMHSDDFDSWSFGPEDLKMELQARKQREAALE
TALAEKEFIEEEYRKRAEEAKRR---EEALENDLANMWVL-VA-------KLKKEGGSSP
DVSTDERHSDG-NASEPKTNEVDQNIVLKERQVSDASKPPDENPKEEPLVVRLKARMQEM
KEKELKYLGNGDANSHMCKVCFEQATAAILLPCRHFCLCKSCSLACS-----ECPICRTK
ISDRLFAFAS
>Mimulus_guttatus_gnl|BL_ORD_ID|1784 _mgv1a009837m|PACid:17671176

M-----------------------------------------------------------
------I-PVGGITCCLSAAALYLLGRSSGRDADLLKSVTRVNQLKDLAQLLEAASKVLP
------------------LVVTVSGRVGSETPIN--------------CEYSGLRGVIVE
QTAEQHFLKHNDAGSWIQDSALM-----------LSMCKEVPWYL-DDGT---SRVHVVG
ARGA-----TGLVLTVGSEVFE--ESGRSLVRGTLDYLQGLKM-LGVKRIERVLPTGSPL
TVVGEAVKDDIGSIRIQRPHKGP-FYVTDKTIDQLIANLGKWSRLYKYASMGLTAFGVYL
LAK-------HAFQYIMDRRRLW----ETRKRVLDAAAKKAGQNE--GALNGEAEIGSDS
SNKER----PIPELCVICLEQEYNSVFVQCGHMCCCMACSSHL-----TNCPL-------
----------------------------H
>Mimulus_guttatus_gnl|BL_ORD_ID|5327 _mgv1a010644m|PACid:17674722

MDWSKLKMDL----------------------------SKLEI--------DLSKLEIDW
---SWLI-PVEGTVCCVVSAVLYAGGALVQGEAKELDSVVRVSKLKDLSQLLDAASTVFP
------------------LVVAVTGLVSSDTPIE--------------CEYSGLKGVIVD
NKEETHILRRNFRGVWKKESILP-----------ASVWNEVPWYL-DDGT---GRASVLD
ARSANTLTYAGLPMTCGGEVFE--RSIQSSIHEKIELDNGVKT-LGVQKTERVLPTGTCL
TVIGEVIKDETGAFAIQKPYRLPFYYISYRSVSEIIENLRSHSSVCMYASAAFGVMGGIL
IVR-------HAFRYMEYKKMQKR-EAELRRRLL-AAAKQASNK----------------
------------------------------------------------------------
----------------------------Q
>Mimulus_guttatus_gnl|BL_ORD_ID|11897 _mgv1a021515m|PACid:17681292

MEGNWLTIPILARTPASKIITTSSRPPMLRRRHPPQPQAKLATVHGGAVGAELGEVVRGW
WLSSWLLSPVDD---------------LRRWHAKDLESATRVSKLKD-------------
------------------------------------------------------------
-------LERNFRGEWKKESILP-----------SSVWNEVPWYL-DDGT---SRVRVAE
ARSVEDFTFTCLPMACGGEVFE--KSIQTPIQEKIQLDTGAKT-LGVHKIERVLPIGTCL
TVVGEVIKDEAGNFVIQKLYGGHPFYVSYRSVSEIIENFRETSRFCMYASAAFGLIGVVL
IAK-------HAFQYMEFKKMQK-------------------------------------
------------------------------------------------------------
-----------------------------
>Mimulus_guttatus_gnl|BL_ORD_ID|2783 _mgv1a007519m|PACid:17672175

M--------------------------SLHDRALTAVLTQLAMAADGA------------
------FIGVGVAYVAFSCFRKYAATSSALRKISQSASV----QPSDLRSILSDSDDSRP
SSSRRDDGDASSLNFDCGKLVFVSGSVEVKSALDKANWKSLRGTDLVVSHESGEKGVILQ
RIQTCIYNEWRGLFRWTADLGSMLMPRRITKENASSSMNMVPFILVEEGKWPPSDHVVVN
MEGSTH----PLPL---TTVYQHLQPVKASSYTVFQALVGLEYPVGLLYEEKILPLGKDI
TAVG-ICNLKNGIPEIKSCEDLP-YFLSILTKDQMIADLSFKSKVLLWSGLILGTVAIGV
LGYSISRN--------------------------WSKWKEWKARRAQQQQNASRIENLDE
TEEEESGDVPDGELCVVCLMRRRRSAFVPCGHLVCCHRCAFSVEREVSPKCPVCRQPIRN
SVRI----------------------YDS
>Medicago_truncatula_gnl|BL_ORD_ID|7454 _Medtr1g111550.1|PACid:17439105

MAMVPWRGVGCCLSAAALYLLGRTSGRD-----VDILKSVNRVNQLR------ELAQL--
LDEEIFPLVVAISGRVGSETPISCEFSGLRGVIIEETAEQHFLKH----------SDAGS
----------WIQDSALMQSRSNEVPWYLDDGTGRVRVVGAQGATGFVLPVGSEAFEESG
RLPVRGTSDYVQGLK------------MLGVKRIERVLPVGTSLTVVGEAAKDDVGTIRI
QRPSKGPFYVSPKTIDELIANIGRWARWYKYASAGLTVLSVYMIANHAVRYILERRRRNE
LEKRVLAAAAKISGQDNGGE--MDDSLSDGAKRERAMPNLCVICLEQEYNSVFVPCGHMC
CCTACSSHLTSCPLCRRQIEKAVKTFRH
>Medicago_truncatula_gnl|BL_ORD_ID|7458 _Medtr1g111580.1|PACid:17439109

M-------------------------KQ-----FVLLWFLIMVGILH------FSEQL--
LDVERLPLLVAISGNVVSETPIKCEITGLRGVIVEEREERHYLQR---DISIGQCKDAAT
QTQNGKIDIYWKNHSSLLSSNRKEVPWYLDDGTGRVLVVGARGGTDFVLPAGTSTFEKLE
QTQINETSDHIQLIK------------VKGLKRIERVLPVGTALTVVGQASKDDDGTIRI
QRPPKGPFYVSSKAIDEHAAKFVNYARSCEYTSTGLIVLGAFQIAARIYYLLHRRRRCSE
L-----------------------------------------------------------
----------------------------
>Medicago_truncatula_gnl|BL_ORD_ID|7456 _Medtr1g111560.1|PACid:17439107

M-----GGVVFCSAAAVLYTCSKYNHRN-----AEILKSVTQRFQQRLSLKMVTEKQL--
LDGERSHLVVAISGCVVSETPIKCELTGLRGVVVEETVVQHYLRECDANKLIMKCNDNGS
----------WLQNSPLTLYTRNEVPWYLDDGTGRVLV------------VGSETFEDSG
WARACKTLNHLQGVKVGVSAPLSASVSVVGLKRIEWALPFGTSLTVVGEASRDGDGTVRI
QRPPKGPFYVSRKTIDEQIADLTYFARRFKYASVGLTLFGAWLIAEFAIWCITKDGDAVS
CEK-VEIAPVDFSEGVGSQQ--VDSS----------------------------------
----------------------------
>Oryza_sativa_gnl|BL_ORD_ID|18392 _LOC_Os07g45350.2|PACid:21900864

MLIPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSTKDLAAILDTASKVLPLVVAV
SGRVGSDTPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDG
TGRVFVVGARGAAGLVLTVASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSL
TVVGEAIKDDVGTIRIQRPHKGPFYVSPKSIDQLIMNLGKWAKLYQLASMGFAAFGVFLL
AKRALQHFLERKRRHELQKRVHAAAAQRQAREAEGGNGTSD-VDSNNKKDQLVLDICVIC
LEQEYNAVFVPCGHMCCCMNCSSHLTN---CPLCRRRIDQAVRTFRH
>Physcomitrella_patens_gnl|BL_ORD_ID|11998 _Pp1s12_190V6.3|PACid:18048533

MLSWGGITLCLSGAALYCLSRNTGRDALNLRSIERVNQLKDLAILLESACKVVPLVVTVA
GRVGSETPIACEHSSLRGVILEETAEQHFLKHNDTGSWIQDSALMLSISKEVPWYLEDGT
GRVYIVGARNAAGMELTVASEVFEESGRSLVRGTLDYLQGLKMLGVKRVERVLPTGTNLT
VVGEAVQDDRGLIRIQKPNKGPFYVTPKSLDQLVANLGRWSRWYKYMSLGFTIVGIYFIT
SHAIKHFMERRRREALHRRVMEAAALRQASQREGGDGDMGDVTSHPLDDSVDTSQKKDRG
TPDLCVICLEQDYNAVFLPCGHMCCCTSCSAQLTSCPLCRRHIDKFVKTYRH
>Physcomitrella_patens_gnl|BL_ORD_ID|18939 _Pp1s175_124V6.2|PACid:18055474

MLSWGGITLCFSGAALYCLSRNTGRDALHLMSVERVNQLEDLAKLLESACTVVPWVVTVA
GRVGAEAPIASEHSSLRGVILEKSAEQHFLKHNDTGSWIQHSALMLSISKEVPWYLEDGT
SRVFIIGARNAAGMDLTVASESFEEYGGSLVRGTLDYLQGLKMLGVKRVERVLPTGTNLT
VVGEAVQDDRGLIRIQKPDKGPFYVTPQSQDQLIENLGRWSRWCQYMSFGLTLVGIYFIT
SRAIKHMLERWRREALLTRVMEAAALRKALQQEGVDEESDGVTAFPHDDNAHTAQKKDGG
MPSLCVICLEQDYNAVLVPCGHMCCCTSCSSQLSLCPLCRRHIDQVVKTFRH
>Prunus_persica_gnl|BL_ORD_ID|4153 _ppa008230m|PACid:17644506

MLPWG-------------------GLSCCLSAAALYLLGRSSGRDADILKSATRINQLKE
LAKLLDSEC------ILPLVVAISGRVSSETPIT------------CEFTGLRGVVVEET
AEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDDGTGR-VHVVGARGAT--
-GFVLPVASEVFEESGRSLVRGTLDYLQ---GLKM-LGVKRIERVLPTGTSLSVVGE-AV
KDDIGTIRIQRPHKGPFYVSPKTID-----QLIANLGKWARWYKYAS--LGLTVFGV--Y
LVAKHS------VQYILERRRRWEL--------QRRVLAAAAKRSGEDNEGSNEKDDNVL
DGSKR--LMPD--LCVICLEHEYNAVFVPCGHMCCCTTCSLHLT-----NCPLCRRRIDQ
AVKTFRH
>Prunus_persica_gnl|BL_ORD_ID|845 _ppa018270m|PACid:17641146

------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DDGTGR-VNVVGAQGAS--
-GFNLPASSGVFEQSRRCLKCETTDYRP---GHKV-LGVKRTEWVLPVGTSLSVVGE-AV
KDAVGTIRIQKPHD--LYVCASFVC-----VFL----------KYAS--FSLAFIGL--T
LIALEF------NENIMGRQSRFEL--------QRSLT----------------------
------------------------------------------------------------
-------
>Prunus_persica_gnl|BL_ORD_ID|16287 _ppa006914m|PACid:17656817

MSSHEQALISLVSQLALSFDGAILGVALAYAAVRTVLKLNSVSSALRKLHNAPSV-QVSD
LRSILSLDHSDESQPSDAKLVVVRGTVEAKSAVDGNWNILNSGVLVSQGTKERAVVLQRT
QTCVYNEWKGFVGWPSDLRAIFSRSWRERESKVFRTVPFILAEGGRRPISEFVAVDMD--
-GSRHPLPLTTVYHHLHPVNPSPYTFLEALFGHRYPVGLLDEEKILPLGKEISAVGLCSV
KD--GVLEIKSCKDFPYFLSEMSKD-----QMVVDLTSRTKVLFWSGIFLGSVSIGVLAY
AVSRNW------NRWKVWRQQR-EL--------QRSIRASNAEAQIQEEEEEEDAGD---
--------VPDGQLCVICLMRRRRSAFIPCGHLVCCQLCSISIERDVAPKCPVCRQQIRT
SVRIYDS
>Prunus_persica_gnl|BL_ORD_ID|11467 _ppa010006m|PACid:17651932

M---------------------------------------------RVEAHATTLNKLQ-
-------------------VVMLKGEQKIEILEP------------EHTSSQDGLASEET
-------------------------------KIGKEAEYNIEEDDKYYLDIINTKPRGII
ITLNVNVSSTMYDITKAKAICSTTK-----------------------------------
----GSCRLRLVFPNTHYVILTTPNNGYLGDWYIELSFVARVVTYIAI-LGFIVVTI--F
LILKYLGACDGESSTVVERVEE-EVNETYPIVPQKNMRRTYG----TNEEDEEDPGASSS
SSEE----LYDEKLCIICYDEQRNSFFVPCGHCATCYDCAQRIMDGENKVCPICRRLIHK
VRKLFNP
>Populus_trichocarpa_gnl|BL_ORD_ID|16447 _POPTR_0014s13410.1|PACid:18222628

M-----------------------------------------------------------
------------------------------------------------------------
------------MIPWGGISCCLSGAALYLLGR---SSGR---YLPSLI-----PLFFLI
ISSKLLDIESKVLPL-VVAISGRVGAESPIS--------------CEFSGLRGVIVEETA
EQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDDG-----TDRVYVVGA---
---------------------------------------RGASGFVLTVGSEVFEESGRS
LVRGTLDYLQGL----KMLGVK---RIERVLPTGTSLTVVGEAVKDDIGTVRIQRPHKGP
FYVSPKSIDELIGNLGKWARWYKYA-----SLGLTVFGAFLITKHVIRYIMERRRRWELQ
SRYV-SLV-------EGIHDKMFQGKGHANGAKRERPIPDLCVICLEQEYNAVFLPCGHM
CCCITCCSQLSN-----CPLCRRRIEQVVKTFRH
>Populus_trichocarpa_gnl|BL_ORD_ID|16448 _POPTR_0014s13410.2|PACid:18222629

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MLSMS---------KEVPWYLDDG-----TDRVYVVGA---
---------------------------------------RGASGFVLTVGSEVFEESGRS
LVRGTLDYLQGL----KMLGVK---RIERVLPTGTSLTVVGEAVKDDIGTVRIQRPHKGP
FYVSPKSIDELIGNLGKWARWYKYA-----SLGLTVFGAFLITKHVIRYIMERRRRWELQ
SRVL-AAAKRSGQDNEGSNDKAENG---SDGAKRERPIPDLCVICLEQEYNAVFLPCGHM
CCCITCCSQLSN-----CPLCRRRIEQVVKTFRH
>Populus_trichocarpa_gnl|BL_ORD_ID|12209 _POPTR_0003s06390.1|PACid:18218320

M-----------------------------------------------------------
--------------------------------------------------------ASRA
HEQALAAMLSHLALSFDG--AILGAALAYAAVRSFLNFTANSKSLAKIRKAPTLSVSDLR
SLLQNHDQDHQDQEQKLVIVRGQVEAKSAVDGSGKKSSRDSNVLLSHESGDKAVILQRTQ
TCIYNEWKGFFGWTSDLRSIFGRSLKEQETTFLRTVPFTLVEGGQWPQSDYVIVNMD---
---------------------------------------GSSHPLPLTMVYHQLQ----P
IVASRYTFIQALFGHEYPVGVL---HEEKILPLGKCISAVG-ICNSKDGIPEIKSCKELP
YFLADMTKDEMVADLAFKAKILLWSGIVLGSLSIGVLG-FAVMRNWNKWKAWRQRRSQQP
IHTTSDEDVSQIDDNEDAGDV---------------PEGQLCVICLMRRRRAAFIPCGHL
ACCHTCAVSVESEVSPKCPLCRQAVRNSIRIFEC
>Populus_trichocarpa_gnl|BL_ORD_ID|32327 _POPTR_0001s16880.1|PACid:18238703

M-----------------------------------------------------------
--------------------------------------------------------SSRS
HEQALAALLSQLALSFDG--AILGAALAYAAVRAILNYTANSKSLAKISKAPTLSVSDLR
SLLQNHDQDHQDHEHNLVIVKGIVEAKSAVEWTWKESFRPPKVLLSHNSAYKAVILQKTQ
TCIYNEWKGFLGWTSELRAIFGRSLKEQETTLLRTVPFILVEGAQWPRSDYVIVNMV---
---------------------------------------GSAHPLPLTTVYHQLQ----R
IAASRYTFIQALFGHEYPVGVL---HEEKILPLGKCISAVG-ICNSKKGIPEIKSCKDLP
YFLADITKDQMVADLAFKAKIQLWSGIFLGSLSIGVLG-FAVMRNWNKWQAWRQRHSHLP
NHTTIDADVSRIDEDE-AGDV---------------PDGQLCVICLTRRRRSAFIPCGHL
ACCHFCAISVESEVSPKCPLCRQAIRNSIRVFEC
>Populus_trichocarpa_gnl|BL_ORD_ID|41746 _POPTR_0008s16740.1|PACid:18248213

MGQQQSKDELLYQQVNYGNIGGIKTLCSQGAGLEWIDKEGKTPLILACLNPQLFDVAQTL
IELGANVDAYRPGRNAGTPLHHAAKRGLENTVKLLLSRGANALVTNDDCQTPLQVARAKG
HSIVVRAIESHICLFSGWLREFYGPGFLEVLAPRLVSRDVWVVVLPTGSRNPR-RPYKLE
LAIYSRLQDAQP--------RTIVALWKANLEEMKFHHSDPSVMIVDNSTKTQIKLAPAN
ESDKQQLQWFCDACKGIQQVM------HPPAFLHNSQAPAVQATAPPSAEDIEIAMAMNA
YIQSAAERPIFDPHSSAGASSSTSWSYPVNTGSQVALETPAAPPPKVTISELALHETGAT
SSSTQQTKIQNS----SIADVQTATDAQDSVPSAPPI--VDEIVED--GPIHYPSIDSSP
IDTSSLSVENLPENTG--------------------------------------------
-------------------------------EKREDGGSSSCVICLDALVEGACIPCGHM
AGCMSCLKEIKAK-KWGCPVCRAKIDQVVRLYAV
>Panucum_virgatum_gnl|BL_ORD_ID|33311 _Pavirv00039228m|PACid:23789376

MMI------------------PWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKD
LAAILDTASKVLPLVVAVSGRVGSD---TPLICQQSGMRGV-----IVEETAEQHFL---
-KHNDAGSWIQD---------SAVMLSVSKEVPWYLDD-------GTGRVYVVGARAAAG
LILTVASEVF---EESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDV
GTIRIQRPHKGPFYVSPKSIDQLILNLGKWAKLYRLASMGFATFGVFLLAKRAIQHFLER
KRRHELQKRVFNAAAQRQARESEGGNGTSDTEPNS-KKDQLVLDICVICLEQEYNAVFVP
CGHMCCCMACSSHLTN-----CPLCRRRIDQAVRTFRH
>Panucum_virgatum_gnl|BL_ORD_ID|26684 _Pavirv00002727m|PACid:23782682

MWL------------------LLVLRLTCLAFVGI-------------------------
----------------------------TDLLEEAEGCQGIRGSKRTEDEDGTEHITVRK
KENNNAEQWIRC---------SEQISSKRKEVPWYLDD-------GTGRFEVVRAHNADG
SVLRLASDDF---ETQPRTCGCEC-----SIRILGLRRTEWTLPTGTNLTVVGEVITQPE
HEL---------------------------------------------------------
------------------------------------------------------------
----------------------------MDPGIR--KE
>Panucum_virgatum_gnl|BL_ORD_ID|48680 _Pavirv00039347m|PACid:23804892

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLTVSGQLRLVASAA-ASSIAD
LRSLL-PGSGGEPRLAAVRGYVRPKPGGMILQPPFSGEHGV-----ITKHTQMCLFT---
-EWRGIFGWTFDLHALLFRSWKEQIVTSFRTVPFVLASSEIGNPIGMVHINVEKADPNQP
LPLTTVFHKLIPIETTPYALFQTIIGNGYPIALL---DEEKILPIGKELTAIGLCRAKDE
-SVEISSCPDLPFFLSELTKDEMQAQLASRARTLFWGSIVLGTLSVCLVGHAIYRCWKRI
KLRREARQ------AQQLFEEAEDAI----QEGDSSDEEVGDGQLCVVCLRRRRKAAFIP
CGHLVCCCKCALRMEREAEPLCPMCRQDIRYMMRIYDS
>Panucum_virgatum_gnl|BL_ORD_ID|10708 _Pavirv00062728m|PACid:23766539

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQLRLVASAA-ASSISD
LHSLL-PGSGGEPRLAAVRGYVRPKPGGTILRTPFSGEHGV-----VTKHTQMCLFT---
-EWRGIFGWTFDLHALLFRSWKEQIVTSFRTVPFVLASSEIGNPIGMVYINVEKAD--QP
LPLTTVFHKLIPIETTPYTLFQTIIGNGYPIALL---DEEKILPIGKELTAIGLCRAKDE
-SVEISSCPDLPFFLSELTKDEMQAQLASRARTLFWGSIVLGTLSVCLMGRAIYRCWKRI
KLRREARQ------AQQLFEDAEDAI----QEGDSSDEEVGDGQLCVVCLRRRRKAAFIP
CGHLVCCCKCALRMEREAEPLCPMCRQDIRYMMRIYDS
>Phaseolus_vulgaris_gnl|BL_ORD_ID|17669 _091029254m|PACid:23548376

-------------MKMIPWGG--LSCCLSAAALYLLGRSSGRDAEILKSVTR-----VNQ
LKELAQLL--DAEILP---LIVTISGRVGSETPISCDF------------SGLRGVIVEE
TAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDD---GSDRVHVVGARGA
TGFALPVGSEAFEESGRSLVRGTLDYLQGL----KMLGVKRIERVLPVGTSLTVVGEAAK
DDVGTIRIQRPHKGPFYVSPKTIDQLIANLGKWARWYKYASMGLTVFGAYLIAKHAIRFI
LERRRRSELQRRVLAAAAAKKS-GPNNDVEKADSLSDVAKRDHLMPD--LCVICLEQEYN
AVFVPCGHMCCCTACSSHLTN-----CPLCRRQIEKVVKTFRH
>Phaseolus_vulgaris_gnl|BL_ORD_ID|21270 _091018531m|PACid:23552061

MSHQEQALVSLLSQLALSFDGAVLGFALAYAAIRTLVKFSATSA-ALRKLRRAPYLSVSD
LRSLLADTPSDANSNSDGGAIVIVRGNVDAKSAVDGSWKTLRPGVLVSRESGDRGVILQR
TQTCIYNEWKGLFGWTSDLRAIFARSWRQQESTSLRKVPFVLIDVGWRPSTEYVVVNMDG
SRHPLPL-TTVYHKL-QPINASPYTFLQALFGHEYPVGLLDEEKILPVGKDVTAVGLVSL
NN-GVAEIKSCKDLPYFLSDLSKDQMIVDLSIKTKILFWGGIALGSMSVGILGYAVVRN-
WNKWKQWKLQRQLQQQRQAVSDVEPQVDDEIED-----------VPDGQLCVICLMRRRR
SVFIPCGHLVCCQGCAISVEHEVAPKCPVCRQEIRNSVRIFES
>Ricinus_communis_gnl|BL_ORD_ID|8077 _29703.m001546|PACid:16806242

M----------------------------------RNAEYSKTTFGKGLDAEALKSVTRV
NQLNELAKLLDIESKVLPLVVAISGRVGSETPIN----------------CEYSGLRGVI
VEETAEQHFLKHNDAGSWIQDSALML---------SMSKEVPWYLDDG---TDRTFVVGA
RGASGFALTVGS-----EVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGTSLSVIG
EAVKDDIGTVRIQRPHKGP-----FYVSPKTIDELIGNLGKWARWYRYASVGLTVFGVFL
IAKHAI---QYIMERRRRWELQSRVLAAAAKRQGQDSDGSNGKAENGSDSSKRERPIPD-
-LCVICLEQEYNAVFLPCGHMCCCTACSSHL-----TNCPLCRRRIEQISASIPVKDSCQ
GTDFLFHPRIRCKILPIAAIAYNWK
>Ricinus_communis_gnl|BL_ORD_ID|8129 _29706.m001280|PACid:16806294

M-----SSHEQALASLVSQLALSFDGAFLGVVVALTAVRSILKFASNSKALRKIRNAPTV
KVSDIRSVLEVSDETQDQKLVIVRGQVEAKSAVDGNWKSLIPNN--NVLVAHESGDKAVI
VQRIQTCIYNEWKGFFGWTSDIRAIFGRSWREQESTLSRSVPFVLVEAGRWPQSDYVIVN
LDGSRHPLPLTTVYHQLQPIDASPYTFLQAFFGYEYPVGLLDE---EKILPLGKEINAVG
LCGSKN-GILEITSCKDLP-----FFLSDLSKEQMVVDLAFKTKVLFWSGVVLGSFSICI
LGYAAVRNWNRWKAWRQQRQFQQ------QSNSVSDAD------VSQIDVEEETVDVPDG
QLCVICLMRRRRAAFIPCGHLVCCQICAISVEREVSPKCPLCRQAVRNS-----------
--------------IRI-----FEC
>Sorghum_bicolor_gnl|BL_ORD_ID|8897 _Sb02g041380.1|PACid:1959657

MMIP--------------------------------------------------WGG---
------------------------------------------------------------
-----------------VGCCLSAAALYLLGRSSGR------DAEVLRSVAR--------
-AGSMKDLAA-----ILDTASKVL--------PLVVA---------VSGRVSSD-TPLIC
QQSGMRGVIVEE----TAEQHFLKHNDAGSWIQDSAVMLSVS---------KE-VPWYLD
D------GTGRVYV-V-----------GARSAAGLILTV---------------------
--ASEVFEESGRTLVRGT-LDY-L-QGLKMLGV-----------------KRTERVLPTG
TS----------------------------------------------------------
----------LTVVGEAIRDDV---------GTIRIQR----------------------
------------------------------------------PHKGPFYVSPKSIDQLIM
NLGKWAKLYRLAS----MGFA-------------------TFGVFLLAKRAIQHF-----
----------------LERKRRHELQKRVLNAA---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------AQ
RQAREAEGSNGSSDT---------------------------------------------
---EPNSKKDQL-VLDICVICLEQEYNAVFVPCGHMCCCMACSSHL-----TNCPLCRRR
IDQAV--RTFRH
>Sorghum_bicolor_gnl|BL_ORD_ID|4679 _Sb01g045370.1|PACid:1954575

MSARDRE-----------------------------------------------------
------------------------------------------------------------
-----------------TAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAV--------
-SGQLR-LVASAATASIGDARSLL--RGDGNEPRIAA---------VRGYVRTQGSFLRA
PFSSEAGVVVKH----TQMCLFTEWRGIFGWTFDLHALLFRSWKEQIVTSFRA-VPFVLA
STELGN-STGVVHINV-----------DEVDYQPLPLTT---------------------
-----VFHK----LIPLETTPYTLFQTIIGNGY-------------PIALLDEEKILPIG
KK----------------------------------------------------------
----------ITAIGLCRAKNA---------ESVEITS----------------------
------------------------------------------CPEIPFFLSELTKDEMQA
QLASRARILFWGS----IVLG-------------------TLSVCLVGHAIYRGW-----
-----------------KRIKLRREARQA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-QQMFEDAEDAIREDN--------------------------------------------
---SSDDDDDDVGDGQLCVVCLRKRRKAAFIPCGHLVCCCKCALRMEREVEPLCPMCRQD
IRYMI--RIYDS
>Setaria_italica_gnl|BL_ORD_ID|40388 _Si030396m|PACid:19714000

MMI------------------PWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKD
LAAILDTASKVLPLVVAVSGRVGSD---TPLICQQSGMRGVIVEETAEQHFL--------
---------------------KHNDAGSWIQDSAVMLSVS---------KEVPWYL----
-DDGTGRVYVVGARAAAGLILTVASEVF---EESGRTLVRGTLDYLQGLKMLGVKRTERV
LPTGTSLTVVGEAIKDDVGTIRIQRPHK-GPFYVSPKSIDQLILNLGKWAKLYRLASMGF
ATFSVFLLAKRAIQHFLERKRRHELQKRVLNAAAQRQAREAEGGKGTSNTEPNS-KKDQL
VLDICVICLEQEYNAVFVPCGHMCCCMACSSHLTN-----CPLCRRRIDQAVRTFRH
>Setaria_italica_gnl|BL_ORD_ID|5804 _Si039161m|PACid:19679179

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-DDGTGRLEVVRAHNADGSILRLESVDF---EKQPRT-----CGCECSIKILGLRRTEWT
LPTGTNLTVVGEAVKGNSGEILIKRPRNGGPFHVSRSSIDKIVSNLGSDARY--------
------------------------------------------------------------
---------------------------------------------------------
>Setaria_italica_gnl|BL_ORD_ID|11123 _Si036246m|PACid:19684534

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQLRLVASAATA-SIAD
LRSLLPGDGG-EPRVAAVRGYVRPKPGGNILRVPWSGEHGVVTKHTQMCLFT--------
---------------------EWRGIFGWTFDLHALLFRSWKEQIVTYFRSVPFVLASSE
IGNPIGMVYIDVEKAAQPLPLTTVFHKLIPIETTPYTLFQTIIGNGYPIALL---DEEKI
LPIGKELTAIGLCRANDEGSVEISSCPE-LPFFLSELTKDEMQAQLASRARILFWGSVVL
GTLSVCLVGHAIYRGWKRIKLRRE--------ARQAQQLFEEGEDAIQE--DDSSDEEVG
DGQLCVVCLRKRRKAAFIPCGHLVCCCKCALRMERETEPLCPMCRQDIRYMMRIYDS
>Selaginella_moellendorffii_gnl|BL_ORD_ID|15488 _231449|PACid:15416766

MLPWG-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------G-------------
--------------------------ITMC---------------------------LSG
VAL----YFLSRNSGRD-------------------------------------------
------AATLKAVRRVDQLKDLAHLLDSACK-----AVPLVVTVAGRV------GSETPI
GCDHSSLRC---VILEETAEQHFLKHNDTGSWIQDSALML----------SNNKEVPWFL
EDASGR------------------------------------------------------
------------------------------------------------------------
------VFIVGARGAAGLELT-------------IASEVFEESGRSLVRGTLDYLQ----
GLKMLGVKRVERVLPTGTALTVVGEAIKDDQGTLRIQRP--------HKGPFYVTPKSID
QLI---------------------------------------------------------
------------------------------------------------------------
-------------------------------ANLGKWSRWYKYMSLGFTLFGVFLVA---
----------------------------------------------------------SH
TIRYVMEKRRR-------------------------------------------------
-----AALNRRVMEAAARRRERKEHEGK--------------------------------
--AQVGEFAKVET-------------------------ATKRDGRLPD--LCVICLEQEY
NAVFVPCGHMCCCISCS--------AQLQNCPLCRRRIEQIVKTYRH
>Selaginella_moellendorffii_gnl|BL_ORD_ID|11999 _91152|PACid:15413277

MASHD-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------EEICAALTRLAMAGDG-------------
--------------------------IVLG---------------------------LGM
AALALRTWLKFGSHTRA-------------------------------------------
------LKQVEGTAQV-EIHDLRSLVESGEKEPSSDSSPPLVIVRGRVALPPKTSSEEVL
LARNQTDLA---VFVERTQTYLFNEWRGLFRWGPEWRGLLGWGSLKEQVAFSRRKIPFVL
LDSDPQYDGAC-------------------------------------------------
------------------------------------------------------------
------VHINMENVEHPLPLV----------------TVFHQL-HPVQTSSSTFLQAVFG
RRYPVGVIDEEKILPLNREITAVGFLSKHPQGLPAIKSS--------NQMPFFLTEFSRE
ELI---------------------------------------------------------
------------------------------------------------------------
-------------------------------VELASATHALFWTGIVISSLALGVIG---
----------------------------------------------------------YS
AFKNWCKWKEWRRL----------------------------------------------
-----RQIQE-------------ELRRE--------------------------------
--EQVMEEDEEPA-------------------------TTQEGSEVPDGQLCVVCLLRRK
RAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSGYIRVYD-
>Selaginella_moellendorffii_gnl|BL_ORD_ID|14317 _180753|PACid:15415595

MQALS-------------------------------------------------------
----------KLNSPSSTLSASFSSSTTTTTSSSSDLGSGTTKF---NKENVTVTVRFRP
LNSREIQKGDEVAWYADGDTSVCSEYNASTVYAFDKVFGPATTTRGVYDIAAQQVVSGAM
EGVNGTVFAYGVTSSGKTHTMHGDQKSPGIIPLAVKDVFNIIQESPGREFLLRVSYLEIY
NEVINDLLNPAGQNLRVREDSHGTYVEGIKEEVVLSPAHALSLIATGEEHRHVGSNNLNL
MSSRSHTIFTLTVESSARGEGSREEEVTLSQLNLIDLAGSESSKAETVGLRRKEGSYINK
SLLTLGTVISKLTDGKSSHIPYRDSKLTRLLQSSLSGHGRVSLICTVTPASSSNEETHNT
LKFAHRAKHVELHSSANKILDEKSLIKKYQKEITSLKQELEQLRKGMVGKPFVEGTNDDV
IQLRQQLEAGQVKLQSRLEEEEQAKAALLGRIQRLTKLIL---------VSTKNTIP-NL
PDRPTHRRRYSFGEEEVYDELDVDLPELSSDGKSESANGDDVHKDDKKPKKRGMLGWFKT
KKHEQLHSRTDSDIPSPTG----RLDDNTATKRKPLMRVKSDELADAFLEPTQAGELFSA
AVYGRRPPPTGTTMADQMDLLKEQVKMLAGEVAFCSSSLKRLSEQSALTPDDGDIQVQMK
RLKEEISMKRQQMQVLERRILGSVENAPANTP--QLSQTMMKLTSQLNEKSFELEIKAAD
NRILQEQLQSKNVENTELQSTIHSLKQQLQQAVAEKKASIHKKAGSDSHKKGHSFFDSEE
TSEWLNDVDLSRELRMVENGGDANFAQGFASKIIPGAGFPLQSQLFSQMNEIEKLKLEKT
RLAEEKTMLEAKGQKLMDEAAYAKELATAAAVELKGLAEEVTKLSAQNAKLSTEVEALR-
----------SKAAGEEKSRREGVSMDQDMIQQLRAELSEAKRKVASLEQN-------EA
TLNRRIEEGKEREADLENDLAGMWVLVAKVKQEKERDEF-EILGNGNGLESGLLTSKNNA
HVEDESPVEELQCQLEAARTKVAELELGNSQLKGENLESLDLSALESLQNLHVEALTRLC
QAKTKAQERLEREKRRSMEERALSRSQADSLSSIGVQHLLLEEERNGH--VCKVCFEAPT
AAVLLPCRHFCLCKSCA--------IACTECPLCRSGITDRIITFT-
>Selaginella_moellendorffii_gnl|BL_ORD_ID|9807 _83012|PACid:15411085

MASTSASSRRSSSPFRFRRPSSVNGRIPGFQPASPSSISSPSSTGRASLGGGGGGSHRSL
TPTRSRSSSQALMTPPSMKYSSFNGGSSPFTPSSSSSMFDRVEFINRAKESISVTVRFRP
LSSREIQKGDEVAWYADGDTTVRSEYNLATFYAFDRVFGPATTTRGVYDIAAQHVVAAAM
QGVNGTVFAYGVTSSGKTHTMHGDQKSPGIIPLAVKDVFSIIQDTPGREFLLRVSYLEIY
NEVINDLLDPAGQNLRVREDAQGTYVEGIKEEVVLSPAHALSLIAAGEEHRHVGSNNFNL
FSSRSHTIFTLTIESSCRGEDFSDDEITLSQLNLIDLAGSESSKTETTGLRRKEGSYINK
SLLTLGTVISKLSDGKASHIPYRDSKLTRLLQSSLSGHGRISLICTITPASSSTEETHNT
LKFAQRAKRVELHAAPNRILDEKSLIKKYQKEITHLKQELEQLRRGLFERPFVVSNHDDL
LTLRQQLEAGHLKMQSRLEEEEQAKAALMGRIQRLTKLIL---------VSTKNTIPLSL
PEKSTQRRRHSFGEEE--------------------------------------------
-KHESMHAVPEEHTPSGSSVSFEPPVDFKSRRRKSFSR-KPDEL----------------
------PPITGTTMADQMDLLREQMKMLAGEVALCSSSLKRLSEQAVTNPEDDQLHMQMR
KLKEEIDEKRRQMSIIEKRIAGSAEASSTNASGFEMSQTISKLISQLHEKAFELEIKSAD
NRILQEQLQSQTNEINELQETVVSLRQELQ-------ASLEKRYSQPKSRK---------
---------LSRTL----------------------LDFSITLICLLQAAELTKLKKDYT
HLLEVKDGLYLENQNLNEEASYAKELASAAAVELKHLADEVTKLSLQNSKLNSELAAAEA
SAYRTGTATVSKANANKMGRNPGA--DEDIL------LDDCELLPKESSRN-------YQ
ELEKKLEESRQREVSLESDLANMWVLVAKLKKEKEEAEAGRKFSTENGHTDGNGELTINE
ETEQWGTLKELKVYLKDEKQRVSEMERFISQL----------------------------
--KTRIQEEKERE------------SSNDPAPAPASIDEIFDEDRGSH--VCKICFEAPT
AAVLLPCRHFCLCKPCA--------VACSECPLCRSSITDRIITYTS
>Selaginella_moellendorffii_gnl|BL_ORD_ID|19695 _77786|PACid:15420973

MHSDE-------------------------------------------------------
----------------------------------------SVDY---GKENISVTVRFRP
MSEREIHRGDNAAWYVDGDI-VRSEFNPSVAYTFDKVFGASATTRNVYDTVARNVVRGAM
EGINGTVFAYGVTSSGKTHTMHGDQNYPGVIPQAIKDVFSIIQETPDREFLLRVSYLEIY
NEVINDLLDPAGQNLRIREDAQGTYVEGVKEEVVLSPSHALSLIAAGEEHRHVGSNNFNL
FSSRSHTIFTLTIESSLRAQG-PDDEVTLSQLNLIDLAGSESSKTETTGLRRKEGSYINK
SLLTLGTVIAKLSEGKASHIPYRDSKLTRLLQSSLSGNGRITLICTITPASSNMEETHNT
LKFAQRAKRIEIYAAPNRIMDERSLIKKYQKEITKLKQELLLIKRGMTERPYATTNQEDL
LTLRQQLEAGQLKMQSRLEEEEQAKAALMGRIHKLTKLIL---------VSTKNNLSGSF
PD-AAHNRRHSFAESE--------------------------------------------
-ERYDEQSDLDTSSFPPDRCTDSCSIDLGNGQEH--------------------------
------FNICLQDIADQIDLTREQVKMLAGEIALRSSSLKRLSEQAANHPDD--FQVQIG
KLRDDIEDKKSQMQLLEQRITELGERSSYP----EMSQAIEKLTSQLNEKAFELEIRTAD
NRVLEEQLQSKV--------TFWFLKASHQKIVL-----------------------GPQ
TTNCLIEANDAGERLCAE--------KAIKTVVSHQENYPKKKE--TEDAEIEVVSQERS
RLSEENNCLQMKNVKLEEEACYARDLAAAAATEIKDLTEQIKKLVFQNTRLSNEALSIT-
CQGKTGRISVSSVDRRLM--IPYA------VQALKEELRSKREKQAYLEQTVSEKQALEK
ELKRKLDESKQREADLENDLASMWVLLAKMKTNDPPTSGPVQDVVE--ITECRPERNVST
AV---APISPQSVESAANIQKIKEQHQELERL----------------------------
--RTSGSEDKE----------------TDDLKA-----LLYDEDKHAH--VCKVCFEAAT
AAVLLPCRHFCLCQPCA--------VACTECPLCRSSISDRIVTFAS
>Thellungiella_halophila_gnl|BL_ORD_ID|8267 _Thhalv10008106m|PACid:20187792

MIPWGGVTCCLSAAALYLLGRSSGRDAEVLKTVTRVSQLKELAQLLELDSSKLLPFIVAV
SGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDG
TSRVNVVGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGMPL
TIVGEAVKDDIGDLRIQKPERGPFYVSPKSLDQLISNLGKWSRWYKYASMGLTVFGVFLI
TKHVIDSVLERRRRRELQKRVLDAAAKRAERESEGSNGTHESVSDSTKKEDAVPDLCVIC
LEQEYNAVFVPCGHMCCCTACSCHLTSCPLCRRRIDQVVKTYRH
>Volvox_carteri_gnl|BL_ORD_ID|2800 _Vocar20010130m|PACid:23126664

MGE---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------LADRPSSWLNFVSYG
GLASLG---ISAVLFQLAKL--QDGRVFE-LDRAQALETLASICRPDHI-------LPLL
VAVRGRITCREPAVCQLSGVPAVMRELVEEEVYFKEQH-TGRTSQECFEIRREQEQREAF
LEDRTGSIRLENLQHASGLPGVM--EVKQEFRHADLLQGTLLQAVLSKALKSMVKHGVRV
TER----------YLPVDTAVTVVG------------ELVADCMGSTAAAAAGCR-----
-----TRPAAGGSGNPLLASSSQQQPSDVSGSGVEAA-----------------------
------------------------------------------------------------
--AAADVARTATGGGGGTGSLSAAATAVAAAAGAEL------------------------
-------------------LGQAALQALPYTLRMPGRGPFHVTTLTL------PQLRASL
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------ERTSGVIRAFAWGFGLLGAAL------FVRKAAQAYHRLQAYRRYKRYA
ALAEAARRTAAAGG----------GAAAGMGTSAAT------------------GATAGD
DDGD---------------------------------GVRSPGTVTSRTIRV-----F--
--------------------RP
>Vitis_vinifera_gnl|BL_ORD_ID|6424 _GSVIVT01011070001|PACid:17823049

M-----------------------------------------------------------
--------------------------------------IPWGGISCCLSAAALYLLGRSS
GR----------------------------------------------------------
------DAEALKSVTRVQQ-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------LKDLVQLL--------DTACKVLPLVVTVS----------------
------------------------------------------------------------
--------------------------------------------------------G---
---RVGSDTPIK------------CEYSGLRGVIVEETAEQHFLKHNDA----GSWIQDS
ALMLSMS---------KEVP--------------WYLDDDTGRAYIVGARGATGLVLTVG
SEVFEESGRSLVRGTLDYLQGL----KMLGVKRIERV-----------------------
---------------------------------------LPTGTPLTVVG-EAIKDDVGT
IRIQR------------------------------PHKGPFYVSPKS--IDHLVA---NL
G---------------KWARWYRYAS-LGFTVFGVYLIAKSAIQYVMERKRCWELRK---
----------RVLAAASKKSGQDSEDPDEKDENGSDNTKRDRLMPDLCVICLEQEYNAVF
VPCGHMCCCTMCSSQL-----TNCPLCRRRIEQVVRTFRH-----
>Vitis_vinifera_gnl|BL_ORD_ID|146 _GSVIVT01000174001|PACid:17816771

MWL---------------------------------------------------------
--------------------------------------IPAGGL----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------RGIGLKEVKRL-----------------------
---------------------------------------TSMSTAIEGLGQEKLHFRVLT
SPV----------------------------------------------QDDQIAWYYAI
S---------------FVARLVAYVSTLGLLVIFIFLILKYFGDFGSETTTFEEEVRETE
TNPLLPSKRVPFTYGACEEDLESGEGNGGSSQDLYDG--------KICVICFDEPRNCFF
VPCGHCATCYVCAQRIAKGDNSVCPVCRRFIRKVRKFIVQ-----
>Zea_mays_gnl|BL_ORD_ID|14577 _GRMZM2G020574_T08|PACid:20834303

MMIPWGGVGCCLSAAALYLLGRSSGSDAEVLRSVARAGSMKDLAAILDTASKVLPLVVAI
SGRVGSDTPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDG
TGRVYVVGARSAAGLILTVASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSL
TVVGEAI-KDDVGTIRIQRPHKG-PFYASSKSIDQLIVNLGKWAKLY-RIASMGFATFGV
FLLAKRALQHFLERRRRHELQKRVLNAAAQRQAREAEGSKGTSDAEPNS-KKDQLVLDIC
VICLEQEYNAVFVPCGHMCCCVACSSHLTNCPLCRRRIDQAVRTFRH
>Zea_mays_gnl|BL_ORD_ID|23792 _GRMZM5G871572_T01|PACid:20843518

MMIPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKDLAAILDTASKVLPLVVAV
SGRVGSDTPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDG
TGRVYMVGARSAAGLILTVASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGISL
TVVGEAI-KDDVGTIRIQRPHKG-PFYVSPKSIDQLIMNLGKWAKLY-RLASMGFATFGA
FLLAKRAIQHFLERKRRHELQKRVLNAAAQRQAREAEGSIGSSDTEPNS-KKDQLVLDIC
VICLEQEYNAVFVPCGHMCCCMACSSHLTNCPLCRRRIDQAVRTFRH
>Zea_mays_gnl|BL_ORD_ID|14579 _GRMZM2G020574_T06|PACid:20834305

MMIPWGGVGCCLSAAALYLLGRSSGSDAEVLRSVARAGSMKDLAAILDTASKVLPLVVAI
SGRVGSDTPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVMLSVSKEVPWYLDDG
TGRVYVVGARSAAGLILTVASEVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSL
TVVGEVLFLLSIGMCCVALVFLGMSIFVSSFCSILLLYHMNRPLKMMLELFEFSDRTKDP
FMHHQRALINLL------------------------------------------------
-----------------------------------------------
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
