>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|6149 641255358 AM1_6306 response regulator [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------QLTTPQA----------------------
--ANILIVDDNLNNLKVLVGILSDSPYKIRRAVTGDIALQC------ITAAPPDLIML--
----DIILPDFSGYEI--------------------------------------CAKLKQ
DPETASIPIIF--------MSALSSNADKVKAF--TVGGADYITKPFE------------
-------------------------------------STEVKARIRNQLQLRAAQAQVKL
L--TAELEKMRTVQISQSG-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------NN
>Anabaena_variabilis_ATCC_29413_gnl|BL_ORD_ID|521 gi|75812808|ref|YP_320425.1| flavin oxidoreductase/NADH oxidase [Anabaena variabilis ATCC 29413]
M-----------------DL----------------------------------------
-----------FTPLIIRDITLPSRVAMSP--MCQYSAENGFANDWHFVHLGSRAVGGTG
LIMVEATAVTPQGRITPGDLGLWDDKQIEPLTRIVRF-----------------------
---LRQQGSVTGIQLAHAGRKASCNVPWLGGTPLTPEQ--------GGWQPVAPSPIPF-
--QENAPVPISLD-----ERGIQETIFAFVAAAQRALQVGFQM----IEIHAAHGYLL--
----HSFLSPLSNRRT----------DRYG-----GSLENRMRLLLE-------VVRRVR
DVLPNGMPLFV------------------------RISATDWVEGGWDLQQSIILS----
REL----KTLGVDLIDVS-------------------TGGLVPHARIPVEKGYQVPFAAK
I--REEAGIMTGAVGLINEAEYA------------DQI---------ITRGCAD------
--------------------LVLIGRELLRNPYWSIYARC-----------SLDEEPNWP
VPYGYAV-----KR---------------------QR-----------------------
--------------R
>Synechococcus_sp_JA_2_3B_a2_13_gnl|BL_ORD_ID|1069 637875498 CYB_1096 putative nicotinate phosphoribosyltransferase [Synechococcus sp. JA-2-3Ba(2-13)]
MLSPDFSSLRPQDYGLLTDLYQFTMAACYVGEGLESQPAAFELFVRRLPTDYGYLIAMGL
TQAVDYLQQLSFAPEALRALRETGIFADAPERFWELLARCRFEGDVWAVPEGTAIFANQP
LLRVEAPLW--QAQLVETYLLSTFNYQTLIATKAAR------------------------
---MRDAAGDEAILLEFGTRRA-----------FGPQA--------GLWAARAALAAGF-
--NATSNVLAALKLGRKPAGTMAHSLVMAIAALSGDETRAFQS----FRRYFPQAALL--
----IDTYDPIQGARTAAQLFAARSPDQLGSQGEIGGVRIDSGDLED-------LSRRVK
QILPQGAPVFVS-------G-----DLDEYEIE--RLHRSQAPISGYGVGTRLVTG----
EGVNGVYKLVEINGIPVAKASFAKATLPGRKQIFRGPEGDLLGHADEPPPPGYE-PLLRK
V--MEK--------GLLLDPLPD------------LEA---------IARTSRA------
--------------------SVLCLPQGVR---------------------QLRQPDPWP
TALTAAL-----QR---------------------LKDHTLGQECASA-G----------
-------------PA
