>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|6149  641255358 AM1_6306 response regulator [Acaryochloris marina MBIC11017]

------------------MQLTTPQAANILIVDDNLNNLKVLVGILS-DS---PY--KIR
RAVTGDIALQCITAAPPDLIMLDIILPDFSGYEICAKLKQDPE-----------------
-----------------------------------------------------TASIPII
FMS-ALSSNADKVK-----------------------------------AFTVGGADYIT
KPFESTEVKARIRNQLQLRAAQAQVK----------------------------------
-----------------------LLTAELEKMRTVQISQSGNN
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGT
SRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLT
IVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLIT
KHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICL
EQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>Anabaena_variabilis_ATCC_29413_gnl|BL_ORD_ID|521  gi|75812808|ref|YP_320425.1| flavin oxidoreductase/NADH oxidase [Anabaena variabilis ATCC 29413]

MDLFTPLIIRDITLPSRVAMSPMCQYSAENGFANDWHFVHLGSRAVGGTGLIMVEATAVT
PQGRITPGDLGLWD-DKQIEPLTRIVRFLRQQGSVTGIQLAHAGRKA-----SCNVPWLG
GTPLTPEQGGWQPVAPSPIPFQENAPVPISLDERGIQETIFAFVAAAQRALQVGFQMIEI
HAAHGYLLHSFLSPLSNRRTDRYGGSLENRMRLLLEVVRRVRDVLPNGMPLFV-------
-----RISATD----WVE-----------GGWDLQQSIILSRELKTLGVDLI--DVSTGG
LVPHARIPVEKGYQVPFAAKIREEAGIMTGAVGLINEAEYADQIITRGCADLVLIGRELL
RNPYWSIYARCS-----------LDEEPNWPVPYGYAVKRQRR
>SP1_NM_105064
-----MIPWGGVT----------CCLSAAA--------LYLLGRSSGRDAEVLETVTRVN
QLKELAQ----LLELDSKILPF--IVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLK
HN----ETGSW--VQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFE-
--------------ESGRSLVR--GTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKD
DIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWS-RLYKYASMGFTVLGVFLITKHVIDSV
LERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAV----PDLCVIC---L
EQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>Cyanothece_PCC_7425_gnl|BL_ORD_ID|497  gi|220905952|ref|YP_002481263.1| unnamed protein product [Cyanothece sp. PCC 7425]

------------------------------------------------------------
-------------------------------------------------MDMPNLMPQQT
QPIH----RTTTG-----------------------------------------------
------------------------------------------------------------
----------------------------QLPAELAELSEESLTHSSSVLPSIPSLCCIC-
--DTNV----CVLICVVL-------------------------
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGT
SRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLT
IVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLIT
KHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICL
EQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSETPIKCEHSGIRGVIVEE-TAEQHFLKHNETGSWVQDSALMLSMSKEVPW--FLD
DGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGI
PLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVF
LITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKE-----DAV
PDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>Cyanothece_PCC_8801_gnl|BL_ORD_ID|703  gi|218245500|ref|YP_002370871.1| hypothetical protein PCC8801_0627 [Cyanothece sp. PCC 8801]

MRP-------------VIRGEVKDKNTD----FTKYEDAK-------------PYLIKNI
GEYCS----YCERRVTNLLAVEHIQPKEHYPEL------------------ELVWGNFLL
ACTNCNSIKGQKN-----INLSDYFW--CNRDNTFRVFTYFDGV--VNINNQLTLIEQNI
-----GKKTIDLIGLDRV--PGHRKYSNKDTRWQKRRDIWGKAQRSYDN-----------
----------LQNNNTEELRQTIVDLA-----LES-GFWSIWMTVFNDDKDMLKRFIEAF
PGTCQNCFDQDFNAVPRPGGIV-----------------------------
>Cyanothece_sp_BH68_ATCC_51142_gnl|BL_ORD_ID|5037  641679458 cce_4951 hypothetical protein [Cyanothece sp. BH68, ATCC 51142]

------------------------------------MKSDEAGVRLYFD-----------
---GGTFPLNPGHGGCGAVIIQENDEQSFSKYLGENITNNQAEYGGLILGLEKAL-----
--EMNISSLEVKGDSELVICQVIGSYRCRNSGLRPLHRQAISLAKQFEHIHFDWIPREIN
KKAD-AAATEAIQSVLPQSKAIIPDNLPLCKAREGLKKRINRLNQQGDGAKFKEWIQL-K
SGRDQFSSLRGARLHEAVPDSVIDAISQALIEDEQDLLDKSLRWY------LRGLKPALA
LKKARVDAE--------------------------------ISANITRKKSAL-------
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSETPIKCEHSGIRGVIVEETAEQHFLKH---NETGSWVQDSALMLSMSKEVPWFLD
DGTSRVHVMGARGATGFALT--VGSEVFEESG-RSLVRGTLDYLQGLKMLGVKRIERVLP
TGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGK---------WSRLYK
YASMGFTVLGVFLITKHVIDSVLERRRRRQL--QKRVLDAAAKRAELESEGSNGTRESIS
DSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|1747  637459140 glr1748 hypothetical protein [Gloeobacter violaceus PCC 7421]

M---------------------AVSLKQAFEVGKYLISQRLAGRERFPLVLMLEPLFRCN
LACPGCGKIQHPGEILRRN----------------LTPEECSRA------VEECGAPIVT
IPGGEPLLHPQIDQIVEGLVDRGKFVYLCTNAILLEKNLDKFTPSDYFSFSVHLDGLREE
HDQAVDREGVFDIAMRAIKAAKARGFRVTTNTTIFNNADPQRVREFFDFLGGLDIDGM--
--MVSP----------------GYSYEWAPDQEHFLQRDQTRALFREILAPYRSGEARWN
FNHNPLFLDFLEGLKDYECTPWGMPSYSVLG----------------------------W
QKPCYLLNEGHYATWQELLDNTRWEDYGHASGNPK-CRDCM--------VHCGYEQTAAI
DAMEIANIP----RVLASVITGR-
>SP1_NM_105064
M----------IPWGGVTCCLSAAAL--------YLLG-RSSGRD----AEVLETVTRVN
-------QLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQ---
----HFLKHNETGSWVQ------------DSALML--SMSKEVP--WF------------
LDDGTSR-------VHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKR
IERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKS-------LDQLISNLGKWS
--------------RLYKYASMG---FTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAA
AKRAELESEGSNGTRESISDSTKKED-----AVPDLCVICLEQEYNAVFVPCGHMCCCTA
CSSHLTSCPLCRRRIDLAVKTYRH
>Lyngbya_sp_CCY_8106_gnl|BL_ORD_ID|2306  640016327 L8106_19221 formate dehydrogenase accessory protein [Lyngbya sp. CCY 8106]

MSAAKSKKKSNIWTIEESQIRSRLDDIATEEPLEIRLVSPAQTLAVTMRTPGADFDLVTG
FLYSEGVITSREDISKMSYCVDPDIDGEQRQNIINVALKSGLTFDFKRLERHFFMTSACG
VCGKASIESLKFRELPQISSDFNVNTEIIYRLNDQLKLAQGLFSATGGLHAAALF---NS
QGKLLKLREDVGRHNALDKLIGSSLLTDDLPLAHHIVMVSGRSSFEILQKCIVAGV----
----------------------PILCAVSA------------------------------
---------------------------------PSSLAVEIA------------------
--------------------------QAFNITLIG-FL-----------RGRRFNI----
-------------------------------------------YSGI-------------
-----------ERIKLA-----S
>SP1_NM_105064
MIP---------WG----------------------------------------------
------------------------------------------------------------
-------------------------------------------GVTCCLSAAALYLLGRS
SGRDAEVLETVTRVNQLKEL--AQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVI
VEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGS
EVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDR
GPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQKRV
LDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTAC
SSHLTSCPLCRRRIDLAVKTYRH
>Synechococcus_sp_JA_2_3B_a2_13_gnl|BL_ORD_ID|1069  637875498 CYB_1096 putative nicotinate phosphoribosyltransferase [Synechococcus sp. JA-2-3Ba(2-13)]

MLSPDFSSLRPQDYGLLTDLYQFTMAACYVGEGLESQPAAFELFVRRLPTDYGYLIAMGL
TQAVDYLQQLSFAPEALRALRETGIFADAPERFWELLARCRFEGDVWAVPEGTAIFANQP
LLRVEAPLWQAQLVETYLLSTFNYQTLIATKAARMRDAAGDEAILLEFGTRRAFGPQAGL
WAARAALAAGFNATSNVLAALKLGRKPAGTMAHSLVMAIAALSGDETRAFQSFRRYFPQA
ALLIDTYDPIQGARTAAQLFAARSPDQLGSQGEIGGVRIDSGDLEDLSRRVKQILPQGAP
VFVSG-----DLDEYEIERLHRSQAPISGYGVGTRLVTGEGVNGVYKLVEIN----GIPV
AKASFAKATLP-GRKQIFRGPEGDLLGHADEPPPPGYEPLLRKVMEKGLLLDPLPDLEAI
ARTSRASVLCLPQGVRQLRQPDPWPTALTAALQRLKDHTLGQECASAGPA----
>SP1_NM_105064
MIP----------WGGVT--------CCLSAAAL-------------------YLLGRSS
GRDAEVLETVT----RVNQLKELAQLLELDSKILPFIVAVS-------------------
-------------------GRVGSETPIKCEHSGIRGVIVEETAEQHFLKHN----ETGS
WVQDSALM--LSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSE--VFEESGR-----
SLVRGTLDYLQGLKM------------LG------------------VKRIERVLPTGIP
LTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFL
ITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDL---
------CVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>Synechococcus_sp_RS9917_gnl|BL_ORD_ID|2480  638963667 RS9917_02056 FAD linked oxidase, N-terminal [Synechococcus sp. RS9917]

MTQ--------GSAGLQAL-------------------QAELAPLPQL------------
------------------------------------SLLQGEADLLRFSRDAYDY-----
-------------------SPVLRER-LSHCRAGL----------VVRPESVAAVRAVAA
ACARHGVPLTLRGAGTGNYGQCVPLQGGVVMLMGALSAVRAIDPHSGVVEVESGCLLRDL
DQAVAGHHRQLRLLPSTWRTATIGGFIAGGSGGIGSVRWGFLRDPGHLLGLEVVTLEAEP
RLLQ---LDAADAEALNHAYGTNGIITALRLSTAPRQAWHELSIDCADWE---VAVDLAQ
RCQQAALELHL--CTVLERSIVDQLPNWSGAPAGCHRLLLLVAADGVSTVERLAAAVGAV
CRHLGPEADHHGNGLRELSWNHTTLHCRSLDPSWTYLQMLLPQPELPLLNQLRADWGDDL
LWHLEGVRQGGTARLAALPLVRWQGGDALERLIAQCRDLGAVIFNPHVITVEDGGLGVID
GEQVAAKRHHDPMGLLNPGKLRGWSA
>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVS
GRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGT
SRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPT-----
-----GIPLTIVGEAVKD----------------DIGEFRIQKPDRGPFYVSS----KSL
DQLISNLGKWSRL----YKYASMGFTVLGVFLITKHV-------------IDSVLERRRR
RQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGH
MCCCTACSSHLTSCPLCRRRI---------------------------------------
------------------------------------------------------------
-------------------------------------DLA--------------------
---VKTYRH-----------------
