>QUERY_Prochlorococcus_sp_CC9311_gnl|BL_ORD_ID|1836 @Prochlorococcus_sp_CC9311@ 638115460 sync_1872 possible Arginine repressor, C-terminal domain [Prochlorococcus sp. CC9311]
M------------HHDLLALNSNWNLSQTDPSTRVPLVSLDEALERSSLKKGISRRDFLA
ELLKDVQHQRLLPLLAMLPRRWRQEPASLPEQLRGLGNLLGEGLMSPLLLAAFADDLQHL
LPQR---TNPRRSALDLWCQRTY-NNPGSQQWPLPEGLETWRSQAAESLKSQNERLKPK-
-GRSGLTGLTSLGGEIAWSNHGLSYLQSAEARHRNQQMAQVFNVLGSNLLVEQ-----NL
NVDTYRFEGQSSGKDLIQCLQSKGWRCQARVRTSVASFGLGAS---TPSSDSNQWNQIPL
AVPYRTGLQETNQKEINALLPHACLELELQPPEDDTV-LLQYYQGTEGLNGWAAMNDLDR
PWQNGRSNGSVQYSPTVFRDQQLSDAVELCELMGAIHNSEAGMENLHLGGYGAIGFCIDS
TALLEYALTGQTNLFPLTLGGLWRERLSAQLNHLLEQNMRPND-----DAVDRYKRAIED
MPQDLYHTSVTRTDARRRLLASQPSYSPFLLIQDLNLQKS---------
>gnl|BL_ORD_ID|769 @Prochlorococcus_sp_WH_7803@ 640543123 SynWH7803_0770 hypothetical protein [Prochlorococcus sp. WH 7803]
M------------ADDLLKLSDSWGHSQGDGTDIAPLVPFEQALESSSLRRNISRDDFLK
STLTQLNHQRLIPLLFMLPRRWRLQPAALPQSLRNLGGVLEHGLLSPLLLAALADDLQHL
IAHEGKRQPAKKNAMDRWCQRSI-DLDDGSSRLLPTNL-----IALQSISSPDSAPPSP-
GAGALARVAKGFSAELQWRNEGLPFLQPENARLRNRALAQVLNVLGSNRLPPP-----PG
SSEPFRFESCDRSSALITHLIAGGWQCRARFRASVASFGLGAS-----TRDGDQWSQIPL
AVPYRTGLCDSQGEERRALLPHCSLEMELQPDHGEPF-LLQYYQGTEGLNGWAALNDLNR
PWQNDRSNGTVAYPGPELTGETLSAALDLCDLMGAVHNSAAQQNRLVIGGYGALGYCIDS
TAMLEVAVRQTTHLFPLTLGGLWRQRLDDQLNQLLENGLKASA-----ETVERYRQSLDT
TPQDLFVNRNTVNDANRRLLASQPPHSPFALVRSLNGESTAKP------
>gnl|BL_ORD_ID|769 @Synechococcus_WH_7803@ gi|148239106|ref|YP_001224493.1| hypothetical protein SynWH7803_0770 [Synechococcus sp. WH 7803]
M------------ADDLLKLSDSWGHSQGDGTDIAPLVPFEQALESSSLRRNISRDDFLK
STLTQLNHQRLIPLLFMLPRRWRLQPAALPQSLRNLGGVLEHGLLSPLLLAALADDLQHL
IAHEGKRQPAKKNAMDRWCQRSI-DLDDGSSRLLPTNL-----IALQSISSPDSAPPSP-
GAGALARVAKGFSAELQWRNEGLPFLQPENARLRNRALAQVLNVLGSNRLPPP-----PG
SSEPFRFESCDRSSALITHLIAGGWQCRARFRASVASFGLGAS-----TRDGDQWSQIPL
AVPYRTGLCDSQGEERRALLPHCSLEMELQPDHGEPF-LLQYYQGTEGLNGWAALNDLNR
PWQNDRSNGTVAYPGPELTGETLSAALDLCDLMGAVHNSAAQQNRLVIGGYGALGYCIDS
TAMLEVAVRQTTHLFPLTLGGLWRQRLDDQLNQLLENGLKASA-----ETVERYRQSLDT
TPQDLFVNRNTVNDANRRLLASQPPHSPFALVRSLNGESTAKP------
>gnl|BL_ORD_ID|2526 @Synechococcus_sp_RS9916@ 639889746 RS9916_27834 possible Arginine repressor, C-terminal domain [Synechococcus sp. RS9916]
M-----TEQGNARMPDPLALSSAWGASPGDQTDIAPLLGLNAVLETSWLRKGISRDHFLT
ELLTDLHQRRLVPLLAMLPKRWRLGAAALPDHLRKLAELLEGGSVSPLLLAALADDLHHL
FPVQDNATGATADALKRWTATTVQPGPDAAGQPLPQSLKAWKEQADHGQHEQ--------
AHNAAAGGLRQLGADLVWQNHGLQNLQSAASRWGNTLMAQVFNALGANHLPPSVRGT-SG
RDTPFLFEGVSTSQQLLELLRTRGWSCKARVRASVASFGLGASCPNTAATTT-TWLQVPL
AVPYRTGLLD-QGEELEALLPHCSLELELTPPDAQAPTLLQYYQGTEGFNGWAAMNDLHR
PWQNDRTNGSVAYPGEPIEAAQLDLALDLCDLMAAVHNSAATQGKLRTGGYGALGFCIDS
TALIEQALTGRCHLFPLTLGGIWRERLREHLEQLLDQGLRVID----DTSVERYRQALDT
LPCDLHLHGNACAGALERLRASQPAHSPFLLVRRLNGEEHRR-------
>gnl|BL_ORD_ID|1012 @Synechococcus_sp_RS9917@ 638962170 RS9917_10556 possible Arginine repressor, C-terminal domain [Synechococcus sp. RS9917]
M-------------ADLLALSGQWGAREEDRTALAPLLPFPAVLEDSWLRRGIQRDAFLR
ELLQGLHQRRLIPLLAMLPRGWRLAPAALPEKLRGLGSLLEEGLVSPTLLAALADDLQHL
LPAGDPDNAAGTTALSRWTARQVVNPEDGSRQALPQSLQQWQELAHQPAMEPTPWPPAK-
AGSMSAPNLRSLGAGLTWHNQGLAPLQPAHCRQANRLLAQVFNALSANRLPDAARGATAA
AVEPFQFEGVVSTAALMALLRSRGWSARARVRSSVASFGLGAS---TAAEDG-TWHQIPL
ALPYRTGLLR-HGLEIESLLPHCCLELELQPPEAAEPVLLQYYQGSEGLNGWAAMNDLDR
PWQNDRGNGTVAYPGPAFEAEHLDLALDLCDLMAAVHNSTAAAGQLRFGGYGALGFCIDS
TALLEQALTGRSTLFPLTLGGIWRERLAQQLERLLNTGLSTASTSHGDEAVERYRDALQR
LPQDLSLQGEAALRAEARLIRSLPTHSPFVCVRALNGEAAAETSLSDPL
>gnl|BL_ORD_ID|1840 @Prochlorococcus_marinus_MIT_9303@ 640087364 P9303_18551 possible Arginine repressor, C-terminal domain [Prochlorococcus marinus MIT 9303]
M-----AEETPH-SLNPLALSQSWGQDEHDDIHTAPLIALEEVLETSRLRRGISREQLLS
ELLRDLDHRRLIPLIGMLPRGWRIAPAVLPERLRGIATLLEDGLLSPLLLAALADDLQHL
LPTPENQPP---SALELWRQPSV-ALKPGHGVGVPSNLKNCRLLANQPITSDALFDRKQL
GRTPLGKGLTAVGSGLVWHNEGLVMLQNESSQRMNELMAQVLNCLAANRLPE-----ALH
HSEPFLFEGLSSGRQLIELLNRQGWHCCGRIRASVASFGLGAS---QAKGRG-RWLQVPL
AMPYRTGLEDDRNQEILSLLPHCSFELELQ-PQDNDSILLQYCQGIEGMNGWVAMNDLHR
PWQNDRHNGTVAYPSQPSTQQRLADAIEITELIAAVHNVEASSQKLHLGGYGALGYCIDS
TALLEQCLNGSTHLFPLTLGGIWRERLRRRLDILLDQGFCINT-----SVVDRYRWGLDT
LPQDLNLQGSARLEAMQRLSSCQPSHSPFALVRSLNGEVDL--------
>gnl|BL_ORD_ID|429 @Prochlorococcus_marinus_MIT_9313@ gi|33862702|ref|NP_894262.1| arginine repressor domain-containing protein [Prochlorococcus marinus str. MIT 9313]
M-----AEEIPH-SLNPLALSQSWGQDEHDDIHTAPLIALEEVLETSSLRRGISREQLLS
ELLRDLDHRRLIPLIGMLPRGWRMAPAVLPELLRGIATLLEDGLLSPLLLAALADDLQHL
LPIRENEPP---SALELWRQPSV-ALKPGHGVGVPCNLKNCRLLANQPITSDAFSDPKQL
APTALGKGLTALGSGLVWHNEGLVMLQNESSQRMNELMAQVLNCLAANRLPE-----ALH
PSEPFLFEGLSSGRQLIELLNRQGWHCCGRIRASVASFGLGAS---QANESG-RWFQVPL
AIPYRTGLEDDRNQEILSLLPHCSFELELQ-PQGNDSILLQYCQDIEGVNGWTAMNDLHR
PWQNDRHNGTVAYPSQPLTQQRLADAIEITELIAAVHNMEASSQKLHLGGYGALGYCIDS
TALLEQCLNGSTHLFPLTLGGIWRERLRRSLDILLDQGFCINT-----SVVDRYRWGLDT
LHQDLSLQGSARLEAMQRLLSCQPSHSPFALVRNLNGEVDL--------
>gnl|BL_ORD_ID|1592 @Synechococcus_RCC307@ gi|148242692|ref|YP_001227849.1| hypothetical protein SynRCC307_1593 [Synechococcus sp. RCC307]
M--------------DPLQLDPAWPSA-------VPLLDLETALEQSLLQSGLSRQDYIK
RLVQDLHKPRLQPLLWLLPRRWRLAPAQLPQQLHGLAQLLERGLLTPSLLAVLGDEMAQL
LPQPDQAT----TPLERWSG------------AGESSLKPWSEVMALSQSDAPA------
DATGAEAKASHLAPGLVWNNLGLHYGQNQARRQANSAAAQWLNHHAAR------------
----------GGSRELIETLQQRGWQIKARFRASVASFGLGAC---FRSQASDSWQQIPI
GLPMRSGLLDQNGQEITMLLPHSAVEMELCGEGCEL--LLQFYQGTEGICGWEALNDLQR
PWQNDRHNGTVRYMGEPWQGSNLLELMDLTDVMALVHNSVASELQLRWGGYGSVGYCIDT
TALVQQALLDQCDLFPLLLNGIWRERLLRTSQRLPAS-----------SALQRYQKALME
LPLDLSHHGSSSTEAWQRLQGCQPLSSPFCLSQHIQHAPNDVTAVAL--
>gnl|BL_ORD_ID|1793 @Synechococcus_sp_CB0205@ 650132433 SCB02_010100009145 hypothetical protein [Synechococcus sp. CB0205]
MGRPMASGSPLASVVDPLQLDPDWSCS-------VPLLAFEDALDQSVFRSGLTRSDWLK
RLAHQLHKPQLLPLLWLLPKGWKLAPADLPQRLQTLGGLVERELLTPALLGAVADALPHF
L------NGEHAAAMGRWRGQ--------QDAELPSSLEQLLQLNPSSTDPT--------
DPQVGNTEAERLSGGLIWHNAGLHHEQSASERERNALAARVLNRLAANALEQ--------
--DQWQIDGASSCRAWFSRLQQEGWSLQAQLRASVASFGLGAS---LPNPEG--CSQVPL
ALPIRTGLLGEGEQDIQGLLPHSCLELEWRRGNDLI--RLQYYQGTEGLCGWEALNDLHR
PWQNDRVNGTIRYLGEPFCAERLLEVMDLCDIMALIHNQQSDADALWLGGYGALGFCIDS
SAVLQQAMDGRCDLFPCLLGAIWRERLLQRARGLQLQQESQH------RARERYCRALTE
LPHDGFCFAEGSRDAKRRLKASQPQSSPFRLTQQALVL-----------
