>Rickettsia_akari_str_Hartford gnl|BL_ORD_ID|412    gi|157825538|ref|YP_001493258.1| unnamed protein product [Rickettsia akari str. Hartford]
-----MSDLFSNVNNSFVQYMKYP---VVLSIVI-----------CFCLVAC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------VEQPPAPIEYKVGDVT-----------
---------ANNNSTALEHDEG--------------------------------------
------------------------------------------------------------
-----------LIVQRTMEDDTVSEK----------------------------------
---VSGILEEPKAKII--ECYNDDIEIPISRN----------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------EYEEE-----------IEQSNFVKPLNG--VMLT---------------
----------------------------------------------E-FKD---------
GKSKG---IDIAV----KEYS--------------------------------DVKSIAA
GTVIYSGFN-KQFGNLVI-------VKLDKDD--LEVAYASLDDLLLKKGDKIT---KNS
VIGHV----------KHKLYFAMRR-----------------------------------
------------------------------------------------NRIAVDPSKYIE
----------------F
>Anaplasma_centrale_str_Israel gnl|BL_ORD_ID|285 gi|269958541|ref|YP_003328328.1| peptidase [Anaplasma centrale str. Israel]
-----MR--------------------VVALIAA-----------SFLLYGC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------FTQDPAPVSLRGEEF----YGNRERD
ESVDYRLTRDYSERGAATTAASKRKVLVR-------------------------------
------------------------------------------------------------
---------------------DISTR----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------G
APPSSTKLKQTSKPSP-----------SKECEFGMPLDGGKVVHT---------------
----------------------------------------------P-SSD----SGKAP
YCNDG---VAIFA----DGIA--------------------------------KVKAAGS
GKVMYVGKGLRWYGSLVI-------LEHN-KY--TISLYSYLHEVHVKIGDKVK---KGQ
VIATITKSSQS-ADSGYFFCFAMRR-----------------------------------
------------------------------------------------NGKPVNPVQYIK
------------KCKSK
>Ehrlichia_chaffeensis_str_Arkansas gnl|BL_ORD_ID|339 gi|88658571|ref|YP_507175.1| M23/M37 peptidase domain-containing protein [Ehrlichia chaffeensis str. Arkansas]
-----MT--------------------IRKTLLI-----------VLLCFGC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------TQKPAPSFLRGEEF----HGKKELD
DINEYHLVR---------------------------------------------------
------------------------------------------------------------
--------------HDVKKDENIESH----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
IQDNHQVMK--EIKTI-----------DKKCNFIMPIEG--IITS---------------
----------------------------------------------K-FSI----NNQDR
NCKEG---INIKS----NGAQ--------------------------------QVRASSS
GKILYVGKGSKWYGNMII-------IEHN-KN--TITTYSYLDSIDVKIGDKVT---QGQ
AIGSI-KSINS-QKNKSYLCFAMRK-----------------------------------
------------------------------------------------HGQAVNPLLYIN
---------------CK
>Agrobacterium_tumefaciens_str_C58 gnl|BL_ORD_ID|1660 gi|159184876|ref|NP_354688.2| lipoprotein [Agrobacterium tumefaciens str. C58]
-----MRMRHSSKI------GKSVAK-MFAAALL-----------ASVATGC--------
----------SSDA---TRFSGLF-SSG-----------PDRMTT---------------
ASIPARQGGGAYGQAPVPQGDMNGG--YASAAPQGGYAN------QNMAGNSYPQ-----
---QSGGYGGVQP-----STARASASPV--QRSELS-----------------AP---TA
VASRDP------STRNEAMAQPFPSAQRPAAP-----------------------SLAAP
ARQAAAPTDN--LTTATVRSD--------KNGWHTDGASSVTLRPGESI----ATISNRY
GVPEKELLRVNGLKTASSAQAGQSILIPKFGQAR-------------NAAKDAAGN--IA
LNRNGDQPTPLRAPD-GNVAVLPSQAAARDKL---------SSEA-GKLTPPG--GK-PL
PP---------SGGYKVQPGDSLAKI-----ARANGVSVA-------------------A
LKAANGISN-ESIRVG------QTLAMPGA--------------STDAIKTA------SV
PA---------------------------------------------------------K
EAAAAKPVETASIKPEPYK-------APAAAATTAAPATPATA-SVSDIE----KK----
-ADMAS-----IAPES-----------TGIGKYRWPVRG--AVIN---------------
----------------------------------------------N-FGD-----NVEG
SRNDG---INISV----PEGT--------------------------------PIKAAEN
GVVIYAGNGLKQLGNTVL-------VRHD-DG--KVTVYGNAANLDVQRGQKVQ---RGQ
TIATS--GMTG-SAKRPQVHFEVRK-----------------------------------
------------------------------------------------DATPVNPSGFLE
-----------------
>Rhizobium_etli_CFN_42 gnl|BL_ORD_ID|2123 gi|86357457|ref|YP_469349.1| lipoprotein precursor protein [Rhizobium etli CFN 42]
-----MRFSLSPKF------GKSAGN-LLVVGLL-----------ASAATGC--------
----------SSDV---TRFGGLFSSSG-----------QDQVTT---------------
SSIPRR--GGVQGD-PVPRADLGG----SAVASQSGYGG------NNALNQPYPA-----
---NP-GYEPVRT-----SSARLASSPVSIQRSELA-----------------AP---TA
AAPSRQ------RDKEVALAQPFPASPQAQKP-----------------------RLVAP
AAPKATP-DS--LTTGTT-PK--------ISGWSSTNAPSVTLRPGENI----ATLSRRF
GVPEKEILRINNLKTASAAQPGQAILIPTL-NGG-------------NAAKAASQA--AD
LAKPGNMPEPAKAPE-QKVAVVPGANSARDKTMA------SADPA-AKLPAGA--GKDPK
AP---------AGTYVVKQGDSLAKI-----AKATGANID-------------------D
LKAANNISA-SSLRVG------QALKIPAA--------------KADTIKTA------SI
PA----------------------------------------------------EKVESK
PADPAPAQQTASVQPAPYK-------APA-----------ATQ-TVDEVE----KK----
-ADVSS-----DAPES-----------TGIGKYRWPVRG--QVIA---------------
----------------------------------------------A-YGA-----NVNG
SRNDG---IDISV----PQGT--------------------------------PIKAAEN
GVVIYAGNGLKELGNTVL-------VRHD-DG--TVTVYGNADTLSVARGQKIQ---RGQ
TVAVS--GMSG-DVKQPQVHFEVRK-----------------------------------
------------------------------------------------DASPVNPMTFLE
-----------------
>Sinorhizobium_fredii_NGR234 gnl|BL_ORD_ID|4086 gi|227821941|ref|YP_002825911.1| lipoprotein [Sinorhizobium fredii NGR234]
-----MRKFSSPSA------GKSLVR-LSGAILL-----------ASVATGC--------
----------SSDV---SRFNGLFSSS-------------DDITT---------------
SSIPGN----------VPRGDVSS----GQLASSAGAGG-------GSYGQAFPSS----
--GQSASYDPMSTASTPVSSARAASTPVSVQRTALA-----------------EP---TA
AMPRQP--------------QPLPAARQPQ-----------------------------P
VLAKAEPLP----SSSSGASG--------KGGWTTANAPTIMVRPGDTV----AGLARRF
GVPEKEILKANGLKSASQVEPGQRLVVPTFGGAS-------------SAAKAAASGSIAD
FEGGKRQPSPLPEGQ-REMAILPGQSQSREKSEG------RSDVAAGKLNNAG--AGD--
GS---------DGAYTVKPGDSLNKI-----AKANGVSVA-------------------A
LKQANGLTA-ESIRIG------QKLKMPGAAG-----------SATDAVVTA------SV
PA-----------------------------------------------------KSETK
VASLDQG------KPAEYK-------PPV-----------AKE-SVSDVA----IK----
-TDIDQ-----ESPKS-----------TGIGKYRWPVRG--AVVA---------------
----------------------------------------------G-YGA-----NVDG
NRNDG---INISV----PEGT--------------------------------AIKAAEN
GVVIYSGSSLKELGNAVL-------VRHD-DG--TVTVYGNASQLKVQRGEKVQ---RGQ
TLAAS--GMTG-KASQPQVHFEVRK-----------------------------------
------------------------------------------------NATPVNPATFLE
-----------------
>Agrobacterium_vitis_S4 gnl|BL_ORD_ID|3996 gi|222148964|ref|YP_002549921.1| lipoprotein [Agrobacterium vitis S4]
-----MRQSQSYKS------GMPVAQ-ILWVGLM-----------ASVATGC--------
----------SSDS---SRFSGLFSKT-------------DSMTT---------------
ASTGGQITGMA--NAPVPQTDVDGGGSYAPAASGGSMGGGGYGNRQQAMTQPYPA-----
---QQ-TY----------SPARRASSAVSVQKAELA-----------------PPSGSTA
STGPIS------SRRQTASAQPFPAATHQSAALEDGDGL-------------STNTLPQP
AKPGL-PSGQ--GAGANG-QG--------ANGWSTVNAPRVVLKPGESL----ATLSQRY
GVPEKEIVKANGLSTAGAARPGQSILIPTFGSRN-------------TPTRAAAAE--GT
LLPPGQSPGPTPRQE-EKVAVLPTNPKLRDKV--------KTDIAANNTTNAAGTGKTP-
PA---------AGTYVVKSGDSIAKI-----ARENGVSVA-------------------A
LKQANHLGT-QGVRVG------QTLELPQA-D-----------QKLAATPVS------TA
PA-----------------------------------------------------NTKPE
APKVTAA------APAP----------AA-----------PTK-SVTDV-----AS----
-ADPGD-----KAPDA-----------TGIGKYRWPVRG--AVVA---------------
----------------------------------------------P-FGA-----NVAG
KRNDG---IDISV----PTGT--------------------------------PIKAAEN
GVVIYAGNGLKELGNTVL-------VRHD-DG--TVTVYGHADAISVQRGQKVQ---RGQ
QVATS--GMSG-NASQPTLHFEVRK-----------------------------------
------------------------------------------------DATPVNPMGFLE
-----------------
>Brucella_abortus_A13334 gnl|BL_ORD_ID|2742 gi|376273386|ref|YP_005151964.1| unnamed protein product [Brucella abortus A13334]
MDELNMRLPILQHT------SERLLR-NVAIVLI-----------AGFGAGC--------
----------SADT---MRF--T-----------------DGIFT---------------
GSTSSQP--VA----------------------------------QQPAGNVY-------
--ASAP------------VASAPPVSSGTVQRNSL------------------PPVSSAP
LG-----------------APVAAASTQMRNQVDQAQDM-------------AASRVNNT
VN------------------------------------------------------AAET
RVASAATVTHNTVNGAKEKVLGQ---LPA---TG-------------QGAPRPMD-----
----------------NNIAGVPQAPAVNGKKSS------PTNMA-----SAGGAIATPP
SV---------GGAYVVKSGDSLFSI-----AKKHNVPVD-------------------Q
LKAANGLTS-GAIRVG------QSLVIPSAAA-----------GAPT-----------QV
AA-----------------------------------------------------ITPQP
AN--------------PAKAAS----APANGGAEVKPYTPPQA-SNKVIE----DA----
-EKDQA-----AAPSS-----------TGISQMRWPVRG--RILA---------------
----------------------------------------------S-FGQ-----REGT
SVSDG---IDIMV----PEGT--------------------------------PVKAAEN
GVVIYAGDGLKEFGQTVL-------IRHD-NG--LVTVYGHNSQIMVQRGQKVR---RGE
EIAKS--GMSG-NAKSPKLHFEVRK-----------------------------------
------------------------------------------------NSAPVNPTKYLE
----------------S
>Ochrobactrum_anthropi_ATCC_49188 gnl|BL_ORD_ID|2320 gi|153009667|ref|YP_001370882.1| unnamed protein product [Ochrobactrum anthropi ATCC 49188]
MGELNMRLQVLQHT------SERLLR-NVAIVLI-----------AGFGAGC--------
----------SADT---MRF--T-----------------DGIST---------------
GSTSSQR--VA----------------------------------QQPAGDLY-------
--ASA--------------APVAPASSGSVQRNSL------------------PPVSSAP
MAAPVA------AARQSVQAPVAAASNNIQNQVGQAQDM-------------AANRVNNT
VN------------------------------------------------------AAET
KVASAATSTRNTVNGAQEKVLGQ---LPA---N--------------PAMPRPTD-----
----------------NNIAVVPQAPAVNGKKPS------ANDMA-----SAGANATTPP
AP---------NGTYTVKSGDSLFSI-----AQKHNVPVE-------------------Q
LKKANGLSN-GAIRVG------QALVIPSAAA-----------GNAT-----------QV
AA-----------------------------------------------------VSQPP
EN--------------PAKAAA----PAAN--ADVKPYTPPQA-SNKVIE----DA----
-EKDQA-----AAPSS-----------TGISQMRWPVRG--RILA---------------
----------------------------------------------S-FGQ-----RDGT
SVSDG---IDIMV----PEGT--------------------------------SVKAAEN
GVVIYAGDGLKEFGQTVL-------IRHD-NG--LVTVYGHNSQILVQRGQKVR---RGE
EVAKS--GMSG-NAKSPKLHFEVRK-----------------------------------
------------------------------------------------NSAPVNPSKYLE
----------------S
>Mesorhizobium_loti_MAFF303099 gnl|BL_ORD_ID|850 gi|13471177|ref|NP_102746.1| unnamed protein product [Mesorhizobium loti MAFF303099]
-----MQLSVLKTN------SRNLAR-GCAVLMI-----------AGAAAGC--------
----------SSQA---SRFNSV-----------------DDVFT---------------
SSTNNQRAIIN----------------------------------KQDAVQPYPGD----
--VSA--------------APLDGSHTQSVSRSSL------------------EPVSSRP
LPPPAS------AQAQPAPA-LAPAANPVRVASAPAMVR-------------PAPHVDRT
TTGTVEPAAKPFKNAQPDAPK--------VADAGRPHATEIVVRDGETI----SGLAAHY
KVPADVIMKVNGLSPTKGLKTGQKIVIPAYAYSS-------------KAEPKVADAKQLK
DGPAKDGKHDLPATAPDKVAVLPQQPKLKEGKSA------AQVDA-----SAAASQPKEP
KPAQVAKATGAGGTYTVQSGDTMSSI-----ARKTGVGVV-------------------A
LKQANGMKD-GLLKIG------QTLKVP---A-----------GGTA-----------TV
AS-----------------------------------------------------SKPAK
VD--------------PVTTATTQPPAKTTPSETLASYTPPKK-DAKVIQ----QA----
-EDDEA-----VAPDA-----------TGIGKMRWPVRG--RVIS---------------
----------------------------------------------G-FG----------
SGKDG---VDIAV----PSGT--------------------------------PIKAAEN
GVVIYAGDGLKEFGNTVL-------VRHE-NG--LVTVYGHASSIEVQRGQKVK---RGQ
EIALS--GMSG-TTDSPKLHFEVRK-----------------------------------
------------------------------------------------NSAPVDPSGYLE
-----------------
>Bartonella_clarridgeiae_73 gnl|BL_ORD_ID|994 gi|319899188|ref|YP_004159281.1| unnamed protein product [Bartonella clarridgeiae 73]
-----M-----------------------ILLAV-----------TAITTGC--------
----------SSST---ERFYG--GSYNNTTPVHSITTMTDDSGM---------------
------------------------------------------------------------
-----------------------LSQNVEIQSSELP------------------------
------------------------------------------------------------
----------------------------------PVESSSISEAGYDSI----YNDSSRQ
GEVSY------SDKNKQFFSDGRVMGTPP-------------------------------
----------------RNLGTLPRSQINTFPVFK--------------------------
-----------RNSYIVQSGDTLLSI-----AQQLGVSVD-------------------A
LRLVNGINA-NSIYIG------QSLIIPDRST-----------KMASNVQDSTSDVSKKV
FS-----------------------------------------------------SQSKN
VSSVEQKKTPASVYEAPIKTAP----AVKNNMLDIEKNSLAQATTHKSIN----DSSDRV
TDPNDI-----VVPQS-----------TGISKMRWPVRG--RLLS---------------
----------------------------------------------H-FGQ-----KKGT
AVNRG---IDITV----PEGS--------------------------------SVKAAEN
GVVIYASDGLKKLGNVVM-------IRHE-NN--IITIYGHNSKLIVNRGQRVR---RGD
EIAKS--GFSG-DAKTPRVYFEVRK-----------------------------------
------------------------------------------------NSIPVDPAEYLE
----------------N
>Beijerinckia_indica_subsp_indica_ATCC_9039 gnl|BL_ORD_ID|2826 gi|182679614|ref|YP_001833760.1| peptidase M23 [Beijerinckia indica subsp. indica ATCC 9039]
-----MRFSFSLRGSRAAT-SCLALR-LALTGAT-----------AGLLAGC--------
----------AN----SERLS---DPFG--NPFQSSANGTDSTPT---------------
GSLGSYQQSAPVTPVQ-----------------------------RHALGQAIPQP----
-------------------------AAPPVQTRSLT-----------------AATVPVA
PSLPRG---------AGGAAGWTIE-----------------------------------
------------------------------------GGTPIAVRPGESA----SVLAQRY
GVPTESLVRANGFGSAGEIQPGTRVVIPVYNAAL-------------AASSGAHLVQNTE
QAVSRTATAAQNLP--TRLPTIP-KPTPIAQAEPV-------------------------
-----------KLVRNVAQNTTKSVV-----AETNAVKGAARAKLVQGHAQEQAVVQHVQ
TAQATVKSQVKPEAIAKNVAKAEHLAKPEP-------------IAKAEATV-------KA
TA------------------------------------------GKLEHAQVETKKAVKT
AALAP-------AREARIA--ESKPVEARAVEPKQTRSEVKQAEPVKSAE--------PV
AVEPAR-----EAAND-----------SANPEFRWPARG--RIIQ---------------
----------------------------------------------S-FKP---------
GGNDG---INIAV----PEGT--------------------------------AVKAAEG
GVVAYAGSELKGYGNLVL-------IRHP-NG--FVSAYANNGDLEVKRGETVK---RGQ
TIAKS--GQSG-NVNSPQLHFELRK-----------------------------------
------------------------------------------------GATPVDPTQYLA
---------------GL
>Methylocella_silvestris_BL2 gnl|BL_ORD_ID|1320 gi|217977521|ref|YP_002361668.1| peptidase M23 [Methylocella silvestris BL2]
-----MSHIALVYR------SRLAFR-FALIGVS-----------ASVLAGC--------
----------AG----SERMA---DPFS--NPFSTAQAPTDPAPT---------------
SSINP---GAPVTPVQ-----------------------------SRPLAAASSQR----
--------------------------------------------------------PAVV
ASLPAH--------GAQGPAGWTAA-----------------------------------
------------------------------------GGTPISIAQGESA----DLIARRY
GVPTDALLKANGFSNAAQVQPGARVIIPVYHAVG--------------------------
--------------APMAVAQAP-AAAPVSAPKP--------------------------
-------------------------------ARTPDEMHAQKIKLLKGAPATQ------Q
FASASANSAAKSEKLG---------APPRS-------------AAFVPETP-------KK
TA----------------------------------------------------EAAAKA
AAAQP-------AVSTKAASIKTEPVKTAAL----TKADTPKAETAKSAA-------PAV
EAKAAAEDEGDSGKAA-----------GANPEFRWPARG--RIIQ---------------
----------------------------------------------A-FKP---------
GGNDG---INIAV----PEGT--------------------------------SVKAAES
GVVAYAGSELKGYGNLIL-------IRHP-NG--FVSAYANNGDIEVKRGETVK---RGQ
TIAKS--GQSG-NVASPQLHFELRK-----------------------------------
------------------------------------------------GATPVDPTQYLA
---------------GL
>Bradyrhizobium_sp_BTAi1 gnl|BL_ORD_ID|4369 gi|148255769|ref|YP_001240354.1| peptidoglycan-binding LysM [Bradyrhizobium sp. BTAi1]
-----MPAIVELPR------SRRLPQ-FAALALM-----------SFGVAGC--------
----------SADM--STRLSQAQNPFS--NPFA---SDA----T---------------
GSVQ----APPR---Q-----------------------------HQPVAQQYTPA----
--PA---------------------PAPTYSSSALP-----------------PPAVATP
QSYPSGGGSGGVSGGGRGVASYVPPAAVPAAAPQPAYAQ-------------PTHSYAPP
AQPQLETTGAV-PPRSVAAAR--------PT-----GGTKIIVGTSDTL----EILAKRY
RVSPAEILAANGYKGPRALSPGQQLTIPHPGAVA-------------AAP-AAQPV----
-------------A--TPVAAAPVAPKP-VAVAA------ATAP----------------
-----------STVHFVNRGETLASI-----ARQNHLTPA-------------------E
LARANNLDQASPLKLG------ARLTVP-AKA-----------AAVAAPVA-------PV
AT-------------------------------------------------V-PQAVATV
PAPAPT------TR---VA--AAGPVQTARL---------AQANPAPEKE----------
-EEPAR-----PAETT-----------SSLPTFRWPARG--KVIT---------------
----------------------------------------------S-YGA-----KTNG
KSNDG---INIAV----PEGT--------------------------------PVKAAED
GVVAYAGNELKGYGNLVL-------VRHS-NG--YVTAYAHASELMVKRGDPIK---RGQ
VIAKS--GQSG-EVGSPQLHFEIRK-----------------------------------
------------------------------------------------GSSPVDPLQFLN
---------------GA
>Rhodopseudomonas_palustris_BisB5 gnl|BL_ORD_ID|2768 gi|91977251|ref|YP_569910.1| peptidase M23B [Rhodopseudomonas palustris BisB5]
-----MSRVVELLC------SRRAPQ-MAVLTLI-----------SVGFSAC--------
----------SADM--QTRFQ------Q--APFGP--VET----T---------------
GSVQ----QPRYG--E-----------------------------RRELPQYARPQ----
--YQS-------------AQPQYQPAQPQYQSQALP-----------------P--IAAP
PSYPVAGGGSGVSSGGRGVASYEPPQRAP-------------------------------
----IETTGTV-APRSVAAARPAPAPAAVPA-----SGTTIIVGTSDTL----EGLARRY
NVATADILQANGYKGPRRLQPGQSLVIPQRTASL-------------QAPVAAPPV----
-------------A--RPLAAAP-APMP----VA------AAAP----------------
-----------PRVHYVNSGDTLMNI-----ARRNNISAA-------------------E
LARYNRIDANARLQPG------MKINVPGAQS-----------AALAAPPL-------AA
PA-------------------------------------------------TAQPAAQPA
VSAAPP------VRMAVAA--PADPVQKARM---------VAPTETPAAA----EP---A
EASPVK-----SAEAT-----------GALPSFRWPVRG--RVIT---------------
----------------------------------------------A-YGA-----KTNG
KSNDG---INLAV----PEGT--------------------------------PVKAAED
GVVAYSGNELKGYGNLVL-------VRHS-NG--YVTAYAHASELMVKRGETIK---RGQ
TIAKS--GQSG-EVGSPQLHFEIRK-----------------------------------
------------------------------------------------GSSPVDPLKFLN
---------------GA
>Oligotropha_carboxidovorans_OM5 gnl|BL_ORD_ID|2220 gi|209885381|ref|YP_002289238.1| peptidase M23B [Oligotropha carboxidovorans OM5]
-----MSRLLELLG------TRRVPS-LAVMALV-----------SVSFGGC--------
----------SADY--DSRFS--DNSFQ--NPFASQRSDA----T---------------
GSVR----QNNHY--A-----------------------------QRELPQYSRPA----
--SHA------------------------------P-----------------V--VSAP
LSYPAAQGNSG---GGHGMASYTPPASNP-------------------------------
----IQHTGSVNAPRSVAATR--------PE-----GGTKIIVGTSDTM----EILARRY
NVSVADIVRANGYRGPRALSPGQSLIIPKRAAQA-------------Q------------
---------------------AP-APAT----RG------ATMP----------------
-----------SSVHVAAPGDTLMNI-----SRRNHISVS-------------------E
LARANNLPVTAQLKVG------DRITVPSSSK-----------TLAAAQPA-------PA
PA-------------------------------------------------A---PAQPV
AAAAPPKPQPVAAKPVVTA--SAEPAQKVRM---------ATETKEIERT----H-----
--SPVK-----AAEAT-----------NALPTFRWPVRG--RVIT---------------
----------------------------------------------S-YGA-----KTNG
KQNDG---INVAV----PEGT--------------------------------PVKAAED
GVVAYSGNELKGYGNLIL-------VRHA-NG--YVTAYAHASELMVKRGDSIK---RGQ
IIAKS--GQTG-EVGSPQLHFEIRK-----------------------------------
------------------------------------------------GSSPVDPLQFLN
---------------GA
>Nitrobacter_winogradskyi_Nb-255 gnl|BL_ORD_ID|1764 gi|75675964|ref|YP_318385.1| unnamed protein product [Nitrobacter winogradskyi Nb-255]
-----MSRVVELLC------SRRVPQ-VAVLALV-----------SIGFAGC--------
----------SADM--STRLAQLDSGPQQSNRFGWQR-ET----T---------------
GTVA----AAPAAPVE-----------------------------RRELHQYSRPP----
--YR---------------------PHSDYQSQPLP-----------------P--ISTP
KSYPVA---SSVSVSGRGPGSYTPPARA--------------------------------
----IESAPAV-AARDGWNHK---------------GGTPIIVGTSDTL----EGLSRRY
GVSSAEILKANGYRGPRQLQPGQRLIIPKRAAVA-------------E------------
--------------------TQP-APAAKPAVVA------TAAS----------------
-----------GATHHVNRGDTLMNI-----ARRNHISVG-------------------E
LARANGLPPSAKLKIG------TRITVP-TKV-----------AAVSAQPV-------AA
PA-------------------------------------------------A-PPAVAPK
PAPAP-------VVHAAAA--TAGPVQKVNL---------AAATATPEAA---------V
VKPSVK-----AAEAT-----------GALPTFRWPVRG--RVIT---------------
----------------------------------------------A-YGA-----RTNG
KSNDG---INVAV----PEGT--------------------------------PVKAAED
GVVAYAGNELKGYGNLVL-------VRHS-NG--YVTAYAHARELMVKRGDSIR---RGQ
VIAKS--GQSG-EAGSPQLHFEIRK-----------------------------------
------------------------------------------------GSTPVDPLNFLN
---------------GA
>Hyphomicrobium_denitrificans_ATCC_51888 gnl|BL_ORD_ID|1252 gi|300022791|ref|YP_003755402.1| peptidase M23 [Hyphomicrobium denitrificans ATCC 51888]
-----MMNCFGVSHGGRF--SLKSAA-AVSTVIA-----------GLAIGGC--------
----------SADV---TRFD--SASFNLNDPPDARPIPSQSIRT---------------
SSLS-----------D-----------------------------STAVGQPPRGP----
--YGA--------------------GASSVQVAALP-----------------D---AGP
SYQPAP--------------SYSPPAYNP----PPAYSA-------------PAKSY---
------------EPKPFGRARSDSAPSARPAMQAALNGNEIIVQPGDTL----YSISRAH
HVSLAELMSANSLSNP-NVHPGQKLILPSSSGAR-------------SSRSSVAAA----
-------------K--AVESARP-APAP----LAEPPHDVAANY----------------
-----------NSTYTVKAGESLYGI-----ARAHNVKFA-------------------E
LQQVNGIADPRRVKPG------VVLKVP-GRS-----------GADMPASQ-------PA
PAAPASVADNAPAAIVPPLAATEKGSDIPAYGQSLSTRPTIINSERRVAALTDTGKATDA
APAAPAAPAPSVALSEPPA--SAPPVAEAAP---------AKAEQKVALA----------
--APAA-----ASAVA-----------DSV-KLRWPTTG--RVIA---------------
----------------------------------------------G-FGG-----RPDG
THNDG---INLAV----PLGT--------------------------------EVHAAES
GVVAYSGNELKGYGNLVL-------LRHD-NG--WVTAYAHNDELLVKRGDKVK---RGQ
VISKA--GKTG-SVDQPQVHFELRQ-----------------------------------
------------------------------------------------GSRPVDPTPYLE
---------------KL
>Magnetospirillum_magneticum_AMB-1 gnl|BL_ORD_ID|2518 gi|83311617|ref|YP_421881.1| membrane protein related to metalloendopeptidase [Magnetospirillum magneticum AMB-1]
-----M--IAAGRRRAYSTGMRHAPHHLVILLIL-----------AAAISAC--------
----------TPSY--DSK-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--VPVG--------RSDGPLQVQ-------------------------------------
------------------------------------RPATVTVYAGDTV----YSIARRY
SLTVRDLIETNNLQPPYQLQPGTVLRLPGG------------------------------
------------------------------------------------------------
-----------GSDYVVQRGDTLSVL-----ARRFKVDFN-------------------S
LAATNGKRAPYVLQVG------ERLTIPGPKA-----------SVTQTAAT-------PA
PA----------------------------------------------------TGGGSM
VVTSP-------HASGGAG--GGKPAAKAEVPPVY-----AQAPSHPAPP----P-----
--AAVP-----AVPPA-----------RAGSTFLWPVKG--EVVA---------------
----------------------------------------------E-FGP----LPGKG
QHNDG---INIVA----AKGT--------------------------------PVRAAEN
GVVAYVGNELKGFGNLLL-------IKHA-DN--WMTAYAHNDQLMVKRGDRVR---RGQ
TIATL--GASG-SVTSPQLHFEIRR-----------------------------------
------------------------------------------------GTEAVNPVEYLQ
DKVADDGAVRQLAAIAY
>Hirschia_baltica_ATCC_49814 gnl|BL_ORD_ID|1392 gi|254293769|ref|YP_003059792.1| peptidase M23 [Hirschia baltica ATCC 49814]
-----MSEQKRLS-------TRSV---LTIKLVL-----------ACVLSMCWCAPAIAQ
ARETAPVEFRSA-----ARYSEYRIPEGADYAPVTQGSPLGQPDTQYYEKVAQAREQAER
QRLAAEQVAQQQARANAINNSQPEIYSQAGSAQQKYVTHQSTGVYQQGIAQTRYPP----
--VTYGQAGTQIVDTNSSLNQQQFGTSANYANSGMPQTIPHLAVGSLPAAAPIANIYATP
MAPLSGGVAGGGALIGAGVVDHSFKQRELSGAGEMSFSNEDLMGMDEGRYDNAASMQSLS
HSQHQQTLVSNTSTASVYSQPSNISAYTNASVSELPVGDKVEVLAGDTL----YSLSTRY
RVALRALVETNDLQPPFRLEVGSFVHLPP-------------------------------
------------------------------------------------------------
-----------PNIHVVETGETLYAI-----SRRYNVDTR-------------------S
LANMNGLPKPWTIYPG------DQMILPSLAR-----------DSFASEST-------AI
AS----------------------------------------------------------
AKARDKILRESKGIAAPIVGQT----ATASSPTAVQLGGDQQAGPGLAVD----SAKLAV
KNEALG-RFDESAPVSAIKTSEKIDLPGDAKGFVWPVNG--NIIK---------------
----------------------------------------------T-YGQ-----MPNG
KINDG---VNIAA----RAGS--------------------------------TIKAASD
GYVVYAGSELPGFGLLIL-------INHG-NG--WVSAYAHAEELLVEENQPIR---QGQ
AIAKV--GETG-SVDRPQLHFQLRR-----------------------------------
------------------------------------------------GKSPIDPASHLL
------------PKRSI
>Pelagibacterium_halotolerans_B2 gnl|BL_ORD_ID|1441 gi|357384516|ref|YP_004899240.1| unnamed protein product [Pelagibacterium halotolerans B2]
-----MTLSVTGSK------LRSAGS-ALAMSAA-----------ALVLAGC--------
----------SSM----GSFGG------------------DPTVT---------------
GATSRMGGAVV----------------------------------GQAMPAYLPPANIGG
GVAANGTTGPALIDRTTASPVGTQSAVVSQDLPALQ-----------------PSSVTST
QAMPAQ------TAAVSSPSSTLSQAAQPSAP----------------------------
-----------------------------QLGVVQGDTYSHTIASGESL----YTIARRY
DVSATEIIAANNIGSPDRIVVGQSLIIPG-------------------------------
------------------------------------------------------------
-----------RPDLLAQRGQTQ------------------------------------Q
VAAVSGSQAAA---------------SPSGTS-----------AANTQTAT-------PA
PA----------------------------------------------------------
--------------------------APARPEEQ------PEPQPTQVAA----AP----
TQQPTP-----AATAS-----------VTSDKFRWPLSG--RVIT---------------
----------------------------------------------D-FAA---------
SRGTG---INIEA----PEGT--------------------------------SVRAAEN
GEVIYVGNAVEGYGNLVL-------VKHA-NG--FVSAYAHLNTIGVVKGDSVS---RGD
ALGTV--GMTG-SVSRPQLHFELRK-----------------------------------
------------------------------------------------GATPVDPMPLLA
----------------G
>Ketogulonicigenium_vulgare_Y25 gnl|BL_ORD_ID|1386 gi|310815671|ref|YP_003963635.1| LysM domain-containing protein [Ketogulonicigenium vulgare Y25]
-----M---------------KNLGL-HLMGGVA-----------LMALAAC--ND----
----------VPDY--DLRGMG-TG-FT----------------T---------------
------------------------------------------------------------
-----------------------AGAMPS--TNNRP-----------------APDANGV
ISYP--------------------------------------------------------
------------------------------------TYQVAVARAGDTV----ATIAGRL
SLDAGQLASYNGLQTGTSLRAGEVLALPARVSGG-----------LSGGMTDITSIAGAA
IDRAGDVT---------TTALAPSGSSAATAPAA------SSTPLQI-SE----------
-----------PVRHQVARGETAYII-----ARRYNIPVR-------------------S
LAEWNGLDSNMTIREG------QYLMIPTANG-----------TPSTTPVT-------SA
PG----------------------------------------------------------
-------------------QGSATPVPPSASQPMPSEATPPAAAAPAAAA----AAAAAT
PNLGAQ-----QTSAS-----------QSTSTLQRPVAG--NIIR---------------
----------------------------------------------A-YAR---------
GRNDG---IDIGA----PAGT--------------------------------DVQAAAA
GTVAAITTNTDGI-QIVV-------IRHD-GN--LMTVYTHLDRLTVARGASVS---RGQ
VIGKV-----A-DGATPYLHFEVRR-----------------------------------
------------------------------------------------GLDSVDPSTMLP
-----------------
>Rhodobacter_capsulatus_SB_1003 gnl|BL_ORD_ID|2391 gi|294677949|ref|YP_003578564.1| M23 family peptidase [Rhodobacter capsulatus SB 1003]
-----MQAPH----------SRRLTR-VLLTGVA-----------LAVLAGCGKDG----
----------SFDA--DLRHFGKTG-FD----------------T---------------
------------------------------------------------------------
-----------------------TDAVRQA-TADRP-----------------APDARGV
ISYP--------------------------------------------------------
------------------------------------NYQVAVARQGDSV----GSIASRL
GLDAAELARYNALAPNTPLGKGEVLALPKRVGEPAPAAVAGGAAAAGSERIDITSLAGAA
IDRAAVTQPPAETPAAPATAPRPAAPSASPVAKP------AA-PAQTGAE----------
-----------PIRHRVARGETAYSI-----ARYYNVPAK-------------------S
VADWNGLPADLSVREG------QMLMIPPATGAAPRSA---------TATL-------TE
PG----------------------------------------------------------
-------------------EGSPTPEPPSAAKPLPKE-VPPKASDPVDTS----AA----
PDLGAA-----RTEAS-----------RS-SKFVMPVPG--AIIR---------------
----------------------------------------------P-YAK---------
GKNDG---VDIRA----AAGT--------------------------------AVKAADA
GTVAAITKDTEQV-PILV-------LRHE-GG--LLTVYANIDGITVAKGDKVR---RGQ
SIAKV-----R-AGDTGFLHFEVRK-----------------------------------
------------------------------------------------GYDSVDPMPYLD
-----------------
>Ruegeria_pomeroyi_DSS-3 gnl|BL_ORD_ID|2622 gi|56697528|ref|YP_167896.1| unnamed protein product [Ruegeria pomeroyi DSS-3]
-----MSVLF-----------RTLPR-PLMGLSA-----------LALLAAC--EA----
----------PLDY--DLR--GQIGAFN----------------T---------------
------------------------------------------------------------
-----------------------TEAAQSARTAARP-----------------KPDERGV
ISYP--------------------------------------------------------
------------------------------------NYQVAVAKRGDTV----ATLSDRV
GLPVGEVARFNGLQPTDGLREGEVLALPRRVTEP----------VGQGNNVDIASLAGSA
IDQAPDTTP------VQTTALEPAKPAASPAPKP------AA-P-----E----------
-----------PVRHKVERGETAYTI-----SRLYQVPVK-------------------A
LGEWNGLGPDFTIREG------QYLLIPVKDQPAPKSAAKPAAATTTTAAV-------SA
PG----------------------------------------------------------
-------------------AGSATPTPPSATKPLPEE-KVPAAK-----P----AE----
PDVSVG-----QPTAS-----------SN-ARLGFPVKG--KIVR---------------
----------------------------------------------P-YSK---------
GKNDG---IDIAG----APGS--------------------------------AVSAAEA
GTVAAITADADQV-PIVV-------IRHA-DN--LLTVYANVDGIEVNKGDTVS---RGQ
KIARL-----R-GGDNAYVHFEVRK-----------------------------------
------------------------------------------------GFDSFDPEPYLK
-----------------
>Magnetococcus_sp_MC-1 gnl|BL_ORD_ID|366 gi|117923685|ref|YP_864302.1| unnamed protein product [Magnetococcus sp. MC-1]
-----M--------------DRLTIKHRLTGLMT-----------LLLLGGC--------
----------------------------------------MPLDT---------------
------------------------------------------------------------
-----------------------------------------------------LNLSTTP
TDTPVR--------VARGPALGWQPTTT--------------------------------
-----------------------------PNHVEPSNAPTYQVQAGDSL----WSIAMSH
QVDVFDLARWNGVDDPDKVVAGQLLYVRS-------------------------------
----------------------PSMPVPNGKPDVMDEGN---------------------
-----------------SSGDTPLRT-----VHLPQPSVV-------------------A
QPDPMGVAQSGGFLKQ------HSFILPTGRT-----------APL------------PL
PA----------------------------------------------------------
-----------LATPLAAVGSTATPTDKATPAPKSRDLTTQPATRQIVVQIRGDEEKPGI
IQQPAT-----LSSATAAANLQRMKGKPAPQQWNWPVQG--TVVA---------------
----------------------------------------------S-FGR------RGA
KINPG---IDIAA----EKGT--------------------------------PVLAPAA
GVVAYVGGH-DSFGNLII-------VNHG-GD--YKTLYAHNDVNLVERGQEIR---PGQ
MIARV--GNTGVRVRSPRLHFEIRR-----------------------------------
------------------------------------------------PIKPLNPLNYLS
----------------K
>Agrobacterium_sp_H13-3 gnl|BL_ORD_ID|1780 gi|325293234|ref|YP_004279098.1| membrane protein associated metalloendopeptidase [Agrobacterium sp. H13-3]
-----MTDTAENRVF-----GKKRQQHVLVLASGDKVRHMTIRPWMTALAGCTIGLFSLG
YLGATGYLILRDDLIGATMARQTRMQHDYEDRIAALRAQVDRVTS---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------RQLFDQQVVEKKVEKLLQQQAALTSRH
GRMSELLERAENSGIAASTATAPIPTAPSSLSNAMAPEKRADLTGGLSAIE---------
----------------NLMAPRPSQPEKPAGTDK--------------------------
-----------RASYVPENGETPSDR-----ADRVFSKVTLSLKDIERQ----------Q
ISRIARLTSDAEDKAS------AMQDIIRQAG-----------LKIDESDTDGVGGPYAD
PQ----------------------------------------------------------
----------------------------------------GNETDPFNMS---------L
TNLDNALNRLDIVKET-----------ATALPFGNPAPG--RAIT---------------
----------------------------------------------SRFGNRLDPFLGRP
ALHTG---IDFRA----ETGA--------------------------------DVKATGA
GKVTVAENS-GGYGNMVE-------IDHG-QG--VSTRFGHLSTILVKAGDKVE---AGD
IVGRA--GSTG-RSTGPHVHYEVRR-----------------------------------
------------------------------------------------NDTPVDPMRFLV
-------AGAELKTYLK
>Caulobacter_crescentus_CB15 gnl|BL_ORD_ID|3407 gi|16127664|ref|NP_422228.1| M24/M37 family peptidase [Caulobacter crescentus CB15]
-----MSR------------SRLVLAFCALILAV-----------PTAVVGW--------
--------QRADAAFEARRARDRQIAAETRREIQDLRAELDRLDH---------------
------------------------------------------------------------
-------------------ARIAAGVDVDAKRARL-------------------------
------------------------------------------------------------
-----------------------------------------------------EALNARE
NAILAELGR-NRQRLSLLLSALQMFRRDP-------------------------------
------------------------------------------------------------
-----------PPALLVSPGDARNAVRAAILIRAMTPELK-------------------Q
RADAYGRQAVAIRALR------REAA--------------------------------AA
SA----------------------------------------------------------
-----ELFTAESVVADRKGEIERLIIEKTELERAYAQETLTQANELKTLGALTDGL----
-----------GNAQP-----------SGPLSLRPPVQG--AIVR---------------
----------------------------------------------R-FGQ----EMPAG
GKSPG---LTLRP----EKGA--------------------------------TIAAPAG
GVVEYAG-ALNGWGAVLI-------LRVQ-GA--YHIVLAGLDQINVSPGQSVA---AGA
PIGKM--PDP--VSSEPELYMEVRE-----------------------------------
------------------------------------------------NGAPSDPERWLK
-------------QESR
>Mulan_NP_078820
-----MESG-----------GRPSLCQFILLGTT-----------SVVTAAL--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------YSVYRQK
ARVSQEL-----------------------------------------------------
------------------------------------------------------------
-----------KGAKKVHLGEDLKSI----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------LSEAP-----------GKCVPYAV-IEGAVRSVKETLNSQFVENCKGVI
QRLTLQEHKMVWNRTTHLWNDCSKIIHQRTNTVPFDLV----------------------
PHEDG---VDVAVRVLKPLDSVDLGLETVYEKFHPSIQ-SFTDVIGHYISGERPKGIQET
EEMLKVGATLTGVGELVLDN-NSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVR---LWK
VLALVFG-----FATCATLFFILRK--QYLQRQERLRLKQMQEEFQEHEAQLLSRA----
------KPEDRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRAL--PEPKKCPICRQA
-------ITRVIPLYNS
>SP1_NM_105064
-----MI--------------------PWGGVTC-----------CLSAAAL--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------YLLGRSS
GRDAEVL-----------------------------------------------------
------------------------------------------------------------
-----------ETVTRVNQLKELAQL----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------LELD-----------SKILPFIVAVSG--RVGSETPIKCEHSGIRGVI
VEETAEQHFLKHNETGS-WVQDSALMLSMSKEVPWFL-----------------------
--DDGTSRVHVMG----ARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLKMLGVKRI
ERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRG-PFYVSSKSLDQLISNLGKWSR---LYK
YASMGFTVLGVFLITKHVIDSVLER------RRRRQLQ-KRVLDAAAKRAELESEGSNGT
RESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACS-----SHLTSCPLCRRR
-------IDLAVKTYRH
>SPL1_NP_564745_AT1G59560
-----MI--------------------HLAGFTC-----------CLGGVAL--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------YLLTRST
GRDI--------------------------------------------------------
------------------------------------------------------------
-----------KSITRVYQLKDLEQL----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------VEVE-----------SKVVPLIIAVSG--DVGSETPIKCEHSYVLGVF
LKRTAEQQVLRRNWRFS-WVRNSTLMQPMTKEVPWYL-----------------------
--DDGTGRVNVDV----SQGELGLALTVGSDVFEKAEPVSLVQGALGYLKGFKILGVRHV
ERVVPIGTPLTVVGEAVRDGMGNVRIQKPEQG-PFYVTYIPLDQLISKLGDLSR---RFK
YASMGLTVLGVILISKPVIEYILKRIEDTLERRRRQFALKRVVDAAARRAKPVTGG----
------GTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCS-----LQLRTCPLCRER
-------IQQVLKIYRH
>SPL2_NP_564653
-----MSSPERALLNLLTDIALSFDG-AILGLTL-----------AVSAVGS--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------ALKYAST
NAALKKI-----------------------------------------------------
------------------------------------------------------------
-----------KDAPEVSISD-LRSL----------------------------------
--------------------------LPASED----------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------KSETNDNR--------KSNDQRIVVVRG--VVKPKISGDEGYKNNNVLI
SPETGDKALIIQRTQTYVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVIVGKDQQ
SNSSF---VAVNM----DGSRQPLPLTTVYNRLQPINS----SFLQAFLYPDYPVGLLDI
EKILPPGKDITAVGIYSFNN-GVPEIKSC-QDLPYFLSEMTKDKMIEDLMEQTNFIFLGS
VILGI--------VSVGILSYAAVR--------------TWNKWKQWNHQRELPQRPNDS
VVDDEPEDADEIPDGELCVICVSRRRVPAFIPCGHVVCCRRCASTVERELNPKCPVCLQS
-------IRGSMRVYYS
