>Rickettsia_akari_str_Hartford gnl|BL_ORD_ID|412    gi|157825538|ref|YP_001493258.1| unnamed protein product [Rickettsia akari str. Hartford]
---------------------------MSDLFSNVNNSFVQYMKYPVVLSIVICFCLVAC
------------------------------------------VEQPPAPIEYKVGDVTAN
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------NNSTAL----EHDE---
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GLIVQ
RTMEDDTVSEKVSGILEEPKAKIIECYNDD------IEIPI-------S-----------
------------------------------------------------------------
--------------------------------------------------------RN--
EYEEEI-EQSNFVKPLNG-VMLTE-FKD----------GKSKGIDIAVKEYSDVKSIAAG
TVIYSGFN-KQFGNLVIVKLDKDDLEVAYASLDDLLLKKGDKITKNSVIGHVKHK-----
----LYFAMRRNRIAVDPSKYIE----------------F
>Anaplasma_centrale_str_Israel gnl|BL_ORD_ID|285 gi|269958541|ref|YP_003328328.1| peptidase [Anaplasma centrale str. Israel]
--------------------------------------------MRVVALIAASFLLYGC
------------------------------------------FTQDPAPVSLRGEEFYGN
RERDE-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------SVDYR
LTRDYSERGAATT---AASKRKVLVRDIST------RGAPP-------------------
------------------------------------------------------------
---------------------------------------------------SSTKLKQ-T
SKPSPS-KECEFGMPLDGGKVVHTPSSDSGKA-----PYCNDGVAIFADGIAKVKAAGSG
KVMYVGKGLRWYGSLVILEHNKYTISL-YSYLHEVHVKIGDKVKKGQVIATITKSSQSAD
SGYFFCFAMRRNGKPVNPVQYIK----KCKSK--------
>Ehrlichia_chaffeensis_str_Arkansas gnl|BL_ORD_ID|339 gi|88658571|ref|YP_507175.1| M23/M37 peptidase domain-containing protein [Ehrlichia chaffeensis str. Arkansas]
--------------------------------------------MTIRKTLLIVLLCFGC
-------------------------------------------TQKPAPSFLRGEEFHGK
KELD--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------DINEY
HLVRHDVKKDENIESHTIQDNH--------------------------------------
------------------------------------------------------------
--------------------------------------------------------QVMK
EIKTID-KKCNFIMPIEG-IITSK-FSINNQD-----RNCKEGINIKSNGAQQVRASSSG
KILYVGKGSKWYGNMIIIEHNKNTITT-YSYLDSIDVKIGDKVTQGQAIGSIKSINSQKN
KSY-LCFAMRKHGQAVNPLLYIN---------------CK
>Agrobacterium_tumefaciens_str_C58 gnl|BL_ORD_ID|1660 gi|159184876|ref|NP_354688.2| lipoprotein [Agrobacterium tumefaciens str. C58]
-----MRMRHSSKI------GKS-----VA---------------KMFAAALLASVATGC
----------------------------------------------SSD-ATRFSGLFS-
SGPDRMTTASIPARQGGGAYGQAP--VPQGDMNGG--YASAAP-----QGGYANQNM-AG
NSYPQQS--------G-----GYGGVQ--PSTAR-ASASP--VQRSELSAPTA-VASRDP
S-----------------------TRNEAMAQPFPSAQRPAAP----------SLAAP-A
RQAAAPTDNLTTA-----TVRSDKNGWH--------TD-----GASSVTLRPGESIA---
------TISNRYGVPEKELLRVNGLKTASSAQAGQSILIPKFGQ--ARNAAKDAAGN--I
-----ALNRNGDQPTPLRAPDGNVAVLPSQAAARDKLSSE---A-GKL--TPPGG-----
-----K-PLPPS-GGYKVQPGDSLAKIARANGVSVA-------------------ALKAA
NGI-SN-ESIRVGQTLAMPGA-----ST-D------AIKTA-------SVPA--------
------------------------------KEAAAAK--PVETASIKPEP------YKAP
AAAATT-AAPATPATASVSDIEK------------------------------KA-DMAS
IAPEST-GIGKYRWPVRG-AVINN-FGD-NVE-----GSRNDGINISVPEGTPIKAAENG
VVIYAGNGLKQLGNTVLVRHDDGKVTV-YGNAANLDVQRGQKVQRGQTIATSGMTG-SAK
RPQ-VHFEVRKDATPVNPSGFLE-----------------
>Rhizobium_etli_CFN_42 gnl|BL_ORD_ID|2123 gi|86357457|ref|YP_469349.1| lipoprotein precursor protein [Rhizobium etli CFN 42]
-----MRFSLSPKF------GKS-----AG---------------NLLVVGLLASAATGC
----------------------------------------------SSD-VTRFGGLFSS
SGQDQVTTSSIPRR--GGVQGD-P--VPRADLGGS----AVAS-----QSGY-GGNNALN
QPYPANP--------------GYEPVR--TSSAR-LASSPVSIQRSELAAPTA-AAPSRQ
R-----------------------DKEVALAQPFPASPQAQKP----------RLVAP-A
APKATP-DSLTTG------TTPKISGWS--------ST-----NAPSVTLRPGENIA---
------TLSRRFGVPEKEILRINNLKTASAAQPGQAILIPTLN---GGNAAKAASQA--A
-----DLAKPGNMPEPAKAPEQKVAVVPGANSARDKTMASADPA-AKL--PAGAG-----
-----KDPKAPA-GTYVVKQGDSLAKIAKATGANID-------------------DLKAA
NNI-SA-SSLRVGQALKIPAA-----KA-D------TIKTA-------SIPAE-------
--------------------------KVESKPADPAP--AQQTASVQPAP------YKAP
AA------------TQTVDEVEK------------------------------KA-DVSS
DAPEST-GIGKYRWPVRG-QVIAA-YGA-NVN-----GSRNDGIDISVPQGTPIKAAENG
VVIYAGNGLKELGNTVLVRHDDGTVTV-YGNADTLSVARGQKIQRGQTVAVSGMSG-DVK
QPQ-VHFEVRKDASPVNPMTFLE-----------------
>Sinorhizobium_fredii_NGR234 gnl|BL_ORD_ID|4086 gi|227821941|ref|YP_002825911.1| lipoprotein [Sinorhizobium fredii NGR234]
-----MRKFSSPSA------GKS-----LV---------------RLSGAILLASVATGC
----------------------------------------------SSD-VSRFNGLFSS
S--DDITTSSIP---G-------N--VPRGDVSSG----QLAS-----SAG--AGGGSYG
QAFPSSG--------QSASYDPMSTASTPVSSAR-AASTPVSVQRTALAEPTA-AMPRQP
-------------------------------QPLPAARQP----------------QP-V
LAKAEP-LPSSSS------GASGKGGWT--------TA-----NAPTIMVRPGDTVA---
------GLARRFGVPEKEILKANGLKSASQVEPGQRLVVPTFGG--ASSAAKAAASGSIA
-----DFEGGKRQPSPLPEGQREMAILPGQSQSREKSEGRSDVAAGKL--NNAGA-----
-----G---DGSDGAYTVKPGDSLNKIAKANGVSVA-------------------ALKQA
NGL-TA-ESIRIGQKLKMPGAAGS--AT-D------AVVTA-------SV-PA-------
--------------------------KSETKV--------ASLDQGKPAE------YKPP
VA------------KESVSDVAI------------------------------KT-DIDQ
ESPKST-GIGKYRWPVRG-AVVAG-YGA-NVD-----GNRNDGINISVPEGTAIKAAENG
VVIYSGSSLKELGNAVLVRHDDGTVTV-YGNASQLKVQRGEKVQRGQTLAASGMTG-KAS
QPQ-VHFEVRKNATPVNPATFLE-----------------
>Agrobacterium_vitis_S4 gnl|BL_ORD_ID|3996 gi|222148964|ref|YP_002549921.1| lipoprotein [Agrobacterium vitis S4]
-----MRQSQSYKS------GMP-----VA---------------QILWVGLMASVATGC
----------------------------------------------SSD-SSRFSGLFSK
T--DSMTTASTGGQITGMANA--P--VPQTDVDGGGSYAPAASGGSMGGGGYGNRQQAMT
QPYPAQQ--------T-------------YSPAR-RASSAVSVQKAELAPPSGSTASTGP
--ISS-------------------RRQTASAQPFPAATHQSAALEDGDGLSTNTLPQP-A
KPGLPS-GQGAGA------NGQGANGWS--------TV-----NAPRVVLKPGESLA---
------TLSQRYGVPEKEIVKANGLSTAGAARPGQSILIPTFGS--RNTPTRAAAAE--G
-----TLLPPGQSPGPTPRQEEKVAVLPTNPKLRDKVKT--DIAANNT--TNAAG-----
-----TGKTPPAAGTYVVKSGDSIAKIARENGVSVA-------------------ALKQA
NHL-GT-QGVRVGQTLELPQADQKLAAT--------PVSTA-------PANTK-------
--------------------------PEAPKV-----------TAAAPAP---------A
AP------------TKSVTDVA-------------------------------SA-DPGD
KAPDAT-GIGKYRWPVRG-AVVAP-FGA-NVA-----GKRNDGIDISVPTGTPIKAAENG
VVIYAGNGLKELGNTVLVRHDDGTVTV-YGHADAISVQRGQKVQRGQQVATSGMSG-NAS
QPT-LHFEVRKDATPVNPMGFLE-----------------
>Brucella_abortus_A13334 gnl|BL_ORD_ID|2742 gi|376273386|ref|YP_005151964.1| unnamed protein product [Brucella abortus A13334]
MDELNMRLPILQHT------SER-----LL---------------RNVAIVLIAGFGAGC
----------------------------------------------SAD-TMRFT-----
---DGIFTGSTSSQPVAQ--------QPAGNVYASAPVASAPP--------VSSGTVQRN
SLPPVSS---------------------------APLG-----------APVAA------
------------------------------------------------------------
-------------------------------------------ASTQMRNQVDQAQDMAA
SRVNNTVNAAETRVASAATVTHNTVNGAKEKVLGQL------------------------
---------PATGQGAPRPMDNNIAGVPQAPAVNGKKSSPTNMA------SAGGA-----
-----IATPPSVGGAYVVKSGDSLFSIAKKHNVPVD-------------------QLKAA
NGL-TS-GAIRVGQSLVIPSA-----AAGA------PTQVA-------AITPQ-------
--------------------------PANPAKAAS----APANGGAEVKP------YTPP
QAS-----------NKVIEDAE----------------------------------KDQA
AAPSST-GISQMRWPVRG-RILAS-FGQ-REG-----TSVSDGIDIMVPEGTPVKAAENG
VVIYAGDGLKEFGQTVLIRHDNGLVTV-YGHNSQIMVQRGQKVRRGEEIAKSGMSG-NAK
SPK-LHFEVRKNSAPVNPTKYLE----------------S
>Ochrobactrum_anthropi_ATCC_49188 gnl|BL_ORD_ID|2320 gi|153009667|ref|YP_001370882.1| unnamed protein product [Ochrobactrum anthropi ATCC 49188]
MGELNMRLQVLQHT------SER-----LL---------------RNVAIVLIAGFGAGC
----------------------------------------------SAD-TMRFT-----
---DGISTGSTSSQRVAQ--------QPAGDLYASA--APVAP--------ASSGSVQRN
SLPPVSS---------------------------APMAAPVAAARQSVQAPVAA------
------------------------------------------------------------
-------------------------------------------ASNNIQNQVGQAQDMAA
NRVNNTVNAAETKVASAATSTRNTVNGAQEKVLGQL------------------------
---------PAN-PAMPRPTDNNIAVVPQAPAVNGKKPSANDMA------SAGAN-----
-----ATTPPAPNGTYTVKSGDSLFSIAQKHNVPVE-------------------QLKKA
NGL-SN-GAIRVGQALVIPSA-----AAGN------ATQVA-------AVSQP-------
--------------------------PENPAKAAA----PAAN--ADVKP------YTPP
QAS-----------NKVIEDAE----------------------------------KDQA
AAPSST-GISQMRWPVRG-RILAS-FGQ-RDG-----TSVSDGIDIMVPEGTSVKAAENG
VVIYAGDGLKEFGQTVLIRHDNGLVTV-YGHNSQILVQRGQKVRRGEEVAKSGMSG-NAK
SPK-LHFEVRKNSAPVNPSKYLE----------------S
>Mesorhizobium_loti_MAFF303099 gnl|BL_ORD_ID|850 gi|13471177|ref|NP_102746.1| unnamed protein product [Mesorhizobium loti MAFF303099]
-----MQLSVLKTN------SRN-----LA---------------RGCAVLMIAGAAAGC
----------------------------------------------SSQ-ASRFNSV---
---DDVFTSSTNNQRAIIN----K--QDAVQPYPGDVSA--AP-----LDGSHTQSVSRS
SLEPVSS--------R-------------------PLPPPASAQAQPAPA-LA-PAANPV
------------------------RVASAPAMVRPAPHVD-------------RTTTGTV
EPAAKP-FKNAQP------DAPKVADAG--------RP-----HATEIVVRDGETIS---
------GLAAHYKVPADVIMKVNGLSPTKGLKTGQKIVIPAYAY--SSKAEPKVADA--K
QLKDGPAK-DGKHDLPATAPD-KVAVLPQQPKLKEGKSAAQVDA------SAAASQPKEP
KPAQ-VAKATGAGGTYTVQSGDTMSSIARKTGVGVV-------------------ALKQA
NGM-KD-GLLKIGQTLKVP-------AG-G------TATVA-------SSKPA-------
--------------------------KVDPVTTATTQPPAKTTPSETLAS------YTPP
--------------KKDAKVIQQ------------------------------AE-DDEA
VAPDAT-GIGKMRWPVRG-RVISG-FG-----------SGKDGVDIAVPSGTPIKAAENG
VVIYAGDGLKEFGNTVLVRHENGLVTV-YGHASSIEVQRGQKVKRGQEIALSGMSG-TTD
SPK-LHFEVRKNSAPVDPSGYLE-----------------
>Bartonella_clarridgeiae_73 gnl|BL_ORD_ID|994 gi|319899188|ref|YP_004159281.1| unnamed protein product [Bartonella clarridgeiae 73]
-----------------------------------------------MILLAVTAITTGC
----------------------------------------------SSS-TERFYG--GS
YNNTTPVHSITTMTDDSG------------------------------MLSQNV-EIQSS
ELPPVES-----------------------------------------------------
------------------------------------------------------------
---------------------------------------------------SSISEA---
------GYDSIYNDSSRQGEVSYSDKNKQFFSDGRVMGTPPRNLGTLPRSQI--------
------------------------------------------------------------
-----NTFPVFKRNSYIVQSGDTLLSIAQQLGVSVD-------------------ALRLV
NGI-NA-NSIYIGQSLIIPDRSTKMASNVQ------DSTSD--------VSKK-------
------------------------------VFSSQSKNVSSVEQKKTPASVYEAPIKTAP
AV------------KNNMLDIEKNSL-----------AQATTHKSINDSSDRVTD-PNDI
VVPQST-GISKMRWPVRG-RLLSH-FGQ-KKG-----TAVNRGIDITVPEGSSVKAAENG
VVIYASDGLKKLGNVVMIRHENNIITI-YGHNSKLIVNRGQRVRRGDEIAKSGFSG-DAK
TPR-VYFEVRKNSIPVDPAEYLE----------------N
>Beijerinckia_indica_subsp_indica_ATCC_9039 gnl|BL_ORD_ID|2826 gi|182679614|ref|YP_001833760.1| peptidase M23 [Beijerinckia indica subsp. indica ATCC 9039]
-----M-RFSFSLRGSRAATSCL-----AL---------------RLALTGATAGLLAGC
----------------------------------------------AN--SERLSD----
-PFGNPFQSSANGTD--------S--TPTGSLGSYQQSAPVTP-----VQRHALGQAIPQ
PAAPP-------------------------------------VQTRSLTAATVPVAPSLP
-------------------------------RGAGG------------------------
-----------------------AAGWT--------IE-----GGTPIAVRPGESAS---
------VLAQRYGVPTESLVRANGFGSAGEIQPGTRVVIPVYNAALAASSGAHLVQN---
----------------------TEQAVSRTATAAQNLP-------TRL--PTIP--KPTP
I-----AQAEPVKLVRNVAQNTTKSVVAETNAVKGAARAKLVQGHAQEQAVVQHVQTAQA
TVK-SQVKPEAIAK--NVAKAEHLAKPE--------PIAKA-------EATVK-------
--------------------------ATAGKLEHAQVETKKAVKTAAL---------APA
REAR---IA-------ESKPVEARAVEPKQTRSEVKQAEPVKSAEP-VAVEPARE-AAND
S------ANPEFRWPARG-RIIQS-F-----K-----PGGNDGINIAVPEGTAVKAAEGG
VVAYAGSELKGYGNLVLIRHPNGFVSA-YANNGDLEVKRGETVKRGQTIAKSGQSG-NVN
SPQ-LHFELRKGATPVDPTQYLA---------------GL
>Methylocella_silvestris_BL2 gnl|BL_ORD_ID|1320 gi|217977521|ref|YP_002361668.1| peptidase M23 [Methylocella silvestris BL2]
-----MSHIALVYR------SRL-----AF---------------RFALIGVSASVLAGC
----------------------------------------------AG--SERMAD----
-PFSNPFSTAQAPTD--------P--APTSSINP---GAPVTP-----VQSRPLAAASSQ
RPA---------------------------------------------------VVASLP
A------------------------------HGAQG------------------------
-----------------------PAGWT--------AA-----GGTPISIAQGESAD---
------LIARRYGVPTDALLKANGFSNAAQVQPGARVIIPVYHAVGA-------------
-------------------------------------P-------MAV--AQAP--AAAP
V-----SAPKP----------------ARTPDEMHAQKIKLLKGAPATQ------QFASA
SAN-SAAKSEKLG-----------APPR--------SAAFV-------PETPK-------
--------------------------KTA----------EAAAKAAAA---------QPA
VSTK---AA-----SIKTEPVKTAAL----TKADTPKAETAKSAAPAVEAKAAAE-DEGD
SGKAAG-ANPEFRWPARG-RIIQA-F-----K-----PGGNDGINIAVPEGTSVKAAESG
VVAYAGSELKGYGNLILIRHPNGFVSA-YANNGDIEVKRGETVKRGQTIAKSGQSG-NVA
SPQ-LHFELRKGATPVDPTQYLA---------------GL
>Bradyrhizobium_sp_BTAi1 gnl|BL_ORD_ID|4369 gi|148255769|ref|YP_001240354.1| peptidoglycan-binding LysM [Bradyrhizobium sp. BTAi1]
-----MPAIVELPR------SRR-----LP---------------QFAALALMSFGVAGC
----------------------------------------------SADMSTRLSQ--AQ
NPFSNPFA---SDA--------------TGSVQ----APP-R-------QHQPVAQQYTP
APAPA-----------------------------------PTYSSSALPPPAVATPQSYP
SGGGS-------------------GGVSGGGRGVASYVPPAAVPAAAPQPAYAQP-THSY
APPAQP-QLETTGA---V-PPRSVAAAR--------PT-----GGTKIIVGTSDTLE---
------ILAKRYRVSPAEILAANGYKGPRALSPGQQLTIPHPGAVAAA------------
-------------------------------------P-AAQPVATPV--AAAP-VAPKP
VA-V-AAATAP-STVHFVNRGETLASIARQNHLTPA-------------------ELARA
NNL-DQASPLKLGARLTVPA-KAAAVAA--------P--VA-------PVA-T-------
---------------------------------------VPQAVATVP---------APA
PTTR---VA-------AAGPVQTARL-----------AQANPAPE-----KE--E-EPAR
PAETTS-SLPTFRWPARG-KVITS-YGA-KTN-----GKSNDGINIAVPEGTPVKAAEDG
VVAYAGNELKGYGNLVLVRHSNGYVTA-YAHASELMVKRGDPIKRGQVIAKSGQSG-EVG
SPQ-LHFEIRKGSSPVDPLQFLN---------------GA
>Rhodopseudomonas_palustris_BisB5 gnl|BL_ORD_ID|2768 gi|91977251|ref|YP_569910.1| peptidase M23B [Rhodopseudomonas palustris BisB5]
-----MSRVVELLC------SRR-----AP---------------QMAVLTLISVGFSAC
----------------------------------------------SADMQTRFQQ--A-
-PFG---P---VET--------------TGSVQ----QPRYG-------ERRELPQYARP
QYQSAQP--------Q-------------------YQPAQPQYQSQALPP--IAAPPSYP
VAGGG-------------------SGVSSGGRGVAS-----------------------Y
EPPQRA-PIETTGT---V-APRSVAAARPAPAPAAVPA-----SGTTIIVGTSDTLE---
------GLARRYNVATADILQANGYKGPRRLQPGQSLVIPQRTASLQA------------
-------------------------------------PVAAPPVARPL--AAAP--APMP
V-----AAAAP-PRVHYVNSGDTLMNIARRNNISAA-------------------ELARY
NRI-DANARLQPGMKINVPGAQSAALAA--------PPLAA-------PAT-A-------
---------------------------------------QPAAQPAVS--------AAPP
VRMA---VA-----A-PADPVQKARM-----------VAPTETPAA---AEPAEA-SPVK
SAEATG-ALPSFRWPVRG-RVITA-YGA-KTN-----GKSNDGINLAVPEGTPVKAAEDG
VVAYSGNELKGYGNLVLVRHSNGYVTA-YAHASELMVKRGETIKRGQTIAKSGQSG-EVG
SPQ-LHFEIRKGSSPVDPLKFLN---------------GA
>Oligotropha_carboxidovorans_OM5 gnl|BL_ORD_ID|2220 gi|209885381|ref|YP_002289238.1| peptidase M23B [Oligotropha carboxidovorans OM5]
-----MSRLLELLG------TRR-----VP---------------SLAVMALVSVSFGGC
----------------------------------------------SADYDSRFSD--NS
--FQNPFASQRSDA--------------TGSVR----QNNHY-------AQRELPQYSRP
ASHA----------------------------------------------PVVSAPLSYP
AAQGN----------------------SGGGHGMAS-----------------------Y
TPPASN-PIQHTGS---VNAPRSVAATR--------PE-----GGTKIIVGTSDTME---
------ILARRYNVSVADIVRANGYRGPRALSPGQSLIIPKRAAQAQA------------
-------------------------------------P------------------APAT
R-----GATMP-SSVHVAAPGDTLMNISRRNHISVS-------------------ELARA
NNL-PVTAQLKVGDRITVPSSSKTLAAA--------QPAPA-------PAAPA-------
---------------------------------------QPVAAAAPP---------KPQ
PVAAKPVVT-----A-SAEPAQKVRM-----------ATETKEIE-----RT--H-SPVK
AAEATN-ALPTFRWPVRG-RVITS-YGA-KTN-----GKQNDGINVAVPEGTPVKAAEDG
VVAYSGNELKGYGNLILVRHANGYVTA-YAHASELMVKRGDSIKRGQIIAKSGQTG-EVG
SPQ-LHFEIRKGSSPVDPLQFLN---------------GA
>Nitrobacter_winogradskyi_Nb-255 gnl|BL_ORD_ID|1764 gi|75675964|ref|YP_318385.1| unnamed protein product [Nitrobacter winogradskyi Nb-255]
-----MSRVVELLC------SRR-----VP---------------QVAVLALVSIGFAGC
----------------------------------------------SADMSTRLAQLDSG
PQQSNRFGWQ-RET--------------TGTVA----AAPAAP-----VERRELHQYSRP
PYRPH-----------------------------------SDYQSQPLPP--ISTPKSYP
VAS----------------------SVSVSGRGPGS-----------------------Y
TPPARA--IESAPA---V-AARD--GWN--------HK-----GGTPIIVGTSDTLE---
------GLSRRYGVSSAEILKANGYRGPRQLQPGQRLIIPKRAAVAETQ-----------
-------------------------------------P------------------APAA
KPAV-VATAAS-GATHHVNRGDTLMNIARRNHISVG-------------------ELARA
NGL-PPSAKLKIGTRITVPT-KVAAVSA--------QPVAA-------PA--A-------
---------------------------------------PPAVAP------------KPA
PAPVVHAAA-----A-TAGPVQKVNL-----------AAATATPE-----AAVVK-PSVK
AAEATG-ALPTFRWPVRG-RVITA-YGA-RTN-----GKSNDGINVAVPEGTPVKAAEDG
VVAYAGNELKGYGNLVLVRHSNGYVTA-YAHARELMVKRGDSIRRGQVIAKSGQSG-EAG
SPQ-LHFEIRKGSTPVDPLNFLN---------------GA
>Hyphomicrobium_denitrificans_ATCC_51888 gnl|BL_ORD_ID|1252 gi|300022791|ref|YP_003755402.1| peptidase M23 [Hyphomicrobium denitrificans ATCC 51888]
-----MMNCFGVSHGGRF--SLK-----SA---------------AAVSTVIAGLAIGGC
----------------------------------------------SADV-TRFDS--AS
FNLNDPPDARPIPSQ--------S--IRTSSLS----------------DSTAVGQPPRG
PYGAG----------------------------------ASSVQVAALPD---AGPSYQP
APS--------------------------------------------------------Y
SPPAYN-PPPAYSAPAKSYEPKPFGRARSDSAPSARPAMQAALNGNEIIVQPGDTLY---
------SISRAHHVSLAELMSANSLSNP-NVHPGQKLILPSSSGARSS------------
-------------------------------------RSSVAAAKAVE--SARPAPAPLA
EPPH-DVAANY-NSTYTVKAGESLYGIARAHNVKFA-------------------ELQQV
NGI-ADPRRVKPGVVLKVPGRSGADMPASQ------PAPAA-------PASVADNAPAAI
VPPLAATEKGSDIPAYGQSLSTRPTIINSERRVAALTDTGKATDAAPAAP------AAPA
PSVALSEPP-----A-SAPPVAEAAP-----------AKAEQKVA---------L-AAPA
AASAVA-DSVKLRWPTTG-RVIAG-FGG-RPD-----GTHNDGINLAVPLGTEVHAAESG
VVAYSGNELKGYGNLVLLRHDNGWVTA-YAHNDELLVKRGDKVKRGQVISKAGKTG-SVD
QPQ-VHFELRQGSRPVDPTPYLE---------------KL
>Magnetospirillum_magneticum_AMB-1 gnl|BL_ORD_ID|2518 gi|83311617|ref|YP_421881.1| membrane protein related to metalloendopeptidase [Magnetospirillum magneticum AMB-1]
-----MI---------------------AAGRRRAYSTGMRHAPHHLVILLILAAAISAC
----------------------------------------------TPSYDSKVPVGRSD
GPLQVQ------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------RPATVTVYAGDTVY---
------SIARRYSLTVRDLIETNNLQPPYQLQPGTVLRLPGG------------------
------------------------------------------------------------
------------GSDYVVQRGDTLSVLARRFKVDFN-------------------SLAAT
NGK-RAPYVLQVGERLTIPGPKASVTQTAA------TPAPA-------------------
-------------------------------------TGGGSMVVTSPHASGGAGGGKPA
A-------------KAEVPPVYAQAP-----------------------SHPAPPPAAVP
AVPPAR-AGSTFLWPVKG-EVVAE-FGPLPGK-----GQHNDGINIVAAKGTPVRAAENG
VVAYVGNELKGFGNLLLIKHADNWMTA-YAHNDQLMVKRGDRVRRGQTIATLGASG-SVT
SPQ-LHFEIRRGTEAVNPVEYLQDKVADDGAVRQLAAIAY
>Hirschia_baltica_ATCC_49814 gnl|BL_ORD_ID|1392 gi|254293769|ref|YP_003059792.1| peptidase M23 [Hirschia baltica ATCC 49814]
-----MSEQKRLSTRS-----------------------------VLTIKLVLACVLSMC
WCAPAIAQARETAPVEFRSAARYSEYRIPEGADYAPVTQGSPLGQPDTQYYEKVAQAREQ
AERQRLAAEQVAQQQARANAINNS--QPEIYSQAGSAQQKYVTHQSTGVYQQGIAQTRYP
PVTYGQAGTQIVDTNSSLNQQQFGTSANYANSGMPQTIPHLAVGSLPAAAPIANIYATPM
APLSGGVAGGGALIGAGVVDHSFKQRELSGAGEMSFSNEDLMGMDEGRYDNAASMQSLSH
SQHQQT-LVSNTSTASVYSQPSNISAYTN-------ASVSELPVGDKVEVLAGDTLY---
------SLSTRYRVALRALVETNDLQPPFRLEVGSFVHLPP-------------------
------------------------------------------------------------
------------PNIHVVETGETLYAISRRYNVDTR-------------------SLANM
NGL-PKPWTIYPGDQMILPSLARDSFAS-E------STAIA-------SAKAR-------
-----------------------------DKILRESKGIAAPIVGQTATA------SSPT
AVQLGGDQQ-----AGPGLAVDSAKL-----------AVKNEALGRFDESAPVSAIKTSE
KIDLPG-DAKGFVWPVNG-NIIKT-YGQ-MPN-----GKINDGVNIAARAGSTIKAASDG
YVVYAGSELPGFGLLILINHGNGWVSA-YAHAEELLVEENQPIRQGQAIAKVGETG-SVD
RPQ-LHFQLRRGKSPIDPASHLL------------PKRSI
>Pelagibacterium_halotolerans_B2 gnl|BL_ORD_ID|1441 gi|357384516|ref|YP_004899240.1| unnamed protein product [Pelagibacterium halotolerans B2]
-----MTLSVTGSK------LRS-----AG---------------SALAMSAAALVLAGC
----------------------------------------------SS--MGSFGG----
---DPTVTGATSRMGGAVVGQAMPAYLPPANIGGGVAA----------NGTTGPALIDRT
TASPVGT-----------------------------QSAVVSQDLPALQPSSVTSTQAMP
AQTAA-----------------------------------------------VSSPSSTL
SQAAQP-------------------------------------SAPQLGVVQGDTYS---
------------------------------------------------------------
------------------------------------------------------------
---------------HTIASGESLYTIARRYDVSAT-------------------EIIAA
NNI-GSPDRIVVGQSLIIPGRPDLLAQRGQ------TQQVA-------AVSGS-------
-----------------------------QAAASPSGTSAANTQTATPAP------AAPA
R------------------------------------PEEQPEPQPTQVAAAPTQ-QPTP
AATASV-TSDKFRWPLSG-RVITD-FAA----------SRGTGINIEAPEGTSVRAAENG
EVIYVGNAVEGYGNLVLVKHANGFVSA-YAHLNTIGVVKGDSVSRGDALGTVGMTG-SVS
RPQ-LHFELRKGATPVDPMPLLA----------------G
>Ketogulonicigenium_vulgare_Y25 gnl|BL_ORD_ID|1386 gi|310815671|ref|YP_003963635.1| LysM domain-containing protein [Ketogulonicigenium vulgare Y25]
-----M---------------KN-----LG--------------LHLMGGVALMAL-AAC
--------------------------------------------NDVPDYDLR--GMGTG
FTTAGAMPS--TNNR---------------------------------------------
------------------------------------------------PAPDANGVISYP
------------------------------------------------------------
-------------------------------------------TYQVAVARAGDTVA---
------TIAGRLSLDAGQLASYNGLQTGTSLRAGEVLALPARVS----GGLSGGM-----
----------------TDITSIAGAAIDRAGDVT---------TTALA--PSGSSAATAP
AASSTPLQIS-EPVRHQVARGETAYIIARRYNIPVR-------------------SLAEW
NGL-DSNMTIREGQYLMIPTANGTP-----------STTPV-------TSAPG-------
---------------------------------------QGSATPVPPSA------SQPM
PSEATP--------PAAAAPAAAAAA------------------------AAATP-NLGA
QQTSASQSTSTLQRPVAG-NIIRA-YAR----------GRNDGIDIGAPAGTDVQAAAAG
TVAAITTNTDGI-QIVVIRHDGNLMTV-YTHLDRLTVARGASVSRGQVIGKV--AD--GA
TPY-LHFEVRRGLDSVDPSTMLP-----------------
>Rhodobacter_capsulatus_SB_1003 gnl|BL_ORD_ID|2391 gi|294677949|ref|YP_003578564.1| M23 family peptidase [Rhodobacter capsulatus SB 1003]
-----MQAPHS----------RR-----LT--------------RVLLTGVALAVL-AGC
------------------------------------------GKDGSFDADLRHFGKTG-
FDTTDAVRQA-TADR---------------------------------------------
------------------------------------------------PAPDARGVISYP
------------------------------------------------------------
-------------------------------------------NYQVAVARQGDSVG---
------SIASRLGLDAAELARYNALAPNTPLGKGEVLALPKRVGEPAPAAVAGGAAAAGS
--------------ERIDITSLAGAAIDRAAVTQPPAETPAAPATAPR--PAAPSASPVA
KPAA-PAQTGAEPIRHRVARGETAYSIARYYNVPAK-------------------SVADW
NGL-PADLSVREGQMLMIPPATGAAPR---------SATAT-------LTEPG-------
---------------------------------------EGSPTPEPPSA------AKPL
PKEVPP--------K-ASDPVDTSAA----------------------------P-DLGA
ARTEAS-RSSKFVMPVPG-AIIRP-YAK----------GKNDGVDIRAAAGTAVKAADAG
TVAAITKDTEQV-PILVLRHEGGLLTV-YANIDGITVAKGDKVRRGQSIAKV--RA--GD
TGF-LHFEVRKGYDSVDPMPYLD-----------------
>Ruegeria_pomeroyi_DSS-3 gnl|BL_ORD_ID|2622 gi|56697528|ref|YP_167896.1| unnamed protein product [Ruegeria pomeroyi DSS-3]
-----MS---VL--------FRT-----LP--------------RPLMGLSALALL-AAC
--------------------------------------------EAPLDYDLR--GQIGA
FNTTEAAQSARTAAR---------------------------------------------
------------------------------------------------PKPDERGVISYP
------------------------------------------------------------
-------------------------------------------NYQVAVAKRGDTVA---
------TLSDRVGLPVGEVARFNGLQPTDGLREGEVLALPRRVTEPVGQGNN--------
----------------VDIASLAGSAIDQAPDTTP------VQTTALE--PAKPAASPAP
KPAA------PEPVRHKVERGETAYTISRLYQVPVK-------------------ALGEW
NGL-GPDFTIREGQYLLIPVKDQPAPKSAAKPAAATTTTAA-------VSAPG-------
---------------------------------------AGSATPTPPSA------TKPL
PEEKVP----------AAKPAE--------------------------------P-DVSV
GQPTAS-SNARLGFPVKG-KIVRP-YSK----------GKNDGIDIAGAPGSAVSAAEAG
TVAAITADADQV-PIVVIRHADNLLTV-YANVDGIEVNKGDTVSRGQKIARLRG----GD
NAY-VHFEVRKGFDSFDPEPYLK-----------------
>Magnetococcus_sp_MC-1 gnl|BL_ORD_ID|366 gi|117923685|ref|YP_864302.1| unnamed protein product [Magnetococcus sp. MC-1]
-----MDRLTIK---------------------------------HRLTGLMTLLLLGGC
-----------------------------------MPLDTLNLSTTPTDTPVRVARGPAL
GWQPTTTPNHVEPS----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------NAPTYQVQAGDSLW---
------SIAMSHQVDVFDLARWNGVDDPDKVVAGQLLYVRSPS-----------------
----------------MPVPNGKPDVMDEGN-----------------------------
------------------SSGDTPLRTVHLPQPSVV-------------------AQPDP
MGV-AQSGGFLKQHSFILPTGRTAPLPLPA------LATPL-------AAVGS-------
--------------------------------------TATPTDKATPAPKSRDLTTQPA
TRQIV---------VQIRGDEEKPGI----------------IQQPATLSSATAA-ANLQ
RMKGKP-APQQWNWPVQG-TVVAS-FGR--RG-----AKINPGIDIAAEKGTPVLAPAAG
VVAYVGGH-DSFGNLIIVNHGGDYKTL-YAHNDVNLVERGQEIRPGQMIARVGNTGVRVR
SPR-LHFEIRRPIKPLNPLNYLS----------------K
>Agrobacterium_sp_H13-3 gnl|BL_ORD_ID|1780 gi|325293234|ref|YP_004279098.1| membrane protein associated metalloendopeptidase [Agrobacterium sp. H13-3]
-----MTDTAENRVFGKK-RQQHVLVLASG------------DKVRHMTIRPWMTALAGC
-------------TIGLFSLGYLGATGYLILRDDLIGATMARQTRMQHDYEDRIAA----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------LRAQVDRVTSRQLFDQQVVEKKVEKLLQQQAALTSRHGRMSELLERAENSGIAA
STATAPIPTAPSSLSNAMAPEKRADLT-----GGLSAIENLMAPRPSQPEKPAGTDKRAS
YVPENGETPSDRADRVFSKVTLSLKDIERQQISRIA-------------------RLTSD
----AEDKASAMQDIIRQAGLKIDESDT--------DGVGG-------------------
-----------------------------------------------PYADPQGNETDPF
--------------NMSLTNLDNAL-------------------------------NRLD
IVKETA-TALPFGNPAPGRAITSR-FGN-RLDPFLGRPALHTGIDFRAETGADVKATGAG
KVTVAENS-GGYGNMVEIDHGQGVSTR-FGHLSTILVKAGDKVEAGDIVGRAGSTG-RST
GPH-VHYEVRRNDTPVDPMRFLV-------AGAELKTYLK
>Caulobacter_crescentus_CB15 gnl|BL_ORD_ID|3407 gi|16127664|ref|NP_422228.1| M24/M37 family peptidase [Caulobacter crescentus CB15]
-----MSRSR--------------------------------------------LVLAFC
--------------------------------ALILAVPTAVVGWQRADAAFEARRARDR
QIAAETR-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------REIQDLRAELDRLDHAR
IAAGVDVDAKRARLEA-----------LNARENAILAELGRNRQRLSLLLSALQMFRRDP
------------------------------------------------------------
------------PPALLVSPGDARNAVRAAILIRAM------------------------
-----------------TPELKQRADAYGR------QAVAIRALRREAAAASAELFTAES
VVADRKGEIERLIIEK----------TELERAYAQETLTQANELKTLGAL----------
--------------------------------------------------------TDGL
GNAQPS-GPLSLRPPVQG-AIVRR-FGQEMPA-----GGKSPGLTLRPEKGATIAAPAGG
VVEYAGAL-NGWGAVLILRVQGAYHIV-LAGLDQINVSPGQSVAAGAPIGKMPDP--VSS
EPE-LYMEVRENGAPSDPERWLK-------------QESR
