>gnl|BL_ORD_ID|0:46263202-46268916 gnl|BL_ORD_ID|12 SL2.31ch12
ttataacacctacaatagaagatgatcaacaaagaaatagtccatttgtagttggtccag
gtggttacaacttttcagtgcaactacttgcctttgccaaggcgattaacatcaatctac
aaatcaacagactggagaattacccacttcagaatcttgattcgcaagtgataaatacat
ccccagatgaaatcttggttatttgtgcacagttcagactccataacttgaaacacaaca
atccagacgacaggacagagttgttgagaagactaaagagtttggagccaaaaggactgg
ttttgagtgagaacaac---------atggattgcagctgcaacagttgcggggacttca
caacaagattctcaaggcgagtggagtact-tgtggaagttcttggactctaccagtgta
gcatacaaaggacgtgagagcgagggaaggaggatgatggaaggagaagcagcaaaggct
ttgacaaacatgggagagatgaatgagacaaaggagaaatggtgtgaaagaatgaggagt
gttggtttcgtatgggagatgtttggagatgatgctattgatagagctcgtgcattgttg
aagaagtatgacaacaactgggagatgagagttgatgagaaggatggctgtgttggactg
tggtggaaaggagatcctgtttcattttgttcattatggaagatagatcacaacacatga
gatgcacaaggcttttaagcacaaacagagtcaaaagtctaccggtaaatctagagcctg
gaagaat--ctttcattagctgtgctttgacacaggttcagatagtgcatttgcaaaggc
aacaagtcaaaaaaattatcaaattccttaagaatttgattctaggcaaggtggtcatgt
acctataagaatatagatgtgtaattattgtgtgttttgatgaaataactgagtgcttag
aactcaaagcttttttagcaaaatgactccctagcattgtaat--gaatattgtctttaa
gggtacaataatgagtcagc-----------------------------------aaaaa
atgtatgtacagacacgaaaaatatgcatgttaaattctagtatctaatcccctcggaat
atcaacgaccatcctcccatgagacagtccaatgtagttttcatcacatgctttacaaat
gcacaaccaccttcccag------catcagctactcaaaataactcgtaactatttgctc
gtcaagaatcatatatccttacagaactatgaattgtctgcctacataaaggacacttgg
gt-------------------gctaaatcacgttcaactgacaaggcacagcgctggcaa
cataccaggtgtccacacggaacaaatgctgcgcgcttcctcctcgtaaggcatatcaca
cacaactgaccatcgggaacatctccagattcctcatcagcactaacctgcacatcatcg
tcattgcttgcagcatccctttgttgctgagcctgcctctggtgtctccacagcttccat
cgattccagttcctaaaacatataaataccaatgagaaaatgcgaccactacagtaaata
ctttttcaccctgttttcctttcaaacaagcatatctccccttttttctgttttttcagt
cttaggtttcctgggatagtgtagtctagaatatgtaagccaat----------------
--------------------ttcaaggttccgctcatctgaaatatgcacccatcatgat
tctttcatgcttaaaggtagctagctgcattattctttttggcacgtgatgatggtccta
ctcaaacatcaattgcatcagag-------ataaaactatacttccttcaattcaataga
atacaagtacactagtctgtatcgcacaacttccctaaagtaatatg-------------
------catcaaataattgcatacacgaaatgacaacaactgtaatccaaatcaaccaac
cagccttctacccagtagg--gttataagttcatgtcat---------------------
------------agtatttataagttgactcatttgatgcagccgcgagataaattgcag
a-----------------------------------------------------------
---tgaagtagggaaaggaatccatcaatctgggagcagatgtggatgac----------
ttgattatttaagaggtaaccactcaataga-----------------aggttcctacaa
ccctaactcatgctcggtaagcagaatcataaaatactatatgaaacaattaaggatttt
gtccctacctagacttcacgtcaactacagtctatgagagcgaaaaggacaaagaagaaa
atagagtgtcacagtgagatcttgaaggcatgatatccacaaaaaaagttcaagtgtttg
agagatgaaactagtttacctcacaa---------------cagcatatccaaggacacc
aactgcaactgaaccaaataaaactccactccacatcagaatttttgttttgaaggcaag
ctctaccagcatttgatccttggtcatatcagacctaccaaagtgaaaaattaacactca
caaatttcaacaaaataaatcaattcggaaataaaagatcacccaaattttagaacaaga
gctgagtgtcatgctttatcaatttattaagaaaactattctgtaaaccttccttacaag
aaatagggtaggtcttcacatgatttgatctccaaaatcccatcttttgagctgcaaaca
ccaatagcggttatatctttaccaagtggtagaattttttcttcatccaatactccaacc
tttgtcacagaaaacaatatgttacatgagttgcaggaagaaagacaaactttaaaagtt
gtataagcaatcacaaatggtcaagaagcccatatccacaacatatttttaaactcacag
gatagtgatgaccaaagagagcctggataaaagtgagaggcgtagcatgtaaaggttgca
agtgatgataaactgtcacaagagg-----------------------------------
---tagggaatgcgtagaaccatccatattgacattaacatattttggttgcggccacct
cccagtttcaataagaacaaagggaacctaagtcgaagatagagaagcacaaaagcttag
aaagcttatattatgaaaacaaataaagctatataacacttattagcaggcaaaagagca
gcaactacaaaattggagcgtattaactagatttaaagatgacgagtaggaaaaactttt
tatgcag----------agaaatttgcattaataattctaagat----------------
-------tataacttcttacaaaatattcacataacctagcagaatttatggcaaaaata
gaaaatt-------------------------gacaaatattagcaatactgactcaata
tc-tcttttgtgcttcactggtgaaattaaaggcactagcaaaatcaagagacttgtgtt
gttggaaaattttcacattaccgttctcaaagaggacgattgttgatccttccggactct
tggaaatat-------------tgaatacagatc----accagcccacgaaaagaagcct
ctccactcattatagatacactagaataagacagcaaatgaacatcagtatgctgccaaa
attcactagaaaaaaagaaatacacacaaaaactgacaaaaaaatagcagccaaacatag
gttgcaaattaaatt---------ggttgtggatcatatt--------------------
--------gtttctgtttaaagtacaccggttcaaagagttctttga-aaactgaaggat
gtccatcaccagt----------agataatagctattgatttctttctgt-----aacag
ctaatctatatattcacacgtataaaacatccaaaacacgtagttccccttcgaa-----
actgttaataattgttgatatttacaatgtaacaactgcagctt----------------
------------------------ccgcacatcaattccaaacaactttggataagctat
atgaatcctcacaatccatttagctctaatataacacaatttcattacaa-aaatagttt
gta---ttttaagacacactctcagc--------------------ctctgcgaccaaag
ggtcatgaggcgaagcgggaattcat-----------ccctagacatccctccctgt---
--gcaccagcttattat------------------------ctcatgtcctctctctatg
tctagggattccttcaacgcgggctaagcaaaacatcgattgttctttttttcgattgtg
cattaacatttaacaaaaatgtaggataaattatcacaagtacaagatcaaaccctgcag
tttaaccaaagtttgcaacccacattgtaattcaaaacgatcaccgcatcatatcacatg
cctaaaaaagccctaacaca-tcaattatagtgaatattcacaaatttagattgatcata
actaactctaacagtaccactaatcctaaatgtcgttgaatacgaaatttccagctcgaa
taaggatattaattgcctaataaagcatgataaattgactaatttaatactgtttgaaca
taaattaaagtaaaacgaaaagtgtagaaga------attatactgtttgagtatgttgc
aatataacgcctttttcagcagaattatgagctgagagaatattagctctcaa-------
---------------gcttttccagttaccc---tcaaccgccgatttcgcctccacagt
accgcgaacaatcacaagcttaccgtcatcggaatgatttgaactatcagagttgtcgga
agaagaaagtaatgaacggagatcggagacattaagcgacggcgcatcgttgattttg--
------------------tgaagggcggaagaattggctttgaacttgacaatactccgt
acggcaacgtaagc---tagggctaagccaataagtgcgccatccgccgccgtagctatt
tgcgatagcacggcagctgccgcttga---------------------------------
--tcgtatattgacatggctactttcaaattctc------ggtcgccggaaactgaacgc
tatttctatggcttgtttattggctat--------gagtacctctttttttaagactact
ttcggtttactaaagtgtttattataaatagattggattaaaatggattgtatttaagtt
tatcataaacttattcgataggt-attgtcaagataacttt-----ttgatagaaatgta
tttatttatgttatattaaatatggtgatcttttgattgatttttctacctataaataga
gatatcattcacta----------------------------------------------
-------------------ttaaaatatacacttgaataatatacacttgaataagaaga
aattttttttcttctatctatttctcttgtcttttttttctttatgattatat-------
--tcttatgagcttgattttataatacgttatcagcacgagtctctagccaattaagatt
------------------------------------------------------------
----------gagttttagttt-----ttctttaactcat--------------------
--------------------------------gttttggttgatctcgttatgaa--aaa
tcaaggtat---------tatatgcataaaatcaggtatgtattttctaaa---------
-----------------------------atatttttatgatttagaataaa--------
----------------------------atagtattgagtcactaac----------aat
tatcaggaatcgaagacatatactactattga---ttgaatatgacatgctat-------
-------acaaaatttcttaaatagaaaaaggtataaatatcatgagtttgaatattat-
-----------------------------------------------------------t
ttgattgttttgaaagactcagggtgagttatgttgtactttggtctattataccattag
tttaggg-----taagacgatgggttcaagtctcatcgcaccaaaaagggtaagacat--
caaattaagtccagatgcacataatgaaaaatattgacg-gataagacaatagatt----
----caaattctatcgccccaagagggtaagacatcaatttgaattttgatgcaccgt--
----gataataatgtattgggttcaagtcc----------------------------ca
tagaattatgac---------------------ctaatgtgcctttgtatgcataagaca
ttgagtttgagtct------------------caatgcaccatagtggtgataaaatg
>R_gnl|BL_ORD_ID|0:46263202-46268916
gtaaaatagtggtgataccacgtaac------------------tctgagtttgagttac
agaatacgtatgtttccgtgtaat---------------------ccagtattaagatac
----------------------------cctgaacttgggttatgtaataatag------
tgccacgtagttttaagtttaactacagaatgggagaaccccgctatcttaaac------
--ttagataacagaatag-gcagttataaaaagtaatacacgtagacctgaattaa--ac
tacagaatgggaaaaaccacgctactctgaacttgggtagcagaa-----tgggatttga
ttaccatattatctggtttcatgttgtattgagtgggactcagaaagttttgttagttt-
-----------------------------------------------------------t
attataagtttgagtactataaatatggaaaaagataaattctttaaaaca---------
-----tatcgtacagtataagtt---agttatcatcatatacagaagctaaggactat--
--------taacaatcactgagttatgata------------------------------
------aaataagatttagtatttttata-------------------------------
-------aaatcttttatgtatggactaaaatacgtat---------attatggaactaa
aaagtattgctctagttggttttg------------------------------------
----------------tactcaatttctt-----tttgattttgag--------------
--------------------------------------------------------ttag
aattaaccgatctctgagcacgactattgcataatattttagttcgagtattct------
---tatattagtatttcttttttttctgttctctttatctatcttcttttttttaaagaa
gaataagttcacatataataagttcacatataaaatt-----------------------
------------------------------------------atcacttactatagagat
aaatatccatctttttagttagttttctagtggtataaattatattgtatttatttatgt
aaagatagtt-----tttcaatagaactgt-tatggatagcttattcaaatactatttga
atttatgttaggtaaaattaggttagataaatattatttgtgaaatcatttggctttcat
cagaatttttttctccatgag--------tatcggttatttgttcggtatctttatcgca
agtcaaaggccgctgg------ctcttaaactttcatcggtacagttatatgc-------
----------------------------tagttcgccgtcgacggcacgatagcgtttat
cgatgccgccgcctaccgcgtgaataaccgaatcggga---tcgaatgcaacggcatgcc
tcataacagttcaagtttcggttaagaaggcgggaagt--------------------gt
tttagttgctacgcggcagcgaattacagaggctagaggcaagtaatgaaagaagaaggc
tgttgagactatcaagtttagtaaggctactgccattcgaacactaacaagcgccatgac
acctccgcttt---agccgccaactcccattgaccttttcg-------------------
---aactctcgattataagagagtcgagtattaagacgactttttccgcaatataacgtt
gtatgagtttgtcatatta------agaagatgtgaaaagcaaaatgaaattaaatacaa
gtttgtcataatttaatcagttaaatagtacgaaataatccgttaattataggaataagc
tcgacctttaaagcataagttgctgtaaatcctaatcaccatgacaatctcaatcaatac
tagttagatttaaacacttataagtgatattaact-acacaatcccgaaaaaatccgtac
actatactacgccactagcaaaacttaatgttacacccaacgtttgaaaccaatttgacg
tcccaaactagaacatgaacactattaaataggatgtaaaaacaatttacaattacgtgt
tagctttttttcttgttagctacaaaacgaatcgggcgcaacttccttagggatctgtat
ctctctcctgtactc------------------------tattattcgaccacg-----t
gtccctccctacagatccc-----------tacttaagggcgaagcggagtactgggaaa
ccagcgtctc--------------------cgactctcacacagaatttt---atgtttg
ataaa-aacattactttaacacaatataatctcgatttacctaacactcctaagtatatc
gaataggtttcaacaaaccttaactacacgcc----------------------------
------------ttcgacgtcaacaatgtaacatttatagttgttaataattgtca----
-aagcttccccttgatgcacaaaacctacaaaatatgcacacttatatatctaatcga--
---caatgtctttctttagttatcgataataga----------tgaccactacctgtagg
aagtcaaa-agtttcttgagaaacttggccacatgaaatttgtcttt-------------
---------------gttatactaggtgttgg---------ttaaattaaacgttggata
caaaccgacgataaaaaaacagtcaaaaacacacataaagaaaaaaagatcacttaaaac
cgtcgtatgactacaagtaaacgacagaataagatcacatagatattactcacctctccg
aagaaaagcacccgacca----ctagacataagt-------------tataaaggttctc
aggccttcctagttgttagcaggagaaactcttgccattacacttttaaaaggttgttgt
gttcagagaactaaaacgatcacggaaattaaagtggtcacttcgtgttttc-tctataa
ctcagtcataacgattataaacag-------------------------ttaaaagataa
aaacggtatttaagacgatccaatacacttataaaacattcttcaat-------------
----------attagaatcttaataattacgtttaaaga----------gacgtattttt
caaaaaggatgagcagtagaaatttagatcaattatgcgaggttaaaacatcaacgacga
gaaaacggacgattattcacaatatatcgaaataaacaaaagtattatattcgaaagatt
cgaaaacacgaagagatagaagctgaatccaagggaaacaagaataactttgaccctcca
ccggcgttggttttatacaattacagttatacctaccaagatgcgtaagggat-------
-------------------------------ggagaacactgtcaaatagtagtgaacgt
tggaaatgtacgatgcggagagtgaaaataggtccgagagaaaccagtagtgataggaca
ctcaaatttttatacaacacctatacccgaagaactggtaaacactaacgaatatgttga
aaatttcaaacagaaagaaggacgttgagtacattgtataacaaaagacactgtttccaa
cctcataacctacttcttttttaagatggtgaaccatttctatattggcgataaccacaa
acgtcgagttttctaccctaaaacctctagtttagtacacttctggatgggataaagaac
attccttccaaatgtcttatcaaaagaattatttaactatttcgtactgtgagtcgagaa
caagattttaaacccactagaaaataaaggcttaactaaataaaacaactttaaacactc
acaattaaaaagtgaaaccatccagactatactggttcctagtttacgaccatctcgaac
ggaagttttgtttttaagactacacctcacctcaaaataaaccaagtcaacgtcaaccac
aggaacctatac---------------gacaacactccatttgatcaaagtagagagttt
gtgaacttgaaaaaaacacctatagtacggaagttctagagtgacactgtgagataaaag
aagaaacaggaaaagcgagagtatctgacatcaactgcacttcagatccatccctgtttt
aggaattaacaaagtatatcataaaatactaagacgaatggctcgtactcaatcccaaca
tccttgga-----------------agataactcaccaatggagaatttattagtt----
------cagtaggtgtagacgagggtctaactacctaaggaaagggatgaag--------
------------------------------------------------------tagacg
ttaaatagagcgccgacgtagtttactcagttgaatatttatga----------------
-----------------tactgtacttgaatattg--ggatgacccatcttccgaccaac
caactaaacctaatgtcaacaacagtaaagcacatacgttaataaactac----------
---------gtataatgaaatcccttcaacacgctatgtctgatcacatgaacataagat
aacttaacttccttcatatcaaaat-------agagactacgttaactacaaactcatcc
tggtagtagtgcacggtttttcttattacgtcgatcgatggaaattcgtactttcttagt
actacccacgtataaagtctactcgccttggaact-------------------------
-----------ttaaccgaatgtataagatctgatgtgatagggtcctttggattctgac
ttttttgtcttttttcccctctatacgaacaaactttccttttgtcccactttttcataa
atgacatcaccagcgtaaaagagtaaccataaatatacaaaatccttgaccttagctacc
ttcgacacctctgtggtctccgtccgagtcgttgtttccctacgacgttcgttactgcta
ctacacgtccaatcacgactactccttagacctctacaagggctaccagtcaacacacac
tatacggaatgctcctccttcgcgcgtcgtaaacaaggcacacctgtggaccatacaacg
gtcgcgacacggaacagtcaacttgcactaaatcg-------------------tgggtt
cacaggaaatacatccgtctgttaagtatcaagacattcctatatactaagaactgctcg
tttatcaatgctcaataaaactcatcgact------acgacccttccaccaacacgtaaa
catttcgtacactacttttgatgtaacctgacagagtaccctcctaccagcaactataag
gctcccctaatctatgatcttaaattgtacgtataaaaagcacagacatgtatgtaaaaa
a-----------------------------------cgactgagtaataacatgggaatt
tctgttataag--taatgttacgatccctcagtaaaacgattttttcgaaactcaagatt
cgtgagtcaataaagtagttttgtgtgttattaatgtgtagatataagaatatccatgta
ctggtggaacggatcttagtttaagaattccttaaactattaaaaaaactgaacaacgga
aacgtttacgtgatagacttggacacagtttcgtgtcgattactttc--taagaa--ggt
ccgagatctaaatggccatctgaaaactgagacaaacacgaattttcggaacacgtagag
tacacaacactagatagaaggtattacttgttttactttgtcctagaggaaaggtggtgt
caggttgtgtcggtaggaagagtagttgagagtagagggtcaacaacagtatgaagaagt
tgttacgtgctcgagatagttatcgtagtagaggtttgtagagggtatgctttggttgtg
aggagtaagaaagtgtggtaaagaggaaacagagtaagtagagagggtacaaacagtttc
ggaaacgacgaagaggaaggtagtaggaggaagggagcgagagtgcaggaaacatacgat
gtgaccatctcaggttcttgaaggtg-ttcatgaggtgagcggaactcttagaacaacac
ttcaggggcgttgacaacgtcgacgttaggt---------acaacaagagtgagttttgg
tcaggaaaaccgaggtttgagaaatcagaagagttgttgagacaggacagcagacctaac
aacacaaagttcaatacctcagacttgacacgtgtttattggttctaaagtagaccccta
cataaatagtgaacgcttagttctaagacttcacccattaagaggtcagacaactaaaca
tctaactacaattagcggaaccgtttccgttcatcaacgtgacttttcaacattggtgga
cctggttgatgtttacctgataaagaaacaactagtagaagataacatccacaatatt
>Solyc12g049330.1.1 SL2.31ch12 10F0H1E0IEG 46263202-46267916 20101015/09:21:03GMT
------------------------------------------------------------
------------------------------------------------atgtcaatatac
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
gatcaagcggcagctgccgtgctatcgcaaatagctacggcggcg---------------
-------------------gatggcgcacttattgg------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------cttagccctagcttacgttgccgtac
g-----------------------------------------------------------
---------------------------------------------gagtattgt------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------caagt
tcaaagccaattcttccgc-----------------------------------------
---------------ccttcacaaaatca-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------acgat
gcgccgtcgcttaatgtctccgatctccgttcattactttc-------------------
---------------------------------------ttcttccgacaac--------
------------------------------------------------------------
------------------------------------------------------------
---------------------tctgatagttcaaatcattccgatga-------------
------------------------------------cggtaagcttgtgattgttcgcgg
t-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------actgtggaggcgaaatcggcggttgag---
------------------------------------------ggtaactggaaaagcttg
agagctaatattctctcagctca-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------taattctgctgaaaaa---------------------
------------------------------------------------------------
-------ggcgttatattgcaacatactcaaacatgtatctataatgagtggagaggct-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------tcttttcgtgggctggtgatctgtatt--------------------
------------------------caatatttccaagagtcc------ggaaggatcaac
aatcgtcctcttt----------gagaacggttccctttgttcttattga----------
------------------------------------------------------------
--aactgggaggtggccgcaaccaaaatatgttaat------------------------
------------------------------------------------------------
-------------------------------------------gtcaatatggatggttc
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------tacgcattccctacc
tcttgtga----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------c
agtttatcatcacttgcaac----------------------------------------
----------------ctttacatgctacgcctctca-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------cttttatccaggctctc
tttgg-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------t
catcactatcctgttggagtattggatgaagaaaaaattctaccacttggtaaagatata
accgctattggtg----------------------------tttgcagctcaaaagatgg
gattttggagatca----------------------------------------------
------------------------------------------------------------
---------------------------------------------aatcatgtgaagacc
taccctat----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ttcttgtctgatatgaccaaggatcaaa
tgctggtagagcttgccttcaaaacaaaaattctgatgtggagtgg--------------
-----------------------------agttttatttggttcag--------------
------------------------------------------------------------
-----------------------------------ttgcagttggtgtcct---------
-------tggatatgctgttgtgaggaactggaatcgatggaagctgtggagaca-----
------------------------------------------------------------
-----------------ccagaggcaggct------------------------cagcaa
caaagggatgctgcaagcaatgacgatgatgtgca-------------ggttagtgctga
tgaggaatctggagatgttcccgatggtcagttgtg-tgtgata----------------
--------------tgccttacgaggaggaagcgcgca----------------------
------------------------------------------------------------
----------------------------------------gcatttgttccgtgtggaca
cctggtatgttgccagcg--------------ctgtgtgttataa-------------
