>gnl|BL_ORD_ID|0:46263202-46268916 gnl|BL_ORD_ID|12 SL2.31ch12
ttataacacctacaatagaagatgatcaacaaagaaatagtccatttgtagttggtccag
gtggttacaacttttcagtgcaactacttgcctttgccaaggcgattaacatcaatctac
aaatcaacagactggagaattacccacttcagaatcttgattcgcaagtgataaatacat
ccccagatgaaatcttggttatttgtgcacagttcagactccataacttgaaacacaaca
atccagacgacaggacagagttgttgagaagactaaagagtttggagccaaaaggactgg
ttttgagtgagaacaacatggattgcagctgcaacagttgcggggacttcacaacaagat
tctcaaggcgagtggagtacttgtggaagttcttggactctaccagtgtagcatacaaag
gacgtgagagcgagggaaggaggatgatggaaggagaagcagcaaaggctttgacaaaca
tgggagagatgaatgagacaaaggagaaatggtgtgaaagaatgaggagtgttggtttcg
tatgggagatgtttggagatgatgctattgatagagctcgtgcattgttgaagaagtatg
acaacaactgggagatgagagttgatgagaaggatggctgtgttggactgtggtggaaag
gagatcctgtttcattttgttcattatggaagatagatcacaacacatgagatgcacaag
gcttttaagcacaaacagagtcaaaagtctaccggtaaatctagagcctggaagaatctt
tcattagctgtgctttgacacaggttcagatagtgcatttgcaaaggcaacaagtcaaaa
aaattatcaaattccttaagaatttgattctaggcaaggtggtcatgtacctataagaat
atagatgtgtaattattgtgtgttttgatgaaataactgagtgcttagaactcaaagctt
ttttagcaaaatgactccctagcattgtaatgaatattgtctttaagggtacaataatga
gtcagcaaaaaatgtatgtacagacacgaaaaatatgcatgttaaattctagtatctaat
cccctcggaatatcaacgaccatcctcccatgagacagtccaatgtagttttcatcacat
gctttacaaatgcacaaccaccttcccagcatcagctactcaaaataactcgtaactatt
tgctcgtcaagaatcatatatccttacagaactatgaattgtctgcctacataaaggaca
cttgggtgctaaatcacgttcaactgacaaggcacagcgctggcaacataccaggtgtcc
acacggaacaaatgctgcgcgcttcctcctcgtaaggcatatcacacacaactgaccatc
gggaacatctccagattcctcatcagcactaacctgcacatcatcgtcattgcttgcagc
atccctttgttgctgagcctgcctctggtgtctccacagcttccatcgattccagttcct
aaaacatataaataccaatgagaaaatgcgaccactacagtaaatactttttcaccctgt
tttcctttcaaacaagcatatctccccttttttctgttttttcagtcttaggtttcctgg
gatagtgtagtctagaatatgtaagccaatttcaaggttccgctcatctgaaatatgcac
ccatcatgattctttcatgcttaaaggtagctagctgcattattctttttggcacgtgat
gatggtcctactcaaacatcaattgcatcagagataaaactatacttccttcaattcaat
agaatacaagtacactagtctgtatcgcacaacttccctaaagtaatatgcatcaaataa
ttgcatacacgaaatgacaacaactgtaatccaaatcaaccaaccagccttctacccagt
agggttataagttcatgtcatagtatttataagttgactcatttgatgcagccgcgagat
aaattgcagatgaagtagggaaaggaatccatcaatctgggagcagatgtggatgacttg
attatttaagaggtaaccactcaatagaaggttcctacaaccctaactcatgctcggtaa
gcagaatcataaaatactatatgaaacaattaaggattttgtccctacctagacttcacg
tcaactacagtctatgagagcgaaaaggacaaagaagaaaatagagtgtcacagtgagat
cttgaaggcatgatatccacaaaaaaagttcaagtgtttgagagatgaaactagtttacc
tcacaacagcatatccaaggacaccaactgcaactgaaccaaataaaactccactccaca
tcagaatttttgttttgaaggcaagctctaccagcatttgatccttggtcatatcagacc
taccaaagtgaaaaattaacactcacaaatttcaacaaaataaatcaattcggaaataaa
agatcacccaaattttagaacaagagctgagtgtcatgctttatcaatttattaagaaaa
ctattctgtaaaccttccttacaagaaatagggtaggtcttcacatgatttgatctccaa
aatcccatcttttgagctgcaaacaccaatagcggttatatctttaccaagtggtagaat
tttttcttcatccaatactccaacctttgtcacagaaaacaatatgttacatgagttgca
ggaagaaagacaaactttaaaagttgtataagcaatcacaaatggtcaagaagcccatat
ccacaacatatttttaaactcacaggatagtgatgaccaaagagagcctggataaaagtg
agaggcgtagcatgtaaaggttgcaagtgatgataaactgtcacaagaggtagggaatgc
gtagaaccatccatattgacattaacatattttggttgcggccacctcccagtttcaata
agaacaaagggaacctaagtcgaagatagagaagcacaaaagcttagaaagcttatatta
tgaaaacaaataaagctatataacacttattagcaggcaaaagagcagcaactacaaaat
tggagcgtattaactagatttaaagatgacgagtaggaaaaactttttatgcagagaaat
ttgcattaataattctaagattataacttcttacaaaatattcacataacctagcagaat
ttatggcaaaaatagaaaattgacaaatattagcaatactgactcaatatctcttttgtg
cttcactggtgaaattaaaggcactagcaaaatcaagagacttgtgttgttggaaaattt
tcacattaccgttctcaaagaggacgattgttgatccttccggactcttggaaatattga
atacagatcaccagcccacgaaaagaagcctctccactcattatagatacactagaataa
gacagcaaatgaacatcagtatgctgccaaaattcactagaaaaaaagaaatacacacaa
aaactgacaaaaaaatagcagccaaacataggttgcaaattaaattggttgtggatcata
ttgtttctgtttaaagtacaccggttcaaagagttctttgaaaactgaaggatgtccatc
accagtagataatagctattgatttctttctgtaacagctaatctatatattcacacgta
taaaacatccaaaacacgtagttccccttcgaaactgttaataattgttgatatttacaa
tgtaacaactgcagcttccgcacatcaattccaaacaa-----ctttggataagctatat
gaatcctcacaatccatttagctctaatataacacaatttcattacaaaaatagtttgta
ttttaagacacactctcagcctctgcgaccaaagggtcatgaggcgaagcgggaattcat
ccctagacatccctccctgtgcaccagcttattatctcatgtcctctctctatgtctagg
gattccttcaacgcgggctaagcaaaacatcgattgttctttttttcgattgtgcattaa
catttaacaaaaatgtaggataaattatcacaagtacaagatcaaaccctgcagtttaac
caaagtttgcaacccacattgtaattcaaaacgatcaccgcatcatatcacatgcctaaa
aaagccctaacacatcaattatagtgaatattcacaaatttagattgatcataactaact
ctaacagtaccactaatcctaaatgtcgttgaatacgaaatttccagctcgaataaggat
attaattgcctaataaagcatgataaattgactaatttaatactgtttgaacataaatta
aagtaaaacgaaaagtgtagaagaattatactgtttgagtatgttgcaatataacgcctt
tttcagcagaattatgagctgagagaatattagctctcaagcttttccagttaccctcaa
ccgccgatttcgcctccacagtaccgcgaacaatcacaagcttaccgtcatcggaatgat
ttgaactatcagagttgtcggaagaagaaagtaatgaacggagatcggagacattaagcg
acggcgcatcgttgattttgtgaagggcggaagaattggctttgaacttgacaatactcc
gtacggcaacgtaagctagggctaagccaataagtgcgccatccgccgccgtagctattt
gcgatagcacggcagctgccgcttgatcgtatattgacatggctactttcaaattctcgg
tcgccggaaactgaacgctatttctatggcttgtttattggctatgagtacctctttttt
taagactactttcggtttactaaagtgtttattataaatagattggattaaaatggattg
tatttaagtttatcataaacttattcgataggtattgtcaagataactttttgatagaaa
tgtatttatttatgttatattaaatatggtgatcttttgattgatttttctacctataaa
tagagatatcattcactattaaaatatacacttgaataatatacacttgaataagaagaa
attttttttcttctatctatttctcttgtcttttttttctttatgattatattcttatga
gcttgattttataatacgttatcagcacgagtctctagccaattaagattgagttttagt
ttttctttaactcatgttttggttgatctcgttatgaaaaatcaaggtattatatgcata
aaatcaggtatgtattttctaaaatatttttatgatttagaataaaatagtattgagtca
ctaacaattatcaggaatc-gaagacatatactactattgattgaatatgacatgctata
caaaatttcttaaatagaaaaaggtataaatatcatgagtttgaatattattttgattgt
tttgaaagactcagggtgagttatgttgtactttggtctattataccattagtttagggt
aagacgatgggttcaagtctcatcgcaccaaaaagggtaagacatcaaattaagtccaga
tgcacataatgaaaaatattgacggataagacaatagattcaaattctatcgccccaaga
gggtaagacatcaatttgaattttgatgcaccgtgataataatgtattgggttcaagtcc
catagaattatgacctaatgtgcctttgtatgcataagacattgagtttgagtctcaatg
caccatagtggtgataaaatg
>R_gnl|BL_ORD_ID|0:46263202-46268916
gtaaaatagtggtgataccacgtaactctgagtttgagttacagaatacgtatgtttccg
tgtaatccagtattaagataccctgaacttgggttatgtaataatagtgccacgtagttt
taagtttaactacagaatgggagaaccccgctatcttaaacttagataacagaataggca
gttataaaaagtaatacacgtagacctgaattaaactacagaatgggaaaaaccacgcta
ctctgaacttgggtagcagaatgggatttgattaccatattatctggtttcatgttgtat
tgagtgggactcagaaagttttgttagttttattataagtttgagtactataaatatgga
aaaagataaattctttaaaacatatcgtacagtataagttagttatcatcatatacagaa
g-ctaaggactattaacaatcactgagttatgataaaataagatttagtatttttataaa
atcttttatgtatggactaaaatacgtatattatggaactaaaaagtattgctctagttg
gttttgtactcaatttctttttgattttgagttagaattaaccgatctctgagcacgact
attgcataatattttagttcgagtattcttatattagtatttcttttttttctgttctct
ttatctatcttcttttttttaaagaagaataagttcacatataataagttcacatataaa
attatcacttactatagagataaatatccatctttttagttagttttctagtggtataaa
ttatattgtatttatttatgtaaagatagtttttcaatagaactgttatggatagcttat
tcaaatactatttgaatttatgttaggtaaaattaggttagataaatattatttgtgaaa
tcatttggctttcatcagaatttttttctccatgagtatcggttatttgttcggtatctt
tatcgcaagtcaaaggccgctggctcttaaactttcatcggtacagttatatgctagttc
gccgtcgacggcacgatagcgtttatcgatgccgccgcctaccgcgtgaataaccgaatc
gggatcgaatgcaacggcatgcctcataacagttcaagtttcggttaagaaggcgggaag
tgttttagttgctacgcggcagcgaattacagaggctagaggcaagtaatgaaagaagaa
ggctgttgagactatcaagtttagtaaggctactgccattcgaacactaacaagcgccat
gacacctccgctttagccgccaactcccattgaccttttcgaactctcgattataagaga
gtcgagtattaagacgactttttccgcaatataacgttgtatgagtttgtcatattaaga
agatgtgaaaagcaaaatgaaattaaatacaagtttgtcataatttaatcagttaaatag
tacgaaataatccgttaattataggaataagctcgacctttaaagcataagttgctgtaa
atcctaatcaccatgacaatctcaatcaatactagttagatttaaacacttataagtgat
attaactacacaatcccgaaaaaatccgtacactatactacgccactagcaaaacttaat
gttacacccaacgtttgaaaccaatttgacgtcccaaactagaacatgaacactattaaa
taggatgtaaaaacaatttacaattacgtgttagctttttttcttgttagctacaaaacg
aatcgggcgcaacttccttagggatctgtatctctctcctgtactctattattcgaccac
gtgtccctccctacagatccctacttaagggcgaagcggagtactgggaaaccagcgtct
ccgactctcacacagaattttatgtttgataaaaacattactttaacacaatataatctc
gatttacctaacactcctaagtatatcgaataggtttc-----aacaaaccttaactaca
cgccttcgacgtcaacaatgtaacatttatagttgttaataattgtcaaagcttcccctt
gatgcacaaaacctacaaaatatgcacacttatatatctaatcgacaatgtctttcttta
gttatcgataatagatgaccactacctgtaggaagtcaaaagtttcttgagaaacttggc
cacatgaaatttgtctttgttatactaggtgttggttaaattaaacgttggatacaaacc
gacgataaaaaaacagtcaaaaacacacataaagaaaaaaagatcacttaaaaccgtcgt
atgactacaagtaaacgacagaataagatcacatagatattactcacctctccgaagaaa
agcacccgaccactagacataagttataaaggttctcaggccttcctagttgttagcagg
agaaactcttgccattacacttttaaaaggttgttgtgttcagagaactaaaacgatcac
ggaaattaaagtggtcacttcgtgttttctctataactcagtcataacgattataaacag
ttaaaagataaaaacggtatttaagacgatccaatacacttataaaacattcttcaatat
tagaatcttaataattacgtttaaagagacgtatttttcaaaaaggatgagcagtagaaa
tttagatcaattatgcgaggttaaaacatcaacgacgagaaaacggacgattattcacaa
tatatcgaaataaacaaaagtattatattcgaaagattcgaaaacacgaagagatagaag
ctgaatccaagggaaacaagaataactttgaccctccaccggcgttggttttatacaatt
acagttatacctaccaagatgcgtaagggatggagaacactgtcaaatagtagtgaacgt
tggaaatgtacgatgcggagagtgaaaataggtccgagagaaaccagtagtgataggaca
ctcaaatttttatacaacacctatacccgaagaactggtaaacactaacgaatatgttga
aaatttcaaacagaaagaaggacgttgagtacattgtataacaaaagacactgtttccaa
cctcataacctacttcttttttaagatggtgaaccatttctatattggcgataaccacaa
acgtcgagttttctaccctaaaacctctagtttagtacacttctggatgggataaagaac
attccttccaaatgtcttatcaaaagaattatttaactatttcgtactgtgagtcgagaa
caagattttaaacccactagaaaataaaggcttaactaaataaaacaactttaaacactc
acaattaaaaagtgaaaccatccagactatactggttcctagtttacgaccatctcgaac
ggaagttttgtttttaagactacacctcacctcaaaataaaccaagtcaacgtcaaccac
aggaacctatacgacaacactccatttgatcaaagtagagagtttgtgaacttgaaaaaa
acacctatagtacggaagttctagagtgacactgtgagataaaagaagaaacaggaaaag
cgagagtatctgacatcaactgcacttcagatccatccctgttttaggaattaacaaagt
atatcataaaatactaagacgaatggctcgtactcaatcccaacatccttggaagataac
tcaccaatggagaatttattagttcagtaggtgtagacgagggtctaactacctaaggaa
agggatgaagtagacgttaaatagagcgccgacgtagtttactcagttgaatatttatga
tactgtacttgaatattgggatgacccatcttccgaccaaccaactaaacctaatgtcaa
caacagtaaagcacatacgttaataaactacgtataatgaaatcccttcaacacgctatg
tctgatcacatgaacataagataacttaacttccttcatatcaaaatagagactacgtta
actacaaactcatcctggtagtagtgcacggtttttcttattacgtcgatcgatggaaat
tcgtactttcttagtactacccacgtataaagtctactcgccttggaactttaaccgaat
gtataagatctgatgtgatagggtcctttggattctgacttttttgtcttttttcccctc
tatacgaacaaactttccttttgtcccactttttcataaatgacatcaccagcgtaaaag
agtaaccataaatatacaaaatccttgaccttagctaccttcgacacctctgtggtctcc
gtccgagtcgttgtttccctacgacgttcgttactgctactacacgtccaatcacgacta
ctccttagacctctacaagggctaccagtcaacacacactatacggaatgctcctccttc
gcgcgtcgtaaacaaggcacacctgtggaccatacaacggtcgcgacacggaacagtcaa
cttgcactaaatcgtgggttcacaggaaatacatccgtctgttaagtatcaagacattcc
tatatactaagaactgctcgtttatcaatgctcaataaaactcatcgactacgacccttc
caccaacacgtaaacatttcgtacactacttttgatgtaacctgacagagtaccctccta
ccagcaactataaggctcccctaatctatgatcttaaattgtacgtataaaaagcacaga
catgtatgtaaaaaacgactgagtaataacatgggaatttctgttataagtaatgttacg
atccctcagtaaaacgattttttcgaaactcaagattcgtgagtcaataaagtagttttg
tgtgttattaatgtgtagatataagaatatccatgtactggtggaacggatcttagttta
agaattccttaaactattaaaaaaactgaacaacggaaacgtttacgtgatagacttgga
cacagtttcgtgtcgattactttctaagaaggtccgagatctaaatggccatctgaaaac
tgagacaaacacgaattttcggaacacgtagagtacacaacactagatagaaggtattac
ttgttttactttgtcctagaggaaaggtggtgtcaggttgtgtcggtaggaagagtagtt
gagagtagagggtcaacaacagtatgaagaagttgttacgtgctcgagatagttatcgta
gtagaggtttgtagagggtatgctttggttgtgaggagtaagaaagtgtggtaaagagga
aacagagtaagtagagagggtacaaacagtttcggaaacgacgaagaggaaggtagtagg
aggaagggagcgagagtgcaggaaacatacgatgtgaccatctcaggttcttgaaggtgt
tcatgaggtgagcggaactcttagaacaacacttcaggggcgttgacaacgtcgacgtta
ggtacaacaagagtgagttttggtcaggaaaaccgaggtttgagaaatcagaagagttgt
tgagacaggacagcagacctaacaacacaaagttcaatacctcagacttgacacgtgttt
attggttctaaagtagacccctacataaatagtgaacgcttagttctaagacttcaccca
ttaagaggtcagacaactaaacatctaactacaattagcggaaccgtttccgttcatcaa
cgtgacttttcaacattggtggacctggttgatgtttacctgataaagaaacaactagta
gaagataacatccacaatatt
>Solyc12g049330.1.1 SL2.31ch12 10F0H1E0IEG 46263202-46267916 20101015/09:21:03GMT
------------------------------------------------------------
------------------------------------------------atgtcaatatac
gatcaa------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------gcggcagctgccgtgctatcgcaa------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------atagctacggcgg--------------
------------------------------------------------------------
------------------------------------------------cggatggcgcac
ttattggcttagccctagcttacgtt----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------gccgtacggagtattgt--------------------
-------------------------------------caagttcaaagccaattcttccg
cccttcacaaaatcaacga-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------tgcgccgtcgcttaatgtctccg------------------------
------------------------------------------------------------
-------------------atctccgttcattactttcttctt-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------ccgacaactctgatagttcaaatcattccgatga---------cggt
aagcttgtga--------------------------------------------------
------------------------------------------------------------
-----------------------------------------------ttgttcgcggta-
------------------------------------------------------------
-----------ctgtggaggcgaaatcggcgg----------------------------
-ttgagggt----------------aactggaaaagcttgagagctaatattctctcagc
tcataa------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ttctgctgaaaaaggcgttatattgca---------
------------------------------------------------------------
-------acatactcaaac-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------atgtatctataatgagtggagaggcttcttttcgtgg------
------------------------------------------------------------
----------------------------gctggtgatctgtattcaatatttcc------
-----------------aagagtccggaaggatcaaca----------------------
-------atcgtcctctttgagaacggt--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------tccct
ttgttcttatt-----------------------------gaaactgggaggtggccgca
accaaaatatgttaat---------------------gtcaatatggatggttctacgca
t-----------------tccctacctcttgtgacagtttatcatcact-----------
tgcaacctttacatgctacgcctctcacttttatccaggctctctttgg-----------
---tcatcactatcctgtt-----------------------------------------
---------------------------------ggagtattggatgaagaaaaaattc--
------------------------------------------------------------
---------------------------------------------------------tac
cacttggtaaagatata-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------accgctatt-------------------ggtgtttgcagctcaaaagatggg
at-------------------------------------------tttggagatcaaatc
atgt---------------gaagacctaccctattt------------------------
-----------------------------------------cttgtctgat---------
------------------------------------------------------------
---------------------------------atgaccaaggatcaaatgc--------
---------------------------tggtagagcttgccttcaaaacaaaaattct--
-------gatgtggagtggagtt-------------------------------ttattt
ggttcag--------------------------ttgcagttggtgtccttggatatgctg
ttgtgaggaactgg----------------------------------------------
------------------------------------------------------------
----------------------aatcgatggaagctgtggagacacc-------------
------------------------------------------------------------
-agaggcaggctcagcaacaaagggat---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------gctgcaagcaatgacgatgatgtgcaggt-
------------------------------------------------------------
-tagtgctgatgaggaatctggagatgttcccgatggtcagttgtgtgtgatatgcctta
c-----------------------------------------------------------
------------------------------------------------------------
------------------------------gaggaggaagcgcgcagcatttgttccgtg
tggaca------------------------------------------------------
------------------------------------------------------------
-----------------------cctggtatgttgccagcgctgtgt-------------
----------gttataa----
