>Aquilegia_coerulea_gnl|BL_ORD_ID|4964 _014_00808.1|PACid:22027970

MSSTLNER---IISLIAQLALATDGAGAGVFLAYFTVQIWRNYRYTSSALERIHQAKSIT
ISDLRSLLIDDNNSSQT---QSSSEKQLVIIRGLVEAKSVVDGNWKNLIPSSSSSNSSSI
SSSIGKSGGLL-LSNQSGA-KGVVLQNTQTYV-YNDYKGLLGYAVDLRTLLGKPSKGPNA
LSIRTIPFVLVQ-NGDSQSLDSKDYVVVNLEG-SMHP-LPLTTCYHHLQPIPTT-----P
YTL---IQAIVGHAYP-V------------------GLLDEEKILPLGKEITAVGHCTL-
QDGNPQIISCKKVPYFLSDMTKDQMIVDLVSKKKILFWAGIVLGSVSLGVLGYA-L--TR
N-------WQRLKEWRQRRQIQQSREEEIANLDATPEDTRADEETED---IPEGQLCVIC
LMRRKRAAFVPCGHFVCCYRCALSVERDSAPKCPLCRQDIRTSVRIYDS
>Aquilegia_coerulea_gnl|BL_ORD_ID|6437 _041_00112.1|PACid:22029447

M--DRGTM---VSSLLSQFALAIGGGVSGFTLGYTTLRTWIELKSTSFALYKITQAKTVP
IYDLRSLIASSLDDSE------SSNKTLVVIRGVVEAKA---RNWGSFTP----------
--------NVL-VSPSSGE-KGVILQETQ-------------------------------
--------VLLV-SSQQQYYDP---VIVDLDS-STHL-LPLTTVYHKLQDLHVMSDEILP
YAF---LEAFF---LP-V------------------GHM-QKKILPLGKEINAIGLCSL-
QDGNLHIKATQELPYFLSEMTKGEMVKHLAYKTTILFWGGCIIGIVSLGVLGYT-S--FR
I-------WEWWKVRRQHFSNAEVDDVYIGN-----------------DEIPSEQLCTIC
TMRRKKYACVPCGHLVCCHKCARSIQHDSTARCPECRHIM--WFRLDVS
>Aquilegia_coerulea_gnl|BL_ORD_ID|6222 _041_00086.1|PACid:22029231

M--STYDR---TNTVLWELGTVTSGVVTSLALAYGSVKRFIEYHSTRRSFNKVLAAKIVP
ITDLRSLILSSANEAE------SNDEKLIVVRGLVR----------NLSS----------
--------NVL-VDHASGK-RGVVLQETHTCIEYKNLDDLLGWDRFNPFKLLKPWKYLRY
TLLRTVPFQLEG-FSPGSYSDS---VVVNLSG-STHS-LPLKPVFDLCRVLPK-------
------NRLTLSILYP-V------------------GLL-EVKLLPLGKEITAIGFCSL-
QDGNLQIKACENIPYFLTELTKYHMVENLGHMGCSFFIQGVTFGSLALFVLFLTFATFVR
NRPCC---WQRWKDWRQRWRKSDD-----------------DNSNEK---IVHG------
-------------------------------------------------
>Aquilegia_coerulea_gnl|BL_ORD_ID|3755 _038_00101.1|PACid:22026760

M--STYDS---I-TLDLDDGLIT----SAIALGFLAVLKFWDFHSYSSALSKLRDARTVS
VSGLRHLLSCS-----------TEKNHLVVVHGFVQAEP---KRCFSLQP----------
--------NILESSTASGKTQGVVLLKTQARSVYHAWK-------GPSMGCTSYLGGVST
SITKVPSFLLAGRKGSDSSSDC---VTVNLSA-LNHDHLPLTTIFDQLSSPNAT-----C
FTLPLPVKSLLGHAYP-FGLCLQEKFLPLNFAWYHPGLL-EEKILPLGKEISVVGIGTS-
EYGNVEIKPCDELPYFLSDLTKDQMIGELAQKTNYLLLSAIFFGSLSLAVIAYA-V--MI
G-------CQRFEEKTQQRRQVQQ---QMTQVQQSLRNDVVEEGMEA---LPEGLSCVVC
ITRGRRAVFEPCSFLA-------------------------------DI
>Aquilegia_coerulea_gnl|BL_ORD_ID|33211 _026_00020.1|PACid:22056322

MSTDNNNNDMGVLDAVIDISLAT----LALTLGWKFVRNSISYNQTNTYLSKIRGSKKLS
ISDLRSFASESD----------INNNTLVVVRGMIKPLS-------SNSP----------
---------LI-LSEHCGR-EGVLLRTIKTFK----------LDIFNSLSTVLPSLNRTV
GTIQKIPLVLVE--NDKSNSPS---VVINMEGLGSHN-VDLTEVCNYVQPTFT-------
--------KFLGIKFSGV------------------TQV-EEEMLLLGKRITAFGNVSVS
EDGILEIKACKDFIYFLADITKLDAEMDLFFERLIFMWWKTFHVTFFLGLLVLI-VLLRR
NRSHSKPWFQRFYSWLRHRKQQGT------------------------------------
------------------------------------------------D
>Arabidopsis_lyrata_gnl|BL_ORD_ID|6881 _474546|PACid:16040628

MSSPERALLNLLTDIALSFDGAILGLTLAISAVGSALKYASTNAALNKIKEAPEVS-VAD
LRSLLPVSEDKSETNDHGK-----IVVVRGVVKPKYSGDESHKNNNVLISPETGDKALII
QRTQTYVYSGWKRLFQSTGHRFMLERSMRKHGADFMRTVPFVIVGKDQQSQSTFLDVNMD
GSRQPLPLTTVYNRLQPINSSFLQA----FLFPDYPVGLLDIEKILPPGKDITAVG-ICS
FNNGVPEIKSCQDLPYFLSEMTKDKMIEELMDQTSFIFFGS---VILGIVSVGI-LSYAA
VRTWNKW-KQWNHQRDLPQRPNEPV-------VD------DEPE-------------DAD
EIPDGELCVICVTRRRVPAFIPCGHVVCCRVCASTVERELNPKCPVCLQSIRGSMRVYYS
--
>Arabidopsis_lyrata_gnl|BL_ORD_ID|28364 _329238|PACid:16062111

MR-----------------------VTCIL------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------QDEFV----RWYLELSFSARVVIYITVLGTIMTITYLV
LKFLSECDMEDDTERLLPLMAEEEVHTVWTPLIN------ESSEVTGKGDVETASFSSSD
DVDYSTLCVICFEERRNCFFVPCGHSATCRGCAQKILSEENKVCPICRRVIRKSKRLVLK
KL
>Arabidopsis_lyrata_gnl|BL_ORD_ID|19937 _474968|PACid:16053684

MIP-------------------WGGVTCCLSAAALYLLGRSSGRDAEVLKTVTRVNQLKE
LAQLLELDSKILPF----------IVAVSGRVGSETPIKCEHSGIRGVIVEETAEQ-HFL
KHNETGSWVQDSALMLS-----------------MSKEVPWFL-----DDGTSRVHVMGA
RGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVK
DDIGEFRIQKPDRGPFYVSPKSLDQLISNLGKWSRWYKYAS---MGFTVFGVFL-ITKHV
I--------DSVLERRRRRQLQKRV-------LDAAAKRAELESEGSNGARESIADSTKK
EDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLT-----SCPLCRRRIDLAVKTYRH
--
>Arabidopsis_lyrata_gnl|BL_ORD_ID|12068 _338432|PACid:16045815

MIH-------------------LAGFTCCLGGIALYLLSRNTGG---VVKSITRVNHLKD
LEQLVE--SKVFPL----------IIAVSGIVGSETPIKCEHSDILGVFLKKTAEQ-QVL
SRNWRFSWVRKSTLMQP-----------------MTKEVPWFL-----DDGTGRVNVAVS
QGEIGLALTVGSDVFEKAEPVSLVQGTLDYLKGLKILGVRRVEHVVPIGTPLTIVGEAVK
DGMGNVRIQKPEQGPFYVSYVPLDQLISKLGEWSRRFKYAS---MGLTVVGVIL-LSKPV
IKYILKK-IEDTLERRRRQLLQKRV-------VD--------------------------
---VPDLCVICHDQKYNTAFVQCGHMCCCLTCSLRLT-----TCPLCREQIQQVLKIYRH
--
>Arabidopsis_lyrata_gnl|BL_ORD_ID|936 _867782|PACid:16034683

MIH-------------------LGGLTCCVSGGVLYLLSMIPGSFFEMLNSVTRVHQIKD
LENLLQVEGK--------------IIAVSG----------------------TAQQ-LFL
KRNWLFSWVEDSKWMLP-----------------QAKEVPWYL-----------------
-----------------------------------MLGVRRTEHVLPIGTPVTVVGEAVK
DGIRGFRIQKPEKGLFFVSPVPLDKIISPMGKWLRRFKYVY---VGLTVVGVIL-ISKPV
I--------EYILERRRGRLLRKRV-------ADAAAKRAKLVARGLETQHENSLDSTSR
DRDVLDLCVICLEQKYDATFVKCGHMCCCLTCSLHVK-----TCPICRRPIEHVLKIDRR
--
>gnl|BL_ORD_ID|17011 Arabidopsis_thaliana AT1G54150.1|PACid:19654958
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGDKALIIQ
RTQTYVYSGWKRLFQSTGHRFMLERSLR-------KHGADFTRTVPFVIVGKDQQSNSSF
VAVNMDGSRQPLPLTT---VYNRLQPIN-----SSFLQAFLYPDYPVGLLDIEKILPPGK
DITAVGIYSFNN-GVPEIKSCQDLPY-FLSEMTKDKMIEDLMEQTNFIFLGS----VILG
IVSVG---ILSYAAVRTWNKWKQWNHQRELPQRP--NDSVVDD-----------------
-----EPEDADEIPDGELCVICVSRRRVPAFIPCGHVVCCRRCASTVERELNPKCPVCLQ
SIRGSMRVYYS--
>gnl|BL_ORD_ID|9028 Arabidopsis_thaliana AT4G24204.3|PACid:19646975
M-----------------------------------------------------------
------------------------------------------------------------
-------------FDAT-------------------------------------------
------------------------------------------------------------
-----------------ISKCLQLLYMFFRKLNSIKLPSDNDEFVRWYLGLSFSARVVIY
ITVLGTIMTITYLVLKFLSECDMEDDTQRLPLVA--EEEVTTDWTPPLINESLEVTG-KG
DVETASFSSSDDVDYSTLCVICFEERRNCFFVPCGHSATCRGCAQRILSEESKVCPICRR
VIRKSKRLVLKKL
>gnl|BL_ORD_ID|19755 Arabidopsis_thaliana AT1G59560.1|PACid:19657702
MIH-------------------LAGFTCCLGGVALYLLTRSTGRD---IKSI--TRVYQL
KDL------------------EQLVEVESKVVPLI----------IAVSGDVGSET-PIK
CEHSYVLG---VFLKRTAEQQVLRRNWRFSWVRNSTLMQPMTKEVPWYL-----DDGTGR
VNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGYLKGFKI----LGVRHVERVVPIGT
PLTVVGEAVRDGMGNVRIQKPEQGPF-YVTYIPLDQLISKLGDLSRRFKYAS------MG
LTVLGVILISKPVIEYILKRIEDTLERRRRQFA---LKRVVDA---AARRAKPVTGG---
-------GTSRDGDTPDLCVVCLDQKYNTAFVECGHMCCCTPCSLQLR-----TCPLCRE
RIQQVLKIYRH--
>gnl|BL_ORD_ID|17261 Arabidopsis_thaliana AT1G63900.1|PACid:19655208
MIP-------------------WGGVTCCLSAAALYLLGRSSGRDAEVLETV--TRVNQL
KEL------------------AQLLELDSKILPFI----------VAVSGRVGSET-PIK
CEHSGIRG---VIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFL-----DDGTSR
VHVMGARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLKM----LGVKRIERVLPTGI
PLTIVGEAVKDDIGEFRIQKPDRGPF-YVSSKSLDQLISNLGKWSRLYKYAS------MG
FTVLGVFLITKHVIDSVLER------RRRRQLQK----RVLDA---AAKRAELESEGSNG
TRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLT-----SCPLCRR
RIDLAVKTYRH--
>gnl|BL_ORD_ID|17260 Arabidopsis_thaliana AT1G63900.2|PACid:19655207
MIP-------------------WGGVTCCLSAAALYLLGRSSGRDAEVLETV--TRVNQL
KEL------------------AQLLELDSKILPFI----------VAVSGRVGSET-PIK
CEHSGIRG---VIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFL-----DDGTSR
VHVMGARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLKM----LGVKRIERVLPTGI
PLTIVGEAVKDDIGEFRIQKPDRGPF-YVSSKSLDQLISNLGKWSRLYKYAS------MG
FTVLGVFLITKHVIDSVLER------RRRRQLQKSCFCRVLDA---AAKRAELESEGSNG
TRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLT-----SCPLCRR
RIDLAVKTYRH--
>Brachypodium_distachyon_gnl|BL_ORD_ID|13589 _1g72800.1|PACid:21816359

MSARDRETVEALARVAAALDGAVLGLGTAALAVVSLAKYLAASGALRRIAEAPEVAIPDL
RYSLLAGLGEGES---------RLAVVRGLVRSPPWG-------KFLIPPGSREHC----
-----------------------------------VVAKHTQTCLFGEWRGIFGWTFDLH
ALFFKSLKEQTITSFRWVPFALVDPASASDKSTEMIHVKLDGAVQQSLPLTTVYHKLIPV
EQNSYTLFQTIVGNGYPIALL-----DEEKILPIGKEITAIGLCRVNN-QNVEITSCP-E
IPFFL---------SDLTKGEIEAELDSRARTLFWVTFALGTMSVGLLGHAIYRFWEKVK
QHREARQAQQRFHQAD-----DEDDTGENGSDDDFPG--EMGDGQLCVICLRKRRKAAFV
PCGHLVCCCNCAKRVELMNEPLCPVCRQDIQYMLRVY---------DS
>Brachypodium_distachyon_gnl|BL_ORD_ID|17609 _1g19510.1|PACid:21820379

MMVP---------------------WGGVGCCLSAAALYLLGRSSGRDAEVLRSVTRTGS
LKDLAAILDTASK------VLPLVVAVSGRV----------SSDTPLICQQSGMRG----
-----------------------------------VIVEEMAEQHFLKHNDAGSWIQDSA
VMLSVS---------KEVPWYL------DDGTGRVYVVGARAAAGLVL---TIASEVF--
EESGRTLVRGTLDYLQGLKML--GVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQRPH-K
GPFYA---------SPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLL---AKRALQHFL
QKKRQHELNKRVRAAAAQRQAREAEGADGTSNGDPNSKKDQLVLEICVICLEQEYNAVFV
PCGHMCCCMNCSSHVT-----NCPLCRRRIDQAVRTF---------RH
>Brachypodium_distachyon_gnl|BL_ORD_ID|3019 _2g26290.1|PACid:21805789

M-----------------------------------------------------------
-----GGSSSSRRRRDDYYPAPPLHHYSNYPPPPPPPHHHHHPPPPPPPHHHHHHGPPPP
PPPHHGPSPSAAAYYYHHHHPPPPHAYHGPWHPAPQPPQPQRPALIGPPPEFVGHQQALK
VKNDINLRK---DTIRLVP-------DANDPDRRLVSFTFDAVTDGSL---TIYYFAK--
EGKDCSFSSVYPDLQAPTKIPFQKGLDQKYVQPSGSGI---DLGFFSL-DELSDTTGE-V
FPLVVYAE---ACPSQEEGDDPVKSTRAQITLAV---------------------IEKHN
NDLQVKVVKQILWIAGVRYELKEIFGIVNSTEADVPDADDDGMGKECVICLTEPRDTAVF
PCRHLCMCSECAQALRLQSN-KCPICRQPVEKLIEIKVRSS-----EP
>Brachypodium_distachyon_gnl|BL_ORD_ID|5932 _2g13150.1|PACid:21808702

M-----------------------------------------------------------
-----GNTGSTGS-----------------------------SNPPRPPFDGRGHGLPPP
--------------YYHRYPPWPPSAAAPP--PVPVPAQVER-------------HRAVA
VHAGVNVKG---DTLRLVP--------DDDGRCLLLAFSFDADAPGSI---TVYFFAQ--
EDDDHVLKATKENVLQPVKITFKEGQGQEFKQPSGTGI---NVSMFEE-SELTKVGEDGV
FPVAFKVEVGISSNQESEREQDAEDSKSLVKFAVF--------------------VKKEK
AEYGVRVVQQIMWVNGTRYVLQEIYGIRNTTDKNVP---EDDFGKECVVCLSEPRDTTVL
PCRHMCLCRECAQLLRFQTN-KCPICRQPVERLLEIEVDSNMLHQGDQ
>Brachypodium_distachyon_gnl|BL_ORD_ID|11771 _4g34480.1|PACid:21814541

M-----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------ERRNGGGVTLAQQ
LAASSNLR----DLLKLRE-------DDDDDGTRL------AAAGRRR---TLLDVIR--
--------SGAEDERAPTA-------------PSSSSR-----------RRASPAAAPPT
PP------------APGEGER-------RVSLMAL--------------------LEQAE
QQWTAATAGGGAWTRVEEVAASE---------EGRKGGGASSVGGRCCVCMARGKSAAFI
PCGHTF-CRACARELR-AGRGRCPLCNAAIREVLNLF-----------
>Brassica_rapa_gnl|BL_ORD_ID|14784 _037967|PACid:22698294

MSSPDRSAVFPLLIDIALSFDGAILGVTLALGAVRAAFKYASTS---------AALNKIK
DAPEVSVSDLRSLIPASDDQSET----SGEQERIVVVRGTVKAKVTGGEGSNKQNNNVLI
SQETGDKALIIHRS--QTYVYSGWKTLFQLTNGHRFLLERSLPKQGADFMRMVPFVIVDN
TQPSQSSFVVVNMDGARQP--LPLTTVYNRLQPINSSP-----YAFLQALFFPEYPVGLI
DVEKILPPGRDLTAVGICSFNNGVPE--IKSCQDLPYFLSEMTKDKMILDLAETTS----
----------VIFWGGIIMGC--LSAGILGFAAARAWNRWKQRHHEREQQQR--------
------PDEQ------RPEQPMVADET-EDEDEIPDGALCVICVTRRRVPAFIPCGHVVC
CRQCASTVEREVNPKCPVCLQSIRGSMRVYYS-
>Brassica_rapa_gnl|BL_ORD_ID|38557 _030900|PACid:22722067

MSSPDR-AVLSLLTDIFLSFDGAILGVTLAFGAVRAASKYASTS---------AALNKIK
DSPEVSVCDLRSLIPPSD--GES----SHANQRIVVVRGTVEPKVT-GDGSHK-NNNVLI
SQETGEKALIIHRT--QTYMYSGWKTLFHLSSGHRFLLERSLPKQGAGFMRMVPFVIVDK
NQWSQSSFLVVNMDGARQP--LPLTTVYNRLQPINSSP-----YSFLQALFFPEFPVGML
DVEKILPPGRDLTAVGICSLNNGVPE--IKSCQDLPYFLSDMTKDKMIMDLTETTS----
----------VLFWGGVILGC--LSVGILGFAAVRAWNRWKLR---RELLQR--------
----------------RPDQHMVDDETEEDADEIPDGELCVICVTRRRIPAFIPCGHVVC
CRYCALTVERGLNPKCPVCLQSIRGSMRIYYS-
>Brassica_rapa_gnl|BL_ORD_ID|33068 _027667|PACid:22716578

MIHWG--------------------GVTCCLSAAALYLLGSSSGRDAEVLKTVTRVNQLK
ELAQLLELDSSKLLPF-----------------IVAVSGRVGSDTP------------IK
CEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALML-----------SMSKEVPWFLDDG
TSR-------VNVVGARGATGFALTVGSEVFEE-SGRSLVRGTLDYLQGLKM----LGVK
RIERVLPTGMPLTIVGE-AVKDDIGDLRIQKPERGPFYVSPKSLDQLISNLGKWSRWYKY
AS-----------MGLTVFGVFLITKHVIDHV--------LERRRHRELQKRVLDAAAKR
---AEETEGS------NGAHESVSDSTKKEGAV---PDLCVICLEHNYNAVFVPCGHMCC
CTACSSHL-----TSCPLCRRRIDQVVKTYRH-
>Brassica_rapa_gnl|BL_ORD_ID|36378 _040424|PACid:22719888

MEPWS--------------------GL-CCIGAVALYLLSRRTARDVDFLKSVTRVDQLK
DL-------ESAVLPS-----------------IVAVSGTVGSETP------------IK
CEHSGILSVILQETAEQQFLKRNWKFSWVQDTALML-----------PVCKEVPWFLDDG
TGR-------VIVEGARSGIGFELTVGGEVFEKPEASSLVRGTLDFLRGLEM----LGIR
RIERVLPVGTRLTVVGQ-TIKDGVGDVRIQKPDQGPFYVSPIPLDHLISKVGKWSRRFKK
AS-----------MGLAVVGVILISKPVIKYILVRTGDF-LERRQQRLLKKRVVDAAAKR
KKLAAPKREE------RVTSKGLENGKSRDGDE---HDRCVVCLERKCDAAFVPCGHMCC
CLTCALKL---LGKPCPLCRKRGIRILKIYRN-
>Brassica_rapa_gnl|BL_ORD_ID|22231 _013775|PACid:22705741

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------FG--
------------TTISR-------------------YMFSGVLQD-------EFSGWYNE
LSITARAVVYITFLGTIMFLIFLILKF-------------LSDCDMEDDTERLPVVAGEE
VTGWTPLVNETSEVTGKGDLETASFSSAEDVDY---STYCVICFEERRNCFFVPCGHSAT
CRGCAEKIMSEENKVCPICRRVIRKSKRLVLKV
>Citrus_clementina_gnl|BL_ORD_ID|23563 _0.9_012472m|PACid:19274709

MSLLEQHLAS-LYQLAVSFDGAVL----GVALAYTAVRSFLDFRYT---SNALGKVRNAP
QLKVSDLRALL----DEKQSQPSDQEQNSRLVIVRGQVEAKSAVDGINWKTLMYSNDILV
S-E-SGDKAVILEQRKAFLYNEWR----DLFGWTPDIRAIFGRSLKTSEPSSLRTVPFIL
VEGDRWPQSDYIIVNMDGSR--QPLPLTTAYQRLELANVSPF-TFLQAMFGLKCPIGVLA
EEKILPLGKDISAVGICSFKN-GIPEIKSCKDLPYFLSEKTKDLMVVDLVNRSKILFWSG
IVLGSLSIGILGYAIVR----NWNRWKDRQQRMSRQLTEAPSDDADSQIGSDEDVAGD--
----IPDGQLCVVCLTRRRISAFNPCGHLVCCRRCAISVEREASPKCPVCRMTVRSSMRI
YFS
>Citrus_clementina_gnl|BL_ORD_ID|23562 _0.9_012450m|PACid:19274708

MSLLEQHLAS-LYQLAVSFDGAVL----GVALAYTAVRSFLDFRYT---SNALGKVRNAP
QLKVSDLRALL----DEKQSQPSDQEQNSRLVIVRGQVEAKSAVDGINWKTLMYSNDILV
S-E-SGDKAVILEQRKAFLYNEWR----DLFGWTPDIRAIFGRSLKTSEPSSLRTVPFIL
VEGDRWPQSDYIIVNMDGSR--QPLPLTTAYQRLELANVSPF-TFLQAMFGLKCPIGVLA
EEKILPLGKDISAVGICSFKN-GIPEIKSCKDLPYFLSEKTKDLMVVDLVNRSKILFWSG
IVLGSLSIGILGYAIVR----NWNRWKDRQQRMSRQLTEAPSDDADSQIGSDEDVAGD--
----IPDGQLCVVCLTRRRISAFNPCGHLVCCRRCAISVEREASPKCPVCRMTVRSSMRI
YFS
>Citrus_clementina_gnl|BL_ORD_ID|13924 _0.9_014777m|PACid:19265048

M-----------------------ISWGGISCCLSGAALYLLGRSSGRDAELLKTVTRVN
QLE--ELAHLL----------DGGSKVLPSIVSVSGRVGSE----------------TPI
SCEYSGLRGVIVEETTERHFLKHN----DAGSWIQDSALMLSMS---------KEVPWYL
---DDGTGCVFVV----GARGATGFALTVGSEVFEESGRSLVHGTLDYLQGLKM-LGVKR
IGRLLPTGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELLENLGKWARWYKYAS
FGLTIFGAFLIAKRVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNGQAENGSDSTQ
RDRVMPD--LCVICLEQEYNAVFFPCGHLCCCLICSSRLT-----NCPLCRRRIDQVVRT
FRH
>Citrus_clementina_gnl|BL_ORD_ID|13925 _0.9_019918m|PACid:19265049

M-----------------------------------------------------------
------------------------------------------------------------
-----------------RSFLRQSRVSINSRSW---------------------------
---DDGTGCVFVV----GARGATGFALTVGSEVFEESGRSLVHGTLDYLQGLKM-LGVKR
IGRLLPTGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELLENLGKWARWYKYAS
FGLTIFGAFLIAKRVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNGQAENGSDSTQ
RDRVMPD--LCVICLEQEYNAVFFPCGHLCCCLICSSRLT-----NCPLCRRRIDQVVRT
FRH
>Carica_papaya_gnl|BL_ORD_ID|10657 _evm.model.supercontig_25.125|PACid:16414718

MSSPEQALASLVSHLALSLDGAVLGVALAYA-----------------------------
---AVRSFFKFTANSAALRKIRSA---PQLRVSDLRSLLPV-------------------
------------------------------------------------------------
----SSEDQSQPSDSDPSS--TLVIVRGTVEAKSAVDGSWKGLRHNNV--LVSQESGDKA
VVIQRTQTYIYNEWKGFFGWTSDLRAIFGRSWGKQES------ASSRMVP----------
FVLVEDGR--------------WPQSDYVIVNTEGSLHPLPLTTVYHQLQPVNAS----P
YTFLQALFGHEYPVGLLNEEKILPLGKDISAVGICSFKNGIPEIMSCKDLPY--------
-------------------------FLSDLTKDQMLL----------------DLAFRTK
ILF--------WSGIILGSLSISILG----------------------------------
-YAALRNWNRWKERRQQRQAHQPS-------HAASIDANSELTGEEEIG-----------
-DIPDGQ--------LCVICLMRRRVPAFIPCGHIACCQPCALSVERELTPKCPVCRQEI
RGSMRV-----------------------FYA
>Carica_papaya_gnl|BL_ORD_ID|23657 _evm.model.supercontig_9.121|PACid:16428004

M-IPWGGITCCMSAAALYLLGRSSG-----------------------------------
------------RDADILRKVTRV--------NQLKELAQLL------------------
------------------------------------------------------------
----DIESKIMP---------LIVAISGRVGSETPISCEY---------------SGLRG
VIVEETAEQHFLKHNDAGSWIQDSALML---------------SMSKEVPWYLDDGTARV
FVVGARGATGFV-----------------------------LTVGSEVFEESGRSLVRGT
LDYLQGL----KMLGVKRIERVLPTGTSLTVVGEMTLEQFRYEDRTNGLFTC--------
-------------------------LQINGSPDFQLG----------------KWARWYK
YAS--------MGLTFLGVFLIAKRS----------------------------------
-IEYVLERRRRREL-QKRVLAAAA-------KRSGQDN-------EGSNIIPENGLDGAK
REHLMPD--------LCVICLEQEYNAAFVPCGHMCCCMTCSSHLTN-----CPLCRRRI
EQVLRT-----------------------FRH
>Carica_papaya_gnl|BL_ORD_ID|19402 _evm.model.supercontig_6.71|PACid:16423665

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--YKQKL----QIV------------------------------NPHGDLNL--------
-------------------------SKTNGEDD--LA----------------EWSVTLV
LVSRFVACIIVIALIMMVILMILKYL----------------------------------
-GELDSERTGEDAR-TQTNLLPAT-------KTASSFTYGTMCDQHDCSTSYSNTSYNYS
EDLYDKK--------LCIICYDEERNSFFVPCGHCATCYDCAKRIFNVENKACPVCRRFI
GKVRKL-----------------------FAP
>Carica_papaya_gnl|BL_ORD_ID|55 _evm.model.supercontig_0.150|PACid:16403859

MRLKHKPIINISELQRVAFIPAANGTRLVIANALFVRLTINLSPFAFELPSLYLPFVKIL
KDLGLQDMLSVASAKDLLLTLQKACGYQRLNPNELRAVMEILYFVCNAELDVSDGLNWRS
DAIIPDDGCRLVHAQSCVYVDPYGSRCVKYIDTSRLRFVHPDLPERICIDLGIRKISDVV
MEELDCEQDIQPLDYIGSV--AVELIREKLRSRSLQAAVW-------I--LLNSVAGYIP
SINNIPLETIETSLRSVAAELQFVNCIYTRFLLLQSSVDITLVSKDSIIPEWEDGCRHRT
LYFINQSKTRFLVAEPPSYLAVLDVVATVVSQVLGSPAPLPIGFLFSCPEGSESAIV---
-----------TFMGLCPVKRVI-EATPTSFVGKEILPQDALQVQIHPSRPFYRGEIVAW
RTQHGNKLKYGRVPENVRPSAGQALYRFKVETSPAMT----ELLLSSQVFSFRSVSMENE
GTS--------ASLLDVSPTVINNRSQVKAPESSREAKPRTYQLPPVKELQYAAPVSAAE
LVQAVHEMLSAAGI-SMEVDKQSLLHRNLTLQEELKESQAALLLEQEKA-----------
-DVAAKDADTAKVAWICRVCLSNEVDMTIIPCGHV-LCRKCSSAVSR-----CPFCRLQV
SKTMRI-----------------------FRP
>Carica_papaya_gnl|BL_ORD_ID|16613 _evm.model.supercontig_48.20|PACid:16420840

M-----------------------------------------------------------
--------------GHSLSKFRRR------HHNHHNSPLP--------------------
------------------------------------------------------------
----SIPENPIPSNSSSST--NPTAVSMTSSSINIANTRYGSPQNNPIRPILANASSSLS
PETQTPPSSSYNTHINSSLNYAPPVGGYSSYRPYHDH------QPRRGIP----------
----SQQQTVLPVIAPPPY---VDHNSTKKINSNVNVHKDTITLV---LDENNLDCHLVS
FTFDALVDGSITIL----------------------------------------------
-------------------------YFAKEDTDCMLTPLYPEIYTPRRIPFHKGLGQKFS
QPS--------GTGIDLGFFELDDLSKPFPKEDSFPLVIFAETCFPLNVGLDQSPRTNAQ
ITEAVIEKNNEGQF-QVKVIKQILW------IDEVRYELHEIYG-------IGNPKEADP
SDSDTGK--------ECVICLAEPKDTAVLPCRHMCMCSKCAKEL-RLLSKKCPICRQPI
QELIEIKVMEGEKGESIFHIGLSSSIHSSHFK
>SPL2_NP_564653
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------SSPERA---------------------------------LLN
LLTDIALSF---------------------------------------------------
------------------------------------------------------------
-----DGAILGLTLAVSA---------VGSALKYAS------------------------
-------------------------------------------------TNAALKKIKDA
PEVSISDLRSLLPASEDKSETNDNRKSNDQRIVVVR-----------------------G
VVKPKISGDE--GYKNNNVLISPE----------TGDKALIIQRTQTYVYSGWKRLFQST
GH------------------------------RFMLERSLRKHGADFTRTVPFVIVGKDQ
QSN---------------------------------------SSFVAVNMD---------
-----GSRQPLPLTTVYNRLQPINSSFLQAFLYPDYPVGLLDI-----EKILPPGKDITA
VGI-----------------YSFNNGVPEIKS---------CQDLPYFLSEMTKDKMIED
LMEQTNFIFLGSVILGIVSVGILSYAAVRTWNKWKQWNHQRELPQRPN------------
------DSVVDDEPEDADEIP------------------DGELCVICVSRRRVPAFIPCG
HVVCCRRCASTVERELNPKCPVCLQSIRGSMRVYY--------------S
>Capsella_rubella_gnl|BL_ORD_ID|3556 _v10009435m|PACid:20889189

MSSPERAVLNLLTDLALSFDGAILGLTLAISAVSSALKYASTNAALKKIKDAPEVSVADL
RSLLPASEEKSETNDQGTSHDQRIVVVRGVVKPKFSGDESQK-NNVLISP----------
-----------------------------------------ETGDKALIIQRTQTYV-YS
GWKRLFQSTGYRFMLERSMPKQGADFMRKVPFVIVGKDQQSQSSYLLVNMDGSRQPLPLT
TVYNRLQPINSSFLQAFLFPEYPVGLLDVEKILPPGKDITAVGICSFRN-GVPEIKSSQD
LPYFLSEMTKDKMIEDLIDQTSAIFFGT---VFLGIVSVG-I-LSYAAVR--------TW
NKWKLWNRQRELPRRPNEPVAD------DEPEDA----------------DEIPDGQLCV
ICVTRRRVPAFIPCGHVVCCRLCASTVERELNPKCPVCLQSIRGSMRVY-------YS
>Capsella_rubella_gnl|BL_ORD_ID|1198 _v10019584m|PACid:20886816

MIQ-------------------LGGLACCLSGSFLDYLSKIPASFVKSVTRV--RHIKDL
EQLVP-----------LESKV---VAVSGIVGSETPLKCKHS-DMLCVFI----------
-----------------------------------------EETAQQLFLKRNWMFS-WV
PDCNWMVP------ITKEVPWYLDDGTGRVN---VEANKVRC-FELKVGSKVFQESEPSS
ECH-----------RGLEM----LGVLRTERVLPIGTSVTIIGEAVKDSIGGFTIQESKE
VPFFVSSLPFDELISSFGKWSRKLKYAS---IGFTVVGVV-L-ILKPVVDY-------ML
ERRRRRLLRKRVADAAV---------KRAKL--VTRGLEAQD----------GDLLDLCV
ICLEHKNDAAFVRCGHMCCCSICSLHV-----KTCPLCRRPIEQVLRIY-------RL
>Capsella_rubella_gnl|BL_ORD_ID|21378 _v10020547m|PACid:20907165

MMH-------------------LAGFTCCLGGVALYLLSRSTGRVVESINRV--CHLKDL
EQLVD-----------GESKVFPLVIVSGTVGSETPIKCEYS-DVLGVFV----------
-----------------------------------------KKTAEQQVLRRNWRFS-WV
RDRTFMQP------MTKEVPWYLDDGTGRVN---VAVSQGEIGLALTVGSDVFEKSVPVS
LVQGAL-----SYLKGLQI----LGVRRIEHVVPIGTPLTVVGEAVKDGMGNVRIQKPEQ
GPFYVSYIPLDQLISKLGECSRKFKYAS---MGLTVLGVI-L-LSKPVIRYILKRIEDYL
ERRRRQLLLNRVADAAARRAEPV-APRRAEP--VTRGLERQHENSSDGTSRYGDTPDLCV
ICLDRKYNAAFVQCGHMCCCVRCSSQL-----STCPLCREPIEQVLRIY-------RH
>Capsella_rubella_gnl|BL_ORD_ID|11461 _v10006969m|PACid:20897164

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------DEFVRWYLELSFTARVVIYITVLGTIMM-IIFLILK--------FL
SECDMEDDMERLPVVAGEEVVPIWTPLINEPSEVVTGKGDVETASFSSSDDDVDYSTLCV
ICFEERRNCFFVPCGHSATCRGCALKILSEESKVCPICRRVIRKSKRLVLK-----KI
>Capsella_rubella_gnl|BL_ORD_ID|22308 _v10001179m|PACid:20908105

M---------------------GISFSNRRRDNNHHRLHHNPPPPPPPPPHRPPYYYPDP
PSQPP---------------------------PQNEYNYSYTQNNLVSTPPPPPPPPPPP
PPQINYGAYGHNYHQNQYYPQQAPPYFAGYHQNGWNNFGRRHYIPQPPTVQIVQPYVEHQ
SAKKVRNAVNVNKATVKLEPDDLNPGHHLVSFVFDAIFDGSFTIIFFAKEESDCTIVP--
-----------HLPEAYPQTKVPFEKGTGQKFLQPSGTGTDLGFFSLDDLSKPTPEGVYP
LVISAEAVTPPSSVSEEIFAHKQITLAS---LEKTNDKTFKVKVMKQIL---------WV
EGERYELQELYGIDNSV-----------------------IQDNGESGLEDAG--GKECV
ICLTEPKDTAVMPCRHLCLCSDCAKEL-TFQSNKCPICREPIEQLVKMKVQSSDGGQH
>Cucumis_sativus_gnl|BL_ORD_ID|29614 _360260.1|PACid:16980714

MSTSEQALVTLLSRFALSFD----GAVLGAALA-----YATVRTV---LKLTASCSA---
--------------------------LNELRK-APYVTVSDLRHIV------SDGVSEQS
ESDRKLVVVRGTVETRSSVEGNRKSLQPNVLISQESGDRAVIIQRTQVCIFNEWKGFFGW
TSDLRAIFGR----TFRKQESTSFRTVPFVLL-EGHSTYSDFV---VVNMEGSRHPLPL-
-----------------------------------------------------------T
TVYHQL-----QPVCA-TPYTFLQAVFGHEYPVGVLDE-------------------EKI
LPLGKNISAVGICSFEN-GVPVIKSCSDFPHFLCEMTKDQMILDLVFKTKFLFWSSIVLG
SLTVGILG-YSAARNWNRWKQWRQHRQLQNSRNDSPTSQLDSSNDIPIYGDFASDDEAAT
VPDDELSSHVPDDELSSHVPDDELSSHVPDG--------QLCVICLMRRKRSAFIPCGHL
VCCERCAVSVERESSPKCPICRQQIRSSVRI----YDS
>Cucumis_sativus_gnl|BL_ORD_ID|5673 _084910.1|PACid:16956611

M---------------LPWG--GISCCLSAAAL-----YLLGRSSGRDAELLKSVTR---
--------------------------VNQLKELAQLLEAEHLLPL---------------
-----VVAISGRVSSDTPIN------------CEFSGLRGVIVEETAEQHFLKHNDAGSW
IQDSALML-------------SMSKEVPWYL---DDGTGRAFV---LGARNATNFILPV-
------------------------------------------------------------
--VSEVFEESGRSLMR-GTLDYLQGLKM----LGVKRI-------------------ERV
LPTGTSLTVVGEAAKDDIGTIRIQRPHKGPFYVSPKTIDQLISNLGKWARWYKYASMGLS
IFGLYLVTKHVILYLMERRRRW----ELQKRVLAAAAKRSSQENEGEIEK----------
------------------------ASNGTDGTKRDRSMPDLCVICLERDYNAVFVPCGHM
CCCVACCSHLT-----NCPLCRRRIELVVKT----FRH
>Cucumis_sativus_gnl|BL_ORD_ID|21149 _253990.2|PACid:16972178

MG--------------ISWSNRRRNNYLQNPPPPPPPPYLSSSS----FYYPSEPQSLSP
APPPPPPPPPLQTHQFTNSHPPPPHS-------HPYSSTSQTLPL---------------
----------------PPIPHPPPPAP-----APHS------------YYFSGG------
----------YNSCNYGNSSMGRFNFYPYYA---NQSNGWSQVRPPMGPPLLPPPPLPIV
EHRQAKKVRNDVNVHKDTLKIEVDEQNPDHHLVSFVFDALYDGSITILFFAKEEPNCRFV
PVYPDAFKPVKIPFQKGPAQKFFQPVGT-GFDLGFFDLDDLSKPSPAEDTFPLVISAETC
SPSQSDDERIGEPHRDN----------------SHMQITQAVLEK------KNGGPFQVR
VIRQLL---------------WIDGVRYELREIFGIGSSSAEG-----------------
------------------------FDDNDTG--------KECVICMTEPKDTAVLPCRHL
CMCSECAKEL-RLQSNKCPICRQPIEELIEIRINNSDQ
>Citrus_sinensis_gnl|BL_ORD_ID|39549 _1.1g016312m|PACid:18132960

MSLLEQHLAS-LYQLAVSFDGAVLGVALAYTAVRSFLDFRYTSNALGKVRNAPQLKVSDL
RALL----DEKQSQPSDQEQNSRLVIVRGQVEAKSAVDGINWKNLMYSNDILVS-ESGDK
AVILEQRKAFLYNEWRDLFGWTPDIRAIFGRSLKTSEPSSLRTVPFILVEG---------
DRWPQSDYIIVNMDGSR--QPLPLTTAYQRLELANVSPF-TFLQAMFGLKCPIGVLAEEK
ILPLGKDISAVGICNFKN-GIPEIKSCKDLPYFLSEKTKDQMVVDLVNRSKILFWSGIVL
GSLSIGILG----YAIVRNWNRWKDRQQRMSRQLTETPSDDADSQIGSDEEVAGD-----
-IPDGQLCVVCLTRRRISAFNPCGHLVCCRRCAISVEREASPKCPVCRMTVRSSMRIYFS
>Citrus_sinensis_gnl|BL_ORD_ID|2129 _1.1g025999m|PACid:18093194

------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------MQSFLRQSRVSINSRSW
DDGTGRAFVV----GARGATGFVLTVGSEVFEESGRSLVRGTLDYLQGLKM-LGVKRIER
LLPTGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELIENLGKWARWYKYASFGL
TIFGTFLIAKRAIHYILQRKRRWELHRRVLAAAAVKRSEQDNEGTNGQAENGSDGTQRDR
VMPD--LCVICLEQEYNAVFVPCGHMCCCIICSWHLT-----NCPLCRRRIDQVVRTFRH
>Citrus_sinensis_gnl|BL_ORD_ID|2128 _1.1g024334m|PACid:18093193

MIPWGG------------------------------------------------------
------------------------------------------------------------
-------------------------ISCCLSGAALYLLGRSSEMQSFLRQSRVSINSRSW
DDGTGRAFVV----GARGATGFVLTVGSEVFEESGRSLVRGTLDYLQGLKM-LGVKRIER
LLPTGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELIENLGKWARWYKYASFGL
TIFGTFLIAKRAIHYILQRKRRWELHRRVLAAAAVKRSEQDNEGTNGQAENGSDGTQRDR
VMPD--LCVICLEQEYNAVFVPCGHMCCCIICSWHLT-----NCPLCRRRIDQVVRTFRH
>Citrus_sinensis_gnl|BL_ORD_ID|2130 _1.1g026347m|PACid:18093195

------------------------------------------------------------
------------------------------------------------------------
------------------------------------MLSMSKEVPWYL------------
DDGTGRAFVV----GARGATGFVLTVGSEVFEESGRSLVRGTLDYLQGLKM-LGVKRIER
LLPTGTSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELIENLGKWARWYKYASFGL
TIFGTFLIAKRAIHYILQRKRRWELHRRVLAAAAVKRSEQDNEGTNGQAENGSDGTQRDR
VMPD--LCVICLEQEYNAVFVPCGHMCCCIICSWHLT-----NCPLCRRRIDQVVRTFRH
>Eucalyptus_grandis_gnl|BL_ORD_ID|23965 _F04419.1|PACid:23585686

MSS---------------------------------------------------------
------------------------------------------------------HEQAIV
SLLSNFA----LSFDGAVLGLTLAYAAVRT----------IVKLTSSSSALRKLQDAPSV
RVSDLRSVLSLEGGSDSEPDSSSRSGREDLVIVR-GLVEAKSAVEGGTWKSLRQNVLVSQ
DSGDRAVIVQRTQTCIYNEWKGFFGWTSDLRAILSRSLRERKSSSLRTVPFVLIDGSQWP
AVDYVVVNMDGSKHHLPLTT--VYHQLQPINASPYTFLQALFGHEYPVGLLDEEKILPIG
KDVSAVGLCFLKN-GILEIKSCKDLPYFLTEMTKDQMVIDLAFRTKILFWSSIFLGSASI
GILGFAFVR-NWNRWKEWRQRRRD-------EQQSHAAVDEATAHIAEDELGDA---PDG
QLCVICLMRRRRSAFVPCGHLVCCQRCALSVEREVSPKCPVCRQ----------------
----------------------------------------TITNSVRIYDS
>Eucalyptus_grandis_gnl|BL_ORD_ID|33295 _I00478.1|PACid:23595016

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------MTKDQMVIDLACQTRILFWISIYLGKVSI
DGKSGGSAD-GMSR-----------------SSSSRAMLQSTSPTQTQWMIG---SVPDG
HLLVICLMRRGRSTFVPCGHLVCRQRCALSVEREVSPKCSVVGSRSLIQSGFLSIIVISF
LLVRGWNVEIVSFSSFIYPSEKEHAHPLMESPQWTSDYFVSITMLRRSLQL
>Eucalyptus_grandis_gnl|BL_ORD_ID|29270 _H01525.4|PACid:23590991

MGEIRTLSSFECKYNHVDRLIKGMASEITTLRTKVKEHREAWVKRPLVGRASRDTLSLST
RPVPHILTSPLIVSDSSPPPYPSIVSCSRPSSSCSCPSSIPATSVPLRSGELVLAGHALV
AFRAPFGGGGLISVGGPRASVSCSWSARGSRSLPHMIPWGGLSCCLSAAALYVLGRSSGR
DAEALKCVFRVNQLKELAQLLDTECKVLPLVVTLCGRVGSDTPIN-------------CE
YSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDDGT---
GRAYVLGARGASGFELNIASEVFEESGRSLVRGTLDYLQGLKM----LGVKRIERLLPVG
SSLTVVGEAVKDDIGTVRIQRPHKGPFYVSPKTIDQLISNLGKWARWYRYASYGFTVFGI
CLIAKRAIQYIMERKRRWELQRRVLAAVARRSEQDTEGTDDKTKNAPDSAKRDR-SMPD-
-LCVICLEQEYNSVFVPCGHMCSCTTCSLQLT-----NCPLCRR----------------
----------------------------------------RIEQAVKTFRH
>Glycine_max_gnl|BL_ORD_ID|6360 _03g13060.1|PACid:16251643

MSHQEQAFVSLLSQLALSFDGAVLGLALAYAAVRTLFKFTATSAALRKLHRAPSVS-VSD
LRSLL--AEIPSDADGNSDGG--NIVIVRGTVDAKSTVEGGTWKTLRPGVLVSRESGDKS
VILQRTQTCIYNEWKGLFGWTSDLRAIFARSWRQQESTSLRKVPFVLIDVGRWPNAEYVV
VNMDGSRHPLPL--STVYHKLQPITASPYTFLQALFGHEYPVGLLDEEKILPLGKNITAV
GLCSLKN-GIAEIKSCKDLPYFLSDLSKDQMIVDLSSKTKILFWGGIALGSMSVGVLGYA
VVRNWNKWKQWK--QQRQL-QQQRQAVSDVEPQMDDEIEDVPDG--------QLCVICLM
RRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRIYES
>Glycine_max_gnl|BL_ORD_ID|49470 _18g27930.1|PACid:16309372

MSHQEQALVSLLSQLALSLDGAVLGFALAYAAVRTLFKFTATSSALRKLRRAPSLS-VSD
LRSLL--AEIPSDGDGNSKGG--IIVIVRGTVDAKSAVD-GTWKTLRPGVLVSRESGDKG
VILQRTQTCIYNEWKGLFGWTSDLRAIFARSWRQQESTSLRKVPFLLTDVGRRPNAEYVV
VNMDGSRHPLPL--TTVYHKLQPITASPYTFLQALFGHEYPVGLLDEEKILPLGKDITAV
GLCSLKN-GIAEIKSCKYLPYFRSDLSKDQMIMDLSIKTKILFWGGIALGSMSVGVLGYA
VVRNWNKWKQWK--QQRQL-QQQRQAVSDVEPQMDDEIEDAPDG--------QLCVICLM
RRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRIYES
>Glycine_max_gnl|BL_ORD_ID|43458 _16g01030.1|PACid:16301042

MSHQEQAVLSLLSKLALSFDGAVLGVALAFAAVRTLFKFTATSASLRKLRRAPSIS-VSD
LRSLL--AEPPSDAD----AG--EIVIIRGTVDAKSAVD-GTWKTLKPGVLVSRESGDKG
VILQRTQTCIYNDWKGLLGWTSDLRAICARSLRQQDSTSFRKVPFVLIDVGRRPNAEYVV
VNMDGSRHPLPL--TTVYHKLQPINASPYTFLQALFGHEYPVGLLDEEKILPLGKDITAV
GHCSLKN-GIAEIKSCKDIPYFLSDLSKDQMIVDLSIKAKILFWGGISLGSMSVGVLGYA
VLRNWIKWKRWK--VQRQL-QQQRQAVSDAEPQVDDEIEDVPDG--------QLCVICLM
RRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRTYES
>Glycine_max_gnl|BL_ORD_ID|26571 _10g02920.1|PACid:16278382

MIPWG-------------------GLSCCLSAAALYLLGRSSGRDAEILKSVTRVNQLKE
LAQLLDAEILP------------LIVTISGRVSSETPIN-------------CEFSGLRG
VIVEETAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDD---GTDRVHVV
GARGASGFALPVGIEAFEESGRSLVRGTLDYLQGL----KMLGVKRIERVLPVGTSLTVV
GEAAKDDVGAIRIQRPHKGPFYVSPKTIDQLIANLGKWARWYKYASVGLTVFGAYLIAKH
AIRYILERRRRSELQRRVLAAAAKKSGQNNDVEKADSL---SDGAKKDRLMPDLCVICLE
QEYNAVFVPCGHMCCCTACSSHLT-----NCPLCRRQIEKVVKTFRH
>Glycine_max_gnl|BL_ORD_ID|4091 _02g16860.1|PACid:16248331

MIPWG-------------------GLSCCLSAAALYLLGRSSGRDAEILKSVTRVNQLKE
LAQLLDAEILP------------LIVTISGRVSSETPIN-------------CEFSGLRG
VIVEETAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDD---GTDRVHVV
GARGAAGFALPVGSEAFEESGRSLVRGTLDYLQGL----KMLGVKRIERVLPVGTSLTVV
GEAAKDDVGAFRIQRPHKGPFYVSPKTIDQLIANLGKWARWYKYASMGLTVFGAYLIAKH
AIRYILERRRRSELQRRVLAAAAKKSGQNNDVEKADGL---SDGVKKDRLMPDLCVICLE
QEYNAVFVPCGHMCCCTTCSSHLT-----NCPLCRRQIEKVVKTFRH
>Linum_usitatissimum_gnl|BL_ORD_ID|1179 _10000533|PACid:23140359

MSS-------QDQALLSIVSQLALSFDGAVLGVALAYAAVRSFLKFAARSKALKKVRNA-
--------------PVLTVSDLRSLLDAPSPPSHQDHNLDLDLGASTISSQQLVILRGQV
EAKSVVDGIWKSSLRPTLLVSHESGEKAVVIQRTQ-------------------------
--------TVPFVLLETGRWPQSEYVSVNM---------DGSRHPLP--------LTTVY
HQLQPIDASPYTFLQALFGHEYPVGLLD------------EEK--ILPVGKEITAIGMCG
SGN-GTPEITS--------CKDLPYFLTEMSKDEMVLQLAFTTKVLMWSGIVLGSVSVGI
LGYALRK----NWNRWKEHRQ-------RRESEQSTSEMSQVDESDDDVGGVADG-QLCV
ICLARRRRSAFIPCGHLVCCQYCAISVERDASPKCPLCRQLIRNSIRIF-----DT
>Linum_usitatissimum_gnl|BL_ORD_ID|42029 _10027994|PACid:23181209

MMV-------PWGGIGCCLSAAALYLLG------------RSSGRDAEALKSVTRVNQ--
------------------LKELAKLFDV-----------------ENNLLPLVVAISGRV
GSETPIN-------------CEFSGLRGVIVEETA--------------------EQHFL
KHN------------DAGSWIQDSALMLSMSKEVPWYLDDGTDRAFV--------LGARG
ASGFVLTVASEVFEES--GRSLVRGTLDYLQGLKMLGVKRIER--VLPTGTSLTVVGEAV
KDDIGKVRIQR--------PHKGPFYVSPKNIDELIGNLGKWARLYKYASAGLTVFGAFL
IAKQAVEYIMERRRRWDLHRKVLAAAAAKRSGNQDTESLNATAEDDSDGSKRDRVPDICV
ICLENEYNAVFLPCGHMCCCTTCCSHLS-----SCPLCRRRIEQVVKTY-----RH
>Linum_usitatissimum_gnl|BL_ORD_ID|6898 _10010392|PACid:23146078

MGAISDRGGGEWSSLLVLLANLLAYFMV--------------------------------
---------------------LGSLL----------------------------------
-----------------------------------------------------------L
KHNSLLHSSRPWFVI----------IMIFL------------------------------
---------------------------------------------VL-------------
-------KISS-------------YFVNVTEEEAAGEDAIEIDPL---------------
LLQQKTAVLYAYYGTCGDHQESLAAATC--SSSSSSSSSNGVAAHDDNHGSDDQV-KLCV
ICYDEERNSFFVPCGHSATCLACARRIYNEENKVCPVCRRLIGRVKKL--------
>Linum_usitatissimum_gnl|BL_ORD_ID|15586 _10034030|PACid:23154766

MGI-------SWSS-------------------------------------SRRRQNHAF
YHQQQHPPHLPPPPPPHYFSTEQTLLPPPPPPPNPIQGYYAAAPTTTVASPSTTTPQPSY
AAPPPPPQPPTHSYYS----SHPYNSRGYSNQLAGRFNYQPY-YYGNSSGGWPAPPHAVR
PNAGPSVQPVPYVEHQNAKKVRNE-VNVHK---------DTLRLELDENNPDHHLLSFVF
DALVDGSISISYFAKEEPNCKFVPAYPDVHMPVRVPFQKGVAQKFLQPSGTGID-LGFFE
LDDLSKPSFDEDVFPLVIVAETCPPVNSTGELDDSLSGPGSPGNM-QITQAVLEKKDCGP
FSVKVIK--------------QILWIEGVRYELREIYGMRSSAAEDFDDTEPG---KECV
ICMTEPKDTAVLPCRHMCMCSECAKELRIQSN-KCPICRQPIEELIEIKVKSGGDQ
>Malus_domestica_gnl|BL_ORD_ID|47849 _0000215866|PACid:22667834

MSS--DSNAIISLLSQLVLSWDGAVLGVALACAAMRSVLNFTASSSALRNLRQAPAVKVS
DLRSILPL--------DHSD----KLVVVRGTVEAKSLVD-GTWTAF-KSGVLVSKDRND
RAVILQSTKTYIIHKWKGFIGF-FNLRSIVWRYWRHWKDSEEHESNLVRKVPFVLVDG--
-DQWPIRDMVVVNVDGSSHPIPLTIAYHHLQPVNP--SPFSFLKALFGTNY-PIGVLTVD
KILPVGKEISAVGLCSLKNGVSEIKFCNDLPYFLSEMSKDEMVGDLASSTRMLFWTAFVL
GSMSIGVLSYAVVRNWNKWKVWRQQRQLQQSSQAADSDAEAQIEEE----DVPEGQLCVI
CLMRRRRSAFIPCGHRVCCHPCSISIERDIAPKCPVCRQEIRTS----------------
------------------------------------------------------------
-----------------------------------------------------LRVYDS
>Malus_domestica_gnl|BL_ORD_ID|47852 _0000215865|PACid:22667837

MSSPVPDNVFVSQLSRFVLSWDGAVLGVSLACAAVHSVLNFTSTSSSLSKLRDAPAVKVS
DLRSILPL--------DQSD----KLVVVRGTVEAKSAVD-GTWTGL-QSGVLVSKETNH
RAVIVDSTKTCIVQEWKGLIGWSSDLRAIIWRYWR------EHESNLVRKVPFVLVDG--
-DQWPIRDIVVVNVEGSRHPLPLTIAYHHLQPVHA--SPYSFLEALFGTNY-PVAFLNVE
KILPVGKEISAVGLCSLRNGVPEIKSCKDLPYFLSEMSKDEMVADLASRARMLFWVGIVL
GSMSIGVLGYAVVRNWNRWKVERQQRQLQQSSRDADSNAEAQIEDE-DAGDVPEGQFCVI
CLTRRRRSAFIPCGHRVCCHPCSISIERDIAPKCPVCRQEIRTS----------------
------------------------------------------------------------
-----------------------------------------------------LRIYDS
>Malus_domestica_gnl|BL_ORD_ID|47850 _0000308433|PACid:22667835

MSL--HERAVINLVSQLALSCDGAVLGVVLACAAVRTVIKFAYTSSALRKLRNAPYVKVS
DLRAILAP--------DESQPSDAKLVVLRGTVDGKS-------NSP-KSGVFVSRGTKN
SAVVVQRTQTCVYKDRKNFIGFPFDLRSLILKPWR------EQESKDLRTVPFVLVEG--
-SRRRVSEFVVVNI----------------------------------------GFLDEE
KILPLGKEISAVGLCSLKNGVPDIKSCKDLPYFLSEMSKDEMVVELTSRTRVLFWSGIVL
VSMSIGILGYAVSRNWDKLKAWKQGRQSQQSIPAADGNTETQIEEEEEVGEVPDGQLCVI
CLMRRRRSAFIPCGHRVCCHPCSISIQRNVTPCCPVCRQDIRASNPNDNAMSLHERAVIN
LFSQLALSYNGAALGVVLACAASRTVIKFAYTSSALLKLRNAPYVKVSGHRAILAPDESQ
PSDAKLVVLRGTVEAKSAVVGKWNSLKSGVFVSRGNKEQCRRRSKNQTARFGFFRFSVN
>Malus_domestica_gnl|BL_ORD_ID|40123 _0000200378|PACid:22660106

MPS--PQQVLIFLVSKLTLSFDSPILGVALGYAAVRTLLKLSSYSSVLPKVRIAPSVQIS
DLRSSLAF--------DQSDQSTAKLAVFRGTVEAKSALDDSKWNIFKKSDVLVSRGTXD
RAVIVXRTQTCVFNEWMGLFGW-WDFRAYWRALWR---ALTDPGSSSLXXVPLILVEGGG
RGKKPISDFVVVNVHRSRQPLPLTTVYRRLHPVIAPPSPISFFEALYGRDECQGGVLEEE
EILRLGKEISAIGLYSFKNGVLEVKSCXDLPYFLSGMSKEQMVVDLALRTKKLFRSGIVL
GSMSIGLLGYSAV-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------X
>Malus_domestica_gnl|BL_ORD_ID|9610 _0000250750|PACid:22629583

M----PDQILISLVPELAFSFDSPIV--------------------ALRKIRNAPSVKVS
NLRSILAF--------DQLGQSDAKLVIVRGTVEAKFVFD-CRWNVF-KSGVVPPQGT--
KAVLIHRSQRF----------------------------------------RFILVDRGG
-ARKSSSGFVSVNVDGSRHPLPLTTVYRYVHPVDA--SPYSSLKTHFGHEY-PASVLDEV
KILPLGKEISAVGLYSFKNGVPEVKSCKDLPYFLVAVKCRKVITLIPANVHQLILYDL--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------Q
>Manihot_esculenta_gnl|BL_ORD_ID|16192 _4.1_009144m|PACid:17976041

MSSHEQVLASLVSQLALSFDGAILGVALAYAAVRSFLKFTSNSKALRKISKAPTLRVSDL
RSVLDLPQPSDENQNQNVDQGQTQKLVIVRGQVEPKSAVDGNWKSLRSNALVSHECGDKA
VIIQRTQTCIYNEWKGFFGWTSDIRAIFGR--SWREQESTSLRMVPFVL-----------
------------------------VEGGRWPQSDYVIVNIDGSRHALPLTTVYHQLQPID
ASPYTFLQALFGHEYPVGLLDEEKILPLGKEINAVGICSSRN-GVLEIKSCKDLPYF-LS
DMTKDQ-----MVVDLAFKTKVLLWSGV-VLGSLSIGILGYAAV----------RNWNRW
KEWRQHRQSQQQN---------------------HAASTDDDPQIDADEEAGDVPDGQLC
VICLMRRRRSAFIPCGHLVCCQLCAISVEREVSPKCPLCRQAVRNSMRIFEC----
>Manihot_esculenta_gnl|BL_ORD_ID|33953 _4.1_032481m|PACid:17993992

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------EKITEMCLNHA---------------------------
-----------------------------ALVILMVFLIMKYLM-----ENGDESTSDGG
SATEINPLPLGKAMACTYGT----CHIDIESGCCNINSSDSDSSSSSNKISAELYDGKIC
VICYDEERNCFFVPCGHCATCYICARRILHEENKVCPVCRRFIGKVRKLFA-----
>Manihot_esculenta_gnl|BL_ORD_ID|32693 _4.1_011187m|PACid:17992725

M----------------------------------------------LLGPSSSRL----
-----MKASSVFVEQVEVRDDDKKGVILYGFYEKPELIVETNW------------SLSDY
MIVAPYSRKGFSVWLNKGS----------RIRMRWETQTTILNQLQVVLIKGERKYETLL
PTLTTSPDALNLSKPLNGKDAEYTIQEDDKYYLGLVNTN--------PKSIIMNIAVNVT
AK----------------LYDVSKARNMCSTIK----------GSCRLMLPFPKAQY-VV
VTTPDNGDLGGWYIELSFVARVITYIAILGFIIFIILLVLKYLGTCD--SEGNMADTEAR
QVSETEPILPEKPVPFTYGT----------------NEKDEDDGSSSTS-SEDLYDAKLC
VICYDEQRNCFFVPCGHCATCYECAQRIIEGEGKICPICRRLIYKVRRLFTS----
>Manihot_esculenta_gnl|BL_ORD_ID|26209 _4.1_011064m|PACid:17986177

M-LPWGGISCCLS-----------------------------AAALYLLGRSSGRDAEVL
KSVTRVNQLKELAKLLDIESNISPSVVSISGRVGSETPINCEY------------SGLRG
VIVEETAEQHFLKHNDAGSWIQDSALMLSMSKEVPWYLDDGTDRVYVVGARGASGFVLTV
GSEVFEESGRSLVRGTLDYLQGLKM-----------------------------------
----------------LGVKRIERVLPTGTSLTVVGEAVKDDIGTVRVQRPHKGPFY-VS
PRTIDE-----LIGNLGKWARWYRYASV-SLTVFGAFLIAKHAI---------QYIMERR
RRWELQSRVLAAAAAKRQGQ--------------DSEGSNGKAENGSDNSKRERPVPDLC
VICLEQEYNAVFLPCGHMCCCTTCSSHLTN-----CPLCRRRIEQVVKTFRH----
>Manihot_esculenta_gnl|BL_ORD_ID|2107 _4.1_010107m|PACid:17961845

MG----------------------------------------------------------
-----ISVSSNRRRNNTHYHHHPPPPYYYSTEASSLPPPPLNYFPAPTQPTSYPPSHNPY
----PTPPPPIHIHSNHSSHPYHASRYPSRFSDRPYYYANQTNEWPVIRPNVGTGQPIEP
PPYIEHQNAKKVRNDVNVHKDTLKVEIDEQTPDNYLVSFVFDALFDGSITIFYFAKEEVN
CK---FVPLFPEAHLPLRIPFQKGLGQKFRQPVGTGI---------------DLGFFELD
DLSK---------------------PSP-GEDVFPLVIVAETCLPVDSTDEYDDSVQNTS
GHMQITQAVLEKKNSDSFQVKVVKQILWIDGVRYELRELYGEGS-SASEGFNECDPGKEC
VICMSEPKDTAVLPCRHMCMCSECAKALRLQSNK-CPICRQPIGELIEIKINNGGQ
>Mimulus_guttatus_gnl|BL_ORD_ID|2783 _mgv1a007519m|PACid:17672175

MSLH--------------------------------------------------------
------------------------------------------------------------
-----DRALTAVLTQ-------LAMAADGAFIGVGVAYVAFSCFRKYAAT--SSALRKIS
QSASVQPSDLRSILSDSDDSRPSSSRRDDGDASSLNFDCGKLVFVSGSVEVKSALDKANW
KSLRGTDLVVSHESGEKGVILQRIQTCIYNEWRGLFRWTADLGSMLMPRRITKENASSSM
NMVPFILVEEGKWPPSDHVVVNMEGSTHPLPLTTVYQHLQPVKASSYTVFQALVGLEYPV
GLLYEEKILPLGKDITAVGICNLKN-GIPEIKSCEDLPYFLSILTKDQMIADLSFKSKVL
LWSGLILGTVAIGVLGYSISRNW-SKWKEWKARRA-------QQQQNASRIE---NLDET
EEEESGDVPDGELCVVCLMRRRRSAFVPCGHLVCCHRCAFSVEREVSPKCPVCRQPIRNS
VRIYDS-----
>Mimulus_guttatus_gnl|BL_ORD_ID|20512 _mgv1a015305m|PACid:17689913

MG----------------------------------------------------------
------------------------------------------------------------
----------TWVDDDDDEETPLSIVFYAPIIAILVMIIALIVKLLWNWN-EDGGYGE--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------EATESSGLLSYKDEESL---YSSYGTSEEDL-----ESCNNNINNNSKGSCSSS
YSSSGDDLYDGTICAICYDEQRSCFFVPCGHCITCYTCANRIISEEIKTCPICRTSIIKI
MKLHIS-----
>Mimulus_guttatus_gnl|BL_ORD_ID|10974 _mgv1a012839m|PACid:17680369

MLAG--------------------------------------------------------
------------------------------------------------------------
-----SAGLAEWLKDPSQPSIHFSMS--------------------WNLIHGNGSIQK--
------------------DVSESS----------------TYYIAVGNLNAEFAGVNLNT
T-----------------------------------------------------------
-----------------------------------------IKAFLHNTTESYYKCAPAE
GNCTFQLFLKGGNAAV--------------LTSPARSPGMVSGDWYFEL-----------
-WYGRRWVTYLIGTGGITSLLLLMNYFSNHLRRRDPLGEI--EPERNTLLSHEDGDSSAS
ISD--DDEHRHRHCAICFTAPKDCFFLPCGHSVACFQCATRI-RKSSAVCPICRQRTRKV
KRIYTV-----
>Mimulus_guttatus_gnl|BL_ORD_ID|1784 _mgv1a009837m|PACid:17671176

MI----------------------------------------------------------
------------------------------------------------------------
-----------------------------PVGGITCCLSAAALYLLGRSSGRDADLLK-S
VTRVNQLKDLAQLLEAASKVLP------------------LVVTVSGRVGSETPIN----
----------CEYSGLRGVIVEQTAEQHFLKHNDAGSWIQDSALML-----------SMC
KEVPWYL----DDGTSRVHVVGARGATGLVLTVGSEVFEESGRSLVRGTLDYLQGLKM-L
GVKRIERVLPTGSPLTVVGEAVKDDIGSIRIQRPHKGPFYVTDKTIDQLIANLGKWSRLY
KYASMGLTAFGVYLLAKHAFQYIMDRRRLWETRKRVLDAAAKKAGQNEGALN--GEAEIG
SDSSNKERPIPELCVICLEQEYNSVFVQCGHMCCCMACSSHLT-----NCPL--------
-----H-----
>Mimulus_guttatus_gnl|BL_ORD_ID|20244 _mgv1a011000m|PACid:17689645

MPMPMPLPAPYDHHHAAAHANWANGRYPYPMMPPAPAPAPYVEHQKAVTIRNDVNLKKET
LRIDPDEENPGKHLVSFTFDATVAGSSFMLMIIYNDSAGLHFSLGEDCCLTPTKENLHPP
IVVQFEQGLAQKFKQPSGTGIDLSMF-------------------------EDGELSK--
--------------ELDMDVYPLA------------------------VKAEASPDNQNE
SSD---------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SGSTNSQITQAVFEKDKGE
YQLRVVKQILWVNGMRYELQEIY--------------------------------GIGNS
VEGEFDANDPGKECVICLSEPRDTTVLPCRHMCMCSECAKVL-RFQTNRCPICRQPVERL
LEIKVSSGGDE
>Medicago_truncatula_gnl|BL_ORD_ID|48043 _Medtr8g025010.1|PACid:17479694

MSSQEQALVSLLSQLALSFDGAVLGFAVAYV--AVRSIRKFTLTSAALRKITAAPSVSVS
DLRSLL------TETDEN--SDEGKIVIVRGTVDAKNVVDGSWKALWPGVLVSSESGDKG
VVLQRTQTCIYNEWKGLFGWTSDLRALFLRSWRQQESTSLRKIPFVLIDVGRPSNPEYVV
VNMDGSSHPLPLTTVYHRLQPVNPPPYT--FLQALFGHEYPVGLLDEEK---ILPLGKDV
S--------AVGLCSLRN-GIAEIKACNDLPYYL-------SDLSKDQMIVDLSFKTKLL
FWSGILLGSMSVGII--------GYAVVRNWNKWKQWKQQRQLQQ--RRQQPIEPVPPTD
DEIED---VPDG--------QLCVICLMRRRRSVFIPCGHLVCCQGCAISVESE------
----VAPK---CPVCRQEVRDSVRIFES
>Medicago_truncatula_gnl|BL_ORD_ID|7454 _Medtr1g111550.1|PACid:17439105

MAM-----------VPWRGVGCCLSAAALYLLGRTSGRD-----VDILKSVNR-----VN
QLRELA------QLLDEEIFP---LVVAISGRVGSETPISCEF------------SGLRG
VIIEETAEQHFLKHSDAGSWIQDSALMQSRS---------NEVPWYL---DDGTGRVRVV
GAQGATGFVLPVGSEAFEESGRLPVRGTSDYVQGL----KMLGVKRIER---VLPVGTSL
T--------VVGEAAKDDVGTIRIQRPSKGPFYV-------SPKTIDELIANIGRWARWY
KYASAGLTVLSVYMI--------ANHAVR---YILERRRRNELEK--RVLAAAAKISGQD
NGGEMDDSLSDGAKRERAMPNLCVICLEQEYNSVFVPCGHMCCCTACSSHLTS-------
-----------CPLCRRQIEKAVKTFRH
>Medicago_truncatula_gnl|BL_ORD_ID|7431 _Medtr1g111340.1|PACid:17439082

MAM-----------VPWRGVGCCLSAAALYLLGRTSGSSMFFWYVDILKSVNR-----VN
QLRELA------QLLDEEIFP---LVVAISGRVGSETPISCEF------------SGLRG
VIIEETAEQHFLKHSDAGSWIQDSALMQSRS---------NEVPWYL---DDGTGRVRVV
GAQGATGFVLPVGSEAFEESGRLPVRGTSDYVQGL----KMLGVKRIER---VLPVGTSL
T--------VVGEAAKDDVGTIRIQRPSKGPFYV-------SPKTIDELIANIGRWARWY
KYASAGLTVLSVYMI--------ANHAVR---YILERRRRNELEK--RVLAAAAKISGQD
NGGEMDDSLSDGAKRERAMPNLCVICLEQEYNSVFVPCGHMCCCTACSSHLTS-------
-----------CPLCRRQIEKAVKTFRH
>Medicago_truncatula_gnl|BL_ORD_ID|4477 _Medtr1g023680.1|PACid:17436128

MYN--------------------FGVESSKIWP-------------------------KS
QLHSCGKRAEYIVEEDDR------------------------------------------
------------------------------------------------------------
---------------------------------------YQIGILNMNARNIILTLHINV
SAKIYDTTKATNKCSTRN-GSCKLDLFFPITYYLVLTAPKNGNDDDDAWFVEISFMARVF
SY-IILLGVFMIVIFMILKCLGADYGEIHNVAEAQEVTETEPLMQPNPVTYGTNIFHEKE
ETNSD-------VSEELYDEKLCIICFDEQRNCFFVPCGHCATCYDCAQRIMDEESNSTL
TDQIANPKSKVCPVCRRVINKVKRLF--
>Oryza_sativa_gnl|BL_ORD_ID|30371 _LOC_Os03g08000.1|PACid:21912843

MSARDRETAVALARLAAALDGAVLGLGTAALAVASWVKYLAASGQLRRIASAPAAAIPDL
RSLL------AEYGGGGGDGDQPILAVVRGHVRAAPRG-------KYLVPPGSGEHCVVA
KHTQLCLFNEWRGIFGWTFDLHALFFKSIKEQIITSFRWVPFVLV--DPENMTGMVHVKL
DRAMQPLPLTTVYHKLTPVDSTPYTLFQTIIGNGYPIALL---DEEKILPVGKEITAIG-
YIRPHKASVEISSCSEIPFFLSDLTKDEMEAELSSRAKTLFWASVVLGTMSVCLLGFATY
RSWKKIKERREARQ---AQEVFRQTTDEVTDDQSSDEEAGEMGDG---QLCVICLRKRRK
AAFIPCGHLVCCCKCALIVERQFDPLCPMCRQDIRYMIRIYDN
>Oryza_sativa_gnl|BL_ORD_ID|18391 _LOC_Os07g45350.1|PACid:21900863

MLIPWGGVGCCLSA------AALYLLGRSSGRDAEVLRSVARAGSTKDL-----AAILDT
ASKV-----------------LPLVVAVSGRVGSD----------TPLICQQSGMRGVIV
EETAEQHFLKHNDAGSWIQDSAVML---------SVSKEVPWYLD--DG---TGRVFVVG
ARGAAGLVLTVASEVF---EESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGE
AIKDDVGTIRIQRPHKGPFYVSPKSIDQLIMNLGKWAKLYQLASMGFAAFGVFLLAKRAL
QHFLERKRRHELQKRVHAAAAQRQAREAEGGNGTSDVDSNNKKDQLVLDICVICLEQEYN
AVFVPCGHMCCCMNCSSHLTN-----CPLCRRRIDQAVRTFRH
>Physcomitrella_patens_gnl|BL_ORD_ID|37837 _Pp1s52_256V6.3|PACid:18074375

MAGHEDELCAALMRLALAGDGLVMGVGMTVLAFRTWIKFWSHSKALKDIKDTPVTRIADL
RTLVEEPDVQAKEKIRTPEKISPPHQDIEVFATRSKVKMPSRPWMVERLPIPSLETKQEK
LVIVRGRVQTKAFVESEG--DQRDAEALIPLNVPEKAVFVERTQTYVLTEMSNFL-----
GWITQKDLVK----FTRQVVPFVLAETEAHWSFRPSDMAVYVHINLDESQHPIPLVTVHH
QLHPVPASSYTLFQAMFGRRYPVGLLDEEKILPLGAEITAVGVLHTAPDGTPVVKSSKRL
PIFLTEFTREQLLVELASSTKVLFWMGVAVSTVAAGVLGYSLVKNWTRWKQ-RQQQRQSQ
NNSENRQNSTI-EDEAENFEDIPDGELCVVCLLRRRRAAFIYCGHRVCCMGCAERVEHGA
NPRCPVCRQSVTGIVRVYDS
>Physcomitrella_patens_gnl|BL_ORD_ID|13900 _Pp1s15_293V6.1|PACid:18050435

MGSHDEEICVALTRIALAGDGVVLGLGMACLAVKAWLKYRTHEQALVAIKNTPLSHIADL
RILLQRQTLNSDPEIVISNQYPRSIQMTEALASKQPARFGFRMWR----KLDADLIKQER
IVMVRGKIQTKASVEPSAVLNAEDLQGITPSQSDTKAVYLERIQTYVHFEMNCML-----
GWIKQRDLVK----FTQKM-----------------------------------------
----------------------VGLLDEERILQMGREITAVGILDSTPDGKPVIKPCSGL
PIFLTECTREQLLMELARGTKMLLWLGVIATTFSAGVLTYAVIKNWLRWKQHRQLEEQQR
VNEERRQQRLMDEEEVENLVDVPEGELCVVCLLRRRRSAFIHCGHRVCCIVCARRVQQGA
DPRCPVCRQIVTSTMTVFDA
>Prunus_persica_gnl|BL_ORD_ID|16287 _ppa006914m|PACid:17656817

MSSHEQALISLVSQLALSFDGAILGVALAYAAVRTVLKLNSVSSALRKLHNAPSVQVSDL
RSILSLDH-----SDESQPSDAKLVVVRGTVEAKSAVDGNWNILNSGVLVSQGTKERAVV
LQRTQTCVYNEWKGFVGWPSDLRAIFSRSWRERESKVFRTVPFILAEGGRRPISEFVAVD
MDGSRHPLPLTTVYHHLHPVNPSPYTFLEALFGHRYPVGLLDEEKILPLGKEISAVGLCS
VKD-GVLEIKSCKDFPYFLSEMSKD---------------QMVVDLTSRTKVLFWSGIFL
GSVSIGV---LAYAVSRNWNRWKVWRQQR--ELQRSIRASNAEAQ-----IQEEEEEEDA
G-----------------DVPDG------QLCVICLMRRRRSAFIPCGHLVCCQLCSISI
ERDVAPKCPVCRQQIRTSVRIY--DS
>Prunus_persica_gnl|BL_ORD_ID|4153 _ppa008230m|PACid:17644506

M---------------LPWGG--LSCCLSAAALYLLGRSSGRDADILK----SATRINQL
KELAKLLD-----SECILP---LVVAISGRVSSETPI------------TCEFTGLRGVV
VEETAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDDGTGR-VHVVGARG
ATGFVLPVASEVFEESGRSLVRGTLDYLQGLKM----LGVKRIERVLPTGTSLSVVGEAV
KDDIGTIRIQRPHKGPFYVSPKTID---------------QLIANLGKWARWYKYAS--L
GLTVFGVYLVAKHSVQYI------LERRRRWELQRRVLAAAAKRS-----GEDNEGSNEK
D----------------DNVLDGSKRLMPDLCVICLEHEYNAVFVPCGHMCCCTTCSLHL
T-----NCPLCRRRIDQAVKTF--RH
>Prunus_persica_gnl|BL_ORD_ID|11467 _ppa010006m|PACid:17651932

MRVE--------------------------------------------------------
-------------AHATTLNKLQVVMLKGEQKIE--ILEPEHTSSQDGLASEETKIGKEA
EYNIEEDDKYYLDIINTKPRGIIITLNVNVSSTMYDITK---------------------
------------------------------------------------------AKAICS
TTK-GSCRLRLVFPNTHYVILTTPNNGYLG----------DWYIELSFVARVVTYIAI-L
GFIVVTIFLILKYLGACDGESSTVVERVE--EEVNETYPIVPQKNMRRTYGTNEEDEEDP
GASS----------SSSEELYDE------KLCIICYDEQRNSFFVPCGHCATCYDCAQRI
MDGENKVCPICRRLIHKVRKLF--NP
>Prunus_persica_gnl|BL_ORD_ID|24091 _ppa025017m|PACid:17664719

------------------------------------------------------------
------------------------------------------------------------
--------------------------------------K---------------------
------------------------------------------------------VKAVCS
FIS-LSSWTMFQFQNWSLVLTFLPENGKPTIQDTQKDDQVEWCVTLTFLARLIAYVGI-L
TLLVIVAYMILKYINEYDGEEGG-IEDVR--ES-TETSTLQPGKTMPVTYGTCDEWDIES
GNCSSSNSSNGPITSSSEDLYDG------KICVICYTEQRDCFLVPCGHCATCYVCAQRI
FYGDSKICPICRRSIRKVRKLFAAQD
>Populus_trichocarpa_gnl|BL_ORD_ID|12209 _POPTR_0003s06390.1|PACid:18218320

MASRAHEQALAAMLSHLAL-----SFDGAILGAALAYAAVRSFLNFTANSKSLAKIRKAP
TLSVSDLRSLL------QNHDQDHQDQEQKLVIVRGQVEAKSAVDGSGKKSSRDSNVLLS
HESGDKAVILQRTQTCIYNEWKGFFGWTSDLRSIFGRSLKEQETTFLRTVPFTLVEGGQW
PQSDYVIVNMDGSSHPLPLTMVYHQLQ----PIVASRYTFIQALFGHEYPVGVLHEEKIL
PLGKC--------------------------------------ISAVGI-----------
----CNSKD-GIPEIKSCKELPYFLADMTKDEMVADLAFK-------AKILLWSGIVLGS
LSIGVLGFAVMRNWN--------------KWKAWRQRRS--QQPIHTTSDEDV-----SQ
IDDNEDAG---------DVPEGQLCVICLMRRRRAAFIPCGHLACCHTCAVSVESEVSPK
CPLCRQAVRNSIRIFEC
>Populus_trichocarpa_gnl|BL_ORD_ID|32327 _POPTR_0001s16880.1|PACid:18238703

MSSRSHEQALAALLSQLAL-----SFDGAILGAALAYAAVRAILNYTANSKSLAKISKAP
TLSVSDLRSLL------QNHDQDHQDHEHNLVIVKGIVEAKSAVEWTWKESFRPPKVLLS
HNSAYKAVILQKTQTCIYNEWKGFLGWTSELRAIFGRSLKEQETTLLRTVPFILVEGAQW
PRSDYVIVNMVGSAHPLPLTTVYHQLQ----RIAASRYTFIQALFGHEYPVGVLHEEKIL
PLGKC--------------------------------------ISAVGI-----------
----CNSKK-GIPEIKSCKDLPYFLADITKDQMVADLAFK-------AKIQLWSGIFLGS
LSIGVLGFAVMRNWN--------------KWQAWRQRHS--HLPNHTTIDADV-----SR
IDEDE-AG---------DVPDGQLCVICLTRRRRSAFIPCGHLACCHFCAISVESEVSPK
CPLCRQAIRNSIRVFEC
>Populus_trichocarpa_gnl|BL_ORD_ID|16448 _POPTR_0014s13410.2|PACid:18222629

------------------------------------------------------------
------------------------------------------------------------
---------------------------------MLSMS---------KEVPWYLDDG---
--TDRVYVVGARGASGFVLTVGSEVFEESGRSLVRGTLDYLQGL----KMLGVKRIERVL
PTGTS--------------------------------------LTVVGE-----------
----AVKDDIGTVRIQRPHKGPFYVSPKSIDELIGNLGKW-------ARWYKYAS--LGL
TVFGA--FLITKHVI--------------RYIMERRRRW--ELQSRVLAAAKRSGQDNEG
SNDKAENG---SDGAKRERPIPDLCVICLEQEYNAVFLPCGHMCCCITCCSQLSN-----
CPLCRRRIEQVVKTFRH
>Populus_trichocarpa_gnl|BL_ORD_ID|16447 _POPTR_0014s13410.1|PACid:18222628

MM--IPWGGISCCLSGAALYLLGRSSGRYLPSLIPLFFLIISSKLLDIESKVLPL-----
------------------------------VVAISGRVGAESP--------------ISC
EFSGLRGVIVEETAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDDG---
--TDRVYVVGARGASGFVLTVGSEVFEESGRSLVRGTLDYLQGL----KMLGVKRIERVL
PTGTS--------------------------------------LTVVGE-----------
----AVKDDIGTVRIQRPHKGPFYVSPKSIDELIGNLGKW-------ARWYKYAS--LGL
TVFGA--FLITKHVI--------------RYIMERRRRW--ELQSRYVSLV-------EG
IHDKMFQGKGHANGAKRERPIPDLCVICLEQEYNAVFLPCGHMCCCITCCSQLSN-----
CPLCRRRIEQVVKTFRH
>Populus_trichocarpa_gnl|BL_ORD_ID|16614 _POPTR_0014s02100.1|PACid:18222795

ME--RKLGTVNCLFDNMDMWHTHFGYD----------FAVSVSLRYG-------YFGDSR
MVLGPSSSRLMKASSVFVDHVEVRDEDKKGVLLYGFYEKPELS-----------------
-----------------------------------------------FETNWSVAD----
-----YMIVASYSRKGFSLWLNKGSKIRMRWEARTSILNQLQVV----MIKGERKYETLL
PKQTSSPDALNLSEPLNGKEAEYTIEEDNRYYLGLINTNPKNIITTLSVNVTSKMYELSK
ARNMCSTTQ-GSCRLKLLFPKTQYVVVTTPDN--GDINGWNIEVAFVARAIIYVAI-LGA
IVIII--FLILKYLGACDTDQSTNLVETATWQASEPSETEPIMPAKSVRLT-------YG
TNEEDDEG--SSCSSSEDLYDAKLCVICYDDQRNCFFVPCGHCATCYDCAQRIMEEDNKM
CPICRRLIHKVRRLFTS
>Panucum_virgatum_gnl|BL_ORD_ID|10707 _Pavirv00062729m|PACid:23766538

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQLRLVASAA-ASSISD
LHSLLPGS-----------GGEPRLAAVRGYVRPKPGG-------TILRTPFSGEHGVVT
KHTQMCLFTEWRGIFGWTFDLHALLFRSWKEQIVTSFRTVPFVLASSEIGNPIGMVYINV
EKAD--QPLPLTTVFHKLIPIETTPYTLFQTIIGNGYPIALL---DEEKILPIGKELTAI
GLCRAKD-ESVEISSCPDLPFFLSELTKDEMQAQLASRARTLFWGSIVLGTLSVCLMGRA
IYRCWKRIKLRREARQ------AQQLFEDAE--DAIQEGDSSD-EEVGDGQLCVVCLRRR
RKAAFIPCGHLVCCCKCALRMEREAEPLCPMCRQDIRYMMRIYDS
>Panucum_virgatum_gnl|BL_ORD_ID|48680 _Pavirv00039347m|PACid:23804892

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLTVSGQLRLVASAA-ASSIAD
LRSLLPGS-----------GGEPRLAAVRGYVRPKPGG-------MILQPPFSGEHGVIT
KHTQMCLFTEWRGIFGWTFDLHALLFRSWKEQIVTSFRTVPFVLASSEIGNPIGMVHINV
EKADPNQPLPLTTVFHKLIPIETTPYALFQTIIGNGYPIALL---DEEKILPIGKELTAI
GLCRAKD-ESVEISSCPDLPFFLSELTKDEMQAQLASRARTLFWGSIVLGTLSVCLVGHA
IYRCWKRIKLRREARQ------AQQLFEEAE--DAIQEGDSSD-EEVGDGQLCVVCLRRR
RKAAFIPCGHLVCCCKCALRMEREAEPLCPMCRQDIRYMMRIYDS
>Panucum_virgatum_gnl|BL_ORD_ID|15701 _Pavirv00022452m|PACid:23771586

MMIPWG------------------GVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKD
LAAIL----------DTASKVLPLVVAVSGRVGSD----------TPLICQQSGMRGVIV
EETAEQHFLKHNDAGSWIQDSAVMLSVS---------KEVPWYL---DDGTGRVYVV---
-GARAAAGLILTVASEVF---EESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVV
GEAIKDDVGTIRIQRPHKGPFYVSPKSIDQLILNLGKWAKLYRLASMGFATFGVFLLAKR
AIQHFLERKRRHELQKRVFNAAAQRQAREAEGGNGTSDTEPNSKKDQLVLDICVICLEQE
YNAVFVPCGHMCCCIACSSHLTN-----CPLCRRRIDQAVRTFRH
>Phaseolus_vulgaris_gnl|BL_ORD_ID|21270 _091018531m|PACid:23552061

MSHQEQALV---------SLLSQ-------LAL-------------SFDGAVLGFALAYA
--------AIRTLVKFSATSAAL-----------------------RKLRRAPYLSVSDL
RSLLADTPSDANSN----SDGGAIVIVRGNVDAKSAVDGSWKTLRPGVLVSRESGDRGVI
LQRTQTCIYNEWKGLFGWTSDLRAIFARSWRQQESTSLRKVPFVLID-------VGWRPS
TEYVVVNMDGSRHPLPLTTVYHKLQPINASPYTFLQALFGHE----YPVGLLDE------
---EKILP-VGKDVTAVGLVSLNN---GVAEIKSCK-------------DLPYFLS---D
LSKDQMI-----------VDLSIKTKILFW-GGIALGSMSVGILGYA-------------
------VVRN-WNKWKQWKLQRQL---QQQRQAVSDVEPQVDDEIEDV-------PDGQL
CVICLMRRRRSVFIPCGHLVCCQGCAISVEHEVAPKCPVCRQEIRNSVRIF----ES
>Phaseolus_vulgaris_gnl|BL_ORD_ID|17669 _091029254m|PACid:23548376

MK-----------------------------MI-------------PWGG--LSCCLSAA
--------ALYLLGRSSGRDAEI-----------------------LK----SVTRVNQL
KELAQLLDAEILP---------LIVTISGRVGSETPISCDF------------SGLRGVI
VEETAEQHFLKHNDAGSWIQDSALMLSMS---------KEVPWYLDDGSDRVHVVGARGA
TGFAL--------PVGSEAFEESGRSLVRGTLDYLQGL--------KMLGVKRI------
---ERVLP-VGTSLTVVGEAAKDDV--GTIRIQRPH-------------KGPFYVS---P
KTIDQLI-----------ANLGKWARWYKY-ASMGLTVFGAYLIAKH-------------
------AIRFILERRRRSELQRRVLAAAAAKKSGPNNDVEKADSLSDVAKRDHLMPD--L
CVICLEQEYNAVFVPCGHMCCCTACSSHLTN-----CPLCRRQIEKVVKTF----RH
>Phaseolus_vulgaris_gnl|BL_ORD_ID|13520 _091008261m|PACid:23544116

MALLHPPVR---------TAPSQPHRWQQAWML-------------PPLA--IWICVSAT
LRYGYYGDSLILLGPGSS-----------------------------RLIRTSSVFVKQL
QVASKDQNQVFLH-----------------AFSKKP---------------ELSSLTNWT
ASDFFLVEAYKSKGISLWLNQGSTIRIR-WEEHTSRSLDQLHGMVI-----------KGD
MKFEL--------PQAPQTSFLNAISL-RGTVNGKEAEYMVEEDDRYHIGVLNM------
---NARNI-ILTMEVNVSAKVYDTT--KAKKMCSSE-------------NGPCRLSFSFP
NTYYVILTATNNGDGASYVEISLVVRVFVYILLLGIIVIAVYLILKALGVYDDAEQHSHV
TVDVTYGTSNVVATQTETEPLMRVEANRMSYGTNAKDDEENSVAYSSSSEEL---YDEKL
CCICYDEQRSSFFVPCGHCATCYDCAQRIVDGESKVCPICRRLIHKVRRLF----HI
>Phaseolus_vulgaris_gnl|BL_ORD_ID|12949 _091022080m|PACid:23543541

MG-------ISWSGRRRNNYIQNPPPPLPPPPYYYPPQSHHPPLPPPPQGYFLP------
--------STTTYAPNSNNYAAPPPLVPPPQPPPQTHSISFYYTNQSAYPNYANSAPNRL
Q-----------YQPFYHPQPSVWPAATGAPASTPPPYVDHQAAKK---------IRNYV
N-----------------VHKDTLRLEVDQENPDHHLISFVFDAVYDGSITVFYFAKEEE
KCRFV--------PLFPDAFQPVRIPFQKGVG---QTFSQPSGTG-IDLGFFELDDLSKP
SPEEDVFPLVICAETSLKTPSEDETLGDSVLDASPHMQITQGVLEKSNGAGPFLIK----
-VVRQIL-----------------------------------------------------
-----------WIDGVRYELRELYGIASSSAADFDDNDP------------------GKE
CVICMTEAKDTAVLPCRHMCMCGECAKSL-RLQSNKCPICRQSIEELIEIKVNNDNQ
>Ricinus_communis_gnl|BL_ORD_ID|8129 _29706.m001280|PACid:16806294

MSSHEQALASLVSQLALSFDGAFLGVVVALTAVRSILKFASNSKALRKIRNAPTVKVSDI
RSVLEVSDE---------TQDQK-------------------------------------
--------LVIVRGQVEAKSAVDGNWKSLIPNNNVLVAHESGDKAVIVQRIQTCIYNEWK
G---FFGWTSDIRAIFGRSWRE-QES---TLSRSVPFVLVEAGRWPQSDYVIVNLDGSRH
PLPLTTVYHQLQPIDASPYTFLQAFFGYEYPVGLLD---EEKILPLGKEINAVGLCGSKN
-GILEITSCKDLPFFLSDLSKEQMVVDLAFKTKVLFWSGVVLGSFSICILG---------
--------------------YAAVRN-WNRWKAW--------------------------
-------------------------------RQQRQFQQQSNSVSDADVSQIDVEEETVD
-VPDGQLCVICLMRRRRAAFIPCGHLVCCQICAISVEREVSPKCPLCRQAVRNSIRIFEC
------------------------------
>Ricinus_communis_gnl|BL_ORD_ID|16536 _29970.m001010|PACid:16814701

ME----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------FSYGTCSNTDSE--ESGYCS-SSTSSSNFSTE
-LYDGKVCVICYDEERNCFFVPCGHCATCYVCARRIFDGENKVCPVCRRFIGKVRKLFAL
------------------------------
>Ricinus_communis_gnl|BL_ORD_ID|23456 _30170.m013775|PACid:16821621

MESKE-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-AEYKIEEDDKYYLSLVNTNPKSILVRVAVNVTSKLYD--LSKARNMCSAIKGSCRLTIL
FPKTQYVVVATPDTGDIRGWYIELSF-VARVITYIAILGFIIVIIFLILKYLGACSENTV
VEMAAGPIQISETQPILPEK-----SIRYTYGT-NDEDND--EDG--------SSSSSED
-LYDAKLCVICYDEQRNCFFVPCGHCATCFDCAQRIIEGEGKMCPICRRLIHRVRKLFTP
------------------------------
>Ricinus_communis_gnl|BL_ORD_ID|7472 _29681.m001351|PACid:16805637

MNYHSGGETERPLG-----ERQLIAISLFLLSQNAAVQFCNSFTFFRQLMEEADHPSSSS
SVPVAEPSASQVQEEEVRNEQIENGNNSHHQRNHPSYSYSSALPYRVNISISNMAPTEMT
DDVWSCLVVLVTFWFFASMTLILGFYGSVNLELGPNCSYLIKTNPLFVQSIKVEEVDEPK
HGPMLYGFHKPPPMDVETTWTETHKALILPHLQEWAYFL---NKGSKVAIFYTIKSPSSS
PLSL--------VIAQGRDSLVEWIDEPSYPNSTLS---WNIIFGSGK------------
-IEQEISESSNYYIAVGNLNSEDVEVELKFRMNAFIYN--TTNAFYMCSLGHRLCSLKLF
LLGTNVAVLTSPVPQEGDDWYVKVSY-GPRWMTYFIGSGFMTLLILFTLRYCKMFQASSG
DGIQEGDNLRSERAPLLLPKDDDVSSWGSSYGSTSQEEHEDLDELLAM-NSGAGKQLSEG
-ENLNRLCVICFDAPRDCFFLPCGHCAACFTCGTRIAEEPG-TCPICRRSMKKVRKIFTV
------------------------------
>Ricinus_communis_gnl|BL_ORD_ID|8077 _29703.m001546|PACid:16806242

MR-------------------------------------------------NAEYSKTTF
GKGLDAEALKSVTRVNQLNELAK-------------------------------------
--------LLDIESKVLPLVVAIS--GRVGSETPINCEY-SGLRGVIVEETAEQHFLKHN
D---------------AGSWIQ-DSALMLSMSKEVPWYL---DDGTDRTFVVGARGASGF
ALTVGS-----EVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGTSLSVIGEAVKDD
IGTVRIQRPHKGPFYVSPKTIDELIGNLGKWARWYRYASVGLTVFGVFLIA---------
--------------------KHAIQYIMERRRRW--------------------------
----------------------ELQSRVLAAAAKRQGQDSDGSNGKAE-NGSDSSKRERP
-IPD--LCVICLEQEYNAVFLPCGHMCCCTACSSHLTN-----CPLCRRRIEQISASIPV
KDSCQGTDFLFHPRIRCKILPIAAIAYNWK
>Sorghum_bicolor_gnl|BL_ORD_ID|4679 _Sb01g045370.1|PACid:1954575

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQLRLVASAATA-SIGD
ARSLLRGD-----------GNEPRIAAVRGYVRTQ---------GSFLRAPFSSEAG---
------------------------------------------------VVVKHTQMCLFT
EWRGIFGWT--------------FDLHALLFR----SWKE--------QIVTSFRAVPFV
LASTELGNSTGVVHINVDEVDYQPLPLTTVFHKLIPLETTPYT--LFQTIIGNGYPI---
ALLDEEKILPIGK-KITAIGLCRAKNAESVEITSCPEIPFFLSELTKDEMQAQLASRARI
LFWGSIVLGTLSVCLVGHAIYRGWKRIKLRREARQ-------AQQMFEDAEDAIREDNSS
DDDDDDVGDGQLCVVCLRKRRKAAFIPCGHLVCCCKCALRMEREVEPLCPMCRQDIRYMI
--RIYDS-----------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|8897 _Sb02g041380.1|PACid:1959657

MM------------------IPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKD
LAAIL----------DTASKVLPLVVAVSGRVSSDTP----------LICQQSGMRG---
------------------------------------------------VIVEETAEQHFL
KHNDAGSWI--------------QDSAVMLSV---------------------SKEVPWY
LD-----DGTGRVYV-VGARSAAGLILTVASEVFEESGRT-----LVRGTLDYLQGLKML
GVKRTERVLPTGT-SLTVVGEAIRDDVGTIRIQRPHKGPFYVSPKSIDQLIMNLGKWAKL
YRLASMGFATFGVFLLAKRAIQHFLERK-RRHELQKRVLNAAAQRQAREAEGSNGSSDTE
PNSKKDQLVLDICVICLEQEYNAVFVPCGHMCCCMACSSHLTN-----CPLCRRRIDQAV
--RTFRH-----------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|25703 _Sb09g019560.1|PACid:1980775

MG-------------------------------------ASSSRRRR-------------
-------DDYYPPPHHYSSYPPP------------------------PPPPPH----HHH
PPPP----------PPPPHHRPPPPPPPSSYYYH---------PHPPP-----PHAYHGP
WHPAPAPPPQPQPPALTGPPPEFVEHQQAQKVKNYVNLHKDTIRLVPDDADPDRRLVAFT
FDAITDGSVTIYYFAKEEK----DCSFSSIYPELQTPTKIPFEKGLAQRFIQPSGSGVDL
GFF-SLDELSSSSGEVFPLVVYA-------EAYPS---P---EEGGPSVNST-RAQITLA
VLE-KHN-NDLQV-----KVVKQILWIDGVRYELQ-------------EIFGMVNSTESD
VADADADDTGKECVICLTEPRDTAVMPCRHLCLCSECAKTLRFQSNK-CPICRQPVEKLM
EIKVRSSEP---------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|4175 _Sb01g040770.1|PACid:1954038

MG-----------------------------NAGSNGGGAAAGHRRR-------------
-------SSSHGHGHHHQAPPPP---------QPQETAPNRYVFAAATPYPPQ----YPN
PNPPQYYPQYGNYYPPPPPSVPVPLPAPYDHHHRPPTAAPGEFPPPPP-----AHPHHYP
GWAGRYPSYGPHLPM----PTPYVEHQKAVTIRNDVNLKKETLRIEPDEECPGHFLVAFT
FDATVAGSMTVYFFAKEEL----NCNLAAMKEDLIKPVTVSFKEGLGQKFRQPSGTGIDF
SVFEESDLLKQGDMDVYPLVVKA-------ETALSADHP---SEGDDQKMKTPNSQITQA
VFEKKEN-GDYQV-----RVVCQILWVNGTRYELQ-------------EIYGIGNSME--
-GDADANDPGKECVICLSEPRDTTVLPCRHMCMCSECAKVLRYQTTR-CPICRQPVERLL
EIKVNNKSEEQQQTPQSPPLPAPAPQQEEV
>Setaria_italica_gnl|BL_ORD_ID|11123 _Si036246m|PACid:19684534

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQLRLVASAATA-SIAD
-----------------------------------LRSLLPGD-----------GGEPRV
AAVRGYVRPKPGG-------NILRVPWSGEHGVVTKHTQMCLFTEWRGIFGWTFDLHALL
FRSWKEQIVTYFRSVPFVLASSEIGNPIGMVYIDVEKAAQPLPLTTVFHKL-----IPIE
TTPYTLFQTIIGNGYPIALL---DEEKILPIGKELTAIGLCR----ANDEGSVEISSCPE
LPFFLSELTKDEMQAQLASRARILFWGSVVLGTLSVCLVGHAIYRGWKRIKLRR------
-------------EARQAQQLF----EEGEDAIQEDDSSD-EEVGDGQLCVVCLRKRRKA
AFIPCGHLVCCCKCALRMERETEPLCPMCRQDIRYMMRIY----DS
>Setaria_italica_gnl|BL_ORD_ID|31124 _Si008199m|PACid:19704670

M-----------------------------------------------------------
------------------------------------------------------------
--------------------NIL-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------NALVSFASRWFLYFVVAVVILAVFYCFLKQLADDAGTEHEPIRRQDATAR
ETEPIL-------PRKEVFFSYGATGEQPESSVCPAEDSD-----SDKMCKICYDAPRSC
FFIPCGHCFTCFTCARRIVEEENKACPICRRLIHRVKRVE----SP
>Setaria_italica_gnl|BL_ORD_ID|40388 _Si030396m|PACid:19714000

MMIPWG------------------GVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKD
---------------------------------------------LAAILDTASKVLPLV
VAVSGRVGSD----------TPLICQQSGMRGVIVEETAEQHFLKHNDAGSWIQDSAVML
---------SVSKEVPWYL-----DDGTGRVYVVGARAAAGLILTVASEVF--------E
ESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAI----KDDVGTIRIQRPHK
GPFYVSPKSIDQLILNLGKWAKLYRLASMGFATFSVFLLAKRAIQHFLERK-RRHELQKR
VLNAAA-----QRQAREAEGGKGTSNTEPNSK----KDQL-----VLDICVICLEQEYNA
VFVPCGHMCCCMACSSHLTN-----CPLCRRRIDQAVRTF----RH
>Setaria_italica_gnl|BL_ORD_ID|27105 _Si022534m|PACid:19700622

M-------------------------------------------------GASSSRRRRD
DYYPPPPPPPPHHYSSYPPPPPPHHHHHHHHPPPPPHHRAPPPPPPPSSSYYYHPHPPPP
QAYHGSWHPAPAPPPPPPQPPAL----TGPPPEYVEHQQAQKVKNYVNLHKDT-------
IRLEPDAADPDRRLVAFTF---DAVTDGSVAIYYFAKEGKDCSFSSVYPELQTPTKIPFQ
KGLAQRFIQPSGSGVDLGFF---SLDELSNSSGEVFPLVVYAEAYPSPEEGGTSVNSTR-
--------------------------AQITLAVL---------------EK-HNDDLRVK
VVKQILWIDGVRYELQEIFGLVNST----ETDVADADADD-----TGKECVICLTEPRDT
AVMPCRHLCLCSECAKTLRFQSNK-CPICRQPVEKLMEIRVRGPEP
>Selaginella_moellendorffii_gnl|BL_ORD_ID|11999 _91152|PACid:15413277

M-----------------------------------------------------------
-------------------------------------------ASHDEEICAALTRLAMA
GDGIVLGLGMAALALRTWLKFGSHTRALKQVEGTA-------------------------
----------------QVEIHDLRSLVESGEKEPSSD-----SSPPLVIVRGRVALPPKT
SSE------EVL-------------------------LARNQTD-------LAVFVERTQ
T------------YLFNEWRGLFRWGPEWRGLLGWGSLKEQVAFSRRKIPFVLL------
-DSDPQYDGAC-----------------------VHINMENVEHPLPLV--TVFHQLHPV
QTSSSTFLQAVFGRRYPVGVIDEEKILPLNREITAVGF------LSKHPQGLPAIKSSNQ
MPFFLTEFSREELIVELAS---ATHALFWTGIVISSLALGVIGYSAFKNWCKWKEWRRL-
-RQIQEEL------------RREE--------QVMEEDEE--------PATTQ-------
---EGSEVPDGQLCVVCLLRRKRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSV
SGYIRVY---D
>Selaginella_moellendorffii_gnl|BL_ORD_ID|5424 _74018|PACid:15406702

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----DEKL------------SNEQ--------PSV--DHR--------PAEGS-------
---HSSP-GDEQLCAICLDAPKDSFFDPCGHCATCYACGERI---KASGNAICPICRENI
RTVRRLF--VS
>Selaginella_moellendorffii_gnl|BL_ORD_ID|15488 _231449|PACid:15416766

M-----------------------------------------------------------
----------------------------------------------------------LP
WGGITMCLSGVALYFLS-RNSGRDAATLKAVRRVD-------------------------
------------------QLKDLAHLLDSACK----------AVPLVVTVAGRVG--SET
PIGCDHSSLRCV------------------------------------------ILEETA
E------------QHFLKHNDTGSWIQDSALMLS----------NNKEVPWFLE------
-DASGR----------------------------VFIVGARGAAGLELT--IASEVFEES
GRSLVRGTLDYLQGLKMLGVKRVERVLPTGTALTVVGE------AIKDDQGTLRIQRPHK
GPFYVTPKSIDQLIANLGK---WSRWYKYMSLGFTLFGVFLVASHTIRYVMEKRRRAALN
RRVMEAAA------------RRRERKEHEGKAQVGEFAKV--------ETATK-------
---RDGRLPD--LCVICLEQEYNAVFVPCGHMCCCISCSAQL---QN-----CPLCRRRI
EQIVKTY--RH
>Selaginella_moellendorffii_gnl|BL_ORD_ID|11098 _442650|PACid:15412376

MSSKR-------------------------------------------------------
----------------KRDEEKKRMDLWKAMRDSSVERLAAVIASARTEFGDQLDDLCSD
AEGVLQRL----------LREGRATGTHRKITLRE-------------------------
----------------RLLLADIEA---------------SSQQQPLLPQETSTAVPREN
CSG----NSEIV-------------------------PAATAADAPPVIQAVLTLVRPAS
T------------TEIQQQSNPEVAGGEGASLAAQPLSGNQNTTSGRRLLSALLWEERNL
DGPDQGLTEGW-----------------------VAFGVTAPIH----------------
--------------------FDHSRSQSVASELNRVGFHRPSASLDAPPEAAAAAAAAAA
AAAAPTRSLSSFMTSTPSSRDASTATVPETPMRVSLMSLL--------------------
-REAEEGGSGIIFMNRQMIDRNSGGGGGGGAGGVAFESPA--------KEATGLTGGGGS
NVVTGDGITMEQTCCVCMGRQKGAAFIPCGHTFCRRCCKELQ---QARGS--CPLCNKEI
SDVLNLY----
>Selaginella_moellendorffii_gnl|BL_ORD_ID|17002 _437462|PACid:15418280

MSSSSGIACSCDAIPGEKSKGKWKLGENGTRLRKRDDRSRELEDRSGGGEAGGISRGVDG
VSWCQYRESSDWGEYTEAQLENLVLESIKVTIETGVRKLVAMGYSTEEATDAIVT-----
-SGNYVRFSATIEIAEGHLKKGGGGGGRKKVPAGEFTVEEFERLALAKMIGAVRSDRPSL
SRPDALWCLLVSDLDVVAAIKDLESIDNALSSSSSYP-----ASPHLSSTPQRPTCDFSS
DDEDELDMNEELRTECLSACTELSLALTADPKYLKLKPVTSESDIPRGIDVVNRLFESLD
SKSKAIKELEEKVTDLDRQLEERTEWARAKVLQAAQRLSKDINELKK-----LRAEREEA
FRASESNTKKYLELESSFQKLTSQLDQAKVGFQKVEAVNAELRAELEATKLSASESFESS
VKAS----------------KQERKLLKTAQNWEKQRA------KLQEELSTERRKLSKL
QEQMAQTKEIQHQAEDRSR--QDKKAKDEALFRLEAEKLA--------------------
-REKAEAA---AKQRVERIQRKSEADLRAHRDEIHKLEQEVCKLKFGASELSLLDLSEQD
AMPMAWGVRRDRECVMCLCEEISVVFLPCAHQVVCVKCNDLH---ERKGMAECPSCRTRI
QQRVRVYNGAN
>Thellungiella_halophila_gnl|BL_ORD_ID|4555 _Thhalv10011564m|PACid:20184051

MSSPDRAIFNLLTDIALSFDGAFLGVTLAYGAIRSAFKYASSSAALSKIKDAPEVSVSDR
RSLIPASEDQSENRDHGNSHDQRIVVVRGTVRPKFTGDGSHK-DNVLISQETGDKALIIQ
RTQTYTYSGWKTLFQLSNTHRFLFERSMMPKQETALTRMVPFVIVEKNQRSQSSFLLVNM
DGARQPLPLT-TVYNRL-----QPINSTPFAFLQVLFFPEYPVGLLDVENILPPGRDLTA
VGVCSLNN-GVPEIKSCQDLPFFLSEMTKDKMILDLMHTTRVTFWAGVVMGCLSAGILGL
VAV-RTWKRWKLRYHQREPL-------QRPDE------PVVDDETEDADEIPDGQLCVIC
VTRRRIPAFIPCGHVVCCRQCALTVERALNPKCPVCLQSIRGSMRVYYS
>Thellungiella_halophila_gnl|BL_ORD_ID|8270 _Thhalv10008098m|PACid:20187795

M-IPWGGVTCCLS------AAALYLLGRSSGRDAEVLKTVTRVSQLKELAQLLEL---DS
SKLLPF-----------------IVAVSGRVGS----------ETPIKCEHSGIRGVIVE
ETAE------QHFLKHNETGSWVQDSALM----LSMSKEVPWFLDDGTSR-------VNV
VGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKM----LGVKRIERVLPTGMPLTI
VGEAVKDDIGDLRIQKPERGPFYVSPKSLDQLISNLGKWSRWYKYASMGLTVFGVFLITK
HVIDSVLERRRRRELQKRVLDAAAKRAERESEGSNGTHESVSDSTKKEDAVPD--LCVIC
LEQEYNAVFVPCGHMCCCTACSCHLT-----SCPLCRRRIDQVVKTYRH
>Volvox_carteri_gnl|BL_ORD_ID|2238 _Vocar20008962m|PACid:23126102

MGEPGRL--------APGTKKTSDQGNLFPWFLTFCCVAIAAQPVFALRGLHSFSSGRAD
ALEKSTGQDYRVELCE----CEPAAGVP-HGLGCERDGWFISNFEYQGAWMGRDGLVPL-
--SRAICCRPCLPGELPRPARVGNGTARPVAVVAMGCH---------------PSTGKQF
RALTCELAGSSFVTAP----------RTPGRPQHPQAALMAVGPRGGKETSTAAEILVAA
AH-----------ERRTAVLASEWRKILAPPLAAAAVIVVVVMVMVMVMVVVVLAVHPTD
MYTPSYAGAHACTGFSQAERARSS------MYDEYYPVGQVECCTPAVLLSSGEFWSLKR
CDCSSSATKDCGGSDTDRLLWGFSQWRV--------TAGGEYIPVAPLECCGVCLGGKMP
DHANCADLDYCSNNGICTLGACDCFEGFRGADCSQRVDGDDGGSSMPWWGSVLIVAGSVV
FISFSSIAM---------RFTFQTIRGMHGGVGGSGGGTGAGGGGGGGG-----------
------GGGLRQQGAVLRRATSAYVVSGGEVDSSRGSRQQRLSWQRLFINRNFGAGGAGR
SAANTQARPLLLAAFGDEGSAGSHDTDEQDLTGFGEDDSCARAAGGGLYGTQSVHSYTSL
HQYQQQQQQDRSNHSR----RRSGSSRPSVGHQRPDVLVPAQEGGGGGGGGGLAAMSPVM
SSFSTSEAIIFQMDDVMTLLPPR-------------------------------------
------QSTAAATAVAVAGPGTTTTTTTAVVVPAAVAAVAAPARNPEPISGQPEAEQEAL
LVGDPGDNVNICRVQRGGPQRQHTEYCRAAAAAAALDGRTPAAEVVTAAGRFELA-----
---------------------------------------LPPPAAPSPQNQPSD---AVA
AAAAGQRQAGSHVYGSGGGGSGSGGGSDLVCCGSGLGRSASGSLTLAAA-----------
---------VA-------------AAAAAVPVPIGLDVTAW----GSLPGTSVHTHTHHH
THTPTQTLPKQPTLAQFLPSPHQLLLSLPMVRQPQQLQGTAGDSAAAAA-----------
-AAAPAATASTA--AAAAAPSLSSSSPSQGGVLVSVSHSRSHAFSLQTGWLDEQLTAERE
PPAGYDGSELQQAWSMDGGSSACAPLGLDPHDALPDSVSRVHSRTQLMDFHLTYPGGLPG
CSDGGGDGSI-----AAAATAAEGGDSQACGSGGGGGGGHGIYP------SQEWSQPP--
----------SEVHGSGSRAHGGRAASVAAGSQCYHLYGTAADPYEQWLHLDRRLQLQQQ
LQAVLHPVTGAAGRPQTR--SSSAVGAPEDAAAAAAAGGPVSAVAGYDDFYYHHGQQPRH
THHH-PHPRQQHHHDTHHDT-------TAVATTTVAA------AAGDIDNN-----NDND
DDDDGGGGGGGGDGV--------GGVGAAGLLSREPPQAHTYLDAGSETAVSAASVP---
--------SGAGGASVANCH-QDLVSSDYGSET-----AAQERGDTSGTQGGGGAAGTTA
SVGAAGGGPQP-----GMEAEAAGAAAAAAAIASSS------------------------
-------GGGGGGGGSSANGFAGATCSICMEKPIQVALV--PCGHANVCRRCSRRL----
Q-RCPFCRKEILRRQRLF----------------------YSS
>Volvox_carteri_gnl|BL_ORD_ID|14611 _Vocar20000105m|PACid:23138506

MA------------------------------SNYFPVGLLDQPW---------------
------------------------------------------------------------
------------------------------------------------------------
----------------GEDDSLGTLSSLERRQR---------------------------
------------------------------KAAEKSDINAFYKFLGIVFVTLTLLLLGSE
LYTVATEPSRGLTGAFFLEIGRMSGVAYGQLQNLYKAVGDVAWTGIAVV--YGHDFAQRG
VSITDGAAQLLANG-LYYLALALSVLIM--------YYAHPAVVCAPLR-----------
------TAALSTLTAGGLFGAPTLYAWLVSRLCKTR-------SPEPVVLWALLFAGMMC
FASLSVVR----------------------------------------------------
--------------TVGIRPGDAPHHAPGVASLSRHRSSAALRCQRPMTASAASAMGSGG
AAGNAAS----------TGSSGHRRSAQSRTTSVGRN--------GGGSGSGSIAAAAAM
ARGDAMQPPSMARSGS-----------------------SASLTVSGGLLAAFSCLSGAS
TPGSTA------------------------------------------------------
-DPVGMQASVRAVHRTTGSSGVSGSRSTADLTPAPHASGG-----------VPPNPTSSM
VTKRGAAAA---------------------AAAAAQRGTTGGGAAAT-------------
---------------------------------------GPFSSSSSSSFAP---SASAA
AAVDGRDRPTGHAYGLPACFDPVGVSSSKLAGSSAPPRSSGTRRAMSAVLG---------
------------------------GTAAAVA----------GFGSGSSSNSSCSASAAAK
LNTSNSSSSSKYVIVQPPPP-------PPPRKSHVQIADSSVAAPAAAATA---------
---TPASGAQPAGGGGAAAAATAAVTSSQSSVSRNPWLNPNPAIKLAVGLPKGLKSA---
PAAGRQSQSMPMSVHHPAAAAAAAA--------------------------AEAPAGAAR
SSGGGGAAAMHSLVASSARSISYGGSAAATASATA--GVTSAYPSIVDSDSHAYARPPIF
GNTAAATATTAAPHLSSEPVATAAVAAVAAAPVLGV-------PASVFLQPHTQEQLRNH
FQSN-SATTGPDSFISTTFISSDASVGPLVAHKHASGDLDIANVAANYHPYPSAVTTPRN
EFSTVPILRAAESESTDSFSLFSTPPPPLITSEAAAA------AAASIDPAVGLMPADAE
PAPRGVSTGAAGHVLYGSYGMYGGHYTALPSLGGDPVWSH--------NVPSVFGVP---
--------PGLKG-----------------ARAAATAAMAPPPGFPSHAYGGVFAAGP--
-VSGGGD---------GWEQSAAAAAAVVATTASSTLSAALPLPPAGKNDVLASLGFVDD
GADAAADGASGGGGGSSED--AGASCAICWSEPRQVGFLHGKTSHLCVCRRCAAKLREGV
H-RCPMCRQLIERIIDIY-------------------------
>Volvox_carteri_gnl|BL_ORD_ID|6686 _Vocar20001221m|PACid:23130564

MSGNGRQPLLQRLHDAPATAQVAQQAGMAQAAAGLPGNAVGEQPQ---------------
----------------MLPDVTLAVSVPMYGLAADLAGLGPSQPADPG-----DNLLPVR
PPARLGTARPNRPAQPPRVPGVRVARGANTGGVAQAAENPFTLMEGQAQQPFPGPDGEAQ
YGLALELLNNQELGFPGPDQSVEHRTRRAGRPRGNRIARLGTSNRTDAVAASQPPPLDPF
TVKEMAASQPGLPEPDYGIVAELRNRELPNPLASD----------------FGLAAEVAR
RRSRSPSPLSRTAGVLPPLRSRRR------LDPVMPPPGSEGGVGYGLADEVAARQQQDA
ADMAEPFGAAARAGELDPFALAHEQLKVPRELLEPYEATQQEIPGEDVR-----------
-----LKTSGDTVAEPTALGSEKEHYGIAQELGADKAIETRQGREAP---------GAVL
PGQTSAVEYAEQPDPPGHKYTYDEDTGML--------VTTAGGQGEGGRVARQYIEDEVT
GIFFKLQSKRRKLFGLLRRKPHAIVEDDEEDDKGFRGR---LRRTLLFL-----------
-------------------------TNACNVLGMFAQGLLAGFALLNFFMTYMLYSSSDM
RKFLSYYAPLAQNNNRIYYALITLSVIFSTSRLAQDKLRDFEPRRLQLGPVDVIQMLMYV
GAYVAS-VLCTPLDDELTYESNRNPRFYELTWTSAFKRRVSLWHALNIIRSVLVGLAWLL
LIRAHMAVVAQAVPNDVAGPKIIAKTSS-----------------------QPPHDTGPS
CVGGDAEDCKVSQVKVNSIKDL--------AASTTLGFEKPKVESSVVSSTLQPADCSES
ENSWAVVNQGVTSGTGAGATIELSSEDADNEYVDAPPSDAGVPAAGAPPGAPADVPNAPA
PAAGGVPPAAGFVDGAAPPLG--NGGGPVVANGDGGGDQGGGGGGGAAASDDDDDDDDVE
NFMARAYELFL-------------SANPTVP-------------------EACSAQEAAA
LAAATISGATGDAAMSDSPST----VVPAPAAASTLIASAPAAAPAAAAVIKAGGFFEST
INLVPNEPSPPAAGTFASARSPAAAVATAAG-----------MDSGSAGLSSSV------
PAGGKKSQAAA------AAAAAPVP--------------------------AKEPTTAAD
DDKEKGKACREIAEEEAKRKAAEQLANELI----------MAEEAEKAKKEKANKKKSEK
KKAAKAAKKAGAAGAAGEEASAAAVSAAPTAP-----------PPGPFINP---------
------------------------------------------------------------
--------------------------ALALVNPALAA------AAGRLG-----------
-----------------------GSAPTAVPVARPTM-----------GVAPVRAFP---
--------AGARGVRCGSSQWRGLLSHSSSSRIRSMLRSQLLSGNRRRVPGGVQFAAA--
PVATGGTRPTNAMAAAFMQYRSTTVTAS---------AAAAPIPAA--------------
---PAVTVQAATFASKYDD--DEHLCVVCMENTRSILLM--PCGHLVLCGTCLPAIEAKG
N-LCPICRESIQDAQLMA----------------------Q--
>Volvox_carteri_gnl|BL_ORD_ID|15021 _Vocar20007914m|PACid:23138916

MG----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----SSQSNERPRRQA--------------------------------------------
------------------------------------------------------------
---------------------------------------------------PPPVPTT--
------------------------------------------------------------
-----------------------------------------VPPTYTTQVYP---PPPVF
LTAPG-------------------------------------------------------
-----------QYPPPPTSQQQYYGGTMPIP-----------------------------
-------QPYRPPMMQ--------------------------------------------
---VPMSQPAFAPHQYGQPPRPVPTQECQTA-----------TIRNQVNL----------
-----KKQTLALEATSQPGIYAIT------------------------------------
-----------------------------------------------------------F
QFDASAPCRVTTFVCAHEDSRRACKITSPL-------------PPAPAVSY---------
------------------------------------------------------------
--------------------------PQGLNHKFPSA------PSGLASGHVVNTI----
-----------------------SGRISARDL----------------TSASNDTFPVII
RLEALGEEAAAEGRSLGSLELGCELPHWVQSQTTYAKLVKEDD--------GSWGLRVIK
QKIWVKGTPYELQEIYGMEQNKAGGNAA--------------------------------
-------------AGDGYDDLDGNECVICMSAARDTTAL--PCRHMCMCHSCASALKAQT
N-KCPICRNEIESLLHIKINKSAATAAAAAGQGAAAASSGASA
>Vitis_vinifera_gnl|BL_ORD_ID|10490 _GSVIVT01016752001|PACid:17827115

MSAHDQAAAAILAQVALAADGAILGLALAYVAVRSFIRLSSTSSALRQIDQSPSFRVSDL
RSLLSPSSDDES---D----QSTSSDGLLVVVRGTVEAKSAIDGNWKSLRPNVLVSHESG
EKGVILQRT-----QTCIYNEW------RGFFGWTSDIRTLFARSWKEKESTSLRTVPFI
LV--------------EGGRWPQSDYVIVNMDGSRHPLPLTTVYHQLQPVNASPYTFLQA
LFGHDYPVGLLDEEKLLPLGKE---------------------------ITAVG-ICSLK
NGIPEIKSCKDLPYFLSEMSKDQMV--------------------VDLVFKSKVLFWSG-
VILGSVSIGVLGYAVVRNWNRWK-----------------------EWRQQRGV-RPPS-
--QAVTDDTDTQIAEDDAG-----DVPDGELCVICLMRRKRSAFVPCGHLVCCQRCALSV
ERELSPKCPVCRQIIRSSVRIYGS
>Vitis_vinifera_gnl|BL_ORD_ID|6424 _GSVIVT01011070001|PACid:17823049

M-------------IPWGGISCCLSAAALYLLGRSSGRDAEALKSVTRVQQ-----LKDL
VQLL-----------D----TACKVLPLVVTVSGRVGSDTPIKCEYSGLR----------
--GVIVEET-----AEQHFLKH------NDAGSWIQDSALMLSMSKEVPWYLDDDTGRAY
IVGARGATGLVLTVGSEVFEESGRSLVRGTLD------------------------YLQG
LKM----LGVKRIERVLPTGTP---------------------------LTVVGEAIKDD
VGTIRIQRPHKGPFYVSPKSIDHLV--------------------ANLGKWARWYRYAS-
----------LGFTVFGVYLIAK----------SAIQYVMERKRCWE-LRKRVLAAASK-
--KSGQDSEDPDEKDENGSDNTKRDRLMPDLCVICLEQEYNAVFVPCGHMCCCTMCSSQL
TN-----CPLCRRRIEQVVRTFRH
>Vitis_vinifera_gnl|BL_ORD_ID|146 _GSVIVT01000174001|PACid:17816771

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------WLIPAGG----------------------------LRGIG------
-----------LKEVKRLTSMSTAIEGLGQEKL-----HFRVLTSPVQDDQIAWYYAISF
VARLVAYVSTLGLLVIFIFLILKYFGDFGSETTTFEEEVR------E-TETNPLLPSKRV
PFTYGACEEDLESGEGNGG--SSQDLYDGKICVICFDEPRNCFFVPCGHCATCYVCAQRI
AKGDNSVCPVCRRFIRKVRKFIVQ
>Vitis_vinifera_gnl|BL_ORD_ID|5191 _GSVIVT01009392001|PACid:17821816

M----------------------------------------------------------Y
RPVLAPPSRHQGWQESTARLLAPLTLWLCVTVSIRYGY-------------------YGN
CRMVLGPSSSRLMKASSLFVKQIEVKDDDKKGVLLYGFAEKPELSVETNWSVSN----YL
IVGSYGRKGFSLWLNKGSSIRVRWEAQPSSLS------------------------DLQV
FLI----KGERKYETLLPNPTNSPAAFPFHESTNGREAEYTILEDNRYYVGIINANRKSV
IMTLNVNVTSKMYDITKAKSMCSTIKGSCRLNLLFPNTQFVILTTPNNGDLAGWYIELSF
VARVVTYVSILGFVVIIIFLVLKYLGACEGDNEVHVEEITPR----EVTETHPLMPEKLF
RLTYGTGEEDAESGM-SSS--SSEDLYDGKICTICYDEPRNCFFVPCGHCATCYDCAKRI
IEGENKVCPICRRFIHKVRKLFTP
>Zea_mays_gnl|BL_ORD_ID|17801 _GRMZM2G004023_T02|PACid:20837527

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQLRLVASAATASIADA
RSLL--SGDGAE---------PRIAAVRGYVR---------AHDKFFRAPFSGEAGVVTK
HTQMCLFTEWRGIFGWTFDLHALLFRSWKEQIVTSFRSVPFVLVSTELGNPTGVVHINVD
KADQPLPLTTVFHKLIPLETTPYTLFQTIIGNGYPIALLDEEKILPIGKKITAIGLCQAK
DAESVEITSCPEIPFFLSELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRGWT
RIKLRREARHARQMFEEAEDAIHRDDSSDDDEIGDGQLCVVCLRKRRRAAFIPCGHLVCC
SECALTIERTPHPLCPMCRQDIRYMMRVYDS
