>Cyanothece_sp_PCC_7425 gi|220906503|ref|YP_002481814.1| unnamed protein product [Cyanothece sp. PCC 7425]
MG----LAIVGAILLV---TGGI-LYFVQRHYQQKLYSIKLARKTTVAELKQLADQVGAE
IGQ-GSLREYVKLSGQIKCDTP--LISELKQVPCVYYQMQVEREYEERLTERDNDGETRE
KTQRGSETIASNSQSTPFFLQDQSGA----IEVDPSGAAIETV-QVLNEFRPEA--GSAR
ISFGNFSLSVGGSFPAGRETIGYRYRESILPPDRRILIVATASDSSGILSL-QKPVEKRQ
KFIISLKSEDHLAQSTQQTATYTFYGMIACLGLGAILLVVGLI-------IR
>Acaryochloris_marina_MBIC11017 gi|158336842|ref|YP_001518016.1| unnamed protein product [Acaryochloris marina MBIC11017]
------MKIIGIILIV---IGII-LFFVYSNLKRKLASLRQARPASIAELNHLASEIALE
MGS-GSWRDYVKLRGTIQCDQP--LISELKQMPCVHYNMTVVREYEEQVTERDSDDKVVT
KTQRGSETLSQNRESVPFFLQDDTGE----IWVEPEGAQIETV-RVLDEFSPEQ-PSGGQ
LSFGGFSLSL-SSAETGRQTIGYRYQESVLPVQRQVFVVAQVSDFNQSLVL-ENPTTKGQ
RFVISLKSEEALAQTTQTSVTYAFYGMISTLVVGGLLVIFGLL-------SA
>Cyanothece_sp_PCC_7424 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece sp. PCC 7424]
------MILIGIICLI---VGVI-LLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEE
IGG-GSLREYVKIRGVIECDRP--LISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIR
EKERKSETVAQNSRSIPFTLQDSTGE----IRVNPERAEIETV-KVLEEFRPEN-FSGGS
LTFGNFSINL-PSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITI-RKPTEKGQ
RYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVL-------RG
>Synechococcus_elongatus_PCC_7942 gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococcus elongatus PCC 7942]
MA----AIILAAITAI---AAIV-LYFVRRHYRFKLQSLLLAQPATSLQLKEIAEHVAGE
IGG-GNLRQYVKMWGAIEVEQP--LVSELKQESCVYYCSTVSREYEERVRKEDSEGKVTW
TTERRSETISQNRRSTPFYLRDQHGR----VRVEPESAAIATI-PVLDEFRPDS--SASS
LIFGAFSLSL-STTAGLGKTLGYRYREEILPCDRSVLVVGAASDETGELTL-GPSSEARQ
QFFIALKPETALLQEVKQTIQWLTIGAIASVVVTVVAAIAALL---------
>Thermosynechococcus_elongatus_BP-1 gi|22298202|ref|NP_681449.1| unnamed protein product [Thermosynechococcus elongatus BP-1]
------MGVLGGILLV---IAVL-VLCGWWDYRLKVRALNLAVSSTPAQLHELQRRVAQE
IGG-GYLQEYVKISGQIVADRP--LVSELKRLPCVHYRLCVSRVYKTTESHEDGSS----
ETKYRHEILSSNTQTIPFRLRDGDME----IYVDPRGAEIETV-QVLNEFQEDN--NTTH
LAFGRFQMDL-SSLPKHSDTVGYRYEEWILPVNQQVFVVGTASDERGKLRI-RRPHQKGQ
LFFISLESEENLTKKVRQYARASIIAAGVFSGLGILLILL------------
>Thermosynechococcus_elongatus_BP-1 gi|22297743|ref|NP_680990.1| unnamed protein product [Thermosynechococcus elongatus BP-1]
------MGVFAHLCLT---GSAF-LFALEGYYRLQLRGIKVASPSTIGELEKFQQQVAQE
MGS-GSWREYVQVVGQVTTSQP--LLSEVKRIPCVYYKTIISREYEKE------------
GSDRPSEIIGRHEQSTLFLLRDHQGE----IEVNPFGAEIEAV-QVLDELRPADQPHAFA
LSLGFLSFNW---HFGKGTTLGYRYQEWVLPLGQPVSVVGMASDQGGVLRL-QKPQNRGQ
KFIISLSFEDPLIQQYKQQKRKMTYASLGATLCGVCGLVLALF---------
>Rubrobacter_xylanophilus_DSM_9941 gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941]
MVGTVVFLLVGVVLCV---AGGV-LLYFRRRMLGKAELMRRTRTSGAAGVSALSP-----
-------GTLVEVKGTLRCERP--LQSEMAKERCAYYSSKVVREYLERDR-GDGAP----
GSGRRSEVLARSERFAPFVVEDDTGG----VPVSAEGAEVDAK-KVVDRFERGAGAAGLS
VTIGGATIDL----GGGERTLGYRHTEEILPVDAPVYVLGAVRRDGGI----GPPEEGAG
RFVVSWRSEEALGESLGRGARLLGLIALGLFLAGAAFLAVGAAAALGYLQFR
>Sphaerobacter_thermophilus_DSM_20745 gi|269838375|ref|YP_003320603.1| hypothetical protein Sthe_2360 [Sphaerobacter thermophilus DSM 20745]
MGTSGVLLIIGLVAAG---IGAV-LLFIGRRIQAKTDLLAKVPTVDASEVASLIP-----
-------GEMIEVKGVIRCDTP--LTAELAQRACVYYSSRVVREYEYRRRNAKGET----
VRSRRSETVAHNEQFTPFYVEDSSGR----VLVDPEGAEVDAQ-KLVDRFERNPGALGPT
ISLGGISLNL----GGDDGTIGYRYQEHVLPVDIPVYVLGVVQE-GGTIGR-PPAALKGR
RFIISYRAEEALRESWGKKARWLGISAVALFALAVILFVVAVG-----MLVA
>Thermomicrobium_roseum_DSM_5159 gi|221632287|ref|YP_002521508.1| unnamed protein product [Thermomicrobium roseum DSM 5159]
------MIFVTLCFLITAGVGLV-CLIGYRRTRQQLRLLRLVATCPIAELHERIP-----
-------GEMVEITGTVHCATP--LRSEYTGQPCVYYRTVTERVVERHGRSKKG------
--GRLSEVVAQNEQRIAFEVDDGTGR----VAVDPVGAEIDGR-KLLDRFEPVENGEGAT
LRIAGMSVEV---RAAEWRTLGYRKIEEAVLVGYPVYVLGVLQDD-GSIGR-PPEGSRLR
EFLISARSEEELATSLRRRSYLFLAGAITSFVVAGMLLIALLV--QSVISIS
>Chloroflexus_aurantiacus_J-10-fl gi|163846705|ref|YP_001634749.1| hypothetical protein Caur_1130 [Chloroflexus aurantiacus J-10-fl]
------MIVGGVLLLV---LAVI-FFFVARANAGKLQALNAVDTYDTATLSAIHRRITTA
LGA-HDFAQPCEVMGLIECATP--LTGPVSGQALVAYLYTTHREYEERITTQES-GRSTT
RIERRSEQLEQNERRVPFTIRDDTGQ----VLVVPDGAKIDLI-ETANRFLETPQP----
-------------WTGATRTLGQRQFERGLEVGIRVFVSGTAIDQNGQVVIARHPTNSKQ
TFIISRKSEHELANSAATWARNMRYAAIASGVIGLALVVGGVL------VSG
>Chloroflexus_sp._Y-400-fl gi|222524514|ref|YP_002568985.1| hypothetical protein Chy400_1238 [Chloroflexus sp. Y-400-fl]
------MIVGGVLLLV---LAVI-FFFVARANAGKLQALNAVDTYDTATLSAIHRRITTA
LGA-HDFAQPCEVMGLIECATP--LTGPVSGQALVAYLYTTHREYEERITTQES-GRSTT
RIERRSEQLEQNERRVPFTIRDDTGQ----VLVVPDGAKIDLI-ETANRFLETPQP----
-------------WTGATRTLGQRQFERGLEVGIRVFVSGTAIDQNGQVVIARHPTNSKQ
TFIISRKSEHELANSAATWARNMRYAAIASGVIGLALVVGGVL------VSG
>Pseudonocardia_dioxanivorans_CB1190 gi|331695440|ref|YP_004331679.1| hypothetical protein Psed_1589 [Pseudonocardia dioxanivorans CB1190]
------MWVIGVVVVL---VGAG-FLWSAVRAQRSVHAMLAAETLSVPELEEL-RRVSDD
LGARGSFRKVCEVVGAAHPSPEGVLRSELSGVECVWHSHRVQRRYKHYDRDRDGST----
RVTTRTETVAEQTSGPGFALLRDGRT----IGVDHAGRRPDGVEQVTDRFEQTQEPSNGW
ADVVGALVGS-----DRDETIGYQYTEWVLRPGTPMYVLGEVHDAIGPLVI-APPADPKQ
PFVMSTSTEQQLTDAARGRQRFRSRLGAALVVVGIVVVVLAL--------VL
>Acetobacterium_woodii_DSM_1030 gi|379012200|ref|YP_005270012.1| unnamed protein product [Acetobacterium woodii DSM 1030]
M-----AIIIGLLIII---AGIFYAVYIYRKNTNKVQEIQFQQTTCIKDVLDIVGDLSSL
D---ENYRHYSEVKGQLHSVSG-NVEAPFSQRPVAYYENEVYSVHEETRTERDDKGNTRT
VTDKVETSLSSEKSPVEVYLSDSSSDEKVYIDLASFGSDVDLM-PGCNRMESKD--SDWV
RNNFNFSVNQ----NRGSRFLGYRFFEEILPEDQPMYILGEIHKRGNRLYV-GRSVAAKK
PSHVTYKSEDELLDDIKNEK-------LVAIGIGVAGVVVGIA----VMFLF
