>xbat31_At2g28840 gi|70905107|gb|AAZ14079.1| At2g28840 [Arabidopsis thaliana]
M----------------GQSMSCGSRPEHG----------------IFASVQCGDIITIR
RVMATEPSLLNQTTPYDRHSVLHVAAANGQIEIL-SLLLERFTNPDLLNRHKQTPLMLAA
MYGRISC---------------VKKLAEVGANILMFDS----VNRRTCLHYAAYYGHANC
VQAILSAAQSSPVA--------------------VHWGYARFVNIRDDKGATPLHLAARQ
RRPECVNV------------------------LLDSGSLVCASTSVYGSP------GSTP
LHLAARSGSIDCVRKLLAWGADRLQRDASGRIPYVVAMKHKHGACGALLNPSSAEPLVWP
SPLKFISELNDEAKLLL--------------------------------------EQALM
EA----------------------------------------------------------
-NREREKTILKGT-----------------------AYSLPSPSFSDTDDNMSEVSDTEL
CCICFEQVCTIEVKDCGHQM-CAQCTLALCCHNKPNPTTSTVTPPV--CPFCRSTIACLV
VAQNNNNNNEKSKSLDDVVVVDREA-----------------------------------
-----------------------------------------G--DVSSSKFRKHRRSINL
GEESSSFMGLSTIGSFGRITGRGSGRIAAENELMDKPIL
>xbat32_At5g57740 gi|45773910|gb|AAS76759.1| At5g57740 [Arabidopsis thaliana]
M----------RFLSLVGNSFGCSASGER-----------------LVSAARDGDLQEAK
ALLDYNPRLARYSTFGVRNSPLHYSAAQGHHEIV-SLLVESGVDINLRNYRGQTALMQAC
QHGHWEV---------------VLILILFGANIHRSDY----LNGGTALHLAALNGHPRC
IRILLSEYIP-----SVPNCWSLLKNKKTSVAGFDSSVLHEVINRAADGGITPLHVAALN
GHIETVQL------------------------LLDLGASVTQVTVEDGTTIDLIGAGSTA
LHYASCGGNTQCCQLLISKGACLAAVNSNGWTPMMVARSWHRNWLEEILNPTTEQPQL--
----HLPNVP-SPFLCL------PLMSIVNIAQEC-------------------------
------------------------------------------------------------
----------------------------------------------GWRENDCLTPCRDP
CAVCLERKCTVAADGCAHEF-CTNCALYLSTTSITSSKTSNVTPGSVPCPLCRNGIVSFT
KLPHTTATTRTSTSSRTSISLSFCT-CSSDVLDTALLTNPHYSCKPVVSRTGSRTPQSAR
SSAFRSLSCRRFPPSLCLGGSDVDEPRSRLIGGSYSRSGVGF--RRSTSQVEGKRSWFSA
LNHCVTTG-----GSAC----------------------
>xbat33_At5g07270 gi|70905089|gb|AAZ14070.1| At5g07270 [Arabidopsis thaliana]
M----------------GNSFGCSASGER-----------------LVSAARDGDFVEAK
MLLDCNPCLAKYSTFGGLNSPLHFAAAKGHNEIV-GLLLENGADVNSRNYCGQTALMQAC
RYGHWEV---------------VQTLLLFRCNVTRADY----LAGRTALHFAAVNGHARC
IRLVLADFLPSDKLNSLPETGVVTAKNKS-----EQSALSKFVNKAADGGITALHMAALN
GLFDCVQL------------------------LLDLEANVSAVTFHYGTSMDMIGAGSTP
LHYAACGGNLKCCQILLARGARKMTLNCNGWLPIDIARMWSRHWLEPLLSPNSDV-----
----VIPAFPHSNYLSL------PLLSILNIAREF-------------------------
------------------------------------------------------------
-----------------------------------------------GLQSATIGDEVDI
CAVCLERTCTVAAEGCEHQL-CVRCALYLCSSSNVPSVTVG-PPGSIPCPLCRHGITAFK
RLP-----SSLTREMKLPMSLGFCAPCMLHTGDTTDQSSP--TCPPTEQRSSKTRAASVS
SDIFCPVTCSPFP--------SVNIPMCTCNEGTCPNFETHGTERHSEEHVESSPSRTTT
EQEKIEEGQRLGKTTTCSSMFWGRRSCSRENQCNSEINA
>xbat34_At4g14365 gi|70905081|gb|AAZ14066.1| At4g14365 [Arabidopsis thaliana]
MGQQQSQSKDEMLFQEVSNNNVEGIKSLHHEGAGLEGVDKLGRTPLILACTNDDLYDVAK
TLLELGSNVNAYRSGCNGGTPLHHAAKRGLVHTV-KLLLSHGANPLVLDDDVKTALEVAR
DEGYSNV------------------VRAIESHICLFSGCMREYSGSSLLNLFAPQLLSRK
VWVVVVPTGSRNPTKPLKLELVLYDS----------------IQDAQPRMVIPLWKANLE
E-----------------------------PKSFRCDDSVMIIDDSRSP-KSMRQRRESG
FISQARR-----------------------------------------------------
-----WAQVDRQIRLKLAAEIKGDMKQMNWFSEACKGVPQPMNPPRF-------------
------MKTSQATT----------------------------------------------
-TTTNVPALSDDALTRV-------------------AMSLP-SPKTANKED-------GL
CVICVDAPSEAVCVPCGHVAGCISCLKEIENKKMG-------------CPVCRANIDQVI
KLY--HV-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
>xbat35_At3g23280 gi|70905085|gb|AAZ14068.1| At3g23280 [Arabidopsis thaliana]
MGQQ--QSKGELLYQQVSYGNSEGIRALHRDGGDLEWMDREGKTPLILACMNSELFDVAK
TLIELGSNVNAYRPGRHAGTPLHHAAKRGLENTV-KLLLSHGANPLVLNDDCQTPLEVAR
VKGFSNV------------------VRAIEKHICLFSGWMREFYGPTFLDLFAPQLLSRR
VWVVIVPTGSRNPTKPFKLELVVYAS----------------LQDAQPRTVMPLWKANLE
E-----------------------------PKAKQSDTSVMIVDNSTIPSRRMKKRRVCA
--SHGRR-----------------------------------------------------
-----RPQVVRQTRLKFAPSTEGDSQQLKWFCDACKGIPQPMHPPVFLQAPPSAPPPPSE
DGLAMGMNASLHTTMSDPSNLNHHSIGQASSSSGPSSSTAPPSGKASAFGFNSHGIGIVL
ESSPSAPPLTDDDIATVDDGPIHYPSIDSTPVDLPSAASLPASTEGERKED----GNTGT
CAICLDAPSEAVCVPCGHVAGCMSCLKEIKSKNWG-------------CPVCRAKIDQVI
KLY--RV-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
>SP1_NM_105064
M----------------------------------------------------IPWGGVT
CCLSAAALYLLGRSSGRDAEVLETVTRVNQLKEL-AQLLELDSKILPF---------IVA
VSGRVGS--ETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALML----------
-----------SMSKEVPWFL---------------DDGTSRVHVMGARGATGFALTVGS
EVFEESGR-SLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDI-----GEFR
IQKPDRG-------------------------PFYVSSKSL-----------DQL-----
-----ISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLER------RRRRQLQ-KRVL
DA----------------------------------------------------------
-AAKRAELESEGS-----------------------NGTRESISDSTKKED----AVPDL
CVICLEQEYNAVFVPCGHMCCCTACSSHLTS-----------------CPLCRRRIDLAV
KTY--RH-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
>SPL1_NP_564745_AT1G59560
M----------------------------------------------------IHLAGFT
CCLGGVALYLLTRSTGRD---IKSITRVYQLKDL-EQLVEVESKVVPL---------IIA
VSGDVGS--ETPIKCEHSYVLGVFLKRTAEQQVLRRNWRFSWVRNSTLMQ----------
-----------PMTKEVPWYL---------------DDGTGRVNVDVSQGELGLALTVGS
DVFEKAEPVSLVQGALGYLKGFKILGVRHVERVVPIGTPLTVVGEAVRDGM-----GNVR
IQKPEQG-------------------------PFYVTYIPL-----------DQL-----
-----ISKLGDLSRRFKYASMGLTVLGVILISKPVIEYILKRIEDTLERRRRQFALKRVV
DA----------------------------------------------------------
-AARRAKPVTGG---------------------------------GTSRDG----DTPDL
CVVCLDQKYNTAFVECGHMCCCTPCSLQLRT-----------------CPLCRERIQQVL
KIY--RH-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Mulan_NP_078820
MESGGRPSLCQF-------------------------------------------ILLGT
TSVVTAALYSVYRQKARVSQELKGAKKVHLGEDLKSILSEAPGKCVPY----------AV
IEGAVRSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTTHLWNDCSKIIH---------
-----------QRTNTVPFDLVPHEDGVDVA-----------VRVLKPLDSVDLGLETVY
EKFHPSIQ-SFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDN------NSVR
LQPPKQG------------------------MQYYLSSQDF-----------DSL-----
-----LQRQESSVRLWKVLALVFGFATCATLFFILRKQ--------YLQRQERLRLKQMQ
EE----------------------------------------------------------
-FQEHEAQLLSRA--------------------------------KPEDRE----SLKSA
CVVCLSSFKSCVFLECGHVCSCTECYRALPEPKK--------------CPICRQAITRVI
PLY--NS-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
>SPL2_NP_564653
MSSPERALLNLLT---------------------------------DIALSFDGAILGLT
LAVSAVGSALKYASTNAALKKIKDAPEVSISDLR-SLLPASEDKSETNDNRKSNDQRIVV
VRGVVKP--KISGDEGYKNNNVLISPETGDKALIIQRTQTYVYSGWKRLFQSTGHRFMLE
RSLRKHGA---DFTRTVPFVIV----------GKDQQSNSSFVAVNMDGSRQPLPLTTVY
NRLQPINS----SFLQAFLYPDYPVGLLDIEKILPPGKDITAVGIYSFNN------GVPE
IKSCQDL-------------------------PYFLSEMTK-----------DKM-----
-----IEDLMEQTNFIFLGSVILGIVSVGILSYAAVRTWNKWKQWNHQRELPQRPNDSVV
DD----------------------------------------------------------
-----------------------------------------------EPEDADEIPDGEL
CVICVSRRRVPAFIPCGHVVCCRRCASTVERELNPK------------CPVCLQSIRGSM
RVY--YS-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
>gnl_BL_ORD_ID_9028_Arabidopsis_thaliana_AT4G24204.3_PACid_19646975
M-----------------------------------------------------------
-------------------------FDATISKCL-QLLY---------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MFFRKLNS
IKLPSDN---------------------------------------------DEFVRW--
-----YLGLSFSARVVIYITVLGTIMTITYLVLKFLSECD------MEDDTQRLPLVAEE
EV----------------------------------------------------------
-TTDWTPPLINESLEVT------------------GKGDVETASFSSSDDV----DYSTL
CVICFEERRNCFFVPCGHSATCRGCAQRILSEESKV------------CPICRRVIRKSK
RLVLKKL-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
>gnl_BL_ORD_ID_1107_Arabidopsis_thaliana_AT2G38195.2_PACid_19639054
MSKENEES--------------------------------------------EANLYSAK
ELDFSKPGLQLY-GFNGQSTPSGYFVNWTESRVL-SVSQNS-------------------
------------------------------------------YKGWPYYLNRGTHMNISY
NILPKGSAVRLVITEGMPFF---YRSSLKDIAFRDTAWSWNLIQ---GSGMIQLDISKSK
GYYLTVAN----------------LKRKDVEVELDIDVKVVLYDTKQSSYNCSFSNGECS
FKMNERS-------------------------PVENYAVVTSPALGQGVSIDDEW-----
-----YIELSYQPRLIAYGSFTGVLLSFMLVAIHFCNKLKCCGGEGFLSEDDSVRTCLLA
DK----------------------------------------------------------
------------------------------------------GDNDCCNDV--EASNKSL
CAICFDAPRDCCFLPCGHCVSCYQCGTKIKRTKGR-------------CPICRKKIMHVK
RIY--TA-----------------------------------------------------
------------------------------------------------------------
---------------------------------------
