>SP1_RNF
CVICLEQEYNAVFVPCGHMCCCTACSSHL-----TSCPLC
>SPL1_RNF
CVVCLDQKYNTAFVECGHMCCCTPCSLQL-----RTCPLC
>Mulan_RNF
CVVCLSSFKSCVFLECGHVCSCTECYRALPEP--KKCPIC
>SPL2_RNF
CVICVSRRRVPAFIPCGHVVCCRRCASTVERELNPKCPVC
