>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>SPL1_NP_564745_AT1G59560
mihlagftcclggvalylltrstgrdiksitrvyqlkdleqlveveskvvpliiavsgdvgsetpikcehsyvlgvflkrtaeqqvlrrnwrfswvrnstlmqpmtkevpwylddgtgrvnvdvsqgelglaltvgsdvfekaepvslvqgalgylkgfkilgvrhvervvpigtpltvvgeavrdgmgnvriqkpeqgpfyvtyipldqlisklgdlsrrfkyasmgltvlgviliskpvieyilkriedtlerrrrqfalkrvvdaaarrakpvtgggtsrdgdtpdlcvvcldqkyntafvecghmccctpcslqlrtcplcreriqqvlkiyrh
>SPL2_NP_564653
mssperallnlltdialsfdgailgltlavsavgsalkyastnaalkkikdapevsisdlrsllpasedksetndnrksndqrivvvrgvvkpkisgdegyknnnvlispetgdkaliiqrtqtyvysgwkrlfqstghrfmlerslrkhgadftrtvpfvivgkdqqsnssfvavnmdgsrqplplttvynrlqpinssflqaflypdypvglldiekilppgkditavgiysfnngvpeikscqdlpyflsemtkdkmiedlmeqtnfiflgsvilgivsvgilsyaavrtwnkwkqwnhqrelpqrpndsvvddepedadeipdgelcvicvsrrrvpafipcghvvccrrcastverelnpkcpvclqsirgsmrvyys
>Mulan_NP_078820
mesggrpslcqfillgttsvvtaalysvyrqkarvsqelkgakkvhlgedlksilseapgkcvpyaviegavrsvketlnsqfvenckgviqrltlqehkmvwnrtthlwndcskiihqrtntvpfdlvphedgvdvavrvlkpldsvdlgletvyekfhpsiqsftdvighyisgerpkgiqeteemlkvgatltgvgelvldnnsvrlqppkqgmqyylssqdfdsllqrqessvrlwkvlalvfgfatcatlffilrkqylqrqerlrlkqmqeefqeheaqllsrakpedreslksacvvclssfkscvflecghvcsctecyralpepkkcpicrqaitrviplyns
