>SP1_NM_105064
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>T.parvula tpSP1 protein
MIHWGGVSCCVSAAALYLLGRSSGRDAEVLKTVTRVNQLKELAQLLELDSSKLLPFIVAVSGRVGSETPIKCEHSGIRGV
IVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVVGARGATGFALTVGSEVFEESGRSLVRGTLDYLQ
GLKMLGVKRIERVLPTGMPLTIVGEAVKDDIGDFRIQKPDRGPFYVSPKSLDQLISNLGKWSRWYKYASMGLTVFGVFLI
TKHVIDRVLERRRRRELQKRVLDAAAKRAELESEGSNGAHESVSDSTKKEGSVPDLCVICLEQEYNAVFVPCGHMCCCTT
CSSHLTSCPLCRRRIDQVVKTYRH
>T.salsuginea (halophila) Thhalv10008106m|PACid:20187792
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLKTVTRVSQLKELAQLLELDSSKLLPFIVAV
SGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDG
TSRVNVVGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGMPL
TIVGEAVKDDIGDLRIQKPERGPFYVSPKSLDQLISNLGKWSRWYKYASMGLTVFGVFLI
TKHVIDSVLERRRRRELQKRVLDAAAKRAERESEGSNGTHESVSDSTKKEDAVPDLCVIC
LEQEYNAVFVPCGHMCCCTACSCHLTSCPLCRRRIDQVVKTYRH

>SPL1_NP_564745_AT1G59560
mihlagftcclggvalylltrstgrdiksitrvyqlkdleqlveveskvvpliiavsgdvgsetpikcehsyvlgvflkrtaeqqvlrrnwrfswvrnstlmqpmtkevpwylddgtgrvnvdvsqgelglaltvgsdvfekaepvslvqgalgylkgfkilgvrhvervvpigtpltvvgeavrdgmgnvriqkpeqgpfyvtyipldqlisklgdlsrrfkyasmgltvlgviliskpvieyilkriedtlerrrrqfalkrvvdaaarrakpvtgggtsrdgdtpdlcvvcldqkyntafvecghmccctpcslqlrtcplcreriqqvlkiyrh
>SPL2_NP_564653
mssperallnlltdialsfdgailgltlavsavgsalkyastnaalkkikdapevsisdlrsllpasedksetndnrksndqrivvvrgvvkpkisgdegyknnnvlispetgdkaliiqrtqtyvysgwkrlfqstghrfmlerslrkhgadftrtvpfvivgkdqqsnssfvavnmdgsrqplplttvynrlqpinssflqaflypdypvglldiekilppgkditavgiysfnngvpeikscqdlpyflsemtkdkmiedlmeqtnfiflgsvilgivsvgilsyaavrtwnkwkqwnhqrelpqrpndsvvddepedadeipdgelcvicvsrrrvpafipcghvvccrrcastverelnpkcpvclqsirgsmrvyys
>Mulan_NP_078820
mesggrpslcqfillgttsvvtaalysvyrqkarvsqelkgakkvhlgedlksilseapgkcvpyaviegavrsvketlnsqfvenckgviqrltlqehkmvwnrtthlwndcskiihqrtntvpfdlvphedgvdvavrvlkpldsvdlgletvyekfhpsiqsftdvighyisgerpkgiqeteemlkvgatltgvgelvldnnsvrlqppkqgmqyylssqdfdsllqrqessvrlwkvlalvfgfatcatlffilrkqylqrqerlrlkqmqeefqeheaqllsrakpedreslksacvvclssfkscvflecghvcsctecyralpepkkcpicrqaitrviplyns
