>gi|145362603|ref|NM_203003.2| Arabidopsis thaliana translocase of chloroplast 34 (TOC34) mRNA, complete cds
ggagacaacggcaaatgaagatggattttaagggtttttgttcttagtaaaaaaaagtta
tcttctttttaattttctgagactttaattgctagaaagttataggattgattcagatag
tggaatcagacaactttttcttttatgggcgattactcatttttgttctttggtcttctg
attgtttagtttcttagcagatgatttagtcttctcttttgtgatccttttttgctttcc
ttggaagtgtaggtaaggatttgtgtccatggcagctttgcaaacgcttcgtgaatggat
cggtatccagcagttcccacctgctactcaatctaaattgctcgagatccttgggaagta
taaagaagaggatgtgagctcgctaacggtccttgtaatggggaaaggtggtgttggaaa
gtcatcaactgtgaattcagttataggcgagaaagctgctgcagttagtactttccagtc
tgaaggactgaggcctaccttggtctctcgcacaagatcgggatttacattgaatatcat
cgacactcctggtcttattgagggaggatatgtgaatgatcaagccatcaacattataaa
acgatttctcctcaacatgactatagatgtgctactatacgtagaccgtttggatgtgta
ccgggtggatgaccttgataggcaagttgtcggtgctataactgatgcatttggtaaaga
gatatggaagaagtctgctcttgttctcacccatgctcagttctctccaccagacgggtt
aaattataaccactttgtctccaaaagatctaatgctcttctaaaagttatccagacagg
cgctcaactgaagaaacaggatttgcagggtttttctattcctgtcattcttgttgagaa
cagcggaagatgccataagaacgaaagcgatgaaaagattcttccatgcgggactagttg
gattcccaatctgttcaacaaaatcacagagatctcttttaatggcaacaaggcgattca
tgttgacaagaaactggtcgaagggccaaacccaaacgaaagaggaaaaaaactgattcc
tttaatgtttgcattccaatacttgctggtgatgaagccattggttcgagcaatcaagtc
cgatgtttcgagagagagtaaaccggcgtgggagctgcgagactccggtttagcaagtcg
aaggtcttgagttgtggacacgagttttgtttggtttgtttgtctatctgagagattgtt
ctgtagttgaaattgtgatacaactcgagaaatgtggttcacagataattactgtcgcaa
agttctctcatcttaattacatcttctttagcctctcgt
>Thhalv10014156m|PACid:20203668
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------atggcagcgtttcaaatgtctcgtgaatggat
aggtatccagcagttcccacctgctactcaaactaaattgctcgaaatccttgggaagta
taaagaagaggatgtgagctcgctaacagtacttgtaatggggaaaggtggtgttggaaa
gtcatccactgtgaattcggttataggcgagaaagctgctgcagttagtactttccagtc
tgaaggactaaggccgtccttggtctcccgctcaaggtcggggtttacattaaacatcat
cgacactcctggtcttattgaaggaggatatgtgaatgatcaagccgtcaaccttataaa
aggatttctcctcaataagactatagatgtgctattatacgtagaccgtttggatgtata
tcgggtggatgacttggataggcaggttgtcacggctataaccgatgcatttggtaaaga
gatatggaagaagtctgcccttgtcctcagtcatgctcagttctctccaccggacggatt
aaattatgatctctttgtctccagaagatccgatgctcttcttaaagtgatctgtgcagg
cgctcaactgaagaaacaggatttgcagggttcatctattcccgtcattcttgttgagaa
tagcggaagatgtcacaagaatgaaagcgatgaaaagattcttccagacgggactagttg
gattccaaattttgtgaagacaatcacagagatctcctttaatggcaacaagccgattca
cgttgacaagaagctggtcgaagggccaaacccaaacgaaaaaggaaaacgactaattcc
tttaatcgttgcattccaatatctgttactcatgaagccattggttcgagcaatcaagtc
ggatgttgctagagagagtaaacaggcgtgggagatgcgggactcaggtttagcaagtcg
aaagacttaa--------------------------------------------------
------------------------------------------------------------
---------------------------------------
