>gi|145338597|ref|NM_112535.3| Arabidopsis thaliana translocase of chloroplast 120 (TOC120) mRNA, complete cds
agacttttgccttctctaaccagtgtttcgtgattttgggtgatcctagaaatgggagat
ggggctgagattgtaaccaggttatatggggatgagaagaag---cttgcagaggatggt
a---------------------gaattagtgagttggtgggatctgatgaagtg------
aaggataatgaagaagaggtctttgaggaagcaattggttcgcaggagggtctaaaacct
gaatctctcaaaaccgatgtgttgcaagaggattttcctttagcttcca-----------
-------------atgatgaagtgtgtgatttggaagaaacaagtagaaatgagagagga
gtagaaaatttaaaggttaattattcggagattggagagagccatggtgaggttaacgag
caatgtataactacgaaagaggctgattctgatttggtgactctcaaaatgaatgattat
gatcacggggaagtagcagatgcagatatttcttatggtaaaatggcatcaagcttggat
gtggttgagaacagtgagaaagc---tac---------ttccaatttagctactgaggat
gtgaatttggaaaacggaaatacacattcttcttcagaaaatggagtagtctctcctgat
gagaataaagaactggtggcggaagttatctcagtaagtgcctgttccgtggaaacaggg
agtaatggtattgacgacgaaaaatgggaggaagaaattgatgtatcagctggcatggta
aca---------------------------------------------------------
------------------------gaacaaagaaatggtaagactggtgctgagttc---
---aatagtgttaaaattgtttcaggtgacaaatccttgaatgatagtattgaagtagca
---gctgggaccttatctccattggaaaaatctagttcggaggagaagggagagactgaa
ag----------------------------------------------------------
------------------------------------------------------------
--------tcaaaacagtaatggaggacatgatat------------tcaatctaataag
gaaattgtaaagcagcaagatagcagtgtaaatataggtccagagattaaggaaagccaa
catatggaaagagaatctgaggtattaagttctgtttcaccaacagagtctagaagtgat
actgcagcattaccacctgctcgcccagcaggtcttggtcgtgctgctccacttttggaa
cctgcaccacgcgttacacaacagcctcgtgtcaatggaaatgtgtctcacaatcagcct
cagcaagctgaagactctaccactgcagagacagatgagcatgatgagacccgtgagaag
ctccagtttatcagggtcaaatttttgaggctttcacatagattagggcaaactccacat
aatgttgttgttgctcaggttttgtacaggcttggattggctgaacagttgaggggcaga
aacggaagccgtgttggtgcctttagttttgatcgtgccagtgccatggcagaacagctt
gaggcagctgcacaagatccccttgatttttcttgtacgattatggtgcttggtaaaagt
ggggttggtaaaagtgcaaccatcaattctatttttgatgaactgaaaattagtactgat
gcattccaggtggggacaaagaaggttcaggatattgagggttttgttcagggaattaag
gtacgggtaattgacactcccggtctcttaccatcctggtcagatcaacacaagaatgag
aagatcctgaagtctgttagggcattcatcaagaaaagtccgcctgacattgtgttatat
cttgataggttggatatgcaaagcagagattctggtgacatgcctctcttacgcaccatc
actgatgtttttggaccatcaatatggtttaatgccattgtgggtttgactcatgccgct
tcggctccaccagatggcccaaatggtactgcttctagctatgacatgtttgtgacacaa
cgttctcatgtcatccagcaggccattcgccaagcagcgggagatatgaggctcatgaac
cctgtttctttagttgagaaccactctgcttgcaggacaaatcgggcaggccagagagta
ttacctaatggccaagtgtggaagcctcatttgttattactctcatttgcatccaagatt
cttgccgaagcaaatgctcttctgaaattacaagataatattccagggggacaatttgca
actcggtccaaggctccgccactaccattgctcctctcatcgcttctgcaatcaagacca
caagctaagcttcctgagcaacagtacgatgatgaagacgatgaagatgatttagacgaa
tcatcagattctgaggaagaatcagagtatgatgagcttcctccctttaagcggttgact
aaagcagagatgactaagcttagcaaatctcagaagaaggaatatctcgatgagatggag
tatcgggagaaactatttatgaagagacagatgaaagaggaaagaaagagacgtaagttg
ttgaagaaatttgctgctgagattaaagatatgcctaacggg---tatagtgaaaatgtg
gaagaggagagaagtgaacctgcatctgttccagttccaatgccagatttatctctacct
gcatcttttgactctgacaatcctactcatcggtaccggtaccttgatacctccaatcaa
tggcttgttaggccagtgctggaaactcatgggtgggatcatgatattggttatgaaggt
gtgaatgcggaacgactatttgttgttaaagacaaaataccagtatctttctctggccaa
gtgacaaaggacaagaaggatgcacatgtgcagctagaattggccagctcggttaaacat
ggagaaggtagatcaacttccctaggttttgacatgcaaaatgctgggaaggaattagcg
tacactattcgaagtgaaacaagatttaacaagtttaggaaaaacaaagcagcagctggt
ctctctgttacgctcttaggtgattcagtttccgcgggactaaaagtcgaagataagttg
attgctaataaacggttcaggatggttatgtcaggtggagcaatgactagtcgtggagat
gttgcttatggtggtactttagaagctcagtttcgagataaagattatccgcttggtcgg
tttttatcaactcttggactctctgtgatggattggcatggcgatcttgctatcggaggg
aatatacagtctcaagtacccattggacgttcctctaatctcattgctcgtgctaatctg
aataacagaggagcagggcaagtaagcatccgcgtaaacagctctgagcagcttcaactt
gctgtggttgcacttgttcctctgttcaagaagcttcttacttattattcccctgagcaa
atgcaatatggacactgatgagtaacatttaactgttttgattttttcttgaaacatgtt
tttctttttttagttgtcggaattcacttttgttttaagtctttgatgtttggttgtaac
atatgtctgaaacttaaaatccattatcccaatgtttctaagtcttcttg
>Thhalv10022323m|PACid:20183478
---------------------------------------------------atgggagat
ggagctgagattgtgaacatgtcagagggagaagagaagaag---cttccagaggataga
attagcgatgagcaagtag---agaaaaatgagctggtggggtcagatgaagcgagtgat
agtgataacgaagaagagatctttgaagaggcaattggttcgcaggaggctccaaaaact
gaacctttcgaagtcgatgggttgcacgaggatttacgtttagaggcaactcctgaaaat
ttcaaggatgagcatgaagtggttgatgatctggaagaagtaagtagcaatgagagtgga
gtgaaagattccaagacttatcattcgatagttggagagagccatggcgaggtgaacgtg
caagatataactacgggagaggcggaacgtgatctagtgactcctaaaatgaatgatgat
aa------aggggaagctggtgaagagatttctcatggtcaaattgattcaagcttggat
gtggttgaaaacagcgagaaagc---tacctgcagtggttccaatttagcgggtgaggat
gtgaatatgcaaaacggaaatacacattctttcccggaaaatggaat-------------
--------------------------tatctcagtaagtgccctttccgaggaaacaagg
aatgatagcattgaagacataaactgggaggagaaagctgatgtatcagctggcatggaa
acagaagaagagattgggggaggtgaaggaacaaataagaattgctctgaaaacggtttc
gtatgtataaacaatgtgtctggggaacaaagaaatggtgaaactggtgccggatac---
---agtagtgttaaaatggcctctggagacaaatccttaaatgatagtcttgaaatatta
aatgttgggacctcttctccgttggagaaatctagtcccgaggaaaagggagagatcgaa
gg----------------------------------------------------------
-----------------tcacagcagtagtggtttccctggggtaacttgtagagaacat
gagactgttcaaaatagtaatgtaagacatgatgttcaacagagtcctcaacgtaataag
gatcttgagaagcagcaaggcagcagagtaaatataggaccagagattacggtaagccca
catgtggaacgagaatttgaggtagttagttctgattcacggacagagtctgtaagt---
------tcattaccacctgctcgcccagcaggtcttggtcgtgctgctcctcttttggga
ccgacaccacgtgttactcaacagcctcgtgtcaatggcaatgtgtctcacgaccaacat
cagcaagttgaggactct---actgcagagaccgatgagcatgatgagacccgtgagaag
ctccagttgattagggtcaaatttttgaggcttgcacatagattagggcaaactccacat
aacgttgttgttgctcaggtcttgtacaggcttggattggctgaacagttgaggggccga
agcggaagccgtgttggggcctttagttttgatcgtgccagtgccatggcagaacagctt
gaggcagctggacaggatccacttgatttttcttgtacgattatggtgctgggtaaaagt
ggggttggtaaaagtacgacgatcaattccatttttgatgaagtgaaaatgagtactgat
gcattccagatggggacaaagagggttcagaatgttgagggttttgttcagggaattaaa
gtacgggtgattgacactcccggtctcttaccatcgtggtctgatcaacacaagaatgag
aagatcctcaggtctgttagggcgttcatcaagaaaaatccacctgacattgtattatat
cttgataggttggatacgcaaagcagagattctggtgacatgcctctcttgcgcactatc
attgatgtttttggaccatcgatatggtttaatgccattgtggggttgacacatgccgct
tctgctccaccagatggcccaaatggcactgcttctagctatgacatgtttgtaacacaa
cgttctcatgtcattcagcaggccattcgccaagcagctggagatgtgaggctcatgaac
cctgtttctttagttgagaaccactctgcttgcaggacaaatcgggcaggccagagagta
ttaccgaatggccaagtgtggaagcctcatttgctgttactctcatttgcatccaagatt
ctagcagaagcaaatgctcttctgaaatcacaagataatactgcagggagaccatttgca
gctcggtccaaggctccgccattgccatttctcctctcatcgcttctgcaatccagacca
caagctaagcttcctgaagagcagtatggtgatggagaagatgaagatggtttggacgaa
tcatcagattctgatgaagaatcagagtatgatcagcttcctccttttaagcggttgact
aaagctgagatggctaagcttagtaaatctcagaagaaacaatacctcgatgagatggat
taccgggagaaactatttatgaagaagcagatgaaagaggaaagaaagagacgtaagatg
ttgaagaaatttgctgccgagatcaaagatttgcctaacggg---catagtgaaaatgtg
gaagaagagagaagtgaacctgcatctgttccagttcccatgccagatttatctctacct
gcatcgtttgactctgacaaccctactcacaggtaccggtcccttgattcctccaatcag
tggcttgttagggctgtcctggaaactcatgggtgggatcatgatgttggttatgaaggt
gtgagtgcagaacgactttttgttattaaagaaaaaataccgatatctttctcgggccaa
gtgacaaaggacaagaaggatgcaactgtgcagctggaaatggccagctcggtgaaacat
ggaaagggtagatcaacgtccctaggttttgacatgcaaaatgttgggaaggaactggct
tacactgttcgaagtgacacgaggtttaaaaattttaggaacaacaaagctgcagctggt
ctctctgtaacactcttgggtgattcggtttctgcggggctgaaagtcgaagacaagttg
attgctaataaatggttcagaatggttatgtctggtggggcaatgactagtcgtggagat
gttgcttatggtggtagtttagaagctcagttgagagataaagattatccgcttgggcag
tgtttgtccactcttggactttctgtgatggattggcacggtgatcttgccataggaggg
aatatacagtcccaagtgcccattggacgttcctctaatctaattgctcgtgctaatctg
aacaacagaggagcagggcaagtaagcatccgcgtgaacagctctgagcagctccaactt
gctatggttgcacttgttcctctgttcaagaagctactt---------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Thhalv10022525m|PACid:20202302
---------------------------------------------------atgggagat
gggactgatgttgtggttaggtcagaaggggaagagaagaagaagcttgccgatgataga
attagcgatgagcaagtagagaagaagaatgagtttgtgcgatctgataaggct------
aaagataacgaagatgagatctttgaggaagcaacggg----------------------
------------------------------------------------------------
--------------------------tgatcttgatgaaacaagtagcaatgaaggggga
gtaaaagattccaaagttgattatcc------------------------ggttaacgtt
caac------------gagaggctgaacctgattttgtgactcctaaaatgaatggtgat
ga------ggaggaagcaggtgcagaaaattcc------------------------aat
gttgttgagaactctgagaaggcggctgattccaatggttcgaatttagtggctgaagat
gtgaatatggaaaacggaaatacacattctttatctgaaaatggaatcgtctctc---at
gagaatgaagaactggtggctgatggtatctcaaaaagtgttgcgcctgaggaaatgtgg
aatgatggcattgaagtcgaaaattgggaggaaagagctgatgcttcacctggcatacga
acagaaccacaagttgagggaagtggagtaacacacgagaatcgccctga----------
-----------------------ggcaaacggaaatggtgagactagtgccgattacaca
agtaatactgttgaaaatgcctctggtgaaaaatccttgaatggtggtattggagttgca
agtgctgtgacctcatctccatctgagaaatctagttctgatgaaaagccagagattgaa
agtgacagtagttgtttgaaaccagagcatcacgtagcttcttcactgaactcaaatttg
gagtcgtctactgaagttcgcagcaatagtggcttcccgggagttactagtaaagaacac
gagacagttcaaactgctaacggaggacatggtgttcaacaaagtcctcaacctaacaag
gaacttgaaaatcagcaaagcagcagagtaaatatagatccagagattaaggaaacatca
catgtggaaagagagtctgaagtagtaaattctgtttcaccgacggaatctagaagtaat
cctgcagcattgccacctgctcgaccagcaggtcttggtcgtgctgctcctcttttgcaa
cctgcaccacgtgctcctcaacagtctcgagtcaatggaaatgtgtctcacagtcagcct
cagcaagctgaggactctaccactgcagagaccgatgagcatgatgagacccgtgagaag
ctccagttgatcagggtcaaatttttgaggcttgcacatagactagggcaaactccacat
aatgttgtagttgctcaggttttatataggcttggattggctgaacagttgagaggtaga
aatggaagccgtgttggtgcttttagttttgatcgtgctagtgccatggcagaacagctt
gaggcagctggacaggatccacttgatttttcttgtacgattatggtgctcggtaaaagt
ggggttggtaaaagtgcaacgatcaattccatatttgatgaagtgaaattttgtactgat
gcattccagatgggaacaaagagggttcaagatgttgagggttttgttcagggaattaag
gtacgggtgattgacactcccggtctcttaccgtcctggtctgatcaatccaagaatgag
aagatcctgaactctgttaaggcgttcatcaagaaaaatccaccggacattgtactatat
cttgataggttggatatgcaaagcagagattctggtgacatgcctctcttgcgcaccatc
agtgacgtttttggaccatcgatatggtttaatgccattgtgggtttgactcatgccgct
tctgttccaccagacggcccaaatggcactgcttcgagctatgacatgtttgtaacacaa
cgttctcatgtcatccagcaggctattcgccaagcagctgaagatatgaggctcatgaac
cctatttctttagttgagaatcactctgcttgcaggactaatcgggcaggccagagagta
ttaccgaacggccaagtatggaagcctcatttgctgttactctcatttgcatcaaagatt
ctagcagaagcaaatgctcttctgaaattacaagataatattccagggagaccatttgca
gctcggactaaggctccgccattaccgtttctcctatcttcgcttctgcaatcaagacca
cagcctaagcttcctgaacagcagtatggtgatgaagaagatgaagatgatttggatgaa
tcatcagattctgacgaagaatcagagtatgatcagcttccaccctttaagcatttgact
aaagatcaaatggcgaagcttagtaaatctcagaagaagcaatatcttgatgagatggag
taccgtgagaaactattgatgaagaagcaaatgaaagaggaaagaaagagacgtaagatg
tttaagaagtttgctgccgagatcaaagatttgccgaacgagcctcctagtgacaatgtg
gaagaggagagtggtggacctgcatcagttccagttcccatgccagatttatctctacct
gcgtcttttgactctgacaaccctactcaccgctaccgctaccttgattcatcgaatcaa
tggcttgttaggccggtcttggaaactcatggctgggatcatgacattggttatgaaggt
gtgaatgcggagacactctttgttgttaataaacaaataccagtatctttgtcaggccaa
gtgacaaaggacaagaaggatgcaaatgtgcagctggaaatggccagctcggttaaacat
ggagaaggtagatcaacttcactaggttttgacatgcaaaccgttggaaaggaattggct
tacactgttcgaggtgaaacgagattcaacaatttcaggagaaacaaagctgcagcgggt
ctgtctctaacgctcttgggtgattctgtatctgctgggttaaaagtcgaagataagttg
attgctaataaatggttcagaatggttatgtctggtggagcaatgacttctcgaggagat
gttgcttatggtggcagtttagaagctcagctgagagataaagattatccacttggtcgg
tttttgaccactcttggactttcggttatggattggcacggtgatcttgctataggaggg
aatatacagtctcagattcccattggtcgttcctctaatttagtcgctcgtgctaatctg
aacaatagaggcgcagggcaagtaagtgtccgtgtaaacagctcagaccagctccaactt
gcaatggttgcaattgttcctctcttcaagaagctacttagttattattccc---agcag
acgcaatatggacaatga------------------------------------------
------------------------------------------------------------
--------------------------------------------------
