>Selaginella_moellendorffii_91152_PACid_15413277
--------------------GIVLGLGMAALALRTWLKFGSHTRALKQVEGTAQVEIHDL
RSLVESGEKEPSSD---------SSPPLVIVRGRVALPPKTSSEEVLLARNQTD------
-LAVFVERTQTYLFNEWR-GLFRWGPEWRGLLG-WGSLKEQVAFSRRKIP-FVLL--DSD
PQYD------GACVHINMENVE-HPLPLVTVFHQLHPVQT-S-----SSTFLQAVFGRRY
---PVGV-----------------IDEEKILPLNREITAVGFLS------------KHPQ
G-LPAIKSSNQ-------------------------------------------M-PFFL
-----TEFSREELIVELASATHALFWTGIVISSLALGVIGYSAFKN--------WCKWKE
WRRL-RQI-QEEL-RR------------------------------------EEQVMEED
E------------EPATTQEGSE------------VPDGQLCVVCLLRRKRAAFITCGHR
VCCMGCARRIRHSQNAANARCPVCRQSVSGYIRVY----
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
------------------------------------------------------------
--AVFVERTQTYVLTEMS-NFLGWI-----------TQKDLVKFTRQVVP-FVLA--ETE
AHWSFRPSDMAVYVHINLDESQ-HPIPLVTVHHQLHPVPA-S-----SYTLFQAMFGRRY
---PVGL-----------------LDEEKILPLGAEITAVGVLH------------TAPD
G-TPVVKSSKR-------------------------------------------L-PIFL
-----TEFTREQLLVELASSTKVLFWMGVAVSTVAAGVLGYSLVKN--------WTRWKQ
RQQQ-RQS-QNNS-EN------------------------------------RQNSTIED
----------------EAENFED------------IPDGELCVVCLLRRRRAAFIYCGHR
VCCMGCAERVEH---GANPRCPVCRQSVTGIVRVY----
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
------------------------------PRIAAVRGYVRTQGSFLRAPFSSE------
-AGVVVKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRAVP-FVLA--STE
LGNS------TGVVHINVDEVDYQPLPLTTVFHKLIPLET-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKILPIGKKITAIGLCR-------------AKN
AESVEITSCPE-------------------------------------------I-PFFL
-----SELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRG--------WKRIKL
RREA-RQA-QQMF-ED------------------------------------AEDA--IR
E------------DNSSDDDDDD------------VGDGQLCVVCLRKRRKAAFIPCGHL
VCCCKCALRMER---EVEPLCPMCRQDIRYMIRIY----
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
------------------------------------------------------------
------------------------------PRIAAVRGYVRAHDKFFRAPFSGE------
-AGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTSFRSVP-FVLV--STE
LGNP------TGVVHINVDKAD-QPLPLTTVFHKLIPLET-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKILPIGKKITAIGLCQ-------------AKD
AESVEITSCPE-------------------------------------------I-PFFL
-----SELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRG--------WTRIKL
RREA-RHA-RQMF-EE------------------------------------AEDA--IH
R------------DDSS--DDDE------------IGDGQLCVVCLRKRRRAAFIPCGHL
VCCSECALTIER---TPHPLCPMCRQDIRYMMRVY----
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
-------------------------------------------------PWSGE------
-HGVVTKHTQMCLFTEWR-GIFGWTFDLHALL--FRSWKEQIVTYFRSVP-FVLA--SSE
IGNP------IGMVYIDVEKAA-QPLPLTTVFHKLIPIET-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKILPIGKELTAIGLCR-------------AND
EGSVEISSCPE-------------------------------------------L-PFFL
-----SELTKDEMQAQLASRARILFWGSVVLGTLSVCLVGHAIYRG--------WKRIKL
RREA-RQA-QQLF-EE------------------------------------GEDA--IQ
E------------DDSS---DEE------------VGDGQLCVVCLRKRRKAAFIPCGHL
VCCCKCALRMER---ETEPLCPMCRQDIRYMMRIY----
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
---------QLCLFNEWR-GIFGWTFDLHALF--FKSIKEQIITSFRWVP-FVLV--DPE
--NM------TGMVHVKLDRAM-QPLPLTTVYHKLTPVDS-T-----PYTLFQTIIGNGY
---PIAL-----------------LDEEKILPVGKEITAIGYIR-------------PHK
A-SVEISSCSE-------------------------------------------I-PFFL
-----SDLTKDEMEAELSSRAKTLFWASVVLGTMSVCLLGFATYRS--------WKKIKE
RREA-RQA-QEVF-RQ------------------------------------TTDE--VT
D------------DQSSDEEAGE------------MGDGQLCVICLRKRRKAAFIPCGHL
VCCCKCALIVER---QFDPLCPMCRQDIRYMIRIY----
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ALF--FKSLKEQTITSFRWVP-FALVDPASA
SDKS------TEMIHVKLDGAVQQSLPLTTVYHKLIPVEQ-N-----SYTLFQTIVGNGY
---PIAL-----------------LDEEKILPIGKEITAIGLCR-------------VNN
Q-NVEITSCPE-------------------------------------------I-PFFL
-----SDLTKGEIEAELDSRARTLFWVTFALGTMSVGLLGHAIYRF--------WEKVKQ
HREA-RQA-QQRF-HQ------------------------------------ADDEDDTG
E------------NGSDDDFPGE------------MGDGQLCVICLRKRRKAAFVPCGHL
VCCCNCAKRVEL---MNEPLCPVCRQDIQYMLRVY----
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
------------------------------------------------------------
--AVILQRTQTCIYNEWK-GFFGWTSDLRSIF--GRSLKEQETTFLRTVP-FTLV--EGG
QWPQ------SDYVIVNMDGSS-HPLPLTMVYHQLQPIVA-S-----RYTFIQALFGHEY
---PVGV-----------------LHEEKILPLGKCISAVGICN-------------SKD
G-IPEIKSCKE-------------------------------------------L-PYFL
-----ADMTKDEMVADLAFKAKILLWSGIVLGSLSIGVLGFAVMRN--------WNKWKA
WRQR-RS--QQPI-HT------------------------------------TSDEDVSQ
--------------IDDNEDAGD------------VPEGQLCVICLMRRRRAAFIPCGHL
ACCHTCAVSVES---EVSPKCPLCRQAVRNSIRIF----
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWR-GFFGWTSDIRTLF--ARSWKEKESTSLRTVP-FILV--EGG
RWPQ------SDYVIVNMDGSR-HPLPLTTVYHQLQPVNA-S-----PYTFLQALFGHDY
---PVGL-----------------LDEEKLLPLGKEITAVGICS-------------LKN
G-IPEIKSCKD-------------------------------------------L-PYFL
-----SEMSKDQMVVDLVFKSKVLFWSGVILGSVSIGVLGYAVVRN--------WNRWKE
WRQQ-RGV-RPPS-QA------------------------------------VTDDTDTQ
--------------I-AEDDAGD------------VPDGELCVICLMRRKRSAFVPCGHL
VCCQRCALSVER---ELSPKCPVCRQIIRSSVRIY----
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTLSRSVP-FVLV--EAG
RWPQ------SDYVIVNLDGSR-HPLPLTTVYHQLQPIDA-S-----PYTFLQAFFGYEY
---PVGL-----------------LDEEKILPLGKEINAVGLCG-------------SKN
G-ILEITSCKD-------------------------------------------L-PFFL
-----SDLSKEQMVVDLAFKTKVLFWSGVVLGSFSICILGYAAVRN--------WNRWKA
WRQQ-RQF-QQQS-NS------------------------------------VSDADVSQ
--------------IDVEEETVD------------VPDGQLCVICLMRRRRAAFIPCGHL
VCCQICAISVER---EVSPKCPLCRQAVRNSIRIFE---
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
-----------CIYNEWK-GFFGWTSDIRAIF--GRSWREQESTSLRMVP-FVLV--EGG
RWPQ------SDYVIVNIDGSR-HALPLTTVYHQLQPIDA-S-----PYTFLQALFGHEY
---PVGL-----------------LDEEKILPLGKEINAVGICS-------------SRN
G-VLEIKSCKD-------------------------------------------L-PYFL
-----SDMTKDQMVVDLAFKTKVLLWSGVVLGSLSIGILGYAAVRN--------WNRWKE
WRQH-RQS-QQQN-HA------------------------------------ASTDDDPQ
--------------IDADEEAGD------------VPDGQLCVICLMRRRRSAFIPCGHL
VCCQLCAISVER---EVSPKCPLCRQAVRNSMRIF----
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------RTVP-FVLI--DGS
QWPA------VDYVVVNMDGSK-HHLPLTTVYHQLQPINA-S-----PYTFLQALFGHEY
---PVGL-----------------LDEEKILPIGKDVSAVGLCF-------------LKN
G-ILEIKSCKD-------------------------------------------L-PYFL
-----TEMTKDQMVIDLAFRTKILFWSSIFLGSASIGILGFAFVRN--------WNRWKE
WRQR-RRD-EQQS-HA------------------------------------AVDEATAH
--------------I-AEDELGD------------APDGQLCVICLMRRRRSAFVPCGHL
VCCQRCALSVER---EVSPKCPVCRQTITNSVRIY----
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
------------------------------------------------------------
------------------------------------------------------------
--GVVLQRTQTCIYNEWK-GLFGWTSDLRALF--LRSWRQQESTSLRKIP-FVLI--DVG
RPSN------PEYVVVNMDGSS-HPLPLTTVYHRLQPVNP-P-----PYTFLQALFGHEY
---PVGL-----------------LDEEKILPLGKDVSAVGLCS-------------LRN
G-IAEIKACND-------------------------------------------L-PYYL
-----SDLSKDQMIVDLSFKTKLLFWSGILLGSMSVGIIGYAVVRN--------WNKWKQ
WKQQ-RQL-QQRR-QQ------------------------------------PIEPV---
--------------PPTDDEIED------------VPDGQLCVICLMRRRRSVFIPCGHL
VCCQGCAISVES---EVAPKCPVCRQEVRDSVRIFE---
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
------------------------------------------------------------
--GVILQRTQTCIYNEWK-GLFGWTSDLRAIF--ARSWRQQESTSLRKVP-FLLT--DVG
RRPN------AEYVVVNMDGSR-HPLPLTTVYHKLQPITA-S-----PYTFLQALFGHEY
---PVGL-----------------LDEEKILPLGKDITAVGLCS-------------LKN
G-IAEIKSCKY-------------------------------------------L-PYFR
-----SDLSKDQMIMDLSIKTKILFWGGIALGSMSVGVLGYAVVRN--------WNKWKQ
WKQQ-RQL-QQQR-QA------------------------------------VSDVE---
--------------PQMDDEIED------------APDGQLCVICLMRRRRSVFIPCGHL
VCCQGCAISVER---EVAPKCPVCRQEIRDSVRIY----
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------NA-S-----PYTFLQALFGHEY
---PVGL-----------------LNEEKILPLGKDISAVGICS-------------FKN
G-IPEIMSCKD-------------------------------------------L-PYFL
-----SDLTKDQMLLDLAFRTKILFWSGIILGSLSISILGYAALRN--------WNRWKE
RRQQ-RQA-HQPS-HA------------------------------------ASIDANSE
--------------LTGEEEIGD------------IPDGQLCVICLMRRRVPAFIPCGHI
ACCQPCALSVER---ELTPKCPVCRQEIRGSMRVF----
>S.lycopersicum_New__Gene_Model_C_gnl|BL_ORD_ID|12:46263002-46267916
MSIYDQAAAAVLSQIATAADGALIGLALAYVAVRSIVKFKANSSALHKINDAPSLNVSDL
RSLLSSSDNSDSSN-HSDDGKLVIVRGTVEAKSAVEGNWKSLRANILSAHNSAE------
-KGVILQHTQTCIYNEWR-GFFSWAGDLYSIF--PRVRKDQQSSSLRTVP-FVLI--ETG
RWPQ------PKYVNVNMDGST-HSLPLVTVYHHLQPLHA-T-----PLTFIQALFGHHY
---PVGV-----------------LDEEKILPLGKDITAIGVCS-------------SKD
G-ILEIKSCED-------------------------------------------L-PYFL
-----SDMTKDQMLVELAFKTKILMWSGVLFGSVAVGVLGYAVVRN--------WNRWKL
WRHQ-RQA-QQQR-DA------------------------------------ASNDDDVQ
--------------VSADEESGD------------VPDGQLCVICLTRRKRAAFVPCGHL
VCCQRCALSVER---DLAPKCPLCRQTIHSSVRIYDS--
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------------IF--SRSWRERESKVFRTVP-FILA--EGG
RRPI------SEFVAVDMDGSR-HPLPLTTVYHHLHPVNP-S-----PYTFLEALFGHRY
---PVGL-----------------LDEEKILPLGKEISAVGLCS-------------VKD
G-VLEIKSCKD-------------------------------------------F-PYFL
-----SEMSKDQMVVDLTSRTKVLFWSGIFLGSVSIGVLAYAVSRN--------WNRWKV
WRQQ-REL-QRSI-RA------------------------------------SNAEAQIQ
-------------EEEEEEDAGD------------VPDGQLCVICLMRRRRSAFIPCGHL
VCCQLCSISIER---DVAPKCPVCRQQIRTSVRIY----
>Citrus_clementina_0.9_012450m_PACid_19274708
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTAYQRLELANV-S-----PFTFLQAMFGLKC
---PIGV-----------------LAEEKILPLGKDISAVGICS-------------FKN
G-IPEIKSCKD-------------------------------------------L-PYFL
-----SEKTKDLMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRN--------WNRWKD
-RQQ-RMS-RQLT-EA------------------------------------PSDDADSQ
-------------IGSDEDVAGD------------IPDGQLCVVCLTRRRISAFNPCGHL
VCCRRCAISVER---EASPKCPVCRMTVRSSMRIY----
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTAYQRLELANV-S-----PFTFLQAMFGLKC
---PIGV-----------------LAEEKILPLGKDISAVGICN-------------FKN
G-IPEIKSCKD-------------------------------------------L-PYFL
-----SEKTKDQMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRN--------WNRWKD
-RQQ-RMS-RQLT-ET------------------------------------PSDDADSQ
-------------IGSDEEVAGD------------IPDGQLCVVCLTRRRISAFNPCGHL
VCCRRCAISVER---EASPKCPVCRMTVRSSMRIY----
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
------------------------------------------------------------
--GVILQRIQTCIYNEWR-GLFRWTADLGSMLMPRRITKENASSSMNMVP-FILV--EEG
KWPP------SDHVVVNMEGST-HPLPLTTVYQHLQPVKA-S-----SYTVFQALVGLEY
---PVGL-----------------LYEEKILPLGKDITAVGICN-------------LKN
G-IPEIKSCED-------------------------------------------L-PYFL
-----SILTKDQMIADLSFKSKVLLWSGLILGTVAIGVLGYSISRN--------WSKWKE
WKAR-RAQ-QQQN-AS------------------------------------RIENL---
-------------DETEEEESGD------------VPDGELCVVCLMRRRRSAFVPCGHL
VCCHRCAFSVER---EVSPKCPVCRQPIRNSVRIY----
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PYTLIQAIVGHAY
---PVGL-----------------LDEEKILPLGKEITAVGHCT-------------LQD
G-NPQIISCKK-------------------------------------------V-PYFL
-----SDMTKDQMIVDLVSKKKILFWAGIVLGSVSLGVLGYALTRN--------WQRLKE
WRQR-RQI-QQSR-EEE----------------------------------IANLDATPE
-------------DTRADEETED------------IPEGQLCVICLMRRKRAAFVPCGHF
VCCYRCALSVER---DSAPKCPLCRQDIRTSVRIY----
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------A-T-----PYTFLQAVFGHEY
---PVGV-----------------LDEEKILPLGKNISAVGICS-------------FEN
G-VPVIKSCSD-------------------------------------------F-PHFL
-----CEMTKDQMILDLVFKTKFLFWSSIVLGSLTVGILGYSAARN--------WNRWKQ
WRQH-RQL-QNSR-NDSPTSQLDSSNDIPIYGDFASDDEAATVPDDELSSHVPDDELSSH
--------------VPDDELSSH------------VPDGQLCVICLMRRKRSAFIPCGHL
VCCERCAVSVER---ESSPKCPICRQQIRSSVRIY----
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGD------
-KALIIQRTQTYVYSGWK-RLFQSTGHRFML---ERSLRKHGADFTRTVP-FVIV--GKD
QQSN------SSFVAVNMDGSR-QPLPLTTVYNRLQPINS-S--------FLQAFLYPDY
---PVGL-----------------LDIEKILPPGKDITAVGIYS-------------FNN
G-VPEIKSCQD-------------------------------------------L-PYFL
-----SEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRT--------WNKWKQ
WNHQ-REL-PQRP-ND------------------------------------SVVDD---
----------------EPEDADE------------IPDGELCVICVSRRRVPAFIPCGHV
VCCRRCASTVER---ELNPKCPVCLQSIRGSMRVYYS--
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VNMDGSR-QPLPLTTVYNRLQPINS-S--------FLQAFLFPDY
---PVGL-----------------LDIEKILPPGKDITAVGICS-------------FNN
G-VPEIKSCQD-------------------------------------------L-PYFL
-----SEMTKDKMIEELMDQTSFIFFGSVILGIVSVGILSYAAVRT--------WNKWKQ
WNHQ-RDL-PQRP-NE------------------------------------PVVDD---
----------------EPEDADE------------IPDGELCVICVTRRRVPAFIPCGHV
VCCRVCASTVER---ELNPKCPVCLQSIRGSMRVY----
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VIVDLDSST-HLLPLTTVYHKLQDLHV-MSDEILPYAFLEAFF---L
---PVGH-----------------M-QKKILPLGKEINAIGLCS-------------LQD
G-NLHIKATQE-------------------------------------------L-PYFL
-----SEMTKGEMVKHLAYKTTILFWGGCIIGIVSLGVLGYTSFRI--------WEWWKV
RRQH-FSN--------------------------------------------AEVDDVYI
G-------------------NDE------------IPSEQLCTICTMRRKKYACVPCGHL
VCCHKCARSIQH---DSTARCPECRH-------------
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------LGHAY
---PFGLCLQEKFLPLNFAWYHPGLLEEKILPLGKEISVVGIGT-------------SEY
G-NVEIKPCDE-------------------------------------------L-PYFL
-----SDLTKDQMIGELAQKTNYLLLSAIFFGSLSLAVIAYAVMIG--------CQRFEE
KTQQRRQV-QQQM-TQ------------------------------------VQQSLR--
-------------NDVVEEGMEA------------LPEGLSCVV-------SVFVPCGHL
VCCQTCAPLVAR-----DRRCPICRQYIQKYIITY----
>Mulan_NP_078820
---MESGGRPSLCQFILLGTTSVV---------TAALYSVYRQKARVSQELKGAKKV---
------------HLGEDLKSILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLTLQEHKMVWNRTTHLWNDCSKIIH-----------QRTNTVP-FDLVPHEDG
---------VDVAVRVLKPLDS-VDLGLETVYEKFHPSIQ-S--------FTDVIGHYIS
GERPKGI-----------------QETEEMLKVGATLTGVGELV-------------LDN
N-SVRLQPPKQ-------------------------------------------GMQYYL
-----SSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQ--------YLQRQE
RLRLKQMQEEFQE-HE------------------------------------AQLLSRAK
P-------------------EDR------------ESLKSACVVCLSSFKSCVFLECGHV
CSCTECYRALPE-----PKKCPICRQAITRVIPLYNS--
>Mus_musculus_gi_18043560_gb_AAH19516.1
---MESGSRPSLGQVILLGTSSMV---------TAVLYSIYRQKAQVAQELKGAKKI---
------------HLGEDLKGILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENC------
-KGVIQRLSLQEHKMVWNRTTHLWNDYSKIIH-----------QRTNTVP-FDLVPHEDG
---------VAVSVRVLKPLDS-VDLGLETVYEKFHPSVQ-S--------FTDAIGHYIS
GERPKGI-----------------QETEEMLKVGATLTGIGELV-------------LDN
N-AVRLQPPKQ-------------------------------------------GMQYYL
-----SSQDFDSLLHRQESSVRLWKVLVLVFGFATCATLFFILRKQ--------YLHRQE
RLRQQQLQEEFLE-HE------------------------------------AQLLSQAS
P-------------------EDR------------ESLKSACVVCLSNFKSCVFLECGHV
CSCRQCYLALPE-----PKRCPICRREITRVIPLYNS--
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1
---MENGGRPSVGQVILLTTSSAI---------TALFYSIYRHKYRSVQTLKEAKKF---
------------CLTDDLPAVLSDLPGKCVPYAVIEGAVTSVKEVLNSQYVENC------
-KGVIQRLSLKEHKMVWNRTTHLWNDHEKIIH-----------QRSNTVP-FDLAPENPG
--------ESGVSVRVLRPLEA-VDLGLETIYEKFHPAVQ-S--------FSNILGHYMT
GERPKGV-----------------QETEEMLKIGATITGVGELV-------------LDN
K-TIKLQPPKD-------------------------------------------GMLFYL
-----SSMDYEGLLEKQEVQMRWWRILSIVFGVASCITLFFILRRK--------YRHYKE
KQHLKNLQREFEE-SR------------------------------------ARQRVQQE
P-------------------QNK------------EEVQNPCSICLSTEKSCVFLECGHV
CSCISCYQALPS-----PKKCPICRNFIDRIVPLYNS--
>Danio_rerio_gi_148922854_ref_NP_001092230.1
---MEASGKPSTAQIVLLATSSAL---------TAVLYTIYKRKSSHVARLREAKKM---
------------SLNPELKTILSEAPGKCVPYAVIEGVVRSVKETLNSQFVDNC------
-KGVIQRLTLNEKKMVWNRTTNLWNDCEKVIH-----------QRTNTVP-FDLAPHDDT
---------VPTTVRVLRPLDA-AELDLETTYENFHPSQQ-S--------LTNVIGHFIS
GERPQGI-----------------QETEEMLRLGASMTGVGELV-------------LDN
N-LVRLQPPKK-------------------------------------------GLRYFL
-----SRLDYDTLLSKQEGHLRIWRVLTVLLGLTACATFFYLLWRQ--------YVLRKE
RRKEQSVLDEYRK-WQ------------------------------------SKRFQELH
L-------------------AKE------------DVSPTACTICLNHERSCVFLECGHV
CACEGCYRALPE-----PKKCPICRATIDRIVSLYNS--
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1
--------------MEFLHESVALGVDLLILGLCAREYVHYK---RTAKVLKAAPQY---
------------NIDGDLKSVVERQRDKKIPYAVIRGTVTPIGVPLRSSLVPSV------
-SGVLQIVKLHEHRVTRG-FAGFWTEQHKLLH-----------ESANEMP-FEL------
-------RNQSHGVEIVDALSA-AVLDVDVVYDNYEPSNL-S--------LFDHVFGFFS
GVRQRGL-----------------QTTEEVLREGSFLTAIGELE-------------LDG
D-TLRMQPSNE-------------------------------------------G-PLFL
-----TTATKSTLIKRFEDAKTTTILKLVVCSTISAILVAFIAKKL--------YRKRKQ
EREEAKIRERLDTERR--------------------------------------------
-------------ERRARSRPHT------------LSQDQLCVVCSTNPKEIILLPCGHV
CLCEDCAQKISV-------TCPVCRGSIVSKAAAFIA--
