>Solyc12g049330.1.1 SL2.31ch12 10F0H1E0IEG 46263202-46267916 20101015/09:21:03GMT
atgtcaatatacgatcaagcggcagctgccg-----------------------------
-------------------tgctatcgcaaatagctacggcggcggatggcgcacttatt
ggcttagccctagcttacgttgccgtacggagtattgtcaagttcaaagccaattcttcc
gcccttcacaaaatcaacgatgcgccgtcgcttaatgtctccgatctccgttcattactt
tcttcttccgacaac---------tctgatagttcaaatcattccgatgacggtaagctt
gtgattgttcgcggtactgtggaggcgaaatcggcggttgagggtaactggaaaagcttg
agagctaatattctctcagctcataattctgctgaaaaaggcgttatattgcaacatact
caaaca------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------tgtatctataatgagtgga
gaggcttcttttcgtgggctggtgatctgtattcaatatttccaagagtccggaaggatc
aacaatcgtcctctttgagaac--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------ggttccctttgttcttattgaaactgggaggtggccgcaacca
aaatatgttaatgtcaatatggatggttctacgcattccctacctcttgtgacagtttat
catcacttgcaacctttacatgctacgcctctcacttttatccaggctctctttggtcat
cactatcct---------------------------------------------------
------------------------------------------------------------
--------gttggagtattggatgaagaaaaaattctaccacttggtaaagatataaccg
ctattggtgtttgcagctcaaaagatgggattttggagatcaaatcatgtgaagacctac
cctatttctt--------------------------------------------------
------------------------------------------------------------
---------------------------------gtctgatatgaccaaggatcaaatgct
ggtagagcttgccttcaaaacaaaaattctgatgtggagtggagttttatttggttcagt
tgcagttggtgtccttggatatgctgttgtg-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------aggaactggaatcgatggaagctgtgga
gacaccagaggcaggctcagcaacaaagggatgctgcaagcaatgacgatgatgtgcagg
ttagtgctgatgaggaatctggagatgttcccgatggtcagttgtgtgtgatatgcctta
cgaggaggaagcgcgcagcatttgttccgtgtggacacctggtatgttgccagcgctgtg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------tgttataa
>C_gnl|BL_ORD_ID|12:46263202-46267916
atgtcaatatacgatcaagcggcagctgccg-----------------------------
-------------------tgctatcgcaaatagctacggcggcggatggcgcacttatt
ggcttagccctagcttacgttgccgtacggagtattgtcaagttcaaagccaattcttcc
gcccttcacaaaatcaacgatgcgccgtcgcttaatgtctccgatctccgttcattactt
tcttcttccgacaac---------tctgatagttcaaatcattccgatgacggtaagctt
gtgattgttcgcggtactgtggaggcgaaatcggcggttgagggtaactggaaaagcttg
agagctaatattctctcagctcataattctgctgaaaaaggcgttatattgcaacatact
caaacagtataattcttctacacttttcgttttactttaatttatgttcaaacagtatta
aattagtcaatttatcatgctttattaggcaattaatatccttattcgagctggaaattt
cgtattcaacgacatttaggattagtggtactgttagagttagttatgatcaatctaaat
ttgtgaatattcactataattgatgtgttagggcttttttaggcatgtgatatgatgcgg
tgatcgttttgaattacaatgtgggttgcaaactttggttaaactgcagggtttgatctt
gtacttgtgataatttatcctacatttttgttaaatgttaatgcacaatcgaaaaaaaga
acaatcgatgttttgcttagcccgcgttgaaggaatccctagacatagagagaggacatg
agataataagctggtgcacagggagggatgtctagggatgaattcccgcttcgcctcatg
accctttggtcgcagaggctgagagtgtgtcttaaaatacaaactatttttgtaatgaaa
ttgtgttatattagagctaaatggattgtgaggattcatatagcttatccaaagttgttt
ggaattgatgtgcggaagctgcagttgttacattgtaaatatcaacaattattaacagtt
tcgaaggggaactacgtgttttggatgttttatacgtgtgaatatatagattagctgtta
cagaaagaaatcaatagctattatctactggtgatggacatccttcagttttcaaagaac
tctttgaaccggtgtactttaaacagaaacaatatgatccacaaccaatttaatttgcaa
cctatgtttggctgctatttttttgtcagtttttgtgtgtatttctttttttctagtgaa
ttttggcagcatactgatgttcatttgctgtcttattctagtgtatctataatgagtgga
gaggcttcttttcgtgggctggtgatctgtattcaatatttccaagagtccggaaggatc
aacaatcgtcctctttgagaacggtaatgtgaaaattttccaacaacacaagtctcttga
ttttgctagtgcctttaatttcaccagtgaagcacaaaagagatattgagtcagtattgc
taatatttgtcaattttctatttttgccataaattctgctaggttatgtgaatattttgt
aagaagttataatcttagaattattaatgcaaatttctctgcataaaaagtttttcctac
tcgtcatctttaaatctagttaatacgctccaattttgtagttgctgctcttttgcctgc
taataagtgttatatagctttatttgttttcataatataagctttctaagcttttgtgct
tctctatcttcgacttaggttccctttgttcttattgaaactgggaggtggccgcaacca
aaatatgttaatgtcaatatggatggttctacgcattccctacctcttgtgacagtttat
catcacttgcaacctttacatgctacgcctctcacttttatccaggctctctttggtcat
cactatcctgtgagtttaaaaatatgttgtggatatgggcttcttgaccatttgtgattg
cttatacaacttttaaagtttgtctttcttcctgcaactcatgtaacatattgttttctg
tgacaaaggttggagtattggatgaagaaaaaattctaccacttggtaaagatataaccg
ctattggtgtttgcagctcaaaagatgggattttggagatcaaatcatgtgaagacctac
cctatttcttgtaaggaaggtttacagaatagttttcttaataaattgataaagcatgac
actcagctcttgttctaaaatttgggtgatcttttatttccgaattgatttattttgttg
aaatttgtgagtgttaatttttcactttggtaggtctgatatgaccaaggatcaaatgct
ggtagagcttgccttcaaaacaaaaattctgatgtggagtggagttttatttggttcagt
tgcagttggtgtccttggatatgctgttgtgaggtaaactagtttcatctctcaaacact
tgaactttttttgtggatatcatgccttcaagatctcactgtgacactctattttcttct
ttgtccttttcgctctcatagactgtagttgacgtgaagtctaggtagggacaaaatcct
taattgtttcatatagtattttatgattctgcttaccgagcatgagttagggttgtagga
accttctattgagtggttacctcttaaataatcaagtcatccacatctgctcccagattg
atggattcctttccctacttcatctgcaatttatctcgcggctgcatcaaatgagtcaac
ttataaatactatgacatgaacttataaccctactgggtagaaggctggttggttgattt
ggattacagttgttgtcatttcgtgtatgcaattatttgatgcatattactttagggaag
ttgtgcgatacagactagtgtacttgtattctattgaattgaaggaagtatagttttatc
tctgatgcaattgatgtttgagtaggaccatcatcacgtgccaaaaagaataatgcagct
agctacctttaagcatgaaagaatcatgatgggtgcatatttcagatgagcggaaccttg
aaattggcttacatattctagactacactatcccaggaaacctaagactgaaaaaacaga
aaaaaggggagatatgcttgtttgaaaggaaaacagggtgaaaaagtatttactgtagtg
gtcgcattttctcattggtatttatatgttttaggaactggaatcgatggaagctgtgga
gacaccagaggcaggctcagcaacaaagggatgctgcaagcaatgacgatgatgtgcagg
ttagtgctgatgaggaatctggagatgttcccgatggtcagttgtgtgtgatatgcctta
cgaggaggaagcgcgcagcatttgttccgtgtggacacctggtatgttgccagcgctgtg
ccttgtcagttgaacgtgatttagcacccaagtgtcctttatgtaggcagacaattcata
gttctgtaaggatatatgattcttgacgagcaaatagttacgagttattttgagtagctg
atgctgggaaggtggttgtgcatttgtaaagcatgtgatgaaaactacattggactgtct
catgggaggatggtcgttgatattccgaggggattagatactagaatttaacatgcatat
ttttcgtgtctgtacatacattttttgctgactcattattgtacccttaaagacaatatt
cattacaatgctagggagtcattttgctaaaaaagctttgagttctaagcactcagttat
ttcatcaaaacacacaataattacacatctatattcttataggtacatgaccaccttgcc
tagaatcaaattcttaaggaatttgataatttttttgacttgttgcctttgcaaatgcac
tatctgaacctgtgtcaaagcacagctaatgaaagattcttccaggctctagatttaccg
gtagacttttgactctgtttgtgcttaaaagccttgtgcatctcatgtgttgtgatctat
cttccataatgaacaaaatgaaacaggatctcctttccaccacagtccaacacagccatc
cttctcatcaactctcatctcccagttgttgtcatacttcttcaacaatgcacgagctct
atcaatagcatcatctccaaacatctcccatacgaaaccaacactcctcattctttcaca
ccatttctcctttgtctcattcatctctcccatgtttgtcaaagcctttgctgcttctcc
ttccatcatcctccttccctcgctctcacgtcctttgtatgctacactggtagagtccaa
gaacttccacaagtactccactcgccttgagaatcttgttgtgaagtccccgcaactgtt
gcagctgcaatccatgttgttctcactcaaaaccagtccttttggctccaaactctttag
tcttctcaacaactctgtcctgtcgtctggattgttgtgtttcaagttatggagtctgaa
ctgtgcacaaataaccaagatttcatctggggatgtatttatcacttgcgaatcaagatt
ctgaagtgggtaattctccagtctgttgatttgtagattgatgttaatcgccttggcaaa
ggcaagtagttgcactgaaaagttgtaaccacctggaccaactacaaatggactatttct
ttgttgatcatcttctattgtaggtgttataa----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>C_gnl|BL_ORD_ID|12:46263002-46267916
atgtcaatatacgatcaagcggcagctgccg-----------------------------
-------------------tgctatcgcaaatagctacggcggcggatggcgcacttatt
ggcttagccctagcttacgttgccgtacggagtattgtcaagttcaaagccaattcttcc
gcccttcacaaaatcaacgatgcgccgtcgcttaatgtctccgatctccgttcattactt
tcttcttccgacaac---------tctgatagttcaaatcattccgatgacggtaagctt
gtgattgttcgcggtactgtggaggcgaaatcggcggttgagggtaactggaaaagcttg
agagctaatattctctcagctcataattctgctgaaaaaggcgttatattgcaacatact
caaacagtataattcttctacacttttcgttttactttaatttatgttcaaacagtatta
aattagtcaatttatcatgctttattaggcaattaatatccttattcgagctggaaattt
cgtattcaacgacatttaggattagtggtactgttagagttagttatgatcaatctaaat
ttgtgaatattcactataattgatgtgttagggcttttttaggcatgtgatatgatgcgg
tgatcgttttgaattacaatgtgggttgcaaactttggttaaactgcagggtttgatctt
gtacttgtgataatttatcctacatttttgttaaatgttaatgcacaatcgaaaaaaaga
acaatcgatgttttgcttagcccgcgttgaaggaatccctagacatagagagaggacatg
agataataagctggtgcacagggagggatgtctagggatgaattcccgcttcgcctcatg
accctttggtcgcagaggctgagagtgtgtcttaaaatacaaactatttttgtaatgaaa
ttgtgttatattagagctaaatggattgtgaggattcatatagcttatccaaagttgttt
ggaattgatgtgcggaagctgcagttgttacattgtaaatatcaacaattattaacagtt
tcgaaggggaactacgtgttttggatgttttatacgtgtgaatatatagattagctgtta
cagaaagaaatcaatagctattatctactggtgatggacatccttcagttttcaaagaac
tctttgaaccggtgtactttaaacagaaacaatatgatccacaaccaatttaatttgcaa
cctatgtttggctgctatttttttgtcagtttttgtgtgtatttctttttttctagtgaa
ttttggcagcatactgatgttcatttgctgtcttattctagtgtatctataatgagtgga
gaggcttcttttcgtgggctggtgatctgtattcaatatttccaagagtccggaaggatc
aacaatcgtcctctttgagaacggtaatgtgaaaattttccaacaacacaagtctcttga
ttttgctagtgcctttaatttcaccagtgaagcacaaaagagatattgagtcagtattgc
taatatttgtcaattttctatttttgccataaattctgctaggttatgtgaatattttgt
aagaagttataatcttagaattattaatgcaaatttctctgcataaaaagtttttcctac
tcgtcatctttaaatctagttaatacgctccaattttgtagttgctgctcttttgcctgc
taataagtgttatatagctttatttgttttcataatataagctttctaagcttttgtgct
tctctatcttcgacttaggttccctttgttcttattgaaactgggaggtggccgcaacca
aaatatgttaatgtcaatatggatggttctacgcattccctacctcttgtgacagtttat
catcacttgcaacctttacatgctacgcctctcacttttatccaggctctctttggtcat
cactatcctgtgagtttaaaaatatgttgtggatatgggcttcttgaccatttgtgattg
cttatacaacttttaaagtttgtctttcttcctgcaactcatgtaacatattgttttctg
tgacaaaggttggagtattggatgaagaaaaaattctaccacttggtaaagatataaccg
ctattggtgtttgcagctcaaaagatgggattttggagatcaaatcatgtgaagacctac
cctatttcttgtaaggaaggtttacagaatagttttcttaataaattgataaagcatgac
actcagctcttgttctaaaatttgggtgatcttttatttccgaattgatttattttgttg
aaatttgtgagtgttaatttttcactttggtaggtctgatatgaccaaggatcaaatgct
ggtagagcttgccttcaaaacaaaaattctgatgtggagtggagttttatttggttcagt
tgcagttggtgtccttggatatgctgttgtgaggtaaactagtttcatctctcaaacact
tgaactttttttgtggatatcatgccttcaagatctcactgtgacactctattttcttct
ttgtccttttcgctctcatagactgtagttgacgtgaagtctaggtagggacaaaatcct
taattgtttcatatagtattttatgattctgcttaccgagcatgagttagggttgtagga
accttctattgagtggttacctcttaaataatcaagtcatccacatctgctcccagattg
atggattcctttccctacttcatctgcaatttatctcgcggctgcatcaaatgagtcaac
ttataaatactatgacatgaacttataaccctactgggtagaaggctggttggttgattt
ggattacagttgttgtcatttcgtgtatgcaattatttgatgcatattactttagggaag
ttgtgcgatacagactagtgtacttgtattctattgaattgaaggaagtatagttttatc
tctgatgcaattgatgtttgagtaggaccatcatcacgtgccaaaaagaataatgcagct
agctacctttaagcatgaaagaatcatgatgggtgcatatttcagatgagcggaaccttg
aaattggcttacatattctagactacactatcccaggaaacctaagactgaaaaaacaga
aaaaaggggagatatgcttgtttgaaaggaaaacagggtgaaaaagtatttactgtagtg
gtcgcattttctcattggtatttatatgttttaggaactggaatcgatggaagctgtgga
gacaccagaggcaggctcagcaacaaagggatgctgcaagcaatgacgatgatgtgcagg
ttagtgctgatgaggaatctggagatgttcccgatggtcagttgtgtgtgatatgcctta
cgaggaggaagcgcgcagcatttgttccgtgtggacacctggtatgttgccagcgctgtg
ccttgtcagttgaacgtgatttagcacccaagtgtcctttatgtaggcagacaattcata
gttctgtaaggatatatgattcttgacgagcaaatagttacgagttattttgagtagctg
atgctgggaaggtggttgtgcatttgtaaagcatgtgatgaaaactacattggactgtct
catgggaggatggtcgttgatattccgaggggattagatactagaatttaacatgcatat
ttttcgtgtctgtacatacattttttgctgactcattattgtacccttaaagacaatatt
cattacaatgctagggagtcattttgctaaaaaagctttgagttctaagcactcagttat
ttcatcaaaacacacaataattacacatctatattcttataggtacatgaccaccttgcc
tagaatcaaattcttaaggaatttgataatttttttgacttgttgcctttgcaaatgcac
tatctgaacctgtgtcaaagcacagctaatgaaagattcttccaggctctagatttaccg
gtagacttttgactctgtttgtgcttaaaagccttgtgcatctcatgtgttgtgatctat
cttccataatgaacaaaatgaaacaggatctcctttccaccacagtccaacacagccatc
cttctcatcaactctcatctcccagttgttgtcatacttcttcaacaatgcacgagctct
atcaatagcatcatctccaaacatctcccatacgaaaccaacactcctcattctttcaca
ccatttctcctttgtctcattcatctctcccatgtttgtcaaagcctttgctgcttctcc
ttccatcatcctccttccctcgctctcacgtcctttgtatgctacactggtagagtccaa
gaacttccacaagtactccactcgccttgagaatcttgttgtgaagtccccgcaactgtt
gcagctgcaatccatgttgttctcactcaaaaccagtccttttggctccaaactctttag
tcttctcaacaactctgtcctgtcgtctggattgttgtgtttcaagttatggagtctgaa
ctgtgcacaaataaccaagatttcatctggggatgtatttatcacttgcgaatcaagatt
ctgaagtgggtaattctccagtctgttgatttgtagattgatgttaatcgccttggcaaa
ggcaagtagttgcactgaaaagttgtaaccacctggaccaactacaaatggactatttct
ttgttgatcatcttctattgtaggtgttataactgtcagacgaaccaatggtggtggacc
tcctgctcgatgggtcaa-------------ctcctcgagcaatgttggccattgaacac
catgagaaactccaatatcaacaatgtgtaggttccgggatgaatcatgtttccctagaa
tttggagtatagaagagtttgcaatgctattgggtatgcggaaccagggactgatctcat
tgaag
>gi|186490864|ref|NM_104293.4| Arabidopsis thaliana E3 ubiquitin ligase-like protein (AT1G54150) mRNA, complete cds
acttgtccgtgtgaccgtgtctacgacgttgaaatcgaaattaccacaatgtcctcgccg
gagcgtgctctcttgaatctattgacggacatcgctctctccttcgacggcgcaatcctc
ggactgactttagctgttagcgccgtcggttctgctctcaagtatgcttctaccaacgcc
gcgttgaagaagatcaaagatgcacccgaagtctccatttccgacctccgatcactgctt
ccggcttctgaagacaaatcagagactaacgataacaggaagagcaatgatcagcgaatc
gttgtggttcgcggagtcgtcaaaccgaaaatttccggtgatgagggttacaagaac---
---aacaacgtgttaatctctccggagactggagataaagctcttatcattcagagaacg
caaact------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------tatgtgtatagtggatgga
agagattgtttcagtccactggtcaccggttt---atgttggagagatcattgcgcaaac
acggtgctgattttacgagaac--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------ggtcccatttgtcattgttggaaaggatcagcaatcgaactct
agttttgtcgctgttaacatggatggctcaaggcaacctcttccgcttaccactgtgtat
aatcgcttgcagcctattaattcttcgtttc---------ttcaagcctttttgtacccc
gattatcct---------------------------------------------------
------------------------------------------------------------
--------gttggtctgcttgatatagagaagattttaccacctgggaaagatataacag
ctgttggcatctacagttttaataatggagttcctgaaatcaaatcgtgccaagatcttc
cttatttctt--------------------------------------------------
------------------------------------------------------------
---------------------------------atcagagatgaccaaggacaagatgat
tgaggaccttatggaacagaccaactttatattcttgggcagcgttatcttgggcattgt
gtctgttggcatccttagctatgctgctgtc-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------aggacctggaataaatggaaacaatgga
accatcagagagaactgccacagagaccgaacgattctgtggtcgatgatgaacc-----
----------cgaagatgcagatgaaatcccagatggagaattgtgtgtgatctgcgtgt
caagaaggagagtacctgcgtttattccctgtggacatgtagtatgttgcaggcgatgtg
cttcaaccgtggaacgagagttaaaccctaagtgtccagtttgtcttcagagcattaggg
gatctatgcgtgtatattactcttagtgacc-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------ctgaatcttctc
tcattgtatgtaatagggtaatgcaatttgtactctcagagaatcggaagttaacaaaat
agtttgacaatgatttgaaagttcgtcaagtcactcaatatagagtgagagattgtagag
gatatgaaagcaaagtttttaaaaggaagaaattttgtaaccgataa-------------
------------------------------------------------------------
---ca
