>gnl|BL_ORD_ID|3051 @Acidobacterium_capsulatum_ATCC_51196@ gi|225874751|ref|YP_002756210.1| hypothetical protein ACP_3205 [Acidobacterium capsulatum ATCC 51196]
MRYPQWP----------------PDYDTETARQRGSDRF---------------------
----YAALM-AIQVIKPIQTLGFIYRHQEIERRPPMQPGQ---------WAMMNKFDDAM
LARVPAMIDRIQPVMDGGNVEHK--NALSLLQLGL----EHFHPYIAGLLWVTGLEAIFD
SRGK-----EAFKKKLCDCLGPGTLVFPNWHAKTDAPT---------------LTVEEIA
IPL-----------------FVLRNK-LAHGADLRSAAAD---KKHPVDFTKRVSLTQNT
ETVNYALLLCDAA-----------------CYL---------LC-QVLQRVL-----
>gnl|BL_ORD_ID|2274 @Acidobacterium_capsulatum_ATCC_51196@ gi|225873974|ref|YP_002755433.1| putative regulatory protein, FmdB family [Acidobacterium capsulatum ATCC 51196]
M----------------------PLYE---------------------------------
----Y---------------------------RCKQCGHQ---------FEKIQSFSAPE
LKECPVCQGEVERLLSAPAVQFK----------GA------------------G-WYVTD
YAGK------------------------NGSNK---PKSGSS------------------
-------------------------------------------SESSASAASESSSPAKS
ESASASSTPAAKS-------------------------------------------E
>gnl|BL_ORD_ID|1874 @Agrobacterium_tumefaciens_C58@ gi|15889211|ref|NP_354892.1| hypothetical protein Atu1917 [Agrobacterium tumefaciens str. C58]
MLGLVPSICNQSMLCDVDARDRPEHDVERDVRFTVVRSAALWAAFCCPNQMTHLGSQTDS
SASQADSLTPFNILFSHNKCEIAGSPSATQQSHWSDVRPATLFQNAAMPNFITMKRRTAL
TLIASLPFAPLARAQSAGNNIRFDPLLTQADALSSLKAVIVSIDGEEVASRAYHGASLNG
STNIKSAS--KSVISALVGMAIDRKIIEGADQPIATILRGDFPPNPDPRLERITVGNLLS
MQSGLERMSGPNYGRWVASRNWVRMALGSGFAGEPGGGMLYSTASTHL---LSAILTKAS
GRSTLSL---------ARDWFRPLEGFSIG---GWER---------DPQGIYLGG-----
----NQMAMTARSLLAFGEL------YRLGGVTPDGERLISQEWIS----QSWQQRTNS-
---------VFNGDGYGYC---WFI--------------KEMAGETVYYAWGYGGQMLYI
V-PARRLS------VVMTSREDAPSARTG--------YRDQLHGLMED---------IIR
AV-----
>gnl|BL_ORD_ID|4226 @Anaeromyxobacter_dehalogenans_2CP_1@ gi|220919350|ref|YP_002494654.1| metallo peptidase [Anaeromyxobacter dehalogenans 2CP-1]
MIPLLVALAVSAAPSQPRTLRLDLFHTGTATEERFAVDRVVLEPLPFPGNPARP-VDDTN
LGKYFFEVRDLATNRVVYSRGYASIYGEWETTEDARKVGRTFSESLRFPAPDAPVQVLVK
KRGAGNAFQEVWSTVVDPKDRFVDPSRPPSPG---PLIEILKSGDPAHKLDLLLLGDGYT
EAERGKFEKDARRLVAELFEHEPFRSRKADFNVW-----GLCPPAEEKGVSRPL------
-TGVHRRTRVGATYDA---FGSERYLLTFENRSMRDVASFAPYDALAILANGE-------
--TYGGGG---------------------IFNLYATVAADNRWAGY----IFVHELGHHL
AALAD--EYFTSDTAYLSPEGRPEPWEPNVTADP---KAAKWADLVAAGTPLPTPWPKDV
FTKRANEFQERRK---RIRAQNRPE--AEMDALFLAQQKEETALLGQ-------------
--------ARFSKA-----------VGAFEGANYEATGYFRPQMDCVMFTRDPVPFCSVC
QRSI------------------------------------------------------GR
VI-DLYTAR-------------------
>gnl|BL_ORD_ID|568 @Anaeromyxobacter_dehalogenans_2CP_1@ gi|220915692|ref|YP_002490996.1| SirA-like protein [Anaeromyxobacter dehalogenans 2CP-1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------A
EVTATQGGTVVVVNAEQMGRGDDGLGAKLLGNYLRTLASLEPKPEAIVFYNGA-------
------------------------------------------------------------
------------------------------------------VRLLGPGSAHLE------
------------------ALRQLDDAGVDL------------------------------
--------LACITC-----------LEFFQLTGKLEVGHVSNMRE-------------IA
QRTLAA----------------------------------------------------AK
VI-TL-----------------------
>gnl|BL_ORD_ID|634 @Aquifex_aeolicus_VF5@ gi|15606242|ref|NP_213620.1| hypothetical protein aq_913 [Aquifex aeolicus VF5]
MDIYKKLPPLQEPRLFMSTERTYLSQLRFSILVISFALGLTKI-EWVAKMMNKGDIAEFL
RTG---------------------------------------------------------
----------------------------------------------AGALAVIATLVAAV
----------------------------------------GLFSFYKTMSYLKC------
-----GEQVDAKEVVDPRIYMAAERTFLAWIRTAIAITVFGFVIEKFEFF----------
-------------LVQLDRILHISTRVH----------------------------HEKL
FSIGAF------------------------------------------------------
---------------------------------------------------------IIG
IG----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------VL
TLVLGTANFYRTISQIDRGFYRTNVWLYKAYGLVI-F-----------------------
------------------------------------------------------------
-----------------------------ITCLTLAFYILELI-----------------
----------
>gnl|BL_ORD_ID|28 @Aquifex_aeolicus_VF5@ gi|15605639|ref|NP_213014.1| 3-hydroxyisobutyrate dehydrogenase [Aquifex aeolicus VF5]
MKVG------------------------------------------------------FI
GLG---------------------------------------------------------
----------------------------------------------HLGRAIAKRLIEQG
V---------------------------------------ELIVWNRTLSKAHEF-----
-----AKETGAEVTSSPADLINKVDRVFVIVFD---------------------------
-------------SQASEEVIFGEKGLVKGDIKGKTVIDMTTNHYLYAQK-----AYEEL
KKLGAFYLDAPVLGSVIPALKGELTIVVGGDKEKFEENKPLFEKFCRAIYYLGEAGMGSK
MKLVNNIVL----GGIMEVLAEAIAIGEKAGIDKETLINVLNDGAGKSYILDVKKKKLLE
EDFSTHFSVNLIYKDLHYA-----------------------------------------
----------------------QDLIKDLGLFSFTTAAVKETYGLARKE-----------
------------------------------------GFGNLDFSAVYKLFKED-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|1154 @Bdellovibrio_bacteriovorus_HD100@ gi|42522805|ref|NP_968185.1| hypothetical protein Bd1281 [Bdellovibrio bacteriovorus HD100]
MHRG--------------------------------------------------------
-------------------------------NFMKSVISVFIFLLSLSAHAEVGFKNGNQ
--KTA---------VLAQGRIVVHCFGNNPGGP---------------------------
------------------------------------------------------------
----------SHGSFICRE--EILTAGEYDYFVGPA------------------------
------------------------------------------------------------
---------GIKGDSVTLTALHQDGSQRTKTVDYDSAKGQSKKSINLW--IATLLQRPLL
DPGTN-----------TVRYKITSNGKVTASGEFVAEIKDGGTKNCSRTG-------SYT
SNTP--------------------------------------------------------
------------------------------------------------------------
SDCQNGTSLCRRYFNENNYCL---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>gnl|BL_ORD_ID|693 @Bordetella_petrii_DSM_12804@ gi|163854999|ref|YP_001629297.1| mraY gene product [Bordetella petrii DSM 12804]
M----LLE------------------------IARWLSD---------------------
----------------------DVRAIGVLEY------------------ITMRAVLA--
-----------------------------CATA-----------------------LLIG
LV----------------------------AGPRVIRKLTEMKIG----QAVRAYG----
-------------------PESHLVKTGTPTMGG--------------------------
------------ALILIAV----AISTL--------------------------LWADWT
N-----------------------RF----------------VW------VVLLVTFGFG
WIGWMDDYRKVVYRDPEGMPARQKFFWQATIGLV-AAVYLAFAVSAPANTELWPLFKAWV
SSGFAMPLPTRADLIVPF------FKSVSYPLG---------VLGFVALTWAVIV-----
--------------------------GTSNAVNLTDGLDGLAIMPTVMVG----SALGIF
AYV--------------------------------VGRVDYSKYLLFPYI--------PG
AAELMVLCAAIAGAGLAFLWFNAY----PAQVFMGDVGALALGGALGTIAVIVRQEIVLF
IMGGVFVVETLSVMMQVTWFKYTKR----------------KYGQGRRIFRMAPLHHHFE
VGGWKETQVVVR---FWIISMM--------------------------------------
---LVLIGLSTLK---------------LR
>gnl|BL_ORD_ID|1866 @Bordetella_petrii_DSM_12804@ gi|163856172|ref|YP_001630470.1| unnamed protein product [Bordetella petrii DSM 12804]
MTKKQLLSGACGQAPAGRHDAVQSRLAPGEAILARLETDLDAHLAFRPGSVVLTGRRLLA
CCSDDGQWREWPVAPRLRLSLADHAGVATLELRDGPVRLAAWRFTLARNAAALRLVAAFD
AVQAGRQTSAPACSTCHLPLPAGQAECPVCAQAAARPPSSWALLRLWRFARPYRGPLLAG
FVLTLLATAATLVPPYLTMPLMDDVLIPFQNGAPIDYSLVRLYLGGLLASAALAWGLGWA
RTYILAWVSERIGADLRTTTYEHLQQLSLQYFGGKRTGDLISRIGSETDRICIFLSLHLL
DFATDVLMIAMTAAILVSINPWLALVTLAPLPFIVWMIHAVRDRLRHGFEKVDRIWADIT
NVLADTIPGIRVVKAFAQEKREVQRFRAANNRNLEVNDRVNSLWSLFSPTVTLLTEIGL-
LVVWVFGIWQVANK-------------QITVGVL-AAF---LAYIGRFYTRLDSMSRIVS
VTQKAAAGAKRIFDILDH------VSSVPEPDAPARLDR---VAGRIELRNVAFR-----
--------------------------YGNRSV--IQGLD-LAIAPGEMIGLVGHSGSGKS
TLINLICRFYDVSEGAILVDGIDIRNLRIADHRRHIGLVLQEPFLFFGTIAENIAYGRPQ
ATRAEIVAAARAAHAHDFILRLPH----GYDSLVGERGQALSGGERQRISI----ARALL
IDPRILILDEATSSVDTTTEKEIQKALDNLVRGRTTIAIAHRLSTLRRADRLVVLAHGRV
VEQGRHEALMARQGAYYRLYQA--------------------------------------
---QARTGEADLRDDVDDADGGDDDDAPHA
>Mulan_NP_078820
MES---------------------------------------------------------
--------GGRPSLCQFILLGTTSV---------------------VTAALYSVYRQKAR
VSQELKGAKKVHLGEDLK------------------------------------------
---------------SILSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLTLQ
EHKMV-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------WNRTTHLWNDCSKIIHQRTN-------------------------------
-----------------TVPFDLVPHEDGV------------------------------
-DVAVRVLKPLDSVDLGL------------------------------------------
-------ETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLK---VGATLTGVGELV
LDNNSVRLQPPKQGMQYYLSSQD---FDSLLQRQESSVRLWKVLALVFGFATCATLFFIL
RKQYLQRQERLRLKQMQEEFQE--HEAQLLSRAKPEDRESLKSACVVCLSSFKSCV----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FLECGHVCS-----------------------CTECYRAL------------
------------------------------------------------------------
---------------------------------PEPKKCPICRQAITRVIPL--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------YNS
>gnl|BL_ORD_ID|678 @Campylobacter_concisus_13826@ gi|157164541|ref|YP_001466545.1| DNA-directed RNA polymerase, beta subunit [Campylobacter concisus 13826]
MKLTNLKPVEIKEEHRPRDFEAFQLRLASPEKIKSWSYGEVKKPETINYRTLKPERDGLF
CAKIFGPIRDYECLCGKYKKMRYKGIKCEKCGVEVTTSKVRRSRMGHIELVTPVAHIWYV
NFLPSRIGALLGIKMKDLERVLYYEAYIVDNAGEAYYDNENSKKVEKYDVLNEEQYQSLA
SRYEETGFTARMGGEVIYDMLAELDLTQILNQLKEEMEATNSEAKKKTIVKRLKVIESFL
NSGNRPEWMMITNLPVLPPDLRPLVNLDGGKFAVSDVNDLYRRVINRNSRLKRLLELDAP
EIIIRNEKRMLQEAVDALFDNGRRANAVKGANKRPLKSLSEIIKGKQGR--FRQNLLGKR
VDFSGRSVIVVGPKLKMDQCGLPKKMALELFKPHLLARLEEKGYATTVKQAKKMIEDKTN
EVWECLEEVVKDYPVMLNRAPTLHKLSIQAFHPVLVEGKAIQLHPLVCAAFNADFDGDQM
AVHVPLSQEAIAECKILMLSSMNILLPASGKAITVPSQDMVLGIYYLSLERNDEKGANKI
FSSVDEVMIAEEANTLGLHAKIKTMVDNKIIFTTAGRLILRAILPDFVPENMWNKIMKKK
DIANLVDYVYRNGGLEVTADFLDKLKNLGFRYATKAGISISIADIIVPDSKQKYIDEAKK
KVREIQKQYGAGLLTDSERYNKIIDIWTDTNNSVASEMMKLIQSDKGGFNSIYMMADSGA
RGSAAQIRQLAGMRGLMAKPDGSIIETPIISNFREGLNIMEYFNSTHGARKGLADTALKT
ANAGYLTRKLIDVAQNVKVTMHDCGTHEGVEITDITESGELIESLEERVLGRVLADDVID
PITNEILFSEGTLLDEEKAKAITEAGIKS--VSIRTPITCKAPKGVCAKCYGLNLGEGKL
VKPGEAVGIISAQSIGEPGTQLTLRTFHIGGTASTEQQDRQVIAQKEGFIRYYNLSTYE-
---------NNGKKIVANRRSAAVLLVEPK----------IKSTIDGKIEIEYAHEDVNI
VIKGKKEEIKYTI---RRNDLAKPNELAGVSGKIEGKMYIPYANGDKVKENESI-VEIIK
EGWN-IPNRIPYASELKISDGDPVTRKITADANGVVK----FFILKGDFLDRLKDIKKGH
KVTEKGFFVVVSDKDGREAVRHYIPRNSIIQVSDNDAVERATVVSLPEKDDKLIIAEWDP
YSTPTIAEEAGVVSFEDVEPGYSATEQADEATGQRRLVINEYLPSGVKPAIIITTKSGHL
IKYPLDPKTAIFVSSGDEVAQADILAKTPKAVAKSKDITGGLPRVSELFEARRPKNTAIV
AEIDGVVRFDKPLRSKERIIIQAEDGTTAEYLIEKSRQIQVRDGEFVHAGEKLTDGLISS
HDILRILGEKALHYYLISEIQQVYRRQGVAIADKHIEIIVSQMLRQVKIVDSGNTNFIVG
DMVSRNKFKEENERIMKMGGEPAIAEPILLGVTRAAIGSDSVISAASFQETTKVLTEASI
AAKFDYLEDLKENVILGRMIPVGTGFYKDKKIKIKEN
>gnl|BL_ORD_ID|694 @Campylobacter_concisus_13826@ gi|157164873|ref|YP_001466560.1| bifunctional 2-C-methyl-D-erythritol 4-phosphate cytidylyltransferase/2-C-methyl-D-erythritol 2,4-cyclodiphosphate synthase protein [Campylobacter concisus 13826]
MLDISLIMLGAGNSSR--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------FELPVKKQWL
RIGSDPLWL----------------------FATKNLSNFY--------------TFKEI
IVVSKECKYMSKFAPNYKFVDGGETRQDSLKNALELVSSEFVLVSDIARPCISSELFHKI
IEAAAQADCVV-PALKIADTAYLGENAIDREKVKL-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------IQTPQLS-----------------------------
------------------------------------------------------------
------------------RTTLLKKALSSGEIYTDDSSAMRA------------------
--IGASVWHILGDE---MARKITFKEDLVKISALKAPENELFVGS--------GFDVHEF
EKGRPLVLC--GEKIDYE------FGLKAHSDG-DVALHALTDAILGAAGLGDIGELFPD
TDDKFKDISSIYLLQEAYKRVQ------SVGFVLTNA-------------DITIMAQKPK
LSKLKSKMEANIAQALNLSQSRINVKATTTEGLGFVGRCEGIAVMASASL----------
------------------------------------------------------------
-------------KF---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------YN-----------------------------------
------------------------------------------------------------
---------------------------------WTQI
>Mulan_NP_078820
ME----------------------------------------------------------
------------------------------------------------------------
SGGRPSLCQFILLGTT-SVVT---AALYSVYRQKA-RVSQELKGAKKVHLGEDLK-----
----SILSEAPGKCVPYAVIEGAVRSVKETL---NSQFVENCKGVIQRLTLQEHKMV-WN
RTTHLWNDC-------SKIIHQRTNTVPFDLV------PHEDGVDVAVRVLKPLDSVDLG
--------LETVYEKFHPSIQSFTDVIGHYIS-GERPK-------GIQETEEML------
-------KVGATLTGVGELV-LDNNSVRLQPPKQGMQYY---LSSQDFDSLLQRQESSVR
LWKVLALVFGFA---------------------------TCATLFFILRKQYLQRQERLR
LKQMQEEFQEHEA------QLLSRAKPEDRESLKSACVVCLSSFKSCVFLE-CGHVCSCT
EC-------------------YRALPEPKKCPICR-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------QAITRVIPLYN-----------------------S
>gnl|BL_ORD_ID|2185 @Candidatus_Solibacter_usitatus_Ellin6076@ gi|116621331|ref|YP_823487.1| unnamed protein product [Candidatus Solibacter usitatus Ellin6076]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------KCGVL----------------------------
------------------------------------------------------------
--LAAAALSAAAQAPGPRTLRLDYVHTGTAAEEHFAQDGVVLEGAWPGPLDRWVDESNLG
KYYFQVLDRG------------TNRVIYS-----RGFASIYGEWETTDEAKTQ-----HR
AF----QESV----------RFPAPAGPVQVVIKKR-------GPRNEFREVWS------
--TV----------------------------VDPADPAVDRAAPPK--------VNVW-
---AVMQNGAPRDKVDLLLMGDGY-TAAEMEKWHGDARRMAE-------------TLFA-
-----------ASPFKEHRQDFN--VWAVDTPAEESGVAR------PSDGVFRRSPLRAA
YDVFGSERYV---LTFDNKR------------LREAASAAPYEFIE--------------
IVVNDRKYGGGGIFNLFATVSADNAFTPYVFVHEFGHHFAGLADEYYTSDVAYGSATERP
EPWEPN---------ATADPRAGKWKDLLTAGIDLPSIWPKKAYEQMEQAIQERRRTIRA
Q-HRPEAEMEALFREESGLATKLLGSGPNAGKVGAFEGAMYEGRGYFRAQQDCMMFGRDA
G-----------FCAVCRRAIERV------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------IRMYAK
>gnl|BL_ORD_ID|314 @Chlamydia_trachomatis_434_Bu@ gi|166154288|ref|YP_001654406.1| unnamed protein product [Chlamydia trachomatis 434/Bu]
MSFFH-------------------------------------------------------
------------------------------TRKYKLILRGLLCLAGCFLMNSCS------
-----------------SSRGNQPADE--------------SIYVLSMNRMICDCVSR-I
TGDRVKNIVLIDGAIDPHSYEMVKGDEDRMAMSQLIFCNGLGLE-HSASLRKHLEGNPKV
VDLGQRLLNKNCFDLLSEEGFPDPHIWTDMR-VWGAAVKEMA---AALIQQFPQ------
---YEEDFQKNADQILSEMEELDRWAVRSLSTIPEKNRYLVTGHNAFSYFTRRYLSSDAE
RVSGEWRSRCISPEGLSPEAQISIRDIMRVVEYISANDVEVVFLEDTLNQDALRKIVSCS
KSGQKIRLAKSPLYSDNVCDNYFSTFQHNVRTITEELGGTVLE-
>gnl|BL_ORD_ID|147 @Chlamydia_trachomatis_434_Bu@ gi|166154121|ref|YP_001654239.1| unnamed protein product [Chlamydia trachomatis 434/Bu]
MH----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------SLTVFQ------EIFNRYT
EKPYPATSILVP---LYFPEEPLTFSEDLSPSTAPIL-NPPGLEPQALPVETPKDPV---
----TTSIPPP------SHPKESKHSWACVPIYPGLSHEELLKENYPALKRYIQRPARAS
CGIFVHESQEHEILFFNRLAKILSQKIFPTRLV--------------------LFYQKTL
SDFSHSPH----PFCLAPLPTIRYKN-------------SQVNYHDPVLHDKVT-CI---
-----------PIYSSSQYEK-DSALKRDLWTLLTSLSASMQKS
>gnl|BL_ORD_ID|557 @Chlamydophila_abortus_S26_3@ gi|62185205|ref|YP_219990.1| ligA gene product [Chlamydophila abortus S26/3]
MQSTYSREQYISLCKDIEEDDYRYYVLHNPTISDYDYDMKMRQLLSIEAQHPEWKVLWSP
SMRLGDRTSGSFPIVAHAHPMLSIANAYTLEELYEFFSRIEKTLGYTPKYTLEIKIDGIA
VAIRYEQRVLVQALSRGNGRKGEDITANIRTIRSLPLRLSKEAPEFLEVRGEVFFSRATF
CQINAAQRQAEKPEFANPRNAAGGTLKLLSAKEAAQRNLEISIYGSLAEENKRSHYENLL
LCKEWGFPVFGQPRQCQTIEKVVASLHEIEVARAQLPMEIDGVVIKVDDIEDQKVLGMTA
KHYRWALAYKYAPERAETILEDIIVQVGRTGVLTPVAKLRPVVLSGSRVSRASLYNEDEI
ERKDIRIGD---TVYVEKGGEIIPQVVGVCLEKRPEGTQPWVMPEYCPVCHQKVTRESDK
VSVRCTNSL---CSA------------------GVIEKIRFFCGRDALDIDHLGEKVVTK
LFDLGCIHRRCDIFQITEEDLRQVPGFKDKSIR------NVLKSIEKAKSVPLDRFITAL
GIPYVGIGGANALAQHFLSLESVMAASLDDLKAIEGIGDKVAESIVAYFHQPEHLEEIQK
ML-------------------------SLGVHILPCHRASSSCLGKAFVITGTLEKLTRS
EAETYIRNCGGKVGSSVSKNTDYLVVGQDPGS--KLKRAQELGVPILSEDELLKLLY
>gnl|BL_ORD_ID|1401 @Chlorobium_tepidum_TLS@ CT1422 2-desacetyl-2-hydroxyethyl bacteriochlorophyllide A dehydrogenase
ME----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------AK
KSKAIVFSGVNQIELREVTLKPVSSTDVLVETWWSSISTGTE------------------
---------------------------------KMALNGLIPSPPF------IFPFIPGY
ETVGRIVEA---------------------GDHVNQGLIGKFAYVAGS------FGYEDV
NAAFGGASQFIV---------------CPVESLTVLDGIANPQCGI--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AL--------PLGATAL-------------------------
------------------------------------------------------------
------------------------------HIVDLAEVKNRKVL----------------
-VLGQGAVGILAAELAKRFGASLVAVTEPHQRRLDISTSDIKVNPEKQDVSVALAGHEF-
-DVLIDSTGIMSAIETGLRFLKFHGKVIFGGYYQ---------------------RMNID
YSQAFNKELSFIAARQWAKGDLHRVRELIAAGKINAEKIFTHQCTVD---DNLMEAYMQA
FSDSDCLKMIIHWKHGNEAGEHFPTCNTA---------N
>gnl|BL_ORD_ID|1528 @Chlorobium_tepidum_TLS@ CT1552 valyl-tRNA synthetase
MSDHSAQNLEKTYNHHEVEERWRSAHWEAIGTFHAEHSRVLKEGATPYTVLMPPPNVTGS
LTLGHVLNHTLQDIFIRYARMMGKEALWLPGTDHAGIATQTVVEKKLRKEGVTRHDLGRR
DFLDKVWEWREEYGGLILRQLRKLGISCDWRRNLFTMDERASEAVINTFVALYREGLIYR
GRRIINWCPVSQTALSDEEVIMKSRRDKLVYISYPLAKDPTR------------------
---------------------------------SITIATVRPETILADVAIAVNP-----
------------------------------NDERYADLIGELVIVPIAGRHVPVIADDYV
DIEFGTGALKITPAHDPNDYEVAKRHNLPVFSVIGKDARMTDECGYAGMDRFDARDKIVA
DLAELGYLVKLEEYEHNVGYSERADVVVEPYLSEQWFVKMQPLAEPALKVVNDGEIRFHP
EHWINTYRHWMENIQDWCISRQLWWGHRIPAWYDDKGNV---------------WVASSY
EEA------CHLAGTD---KLSQDEDVLDTWFSSWLWPLTTLGWTGPHSDNDDLRAFY--
PTDTLVTGPD--IIFFWVARMIMAGLHFKGDV------PFRDVYFTSIIRDMKGRKLSKS
LGNSPDPLKVIDTYGTD-ALRFTIVYIAPLGQDVLFGEEKCELGRNFATKIWNASRFVFM
QREKLFATREEFVEAFANFTPQRELMSSAGRWLMSRYNAMLERYHQAMANFKVNDMVKIV
HEFFWGDYCDWYVEALKSELTGDITEERGRHAVCLAVSVLEGVLKALHPVMPFITDEIWH
AIAPRSAEETIATEAMPQPDASWRGEDA-----AAFDLVRNMVSEIRSLRSAFNVPHDLR
AQAVIRAS----SPAALVALQTGRAIFPAMTKCEVELGESVERPAHSAASVVDGNELFIK
LEGLISFEKEKQRLEKEITKVTAYIESLEKKLSNEKFVSNAPADVVAKEKEKLEESRSMV
LKLQGNLEVL----------------------------S
>gnl|BL_ORD_ID|1927 @Chloroflexus_aurantiacus_J_10_fl@ gi|163847531|ref|YP_001635575.1| hypothetical protein Caur_1971 [Chloroflexus aurantiacus J-10-fl]
MKA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-REIMT------------------------------------------------------
-------------KNVVC------------------------------------------
-----------------------------------------------------VTDD---
------------------------------------------------------------
------------AAVEDAARLMTRNRISGLPVVNPQGMLVGLVTEHDLIAKEGRTVKEIM
TRSVISVSPDTEVEQIQH----------------------LLTNQRIRRVPVVENGKVVG
IVSRSDLVRQ----IAMRWVC--------------------GVCGEIVRALEAPKHCPRC
GADT--------------------------------------------------------
---------------------------HAF------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------THEVVPPGM------------------
------------------------------------------------------------
-----------------------------
>gnl|BL_ORD_ID|2164 @Clostridium_tetani_E88@ gi|28211998|ref|NP_782942.1| inosine 5-monophosphate dehydrogenase [Clostridium tetani E88]
MAII-------------------LKKGYTFDDVLLLPN----------------------
----------------KSEVLPKDVLLNTNLTKKIKLNIPLI-------SAGMDTVTESR
MAIAMAREGGIGIIH---KNMSIEKQAEEVDRVKRQENGVITDPFHLSPDKKLQDALDLM
SKYRISGVPITVEGKLVGIITNRDIVFEDDYSKKISELMTDEDLITAPENTTIDQAREIL
KKHKIE---KLPLVDENFNLKGLITIKDIDK---------IKMYPNSAKD----------
DKGRLLCGAAVGVTADMIERVDAL--------VKAQVDVITIDTA----HGHSRGVLEGV
------------------------------RKIKELYPELQIIAGNVATPEATRDLILAG
ADCVKVG---IGPGSICTTRVVAGVGVPQLTAVMDCVEEAQKHGVPVIADGGIKYSGDIV
KALAAGASVCMMGSLLAGCAESPGETEIYQGRSYKVYRGMGSLASMACGSKDRYFQEDNK
KLVPEGVEGRVPYKGYLSDTVYQLVGGIRSGMGYLGSKTLKDLYESARFIVQTSAGLRES
HPHDISITKEA-----PNYST---------NA
>gnl|BL_ORD_ID|2206 @Clostridium_tetani_E88@ gi|28212040|ref|NP_782984.1| diaminopimelate decarboxylase [Clostridium tetani E88]
MRLFGTMEVKDNNLYIGGVSCKELKNKYSTPLYIIDEDFLRGRCKEYYNNFGVEKHGNKV
AYAGKSFLTIAMCQIIKEEGLFLDVVSSGELYTALKANFPMN-------KIYFHGNNKTL
DEIEMG--IELGVGKFVVDNFYEMNNINNMARKKGIKQSIL---LRITPGIEAHTHDYIK
TGQVDSKFGFSMVGEEVYKAVETALSLPNINLSGIHCHIGSQIFETTPYEEAVDIMFEIL
KEIKNRYDYEISEVDLGGGFGIYYTKEDKPKETKEYCEAILKKALNKSKELGIKLPMLGI
EPGRSIIGNA----ATLIYTIGAIKEIP---GIRKYVS---IDGGM---NNNIRPALYDA
--------------------------------------KYECEVANNMNSD-DRELVTIA
GKCCETGDIVIEDVEISKSK-----------------------------------SGDIL
AIPSVGAYGYSM-------------SSNYNK-----------------------------
--IPK-------------------------------------------------------
-PAIV-LVKDGESRVMCKRESFDDMLKNELSL
>gnl|BL_ORD_ID|1363 @Cytophaga_hutchinsonii_ATCC_33406@ gi|110637791|ref|YP_677998.1| ADP-glyceromanno-heptose 6-epimerase [Cytophaga hutchinsonii ATCC 33406]
M-----------------------------------------------------------
----------------------------------------------------MVVTGAAG
FIGSCLIQRLNELNFNFI-----------------------------VAVDHFENPEKKK
N-----------------------------------------LENKKIQEYV------DR
DDFFDWLDKNNKHVEFIFHIGART---------DTTEFDKAIFDRLNVA-YSKNM---WN
ACIKYQIPLVYASSAA-------------------------TYGNGEFGYDDNEQKIP--
---QLKPLNPYGDSKNDFDIWALQQEKQPFFWAGLKFFNVYGPNEYHKSRMASVIFHAFH
QIKNSGKMKLFRSHKAEYTDGGQMRDFVYVKDVCNVIIFLMNHRKNSGIYNLGSGTARTF
LDLAKNTFKNMEVTENISFIDTPIDIRDKYQYFTEANMGKLKSIGYTDTFHT---LEEGI
KDYVKNYLI----PNKYW
>gnl|BL_ORD_ID|1477 @Cytophaga_hutchinsonii_ATCC_33406@ gi|110637905|ref|YP_678112.1| copper transport system protein [Cytophaga hutchinsonii ATCC 33406]
MNLHMKNIVLGLTLLIVAWSCNKESGKNTPDNVFYTCSMDPQVMEKKPGKCPICKMDLTK
VIIDKNDMQSGLKLNNEQEQSANIKTLIISEGDLGREKTVNGRIVINENKRFKISSRVSG
RIEKLYIKSLGETISKGVKLYDLYSEDLLVAQREYLIAIEKSKEFSGSELDYIQLADGAK
NKLILWGMNENQIKSLI-----NKKELSNTVTIYSPYKGVVTSVNKREGDYV-----MDG
DVVFETADLSTLWVEAELYAG------------EVNEFDVNDPVAIKIIGFPGKI---WN
SRIDFFAPQLQTQSKV-------------------------NLVRAEISNTDMSLRPGMQ
ANIVLKENTKKALF--LPLNAILQDSKGATVWI---------------------------
------KEKDGSYHSRMVITGIESNDNIEIRSG---------------------------
-----------------------------------IEAGEEVVINGAYLLNSEYIFKKGT
NPMAGH-------DMSNM
>gnl|BL_ORD_ID|1150 @Dehalococcoides_ethenogenes_195@ gi|57234064|ref|YP_181906.1| orotate phosphoribosyltransferase [Dehalococcoides ethenogenes 195]
M----------------------------------------------------------E
DVETLFEKTGAILK----GHFLLT---------SGLHSPI--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------YWEKFRIIENPEYNQQLC
GMIAEHYKDKGIELVAGPTTGGIVLAHEIARQMGLKCVFAEKIADSERG-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------FRRGFVIKPGAKVLVVDDI
LTTGKSVREVLAAVKKA---GGEVAGIGVLVDRSDTALQFNAPVFS--------------
---------------------------------------------------CLRSATTTY
KPEDCPLCRQGL------------------------------------------------
------------------------------------------------------------
------------------------P------------------------LTKHGS-----
------------------------------------------------------------
------------S
>gnl|BL_ORD_ID|1081 @Dehalococcoides_ethenogenes_195@ gi|57234088|ref|YP_181837.1| glutamine-dependent NAD(+) synthetase [Dehalococcoides ethenogenes 195]
MGKLRLAMAQIDSVVGDLAGNTACIIRHIQEARSLGADVIVFPELAICGYPPEDLLHKPR
FVEGNLHSLDSVIK----ASEGITVIVGYVDSHNGLHNSAAIIHNASLIDSYHKIFLPNY
GVFDENRYFLPGNRCPVYTICGLRVGVNICEDIWFASGPSTAQSNKGAELIINISASPYH
FGKRNQREKMLSDRARENRVYIAYTNMVGGQDELVFDGASNVFDYTGNLVLRGKQFQEDL
LVLDLDIPALTRQGDMSTEIPDSIFVSASGLSEPKLPFENSDSVPLDADAEVYQALLLGT
KDYINKNGFKKVVI--GLSGGIDSSLVAAIATDALGADNVVGVIMPSRYSSAGSISDSLR
LAE--NLGIKTLQIPIDPIFKSFLSTLSEVFAGTETDTTEENIQARIRGNLLMALSNKFH
WLVLNTSNKSETAIGYSTLYGDMAGGFAIIKDVPKVLVYRLAHNRNKSAGFELIPHNVLT
KPPSAELKP-NQ----------------------------LDTDSLPPY-ELLDPILE--
----------AYV---------EQDKSIDQIVALGFEESIV-------KRVVKMVDRSEY
KRRQAPPGI------------------------KITP----------KAFG---------
------------RDRRL-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------P------------------------ITNRYNH----
------------------------------------------------------------
-----------VG
>gnl|BL_ORD_ID|405 @Dehalococcoides_ethenogenes_195@ gi|57234804|ref|YP_181161.1| hypothetical protein DET0416 [Dehalococcoides ethenogenes 195]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------AQDKTLVCRDCGNEFI-------
------------------------------------------------------------
----------------------------------------FTAGEQEFY-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------ASRGLKN
EPKRCPACRSARRSENRGEGGERRTYEVVCA-----------------------------
------------------------------------------------------------
----------------ACGVQTTVP--------FEPTEGRPVYCKDCYAKTKESE-----
------------------------------------------------------------
-------------
>gnl|BL_ORD_ID|419 @Ehrlichia_canis_Jake@ gi|73667053|ref|YP_303069.1| hypothetical protein Ecaj_0429 [Ehrlichia canis str. Jake]
M-----------------------------------------------------------
------------------------------------------------------------
----------LVPQEVIASNSLLCEYVKYTTINIKSATCIGSTDIINNKLKIHISKDSNL
QPIVQPHAKSLFLLEVTIPSSIV-KNDPYLRNIYI-----ISQSESLDANLYCLVDASH-
-IQSFTNEIYDTVQNKVPKFVDNIFKYTEV----------------------------IF
AKLEIDSHLKLNE-----YEILCSILPDAE-----FIIHEIEEKNSCCSCCPPFTSKQNI
TRVQSQESLLQENDAEQVTLPKPE------------------------------------
-----------------DNITNTSISSTDSSTEHNSISSLLSFVNVTIESINSFQNN---
---------------SK-----------------
>Mulan_NP_078820
M------------------------------ESGGRPSLCQFILLGTTSVVTAALYSVYR
Q-----------KARVSQELKGAKKVHLGEDLKS--------------------------
--ILSEAPGKCVPYAVIEG---AVRSVKETLNSQFVENCKGVIQRLT--LQEHKMVWNRT
THLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRV-----LKPLDSVDLGLETVYEKFHP
SIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSVRLQPPKQGMQYYL
SSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRK------------QYLQRQER
LRLKQMQEEFQEHEAQLLSRAKPE------------------------------------
-----------------DRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEP---
---------------KKCPICRQAITRVIPLYNS
>gnl|BL_ORD_ID|199 @Ehrlichia_canis_Jake@ gi|73666833|ref|YP_302849.1| trigger factor [Ehrlichia canis str. Jake]
MLDCYVVKEVSNDKLKWEYEFVIDKKYFLDQLDSKLSEIAKNVKVPGFRVGKASIDLVKK
EYLNDVMTDVVRKTIESTSSDFVKSNKFGEIISSNIDIVSYPNYYSDNDSKEENLVYKLS
FEVMPEAPLMDIDSIVLNG---IEVDIQESDVSEFIENLKK--QRPN------FIVVNGA
EYAVQEGDKVVIDYQNKVKGKILRGGSAKDFALVIGKGVALKEFENQLLGMRVGETKSFP
-LTFPDDYSVAYLAGK-------TTDMSVVVKSIYVVKD-VQDNESV-------------
----------------------ARSYGFKDVAEMENFVRK------------QIGQQFDQ
MVLTIMKKELFDYMDNTYSIDVPECVVKQEITKINKEILDSGEDIQIDVEKEAVRRVKLG
MLLIRMSRHNNITIKNEDVLSFIKNNYTDYGVDINNVLKML-------QSNKNFANYISG
KVLEDKVINYIIKLVKKDRKVMTTKEINLMFENI
>gnl|BL_ORD_ID|3459 @Flavobacterium_johnsoniae_UW101@ gi|146301226|ref|YP_001195817.1| unnamed protein product [Flavobacterium johnsoniae UW101]
MFFIEVILPLSLAKTFTYRVSEAEFHFIKKGMRVAVPFGKSKIYTALVLDIHENAPTLYE
AKEIHQILDERPIATEIQIKHWLWVANYYMCGIGDVYRGAFPTGLLLESETIVSHKPDVV
VNDSELSDDEFLIYEALQHQSSLKVQ-------------EIASILNRKNILP--------
-----ILQKLIARDIIFLEEEIKESYKPKLVRYVKLHSKYETDQGLGSLLDILKNDKQKE
IVLAY-------------------------------------------------------
---------FQISASEKKPVTVKKLVEV-SGSSSSVVKTLVKNEILEEYLLQQDRVLFTG
EKSEKELLLSEAQQNAFTAIKQSLTEKEVCLLHGVTSSGKTEIYIKLIEEYLHTGRQVLY
LLPEIALTTQLV-SRLRLHFGDKVAVFHSKYSNNERVEVWKQ-----------TLENSEK
AQIVIGARSALFLPFNDLGLLIVDEEHEQT------------------------------
-------------FKQTDPAPRYHARDAAIVLANFH-------------NAKVLLGSATP
SIET-YFNTQNDKYGLVTLT------------------------------ERYKNVRLPE
VVLVDLKD-----------KHFRKRMTGHFSD--LLIEEITEALSLGEQV-ILFQNRRGY
SPIIEC--------------LTCGHVPHCQQCDVSLTYHKFKNQLRCHYCGYAIAKPTNC
HSCSSIDLTTKGFGTEQIEQELASLFPKAKTARMDQDTTRGKFGFEKIIDTFKNREIDIL
VGTQMLAKGLDFDNVSLVGIMNADNMLHHPDFRAFERSFQMMTQVAGRAGRSEKQGKVVI
QTYNPNHNTIQQVTNHNYNGMYKEQLYDRQIYKYPPYFRIIKLTIKHKDFDKLKEGSMWL
YQVLSQNLNIPVLGPEEPAISRIRNEYIRTILIKIPQNMHLGNTKKTIQKMLNSFEAVAQ
YRAIKVVVNVDFY
>gnl|BL_ORD_ID|1267 @Frankia_alni_ACN14a@ gi|111220773|ref|YP_711567.1| unnamed protein product [Frankia alni ACN14a]
MLYLAG---QILAYVLVAM--VIGAALAWVFLIAPLRRQVRQTRDAQPDPTVDGAEPAPA
ADAVEADAVEADG--------TDAGRT-----------EAWGIEARET--DARETDPRSA
-----------DRAGTALALLPSPGEPYPRELGGEIAVGGDSGRVPESAGSSERAGAPAT
VGDRLGQDADSRAFVPD---------------------------TVGAELATTGPIPLPI
NAVRVGEPVAELVALLRRQRDDAALEKADLTARL-----------------AVAEQRAAE
SEQRIGAAERH--------AMTASARVEEIESTLRARVEAATSAAGGGTRAVDAPSPTGP
DTTAADTGLTVAELAREAELLRQQLVEAEGRAAKFSSRLAMARTEAEDAQRLVATMTTRL
DRHQAEWAAERLSLLGRIERTEASLERGTEAASAANPVAEPASAAVEYAELVGTAKALAS
ARAVRSTRAAVPLFAAEPAEVAEPAEVAEPVDADEPVDVAEPGGTPEPVDRAEPVDRAEP
VDGAESVDAVVSPGVAGPGREDEPAVGEESARLDESVRPHSDGAALAAAASVESGTAAPA
GSEPVRAGALGVAGMRARTSGVTKERPAAVAGVPAPTGSGSVTAPGVRSGATGEQAAGGR
VVQEAAPRWNGLLDPGGAVGDNLKEIVGIGPVIESRLRTLGITTFSQLAEMGDTDVDRLA
HKLDGFGDRIISDDWVGQAQDLQVRHYGGVF
>gnl|BL_ORD_ID|1839 @Geobacter_metallireducens_GS_15@ gi|78223054|ref|YP_384801.1| unnamed protein product [Geobacter metallireducens GS-15]
ML----------------------------------------------------------
-----------------------------------------------------VMKNIWK
E-----------------------------------------------------------
---------REKA-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------LENQYIYKQE
Q-----------------------------DKIERMQKEERERLV----------REMCR
N--RCPKCGDEIKAMTF-------------RGVPLDR-CPGCGGVWLGPNDLRILASKDH
RSWFEKWFKEENETSE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------KV
A
>gnl|BL_ORD_ID|249 @Legionella_pneumophila_2300_99_Alcoy@ gi|296105747|ref|YP_003617447.1| O-methyltransferase [Legionella pneumophila 2300/99 Alcoy]
MN----------------------------------------------------------
------------------------------------------------------------
---------------------------KFP------QSFSE-------------------
-------ANERIGNAIHHVCLNALDAKFIKSNIQESYQSWANVLY------------DRV
FLNWGLCDK------------------KIYRELSSLNFDFSTVGFFPHVYGQSLLFYLIR
PLIK---------------------------------------------------IHFFN
KRLLDVGCGNGVGLKIS-----SELLKTRY-------------------------ALGID
LVNK-------LVTNSNNNFYIED------------------------------------
-KINYMQADAENMAIANESFDIVTNLESSHLYPQIEHFFSEVERVLA-PNGFFCYADVNF
DVKRQAERFETFVKTRKNLRIIEKHNIT-KMIQASIYQRLIVNEKRFYQLAQY-------
-------LLGPDKINYTSELANV----ASSMGL-MFLPWWRIRFKNPALQALGKFARR-Y
KHWNKKYYFYYLIQKID-------------------------------------------
-----------------------------------------------------------S
>gnl|BL_ORD_ID|2990 @Methylibium_petroleiphilum_PM1@ gi|124268184|ref|YP_001022188.1| uroporphyrin-III methylase [Methylibium petroleiphilum PM1]
M----------------------------QLGLMLLLLLVSVTALSMAWYGQRRVRTLEQ
ELVRRQQDSAGQAAEAQLLAKQAQELSRDAVAKVTLTESRLAEITAQRGQLEELIQSLSR
ARDENLVVDIDA--GIRVALQQTAITGSA-----APLVAALKAADERLARVSQPRLEPVR
RAIARDLDRVKAVSVADIASLAI--KLDEAARLVDEAPLQVLDPQRLAEAKAPRAVARVA
PSPASAAASAAPVGGLRAELGDWWQGLWAETRTLLRVTRIDQPQAMLLAPEQGFFLR-EN
LKLRLLNARLALMSRQFDTAQSDLQAAVAAVDNYFDRGARKT----------QLLTELLR
SVVPQARQAGVPRPDDTLAALTTA----AAGR----------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|248 @Mycobacterium_smegmatis_MC2_155@ gi|118469180|ref|YP_884672.1| unnamed protein product [Mycobacterium smegmatis str. MC2 155]
MQI---------------------------------------------------------
-------------------------------REHVGANKPAIILYPSGTVVTFD----EL
EARANRLAHHFRNQGLQEGDVVAILMENN-------SHIHTVMWAARRSGL-------YY
VPISTHLTAAE---------------AAYIVDNSGAKAIVGSAKMRDV---------LAG
LGDEL------PNGLPDTLLIADGDLDGWLRYPE----------AVADLPDTPIDDELDG
DLLQYSSGTTGRPKGIKRELPHVHPSENPGMMAALISFWMTPDSVYLSPAPLYHTAPSVW
SMQVQAAGHTTVVMEKFDAEGCLEAIQKHRVTHGQFVPAMFTRMLKLPESVRNSYDVSSL
KRVMHAAAPCPVDIKKQMIDWWGPIVDEYYASSEAIGATLITAEEWLKHPGSVGKPLTGI
VH-VLDEDGNELPPGQAGEIFFEGGQDFEYLNDAEKTASSRDARGWKTVGDIG-YLDEEG
YLYLTDRRHHMIISGGVNIYP-----QEAENMLVTHPKVMDAAVFG-VPDDEMGQSVKGV
VQTVDPADATPEFGEELLAWLRDRLAHYKCPRSISFELQLP--RTDTGKLYKQELIAKYS
>gnl|BL_ORD_ID|3363 @Pseudomonas_stutzeri_A1501@ gi|146283762|ref|YP_001173915.1| hypothetical protein PST_3445 [Pseudomonas stutzeri A1501]
M--------------------------------------------LNATTWFERYQQRYR
WATRAYDRFVQDLVPELVDTLQRNEQVTVAVYGATQVGKTTLILDLLGLSTLTTNEVGSV
LRGGQQLGKSATAMPIRYGRSLDDGWYIAGEGPLSADTARETLRAFRRKVESGGICDAEV
LDIRIPRG----LFQQCDDSSAGLELNIIDIPGIN------------SHSSAEQALVTKL
ADRYVVAADIVLLV-------------------------GKADSLGFLNERDLIIPALAD
WAAQPTRFRIVLTYGFSPDSLVSQFKDQELTVEQVRDVHIGQM-----------------
-----------------------------------RTHDYVFPPEFRSNLFVL-------
------------------ELGDSIVDLGRTNPEYLQRIL---------QVTNDFRGELLE
----NIVKAAG---------PYARL-------------------QGAFQLDRVINARVER
LRKAL--------------------------ENQEVEYGRQRRQITDELAAFHPELLDA-
------SDEEIYVAIDKLGVDRL------DLKNKL--DELSASIKRLEEFNCAALFLTEF
SAGAVEKVSWLQEQLENCE-----------------------------------------
------------------------------QLQRKACIQAASLLFDKG------------
------------------VLPSWLKDEVPVIEYQRKALLDIDSHLNSYVLDGYWW-----
---SSSNFNEDR----NSLQKALRLNAREHGERIQSA-----------------------
----------------TKRALHERKRALLADYKNLKSHCIILQSYLESLQALEREYRCIC
AEYADD-----LQEMDRALGMASSFESQLNAAFMEELRSTKEDVESHPVPA---------
------------------------------------------------------------
--QRFYGLLHTRLLLSEIDRMYEGKSF-----------------------
>gnl|BL_ORD_ID|1342 @Rhodopseudomonas_palustris_CGA009@ RPA1350 putative transport protein ExbB2
MTIEKNDVRGAGWGWSRGAKSVAKAVTKAGLLAAVGGMLLTATPANAWWNDEWQLRKKIT
IDTSAAGANITDPIGTTPVLVRLHTGNFRFNATKEDGGDLRFVAGDDKTPLKYHVEKFDA
LLGEALVWVAVPDLQPGAKTDLWLYYGNKKAVAIADSKGTYDPDTQLVYHFAERGTVPLD
STVWANNAQSVGQPADGAIIGTGLRLDGRTPLTLPSSSALALAGSGGWTWSAWVKPAAAQ
PNSALYSRR----DGGNAVVIGFDNGAPFVEVANAGAVQRSATAAPVALNSWHHVAVVAG
NGRVTLYLDGNAYAVLDAALPALNTLAFVGGDALASNPAPTASPAASQAPLPDGSSPQGA
PTGDAPAADAPVAAAPAAMAGFAGDIDELEISKASRPAGFVRVAALGQGLDKGKLLTFTI
DEETASWLSGYFAVILKSVTLDGWVVIAILMVMAVISWMVMVDRASYLRRQARANARFIA
CYNAVDFDLRLLSYGSPEDVATLGGRLNNKDAALMRSSSLYRIYHIAADEIRRRSHQGGL
PVLTSNSIAAMRAALDGGVVRESQRLNRLMVMLTIAISGGPFLGLLGTVVGVMITFAAIA
ASGDVNVNAIAPGIAAALVATVAGLGVAIPALFGYNYLISQIKNLTADVQVFVDDVVTRI
AELYTSDLPSPLRRDQAAE
>gnl|BL_ORD_ID|2307 @Rubrobacter_xylanophilus_DSM_9941@ gi|108805164|ref|YP_645101.1| hypothetical protein Rxyl_2361 [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
----------VGTVVF--------------------------------------------
----------------------------------------------------------LL
VGVVLCV----------------------------------------AGGVLLYFR----
------------------RRMLGKA-----------------------------------
------------------------------------------------------------
------------------------------------------ELMRRTRTS---GAAGVS
AL---SPGTLVE---VKGTLRCERPLQSEMAKERCAYYSSKVVREYLERDRGDGAPGSGR
RSEVLARSERFAPFV---------------------VEDDTGGVPVSA------EGAEV-
-----------DAKKVVDRFERGAGAAGLSVTIGGATIDLGGGERTLGYRHTEEILPVDA
------------------------------------------------------------
----------------------------------------------------PVYVLGAV
RRDG---------------------------------------------------GIGPP
EEGAGR---------------------------------FVVSWRSEEALGE--------
-------------------------------------------------SLGRGARLLGL
IALGLFLAGAAFLAVGAAAALGYLQFR---------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|2252 Streptomyces_avermitilis_MA_4680 gi|29828788|ref|NP_823422.1| ABC transporter ATP-binding protein [Streptomyces avermitilis MA-4680]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------VHVSATPVL-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------ALRGVSKR-----------------------------------
----------FGAVQALTDVELEIHAGEVVALV---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GDNGAGKSTLVKTIA---------------------------------------------
-------------------------------------GVHPIDEGVIEWDGKAVQIN-KP
HDAQNLGIA--------------TVYQDL--ALCDNIDVVGNLYLGRELRKRGI------
--------------LDEVEMERRSRELLTTLSI---------------------------
---------RIPSVRIPIASLSGGQ-------------RQTV------------AIARSM
LGEPKLVILDEPTAAL-------GVEQTAQVLDLVERLRERGHA----------------
------------------------------------------------------------
-VILISHNMADVKAVADKVAVLRLGRNNGVF---EVKSTSQEEIISAITGATDNAVTRRA
ARNGEAQK----------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|37 @Sulfurimonas_denitrificans_DSM_1251@ gi|78776239|ref|YP_392554.1| succinate dehydrogenase/fumarate reductase iron-sulfur protein [Sulfurimonas denitrificans DSM 1251]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------KINIKRESLHVEYDVSLQGVTL--LEVLN-------------------
------------------------------------------------------------
------------------------------------------------------------
----EIKYKLDAT-----------------------------------------------
----------------------------------------------------------LT
FNSGCRSSVCG-------------------------------------------------
------------------------------------------------------------
--------SCALRVNG-REVLACSYKAEDGDVVEPLLNSPIERDLVVNMDKAYSF-----
------------------NAKAKAWQSSFAQH---VKLTDEDEMRNALQSDCILCGSCYS
ACPVYEVNKEFLGPFSLTRVWRYVSDK-------------------------REENPKGK
IDNIQINGVWDCTLCNACTLVCPQGISSKADIEKLRARSVMFGYSDSSFANFGGGFSFDG
TPSF
>gnl|BL_ORD_ID|2206 @Syntrophomonas_wolfei_Goettingen@ gi|28212040|ref|NP_782984.1| diaminopimelate decarboxylase [Clostridium tetani E88]
MRLFGTMEVKDNNLYIGGVSCKELKNKYSTPLYIIDEDFLRGRCKEYYNNFGVEKHGNKV
AYAGKSFLTIAMCQIIKEEGLFLDVVSSGELYTALKANFPMN-------KIYFHGNNKTL
DEIEMG--IELGVGKFVVDNFYEMNNINNMARKKGIKQSIL---LRITPGIEAHTHDYIK
TGQVDSKFGFSMVGEEVYKAVETALSLPNINLSGIHCHIGSQIFETTPYEEAVDIMFEIL
KEIKNRYDYEISEVDLGGGFGIYYTKEDKPKETKEYCEAILKKALNKSKELGIKLPMLGI
EPGRSIIGNA----ATLIYTIGAIKEIP---GIRKYVS---IDGGM---NNNIRPALYDA
--------------------------------------KYECEVANNMNSD-DRELVTIA
GKCCETGDIVIEDVEISKSK-----------------------------------SGDIL
AIPSVGAYGYSM-------------SSNYNK-----------------------------
--IPK-------------------------------------------------------
-PAIV-LVKDGESRVMCKRESFDDMLKNELSL
>Mulan_NP_078820
M----------------------------------------------------ESGGRP-
----------SLCQFIL---LGTTSVVTAALYSVYRQKARVSQELKGAKKVHLGEDLKSI
LSEAPGKCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLT---L------QEHKMVWNR
TTH-----------------------LWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRVL
K--------PLDSVDLG-----LETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEML
KVGATLTG-V----GELVLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVR--LWKV
LALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQEHEAQLLSRAKPE-DRESLKSA
CVVC-----------LSSFK-----------------------------------SCVFL
ECGHV----CSC-------------TECYRA-----------------------------
--LPE-------------------------------------------------------
-PKKCPICRQAITRVIPLYNS-----------
>gnl|BL_ORD_ID|11 @Treponema_pallidum_DAL_1@ gi|378974645|ref|YP_005223253.1| lon1 gene product [Treponema pallidum subsp. pallidum DAL-1]
MLGN--------LMLGPYCRSSLWRELSWQEVTGIVAPDTIAYLKARAQDHPFLLAHERA
CAAIRLGMRMYGDGYNICVIGASGTGKRTTLQYLLKDFVPRPEQMWDIAYAYNFVHPHEP
QVLQFPAGEGMPFAT--ALRRSVNAILNTAQDIVKSDAFLRERRTLLADIETRECAELSR
IEAELYTRGFRVRWHRKRGTYSFDLVPLLKGKDSSFEALHDLASRAKLSRCVVHELHARY
RLSCDEVSSLLHTLR----------------------------TARRAARRRLAQYYRAR
LRLIILEQMACIKKRV-ACYAPVFSPPPVSCAA-----EQTEREKTSSSRLIEVPHEFEE
MRARIISYI--ERIQTDVQVRVQCLMSMRISALVKKRFFDRYTLNFVCVHTEHAGYVFTE
HQPNLANLCGSIESKGNEGDTLENGHLRIRAGALHRAHAGVLIVQLEDLLAEEEAWTHLK
RALRTKQVLLPAGSSQSQGMLRPEGVPLTCKLVLVGEPCSFERLSQEDSSFRELFKVCAE
FDTSMPNSDKNQVALIAYLDRVVARYGTFSLDSSAYARLLAYAEELAESHTRLSTSFVQI
ADLVLESHAVAVDMHPDVSVITAHVVQEALNRRQYVCSRARERFQRMIACGELLVEVQGY
RIGRINALAIEEHCGHSFGIVISLTAQASAGKEGVMNIEREAGLSGEIYDKAHLIITSLL
REKCLSAFADAAFDPAVDDLGKGQDSFPLCLSAALCFEQSYHGIDGDSASAAEFLVLLSA
IGRFPLRQDRAITGSVNQLGQVQAIGGVSEKISGFYDVCALNGLTGMQGVLIPKSSCAQL
FLPERVQDAVRAGTFHVWAVCTIDDALELMVPDDLKEQGSAQLYQCVRARLRDFYVTVKG
HCE
>Mulan_NP_078820
MESGGRPSLCQFILLG---------------TTSVVTAALYSVYRQKA------------
----RVSQELKG-------------AKKVHLGEDLK------------------------
SILSEAPGKCVPYAVIEGAVRSVKETLNS--------QFVENCKGVIQRLTLQEHKMVWN
RTTHLWNDCSKI-IHQRTNTVPFDLVPHEDGVDVAVRVLKPLDSVDLGLETVYEKFHPSI
QSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSVRLQPPKQGMQYYLSS
QDFDSLLQRQESSVRLWKVLALVFG--FATCATLFFILRKQYLQRQERLRLKQMQEEFQE
HEAQLLSRAKPEDRESLKSACVVCLSSFKSCVFLE--------CGHVCSCTE--------
--------C-------------------------YRA-----------------------
---------LP-------------------------EP----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-KKC-----------------------PIC------------------------------
------RQ----------------------------------------------------
-------------------------AITRVIP----------LYN---------------
--S
