>gnl|BL_ORD_ID|33007 @Branchiostoma_floridae@ jgi|Brafl1|130821|estExt_fgenesh2_pg.C_4660007
M-----------------------------------------------------------
-TDVSRPPPRKSPDPSGPRAKLRARKPPGWRAKPPVPSSS--------------------
-----------------------------------IRFHAVPFTDSTPIRPQPPPAVPFN
NGTPARLPVPSTAVCQSPGENTRHHDNSQSGASLIPSPSEAVRSVMTGAMRLTGLIPSPS
EAVRSVMTGAMRLTGLIPSPSEAVRSVMTGAMRLTGLIPSPSEAVRSVMTGAMRLTGLIP
SPSEAVRSVMTGAMRLTGLIPSPSEAVRSVMTGAMRLTGLVRETMV-KVTHAASATTSVV
TRTCCADNTKTESSHRTATFSTARQTESYKMAIPTDDNVEAGPPVMLGKMAVMAIPSDDS
VKTGPQQGKAPLTKKCKALPPRKVAPVPQKSEQELSSEATPDESQDLQQGKAPLTKKCKA
VPFRKVAPVQKK------------------------------------------------
------------------------------------------------------------
----------------------------SEQEPSSESSPDEQQDSQADQELGQTYSVAQL
RKLFGETYSVEKPEQSSNFSDTYMVSPQAQDLGSTFVVRAENSEEVGALPYDSSDTVTAD
------------------------------------------------------------
------------------------------------------------------------
----HIDDVDAKPFDTTFNKGKLCLMAIPTGPHEEDEEAGGPSPGATSAPQPPSL-----
----TDAMKSMVVKNIVREGYSLELVQHAV-----------------WRRLHAGGVLSGP
ELLQAVKDLEQEYAAAEKKLGDKD------------------FLKEKEEVDLTLAMEDQV
VLCVLSQGHSLDTVRHVVWRRLQEGKGPFKSAPELLQA---VADLKREYERAGKKLDDTE
---------------------------------------KTFEEKTVEYKDGEGKTV---
-----------------------------------------------------------D
ASRASLQRANSVVEAMASPVVE-----------------------------------NVL
RAGYDRDLVQHAVWRRLETHGEN-------------------------------------
--------FASVAELLQALKDLEDEYVMAK------------------------------
------------------------------------------------------------
-------------------------------EKLGNDELPNMPPAVVTATTNTTTPESEN
TPSTEDIPPSPTTD----------------------------------------------
------------------------------------------------------------
--------------------NGTVQPISKETTDDNVESELERYREE--------------
---------------HTCKV-------------CFDARIEVVFV----PCGHYACCG---
-----------HC--AEGM-----AECPM--------------C---------RRGVDST
VK----------------------------------------------------------
------------------------------------VFFS--------------------
-------------------------
>gnl|BL_ORD_ID|18723 @Drosophila_melanogaster@ gi|21356375|ref|NP_647847.1| CG1134 [Drosophila melanogaster]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------EFLHESVALGVDLLI
LGLCAREYVHYKRTAKVLKAAPQYNIDGDLKSVVERQRDKKIPYAVIRGTVT--------
--------------------------------------------PIGVPLRSSLVPSVSG
VLQIVKLHEHRVTRGFAGFWTEQ-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------HKLLHESANEMPFELRNQSHGVEIVDA
LSAAV---------------------------------------LDVDVVYDNYEPSNLS
LFDHVFGFFSGVRQRGLQTTEEV-------------------------------------
---------LREGSFLTAIGELELD-----------------------------------
------------------------------------------------------------
------------------------------GDTLRMQPSNEGPLFLTTATKSTLIKRFED
AKTTTILKLVVCST----------------------------------------------
------------------------------------------------------------
----------ISAILVAFIAKKLYRKRKQEREEAKIRERLDTERRERRARSRPHTLSQD-
---------------QLCVV-------------CSTNPKEIILL----PCGHVCLCE---
-----------DC--AQKI----SVTCPV--------------C---------RGSIVSK
AA----------------------------------------------------------
------------------------------------AFIA--------------------
-------------------------
>gnl|BL_ORD_ID|768 @Trichoplax_adhaerens@ jgi|Triad1|54791|fgeneshTA2_pg.C_scaffold_3000798
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------ASCDSATIPCNDNFHK----------------------
----KMDDNGSRELNEEIKKNRIVISDRDPFSYNGDRLVVKPNAELMQFLPPENVNG---
----KELTALQVMEYLIDYISSRKLCNPLR---------------------ADYVDCKGD
PLEKLLSCDQFPVANLWDRLKM--------------------------------------
--HLEVVPVANEQSVINVDWRSRQNSQAHYDNSLTKEE------IPDSTEVAKGSKPTLF
-----------------------SVLEKLKAQVQQQL--DSVVGYETSTASEPEEND---
---------------------------------WSLEDTNYPTFELEPVTDSETDAPNSG
YSNSSSSDVVEVISSIKDERNSADNIGD--------------------------DDPEIG
EKDHWKCLYCQQLNNPI-------------------------------------------
------------ARNCAFCWKLRENWLPSD------------------------------
------------------------------------------------DDIAVDD-----
-------------------------TNDGTLSLIPQDDDLELSTSANSSIDFSLRQESDS
SGSESHIDSPVRSN----------------------------------------------
------------------------------------------------------------
------------------NRNNRLKKEQRKKKHCKISRQLKRYKSASNKRLSTVD-----
---------------GMCMI-------------CLSEPRSASIIHINEGIGHQVCCY---
-----------NC--AEKL-RRRRKKCPI--------------C---------RRPIELI
VQ----------------------------------------------------------
------------------------------------NFIG--------------------
-------------------------
>gnl|BL_ORD_ID|30765 @Branchiostoma_floridae@ jgi|Brafl1|126022|estExt_fgenesh2_pg.C_2010087
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------PSSLFPDMEP
ANGGAPTSMGSQDEARALQLAVDLAMLGLSVGGDQDDKMSNSGFDNDARNRKSSNMTECV
P---------------------------------------------VPSSEHVAEIVGRQ
GCKIKALRAKTNTYIKTPVRGEEPVFVVTGRKEDVAMA----------------------
----KREIMSAAEHFSQIRAARKNNMNMGPGPNPNQPGQITI------------------
----QVRVPYRVVGLVV-------------------------------------------
------------------------------------------------------------
-----------GPKGATIKRIQQQTHTYIVTPSRDKEPVFEVTGMPENVDRAREEIEAHI
AMRTGGLIDPVGDPDDFHRNGTETPLDHFGTAATFPGTNGSGTVPDFNPNNYTSSNGLAF
DTFNNFTPGDDRDLGIGESPPFDPAPAPPTNMWAPLDLVPNSRSGSSVTAALFGSNAANG
TIPNVQRRSSSISGSSGHPRLS-------------------------------PTLSDSN
EHPTARRVRSDPLSGG--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------PTMFTPLPG
SGFSTSVSSVQSGS----------------------------------------------
------------------------------------------------------------
--------------------------------STSISSSPTDSTGSLPPRSKNK------
---------------KDCMI-------------CYESEVVAALV----PCGHNLFCM---
-----------EC--ANRLCEKKDAECPV--------------C---------HTTISQA
IR----------------------------------------------------------
------------------------------------IFS---------------------
-------------------------
>AT1G30860.1|PACid:19654074
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------VSSPQRFGLILRDRNQNAGV
FQKNLKSPVKEVLKSHVSDENLVDSWIETHNNKNNRVLESPLESKRNDNLVASSLVQIWE
ARLNRSNGGN----SPSSSQSTASSSSRSDSGVSVQDSGLSESSSIDGDSEIADRTVEIE
SRSHGLVSDSGESKWGRVADLIRRLSNEDKKRTAGDNGSGGGGGLEIIRTPRPYCTSSSS
EKSNF-PVVSFSPKIRGRQAFTDFLMQMERDRHRELDSLFERNAVSRFTQRGRLQSMLRL
RNLNRCLVIQDR------------------------------------------------
------------------------------------------------------------
----------------------------NRSNAKTTGLNRIESGSAVLHLREKFHANVVN
---------------SAAATDKRKNHQRSTEMNNKSVEETEGTTTTSTRLKDGGVTLEAF
------------------------------------------------------------
--FAERLRPRNRKIEEATLCKEEESVSGTVDSQKNCLQ----------------------
----LQETREVEETCNDGKSEKKEEENTSPSEYLSRESRLRQNQDENNVG----------
----KYMQETRETEGLV---------------------------------------HESN
EMDQCLDQQETSYLNRWGEQEEYA------------------------------------
--DEQSYYGEYNDDWLSEIARPRSYWEELRKSRYLEVM------NTRSEKDDICRLLERR
-----------------------TVTDFLDSGLREKI--DNLMMSRVQTHSDKHSKK---
---------------------------------WELQQEEEEEVNFEID---EEIKEEPL
RGGEEQDDRDDLSQSSSSHISASSPAGSWSSQDTDVTSTPALVVQNP-------------
-QSPEMELISGMRSQIQQLQQE--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVLRDSVKTCLDANASLQHKAHQENPMK-----------
---------------RKCCV-------------CDETQVEAVLY----RCGHMCMCL---
-----------KC--ANEL-HWSGGKCPI--------------C---------RAQIVDV
VR----------------------------------------------------------
------------------------------------VIYDTRN-----------------
-------------------------
>gnl|BL_ORD_ID|17512 @Drosophila_melanogaster@ gi|24585479|ref|NP_610050.1| CG2617 [Drosophila melanogaster]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------LDALIRA----------------------------------------
----AELVDLVLLRPLA-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------SVIDAVITGVYYFLWGSYLVGFCLVEGSRKGWNL---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------LRCAVRNINEGIRDLGLITLDVADYFYGGTK
GGLKNVLDFGHCISRFICNLLIDLGDGILWLLMLLPRAILFLWDCLLDFVVHSIVAHGLS
LLNSAFRASIGLALLLVLYMFRRYVYLMLIYLL---------------------------
-------------------------------QRGRIEISTKTQSVYLWTHHKLQHFIHN-
--VWYVSENAGSASPERCVV-------------CMAQSRNVVVM----PCRHLCLCK---
-----------EC--SLQLVLLLEDRCPV--------------C---------RHNITSF
LS----------------------------------------------------------
------------------------------------VYV---------------------
-------------------------
>gnl|BL_ORD_ID|6943 @Drosophila_melanogaster@ gi|21356215|ref|NP_650865.1| CG4973 [Drosophila melanogaster]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------SE
EAASTSSFGFKKRNLKKGAGIRRKKETSSDESAKSSDEETKGKASALVRAEN--------
------------------------------------------------------------
----RRKRTNPNFQSTKTMSKAKRQAGGVGDDG---------------------------
----SSSASDDDKLGIAYKSKREALPSGP-------------------------------
---------------------------------------------------QDQGATSIN
EMDTELDRDAQAIHARALKINEEL------------------EGKADDKIYRGI------
--NNYAQYYKKQDTAAGNASSGMVRSGPIRAPAHLRAT------VRWDYQPDICKDYKET
GYCGFGDSC------------------------------------KFLHDRSDYKAG---
---------------------------------WQLEMDHE-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------NQRTGDVDSDGDDTKYEIHSDEETLP--------------
---------------FKCHI-------------CRQSFVNPVVT----KCKHYFCE----
-----------KC--ALAQ-YKKSQRCII--------------C---------SQQTNGI
FNPAKELI----------------------------------------------------
--ARLKTNPMENSDSDEEEEFGKKEDKAEAGEEAQEISSDDSD-----------------
-------------------------
>gnl|BL_ORD_ID|5432 @Saccharomyces_cerevisae@ gi|6325007|ref|NP_015075.1| Gyp5p [Saccharomyces cerevisiae S288c]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------SSDKSIEKNTDTIASEVHEGDNHSNNLGSMEEEIKSTPSDQYEE--------
-----------------------------------------IAIIPTEPLHSDKELNDKQ
QSLGHEAPTNVSREEPIGISGDEDTQITEQNVNEQRQETREPSSEIDLNEPLDVEKDVTT
DVQAPNGLNIEKEYDAVKENEKVYADTKEVVSSPENREVTGKNSGGEKSSSSKFLDDESG
TTTAANANDISISSEVTPERSSENDNNQIHITNEVAAGINLNENKEQKAAIED-GPVTAE
NLSSETARKVPPIPTQIINEKGDN--------------------SSENEVSAIPTTSSPP
LPPRQNVATSTSPKLPPRGKQREQPPKTKNAVPPPLEEEMKSEKFRKNFEETKRNSYHHV
PLTG-------------------SKTAQLESTAEINLIASRYRKTSHHLNKEGEETR---
---------ESLQEGQSFLKSTFTSFLENLSEYNEVENVNEEDREMFKIDWSFWTQVVND
YATVASNEPENLEAHVTNGIPPQIRGIIW-------------------------------
------QLMANSKSREMEDIYETLLDTECLHEATIRRDLRRTKFVAEDKMESLYKVIKVY
SVYDPDVGYTQGMGFIAAPLLINCENEAESFGLLVGLMKNYGLRELFLPGMPGLMLMLYQ
FDRLLEEHSPSLYNRLIREGISSTMYATQWFLTFFAYKFPLEFVLRIFDIVFVEGIEVLL
KFAVNLMLKNEETLVKLRFDELLDFLKDELFNYYLMGNQDDASVVQMGLSNGNSFKGNDD
GTFSYNVDLFVHDA----------------------------------------------
------------------------------------------------------------
---MTGVYITPLTLRRYRGEYVEIHEKEQKKEDHYESLRIQNHQLQREAQKLEHDYSILN
K--------------ENISAANELIQNRLNMEMLLDEKNDLINTITDIK-----------
---------------SQIEEEIRKQNLPN--------------PDASLPKADLREDLERT
IS------RNNEVMRENGQLEERITELQAEIDELININKEQVSTASLLERDSKAKGRKGW
TGFKK-------------------------------VFK---------------------
-------------------------
>gnl|BL_ORD_ID|10951 @Takifugu_rubripes@ jgi|Takru4|737563|fgh5_pg.C_scaffold_216000008
MKLNQERWKEGNKRGRQQGIKAKGREEEWKGQIKEGMEDRKEGRKDDGWMDGWMDGWMDG
WMEQKKPERKKKKQGRAKEGRKEGRQEGRKEGMLTMPFRQ--------------------
-----------------------------------TGRQTDRWIFSAFSKDTEGISGGGG
LWSFAVLSQQLTFHLQQLHRQTEQELSNIQLQMKRRKKSHCVPACVLLTVNVQMVVGGCR
LTLLACTLCTPALSDLAERHFDWSHFCQTRQAKTHLGIQGAPADESLTCMHDYPDEAPVT
TRIKGTMRGFLALFTFALFHVRGKPCWQFATDAFSLKAGLRDKLETLEFFPSSGALLQTE
LRYLCCVSDSEMIKLNRESKCAATQQTQNRLLQIEGQRQQLRTDLVDLQQKKKQREEELK
TPRSLQESAIQLCSCRQLQASIGERLLQSERLVFQQEALSSLYSLLSQDLQRYQEETQRL
TCFTQRILTAPHRWDQEEPCRPTGCSMQEKTEAEQGSNMDNMKPDSSSHFFAFFCLVVLR
RCSSNPQREDPPGGVLCSQASERHSQPRLVSLFSGEVARRVRGLRPLATLHPGVSKFKPL
DSRHFISLSGTGILLMIVIKVGFKQHPPEPSPSQTASNHSNQTSSQTWRSEQKKPPVGLP
RGPSLHRAGSIKDLISRFSSVDQKFYTGSLSFSRRGRLQKSASIEVLDFPGQETGSSALS
STKPVQS--------------PVLDEVESLKLKEIKSLLPSPTITTLQDTSSKKTEPAEK
TTKATQAEQNSDQTDSKAAHMTQTSDSGSDSVADSGMG----------------------
----SESEMDLNKQPDSLSEEEPSTPRIVSTSQNPKYQLFLGNDIKTNGESGKDADGPGG
GESLRENGP-----KLARWETTRVGLNHYRGSLESLASRDLDANSDRVGVGDSFPRVFNS
PYSANASLDYNPIHRMSEYRLQSGMSPATSEVNLFT------------------------
--RSTSPVGVPVPTMAASRTRFSTYESMLRRRAELNNP------MPPTLNTHYSMRSATL
GGLNKKDYIEELTKQLDVCQKRNQFLEAESVEMEKERNQIRLEMRSLLVNNEDLLRT---
----------------------------NTQMTNEMRRMREQMIEMERANQSMGDKFRAM
EIEVKEARNVMVEANNQEYAFNYLQQSL------------------------NNKIQDAE
ESLDKQAQYAQTLSEKLWLAERQ----------------------------------LEE
LQIDKETKEKKSSELQSTILKLETECHAQQ------------------PPNRSFMGYSEG
HGDTFRLCLQVSGKLIDKEQILEEEIQLRERIQLQCKQAERMVEDLKMELHTTNQ-----
-------------------------AKDELAKQVKVTQEKMLDMESDLEELHDSEQRWAA
KHKRAIEQTEQLQM----------------------------------------------
----------------------------------------------------------KL
IQEKDQNDHLEIEKATLERQLRELRLEVEDLHNSRVQEDVISRAETRVKELENTLRLEE-
---------------RNKAILNNTITKLERRINEINDQMEE---------EHRIANEQKD
LMTQRIRSLKRQLNEAEEESSRKEAQSRH--------------S---------QRELAEE
RETNARLQRQLLEQHLQTKRKETLTIRQTLDNLRLDLSVDEEDEDQTHQPEETITKV---
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|4832 @Saccharomyces_cerevisae@ gi|6324375|ref|NP_014445.1| Fpk1p [Saccharomyces cerevisiae S288c]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------AGHHHEHEQERDHEQEHEHDSLQRPTTGSERTRS
ISFSKLLTRSWK------------------------------------------------
------------------------------------------------------------
--------------------------------------RNASSSNNMSVSSVNLYSDPEN
SRESDHNNSGSEGQSSRFSKLKSMFQSGNSSKNASAHNSSQSSLEGDSASSS--------
---------------------SKLRYVKPMTSVANASPASPPLSPTIPETDVLQTPKMVH
IDQHEHEREHSNCGSPIMLSSS----SFSPTVARTGTG----------------------
----RRRSPSTPIMPSQNSNNSSSTSAIRPNNYRHHSGSQGF------------------
----SSNNPFRERAGTV------------------------------------------R
SSNPYFAYQGLPTHAMSSHDLDEG------------------FQPYANGSGIHFL-----
--STPTSKTNSLTNTKNLSNLSLNEIKENEEVQEFNNEDFFFHDIPKDLSLKDTLNGSPS
RGSSKSPTITQTFP---------SIIVGFDNEYEEDNNNDKHDEKEEQQTTTDNKTR---
----NLS------------PTKQNGKATHPRIKIPLRRAASEPNGLQLASATSPTSSSAR
KTSGSSNINDKIPGQSVPPPNSFFPQEP------------------------SPKISDFP
EPRRSRRLRTKSFSNKFQD-----------------------IMVGPQSFEKIRLLGQGD
VGKVFLVREKKTNRVYALKVLSKDEMIKRNKIKRVLTEQEILATSNHPFIVTLYHSFQSE
DYLYLCMEYCMGGEFFRALQTRKTKCICEDDARFYASEVTAALEYLHLLGFIYRD-----
-------------------------LKPENILLHQSGHIMLSDFDLSIQAKDSKVPVVKG
SAQSTLVDTKICSDGFRTNSFVGTEEYIAPEVIRGNGHTAAVDWWTLGILIYEMLFGFTP
FKGDNTNETFTNILKNEVSFPNNNEISRTCKDLIKKLLTKNESKRLGCKMGAADVKKHPF
FKKVQWSLLRNQEPPLIPVLSEDGYDFAKLSSNKKRQTSQDSHKHLDEQEKNMFEERVE-
---------------YDDEVSEDDPFHDFNSMSLMEQDNNSMIY----------------
---------------GNTNSYGKIAYTPN--------------S---------NRSRSNS
HR----------------------------------------------------------
------------------------------------TFFK--R-----------------
-------------------------
>gnl|BL_ORD_ID|18738 @Homo_sapiens@ gi|222418791|ref|NP_001138430.1| EF-hand calcium-binding domain-containing protein 4B isoform a [Homo sapiens]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------AAPD
GRVVSRPQRLGQGSGQGPKGSGACLHPLDSLEQKETQEQTSGQLVMLRKAQEFFQTCDAE
GKGFIARKDMQRLHKELPLSLEELEDVFDALDADGNGYLTPQEFTTGFSHFFFSQNNPSQ
EDAGEQVAQRHEEKVYLSRGDEDLGDMGEDEEAQFRML-----------------MDRLG
AQKVLEDESDVKQLWLQLKKEEPHLLSN--------------------------------
----FEDFLTRIISQLQ------------------------------------EAHEEKN
ELECALKRKIAAYDEEIQHLYEEMEQQIKSEKEQFLLKDTERFQARSQELEQKLLCKEQE
LEQLTQKQKRLEGQCTALHHDKHETKAENTKLKLTNQE------LARELERTSWELQDAQ
-----------------------QQLESLQQEACKLHQEKEMEVYRVTESLQREKAG---
-----------------------------LLKQLDFLRERNKHLRDERDICFQKNKAAKA
NTAASRASWKKRSGSVIGKYVDSRGILR--------------------------SQSEEE
EEVFGIPRRSSLGLSGYPLTEEEPGTGEPGPGGPYPRPLRRIISVEEDPLPQLL------
-----------DGGFEQPLSKCSEEEEVSD------------------------------
-----------------------------------------------------QG-----
-------------------------VQGQIPEAPPLKLTPTSPRGQPVGKEALCKEESSP
SAPDRLFKIVFVGN----------------------------------------------
-------SAVGKTSFLRRFCEDRFSPGMAATVGIDYRVKTLNVDNSQVALQLWDTAGQER
YRCITQQFFRKADG------VIVMYDLTDKQSFLSVRRWLSSVEE---------------
---------------------------------AVGDRVPVLLL----------------
---------------GNKLDNEKEREVP--------------------------RGLGEQ
LATENNL-----------------------------------------------------
------------------------------------IFYECSAYSGHNTKESLLHLARFL
KEQEDTVREDTIQVGHPAKKKSCCG
>gnl|BL_ORD_ID|30422 @Homo_sapiens@ gi|71565160|ref|NP_683515.3| structural maintenance of chromosomes protein 1B [Homo sapiens]
MAHLELLLVENFKSWRGRQVIGPFRRFTCIIGPNGSGKSNVMDALSFVMGEKIANLRVKN
IQELIHGAHIGKPISSSASVKIIYVEESGEEKTFARIIRGGCSEFRFNDNLVSRSVYIAE
LEKIGIIVKAQNCLVFQGTVESISVKKPKERTQFFEEISTSGELIGEYEEKKRKLQKAEE
DAQFNFNKKKNIAAERRQAKLEKEEAERYQSLLEELKMNKIQLQLFQLYHNEKKIHLLNT
KLEHVNRDLSVKRESLSHHENIVKARKKEHGMLTRQLQQTEKELKSVETLLNQKRPQYIK
AKENTSHHLKKLDVAKKSIKDSEKQCSKQEDDIKALETELADLDAAWRSFEKQIEEEILH
KKRDIELEASQLDRYKELKEQVRKKVATMTQQLEKLQWEQKTDEERLAFEKRRHGEVQGN
LKQIKEQIEDHKKRIEKLEEYTKTCMDCLKEKKQQEETLVDEIEKTKSRMSEFNEE----
------------------------------------------------------------
------------------------------------------------------------
--------------------LNLIRSELQNAGIDTHEGKRQQKRAEVLEHLKRLYPDSVF
GRLFDLCHPIHKKYQLAVTKVFGRFITAIVVASEKVAKDCIRFLKEERAEPETFLALDYL
DIKPINERLREL---------KGCKMVIDVIKTQFPQLKKVIQFVCGNGLVCETMEEARH
IALSGPERQKTVALDGTLFLKSGVISGGSSDLKYKARCWDEKELKNLRDRRSQKIQELKG
LMKTLRKETDLKQIQTLIQGTQTRLKYS--------------------------------
----QNELEMIKKKHLVAFYQEQSQLQSELLNIESQCIMLSEGIKERQRRIKEFQEKIDK
VEDDIFQHFCEEIGVENIREFENK------------------------------------
--HVKRQQEIDQKRLEFEKQKTRLNVQLEYSRSHLKKKLNKINTLKETIQKGSEDIDHLK
K----------------------AEENCLQTVNELMAKQQQLKDIRVTQNSSAEKVQ---
---------------------------------TQIEEERKKFLAVDREVGKLQKEVVSI
QTSLEQKRLEK-----------------------------------------HNLLLDCK
VQDIEIILLSGSLDDIIEVEMGT---------------EAESTQATIDIYEKEEAFEIDY
SSLKEDLKALQSDQEIEAHLRLLLQQVASQ------------------------------
------------------------------------------------------------
------------------------------EDILLKTAAPNLRALENLKTVRDKFQESTD
AFEASRKEARLCRQ----------------------------------------------
------------------------------------------------------------
--------------EFEQVKKRRYDLFTQCFEHVSISIDQIYKKLCRNNSAQAFL-----
---------------------------------SPENPEEPYLE----GISYNCVAPGKR
FMPMDNLSGGEKCVAALALLFAVHSFRPAPFFVLDEVDAALDNTNIGKVSSYIKEQTQDQ
FQMIVISLKEEFYSRADALIGIYPEYDDCMFSRVLTLDLSQYPDTEGQESSKRHGESR--
------------------------------------------------------------
-------------------------
>gnl|BL_ORD_ID|12291 @Ciona_intestinalis@ jgi|Cioin2|298062|estExt_fgenesh3_kg.C_chr_08q0097
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------PASQKL
VNEFISITGSDETTANHLLEAFSNNLELAVSNYLDENASKNNSENGSAASKNNKDKVRAP
----------------------------------------------IPQTRGVLVEESHT
WTPAPRRRQHSVFDGFRNFKAEADDTTGSTDKNVKRLE----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--DLFRPPLDMMHRGSFESAREEGTKSKKWLLVNIQNTKEFACQV---------------
-----------------------LNRDVWSSSSVKTIIKENFVFWQVYSDSSEGERF---
-------------------------------------------MTFYSINGWPHVSILDP
RTGGRMGVLTNITKDSV-------------------------------------------
------------------------------------------------------------
--------IQEVRAFLDGHGTLDPEEPPTK------------------------------
------------------------------------------------------------
---------------------------RTKRDILDASEDSQLAAAIAASLRENTAKKVVD
SESEFEISSESEDE----------------------------------------------
------------------------------------------------------------
------------------KKNSEEKDGNKEQEDQKIKEDVKTEQKPRKPLVKIFPKK---
---------------KKPNVENSNSEKTSEMFSAPSKQVEPTSL----------------
-----------NCNGNSRSTNPVSNGASK--------------CKLVLRFPNGKRDIITM
YASDTLKDLAHFISSKDFDLKFYEFLTNFPRKKLSSMDDSITLDAAGLCPQDT-------
------------------------------------IFIQEKL-----------------
-------------------------
>gnl|BL_ORD_ID|3267 @Cladonia_grayi@ jgi|Clagr2|113146|estExt_fgenesh1_pm.C_50079
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GVGR--------------------------------------------
------------------------------------------------------------
-------------------RMK-KQGPPPDLGAIAAKKRNAPNIDDSTRGKKRKASGEIK
TQSLGRVSTNGTAKSSHKKSTKGSVADEDIKQAKRSRKMPAKPAPMMSGALL--------
------------------------------------------------------------
---------D-------ESSDDDAADLLGGDNADDNDE--------------------LL
SGSANSMLEDGERLQDEFPDSGSSVY---DSDPQHERARFSEDDDESDAEERLTAAN---
----IEGLSRRLDEEQE-------------------------------------------
------------------------------------------------------------
----------------------EEAAEAQLELEEAALQTNIDGDRPKVLEDDDDDE----
GAVSRLAP-------------DLQLLRSRITDAVRVL--DDFAKLAEEGRSRAEYTA---
----QLL------------KDICLYYGYSLYLAEKLFNLFPPREAFAFFEANESARPVVL
RANTLRTHRRELAQSLINRGVTLEPVGKWSKVGLQVFESQVPLGATPEYLAGHYILQAAS
SFLPVMALAPQEHERILDMAAAP-------------------------------------
---------GGKTTYIAALMKNTGCIFAND------------------------------
------------------------------------------------------S-----
-------------------------NKSRAKGLIGNVHRLGVKNTIICSYDAKEFPRVIG
GFDRVLLDAPCSGT----------------------------------------------
------------------------------------------------------------
---------------------------GVIAKDPSVKTNKTEKDFMQLPHLQKQLLLCAI
DSVDHTSKTGGYIVYSTCSV-------------TVEENEQVVQY----------------
---------------------------AL--------------A---------KRPNVKL
VETGLTFGVDGFVSYMGKQFDPKMKMTKRYYPHAYNVDGFFVSKFKKVAPS--SGGRARD
EIADRAGNGGDLTAEDKTLVIAGDEEDEPFGDFNDSEDEKYIEKARRNQLRRKGIDPRAV
NRKKRFQGAGICKLRLGCKSSYYRG
>gnl|BL_ORD_ID|1466 @Ustilago_maydis@ jgi|Ustma1|1467|UM01467
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------GR--------------------------------------------
------------------------------------------------------------
-------------------RSKNKQAPPQPL-------REDHSLTNTIKGKRKAHESSLP
VKKAKIAPTSTKALRSAPAAVARSIKTSNSKTGANG-KAKARAATIEESEDE--------
------------------------------------------------------------
---------DRDEEVELEGEEDEEVDQEEEDEEEEEEEDEEEVEEDPLEALGLPKNGKLS
ERQRKKALAEAERLEELLKSQGLSLESDDDDDEQDEDLEGSEEGEEGSEQEEL-------
------GDEFDLGEEDI-------------------------------------------
------------------------------------------------------------
----------------------EGEEGDQVELD--------DGDDDKDDEDDEDDEDEEA
GGAEFMLPTLEEREAEKVRGADLQLVHMRIQEVVTVL--SNFKKLAVDGRSRSEYVE---
----QLL------------ADICTYYGYNAFLAEKLFELFTPAEAIEFFEANETPRPVTI
RANTLRTRRRDLAQALINRGVNLEPIGAWSKVGLQVFESSVPIGATPEYLAGHYMLQAAS
SFLPCIALAPQPNERVLDMASAP-------------------------------------
---------GGKSTYLSALMQNTGTVFAND------------------------------
------------------------------------------------------S-----
-------------------------NKNRIKSLVANIHRLGCKNVVVCNYDGRQFPKVIG
GFDRVLLDSPCSGT----------------------------------------------
------------------------------------------------------------
---------------------------GVIHKDQSVKVNKSERDFALLTHLQKQLLLCAI
DSVNPRSSTGGYVVYSTCSV-------------MVEENEEVVQY----------------
---------------------------AL--------------R---------KRSNVKI
VDTGIQFGRDGFKSFGRSKFDERMVYARRIFPHVHNLDGFFVCKLKVNPPSNNNASAARS
EKPNSATAG---IVDDQDQDDVQQDTDNGLVSLDNPEDQKLMQKSLKKATAK--------
--------------------GKARR
