>Mulan_NP_078820
mesggrpslcqfillgttsvvtaalysvyrqkarvsqelkgakkvhlgedlksilseapgkcvpyaviegavrsvketlnsqfvenckgviqrltlqehkmvwnrtthlwndcskiihqrtntvpfdlvphedgvdvavrvlkpldsvdlgletvyekfhpsiqsftdvighyisgerpkgiqeteemlkvgatltgvgelvldnnsvrlqppkqgmqyylssqdfdsllqrqessvrlwkvlalvfgfatcatlffilrkqylqrqerlrlkqmqeefqeheaqllsrakpedreslksacvvclssfkscvflecghvcsctecyralpepkkcpicrqaitrviplyns
