>Mulan_NP_078820
CVVCLSSFKSCVFLECGHVCSCTECYRALPE-----PKKCPICRQAITRVIPLYNS
>SPL2_NP_564653
CVICVSRRRVPAFIPCGHVVCCRRCASTVER---ELNPKCPVCLQSIRGSMRVYYS
>Arabidopsis_lyrata_474546_PACid_16040628
CVICVTRRRVPAFIPCGHVVCCRVCASTVER---ELNPKCPVCLQSIRGSMRVY--
>Glycine_max_Glyma16g01030.1_PACid_16301042
CVICLMRRRRSVFIPCGHLVCCQGCAISVER---EVAPKCPVCRQEIRDSVRTY--
>Ricinus_communis_29706.m001280_PACid_16806294
CVICLMRRRRAAFIPCGHLVCCQICAISVER---EVSPKCPLCRQAVRNSIRIF--
>Aquilegia_coerulea_v1.024769m_PACid_18143411
CVICLMRRKRAAFVPCGHFVCCYRCALSVER---DSAPKCPLCRQDIRTSVRIY--
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
CVICLMRRRVPAFIPCGHIACCQPCALSVER---ELTPKCPVCRQEIRGSMRVF--
>Zea_mays_GRMZM2G004023_T01_PACid_19546755
CVVCLRKRRRAAFIPCGHLVCCSECALTIER---TPHPLCPMCRQDIRYMMRVY--
>Setaria_italica_Si036246m_PACid_19684534
CVVCLRKRRKAAFIPCGHLVCCCKCALRMER---ETEPLCPMCRQDIRYMMRIY--
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
CVICLRKRRKAAFIPCGHLVCCCKCALIVER---QFDPLCPMCRQDIRYMIRIY--
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
CVICLRKRRKAAFVPCGHLVCCCNCAKRVEL---MNEPLCPVCRQDIQYMLRVY--
>Selaginella_moellendorffii_91152_PACid_15413277
CVVCLLRRKRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSGYIRVY--
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
CVVCLLRRRRAAFIYCGHRVCCMGCAERVEH---GANPRCPVCRQSVTGIVRVY--
>Physcomitrella_patens_Pp1s15_293V6.1_PACid_18050435
CVVCLLRRRRSAFIHCGHRVCCIVCARRVQQ---GADPRCPVCRQ-----------
>Aquilegia_coerulea_v1.022773m_PACid_18144013
CTICTMRRKKYACVPCGHLVCCHKCARSIQH---DSTARCPECRHIMWFRLDVS--
>Aquilegia_coerulea_v1.012733m_PACid_18142466
CVV-------SVFVPCGHLVCCQTCAPLVAR-----DRRCPICRQYIQKYIITY--
>Arabidopsis_thaliana_AT4G24204.3_PACid_19646975
CVICFEERRNCFFVPCGHSATCRGCAQRILS---EESKVCPICRRVI---------
>Arabidopsis_lyrata_329238_PACid_16062111
CVICFEERRNCFFVPCGHSATCRGCAQKILS---EENKVCPICRRVI---------
>Physcomitrella_patens_Pp1s212_60V6.1_PACid_18042245
CTLCLDAPKNSFFDPCGHRCTCYSCGLRIQR---GDSNRCPICRQTIRTVRRIY--
>Brachypodium_distachyon_Bradi1g28820.1_PACid_16474995
CVICLDAPVEGACIPCGHMAGCMSCLKDIES----KKWGCPICRAKINQIIRLY--
>Oryza_sativa_LOC_Os07g26490.1_PACid_16871541
CVICLDAPVEGACIPCGHMAGCMSCLKDIES----KKWGCPICRAKINQIIRLY--
>Zea_mays_GRMZM2G133396_T01_PACid_19531762
CVICLDAPVEGACIPCGHMAGCMSCLKDIES----KKWGCPICRATINQVVRLY--
>Setaria_italica_Si029529m_PACid_19712709
CVICLDAPVEGACIPCGHMAGCMSCLKDIES----KKWGCPICRATINQVVRLY--
>Aquilegia_coerulea_v1.004114m_PACid_18162631
CVICLDAPIEGACIPCGHMAGCMSCLNGIQA----KKWGCPVCRAKIQQVIKLY--
>Arabidopsis_thaliana_AT3G23280.1_PACid_19663410
CAICLDAPSEAVCVPCGHVAGCMSCLKEIKS----KNWGCPVCRAKIDQVIKLYR-
>Arabidopsis_lyrata_898841_PACid_16047400
CAICLDAPSEAVCVPCGHVAGCMSCLKEIKS----KNWGCPVCRAKIDQVIKLYR-
>Glycine_max_Glyma10g32440.1_PACid_16280695
CVICLDAPAEGACIPCGHVAGCMSCLNEVKS----KKWGCPVCRAKIDQVIKLYH-
>Carica_papaya_evm.model.supercontig_44.48_PACid_16420187
CVVCLDAPSEAACVPCGHVAGCISCLNEIKA----KKWGCPVCRAKIDQVVKLYR-
>Arabidopsis_thaliana_AT4G14365.1_PACid_19648313
CVICVDAPSEAVCVPCGHVAGCISCLKEIEN----KKMGCPVCRANIDQVIKLY--
>Arabidopsis_lyrata_493466_PACid_16066361
CVICVDAPSEAVCVPCGHVAGCISCLKEIKN----KKMGCPVCRANIDQVIKLY--
>Ricinus_communis_29611.m000230_PACid_16803674
CIICWEAPIEGACIPCGHMAGCMACLSEINA----KKGVCPVCRAKIKQVIRLY--
>Zea_mays_GRMZM2G081965_T01_PACid_19581586
CCVCCDSQIDSLLYRCGHMCTCSKCANELVR----SGGKCPLCRAPIVEVVRAY--
>Setaria_italica_Si016443m_PACid_19688508
CCVCCDTQIDSLLYRCGHMCTCSKCANELVR----SGGKCPLCRAPIVEVVRAY--
>Oryza_sativa_LOC_Os02g57750.1_PACid_16843989
CCVCCDAQIDSLLYRCGHMCTCSKCANELIR----SGGKCPLCRAPIAEVVRAY--
>Brachypodium_distachyon_Bradi4g38750.1_PACid_16499782
CCVCCDTPIDSLLYRCGHMCTCSKCANELVR----SGGKCPLCRAPIIEVIRAY--
>Ricinus_communis_28546.m000072_PACid_16801083
CCVCCDSHIDSLLYRCGHMCTCSKCANELVR----GGGKCPLCRAPIVEVIRAY--
>Carica_papaya_evm.model.supercontig_53.170_PACid_16422237
CCVCCDSHIDSLLYRCGHMCTCSKCANELVR----GGGKCPLCRAPIVEVIRAY--
>Glycine_max_Glyma20g33300.1_PACid_16317711
CCVCCDNHIDSLLYRCGHMCTCSKCANELIR----GGGKCPLCRAPIVEVVRAY--
>Glycine_max_Glyma10g34240.1_PACid_16280900
CCVCCDNHIDSLLYRCGHMCTCSKCANELIR----GGGKCPLCRAPILEVVRAY--
>Aquilegia_coerulea_v1.000901m_PACid_18147189
CCVCCDSHIDSVLYRCGHMCTCSKCANELVR----SGGKCPLCRAPIVEVIRAY--
>Arabidopsis_thaliana_AT5G04460.1_PACid_19667116
CCVCCDNHIDALLYRCGHMCTCSKCANELVR----NGGKCPLCRAPIIEVIRAY--
>Arabidopsis_lyrata_487227_PACid_16053924
CCVCCDSHIDALLYRCGHMCTCSKCANELVR----NGGKCPLCRAPIIEVIRAY--
>Ricinus_communis_29589.m001277_PACid_16803318
CCICSDSNIDSLLYRCGHMCTCSKCANELVQ----KGEKCPMCKAPVIEVIRAY--
>Glycine_max_Glyma12g30330.1_PACid_16288390
CCICCESNINSLLYRCGHMCTCSKCANDLLQ----SRRKCPMCQAPVVEVIRAY--
>Glycine_max_Glyma12g08770.1_PACid_16286898
CCICCESNIDSLLYRCGHLCTCSKCANELLQ----SRRNCPMCQAPVVEVIRAY--
>Physcomitrella_patens_Pp1s266_64V6.1_PACid_18053468
CCICCDKQINSLLYRCGHMCTCLQCANEIIY----NSGTCPMCRAPIVEVVRAF--
>Oryza_sativa_LOC_Os03g01720.1_PACid_16844435
CCICCDRQIDSLLYRCGHMCTCSKCASELLH----GVGKCPLCRAPIVEGL-----
>Brachypodium_distachyon_Bradi1g78060.1_PACid_16480756
CCVCCDKQIDSLLYRCGHMCTCSKCARELLH----GVGRCPLCRAPI---------
>Glycine_max_Glyma15g16660.1_PACid_16299010
CCICYEMKVDSVLYRCGHMCTCLKCANELQW----NSGKCPICRAKIEDVVRVY--
>Glycine_max_Glyma09g05320.1_PACid_16274857
CCICYEMKVDSVLYRCGHMCTCLKCANELQW----NSGKCPICRAKIVDVVHVY--
>Zea_mays_GRMZM2G036697_T01_PACid_19542768
CVICLSEPRDTTVLPCRHMCMCSECAKVLRY----QTTRCPICRQPVE--------
>Setaria_italica_Si035963m_PACid_19683186
CVICLSEPRDTTVLPCRHMCMCSECAKVLRY----QTTRCPICRQPVE--------
>Aquilegia_coerulea_v1.007182m_PACid_18140833
CVICLSEPRDTTVLPCRHMCMCSGCAKVLRF----QTNRCPICRQPVE--------
>Arabidopsis_lyrata_478299_PACid_16061774
CVICLSEPRDTTVLPCRHMCMCSGCAKVLRF----QTNRCPICRQPVE--------
>Ricinus_communis_28076.m000421_PACid_16799878
CVICLSEPRDTTVLPCRHMCMCSTCAKVLRF----QTDRCPICRQPVE--------
>Oryza_sativa_LOC_Os10g13670.1_PACid_16884438
CVICLSEPRDTTVLPCRHMCMCSECAKVLRY----QTNRCPICRQPVERLLEI---
>Oryza_sativa_LOC_Os03g15000.1_PACid_16846017
CVICLSEPRDTTVLPCRHMCMCSECAKVLRY----QTTRCPICRQPVERLLEI---
>Brachypodium_distachyon_Bradi1g67780.1_PACid_16479507
CVICLSEPRDTTVLPCRHMCMCSECAKVLRY----QTTRCPICRQPVERLLEI---
>Carica_papaya_evm.model.supercontig_102.1_PACid_16404826
CVICLSEPRDTTVLPCRHMCMCSGCAKVLRF----QTNRCPICRQPVERLLEI---
>Physcomitrella_patens_Pp1s131_9V6.1_PACid_18045395
CVVCMSEPRDTTVLPCRHMCMCSECAKVLRF----QTNRCPICRTPVERLLEI---
>Arabidopsis_thaliana_AT3G06140.1_PACid_19662767
CVICMTEAKDTAVLPCRHLCMCSDCAKELRL----QSNKCPICRQPIEELLEI---
>Arabidopsis_lyrata_317476_PACid_16060130
CVICMTEAKDTAVLPCRHLCMCSDCAKELRL----QSNKCPICRQPIEELLEI---
>Ricinus_communis_29844.m003308_PACid_16811015
CVICMTEPKDTAVLPCRHMCMCSDCAKELRL----QSNKCPICRQPIDELIEI---
>Glycine_max_Glyma07g38670.1_PACid_16269181
CVICMTEPKDTAVLPCRHMCMCGDCAKALRL----QSNKCPICRQPIEELIEI---
>Glycine_max_Glyma15g11100.1_PACid_16298398
CVICMTEPKDTAVLPCRHMCMCSECANALRQ----QSNKCPICRQPIEELIEI---
>Aquilegia_coerulea_v1.005917m_PACid_18144975
CVICMSEPKDTAVLPCRHMCLCCECAKELRL----QTNKCPICRQPIEQLIEI---
>Glycine_max_Glyma13g27930.1_PACid_16291813
CVICMTEPKDTAVLPCRHMCMCSECANAHRL----QSNKCPICRQSIEELIEI---
>Carica_papaya_evm.model.supercontig_16.23_PACid_16410055
CVICMSEPKDTAVLPCRHMCMCSDCAKALRV----QSNKCPICRQPIE--------
>Brachypodium_distachyon_Bradi2g26290.1_PACid_16484039
CVICLTEPRDTAVFPCRHLCMCSECAQALRL----QSNKCPICRQPVEKLIEI---
>Arabidopsis_lyrata_909929_PACid_16049698
CVICLTEPKNTAVMPCRHLCLCSDCAKELRF----QSNKCPICRQPIAELLEI---
>Arabidopsis_thaliana_AT5G19080.1_PACid_19665517
CVICLTEPKDTAVMPCRHLCLCSDCAEELRF----QTNKCPICRQPIHELVK----
>Carica_papaya_evm.model.supercontig_48.20_PACid_16420840
CVICLAEPKDTAVLPCRHMCMCSKCAKELRL----LSKKCPICRQPI---------
>Glycine_max_Glyma13g40170.1_PACid_16293251
CVICLSEPPDITVLPCRHMCMCSGCANLLKV----HTANCPICRYPVE--------
>Physcomitrella_patens_Pp1s313_100V6.2_PACid_18071841
CAVCYRDAANTVLLNCSHMCCCTVCSRAV--------KLCPICNNKV---------
>Zea_mays_GRMZM5G869246_T01_PACid_19628118
CKVCFESAAAAVLLPCRHFCLCKPCSLAC--------SECPLCRTRIADRIITF--
>Oryza_sativa_LOC_Os10g36880.1_PACid_16886503
CKVCFESATAAVLLPCRHFCLCKPCSLAC--------SECPLCRTRIADRIITF--
>Setaria_italica_Si034031m_PACid_19682087
CKVCFESATAAVLLPCRHFCLCKPCSLAC--------SECPLCRTRIADRIITF--
>Aquilegia_coerulea_v1.000321m_PACid_18148986
CKVCFEAPTAALLLPCRHFCLCKPCSLAC--------SECPLCRTKI---------
>Arabidopsis_thaliana_AT4G39050.1_PACid_19649007
CKVCFESPTAAILLPCRHFCLCKSCSLAC--------SECPICRTKI---------
>Arabidopsis_lyrata_327857_PACid_16049935
CKVCFESPTAAILLPCRHFCLCKSCSLAC--------SECPICRTKI---------
>Carica_papaya_evm.model.supercontig_150.41_PACid_16409496
CKVCFESPTAAILLPCRHFCLCKSCSLAC--------SECPICRTKI---------
>Glycine_max_Glyma06g01130.1_PACid_16261298
CKVCFESPTAAILLPCRHFCLCKSCSLAC--------SECPICRTSI---------
>Glycine_max_Glyma11g12050.1_PACid_16283586
CKVCFQSSTAAILLPCRHFCLCKSCSLAC--------SECPLCRTNI---------
>Brachypodium_distachyon_Bradi3g30550.1_PACid_16491601
CKVCFESATAAVLLPCRHFCLCKPCALAC--------SECPLCRTRI---------
>Selaginella_moellendorffii_77786_PACid_15420973
CKVCFEAATAAVLLPCRHFCLCQPCAVAC--------TECPLCRSSISDRIVTF--
>Selaginella_moellendorffii_97410_PACid_15410678
CKVCFEAPTAAVLLPCRHFCLCKSCAIAC--------TECPLCRSGITDRIITF--
>Zea_mays_GRMZM2G084819_T02_PACid_19558601
CRICLNAEVNMTIIPCGHV-LCNRCSSSV--------SRCPFCRTQVARMMKIFR-
>Setaria_italica_Si020938m_PACid_19702032
CRICLNAEVNMTIVPCGHV-LCNRCSSSV--------SRCPFCRTQVSRMMKIFR-
>Brachypodium_distachyon_Bradi5g26020.1_PACid_16503426
CRVCLNSEVNMTIIPCGHV-LCNRCSSSV--------SRCPFCRTQVSRLMKIFR-
>Glycine_max_Glyma09g41880.1_PACid_16278032
CRVCLSSEVDITIVPCGHV-LCRRCSSAV--------SRCPFCRLQVTKAIRIFR-
>Physcomitrella_patens_Pp1s78_164V6.1_PACid_18063332
CRVCLTNEVDTIVIPCGHV-LCQNCSRAV--------TRCPFCRRSVTISQRLYR-
>Selaginella_moellendorffii_152901_PACid_15423420
CRICLNSEVNSLLVPCGHV-LCHSCCSSL--------SRCPFCRQFVTSIHRMFR-
>Chlamydomonas_reinhardtii_Cre02.g110000.t1.2_PACid_19869670
CAICMEKPIQVALVPCGHANVCRRCSRRL--------TRCPFCRKEI---------
>SPL1_NP_564745
CVVCLDQKYNTAFVECGHMCCCTPCSLQL--------RTCPLCRERIQQVLKIYRH
>Arabidopsis_lyrata_338432_PACid_16045815
CVICHDQKYNTAFVQCGHMCCCLTCSLRL--------TTCPLCREQIQQVLKIYRH
>SP1
CVICLEQEYNAVFVPCGHMCCCTACSSHL--------TSCPLCRRRIDLAVKTYRH
>Arabidopsis_lyrata_474968_PACid_16053684
CVICLEQEYNAVFVPCGHMCCCTACSSHL--------TSCPLCRRRIDLAVKTYRH
>Brachypodium_distachyon_Bradi1g19510.1_PACid_16473835
CVICLEQEYNAVFVPCGHMCCCMNCSSHV--------TNCPLCRRRIDQAVRTFRH
>Oryza_sativa_LOC_Os07g45350.5_PACid_16873617
CVICLEQEYNAVFVPCGHMCCCMNCSSHL--------TNCPLCRRRIDQAVRTFRH
>Zea_mays_GRMZM5G871572_T01_PACid_19559193
CVICLEQEYNAVFVPCGHMCCCMACSSHL--------TNCPLCRRRIDQAVRTFRH
>Setaria_italica_Si030396m_PACid_19714000
CVICLEQEYNAVFVPCGHMCCCMACSSHL--------TNCPLCRRRIDQAVRTFRH
>Zea_mays_GRMZM2G020574_T08_PACid_19536933
CVICLEQEYNAVFVPCGHMCCCVACSSHL--------TNCPLCRRRIDQAVRTFRH
>Aquilegia_coerulea_v1.007878m_PACid_18162338
CVICLEQEYNAVFVPCGHLCCCTTCSSHL--------SNCPLCRRRIDQVVRTFRH
>Glycine_max_Glyma10g02920.1_PACid_16278382
CVICLEQEYNAVFVPCGHMCCCTACSSHL--------TNCPLCRRQIEKVVKTFRH
>Carica_papaya_evm.model.supercontig_9.121_PACid_16428004
CVICLEQEYNAAFVPCGHMCCCMTCSSHL--------TNCPLCRRRIEQVLRTFRH
>Selaginella_moellendorffii_231449_PACid_15416766
CVICLEQEYNAVFVPCGHMCCCISCSAQL--------QNCPLCRRRIEQIVKTYRH
>Physcomitrella_patens_Pp1s175_124V6.2_PACid_18055474
CVICLEQDYNAVLVPCGHMCCCTSCSSQL--------SLCPLCRRHIDQVVKTFRH
>Physcomitrella_patens_Pp1s12_190V6.2_PACid_18048531
CVICLEQDYNAVFLPCGHMCCCTSCSAQL--------TSCPLCRRHIDKFVKTYRH
>Arabidopsis_lyrata_867782_PACid_16034683
CVICLEQKYDATFVKCGHMCCCLTCSLHV--------KTCPICRRPIEHVLKIDR-
>Chlamydomonas_reinhardtii_Cre03.g169050.t1.1_PACid_19872172
CVVCMDRDADVVFTGCGHLCACYGCSTNL--------TKCPICR------------
>Physcomitrella_patens_Pp1s304_2V6.1_PACid_18057177
CIVCIEHQASVQLMPCGHNLFCFSCVGGL--------LTCPLCRQPI---------
>Setaria_italica_Si028975m_PACid_19711851
CAMCLEEEVSVVFLPCGHQVVCAGCNQRHQE---VGMTECPSCRSPIE--------
>Glycine_max_Glyma17g16560.1_PACid_16305806
CIVCMKDEVSIVFLPCAHQVMCASCSDEYGR---KGKATCPCCRVQIQQRIRVF--
>Glycine_max_Glyma05g23770.1_PACid_16259408
CIVCMKDEVSIVFLPCAHQVMCASCSDEYGR---KGKAICPCCRVQIQQRIRVF--
>Zea_mays_GRMZM2G073049_T01_PACid_19518540
CPVCLSKPRDMAF-GCGHQ-TCSECGPQV--------TDCPICRRPIDTRVKLY--
>Arabidopsis_thaliana_AT3G01650.1_PACid_19661381
CPICLSNPKNMAF-GCGHQ-TCCECGPDL--------KVCPICRAPIQTRIKLY--
>Arabidopsis_lyrata_896079_PACid_16045152
CPICLSNPKNMAF-GCGHQ-TCCECGPDL--------KVCPICRAPIQTRIKLY--
>Glycine_max_Glyma19g22800.1_PACid_16312609
CPICLSNAKDMAF-GCGHQ-TCCECGQDL--------QSCPMCRSPINTRIKLY--
>Aquilegia_coerulea_v1.006122m_PACid_18147984
CPICLTNAKDLAF-QCGHM-TCRECGRNL--------STCPICRATIRSRLRVY--
>Glycine_max_Glyma08g17330.1_PACid_16271470
CPVCLTNARDLAF-GCGHM-TCRECGHKL--------TNCPMCRERITSRLRVY--
>Selaginella_moellendorffii_442650_PACid_15412376
CCVCMGRQKGAAFIPCGHT-FCRRCCKELQQ----ARGSCPLCNKEISDVLNLY--


>C_merolae_gnl_CMER_CML314C_similar_to_RING_zinc_finger_protein
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------LCIICMTD-PR--DTTV-LPCRHLCLCV-DCAQLLRVRS--------DRCPICRSPVD--------------------
>C_merolae_gnl_CMER_CMS172C_similar_to_ankyrin_1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CAVCADS-GPCVQWTV-YNCGH-CTCQ-PCAEQL------------SECPMCRVTITSRIRLY--------------
>C_merolae_gnl_CMER_CMG126C_similar_to_zinc_finger_protein
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CPICGEH-FR--APVL-LECGH-SFCS-ECIRRALVYR--------SECPQC-------------------------
>C_merolae_gnl_CMER_CMK039C_photoregulatory_zinc-finger_protein_COP1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CPICFDL-FR--AAVT-TRCGH-TFCF-SCIMRHFRNH--------KSCPVC-------------------------
>C_merolae_gnl_CMER_CMT222C_unknown_ring-finger_protein
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CTVCKAQ-EK--QVTL-LRCFH-MFCR-DCIQTNIANR-------NRKCPLC-------------------------
>C_merolae_gnl_CMER_CMO233C_hypothetical_protein__conserved
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CPLCMRL-LY--EPLT-TPCGH-TFCR-SCLARALDHA--------SYCPICR------------------------
>C_merolae_gnl_CMER_CME171C_similar_to_ring_finger_protein
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CSICFEVPLE--DPVV-TMCGH-LFCW-SCLHRWMAQH--------ATCPVCKSLVDRERVIPLYG-----------
>C_merolae_gnl_CMER_CMT287C_unknown_zinc-finger_protein
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------LCPICLDMLF---ETVE-LPCRH-RFCE-VCIQEARFSA--ELQGATLSCPLCQ------------------------
>C_merolae_gnl_CMER_CMT259C_hypothetical_protein
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------LCPICLDMLF---ETVE-LPCRH-RFCE-VCIQEARFSA--ELQGATLSCPLCQ------------------------
>C_merolae_gnl_CMER_CML287C_helicase-like_protein
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------RILEAEIESTALALELDRRLAEEQSDRKKGQLVYLQRLKSSCVEDLAAKRQEPCPICYRQLGS--ELVL-LPCGH-CFCI-ECTSSYLEARVYRQHSRSLPCPLCR------------------------
>C_merolae_gnl_CMER_CMT012C_similar_to_C3HC4_zinc-binding_integral_peroxisomal_membrane_protein_PEX10
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------EPVPTARRARNESRHRCVLCLDQ-CQ--DPTC-TACGH-VFCW-ICILDWVRQQ--------NSCPVCRREAQL-------------------
>C_merolae_gnl_CMER_CML213C_hypothetical_protein__conserved
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ADAAKRELEQSTQCPVCFERLHA--PSAL-VPCGH-VLCK-SCFVTLTTTL------EEHLCPTCRQVFD--------------------
>C_merolae_gnl_CMER_CMT363C_similar_to_glycogenin-interacting_protein
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CLICAEL-PR--EPLLCPSCGV-LFCE-RCATKWWRE----------------------------------------
>C_merolae_gnl_CMER_CMG190C_unknown_zinc_finger_protein
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------LSQIVRYVVFIIDVFVLTEGTWDDKGLWLFYNELLSLFLQLAAYLAFFTYVHLFYSLPLHILRDLAVTARTFRQRLIEFIRYRQVVRSMHTQFPNATEQELAAGDRTCIICREEMFGGAGAKK-LVCGH-IFHL-RCLRSWMERS--------MSCPTCRRDI---------------------
>C_merolae_gnl_CMER_CMM141C_similar_to_zinc_finger_protein
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SLESDCPVCGEYLFTSTNPIKFLRCGH-LMHA-SCYRRYAAAD--------YRCPLCKKSLA--------------------
>C_merolae_gnl_CMER_CMI164C_hypothetical_protein__conserved
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------VACGTIALPVLMRATRLLATRESWTQREELPVEIDLGKKYKYHSIFVCPVSREQSTPTNPPYL-LPCGH-VLCK-ETVNRLPRGN------TRFKCPYC-------------------------
>C_merolae_gnl_CMER_CMS206C_hypothetical_protein
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------LPYLCNWCLGQVSNQDQAVF-TDCAC-LFCSGTCASQL------------RRGPLC-------------------------
>C_merolae_gnl_CMER_CMT374C_zinc-finger_protein
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------VCLVCRERAT---FWAI-GSCAH-RICL-LCAHRIRCLY------RLRRCVVCNQDLEEMLVI---------------
>Danio_rerio_gi_148922854_ref_NP_001092230.1__mitochondrial_ubiquitin_ligase_activator_of_NFKB_1__Danio_rerio_
MEASGKPSTAQIVLLATSSALTAVLYTIYKRKSSHVARLREAKKMSLNPELKTILSEAPGKCVPYAVIEG
VVRSVKETLNSQFVDNCKGVIQRLTLNEKKMVWNRTTNLWNDCEKVIHQRTNTVPFDLAPHDDTVPTTVR
VLRPLDAAELDLETTYENFHPSQQSLTNVIGHFISGERPQGIQETEEMLRLGASMTGVGELVLDNNLVRL
QPPKKGLRYFLSRLDYDTLLSKQEGHLRIWRVLTVLLGLTACATFFYLLWRQYVLRKERRKEQSVLDEYR
KWQSKRFQELHLAKEDVSPTACTICLNHERSCVFLECGHVCACEGCYRALPEPKKCPICRATIDRIVSLY
NS
>Drosophila_melanogaster_gi_21356375_ref_NP_647847.1__CG1134__Drosophila_melanogaster_
MEFLHESVALGVDLLILGLCAREYVHYKRTAKVLKAAPQYNIDGDLKSVVERQRDKKIPYAVIRGTVTPI
GVPLRSSLVPSVSGVLQIVKLHEHRVTRGFAGFWTEQHKLLHESANEMPFELRNQSHGVEIVDALSAAVL
DVDVVYDNYEPSNLSLFDHVFGFFSGVRQRGLQTTEEVLREGSFLTAIGELELDGDTLRMQPSNEGPLFL
TTATKSTLIKRFEDAKTTTILKLVVCSTISAILVAFIAKKLYRKRKQEREEAKIRERLDTERRERRARSR
PHTLSQDQLCVVCSTNPKEIILLPCGHVCLCEDCAQKISVTCPVCRGSIVSKAAAFIA
>Mus_musculus_gi_18043560_gb_AAH19516.1__Mitochondrial_ubiquitin_ligase_activator_of_NFKB_1__Mus_musculus_
MESGSRPSLGQVILLGTSSMVTAVLYSIYRQKAQVAQELKGAKKIHLGEDLKGILSEAPGKCVPYAVIEG
AVRSVKETLNSQFVENCKGVIQRLSLQEHKMVWNRTTHLWNDYSKIIHQRTNTVPFDLVPHEDGVAVSVR
VLKPLDSVDLGLETVYEKFHPSVQSFTDAIGHYISGERPKGIQETEEMLKVGATLTGIGELVLDNNAVRL
QPPKQGMQYYLSSQDFDSLLHRQESSVRLWKVLVLVFGFATCATLFFILRKQYLHRQERLRQQQLQEEFL
EHEAQLLSQASPEDRESLKSACVVCLSNFKSCVFLECGHVCSCRQCYLALPEPKRCPICRREITRVIPLY
NS
>Xenopus_laevis_gi_148226332_ref_NP_001084716.1__mitochondrial_ubiquitin_ligase_activator_of_nfkb_1__Xenopus_laevis_
MENGGRPSVGQVILLTTSSAITALFYSIYRHKYRSVQTLKEAKKFCLTDDLPAVLSDLPGKCVPYAVIEG
AVTSVKEVLNSQYVENCKGVIQRLSLKEHKMVWNRTTHLWNDHEKIIHQRSNTVPFDLAPENPGESGVSV
RVLRPLEAVDLGLETIYEKFHPAVQSFSNILGHYMTGERPKGVQETEEMLKIGATITGVGELVLDNKTIK
LQPPKDGMLFYLSSMDYEGLLEKQEVQMRWWRILSIVFGVASCITLFFILRRKYRHYKEKQHLKNLQREF
EESRARQRVQQEPQNKEEVQNPCSICLSTEKSCVFLECGHVCSCISCYQALPSPKKCPICRNFIDRIVPL
YNS


>gi|10434615|dbj|BAB14317.1| unnamed protein product [Homo sapiens]
MESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQELKGAKKVHLGEDLKSILSEAPGKCVPYAVIEG
AVRSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVR
VLKPLDSVDLGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSVRL
QPPKQGMQYYLSSQDFDSLLQRQESSVRLCKVLALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQ
EHEAQLLSRAKPEDRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEPKKCPICRQAITRVIPLY
NS
>gi|221044766|dbj|BAH14060.1| unnamed protein product [Homo sapiens]
MVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRVLKPLDSVDLGLETVYEKFHPSIQSFTDVI
GHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLW
KVLALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQEHEAQLLSRAKPEDRESLKSACVVCLSSFK
SCVFLECGHVCSCTECYRALPEPKKCPICRQAITRVIPLYNS
>gi|171542821|ref|NP_078820.2| mitochondrial ubiquitin ligase activator of NFKB 1 [Homo sapiens]
MESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQELKGAKKVHLGEDLKSILSEAPGKCVPYAVIEG
AVRSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVR
VLKPLDSVDLGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDNNSVRL
QPPKQGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQYLQRQERLRLKQMQEEFQ
EHEAQLLSRAKPEDRESLKSACVVCLSSFKSCVFLECGHVCSCTECYRALPEPKKCPICRQAITRVIPLY
NS
