>sz14n09
------------------------------------------------------------
-----CP-------ICGEHFRA--------------------------------------
------------------------------------------------------------
PVLLECGHSF-------C---SECIRRALV--YRSECPQCR-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>sz14n09_3
LIFLDAAFAATAAAAPNHSSCSLPLRMPKNGLSLGKVEAVAASLDVPEGYHWPHEAFRSL
DVLTRCP-------ICGEHFRA--------------------------------------
------------------------------------------------------------
PVLLECGHSF-------C---SECIRRALV--YRSECPQCR---------APASAGQLRR
-NRLVQDV--TTAWQQARECV--------------LTRFSPQEHAGNTECRSSKLEA--S
TESGL----------TVRER------------------TEAACPVRAAALTAQVATRGRA
RSAPVPPDEHTAAVSAVWTDX---------------------------------------
-------
>sz14d10
------------------------------------------------------------
-----CP-------LCMRLLYE--------------------------------------
------------------------------------------------------------
PLTTPCGHTF-------C---RSCLARALD--HASYCPICR-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>sz14d10_1
VDEQNFERYGLD------------------------------------------------
-----CP-------LCMRLLYE--------------------------------------
------------------------------------------------------------
PLTTPCGHTF-------C---RSCLARALD--HASYCPICRTVLYVDSEKHPVTVAVAKV
CEELFPDVYRQRAIEEERECT--------------HQFDAPAATAAVAPDGTPPVETQPA
SNSGN----------SSRSSG----------------TTETTVPVTSG---PAVTVNQRI
RWLPLFLLDEAVFPYQRIQLHIFEPRYRLMLRRVMASSRQFGFVAVFRQPPAGLNVIRAA
GGHPFMX
>sz14n09_6
V-----------------------------------------------------------
-----CP----NSYRCGMLVWRDRSAPSATSSRNLCGQRCRSHRASCFGSF---------
-SNREAALSRSFQFRAPAFRIPS-------------------------------------
VLLWKAGHAFACLLPRGCNVLNQTVSTKLP---------CT---GGRSTLRALASINKRT
TNAFAAETVATLKQHRRAEVFPT--------------DRAPSNVEGTEGLVRPVVALGNV
QTSSNRFYFPRETILRHSERT-------------------AMVRSCGSRGCRKSSVEDEV
------------------------------------------------------------
-------
>sz14n09_2
PH----------------------------------------------------------
-----LP----RRCFCGNRGCRMTPLMFTTSPNAEEWSLFRESR----------------
-SGCCSGRSRGLPLAARGLPF-----------------PRRFNSVPDLWGTLPRACAAVW
PQFLQRMHSS-----------CACLSKRVP--AVSSARQCR-------------ATSSKP
FGSGRYNRVATSTRMRANPLFTT----RARWEYGMPELEIGSFDERPHGSRKNRSSLPGA
SGSADR---------TSCDRS----------------RSERSCPARRAYRSGISCLDRQ-
------------------------------------------------------------
-------
>sz14n09_4
------------------------------------------------------------
-----CL----SKQLIPLRYARLA---GQERSERDLSQLVRSALPLAPGKLLRFFLEPGR
SQSKLPISSSGIPYSQRALVVKSGLARIRVLVATRLRP---EPNGFDEVALHWRALDTAG
TRFDKQAHDE-----------------------CIRCRNCG-------------HTQAAQ
ARGSVPHRSGTELKRRGN-----------------GRPRAASGSPRERPDQQPLLLS---
---------------LKRDHS----------------SAFGEVVNMSYGVMRQPRLPQKQ
RLGRG-------------------------------------------------------
-------
>sz14d10_6
MNG---------------------------------------------------------
-----CP----PAARITLSPAGGCRNTATKPNCLELAMTRRSIKRYRGSKMCSWILGNTA
SSSRKSGNQRILWFTVTAGPLVTGTVVSVVPLLLLLFPLLLAGCVSTGGVPSGATAAVAA
GASNWCVHSR-----------SSSIARRYT----------------SGNSSSHTFATATV
TGCFSESTYSTVRHIGQYDAW---------------------SSARARQLRQNVCPQGVV
SG-------------SYKRRM----------------HKGQSRPYRSKFCSST-------
------------------------------------------------------------
-------
>sz14n09_5
LSVQTADTAAV-------------------------------------------------
-----CS----SGGTGALRARPLVATCAVSA-----------------------------
-AARTGQAASVLSRTVRPLSVEASNFELRHSVFPA------CSCGEKRVSTHSRACCHAV
VTSTKRFRRS-------CP-------------ALAGARHCG-----------HSLRTSAR
RMHSLQKLWPHSSSTGARKCSPQ------------IGHRVKTSRERKASCGQWPSGTSRL
AATASTFPKERPFFGIRRGSE----------------HELWLGHAAAAVAAKAASRKMRX
------------------------------------------------------------
-------
>sz14n09_1
------------------------------------------------------------
------------TSSSTLLLRQPRLPHDLTIAHVHYLSECRRMVSLGKKRLLLVWTFPRA
TTGRTRPSVPSTFLGARSVGNTS------------------ARLCCLSVATVSAANAFVV
RLFIEASARSVERPPVQGNFVETVWFRTLQPRGNKHANACPAFHHKSTLGIRNAGARNWK
LRLRAASRFEKEPKQLAR------------------------------------------
---------------CERQRP----------------HKLRLEVALGALLSRQTSIPQRY
QLFGQTX-----------------------------------------------------
-------
>sz14d10_3
------------------------------------------------------------
------------------------------------------------------------
--------RTKLAVWSLSFVHASFIRTADNTLWTYVLPQLPSSSTGPRIVLSNMPDSAVR
RLKAPCYGSS-------CEGMRGAISRCVP--SACYRRTRVHTPVRTCSNSSSSTRRNAP
GGDAACQQWEQQQEQRYHRDNSA------------CDERPSCDCEPKNPLVAAFSAGGGV
SLSENPTAHFRTSIPFDAASS----------------HGQFKAVRLRSRIPTTTRWAQRY
TGSGWASVHG--------------------------------------------------
-------
>sz14d10_2
------------------------------------------------------------
-----SM----NKTLSGMVLIVLCACVFYTNRQHLVDIR---------------------
--------------------------------------------------------SAAV
ALEHWTTHRTVQYAGQCCTTLKSTLLRQLRRYARSYFPMCT---------VSVLLKKNES
AHTSLTHLQQQQQHQTERPRWRRSLPVT-------VGTAAGAAVPPRQQCLRAAQLLTKE
SAGCRFFCWMRRCFLIRESNCTFSNLDTVCCVESWPVQGSSASPYSDNHPLGSTLYGQRV
GIRSW-------------------------------------------------------
-------
>sz14d10_5
------------------------------------------------------------
-----PT----DAHPLPVRAQRVVVGIRLRSRTALNWPLDAASNGIEVRKCAVGFSDKET
PPHPAEKAATSGFFGSQS------------------------------------------
----QLGRSS-----------QALLSRWYR--CSCCCSHCY-------------WQAASP
PGAFRLVLLLLLLQVRQTGVCTLVLLQHADGTHREIAPRIPSQLLPQGAFQSLRTALSGI
LDSTMRGPV------LELGNC----------------GRTYVHKVLSAVRIKDACTKDNQ
DHTAQSFVHRX-------------------------------------------------
-------
>sz14d10_4
HERMPTR-----------------------------------------------------
-----CPYNVEPSGWLSEYGYEAELPTGHDSTQHQTVSRFENVQLDSLIRKHRLIQQKKR
QPADSLVHSHSWAARHRHCCLGGTAAPAAVPTVTGRLRLHRGRSVWCYCCCCCRCVKLVC
ALSFFFNSTLTVHIGKLLAYLRNCYRNRVL--FRVYVQHCPAYWTVRCVVQCSSATAAER
MSTRCCQRFVKTHAQRTIKTIPLKVLFID-------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
