>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|3610  641252794 AM1_3710 hypothetical protein [Acaryochloris marina MBIC11017]
------------------------------------------------------------
------------------------------------------------------------
----------------MKIIGIILIVIGIILFFVYSNLKRKLASLRQARPASIAELN---
-------------------------------HLASEIALEMGS----------------G
SWRDYVKLRGTIQ-------CDQPLISELKQ-----MPCV--------------------
-----------------HYNMTVVREYEE--------------QVTERDSDDKVV-----
------------------------------------------------------------
---------------------------TKTQRGSETLSQNRES---VPFFLQDDTGEI--
----WV-----EPEGAQIETV------RVLDE-FSPEQPSGGQLSFG-----------GF
S-LSL-SSAETGRQTI----------------------G---------YRYQE-------
----SVLPVQR------QVFVVAQV-SDFN---QSLVLENPTTK----------------
-----------------GQRFV--------------ISLKSEEALAQTTQTSVTYAFYGM
ISTLVVGGLLVIFGLLSA------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7425_gnl|BL_ORD_ID|1048  gi|220906503|ref|YP_002481814.1| unnamed protein product [Cyanothece sp. PCC 7425]
MG----------------------------------------------------------
------------------------------------------------------------
----------------LAIVGAILLVTGGILYFVQRHYQQKLYSIKLARKTTVAELK---
-------------------------------QLADQVGAEIGQ----------------G
SLREYVKLSGQIK-------CDTPLISELKQ-----VPCV--------------------
-----------------YYQMQVEREYEE--------------RLTERDNDGETR-----
------------------------------------------------------------
---------------------------EKTQRGSETIASNSQS---TPFFLQDQSGAI--
----EV-----DPSGAAIETV------QVLNE-FRPEA-GSARISFG-----------NF
S-LSVGGSFPAGRETI----------------------G---------YRYRE-------
----SILPPDR------RILIVATA-SDSS---GILSLQKPVEK----------------
-----------------RQKFI--------------ISLKSEDHLAQSTQQTATYTFYGM
IACLGLGAILLVVGLIIR------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
------------------------------------------------------------
----------------MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQ---
-------------------------------TIANQIAEEIGG----------------G
SLREYVKIRGVIE-------CDRPLISQLKQ-----EPCV--------------------
-----------------YYSMTVTWEYNE--------------EVIKQDNEGKTI-----
------------------------------------------------------------
---------------------------REKERKSETVAQNSRS---IPFTLQDSTGEI--
----RV-----NPERAEIETV------KVLEE-FRPENFSGGSLTFG-----------NF
S-INL-PSFEERRQTI----------------------G---------YRYQE-------
----EILPIGR------QILVIGTA-TDEE---GMITIRKPTEK----------------
-----------------GQRYF--------------ISLKSEEELSQATNNAIRGTFYSM
IFFLTLGLILLVAGVLRG------------------------------------------
-------------------------------------------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|2513  637618204 syc2512_d hypothetical protein [Synechococcus elongatus PCC 6301]
MA----------------------------------------------------------
------------------------------------------------------------
----------------AIILAAITAIAAIVLYFVRRHYRFKLQSLLLAQPATSLQLK---
-------------------------------EIAEHVAGEIGG----------------G
NLRQYVKMWGAIE-------VEQPLVSELKQ-----ESCV--------------------
-----------------YYCSTVSREYEE--------------RVRKEDSEGKVT-----
------------------------------------------------------------
---------------------------WTTERRSETISQNRRS---TPFYLRDQHGRV--
----RV-----EPESAAIATI------PVLDE-FRPDS-SASSLIFG-----------AF
S-LSL-STTAGLGKTL----------------------G---------YRYRE-------
----EILPCDR------SVLVVGAA-SDET---GELTLGPSSEA----------------
-----------------RQQFF--------------IALKPETALLQEVKQTIQWLTIGA
IASVVVTVVAAIAALL--------------------------------------------
-------------------------------------------------------
>Synechococcus_elongatus_PCC_7942_gnl|BL_ORD_ID|1573  gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococcus elongatus PCC 7942]
MA----------------------------------------------------------
------------------------------------------------------------
----------------AIILAAITAIAAIVLYFVRRHYRFKLQSLLLAQPATSLQLK---
-------------------------------EIAEHVAGEIGG----------------G
NLRQYVKMWGAIE-------VEQPLVSELKQ-----ESCV--------------------
-----------------YYCSTVSREYEE--------------RVRKEDSEGKVT-----
------------------------------------------------------------
---------------------------WTTERRSETISQNRRS---TPFYLRDQHGRV--
----RV-----EPESAAIATI------PVLDE-FRPDS-SASSLIFG-----------AF
S-LSL-STTAGLGKTL----------------------G---------YRYRE-------
----EILPCDR------SVLVVGAA-SDET---GELTLGPSSEA----------------
-----------------RQQFF--------------IALKPETALLQEVKQTIQWLTIGA
IASVVVTVVAAIAALL--------------------------------------------
-------------------------------------------------------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|658  637313275 tll0660 hypothetical protein [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
------------------------------------------------------------
----------------MGVLGGILLVIAVLVLCGWWDYRLKVRALNLAVSSTPAQLH---
-------------------------------ELQRRVAQEIGG----------------G
YLQEYVKISGQIV-------ADRPLVSELKR-----LPCV--------------------
-----------------HYRLCVSRVYKT--------------TESHEDGSS--------
------------------------------------------------------------
----------------------------ETKYRHEILSSNTQT---IPFRLRDGDMEI--
----YV-----DPRGAEIETV------QVLNE-FQEDN-NTTHLAFG-----------RF
Q-MDL-SSLPKHSDTV----------------------G---------YRYEE-------
----WILPVNQ------QVFVVGTA-SDER---GKLRIRRPHQK----------------
-----------------GQLFF--------------ISLESEENLTKKVRQYARASIIAA
GVFSGLGILLILL-----------------------------------------------
-------------------------------------------------------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|198  637312804 tll0199 hypothetical protein [Thermosynechococcus elongatus BP-1]
------------------------------------------------------------
------------------------------------------------------------
----------------MGVFAHLCLTGSAFLFALEGYYRLQLRGIKVASPSTIGELE---
-------------------------------KFQQQVAQEMGS----------------G
SWREYVQVVGQVT-------TSQPLLSEVKR-----IPCV--------------------
-----------------YYKTIISREYEK--------------E----------------
------------------------------------------------------------
----------------------------GSDRPSEIIGRHEQS---TLFLLRDHQGEI--
----EV-----NPFGAEIEAV------QVLDE-LRPAD-QPHAFALS-----------LG
F-LSF-NWHFGKGTTL----------------------G---------YRYQE-------
----WVLPLGQ------PVSVVGMA-SDQG---GVLRLQKPQNR----------------
-----------------GQKFI--------------ISLSFEDPLIQQYKQQKRKMTYAS
LGATLCGVCGLVLALF--------------------------------------------
-------------------------------------------------------
>Synechococcus_sp_JA_2_3B_a2_13_gnl|BL_ORD_ID|170  637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba(2-13)]
MGVSYRRSNRAKAVLEGR--GFRPSFLVKFGTARIRDCLKLLLNPVSQVTASM-------
------------------------------------------------------------
RPTSLPPPERKAFMNWLMLLGLLCLPASLFSFVEYLRSQRLVQQLSATRLLKIAELR---
-------------------------------HLGQTNPQAKGA-----------------
---NLAQVYGRVV-------CDRPLVSELSR-----QPCV--------------------
-----------------YYKSEISWEYDEIECYRRYLNSRGDVAYSERISEGEYQNALRL
GSRAKSYPGEMVGKKPGLGYSDSGSFQKRVDPDYSNSFPQKPNPGYPQQLGSPGYPQKSP
FSEVSSPQKHYANVYYDPSTGREYLLERETRTRDETLHSVVRQ---IPFFIEDETGRV--
----RV-----DPTGAEIEAM------SVVDEHIFPGK-GPSRFNFN-----------LK
R-YLS-GVRTENRSTR----------------------A---------FIYKE-------
----WVIPVDA------MAFTMGQV-RFEA---GDPVIRKPLS-----------------
-----------------GERFM--------------IAPKSPEALLEEQRSNASSYLVGS
VVLLGIGIFTVLHLLQSLQPYR--------------------------------------
-------------------------------------------------------
>gnl|BL_ORD_ID|17261 Arabidopsis_thaliana AT1G63900.1|PACid:19655208
M-----------------------------------------------------------
------------------------------------------------------------
----------------IPWGGVTCCLSAAALYLLGRSSGRDAEVLETV--TRVNQLK---
-------------------------------ELAQLL--ELDS----------------K
ILPFIVAVSGRVG-------SETPIKCEHSG-----IRGV--------------------
---------------------IVEETAEQ--------------HFLKHNETGSWV-----
------------------------------------------------------------
-------------------------------QDSALMLSMSKE---VPWFLDDGTSRV--
----HVM----GARGATGFAL------TVGSE-VFEE--SGRSLVRG-----------TL
D-YLQ------GLKML----------------------G---------VKRIE-------
----RVLPTGI------PLTIVGEAVKDDI---GEFRIQKPDR-----------------
------------------GPFY--------------VSSKSLDQLISNLGKWSRLYKYAS
MGFTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKK
EDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|5027  650388367 NIES39_M00310 translation initiation factor IF-3 [Arthrospira platensis NIES-39]
MP----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------VIESKRNRNLPQINDNI
RF--------------------------PKIRLIDTEGGQLGI----------------M
TPREAMKLAQEKE-------LDLVLVSDKAD-----PPVC--------------------
-----------------RIMDYGKFKYEQ--------------EKKVR------------
------------------------------------------------------------
----------------------------EARKKQHTADVKEVK---MRYKIDDHDYQV--
----RV-----NQAKRFL------------------------------------------
------KSGDKVKATI----------------------M---------FRGRE-------
----IQHSNLA------RELLKRMAEDLEE---HAEVQQSPKQE----------------
-----------------GRSMM--------------MLLAPKKTTTS-------------
------------------------------------------------------------
-------------------------------------------------------
>Arthrospira_platensis_Paraca_gnl|BL_ORD_ID|3312  646131044 AplaP_010100016907 translation initiation factor IF-3 [Arthrospira platensis Paraca]
MP----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------VIESKRNRNLPQINDNI
RF--------------------------PKIRLIDTEGGQLGI----------------M
TPREAMKLAQEKE-------LDLVLVSDKAD-----PPVC--------------------
-----------------RIMDYGKFKYEQ--------------EKKVR------------
------------------------------------------------------------
----------------------------EARKKQHTADVKEVK---MRYKIDDHDYQV--
----RV-----NQAKRFL------------------------------------------
------KSGDKVKATI----------------------M---------FRGRE-------
----IQHSNLA------RELLKRMAEDLEE---HAEVQQSPKQE----------------
-----------------GRSMM--------------MLLAPKKTTTS-------------
------------------------------------------------------------
-------------------------------------------------------
>Arthrospira_sp_PCC_8005_gnl|BL_ORD_ID|1245  648386468 APCC8_010100006537 translation initiation factor IF-3 [Arthrospira sp. PCC 8005]
MP----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------VIESKRNRNLPQINDNI
RF--------------------------PKIRLIDTEGGQLGI----------------M
TPREAMKLAQEKE-------LDLVLVSDKAD-----PPVC--------------------
-----------------RIMDYGKFKYEQ--------------EKKVR------------
------------------------------------------------------------
----------------------------EARKKQHTADVKEVK---MRYKIDDHDYQV--
----RV-----NQAKRFL------------------------------------------
------KSGDKVKATI----------------------M---------FRGRE-------
----IQHSNLA------RELLKRMAVDLEE---HAEVQQSPKQE----------------
-----------------GRSMM--------------MLLAPKKTTS--------------
------------------------------------------------------------
-------------------------------------------------------
>Anabaena_variabilis_ATCC_29413_gnl|BL_ORD_ID|3683  gi|75909288|ref|YP_323584.1| unnamed protein product [Anabaena variabilis ATCC 29413]
MMSVPNITREILADDPFP--RFDEWLDQVEQVLEQNTALLMLDEFEALDSAIN-------
------------------------------------------------------------
RGRFDEED-----------------VLGMLRHLIQHRPRFK---MLLAGSHTIEEYQ---
-------------------------------RWASYLIN---------------------
-----VQVVHISY-------LKEEEARQLIE-----HPVK--------------------
-----------------YF----TLRYEP-------------------------------
------------------------------------------------------------
-------------------------------EAVERVLQLTRC---HPFLIQLLCGEI--
----IVLKNEQDPSIRRLTSL------EDVEA-AIPEALQSGGFFFA-----------DI
Q-NNQ-------------------------------------------------------
-----VDANGR------EVLRLIAA-QGEGEIVSKFTLSEQFPD----------------
-----------------VWERT--------------IALLLQQELIEEVADSYRFQVELI
RRCFV-------------------------------------------------------
-------------------------------------------------------
>Lyngbya_sp_CCY_8106_gnl|BL_ORD_ID|1789  640015809 L8106_17014 hypothetical protein [Lyngbya sp. CCY 8106]
MSETTPITPYLITLP---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------PTQEELPYDDGE--------------PME
SQRHQFQMEILLN-------TLQPWMASRSDGFIGGNMFV--------------------
-----------------YYSLEQVRNKDF-------------------------------
------------------------------------------------------------
----------------RGPDFFAVLGVPKKERRSWVVWEEGKAPDVVIELLSDSTAELDK
TEKKYI-----YQDRLRVSEY------FWFDP-FNPEDLAGFSLQQG-----------VF
QPIDFNAKNQLVSQAL----------------------GLSLVRWFGEYKGIEATWLRWA
NLDGELFPLPQ------EI-------AEQA---HQRAEQEYQRA----------------
-----------------EQEYQ--------------RAEQVESQLNQVARTLLQQGMTQE
QVVQVTGLSLAKIQELMNTNR---------------------------------------
-------------------------------------------------------
>Cylindrospermopsis_raciborskii_CS_505_gnl|BL_ORD_ID|3366  647107707 CRC_03432 3-beta hydroxysteroid dehydrogenase/isomerase [Cylindrospermopsis raciborskii CS-505]
MI----------------------------------------------------------
------------------------------------------------------------
----------------MNVAIIGCGYVGYAVAKFWRQNPSFRVTVTTTSEHKVSTLQ---
-------------------------------EVADAVEVTMGD--------------DQI
FLNRVLK-----N-------QDVVLLAVGAK-----------------------------
----------------------SSSSYEK-------------------------------
------------------------------------------------------------
----------------------------TYLETAKTVTSLIKYHPKIKQLIYTSSYAIYG
DRNGVWVDEETPPAPPNLNSQILGKTEEILLA-AATEKLRVCILRLGGIYGPGRELIKIF
S-RTAGTTREGNGEEITNWVHLDDIVRVVEFARWQRLQGIYNLVDDSHFTSRE-------
--------------------LIDGVLKTHN---LPNVIWDATNK----------------
-----------------STRQY--------------NTWVSNQKLKDAGYQFIHPHIVL-
------------------------------------------------------------
-------------------------------------------------------
>Synechococcus_sp_PCC_7335_gnl|BL_ORD_ID|4701  647580957 S7335_206 conserved domain protein [Synechococcus sp. PCC 7335]
MDFLSDFLTLFLSKLQSPTLGFLIGGAIVAALNSRLTIPDPVYKFIVFMLLIK-------
------------------------------------------------------------
VGLSGGIAIRNANLFEMLLPAAFAVVIGILIVFLGKYTLAKLPNVRTVDALATAGLFGAV
SG--------------------------STLAAALTLLETEG------------------
-----IEYEAWAA-------ALYPFMD---------IPAL--------------------
-----------------VTAIVLASVYTS-------------------------------
------------------------------------------------------------
----------------------------KRRSIANEELSKQEYLGKQEYLGKQRVATV--
-----------EHSAVEGTTV--------------PGEYSGGQ---G-------------
--TAVSEYRSGQGSTP--------------------------------SKRVE-------
-----IWPIVK------ES-LQGSALSALLLGLALGIITQPESV----------------
-----------------YESFFNPLFRGLLSILMLVMGMEATARLGELRKVGQWYALYAF
VAPLVHGLIAFGFGMIAHVTTGFSPGGVVILAVIAASSSDISGPPTLRAGIPSANPSAYI
GSSTAVGTPVALAIGIPLFIGLAQAVMGS--------------------------
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|1046  all1047 ABC transporter, permease protein NatC
MIEYLIFLAISTATFALFSLGLNLQWGFTGLINFGHIAFMTLGAYTTVLLSLKGVPLFIS
AIVGAIFAALLGLVIGFATLRLREDYLAIVTIGTGELIRLVVNNQDLPVGDTWVSGAFGV
QSYPIPLSTEPNLFFRLLMIGILTLLFAVTVFSLWRWIRNAQKLQLTDATDKTSSKQ---
-------------------------------EIASRFG--VGI--------------ILG
LLATAIYISGVITLYNYIPKAGLMLVSLLV------LAFV--------------------
-----------------FWRL----------------------EYLVRSPWGRVL-----
------------------------------------------------------------
----------------------------KAIREDEEIPKAMGK---NVFWYKLQSLML--
--------------GGAIAGIAGAFFAWQISA-IYPDNFQP-QLTFD-----------SW
IMVILGGAGNNIGSIL----------------------GAVIYFAYDAITREV-------
--LPKIIPLDEARLGAFRIMCIGLIL-------MVLMIWRPQGI----------------
------------------------------------LGKKEELTLGK-------------
------------------------------------------------------------
-------------------------------------------------------
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|1356  637231412 all1047 permease protein of ABC transporter [Nostoc sp. PCC 7120]
MIEYLIFLAISTATFALFSLGLNLQWGFTGLINFGHIAFMTLGAYTTVLLSLKGVPLFIS
AIVGAIFAALLGLVIGFATLRLREDYLAIVTIGTGELIRLVVNNQDLPVGDTWVSGAFGV
QSYPIPLSTEPNLFFRLLMIGILTLLFAVTVFSLWRWIRNAQKLQLTDATDKTSSKQ---
-------------------------------EIASRFG--VGI--------------ILG
LLATAIYISGVITLYNYIPKAGLMLVSLLV------LAFV--------------------
-----------------FWRL----------------------EYLVRSPWGRVL-----
------------------------------------------------------------
----------------------------KAIREDEEIPKAMGK---NVFWYKLQSLML--
--------------GGAIAGIAGAFFAWQISA-IYPDNFQP-QLTFD-----------SW
IMVILGGAGNNIGSIL----------------------GAVIYFAYDAITREV-------
--LPKIIPLDEARLGAFRIMCIGLIL-------MVLMIWRPQGI----------------
------------------------------------LGKKEELTLGK-------------
------------------------------------------------------------
-------------------------------------------------------
>Synechococcus_sp_WH7805_gnl|BL_ORD_ID|1619  639020969 WH7805_03377 hypothetical protein [Synechococcus sp. WH7805]
MTMPSRHAWFSSCL----------------------------------------------
------------------------------------------------------------
----------------LASLPWLAGCADGDAPVAVEAPPFVFRSLELEQKSSTGQKEWSL
SSPEARYELNRRLVRARQPVGLLFRNGKPSFRIQSDLAQVIND-----------------
--GEKILLEGNVKLQQL---TGSKLLIQGDR-----LRWR--------------------
-----------------PDQGVLTMEQRP-------------------------------
------------------------------------------------------------
---------------------------RASDQESRISASQAE--------LQQTTNEL--
----------------TLTGTVQLDRWSTSDRNARPDS----SLRSGKAQWNLDTGLLNA
KGPILGQRRDKEGTVL---------------------------------EQLE-------
-----------------GQSLEGNTLKGEITVQAPVILRIPREKGVLRAKATTWVFRDQI
IRSAKPFKADLDRTTIRGESFRADLGQSSVDV----NGACEIRQPGEALKAERCRWNWSN
EAVLAEGKVELRRDENDQVTRATRLEGTVGKEGRISFTAPGSKVQSEVRIPTEGPEGTPE
ARPQPNPVSF---------------------------------------------
>Prochlorococcus_marinus_MIT_9303_gnl|BL_ORD_ID|1470  640086991 P9303_14811 SAM-dependent methyltransferase [Prochlorococcus marinus MIT 9303]
MTSSTNSSLTSTPTPGDKVEITCVDLDRHGNGLARWNN----------------------
------------------------------------------------------------
----------------WVVIVNDLLPGERAQIEFVRRHRNQFLARKVHSIETVSSRR---
-------------------------------QPPCKIAKECGGCSIQHLNDHGQSLLKQS
HLREILLRLGQLD------NKIEPIMTDYTRALGYRNRALIPLYRNREGQLLMGYYRRGS
HQIIDLNRCPVLDRGIDQYLAWIKDDLQQ-------------------------------
------------------------------------------------------------
---------------QNWPADSDLSSGEGVRHLGIRIGQKTRQ---VLITLVSSTTELSG
LHQQANDWYRRWPEVKGITLNIQRQRNNLVLG-------QETILLAG--DLDIEEHFCNL
S-LLLSTTTFFQVNTI----------------------------------QAERIVLKLL
KWLSTTLP---------DINIIDAYC-------GIGTISLPIAA----------------
-----------------AGYHV--------------IGLELHAEAIAQANKNALRNNLGN
ASFLCGDVSLLLAKILQHHDVLVLDPPRKGLDQMVIKTILSVRPERVAYLSCDPATLARD
LKQLIVPNGPYQIDQLQPIDFFPQTMHIECLALLIRISS----------------
