>gnl|BL_ORD_ID|41015 @Branchiostoma_floridae@ jgi|Brafl1|218311|e_gw.74.19.1
M-------------------------------------------------------FIDA
NIHDVVAGTPNQTIPYAVIEGLVEPV----------------------------------
-------GKPLQSQLGVE------------------------------------------
-----------------------------------------------------------G
VIQELLMEEHRRVWNKVSRIWY---------------------DTSRTIRRVTNRIPFSL
ACKGGKVRVLEPTQAAMLSLDVIYDKFE--------------------------------
------------------------------------PEDSTMGKRVVDWMS-------GE
AIKGYQETEKMLKVGTQLFGYGEL--------------------------SLEEGQVVLR
NPS----------------------------------NNASYFITNLS------------
---------------------------PSELAKQYQSKVTMLKAFTILFG----------
---------VGTLI----------------ALCAFAAKWYRRYRENQ-------------
----EFFAQTEQVRAARRRPDGEP------------------------------------
------------------------------------------------------------
------------------------------------------PEELDE------------
--------------------------EHACVVCQA------------------NAREVII
--------------------LDCGHICCCADCADMLQP-------RKCPICRRHIARILP
VYNP
>AT1G63900.1|PACid:19655208
M------------------IPWGG---------------VTCCLSAAALYLLGRSSGRDA
EVLETVTRVNQLKE----LAQLLELD----------------------------------
-------SKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEE-------------------
------------------------------------------------------------
------TAEQHFLKHNETGSWV---------------------QDSALMLSMSKEVPWFL
DDGTSRVHVMGARGATGFALTVGSEVFE--------------------------------
------------------------------------ESGRSLVRGTLDYLQ-------GL
KMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQ---------------KPDRGPFYVS
S------------------------------------KSLDQLISNLG------------
---------------------------------KWSRLYKYASMGFTVLG----------
---------VFLIT----------------KHVIDSVLERRRRRQLQ-------------
-------KRVLDAAAKRAELESEGSNGTRESISDST------------------------
------------------------------------------------------------
------------------------------------------KKEDAV------------
--------------------------PDLCVICLE------------------QEYNAVF
--------------------VPCGHMCCCTACSSHLTS---------CPLCRRRIDLAVK
TYRH
>gnl|BL_ORD_ID|2293 @Trichoplax_adhaerens@ jgi|Triad1|59820|fgeneshTA2_pg.C_scaffold_12000171
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------DSVWM---------------------TLAKDKEELKKEGILHR
DNFLGNIILTNVLTEAVKNADFVFE-----------------------------------
----------------------------------AAVDDTDVKRSILDRIS---------
--------------------------------------------------HMSRHDTIIA
S------------------------------------NTIRLDINDLAQYAEYPERVIGL
RFLYPVYCIPEVELTTTDCTAPYAVEKVKTLLTEIGKTLLPRSGSPLVLS----------
---------PLQIE----------------------------------------------
----------ARVIAKRNRIEETRRRALTTG-----------------------------
------------------------------------------------------------
------------------------------------------ETSDVK------------
--------------------------EKECAICMD------------------KPRNCVF
--------------------RPCNHMCSCIDCAKIVKK-----RSDGCPICRKRITEVLR
VFQS
>gnl|BL_ORD_ID|18494 @Homo_sapiens@ gi|14042925|ref|NP_114404.1| RING finger protein 26 [Homo sapiens]
M------------------------------------EAVYLVVNGLGLVLDVLTLVLDL
NFLLVSSLLASLAWLLAFVYNLPHTVLTSLLHLGRGVLLSLLALIEAVVRFTCGGLQALC
TLLYSCCSGLESLKLLGHLASHGALRSREILHRGVLNVVSSGHALLRQACDICAIAMSLV
AYVI-------------------------------------------------------N
SLVNICLIGTQNLFSLVLALWD---------------------AVTGPLWRMTDVVAAFL
AHISSSAVAMAILLWTPCQLAL--------------------------------------
------------------------------------ELLASAARLLASFVLVNLTGLVLL
ACVLAVTVTVLHPDFTLRLATQALS-------------------------QLHARPSY--
-------------------------------------HRLREDVMRLS------------
-----------------------RLALGSEAWRRVWSRSLQLASWPNRGG----------
---------APGAP----------------QGDPMRVFSVRTRRQDT------LPEAGRR
SEAEEEEARTIRVTPVRGRERLNEEEPPGGQDPWKL------------------------
------------------------------------------------------------
------------------------------------------LKEQEE------------
--------------------------RKKCVICQD------------------QSKTVLL
--------------------LPCRHLCLCQACTEILMR--HPVYHRNCPLCRRGILQTLN
VYL-
>gnl|BL_ORD_ID|5536 @Nematostella_vectensis@ jgi|Nemve1|82063|e_gw.5.135.1
M---------------------------------------------------SSILLPVG
QCGNQIGHELMTLVEKQCEGKPLSHR----------------------------------
-------DGKLRCVCVDSESKVIASNRRSDGVHGQYRDSNIIAGRRGRGNNFALGYHGNS
IDEGGT------------------------------------------------------
-------------------------------------------SLLHMTMDAMRKEVERC
DSFAGTIVMHSLTGGTGSGLGA-------------RLVETLSDAYPLAHVMSVAVS----
----------------------------------PHVSGESPLQHYNSLLSLAALQRNAD
GILLFHNDDVLRQVMLQRV-------------------------------KISEHQVLSG
GS-----------------------------------VSLIDMNRSIA------------
---------------------------------------------KSLVG----------
---------VLQPL----------------GEKPKSIKKTSKKPWEM-------------
-----------------------------------LRSICPEPSKKFVSVYHSEKVKVGQ
SWDHLCQSLVHSMNLYDKSGHPYSTLASLLIARGDT------------------------
------------------------------------------DNTFAESALKIEKRLKGT
LRCVEWNPFPVDFWISPHSVVGSPFCGQSLTLCTNSNRARDSLGNILTRAKSMFDAGAYL
-------------------HWFEKHGCVKNDFLDGFSTLQDIIDEYNCATS---------
----
>gnl|BL_ORD_ID|6797 @Drosophila_melanogaster@ gi|24648140|ref|NP_732403.1| CG11779, isoform B [Drosophila melanogaster]
MYRIAALVRDRACLFTCQQASQNLQQQQPRFYSAPGRRAGFFSQFFDNMKAEMDKNKEIK
DNIRKFREEAQKLE----ESDALKSA----------------------------------
-------RQKFNIVESEAQKSSSMLKE---------------------------------
------QLGAIKERVGD-------------------------------------VLEDAS
KSHLAKKVTE---------------------------------ELSKKARGVSDTISDTS
GKLGQTSAFQAISNTT------------------------------------TTIK----
----------------------------------KEMDSASIENRVYRAPA-KLRKRVQL
VMSDSDRVVEPNTEATGMELHKDSKFYESWENFKNNNTYVNKVLDWKVKYDESENPVIRA
S------------------------------------RLLTDKVSDVM------------
---GGLFSKTELSETMTELVKIDPSFDQKDFLRDCETDIIPNILESIVRG----------
---------DLEILKDWCFESTFNIIANPIKEAKKAGVYLDSKILDIENIELAMGKVMEQ
GPVLIITFQAQQIMCVRDQKSQVVEGDP--------------------------------
------------------------------------------------------------
------------------------------------------EKVMRV------------
--------------------------HYVWVLCRDRNELNPKAAWRLMELSANSSEQFV-
------------------------------------------------------------
----
>gnl|BL_ORD_ID|6792 @Trichoplax_adhaerens@ jgi|Triad1|52477|fgeneshTA2_pg.C_scaffold_1001224
M-----------------------------------------AVNKSSSISEIVSLMEAY
TDMSKVSNESLKNV----TGGILEVF----------------------------------
-------TCKINILIQNLHRELNEHSR---------------------------------
-------------------------------------------------------LNDTV
KIREKFKLGQDHLRSHSDIIWYYVLHALY--------------LLQTLKDELNKAYTNDC
NADSNCKIKADSTKLRQASVH-------------------------AKPSIETPVS----
----------------------------------PSDILSVKEQKVIQTLT---------
QIITCLGIYPYLESGVGLPLYMRSVFSNILEEIIQNTDFNNH--------QFYERRLYLA
TQVLFSCLNQKSLK------------------VVLISRHLIDIVSALCQLGYSKLQVK--
--DIYLHHDEDNESNDLQQISNYDLIDISDSEASRKNFSLSTKERNSCAG----------
---------LLSQILNSTYRPMVVQMLFTLQNPSRSTKETSETRKGIP------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------ERALIRCEQ-------------------------
------------------------------------------------------------
----
>gnl|BL_ORD_ID|2386 @Ciona_intestinalis@ jgi|Cioin2|219345|fgenesh3_pg.C_chr_08q000972
M---------------SDVMSKSL---------------GFAMEYIKGKAQSIDHPYTIH
DFLSTVSKISNSKDEILVLSKFLQQM----------------------------------
-------KDHFNICPLIRQRQSLVTLTYCCQMPGIKSVVKLLH-----------------
------------------------------------------------------------
-------------------------------------------DVAAVVITFVERAKSVK
DKRLGYLALTTLADIC---------DNEIVYLAVNTVVKDVASKSPAVIIIALNCM----
----------------------------------VHIVSIDIIPVLLPIAE--KRLSHSD
GNVRAKSVMALHR-------------------------------------MYLVGPEFVH
SPQ----------------------------------RHLKQALSDKD---PEVMATV--
--LPYVYDVLKTNPELRSSFAPKLVHILKQVVKNRLPMYMSRQGVPAPWV----------
---------QINIMKSLFFC----------VDNLKENDSLANILIEILNRGQSLNNTASY
SVVAECTHLISRLYDAKHEAFQTVLGCMGCFLHSKHPNLLLVGLQLLS------------
------------------------------------------------------------
------------------------------------------ELTTVD------------
--------------------------STCCVQYQDIIINSLSHPDMTVKKQVLSECHMYT
------------------------------------------------------------
----
>gnl|BL_ORD_ID|25543 @Takifugu_rubripes@ jgi|Takru4|590177|e_gw2.22.189.1
M---------------------------------------------------------AT
VVMEQIGRLFINVQQLRQIPQLLETA----------------------------------
-------FPTLPCTVKVSDVPWVFRER---------------------------------
-------------HILT-------------------------------------GYRQPD
QSWRYYFLTLFQRHNETLNVWSHLLAAF---------------IILVKWQEMSETVDFLR
DPHAQPLFIVLLAAFTYLSFSALAHLLSAKSELSYYTFYFLDYVGVAVYQYGSALAHYYY
AIEKEWHNRVQRLFLPTAAFLAWLTCFGCCYGKYARADMSKLAQKLLQVVP--------S
ALAYCLDISPVVHRVYRCYQDGCSDPVVAY--------------------HFYHVLFFLI
GAYFFCCPHPESLFPGRCDFIGQGHQFFHAFVVVCTLMQIEALRTDFA------------
------------------------------------------------------------
-----------------------------------------ERRPLYEELHGDLAHDAVA
LFIFTACCSGLTAFCVRQRVRAS-------------------------------------
------------------------------------------------------------
------------------------------------------LQEKKE------------
------------------------------------------------------------
------------------------------------------------------------
----
>gnl|BL_ORD_ID|501 @Cladonia_grayi@ jgi|Clagr2|60000|estExt_Genewise1.C_120098
MSLTNCRFYENKYPDLEEFVMVNV---------------KQIAEMGAYVKLLEYDNIDGM
ILLSELSRRRIRS-----IQKLIRVG----------------------------------
-------RNEVVVVLRVDKEKGYIDLS---------------------------------
------KRRVSAEDIVK-------------------------------------CEERFN
KGKMVASIMRHVAE-----------------------------KTRTPMETLYQEIGWPL
NKRYGHAVDAFKLSITNPDVW-------------------------TDITFPSPAV----
----------------------------------KSELQSYISKRLTPQPT-KVRADVEV
TCFGYEGIDAVKTSLRAAEALNSTTPDAQVKV------------------KLVSPPLYVL
TSQ----CLEKGVG------------------IGCLEKAIREIEGSIR------------
-----------------------------------------------GAG----------
---------GGCVV----------------KMAPKAVTENDD------------------
-------AELQALMERRERENAEVSG----------------------------------
------------------------------------------------------------
------------------------------------------DESVSE------------
--------------------------SDEGVVAETI------------------------
------------------------------------------------------------
----
>gnl|BL_ORD_ID|7417 @Cladonia_grayi@ jgi|Clagr2|90138|fgenesh1_kg.4_#_147_#_isotig07723
M-----------------------------------------------------------
------------------KALILVGG----------------------------------
-------YGT--------------------------------------------------
------------------------------------------------------------
-------------------------------------------RLRPLTLTLPKPLVEFA
NKPMIE-----------------------------HQVESLAAAGVTDIVLAVNYR----
----------------------------------PEIMSAALKKYEKEYNV-NIEFSIET
EPLGTAGPLKLAEKTL----------------------------------GKDDSPFFVL
NSDVIC-------------------------------EYPFQDLADFH------------
-----------------------------KQHGEEGTIVVTKVEEPSKYG----------
---------VIVHK----------------PDHPSRIDRFVEKPVEF------VGNRINA
GLYILNPSVLRRIELRPTSIEQE------------TFPAIVKDGQLHSFDLEGFWMDVGQ
PKDFLSGTCLYLSSLTKRGSKKLESPSKPYVYGGNVLVDPSAKIGKNCRIGPNVTIGPNV
VVGDGVRLQRCVLLAGSKVKDHAWIKSTIVGWNSSIGKWARLENVSVL------------
--------------------------GDDVTIGDEIYVNGGSILPHKSIKANIDSPSIIM
------------------------------------------------------------
----
>gnl|BL_ORD_ID|1877 @Ustilago_maydis@ jgi|Ustma1|1878|UM01878
M-----------------------------------------------------------
---------PKSRSLPPTLKQLLQQP----------------------------------
-------TFPARASKLSASKQLPAGRQ---------------------------------
------------------------------------------------------------
------------------------------------ANPAPTPKLTAVSQHFRSLQAEAT
QKGIGWGEWISIATATLFTLNNPGSLHALHQFAAGSKTEDLEHRTNVALLMRETGL----
----------------------------------KCIGFIGIPKVINNLAALRKVVEEDD
QLVQALPTQPRRQIGKDRLDDVHKAAYGLWDDIYTPHSEKLLKI---LGSSHPDLPVFIV
ESEYGPLFSSPASF------------------ALPSDPELMKTEPSWD------------
-------------------------------VNRLRTSLVAISALRAQGG----------
---------VGPQV----------------TSHVWGLMKAKDSIKP--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------DDASKQ------------
--------------------------GLEWLTTEE-----GALWVVRTVDSKYSPSGVFL
------------------------------------------------------------
----
>gnl|BL_ORD_ID|2138 @Ustilago_maydis@ jgi|Ustma1|2139|UM02139
M----------------SLIVILL---------------WAFQVARAAPAGPADRNTDWQ
QYLRGSSTQPGLSWPHQHQGSTSSDL----------------------------------
-------RSNYELQDAGAGYWSPANSH---------------------------------
--------------------------------------------------------FDSD
PAQSSQHWGEHAHDIQPSQSWSHNFAPHHPLTQYEHDYSYTPPELNTEDLEMLRDILTDS
DNDGTSSVYRSN------------------------------------------------
------------------------------------GRDASIGKNVVNVGH---------
-----INNDQTHSSLYRDMHFSDAEPSQSW--------------------NYASTPHHTI
SPY------------------------------------------DLS------------
--------------HTPRLLNAEELEFLHNALMASDSEALPPSGRPIGGETNTAFNVAKN
PQTDQGESMSSSVPRKRVRKSSQVHGEERIRKQPESLKRTEPEVLRSIPYTEPLGSDRQT
LGVLALRPNEKLIQEISSRVFAGKLRVAQEHLFYHLRM----------------------
------------------------------------------------------------
------------------------------------------EDYFRKWPLRRRNRRLPL
ISTTAADG------------------KTKLRIHMTDHYSSPRNANLRGTILENKQYYMFF
GVPETLQAKNPIEYYGSGYIDVKDHSAVDQHLLPLLKGL---------------------
----
>gnl|BL_ORD_ID|2744 @Nematostella_vectensis@ jgi|Nemve1|41453|gw.1924.2.1
X--------------------------------------------------------KNH
LDPNKIGRLEVGTETIIDKSKSVKSVLMQLFEDSGNTEIEGIDTTNACYGGTQALFNALS
WIESSAWDGRLAIVVAADIAVYAAGNARSSGGAGAIAMLVGPHAPLVVERGMPLNXLDHN
KHEYTVTHTCQPPKISRFEFFWGGVGYIHFFERREGEDVKNLETPPNAGELTDIVTGDSY
EITLLXFIRTSHFHLRLGXFYHLLLPTNFKFLSFAGLFRDIKLSETFQDENLAKEIEKAS
VKASQGVFDAKARPCTHVAQDVG-------------------------------------
------------------------------------------------------------
--------------------------------------------------NMYTPSLY--
-------------------------------------GSLVSLLNSVP------------
---------------------------ASQLAGKRIGMFSYGSGLASAMF----------
---------SIRVSPNTSPSSPLTNLVGSLSDVPSRLACRSEVSPSDFVATLELREKTHH
ASSYVPKGSIHMLFPGTYYLESV-------------------------------------
------------------------------------------------------------
------------------------------------------DDKFRR------------
--------------------------KYGRVSCARQNAASAR------------------
------------------------------------------------------------
----
