>Chlamydomonas_reinhardtii_Cre03.g169050.t1.1_PACid_19872172
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----YTLRMPSHGPFHVTTLTLPQLRASMERTSRTLRVFAWGFGVLGTALVVRKLFAQL-
-WRLRQHRIGQRRMAEAEAVRRQRAAERAAAAG-------------------------VN
GTAALAQAA-----------------AEEESGARNPGTCVVCMDRDADVVFTGCGHLCAC
YGCSTNL--------TKCPICR------------
>Zea_mays_GRMZM2G004023_T06_PACid_19546760
------------------------------------------------------------
-----------------------------PRIAAVRGYVRAHDKFFRAPFSGEAGVVTKH
TQMCLFTEWRGIFGWTFDLHALLFRSWKEQIVTSFRSVPFVLVSTELGNPTGVVHINVDK
ADQPLPLTTVFHKLIPLETTPYTLFQTIIGNGYPIALLDEEKILPIGKKITAIGLC-QAK
DAESVEITSCPEIPFFLSELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRGW-
-TRIKLR-------------REARHARQMFEEA---------------------------
---------EDAIHR---DDSS------DDDEIGDGQLCVVCLRKRRRAAFIPCGHLVCC
SECALTI---ERTPHPLCPMCRQDIRYMMRVY--
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPIGKKITAIGLC-RAK
NAESVEITSCPEIPFFLSELTKDEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRGW-
-KRIKLR-------------REARQAQQMFEDA---------------------------
---------EDAIRE---DNSS----DDDDDDVGDGQLCVVCLRKRRKAAFIPCGHLVCC
CKCALRM---EREVEPLCPMCRQDIRYMIRIY--
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPIGKELTAIGLC-RAN
DEGSVEISSCPELPFFLSELTKDEMQAQLASRARILFWGSVVLGTLSVCLVGHAIYRGW-
-KRIKLR-------------REARQAQQLFEEG---------------------------
---------EDAIQE---DDSS-------DEEVGDGQLCVVCLRKRRKAAFIPCGHLVCC
CKCALRM---ERETEPLCPMCRQDIRYMMRIY--
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPVGKEITAIGYI-RPH
KA-SVEISSCSEIPFFLSDLTKDEMEAELSSRAKTLFWASVVLGTMSVCLLGFATYRSW-
-KKIKER-------------REARQAQEVFRQT---------------------------
---------TDEVTD---DQSS----DEEAGEMGDGQLCVICLRKRRKAAFIPCGHLVCC
CKCALIV---ERQFDPLCPMCRQDIRYMIRIY--
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPIGKEITAIGLC-RVN
NQ-NVEITSCPEIPFFLSDLTKGEIEAELDSRARTLFWVTFALGTMSVGLLGHAIYRFW-
-EKVKQH-------------REARQAQQRFHQA---------------------------
---------DDEDDT-GENGSD----DDFPGEMGDGQLCVICLRKRRKAAFVPCGHLVCC
CNCAKRV---ELMNEPLCPVCRQDIQYMLRVY--
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
-------------------------------------------------ESGDKGVILQR
TQTCIYNEWKGLFGWTSDLRAIFARSWRQQESTSLRKVPFLLTDVGRRPNAEYVVVNMDG
SRHPLPLTTVYHKLQPITASPYTFLQALFGHEYPVGLLDEEKILPLGKDITAVGLC-SLK
NG-IAEIKSCKYLPYFRSDLSKDQMIMDLSIKTKILFWGGIALGSMSVGVLGYAVVRNW-
-NKWKQW-------------KQQRQLQQQRQAV---------------------------
---------SDV------EPQM----DDEIEDAPDGQLCVICLMRRRRSVFIPCGHLVCC
QGCAISV---EREVAPKCPVCRQEIRDSVRIY--
>Glycine_max_Glyma03g13060.1_PACid_16251643
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPLGKNITAVGLC-SLK
NG-IAEIKSCKDLPYFLSDLSKDQMIVDLSSKTKILFWGGIALGSMSVGVLGYAVVRNW-
-NKWKQW-------------KQQRQLQQQRQAV---------------------------
---------SDV------EPQM----DDEIEDVPDGQLCVICLMRRRRSVFIPCGHLVCC
QGCAISV---EREVAPKCPVCRQEIRDSVRIY--
>Glycine_max_Glyma16g01030.1_PACid_16301042
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPLGKDITAVGHC-SLK
NG-IAEIKSCKDIPYFLSDLSKDQMIVDLSIKAKILFWGGISLGSMSVGVLGYAVLRNW-
-IKWKRW-------------KVQRQLQQQRQAV---------------------------
---------SDA------EPQV----DDEIEDVPDGQLCVICLMRRRRSVFIPCGHLVCC
QGCAISV---EREVAPKCPVCRQEIRDSVRTY--
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPLGKEISAVGLC-SVK
DG-VLEIKSCKDFPYFLSEMSKDQMVVDLTSRTKVLFWSGIFLGSVSIGVLAYAVSRNW-
-NRWKVW-------------RQQRELQRSIRAS---------------------------
---------NAEAQI--QEEEE----EEDAGDVPDGQLCVICLMRRRRSAFIPCGHLVCC
QLCSISI---ERDVAPKCPVCRQQIRTSVRIY--
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------QDSGDRAVIVQR
TQTCIYNEWKGFFGWTSDLRAILSRSLRERKSSSLRTVPFVLIDGSQWPAVDYVVVNMDG
SKHHLPLTTVYHQLQPINASPYTFLQALFGHEYPVGLLDEEKILPIGKDVSAVGLC-FLK
NG-ILEIKSCKDLPYFLTEMTKDQMVIDLAFRTKILFWSSIFLGSASIGILGFAFVRNW-
-NRWKEW-------------RQRRRDEQQSHAA---------------------------
---------VDEATA---HI-A----EDELGDAPDGQLCVICLMRRRRSAFVPCGHLVCC
QRCALSV---EREVSPKCPVCRQTITNSVRIY--
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGLLDEEKLLPLGKEITAVGIC-SLK
NG-IPEIKSCKDLPYFLSEMSKDQMVVDLVFKSKVLFWSGVILGSVSIGVLGYAVVRNW-
-NRWKEW-------------RQQRGVRPPSQAV---------------------------
---------TDDTDT---QI-A----EDDAGDVPDGELCVICLMRRKRSAFVPCGHLVCC
QRCALSV---ERELSPKCPVCRQIIRSSVRIY--
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGLLDEEKILPLGKEINAVGIC-SSR
NG-VLEIKSCKDLPYFLSDMTKDQMVVDLAFKTKVLLWSGVVLGSLSIGILGYAAVRNW-
-NRWKEW-------------RQHRQSQQQNHAA---------------------------
---------STDDDP---QIDA----DEEAGDVPDGQLCVICLMRRRRSAFIPCGHLVCC
QLCAISV---EREVSPKCPLCRQAVRNSMRIF--
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPLGKEINAVGLC-GSK
NG-ILEITSCKDLPFFLSDLSKEQMVVDLAFKTKVLFWSGVVLGSFSICILGYAAVRNW-
-NRWKAW-------------RQQRQFQQQSNSV---------------------------
---------SDADVS---QIDV----EEETVDVPDGQLCVICLMRRRRAAFIPCGHLVCC
QICAISV---EREVSPKCPLCRQAVRNSIRIF--
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGLLNEEKILPLGKDISAVGIC-SFK
NG-IPEIMSCKDLPYFLSDLTKDQMLLDLAFRTKILFWSGIILGSLSISILGYAALRNW-
-NRWKER-------------RQQRQAHQPSHAA---------------------------
---------SIDANS---ELTG----EEEIGDIPDGQLCVICLMRRRVPAFIPCGHIACC
QPCALSV---ERELTPKCPVCRQEIRGSMRVF--
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGVLHEEKILPLGKCISAVGIC-NSK
DG-IPEIKSCKELPYFLADMTKDEMVADLAFKAKILLWSGIVLGSLSIGVLGFAVMRNW-
-NKWKAW-------------RQRRS-QQPIHTT---------------------------
---------SDEDVS---QIDD----NEDAGDVPEGQLCVICLMRRRRAAFIPCGHLACC
HTCAVSV---ESEVSPKCPLCRQAVRNSIRIF--
>Populus_trichocarpa_POPTR_0001s16880.1_PACid_18238703
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGVLHEEKILPLGKCISAVGIC-NSK
KG-IPEIKSCKDLPYFLADITKDQMVADLAFKAKIQLWSGIFLGSLSIGVLGFAVMRNW-
-NKWQAW-------------RQRHS-HLPNHTT---------------------------
---------IDADVS---RID-----EDEAGDVPDGQLCVICLTRRRRSAFIPCGHLACC
HFCAISV---ESEVSPKCPLCRQAIRNSIRVF--
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGLLYEEKILPLGKDITAVGIC-NLK
NG-IPEIKSCEDLPYFLSILTKDQMIADLSFKSKVLLWSGLILGTVAIGVLGYSISRNW-
-SKWKEW-------------KARRAQQQQNASR---------------------------
---------IENL-----DETE----EEESGDVPDGELCVVCLMRRRRSAFVPCGHLVCC
HRCAFSV---EREVSPKCPVCRQPIRNSVRIY--
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGVLDEEKILPLGKNISAVGIC-SFE
NG-VPVIKSCSDFPHFLCEMTKDQMILDLVFKTKFLFWSSIVLGSLTVGILGYSAARNW-
-NRWKQW-------------RQHRQLQNSRNDSPTSQLDSSNDIPIYGDFASDDEAATVP
DDELSSHVPDDELSS---HVPD----DELSSHVPDGQLCVICLMRRKRSAFIPCGHLVCC
ERCAVSV---ERESSPKCPICRQQIRSSVRIY--
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPLGKEITAVGHC-TLQ
DG-NPQIISCKKVPYFLSDMTKDQMIVDLVSKKKILFWAGIVLGSVSLGVLGYALTRNW-
-QRLKEW-------------RQRRQIQQSREEE---------------------------
---------IANLDATPEDTRA----DEETEDIPEGQLCVICLMRRKRAAFVPCGHFVCC
YRCALSV---ERDSAPKCPLCRQDIRTSVRIY--
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGDKALIIQ
RTQTYVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVIVGKDQQSNSSFVAVNMDG
SRQPLPLTTVYNRLQPINSS---FLQAFLYPDYPVGLLDIEKILPPGKDITAVGIY-SFN
NG-VPEIKSCQDLPYFLSEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRTW-
-NKWKQW-------------NHQRELPQRPNDS---------------------------
---------VVDDE------------PEDADEIPDGELCVICVSRRRVPAFIPCGHVVCC
RRCASTV---ERELNPKCPVCLQSIRGSMRVYYS
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGLLDIEKILPPGKDITAVGIC-SFN
NG-VPEIKSCQDLPYFLSEMTKDKMIEELMDQTSFIFFGSVILGIVSVGILSYAAVRTW-
-NKWKQW-------------NHQRDLPQRPNEP---------------------------
---------VVDDE------------PEDADEIPDGELCVICVTRRRVPAFIPCGHVVCC
RVCASTV---ERELNPKCPVCLQSIRGSMRVY--
>Selaginella_moellendorffii_91152_PACid_15413277
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VGVIDEEKILPLNREITAVGFLSKHP
QG-LPAIKSSNQMPFFLTEFSREELIVELASATHALFWTGIVISSLALGVIGYSAFKNW-
-CKWKEW-------------RRLRQIQEELR-----------------------------
---------REEQVM---EEDEEPATTQEGSEVPDGQLCVVCLLRRKRAAFITCGHRVCC
MGCARRIRHSQNAANARCPVCRQSVSGYIRVY--
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPLGAEITAVGVLHTAP
DG-TPVVKSSKRLPIFLTEFTREQLLVELASSTKVLFWMGVAVSTVAAGVLGYSLVKNW-
-TRWKQR-------------QQQRQSQNNSEN----------------------------
---------RQNSTI----EDE----AENFEDIPDGELCVVCLLRRRRAAFIYCGHRVCC
MGCAERV---EHGANPRCPVCRQSVTGIVRVY--
>Physcomitrella_patens_Pp1s15_293V6.1_PACid_18050435
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------KMVGLLDEERILQMGREITAVGILDSTP
DG-KPVIKPCSGLPIFLTECTREQLLMELARGTKMLLWLGVIATTFSAGVLTYAVIKNW-
-LRWKQH-------------RQLEEQQRVNEER---------------------------
---------RQQRLM---DEEE----VENLVDVPEGELCVVCLLRRRRSAFIHCGHRVCC
IVCARRV---QQGADPRCPVCRQ-----------
>Eucalyptus_grandis_Egrandis_v1_0.030865m_PACid_18770349
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------DMTFSSIELTKDQMVIDLACRTKILFWISIYLGKVSIGILGFAKLVT--
------------------------------------------------------------
-----------------------------IFYVPDGHFLVICLMRRGRSTFVPCGHLVCH
QRCALSM---EWEVSPKCSV--------------
>Eucalyptus_grandis_Egrandis_v1_0.028589m_PACid_18769331
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MTKDQMVIDLACQTRILFWISIYLGKVSIDGKSGGSADGM-
-SRSSSS-------------RAMLQSTSPTQT----------------------------
--------------------------QWMIGSVPDGHLLVICLMRRGRSTFVPCGHLVCR
QRCALSV---EREVSPKCSV--------------
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------KKILPLGKEINAIGLC-SLQ
DG-NLHIKATQELPYFLSEMTKGEMVKHLAYKTTILFWGGCIIGIVSLGVLGYTSFRIW-
-EWWKVR-------------RQHFSNAEVDDV----------------------------
--------------------------YIGNDEIPSEQLCTICTMRRKKYACVPCGHLVCC
HKCARSI---QHDSTARCPECRHIMWFRLDVS--
>Aquilegia_coerulea_v1.025445m_PACid_18167601
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------QEMVVELTHKTNCLFWSAIIFGSLSLGFLGCYLTRPWL
LKWWEQR-------------RRIRQSRRN-------------------------------
--------------------------RELTEDISLEYLCVICLARKRTTAFLPCGHFVSC
RTCAPHV---VE--THKCPVCRQTINASAHIF--
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKILPLGKEISVVGIG-TSE
YG-NVEIKPCDELPYFLSDLTKDQMIGELAQKTNYLLLSAIFFGSLSLAVIAYAVMIGC-
-QRFEEK-------------TQQRRQVQQQMTQ---------------------------
---------VQQSLR---NDVV----EEGMEALPEGLSCVV-------SVFVPCGHLVCC
QTCAPLV---AR--DRRCPICRQYIQKYIITY--
>Arabidopsis_lyrata_334747_PACid_16034463
------------------------------------------------------------
---------------------------VDELKGLGEFLETKPLNNTVVVFGTVGSTSTVE
TMCKSALGVFVEETATVTYDRRNCVGLIREHESTLVNRKEVSWYLEDGTARVNVTNYQHA
KGFDDILRTYSSTVPVSKHFKRLLSVEEITICDPDSCESWEDVLEIGTPLTIVGGAGRDK
DG-NITIRHVYQV--FNKRIELKKLISNMESKSVNYGNFSIYFAAMGMVLL---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
