>Chlamydomonas_reinhardtii_Cre03.g169050.t1.1_PACid_19872172
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------YTLRMPSH-GP-FHV-----TTLT
L-------PQLRASMERTSRTLRVFAWGFGVLGTALVVRKLFAQL------------WRL
RQHRIGQRRMAEAEAVRRQRA---------------------------------------
-AERAAAAG--VNGTAALAQAAAEEES-----GARNPGTCVVCMDRDADVVFTGCGHLCA
CYGCSTNL---TK-----CPICR------------
>Arabidopsis_lyrata_334747_PACid_16034463
----------------------------------------VDE----LKGLGEFL--ETK
PLNNTVVVFGTVGSTSTVETMCKSALGVFVEETATVTYDRR-------------------
-------NCVG----------LIREHESTLVNRKEVSWYLEDGTARVNVTNYQHA-----
KGFDDILRTYSSTVPVSKH----------------------F-----------KRLLSVE
EITICDPDSCESWEDVLEIGTPLTIVGGAGRDKDGNITIRHVYQ----VFN-----KRIE
L-------KKLISNMESKSVNYGNFSIYFAAMGMVLL-----------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>Zea_mays_GRMZM2G004023_T06_PACid_19546760
------------------------------------------------------------
-----------------------------PRIAAVRGYVRAHDKFFRAPFS-----GEAG
VVTKHTQMCLFTEWRGIFGWTFDLHALLFRSWKEQIVTSFRSVPFVLVSTELGNP-----
TGVVHINVDKADQPLPLTT-VFHKLIPLETTPYTLFQTIIGN-----------GYPIALL
DE-----------EKILPIGKKITAIGLC-QAKDAESVEITSCPEIP-FFL-----SELT
K-------DEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRGW-------TRIKLRRE
A-RHAR-------------QM------------------------------------FEE
AEDA--IHRD-DSS---------D-DD-----EIGDGQLCVVCLRKRRRAAFIPCGHLVC
CSECALTI---ERTPHPLCPMCRQDIRYMMRVY--
>Sorghum_bicolor_Sb01g045370.1_PACid_1954575
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPIGKKITAIGLC-RAKNAESVEITSCPEIP-FFL-----SELT
K-------DEMQAQLASRARILFWGSIVLGTLSVCLVGHAIYRGW-------KRIKLRRE
A-RQAQ-------------QM------------------------------------FED
AEDA--IRED-NSSD-------DD-DD-----DVGDGQLCVVCLRKRRKAAFIPCGHLVC
CCKCALRM---EREVEPLCPMCRQDIRYMIRIY--
>Setaria_italica_Si036246m_PACid_19684534
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPIGKELTAIGLC-RANDEGSVEISSCPELP-FFL-----SELT
K-------DEMQAQLASRARILFWGSVVLGTLSVCLVGHAIYRGW-------KRIKLRRE
A-RQAQ-------------QL------------------------------------FEE
GEDA--IQED-DSS-----------DE-----EVGDGQLCVVCLRKRRKAAFIPCGHLVC
CCKCALRM---ERETEPLCPMCRQDIRYMMRIY--
>Oryza_sativa_LOC_Os03g08000.1_PACid_16845209
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPVGKEITAIGYI-RPHKA-SVEISSCSEIP-FFL-----SDLT
K-------DEMEAELSSRAKTLFWASVVLGTMSVCLLGFATYRSW-------KKIKERRE
A-RQAQ-------------EV------------------------------------FRQ
TTDE--VTDD-QSSD-------EE-AG-----EMGDGQLCVICLRKRRKAAFIPCGHLVC
CCKCALIV---ERQFDPLCPMCRQDIRYMIRIY--
>Brachypodium_distachyon_Bradi1g72800.1_PACid_16480157
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPIGKEITAIGLC-RVNNQ-NVEITSCPEIP-FFL-----SDLT
K-------GEIEAELDSRARTLFWVTFALGTMSVGLLGHAIYRFW-------EKVKQHRE
A-RQAQ-------------QR------------------------------------FHQ
ADDEDDTGEN-GSDD-------DF-PG-----EMGDGQLCVICLRKRRKAAFVPCGHLVC
CCNCAKRV---ELMNEPLCPVCRQDIQYMLRVY--
>Citrus_sinensis_orange1.1g016312m_PACid_18132960
------------------------------------------------------------
---------------------------------------------ILVSES-----GDKA
VILEQRKAFLYNEWRDLFGWTPDIRAIFGRSLKTSEPSSLRTVPFILVEGDRWPQ-----
SDYIIVNMDGSRQPLPLTT-AYQRLELANVSPFTFLQAMFGL-----------KCPIGVL
AE-----------EKILPLGKDISAVGIC-NFKNG-IPEIKSCKDLP-YFL-----SEKT
K-------DQMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRNW-------NRWKD-RQ
Q-RMSR-------------QL------------------------------------TET
PSDD--ADSQ-IGSD-------EEVAG-----DIPDGQLCVVCLTRRRISAFNPCGHLVC
CRRCAISV---EREASPKCPVCRMTVRSSMRIY--
>Citrus_clementina_0.9_012472m_PACid_19274709
------------------------------------------------------------
---------------------------------------------ILVSES-----GDKA
VILEQRKAFLYNEWRDLFGWTPDIRAIFGRSLKTSEPSSLRTVPFILVEGDRWPQ-----
SDYIIVNMDGSRQPLPLTT-AYQRLELANVSPFTFLQAMFGL-----------KCPIGVL
AE-----------EKILPLGKDISAVGIC-SFKNG-IPEIKSCKDLP-YFL-----SEKT
K-------DLMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRNW-------NRWKD-RQ
Q-RMSR-------------QL------------------------------------TEA
PSDD--ADSQ-IGSD-------EDVAG-----DIPDGQLCVVCLTRRRISAFNPCGHLVC
CRRCAISV---EREASPKCPVCRMTVRSSMRIY--
>Citrus_sinensis_orange1.1g028047m_PACid_18128173
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------LQAMFGL-----------KCPIGVL
AE-----------EKILPLGKDISAVGIC-SFKNG-IPEIKSCKDLP-YFL-----SEKT
K-------DLMVVDLVNRSKILFWSGIVLGSLSIGILGYAIVRNW-------NRWKD-RQ
Q-RMSR-------------QL------------------------------------TEA
PSDD--ADSQ-IGSD-------EDVAG-----DIPDGQLCVVCLTRRRISAFNPCGHLVC
CRRCAISV---EREASPKCPVCRMTVRSSMRIY--
>Glycine_max_Glyma18g27930.1_PACid_16309372
------------------------------------------------------------
-------------------------------------------------ES-----GDKG
VILQRTQTCIYNEWKGLFGWTSDLRAIFARSWRQQESTSLRKVPFLLTDVGRRPN-----
AEYVVVNMDGSRHPLPLTT-VYHKLQPITASPYTFLQALFGH-----------EYPVGLL
DE-----------EKILPLGKDITAVGLC-SLKNG-IAEIKSCKYLP-YFR-----SDLS
K-------DQMIMDLSIKTKILFWGGIALGSMSVGVLGYAVVRNW-------NKWKQWKQ
Q-RQLQ-------------QQ------------------------------------RQA
VSD-----VE-PQMD-------DE-IE-----DAPDGQLCVICLMRRRRSVFIPCGHLVC
CQGCAISV---EREVAPKCPVCRQEIRDSVRIY--
>Glycine_max_Glyma03g13060.1_PACid_16251643
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGKNITAVGLC-SLKNG-IAEIKSCKDLP-YFL-----SDLS
K-------DQMIVDLSSKTKILFWGGIALGSMSVGVLGYAVVRNW-------NKWKQWKQ
Q-RQLQ-------------QQ------------------------------------RQA
VSD-----VE-PQMD-------DE-IE-----DVPDGQLCVICLMRRRRSVFIPCGHLVC
CQGCAISV---EREVAPKCPVCRQEIRDSVRIY--
>Glycine_max_Glyma16g01030.1_PACid_16301042
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGKDITAVGHC-SLKNG-IAEIKSCKDIP-YFL-----SDLS
K-------DQMIVDLSIKAKILFWGGISLGSMSVGVLGYAVLRNW-------IKWKRWKV
Q-RQLQ-------------QQ------------------------------------RQA
VSD-----AE-PQVD-------DE-IE-----DVPDGQLCVICLMRRRRSVFIPCGHLVC
CQGCAISV---EREVAPKCPVCRQEIRDSVRTY--
>Medicago_truncatula_Medtr8g025010.1_PACid_17479694
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGKDVSAVGLC-SLRNG-IAEIKACNDLP-YYL-----SDLS
K-------DQMIVDLSFKTKLLFWSGILLGSMSVGIIGYAVVRNW-------NKWKQWKQ
Q-RQLQ-------------QR------------------------------------RQQ
PIE-----PV-PPTD-------DE-IE-----DVPDGQLCVICLMRRRRSVFIPCGHLVC
CQGCAISV---ESEVAPKCPVCRQEVRDSVRIF--
>Prunus_persica_ppa006914m_PACid_17656817
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGKEISAVGLC-SVKDG-VLEIKSCKDFP-YFL-----SEMS
K-------DQMVVDLTSRTKVLFWSGIFLGSVSIGVLAYAVSRNW-------NRWKVWRQ
Q-RELQ-------------RS------------------------------------IRA
SNAE--AQIQEEEEE-------ED-AG-----DVPDGQLCVICLMRRRRSAFIPCGHLVC
CQLCSISI---ERDVAPKCPVCRQQIRTSVRIY--
>Eucalyptus_grandis_Egrandis_v1_0.015104m_PACid_18759688
------------------------------------------------------------
------------------------------------------------QDS-----GDRA
VIVQRTQTCIYNEWKGFFGWTSDLRAILSRSLRERKSSSLRTVPFVLIDGSQWPA-----
VDYVVVNMDGSKHHLPLTT-VYHQLQPINASPYTFLQALFGH-----------EYPVGLL
DE-----------EKILPIGKDVSAVGLC-FLKNG-ILEIKSCKDLP-YFL-----TEMT
K-------DQMVIDLAFRTKILFWSSIFLGSASIGILGFAFVRNW-------NRWKEWRQ
R-RRDE-------------QQ------------------------------------SHA
AVDE--ATAH-I-AE-------DE-LG-----DAPDGQLCVICLMRRRRSAFVPCGHLVC
CQRCALSV---EREVSPKCPVCRQTITNSVRIY--
>Vitis_vinifera_GSVIVT01016752001_PACid_17827115
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGLL
DE-----------EKLLPLGKEITAVGIC-SLKNG-IPEIKSCKDLP-YFL-----SEMS
K-------DQMVVDLVFKSKVLFWSGVILGSVSIGVLGYAVVRNW-------NRWKEWRQ
Q-RGVR-------------PP------------------------------------SQA
VTDD--TDTQ-I-AE-------DD-AG-----DVPDGELCVICLMRRKRSAFVPCGHLVC
CQRCALSV---ERELSPKCPVCRQIIRSSVRIY--
>Manihot_esculenta_cassava4.1_009144m_PACid_17976041
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGLL
DE-----------EKILPLGKEINAVGIC-SSRNG-VLEIKSCKDLP-YFL-----SDMT
K-------DQMVVDLAFKTKVLLWSGVVLGSLSIGILGYAAVRNW-------NRWKEWRQ
H-RQSQ-------------QQ------------------------------------NHA
ASTD--DDPQ-IDAD-------EE-AG-----DVPDGQLCVICLMRRRRSAFIPCGHLVC
CQLCAISV---EREVSPKCPLCRQAVRNSMRIF--
>Ricinus_communis_29706.m001280_PACid_16806294
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGKEINAVGLC-GSKNG-ILEITSCKDLP-FFL-----SDLS
K-------EQMVVDLAFKTKVLFWSGVVLGSFSICILGYAAVRNW-------NRWKAWRQ
Q-RQFQ-------------QQ------------------------------------SNS
VSDA--DVSQ-IDVE-------EE-TV-----DVPDGQLCVICLMRRRRAAFIPCGHLVC
CQICAISV---EREVSPKCPLCRQAVRNSIRIF--
>Carica_papaya_evm.model.supercontig_25.125_PACid_16414718
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGLL
NE-----------EKILPLGKDISAVGIC-SFKNG-IPEIMSCKDLP-YFL-----SDLT
K-------DQMLLDLAFRTKILFWSGIILGSLSISILGYAALRNW-------NRWKERRQ
Q-RQAH-------------QP------------------------------------SHA
ASID--ANSE-LTGE-------EE-IG-----DIPDGQLCVICLMRRRVPAFIPCGHIAC
CQPCALSV---ERELTPKCPVCRQEIRGSMRVF--
>Populus_trichocarpa_POPTR_0003s06390.1_PACid_18218320
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGVL
HE-----------EKILPLGKCISAVGIC-NSKDG-IPEIKSCKELP-YFL-----ADMT
K-------DEMVADLAFKAKILLWSGIVLGSLSIGVLGFAVMRNW-------NKWKAWRQ
--RRSQ-------------QP------------------------------------IHT
TSDE--DVSQ-IDDN-------ED-AG-----DVPEGQLCVICLMRRRRAAFIPCGHLAC
CHTCAVSV---ESEVSPKCPLCRQAVRNSIRIF--
>Populus_trichocarpa_POPTR_0001s16880.1_PACid_18238703
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGVL
HE-----------EKILPLGKCISAVGIC-NSKKG-IPEIKSCKDLP-YFL-----ADIT
K-------DQMVADLAFKAKIQLWSGIFLGSLSIGVLGFAVMRNW-------NKWQAWRQ
--RHSH-------------LP------------------------------------NHT
TIDA--DVSR-IDE--------DE-AG-----DVPDGQLCVICLTRRRRSAFIPCGHLAC
CHFCAISV---ESEVSPKCPLCRQAIRNSIRVF--
>Mimulus_guttatus_mgv1a007519m_PACid_17672175
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGLL
YE-----------EKILPLGKDITAVGIC-NLKNG-IPEIKSCEDLP-YFL-----SILT
K-------DQMIADLSFKSKVLLWSGLILGTVAIGVLGYSISRNW-------SKWKEWKA
R-RAQQ-------------QQ------------------------------------NAS
RIENLD-----ETEE-------EE-SG-----DVPDGELCVVCLMRRRRSAFVPCGHLVC
CHRCAFSV---EREVSPKCPVCRQPIRNSVRIY--
>Cucumis_sativus_Cucsa.360260.1_PACid_16980714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGVL
DE-----------EKILPLGKNISAVGIC-SFENG-VPVIKSCSDFP-HFL-----CEMT
K-------DQMILDLVFKTKFLFWSSIVLGSLTVGILGYSAARNW-------NRWKQWRQ
H-RQLQ-------------NSRNDSPTSQLDSSNDIPIYGDFASDDEAATVPDDELSSHV
PDDE--LSSH-VPDD-------EL-SS-----HVPDGQLCVICLMRRKRSAFIPCGHLVC
CERCAVSV---ERESSPKCPICRQQIRSSVRIY--
>Aquilegia_coerulea_v1.024769m_PACid_18143411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGKEITAVGHC-TLQDG-NPQIISCKKVP-YFL-----SDMT
K-------DQMIVDLVSKKKILFWAGIVLGSVSLGVLGYALTRNW-------QRLKEWRQ
R-RQIQ-------------QS------------------------------------REE
EIANLDATPEDTRAD-------EE-TE-----DIPEGQLCVICLMRRKRAAFVPCGHFVC
CYRCALSV---ERDSAPKCPLCRQDIRTSVRIY--
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPE-----TGDK
ALIIQRTQTYVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVIVGKDQQSN-----
SSFVAVNMDGSRQPLPLTT-VYNRLQPINSS---FLQAFLYP-----------DYPVGLL
DI-----------EKILPPGKDITAVGIY-SFNNG-VPEIKSCQDLP-YFL-----SEMT
K-------DKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRTW-------NKWKQWNH
Q-RELP-------------QR------------------------------------PND
SVVD--DEPE-------------D-AD-----EIPDGELCVICVSRRRVPAFIPCGHVVC
CRRCASTV---ERELNPKCPVCLQSIRGSMRVYYS
>Arabidopsis_lyrata_474546_PACid_16040628
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGLL
DI-----------EKILPPGKDITAVGIC-SFNNG-VPEIKSCQDLP-YFL-----SEMT
K-------DKMIEELMDQTSFIFFGSVILGIVSVGILSYAAVRTW-------NKWKQWNH
Q-RDLP-------------QR------------------------------------PNE
PVVD--DEPE-------------D-AD-----EIPDGELCVICVTRRRVPAFIPCGHVVC
CRVCASTV---ERELNPKCPVCLQSIRGSMRVY--
>Selaginella_moellendorffii_91152_PACid_15413277
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGVI
DE-----------EKILPLNREITAVGFLSKHPQG-LPAIKSSNQMP-FFL-----TEFS
R-------EELIVELASATHALFWTGIVISSLALGVIGYSAFKNW-------CKWKEWRR
L-RQIQ-------------EE------------------------------------LRR
EEQVMEEDEE-PATT-------QE-GS-----EVPDGQLCVVCLLRRKRAAFITCGHRVC
CMGCARRIRHSQNAANARCPVCRQSVSGYIRVY--
>Physcomitrella_patens_Pp1s52_256V6.4_PACid_18074372
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGAEITAVGVLHTAPDG-TPVVKSSKRLP-IFL-----TEFT
R-------EQLLVELASSTKVLFWMGVAVSTVAAGVLGYSLVKNW-------TRWKQRQQ
Q-RQSQ-------------NN------------------------------------SEN
RQNSTIEDE-----A-------EN-FE-----DIPDGELCVVCLLRRRRAAFIYCGHRVC
CMGCAERV---EHGANPRCPVCRQSVTGIVRVY--
>Physcomitrella_patens_Pp1s15_293V6.1_PACid_18050435
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------KMVGLL
DE-----------ERILQMGREITAVGILDSTPDG-KPVIKPCSGLP-IFL-----TECT
R-------EQLLMELARGTKMLLWLGVIATTFSAGVLTYAVIKNW-------LRWKQHRQ
L-EEQQ-----------RVNE------------------------------------ERR
QQRLMDEEE-----V-------EN-LV-----DVPEGELCVVCLLRRRRSAFIHCGHRVC
CIVCARRV---QQGADPRCPVCRQ-----------
>Eucalyptus_grandis_Egrandis_v1_0.030865m_PACid_18770349
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------DMT-FSS-----IELT
K-------DQMVIDLACRTKILFWISIYLGKVSIGILGFAKLVTI---------------
------------------------------------------------------------
-------------------------------FYVPDGHFLVICLMRRGRSTFVPCGHLVC
HQRCALSM---EWEVSPKCSV--------------
>Eucalyptus_grandis_Egrandis_v1_0.028589m_PACid_18769331
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------MT
K-------DQMVIDLACQTRILFWISIYLGKVSIDGKSGGSADGM-------SRSSSSRA
MLQSTS------------------------------------------------------
-----------------------PTQTQWMIGSVPDGHLLVICLMRRGRSTFVPCGHLVC
RQRCALSV---EREVSPKCSV--------------
>Aquilegia_coerulea_v1.022773m_PACid_18144013
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------KKILPLGKEINAIGLC-SLQDG-NLHIKATQELP-YFL-----SEMT
K-------GEMVKHLAYKTTILFWGGCIIGIVSLGVLGYTSFRIW-------EWWKVRRQ
HFSNAEVD----------------------------------------------------
-------------------------DVYIGNDEIPSEQLCTICTMRRKKYACVPCGHLVC
CHKCARSI---QHDSTARCPECRHIMWFRLDVS--
>Aquilegia_coerulea_v1.025445m_PACid_18167601
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------QEMVVELTHKTNCLFWSAIIFGSLSLGFLGCYLTRPW-----LLKWWEQRRR
I-RQSR------------------------------------------------------
-------------------------RNRELTEDISLEYLCVICLARKRTTAFLPCGHFVS
CRTCAPHV-----VETHKCPVCRQTINASAHIF--
>Aquilegia_coerulea_v1.012733m_PACid_18142466
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EKILPLGKEISVVGIG-TSEYG-NVEIKPCDELP-YFL-----SDLT
K-------DQMIGELAQKTNYLLLSAIFFGSLSLAVIAYAVMIGC-------QRFEEKTQ
QRRQVQ-------------QQ------------------------------------MTQ
VQQSLRNDVV------------EEGME-----ALPEGLSCVV-------SVFVPCGHLVC
CQTCAPLV---AR--DRRCPICRQYIQKYIITY--
