>rsz9l20
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------EPVPTARRARNESRHR-CVLCLD
Q-C--QGPTCTACGH-----VFCWICILDW--VRQQNSCPVCRRE-----------A-QL
--------
>sz98a18
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CSICFE
VPL--EDPVVTMCGH-----LFCWSCLHRW--MAQHATCPVCKSL-----------V-DR
ERVIPLYG
>sz14n09
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CPICGE
H-F--RAPVLLECGH-----SFCSECIRRA--LVYRSECPQCR-----------------
--------
>sz14d10
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CPLCMR
L-L--YEPLTTPCGH-----TFCRSCLARA--LDHASYCPICR-----------------
--------
>rsz12o01
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CVLILV
H-A--FNGLFTIVDT----VLVNHA-------QSNXSECPMCRVT-----------I-TL
RIRLY---
>SP1
MIPWGGVTCC---------LSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSK
ILPFIVAVSGRVGS--ETPIKCEHSGIRGVIVEETAEQHFLKHNETGS-WVQDSALMLSM
SKEVPWF-----------------------------------LDDGTSRVHVMGARGATG
FALTVGSEVFEES---GR-SLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDD
IGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLE
R------RRRRQLQ-KRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDL-CVICLE
Q-E--YNAVFVPCGH----MCCCTAC------SSHLTSCPLCRRR-----------I-DL
AVKTYRH-
>SPL1_NP_564745
MIHLAGFTCC---------LGGVALYLLTRSTGRD---IKSITRVYQLKDLEQLVEVESK
VVPLIIAVSGDVGS--ETPIKCEHSYVLGVFLKRTAEQQVLRRNWRFS-WVRNSTLMQPM
TKEVPWY-----------------------------------LDDGTGRVNVDVSQGELG
LALTVGSDVFEKA---EPVSLVQGALGYLKGFKILGVRHVERVVPIGTPLTVVGEAVRDG
MGNVRIQKPEQGPFYVTYIPLDQLISKLGDLSRRFKYASMGLTVLGVILISKPVIEYILK
RIEDTLERRRRQFALKRVVDAAARRAKPVTGG----------GTSRDGDTPDL-CVVCLD
Q-K--YNTAFVECGH----MCCCTPC------SLQLRTCPLCRER-----------I-QQ
VLKIYRH-
>Mulan_NP_078820
MESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQELKGAKKVHLGEDLKSILSEAPG
KCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQR
TNTVPFD-----------------------------------LVPHEDGVDVAVRVLKPL
DSVDLGLETVYEKFHPSIQSFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGELVLDN
NSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRKQYLQ
RQERLRLKQMQEEFQEHEAQLLSRA-----------------KPEDRESLKSA-CVVCLS
S-F--KSCVFLECGH----VCSCTEC-YRA--LPEPKKCPICRQA-----------I-TR
VIPLYNS-
>rsz31o21
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------DL-CIICMT
D-P--RDTTVLPCGH----LCLCVDA-QLL--RVRSDRCPICRSP-----------V-D-
--------
>rsz7l15
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CTVCKA
Q-E--KQVTLLRCFH-----MFCRDCIQTNI-ANRNRKCPLCGEK-----------F---
--------
>rsz42d03
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ADAAKRELEQSTQ-CPVCFE
RLH--APSALVPCGH-----VLCKSCFVTLTTTLEEHLCPTCRQV-----------F-D-
--------
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNVLISPETGDKALIIQ
RTQTYVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVIVGKDQQSNSSFVAVNMDG
SRQPLPLTTVYNRLQPINSSFLQA---FLYPDYPVGLLDIEKILPPGKDITAVGIYSFNN
-GVPEIKSCQDLPYFLSEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVRTWNK
WKQWNHQRELPQRPNDSVVDDEP-------------------EDADEIPDGEL-CVICVS
R-R--RVPAFIPCGH----VVCCRRCASTVE-RELNPKCPVCLQS-----------I-RG
SMRVYYS-
>rsz73h07
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------FPNATEQELAAGDRTCIICRE
EMFGGAGAKKLVCGH-----IFHLRCLRSW--MERSMSCPTCRRD-----------I---
--------
