>rsz9l20_1
I-----------------------------------------------------------
------------------------------------------------------------
-----LSYVFTSHWKTCSTQFWHGCNHRQVRHCHIRAFSAIRRARNAAYNEFIRGCRGNV
SHSTVPLDDKLDKSFADAPSPGCRSNRRRVHRQYMWGPGTDPSRAR------SGVATRFA
LALQWVQARIWAIPQTMTAVDLS-------------------------------------
-----------------------FWSQEARFLRPRIDLWCA-------------------
-QRSPSEAEPARRHHLRFASRWIHWHTFCETAQV--------------------------
----------------------PIKARGAFASMLDAASTHQWVRGRAARAKDLEHH----
-------------------------IEVNTPLTAQYARDAHQQASSLGHSSAHT------
-------------------------
>rsz14d10_2
P-----------------------------------------------------------
-----------------------------IFKGVCGSSCRALLIQTGSHAGINAGDECSS
LEIPSWFLLCKQFDYTRHPLSRSPRLSHVVLRCMVALSPLVSASDERRDAFECMARGICR
H----------------------------------LRLTRALLVSD------KYKSYTTW
FTTRRLHNRVQRALQTAQVAMFT--SCCTFYLIRESLGLFP----------HHEKQQKRR
CNNGSWTCACLSLLVVVAAVAALHSKSSKEHGTTGAHAPHH-------------------
-LIQPFERTAHLQETLSLCCFWCSMMGX--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>rsz12o01_3
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--FESLYSIQTNSQCDGHSTHGTLRXVALRMVDKYSVHNCK-------------------
-QSIERMDQNQHTRHIQVPCVLECYRLRCYASNX--------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>rsz9l20_3
P-----------------------------------------------------------
---------------------------------------------------LVRVYVPLE
DLFHSILAWVQSPSGTLSYGVFSDPTSTERLGIQIHPRLRQRKSFNCASRRQTGQEFCRT
QSRMQIQQKTCPQAVHVGP----------------WHSKQSTQRCR------DSFRARLA
VGTGSNLGDTTDHDRCSVVLEPG--SPVSSPENRSVVCTAV----------TIGRACETP
SPAIRFEVDTLAYILRNSSSAHLKSTRSFRF-----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------HAGRCINTSMGSRTSCTMSKRPRASYRGEYALDRP
ICTRRTPASLFAGSRPY--------
>rsz7l15_3
R-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------LNRLR
VAQRRQLQASIAHVMLVVLVYQAPWRDLCQIHTSSLVPTSRKPRAY------ERPHTHPY
IHARKRGRSLRGANRTPGIRESL-------RRKRSVSHRRCRIFRHITGICDFDSRYSFE
CNPDRTCENSEAVPVSPELCRRCSRACVAYLRSFRVASRHR-------------------
-RSLQRCACVIVRARAPAATRVVRYAFSLRLQHA--------------------------
-------------------------------------------APLFAVRSDHEAEPVLH
GVLPAIGRTRQTAAGYTLPPRSFRRRGGRCRLACEQYAFRYSFSPTGSAAR---------
-------------------------
>rsz14n09_2
V-----------------------------------------------------------
------------------------------------------------------------
---------------------------------RYPATTTIRASILRYESGFTNLQVLND
SHSFFSLAKQVSGCGHPGAVPATRARYRTYTCSAEQTHTDIAQRLR------ACASVDAR
RTSTHTHTHTAAKVASRA-------VCAEARAIDRCSSVSM----------DAQTLPFRN
AYARILINNESRTAIGPVWASSSVHHRLLGLFHSHQTAPTG-------------------
-KTGYNEPSSKISRKEFELHSRSCTHQNLRLTRS--------------------------
------------------------------------------------------------
-------------------------ASHENSPVAQLPRIDASMQETHASVQVVSVX----
-------------------------
>rsz14d10_3
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------RY------LRVYAARH
AERFYRQAVMPASTPATNALRKYPAGSCSANNFRTIHGIRAGVLAYPMWCCDAWSPYRHW
LAPATSAETLSSVWREASAGIGSRGRCAISTNRILHGSPRD-------------------
-AFTIGYRERCRQRKLPCSPAAALSTSSARVSGC--------------------------
--------------------------------------FHTTRSSKRGDATTDPGRAPAC
LYSLLLLLLLLSIRSRLRSMGRRRARTPRITLSSRSSALRISRRRCRSAVSGVVWA----
-------------------------
>rsz42d03_2
A-----------------------------------------------------------
--------------------------GXTFTLRSIRCTAYWPKRSLSRPARQQMLHGDTS
ACEYRKQRSWKFYANCLTKLMPRNVNSNKALSVRSVSNAYTPRRRWFHVGTCSAKAASSP
RQHLRSTSA--------------------------LHVVKSSIRFR------HYASTTRI
RSP-------RDGIGTPCLGRLI--TNFQSRTFDRSRAI---------------------
-----------PNPSTRSVCMAHHSFLISRIKTCPTTPRHL-------------------
-SIIAFCACIRFSACWKTTDCAHSMTSVTSRPRS--------------------------
------------------------------------------AGRQCMKIVSLTPV----
-------------------------ASRSSIEIPANARSRSAISFWPMLAX---------
-------------------------
>rsz7l15_2
SFESFKGRAEEAAAGVNRSCDAGGAGVPGALARLVPNPHILARTYMISLKATCITPAHTS
IHSCSQAWTLITWSKPYSWHSRVAQTKKI-------------------------------
------------------------------------------------GFTSSVPNFSPH
NGHLRFRFA--------------------------IFVMQSRQNMK------QRSSVTCF
SA-------LQTVQSLRRISSII--SCCQSTSLALVAAL---------------------
---RLRNSSSSCSSRDTRRSLRVFASSAARSASVCCSIPRS-------------------
-ASSPLRRLTCDWADSANCRWVYASAALFSAPRR--------------------------
------------------------------------------AMSACLRTIRISLL----
-------------------------IFSNWLCSS--------------------------
-------------------------
>rsz73h07_1
H-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---LGTTKVSGFFIMSYSPCFCSWLHTLRFSPMCIYSTVFRCTFCE------TQQPAPSD
RGSSSSFAIAKWCDPCTPSSRTL--QSKSPPATELASSVAR----------RCSVVLVLR
N------SSAATFSICDASAPGWNAAAARRAGEIYVLCGRQ-------------------
-QRVHVPLLHLVPLRTTTTERGETLRVASVRGRN--------------------------
------------------------------------------EARLRPSKRQRRLH----
-------------------------DGSTRQQCRRVRSSECALRRHLPTGRLPIRSIS--
-------------------------
>rsz14n09_3
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------DTQQRRRS
VLPFCGTSRVLRTSRCTTVTRSFLWRSKSVDAVIRVLCLLR----------ALAIAPIPA
ARSRHTQTLHSVYGHVRALTRGSARAHTHTHTLLRRWHRGR-------------------
---SAQKQGQIGAPVYRWTHRLYPSEMPMRSVFIMNREQQLAPFGPHRPFITDSSVFFIR
TKLHQQEKLGITNQVRKYLARSLSFTRAPVRIRIYDHAVLPMKTAQWHDSYLESMQ----
-------------------------ACKRLMHLSKSSAF---------------------
-------------------------
>rsz73h07_2
T-----------------------------------------------------------
------------------------------------------------------------
-----WXRQRSLAFLATLPVSAAGCIPCVFHLCAFILQSSAAHSARPSSDSPHLPTEAHR
VHSLSPSGA--------------------------IHAHPVPERYR------ARASRRRP
NLHHLSRGDVRWCWCETRLRPHF--------------------------------PSAMP
PLLDGTQHELPDVPARYTSSAGANNECTSRCFIWCRYAPRR-------------------
-RSAAKRSGPQYAAATRRDCAHRSASDGCTTGRH--------------------------
------------------------------------------------------------
-------------------------VSSAGEYAAANAPFDGICRQGGFRSGASX------
-------------------------
>rsz31o21_1
F-----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------RXCKSESTGERQMG
QRSLRT-----------------------------RNNCAQSTQRH------RWPHGSTV
VSRGSVMQMIQRSSCSASAAALG--EIFGA------------------------------
-------LKALQQNHNRVSMLGEFGRVLFEKKRLAISTGHE-------------------
-TAVAILAVPLAHTGLEWGRYWGHRLQRLDMELL--------------------------
------------------------------------------SARCAVREXPSPRR----
-------------------------LCRGPSTFAXKNKLQXKLLWIFGISNKAYTLLPNI
QVVLYGVRVNHGRNRLCGTLRTTLQ
>sz98a18_1
L-----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------LAYWXAAP
KRRXVVSDGGERPGQPVAYRRGTFDRGHTCTCALPRRHRVRGERTRHVTVQVSGCGGDRR
RSQATSGGILSSVKQATVLLHLF-------------------------------------
-----------------GAAGGSCGHHVWALVLLVVPAPLD-------------------
-GATRDVSGLQVAGGSGTSHSALRTRAHTRGRQRCPEAADEGR-----------------
------------------------------------------------------------
-------------------------QAKSDSTAACREAGRTSTPDCQRSASAA-------
-------------------------
>rsz31o21_3
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------NXQKIYRTTDGATIATHAQQLCS------VYTETQVA
TRQHRGIPRVRHANDTEIIVFCF--SGCSWRDLRRSQGAAA----------ESQSGIDAW
RVWPGSVRKETTRDIDWARNRGGYSGGTAGPYRPRMGVLGA-------------------
--PAPAARHGTAQRALCGSGXFAMKKTVQRPEHV--------------------------
------------------------------------------CXQKQTPTXTAVDF----
-------------------------RDLQGVHSSSEHSSRSLWCTREPWSEPAVWNAPHH
PAX----------------------
>rsz14n09_1
R-----------------------------------------------------------
------------------------------------------------------------
-----------------------SIPSNDDDPCFHSAVRVGFYEPPGAERQSLVLFFGEA
SQWMRSSGCCACYARSLSHLYLQRGADTHRHCTAFTGMCERREVAH------EHTHTHTH
CCEGGIEGGLRRSKGNRSVLQCI--DGRTDFTLPKCLCV---------------------
-----------------AYSNKIANSNWPRLGLIVRSSPTP-------------------
-RSFSFAPNCTNRKNWVRTKFENISQGVASLALL--------------------------
------------------------------------------YASESTTDTQCFPK----
-------------------------QPSGMTATSNRCKHARDSCICPSRQRX--------
-------------------------
>rsz42d03_3
P-----------------------------------------------------------
------------------------------------------------------------
-----AXRLRCAQYVARPIGRRDRYRGPQGNRCCMAIRALANTESSGAGNSTQIARSCRE
TTRTKHSVS--------------------------GLFRTPTRPVG------AGSMWARA
LQKLLRHLNDNTGAPLPYMSSSL--RSDFGTTHPLELEFAA----------QGTALVRPV
WAASSPISKVERSTEAERSRTLVHGACAWRITHFSSPESKL-------------------
-APRPHQDTAHSVRAFDFLPAGRQRTVRTPLDRL--------------------------
------------------------------------------LHGLARLVGSAKSY----
-------------------------RLRQWPPGAPSKFDNQQTPAHAQRSDPFGPCSPX-
-------------------------
>rsz14d10_1
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------VDIGCMRLVMQSAFDTD------RQSCRHQR
RRRMLFARNTQLVPALQTILGLY--TASAEQESSPIPCGVA----------MHGRLIATG
RQRRAQRRFRVYGERHLPAFKAHAGAVSERVQIVYYMVHHE-------------------
-TPSQSGTESAADSASCHVHQLLHFLPHPRESRA--------------------------
------------------------------------------VSTPREAAKEAMQQRILD
VRLLVSTRCCCCCCCSPFEVVGAWVDDGRARPASPYPAVRAHCASPGDVVALLFLVYDGP
-------------------------
>sz98a18_3
V-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------GLLGSGTETTXSCKR----------WRRAARSTG
RLPTRYLQGTHVHLCTPQTTQGSRRAHTARLNCPSLWMRRR-------------------
-QTPQPSDQRRHPQRQAVSNRLTAPSVLRCRWRI--------------------------
----------LWSPCVGTCSAGRACTAGWRNTRRVRFASRWWIGNESFRFTDAGAH----
-------------------------ARTSAMPRSSRRRSPGQMKRFHRGLPRGGSNLHPR
LPTERFRR-----------------
>sz98a18_2
C-----------------------------------------------------------
------------------------------------------------------------
-------------------------WPTGXRHRNDVXLAMAESGQVNRSPTDAVPLTGDT
RAPVHSPDD---------------------------------TGFE------ASAHGTSE
LSKSLDAEATDAAAKRPAAASSV--ASSSEQPFDCSICFEV----------PLEDPVVTM
C-GHLFCWSCLHRWMAQHATCPVCKSLVDRERVIPLYGRGR-------------------
-TREDVSDAPKQQTKVARPNEAIPPRPAARRVEPPPQTANGALPPX--------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>rsz73h07_3
P-----------------------------------------------------------
-----------------------------------------------------------G
XDKGLWLFYNELLSLFLQLAAYLAFFTYVHLFYSLPLHILRDLAVTARTFRQRLIEFIRY
RQVVRSMHT--------------------------QFPNATEQELA------AGDRTCII
CREEMFGGAGAKKLVCGHIFHLR-------------------------------------
--------------CLRSWMERSMSCPTCRRDIRPLRAPTT-------------------
-SARPAASSGAATHHDDGARRNAPGSLSTRPQRG--------------------------
------------------------------------------ATAPIEAPATAARR----
-------------------------VDTSAVPASTQQRMRPSTASADREASDPEHL----
-------------------------
>rsz42d03_1
RRQXVYAALNTLHGLLAEEIV---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------IEARKATD
AAWRYERLRIQKAAELEILRKLLDEADAAKRELEQSTQCPV----------CFERLHAPS
ALVPCGHVLCKSCFVTLTTTLEEHLCPTCRQVFDPISALRI-------------------
-HLNNSQPKGRHWYALSGPPHHQFPKSNVRQKPSDPEPYTERVHGASLIFNLVQNQNLPL
DHTKTPEHNSILCVHSIFCLLEDNGLCALHDLIGYFTASLGWAVHENRIAYASGLQ----
-------------------------ELHRNLITSKRPLTLSDLILLAHARP---------
-------------------------
>rsz9l20_2
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------SRTCLRPIGRPVPLN------SGMGAITV
RLDTVILGRFQRSDEHGTLRHTM----NSSEAVEATVIQLC----------LSTTNWTRV
LLTHPVQDADPTEDVSTGSTCGALALIQAEHAAVSRLVSRSPCSGYRLEFGRYHRPPLLI
CRSGARKPGFFARESICGVHSGHHLRPSLRDAIT--------------------------
------------------------------------------CDSLRGGYTGIHFAKQLK
CPFEKHAELSLPCWTLHQHINGFEDELHDEQKTSIISRIRPPPNMHETHTSKPLRWVIVA
PIX----------------------
>rsz12o01_1
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------RSSRFTA
YRRIRNVMVTRHMGHSEXLLCAWLTSTVST------------------------------
------IVNSPLNAWTRISTHGTFRFHVCSSVIGFDAMRRT-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>rsz31o21_2
S-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------EXA
KVNLQVNDRWGNDRYARATTVLSLHRDTGGHTAAPWYPAGPSCKYR------DHRVLLQR
LLLARSSALSRRCSRITIGYRCL--ASLAGFCSKRNDSRYR----------LGTKPRWLF
WRYRWPIPASNGVGTGGTGSSGSTWNCSARVVRFVRXLRHE-------------------
-EDCAEARARLRXKTNSNXNCCGFSGSLTRRTLF--------------------------
------------------------------------------FRTFKSFFMVYATM----
-------------------------VGTGCVERSAPPCX---------------------
-------------------------
>rsz12o01_2
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------VRVALQHTDEFAMWSLDTWDTPXSCS------AHGQVQCP
QLTVHTHGP---------------------------------------------------
----------------ESAHTAHSGSMCARVLSASMLCVER-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>rsz7l15_1
I-----------------------------------------------------------
------------------------------------VIVGSRRGGSCRRQSLMCWWCWCT
RRPGETCAKSTHPRSYLHDLVKSHVHMNARTHIHTFMLASVDAHYVEQTVLLAFASRSDE
KDRFHIVGA---------------------------------EFFA------TRAFAISI
RDIRLNAIPTEHVKTAKQCNLFL--LSFADGAVELASHIFD----------HFVLPVDIA
SARCSVALAFELVLQPRHASFATRFRFVCSTQRLCLLFDLT-------------------
-TKLSQFSTEASYLRLGGLGKLPLGIRFRRALFG--------------------------
------------------------------------------A-----------------
-------------------------EAGDVGLLANNTHFATHFLQLALQLX---------
-------------------------
