>rsz7l15_1
------------------------------------------------------------
-------------------------------------IVIVGSRRGGSCRRQSLMCWWCW
CTRRPGETCAKSTHPRSYLHDLVKSHVHMNARTHIHTFMLASVDAHYVEQTVLLAFA---
----------------------------SRSDEKDRFHIVGAEFFATRAFAISIRDIRLN
AIPTEHVKT----AKQCNLFLLSFADGAVELASHIFDHFVLPVDIASARCSVALAFELVL
QP---------------------------------------RHA------SFATRFRFVC
STQRLCLLFDLTTKLSQFSTEASYLRLGGLGKLPLGIRFRRALFGAEAGDVGLLANNTHF
ATH-FLQLALQLX---------------
>rsz31o21_1
------------------------------------------------------------
-----------------------------------------------FRXCKSESTGERQ
MGQRSLRTRNNCAQSTQRHRWPHGSTVVSRGSVMQMIQRSSCSASAAALGEIFGALK---
-----------------------------------------ALQQNHNRVSMLGEFGRVL
FEKKRLAIS-------TGHETAVAILAVPLAHTGLEWGRYWGHRLQRLDMELLSARCAVR
EX---------------------------------------PSP----------------
--RRLCRG-----PSTFAXKNKLQXKLLWIFGI---------SNKAYTLLPNIQVVLYGV
RVN-HGRNRLCGTLRTTLQ---------
>rsz14n09_2
------------------------------------------------------------
-------------------------------------------------------VRYPA
TTTIRASILRYESGFTNLQVLNDSHSFFSLAKQVSGCGHPGAVPATRARYRTYTCSA---
---------------------------------------EQTHTDIAQRLRACASVDARR
TSTHTHTHT------------AAKVASRAVCAEARAIDRCSSVSMDAQTLPFRNAYARIL
IN---------------------------------------NES----RTAIGPVWASSS
VHHRLLGL-----FHSHQTAPTGKTGYNEPSSKISRKEFELHSRSCTHQNLRLTRSASHE
NSP-VAQLPRIDASMQETHASVQVVSVX
>rsz14d10_2
------------------------------------------------------------
-------------------------------------------------------PIFKG
VCGSSCRALLIQTGSHAGINAGDECSSLEIPSWFLLCKQFDYTRHPLSRSPRLSHVV---
---------------------------------------LRCMVALSPLVSASDERRDAF
ECMARGICRHLRLTRALLVSDKYKSYTTWFTTRRLHNRVQRALQTAQVAMFTSCCTFYLI
RE---------------------------------------SLGLFPHHEKQQKRRCNNG
SWTCACLSLLVVVAAVAALHSKSSKEHGTTGAH------APHHLIQPFERTAHLQETLSL
CCF-WCSMMGX-----------------
>rsz14n09_3
------------------------------------------------------------
-----------------------------------------------FDTQQRRRSVLPF
CGTSRVLRTSRCTTVTRSFLWRSKSVDAVIRVLCLLRALAIAPIPAARSRHTQTLHS---
------------------------------VYGHVRALTRGSARAHTHTHTLLRRWHRGR
SAQKQGQIG-----------APVYRWTHRLYPSEMPMRSVFIMNREQQLAPFGPHRPFIT
DS---------------------------------------SVFFIRTKLHQQEKLGITN
QVRKYLAR-----SLSFTRAPVRIRIYDH---------------AVLPMKTAQWHDSYLE
SMQ-ACKRLMHLSKSSAF----------
>rsz9l20_3
------------------------------------------------------------
---------------------------------------PLVRVYVPLEDLFHSILAWVQ
SPSGTLSYGVFSDPTSTERLGIQIHPRLRQRK-SFNCASRRQTGQEFCRTQSR-------
------------------------------------------MQIQQKTCPQAVHVGPWH
SKQSTQRCR--------DSFRARLAVGTGSNLGDTTDHDRCSVVLEPGSPVSSPENRSVV
CT---------------------------------------AVTIGRACETPSPAIRFEV
DTLAYILR-----NSSSAHLKSTRSFRFHAGRCINTSMGSRTSCTMSKRPRASYRGEYAL
DRP-ICTRRTPASLFAGSRPY-------
>rsz7l15_2
------------------------------------------------------------
-----------------------------------------SFESFKGRAEEAAAGVNRS
CDAGGAGVPGALARLVPNPHILARTYMISLKATCITPAHTSIHSCSQAWTLITWSKP---
----------------------------YSWHSRVAQTKKIGFTSSVPNFSPHNGHLRFR
FAIFVMQSR-------QNMKQRSSVTCFSALQTVQSLRRISSIISCCQSTSLALVAALRL
RN---------------------------------------SSSSCSSRDTRRSLRVFAS
SAARSASV-----CCSIPRS--ASSPLRRLTCD-----WADSANCRWVYASAALFSAPRR
AMS-ACLRTIRISLLIFSNWLCSS----
>rsz14d10_1
------------------------------------------------------------
------------------------------------------------SVDIGCMRLVMQ
SAFDTDRQSCRHQRRRRMLFARNTQLVPALQTILGLYTASAEQESSPIPCGVAMHGR---
------------------------------------LIATGRQRRAQRRFRVYGERHLPA
FKAHAGAVS------------ERVQIVYYMVHHETPSQSGTESAADSASCHVHQLLHFLP
HP---------------------------------------RESRAVSTPREAAKEAMQQ
RILDVRLL-----VSTRCCCCCCCSPFEVVGAW----------VDDGRARPASPYPAVRA
HCA-SPGDVVALLFLVYDGP--------
>sz98a18_1
------------------------------------------------------------
-----------------------------------------------------LLAYWXA
APKRRXVVSDGGERPGQPVAYRRGTFDRGHTCTCALPRRHRVRGER--------------
------------------------------------------TRHVTVQVSGCGGDRRRS
QATSGGILS--------SVKQATVLLHLFGAAGGSCGHHVWALVLLVVPAPLDGATRDVS
GL---------------------------------------QV-----------------
-------------AGGSGTSHSALRTRAHTRGRQRCPEAADEGRQAKSDSTAACREAGRT
STP-DCQRSASAA---------------
>rsz7l15_3
------------------------------------------------------------
----------------------------------RLNRLRVAQRRQLQASIAHVMLVVLV
YQAPWRDLCQIHTSSLVPTSRKPRAYERPHTHPYIHARKRGRSLRGANRTPGIRESL---
--------------------------------RRKRSVSHRRCRIFRHITGICDFDSRYS
FECNPDRTC----------ENSEAVPVSPELCRRCSRACVAYLRSFRVASRHRRSLQRCA
CV---------------------------------------IVRARAPAATRVVRYAFSL
RLQHAAPL-----FAVRSDHEAEPVLHGVLPAI--------GRTRQTAAGYTLPPRSFRR
RGG-RCRLACEQYAFRYSFSPTGSAAR-
>rsz31o21_3
------------------------------------------------------------
--------------------------------------PNXQKIYRTTDGATIATHAQQL
CSVYTETQVATRQHRGIPRVRHANDTEIIVFCFSGCSWRDLRRSQGAAAESQSGIDA---
--------------------------------------WRVWPGSVRKETTRDIDWARNR
GGYSGGTAG-------------PYRPRMGVLGAPAPAARHGTAQRALCGSGXFAMKKTVQ
RP---------------------------------------EHV----------------
-------------CXQKQTPTXTAVDFRDLQGVHSSSEHSSRSLWCTREPWSEPAVWNAP
HHP-AX----------------------
>rsz31o21_2
------------------------------------------------------------
------------------------------------------------------------
-------SEXAKVNLQVNDRWGNDRYARATTVLSLHRDTGGHTAAPWYPAGPSCKYR---
---------------------------------------DHRVLLQRLLLARSSALSRRC
SRITIGYRC--------LASLAGFCSKRNDSRYRLGTKPRWLFWRYRWPIPASNGVGTGG
TG---------------------------------------SSGSTWNCSARVVRFVRXL
RHEEDCAEAR---ARLRXKTNSNXNCCGFSGSL--------TRRTLFFRTFKSFFMVYAT
MVGTGCVERSAPPCX-------------
>rsz73h07_1
------------------------------------------------------------
-----------------------------HLGTTKVSGFFIMSYSPCFCSWLHTLRFSPM
CIYSTVFRCTFCETQQPAPSDRGSSSSFAIAKWCDPCTPSSRTLQSKSPPA---------
------------------------------------------TELASSVARRCSVVLVLR
NSSAATFSI-------CDASAPGWNAAAARRAGEIYVLCGRQQRVHVPLLHLVPLRTTTT
ER---------------------------------------GET----------------
-----LRV-----ASVRGRNEARLRPSKRQRRL------HDGSTRQQCRRVRSSECALRR
HLP-TGRLPIRSIS--------------
>rsz7l15
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CTV-----CKAQEKQ-VTLLRCFHMFCR--------DCIQTNIANRNR-------
KCP-LCGEKF------------------
>rsz73h07
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------FPNATEQELAAGDRTCII
CR----------------------------------------------------------
-------------EEMFGGAGAKKLVCGHIFHL--------RCLRSWMERSM--------
SCP-TCRRDI------------------
>rsz73h07_3
------------------------------------------------------------
--------------------------------------------------PGXDKGLWLF
YNELLSLFLQLAAY-LAFFTYVHLFYSLPLHILRDLAVTARTFRQRLIEFIRYRQVV---
-------------------------------------------RSMHTQFPNATEQELAA
GDRTCIICR--------EEMFGGAGAKKLVCGHIFHLRCLRSWMERSMSCPTCRRDIRPL
RA------------------------------------------------------PTTS
ARPAASSG-----AATHHDDGARRNAPGSLSTR-----PQRGATAPIEAPATAARRVDTS
AVPASTQQRMRPSTASADREASDPEHL-
>rsz9l20
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------EPVPTARRARNESR
HR----------------------------------------------------------
-----CVL-----CLDQCQG-PTCTACGHVFCW--------ICILDWVRQQN--------
SCP-VCRREAQL----------------
>sz98a18
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CSI-----CFEVPLEDPVVTMCGHLFCW--------SCLHRWMAQHA--------
TCP-VCKSLVDRERVIPLYG--------
>sz98a18_2
------------------------------------------------------------
-------------------------------------------------------CWPTG
XRHRNDVXLAMAESGQVNRSPTDAVPLTGDTRAPVHSPDDTGFEASAHGTSELSKSL---
-------------------------------------DAEATDAAAKRPAAASSVASSSE
QPFDCSICF----------EVPLEDPVVTMCGHLFCWSCLHRWMAQHAT-----------
------------------------------------------------------------
-----CPV-----CKSLVDRERVIPLYGRGRTREDVSDAPKQQTKVARPNEAIPPRPAAR
RVE-PPPQTANGALPPX-----------
>sz14n09
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CPI-----CGEHFRA-PVLLECGHSFCS--------ECIRRALV--------YRS
ECP-QCR---------------------
>sz14d10
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CPL-----CMRLLYE-PLTTPCGHTFCR--------SCLARALDHAS--------
YCP-ICR---------------------
>rsz42d03_2
------------------------------------------------------------
-----------------------------------------AGXTFTLRSIRCTAYWPKR
SLSRPARQQMLHGDTSACEYRKQRSWKFYANCLTKLMPRNVNSNKALSVRSVSNAYT---
----------------------------------PRRRWFHVGTCSAKAASSPRQHLRST
SALHVVKSSIRFRHYASTTRIRSPRDGIGTPCLGRLITNFQSRTFDRSRAIPNPSTRSVC
MA---------------------------------------HHSFLISRIKTCPTTPRHL
SIIAFC-------ACIRFSACWKTTDCAHSMTSVTSRPRSAGRQCMKIVSLTPVASRSSI
EIP-ANARSRSAISFWPMLAX-------
>rsz14n09_1
------------------------------------------------------------
---------------------------------------------RSIPSNDDDPCFHSA
VRVGFYEPPGAERQSLVLFFGEASQWMRSSGCCACYARSLSHLYLQRGADTHRHCTA---
----------------------------FTGMCERREVAHEHTHTHTHCCEGGIEGGLRR
SKGNRSVLQ-------CIDGRTDFTLPKCLCVAYSNKIANSNWPRLGLIVRSSPTPRSFS
FA---------------------------------------PN-----------------
-------------CTNRKN--WVRTKFENISQGVASLALLYASESTTDTQCFPKQPSGMT
ATSNRCKHARDSCICPSRQRX-------
>rsz12o01_1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------SRSSRFTAYRRIR
NV----------------------------------------------------------
------------------------------------------------------------
-------------MVTRHMGHSEXLLCAWLTST------VSTIVNSPLNAWTRISTHGTF
RFH-VCSSVIGFDAMRRT----------
>rsz73h07_2
------------------------------------------------------------
--------------------------------------------------------TWXR
QRSLAFLATLPVSAAGCIPCVFHLCAFILQSSAAHSARPSSDSPHLPTEAHRVHSLS---
----------------------------------------PSGAIHAHPVPERYRARASR
RRPNLHHLS---------RGDVRWCWCETRLRPHFPSAMPPLLDGTQHELPDVPARYTSS
AG---------------------------------------ANN---ECTSRCFIWCRYA
PRRRSAAK-----RSGPQYAAATRRDCAHRSAS-------DGCTTGRHVSSAGEYAAANA
PFDGICRQGGFRSGASX-----------
>rsz14d10_3
------------------------------------------------------------
------------------------------------------RRYLRVYAARHAERFYRQ
AVMPASTPATNALRKYPAGSCSANNFRTIHGIRAGVLAYPMWCCDAWSPYRHWLAPA---
--------------------------------------TSAETLSSVWREASAGIGSRGR
CAISTNRIL-------HGSPRDAFTIGYRERCRQRKLPCSPAAALSTSSARVSGCFHTTR
SS---------------------------------------KRG----------DATTDP
GRAPACLY-----SLLLLLLLLSIRSRLRSMGR--------RRARTPRITLSSRSSALRI
SRR-RCRSAVSGVVWA------------
>sz98a18_3
------------------------------------------------------------
---------------------------------------------------------VGL
LGSGTETTXSCKRWRRAARSTGRLPTRYLQGTHVHLCTPQTTQGSR--------------
-------------------------------------------RAHTARLNCPSLWMRRR
QTPQPSDQR----------RHPQRQAVSNRLTAPSVLRCRWRILWSPCVGTCSAGRACTA
GW---------------------------------------RNT----------------
RRVRFAS------RWWIGNESFRFTDAGAHART-------SAMPRSSRRRSPGQMKRFHR
GLP-RGGSNLHPRLPTERFRR-------
>rsz9l20_2
------------------------------------------------------------
--------------------------SSRTCLRPIGRPVPLNSGMGAITVRLDTVILGRF
QRSDEHGTLRHTMNSSEAVEATVIQLCLSTTNWTRVLLTHPVQDADPTEDVSTGSTC---
----------------------------GALALIQAEHAAVSRLVSRSPCSGYRLEFGRY
HRPPLLICR-------SGARKPGFFARESICGVHSGHHLRPSLRDAITCDSLRGGYTGIH
FA---------------------------------------KQL----------------
----KCPF-----EKHAELSLPCWTLHQHINGFEDELHDEQKTSIISRIRPPPNMHETHT
SKP-LRWVIVAPIX--------------
>rsz42d03_3
------------------------------------------------------------
----------------------------------------PAXRLRCAQYVARPIGRRDR
YRGPQGNRCCMAIRALANTESSGAGNSTQIARSCRETTRTKHSVSGLFRTPTRPVGA---
-----------------------GSMWARALQKLLRHLNDNTGAPLPYMSSSLRSDFGTT
HPLELEFAA-----QGTALVRPVWAASSPISKVERSTEAERSRTLVHGACAWRITHFSSP
ES---------------------------------------KLAPRPHQDTAHSVRAFD-
-------------FLPAGRQRTVRTPLDRLLHGLARLVGSAKSYRLRQWPPGAPSKFDNQ
QTP-AHAQRSDPFGPCSPX---------
>rsz9l20_1
------------------------------------------------------------
----------------------------------------ILSYVFTSHWKTCSTQFWHG
CNHRQVRHCHIRAFSAIRRARNAAYNEFIRGCRGNVSHSTVPLDDKLDKSFADAPSP---
-----------------------------------------GCRSNRRRVHRQYMWGPGT
DPSRARSGV-------ATRFALALQWVQARIWAIPQTMTAVDLSFWSQEARFLRPRIDLW
CA---------------------------------------QRSPSEAEPARRHHLRFAS
RWIHWHTF-----CETAQVPIKARGAFASMLDAASTHQWVRGRAARAKDLEHHIEVNTPL
TAQ-YARDAHQQASSLGHSSAHT-----
>rsz12o01_2
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------RVRVALQHTDEFAMWSLDTWDTPXS---------
------------------------------------------------------------
-------------CSAHGQV---------------------QCPQLTVHTHGPESAHTAH
SGS-MCARVLSASMLCVER---------
>rsz12o01_3
------------------------------------------------------------
-------------------------------------------------------AFESL
YSIQTNSQCDGHSTHGTLRXVALRMVDKYSVHNCKQSIERMDQN----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------QHTRHIQVPCVLECYRLRCY---------------------------
----ASNX--------------------
>Mulan_NP_078820
MESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQELKGAKKVHLGEDLKSILSEAPG
KCVPYAVIEGAVRSVKETLNSQFVENCKGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQR
TNTVPFDLVPHEDGVDVAVRVLKPLDSVDLGLETVYEKFHPSIQSFTDVIGHYISGERPK
GIQETEEMLKVGATLTGVGELVLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLW
KVLALVFGF-------------ATCATLFFILRKQYLQRQERLRLKQMQEEFQEHEAQLL
SR---------------------------------------AKP------------EDRE
SLKSACVV-----CLSSFKS-CVFLECGHVCSC-------TECYRALPEPK---------
KCP-ICRQAITRVIPLYNS---------
>SPL2_NP_564653
-----------------------------MSSPERALLNLLTDIALSFDGAILGLTLAVS
AVGSALKYASTNAALKKIKDAPEVSISDLRSLLPASEDKSETNDNRKSNDQRIVVVRGVV
KPKISGDEGYKNNNVLISPETGDKALIIQRTQTYVYSGWKRLFQSTGHRFMLERSLR---
---KHGADFTRTVPFVIVGKDQQSNSSFVAVNMDGSRQPLPLTTVYNRLQPINSSFLQAF
LYPDYPVGLLDIEKILPPGKDITAVGIYSFNNGVPEIKSCQDLPYFLSEMTKDKMIEDLM
EQTNFIFLGSVILGIVSVGILSYAAVRTWNKWKQWNHQRELPQRPNDSVVDDEPEDADEI
PDGELCVI-----CVSRRRV-PAFIPCGHVVCC-------RRCASTVERELNP-------
KCP-VCLQSIRGSMRVYYS---------
>rsz31o21
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---DLCII-----CMTDPRD-TTVLPCGH-LCL---------CVDAQLLRVRSD------
RCP-ICRSPVD-----------------
>SP1
-------MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKIL
PFIVAVSGRVGSETPIKCEHS-----GIRGVIVEETAEQHFLKHNETGSWVQDSALMLSM
SKEVPWFLDDGTSRVHVMGARGATGFALTVGS-EVFEESGRSLVRGTLDYLQGLKML---
GVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLY
KYASMGFTV-----------LGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESE
GS---------------------------------------NGT----RESISDSTKKED
AVPDLCVI-----CLEQEYN-AVFVPCGHMCCC-------TACSSHLT------------
SCP-LCRRRIDLAVKTYRH---------
>SPL1_NP_564745
----------MIHLAGFTCCLGGVALYLLTRSTGRDIKSITRVYQLKDLEQLVEVESKVV
PLIIAVSGDVGSETPIKCEHS-----YVLGVFLKRTAEQQVLRRNWRFSWVRNSTLMQPM
TKEVPWYLDDGTGRVNVDVSQGELGLALTVGSDVFEKAEPVSLVQGALGYLKGFKIL---
GVRHVERVVPIGTPLTVVGEAVRDGMGNVRIQKPEQGPFYVTYIPLDQLISKLGDLSRRF
KYASMGLTV----LGVILISKPVIEYILKRIEDTLERRRRQFALKRVVDAAARRAKPVTG
GG---------------------------------------TSR--------------DG
DTPDLCVV-----CLDQKYN-TAFVECGHMCCC-------TPCSLQLR------------
TCP-LCRERIQQVLKIYRH---------
>rsz12o01
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CVL-----ILVHAFN---------------------GLFTIVDTVLVNHAQSNXS
ECP-MCRVTITLRIRLY-----------
>rsz42d03
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ADAAKRELE
QS----------------------------------------------------------
---TQCPV-----CFERLHAPSALVPCGHVLCK--------SCFVTLTTTLEEH------
LCP-TCRQVFD-----------------
>rsz42d03_1
------------------------------------------------------------
--------------------------RRQXVYAALNTLHGLLAEEIVIEARKATDAAWRY
ERLRIQKAAELEILRKLLDEADAAKRELEQSTQCPVCFERLHAPSALVPCGHVLCKS---
------------------------------------CFVTLTTTLEEHLCPTCRQVFDPI
SALRIHLNN-------SQPKGRHWYALSGPPHHQFPKSNVRQKPSDPEPYTERVHGASLI
FN---------------------------------------LVQNQNLPLDHTKTPEHNS
ILCVHSIF-----CLLEDNGLCALHDLIGYFTASLGWAVHENRIAYASGLQELHRNLITS
KRP-LTLSDLILLAHARP----------
