>SP1
MIPWGGVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKELAQLLELDSKILPFIVAVSGRVGSETPIKCEHSGIRGVIVEETAEQHFLKHNETGSWVQDSALMLSMSKEVPWFLDDGTSRVHVMGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYNAVFVPCGHMCCCTACSSHLTSCPLCRRRIDLAVKTYRH
>SPL1_NP_564745
mihlagftcclggvalylltrstgrdiksitrvyqlkdleqlveveskvvpliiavsgdvgsetpikcehsyvlgvflkrtaeqqvlrrnwrfswvrnstlmqpmtkevpwylddgtgrvnvdvsqgelglaltvgsdvfekaepvslvqgalgylkgfkilgvrhvervvpigtpltvvgeavrdgmgnvriqkpeqgpfyvtyipldqlisklgdlsrrfkyasmgltvlgviliskpvieyilkriedtlerrrrqfalkrvvdaaarrakpvtgggtsrdgdtpdlcvvcldqkyntafvecghmccctpcslqlrtcplcreriqqvlkiyrh
>SPL2_NP_564653
mssperallnlltdialsfdgailgltlavsavgsalkyastnaalkkikdapevsisdlrsllpasedksetndnrksndqrivvvrgvvkpkisgdegyknnnvlispetgdkaliiqrtqtyvysgwkrlfqstghrfmlerslrkhgadftrtvpfvivgkdqqsnssfvavnmdgsrqplplttvynrlqpinssflqaflypdypvglldiekilppgkditavgiysfnngvpeikscqdlpyflsemtkdkmiedlmeqtnfiflgsvilgivsvgilsyaavrtwnkwkqwnhqrelpqrpndsvvddepedadeipdgelcvicvsrrrvpafipcghvvccrrcastverelnpkcpvclqsirgsmrvyys
>Mulan_NP_078820
mesggrpslcqfillgttsvvtaalysvyrqkarvsqelkgakkvhlgedlksilseapgkcvpyaviegavrsvketlnsqfvenckgviqrltlqehkmvwnrtthlwndcskiihqrtntvpfdlvphedgvdvavrvlkpldsvdlgletvyekfhpsiqsftdvighyisgerpkgiqeteemlkvgatltgvgelvldnnsvrlqppkqgmqyylssqdfdsllqrqessvrlwkvlalvfgfatcatlffilrkqylqrqerlrlkqmqeefqeheaqllsrakpedreslksacvvclssfkscvflecghvcsctecyralpepkkcpicrqaitrviplyns

