>rsz9l20_1
ILSYVFTSHWKTCSTQFWHGCNHRQVRHCHIRAFSAIRRARNAAYNEFIRGCRGNVSHST
VPLDDKLDKSFADAPSPGCRSNRRRVHRQYMWGPGT------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------DPSRARSGVATRFALALQWVQ-------------ARIWAIPQTMTAVDL
SFWSQEARFLRPRIDLWCAQR----------SPSEAEPARRHHL----------------
----------RFASRWIHWHTF----------------------------CETAQVPIK-
----------------ARGAFASMLDAASTHQWVRGRAARAKDLEHHIEVNTPLTAQYAR
DAHQQASSLGHSSAHT--------------------------------------------
------------------------------------------------------------
---------------------
>rsz9l20_1
ILSYVFTSHWKTCSTQFWHGCNHRQVRHCHIRAFSAIRRARNAAYNEFIRGCRGNVSHST
VPLDDKLDKSFADAPSPGCRSNRRRVHRQYMWGPGT------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------DPSRARSGVATRFALALQWVQ-------------ARIWAIPQTMTAVDL
SFWSQEARFLRPRIDLWCAQR----------SPSEAEPARRHHL----------------
----------RFASRWIHWHTF----------------------------CETAQVPIK-
----------------ARGAFASMLDAASTHQWVRGRAARAKDLEHHIEVNTPLTAQYAR
DAHQQASSLGHSSAHT--------------------------------------------
------------------------------------------------------------
---------------------
>rsz14d10_2
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------IFKGVCGSSCRALLIQTGSHAGINAGDECSSLE
IPSWFLLCKQFDYTRHPLSRSPRLSHVVLRCM--------VALSPLVSASDERRDAFECM
ARGICRHLRLTRALLVSDKYK----------SYTTWFTTRRLHN----------------
----------RVQRALQ-------------------------------------------
-----------------------------TAQVAMFTSCCTFYLIRESLGLFPHHEKQQK
RRCNNGSW---------------------------------TCACLSLLVVVAAVAALHS
KSSKEHGTTGAHAPHHLIQPFERTAHLQETLSLCCFWCSMMGX-----------------
---------------------
>rsz14d10_2
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------IFKGVCGSSCRALLIQTGSHAGINAGDECSSLE
IPSWFLLCKQFDYTRHPLSRSPRLSHVVLRCM--------VALSPLVSASDERRDAFECM
ARGICRHLRLTRALLVSDKYK----------SYTTWFTTRRLHN----------------
----------RVQRALQ-------------------------------------------
-----------------------------TAQVAMFTSCCTFYLIRESLGLFPHHEKQQK
RRCNNGSW---------------------------------TCACLSLLVVVAAVAALHS
KSSKEHGTTGAHAPHHLIQPFERTAHLQETLSLCCFWCSMMGX-----------------
---------------------
>rsz12o01_3
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------FESLYSIQTNSQCDGHSTHG
TLRXVALRMVDKYSVHNCKQSIERMDQNQHTR----------------------------
-------------------------------HIQVPCVLECYRL----------------
----------RCYASNX-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz12o01_3
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------FESLYSIQTNSQCDGHSTHG
TLRXVALRMVDKYSVHNCKQSIERMDQNQHTR----------------------------
-------------------------------HIQVPCVLECYRL----------------
----------RCYASNX-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz9l20_3
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------LVRVYVPLEDLFHSILAWVQSPSG
TLSYGVFSDPTSTERLGIQIHPRLRQRKSFNCASRRQTGQEFCRTQSRMQIQQKTCPQAV
HVGPWHSKQSTQRCRDSFRARLAVGTGSNLGDTTDHDRCSVVLEPGSPVSSPENRSVVCT
AVTIGRACETPSPAIRFEVDT----------LAYILRNSSSAHL----------------
----------KSTRSFRFHAGR----------------------------CINTSMGSR-
----------------TSCTMSKRPRASYRGEYALDRPICTRRTPASLFAGSRPY-----
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz9l20_3
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------LVRVYVPLEDLFHSILAWVQSPSG
TLSYGVFSDPTSTERLGIQIHPRLRQRKSFNCASRRQTGQEFCRTQSRMQIQQKTCPQAV
HVGPWHSKQSTQRCRDSFRARLAVGTGSNLGDTTDHDRCSVVLEPGSPVSSPENRSVVCT
AVTIGRACETPSPAIRFEVDT----------LAYILRNSSSAHL----------------
----------KSTRSFRFHAGR----------------------------CINTSMGSR-
----------------TSCTMSKRPRASYRGEYALDRPICTRRTPASLFAGSRPY-----
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz7l15_3
RLNRLRVAQRRQLQASIAHVMLVVLVYQAPWRDLCQIHTSSLVPTSRKPRAYERPHTHPY
IHARKRGRSLRGANRTPGIR----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------ESLRRKRSVSHRRCRIFRHITGICDFDSRYSFECNPDRTCENSEAVPVS
PELCRRCSRACVAYLRSFRVA----------SRHRRSLQRCACV----------------
----------IVRARAPAATRV----------------------------VRYAFSLRL-
----------------QHAAPLFAVRSDHEAEPVLHGVLPAIGRTRQTAAGYTLPPRSFR
RRGGRCRL---------------------------------ACEQYAFRYSFSPTGSAAR
------------------------------------------------------------
---------------------
>rsz7l15_3
RLNRLRVAQRRQLQASIAHVMLVVLVYQAPWRDLCQIHTSSLVPTSRKPRAYERPHTHPY
IHARKRGRSLRGANRTPGIR----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------ESLRRKRSVSHRRCRIFRHITGICDFDSRYSFECNPDRTCENSEAVPVS
PELCRRCSRACVAYLRSFRVA----------SRHRRSLQRCACV----------------
----------IVRARAPAATRV----------------------------VRYAFSLRL-
----------------QHAAPLFAVRSDHEAEPVLHGVLPAIGRTRQTAAGYTLPPRSFR
RRGGRCRL---------------------------------ACEQYAFRYSFSPTGSAAR
------------------------------------------------------------
---------------------
>rsz14n09_2
V-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------RYPATTTIRASILRYESGFTNLQVLNDSHSFFSLAKQVSGCGHPGAVPAT
RARYRTYTCSAEQTHTDIAQRLRACASVDARRTSTHTHTHTAAKVASRAVCAEARAIDR-
-------------------------------CSSVSMDAQTLPF----------------
----------RNAYARILINNE----------------------------SRTAIGPVW-
----------------ASSSVHHRLLGLFHSHQTAPTGKTGYNEPSSKISRKEFELHSRS
CTHQNLRL---------------------------------------TRSASHENSPVAQ
LPRIDASMQETHASVQVVSVX---------------------------------------
---------------------
>rsz14n09_2
V-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------RYPATTTIRASILRYESGFTNLQVLNDSHSFFSLAKQVSGCGHPGAVPAT
RARYRTYTCSAEQTHTDIAQRLRACASVDARRTSTHTHTHTAAKVASRAVCAEARAIDR-
-------------------------------CSSVSMDAQTLPF----------------
----------RNAYARILINNE----------------------------SRTAIGPVW-
----------------ASSSVHHRLLGLFHSHQTAPTGKTGYNEPSSKISRKEFELHSRS
CTHQNLRL---------------------------------------TRSASHENSPVAQ
LPRIDASMQETHASVQVVSVX---------------------------------------
---------------------
>rsz14d10_3
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----RYLRVYAARHAERFYRQAVMPASTPATNALRKYPAGSCSANNFRTIHGIRAGVLAY
PMWCCDAWSPYRHWLAPATSAETLSSVWREASAGIGSRGRCAISTNRILHGSPRDAFTIG
YRERCRQRKLPCSPAAALSTSSARVSGCFHTT--------RSSKRGDATTDPGRAPACLY
SLLLLLLLLSIRSRLRSMGRR----------RARTPRITLSSRS----------------
----------SALRISR----------------------------------RRCRSAVS-
----------------GVVWA---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz14d10_3
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----RYLRVYAARHAERFYRQAVMPASTPATNALRKYPAGSCSANNFRTIHGIRAGVLAY
PMWCCDAWSPYRHWLAPATSAETLSSVWREASAGIGSRGRCAISTNRILHGSPRDAFTIG
YRERCRQRKLPCSPAAALSTSSARVSGCFHTT--------RSSKRGDATTDPGRAPACLY
SLLLLLLLLSIRSRLRSMGRR----------RARTPRITLSSRS----------------
----------SALRISR----------------------------------RRCRSAVS-
----------------GVVWA---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz42d03_2
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------GXTFTLRSIRCTAYWP
KRSLSRPARQQMLHGDTSACEYRKQRSWKFYANCLTKLMPRNVNSNKALSVRSVSNAYTP
RRRWFHVGTCSAKAASSPRQHLRSTSALHVVK--------SSIRFRHYASTTRIRSPRDG
IGTPCLGRLITNFQSRTFDRS----------RAIPNPSTRSVCM----------------
----------AHHSFLISRIKT----------------------------CPTTPRHLS-
--IIAFCACIRFSACWKTTDCAHSMTSVTSRPRSAGRQCMKIVSLTPVASRSSIEIPANA
RSRSAISFWPMLAX----------------------------------------------
------------------------------------------------------------
---------------------
>rsz42d03_2
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------GXTFTLRSIRCTAYWP
KRSLSRPARQQMLHGDTSACEYRKQRSWKFYANCLTKLMPRNVNSNKALSVRSVSNAYTP
RRRWFHVGTCSAKAASSPRQHLRSTSALHVVK--------SSIRFRHYASTTRIRSPRDG
IGTPCLGRLITNFQSRTFDRS----------RAIPNPSTRSVCM----------------
----------AHHSFLISRIKT----------------------------CPTTPRHLS-
--IIAFCACIRFSACWKTTDCAHSMTSVTSRPRSAGRQCMKIVSLTPVASRSSIEIPANA
RSRSAISFWPMLAX----------------------------------------------
------------------------------------------------------------
---------------------
>rsz7l15_2
S-----------------------------------------------------------
------------------------------------------------------------
-----------------------------FESFKGRAEEAAAGVNRSCDAGGAGVPGALA
RLVPNPHILARTYMISLKATCITPAHTSIHSCSQAWTLITWSKPYSWHSRVAQTKKIGFT
SSVPNFSPHNGHLRFRFAIFVMQSRQNMKQRSSVTC------------------------
------------------FSALQTVQSLRRIS--------SIISCCQSTSLALVAAL---
---------------RLRNSS----------SSCSSRDTRRSLR----------------
----------VFASSAARSASV----------------------------CCSIPRSAS-
----------------SPLRRLTCDWADSANCRWVYASAALFSAPRRAMSACLRTIRISL
LIFSNWLC---------------------------------SS-----------------
------------------------------------------------------------
---------------------
>rsz7l15_2
S-----------------------------------------------------------
------------------------------------------------------------
-----------------------------FESFKGRAEEAAAGVNRSCDAGGAGVPGALA
RLVPNPHILARTYMISLKATCITPAHTSIHSCSQAWTLITWSKPYSWHSRVAQTKKIGFT
SSVPNFSPHNGHLRFRFAIFVMQSRQNMKQRSSVTC------------------------
------------------FSALQTVQSLRRIS--------SIISCCQSTSLALVAAL---
---------------RLRNSS----------SSCSSRDTRRSLR----------------
----------VFASSAARSASV----------------------------CCSIPRSAS-
----------------SPLRRLTCDWADSANCRWVYASAALFSAPRRAMSACLRTIRISL
LIFSNWLC---------------------------------SS-----------------
------------------------------------------------------------
---------------------
>rsz73h07_1
HLGTTKVSGFFIMSYSPCFCSWLHTLRFSPMCIYSTV-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------FRCTFCETQQPAPSDRGSSS
SFAIAKWCDPCTPSSRTLQSK----------SPPATELASSVAR----------------
----------RCSVVLVLRNSS----------------------------AATFSICDA-
----------------SAPGWNAAAARRAGEIYVLCGRQQRVHVPLLHLVPLRTTTTERG
ETLRVASV---------------------------------RGRNEARLRPSKRQRRLHD
GSTRQQCRRVRSSECALRRHLPTGRLPIRSIS----------------------------
---------------------
>rsz73h07_1
HLGTTKVSGFFIMSYSPCFCSWLHTLRFSPMCIYSTV-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------FRCTFCETQQPAPSDRGSSS
SFAIAKWCDPCTPSSRTLQSK----------SPPATELASSVAR----------------
----------RCSVVLVLRNSS----------------------------AATFSICDA-
----------------SAPGWNAAAARRAGEIYVLCGRQQRVHVPLLHLVPLRTTTTERG
ETLRVASV---------------------------------RGRNEARLRPSKRQRRLHD
GSTRQQCRRVRSSECALRRHLPTGRLPIRSIS----------------------------
---------------------
>rsz14n09_3
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------DTQQRRRSVLPFCGTSRVLRTSRCTTVTRS------------------------
-----------FLWRSKSVDAVIRVLCLLRALAIAPIPAARSRHTQTLHSVYGHVRALTR
GSARAHTHTHTLLRRWHRGRS----------AQKQGQIGAPVYR----------------
----------WTHRLYP---------------------------------SEMPMRSVF-
----------------IMNREQQLAPFGPHRPFITDSSVFFIRTKLHQQEKLGITNQVRK
YLARSLSF---------------------------------TRAPVRIRIYDHAVLPMKT
AQWHDSYLESMQACKRLMHLSKSSAF----------------------------------
---------------------
>rsz14n09_3
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------DTQQRRRSVLPFCGTSRVLRTSRCTTVTRS------------------------
-----------FLWRSKSVDAVIRVLCLLRALAIAPIPAARSRHTQTLHSVYGHVRALTR
GSARAHTHTHTLLRRWHRGRS----------AQKQGQIGAPVYR----------------
----------WTHRLYP---------------------------------SEMPMRSVF-
----------------IMNREQQLAPFGPHRPFITDSSVFFIRTKLHQQEKLGITNQVRK
YLARSLSF---------------------------------TRAPVRIRIYDHAVLPMKT
AQWHDSYLESMQACKRLMHLSKSSAF----------------------------------
---------------------
>rsz73h07_2
TWXRQRSLAFLATLPVSAAGCIPCVFHLCA------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------FILQSSAAHSARPSSDSPHLP----------TEAHRVHSLSPSGAIHAH
PVPERYRARASRRRPNLHHLS----------RGDVRWCWCETRL----------------
----------RPHFPSAMPPLL----------------------------DGTQHELPD-
----------------VPARYTSSAGANNECTSRCFIWCRYAPRRRSAAKRSGPQYAAAT
RRDCAHRS---------------------------------ASDGCTTGRHVSSAGEYAA
ANAPFDGICRQGGFRSGASX----------------------------------------
---------------------
>rsz73h07_2
TWXRQRSLAFLATLPVSAAGCIPCVFHLCA------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------FILQSSAAHSARPSSDSPHLP----------TEAHRVHSLSPSGAIHAH
PVPERYRARASRRRPNLHHLS----------RGDVRWCWCETRL----------------
----------RPHFPSAMPPLL----------------------------DGTQHELPD-
----------------VPARYTSSAGANNECTSRCFIWCRYAPRRRSAAKRSGPQYAAAT
RRDCAHRS---------------------------------ASDGCTTGRHVSSAGEYAA
ANAPFDGICRQGGFRSGASX----------------------------------------
---------------------
>rsz31o21_1
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
RXCKSESTGERQMGQRSLRTRNNCAQSTQRHR--WPHGSTVVSRGSVMQMIQRSSCSASA
AALGEIFGALKALQQNHNRVSMLGEFGRVLFEKKRLAISTGHET----------------
----------AVAILAVPLAHTGLEWGRYWGHRLQRLDMELLSARCAVREXPSPRRLCR-
----------------GPSTFAXKNKLQXKLLWIFGISNKAYTLLPNIQVVLYGVRVNHG
RNRLCGTLRTTLQ-----------------------------------------------
------------------------------------------------------------
---------------------
>rsz31o21_1
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
RXCKSESTGERQMGQRSLRTRNNCAQSTQRHR--WPHGSTVVSRGSVMQMIQRSSCSASA
AALGEIFGALKALQQNHNRVSMLGEFGRVLFEKKRLAISTGHET----------------
----------AVAILAVPLAHTGLEWGRYWGHRLQRLDMELLSARCAVREXPSPRRLCR-
----------------GPSTFAXKNKLQXKLLWIFGISNKAYTLLPNIQVVLYGVRVNHG
RNRLCGTLRTTLQ-----------------------------------------------
------------------------------------------------------------
---------------------
>sz98a18_1
LLAYWXAAPKRRXVVSDG------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GERPGQPVAYRRGTFDRGHTCTCALPRRHRVRGERTRHVTVQ
VSGCGGDRRRSQATSGGILSSVKQATVLLHLF----------------------------
-------------------------------GAAGGSCGHHVWA----------------
----------LVLLVVP-------------------------------------------
--------------------------------APLDGATRDVSGLQVAGGSGTSHSALRT
RAHTRGRQ---------------------------------RCPEAADEGRQAKSDSTAA
CREAGRTSTPDCQRSASAA-----------------------------------------
---------------------
>sz98a18_1
LLAYWXAAPKRRXVVSDG------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GERPGQPVAYRRGTFDRGHTCTCALPRRHRVRGERTRHVTVQ
VSGCGGDRRRSQATSGGILSSVKQATVLLHLF----------------------------
-------------------------------GAAGGSCGHHVWA----------------
----------LVLLVVP-------------------------------------------
--------------------------------APLDGATRDVSGLQVAGGSGTSHSALRT
RAHTRGRQ---------------------------------RCPEAADEGRQAKSDSTAA
CREAGRTSTPDCQRSASAA-----------------------------------------
---------------------
>rsz31o21_3
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------NXQKIYRTTDGATIATHAQQLCSVYTETQV------------------------
-----------ATRQHRGIPRVRHANDTEIIVFCFSGCSWRDLRRSQGAAAESQSGIDAW
RVWPGSVRKETTRDIDWARNR----------GGYSGGTAGPYRP----------------
----------RMGVLGA-------------------------------------------
----------------------------------------------------------PA
PAARHGTA---------------------------------QRALCGSGXFAMKKTVQRP
EHVCXQKQTPTXTAVDFRDLQGVHSSSEHSSRSLWCTREPWSEPAVWNAPHHPAX-----
---------------------
>rsz31o21_3
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------NXQKIYRTTDGATIATHAQQLCSVYTETQV------------------------
-----------ATRQHRGIPRVRHANDTEIIVFCFSGCSWRDLRRSQGAAAESQSGIDAW
RVWPGSVRKETTRDIDWARNR----------GGYSGGTAGPYRP----------------
----------RMGVLGA-------------------------------------------
----------------------------------------------------------PA
PAARHGTA---------------------------------QRALCGSGXFAMKKTVQRP
EHVCXQKQTPTXTAVDFRDLQGVHSSSEHSSRSLWCTREPWSEPAVWNAPHHPAX-----
---------------------
>rsz14n09_1
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------SIPSNDDDPCFHSAVRVGFYEPPGAERQSLVLFFGEASQWMRSSGCCACYARSL
SHLYLQRGADTHRHCTAFTGMCERREVAHEHTHTHT------------------------
-----------HCCEGGIEGGLRRSKGNRSVL--------QCIDGRTDFTLPKCLCV---
--------------------------------AYSNKIANSNWP----------------
----------RLGLIVR----S----------------------------SPTPRSFSF-
----------------APNCTNRKNWVRTKFENISQGVA-------------------SL
ALLYASES---------------------------------TTDTQCFPKQPSGMTATSN
RCKHARDSCICPSRQRX-------------------------------------------
---------------------
>rsz14n09_1
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------SIPSNDDDPCFHSAVRVGFYEPPGAERQSLVLFFGEASQWMRSSGCCACYARSL
SHLYLQRGADTHRHCTAFTGMCERREVAHEHTHTHT------------------------
-----------HCCEGGIEGGLRRSKGNRSVL--------QCIDGRTDFTLPKCLCV---
--------------------------------AYSNKIANSNWP----------------
----------RLGLIVR----S----------------------------SPTPRSFSF-
----------------APNCTNRKNWVRTKFENISQGVA-------------------SL
ALLYASES---------------------------------TTDTQCFPKQPSGMTATSN
RCKHARDSCICPSRQRX-------------------------------------------
---------------------
>rsz42d03_3
PAXRLRCAQYVARPIG--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------RRDRYRGPQGNRCCMAIRALA------------------NTESSGAGNS
TQIARSCRETTRTKHSVSGLF----------RTPTRPVGAGSMW----------------
----------ARALQKLLRHLN----------------------------DNTGAPLPY-
----------------MSSSLRSDFGTTHPLELEFAAQGTALVRPVWAASSPISKVERST
EAERSRTL---------------------------------VHGACAWRITHFSSPESKL
APRPHQDTAHSVRAFDFLPAGRQRTVRTPLDRLLHGLARLVGSAKSYRLRQWPPGAPSKF
DNQQTPAHAQRSDPFGPCSPX
>rsz42d03_3
PAXRLRCAQYVARPIG--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------RRDRYRGPQGNRCCMAIRALA------------------NTESSGAGNS
TQIARSCRETTRTKHSVSGLF----------RTPTRPVGAGSMW----------------
----------ARALQKLLRHLN----------------------------DNTGAPLPY-
----------------MSSSLRSDFGTTHPLELEFAAQGTALVRPVWAASSPISKVERST
EAERSRTL---------------------------------VHGACAWRITHFSSPESKL
APRPHQDTAHSVRAFDFLPAGRQRTVRTPLDRLLHGLARLVGSAKSYRLRQWPPGAPSKF
DNQQTPAHAQRSDPFGPCSPX
>rsz14d10_1
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------VDIGCMR
LVMQSAFDTDRQSCRHQRRRRMLFARNTQLVP-----ALQTILGLYTASAEQESSPIPCG
VAMHGRLIATGRQRRAQRRFRVYGERHLPAFKAHAGAVSERVQI----------------
----------VYYMVHHETPSQ----------------------------SGTESAADS-
----------------ASCHVHQLLHFLPH-----PRESRAVSTPREAAKEAMQQRILDV
RLLVSTRC-----------------------CCCCCCSPFEVVGAWVDDGRARPASPYPA
VRAHCASPGDVVALLFLVYDGP--------------------------------------
---------------------
>rsz14d10_1
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------VDIGCMR
LVMQSAFDTDRQSCRHQRRRRMLFARNTQLVP-----ALQTILGLYTASAEQESSPIPCG
VAMHGRLIATGRQRRAQRRFRVYGERHLPAFKAHAGAVSERVQI----------------
----------VYYMVHHETPSQ----------------------------SGTESAADS-
----------------ASCHVHQLLHFLPH-----PRESRAVSTPREAAKEAMQQRILDV
RLLVSTRC-----------------------CCCCCCSPFEVVGAWVDDGRARPASPYPA
VRAHCASPGDVVALLFLVYDGP--------------------------------------
---------------------
>sz98a18_3
V-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GLLGSG
TETTXSCKRWRRAARSTGRLPTRYLQGTHVHL--------CTPQTTQGSRRAHTARLNCP
SLWMRRRQTPQPSDQRRHPQR----------QAVSNRLTAPSVL----------------
----------RCRWRILWSPCV----------------------------GTCSAGRAC-
----------------TAGWRNTRRVRFASRWWIGNESFRFTDAGAHARTSAMPRSSRRR
SPGQMKRF---------------------------------HRGLPRGGSNLHPRLPTER
FRR---------------------------------------------------------
---------------------
>sz98a18_3
V-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GLLGSG
TETTXSCKRWRRAARSTGRLPTRYLQGTHVHL--------CTPQTTQGSRRAHTARLNCP
SLWMRRRQTPQPSDQRRHPQR----------QAVSNRLTAPSVL----------------
----------RCRWRILWSPCV----------------------------GTCSAGRAC-
----------------TAGWRNTRRVRFASRWWIGNESFRFTDAGAHARTSAMPRSSRRR
SPGQMKRF---------------------------------HRGLPRGGSNLHPRLPTER
FRR---------------------------------------------------------
---------------------
>sz98a18_2
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------WPTGXRHRNDVXLAMAESGQVNRSPTDAVPLTGDTRAPVHSPDDTGFEASA
HGTSELSKSLDAEATDAAAKR----------PAAASSVASSSEQPFDCSICFEVPLEDPV
VTMCGHLFCWSCLHRWMAQHAT----------------------------CPVCKSLVDR
ERVIPLYGRGRTREDVSDAPKQQTKVARPNEAIPPRPAARRVEPPPQTANGALPPX----
------------------------------------------------------------
------------------------------------------------------------
---------------------
>sz98a18_2
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------WPTGXRHRNDVXLAMAESGQVNRSPTDAVPLTGDTRAPVHSPDDTGFEASA
HGTSELSKSLDAEATDAAAKR----------PAAASSVASSSEQPFDCSICFEVPLEDPV
VTMCGHLFCWSCLHRWMAQHAT----------------------------CPVCKSLVDR
ERVIPLYGRGRTREDVSDAPKQQTKVARPNEAIPPRPAARRVEPPPQTANGALPPX----
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz73h07_3
PGXDKGLWLFYNELLSLFLQLAAYLAFFTYVHLFYSLPLHILRDL---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------AVTARTFRQRLIEFIRYRQVV--------RSMHTQFPNATEQELAAGDR
TCIICREEMFGGA------------------GAKKLVCGHIFHL----------------
----------RCLRSWMERSMS----------------------------CPTCRRDIRP
LR--------------APTTSARPAASSGAATHHDDGARRNAPGSLSTRPQRGATAPIEA
PATAARRV---------------------------------DTSAVPASTQQRMRPSTAS
ADREASDPEHL-------------------------------------------------
---------------------
>rsz73h07_3
PGXDKGLWLFYNELLSLFLQLAAYLAFFTYVHLFYSLPLHILRDL---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------AVTARTFRQRLIEFIRYRQVV--------RSMHTQFPNATEQELAAGDR
TCIICREEMFGGA------------------GAKKLVCGHIFHL----------------
----------RCLRSWMERSMS----------------------------CPTCRRDIRP
LR--------------APTTSARPAASSGAATHHDDGARRNAPGSLSTRPQRGATAPIEA
PATAARRV---------------------------------DTSAVPASTQQRMRPSTAS
ADREASDPEHL-------------------------------------------------
---------------------
>rsz42d03_1
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------RQXVYAALNTLHGLLA
EEIVIEARKATDAAWRYERLRIQKAAELEILR----------------KLLDEADAAKRE
LEQSTQCPVCFERLHAPSALV----------PCGHVLCKSCFVT----------------
----------LTTTLEEHLCPT----------------------------CRQVFDPIS-
----------------ALRIHLNNSQPKGRHWYALSGPPHHQFPKSNVRQKPSDPEPYTE
RVHGASLIFNLVQNQNLPLDHTKTPEHNSILCVHSIFCLLEDNGLCALHDLIGYFTASLG
WAVHENRIAYASGLQELHRNLITSKRPLTLSDLILLAHARP-------------------
---------------------
>rsz42d03_1
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------RQXVYAALNTLHGLLA
EEIVIEARKATDAAWRYERLRIQKAAELEILR----------------KLLDEADAAKRE
LEQSTQCPVCFERLHAPSALV----------PCGHVLCKSCFVT----------------
----------LTTTLEEHLCPT----------------------------CRQVFDPIS-
----------------ALRIHLNNSQPKGRHWYALSGPPHHQFPKSNVRQKPSDPEPYTE
RVHGASLIFNLVQNQNLPLDHTKTPEHNSILCVHSIFCLLEDNGLCALHDLIGYFTASLG
WAVHENRIAYASGLQELHRNLITSKRPLTLSDLILLAHARP-------------------
---------------------
>SP1
M-----------IPWG--------GVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKE
LAQLL-ELDSKIL---------PFIVAVSGRVGS--ETPIKCEHSGIRGVIVEETAEQHF
LKHNETGS-WVQDSALMLSM-----------------SKEVPWFL---DDGTS-R-VHVM
GARGATGFALTVGSEVFEESGR-SLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEA
VKDDIGEFRIQKPDRGPFYVSSKSLDQLISNLGKWSRLYKYASMGFTVLGVFLITKHVID
SVLER------RRRRQLQ-KRVLDAAAKR-AE--------LESEGSNGTRESISDSTKKE
DAVPDLCVICLEQEYNAVFVP----------CGHMCCCTACSSH----------------
----------L-----T----S----------------------------CPLCRRRID-
----------------LAVKTYRH------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>SPL1_NP_564745
M-----------IHLA--------GFTCCLGGVALYLLTRSTGRD---IKSITRVYQLKD
LEQLV-EVESKVV---------PLIIAVSGDVGS--ETPIKCEHSYVLGVFLKRTAEQQV
LRRNWRFS-WVRNSTLMQPM-----------------TKEVPWYL---DDGTG-R-VNVD
VSQGELGLALTVGSDVFEKAEPVSLVQGALGYLKGFKILGVRHVERVVPIGTPLTVVGEA
VRDGMGNVRIQKPEQGPFYVTYIPLDQLISKLGDLSRRFKYASMGLTVLGVILISKPVIE
YILKRIEDTLERRRRQFALKRVVDAAARR-AK--------PVTGG----------GTSRD
GDTPDLCVVCLDQKYNTAFVE----------CGHMCCCTPCSLQ----------------
----------L-----R----T----------------------------CPLCRERIQ-
----------------QVLKIYRH------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Mulan_NP_078820
M----------ESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQELKGAKKVHLGED
LKSILSEAPGKCV----------PYAVIEGAVRSVKETLNSQFVENCKGVIQRLTLQEHK
MVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDVAVRVLKPLDSVDLGLETVYEKFH
PSIQ-------------------SFTDVIGHYISGERPKGIQETEEMLKVGATLTGVGEL
VLDNNSVRLQPPKQGMQYYLSSQDFDSLLQRQESSVRLWKVLALVFGFATCATLFFILRK
QYLQRQERLRLKQMQEEFQEHEAQLLSRAKPE--------------------------DR
ESLKSACVVCLSSFKSCVFLE----------CGHVCSCTECYRA----------------
----------------LPEPKK----------------------------CPICRQAIT-
----------------RVIPLYNS------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>SPL2_NP_564653
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSISDL
RSLLPASEDKSETNDNRKSNDQRIVVVRGVVKPKISGDEGYKNNNV---LISPETGDKAL
IIQRTQTYVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVIVGKDQQSNSSFVAVN
MDGSRQPLPLTTVYNRLQPINS----SFLQAFLYPDYPVGLLDIEKILPPGKDITAVGIY
SFN-NGVPEIKSCQDLPYFLSEMTKDKMIEDLMEQTNFIFLGSVILGIVSVGILSYAAVR
TWNKWKQWNHQRELPQR----------------------------PNDSVVDDEPEDADE
IPDGELCVICVSRRRVPAFIP----------CGHVVCCRRCAST----------------
----------VERELNP----K----------------------------CPVCLQSIR-
----------------GSMRVYYS------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz9l20_2
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------SRTCLRPIGRPVPLNSGMGAITVR
LDTVILGRFQRSDEHGTLRHTMNSSEAVEATVIQLCLSTTNWTRVLLTHPVQDA------
-------------------------------DPTEDVSTGSTCG----------------
----------ALALIQAEHAAV----------------------------SRLVSRSPC-
----------------SGYRLEFGRYHRPPLLICRSGARKPGFFARESICGVHSGHHLRP
SLRDAITC---------------------------------DSLRGGYTGIHFAKQLKCP
FEKHAELSLPCWTLHQHINGFEDELHDEQKTSIISRIRPPPNMHETHTSKPLRWVIVAPI
X--------------------
>rsz9l20_2
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------SRTCLRPIGRPVPLNSGMGAITVR
LDTVILGRFQRSDEHGTLRHTMNSSEAVEATVIQLCLSTTNWTRVLLTHPVQDA------
-------------------------------DPTEDVSTGSTCG----------------
----------ALALIQAEHAAV----------------------------SRLVSRSPC-
----------------SGYRLEFGRYHRPPLLICRSGARKPGFFARESICGVHSGHHLRP
SLRDAITC---------------------------------DSLRGGYTGIHFAKQLKCP
FEKHAELSLPCWTLHQHINGFEDELHDEQKTSIISRIRPPPNMHETHTSKPLRWVIVAPI
X--------------------
>rsz12o01_1
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------RSSRFTAYRRIRNVMVTRHMG----------------------------
------------------------------------------------------------
------------HSEXLLCAWL----------------------------TSTVSTIVN-
----------------SPLNAWTRISTHGTFRFHVCSSVIGFDAMRRT------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz12o01_1
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------RSSRFTAYRRIRNVMVTRHMG----------------------------
------------------------------------------------------------
------------HSEXLLCAWL----------------------------TSTVSTIVN-
----------------SPLNAWTRISTHGTFRFHVCSSVIGFDAMRRT------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz31o21_2
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------EXAKVNLQVNDRWGNDRYARATTVLSLHRDTGGHTAAPWYPAGPSCKY
RDHRVLLQRLLLARSSALSRRCSRITIGYRCL----------------------------
-------------------------------ASLAGFCSKRNDS----------------
----------RYRLGTKPRWLF----------------------------WRYRWPIPA-
----------------SNGVGTGGTGSSGSTWNCSARVVRFVRXLRHEEDCAEARARLRX
KTNSNXNC---------------------------------CGFSGSLTRRTLFFRTFKS
FFMVYATMVGTGCVERSAPPCX--------------------------------------
---------------------
>rsz31o21_2
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------EXAKVNLQVNDRWGNDRYARATTVLSLHRDTGGHTAAPWYPAGPSCKY
RDHRVLLQRLLLARSSALSRRCSRITIGYRCL----------------------------
-------------------------------ASLAGFCSKRNDS----------------
----------RYRLGTKPRWLF----------------------------WRYRWPIPA-
----------------SNGVGTGGTGSSGSTWNCSARVVRFVRXLRHEEDCAEARARLRX
KTNSNXNC---------------------------------CGFSGSLTRRTLFFRTFKS
FFMVYATMVGTGCVERSAPPCX--------------------------------------
---------------------
>rsz12o01_2
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------VRVALQHTDE--------FAMWSLDTWDTPXSCSAHGQ
VQCPQLTVHTHGPESAHTAHS----------GSMCARVLSASML----------------
----------CVER----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz12o01_2
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------VRVALQHTDE--------FAMWSLDTWDTPXSCSAHGQ
VQCPQLTVHTHGPESAHTAHS----------GSMCARVLSASML----------------
----------CVER----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz7l15_1
I-----------------------------------------------------------
------------------------------------------------------------
------------------------VIVGSRRGGSCRRQSLMCWWCWCTRRPGETCAKSTH
PRSYLHDLVKSHVHMNARTHIHTFMLASVDAHYVEQTVLLAFASRSDEKDRFHIVGAEFF
ATRAFAISIRDIRLNAIPTEHVKTAKQCNLFLLSFADGAVELASHIFDHFVLPVDIASAR
CSVALAFELVLQPRHASFATRFRFVCSTQRLC--------LLFDLTTKLSQFSTEASYLR
LGGLGKLPLGIRFRRALFGAE----------AGDVGLLANNTHF----------------
----------ATHFLQLALQLX--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>rsz7l15_1
I-----------------------------------------------------------
------------------------------------------------------------
------------------------VIVGSRRGGSCRRQSLMCWWCWCTRRPGETCAKSTH
PRSYLHDLVKSHVHMNARTHIHTFMLASVDAHYVEQTVLLAFASRSDEKDRFHIVGAEFF
ATRAFAISIRDIRLNAIPTEHVKTAKQCNLFLLSFADGAVELASHIFDHFVLPVDIASAR
CSVALAFELVLQPRHASFATRFRFVCSTQRLC--------LLFDLTTKLSQFSTEASYLR
LGGLGKLPLGIRFRRALFGAE----------AGDVGLLANNTHF----------------
----------ATHFLQLALQLX--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
