>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|3610  641252794 AM1_3710 hypothetical protein [Acaryochloris marina MBIC11017]

M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------KIIGIILIVI
GII--LFFVYSNLKRKLASLRQA-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------RPASIAELNHLASE---------------------
-IALEMGSGSWRDYVKLR------------------------------------------
--------------------------------GTIQCDQPLISELKQMP-----------
-----------------------------------------CVHYNMTVVREYEEQVTER
DSDDKVVTKTQ-------------------------------------------------
--------------------------------RGSETLSQNRESV---PFFLQDDTGEIW
VEPEGAQIETVRVLDEFSPEQPSGG-QLSFGGFSLSLSSAETGRQT-IGYRYQESVLPVQ
RQVFVVAQVSDFNQSLVLENPTTKGQ-----RFVISLKSEEALAQTTQTSVTYAFYGMIS
TLVVGGL-----------------LVIFGL------------------------------
------------------------------------------------------------
-----------LSA
>Anabaena_sp_PCC_7120_gnl|BL_ORD_ID|1046  all1047 ABC transporter, permease protein NatC

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------IEYLIFLA
I-------------------------------STATFALFSLGLNLQWGFTG------LI
NFGHIAFMTLGAY--------------------------TTVLLSL--------------
-----------------KGVPLFISAIVGAI-----------------------------
----------------------FAALLGLVIGFATLRL----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----REDYLAIVTIGTGELIRLVVNNQDLPVGDTWVSGAFGVQSYPIPLSTEPNLFFRL
LMIGILTLLFAVTVFSLWRWIRNAQKLQLTDATDKTSSKQEIASRFGVGIILGLLATAIY
I----SGVIT----LYNYIPKAGLMLVSLLVLAFVFWRL--EYLVRSPW-GRVLKAIRED
EE----------------------------------------------------------
---------------------IPKAMG--------------------------------K
N--VFWYKLQ--------------------------------------------------
-------------------------------SLMLG---------GAIAGIAGAFFAWQI
SAIYPD-----------NFQ-P--------------------------------------
------------------------------------------------------------
--------------------------QLTFDSW---------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------IMVILGGAGNNIGSIL------------GAVIYFAYDAI
TREVL-------------------------------------------------------
---------PKIIPL---------------------DEARLGAFR--------IMCIGLI
LMVLM---IWRPQGILGKKEELTLG-----------K
>Anabaena_variabilis_ATCC_29413_gnl|BL_ORD_ID|3683  gi|75909288|ref|YP_323584.1| unnamed protein product [Anabaena variabilis ATCC 29413]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MSVPNI------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TREILADDP
FPRFDEWLDQVEQVLEQNTALLML---------------------------------DEF
EALDSAINRGRFDE--EDVLGMLRHLIQHRP-----------------------------
------------------------------------------------------------
---------------RFKMLLAGSHTIEEYQRWASYLIN---------------------
---------VQVVHISYLKEEEARQLIEHPVKY---------------------------
--FTLRYEPEAV-ERVLQLTRCHPFLIQLLC-G-EIIV-LKNEQDPSI------RRLTSL
EDVEAAIPEAL-------QSGGFFF-----------------------------ADIQNN
QVDA--------------------------------------NGREV-------------
--------LRLIAAQGEGE-IVSKFTLSEQFPDVWERTIALLL----------QQE--LI
EEVA--------------------------------------------------------
---------------------------------------DSYRFQVELIRRCFV-
>Arthrospira_platensis_NIES_39_gnl|BL_ORD_ID|5027  650388367 NIES39_M00310 translation initiation factor IF-3 [Arthrospira platensis NIES-39]

------------------------------------------------------------
---------MPVI---------------ESKRNRNLPQINDNIRFPKIRLIDTE------
--------------------------GGQLGIMTPREAMKLAQEKELDLVLVSDKADP--
-------PV------CRIMDYGKFKYEQE-----------KK--------VREARKKQHT
ADVKEVKMRYKI------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------DDHDYQ----------------------
----VRVNQAKRFLKSGDK-----------------------------------------
-----------------------VKATIMFRGREIQHS-----NLARELLKRMAEDLEEH
A-----------------------------------------------------------
------------------------------------------------------------
-------------EVQQSPKQE-----GRSMMML--------------------------
------------------------------------------------------------
---------------------------------------LAPKKTT--------------
--------T---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------S
>Arthrospira_platensis_Paraca_gnl|BL_ORD_ID|3312  646131044 AplaP_010100016907 translation initiation factor IF-3 [Arthrospira platensis Paraca]

MP----------------------------------------------------------
---------------------VIESKRNRNLPQINDN-----------------------
----------------IRFPK---IRLIDT-------EGGQLGIM-TPREAMKLAQEKEL
DLVLVSDKADPPV---------------------CRIMDYGKFKYEQE-----------K
KVREARKKQHTADVKEVKMRYKID----DHDYQVRVN-----QAKRFLKSGDKVKATIMF
RGREIQHS-----NLARELLKRMAEDLEEHAEVQQS-----PKQE-----GRSMMML---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------LAPKKTTTS
>Arthrospira_sp_PCC_8005_gnl|BL_ORD_ID|1245  648386468 APCC8_010100006537 translation initiation factor IF-3 [Arthrospira sp. PCC 8005]

MP----VI---------------ES-----------------------------KRNRNL
------PQINDN--------------------------IRFPKIRLIDTE----------
----------------GG------------------------------------------
-----------QLGIMTPREAMKLAQEK---------------------ELDLVLVSDKA
DPPVCRIMDYGKFKYEQE---------------------------KKVREARKKQHTADV
KEVKMRYKIDDHDYQVRVNQAKR----------------------------FLK----SG
DKVKATIMFRGREIQHSNLARELLKRMAVDLEEHAEVQQSPKQEGRSMM-------MLLA
PKKTTS------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>gnl|BL_ORD_ID|17261 Arabidopsis_thaliana AT1G63900.1|PACid:19655208
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------IPWGGVTCCLS
AAALYLLGRSSGRDAEVLETVTR--VNQLKELAQLL--ELDSKILPFIVAVSGRVGS-ET
PIKCEHSGIRGVIVEETA----EQHFLKHNETGS----WVQDSALMLSMSKEVPWFLDDG
TSRVHVMGARGATGFAL-TVGSEVFEESGR-SLVRGTLDY------LQGLKM----LGVK
RIERVLPTGIPLTIVGEAVKDDIGEFRIQKP-DRGPFYVSSKSLDQLISNLGKWS-RLYK
YASMGFTVLGVFLITKHVIDSVLER------RRRRQLQK----RVLDAAAKRAELESEGS
NGTRESISDSTKKEDAVPDLCVICLEQEYNA---VFVPCGHMC---CCTACSSHLTSCPL
CR----RRIDLA-VKTYRH
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----ILIGIICLIVGVILL----------------------------FFWRSNRSKLRNL
------------------------------------------------------------
----------------------------------RLASASTISSLQ-----TIANQIAEE
IGGGSLREY---------VKIRGVIECDRPLISQ--------------------------
-LKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFT----LQDS
TGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEE----RRQTIGYRYQ
EEILPIGR---QILVIGTATDEEGMITIRKPTEKGQRYF--------ISLKSEEELSQAT
NNAIRGTFYSMIFFLTLGLILLVAGVLR--------------------------------
G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIG-----------------------------------------IICLIVGVILLFFW
RSN----RSKLRNLRLASASTISSLQTIANQIAEEIGGGSLRE-----------------
-----------------------YVKIRGVIECDRPLIS---------------------
------------------------------------------------------------
----------------------QLKQEPCVYYSMTVTW----------------------
------------------------EYNEEVIKQDNEG--KTIREKERK------------
----------------------------------------SETVAQNSRSIPF-------
--------TLQDSTGEI------------RVNP-----------ERAEIETVKVLEEFRP
ENFSGGSLTFGNFSI-NLPSFEERRQTIGYRYQEEILPIG-------------RQILVIG
TATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAI-------------------RG
TFY---------------SMIFFLTLGLILL------------VAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWE-YN-----EEVIKQDNEGKTIREKERKSE
TVAQN---SRSIPFTLQDSTGEI-----------RVNPERAEIETVKVLEEFRPENFSGG
SLTFG--NFSINLPSFEERRQTIGY----RYQEEILPIGRQIL------VIGTATDEEGM
IT--IRKPTEKGQRYFISLKSEEELSQATNNAI---------------------------
------RGTFYSMIFFLTLGLILLVAGV--------------------------------
-------LRG--------------------------------------------------
---------------------------
>Cyanothece_PCC_7425_gnl|BL_ORD_ID|1048  gi|220906503|ref|YP_002481814.1| unnamed protein product [Cyanothece sp. PCC 7425]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------GLAIVGAILLV-----------------------
-----------------------------------------------------TGGILYF
VQRHYQQKLYSIKL----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------ARKT-----------TVAELKQLADQVGAEIGQGSLREYVKLSGQI
KCDTPLISELKQVPCVYYQMQVEREYEERLTE----------RDNDGETREKTQRGSETI
ASNSQSTPF---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
FLQ---------------------------------------------------------
-DQSGAIEVDP-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------SGAAIETVQVLNEFRPEAGS-ARISF----------------------------
------------------------------------------------------------
------GNFSLSV--GGSFPAGRETI-----G---------YRYRESILPPDR-------
RILIVATASDSSGILSLQKPVEKRQK----------FIISLK--SEDHLA----------
-----QSTQQTATYTFYGMIACLGLG------------------AILLVVGLIIR-----
--------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGV------------------------ILLFF------------------
----------------------------------------WRSNRSKLRNLRLASAS---
TISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEE
VIK---------------------------------------------------------
------------------------------------------------------------
---------QDNEGKTIREKERKSETVAQNSR----------------------------
------------SIPFTLQDSTGEI---------------RVNP----ERAE--------
IETVKVLEEFRPENF------------SGGSLTFG----------------------NFS
INLPSFEERR---------------------------------------QTIGYRYQEEI
LP----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
IGRQILVI------------------------------GTATDEEGMITIRK--------
------------------------------------------------------------
PTEKGQRYFIS------------------------------LKSEEELSQATNNAIR---
-----------------------------------GTFYSMI------------------
------------------------------------------------FFLTLGLI----
---------------------------------------LLVAGVLRG------------
---------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------ILIGI------ICLIVGVILLFFWRS--------------
-----------------------------------------------------NRSKLRN
LRLAS-ASTISSLQTIANQIAEEIGGGSLREYVKIRGV-----------IE---------
-CDRPLISQLKQEPCVYYSMTV--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---TWEYNEEVIKQDNEGKTIREKERKSETVAQNSR---SIPF----TLQDSTGEIRVNP
ERAE---------------------------------------IETVKVLEEFR------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------PENFSGGSLTFGNFSINL--------------------------
------------------------------------------------------------
-------PSFEERRQ--------------TIGYRYQEEILPIGRQILVIGTATDEEGMIT
IRKPTEKGQRYF----------------------------ISLK----------------
--------------------------------------------------SEEE------
-----------LSQATN-NAI-RGTFYSMI------------------------------
--------------FFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M---------------------------------------ILIGI---------------
------------------------------------------------------------
--------------------------------ICLIVGVILLFFWRSN------------
RSKLRNLRLASAS-----------------------------------------------
T----ISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWE
YNEEVIKQD-NEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVN-------------
-----PERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSF------------------
------EERRQTIGYRYQEE----------------ILPIGRQILVIGTAT---------
-----DEEGMITIRKP------------TEKGQRY-----------FISLKSEEELSQAT
-NNAIRGTFYSM-------------IF-------------------------FLTLGLIL
LVAGVLRG----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------LIGIICLIVGVI------------------------------------
------------------------------------------------------------
-------LLFFWRSNR----SKLRNLRLASASTISSLQTIAN----QIAEEIGGGSLREY
--------VKIRGVIECDRPLISQLKQE---PCVYYSMTVTWEYNEEVIKQ------DNE
GKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKV---LEEFRPENFSG
GSLTFGNFSINLPSFEERRQ----------------------------------------
------------------------------------------------------------
-------------------------------TIGYRYQEEILPIGRQI------------
-------------------------LVIGTATDEEGMITIRKPTEKGQRYFI--------
-------------------SLKSEEE-------------------------LSQATNNAI
RGTFYSMIFFLTLGLILLVA----------------------------------------
------------------------------------------------------------
----------------------------------------GVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------ILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIA-----NQ
IAEEIGGGSLREYVKIRGVIECDRPLIS--------------------QLKQEPCVYYSM
TVTWEYNEEVIKQDNE-GKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIET
VKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTA---
---------TDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAI------RGTFYSMI
FFLTLGLILLVA------------------------------------------------
------------------------------------------------------------
------------------------------------------GVLRG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Cylindrospermopsis_raciborskii_CS_505_gnl|BL_ORD_ID|3366  647107707 CRC_03432 3-beta hydroxysteroid dehydrogenase/isomerase [Cylindrospermopsis raciborskii CS-505]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------IMNVAIIGCGYV----------------------------
--------------------------GYAV----------AKFWRQNPSFRVTVTTTSEH
KVSTLQEV----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------ADAVEVTMGDDQIFLNRVLKNQDVVLLAV---------GAKS
SSSYEKTYLETAKTVTSLIKYHPKI-KQLIYTSSY---AIYG--------------DRNG
VWVDEETPPAPPNLNSQILGKT---EEILLAAAT--------------------------
-------------EKLRVCILRLGGIYGPGR---ELIKIFSRT---AGTTREGNGEEITN
WVHLDDIVRVVEFARWQ-----------RLQGIYNLVDD--SHFTSRELIDG--------
--------VLKTHNLPNVIWDATNK--------------STRQYNTWV------------
-------------------------SNQKLKDAGYQFIHPHI------------------
------------------------------------------------------------
---------------------VL
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-------------ILIGIICLIVGVIL--------------------------------
------------------------------------------------------------
--------------------------LFFWR-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------SNRSKLRN-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------LRLASASTISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLK
QEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVN
PERAEIET-VKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQI
LVIGTATDEE------GMITIRKPTEKGQRYFISLKSEEELSQATNNAIR----------
-----GTFYSMI------FFLTLGLILLVAGV------------------------LRG-
-----------------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL-IGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLR--
--EYV---KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERK
SETVAQNSRSIPFTLQDS----TGEIRVNPERAEIETVK-----VLEEFRPENFSGGSLT
FGNFSINLPSFEERRQTIGYRYQEEILPIGR--QILVIGTATDEEGMITIRKPTEKGQRY
FISLKSEEELSQATNNA---------------------------------------IRGT
FYSM-------------IFFLTLGLILLVAGVL------------RG
>Lyngbya_sp_CCY_8106_gnl|BL_ORD_ID|1789  640015809 L8106_17014 hypothetical protein [Lyngbya sp. CCY 8106]

M-----------------------------------------------------------
-----SETTPI-----------------------------TPYLITLPPTQEELPYDDGE
PM-ESQRHQFQM-----------------------------EILLNTLQPWMASRSDGF-
------------------------------I----------------------GGNMFVY
-------------YSL-------EQVRNKDFRGPDFFAVLGVPKKERRSWVVWEEG----
-----------------------KAPDVVIELLSDSTA-ELDKTEKKYIYQD--------
----RLRVSEYFWFDPFNPEDLAGFSLQQG---VFQPIDFNAKNQLVSQALGLSLVR---
-WFGEYKGIEATWLRWANL--------DGELFPLPQEIAEQAH-----------------
---------------------QRAEQEYQRAEQEYQR-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AEQVESQLNQVA--RTLLQQGMTQ------
------------------------------------------------------------
------------------------------------------------------EQVVQV
TG----LSLAKIQ-----------------------------------------------
------------------------------------------------------------
------ELMNTNR
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------IL
IGIICLIVGV--------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ILL
FFWRSNRSKLRNLR---------------------------------LASASTISSLQTI
AN-QIAEEIG------GGSLREYVKI--RGVIECDRPLISQLKQEPCVYYSMTVT----W
EYNEEVIKQDNEGKTIREKERKSETVAQNSRSIP----------------FTLQDSTG-E
IRVNPERAEI-ETVKVLEEFRPENFSGGSLTFG---------------------NFSINL
PSFEERR--QTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFI------
------------------------------------------------------------
----------------------SLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGV
LRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M------------------------ILIGIICL---------------------------
-IVG--VILLFFWRSNR---------SKLRNLRLASASTI--------------------
------SSLQTIANQIAEEIGGG--------SLREYVKIRG-------------------
-------------------------------------VI---------------------
------------------------------ECDRPLISQLKQEPCVYYSMTVTWEYNEEV
IKQDNEGKTIREKERKSE---------------TVAQNSRSIPFTLQDSTGEIRVNPERA
EIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGT
ATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGV
LRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-------------------------------------------ILIGIICLIVGV----
-----------------------------------------------------------I
LLFFWRSNRSKLRNLRLASASTISSLQTIANQ-------IAEEIGGGSLREY----VKIR
GVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEG-KTIREKERKSET-----VA
QNSRSIPFTLQDSTGEIRVNPERAE----IETVKVLEEFRPENFSGGSLT----------
---------------------------------------FGNFSINLPSFEERRQTIGYR
YQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTFY
------------------------------------------------------------
------------------------------------------------------SMIFFL
TLG--------L----------------------I-----LLVAGVLR------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ--
------------------------------------------------------------
-----------------NSRSIPFTLQDSTGEIR----------------VNPERAEIET
VKVLEEFRPENFSGGSLT-------FGNFSINLPS-FEERRQTIGYRYQEEILPIGRQIL
VIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTF--------------
YSMIFFLTLGLILLVA--------------------------------------------
-------------------------------GVLRG------------------------
------------------------------------------------------------
------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ--
------------------------------------------------------------
-----------------NSRSIPFTLQDSTGEIR----------------VNPERAEIET
VKVLEEFRPENFSGGSLT-------FGNFSINLPS-FEERRQTIGYRYQEEILPIGRQIL
VIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTF--------------
YSMIFFLTLGLILLVA--------------------------------------------
-------------------------------GVLRG------------------------
------------------------------------------------------------
------------
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|1356  637231412 all1047 permease protein of ABC transporter [Nostoc sp. PCC 7120]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------IEYLIFLA
I-------------------------------STATFALFSLGLNLQWGFTG------LI
NFGHIAFMTLGAY--------------------------TTVLLSL--------------
-----------------KGVPLFISAIVGAI-----------------------------
----------------------FAALLGLVIGFATLRL----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----REDYLAIVTIGTGELIRLVVNNQDLPVGDTWVSGAFGVQSYPIPLSTEPNLFFRL
LMIGILTLLFAVTVFSLWRWIRNAQKLQLTDATDKTSSKQEIASRFGVGIILGLLATAIY
I----SGVIT----LYNYIPKAGLMLVSLLVLAFVFWRL--EYLVRSPW-GRVLKAIRED
EE----------------------------------------------------------
---------------------IPKAMG--------------------------------K
N--VFWYKLQ--------------------------------------------------
-------------------------------SLMLG---------GAIAGIAGAFFAWQI
SAIYPD-----------NFQ-P--------------------------------------
------------------------------------------------------------
--------------------------QLTFDSW---------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------IMVILGGAGNNIGSIL------------GAVIYFAYDAI
TREVL-------------------------------------------------------
---------PKIIPL---------------------DEARLGAFR--------IMCIGLI
LMVLM---IWRPQGILGKKEELTLG-----------K
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
-----------------------------MILIGII------------------------
------------------------------------------------------------
-----------------------------------------CLIVGVIL---------LF
FWRSNRSKLRNLRLASASTISSLQTIANQ---IAEEIGGGSLREYVKIR-GVIECDRPLI
SQLKQEPCVYYSMTVTWEYNEEVIKQ---DNEGKTIREKERKS----ETVAQNSRSIPFT
LQDSTGEIRVNPERAEIETVKVLE------------------EFRPENFSGGSLTFGNFS
INLP------------------------------------------SFEERRQT-IGYR-
----------YQEEI------------------LPIGRQ--------------------I
LVIGTATDEEGMI--TIRKPTEKGQR---YFI----------------------------
------------------------------------------------------------
-----SLKSE---------EELSQATNNAIRGTFYSMIFFLTL------GLILL------
---------------------VAGVL----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------RG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI--------------------------------------LIGIICLIVGVILLFFWRSN
RSKLRNLRLAS-ASTISSLQTIANQIAEEIGGGSLREY--------------VKIRGVIE
CDRPL-ISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFT
LQDSTGEIRVNP-----ERAEIETVKVLEEFRPE-----------NFSGGSLTFGNFSIN
LPSFEERRQTIGYRYQE------EILP---------------------IG----------
-RQILV---------------------------------IGTATDEEGMITIRKPTEKGQ
RYFISLKSEEELSQATNNAI-----------------------RGT--FYSMIFFLTLGL
ILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------IGIICLIVGVILLFFWR-----------SNRSKLR---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------NLRLASASTISSLQTIANQIAEE-
-----IGGGSLREYVKIRGVI----ECDRPLISQLKQEPCVYYSMTVTWEY---------
-------N------------------------------------EEVIKQDN------EG
KTIR----------------------EKERKSETV---AQNSRSIPFTLQDSTGEIRVN-
-----PERAEIE---TVKVLE------EFRPENFSGGSLTFGN--------------FSI
N------------------------------------------------LPSFEERRQTI
------------GYRYQEEIL-PIGRQILVIGTATDEEGMITIRKPTEKGQRY---FISL
KSEE--ELSQATN-NAIRGTFY-----------SMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL------IGII----------CLIV-----GVILLFFW--------------------
----------------------------------------------RSNRSKLRNLRLAS
ASTISSLQTIANQIAE-------------EIGGGSLREYVKIRGVIECDRPLISQLKQEP
CVYY-SMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSR---------------SIP
FTLQDSTGEI-------RVNP-ER--AEI----ETVKVLEEFRPE-NFSGGSLTFGNFSI
NLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRY--------
---FISLKS-EEELSQATNNAIR-------------------------------------
----------------------GTFYSMIFFLTLGLILL-------VAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------------------LIGIICLIVGVILLFFWRSNRSKLRNLRLASASTIS
SLQTIANQIA--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------EEIGGGSLRE
YVKIRGVIECDRPLISQLKQEPCVYYSMT-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------VTWEYNE--------------EVIKQDNEGKTIREKE
RKSETVAQNSRSIPFTLQ---------------DSTGEIRVNPERAEIETVKVLEEFRPE
NFSGGSLTFGNFSINLPSFEERRQTIGYRYQEE---------------------------
------------------------------------------------------------
-----ILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSE---------------
------------------------------------------------EELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG---------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------LIGIICLIVGVILLFFWRSNRSKLRNLRLASA-
--------------------------STISSLQTI---------------ANQIAEEI--
--------------------------------------------------------GGGS
LREYVKIRG-----------------VIECDRPLISQLK--------------QEPCVY-
---YSMTVTWEYNEEVIKQDNEGK------TIREKERKSETVAQNSRSIPFTLQDSTGE-
--------------------------------------IRVNPERAEIETVKVLEEFRPE
NFSGGSLT---------FGNFSINLP----------------------------------
-SFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEE-
------LSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG--------------------
-------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLT------FGNFSINLPSF
EERRQTIGYRYQEE----------------------------------------------
-----ILPIGRQIL----VIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAI
RG---------------------------------------------TFYSMIFFLTLGL
ILLVA-------------------------------------------------------
---------------------GVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-------------------------ILIGI-------------ICLIVGVIL-------
-----------------------------------------LFFWRSNRSKLRNLRLASA
S-----------TISS-LQTIANQIAEE--------------------IGGGSLREYVKI
RGVIECDRPLISQLKQEPC-VYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSR
SIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTI
GYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRY-FISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>Prochlorococcus_marinus_MIT_9303_gnl|BL_ORD_ID|1470  640086991 P9303_14811 SAM-dependent methyltransferase [Prochlorococcus marinus MIT 9303]

MT----------------------------------------------------------
-------------------------------------------SSTNSSLTSTPTPGDK-
---------VEITCV-------------------DLDRHGNGLARWNNWVVIVND-----
---------------------------------L--LPGERAQIEFVRRHR---------
-------------------------------------NQFLARKVHSIET----------
--------VSSRRQPPCKIAKECGGCSIQHLNDHGQSLLKQSHLREILLRLGQLDNKIEP
IMTDYTRALGYRNRALIP---------------LYRNREGQLLMGYYRRGSHQIIDLNRC
PVLDRGI-DQYLAWIKDDL--------QQQNW--PADSDLSSGEGVRHLGIR---IGQKT
RQVLITLVSSTTELSGLHQQANDWYRRWPEVK--------------GITLNIQRQRNNLV
LGQE----------TILLAGDLDIEEHFCNLSLLLSTTTFFQVNTIQAE-----------
-RIVLKLLKWLSTTLP---DINIIDAYC---GIGTISLPIAAAGYHVIGLELHAEAIAQA
NKNALRNNL-GNASFLCGDVSLLLAKI---LQHHDVLVLDPPRKGLDQMVIKTILSVRPE
RVAYLSCDPATLARDLKQLIVPNGPYQIDQLQPIDFFPQTMHIECLALLIRISS
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------ILIGII--------------------------------
------------------------------------------------------------
--------------------------------------------------------CLIV
GVILLFFW----------------------------------------------------
------------------------------------------------------------
-RSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQ
EPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNP
ERAEIETVKVLEEFRPENFSGGSLTFGNFSIN-------LPSFEERRQT-------IGYR
YQE---------EILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQAT
NNAIRGTFYSM-------------------------------------------------
IFFLTLGLILLVAGVLR--------G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI---------LIGI---------------------------------------------
----------------------ICLI------VGVILLFFWRSNRSKLRNLRLASASTIS
SLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIK
QDNEGKTIREKERKSETVAQNSRSIPFTLQ-DSTGEIRVNPERAEIETVKVLEEFRPENF
SGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIG-------TATDEEGMIT
I---RKPTEKGQRYFISLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGI------------------------ICLIVGVILLFFWRSNRSKLRNLRLASAST
ISSLQTIANQIAEEIGGGS-----LREYVKIRGVIEC-------DRPLISQLKQEPCV--
-----------YYSMTVTWEYNEEVIKQDN------------------------------
--------------------------------------------------E---------
-----------------GKTIRE--------KERKSETVAQN------SRSIPFTLQDST
GE-IRVNPERAEIET-----------------------VKVLEEFRPE-NFSGGSLTFGN
FSINLPSFEERRQTI----GYRYQEEILPIGRQ---------------------------
-ILVIGTATDEEGMITIRKPTEKGQRYFISLK--SEEELSQATNNAIRGTFYSM------
----------------------------------------------------IFFLTLGL
ILLVAGVLR---------------------------------------------------
-------------------------------G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGV---------------------------ILLFFW--------------
---RSNRSKLRNLRLASASTISS------LQTIANQIAEEIGGGSLREYVKIRGVIECDR
PLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDS
TGEIRVNPERAEI-----ETVKVLEEFR-----PENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGV---------------------------ILLFFW--------------
---RSNRSKLRNLRLASASTISS------LQTIANQIAEEIGGGSLREYVKIRGVIECDR
PLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDS
TGEIRVNPERAEI-----ETVKVLEEFR-----PENFSGGSLTFGNFSINLPSFEERRQT
IGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIR
GTFYSMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL------IGII----------CLIV-----GVILLFFW--------------------
----------------------------------------------RSNRSKLRNLRLAS
ASTISSLQTIANQIAE-------------EIGGGSLREYVKIRGVIECDRPLISQLKQEP
CVYY-SMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSR---------------SIP
FTLQDSTGEI-------RVNP-ER--AEI----ETVKVLEEFRPE-NFSGGSLTFGNFSI
NLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRY--------
---FISLKS-EEELSQATNNAIR-------------------------------------
----------------------GTFYSMIFFLTLGLILL-------VAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------IGIICLIVGVILLFFWR-----------SNRSKLR---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------NLRLASASTISSLQTIANQIAEE-
-----IGGGSLREYVKIRGVI----ECDRPLISQLKQEPCVYYSMTVTWEY---------
-------N------------------------------------EEVIKQDN------EG
KTIR----------------------EKERKSETV---AQNSRSIPFTLQDSTGEIRVN-
-----PERAEIE---TVKVLE------EFRPENFSGGSLTFGN--------------FSI
N------------------------------------------------LPSFEERRQTI
------------GYRYQEEIL-PIGRQILVIGTATDEEGMITIRKPTEKGQRY---FISL
KSEE--ELSQATN-NAIRGTFY-----------SMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MI----------------------------------------------------------
------------------------------------------------------------
--LI---GIICLIVGVILLF----------------------------FWRSNRSKLRNL
RLASASTISSLQTIANQIAEE------------IGGGSLREYVKI---RGVIECDRPLIS
QLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ--NSRSIPFT--LQDS
TGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNF-------------SINLPSFEER
RQTIGY-RYQEEILPIGRQILVIG-------------TATDEEGMITIRKPTEKGQRYFI
SLK--SEE--ELSQAT--------------------------------------------
-------------------------------NNAIRGTFYSMIFF---LTLGLILLV---
---------AG-------------------------------------VLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL----IGIICLIVGV---------------ILLF-----------------FWRSNRS
KLRNLRLASASTISSLQTIANQIAEEIGGGS---------LRE-----------------
---------------YVKIRGVIECD---------------------RPLISQLKQEPCV
YYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAE
IETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTA
TDEEGMITIRKPTEKGQRYFISLKSEEELSQATNN-------------------------
--AIRGTFYSMIF-----------------------------------------------
------------------------------------------------------------
-----------------------------------------FLTLGLILLVAGVLR----
G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------ILIGII--------------------------
------------------------------------------------------------
-----------CLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGG---
----------------------GSLREYVKIRGVIECDRPLISQLKQ-------------
----------------------------------------------EPCV---YYSMTVT
WEYNEEVIKQDNEGKTIREKERKSETVAQNS------------------------RSIPF
TL------------------QDSTGEIRVNPERAE------------IETVKVLEEFRPE
NFSGGSLTFGNFSI------NLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMI
TIRK--------------------PTEKGQRYFISL-----------KSEEELSQATNNA
IRGTFYSMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTI-----SSLQTIANQIAEEIGGGS
LR------EYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREK
ERKSETVAQNSRSIPFT-LQDSTGEIR----VNPERAEIETVKVLEEFRPENFSGGSLTF
GNFSINLPSFEE-------------RRQTIGYRYQEEILPIGRQILVIGTATDEEGMI--
-------------TIRKPTEKGQ-----RYFIS--------------------LKSEEEL
SQAT-----------------NNAIRGTFYSMIFFLTLGL-----------ILLVAG---
---------------------------------------VLRG
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|2513  637618204 syc2512_d hypothetical protein [Synechococcus elongatus PCC 6301]

MAA---------------------------------------------------------
-------------------------------------IILAAIT----------------
------AIAAIVLYFVRRHYRFKLQSLLLAQPATSLQLKEIAEHVAGEIGGGNLRQYVKM
WGAIEVEQPLVSELKQ--ESCVYYCSTVS------REYEERVRKEDSEGKVTWTTERRSE
TISQNRRSTPFYLRDQHGRVRVEPESAAIATIPVLDEFR-PDS-SASSLIFGAFSLSLST
TAGLGKTLGYRYREEILPCDRSVLVVGAASDETGELTLGPSSEARQQFFIALKPETALLQ
EVKQTIQWLTIGAIASVVVTVVAAIAALL--
>Synechococcus_elongatus_PCC_7942_gnl|BL_ORD_ID|1573  gi|81300335|ref|YP_400543.1| unnamed protein product [Synechococcus elongatus PCC 7942]

MAA---------------------------------------------------------
-------------------------------------IILAAIT----------------
------AIAAIVLYFVRRHYRFKLQSLLLAQPATSLQLKEIAEHVAGEIGGGNLRQYVKM
WGAIEVEQPLVSELKQ--ESCVYYCSTVS------REYEERVRKEDSEGKVTWTTERRSE
TISQNRRSTPFYLRDQHGRVRVEPESAAIATIPVLDEFR-PDS-SASSLIFGAFSLSLST
TAGLGKTLGYRYREEILPCDRSVLVVGAASDETGELTLGPSSEARQQFFIALKPETALLQ
EVKQTIQWLTIGAIASVVVTVVAAIAALL--
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYV
KIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNS
RSIPFTLQ-----------------DSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLT
FGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFI
SLKSEEELSQATNNAIRGTFYSMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTI-----SSLQTIANQIAEEIGGGS
LR------EYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREK
ERKSETVAQNSRSIPFT-LQDSTGEIR----VNPERAEIETVKVLEEFRPENFSGGSLTF
GNFSINLPSFEE-------------RRQTIGYRYQEEILPIGRQILVIGTATDEEGMI--
-------------TIRKPTEKGQ-----RYFIS--------------------LKSEEEL
SQ---------------------------ATNNAIRG-----------------------
-------------------TFYSMIFFLTLGL------ILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M----------------------------------------------ILI----------
------------------------------------------------------------
----------------GIICLIV--------GVILLF---------------FWRSNRSK
LRNLRLA---------SASTISSLQTIANQIAEEIGGGSLREYVKIRGVIECDRPLISQL
KQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDS-TGEIR
VNPE-------RAEIETVKVLEEFR-PENFSGGSLTFGNFSINLPSFEERRQTIGYRYQE
EILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISLKSEEELSQATNNAIRGTF----
---YSMIFFLTLGLILLVAGVLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL-----------IGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAE
EIGGGSLR--------------------EYVKIRGVIECDRPLISQLKQEPCVYYSMTVT
WEYNEEVIKQDNEGKTIREKERKSETVAQNSR-SIPFT-LQDSTGEIR----VNPERAEI
ETVKVLEEFRPENFSGGSLTFGNFSIN-----------LPSFEERRQT------IGYRYQ
EEILPIGRQILVIGTATDEEGMI---------------TIRKPTEKGQ------------
----------------------------------------------RYFISLKSEEELSQ
ATN----NAIRGTFYSMI-----------FFLTLGLILLVAGVLRG--------------
------------------------------------------------------------
--------
>Synechococcus_sp_JA_2_3B_a2_13_gnl|BL_ORD_ID|170  637874588 CYB_0172 hypothetical protein [Synechococcus sp. JA-2-3Ba(2-13)]

MGVSYRRSNRAKAVLEGRGFRPSFLVKFGTARIRDCLKLLLNPVSQVTASMRPTSLPPPE
RKAFMNWLMLLGLLCLPASLF------SFVEYLRSQRLV---------------------
------------------------------------------------------------
------------------------------------------------------------
---QQLSATRLLKIAELRHLGQ-------TNPQAKGANL---AQVYGRVVCDRPLVSELS
RQPCVYY-----KSEISWEYDEIECYRRYLNSRGDVAYSERISEGEYQNALRLGSRAKSY
PGEMVG---------------------------------KKPGLGYSDSGSFQKRVDPDY
SNSFPQKPNPGYP--QQLGSPGYPQKSPFSEVSSPQKHYANVYYDPSTGREYLLERETRT
RDETLHSV--------------------------VRQIPFFIEDETGRV-----------
-----RVDPTGAEI-----EAMSVV-----------DE---HIFPGKGPS--RFNFNLKR
YLSGVRTENRSTRAFIYKEWVIPVDAMAFTMGQVRFEAGDPVIRKPL-SGERFMIAPKSP
E----ALLEEQRSNASSYL------------VGSVVLLG---------------------
---------------------------IGIFTVL--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------HLLQSLQPYR
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M------------------------ILIGIICLIVGVILLFFWRSNRSKLRNLRLASAST
IS----------------------------------------------------------
--------------------------SLQTIANQIAEEIGGGSLREYVKIRGVIECDRPL
ISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIRE------------------------
---KERKSETVAQNS-------------------------------RSIPFTLQDSTGEI
RVNPERAEIETVKV---------------------------------------LEEFRPE
NFSGGSLTFGNFSINLPSFEERR---QTIGYRYQEEILP-IGRQILVIGTATDEEGMITI
RKPTEKGQRYFISLKSEEELS---------------QATNNAIRGTFYSMIFFLTLGLIL
LVAGVLR----------------G------------------------------------
---------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------ILIGIICLIVGVILLFF
WRSNR-SKLR------NL------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------RLASASTISSLQ-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TIANQIA--------------EEIGGGSLREYV---
-----------------K-------IRGVIECDRPLISQLKQEPCV---YYSMTVTWEYN
EEVIKQ---DNEGKTIREKERKSET----------VAQNSRSIPFTLQDSTGEIRVNPER
AEIETVKVLEEFRPENFSG-GSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVI
GTATDEEGMITIRKPTEKGQ-RYFISLKSEEELSQATNNAIRGTFYS-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MIFFLTLGLILLVAG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--VLRG
>Synechococcus_sp_PCC_7335_gnl|BL_ORD_ID|4701  647580957 S7335_206 conserved domain protein [Synechococcus sp. PCC 7335]

MDFLSDFLTLFLSKLQSPTLGFLIGGAIVAALNSRLTIPDPVYKFIVFMLLIKVGLSGGI
AIRNANLFEMLLPAAFA-------------------------------------------
---------VVIGILIVFLGKYTLAKLPNVRTVDALATAGLFGAV---------------
----SGSTLAAALTLLETEG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------IEYEAWAAALYPFMDI--------PALVTAIVLASVYTSK
RRSIA-NEELSKQEYLGK-----------------------QEYLGKQRV----ATVEHS
AVEGTTVPGE--YSGG------QGTAVSEYRSGQG-ST----PSKRVEIWPIVKESLQGS
ALSALLLGLA------LGIIT--QPESVYESFF---------------------------
------------------------------------------------------------
-----------------NPLFRGLLSILMLVMGMEATARL------GELRKVGQWYALYA
FVAPLV----------HGLIAFGFGMIAHVTTGFSPG-----------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------GVVILAVIAASSSDIS----GPPTLRAGIPS
ANPSAYIGSSTAVGTPVALAIGIPLFIGLAQ-----------------------------
--------------------------------AVMGS
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M----------ILIGIICLIVGVILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEE
IGGGSLREYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQDNEGKTIREKE
RKSETVAQNSRSIPFTLQDSTGEIRVNPERAEIETVKVLEEFRPENFSGGSLTFGNFSIN
LPSFEERRQTIGYRYQEEI-LPIGR------QILVIGT-------------ATDEEGMIT
IRKPTEK-----GQRYFISLKSEEELSQATNN--AIRGTFYSMIFFLTLG--LILL----
-----------VAGVLRG----------------------------------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M-----------------------------------------------------------
---------ILIGIICL-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------IVG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------VILLFFWRSNRSKLRNL----------
------------------------------------------------RLASASTISSLQ
TIANQIAEEIGGGSLRE-YVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVIKQD
NEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIR---------------------VNPE
RAEIETVKV------LEEFRPENFSGGSLT-------FGNF--SINLP--SFEERRQTIG
YRYQEEILPIGRQILVIGTATDEEGMITIRKPTEKGQRYFISL-----KSEEELSQATN-
---------NAIRGTFYSMIFFLT------------------------------------
-----------------------------------------------------LGLI---
--LLVAGVLRG-------------------------------------------------
--------------------------------
>Synechococcus_sp_WH7805_gnl|BL_ORD_ID|1619  639020969 WH7805_03377 hypothetical protein [Synechococcus sp. WH7805]

MTMPSRHAWFSSCLLASLPWLAGCADGDAPVAVEAPPFVFRSLELEQKSSTGQKEWSLSS
PEARYELNRRLVRARQPVGLLFRNGKPSFRIQSDLAQVINDGEKILLEGNVKLQQLTGSK
LLIQGDRLRWRPDQGVLTMEQRPRASDQESRISASQ----AELQQTTNELTLTGTVQLDR
WST---SDRNA-------RPDSSLRSGKAQWNLDTGLLNAKGPILGQRRDKEGTVLEQLE
GQSLEG----------------------------NTLKGEITVQ----------------
-----APVILRIPREKGVLRAKATTWVFRDQIIRSAKPFKADLDRTTIRGESFRADLGQS
SVDVN----------GACEIRQPGEALKAERCR-------WNWSNEA-VLAEGKVELRRD
ENDQVTRATRLEGTVG--------------------------------------------
------------------------------------------------------------
-------------KEGRI---------------------SFTAPGSKVQSEVRIPTE---
-------------------------------------------GPEGTPEARPQPNPVSF
--------------
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M--ILIGIICLIVGVILLFFWRSNR----------SKLRNLRLASASTI-----SSLQTI
ANQIAEEIGGGSLR------EYVKIRGVIECDRPLISQLKQEPCVYYSMTVTWEYNEEVI
KQDNEGKTIREKERKSETVAQNSRSIPFT-LQDSTGEIR----VNPERAEIETVKVLEEF
RPENFSGGSLTFGNFSINLPSFEE-------------RRQTIGYRYQEEILPIGRQILVI
GTATDEEGMI---------------TIRKPTEKGQ-----RYFIS---------------
-----LKSEEELSQAT-----------------NNAIRGTFYSMIFFLTLGL--------
---ILLVAG------------------------------------------VLRG
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL----IGIICLIVGV---------------ILLF-----------------FWRSNRS
KLRNLRLASASTISSLQTIANQIAEEIGGGS---------LRE-----------------
---------------YVKIRGVIECD---------------------RPLISQLKQEPCV
YYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQNSRSIPFTLQDSTGEIRVNPERAE
IETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILVIGTA
TDEEGMITIRKPTEKGQRYFISLKSEEELSQATNN-------------------------
--AIRGTFYSMIF-----------------------------------------------
------------------------------------------------------------
-----------------------------------------FLTLGLILLVAGVLR----
G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
MIL---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------IGIICLIVGVI-----------LLFFWRSNRSK--LRNLRLASA
S-TISSLQTIANQIAEEIG---------------GGSLREYVKIRGVIECDRPLISQ---
------------------------------------------------------------
------LKQEPCV---YYSMTVTWEYNEEVIKQDNEGKTIREKERKSETVAQ--------
---------NSRSIPFTLQDSTG--------------EIRVNPE----------RAEIET
VKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTIGYRYQEEILPIGRQILV---IGTA
TDEEGMITIRKPTEKGQ----------RYFISL----------------------KSEEE
LS---QATNNAIRGTFYSMIFFLTLGLILLVAGVL-------------------------
------------------------------------------------------------
-----------------------------------------------------------R
G
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
M---------------------------ILIGIICLIVGV--------------------
------------ILLFFWRSNRSKLRNLRLASASTISSLQTIANQIAEEIGGGSLREYVK
IRGVIECDRPLI------------------------------------------SQLKQE
PC---------------------------------VYYSMTVTWEYNEEVIKQDNEGKTI
REKERKSETVAQNSRSIPFT------LQDSTGEIRVNPE--RA-----------------
------------------------------------------------------------
------EIETVKVLEEFRPENFSGGSLTFGNFSINLPSFEERRQTI--------------
-----------------------------GYRYQEEILPIGRQI--LVIGTATDEEGMIT
--------IRKPTEKG--QRYFISLKSEEELSQATNNAIRGTFYS------------MIF
FLTLG-----LILLVAGVLRG---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|658  637313275 tll0660 hypothetical protein [Thermosynechococcus elongatus BP-1]

MGVLGGILLVIAVLVLCGWWDYRLKVRALNLAVSSTPAQLHELQRRVAQEIGGGYLQEYV
KISGQIVADRPLVSELKRLPCVHYRLCVSRVYKTTESHEDGSSET----KYRHEILSSNT
QTIPFRLRDGDMEIYVDPRGAEIETVQVLNEFQEDN----------NTTHLAFGRFQMDL
SSLPKHSDTVGYRYEEWILPVNQQVFVVGTASDERGKLRIRRPHQ---KGQLFFISLESE
ENLTKKVRQYARASIIAAGVFSGLGILLILL-----------------------------
-------------------------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|198  637312804 tll0199 hypothetical protein [Thermosynechococcus elongatus BP-1]

MGVFAHLCLTGSAFLFALEGYYRLQLRGIKVASPSTIGELEKFQQQVAQEMGSGSWREYV
QVVGQVTTSQPLLSEVKRIPCVYYKTIISREYEKEGS------------DRPSEIIGRHE
QSTLFLLRDHQGEIEVNPFGAEIEAVQVLDELRPAD----------QPHAFALSLGFLSF
NWHFGKGTTLGYRYQEWVLPLGQPVSVVGMASDQGGVLRLQKPQN---RGQKFIISLSFE
DPLIQQYKQQKRKMTYASLGATLCGVCGLVLA----------------------------
-----------------------LF
>Cyanothece_PCC_7424_gnl|BL_ORD_ID|2656 gi|218439670|ref|YP_002377999.1| hypothetical protein PCC7424_2719 [Cyanothece
------------------------------------------------------------
---MIL--------------------------------IGIICLIVGVILLF------FW
RSNRSKLRNLRL------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ASASTISSLQTIANQIAEEIGGGSLREY
VKIRG-------------------------------------------------------
--VIEC-----DRPLISQLKQE----------------------PCVYYSMTVT------
--------------------------------------WEYNEEVIKQDNEGK----TIR
EKERKSETVAQN--SRSIP---FTLQDSTGEIRVNPERAEIETVKVLEEFRPENFS----
------------------------------------------------------GGSLTF
GNFS--------------INLPSFEE----------------------------------
----------RRQTIGYR------------------------------------------
---YQEEILPIGR-QILVIGTATDEEGMITIRKPTE----------KGQRYFISLKSEEE
LSQATN----------NAIRGTFYSMI-FFLTLGLILL-----------VAGVLRG--
