>Aquilegia_coerulea_gnl|BL_ORD_ID|33246 _026_00048.1|PACid:22056357

MLPW--------------------------------------------------------
------------------------------------------------------------
-GGITCCMSAAALYL-----------------------------------LGKSSGRDAD
ILKSVTRLN---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------QLKDLAQM
LDT------------------ACKVLPFVVTVSG---RVGSDTPINCE------------
----------------------HSGLRGVIVEEAAEQ-----------HFMKQNDSGS-W
IQDSAQM---------------------------------------------------LA
MT-------------------KEVPWYL---DDGT---GRVHVLGARGATG---------
---LVLTVASETFEESGRSLV----RGTLDYLQGLKMLGVKRIERVLPTGTSLTVVGEAV
KDDVGTIW---IQRPHKG---PFYVSPKSIDQLIANLGIWARLYKYASLGFTAFG-----
---------VYLIAKHAIRYILERRRLLDFQR-RVRAAAAQRLEQDNDG---TDGKAEDG
P-DVVNKDRIMPDICVICLEQEYNAVFVPCGHLCCCTTCSSHL-----SNCPLCRRRIDQ
VVRTFR-H
>Aquilegia_coerulea_gnl|BL_ORD_ID|33247 _026_00048.2|PACid:22056358

MLPW--------------------------------------------------------
------------------------------------------------------------
-GGITCCMSAAALYL-----------------------------------LGKSSGRDAD
ILKSVTRLN---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------QLKDLAQM
LDT------------------ACKVLPFVVTVSG---RVGSDTPINCE------------
----------------------HSGLRGVIVEEAAEQ-----------HFMKQNDSGS-W
IQDSAQM---------------------------------------------------LA
MT-------------------KEVPWYL---DDGT---GRVHVLGARGATG---------
---LVLTVASETFEESGRSLV----RGTLDYLQGLKMLGVKRIERVLPTGTSLTVVGEAV
KDDVGTIW---IQRPHKG---PFYVSPKSIDQLIANLGIWARLYKYASLGFTAFG-----
---------VYLIAKHAIRYILERRRLLDFQR-RVRAAAAQRLEQDNDG---TDGKAEDG
P-DVVNKDRIMPDICVICLEQEYNAVFVP-------------------------------
--------
>Aquilegia_coerulea_gnl|BL_ORD_ID|4964 _014_00808.1|PACid:22027970

MSST--------------------------------------------------------
-----------------------------------------LNERIISLIAQLALATDGA
GAGVFLAYFTVQIWR-----------------------------------NYRYTSSALE
RIHQAKSIT---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------ISDLRSL
LIDDNNSSQTQSSSEKQLVIIRGLVEAKSVVDGNWKNLIPSSSSSNSSSISSSIGKSG--
----------------GLLLSNQSGAKGVVLQNTQTY----------------------V
YNDYKGL---------------------------------------------------LG
YAVDLRTLLGKPSKGPNALSIRTIPFVLVQNGDS----------QSLDSKDYVVVNLEGS
MHPLPLTTCYHHLQPIPTTPY----TLIQAIVGHAYPVGLLDEEKILPLGKEITAVGHCT
LQD-GNPQ---IISCKKV---PYFLSDMTKDQMIVDLVSKKKILFWAGI-----------
---------VLGSVSLGVLGYALTRNWQRLKEWRQRRQIQQSREEEIAN---LDATPEDT
RADEETEDIPEGQLCVICLMRRKRAAFVPCGHFVCCYRCALSVERDSAPKCPLCRQDIRT
SVRIYD-S
>Aquilegia_coerulea_gnl|BL_ORD_ID|11545 _009_01076.3|PACid:22034572

MTDFEPLQQKQDSSDACSDFERGLEELMRERLNDCMPLASCSATRDQDDDDDEGDQLVRR
RRRSDLDGDDLAESSAARRRHTRILSRWAQRQAEEMITTIERRNRESELMALAGLHT---
-----VSMLDSSFLRESQSPTSRRQGAVERPNTQASSLLQMWRELEDEHVLNRARERVRE
RLRHQRSVESNTNLSTTTMSESRVSEHQDSSVASESENEYGMWSQGPIDSHNERGNHSLS
SREQSPDLGEVDRERVRHIARGWMDSGLSDHASNVSHRNSPRAEWLGETERERVRLVREW
VQMTSQQRGARSGRRDEQATLSQTNQVRDGLVVDHDEIQPEHVRRDMRRLRGRQAVLDVL
VRIESERQRELQGLLEHRAVSDFAHRNRLQSLLRGRFLRNERPTEDERPPSMAASELGQL
RQRQTVSGLREGFRSRLENIVRGQVSSQSDTLSN--NINGSQNEHNETSISQEVPHEGHE
QSEPRSQESVRSSPDHTRDLESDTAAESINWQQTATQEADWQDQVTEDERINWQQSADVT
FNDWEDTNEDEMEGNWQENIATDWPQGTAENDDEEDSRIQEAHEWHEDDSQDAASSWPDG
HSDPPRTRRAVPSRRANRFH-P-------PDDDNVYSMELRELLSRRSVSN---------
---LLRSGFRESLDQLIQSYVERQSRSPIDW----------DLHRNLPTPASPEQEQVQQ
RDDRSDDQPDTVSRPSLVMPSPPVPPPQPLWHQALHHANWPR----HSMHRTEFEWEIIN
DLRSDMARLQQGMSHMQRMLEACMDMQLELQR-SVRQEVSAALNRSAGG---P----ETS
E-DGSKWGHVRKGTCCVCCDSHIDSVLYRCGHMCTCSKCANELVR-SGGKCPLCRAPIVE
VIRAYSIL
>Arabidopsis_lyrata_gnl|BL_ORD_ID|19937 _474968|PACid:16053684

M-----------------------------------------------------------
----------------------------IPWG--------GVTCCLSAAALYLLGRSSGR
DAEVLKTVT---------------------------------------------------
------------------------------------------------------------
RVNQLKELAQLL----------E-LDSKI----LPFI-----------------------
-----------VAVSGRV------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------GSETPIKCEHSGIRGVIVEETAEQHFLKHNE-TGSWVQDSALMLSMS
-----------------KEVPWFLDDGT-----SRVHVMGARGATGFALTVGSEVFEESG
R-SLVRGTLDYLQGLKMLGVKRIERVLPTGIPLTIVGEAVKDDIGEFRIQ----------
-------------------KPDRG-PFYVSPKSLDQLISNLGKW-------SRWYKYASM
GFTVFGVFLITKHV-------IDSVLERRRRRQLQKRVLDAAAKRAELESEGSNGARESI
ADSTKKEDAVPD--LCVICLEQEYNAVFVPCGHMCCCTACSSHL-----TSCPLCRRRID
LAVKTYRH
>Arabidopsis_lyrata_gnl|BL_ORD_ID|12068 _338432|PACid:16045815

M-----------------------------------------------------------
----------------------------IHLA--------GFTCCLGGIALYLLSRNTGG
---VVKSIT---------------------------------------------------
------------------------------------------------------------
RVNHLKDLEQLV----------E---SKV----FPLI-----------------------
-----------IAVSGIV------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------GSETPIKCEHSDILGVFLKKTAEQQVLSRNW-RFSWVRKSTLMQPMT
-----------------KEVPWFLDDGT-----GRVNVAVSQGEIGLALTVGSDVFEKAE
PVSLVQGTLDYLKGLKILGVRRVEHVVPIGTPLTIVGEAVKDGMGNVRIQ----------
-------------------KPEQG-PFYVSYVPLDQLISKLGEW-------SRRFKYASM
GLTVVGVILLSKPVIKYILKKIEDTLERRRRQLLQKRVVD--------------------
---------VPD--LCVICHDQKYNTAFVQCGHMCCCLTCSLRL-----TTCPLCREQIQ
QVLKIYRH
>Arabidopsis_lyrata_gnl|BL_ORD_ID|936 _867782|PACid:16034683

M-----------------------------------------------------------
----------------------------IHLG--------GLTCCVSGGVLYLLSMIPGS
FFEMLNSVT---------------------------------------------------
------------------------------------------------------------
RVHQIKDLENLL----------Q-VEGK--------I-----------------------
-----------IAVSG--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------TAQQLFLKRNW-LFSWVEDSKWMLPQA
-----------------KEVPWYL------------------------------------
----------------MLGVRRTEHVLPIGTPVTVVGEAVKDGIRGFRIQ----------
-------------------KPEKG-LFFVSPVPLDKIISPMGKW-------LRRFKYVYV
GLTVVGVILISKPV-------IEYILERRRGRLLRKRVADAAAKRAKLVARGLETQHENS
LDSTSRDRDVLD--LCVICLEQKYDATFVKCGHMCCCLTCSLHV-----KTCPICRRPIE
HVLKIDRR
>Arabidopsis_lyrata_gnl|BL_ORD_ID|6881 _474546|PACid:16040628

MSSPERALLNLL------------------------------------------------
----------------------------TDIALSFDGAILGLTLAISAVGSALKYASTNA
ALNKIKEAP---------------------------------------------------
------------------------------------------------------------
EVSVA-DLRSLL----------PVSEDKSETNDHGKI-----------------------
-----------VVVRGVV------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------KP--KYSGDESHKNNNVLISPETGDKALIIQRTQTYVYSGWKRLFQSTG
HRFMLERSMRKHGADFMRTVPFVIVGKDQQSQSTFLDVNMDGSRQPLPLTTVYNRLQPIN
S-SFLQA---FLFPDYPVGLLDIEKILPPGKDITAVGICSFNN-GVPEIK----------
-------------------SCQDL-PYFLSEMTKDKMIEELMDQ-------TSFIFFGSV
ILGIVSVGILSYAAVRTWNKWKQWNHQR-----------DLPQRPNEPVVDDEPEDADE-
---------IPDGELCVICVTRRRVPAFIPCGHVVCCRVCASTVERELNPKCPVCLQSIR
GSMRVYYS
>Arabidopsis_lyrata_gnl|BL_ORD_ID|21963 _321523|PACid:16055710

MDSAPSPSSPDLESSPPVLVTMNSTSSSSDNNVEGDDDDAANHEIFNWREFSSCWRVSES
NLYCFSLALLVWFFASFILIENLYGPKNVWLG----------PNSSILVEPSSIFVKSIK
VVKVLDYSKPGLQLYGFYRSPALDCFVNWSESRVLPVWPYYLNRRTLLNITYTVKPQGSA
VQLVVDEGHQGDPQSFLNDPAYRYKVWSWNLIEGNGMIELEIRKSSSYYLAVANLKRKDV
EVELNIDVRAVLYDTKQSFYNCNFSNGECAFNVMPLVGNSVVVTSTAASQGVSIEDEWYI
RFSYQPREIAYVIGTGVVICFMLVAIQFCNRLQCYGGEGYLTENDSARTRLLENKDDDGS
SMGSCNDSFANDDADLEEFMENDGEASNRSRRLCAICFDAPRDCFFLPCGHSVSCYECGT
TMQEDDGSCPICRRKMKKVKRIFTVQSPLQHTQPSPMDTFLSLSLDIFLDHHLTPKKISM
TSSIVAKLRGGCLACLALLALCVYGSLVASVFLMFGFYGAANVWLGPHSSVLVEPSSIFV
KSIKVKELDFTKPGLQLYGFDDESTPSTYFVNWTESRVLSVSQN-SYKAGSAARLLMSEG
MPGMFRSSSLEDLAFCDRAWSWNLIQGS--------------------------------
------------------GMIELEINKSKGYYLTVANSKRKDVEVELDIDVRAVLYDTNQ
SSYNCTFSNGECAFKTNEVSPVEN-YAVVTSPALGQGVTIEDEWYIELSYQPRWIAYVSF
TGILFSFMLVAIHF-----------CNKLQCSGGEGLLTENDSARTHLLADKDDDDSCND
GEASNRSRC-----VCAICFDAPRDCFIFPCGHCVSCYQCGTKIKRAK-GRCPICRKKMM
LVKRIYTV
>gnl|BL_ORD_ID|17261 Arabidopsis_thaliana AT1G63900.1|PACid:19655208
M-----------IPWG--------GVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKE
LAQLL-ELDSKIL---------PFIVAVSGRVGS--ETPIKCEHSGIRGVIVEETAEQHF
LKHNETGS-WVQDSALMLSM-----------------SKEVPWFL---DDGT--S-RVHV
MGARGATGFALTVGSEVFEESG-----------R-SLVRGTLDYLQGLKMLGVKRIERVL
PTGIPLTIVGEAVKD--------------------------DIGEFRIQKPDRG-PF---
-YVSSKSLDQLIS-------NLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLER-----
-RRRRQLQK----RVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYN
AVFVPCGHMCCCTACSSHL-----TSCPLCRRRIDLAVKTYRH
>gnl|BL_ORD_ID|17260 Arabidopsis_thaliana AT1G63900.2|PACid:19655207
M-----------IPWG--------GVTCCLSAAALYLLGRSSGRDAEVLETVTRVNQLKE
LAQLL-ELDSKIL---------PFIVAVSGRVGS--ETPIKCEHSGIRGVIVEETAEQHF
LKHNETGS-WVQDSALMLSM-----------------SKEVPWFL---DDGT--S-RVHV
MGARGATGFALTVGSEVFEESG-----------R-SLVRGTLDYLQGLKMLGVKRIERVL
PTGIPLTIVGEAVKD--------------------------DIGEFRIQKPDRG-PF---
-YVSSKSLDQLIS-------NLGKWSRLYKYASMGFTVLGVFLITKHVIDSVLER-----
-RRRRQLQKSCFCRVLDAAAKRAELESEGSNGTRESISDSTKKEDAVPDLCVICLEQEYN
AVFVPCGHMCCCTACSSHL-----TSCPLCRRRIDLAVKTYRH
>gnl|BL_ORD_ID|19755 Arabidopsis_thaliana AT1G59560.1|PACid:19657702
M-----------IHLA--------GFTCCLGGVALYLLTRSTGRD---IKSITRVYQLKD
LEQLV-EVESKVV---------PLIIAVSGDVGS--ETPIKCEHSYVLGVFLKRTAEQQV
LRRNWRFS-WVRNSTLMQPM-----------------TKEVPWYL---DDGT--G-RVNV
DVSQGELGLALTVGSDVFEKAE-----------PVSLVQGALGYLKGFKILGVRHVERVV
PIGTPLTVVGEAVRD--------------------------GMGNVRIQKPEQG-PF---
-YVTYIPLDQLIS-------KLGDLSRRFKYASMGLTVLGVILISKPVIEYILKRIEDTL
ERRRRQFAL---KRVVDAAARRAKPVTGG----------GTSRDGDTPDLCVVCLDQKYN
TAFVECGHMCCCTPCSLQL-----RTCPLCRERIQQVLKIYRH
>gnl|BL_ORD_ID|17011 Arabidopsis_thaliana AT1G54150.1|PACid:19654958
MSSPERALLNLLTDIALSFDGAILGLTLAVSAVGSALKYASTNAALKKIKDAPEVSI-SD
LRSLLPASEDKSETNDNRKSNDQRIVVVRGVVKP--KISGDEGYKNNNVLISPETGDKAL
IIQRTQTYVYSGWKRLFQSTGHRFMLERSLRKHGADFTRTVPFVIVGKDQQSNSS-FVAV
NMDGSRQPLPLTTVYNRLQPIN-----------S-SFLQA---FLYPDYPVGLLDIEKIL
PPGKDITAVGIYSFN--------------------------N-GVPEIKSCQDL-PY---
-FLSEMTKDKMIE-------DLMEQTNFIFLGSVILGIVSVGILSYAAVRTWNKWKQWNH
QRELPQRPN---DSVVDDEPEDADEIPDG-------------------ELCVICVSRRRV
PAFIPCGHVVCCRRCASTVERELNPKCPVCLQSIRGSMRVYYS
>gnl|BL_ORD_ID|1107 Arabidopsis_thaliana AT2G38195.2|PACid:19639054
M-------------------------------------SKENEESEANLYSAKELDF---
-------------------------------SKPGLQLYGFNGQSTPSGYFVN-------
---------WTESRVLSVSQNS---------------YKGWPYYL---NRGTHMNISYNI
LPKGSAVRLVITEGMPFFYRSSLKDIAFRDTAWSWNLIQG----------SGMIQLDISK
SKGYYLTVANLKRKDVEVELDIDVKVVLYDTKQSSYNCSFSN-GECSFKMNERS-PVENY
AVVTSPALGQGVSIDDEWYIELSYQPRLIAYGSFTGVLLSFMLV---AIHFCNKLKCCGG
EGFLSE----------DDSVRTCLLADKGDNDCCNDVEASNK------SLCAICFDAPRD
CCFLPCGHCVSCYQCGTKIKRT-KGRCPICRKKIMHVKRIYTA
>Brachypodium_distachyon_gnl|BL_ORD_ID|17609 _1g19510.1|PACid:21820379

M---------------------MVPWGGVGCCLSAAALYLLGRSSGRDAEVLRSVTRTGS
L-----------------------------------------------------------
--------------------------KDLAAILDTA-SKVLPL----------------V
VAVSGRVSSD---TPLICQQS--GMRGVIVEEMAEQHFLKHNDAGSWIQD-SAVMLSVSK
E--------VPWYL---DDGT-GRVYVVG----ARAAAGLVL-------------TIASE
VFEESGRTLVRGTLDYLQGLKMLGVK----RTERVLPTGTSLTVVGEAIKDDVGTIRIQR
PHKG-PFYASPKSIDQLILNLGKWAKLYQLASMGFAAFGVFLLAKRALQHFLQKKRQHEL
NKRVRAA-----AAQRQAREAEGADGTSNGDPNSKKDQLVLEICVICLEQEYNAVFVPCG
HMCCCMNCSSHV----TN-CPLCRRRIDQAVRTFRH------------------------
---
>Brachypodium_distachyon_gnl|BL_ORD_ID|13589 _1g72800.1|PACid:21816359

MSARDRETVEALARVAAALDGAVLGLGTAALAVVSLAKYLAASGALRRIAEAPEVAIPDL
R-----------------------------------------------------------
--------------------------YSLLAGLGEGESRL-------------------A
V-VRGLVRSPPWGKFLIPPGSREHC--VVAKHTQTCLFGEWRGIFGWTFDLHALFFKSLK
EQTITSFRWVPFALVDPASASDKSTEMIHVKLDGAVQQSLPL-------------TTVYH
KLIPVEQNSYT----LFQTIVGNGYPIALLDEEKILPIGKEITAIGLCRVNN-QNVEITS
CPEI-PFFLSDLTKGEIEAELDSRARTLFWVTFALGTMSVGLLG-HAIYRFWEKVKQHRE
ARQAQQR-----FHQADDEDDTGENGSDDDFPGEMGD---GQLCVICLRKRRKAAFVPCG
HLVCCCNCAKRVELMNEPLCPVCRQDIQYMLRVYDS------------------------
---
>Brachypodium_distachyon_gnl|BL_ORD_ID|3019 _2g26290.1|PACid:21805789

M-------------------------G-------GSSSSRRRRDDYY--------PAPPL
H---------------HYSNYPPPPPP---PHHHHHPPPPPP--------PHHHHHHGPP
PPPPPHHGPSPSAAAYYYHHHHPPPPHAYHGPWHPAPQPPQPQRPALIGPPPEFVGHQQA
LKVKNDINLR---KDTI------------------------------------------R
L--------VP------DANDPDR-RLVSFTFDAVTDGSLTIYYFAKEGKDCSFSSVYPD
LQAPTKIPFQKGLDQKYVQPSGSGIDLGFFSLDELSDTTG---EVFPLVVYAEAC----P
SQEE------------GDDPVKSTRAQITLAVI-------------------E-KHNNDL
QVKVVKQILWIAGVRYELKEIFGIVNSTEADVPDADDDGMGKECVICLTEPRDTAVFPCR
HLCMCSECAQALRLQSNK-CPICRQPVEKLIEIKVRSSEP--------------------
---
>Brachypodium_distachyon_gnl|BL_ORD_ID|5932 _2g13150.1|PACid:21808702

M-------------------------GNTGSTGSSNPPRPPFDGRGHG------LPPP--
--------------------------------YYHRYPPWPPSAAAP-------------
--------------------------------------PPVPV--------PAQVERHRA
VAVHAGVNVK---GDTL------------------------------------------R
L--------VP------DD--DGRCLLLAFSFDADAPGSITVYFFAQEDDDHVLKATKEN
VLQPVKITFKEGQGQEFKQPSGTGINVSMFEESELTKVGED--GVFPVAFKVEVGISSNQ
ESE-------------REQDAEDSKSLVKFAVF-------------------VKKEKAEY
GVRVVQQIMWVNGTRYVLQEIYGIRNTTDKNVP-EDD--FGKECVVCLSEPRDTTVLPCR
HMCLCRECAQLLRFQTNK-CPICRQPVERLLEIEVDSNMLHQGDQ---------------
---
>Brachypodium_distachyon_gnl|BL_ORD_ID|12578 _1g67780.1|PACid:21815348

M-------------------------GNTGSNGGGGAPGHRRRGSGHGHGHHHQAPPPPQ
QPEVAPNRYVFAAATPYPPQYPNPNPPQYYPQYGNYYPPPPPSVQVPLPAPYDHHHRGAA
PPPNAAAGEFPPSV----HSHHYP---GWAGRYPYGLQPPMPT--------P-YVEHQKA
VTIRNDVNLK---KETL------------------------------------------R
I--------EP------DEGCPGR-FLVAFTFDATVAGSMIVYFFAKEELNCNLTAVKAD
LIKPVTVSFKEGLGQKFRQPSGTGIDFSAFEDSELLKQGGM--EVYPLAVKAETILSVDP
PSEG------------GDQKIKTPNSQITQAVF-------------------EKKESGDY
QVRVVSQILWVNGTRYELQEIYGIGNSVEGDGD-AND--PGKECVICLSEPRDTTVLPCR
HMCMCSECAKVLRYQTTR-CPICRQPVERLLEIKVNNKSEEQLQQPSQSPPLPPPPSLHQ
EEV
>Brassica_rapa_gnl|BL_ORD_ID|33068 _027667|PACid:22716578

MIHWG--------------------GVTCCLSAAALYLLGSSS--GRDAEVLKTVTRVNQ
LKELAQLLE-----LDSSKLLPFIVAVSGRVGSDTP-IKCEHS-GIRGVIVEETAEQHFL
KHNETGSWVQ---------DSA-LMLSMS---------KEVPWFL---DDGTS-------
RVNVVGARGATGFALTVGSEVFEE-SGRSLVRGTLDYLQGLK----MLGVKRIERVLPTG
MPLTIVGEAVKDDIGDLRIQKPERG-PFYVSPKSLDQLISNLGKWSRWYKYASMG----L
TVFGVFLITKHVIDHVL----------------ERRRHRELQKRVLDAAAKR---AEETE
GSNGAHESVSDS------------TKKEGAVPD--LCVICLEHNYNAVFVPCGHMCCCTA
CSSHL-----TSCPLCRRRIDQVVKTYRH
>Brassica_rapa_gnl|BL_ORD_ID|36378 _040424|PACid:22719888

MEPWS--------------------GL-CCIGAVALYLLSRRT--ARDVDFLKSVTRVDQ
LKDLE------------SAVLPSIVAVSGTVGSETP-IKCEHS-GILSVILQETAEQQFL
KRNWKFSWVQ---------DTA-LMLPVC---------KEVPWFL---DDGTG-------
RVIVEGARSGIGFELTVGGEVFEKPEASSLVRGTLDFLRGLE----MLGIRRIERVLPVG
TRLTVVGQTIKDGVGDVRIQKPDQG-PFYVSPIPLDHLISKVGKWSRRFKKASMG----L
AVVGVILISKPVIKYILVRTGDFL---------ERRQQRLLKKRVVDAAAKRKKLAAPKR
EERVTSKGLENG------------KSRDGDEHD--RCVVCLERKCDAAFVPCGHMCCCLT
CALKL---LGKPCPLCRKRGIRILKIYRN
>Brassica_rapa_gnl|BL_ORD_ID|30202 _007725|PACid:22713712

MISWS--------------------GFKCFIWAYLLYLLSRRTGGGGDVEFFDSVTKVDH
LKGLAELLE------EGREVRPLIVAVTGSVASATP-FKCQRS-EMLAVILEETEEIQFL
KRNWKFSWVQ---------DTASISLPIT---------KQVPWFL---EDGTG-------
RVNVSGAETALGFAFTVGSEVFEKPEASSLLPGALAYLQGLK----MLGVRRFEYVLPIG
TWLTVVGEAVKDGSGNVRIQKPDQG-PFYISPKPLDQLIPTLGTWSRIFKYASMGASFCF
TVRGVIITSKPLIIYILHVIEDILFMFGYILWRMRQGLPILKKHV--TLLKRVFCAAANR
TRQATEEGLCESFFPEYACEFALIISLAPDVPD--LCVICLDRKCDAVFLECGHMCCCLT
CSLSLEL-QGKRCPLCRKPV-VVLKIYRI
>Brassica_rapa_gnl|BL_ORD_ID|14784 _037967|PACid:22698294

MSSPDRSAVFPLLIDIALSFDGAILGVTLALGAVRAAFKYAST--SAALNKIKDAPEVS-
VSDLRSLIPASDDQSETSGEQERIVVVRGTVKAKVTGGEGSNKQNNNVLISQETGDKALI
IHRSQTYVYSGWKTLFQLTNGHRFLLERSLPKQGADFMRMVPFVI---VDNTQPSQSSFV
VVNMDGARQP--LPLTTVYNRLQ-PINSS----PYAFLQALFFPEYPVGLIDVEKILPPG
RDLTAVGICSFNN-GVPEIKSCQDL-PYFLSEMTKDKMILDLAETTSVIFWGGI------
-IMG--CLSAGILGFAAAR--------AWNRWKQRHHEREQQQRP--------------D
EQRPEQPMVADE-----------T-EDEDEIPDGALCVICVTRRRVPAFIPCGHVVCCRQ
CASTVEREVNPKCPVCLQSIRGSMRVYYS
>Brassica_rapa_gnl|BL_ORD_ID|38557 _030900|PACid:22722067

MSSPDR-AVLSLLTDIFLSFDGAILGVTLAFGAVRAASKYAST--SAALNKIKDSPEVS-
VCDLRSLIPPSD--GESSHANQRIVVVRGTVEPKVT-GDGSHK-NNNVLISQETGEKALI
IHRTQTYMYSGWKTLFHLSSGHRFLLERSLPKQGAGFMRMVPFVI---VDKNQWSQSSFL
VVNMDGARQP--LPLTTVYNRLQ-PINSS----PYSFLQALFFPEFPVGMLDVEKILPPG
RDLTAVGICSLNN-GVPEIKSCQDL-PYFLSDMTKDKMIMDLTETTSVLFWGGV------
-ILG--CLSVGILGFAAVR--------AWNRWKLR---RELLQR----------------
--RPDQHMVDDE-----------TEEDADEIPDGELCVICVTRRRIPAFIPCGHVVCCRY
CALTVERGLNPKCPVCLQSIRGSMRIYYS
>Citrus_clementina_gnl|BL_ORD_ID|12827 _0.9_003846m|PACid:19263951

MALKNYMSQLIVVICSCLLATASSLNFSFPAVFNFGDSNSDTGGLAAGVAFPVGPPNGQT
YFHEPSGRFCDGRVVIDFLTAVDAMDHPFLNPYLDSVGAPSFQTGCNFATGGATILPANA
GARNPFSFNIQVAQFARFKARVLQLLAEEDYFKQGLYMLDVGQNDLDGAFNSKTEDQVMA
FIPTILSQFEAGIQRLYNEGARNFWIHNTGPLGCIARIIATFGTDSSKLDQVGCVRSHNS
AANNFNLRLHDLCTNFQDQFPDVNVTYVDIFSVKLDLIANYSQYGFKEPLAACCGYGGPP
LNFDNRVACGETKNLSGSTVSATPCNNTAEYVNWDGNHYTEALFGIEGFDRGKLKMIPWG
GISCC---------LSGAAL-YLLGRS------------SGRDAELLKTVTRVNQLKELA
HLLD-SGSKVLP-----FIVTVCGRV----GSETPISCEYSGLRGVIVEETAEQHFLKHN
----------DAGSWIQDSALMLSMS---------KEVPWYL--------DDGTG-RAFV
VGARGATGFVLTVGSEVFEESGRSLVRGTLDYLQGLK-MLGVKRIERLLPTGTSLTVVGE
AVKDDIGTVRIQRPHKG-PFYVSPKTIDELIENLGKWARWYKYAS--FGLTIFGTFLIAK
RAIHYILQRKRRWELHRRVLAAAAVKRSEQDNEGTNGQAENGSDGTQRDR-VMPDLCVIC
LEQEYNAVFVPCGHMCCCIICSSHL-----TNCPLCRRRIDQVVRTFRH
>Citrus_clementina_gnl|BL_ORD_ID|13924 _0.9_014777m|PACid:19265048

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------ISWG
GISCC---------LSGAAL-YLLGRS------------SGRDAELLKTVTRVNQLEELA
HLLD-GGSKVLP-----SIVSVSGRV----GSETPISCEYSGLRGVIVEETTERHFLKHN
----------DAGSWIQDSALMLSMS---------KEVPWYL--------DDGTG-CVFV
VGARGATGFALTVGSEVFEESGRSLVHGTLDYLQGLK-MLGVKRIGRLLPTGTSLTVVGE
AVKDDIGTVRIQRPHKG-PFYVSPKTIDELLENLGKWARWYKYAS--FGLTIFGAFLIAK
RVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNGQAENGSDSTQRDR-VMPDLCVIC
LEQEYNAVFFPCGHLCCCLICSSRL-----TNCPLCRRRIDQVVRTFRH
>Citrus_clementina_gnl|BL_ORD_ID|13925 _0.9_019918m|PACid:19265049

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------RSFLRQS
RVSI------NSRSW-----------------------------------DDGTG-CVFV
VGARGATGFALTVGSEVFEESGRSLVHGTLDYLQGLK-MLGVKRIGRLLPTGTSLTVVGE
AVKDDIGTVRIQRPHKG-PFYVSPKTIDELLENLGKWARWYKYAS--FGLTIFGAFLIAK
RVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNGQAENGSDSTQRDR-VMPDLCVIC
LEQEYNAVFFPCGHLCCCLICSSRL-----TNCPLCRRRIDQVVRTFRH
>Citrus_clementina_gnl|BL_ORD_ID|23563 _0.9_012472m|PACid:19274709

MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------LLEQH
LASLYQLAVSFDGAVLGVALAYTAVRSFLDFRYTSNALGKVRNAPQLKVS-------DLR
ALLDEKQSQPSDQEQNSRLVIVRGQVEAKSAVDGINWKTLMYSNDILVSESGDKAVILEQ
RKAFLYNEWRDLFGWTPDIRAIFGRSLKTSEPSSLRTVPFILVEGDRWPQSD----YIIV
NMDGSRQPLPLTTAYQRLELANVSPF-TFLQAMFGLKCPIGVLAEEKILPLGKDISAVGI
CSFKN-GIPEIKSCKDL-PYFLSEKTKDLMVVDLVNRSKILFWSGIVLGSLSIGILGYA-
-----IVRNWNRWKDRQQRMSRQLTEAPSDDADSQIGSDEDVAGDIPDGQ-----LCVVC
LTRRRISAFNPCGHLVCCRRCAISVEREASPKCPVCRMTVRSSMRIYFS
>Carica_papaya_gnl|BL_ORD_ID|23657 _evm.model.supercontig_9.121|PACid:16428004

MIP-------------WGGITCCMSAAALYLLGRSSGR---DADILRKVTRVNQLK--EL
AQLLDI---------ESKIMPLIVAISGRVGS--ETPISCEYSGLR-------------G
VIVEETAE-----------------------------------QHFLKHNDAGS-WIQDS
ALML---------SMSKEVPW--------YL--DDG---TARVFV-----------VGAR
GAT-GFVLTVGSE---------VFEESGRSLVRGTLDYLQGLKMLGVKRIERV-------
------LPTGTSLTVV--------GEMTLEQFR---YEDRTNGLFTCLQINGSPD-----
----FQLGKWARWYKYASMGLTFLGVFLIAKRS----------------------IEYVL
ERRRRRELQKRVLAAAAKRSGQDNEG---SNIIPENGLDGA---------------KREH
LMPD--LCVICLEQEYNAAFVPCGHMCCCMTCSSHL-----TNCPLCRRRIEQVLRT---
---------------------------------FRH
>Carica_papaya_gnl|BL_ORD_ID|10657 _evm.model.supercontig_25.125|PACid:16414718

MSSPEQALASLVSHLALSLDGAVLGVALAYAAVRSFFKFTANSAALRKIRSAPQLRVSDL
RSLLPVSSEDQSQPSDSDPSSTLVIVRGTVEA--KSAVDGSWKGLRHNNVLVSQESGDKA
VVIQRTQT-----------------------------------YIYNEWKGFFG-WTSDL
RAIFGRSWGKQESASSRMVP---------FVLVEDGRWPQSDYVI-----------VNTE
GSLHPLPLTTVYH---------QLQPVNASPYTFLQALFGHEYPVGLLNEEKI-------
------LPLGKDISAV--------GICSFKNGIPEIMSCKDLPY---FLSDLTKDQMLLD
LAFRTKILFWS---GIILGSLSISILGYAALRN----------------------WNRWK
ERRQQRQA---------------HQPSHAASIDANSELTGE---------------EEIG
DIPDGQLCVICLMRRRVPAFIPCGHIACCQPCALSVERELTPKCPVCRQEIRGSMRV---
---------------------------------FYA
>Carica_papaya_gnl|BL_ORD_ID|2071 _evm.model.supercontig_112.25|PACid:16405924

MLYGFYGAPPL-------------------------------------------------
------------------------------------------------------------
-------------------------------------------DFEISWNE---------
-------------THNASLPFDFHKEWMFFLNNDSE--VNISYNV-----------ISPR
SSTLFLVIARGKESLAEWINDPSYPSSILSWNIITG---SGEIQQEISTTYDYYIAVANS
NYEEVKVQLKFTVKAVIYNISQAHYRCSLSNKLCS-LKLRFLGANTAVLTSPAPKEGTLD
DYWYVKVSYTPRWLSYFLGSGMMVIITLLAFKF----------------------CDIFQ
PTNGQRGTEIRPEQAPLLLHKDDDVSSRGSSYDSVSHDEEDVEDIFKMNSVEERALKEGE
NVNLKRQCVICFNASRDCFFLPCGHCAACFSCGRRIAEDHAGTCPICRRKIKKVRKI---
---------------------------------FEV
>Carica_papaya_gnl|BL_ORD_ID|16613 _evm.model.supercontig_48.20|PACid:16420840

MGH-------------------------------------------------------SL
SKFRRRHHNHHNSPLPSIPENPIPSNSSSSTNPTAVSMTSSSINIANTRYGSPQNNPIRP
ILANASSSLSPETQTPPSSSYNTHINSSLNYAPPVGGYSSYRPYHDHQPRRGIPSQQQTV
LPVI---------A----PPP--------YVDHNSTKKINSNVNVHKDTITLVLDENNLD
CHLVSFTFDALVDGS---------------------------------------------
--------------ITILYFAKEDTDCMLTPLYPEIYTPRRIPFHKGLGQKFSQPSGTGI
DLGFFELDDLS---KPFPKEDSFPLVIFAETCFPLNVG------LDQSPRTNAQITEAVI
EKNNEGQFQVKVIKQILWIDEVRYEL---HEIYGIGNPKEA---------------DP-S
DSDTGKECVICLAEPKDTAVLPCRHMCMCSKCAKEL-RLLSKKCPICRQPIQELIEIKVM
EGEKGESI-------------FHIGLSSSIHSSHFK
>Carica_papaya_gnl|BL_ORD_ID|6122 _evm.model.supercontig_16.23|PACid:16410055

MVG---------------------------------------------------------
------------------------------------------------------------
-------------------RFNYH-------------------YHQHQNPYYANGWSPIR
PPVI---------GQVQPPPP--------YVDHQNAKKVRNDVNVHKDTLRLKIDEQHPD
QHLVSFVFDAMFDGRSVGFGESESRPLLTGWIMVAKNIIDGIMNKDFKAFRILGHDLHME
FCSIPKFCLPVSLFITIFYFAKEESDCRFVPLFPEAFMPVRIPFQKGLGQKFCQPSGTGI
DLGFFELDDLS---KSSAEEDVFPLVICAETRVSPRLADENLDELVSNASAHMQVTQAVL
EKNNNDSFKVQVIRQILWVDGVRYEL---REIYGIGSSATA---------------EGFD
DSDPGKECVICMSEPKDTAVLPCRHMCMCSDCAKAL-RVQSNKCPICRQPIEELIEIKPK
GEAEREYLPWKLAFRNTNQESSKLGLCVERISTLKR
>Mulan_NP_078820
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------ESGGRPSLCQFILLGTTSVVTAALYSVYRQKARVSQELKG
AKKVHLGEDLKSILSEAPGKCVP--------------------------------YAVIE
GAVRSVKETLNSQFVENC------------------------------------------
----------KGVIQRLTLQEHKMVWNRTTHLWNDCSKIIHQRTNTVPFDLVPHEDGVDV
AV----------------------------RVLKPLDSVDLGLETVYEKFHPSIQSFTDV
IGHYISGE---RPKGIQETEEMLKVGATLTGVG---------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------ELVLDNNSVRLQPPKQGMQ------YYLSSQDFDSLLQRQE
SSVRLWKVLALVFGFATCATLFFILRKQ-YLQRQERLRLKQM----------QEEFQEHE
A------QLLSRAKPEDRESLKSACVVCLSSFKSCVFL--ECGHVCSCTECYRALPE--P
KKCPICRQAITRVIPL--------------YNS
>Capsella_rubella_gnl|BL_ORD_ID|21378 _v10020547m|PACid:20907165

M-----------------------------------------------------------
---------------MHLA--------GFTCCLGGVA-----------------------
-------------------LYLLSRSTGRVVESINRVCHL---KDLEQLVDG--------
---ESKVFPLVIVSGTVGS--ETPIKCEYSDVLGVFVKKTAEQQVLRRNWRF---SW---
VRDRTFMQPMTKEVPW-YLDDGTGRVNVAV----SQGE----IGLALTVGSD-VFEKSVP
VSLVQGALS---------YLKGLQILG--VRRIEHVVPIGTPLTVVGEAVKDGMGNVRIQ
KPEQG-PFYVSYIPLDQLISKLGECSRKFKYASMGLTVLGVILLSKPVIRYILKRIEDYL
ERRRRQLLLNRVADAAARRAEPVAPRRA------------EPVTRGLERQHENSSDGTSR
YGDTPD--LCVICLDRKYNAAFVQCGHMCCCVRCSSQLS-----TCPLCREPIEQVLRIY
RH
>Capsella_rubella_gnl|BL_ORD_ID|1198 _v10019584m|PACid:20886816

M-----------------------------------------------------------
---------------IQLG--------GLACCLSGSF-----------------------
-------------------LDYLSKIPASFVKSVTRVRHI---KDLEQLVPL--------
---ESKV---VAVSGIVGS--ETPLKCKHSDMLCVFIEETAQQLFLKRNWMF---SW---
VPDCNWMVPITKEVPW-YLDDGTGRVNVEA----NKVR-----CFELKVGSK-VFQESEP
SSECH---------------RGLEMLG--VLRTERVLPIGTSVTIIGEAVKDSIGGFTIQ
ESKEV-PFFVSSLPFDELISSFGKWSRKLKYASIGFTVVGVVLILKPVVDYM-------L
ERRRRRLLRKRVADAAV--------KRA------------KLVTRGLEAQD---------
-GDLLD--LCVICLEHKNDAAFVRCGHMCCCSICSLHVK-----TCPLCRRPIEQVLRIY
RL
>Capsella_rubella_gnl|BL_ORD_ID|3556 _v10009435m|PACid:20889189

MSSPERA-----------------------------------------------------
----------VLNLLTDLALSFDGAILGLTLAISAVS-----------------------
-------------------SALKYASTNAALKKIKDAPEVSV-ADLRSLLPASEEKSETN
DQGTSHDQRIVVVRGVVKP--KFSGDESQKNNVLISPETGDKALIIQRTQTYVYSGWKRL
FQSTGYRFMLERSMPK-QGADFMRKVPFVIVGKDQQSQ-----SSYLLVNMD-GSRQPLP
LTTVYNRLQPINSSFLQAFLFPEYPVG--LLDVEKILPPGKDITAVGICSFRN-GVPEIK
SSQDL-PYFLSEMTKDKMIEDLIDQTSAIFFGTVFLGIVSVGILSYAAV-----------
RTWNKWKLWNRQRELPR--------RPN----------------EPVADDEPEDA-----
-DEIPDGQLCVICVTRRRVPAFIPCGHVVCCRLCASTVERELNPKCPVCLQSIRGSMRVY
YS
>Capsella_rubella_gnl|BL_ORD_ID|22605 _v10001505m|PACid:20908404

M-----------------------------------------------------------
----------------------------------------------------------LY
GLKQSPQLDVPAKWSEVHYLAVPNDSYKYWIQYLNKGSRVKVSYNVESVGSS--------
-------LYLVIAQGVDGL-----------------------------------SEW---
VQDPT---RPETTLSW-HIISDSGFIEQDI----TKSS-----TYYVAVGNV-YLNEVKA
TIDIQVEGILYDTT--NAYYNCSFPNDKCTLSVPLFG--TNAAVLTSPG-----------
------PKLNNS--KNEFCAKLSYEPRWIAY-MVCMGVVTALLLIVSSL-----------
FNKRQAVSEDEIVDENDDVAPLIPGKDDDNSSWCSSYSSILTSTEELEGAHGEGH-----
-SSTRY--LCAICYDAPRDCFFLSCGHCVACFQCGTRIA-ETSGFCPVCRRKIRKVKKIF
NV
>Capsella_rubella_gnl|BL_ORD_ID|18519 _v10023281m|PACid:20904273

MDSALLASSPDLESPPPVLISTSSSSNNVERADGAHHGVFNWREFFYSSCRNVSESNVIC
FLLGLYLLSFALFILIETTYAPKNVWLGPNSSILVESSSIFVNSIKVTELDYSNPGLQLY
GFYGSPPLDCVVNWSESRVLPVPHHSNKGWSYYFNQGTFMNISYRVKPQGSA--------
-------VHLVVDEGSRGI-----------------------------------SNS---
FWDAP---TYHNKFWWSNLIEGSGMVELEI----SKSS-----SYYLAVANLNNMREVEV
ELTIDVRAALYDTK--QSLYNCTFSNGECTLKLNALSPVGNSVVITSPA-----------
------PGHQGVSIEDEWYIRLSYEPNVIGY-VIFTGLGISFMLVAIRF-----------
CNRLQCGGEVRHLTEN-------VSSDD-------SFTNDDADLEELMGSNGETS-----
-NRTRC--LCAICFDTPRDCFFLPCGHCVSCYQCGTKMA-EAAGSCPICRRKMKKVKRIY
TV
>Cucumis_sativus_gnl|BL_ORD_ID|5673 _084910.1|PACid:16956611

MLPWGG------------ISCCLSAAAL-YLLGRSSGRDA------ELLKSVTRV-----
------NQLKELAQLLEAE--HLLPLVVAISGRVSSDTPIN-------------------
-----------------CEF-SGLRGVIVEETAEQHFLKHNDA---------------GS
WIQDSALM--------------LSMS---------KEVPWYL---DDGTGRAF-VLGARN
A-TNFILPVVSEV-----FEESGRSLMRGTLDYLQG----LKMLGVK----RIERVLPTG
TSLTVVGEAAKDDIGTIRIQRPHKG-PFYVS------PKTIDQLISNLGKWARWYKYASM
GLSIFGLYLVTKHVILYLME-R--------RRRWELQKRVLAAAAKRSSQENEGE--IEK
ASNGTDGTKRDRSM------------------------PDLCVICLERDYNAVFVPCGHM
CCCVACCSHL-----TNCPLCRRRIELVVKT---FR-H
>Cucumis_sativus_gnl|BL_ORD_ID|29614 _360260.1|PACid:16980714

MSTSEQALVTLLSRFALSFDGAVLGAALAYATVRTVLKLTASCSALNELRKAPYVTVSDL
R-----HIVSDGVSEQSESDRKL----VVVRGTVETRSSVEGNRKSLQPNVLI-------
-----------------SQE-SGDRAVIIQRTQVCIFNEWKGF---------------FG
WTSDLRAI--------------FGRTFRKQESTSFRTVPFVLLEGHSTYSDFVVVNMEGS
R-HPLPLTTVY---------HQLQPVCATPYTFLQAVFGHEYPVGVL----DEEKILPLG
KNISAVGICSFENG--VPVIKSCSDFPHFLC------EMTKDQMILDLVFKTKFLFWSSI
---VLGS---LTVGILGYSAARNWNRWKQWRQHRQLQNSRNDSPTSQLDSSNDIPIYGDF
ASDDEAATVPDDELSSHVPDDELSSHVPDDELSSHVPDGQLCVICLMRRKRSAFIPCGHL
VCCERCAVSVERESSPKCPICRQQIRSSVRI---YD-S
>Cucumis_sativus_gnl|BL_ORD_ID|21149 _253990.2|PACid:16972178

M-----------------------------GISWSNRRRN------NYLQNPPPPPPPPY
LSSSSFYYPSEPQSLSPAPPPPPPPPPL----QTHQFTNSHPPPPHSHPYSSTSQTLPLP
PIPHPPPPAPAPHSYYFSGG-YNS-------------CNYGNSSMGRFNFYPYYANQSNG
WSQVRPPMGPPLLPPPPLPIVEHRQA---------KKVRNDVNVHKDTLKIEVDEQNPDH
HLVSFVFDALYDGSITILFFAKEEPNCRFVPVYPDA----FKPVKIPFQKGPAQKFFQPV
GTGFDLGFFDLDDL--SKPSPAEDTFPLVISAETCSPSQSDDERIGEPHRDNSHMQITQA
---VLEK---KNGGPFQVRV---------------IRQLLWIDGVRYELREIFGI--GSS
SAEGFD----DNDT------------------------GKECVICMTEPKDTAVLPCRHL
CMCSECAKEL-RLQSNKCPICRQPIEELIEIRINNSDQ
>Citrus_sinensis_gnl|BL_ORD_ID|2126 _1.1g019194m|PACid:18093191

MIPWGGISCC---------LSGAALYLLGRSSGRDAELLKTVTRVNQLKEL--AHLL-DS
GSKVLPFIVTVCGRVGS--ETPISCEYSGLRGVIVEETAEQHFLKHNDAGS-WIQDSALM
LSMSKEVPWYL---DDGTGRAF-VVGARGATGFVLTVGSEVFEESGRSLVRGTLDYLQGL
KMLGVKRIERLLPTGTSLTVVGEAVKDDIGTVRIQRPHKG-PFYVSPKTIDELIENLGKW
ARWYKYAS--FGLTIFGTFLIAKRAIHYILQRKRRWELHRRVLAAAAVKRSEQDNEGTNG
QAENGSDGTQRDR-VMPDLCVICLEQEYNAVFVPCGHMCCCIICSWHL---TNCPLCRRR
IDQVVRTFRH
>Citrus_sinensis_gnl|BL_ORD_ID|2039 _1.1g019204m|PACid:18093103

MISWGGISCC---------LSGAALYLLGRSSGRDAELLKTVTRVNQLEEL--AHLL-DG
GSKVLPSIVSVSGRVGS--ETPISCEYSGLRGVIVEETTERHFLKHNDAGS-WIQDSALM
LSMSKEVPWYL---DDGTGCVF-VVGARGATGFALTVGSEVFEESGRSLVHGTLDYLQGL
KMLGVKRIGRLLPTGTSLTVVGEAVKDDIGTVRIQRPHKG-PFYVSPKTIDELLENLGKW
ARWYKYAS--FGLTIFGAFLIAKRVIRCILQRKRRWELRRRVLAAAAVQRSEQDNEGTNG
QAENGSDSTQRDR-VMPDLCVICLEQEYNAVFFPCGHLCCCLICSSRL---TNCPLCRRR
IDQVVRTFRH
>Eucalyptus_grandis_gnl|BL_ORD_ID|29270 _H01525.4|PACid:23590991

MGEIRTLSSFECKYNHVDRLIKGMASEITTLRTKVKEHREAWVKRPLVGRASRDTLSLST
RPVPHILTSPLIVSDSSPPPYPSIVSCSRPSSSCSCPSSIPATSVPLRSGELVLAGHALV
AFRAPFGGGGLISVGGPRASVSCSWSARGSRSLPHMIPWGGLSCCLSAAALYVLGRSSGR
DAEALKCVFRVNQLKELAQLL-DTECKVLPLVVTLCGRVGSDTPIN-------------C
EY-SGLRGVIVEETAEQHFLKHNDAGS-WIQDSALMLSMS---------KEVPWYL---D
DGTGRAY-VLGARGASG--FELNIASEVFEESGRSLVRGTLDYLQGLKMLGVKRIERLLP
VGSSLTVVGEAVKDDIGTVRIQRPHKG-PFYVSPKTIDQLISNLGKWARWYRYASYGFTV
FGICLIAKRAIQYIMERKRRWELQRRVLAAVARRSEQDTE-GTDDKTKNAPDSAKRDR-S
MPDLCVICLEQEYNSVFVPCGHMCSCTTCSLQL-----TNCPLCRRRIEQAVKTFRH
>Eucalyptus_grandis_gnl|BL_ORD_ID|23965 _F04419.1|PACid:23585686

M------SSHE-------------------------------------------------
--------------------------------------------------------QAIV
SLLSNFA----LSFDGAVLGLTLAYAA--VRTIVKLT--------SSSSALRKLQDAPSV
RVSDLRSVLSLEGGSDSEPDS-SSRSGREDLVIVR-GLVEAKSAVEGGTWKSLRQNVLVS
QD-SGDRAVIVQRTQTCIYNEWKGFFG-WTSDLRAILSRSLRERKSSSLRTVPFVLIDGS
QWPAVDY-VVVNMDGSKHHLPLTTVYHQLQPINASPYTFLQALFGHEYPVGLLDEEKILP
IGKDVSAVGLCFLKN-GILEIKSCKDL-PYFLTEMTKDQMVIDLAFRTKILFWSS---IF
LGSASIGILGFAFVRNWNRWKEWRQR------RRDEQQSHAAVDEATAHIAEDELGDA-P
DGQLCVICLMRRRRSAFVPCGHLVCCQRCALSVEREVSPKCPVCRQTITNSVRIYDS
>Glycine_max_gnl|BL_ORD_ID|26571 _10g02920.1|PACid:16278382

MIPW--------GGLSCC---------LSAAALYLLGRSSGRDAEI--LKSVTRVNQLKE
LAQLLD---AEI-----LPLIVTISGRVSSETPIN------------CEF-SGLRGVIVE
ETAEQHFLKHNDAGS-WIQDSALMLSMS---------KEVPWYL---DDGTD-RVH----
-VVGARGAS--GFALPVGIEAFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPVGTSLTV
VGEAAKDDVGAIRIQRPHKG-PFYVSPKTIDQLIANLGKWARWYKYASVGLTVFGAYLIA
KHAIRYILERRRRSELQRRVLAAAAKKSGQNNDVEKADSLSDGAKKDR-LMPD-----LC
VICLEQEYNAVFVPCGHMCCCTACSSHL-----TNCPLCRRQIEKVVKTFRH
>Glycine_max_gnl|BL_ORD_ID|4091 _02g16860.1|PACid:16248331

MIPW--------GGLSCC---------LSAAALYLLGRSSGRDAEI--LKSVTRVNQLKE
LAQLLD---AEI-----LPLIVTISGRVSSETPIN------------CEF-SGLRGVIVE
ETAEQHFLKHNDAGS-WIQDSALMLSMS---------KEVPWYL---DDGTD-RVH----
-VVGARGAA--GFALPVGSEAFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPVGTSLTV
VGEAAKDDVGAFRIQRPHKG-PFYVSPKTIDQLIANLGKWARWYKYASMGLTVFGAYLIA
KHAIRYILERRRRSELQRRVLAAAAKKSGQNNDVEKADGLSDGVKKDR-LMPD-----LC
VICLEQEYNAVFVPCGHMCCCTTCSSHL-----TNCPLCRRQIEKVVKTFRH
>Glycine_max_gnl|BL_ORD_ID|43458 _16g01030.1|PACid:16301042

MSHQEQAVLSLLSKLALSFDGAVLGVALAFAAVRTLFKFTATSASLRKLRRAPSISV-SD
LRSLLAEPPSDAD----AGEIVIIRGTVDAKSAVD-GTWKTLKPGVLVSRESGDKGVILQ
RTQTCIYNDWKGLLG-WTSDLRAICARSLRQQDSTSFRKVPFVL------IDVGRRPNAE
YVVVNMDGSRHPLPLTTVYHKLQPINASPYTFLQALFGHEYPVGLLDEEKILPLGKDITA
VGHCSLKN-GIAEIKSCKDI-PYFLSDLSKDQMIVDLSIKAKILFWGGI---SLG---SM
SVGVLGYAVLRNWIKWKRWKVQRQLQQQ--------RQAVSDAEPQVDDEIEDVPDGQLC
VICLMRRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRTYES
>Glycine_max_gnl|BL_ORD_ID|6360 _03g13060.1|PACid:16251643

MSHQEQAFVSLLSQLALSFDGAVLGLALAYAAVRTLFKFTATSAALRKLHRAPSVSV-SD
LRSLLAEIPSDADGNSDGGNIVIVRGTVDAKSTVEGGTWKTLRPGVLVSRESGDKSVILQ
RTQTCIYNEWKGLFG-WTSDLRAIFARSWRQQESTSLRKVPFVL------IDVGRWPNAE
YVVVNMDGSRHPLPLSTVYHKLQPITASPYTFLQALFGHEYPVGLLDEEKILPLGKNITA
VGLCSLKN-GIAEIKSCKDL-PYFLSDLSKDQMIVDLSSKTKILFWGGI---ALG---SM
SVGVLGYAVVRNWNKWKQWKQQRQLQQQ--------RQAVSDVEPQMDDEIEDVPDGQLC
VICLMRRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRIYES
>Glycine_max_gnl|BL_ORD_ID|49470 _18g27930.1|PACid:16309372

MSHQEQALVSLLSQLALSLDGAVLGFALAYAAVRTLFKFTATSSALRKLRRAPSLSV-SD
LRSLLAEIPSDGDGNSKGGIIVIVRGTVDAKSAVD-GTWKTLRPGVLVSRESGDKGVILQ
RTQTCIYNEWKGLFG-WTSDLRAIFARSWRQQESTSLRKVPFLL------TDVGRRPNAE
YVVVNMDGSRHPLPLTTVYHKLQPITASPYTFLQALFGHEYPVGLLDEEKILPLGKDITA
VGLCSLKN-GIAEIKSCKYL-PYFRSDLSKDQMIMDLSIKTKILFWGGI---ALG---SM
SVGVLGYAVVRNWNKWKQWKQQRQLQQQ--------RQAVSDVEPQMDDEIEDAPDGQLC
VICLMRRRRSVFIPCGHLVCCQGCAISVEREVAPKCPVCRQEIRDSVRIYES
>Linum_usitatissimum_gnl|BL_ORD_ID|42029 _10027994|PACid:23181209

MM------------VPWGGIGCCLSAAALYLLGRSSGRDAEALKSVTRVNQ---------
----------------------------LKELAKLFDVENNLL--P----LVVAISGRVG
S-ETPINCE-FSGLRGVIVEETAEQHFLKH-------NDAGSWIQDS---ALMLSMSKEV
PWYL--------DDGTD-RAFVLGARGASGFVLTVASEVFEESGRSLVRGTLDYLQGLKM
LGVKRIER----------------------------VLPTGTSLTVVGEAVKDDIGKVRI
QRPHKG-PFYVSPKNIDELIGNLGKWARL----------------------YKYASAGLT
VFGAFLIAKQAVEYIMERR--RRWDLHRKVLAAAAAKRSGNQDTESLNATAEDDSDGSKR
DRVPD--ICVICLENEYNAVFLPCGHMCCCTTCCSHL-----SSCPLCRRRIEQVVKTY-
----RH
>Linum_usitatissimum_gnl|BL_ORD_ID|34600 _10008163|PACid:23173780

MM------------VPWGGISCCLSAAAFYLLGRSSGRDAEALKSVTRVNQ---------
----------------------------LKELAKLFDVENSLL--P----LVVAISGRVG
S-ETPINCE-FSGLRGVIVEETAEQHFLKH-------NDAGSWIQDS---TLMLSMSKEV
PWYL--------DDGTD-RAFVLGARGASGFVLTLASEVFEESGRSLVRGTLDYLQGLKM
LGVKRIER----------------------------VLPTGTSLTVVGEAVKDDIGKVRI
QRPHKG-PFYVSPKNIDELIGNLGKWASL----------------------YKYASVGLT
VFGAFLIAKQAVEYIMERR--RRWDLHKKVLAAAAAKRSGSQDTEGSNATAEDDSDASKR
DCIPD--ICVICLENEYNAVFLPCGHMCCCTTCCSHL-----SSCPLCRRRIEQVVKTY-
----RH
>Linum_usitatissimum_gnl|BL_ORD_ID|1179 _10000533|PACid:23140359

MSSQDQALLSIVSQLALSFDGAVLGVALAYAAVRSFLKFAARSKALKKVRN---------
-----------------------APVLTVSDLRSLLDAP-------------SPPSHQDH
NLDLDLGASTISSQQLVILRGQVEAKSVVDGIWKSSLRPTLLVSHESGEKAVVIQRTQTV
PFVLLETGRWPQSEYVSVNMDGSRH----PLPLTTVYHQLQPIDASPYTFLQALFGHEYP
VGLLDEEK----------------------------ILPVGKEITAIGMCGSGN-GTPEI
TSCKDL-PYFLTEMSKDEMVLQLAFTTKV----------------------LMWSGI---
VLGS---VSVGILGYALRKNWNRWKEHRQ-------RRESEQSTSEMSQVDESDDD---V
GGVADGQLCVICLARRRRSAFIPCGHLVCCQYCAISVERDASPKCPLCRQLIRNSIRIF-
----DT
>Linum_usitatissimum_gnl|BL_ORD_ID|15586 _10034030|PACid:23154766

M-------------------------GISWSSSRRRQNHAFYHQQQHPPHLPPPPPPHYF
STEQTLLPPPPPPPNPIQGYYAAAPTTTVASPSTTTPQPSYAAPPP----PPQPPTHSYY
S-SHPYNSRGYSNQLAGRFNYQPYYYGNSSGGWP---APPHAVRPNAGPS------VQPV
PYVEHQNAKKVRNE-VNVHKDTLRL----ELDENNPDHHLLSF------VFDALVDGSIS
ISYFAKEEPNCKFVPAYPDVHMPVRVPFQKGVAQKFLQPSGTGID-LGFFELDD------
----------LSKPSFDEDVFPLVIVAETCPPVNSTGELDDSLSGPGSPGNMQITQA---
VLEK---KDCGPFSVKVIK--------QILWIEGV--RYELREIYGMRSSAAEDFD---D
TEPGK--ECVICMTEPKDTAVLPCRHMCMCSECAKEL-RIQSNKCPICRQPIEELIEIKV
KSGGDQ
>Malus_domestica_gnl|BL_ORD_ID|18124 _0000238779|PACid:22638098

M---------------LPWGG--LSCCLSGAALYLLGRSSGRDA--EILKSATRINQLKE
LAKLL---DSEFRLPVVVAVSGRVSSETPINCEFT-GLR-GVVVE---------ETAEQH
FLKHNDAG----------------S-WIQDSALMLSMSKEVPWYL---DDGTG---RVFV
VGARAATG--FVLPVASEVFE---------------ESGRSLVRGTLDYLQGLKMLGVKR
IERVLPTGTSMSVVGEAVKDDIGTIRIQRPQKG-PFYVSPKTIDQLIANLGKWARWYKYA
SVGLTVFGV-YLVAKHSIQYIIERKRRWEL---QKRVLAAAAKRSGEDGEGILLRDPITM
LFAIYAQKCTKRFYLFLPGSNEKDDGASDGNKRDRMMPDLCVICLEQDYNAVFVPCGHMC
CCTTCSLHLTS-----CPLCRRRIDQAVKTFRH
>Malus_domestica_gnl|BL_ORD_ID|53951 _0000219802|PACid:22673939

M---------------LPWGG--LSCCLSGAALYLLGRSSGRDA--EILKSATRINQLXE
LAKLL---DSEYVLPLVVAVSGRVSSETPISCEFT-GLR-GVVVE---------ETAEQH
FLKHNDAG----------------S-WIQDSALMLSMSKEVPWYL---DDGTG---RVFV
VGARAATG--FVLPVASEVFE---------------ESGRSLVRGTLDYLQGLKMLGVKR
IERVLPTGTSMSVVGEXVKDDIGTIRIQRPQKG-PFYVXPKTIDQLISNLGKWARWYKYA
SMGLTXFGV-YLVAKHSIQYFMERKRRKEL---QKRVLAAAAKRSGEDSEGILLSDPITI
LFAIXXRKCTKGLYVFLPGSNXKDDNASDGSKRDRMMPNLCVICLEQEYNAVFVPCGHMC
CCTTCSLHLTS-----CPLCRRRIDQAVKTFRH
>Malus_domestica_gnl|BL_ORD_ID|10112 _0000162279|PACid:22630085

M---------------LPWGG--LSCCLSGAALYLLGRSSGRDA--EILKSATRINQLXE
LAKLL---DSEYVLPLVVAVSGRVSSETPISCEFT-GLR-GVVVE---------ETAEQH
FLKHNDAG----------------S-WIQDSALMLSMSKEVPWYL---DDGTG---RVFV
VGARAATG--FVLPVASEVFE---------------ESGRSLVRGTLDYLQGLKMLGVKR
IERVLPTGTSMSVVGEXVKDDIGTIRIQRPQKG-PFYVCPKTIDQLISNLGKWARWYKYA
SMGLTMFGV-YLVAKHSIQYFMERKRRKEL---QKRVLAAAAKRSGEDSEGILLSDPITI
LFAIXXRKCTKGLYVFLPGSNXKDDNASDGSKRDRMMPNLCVICLEQEYNAVFVPCGHMC
CCTTCSLHLTS-----CPLCRRRIDQAVKTFRH
>Malus_domestica_gnl|BL_ORD_ID|27598 _0000757393|PACid:22647575

M---------------RIWEG--VWWCLGALALYLPGWRFSSDA--DVLESVPRINPMSE
LAKLL---EFR-RTPLVVGVSGTVCCENPIHCEFA-GLR-GVVVM---------QTAAQR
FLKRNEKG----------------E-WQMGYTSLLSECKEVPWYL---DDGTG---RVNV
VGATDASG--FTFPASSGQFEQSRRCHKCEMNRLECETKRSVERERIDDREGIKLLGVQR
TEHVLPIGISLSVVGEAVKDNVGTIRIQKPHKG-PFYVSTKSIDELIASHKNWARFLKCA
SFGVAVIGL-TLNAAELDKYIRERLRRSEWMRSRRRAAAVADIRSRQHNAGSSDTRAVAA
DYIRSQR-----------------DNAGERAAAAPDGANSCVICLEQQYNVVFIPCGHMC
CCTTCCSQLTE-----CPLCRQPFSQAVRTFRP
>Malus_domestica_gnl|BL_ORD_ID|47849 _0000215866|PACid:22667834

MSSDSNAIISLLSQLVLSWDGAVLGVALACAAMRSVLNFTASSSALRNLRQAPAVKV-SD
LRSIL---PLD-HSDKLVVVRGTVEAKSLVDGTWT-AFKSGVLVSKDRNDRAVILQSTKT
YIIHKWKGFIGFFNLRSIVWRYWRH-WKDSEEHESNLVRKVPFVL---VDGDQWPIRDMV
VVNVDGSSHPIPLTIAYHHLQ---------------PVNPSPFSFLKALFGTNYPIGVLT
VDKILPVGKEISAVGLCSLKN-GVSEIKFCNDL-PYFLSEMSKDEMVGDLASSTRMLFWT
AFVLGSMSIGVLSYAVVRNWNKWKVWR------QQRQLQQSSQAADSDAEAQIEEEDVP-
------------------------------------EGQLCVICLMRRRRSAFIPCGHRV
CCHPCSISIERDIAPKCPVCRQEIRTSLRVYDS
>Manihot_esculenta_gnl|BL_ORD_ID|26209 _4.1_011064m|PACid:17986177

M------------------------------LPWGGISCCLSAAALYLLGRSSGRDAEVL
KSVTRVNQL-----KELAKLLDIE-----------------------------SNISPSV
VSISGRVGSETPINCEYSGLRGVIVEETAEQHFLKHNDAGS-WIQDSALMLSMS------
---KEVPWYL--------DDGTD-RVYVVGARGASGFVLTVGSEVFEESGRSLVRGTLDY
LQGLKMLGV-----------------------------------KRIERVLPTGTSLTVV
GEAVKDDIGTVRVQRPHKG-PFYV------------SPRTIDELIGNLGKWARWYRYASV
SLTVFGAFLIAKHAIQYIMERRRRWELQSRV----LAAAAAKRQGQDSEGSNGKAENGSD
NSKRERPVPDLCVICLEQEYNAVFLPCGHMCCCTTCSSHL-----TNCPLCRRRIEQVVK
TF-----RH
>Manihot_esculenta_gnl|BL_ORD_ID|16192 _4.1_009144m|PACid:17976041

M-----------------SSHEQVLASLVSQLALSFDGAILGVALAYAAVRSFLKFTSNS
KALRKISKAPTLRVSDLRSVLDLPQPSDENQNQNVDQGQTQKLVIVRGQVEPKSAVDGNW
KSLRS--NALVSHEC---GDKAVIIQRTQTCIYNEWKGFFG-WTSDIRAIFGRSWREQES
TSLRMVPFVLVEGGRWPQSD----YVIVNIDGSRHALPLTTVYHQLQPIDASPYTFLQAL
FGHEYPVGL-----------------------------------LDEEKILPLGKEINAV
GICSSRN-GVLEIKSCKD-LPYFL------------SDMTKDQMVVDLAFKTKVLLWSGV
VLGSLSIGILGYAAVRN-WNRWKEWRQHRQ-----------SQQQNHAASTDDDPQIDAD
EEAGDVPDGQLCVICLMRRRRSAFIPCGHLVCCQLCAISVEREVSPKCPLCRQAVRNSMR
IF-----EC
>Manihot_esculenta_gnl|BL_ORD_ID|2107 _4.1_010107m|PACid:17961845

M---GISVSSNRRRNNTHYHHHPPPP------------------YYYS------------
--------------TEASSLPPPPLNYFPAPTQPTS---------YPPSHNPYPTPPPPI
-HIHSNHSSHPYHAS---------------RYPSRFSDRPYYYANQTNEWPVIRPNVGTG
QPIEPPPYI-------EHQNAKKVRNDVNVHKDTL---------KVEIDEQTPDNYLVSF
VFDALFDGSITIFYFAKEEVNCKFVPLFPEAHLPLRIPFQKGLGQKFRQPVGTGIDL---
GFFELDD-----LSKPSPGEDVFPLVIVAETCLPVDSTDEYDDSVQNTSGHMQI------
--------------TQAVLEKKNSDSFQVKVVKQILWIDGVRYELRELYGEGSSASEGFN
----ECDPGKECVICMSEPKDTAVLPCRHMCMCSECAKAL-RLQSNKCPICRQPIGELIE
IKINNG-GQ
>Manihot_esculenta_gnl|BL_ORD_ID|17562 _4.1_010168m|PACid:17977430

M---GISFSSHRRRNHTYYHHHPPP-------------------YYYS------------
--------------TEPLPLHPPPPPPPPPQNFFTT---------TPTGATQPPTPPPPA
PPIQSYYSSHPYHAC---------------SYANRFNYQPYYYAHQTNWWPAIRPNVDIG
QPIELAPYI-------EHQNAKKVRSDVNVHKDAL---------KVEIDEHNPDNYLVSF
VFDALLDGSITIFYFAKEEDNSRFVPLFPEAHLPVRIPFQKGLGQKFRQPSGTGIDL---
GFFELDD-----LSKPSPGEDVFPLVIVAETWLPVDSTDEH-DSVQNTTGQMQI------
--------------TQGVLEKRNSGTFQVRVVKQMLWIDGIRYELRELYGIGRSAAEGFN
----DCDPGKECVICMTEPKDTAALPCRHMCMCSECAKAL-RLQSNKCPICRQPIEELIE
IKINNG-DQ
>Manihot_esculenta_gnl|BL_ORD_ID|7502 _4.1_010565m|PACid:17967275

MGNIGSSGVHGRRRHGSRRSHPPTPPPAAPQPEITGNRYVFAAATPYP------------
--------------SQYPNPNPPPYYQYPGYYHP------------PPPAMPVPLPAP--
-------------------------------------YDHHHRVDPSHWVGGRYPCAPMM
AP--PLPYV-------EHQKAVTIRNDVNLKKESL---------RLEPDEENPGRFLVAF
TFDATVAGSITVMFFAKEGEDCTLTPMKENLLPPVTVTFQQGLGQKFRQPSGTGIDY---
SVFEERD-----LTKVGE-MDVYPLAVKAEASPPNQNEEEGNQISGITNS--QI------
--------------TQAVFEK-EKGEYQLRVAKQILWVNGMRYELQEIYGIGNSVEDAVD
----ANDPGKECVICLSEPRDTTVLPCRHMCMCSECAKVL-RFQTNRCPICRQPVERLLE
IKVNNGPDE
>Mimulus_guttatus_gnl|BL_ORD_ID|1784 _mgv1a009837m|PACid:17671176

M----------------------IPVGGITCCLSAAALYLLGRSSGRDADLLKSVTRVN-
-QLKDLAQLL-EAASKVLP------------------LVVTVSGRVGSETPINCEY-SGL
RG---VIVEQTAEQHFLKHNDAGS-WIQDSALML--------------------SMCKEV
PWYL--------DDGTS-RVHVVGARGAT-GLVLTVGSEVFEESGRSLVRGTLDY---LQ
GLKMLGV------KRIERVLPTGSPLT-VVGEAVKDDIGSIRIQRPHKG-PFYVTDKTID
QLIANLGKWSRLYKYASMGLTAFGVYLLAKHAFQYIMDRRRLWETRKRVLDAAAKKAGQN
EGALNGEAEIGSD-----------------SSNKER-----PIPELCVICLEQEYNSVFV
QCGHMCCCMACSSHL-----TNCPL---------------------H-------------
-
>Mimulus_guttatus_gnl|BL_ORD_ID|2783 _mgv1a007519m|PACid:17672175

MSLHDRALTAVLTQLAMAADGAFIGVG------VAYVAFSCFRKYAATSSALRKISQSAS
VQPSDLRSILSDSDDS-RPSSSRRDDGDASSLNFDCGKLVFVSGSVEVKSALDKANWKSL
RGTDLVVSHESGEKGVILQRIQTCIYNEWRGLFRWTADLGSMLMPRRITKENASSSMNMV
PFILVEEGKWPPSDHV-----VVNMEGSTHPLPLTTVYQHLQPVKASSYTVFQAL---VG
LEYPVGL------LYEEKILPLGKDIT-AVGICNLKN-GIPEIKSC-EDLPYFLSILTKD
QMIADLSFKSKVLLWSGL------ILGTVAIGVLGYSISRNWSKWKE---WKARRAQQQQ
N-----ASRIENL-----------------DETEEEESGDVPDGELCVVCLMRRRRSAFV
PCGHLVCCHRCAFSVEREVSPKCPVCRQPIRNSVRI--------YDS-------------
-
>Mimulus_guttatus_gnl|BL_ORD_ID|11446 _mgv1a026781m|PACid:17680841

L-----------------------------------------------------------
---------------------------------------------------IRPMSQTSG
QGP-PSAPPLQLPPPPLQRAKLIT--ND--------------------------------
----------------------VNVHKDTIRLQLDEFYPDCHLVSFTFDASVNGS---IT
IFYFAEE------GDECKFTPIHPEIN-PVKIQFRKGPGLKFCQPSGTGIDLGFFD----
--IDELSKASLGGFVYPL------VILAQS---------------STNNNAQITQAVLEK
KNGKIFHVKVIKQILWAGGVCYELHDIYGGSGTNRASVSDAESENECIICFAEDKNTVVL
PCRHMCMCGECAKDL-RLKSNKCPICRQPIQELMEINFTKGFIAFSTLVFAQIVKTLRTS
Y
>Mimulus_guttatus_gnl|BL_ORD_ID|20244 _mgv1a011000m|PACid:17689645

MP----------------------------------------------------------
-------------------------------------MPMPLPAPYDHHHAAAHANWANG
RYPYPMMPPAPAPAPYVEHQKAVTIRND--------------------------------
----------------------VNLKKETLRIDPDEENPGKHLVSFTFDATVAGSSFMLM
IIYNDSAGLHFSLGEDCCLTPTKENLHPPIVVQFEQGLAQKFKQPSGTGIDLSMFE----
--DGELSK-ELDMDVYPL------AVKAEASP-----DNQNESSDSGSTNSQITQAVFEK
DKGE-YQLRVVKQILWVNGMRYELQEIYGIGNSVEGEFDANDPGKECVICLSEPRDTTVL
PCRHMCMCSECAKVL-RFQTNRCPICRQPVERLLEIKVSSG---GDE-------------
-
>Mimulus_guttatus_gnl|BL_ORD_ID|23053 _mgv1a025350m|PACid:17692454

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------IT
IYYFAKE------ETNRRVVPLFPETYVPIKVPFRKGLHQEFRQPSGTGIDFRFFP----
--MEDLSHSPSRYEVFPI------VVSADTCPTPYIIDERSYLLSHTFRQMQITQVIVGK
NHEAQFTAKVIRQLLWTGDVCYELREIYGLGKS--------GPGKDCVVCMTEPKDIALL
PCRHMCMCSGCAKAL-RLQSNKCPICRETIEAVLEIKIDTMDFSHKP-------------
-
>Medicago_truncatula_gnl|BL_ORD_ID|7454 _Medtr1g111550.1|PACid:17439105

MAM-----------VPWRGVGCCLSAAALYLLGRT----SGRD-----VDILKSVNRVNQ
LRELAQLLDE---EIFPLVVAISGRVGS-ETP----------------------------
---ISCEF------------SGLRGVIIEETAEQH-FLKHSDAGSWIQD-----SALMQS
RS---------NEVP-WYL---DDGTG-RVR----VVGAQGATGFVLP--VGSEAFEESG
RLPVRGTSDYVQGLKMLGVKRIERVLPVGTSLTVVGEAAKDDVGTIRIQRPSKG-PFYVS
PKTIDELIANIGRWARWYKYASAGLTVLSVYMIANHAVR---YILERRRRNELEKRVLAA
AAKISGQDN--------GGEMDDSLSDGAKRER-AMPNLCVICLEQEYNSVFVPCGHMCC
CTACSSHL-----TSCPLCRRQIEKAVKT---FRH
>Medicago_truncatula_gnl|BL_ORD_ID|7431 _Medtr1g111340.1|PACid:17439082

MAM-----------VPWRGVGCCLSAAALYLLGRT----SGSSMFFWYVDILKSVNRVNQ
LRELAQLLDE---EIFPLVVAISGRVGS-ETP----------------------------
---ISCEF------------SGLRGVIIEETAEQH-FLKHSDAGSWIQD-----SALMQS
RS---------NEVP-WYL---DDGTG-RVR----VVGAQGATGFVLP--VGSEAFEESG
RLPVRGTSDYVQGLKMLGVKRIERVLPVGTSLTVVGEAAKDDVGTIRIQRPSKG-PFYVS
PKTIDELIANIGRWARWYKYASAGLTVLSVYMIANHAVR---YILERRRRNELEKRVLAA
AAKISGQDN--------GGEMDDSLSDGAKRER-AMPNLCVICLEQEYNSVFVPCGHMCC
CTACSSHL-----TSCPLCRRQIEKAVKT---FRH
>Medicago_truncatula_gnl|BL_ORD_ID|48043 _Medtr8g025010.1|PACid:17479694

MSSQEQALVSLLSQLALSFDGAVLGFAVAYVAVRSIRKFTLTSAALRKITAAPSVS-VSD
LRSLLTETDENSDE--GKIVIVRGTVDA-KNV----------------------------
---VDGSWKALWPGVLVSSESGDKGVVLQRTQTCI-YNEWKGLFGWTSD-----LRALFL
RSWRQQESTSLRKIP-FVL---ID-VG-RPSNPEYVVVNMDGSSHPLPLTTVYHRLQPVN
PPPYTFLQALFGHEYPVGLLDEEKILPLGKDVSAVGLCSLRN-GIAEIKACNDL-PYYLS
DLSKDQMIVDLSFKTKLLFWSGILLGSMSVGIIGYAVVRNWNKWKQWKQQRQLQQRRQQP
IEPVPPTDD----------EIED-VPDG---------QLCVICLMRRRRSVFIPCGHLVC
CQGCAISVESEVAPKCPVCRQEVRDSVRI---FES
>Medicago_truncatula_gnl|BL_ORD_ID|46007 _Medtr7g121420.1|PACid:17477658

MGN--------------------ISSTGAHNRRRH-----------------ATASRRTH
PPPPPPVTPQP--EIAPHQFVYPGAAPYPNPPMHYPQYHYPGYYPPPIPMPHHHHPHPHP
HPHMDPAWVSRYYPC---------GPVVNQPAP---FVEHQKAVTIRNDVNIKKETIVIS
PD---------EENPGFFLVSFTFDAAVSGSITIFFFAKEDEGCILTP--TKETHLAPVT
VQFQQGLG-----------QKFRQQAGTGINFSMFEESDLVKVGDVDVYP--LAVKADAS
SDNHDGSNETETSSKPNSQITQAVF---------------------EKEKGEFRVKVVKQ
ILSVNGMRYELQEIYGIGNSVESDVDDNEQG------KECVICLSEPRDTIVHPCRHMCM
CSGCAKVLRFQT-NRCPICRQPVERLLEIKVGTEE
>Medicago_truncatula_gnl|BL_ORD_ID|46008 _Medtr7g121420.2|PACid:17477659

MGN--------------------ISSTGAHNRRRH-----------------ATASRRTH
PPPPPPVTPQP--EIAPHQFVYPGAAPYPNPPMHYPQYHYPGYYPPPIPMPHHHHPHPHP
HPHMDPAWVSRYYPC---------GPVVNQPAP---FVEHQKAVTIRNDVNIKKETIVIS
PD---------EENPGFFLVSFTFDAAVSGSITIFFFAKEDEGCILTP--TKETHLAPVT
VQFQQGLG-----------QKFRQQAGT--------------------------VKADAS
SDNHDGSNETETSSKPNSQITQAVF---------------------EKEKGEFRVKVVKQ
ILSVNGMRYELQEIYGIGNSVESDVDDNEQG------KECVICLSEPRDTIVHPCRHMCM
CSGCAKVLRFQT-NRCPICRQPVERLLEIKVGTEE
>Oryza_sativa_gnl|BL_ORD_ID|18392 _LOC_Os07g45350.2|PACid:21900864

MLIPWGGVGC--------CLSAAALYLLGRSSGRDAEVLRSVARAGSTKDLAAILDTA-S
KVLPLVVAVSGRVGSDTPLICQQ--SGMRGVIVEETAEQHFLKHNDAGS-WIQDSAVMLS
VSKEVPWYL---DDGTG-RVFVVGARGAAGLVLTVASEVFEESGRTLVRGTLDYLQGLKM
LGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQRPHKG-PFYVSPKSIDQLIMNLGKWAK
LYQLASMGFAAFGVFLLAKRALQHFLERKRRHELQKRVHAAAAQR--QAREAEGGNGTSD
VDSNNKKDQLVLDICVICLEQEYNAVFVPCGHMCCCMNCSSHL---TNCPLCRRRIDQAV
RTFRH
>Oryza_sativa_gnl|BL_ORD_ID|18393 _LOC_Os07g45350.3|PACid:21900865

MLIPWGGVGC--------CLSAAALYLLGRSSGRDAEVLRSVARAGSTKDLAAILDTA-S
KVLPLVVAVSGRVGSDTPLICQQ--SGMRGVIVEETAEQHFLKHNDAGS-WIQDSAVMLS
VSKEVPWYL---DDGTG-RVFVVGARGAAGLVLTVASEVFEESGRTLVRGTLDYLQGLKM
LGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQRPHKG-PFYVSPKSIDQLIMNLGKWAK
LYQLASMGFAAFGVFLLAKRALQHFLERKRRHELQKR-----------------------
--------------CVLT-----NHLF---GFR---RTCYSHLHSSVVCSLC--------
-----
>Physcomitrella_patens_gnl|BL_ORD_ID|18940 _Pp1s175_124V6.1|PACid:18055475

MLSWGGITLC---------FSGAALYCLSRNTGRDALHLMSVERVNQLEDL-AKLLESAC
TVVPW-VVTVAGRVGAEAPIASEHSSLRGVILEKSAEQHFLKHNDTGS-WIQHSALMLSI
SKEVPWYL---EDGTS-RVFIIGARNAAGMDLTVASESFEEYGGSLVRGTLDYLQGLKML
GVKRVERVLPTGTNLTVVGEAVQDDRGLIRIQKPDKG-PFYVTPQSQDQLIENLGRWSRW
CQYMSFGL---TLVGIYFITSRAIKHMLERWRREALLTRVMEAAALRKALQQEGVDEESD
GVT-AFPHDDNAHTAQKKDGGMPSLCVICLEQDYNAVLVPCGHMCCCTSCSSQL---SLC
PLCRRHIDQVVKTFRH
>Physcomitrella_patens_gnl|BL_ORD_ID|11996 _Pp1s12_190V6.2|PACid:18048531

MLSWGGITLC---------LSGAALYCLSRNTGRDALNLRSIERVNQLKDL-AILLESAC
KVVPL-VVTVAGRVGSETPIACEHSSLRGVILEETAEQHFLKHNDTGS-WIQDSALMLSI
SKEVPWYL---EDGTG-RVYIVGARNAAGMELTVASEVFEESGRSLVRGTLDYLQGLKML
GVKRVERVLPTGTNLTVVGEAVQDDRGLIRIQKPNKG-PFYVTPKSLDQLVANLGRWSRW
YKYMSLGF---TIVGIYFITSHAIKHFMERRRREALHRRVMEAAALRQASQREGGDGDMG
DVT-SHPLDDSVDTSQKKDRGTPDLCVICLEQDYNAVFLPCGHMCCCTSCSAQL---TSC
PLCRRHIDKFVKTYRH
>Prunus_persica_gnl|BL_ORD_ID|4153 _ppa008230m|PACid:17644506

M------------LPWGGL-------SCCLSAAAL---------------YLLGRSSGRD
ADILKSATRIN-----QLKELAKLLD--------SECILPLVVAISGRVSSETPITCEFT
GLRGVV-----------------VEETAEQ------------------------------
------------HFLKHNDAGSWIQDSAL-MLSMS---------KEVPWYL---DDGTGR
-VHVVGA-RGATG----FVLPVASE---------VFEESGRSLVRGTLDYLQGLKMLGVK
RIERVLPTGTSLSVVGEAVKDDIGTIRIQRPHKG-PFYVSPKTI----------------
-------------------DQLIANLG--KWARWYKYAS--LGLTVFGV--YLVAKHSVQ
YILERRRRWELQRRVLAAAAKRSGEDNEG---SNEKDD----------------------
--------NVLDGSKRLMPDLCVICLEHEYNAVFVPCGHMCCCTTCSLHLT-----NCPL
CRRRIDQAVKT----FRH
>Prunus_persica_gnl|BL_ORD_ID|16287 _ppa006914m|PACid:17656817

MSSHEQ-------ALISLVSQLALSFDGAILGVAL--------------AYAAVRTVLKL
NSVSSALRKLHNAPSVQVSDLRSILSLDHSDESQPSDAKLVVVRGTVEA-KSAVDGNWNI
LNSGVL-----------------VSQGTKE--------------------RAVVLQRTQT
CVYNEW-----------KGFVGWPSDLRA-IFSRSWRERESKVFRTVPFIL---AEGGRR
PISEFVA-VDMDGSRHPLPLTTVYH---------HLHPVNPSPYTFLEALFGHRYPVGLL
DEEKILPLGKEISAVGLCSVKD-GVLEIKSCKDF-PYFLSEMSK----------------
-------------------DQMVVDLT--SRTKVLFWSGIFLGSVSIGVLAYAVSRNWNR
WKVWRQQR-ELQRSIRAS-------NAEAQIQEEEEEE----------------------
-----------DAGDVPDGQLCVICLMRRRRSAFIPCGHLVCCQLCSISIERDVAPKCPV
CRQQIRTSVRI----YDS
>Prunus_persica_gnl|BL_ORD_ID|2211 _ppa005117m|PACid:17642532

MENPEPDQGQHVSGPSSSS-------SSSSSSPSSSQVQDEENNRPQNGDDIY-NEQSQH
NHIEQQQQRISRTFTYHMNLLVSDVAASEMKDDVWSCLVVLVTFWFFASMTLILGFYGSA
NLK----LGPNCSLLIQPNPFFVQSIKAQELDEPKPGPMLYGFHKPPPLDVEVAWTET--
------HDTPVPANYHKEWIYFLNKGSRIDIFYRVKPT------SSLPLTLVVAQGSESM
AEWIEDPSYGNAT----LSWNIIYE--------------------------------SGK
IQQEIPKSSNYYIAVGNLNPED-VEVELEFNIKS-ALYNTTEAYYKCSLDNQLCSLKLSL
LGASAVVITSPGPKEGDPDDDWYIRLS--YGPR---WIMYFLGSGVMTVLLLMALRFCNV
FQNSGEDRIEFQ--------AGEAESERTPLLSPKDDDVLSWGSSYESVSNNEEDLEESL
EVSSLVGKSINEGDSNNTQRLCVICFDGPRDCFFLPCGHCAACFTCGTRIAEE-AGTCPI
CRRRMKKVRKI----FTV
>Prunus_persica_gnl|BL_ORD_ID|22971 _ppa008323m|PACid:17663590

MSIPPPLYAQQPRGPYPAY-------PLPLTPPPP----------PPQTHYCY-GHYSSC
NHANSAMGRFSYNYNYQPYYAANQAN-------GWPAIRPPV------------------
---GPVL----------PPPPHVEHQNAKK------------------------------
----------------------------------------------VKNDVNVHKDTLRL
EIDELNPDQHLVS----FVFDAMYDGSITVFYFAKEEPDCRFVPLFPEAFVPVRVPFQKG
SGQKFRQPSGTGIDLGFFELDD-LSKPSPGEDVF-PLVISAETF----------------
--------------PPHSTDEHIVEPTPDTSPRMQITQA--VLEKNNGD--HFQVRVIRQ
ILWIDEVRYELREIYGIASS----------------------------------------
--------TVEGFDDNDPGKECVICMTEPKDTAVLPCRHMCMCSDCAKELTLQ-SNKCPI
CRQPIEELIGIEINKSRQ
>Populus_trichocarpa_gnl|BL_ORD_ID|16447 _POPTR_0014s13410.1|PACid:18222628

MM----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------IPWGGISCCLSGA------------A
LYLLGRSSGRYLPSLIPLFFLIIS---------SKLLDIESKVLPL---VVAISGRVGAE
SPISCEF--------------SGLRGVIVEETAEQHFLKHND------------------
-----AGSWIQDSALMLSMS---------KEVPWYL---DDG-----TD-RVYVVGARGA
SGFVLTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGTSLTVVGEAVKDDIG
TVRIQRPHKG-PFYVSPKSID-------ELIGNLGKWARWYKYA-----SLGLTVFGAFL
ITKHVIRYIMER-RRRWELQSRYVS-------LV-------EGIHDKMFQGKGHANGAKR
ERPIPD--LCVICLEQEYNAVFLPCGHMCCCITCCSQL-----SNCPLCRRRIEQVVKTF
RH-
>Populus_trichocarpa_gnl|BL_ORD_ID|16448 _POPTR_0014s13410.2|PACid:18222629

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MLSMS---------KEVPWYL---DDG-----TD-RVYVVGARGA
SGFVLTVGSEVFEESGRSLVRGTLDYLQGLKMLGVKRIERVLPTGTSLTVVGEAVKDDIG
TVRIQRPHKG-PFYVSPKSID-------ELIGNLGKWARWYKYA-----SLGLTVFGAFL
ITKHVIRYIMER-RRRWELQSRVLA-------AAKRSGQDNEGSNDKAENG---SDGAKR
ERPIPD--LCVICLEQEYNAVFLPCGHMCCCITCCSQL-----SNCPLCRRRIEQVVKTF
RH-
>Populus_trichocarpa_gnl|BL_ORD_ID|12209 _POPTR_0003s06390.1|PACid:18218320

MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------SRAHEQALAAMLSHLALSFDGAILGAA------------L
AYAAVRSFLNFTANSKSLAKIRKAPTLSVSDLRSLLQNHDQDHQDQEQKLVIVRGQVEAK
SAVDGSGKKSSRDSNVLLSHESGDKAVILQRTQTCIYNEWKG------------------
----FFG-WTSDLRSIFGRSLKEQETTFLRTVPFTL---VEGGQWPQSD-YVIVNMDGSS
HPLPLTMVYHQLQPIVASRYTFIQALFGHEYPVGVLHEEKILPLGKCISAVGICNSKD-G
IPEIKSCKEL-PYFLADMTKD-------EMVADLAFKAKILLWSGIVLGSLSIGVLG-FA
VMRNWNKWKAWR-QRRSQQPIHTTS-------D----------EDVSQIDD---NED---
AGDVPEGQLCVICLMRRRRAAFIPCGHLACCHTCAVSVESEVSPKCPLCRQAVRNSIRIF
EC-
>Populus_trichocarpa_gnl|BL_ORD_ID|32327 _POPTR_0001s16880.1|PACid:18238703

MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------SRSHEQALAALLSQLALSFDGAILGAA------------L
AYAAVRAILNYTANSKSLAKISKAPTLSVSDLRSLLQNHDQDHQDHEHNLVIVKGIVEAK
SAVEWTWKESFRPPKVLLSHNSAYKAVILQKTQTCIYNEWKG------------------
----FLG-WTSELRAIFGRSLKEQETTLLRTVPFIL---VEGAQWPRSD-YVIVNMVGSA
HPLPLTTVYHQLQRIAASRYTFIQALFGHEYPVGVLHEEKILPLGKCISAVGICNSKK-G
IPEIKSCKDL-PYFLADITKD-------QMVADLAFKAKIQLWSGIFLGSLSIGVLG-FA
VMRNWNKWQAWR-QRHSHLPNHTTI-------D----------ADVSRIDE---DE----
AGDVPDGQLCVICLTRRRRSAFIPCGHLACCHFCAISVESEVSPKCPLCRQAIRNSIRVF
EC-
>Populus_trichocarpa_gnl|BL_ORD_ID|18425 _POPTR_0004s22730.1|PACid:18224640

MAIASLHNVSVLDSSFLRESQSEVVRRRGDDGRSTRTSSHLQIQQELEDEHVVSHVQGRV
SDRLVQHQSDGSSTDLLRVDASDSHSNGQSGSSEGGSAGESEYGQWSPGPIGSENGQEDS
SDLGEVGRERVRQIFREWMNSGARECASSISRRNNGSRAEWLGETEQERVRIIREWVQMN
TQQRGACVDRREEQGSEVAGQIEQVLDGLAVNHNDGQAENTRRGIRRLCGRQALLDMLKK
HERERQSELRGLSEHQVVTQFAHRNRIQSLLRGRFLRNDRIIEDERPASPAASELGLLRQ
RHTVSDLREGFFSRLDHSVYGQASSNVSDTSSNTDMNGNRSEQIEANNSQQVIDEFYVQT
ESNTEEIGSLGLLDGRADIEDNIIDETSGQNFTAHSVEGPRQVSDSDVGGRQQLANVAFV
ERRDGTREEASDHRWGGTNNESSQETVGSEAEEDMQLLSTTEVFSQQSEADRGDSVIPLL
SNHLIDLEATANESVNWQESAAPL-----EQWQNQLLENEGQH--------------SFE
ASLTSG---------------EWGDGIQDNIDGHQHETAANEWSENEDREGASEVWHEDD
GFQEAVHSWLTEPSDLEAAPVG-------RMDPFYF-PDDDNV----YSMELRELLSRRS
VSTLLRSGFR------ESLDQLIRSYVERQSHAPLEWELQTAPTPASTEQDLEQQTVD--
----QNESEGNIVQSPSLDLPSRPIRPAEQLWDQESRHYTWPQH-----DMHP-RFGIEW
DIVSDLRIDMARLQQRMNNMQRMLEACMDMQLELQRSIQQEVSAVIAFNAP---EDRTKW
DHVRKG--ICCICCDGSIDSLLYRCGHMCTCSKCANEL-VQSGEKCPMCRAPVIEVIRAY
AVL
>Panucum_virgatum_gnl|BL_ORD_ID|33311 _Pavirv00039228m|PACid:23789376

M----------MIPWG--------GVGCCLSAAALYLLGRSSGRDAEVLRSVARAGSMKD
LAAILDTA-SKVLPLVVAVSGRVGSDTP-LICQQ--SGMRGVIVEETAEQHFLKHNDAGS
-WIQDSAVMLSVS---------KEVPWYL---DDGTG----RVYVVGARAAAGLILTVAS
EVFEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRIQRPHK
G-PFYVSPKSIDQLILNLGKWAKLYRLASMGFATFGVFLLAKRAIQHFLERKRRHELQKR
VFNAAAQRQARESEGGNGTSDTEPNSKKDQLVLDICVICLEQEYNAVFVPCGHMCCCMAC
SSHLTN-----CPLCRRRIDQAVRTFRH
>Panucum_virgatum_gnl|BL_ORD_ID|48680 _Pavirv00039347m|PACid:23804892

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLTVSGQLRLVASAA-ASSIAD
LRSLLPGSGGE--PRLAAVRGYVRPKPGGMILQPPFSGEHGVITKHTQMCLFTEWRGIFG
-WTFDLHALLFRSWKEQIVTSFRTVPFVLASSEIGNPIGMVHINVEKADPNQPLPLTTVF
HKLIPIETTPYALFQTIIGNGYPIALLDEEKILPIGKELTAIGLCRAKD-ESVEISSCPD
L-PFFLSELTKDEMQAQLASRARTLFWGSIVLGTLSVCLVGHAIYRCWKRIKLRREAR--
----QAQQLFEEAEDAIQEGDSSDEEVGD---GQLCVVCLRRRRKAAFIPCGHLVCCCKC
ALRMEREAEPLCPMCRQDIRYMMRIYDS
>Panucum_virgatum_gnl|BL_ORD_ID|10708 _Pavirv00062728m|PACid:23766539

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQLRLVASAA-ASSISD
LHSLLPGSGGE--PRLAAVRGYVRPKPGGTILRTPFSGEHGVVTKHTQMCLFTEWRGIFG
-WTFDLHALLFRSWKEQIVTSFRTVPFVLASSEIGNPIGMVYINVEKAD--QPLPLTTVF
HKLIPIETTPYTLFQTIIGNGYPIALLDEEKILPIGKELTAIGLCRAKD-ESVEISSCPD
L-PFFLSELTKDEMQAQLASRARTLFWGSIVLGTLSVCLMGRAIYRCWKRIKLRREAR--
----QAQQLFEDAEDAIQEGDSSDEEVGD---GQLCVVCLRRRRKAAFIPCGHLVCCCKC
ALRMEREAEPLCPMCRQDIRYMMRIYDS
>Phaseolus_vulgaris_gnl|BL_ORD_ID|17669 _091029254m|PACid:23548376

MKMIPWGGLSC----------CLSAAAL-YLLGRSSGRDAEILKSVTRV--------NQL
KELAQLLDAEI-------------------LPLI-----VTISGRVGSETPI--------
----------------------SCDFSGLRGVIVEETAEQHFLKHNDAGS----------
----------------------WIQDSALMLSMS---------KEVPWYL----------
-----DDGSD--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RVHVVGARGATGFALPVGSEAFEESGR----
------------------------------------------------------------
------------------------------------------------------------
---SLVRGTLDYLQGLK-----MLG-V-------------KRIERVL-------------
----------------------------P-VGTSLTVVGEAAKDDV--GTIRIQRPHK-G
PFYVSPKTI---DQLIANLGKWARWYKYASMGLTVFGAYLIAKHAIR-FILERRR-----
-----------RSELQRRV--LAAAAAKKSGPNNDVEKADSLSDVAKRDHLMPDLCVICL
EQEYNAVFVPCGHMCCCTACSSHL-----TNCPLCRRQIEKVVKT---FR-H
>Phaseolus_vulgaris_gnl|BL_ORD_ID|21270 _091018531m|PACid:23552061

MSHQEQALVSLLSQLALSFDGAVLGFALAYAAIRTLVKFSATSAALRKLRRAPYLSVSDL
RSLLADTPSDA-------------------NSNSDGGAIVIVRGNVDAKSAVDGSWKTLR
PGVL------------------VSRESGDRGVILQRTQTCIYNEWKGLFG----------
----------------------WTSDLRAIFARSWRQQESTSLRKVPFVLIDVGWRPSTE
YVVVNMDGSRHPLP----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------LTTVYHKLQPINA----
------------------------------------------------------------
------------------------------------------------------------
---SPYTFLQALFGHEY-----PVG-L-------------LDEEKIL-------------
----------------------------P-VGKDVTAVGLVSLNN---GVAEIKSCKD-L
PYFLSDLSK---DQMIVDLSIKTKILFWGGIALGSMSVGILGYAVVR--NWNKWK-----
-----------QWKLQRQL----------QQQRQAVSDVEPQVDDEIEDVPDGQLCVICL
MRRRRSVFIPCGHLVCCQGCAISVEHEVAPKCPVCRQEIRNSVRI---FE-S
>Phaseolus_vulgaris_gnl|BL_ORD_ID|2023 _091018338m|PACid:23532374

MAIAGLHSVSVLDSPFLRDSHSQSSRRG-GEGRRGSTRSSSLLQMWREIED------EHV
VNQVQGRPGEVPLEQRRGDGLIAELSQEDRLDIQERGQGHVLEDAVLGENESETWSQSQS
QNEFHEDHEDLNNS--------SCENSSDLGEVERERVRQIFREWMNSGARDHVSNVSRR
NSGSRREWLGETEQERVRIIREWVQTSSQQRSVSSGENREESSAEIGTQI-----ERVRN
GLIVNQNGGQNELSRRGIRKLCGRQAMLDMLKNAERERQREIEDLSVHRAVSQFPYRNRI
QAFLRGRFLRNDRPVDNNRPLSVAESELGFLRRKQTVSGLREGFIARKENSGCSQATSNV
SDTSSNVDIDLNTNEQMGSSSSHLVPIVHSELSDPNDRGSDGLRVSDSQSCVQGATSENL
NWQESIAQLGDGMKHLPIESLDCQSSFSASVERVNNTEQNVDVMPTEYSANEITQQSLRI
EESHHSNNQEFSEVHIEHSQLGDINSIENNSSNHDIHMDGNVVDDVNWNGSGALEVEQPE
EAFENEGSEWYQNNTEWRNITEENADGNQLSNSASEWPENTSGNGDGENSHLQESHEAWQ
EDGSFQEAVENWLGGPSDHESAPAGRIRGFYFPEDDNVYSVELRELLNRRSVSNLLRSSF
RDSLDQLIQSYVVRQGNAHIDWELQETNPSSDSAEQDVEQQSRDQIVHQEVPVNSPLD-L
PSLPIPPPLPLWDQHHHHRDNWSQ----NDINNQRLGIDWEIVNDLR-IDMARLQQRMNN
MQRMLEACMDMQLELQRSIRQEVSEALNRSADSSDVHDYESPEDKSKWECVRKGLCCVCR
ESNIDSLLYRCGHLCTCSKCANELLQS-RKKCPMCQAPVVEVIRA---YSIQ
>Phaseolus_vulgaris_gnl|BL_ORD_ID|12949 _091022080m|PACid:23543541

MGIS-------------------------WSGRRRN------------------------
-NYIQNPPPPLPPPP------YYYPPQSHHPPLPPPPQGYFLPSTTTYAPNSNNYAAPPP
LVPPPQ-PPPQTHSISFYYTNQSAYPNYANSAPNRLQYQPFYHPQPSV------------
----------------------WPAATGAPASTP------------PPYVDHQAAKKIRN
YVNVHKDTLRLEVDQE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------NPDHHLISFVFDAVYDGSITVFYFAKEEEKCRFVPLFPDAFQPVRI----
------------------------------------------------------------
------------------------------------------------------------
---PFQKGVGQTFSQPS-----GTG-IDLGFFELDDLSKPSPEEDVF-------------
----------------------------PLVICAETSLKTPSEDETLGDSVLDASPH---
------------------------MQITQGVLEKSNGAGPFLIKVVRQILWIDGV-----
-----------RYELRELY----------GIASSSAADFDDND--------PGKECVICM
TEAKDTAVLPCRHMCMCGECAKSLRLQ-SNKCPICRQSIEELIEIKVNNDNQ
>Phaseolus_vulgaris_gnl|BL_ORD_ID|12887 _091022123m|PACid:23543477

MGIS-------------------------WSGRRRN------------------------
-NYIQNPPPPLPPPP------YYYPPQSHHLPPPPPPQGYFLPSTTTYAPHSNNYAAPPP
LAPPPQPPPPQTHSISFYYPNQSAYPNYANSAPNRLHYQPFYHPQPSV------------
----------------------WPAATGASESTP------------PPYVDHQAAKKIRN
YVNVHKDTLRLEVDQE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------NPDHHLISFVFDAVYDGSITVFYFAKEEEKCRFVPLFPDAFQPVKI----
------------------------------------------------------------
------------------------------------------------------------
---PFQKGVGQTFSQPP-----GTG-IDLGFFELDDLSKPSPEEDVF-------------
----------------------------PLVICAETSLKTPSEDETPGDSVLDASPH---
------------------------MQITQGVLEKSNGAGPFLIKVVRQILWIDGV-----
-----------RYELRELF----------GIASSSAADFDDND--------PGKECVICM
TEPKDTAVLPCRHMCMCSECANALRIQ-SNKCPICRQPIEEFIEIKVNSGNQ
>Ricinus_communis_gnl|BL_ORD_ID|8077 _29703.m001546|PACid:16806242

MRNAEYSKTTFGKGLDAEAL----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------KSVTRVNQLNELAKLLDIESKVLPLV---------
------------------------------------------------------------
----------------------------VAISGRVGS--------ETPINCEYSGLRGVI
VEETAEQHFLKHND---AGSWIQDSALMLSMS---------KEVPWYL--------DDGT
DRTFVVGARGASGFALTVGS-----EVFEESGRSLVRGTLDY---------------LQG
LKMLGVKRIERVLPTGTSLS-VIGEAVKDDIGTVRIQRPHKGPFYVSPKTIDELIGNLGK
WARWYRYASVGLTVFGVFLIA------------------------KHAIQYIMERRRRWE
LQ-------------SRVLA----------------AAAKRQGQDSDGSNGKAENGSDSS
KRER---PIPDLCVICLEQEYNAVFLPCGHMCCCTACSSHLT-----NCPLCRRRIEQIS
ASIPVKDSCQGTDFLFHPRIRCKILPIAAIAYNWK
>Ricinus_communis_gnl|BL_ORD_ID|7472 _29681.m001351|PACid:16805637

MNYHSGGETE--------------------------------------------------
---------RPLGERQLIAISLFLLSQNAAVQFCNSFTFFRQLM----------------
-------------EEADHPSSSSSVPVAEPSASQVQEEEVRNEQIENGNNSHHQRNHPSY
SYSSALPYRVNISISNMAPTEMTDDV----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------WSCLVV-----------------------------
------------------------------------------------------------
------------------LVTFWFFASMTLILGFYGSVNLELGPNCSYLIKTN----PLF
VQSIKVEEVDEPKHGPMLYGFHKPPPMDVETTWTETH----KALILPHLQEWAYFLNKGS
KVAIFYTIKSPSSSPLSL--------VIAQGRDSLVEWIDEPSYPNST---------LSW
NIIFGSGKIEQEISESSNYYIAVGNLNSEDVEVELKFRMNAFIYNTTNAFYMCSLGHRLC
SLKLFLLGTNVAVLTSPVPQEGDDWYVKVSYGPRWMTYFIGSGFMTLLILFTLRYCKMFQ
ASSGDGIQEGDNLRSERAPLLLPKDDDVSSWGSSYGSTSQEEHEDLDELLAMNSGAGKQL
SEGE---NLNRLCVICFDAPRDCFFLPCGHCAACFTCGTRIAE-EPGTCPICRRSMKKVR
K-----------------------------IFTV-
>Ricinus_communis_gnl|BL_ORD_ID|16536 _29970.m001010|PACid:16814701

MEF---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------SYGTCSNTDSE--ESGYCSSSTSSSNF
STEL---YDGKVCVICYDEERNCFFVPCGHCATCYVCARRIFDGENKVCPVCRRFIGKVR
K-----------------------------LFAL-
>Ricinus_communis_gnl|BL_ORD_ID|8129 _29706.m001280|PACid:16806294

MSSHEQALAS--------------------------------------------------
-----------------LVSQLALSFDGAFLGVVVALTAVRSIL----------------
-------------KFASNSKALRKIR----------------------------------
----------------NAPTVKVSDI----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------RSVLEVSDETQDQKLVIVRGQVEAKS---------
------------------------------------------------------------
-----------------------------AVDGNWKS----LIPNNNVLVAHESGDKAVI
VQRIQTCIYNEWKG---FFGWTSDIRAIFGRSWREQESTLSRSVPFVLVEAGRWPQSD--
---YVIVNLDGSRHPLPLTTVYHQLQPIDASPYTFLQAF------------------FGY
EYPVGLLDEEKILPLGKEIN-AVG-LCGSKNGILEITSCKDLPFFLSDLSKEQMVVDLAF
KTKVLFWSGVVLGSFSICILG----YAAVRNWNRWKA-----------------------
------------------------------------WRQQRQFQQQSNSVSDADVSQIDV
EEETVDVPDGQLCVICLMRRRRAAFIPCGHLVCCQICAISVEREVSPKCPLCRQAVRNSI
R-----------------------------IFEC-
>Ricinus_communis_gnl|BL_ORD_ID|2918 _28546.m000072|PACid:16801083

MSFASCSSTHNQDDEDDEGDQLVRRRRRADLEGDDLAESSAARRRHSRIFSRWAARQAQE
MITTIERRNRESELMALAGLHTVSMLDSSFLRESHSPTSRRQGAVERPSTRASSILQMWR
ELEDEQLLNRARERVRERLRHQRSVESNTNISSTNMSESRGSEIQGSLGDASESENEFGP
WPHERLGSQNERGDNNGSSREQSPDLGEVERERVRQIVRGWMESGISDHTSNVSQRNGSP
RGEWLGETERERVRIVREWVQMASQQRGGRGGRREDQAAGPDAQADRVVRDGSVADHDEG
QPEHIRRDMLRLRGRQAILDLLVRIERERQRELQGLLEHRAVSDFAHRNRIQSLLRGRFL
RNERPVEEERPPSMAASELVQLRQRHTVSGLREGFRSRLETIVRGQASGQSDSTPDNNVN
DGNDWSQISTSENVQHENNEQPRSQEIDIHRLSDQTDSIENNTTVNHMNWQENGNQGEGW
QGQITNDEEQNWQQQNYSQFNEWRNGDAEPMDGNWQENSANHWPQEAAGNVHS----EQR
RLQEAQEVWRENPSQGAVENWTEGPSDPPRTR---------RAVPVRRINRFHPPDDDNV
YSMELRELLSRRSVSNLLRSGFR--ESLDHLIQSYVERQGRAPIDWDMHRNLPTPTPTSP
ERDEDQQRDDQNEDQRDSMN-RPS-LVLPSPPV---PPPQPLWH--QDLHHTSWSRHSMH
RSEL-----------------------------EWEMINDLRADMARLQQGMSHMQRMLE
ACMDMQLELQRSVRQE--------------------VSAALNRSPGEKGLVGAETSEDGS
KWGH---VRKGTCCVCCDSHIDSLLYRCGHMCTCSKCANELVR-GGGKCPLCRAPIVEVI
R-----------------------------AYSIL
>Sorghum_bicolor_gnl|BL_ORD_ID|8897 _Sb02g041380.1|PACid:1959657

MM--------------------------------IPWGGVGCCLSAAA-----------L
YLLGRSSGRDAEVLRSVARAGSMKDLAAILDTA-SKVLP---------------------
-------------------------------------------------LVVAVSGRVSS
DTPLICQQ--SGMRGVIVEETAEQHFLKHNDAGS-WIQDSAVMLSVS---------KEVP
WYL---DDGT--GRVYV-VGARSAAGLILTVASEVFE-----ESGRTLVRGTLDYLQGLK
MLGVKRTERVLPTGTSLTVVGEAIRDDVGTIRIQRPHKG-PFYVSPKSIDQLIMNLGKWA
KLYRLASMGFATFGVFLLAKRAIQHFLERKRRHELQKRVLNAA-----AQRQAREAEGSN
GSSDTEPNSKKDQLVLDICVICLEQEYNAVFVPCGHMCCCMACSSHLT-----NCPLCRR
RIDQAVRT------------------------FRH-
>Sorghum_bicolor_gnl|BL_ORD_ID|4679 _Sb01g045370.1|PACid:1954575

MS------------ARDRETAEALV--RLAASLDGAVLGLGTAAVAVA-----------S
WVKYLAVSGQLRLVASAATASIG-DARSLLRGD-GN-EP---------------------
-------------------------------------------------RIAAVRGYVRT
QGSFLRAPF-SSEAGVVVKHTQMCLFTEWRGIFG-WTFDLHALLFRSWKEQIVTSFRAVP
FVLASTELGNSTGVVHINVDEVDYQPLPLTTVFHKLI-----PLETTPYTLFQTIIGNGY
PIALLDEEKILPIGKKITAIGLCRAKNAESVEITSCPEI-PFFLSELTKDEMQAQLASRA
RILFWGSIVLGTLSVCLVGHAIYRGWKRIKLRREAR------Q-----AQQMFEDAEDAI
REDNSSDDDDDDVGDGQLCVVCLRKRRKAAFIPCGHLVCCCKCALRMEREVEPLCPMCRQ
DIRYMIRI------------------------YDS-
>Sorghum_bicolor_gnl|BL_ORD_ID|4175 _Sb01g040770.1|PACid:1954038

MGNAGSNGGGAAAGHRRRSSSHGHGHHHQAPPPPQPQETAPNRYVFAAATPYPPQYPNP-
------------------------NPPQYYPQYGNYYPPPPPSVPVPLPAPYDHHHRPPT
AAPGEFPPPPPAHPHHYPGWAGRYPSYGPHLPM----PTPYVEHQKAVT----IRNDVNL
KKETLRIEPDEECPGH----------------------------------------FLVA
FTFDATVAGS----MTVYFFAKEELNCNLAAMKEDLIKPVTVSFKEGLGQKFRQPSGTGI
DFSVFEESDLLKQGDMDVYPLVVKAETALSA--DHPSEGDDQKMKT--------------
-----------------PNSQITQAVFEKKENGDYQVRVVCQILWVNGTRYELQEIYGIG
NSME---GDADANDPGKECVICLSEPRDTTVLPCRHMCMCSECAKVLRYQTT-RCPICRQ
PVERLLEIKVNNKSEEQQQTPQSPPLPAPAPQQEEV
>Sorghum_bicolor_gnl|BL_ORD_ID|25703 _Sb09g019560.1|PACid:1980775

MG--------ASSSRRRRDDYYPPPHHYSSYPPPPPP---------------PPHHHHP-
------------------------PPP----------PPPPHHRPPPPPPPSSYYYH---
------PHPPPPHAYHGPWHPAPAPPPQPQPPALTGPPPEFVEHQQAQK----VKNYVNL
HKDTIRLVPDDADPDR----------------------------------------RLVA
FTFDAITDGS----VTIYYFAKEEKDCSFSSIYPELQTPTKIPFEKGLAQRFIQPSGSGV
DLGFF-SLDELSSSSGEVFPLVVYAEAYPS-----PEEGGPSVNST--------------
------------------RAQITLAVLE-KHNNDLQVKVVKQILWIDGVRYELQEIFGMV
NSTESDVADADADDTGKECVICLTEPRDTAVMPCRHLCLCSECAKTLRFQSN-KCPICRQ
PVEKLMEIKVRSSEP---------------------
>Setaria_italica_gnl|BL_ORD_ID|40388 _Si030396m|PACid:19714000

M----------MIPWG--------GVGCCLSAAALYLLGRSSGRD---------------
-----AEVLRSVARAGSMK---------------------DLAAILDTA-SKVLPLVVAV
SGRVGSD---TPLICQQ--SGMRGVIVEETAEQHFLKHNDAGS-WIQDSAVMLSVS----
-----KEVPWYL---DDGTG--RVYVVGARAAAGLI------------------------
-----------------------LTVASEV------------FEESGRTLVRGT----LD
Y----L--QGLKMLGVKRTERVLPTGTSLTVVGEAIKDDVGTIRI------QRPHKG-PF
Y---VSPKSIDQL-ILNLGKWAKLYRLASMGFATFSVFLLAKRAIQHFLERKRRHELQ--
-KRVLNAAAQRQAREAEG--GKGTSNTEPNSKKDQLVLD--ICVICLEQEYNAVFVPCGH
MCCCMACSSHLTN-----CPLCRRRIDQAVRTFRH-------------------------
--
>Setaria_italica_gnl|BL_ORD_ID|11123 _Si036246m|PACid:19684534

MSARDRETAEALVRLAASLDGAVLGLGTAAVAVASWVKYLAVSGQ---------------
-----LRLVASAATA-SIA---------------------DLRSLLPGDGGE--PRVAAV
RGYVRPKPGGNILRVPW--SGEHGVVTKHTQMCLFTEWRGIFG-WTFDLHALLFRSWKEQ
IVTYFRSVPFVLASSEIGNPIGMVYIDVEKAAQPLP------------------------
-----------------------LTTVFHK------------LIPIETTPYTLF----QT
I----I--GNGYPIALLDEEKILPIGKELTAIGLCRANDEGSVEI------SSCPEL-PF
F---LSELTKDEM-QAQLASRARILFWGSVVLGTLSVCLVG-------------HAIY--
-RGWKRIKLRREARQAQQLFEEGEDAIQEDDSSDEEVGDGQLCVVCLRKRRKAAFIPCGH
LVCCCKCALRMERETEPLCPMCRQDIRYMMRIYDS-------------------------
--
>Setaria_italica_gnl|BL_ORD_ID|18990 _Si013872m|PACid:19692445

M---------------------------GGVFGALFGSHRRAGRAPAVRHRGLATQPSSA
YDGGRRRAMLSKK------------------YSYIPDTYTSLDQVAAALRQQGLESSNLI
LGVDFTK----------------------------------SNEWTGKQSFGGQSL----
-----HRLGDTPNPYEQAISI-IGKTLAPFDEDNLI-----------------PCFGFGD
ATTHDYNVFSFHHDNSPCHGFEEVLACYRKIVPHLRLSGPTSFAPIVEAAVDIVERSGGQ
YHVLVIVADGQVTRSVDTGDSDLSPQEKRTVDSIVMASS-YPLSIVLVGVGDGPWEDMQK
FDDKLPTRDFDNFQFVNFTSIMARSTTAQQKESAFALAALMEVPIQYKATVELGILGRTT
GKAKRVQPAPPPLPQRQSSLRRGSSNVSSTSAPSPR--DDQVCPICLTNAKDLAF-GCGH
MC-CRECGESLTR-----CPICRQPIRSKLRLYSG-------------------------
--
>Setaria_italica_gnl|BL_ORD_ID|9783 _Si035963m|PACid:19683186

M--------------G----------NAGSNGGGAAPGHRRRSSSHGHGHHHQAPPPPPP
QEAAPNRYVFAAATPYPPQYPNPNPPQHYPQYNYYPPPPPSVPVPLPAPYDHHHRPPTAA
AGEFPPPPPAHPHHYPG---------------------------WAGRYPSYGPHL----
------PMPTPYVEHQKAVTI--------RNDVNLKKETLRIEPDEECPGRFLVSFTFDA
TVAGSMTVYFFAKEELNCN----LTAVKEDL-----------IKPVTVSFKEGL----GQ
KFRQPS--GTGIDFSVFEESDLLKQG-EMDVYPLAVKAE-TALSV------DPPLEG---
---------EDQK-MKTPNSQITQAVFEKKENGEYQVRVVCQILWVNGTRYEL-------
----------------QEIYGIGNSMEGDTDANDP----GKECVICLSEPRDTTVLPCRH
MCMCSECAKVL-RYQTTRCPICRQPVERLLEIKVSNRSEDQQQAPQSPPRPPPTPQQEDV
HP
>Selaginella_moellendorffii_gnl|BL_ORD_ID|15488 _231449|PACid:15416766

MLPWGGI-------------------TMCLSGVALYFLSRNSGRDAATLKAVRRVDQLKD
LAHLLD------SACKAVPLVVTVAGRV------GSETPIGCDHSSLRCVILEETAEQHF
LKHN----------DTGSWIQDSALMLSNNKEVPWFLED-------ASGRVFIVGARGAA
GLELTIASEVFEESGRSLVRGTLDYLQGLKMLGVK----RVERVLPTGT----ALTVVGE
AIKDDQGTLRIQRPHKG-PFYVTPKSIDQLIANLGKWSRWYKYMSLGFTLFGVFLVASHT
IRYVMEKRRRAALNRRVME----AAARRRERKEHEGKAQVGEFAKVETATKRDGRLPD--
LCVICLEQEYNAVFVPCGHMCCCISCSAQL--------QNCPLCRRRIEQIVKTYRH---
---------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|11999 _91152|PACid:15413277

MASHDEEICAALTRLAMAGDGIVLGLGMAALALRTWLKFGSHTRALKQVEGTAQVEI-HD
LRSLVESGEKEPSSDSSPPLVI-VRGRVALPPKTSSEEVLLARNQTDLAVFVERTQTYLF
NEWRGLFRWGPEWRGLLGWGSLKEQVAFSRRKIPFVLLDSDPQYDG--ACVHINMENVEH
PLPLVTVFHQLHPVQTSSSTFLQAVFGRRYPVGVI----DEEKILPLNR----EITAVGF
LSKHPQGLPAIKSSNQM-PFFLTEFSREELIVELASATHALFWTGIV-----ISSLALGV
IGYSAFKNWCKWKEWRRLR------QIQEELRREE---QVMEEDEEPATTQEGSEVPDGQ
LCVVCLLRRKRAAFITCGHRVCCMGCARRIRHSQNAANARCPVCRQSVSGYIRVYD----
---------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|16265 _98973|PACid:15417543

-----------------------------MVPPQVHQKAITIRNDVNLKRGTLRLEEDKE
------------------------------------------------------NAGKHL
--------------------------------VSFLFDAAVP----GSASILFLAGPGPN
FSLVPLKPHLFRPQRVTFDKGLGQRFCQLPGSGVNLSLFEADDLSKDGKDEVFSL-----
-------VVRLESMPKEQSSDA----SLPVGGPLPRSIH------------------AQT
TYVLLERKASGQYGVRVLKQIIWVEGTRYELQEIYGV-------GNTGDGHPDK--HAGR
ECVICLTNRRDTALLPCRHMCMCSECARILRFQT----QRCPICRCVVDKLLEIKVPRAE
DDDLENRLD
>Selaginella_moellendorffii_gnl|BL_ORD_ID|688 _57157|PACid:15401966

AA---------------------------AIPVAHHQKANTIRNDVNLRKATLRIEKDEE
------------------------------------------------------NPGFYL
--------------------------------VAFSFDATVP----GNICIFFVAKEGVN
CSLTPMKPQVFDPVKVPFDKGLGQKFRQAPGTGIDLSLFEDEDLAQEGQDETYAL-----
-------VVRAETYSRDPPADAPSRDTEPLGAPLPKWVH------------------SQT
THAVVERKDGGEYGVRVIKQIIWVEGVRYELQEIYGI-------ENSGGGSGANFDDSGK
ECVICMSEPRDTTVLPCRHMCMCSECAKVLRFQT----NRCPICRCPVERLLEIKVPKND
---------
>Thellungiella_halophila_gnl|BL_ORD_ID|8267 _Thhalv10008106m|PACid:20187792

M-------------IPWGGVTCCLSAAALYLLGRSSGRDAEVLKTVTRVSQLKELAQLLE
LDSSKLLPF-----------------IVAVSGRVG---------SETPIKCEHSGIRGVI
VEETAE------QHFLKHNETGS-WVQDSALM----LSMSKEVPWFLDDGTSR-------
VNVVGARGATGFALTVGSEVFEESGRSLVRGTLDYLQGL----KMLGVKRIERVLPTGMP
LTIVGEAVKDDIGDLRIQKPERG-PFYVSPKSLDQLISNLGKWSRWYKYAS--MGLTVFG
V-FLITKHVIDSVLERRRRRELQKRVLDAAAKRAERESEGSNGTHESVSDSTKKEDAVPD
--LCVICLEQEYNAVFVPCGHMCCCTACSCHL-----TSCPLCRRRIDQVVKTYRH
>Thellungiella_halophila_gnl|BL_ORD_ID|4555 _Thhalv10011564m|PACid:20184051

MSSPDRAIFNLLTDIALSFDGAFLGVTLAYGAIRSAFKYA---SSSAALSKIKDAPEVSV
SDRRSLIPASEDQSENRDHGNSHDQRIVVVRGTVRPKFTGDGSHKDNVLISQETGDKALI
IQRTQTYTYSGWKTLFQLSNTHR-FLFERSMMPKQETALTRMVPFVIVEKNQRSQSSFLL
VNMDGARQP--LPLTTVYNRLQP----INSTPFAFLQVLFFPEYPVGLLDVENILPPGRD
LTAVGVCSLNN-GVPEIKSCQDL-PFFLSEMTKDKMILDLMHTTRVTFWAGVVMGCLSAG
ILGLVA----VRTWKRWKLRYHQREPL-------QRPDE------PVVDDETEDADEIPD
GQLCVICVTRRRIPAFIPCGHVVCCRQCALTVERALNPKCPVCLQSIRGSMRVYYS
>Volvox_carteri_gnl|BL_ORD_ID|4262 _Vocar20010194m|PACid:23128133

--------------------------------------------------MLGHAAAATG
SKIWIFGGQQGRKFLRTLYCFDTETCT---WTRRDTDSMPP----ARAGHSMVTVHGSVI
Y-----MFGGQGKRLYNDLYKLDPITGIFT-----------------EVEASGKPPTPRR
GHSLVWDGRDYLVCFGGINQSSTDSQ----------LSVFSLSRGAW----FTPQAFG--
-----------------------------PAPSART------------------------
----------QHTAQLLSPGVILIFGGCNSSGTFFNDAIVLDTRTFTWHKPTLLNTAPAP
RYHHTCSVVNGRIIIYGGI---NSKQTFDGVVVLETKFLSDINSVAEELFRMSADATSAA
SLFNAAAAGGGATTAALPAGLQTSTANSPVNMTGSTGARLSAGPSVLSSQMQSTAQHQHP
PVQVVPQ--------------------------------------PGPASELGFSSSKSL
E-AVKIQ-----------------------------------------------------
---------LTDLLLRRNLEEQQLHTAKKA------------------------------
------------------------------------------------ETTESLLIKERE
AREAAVKELLQFKLLLAEAESAQASAQQE----------LQGALAKATREAAAAAELRSQ
LEALQSKLATREEELQEARLLQDGLVKELGIMAS-----------------RYSRLAVDV
QEGAERGGPGGGGGSA------GDRGGGSSAGDRVSQQHHAG------------------
---SSCTRRSSLSSMLAHATHGSGGLAVRGLGGSPSIAREATAVY---------------
------PVSSLQMGTASSSMVASAGGSVLAGGNSGIVDVLQASGCYSVPLPGHSTASMLS
SRQVAPALSSHCTATIRTSASQSAIP------QSTTPTACGNCCQQLLALLSEAEVHRA-
--SLLDSNQGLNEKVEELTAQNNMLYGQLQQMLAEGGAL------------EPLSVGELE
EL----------------------------------------------------------
------------------------------------------------------------
----------ERKLDSSSRAVRAALTQRKIDEAQRRSST---------------------
----EQAACAVCMEGPKAVVF---NCGHQS-CEPCSVKM----TTCPFCRVQITARIRLF
DA-----------------------
>Vitis_vinifera_gnl|BL_ORD_ID|6424 _GSVIVT01011070001|PACid:17823049

M-----------------------------------------------------------
--------------IPWGGIS---CC-------------------------------LSA
AAL---------YLLGRSSG--------RDAEALKSVTRV--------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------QQL-----KDLVQL------------------------LDT
A--------CKV------------------------------------------------
-------------LPLVVTVSGRVGSDTPIKC-EY------------SGLRGVIVEETAE
QHFLKHNDAG----S-WIQDSALMLSMS---------KEVP---------WYL-------
-------DDDTGRA--YIVGARGATGLVLTVGSEVFEESGRSLVRGTL------------
-DYLQGLKMLGVK-RIERVL------PTGTPLTVVGEAIKDDVGTIR---IQRPH---KG
------------------------PFYVSPKSIDHLVANLGKWARWYR------------
----YASLGFTVFGVYLIAKSAIQYVMERKRCWELRKRV------LAAASKKSGQDSEDP
DEK------------DENGSDNTKRDRL----MPD---------LCVICLEQEYNAVFVP
CGHMCCCTMCSSQL-----TNCPLCRRRIEQVVRTF--R-H
>Vitis_vinifera_gnl|BL_ORD_ID|10490 _GSVIVT01016752001|PACid:17827115

M-----------------------------------------------------------
--------------SAHDQAAAAILAQ----------------------VALAADGAILG
LAL--------AYVAVRSFI--------RLSSTSSALRQI--------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------DQSPSFRVSDLRSL------------------------LSP
SSDDESDQSTSS------------------------------------------------
-------------DGLLVVVRGTVEAKSAIDG-NWKSLRPNVLVSHESGEKGVILQRTQT
CIYNEWRGFF----G-WTSDIRTLFARSWKEKESTSLRTVP---------FILV-----E
GGRWPQSD--YVIV--NMDGSRHP--LPLTTVYHQLQPVNASPYTFLQ------------
-ALFGHDYPVGLL-DEEKLL------PLGKEITAVGICSLKN-GIPE---IKSCK---DL
------------------------PYFLSEMSKDQMVVDLVFKSKVLF------------
----WSGV---ILGSVSIGVLGYAVVRNWNRWKEWRQQR------GVRPPSQAVTDDTDT
QIA------------EDDAGD-----------VPDGE-------LCVICLMRRKRSAFVP
CGHLVCCQRCALSVERELSPKCPVCRQIIRSSVRIY--G-S
>Zea_mays_gnl|BL_ORD_ID|23792 _GRMZM5G871572_T01|PACid:20843518

MMI------------------PWGGVGCC-LSAAALYLLGRSSGRDAEVLRSVARAGSMK
DLAAILDTA-SKVLPLVVAVSGRVGSDTPLICQQ--SGMRGVIVEETAEQHFLKHNDAGS
-WIQDSAVMLSVS---------KEVPWYL---DDG--TGRVYMVGARSAAGLILTVASEV
FEESGRTLVRGTLDYLQGLKMLGVKRTERVLPTGISLTVVGEAIKDDVGTIRIQRPHKG-
PFYVSPKSIDQLIMNLGKWAKLYRLASM--GFATFGA--FLLAKRAIQHFLERKRRHELQ
KRVLNAAAQRQAREAEGSIGSSDTEPNSKKDQLVLD--ICVICLEQEYNAVFVPCGHMCC
CMACSSHL---TN-----CPLCRRRIDQAVRTFRH
>Zea_mays_gnl|BL_ORD_ID|17805 _GRMZM2G004023_T06|PACid:20837531

MSARDRETAEALVRLAASLDGAVLGLGTA-AVAVASWVKYLAVSGQLRLVASAATA-SIA
DARSLLSG--DGAEPRIAAVRGYVRAHDKFFRAPF-SGEAGVVTKHTQMCLFTEWRGIFG
-WTFDLHALLFRSWKEQIVTSFRSVPFVLVSTELGNPTGVVHINVDKADQPLPLTTVFHK
LIPLETTPYTLFQTIIGNGYPIALLDEEKILPIGKKITAIGLCQAKDAESVEITSCPEI-
PFFLSELTKDEMQAQLASRARILFWGSIVLG--TLSV--CLVGHAIYRGWTRIKLRRE--
--------ARHARQMFEEAEDAIHRDDSSDDDEIGDGQLCVVCLRKRRRAAFIPCGHLVC
CSECALTI---ERTPHPLCPMCRQDIRYMMRVYDS
>Mulan_NP_078820
mesggrpslcqfillgttsvvtaalysvyrqkarvsqelkgakkvhlgedlksilseapgkcvpyaviegavrsvketlnsqfvenckgviqrltlqehkmvwnrtthlwndcskiihqrtntvpfdlvphedgvdvavrvlkpldsvdlgletvyekfhpsiqsftdvighyisgerpkgiqeteemlkvgatltgvgelvldnnsvrlqppkqgmqyylssqdfdsllqrqessvrlwkvlalvfgfatcatlffilrkqylqrqerlrlkqmqeefqeheaqllsrakpedreslksacvvclssfkscvflecghvcsctecyralpepkkcpicrqaitrviplyns
