>gnl|BL_ORD_ID|4401 @Cyanidioschyzon_merolae@_gnl|CMER|CMT488C glutamine-dependent NAD synthetase
------------------------------------------------------------
----------------MRLVRVATCNLNQWSLDFAGNLERICCSIARAREAGARYRLGPE
LEVSGYGCEDHFLEPDT----FVHSWEVIAEIIARGYTDDILVDLGAPVLHRHVA-----
------------------------------------------------------------
-----------------YNCRVLLLNRRILLIRPKLALADDGNYRESRWFTAWPANGRRA
LEKYPLPDCVRQVAAGAQAETLFGEALLD--------------IGGVVVASETCEELFTP
DAPHIRYSLNGCDIIGNGSGSHHNLRKLNQRIDLLRSATAKGGGAYLYANQQGCDGGRLY
YDGCALICINGEIVAQ-----------------------ASQFSIADEVEVITATIDLDE
----------------------ITAYRIAIASRGVQAASTAPVPRIDAAGRSVSLRHEDI
AGRIDGMPTGCAFSPAFIGDASQRAVPASVDPSERSFRLVLSDGEQLQYMPSQPVPVRLL
SAEEEIAYGPACWLWDYLRRSGASGFFLPLSGGADSSATATIVASMCRLVAVEAQQRNDH
VIREARRILGL-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-GTDAELTENAADAYIPRDAHEFASRILHTAYMRSENSSRATRERAAQLAKEIGAYHLDL
PIDAVVAAVLSVFTLVAGERPRFRVQGGSAVENAALQNIQARIRMVLSYLFAQLLPWARG
HGQRTLLVLGSANVDEALR---------GYLTKYDASSADINPIGGISKHDLRRFLLWAV
HELGFETLQQVVEAP---------------------------------------------
--PTAELEPITGEYVQTDEADMGMTYAELT------------------------------
------VYGRLRKIGR---------------------------------------CGPVS
MYERLSRLWKAHLSPSQVAEKVKFFFRMYSVNRHKMTVLTPSVHCENYSPEDNR------
----------------------FDLRPFLYNIRWPWQFRQIDALTSKVATAASERDALPS
ERDCH-------------------------------------------------------
------------------------------------------------------------
ANLAQIAGASP-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>gnl|BL_ORD_ID|2336 @Cyanidioschyzon_merolae@_gnl|CMER|CMM250C hypothetical protein, conserved
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MATKSFGVSGTKLLMGFVQLHRGAG
QLETAW------------------------------------------------------
-----------------GRFRNF-------------------------------------
------------------------------------------------------------
------------------------------------SAAC--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------SRQQHIVHHHGTFSPRARGLRLYSA-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------ISSQTPSGNSHPDFQPQR------------------------------------
----------------------------------------------KQQPSDADWADVME
RIERDVMSSKVVLYMKGE----------------------------PEAPLCGFSYKAVS
ILKAM-------------------------------------------------------
-----------------------------GV-----------------------------
PFQSYNVLADPLLREAIKKYSQWPTIPQLFVDGEFIGGSDIMESMYRSGELKQILGVYGK
AT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
