>gnl|BL_ORD_ID|6039 @Cyanophora_paradoxa@_ConsensusfromContig37253-snap_masked-ConsensusfromContig37253-abinit-gene-0.0-mRNA-1:cds:7422/1124-1208:0:+
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------MEHWMTAQPRRVVLKGH--------------------
-----------------------------------------KDAVNDARFSPDDIHITSA
SRDGSIRLWPVPVSSRVAELSESHCWPSAHQGQAVYAVRFSKDSSRIVSGGGDCHVRVWD
LK------------SKKQLMELKCDGQILVVAVHQAPQLGEVFASGDLGGKISDGLRLAS
GSWDETA-----------------------------------------------------
---KIWDVLSGAELASMR-HGGAVNGLAFVSLFTASACDDDREAPALYLWDANTSSGKEY
KQLQKQAAQAEQWKGA--------------------------------------------
----AARLKEELSASK------------------K-------------------------
-MQQA--------------------AEQLAA-----------------------------
----------------------SAEQRAASAERRATT-----------------------
---------------------------------------------------------AEK
RATQAKLAEESTVVELKATHAEAARLKRRLEMAEQSAQLLQGQLETAVQLSDAHLQTLSA
AQLKELADRLHREARRVDETH------------VEKKCKEA-AEAARRAAAAEVEDAK--
-----------------------------------TCIVCS------------------E
RSVE---I--TLQPC------------GHST---LC------------------------
------EQCA---------------------------LLL----------WNSSRQC-PV
DR------IA----FT--------------------------------------------
------------------------------------------------------------
---------------------------------------------------EYKRIRLPY
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|6477 @Cyanophora_paradoxa@_ConsensusfromContig37682-snap_masked-ConsensusfromContig37682-abinit-gene-0.0-mRNA-1:cds:7694/5058-6921:0:+
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MQSGWIASEGKLDLAGDDWCGTSERTAW
PSEEIDRAGPANVRVLGLTGNKLTSIPGAELAKLTSLETLVIDFNQLAAIPPEIGRLAAL
QKLLVGANKLTALPEEIGQLAALQYLDVAINQLTTLPAEISQLANLRLLDVSRNMLSALP
PQIGWLVNLPELWLSGNKLTALPSEIGHLANLRLLLLDRNQFTELPPAIGQLANLQVLNV
SSNKLTGLPLEVLQMGRLQELDISGNQLIMLPPEIGQLANLQKLTLCGNGLATLPRELGR
LASLKELEVGDNQLAALPAEIGQLAALQKLDVSGNKPT--ALPPEIGHLANLQKLILGSS
QQNNNQLTVLPSTIGQLTALLYLYVSYNQLTTLPLEIGELVQLRRLDVRFNRLAALPKEI
GQIWGLRLFESSPEFA------------------G-------------------------
-LQLETLEVEGNPLTDLPEHARVSGAAALAHLRSLPAPAAVASASGSAEPGQRRRSKPSA
QPPAPQPVLQQPASAAQQQPLRPATAAAAALQQAPAA-----------------------
------------------VQQQPAARVEQVVAEVAALRDELAALRDRVA-----------
-AEAAERAAHE---GRAVAALEAADAALRSRASGGRWLSRGLAEERTEERARMEAEHAAR
LEAQV-----AALAEE----------------------RAE-ALAEERVKRRRTEGPA--
---------------------------------TYECPICR------------------E
ERDPTERR--LLPHC------------SH-V---FC------------------------
------STCV---------------------------QRL----------KEGTNEC-PK
CRKPLL--PPRRGEVK--------------------------------------------
------------------------------------------------------------
---------------------------------------------------DVLRIFD--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|15179 @Cyanophora_paradoxa@_ConsensusfromContig9059-snap_masked-ConsensusfromContig9059-abinit-gene-0.0-mRNA-1:cds:2341/1581-2253:0:+
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------MDMKS---CCLTE---W
PAAEIASEGQICIRV---------------------------------------------
-------------------------LDLAVNRLSVLPPEIGKLKNLTVLDLSCNWLTSLP
PEIGQLENLKDLNISCNELTALPPEIGQLANLEMLNADRNELTTLPPELGHLENLETLHV
DANRLTA-----------------------LPPEIGQLFN--------------------
---LRELSIRDNQLMEMP-KMCNMFSLRSMLVEGN-PMVDAWPQPARRVVYDNKI----S
RSDNKQEW---KRKGEAQRRAYLYVSH----------------------------LSHVL
GNV-----------NV------------------A-------------------------
-LQAE------------------------ANLEVVRLKQSLQAAVKRAVDAQRQRESARN
RADELQRHLEELNADVQRQ-LEVAQKRATNLQRQLEA-----------------------
------------------SQKQ--------VADATNLQRQLEASQKQVADSFLQLEDMQR
QLEASRKRASD---VQQQSQKRAADAQRQVETSHKRAADLQQQLERSQHRETDLKEQLER
LQAQLQWTSSEARAEDSQR--------------QIDQLRAELAASEQRAADRQLEEHSLD
EGRLRTLSGEELRLLAGRLRAALLLAELEIPRTTFECGICL------------------A
RRPRESRR-----PC------------GH-V---FC------------------------
------ATCA---------------------------PPL----------LAGHGLC-PA
CRCALTGSSP--------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------IFD--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------
